import GroupApproximation.Dynamics.ClopenGroupCrossedProduct
import GroupApproximation.Manuscript.SimpleKazhdanSofic.ElementaryGroupFacts
import GroupApproximation.Meta.AxiomGuard

/-!
# The ring and property (T) for a group action

`simple_kazhdan_sofic_group.tex` at origin/main 37551fd93 (md5 b55c0d23…), "The ring and property
(T)", tex 131–149, the proof of `\label{thm:general}`:

> We write the proof for `n = 3`; for `n ≥ 3` replace `3` by `n` throughout.
> Write `e_U` for the indicator of a clopen set `U ⊆ Z`.  The ring `R = ⊕_{ξ∈Λ} LC(Z,F_2) u_ξ` has
> the multiplication `(f u_ξ)(f' u_η) = f (f' ∘ ξ⁻¹) u_{ξη}`, so `u_ξ e_U u_ξ⁻¹ = e_{ξU}`.  Fix a
> finite symmetric generating set of `Λ`, let `|ξ|` be the word length, and put
> `B_m = {ξ ∈ Λ : |ξ| ≤ m}`.  Let `G = EL_3(R)` be the subgroup of `GL_3(R)` generated by the
> `e_ij(r)` with `i ≠ j` and `r ∈ R`.  With `[g,h] = g h g⁻¹ h⁻¹` and `i, j, l` distinct,
>   `e_ij(r+s) = e_ij(r) e_ij(s)`,  `[e_il(r), e_lj(s)] = e_ij(rs)`.
> So the `e_ij(s)` with `s ∈ S` generate `G`.  By Ershov and Jaikin-Zapirain [Theorem 1.1], `EL_n` of
> every finitely generated associative unital ring has property (T) for `n ≥ 3`.  So `G` has
> property (T), and it is infinite because `e_12(LC(Z,F_2))` is infinite.

`R` is `ClopenGroupCrossedProduct Λ Z (ZMod 2)`, `e_U` is `LocallyConstant.charFn (ZMod 2) hU`,
`EL_n(R)` is `elementaryGroup (Fin n) R` and `e_ij(r)` is `elementaryUnit i j h r`.  Following the
first printed sentence, every statement is made for every `n ≥ 3`.

* `PrintedGroupCrossedProductRing`: the direct sum, the multiplication and covariance on indicators.
* `wordBall T m`: the ball `B_m` of a generating set `T` (products of at most `m` elements of `T`).
* `PrintedGeneralElementaryIdentities`: eq:elementary in every rank.
* `PrintedGeneralElementaryGeneration`: for a ring generating set `S ∋ 1`, the `e_ij(s)`, `s ∈ S`,
  generate `EL_n(R)`, through the coefficient subring as printed.
* `PrintedEJZTheorem`: Ershov--Jaikin-Zapirain, proved in this repository.
* `PrintedGroupCrossedProductPropertyTInfinite`: for a finite ring generating set `S`, `EL_n(R)`
  has property (T), and it is infinite because `e_12(LC(Z,F_2))` is infinite.  The space is any
  infinite totally separated space, so every Cantor set.
-/

namespace GroupApproximation
namespace SimpleKazhdanSofic

open scoped commutatorElement Pointwise

/-! ## The ring -/

/-- **The ring** (tex 134–137): `R = ⊕_{ξ ∈ Λ} LC(Z, F_2) u_ξ` (every element has an expansion, and
expansions over the same finite set agree coefficientwise), `(f u_ξ)(f' u_η) = f (f' ∘ ξ⁻¹) u_{ξη}`,
and `u_ξ e_U u_ξ⁻¹ = e_{ξU}`, for every group acting on a topological space by homeomorphisms. -/
def PrintedGroupCrossedProductRing : Prop :=
  ∀ (Λ : Type) [Group Λ] (Z : Type) [TopologicalSpace Z] [MulAction Λ Z]
    [ContinuousConstSMul Λ Z],
    (∀ r : ClopenGroupCrossedProduct Λ Z (ZMod 2),
      ∃ (S : Finset Λ) (f : Λ → LocallyConstant Z (ZMod 2)),
        r = ∑ ξ ∈ S, ClopenGroupCrossedProduct.coeff Λ Z (ZMod 2) (f ξ) *
          (ClopenGroupCrossedProduct.unit Λ Z (ZMod 2) ξ :
            ClopenGroupCrossedProduct Λ Z (ZMod 2))) ∧
    (∀ (S : Finset Λ) (f g : Λ → LocallyConstant Z (ZMod 2)),
      ∑ ξ ∈ S, ClopenGroupCrossedProduct.coeff Λ Z (ZMod 2) (f ξ) *
          (ClopenGroupCrossedProduct.unit Λ Z (ZMod 2) ξ :
            ClopenGroupCrossedProduct Λ Z (ZMod 2)) =
        ∑ ξ ∈ S, ClopenGroupCrossedProduct.coeff Λ Z (ZMod 2) (g ξ) *
          (ClopenGroupCrossedProduct.unit Λ Z (ZMod 2) ξ :
            ClopenGroupCrossedProduct Λ Z (ZMod 2)) →
      ∀ ξ ∈ S, f ξ = g ξ) ∧
    (∀ (ξ η : Λ) (f f' : LocallyConstant Z (ZMod 2)),
      (ClopenGroupCrossedProduct.coeff Λ Z (ZMod 2) f *
          (ClopenGroupCrossedProduct.unit Λ Z (ZMod 2) ξ :
            ClopenGroupCrossedProduct Λ Z (ZMod 2))) *
        (ClopenGroupCrossedProduct.coeff Λ Z (ZMod 2) f' *
          (ClopenGroupCrossedProduct.unit Λ Z (ZMod 2) η :
            ClopenGroupCrossedProduct Λ Z (ZMod 2))) =
      ClopenGroupCrossedProduct.coeff Λ Z (ZMod 2)
          (f * LocallyConstant.comap (ClopenGroupCoeff.smulMap Λ Z ξ⁻¹) f') *
        (ClopenGroupCrossedProduct.unit Λ Z (ZMod 2) (ξ * η) :
          ClopenGroupCrossedProduct Λ Z (ZMod 2))) ∧
    (∀ (ξ : Λ) (U : Set Z) (hU : IsClopen U),
      (ClopenGroupCrossedProduct.unit Λ Z (ZMod 2) ξ : ClopenGroupCrossedProduct Λ Z (ZMod 2)) *
          ClopenGroupCrossedProduct.coeff Λ Z (ZMod 2) (LocallyConstant.charFn (ZMod 2) hU) *
          ((ClopenGroupCrossedProduct.unit Λ Z (ZMod 2) ξ)⁻¹ :
            (ClopenGroupCrossedProduct Λ Z (ZMod 2))ˣ) =
        ClopenGroupCrossedProduct.coeff Λ Z (ZMod 2)
          (LocallyConstant.charFn (ZMod 2)
            (ClopenGroupCrossedProduct.isClopen_smul_set Λ Z ξ hU)))

theorem printedGroupCrossedProductRing : PrintedGroupCrossedProductRing := by
  intro Λ _ Z _ _ _
  exact ⟨ClopenGroupCrossedProduct.exists_sum_coeff_mul_unit Λ Z (ZMod 2),
    ClopenGroupCrossedProduct.eq_of_sum_coeff_mul_unit_eq Λ Z (ZMod 2),
    ClopenGroupCrossedProduct.coeff_mul_unit_mul_coeff_mul_unit Λ Z (ZMod 2),
    fun ξ _ hU => ClopenGroupCrossedProduct.unit_mul_charFn_mul_inv Λ Z (ZMod 2) ξ hU⟩

#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedGroupCrossedProductRing

/-! ## Balls -/

/-- **The ball** `B_m` (tex 137–139): the elements of word length at most `m` for a generating set
`T`, that is, the products of at most `m` elements of `T`. -/
def wordBall {Λ : Type*} [Group Λ] (T : Set Λ) (m : ℕ) : Set Λ :=
  {ξ | ∃ l : List Λ, l.length ≤ m ∧ (∀ x ∈ l, x ∈ T) ∧ l.prod = ξ}

theorem one_mem_wordBall {Λ : Type*} [Group Λ] (T : Set Λ) (m : ℕ) : (1 : Λ) ∈ wordBall T m :=
  ⟨[], Nat.zero_le m, fun _ hx => absurd hx List.not_mem_nil, List.prod_nil⟩

theorem mul_mem_wordBall {Λ : Type*} [Group Λ] {T : Set Λ} {m m' : ℕ} {ξ η : Λ}
    (hξ : ξ ∈ wordBall T m) (hη : η ∈ wordBall T m') : ξ * η ∈ wordBall T (m + m') := by
  obtain ⟨l, hl, hlT, rfl⟩ := hξ
  obtain ⟨l', hl', hlT', rfl⟩ := hη
  refine ⟨l ++ l', ?_, fun x hx => ?_, List.prod_append⟩
  · rw [List.length_append]
    omega
  · rcases List.mem_append.1 hx with hx | hx
    · exact hlT x hx
    · exact hlT' x hx

/-! ## eq:elementary and generation in every rank -/

/-- **eq:elementary** (tex 140–144), in every rank: `e_ij(r+s) = e_ij(r) e_ij(s)` for `i ≠ j`, and
`[e_il(r), e_lj(s)] = e_ij(rs)` for distinct `i, j, l`, with `[g,h] = g h g⁻¹ h⁻¹`. -/
def PrintedGeneralElementaryIdentities : Prop :=
  ∀ (R : Type) [Ring R] (n : ℕ) (i j l : Fin n) (hij : i ≠ j) (hil : i ≠ l) (hlj : l ≠ j)
    (r s : R),
    elementaryUnit i j hij (r + s) = elementaryUnit i j hij r * elementaryUnit i j hij s ∧
      ⁅elementaryUnit i l hil r, elementaryUnit l j hlj s⁆ = elementaryUnit i j hij (r * s)

theorem printedGeneralElementaryIdentities : PrintedGeneralElementaryIdentities := by
  intro R _ n i j l hij hil hlj r s
  exact ⟨(elementaryUnit_mul i j hij r s).symm, elementaryUnit_commutator i l j hil hlj hij r s⟩

#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedGeneralElementaryIdentities

/-- In rank `n ≥ 3`, two indices leave a third. -/
theorem exists_third_index {n : ℕ} (hn : 3 ≤ n) (i j : Fin n) : ∃ l : Fin n, l ≠ i ∧ l ≠ j := by
  by_contra h
  push Not at h
  have hsub : (Finset.univ : Finset (Fin n)) ⊆ {i, j} := by
    intro l _
    by_cases hli : l = i
    · rw [hli]
      exact Finset.mem_insert_self i {j}
    · rw [h l hli]
      exact Finset.mem_insert_of_mem (Finset.mem_singleton_self j)
  have hcard := Finset.card_le_card hsub
  rw [Finset.card_univ, Fintype.card_fin] at hcard
  have h2 := Finset.card_insert_le i ({j} : Finset (Fin n))
  rw [Finset.card_singleton] at h2
  omega

/-- **The coefficient subring** in rank `n ≥ 3`: if a subgroup `H` contains every `e_ij(1)`, the
coefficients `a` with `e_ij(a) ∈ H` for all `i ≠ j` form a subring, by eq:elementary. -/
def coefficientSubringFin {R : Type*} [Ring R] {n : ℕ} (hn : 3 ≤ n)
    (H : Subgroup (Matrix (Fin n) (Fin n) R)ˣ)
    (hone : ∀ (i j : Fin n) (h : i ≠ j), elementaryUnit i j h (1 : R) ∈ H) : Subring R where
  carrier := {a | ∀ (i j : Fin n) (h : i ≠ j), elementaryUnit i j h a ∈ H}
  mul_mem' := by
    intro a b ha hb
    show ∀ (i j : Fin n) (h : i ≠ j), elementaryUnit i j h (a * b) ∈ H
    intro i j h
    obtain ⟨l, hli, hlj⟩ := exists_third_index hn i j
    rw [← elementaryUnit_commutator i l j (Ne.symm hli) hlj h a b, commutatorElement_def]
    exact H.mul_mem (H.mul_mem (H.mul_mem (ha i l (Ne.symm hli)) (hb l j hlj))
      (H.inv_mem (ha i l (Ne.symm hli)))) (H.inv_mem (hb l j hlj))
  one_mem' := hone
  add_mem' := by
    intro a b ha hb
    show ∀ (i j : Fin n) (h : i ≠ j), elementaryUnit i j h (a + b) ∈ H
    intro i j h
    rw [← elementaryUnit_mul]
    exact H.mul_mem (ha i j h) (hb i j h)
  zero_mem' := by
    show ∀ (i j : Fin n) (h : i ≠ j), elementaryUnit i j h (0 : R) ∈ H
    intro i j h
    rw [elementaryUnit_zero]
    exact H.one_mem
  neg_mem' := by
    intro a ha
    show ∀ (i j : Fin n) (h : i ≠ j), elementaryUnit i j h (-a) ∈ H
    intro i j h
    have hinv : elementaryUnit i j h (-a) = (elementaryUnit i j h a)⁻¹ := by
      rw [eq_inv_iff_mul_eq_one, elementaryUnit_mul, neg_add_cancel, elementaryUnit_zero]
    rw [hinv]
    exact H.inv_mem (ha i j h)

/-- **Generation** (tex 145), in every rank `n ≥ 3`: if `S ∋ 1` generates `R` as a ring, the
`e_ij(s)` with `s ∈ S` generate `EL_n(R)`.  The route is eq:elementary: the coefficients whose
elementary matrices lie in the generated subgroup form a subring containing `S`. -/
def PrintedGeneralElementaryGeneration : Prop :=
  ∀ (R : Type) [Ring R] (S : Set R), (1 : R) ∈ S → Subring.closure S = ⊤ →
    ∀ n : ℕ, 3 ≤ n →
      elementaryGroup (Fin n) R =
        Subgroup.closure {z | ∃ (i j : Fin n) (h : i ≠ j) (s : R), s ∈ S ∧
          elementaryUnit i j h s = z}

theorem printedGeneralElementaryGeneration : PrintedGeneralElementaryGeneration := by
  intro R _ S hS1 hS n hn
  set H : Subgroup (Matrix (Fin n) (Fin n) R)ˣ :=
    Subgroup.closure {z | ∃ (i j : Fin n) (h : i ≠ j) (s : R), s ∈ S ∧
      elementaryUnit i j h s = z} with hH
  have hgen : ∀ (i j : Fin n) (h : i ≠ j) (s : R), s ∈ S → elementaryUnit i j h s ∈ H :=
    fun i j h s hs => Subgroup.subset_closure ⟨i, j, h, s, hs, rfl⟩
  have hC : Subring.closure S ≤ coefficientSubringFin hn H fun i j h => hgen i j h 1 hS1 :=
    Subring.closure_le.mpr fun s hs i j h => hgen i j h s hs
  refine le_antisymm ?_ ?_
  · show Subgroup.closure {z | ∃ (i j : Fin n) (h : i ≠ j) (a : R), elementaryUnit i j h a = z} ≤ H
    refine (Subgroup.closure_le H).mpr ?_
    rintro _ ⟨i, j, h, a, rfl⟩
    have ha : a ∈ Subring.closure S := by
      rw [hS]
      exact Subring.mem_top a
    exact hC ha i j h
  · refine (Subgroup.closure_le _).mpr ?_
    rintro _ ⟨i, j, h, s, -, rfl⟩
    exact elementaryUnit_mem i j h s

#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedGeneralElementaryGeneration

/-! ## Property (T) and infiniteness -/

/-- **Ershov--Jaikin-Zapirain** (tex 145–147): `EL_n` of every finitely generated associative unital
ring has property (T) for `n ≥ 3`.  Proved in this repository. -/
def PrintedEJZTheorem : Prop :=
  FinitelyGeneratedRingGeneralRankElementaryPropertyT

theorem printedEJZTheorem : PrintedEJZTheorem :=
  IntegralColumnPlaneClosure.finitelyGeneratedRingGeneralRankElementaryPropertyT

#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedEJZTheorem

/-- `EL_n(R)` is infinite when an injective ring map sends an infinite ring into `R`: `a ↦ e_12(φ a)`
is injective. -/
theorem infinite_elementaryGroup_of_injective {K R : Type*} [Ring K] [Infinite K] [Ring R]
    (φ : K →+* R) (hφ : Function.Injective φ) {n : ℕ} (hn : 2 ≤ n) :
    Infinite ↥(elementaryGroup (Fin n) R) := by
  have h01 : (⟨0, by omega⟩ : Fin n) ≠ ⟨1, by omega⟩ := fun h => by
    simpa using congrArg Fin.val h
  refine Infinite.of_injective
    (fun a : K => (⟨elementaryUnit _ _ h01 (φ a), elementaryUnit_mem _ _ h01 (φ a)⟩ :
      ↥(elementaryGroup (Fin n) R))) ?_
  intro a b hab
  exact hφ (elementaryUnit_injective _ _ h01 (congrArg Subtype.val hab))

/-- **Property (T) and infiniteness** (tex 148–149): for a group acting by homeomorphisms on an
infinite totally separated space `Z` (for instance a Cantor set), and a finite set `S` generating
`R = LC(Z, F_2) ⋊ Λ` as a ring, `EL_n(R)` has property (T) for every `n ≥ 3`, and it is infinite
because `e_12(LC(Z, F_2))` is infinite. -/
def PrintedGroupCrossedProductPropertyTInfinite : Prop :=
  ∀ (Λ : Type) [Group Λ] (Z : Type) [TopologicalSpace Z] [MulAction Λ Z]
    [ContinuousConstSMul Λ Z] [TotallySeparatedSpace Z] [Infinite Z]
    (S : Finset (ClopenGroupCrossedProduct Λ Z (ZMod 2))),
    Subring.closure (S : Set (ClopenGroupCrossedProduct Λ Z (ZMod 2))) = ⊤ →
      ∀ n : ℕ, 3 ≤ n →
        HasKazhdanPropertyT.{0, 0}
            ↥(elementaryGroup (Fin n) (ClopenGroupCrossedProduct Λ Z (ZMod 2))) ∧
          Infinite ↥(elementaryGroup (Fin n) (ClopenGroupCrossedProduct Λ Z (ZMod 2)))

theorem printedGroupCrossedProductPropertyTInfinite :
    PrintedGroupCrossedProductPropertyTInfinite := by
  intro Λ _ Z _ _ _ _ _ S hS n hn
  haveI := infinite_locallyConstant_zmodTwo Z
  exact ⟨Pestov91.elementary_hasKazhdanPropertyT ⟨S, hS⟩ hn,
    infinite_elementaryGroup_of_injective (ClopenGroupCrossedProduct.coeff Λ Z (ZMod 2))
      (ClopenGroupCrossedProduct.coeff_injective Λ Z (ZMod 2)) (by omega)⟩

#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedGroupCrossedProductPropertyTInfinite

end SimpleKazhdanSofic
end GroupApproximation

#audit_axioms GroupApproximation.SimpleKazhdanSofic.exists_third_index
#audit_axioms GroupApproximation.SimpleKazhdanSofic.infinite_elementaryGroup_of_injective
#audit_axioms GroupApproximation.SimpleKazhdanSofic.mul_mem_wordBall
