import GroupApproximation.Manuscript.SimpleKazhdanSofic.MatricialMarkedLimitWords
import GroupApproximation.Meta.AxiomGuard
import Mathlib.Algebra.Algebra.Operations
import Mathlib.GroupTheory.FreeGroup.Reduce
import Mathlib.RingTheory.Finiteness.Cardinality

/-!
# `simple_kazhdan_sofic_group.tex`, "Finite simple models": surjectivity, generation, degrees

`simple_kazhdan_sofic_group.tex` at f34e9c0b1, "Finite simple models":

> Both are onto, so $G$ and $\EL_3(M_{N_k}(\F_2))$ are quotients of $\EL_3(F)$. [...] The group
> $\EL_3(F)$ is generated by the $e_{ij}(1)$ and $e_{ij}(\tau_s)$, and in both quotients $e_{ij}(1)$
> and $e_{ij}(\tau_1)$ have the same image. A word of length $\lambda$ or less in the
> $e_{ij}(\tau_s)$ has entries of degree at most $\lambda$ in $F$, and $\varphi_k\circ\pi=\rho_k$ on
> the finitely many such entries for large $k$.

This module proves the printed steps for `F = F₂⟨τ_s : s ∈ S⟩`, `π = piLetters S` and
`ρ_k = rhoLetters S N φ k`:

* `subring_closure_range_ι_eq_top`: `F` is generated by its letters;
* `piLetters_surjective`, `rhoLetters_surjective`, and the surjections of elementary groups;
* `freeMarking`, `closure_range_freeMarking_eq_top`: `EL_n(F)` is generated by `e_ij(1)` and
  `e_ij(τ_s)`; `piLetters_freeMarking_one`, `rhoLetters_freeMarking_one`: `e_ij(τ_1)` and `e_ij(1)`
  have the same image in both quotients;
* `degLE`: the span of the monomials of length at most `λ`; `mul_mem_degLE`, `finite_degLE`;
* `entries_lift_mem_degLE`: the entries of a word of length at most `λ` lie in `degLE λ`;
* `eventually_forall_degLE_map_comp_eq`: `φ_k ∘ π = ρ_k` on all of `degLE λ` for large `k`;
* closed endpoints `printedLettersOntoQuotients`, `printedFreeMarkingGeneration`,
  `printedWordEntriesDegreeAgreement`.
-/

namespace GroupApproximation

namespace SimpleKazhdanSofic

open Filter

section Letters

variable {β : Type*}

/-- The free algebra is generated as a ring by its letters. -/
theorem subring_closure_range_ι_eq_top :
    Subring.closure (Set.range (FreeAlgebra.ι (ZMod 2) : β → FreeAlgebra (ZMod 2) β)) = ⊤ := by
  rw [eq_top_iff]
  rintro x -
  induction x using FreeAlgebra.induction with
  | grade0 r =>
      rw [← ZMod.natCast_zmod_val r, map_natCast]
      exact natCast_mem _ _
  | grade1 g => exact Subring.subset_closure ⟨g, rfl⟩
  | mul a b ha hb => exact Subring.mul_mem _ ha hb
  | add a b ha hb => exact Subring.add_mem _ ha hb

/-- `EL_n(F)` marked by `e_ij(1)` (index `none`) and `e_ij(τ_b)` (index `some b`). -/
noncomputable def freeMarking (n : ℕ) (β : Type*) :
    {p : Fin n × Fin n // p.1 ≠ p.2} × Option β → ↥(elementaryGroup (Fin n) (FreeAlgebra (ZMod 2) β)) :=
  rootMarking n fun o : Option β => o.elim 1 (FreeAlgebra.ι (ZMod 2))

/-- tex 215–216: "The group $\EL_3(F)$ is generated by the $e_{ij}(1)$ and $e_{ij}(\tau_s)$". -/
theorem closure_range_freeMarking_eq_top {n : ℕ} (hn : 3 ≤ n) :
    Subgroup.closure (Set.range (freeMarking n β)) = ⊤ := by
  refine closure_range_rootMarking_eq_top hn _ ⟨none, rfl⟩ (eq_top_iff.2 ?_)
  refine (subring_closure_range_ι_eq_top (β := β)).ge.trans (Subring.closure_mono ?_)
  rintro _ ⟨b, rfl⟩
  exact ⟨some b, rfl⟩

end Letters

section Onto

variable {R : Type*} [Ring R] [Algebra (ZMod 2) R] (S : Finset R) (N : ℕ → ℕ)
  (φ : ∀ k, R → Matrix (Fin (N k)) (Fin (N k)) (ZMod 2))

/-- tex 211: "Both are onto": `π` is onto. -/
theorem piLetters_surjective (hS : Subring.closure (S : Set R) = ⊤) :
    Function.Surjective (piLetters S) := by
  intro r
  have hle : Subring.closure (S : Set R) ≤ (piLetters S).range := by
    rw [Subring.closure_le]
    intro s hs
    exact ⟨FreeAlgebra.ι (ZMod 2) ⟨s, hs⟩, piLetters_ι S ⟨s, hs⟩⟩
  obtain ⟨m, hm⟩ := hle (show r ∈ Subring.closure (S : Set R) by rw [hS]; exact Subring.mem_top r)
  exact ⟨m, hm⟩

omit [Ring R] [Algebra (ZMod 2) R] in
/-- tex 211: "Both are onto": `ρ_k` is onto. -/
theorem rhoLetters_surjective (hgen : ∀ k, Subring.closure (φ k '' (S : Set R)) = ⊤) (k : ℕ) :
    Function.Surjective (rhoLetters S N φ k) := by
  intro r
  have hle : Subring.closure (φ k '' (S : Set R)) ≤ (rhoLetters S N φ k).range := by
    rw [Subring.closure_le]
    rintro _ ⟨s, hs, rfl⟩
    exact ⟨FreeAlgebra.ι (ZMod 2) ⟨s, hs⟩, rhoLetters_ι S N φ k ⟨s, hs⟩⟩
  obtain ⟨m, hm⟩ := hle (show r ∈ Subring.closure (φ k '' (S : Set R)) by rw [hgen k]; exact Subring.mem_top r)
  exact ⟨m, hm⟩

/-- tex 211–212: "so $G$ and $\EL_3(M_{N_k}(\F_2))$ are quotients of $\EL_3(F)$". -/
theorem elementaryGroupMap_letters_surjective (hS : Subring.closure (S : Set R) = ⊤)
    (hgen : ∀ k, Subring.closure (φ k '' (S : Set R)) = ⊤) (n : ℕ) :
    Function.Surjective (elementaryGroupMap (ι := Fin n) (piLetters S)) ∧
      ∀ k, Function.Surjective (elementaryGroupMap (ι := Fin n) (rhoLetters S N φ k)) :=
  ⟨elementaryGroupMap_surjective_of_surjective _ (piLetters_surjective S hS),
    fun k => elementaryGroupMap_surjective_of_surjective _ (rhoLetters_surjective S N φ hgen k)⟩

/-- tex 216–217: "in both quotients $e_{ij}(1)$ and $e_{ij}(\tau_1)$ have the same image" (`π`). -/
theorem piLetters_freeMarking_one (hS1 : (1 : R) ∈ S) {n : ℕ} (p : {p : Fin n × Fin n // p.1 ≠ p.2}) :
    elementaryGroupMap (piLetters S) (freeMarking n ↥S (p, some ⟨1, hS1⟩)) =
      elementaryGroupMap (piLetters S) (freeMarking n ↥S (p, none)) := by
  apply Subtype.ext
  show elementaryMatrixUnitMap (piLetters S) (elementaryUnit p.1.1 p.1.2 p.2 (FreeAlgebra.ι (ZMod 2) ⟨1, hS1⟩)) =
    elementaryMatrixUnitMap (piLetters S) (elementaryUnit p.1.1 p.1.2 p.2 1)
  rw [elementaryMatrixUnitMap_elementaryUnit, elementaryMatrixUnitMap_elementaryUnit, piLetters_ι, map_one]

omit [Algebra (ZMod 2) R] in
/-- tex 216–217: "in both quotients $e_{ij}(1)$ and $e_{ij}(\tau_1)$ have the same image" (`ρ_k`). -/
theorem rhoLetters_freeMarking_one (hS1 : (1 : R) ∈ S) (h1 : ∀ k, φ k 1 = 1) (k : ℕ) {n : ℕ}
    (p : {p : Fin n × Fin n // p.1 ≠ p.2}) :
    elementaryGroupMap (rhoLetters S N φ k) (freeMarking n ↥S (p, some ⟨1, hS1⟩)) =
      elementaryGroupMap (rhoLetters S N φ k) (freeMarking n ↥S (p, none)) := by
  apply Subtype.ext
  show elementaryMatrixUnitMap (rhoLetters S N φ k)
      (elementaryUnit p.1.1 p.1.2 p.2 (FreeAlgebra.ι (ZMod 2) ⟨1, hS1⟩)) =
    elementaryMatrixUnitMap (rhoLetters S N φ k) (elementaryUnit p.1.1 p.1.2 p.2 1)
  rw [elementaryMatrixUnitMap_elementaryUnit, elementaryMatrixUnitMap_elementaryUnit, rhoLetters_ι,
    map_one]
  exact congrArg _ (h1 k)

end Onto

section Degree

variable (β : Type*)

/-- The monomials of length at most `d` in the letters. -/
def monomialsLE (d : ℕ) : Set (FreeAlgebra (ZMod 2) β) :=
  {x | ∃ l : List β, l.length ≤ d ∧ x = (l.map (FreeAlgebra.ι (ZMod 2))).prod}

/-- **Degree at most `d`** (tex 218): the span of the monomials of length at most `d`. -/
def degLE (d : ℕ) : Submodule (ZMod 2) (FreeAlgebra (ZMod 2) β) :=
  Submodule.span (ZMod 2) (monomialsLE β d)

variable {β}

theorem one_mem_degLE (d : ℕ) : (1 : FreeAlgebra (ZMod 2) β) ∈ degLE β d :=
  Submodule.subset_span ⟨[], by simp, by simp⟩

theorem ι_mem_degLE (b : β) {d : ℕ} (hd : 1 ≤ d) : FreeAlgebra.ι (ZMod 2) b ∈ degLE β d :=
  Submodule.subset_span ⟨[b], by simpa using hd, by simp⟩

theorem degLE_mono {d d' : ℕ} (h : d ≤ d') : degLE β d ≤ degLE β d' :=
  Submodule.span_mono fun _ ⟨l, hl, hx⟩ => ⟨l, hl.trans h, hx⟩

theorem mul_mem_degLE {a b : FreeAlgebra (ZMod 2) β} {d e : ℕ} (ha : a ∈ degLE β d)
    (hb : b ∈ degLE β e) : a * b ∈ degLE β (d + e) := by
  have h : degLE β d * degLE β e ≤ degLE β (d + e) := by
    rw [degLE, degLE, Submodule.span_mul_span]
    apply Submodule.span_mono
    rintro _ ⟨x, ⟨l, hl, rfl⟩, y, ⟨l', hl', rfl⟩, rfl⟩
    exact ⟨l ++ l', by simp only [List.length_append]; omega, by simp only [List.map_append, List.prod_append]⟩
  exact h (Submodule.mul_mem_mul ha hb)

/-- "the finitely many such entries" (tex 219): for finitely many letters, `degLE d` is finite. -/
theorem finite_degLE [Finite β] (d : ℕ) : (degLE β d : Set (FreeAlgebra (ZMod 2) β)).Finite := by
  have hmon : (monomialsLE β d).Finite := by
    refine ((Finset.range (d + 1)).finite_toSet.biUnion fun k _ =>
      Set.finite_range fun f : Fin k → β => (List.ofFn fun j => FreeAlgebra.ι (ZMod 2) (f j)).prod).subset ?_
    rintro _ ⟨l, hl, rfl⟩
    refine Set.mem_iUnion₂.2 ⟨l.length, by simp only [Finset.coe_range, Set.mem_Iio]; omega, ?_⟩
    refine ⟨fun j => l.get j, ?_⟩
    show (List.ofFn fun j => FreeAlgebra.ι (ZMod 2) (l.get j)).prod = (l.map (FreeAlgebra.ι (ZMod 2))).prod
    congr 1
    change List.ofFn (FreeAlgebra.ι (ZMod 2) ∘ l.get) = _
    rw [← List.map_ofFn, List.ofFn_get]
  haveI : Module.Finite (ZMod 2) ↥(degLE β d) := Module.Finite.span_of_finite (ZMod 2) hmon
  haveI : Finite ↥(degLE β d) := Module.finite_of_finite (ZMod 2)
  exact Set.toFinite _

theorem entries_elementaryUnit_mem_degLE {n : ℕ} (p : {p : Fin n × Fin n // p.1 ≠ p.2}) (o : Option β)
    (i j : Fin n) :
    ((freeMarking n β (p, o) : (Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β))ˣ) :
        Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β)) i j ∈ degLE β 1 ∧
      ((((freeMarking n β (p, o))⁻¹ : ↥(elementaryGroup (Fin n) (FreeAlgebra (ZMod 2) β))) :
          (Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β))ˣ) :
        Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β)) i j ∈ degLE β 1 := by
  have ha : o.elim (1 : FreeAlgebra (ZMod 2) β) (FreeAlgebra.ι (ZMod 2)) ∈ degLE β 1 := by
    cases o with
    | none => exact one_mem_degLE 1
    | some b => exact ι_mem_degLE b le_rfl
  have h1 : ((1 : Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β)) i j) ∈ degLE β 1 := by
    rw [Matrix.one_apply]
    split_ifs
    · exact one_mem_degLE 1
    · exact Submodule.zero_mem _
  have hs : (Matrix.single p.1.1 p.1.2 (o.elim (1 : FreeAlgebra (ZMod 2) β) (FreeAlgebra.ι (ZMod 2)))) i j ∈
      degLE β 1 := by
    simp only [Matrix.single, Matrix.of_apply]
    split_ifs
    · exact ha
    · exact Submodule.zero_mem _
  refine ⟨?_, ?_⟩
  · show (1 + Matrix.single p.1.1 p.1.2 (o.elim (1 : FreeAlgebra (ZMod 2) β) (FreeAlgebra.ι (ZMod 2)))) i j ∈
      degLE β 1
    rw [Matrix.add_apply]
    exact Submodule.add_mem _ h1 hs
  · show (1 - Matrix.single p.1.1 p.1.2 (o.elim (1 : FreeAlgebra (ZMod 2) β) (FreeAlgebra.ι (ZMod 2)))) i j ∈
      degLE β 1
    rw [Matrix.sub_apply]
    exact Submodule.sub_mem _ h1 hs

/-- The entries of a product of root matrices `e_ij(1)`, `e_ij(τ_b)` and their inverses over a list `L`
lie in `degLE L.length`. -/
theorem entries_list_prod_mem_degLE {n : ℕ}
    (L : List (({p : Fin n × Fin n // p.1 ≠ p.2} × Option β) × Bool)) (i j : Fin n) :
    ((((L.map fun x => cond x.2 (freeMarking n β x.1) (freeMarking n β x.1)⁻¹).prod :
        ↥(elementaryGroup (Fin n) (FreeAlgebra (ZMod 2) β))) :
          (Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β))ˣ) :
        Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β)) i j ∈ degLE β L.length := by
  induction L generalizing i j with
  | nil =>
      show ((1 : Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β)) i j) ∈ degLE β 0
      rw [Matrix.one_apply]
      split_ifs
      · exact one_mem_degLE 0
      · exact Submodule.zero_mem _
  | cons x L ih =>
      rw [List.map_cons, List.prod_cons, List.length_cons]
      show ((((cond x.2 (freeMarking n β x.1) (freeMarking n β x.1)⁻¹ :
          ↥(elementaryGroup (Fin n) (FreeAlgebra (ZMod 2) β))) :
            (Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β))ˣ) :
              Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β)) *
          (((L.map fun x => cond x.2 (freeMarking n β x.1) (freeMarking n β x.1)⁻¹).prod :
            ↥(elementaryGroup (Fin n) (FreeAlgebra (ZMod 2) β))) :
              (Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β))ˣ)) i j ∈ degLE β (L.length + 1)
      rw [Matrix.mul_apply]
      refine Submodule.sum_mem _ fun k _ => ?_
      refine degLE_mono (by omega) (mul_mem_degLE (d := 1) ?_ (ih k j))
      rcases x with ⟨q, b⟩
      cases b with
      | false => exact (entries_elementaryUnit_mem_degLE q.1 q.2 i k).2
      | true => exact (entries_elementaryUnit_mem_degLE q.1 q.2 i k).1

/-- tex 217–218: "A word of length $\lambda$ or less in the $e_{ij}(\tau_s)$ has entries of degree at
most $\lambda$ in $F$". -/
theorem entries_lift_mem_degLE [DecidableEq β] {n : ℕ}
    (w : FreeGroup ({p : Fin n × Fin n // p.1 ≠ p.2} × Option β)) (i j : Fin n) :
    ((FreeGroup.lift (freeMarking n β) w : (Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β))ˣ) :
        Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) β)) i j ∈ degLE β (FreeGroup.toWord w).length := by
  have h2 := FreeGroup.lift_mk (f := freeMarking n β) (L := FreeGroup.toWord w)
  rw [FreeGroup.mk_toWord] at h2
  rw [h2]
  exact entries_list_prod_mem_degLE (FreeGroup.toWord w) i j

end Degree

section Agreement

variable {R : Type*} [Ring R] [Algebra (ZMod 2) R] (S : Finset R) (N : ℕ → ℕ)
  (φ : ∀ k, R → Matrix (Fin (N k)) (Fin (N k)) (ZMod 2))

/-- tex 218–219: "and $\varphi_k\circ\pi=\rho_k$ on the finitely many such entries for large $k$": for
large `k`, `φ_k ∘ π = ρ_k` on all of `degLE λ`. -/
theorem eventually_forall_degLE_map_comp_eq (h1 : ∀ k, φ k 1 = 1)
    (hev : ∀ r s : R, ∀ᶠ k in atTop, φ k (r + s) = φ k r + φ k s ∧ φ k (r * s) = φ k r * φ k s)
    (d : ℕ) :
    ∀ᶠ k in atTop, ∀ m ∈ (degLE (↥S) d : Set (FreeAlgebra (ZMod 2) ↥S)),
      φ k (piLetters S m) = rhoLetters S N φ k m := by
  have hadd : ∀ r s : R, ∀ᶠ k in atTop, φ k (r + s) = φ k r + φ k s :=
    fun r s => (hev r s).mono fun _ h => h.1
  have hmul : ∀ r s : R, ∀ᶠ k in atTop, φ k (r * s) = φ k r * φ k s :=
    fun r s => (hev r s).mono fun _ h => h.2
  have hletter : ∀ b : ↥S, ∀ᶠ k in atTop,
      φ k (piLetters S (FreeAlgebra.ι (ZMod 2) b)) = rhoLetters S N φ k (FreeAlgebra.ι (ZMod 2) b) :=
    fun b => Eventually.of_forall fun k => by rw [piLetters_ι, rhoLetters_ι]
  exact (eventually_all_finite (finite_degLE d)).2 fun m _ =>
    eventually_map_comp_eq φ (piLetters S) (rhoLetters S N φ) h1 hadd hmul hletter m

end Agreement

/-- **tex 211–212**, closed: `π` and `ρ_k` are onto, so `EL_n(R)` and `EL_n(M_{N_k}(F₂))` are quotients of
`EL_n(F)`. -/
def PrintedLettersOntoQuotients : Prop :=
  ∀ (R : Type) [Ring R] [Algebra (ZMod 2) R] (S : Finset R), Subring.closure (S : Set R) = ⊤ →
    ∀ (N : ℕ → ℕ) (φ : ∀ k, R → Matrix (Fin (N k)) (Fin (N k)) (ZMod 2)),
      (∀ k, Subring.closure (φ k '' (S : Set R)) = ⊤) → ∀ n : ℕ,
      Function.Surjective (piLetters S) ∧ (∀ k, Function.Surjective (rhoLetters S N φ k)) ∧
        Function.Surjective (elementaryGroupMap (ι := Fin n) (piLetters S)) ∧
        ∀ k, Function.Surjective (elementaryGroupMap (ι := Fin n) (rhoLetters S N φ k))

theorem printedLettersOntoQuotients : PrintedLettersOntoQuotients := by
  intro R _ _ S hS N φ hgen n
  obtain ⟨h3, h4⟩ := elementaryGroupMap_letters_surjective S N φ hS hgen n
  exact ⟨piLetters_surjective S hS, rhoLetters_surjective S N φ hgen, h3, h4⟩

/-- **tex 215–217**, closed. -/
def PrintedFreeMarkingGeneration : Prop :=
  ∀ (R : Type) [Ring R] [Algebra (ZMod 2) R] (S : Finset R) (hS1 : (1 : R) ∈ S)
    (N : ℕ → ℕ) (φ : ∀ k, R → Matrix (Fin (N k)) (Fin (N k)) (ZMod 2)), (∀ k, φ k 1 = 1) →
    ∀ n : ℕ, 3 ≤ n →
      Subgroup.closure (Set.range (freeMarking n ↥S)) = ⊤ ∧
      ∀ p : {p : Fin n × Fin n // p.1 ≠ p.2},
        elementaryGroupMap (piLetters S) (freeMarking n ↥S (p, some ⟨1, hS1⟩)) =
          elementaryGroupMap (piLetters S) (freeMarking n ↥S (p, none)) ∧
        ∀ k, elementaryGroupMap (rhoLetters S N φ k) (freeMarking n ↥S (p, some ⟨1, hS1⟩)) =
          elementaryGroupMap (rhoLetters S N φ k) (freeMarking n ↥S (p, none))

theorem printedFreeMarkingGeneration : PrintedFreeMarkingGeneration := by
  intro R _ _ S hS1 N φ h1 n hn
  exact ⟨closure_range_freeMarking_eq_top hn, fun p =>
    ⟨piLetters_freeMarking_one S hS1 p, fun k => rhoLetters_freeMarking_one S N φ hS1 h1 k p⟩⟩

/-- **tex 217–219**, closed. -/
def PrintedWordEntriesDegreeAgreement : Prop :=
  ∀ (R : Type) [Ring R] [Algebra (ZMod 2) R] [DecidableEq R] (S : Finset R) (N : ℕ → ℕ)
    (φ : ∀ k, R → Matrix (Fin (N k)) (Fin (N k)) (ZMod 2)), (∀ k, φ k 1 = 1) →
    (∀ r s : R, ∀ᶠ k in atTop, φ k (r + s) = φ k r + φ k s ∧ φ k (r * s) = φ k r * φ k s) →
    ∀ (n d : ℕ) (w : FreeGroup ({p : Fin n × Fin n // p.1 ≠ p.2} × Option ↥S)),
      (FreeGroup.toWord w).length ≤ d →
      (∀ i j, ((FreeGroup.lift (freeMarking n ↥S) w : (Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) ↥S))ˣ) :
        Matrix (Fin n) (Fin n) (FreeAlgebra (ZMod 2) ↥S)) i j ∈ degLE (↥S) d) ∧
      (degLE (↥S) d : Set (FreeAlgebra (ZMod 2) ↥S)).Finite ∧
      ∀ᶠ k in atTop, ∀ m ∈ (degLE (↥S) d : Set (FreeAlgebra (ZMod 2) ↥S)),
        φ k (piLetters S m) = rhoLetters S N φ k m

theorem printedWordEntriesDegreeAgreement : PrintedWordEntriesDegreeAgreement := by
  intro R _ _ _ S N φ h1 hev n d w hw
  exact ⟨fun i j => degLE_mono hw (entries_lift_mem_degLE w i j), finite_degLE d,
    eventually_forall_degLE_map_comp_eq S N φ h1 hev d⟩

end SimpleKazhdanSofic

end GroupApproximation

#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedLettersOntoQuotients
#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedFreeMarkingGeneration
#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedWordEntriesDegreeAgreement
