import GroupApproximation.Leavitt.ElementaryGroup
import GroupApproximation.Kazhdan.KazhdanFiniteGeneration
import Mathlib.Data.Set.Finite.Lattice
import Mathlib.GroupTheory.Finiteness
import GroupApproximation.Meta.AxiomGuard

/-!
# Sharpness over `ℤ`: the entries of a finite generating set generate the ring

`simple_kazhdan_sofic_group.tex`, subsection "Sharpness over $\Z$", l.397–399:

> Conversely, a Kazhdan group is finitely generated~\cite[Theorem~1.3.1]{BHV}, and the entries
> of finitely many generators and their inverses generate the ring, as $e_{12}(r)$ has the
> entry $r$.

## Proof route

* The cited fact (property `(T)` implies finite generation) is the corpus theorem
  `GroupApproximation.KazhdanFiniteGeneration.fg_of_hasKazhdanPropertyT`, proved by the
  coset-`ℓ²` argument, so nothing is assumed.
* For a subring `R₀`, the units `g` such that all entries of `g` and of `g⁻¹` lie in `R₀` form
  a subgroup `entrySubgroup ι R₀` (matrix multiplication only adds products of entries).
* If `S` generates `EL₃(R)` and `R₀` is the subring generated by the entries of the elements of
  `S` and their inverses, then `EL₃(R) ≤ entrySubgroup (Fin 3) R₀`; since `e₁₂(r) ∈ EL₃(R)`
  has entry `r` at `(0,1)`, every `r` lies in `R₀`.
-/

namespace GroupApproximation.SimpleKazhdanSofic.SharpnessExample

open Matrix

section Entries

variable {R : Type*} [Ring R]

/-- The units whose matrix and inverse matrix have all their entries in the subring `R₀`. -/
def entrySubgroup (ι : Type*) [Fintype ι] [DecidableEq ι] (R₀ : Subring R) :
    Subgroup (Matrix ι ι R)ˣ where
  carrier := {g | ∀ i j, (g : Matrix ι ι R) i j ∈ R₀ ∧
    ((g⁻¹ : (Matrix ι ι R)ˣ) : Matrix ι ι R) i j ∈ R₀}
  mul_mem' := by
    intro a b ha hb i j
    refine ⟨?_, ?_⟩
    · rw [Units.val_mul, Matrix.mul_apply]
      exact sum_mem fun k _ => mul_mem (ha i k).1 (hb k j).1
    · rw [mul_inv_rev, Units.val_mul, Matrix.mul_apply]
      exact sum_mem fun k _ => mul_mem (hb i k).2 (ha k j).2
  one_mem' := by
    intro i j
    have h1 : (1 : Matrix ι ι R) i j ∈ R₀ := by
      rw [Matrix.one_apply]
      split_ifs
      · exact R₀.one_mem
      · exact R₀.zero_mem
    refine ⟨?_, ?_⟩
    · rw [Units.val_one]
      exact h1
    · rw [inv_one, Units.val_one]
      exact h1
  inv_mem' := by
    intro a ha i j
    refine ⟨(ha i j).2, ?_⟩
    rw [inv_inv]
    exact (ha i j).1

/-- The entries of the elements of `S ⊆ EL₃(R)` and of their inverses. -/
def entries (S : Set (elementaryGroup (Fin 3) R)) : Set R :=
  {r | ∃ g ∈ S, ∃ i j : Fin 3,
    ((g : (Matrix (Fin 3) (Fin 3) R)ˣ) : Matrix (Fin 3) (Fin 3) R) i j = r ∨
      (((g : (Matrix (Fin 3) (Fin 3) R)ˣ)⁻¹ : (Matrix (Fin 3) (Fin 3) R)ˣ) :
        Matrix (Fin 3) (Fin 3) R) i j = r}

/-- A finite set of elements has finitely many entries. -/
theorem entries_finite {S : Set (elementaryGroup (Fin 3) R)} (hS : S.Finite) :
    (entries S).Finite := by
  refine (hS.biUnion fun g _ =>
    (Set.finite_range fun p : Fin 3 × Fin 3 =>
      ((g : (Matrix (Fin 3) (Fin 3) R)ˣ) : Matrix (Fin 3) (Fin 3) R) p.1 p.2).union
    (Set.finite_range fun p : Fin 3 × Fin 3 =>
      (((g : (Matrix (Fin 3) (Fin 3) R)ˣ)⁻¹ : (Matrix (Fin 3) (Fin 3) R)ˣ) :
        Matrix (Fin 3) (Fin 3) R) p.1 p.2)).subset ?_
  rintro r ⟨g, hg, i, j, h | h⟩
  · exact Set.mem_biUnion hg (Set.mem_union_left _ ⟨(i, j), h⟩)
  · exact Set.mem_biUnion hg (Set.mem_union_right _ ⟨(i, j), h⟩)

/-- The `(0,1)` entry of `e₁₂(r)` is `r`. -/
theorem elementaryUnit_zero_one_apply (r : R) :
    ((elementaryUnit (0 : Fin 3) 1 (by decide) r : (Matrix (Fin 3) (Fin 3) R)ˣ) :
      Matrix (Fin 3) (Fin 3) R) 0 1 = r := by
  change (1 + Matrix.single (0 : Fin 3) 1 r) 0 1 = r
  rw [Matrix.add_apply, Matrix.one_apply_ne (show (0 : Fin 3) ≠ 1 by decide),
    Matrix.single_apply_same, zero_add]

/-- **The entries of a generating set generate the ring.** -/
theorem subring_closure_entries_eq_top {S : Set (elementaryGroup (Fin 3) R)}
    (hS : Subgroup.closure S = ⊤) : Subring.closure (entries S) = ⊤ := by
  have hsub : Subgroup.closure S ≤
      (entrySubgroup (Fin 3) (Subring.closure (entries S))).comap
        (elementaryGroup (Fin 3) R).subtype := by
    rw [Subgroup.closure_le]
    intro g hg i j
    exact ⟨Subring.subset_closure ⟨g, hg, i, j, Or.inl rfl⟩,
      Subring.subset_closure ⟨g, hg, i, j, Or.inr rfl⟩⟩
  rw [Subring.eq_top_iff']
  intro r
  have hx : (⟨elementaryUnit (0 : Fin 3) 1 (by decide) r, elementaryUnit_mem _ _ _ _⟩ :
      elementaryGroup (Fin 3) R) ∈ Subgroup.closure S := by
    rw [hS]
    exact Subgroup.mem_top _
  have hmem := hsub hx
  rw [← elementaryUnit_zero_one_apply r]
  exact (hmem 0 1).1

end Entries

/-- **Sentence l.397 (tex l.397–399).** If `EL₃(R)` has property `(T)`, then it is finitely
generated, and there is a finite generating set `S` such that the finitely many entries of the
elements of `S` and their inverses generate the ring `R`; the reason is that `e₁₂(r)` has the
entry `r`. -/
theorem manuscriptSentence_kazhdanEntriesGenerateRing (R : Type) [Ring R]
    (hT : HasKazhdanPropertyT.{0, 0} (elementaryGroup (Fin 3) R)) :
    Group.FG (elementaryGroup (Fin 3) R) ∧
      (∃ S : Set (elementaryGroup (Fin 3) R), S.Finite ∧ Subgroup.closure S = ⊤ ∧
        (entries S).Finite ∧ Subring.closure (entries S) = ⊤) ∧
      ∀ r : R, ((elementaryUnit (0 : Fin 3) 1 (by decide) r : (Matrix (Fin 3) (Fin 3) R)ˣ) :
        Matrix (Fin 3) (Fin 3) R) 0 1 = r := by
  have hfg : Group.FG (elementaryGroup (Fin 3) R) :=
    KazhdanFiniteGeneration.fg_of_hasKazhdanPropertyT _ hT
  obtain ⟨S, hS, hfin⟩ := Group.fg_iff.mp hfg
  exact ⟨hfg, ⟨S, hfin, hS, entries_finite hfin, subring_closure_entries_eq_top hS⟩,
    elementaryUnit_zero_one_apply⟩

#audit_axioms manuscriptSentence_kazhdanEntriesGenerateRing

/-- A ring whose `EL₃` has property `(T)` is finitely generated as a ring. -/
theorem exists_finset_subring_closure_eq_top_of_kazhdan (R : Type) [Ring R]
    (hT : HasKazhdanPropertyT.{0, 0} (elementaryGroup (Fin 3) R)) :
    ∃ s : Finset R, Subring.closure (s : Set R) = ⊤ := by
  obtain ⟨_, ⟨_, _, _, hfin, htop⟩, _⟩ := manuscriptSentence_kazhdanEntriesGenerateRing R hT
  exact ⟨hfin.toFinset, by rw [Set.Finite.coe_toFinset]; exact htop⟩

end GroupApproximation.SimpleKazhdanSofic.SharpnessExample
