import GroupApproximation.CharClass.OddPFrobenius
-- Import notes, checked against pin `81a5d257`: `Mathlib/Algebra/CharP/Polynomial.lean`
-- does NOT exist; the instance `CharP R[X] p` is `Polynomial.charP` in
-- `Mathlib/Algebra/Polynomial/Coeff.lean` l.374.  `X_sub_C_ne_zero` is in
-- `Mathlib/Algebra/Polynomial/Degree/Operations.lean` l.774 and takes the ring
-- element, not a proof that it is nonzero.
import Mathlib.Algebra.Polynomial.AlgebraMap
import Mathlib.Algebra.Polynomial.Coeff
import Mathlib.Algebra.Polynomial.Degree.Operations
-- `Field (ZMod p)` and `IsDomain (ZMod p)` for `[Fact p.Prime]` live in
-- `Mathlib/Algebra/Field/ZMod.lean` l.30, l.39 — NOT in `Mathlib/Data/ZMod/Basic.lean`.
-- Without it `mul_right_cancel₀` cannot find `IsRightCancelMulZero (ZMod p)[X]`,
-- and the error names the polynomial ring, not the missing field instance.
import Mathlib.Algebra.Field.ZMod

/-!
# The norm is `s ^ (p - 1)`

`N := 1 + T + ⋯ + T^{p-1}` equals `s ^ (p-1)` with `s = T - 1`.  This is what
makes `N e_i` a boundary in `W` in **every** degree — for odd `i` because
`d e_{i+1} = N e_i` outright, for even `i` because `N = s · s^{p-2}` and
`d e_{i+1} = s e_i` — which in turn is what makes the reduced powers additive.

## The proof that does not work, and why it is this lane's own hazard

The tempting argument is: multiply `Σ_j T^j` by `T - 1` and telescope.  That
gives only `N · s = 0`, i.e. `N ∈ Ann(s)`.  In `Λ ≅ F_p[s]/(s^p)` the element
`s` is a zero divisor and `Ann(s) = (s^{p-1})` is one-dimensional, so the
telescope shows `N = c · s^{p-1}` for **some** `c` and leaves `c` completely
undetermined — including `c = 0`.

That is exactly the failure this lane's report warns about at §4: an identity
that pins an element only up to an unknown constant is not an identity.  Caught
by `sp-design` in review of the plan, where the wrong justification had been
written out in full.

## The proof that does work

Do the telescope in `F_p[X]`, which is a **domain**, and only then map `X ↦ T`:

```text
(Σ_{j<p} X^j) · (X - 1) = X^p - 1 = (X - 1)^p = (X - 1)^{p-1} · (X - 1)
```

the middle equality being Frobenius in characteristic `p`.  Cancel the nonzero
factor `X - 1` — legitimate in a domain and *not* legitimate in `Λ` — to get
`Σ_{j<p} X^j = (X - 1)^{p-1}`, then apply the algebra map sending `X` to `T`.
-/

namespace GroupApproximation.CharClass

open Polynomial

/-- The identity in the polynomial ring, where cancellation is legitimate. -/
theorem geom_sum_eq_sub_one_pow (p : ℕ) [Fact p.Prime] :
    (∑ j ∈ Finset.range p, (X : (ZMod p)[X]) ^ j) = (X - 1) ^ (p - 1) := by
  haveI : Fact (1 < p) := ⟨(Fact.out : p.Prime).one_lt⟩
  -- `mul_right_cancel₀` wants `IsRightCancelMulZero (ZMod p)[X]`, which is not
  -- found from `[Fact p.Prime]` alone; naming the domain instances supplies it.
  haveI : IsDomain (ZMod p) := inferInstance
  haveI : IsDomain (ZMod p)[X] := inferInstance
  have hne : (X - 1 : (ZMod p)[X]) ≠ 0 := by
    have h : (X - C (1 : ZMod p)) ≠ 0 := X_sub_C_ne_zero (1 : ZMod p)
    simpa using h
  have hp1 : p - 1 + 1 = p := Nat.succ_pred_eq_of_pos (Fact.out : p.Prime).pos
  refine mul_right_cancel₀ hne ?_
  calc (∑ j ∈ Finset.range p, (X : (ZMod p)[X]) ^ j) * (X - 1)
      = (X : (ZMod p)[X]) ^ p - 1 := geom_sum_mul _ _
    _ = ((X : (ZMod p)[X]) - 1) ^ p := by
        rw [sub_pow_char, one_pow]
    _ = ((X : (ZMod p)[X]) - 1) ^ (p - 1) * ((X : (ZMod p)[X]) - 1) := by
        rw [← pow_succ, hp1]

/-- **The norm is `s ^ (p - 1)`.** -/
theorem grNorm_eq (p : ℕ) [Fact p.Prime] : grNorm p = grS p ^ (p - 1) := by
  have h := congrArg (fun q : (ZMod p)[X] => aeval (grGen p) q)
    (geom_sum_eq_sub_one_pow p)
  simp only [map_sum, map_pow, map_sub, map_one, aeval_X] at h
  simpa [grNorm, grS] using h

/-- The norm lies in the ideal generated by `s`, which is what makes `N e_i` a
boundary in `W` in even degrees as well as odd ones. -/
theorem grNorm_eq_grS_mul (p : ℕ) [Fact p.Prime] (hp : 2 ≤ p) :
    grNorm p = grS p * grS p ^ (p - 2) := by
  rw [grNorm_eq, ← pow_succ']
  congr 1
  omega

end GroupApproximation.CharClass
