import GroupApproximation.CharClass.ParityPWuValue

/-!
# Decomposables from a vanishing linear coefficient

Lane `lix-evenside` (successor of `sp-evenside`), L4a of `sp-design` §3.3, the membership half.

`ParityPData`'s field (W) asks that `P^i(γ_{i+1}) − c_i·γ_{ip+1}` lie in `IsDecomposable`, the
additive subgroup generated by products of at least two Chern classes of positive index.  This
file proves the universal form of that membership:

> a symmetric polynomial over `ℤ`, homogeneous of degree `N ≥ 1`, whose `e_N`-coefficient
> modulo decomposables vanishes, is an integral combination of products of at least two
> elementary symmetric polynomials of positive index summing to `N`.

The proof reads off the `e`-expansion `F = eExpand f`.  By the crux
(`ParityPHomogConverse.eExpand_isWeightedHomogeneous`) every monomial of `F` has weight `N`,
where `X_a` carries weight `a + 1`.  A monomial of weight `N ≥ 1` is not `1`, and the only
monomials of degree one and weight `N` are `X_{N−1}`, whose coefficient is `eCoeff (N−1) f = 0`.
So every surviving monomial has degree at least two, and substituting `X_a ↦ e_{a+1}` turns it
into a product of at least two elementary symmetric polynomials.

## Main results

* `ParityP.IsDecomposable.map`, `.intCast_mul`, `.congr` — the closure properties the transport
  to Chern classes needs.
* `ParityP.exists_list_of_finsupp` — a monomial in the `e`-variables as a `gammaProd`.
* `ParityP.isDecomposable_eval₂_of_isWeightedHomogeneous` — the universal membership, for any
  evaluation of the `e`-variables.
* `ParityP.isDecomposable_of_eCoeff_eq_zero` — the membership for a symmetric polynomial.
-/

set_option autoImplicit false

namespace GroupApproximation.CharClass

namespace ParityP

open MvPolynomial

/-! ## 1. Closure properties of `IsDecomposable` -/

section Closure

variable {H : Type*} [CommRing H]

theorem gammaProd_append (γ : ℕ → H) (L M : List ℕ) :
    gammaProd γ (L ++ M) = gammaProd γ L * gammaProd γ M := by
  induction L with
  | nil => rw [List.nil_append, gammaProd_nil, one_mul]
  | cons α L ih => rw [List.cons_append, gammaProd_cons, gammaProd_cons, ih, mul_assoc]

theorem gammaProd_replicate (γ : ℕ → H) (α b : ℕ) :
    gammaProd γ (List.replicate b α) = γ α ^ b := by
  induction b with
  | zero => rw [List.replicate_zero, gammaProd_nil, pow_zero]
  | succ b ih => rw [List.replicate_succ, gammaProd_cons, ih, pow_succ']

theorem gammaProd_map {H' : Type*} [CommRing H'] (f : H →+* H') (γ : ℕ → H) (L : List ℕ) :
    f (gammaProd γ L) = gammaProd (fun k => f (γ k)) L := by
  induction L with
  | nil => rw [gammaProd_nil, gammaProd_nil, map_one]
  | cons α L ih => rw [gammaProd_cons, gammaProd_cons, map_mul, ih]

/-- A ring homomorphism carries decomposables to decomposables of the image classes. -/
theorem IsDecomposable.map {H' : Type*} [CommRing H'] (f : H →+* H') {γ : ℕ → H} {N : ℕ}
    {u : H} (hu : IsDecomposable γ N u) : IsDecomposable (fun k => f (γ k)) N (f u) := by
  induction hu with
  | monomial L hpos hsum hlen =>
    rw [gammaProd_map]
    exact IsDecomposable.monomial L hpos hsum hlen
  | zero =>
    rw [map_zero]
    exact IsDecomposable.zero
  | add u v _hu _hv ihu ihv =>
    rw [map_add]
    exact IsDecomposable.add _ _ ihu ihv
  | neg u _hu ihu =>
    rw [map_neg]
    exact IsDecomposable.neg _ ihu

/-- The decomposables depend on the classes only through their values. -/
theorem IsDecomposable.congr {γ γ' : ℕ → H} (h : ∀ k, γ k = γ' k) {N : ℕ} {u : H}
    (hu : IsDecomposable γ N u) : IsDecomposable γ' N u := by
  have hγ : γ = γ' := funext h
  rw [← hγ]
  exact hu

theorem IsDecomposable.sub {γ : ℕ → H} {N : ℕ} {u v : H} (hu : IsDecomposable γ N u)
    (hv : IsDecomposable γ N v) : IsDecomposable γ N (u - v) := by
  rw [sub_eq_add_neg]
  exact IsDecomposable.add _ _ hu (IsDecomposable.neg _ hv)

/-- Integer multiples of decomposables are decomposable. -/
theorem IsDecomposable.intCast_mul {γ : ℕ → H} {N : ℕ} {u : H} (hu : IsDecomposable γ N u)
    (k : ℤ) : IsDecomposable γ N ((k : H) * u) := by
  induction k using Int.induction_on with
  | zero =>
    rw [Int.cast_zero, zero_mul]
    exact IsDecomposable.zero
  | succ i ih =>
    rw [Int.cast_add, Int.cast_one, add_mul, one_mul]
    exact IsDecomposable.add _ _ ih hu
  | pred i ih =>
    rw [Int.cast_sub, Int.cast_one, sub_mul, one_mul]
    exact ih.sub hu

end Closure

/-! ## 2. Monomials in the `e`-variables -/

section Monomials

variable {H : Type*} [CommRing H] {n : ℕ}

/-- A monomial `∏_a X_a^{d_a}` in the `e`-variables, evaluated at `X_a ↦ γ (a+1)`, is the
`gammaProd` of a list of positive indices whose sum is the weight of `d` and whose length is
its degree. -/
theorem exists_list_of_finsupp (γ : ℕ → H) (d : Fin n →₀ ℕ) :
    ∃ L : List ℕ, (∀ β ∈ L, 1 ≤ β) ∧ L.sum = Finsupp.weight (eWeight n) d ∧
      L.length = Finsupp.degree d ∧
      gammaProd γ L = d.prod fun i k => γ ((i : ℕ) + 1) ^ k := by
  induction d using Finsupp.induction with
  | zero =>
    refine ⟨[], by simp, ?_, ?_, ?_⟩
    · rw [List.sum_nil, map_zero]
    · rw [List.length_nil, map_zero]
    · rw [gammaProd_nil, Finsupp.prod_zero_index]
  | single_add a b f _ha _hb ih =>
    obtain ⟨L, hpos, hsum, hlen, hprod⟩ := ih
    refine ⟨List.replicate b ((a : ℕ) + 1) ++ L, ?_, ?_, ?_, ?_⟩
    · intro β hβ
      rcases List.mem_append.mp hβ with h | h
      · rw [(List.mem_replicate.mp h).2]
        omega
      · exact hpos β h
    · simp only [List.sum_append, List.sum_replicate_nat, hsum, map_add, Finsupp.weight_single,
        eWeight_apply, smul_eq_mul]
    · rw [List.length_append, List.length_replicate, hlen, map_add, Finsupp.degree_single]
    · rw [gammaProd_append, gammaProd_replicate, hprod,
        Finsupp.prod_add_index' (h := fun (i : Fin n) (k : ℕ) => γ ((i : ℕ) + 1) ^ k)
          (fun _ => pow_zero _) (fun _ _ _ => pow_add _ _ _),
        Finsupp.prod_single_index (h := fun (i : Fin n) (k : ℕ) => γ ((i : ℕ) + 1) ^ k)
          (pow_zero _)]

/-- A nonzero exponent vector that is not a single variable has degree at least two. -/
theorem two_le_degree_of_ne {d : Fin n →₀ ℕ} (h0 : d ≠ 0)
    (h1 : ∀ a : Fin n, d ≠ Finsupp.single a 1) : 2 ≤ Finsupp.degree d := by
  obtain ⟨a, ha⟩ : ∃ a, d a ≠ 0 := by
    by_contra hcon
    refine h0 (Finsupp.ext fun i => ?_)
    by_contra hi
    exact hcon ⟨i, hi⟩
  have haS : a ∈ d.support := Finsupp.mem_support_iff.mpr ha
  by_cases h2 : 2 ≤ d a
  · exact h2.trans (Finsupp.le_degree a d)
  · have hda : d a = 1 := by omega
    obtain ⟨b, hb, hba⟩ : ∃ b, d b ≠ 0 ∧ b ≠ a := by
      by_contra hcon
      refine h1 a (Finsupp.ext fun i => ?_)
      by_cases hi : i = a
      · rw [hi, hda, Finsupp.single_eq_same]
      · rw [Finsupp.single_eq_of_ne hi]
        by_contra hdi
        exact hcon ⟨i, hdi, hi⟩
    have hbS : b ∈ d.support.erase a :=
      Finset.mem_erase.mpr ⟨hba, Finsupp.mem_support_iff.mpr hb⟩
    have hle : d b ≤ ∑ i ∈ d.support.erase a, d i :=
      Finset.single_le_sum_of_canonicallyOrdered hbS
    have hsplit := Finset.add_sum_erase d.support d haS
    rw [Finsupp.degree_apply, ← hsplit]
    omega

end Monomials

/-! ## 3. The universal membership -/

section Universal

variable {H : Type*} [CommRing H] {n : ℕ}

/-- **Weighted-homogeneous with no linear part gives decomposables.**  If `F` is
weighted-homogeneous of weight `N ≥ 1` in the `e`-variables and has no linear monomial, then
evaluating `X_a ↦ γ (a+1)` produces an element of `IsDecomposable γ N`. -/
theorem isDecomposable_eval₂_of_isWeightedHomogeneous (φ : ℤ →+* H) (γ : ℕ → H) {N : ℕ}
    (hN : 1 ≤ N) {F : MvPolynomial (Fin n) ℤ} (hF : F.IsWeightedHomogeneous (eWeight n) N)
    (hlin : ∀ a : Fin n, coeff (Finsupp.single a 1) F = 0) :
    IsDecomposable γ N (eval₂ φ (fun a : Fin n => γ ((a : ℕ) + 1)) F) := by
  rw [F.as_sum, eval₂_sum]
  refine IsDecomposable.sum _ _ fun d hd => ?_
  show IsDecomposable γ N (eval₂ φ (fun a : Fin n => γ ((a : ℕ) + 1)) (monomial d (coeff d F)))
  have hcoeff : coeff d F ≠ 0 := MvPolynomial.mem_support_iff.mp hd
  have hweight : Finsupp.weight (eWeight n) d = N := hF hcoeff
  have hd0 : d ≠ 0 := by
    intro h
    rw [h, map_zero] at hweight
    omega
  have hd1 : ∀ a : Fin n, d ≠ Finsupp.single a 1 := by
    intro a h
    rw [h] at hcoeff
    exact hcoeff (hlin a)
  obtain ⟨L, hpos, hsum, hlen, hprod⟩ := exists_list_of_finsupp γ d
  rw [eval₂_monomial, ← hprod, eq_intCast φ]
  refine (IsDecomposable.monomial L hpos (hsum.trans hweight) ?_).intCast_mul _
  rw [hlen]
  exact two_le_degree_of_ne hd0 hd1

/-- **L4a, the membership, universally.**  A symmetric polynomial over `ℤ`, homogeneous of
degree `N ≥ 1`, whose `e_N`-coefficient modulo decomposables vanishes, lies in the additive
subgroup generated by products of at least two elementary symmetric polynomials of positive
index summing to `N`. -/
theorem isDecomposable_of_eCoeff_eq_zero {N : ℕ} (hN : 1 ≤ N)
    (f : symmetricSubalgebra (Fin n) ℤ) (hf : IsHomogeneous (f : MvPolynomial (Fin n) ℤ) N)
    (hlin : ∀ a : Fin n, (a : ℕ) + 1 = N → eCoeff a f = 0) :
    IsDecomposable (fun k => esymm (Fin n) ℤ k) N (f : MvPolynomial (Fin n) ℤ) := by
  have hF := eExpand_isWeightedHomogeneous f hf
  have hlin' : ∀ a : Fin n, coeff (Finsupp.single a 1) (eExpand f) = 0 := by
    intro a
    by_cases ha : (a : ℕ) + 1 = N
    · rw [← eCoeff_eq_coeff_eExpand]
      exact hlin a ha
    · by_contra hc
      have hw := hF hc
      rw [Finsupp.weight_single, eWeight_apply, smul_eq_mul, one_mul] at hw
      exact ha hw
  have hval : (esymmAlgHom (Fin n) ℤ n (eExpand f)).val = (f : MvPolynomial (Fin n) ℤ) := by
    have h := (esymmAlgEquiv (Fin n) ℤ (Fintype.card_fin n)).apply_symm_apply f
    rw [esymmAlgEquiv_apply] at h
    exact congrArg Subtype.val h
  rw [← hval, esymmAlgHom_apply, aeval_def]
  exact isDecomposable_eval₂_of_isWeightedHomogeneous _ (fun k => esymm (Fin n) ℤ k) hN hF hlin'

end Universal

end ParityP

end GroupApproximation.CharClass
