import GroupApproximation.CharClass.ProjectiveSpaceComputation
import GroupApproximation.CharClass.ProjectiveSpaceRing
import GroupApproximation.CharClass.ChernEulerBundle

/-!
# The ring statement, from bijectivity alone

`cupPowE_ne_zero` takes a whole Gysin exact sequence, but its proof uses only one
consequence of it: that cupping with the Euler class is bijective in the even
degrees below the top.  Stating the entry point that way makes the last step of
the bootstrap a single application, and it means the Gysin input is needed only in
the range where the sphere bundle is acyclic rather than everywhere.

The second statement is free once the first holds: each even group up to twice the
dimension is a line, and a line containing a nonzero element contains nothing
else.

## Main declarations

* `cupPowE_ne_zero_of_bijective` — the powers are nonzero, from bijectivity of
  cupping.
* `eq_zero_or_eq_cupPowE_cpGen_of_ne` — and then each even group is exactly the
  two-element set generated by the corresponding power.
-/

set_option autoImplicit false

namespace GroupApproximation
namespace CharClass

open CategoryTheory

noncomputable section

/-- **The powers of the Euler class are nonzero**, given that cupping with it is
bijective in the even degrees below the top.  This is all `cupPowE_ne_zero` ever
used of the Gysin sequence. -/
theorem cupPowE_ne_zero_of_bijective {X : TopCat.{0}} {e : Hmod2 X 2} (N : ℕ)
    (hbij : ∀ m : ℕ, m < N → Function.Bijective (cupRightE e (2 * m)))
    (hone : (one X) ≠ 0) {m : ℕ} (hm : m ≤ N) : cupPowE e m ≠ 0 := by
  induction m with
  | zero => simpa using hone
  | succ m ih =>
    intro hcontra
    refine ih (by omega) ?_
    refine (hbij m (by omega)).1 ?_
    rw [cupRightE_cupPowE, hcontra, map_zero]

namespace CPn

/-- **Each even group of `ℂP^d` up to the top is the two-element set generated by
the corresponding power**, as soon as that power is nonzero.  The group is a line,
and a line containing a nonzero element contains nothing else. -/
theorem eq_zero_or_eq_cupPowE_cpGen_of_ne (d : ℕ) (hd : 1 ≤ d) {m : ℕ} (hm : m ≤ d)
    (hne : cupPowE (cpGen d hd) m ≠ 0) (a : Hmod2 (CPtop d) (2 * m)) :
    a = 0 ∨ a = cupPowE (cpGen d hd) m :=
  eq_zero_or_eq_of_line ((hasCPCohomology_CP d).1 m hm).some hne a

end CPn

end

end CharClass
end GroupApproximation
