# Collapse test for OPEN survivors G = <x, y | r1, r2> of the balanced census.
# For w in G * <t> of exponent sum 1 in t, G_w = <x, y, t | r1, r2, w>.  If G dies in
# G_w then G_w is cyclic generated by t with t = 1, so G_w = 1; hence "coset enumeration over
# the trivial subgroup closes with 1 coset" is exactly a certificate that G dies.
# A closed enumeration with n > 1 cosets means G_w is finite of order n, so G does NOT die
# (G_w != 1).  Overflow decides nothing.
# Reads COL_IN lines "<id> <r1> <r2> <w>" (w over x X y Y t T) and appends
# "<id> <r1> <r2> <w> <verdict>" with verdict KILLED | SURVIVES n=<n> | overflow.

F3 := FreeGroup("x", "y", "t");;
x3 := F3.1;; y3 := F3.2;; t3 := F3.3;;
L3 := rec(x := x3, X := x3^-1, y := y3, Y := y3^-1, t := t3, T := t3^-1);;
W3 := function(s) local w, ch;
  w := One(F3);
  for ch in s do w := w * L3.(String([ch])); od;
  return w;
end;;

Collapse3 := function(r1, r2, w, maxc) local tab;
  tab := CosetTableFromGensAndRels([x3, y3, t3], [W3(r1), W3(r2), W3(w)], [] : max := maxc, silent := true);
  if tab = fail then return "overflow"; fi;
  if Length(tab[1]) = 1 then return "KILLED"; fi;
  return Concatenation("SURVIVES n=", String(Length(tab[1])));
end;;

RunCol := function(inpath, outpath, maxc) local lines, ln, p, t0, v;
  lines := SplitString(StringFile(inpath), "\n");
  for ln in lines do
    if ln = "" then continue; fi;
    p := SplitString(ln, " ");
    t0 := Runtime();
    v := Collapse3(p[2], p[3], p[4], maxc);
    AppendTo(outpath, p[1], " ", p[2], " ", p[3], " ", p[4], " ", v, " ms=", Runtime() - t0, "\n");
  od;
end;;
