import GroupApproximation.BooneHigman.Metabelian.ElemFPK2PolyDegConst
import GroupApproximation.Meta.AxiomGuard

/-!
# Degree reduction for `K₂(F_p[X])`, part 5: an extension off the constants and `P` is a section

Lane `bh-met-91c`.  Notation of `ElemFPK2PolyDegSpans`.

* Generic group theory: `k2PolyDeg_equiv`/`k2PolyDeg_inv` invert a homomorphism on a subgroup
  that it maps injectively, and `k2PolyDeg_fixSub f X Φ` is the subgroup of `X` on which
  `Φ ∘ f` is the identity.
* `k2PolyDeg_eq_one_of_extension`: if `Φ : π(G) → St_I(F_p[X])` sends `π z` to `z` for every
  `z` in the constants `A` and every `z ∈ P`, then `G ∩ K₂ = 1`.

Truth check (paper).  `G` is generated by the roots `x_ij(f)` with `i, j ∈ K'`.  If `j ∈ K`,
then `x_ij(f)` lies in `S` or in `V`, so in `P`.  Otherwise `j = L` and `i ∈ K`, and
`x_iL(f) = w_iL(1) x_Li(-f) w_iL(1)⁻¹`, where `w_iL(1)` lies in `A` and `x_Li(-f)` lies in
`P`.  So `Φ ∘ π` is the identity on a generating set of `G`, hence on `G`, and then
`g = Φ(π g) = Φ(1) = 1` for every `g ∈ G ∩ K₂`.
-/

namespace GroupApproximation.BooneHigman.Metabelian.ElemFP

open GroupApproximation.SteinbergGroup
open GroupApproximation.BooneHigman.SteinbergBasic
open GroupApproximation.SimpleKazhdanSofic.SkRows.SteinbergWeyl (w x_congr)
open GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo (rootSpan
  x_mem_rootSpan rootSpan_induction)

section Generic

variable {G N : Type*} [Group G] [Group N]

/-- A homomorphism that is injective on `X` identifies `X` with its image. -/
noncomputable def k2PolyDeg_equiv (f : G →* N) (X : Subgroup G)
    (hX : ∀ x ∈ X, f x = 1 → x = 1) : X ≃* X.map f :=
  MulEquiv.ofBijective (f.subgroupMap X)
    ⟨(injective_iff_map_eq_one _).mpr fun y hy =>
      Subtype.ext (hX y y.2 (congrArg Subtype.val hy)), f.subgroupMap_surjective X⟩

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2PolyDeg_equiv

/-- The inverse `f(X) → X ≤ G` of a homomorphism that is injective on `X`. -/
noncomputable def k2PolyDeg_inv (f : G →* N) (X : Subgroup G)
    (hX : ∀ x ∈ X, f x = 1 → x = 1) : X.map f →* G :=
  X.subtype.comp (k2PolyDeg_equiv f X hX).symm.toMonoidHom

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2PolyDeg_inv

/-- `k2PolyDeg_inv` sends `f x` back to `x`, for `x ∈ X`. -/
theorem k2PolyDeg_inv_apply (f : G →* N) (X : Subgroup G) (hX : ∀ x ∈ X, f x = 1 → x = 1)
    {x : G} (hx : x ∈ X) {z : N} (hz : z ∈ X.map f) (e : f x = z) :
    k2PolyDeg_inv f X hX ⟨z, hz⟩ = x := by
  have h1 : (⟨z, hz⟩ : X.map f) = k2PolyDeg_equiv f X hX ⟨x, hx⟩ := Subtype.ext e.symm
  rw [h1]
  show ((k2PolyDeg_equiv f X hX).symm (k2PolyDeg_equiv f X hX ⟨x, hx⟩) : G) = x
  exact congrArg Subtype.val (MulEquiv.symm_apply_apply _ _)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2PolyDeg_inv_apply

/-- The subgroup of `X` on which `Φ ∘ f` is the identity. -/
def k2PolyDeg_fixSub (f : G →* N) (X : Subgroup G) (Φ : X.map f →* G) : Subgroup G :=
  ((Φ.comp (f.subgroupMap X)).eqLocus X.subtype).map X.subtype

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2PolyDeg_fixSub

theorem k2PolyDeg_mem_fixSub (f : G →* N) (X : Subgroup G) (Φ : X.map f →* G) {z : G}
    (hz : z ∈ X) (e : Φ ⟨f z, Subgroup.mem_map_of_mem f hz⟩ = z) :
    z ∈ k2PolyDeg_fixSub f X Φ :=
  Subgroup.mem_map.mpr ⟨⟨z, hz⟩, e, rfl⟩

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2PolyDeg_mem_fixSub

theorem k2PolyDeg_eq_one_of_mem_fixSub (f : G →* N) (X : Subgroup G) (Φ : X.map f →* G)
    {z : G} (hz : z ∈ k2PolyDeg_fixSub f X Φ) (h1 : f z = 1) : z = 1 := by
  obtain ⟨y, hy, rfl⟩ := Subgroup.mem_map.mp hz
  have hy' : Φ (f.subgroupMap X y) = y := hy
  have h2 : f.subgroupMap X y = 1 := Subtype.ext h1
  rw [h2, map_one] at hy'
  exact hy'.symm

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2PolyDeg_eq_one_of_mem_fixSub

end Generic

/-- A Weyl element lies in any root span containing both of its roots. -/
theorem k2PolyDeg_w_mem_rootSpan {I R : Type*} [Fintype I] [DecidableEq I] [Ring R]
    {q : I → I → Prop} (i j : I) (hij : i ≠ j) (u : Rˣ) (hq : q i j) (hq' : q j i) :
    w i j hij u ∈ rootSpan (R := R) q := by
  rw [w]
  exact Subgroup.mul_mem _ (Subgroup.mul_mem _ (x_mem_rootSpan hij _ hq)
    (x_mem_rootSpan hij.symm _ hq')) (x_mem_rootSpan hij _ hq)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2PolyDeg_w_mem_rootSpan

variable {I : Type} [Fintype I] [DecidableEq I] {p : ℕ} [Fact p.Prime]

/-- **Extension theorem.** If `Φ : π(G) → St_I(F_p[X])` sends `π z` back to `z` for every
constant `z ∈ A` and every `z ∈ P`, then `G ∩ K₂ = 1`. -/
theorem k2PolyDeg_eq_one_of_extension {K : Finset I} {m L n : I} (hmL : m ≠ L) (hmn : m ≠ n)
    (hLn : L ≠ n) (hthird : ∀ a b : I, ∃ k, a ≠ k ∧ b ≠ k)
    (Φ : (k2PolyDeg_G p K L).map projection →* SteinbergGroup I (Polynomial (ZMod p)))
    (hΦA : ∀ z ∈ k2PolyDeg_A p K L, ∀ hz : projection z ∈ (k2PolyDeg_G p K L).map projection,
      Φ ⟨projection z, hz⟩ = z)
    (hΦP : ∀ z ∈ k2PolyDeg_P p K m L n hmL hmn hLn,
      ∀ hz : projection z ∈ (k2PolyDeg_G p K L).map projection, Φ ⟨projection z, hz⟩ = z)
    {g : SteinbergGroup I (Polynomial (ZMod p))} (hg : g ∈ k2PolyDeg_G p K L)
    (hK2 : g ∈ K2 I (Polynomial (ZMod p))) : g = 1 := by
  have hfix : ∀ z : SteinbergGroup I (Polynomial (ZMod p)), z ∈ k2PolyDeg_G p K L →
      (z ∈ k2PolyDeg_A p K L ∨ z ∈ k2PolyDeg_P p K m L n hmL hmn hLn) →
      z ∈ k2PolyDeg_fixSub projection (k2PolyDeg_G p K L) Φ := by
    intro z hz hAP
    refine k2PolyDeg_mem_fixSub projection _ Φ hz ?_
    rcases hAP with hA | hP
    · exact hΦA z hA _
    · exact hΦP z hP _
  have hle : ∀ z : SteinbergGroup I (Polynomial (ZMod p)), z ∈ k2PolyDeg_G p K L →
      z ∈ k2PolyDeg_fixSub projection (k2PolyDeg_G p K L) Φ := by
    intro z hz
    refine rootSpan_induction (p := fun i j => i ∈ insert L K ∧ j ∈ insert L K)
      (Q := fun z => z ∈ k2PolyDeg_fixSub projection (k2PolyDeg_G p K L) Φ) ?_
      (Subgroup.one_mem _) (fun _ _ _ _ h1 h2 => Subgroup.mul_mem _ h1 h2) hz
    intro i j hij a hq
    show x i j hij a ∈ k2PolyDeg_fixSub projection (k2PolyDeg_G p K L) Φ
    have hq' : i ∈ insert L K ∧ j ∈ insert L K := hq
    have hq1 : i ∈ insert L K := hq'.1
    have hq2 : j ∈ insert L K := hq'.2
    have hxG : x i j hij a ∈ k2PolyDeg_G p K L :=
      x_mem_rootSpan (p := fun i j => i ∈ insert L K ∧ j ∈ insert L K) hij a ⟨hq1, hq2⟩
    by_cases hj : j ∈ K
    · have hSV : x i j hij a ∈ k2PolyDeg_S p K ⊔ k2PolyDeg_V p K L := by
        by_cases hiL : i = L
        · exact Subgroup.mem_sup_right
            (x_mem_rootSpan (p := fun i j => i = L ∧ j ∈ K) hij a ⟨hiL, hj⟩)
        · have hi : i ∈ K := (Finset.mem_insert.mp hq1).resolve_left hiL
          exact Subgroup.mem_sup_left
            (x_mem_rootSpan (p := fun i j => i ∈ K ∧ j ∈ K) hij a ⟨hi, hj⟩)
      have hP' : x i j hij a ∈ (k2PolyDeg_torus p m L n hmL hmn hLn).range ⊔
          (k2PolyDeg_S p K ⊔ k2PolyDeg_V p K L) := Subgroup.mem_sup_right hSV
      exact hfix _ hxG (Or.inr hP')
    · have hjL : j = L := (Finset.mem_insert.mp hq2).resolve_right hj
      have hiL : i ≠ L := fun e => hij (e.trans hjL.symm)
      have hi : i ∈ K := (Finset.mem_insert.mp hq1).resolve_left hiL
      obtain ⟨n', hin', hLn'⟩ := hthird i L
      have e : x i j hij a = w i L hiL (1 : (Polynomial (ZMod p))ˣ) * x L i hiL.symm (-a) *
          (w i L hiL (1 : (Polynomial (ZMod p))ˣ))⁻¹ := by
        rw [k2PolyDeg_w_conj_self_symm_eq i L n' hiL hin' hLn' 1 (-a)]
        exact x_congr _ _ rfl hjL (by rw [Units.val_one, one_mul, mul_one, neg_neg])
      have hwA : w i L hiL (1 : (Polynomial (ZMod p))ˣ) ∈ k2PolyDeg_A p K L :=
        Subgroup.mem_map.mpr ⟨w i L hiL (1 : (ZMod p)ˣ),
          k2PolyDeg_w_mem_rootSpan (q := fun i j => i ∈ insert L K ∧ j ∈ insert L K) i L hiL 1
            ⟨Finset.mem_insert_of_mem hi, Finset.mem_insert_self L K⟩
            ⟨Finset.mem_insert_self L K, Finset.mem_insert_of_mem hi⟩,
          by rw [k2PolyDeg_ringMap_w, map_one]⟩
      have hwG : w i L hiL (1 : (Polynomial (ZMod p))ˣ) ∈ k2PolyDeg_G p K L :=
        k2PolyDeg_w_mem_rootSpan (q := fun i j => i ∈ insert L K ∧ j ∈ insert L K) i L hiL 1
          ⟨Finset.mem_insert_of_mem hi, Finset.mem_insert_self L K⟩
          ⟨Finset.mem_insert_self L K, Finset.mem_insert_of_mem hi⟩
      have hxLG : x L i hiL.symm (-a) ∈ k2PolyDeg_G p K L :=
        x_mem_rootSpan (p := fun i j => i ∈ insert L K ∧ j ∈ insert L K) hiL.symm (-a)
          ⟨Finset.mem_insert_self L K, Finset.mem_insert_of_mem hi⟩
      have hV : x L i hiL.symm (-a) ∈ k2PolyDeg_V p K L :=
        x_mem_rootSpan (p := fun i j => i = L ∧ j ∈ K) hiL.symm (-a) ⟨rfl, hi⟩
      have hxLP : x L i hiL.symm (-a) ∈ (k2PolyDeg_torus p m L n hmL hmn hLn).range ⊔
          (k2PolyDeg_S p K ⊔ k2PolyDeg_V p K L) :=
        Subgroup.mem_sup_right (Subgroup.mem_sup_right hV)
      have hwF := hfix _ hwG (Or.inl hwA)
      have hxF := hfix _ hxLG (Or.inr hxLP)
      rw [e]
      exact Subgroup.mul_mem _ (Subgroup.mul_mem _ hwF hxF) (Subgroup.inv_mem _ hwF)
  exact k2PolyDeg_eq_one_of_mem_fixSub projection _ Φ (hle g hg) ((mem_K2_iff g).mp hK2)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2PolyDeg_eq_one_of_extension

end GroupApproximation.BooneHigman.Metabelian.ElemFP
