import GroupApproximation.BooneHigman.Metabelian.ElemFPK2KaroubiStatement
import GroupApproximation.BooneHigman.Metabelian.ElemFPK2PullRelRing
import GroupApproximation.BooneHigman.Metabelian.ElemFPK2CubeDiagDilateSt
import GroupApproximation.Meta.AxiomGuard

/-!
# Degenerate cases of the Karoubi residual `R1`

Lane `bh-met-92o`.  Notation: `P = A ×_L L[X]`, `L = A_s`, `fst : P → A`, `snd : P → L[X]`.

The results here are unconditional instances of `k2Karoubi_InjAt s` (`R1`).

* `k2KarInjAt_of_sndRetract` and `k2KarInjAt_of_fstRetract`: if `snd` (or `fst`) has a ring
  retraction, then `ringMap` along it is injective on `St(M, P)`, so `y = 1`.
* `k2KarInjAt_of_isUnit`: when `s` is a unit, `L ≅ A` and `h ↦ (λ⁻¹ h(0), h)` retracts `snd`.
* `k2KarInjAt_of_subsingleton` and `k2KarInjAt_of_isNilpotent`: when `L = 0`, `const`
  retracts `fst`.

## LOUD: the suggested route has a vacuous premise

The route asks to show that `ker fst ∩ ker snd` is normally generated by relation-type words,
by analogy with a Milnor square.  That analogy fails in both of its ingredients.

* `k2KarInjAt_snd_injective_of_regular` (in `ElemFPK2KarInjAtStatement`): for regular `s`,
  which covers the whole Pos family, the ring-level `ker snd` is `0`.  So the commutator `[x(ker fst), x(ker snd)]` is trivial.
* `snd` is not surjective (only `P_s = L[X]`).

Once that commutator is gone, the route has nothing left to decompose, and what remains is
exactly `R1`.
-/

universe u

namespace GroupApproximation.BooneHigman.Metabelian.ElemFP

open GroupApproximation.BooneHigman.SteinbergBasic GroupApproximation.SteinbergGroup

section KarInjAtTriv

variable {A : Type u} [CommRing A] {s : A}

/-- If `snd : P → L[X]` has a ring retraction, then `R1` holds at `s`. -/
theorem k2KarInjAt_of_sndRetract
    (g : Polynomial (Localization.Away s) →+* k2DilateSt_pullback s)
    (hg : Function.LeftInverse g (k2PullRel_snd s)) : k2Karoubi_InjAt s := by
  intro M y _ h₂
  have hy : y = 1 :=
    ringMap_injective_of_leftInverse (I := Fin M) (k2PullRel_snd s) g hg
      (h₂.trans (map_one (ringMap (I := Fin M) (k2PullRel_snd s))).symm)
  rw [hy]
  exact cubeDiagDilate_stDies_one

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2KarInjAt_of_sndRetract

/-- If `fst : P → A` has a ring retraction, then `R1` holds at `s`. -/
theorem k2KarInjAt_of_fstRetract (g : A →+* k2DilateSt_pullback s)
    (hg : Function.LeftInverse g (k2PullRel_fst s)) : k2Karoubi_InjAt s := by
  intro M y h₁ _
  have hy : y = 1 :=
    ringMap_injective_of_leftInverse (I := Fin M) (k2PullRel_fst s) g hg
      (h₁.trans (map_one (ringMap (I := Fin M) (k2PullRel_fst s))).symm)
  rw [hy]
  exact cubeDiagDilate_stDies_one

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2KarInjAt_of_fstRetract

/-- For a unit `s`, the inverse `L → A` of `λ : A → L`. -/
noncomputable def k2KarInjAt_unitInv (hs : IsUnit s) : Localization.Away s →+* A :=
  IsLocalization.Away.lift (S := Localization.Away s) (g := RingHom.id A) s hs

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2KarInjAt_unitInv

theorem k2KarInjAt_unitInv_algebraMap (hs : IsUnit s) (a : A) :
    k2KarInjAt_unitInv hs (algebraMap A (Localization.Away s) a) = a :=
  IsLocalization.Away.lift_eq (S := Localization.Away s) (g := RingHom.id A) s hs a

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2KarInjAt_unitInv_algebraMap

theorem k2KarInjAt_algebraMap_comp_unitInv (hs : IsUnit s) :
    (algebraMap A (Localization.Away s)).comp (k2KarInjAt_unitInv hs) = RingHom.id _ := by
  apply IsLocalization.ringHom_ext (Submonoid.powers s)
  refine RingHom.ext fun a ↦ ?_
  simp only [RingHom.comp_apply, RingHom.id_apply, k2KarInjAt_unitInv_algebraMap]

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2KarInjAt_algebraMap_comp_unitInv

/-- For a unit `s`, the section `L[X] → P`, `h ↦ (λ⁻¹ h(0), h)`. -/
noncomputable def k2KarInjAt_unitSection (hs : IsUnit s) :
    Polynomial (Localization.Away s) →+* k2DilateSt_pullback s :=
  RingHom.codRestrict
    (((k2KarInjAt_unitInv hs).comp (Polynomial.evalRingHom 0)).prod (RingHom.id _))
    (k2DilateSt_pullback s) fun h ↦
      (k2DilateSt_mem_pullback s _).mpr
        (RingHom.congr_fun (k2KarInjAt_algebraMap_comp_unitInv hs) (h.eval 0))

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2KarInjAt_unitSection

theorem k2KarInjAt_unitSection_snd (hs : IsUnit s) :
    Function.LeftInverse (k2KarInjAt_unitSection hs) (k2PullRel_snd s) := fun b ↦ by
  refine k2PullRel_ext ?_ ?_
  · show k2KarInjAt_unitInv hs ((k2PullRel_snd s b).eval 0) = k2PullRel_fst s b
    rw [k2PullRel_eval_snd, k2KarInjAt_unitInv_algebraMap]
  · rfl

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2KarInjAt_unitSection_snd

/-- **`R1` for a unit `s`.** -/
theorem k2KarInjAt_of_isUnit (hs : IsUnit s) : k2Karoubi_InjAt s :=
  k2KarInjAt_of_sndRetract (k2KarInjAt_unitSection hs) (k2KarInjAt_unitSection_snd hs)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2KarInjAt_of_isUnit

/-- When `L = 0`, `const : A → P` retracts `fst`. -/
theorem k2KarInjAt_const_fst_of_subsingleton [Subsingleton (Localization.Away s)] :
    Function.LeftInverse (k2PullRel_const s) (k2PullRel_fst s) := fun b ↦
  k2PullRel_ext (k2PullRel_fst_const s _) (Polynomial.ext fun _ ↦ Subsingleton.elim _ _)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2KarInjAt_const_fst_of_subsingleton

/-- **`R1` when `L = 0`.** -/
theorem k2KarInjAt_of_subsingleton [Subsingleton (Localization.Away s)] :
    k2Karoubi_InjAt s :=
  k2KarInjAt_of_fstRetract (k2PullRel_const s) k2KarInjAt_const_fst_of_subsingleton

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2KarInjAt_of_subsingleton

/-- **`R1` for a nilpotent `s`** (then `L = A_s = 0`). -/
theorem k2KarInjAt_of_isNilpotent (hs : IsNilpotent s) : k2Karoubi_InjAt s := by
  obtain ⟨n, hn⟩ := hs
  have h0 : (0 : A) ∈ Submonoid.powers s := (Submonoid.mem_powers_iff 0 s).mpr ⟨n, hn⟩
  haveI : Subsingleton (Localization.Away s) :=
    IsLocalization.subsingleton (M := Submonoid.powers s) (S := Localization.Away s) h0
  exact k2KarInjAt_of_subsingleton

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.k2KarInjAt_of_isNilpotent

end KarInjAtTriv

end GroupApproximation.BooneHigman.Metabelian.ElemFP
