import GroupApproximation.BooneHigman.Metabelian.ElemFPK2SurjStabReduce
import GroupApproximation.BooneHigman.Metabelian.ElemFPCharZeroK2PosStabGen
import GroupApproximation.Meta.AxiomGuard

/-!
# Surjective `K₂` stability over `ℤ[1/m]`: reduction to `P Q P` conjugates (lane bh-met-54)

Target: the `hsurj` input of `charZeroK2PosStabGen_of_fg_of_surj`, namely
`K₂(n+1, ℤ[1/m]) ≤ stab K₂(n, ℤ[1/m])` for `m > 0` and `n ≥ 4`.

## Truth check

The target is TRUE.  `ℤ[1/m]` is a Dedekind domain, so its stable rank is at most `2`.  By
Dennis and van der Kallen, `K₂(n, R) → K₂(n+1, R)` is surjective for `n ≥ sr(R) + 1`.  The
case `m = 1` is a sanity check: `K₂(n, ℤ) = ℤ/2` for `n ≥ 3`, generated by `{-1,-1}`, which is
stabilized from rank 3.

## What is proved

`ElemFPK2SurjStabReduce` proves the following over ANY unital ring: `K₂(n+1) ∩ P Q ⊆ stab K₂(n)`
(`surjStab_col_row_mem_map`), and hence that a `K₂` element with a conjugate in `P Q P` lies
in `stab K₂(n)`.  Here `P = stab St_n · padCol R^n` and `Q = stab St_n · padRow R^n`.

## Remaining gap

`SurjStabConjTripleStatement`: every `x ∈ K₂(n+1, ℤ[1/m])` with `n ≥ 4` has a conjugate
`(stab g₁ · padCol v₁)(stab g₂ · padRow w)(stab g₃ · padCol v₃)`.

LOUD: this gap is logically EQUIVALENT to `hsurj`, not weaker.  The converse
`surjStabConjTriple_of_surj` is trivial and proved below, with `z = 1`, `v = w = 0`.  It is
strictly SMALLER in proof content.  The parabolic intersection argument, i.e. the last-row
functional, the block computation `padMat g = 1`, `v = w = 0`, and the centrality of
`stab K₂(n)`, is now discharged.  What remains is only the factorization step of the
van der Kallen argument: use `sr ≤ 2` to move the last column of a relation into
`e_{n+1}` by lower-triangular operations while staying in `St_{n+1}`.
-/

namespace GroupApproximation.BooneHigman.Metabelian.ElemFPCharZero

open GroupApproximation.BooneHigman.SteinbergBasic
open GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.PaddedCentral

/-- Every `K₂` element over `ℤ[1/m]` (`m > 0`, `n ≥ 4`) has a conjugate in `P Q P`. -/
def SurjStabConjTripleStatement : Prop :=
  ∀ m n : ℕ, 0 < m → 4 ≤ n → ∀ x ∈ K2 (Fin (n + 1)) (Localization.Away (m : ℤ)),
    SurjStabConjTriple x

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFPCharZero.SurjStabConjTripleStatement

/-- Trivial converse: an element of `stab K₂(n)` is already in `P Q P`. -/
theorem surjStab_conjTriple_of_mem_map {R : Type*} [Ring R] {n : ℕ} {x : St (n + 1) R}
    (hx : x ∈ (K2 (Fin n) R).map (stab n R)) : SurjStabConjTriple x := by
  obtain ⟨k, _, rfl⟩ := Subgroup.mem_map.mp hx
  refine ⟨1, k, 1, 1, 0, 0, 0, ?_⟩
  simp only [padCol_zero, padRow_zero, map_one, mul_one, one_mul, inv_one]

#audit_axioms
  GroupApproximation.BooneHigman.Metabelian.ElemFPCharZero.surjStab_conjTriple_of_mem_map

/-- **Surjective stability** over `ℤ[1/m]` from the `P Q P` statement. -/
theorem charZeroK2SurjStab_of_conjTriple (h : SurjStabConjTripleStatement) :
    ∀ m n : ℕ, 0 < m → 4 ≤ n → K2 (Fin (n + 1)) (Localization.Away (m : ℤ)) ≤
      (K2 (Fin n) (Localization.Away (m : ℤ))).map (stab n (Localization.Away (m : ℤ))) :=
  fun m n hm hn => surjStab_k2_le_map_of_conjTriple (h m n hm hn)

#audit_axioms
  GroupApproximation.BooneHigman.Metabelian.ElemFPCharZero.charZeroK2SurjStab_of_conjTriple

/-- The gap is equivalent to `hsurj` (converse direction). -/
theorem surjStabConjTriple_of_surj
    (hsurj : ∀ m n : ℕ, 0 < m → 4 ≤ n → K2 (Fin (n + 1)) (Localization.Away (m : ℤ)) ≤
      (K2 (Fin n) (Localization.Away (m : ℤ))).map (stab n (Localization.Away (m : ℤ)))) :
    SurjStabConjTripleStatement :=
  fun m n hm hn _ hx => surjStab_conjTriple_of_mem_map (hsurj m n hm hn hx)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFPCharZero.surjStabConjTriple_of_surj

/-- Endpoint: the positive-rank stabilized generation statement from finite generation and
the `P Q P` statement. -/
theorem charZeroK2PosStabGen_of_fg_of_conjTriple
    (hfg : ∀ m n : ℕ, 0 < m → 4 ≤ n → Group.FG (K2 (Fin n) (Localization.Away (m : ℤ))))
    (h : SurjStabConjTripleStatement) : CharZeroK2PosStabGenStatement :=
  charZeroK2PosStabGen_of_fg_of_surj hfg (charZeroK2SurjStab_of_conjTriple h)

#audit_axioms
  GroupApproximation.BooneHigman.Metabelian.ElemFPCharZero.charZeroK2PosStabGen_of_fg_of_conjTriple

end GroupApproximation.BooneHigman.Metabelian.ElemFPCharZero
