import GroupApproximation.BooneHigman.Metabelian.ElemFPK2CubeCofinalDiag
import GroupApproximation.BooneHigman.Metabelian.ElemFPK2CubeDiagDilateLocal
import GroupApproximation.Meta.AxiomGuard

/-!
# The diagonal cube gap from generated local Quillen elements

Lane `bh-met-85`.  Target: `CubeCofinalDiagStatement` (module `ElemFPK2CubeCofinalDiag`).  For a
cube `u ∈ K₂(n, F_p[s_0..s_k])`, put `B = F_p[s_1..s_k]` and `ψ u ∈ K₂(n, B[t])`.  For each
maximal `m` of `B`, the target asks for one `s ∉ m` such that `v_s(ψ u)` dies after padding.

**The target is NOT proved here.**  It is true: Quillen homotopy invariance of `K₂` over the
regular ring `F_p[s_1..s_k]` and `K₂(F_p) = 0` give `ψ u = 1` stably, so `s = 1` works.  But a
proof inside the corpus needs three results that are not available here:
(a) unstable `K₂` homotopy invariance after padding over the regular local rings `B_m`;
(b) the colimit step `B_m = colim B_s` for Steinberg relations;
(c) Tulenbaev's Steinberg dilation lemma: if `g ∈ St(B[y])`, `g(0) = 1`, dies over `B_s[y]`, then
`g(s^N y)` dies over `B[y]`.

## The isolated gap: `CubeDiagDilateGeneratedStatement`

For each cube `u` and each maximal `m`, **some padding of `ψ u` lies in the subgroup generated by
`T_m`**.  Here `T_m = cubeDiagDilate_LocalSet m` is the set of `g ∈ St(M, B[t])` having
**their own** local element `a ∉ m` with `v_a(g) = g(t + a y) g(t)⁻¹` dying after padding.  The
generators need not lie in `K₂`.

**LOUD: logical strength.**  Both Statements are true, and the converse
`cubeDiagDilate_generated_of_cubeCofinalDiag` is proved below.  So as propositions the two are
equivalent over the proved lemmas.  The gap is **strictly smaller in proof content**, not strictly
weaker in logical form.  To prove it, one may factor the padded `ψ u` in `St(M, B[t])` into
Steinberg elements outside `K₂`, as a Suslin/Tulenbaev decomposition does, and handle each factor
with its own `a_j ∉ m`.  Those factors need not share a local element and need not be in `K₂`.

**Removed proof content, proved here** (modules `ElemFPK2CubeDiagDilateSt`, `...Local`):
* the crossed-homomorphism identities `v(g₁ g₂) = v(g₁) · C(g₁) v(g₂) C(g₁)⁻¹` and
  `v(g⁻¹) = C(g)⁻¹ v(g)⁻¹ C(g)`;
* the choice of the common local element `a₁ a₂ ∉ m` at a prime, via `μ_c v_a = v_{c a}`;
* invariance of Steinberg-level dying under products, inverses, arbitrary conjugation,
  coefficient maps and padding;
* padding commutes with `v_a`;
* the `K₂ ↔ St` bridge.

Together these make `T_m` a subgroup.  **What remains** is the core (a)–(c) above, now needed only
factor by factor.  This is the `K₂`/Steinberg analogue of `SuslinDilationGeneratedQuillen`, which
is the `E_N` form.

## Endpoints

* `cubeDiagDilate_cubeCofinalDiag_of_generated : CubeDiagDilateGeneratedStatement →
  CubeCofinalDiagStatement`;
* `cubeDiagDilate_generated_of_cubeCofinalDiag`, the converse;
* `cubeDiagDilate_polyK2OneVarNil_of_generated : CubeDiagDilateGeneratedStatement →
  PolyK2OneVarNilStatement`.
-/

namespace GroupApproximation.BooneHigman.Metabelian.ElemFP

open GroupApproximation.BooneHigman.SteinbergBasic

/-- **The isolated gap (generated local Quillen form).**  For every prime `p` and every `n`, some
`k ≥ n` is such that for every `u ∈ K₂(n, F_p[s_0..s_k])` killed by every `π_i : s_i ↦ 0`, and
every maximal ideal `m` of `F_p[s_1..s_k]`, some padding of `ψ u ∈ St(n, F_p[s_1..s_k][t])` lies
in the subgroup generated by the Steinberg elements `g` that each have their own `a ∉ m` with
`g(t + a y) g(t)⁻¹` dying after padding.

LOUD: equivalent to `CubeCofinalDiagStatement` over the proved lemmas.  It is strictly smaller in
proof content only: the generators need not lie in `K₂` and need not share a local element.  See
the module docstring. -/
def CubeDiagDilateGeneratedStatement : Prop :=
  ∀ p : ℕ, p.Prime → ∀ n : ℕ, ∃ k : ℕ, n ≤ k ∧
    ∀ u : K2n n (MvPolynomial (Fin (k + 1)) (ZMod p)),
      (∀ i : Fin (k + 1), K2Map (cubeKill (ZMod p) i) u = 1) →
        ∀ m : Ideal (MvPolynomial (Fin k) (ZMod p)), m.IsMaximal →
          ∃ M : ℕ, ∃ hnM : n ≤ M,
            SteinbergGroup.indexMap (Fin.castLEEmb hnM)
                (SteinbergGroup.ringMap
                  (MvPolynomial.finSuccEquiv (ZMod p) k).toRingEquiv.toRingHom
                  (u : SteinbergGroup (Fin n) (MvPolynomial (Fin (k + 1)) (ZMod p)))) ∈
              Subgroup.closure (cubeDiagDilate_LocalSet (N := M) m)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.ElemFP.CubeDiagDilateGeneratedStatement

/-- **Reduction**: the generated local Quillen form gives the diagonal cube gap. -/
theorem cubeDiagDilate_cubeCofinalDiag_of_generated (h : CubeDiagDilateGeneratedStatement) :
    CubeCofinalDiagStatement := by
  intro p hp n
  obtain ⟨k, hnk, hk⟩ := h p hp n
  refine ⟨k, hnk, fun u hu m hm ↦ ?_⟩
  obtain ⟨M, hnM, hmem⟩ := hk u hu m hm
  obtain ⟨s, hs, hdies⟩ := (cubeDiagDilate_mem_localSet_iff m _).mp
    ((cubeDiagDilate_mem_localSubgroup_iff m hm.isPrime _).mp
      (cubeDiagDilate_closure_localSet_le m hm.isPrime hmem))
  refine ⟨s, hs, (cubeDiagDilate_diesAfterPadding_iff _).mpr ?_⟩
  rw [cubeDiagDilate_coe_quillenDiff, K2Map_apply]
  rw [← cubeDiagDilate_indexMap_stDiff] at hdies
  exact cubeDiagDilate_stDies_of_indexMap hnM hdies

#audit_axioms
  GroupApproximation.BooneHigman.Metabelian.ElemFP.cubeDiagDilate_cubeCofinalDiag_of_generated

/-- **Converse** (LOUD: the gap is implied by the target, with `M = n` and one generator). -/
theorem cubeDiagDilate_generated_of_cubeCofinalDiag (h : CubeCofinalDiagStatement) :
    CubeDiagDilateGeneratedStatement := by
  intro p hp n
  obtain ⟨k, hnk, hk⟩ := h p hp n
  refine ⟨k, hnk, fun u hu m hm ↦ ⟨n, le_rfl, Subgroup.subset_closure ?_⟩⟩
  obtain ⟨s, hs, hdies⟩ := hk u hu m hm
  refine (cubeDiagDilate_mem_localSet_iff m _).mpr ⟨s, hs, ?_⟩
  rw [← cubeDiagDilate_indexMap_stDiff]
  refine cubeDiagDilate_stDies_indexMap le_rfl ?_
  have hd := (cubeDiagDilate_diesAfterPadding_iff _).mp hdies
  rw [cubeDiagDilate_coe_quillenDiff, K2Map_apply] at hd
  exact hd

#audit_axioms
  GroupApproximation.BooneHigman.Metabelian.ElemFP.cubeDiagDilate_generated_of_cubeCofinalDiag

/-- The generated local Quillen form gives `PolyK2OneVarNilStatement`: for `N ≥ k + 5`, every
`u ∈ K₂(N, F_p[s_1..s_k][t])` killed by `t ↦ 0` dies after padding. -/
theorem cubeDiagDilate_polyK2OneVarNil_of_generated (h : CubeDiagDilateGeneratedStatement) :
    PolyK2OneVarNilStatement :=
  polyK2OneVarNil_of_cubeCofinalDiag (cubeDiagDilate_cubeCofinalDiag_of_generated h)

#audit_axioms
  GroupApproximation.BooneHigman.Metabelian.ElemFP.cubeDiagDilate_polyK2OneVarNil_of_generated

end GroupApproximation.BooneHigman.Metabelian.ElemFP
