import GroupApproximation.BooneHigman.Metabelian.EnvelopeHigmanVGenAll
import GroupApproximation.BooneHigman.V.Group
import Mathlib.Data.Set.Finite.List
import Mathlib.SetTheory.Cardinal.NatCard
import GroupApproximation.Meta.AxiomGuard

/-!
# A finite family of cone swaps generating every cone swap

`vgenShortSwaps X` enumerates the cone swaps of the pairs of words of length `≤ 3` (with `1` for
comparable pairs).  `vgenShortSwaps_closure`: over an alphabet with two letters, the subgroup of
`higmanThompsonV X` generated by this finite family contains every cone swap
(`vgen_swapIn_of_short`).
-/

namespace GroupApproximation.BooneHigman.Metabelian.Envelope

variable {X : Type*} [Finite X]

open Classical in
/-- The cone swap of `v` and `w` when they are incomparable, and `1` otherwise. -/
noncomputable def vgenSwapOrOne (v w : List X) : ↥(higmanThompsonV X) :=
  if h : ¬ v <+: w ∧ ¬ w <+: v then
    ⟨coneSwap v w h.1 h.2, coneSwap_mem_higmanThompsonV h.1 h.2⟩
  else 1

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.vgenSwapOrOne

theorem vgenSwapOrOne_eq {v w : List X} (h1 : ¬ v <+: w) (h2 : ¬ w <+: v) :
    vgenSwapOrOne v w = ⟨coneSwap v w h1 h2, coneSwap_mem_higmanThompsonV h1 h2⟩ :=
  dif_pos (And.intro h1 h2)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.vgenSwapOrOne_eq

variable (X) in
/-- The pairs of words of length at most `3`. -/
def vgenShortPairs : Set (List X × List X) :=
  {l : List X | l.length ≤ 3} ×ˢ {l : List X | l.length ≤ 3}

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.vgenShortPairs

variable (X) in
theorem vgenShortPairs_finite : (vgenShortPairs X).Finite :=
  (List.finite_length_le X 3).prod (List.finite_length_le X 3)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.vgenShortPairs_finite

variable (X) in
/-- An enumeration of the pairs of short words. -/
noncomputable def vgenShortEquiv : ↥(vgenShortPairs X) ≃ Fin (Nat.card ↥(vgenShortPairs X)) :=
  @Finite.equivFin _ (vgenShortPairs_finite X).to_subtype

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.vgenShortEquiv

variable (X) in
/-- The short cone swaps, enumerated. -/
noncomputable def vgenShortSwaps (i : Fin (Nat.card ↥(vgenShortPairs X))) :
    ↥(higmanThompsonV X) :=
  vgenSwapOrOne ((vgenShortEquiv X).symm i).1.1 ((vgenShortEquiv X).symm i).1.2

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.vgenShortSwaps

theorem vgenShortSwaps_mem {v w : List X} (hv : v.length ≤ 3) (hw : w.length ≤ 3)
    (h1 : ¬ v <+: w) (h2 : ¬ w <+: v) :
    (⟨coneSwap v w h1 h2, coneSwap_mem_higmanThompsonV h1 h2⟩ : ↥(higmanThompsonV X)) ∈
      Set.range (vgenShortSwaps X) := by
  have hmem : (v, w) ∈ vgenShortPairs X :=
    Set.mk_mem_prod (s := {l : List X | l.length ≤ 3}) (t := {l : List X | l.length ≤ 3}) hv hw
  refine ⟨vgenShortEquiv X ⟨(v, w), hmem⟩, ?_⟩
  simp only [vgenShortSwaps, Equiv.symm_apply_apply]
  exact vgenSwapOrOne_eq h1 h2

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.vgenShortSwaps_mem

/-- **Every cone swap lies in the subgroup generated by the short cone swaps.** -/
theorem vgenShortSwaps_closure [Nontrivial X] {v w : List X} (h1 : ¬ v <+: w)
    (h2 : ¬ w <+: v) :
    (⟨coneSwap v w h1 h2, coneSwap_mem_higmanThompsonV h1 h2⟩ : ↥(higmanThompsonV X)) ∈
      Subgroup.closure (Set.range (vgenShortSwaps X)) := by
  have key : VGenSwapIn ((Subgroup.closure (Set.range (vgenShortSwaps X))).map
      (higmanThompsonV X).subtype) v w := by
    refine vgen_swapIn_of_short ?_ v w
    intro v' w' hv' hw' h1' h2'
    exact Subgroup.mem_map.mpr
      ⟨⟨coneSwap v' w' h1' h2', coneSwap_mem_higmanThompsonV h1' h2'⟩,
        Subgroup.subset_closure (vgenShortSwaps_mem hv' hw' h1' h2'), rfl⟩
  obtain ⟨y, hy, hyv⟩ := Subgroup.mem_map.mp (key h1 h2)
  have hy' : y = ⟨coneSwap v w h1 h2, coneSwap_mem_higmanThompsonV h1 h2⟩ := Subtype.ext hyv
  rw [← hy']
  exact hy

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.vgenShortSwaps_closure

end GroupApproximation.BooneHigman.Metabelian.Envelope
