import GroupApproximation.BooneHigman.Metabelian.EnvelopeHigmanVCOrbitStemReduce
import Mathlib.Tactic.Group
import GroupApproximation.Meta.AxiomGuard

/-!
# Multi-letter pivot closure: generators and canonical conjugation (lane bh-met-92t)

Notation as in `EnvelopeHigmanVCOrbitLongReduce`: `Q = higmanVCCommon_Q d`,
`U = higmanVCTreeNF_U d`, `H_C = higmanVCTreeNFWitPivot_H d C`, and `m(x, y)` is the image of
the letter `(x, y)`.

**Proved.**
* `higmanVCOrbitMulti_H_le`: `H_C` lies in the subgroup generated by the letters `m(x, y)`
  with `x, y ∈ C`.  This is the handle for induction on the word length of `h ∈ H_C`.
* `higmanVCOrbitMulti_conj` (**canonical conjugation**): let `x, y, x₀, y₀ ∈ C` with
  `|x₀| = |x|`, `|y₀| = |y|` and `|x| ≠ |y|`, and put `w = m(y₀, y) m(x₀, x)`.  Then
  `w m(x₀, y₀) w⁻¹ = m(x, y)`.  Both factors of `w` are balanced, so `w ∈ U ∩ H_C`.  The
  proof uses only the proved faithfulness of the transposition presentation on one antichain
  (`higmanVCOrbit_mk_eq_one`), applied to the word `w m(x₀, y₀) w⁻¹ m(x, y)⁻¹`.  Its leaf
  permutation is `σ (x₀ y₀) σ⁻¹ (x y)` with `σ = (y₀ y)(x₀ x)`, and this is trivial because
  `σ x₀ = x` and `σ y₀ = y`.

Nothing here assumes Higman's theorem.
-/

namespace GroupApproximation.BooneHigman.Metabelian.Envelope

/-- The letters of `C`, as elements of `Q`. -/
def higmanVCOrbitMulti_gens (d : ℕ) (C : Finset (List (Fin d))) : Set (higmanVCCommon_Q d) :=
  {g | ∃ x y : ↥C, g = higmanVCCommon_mk d (FreeGroup.of (x.1, y.1))}

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.higmanVCOrbitMulti_gens

/-- `H_C` lies in the subgroup generated by the letters of `C`. -/
theorem higmanVCOrbitMulti_H_le (d : ℕ) (C : Finset (List (Fin d))) :
    higmanVCTreeNFWitPivot_H d C ≤ Subgroup.closure (higmanVCOrbitMulti_gens d C) := by
  intro h hh
  obtain ⟨r, rfl⟩ := higmanVCTreeNFWitPivot_mem_H.mp hh
  clear hh
  induction r using FreeGroup.induction_on with
  | C1 =>
    rw [map_one (higmanVCAll_iota C), map_one]
    exact Subgroup.one_mem _
  | of p =>
    rw [higmanVCAll_iota_of]
    exact Subgroup.subset_closure ⟨p.1, p.2, rfl⟩
  | inv_of _ ih =>
    rw [map_inv (higmanVCAll_iota C), map_inv]
    exact Subgroup.inv_mem _ ih
  | mul g₁ g₂ ih₁ ih₂ =>
    rw [map_mul (higmanVCAll_iota C), map_mul]
    exact Subgroup.mul_mem _ ih₁ ih₂

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.higmanVCOrbitMulti_H_le

/-- A letter squares to one, so its inverse is itself. -/
theorem higmanVCOrbitMulti_letter_inv {d : ℕ} (u v : List (Fin d)) :
    (higmanVCCommon_mk d (FreeGroup.of (u, v)))⁻¹ = higmanVCCommon_mk d (FreeGroup.of (u, v)) :=
  inv_eq_of_mul_eq_one_right (higmanVCCommon_mk_sq u v)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.higmanVCOrbitMulti_letter_inv

/-- The leaf permutation of `w m(x₀, y₀) w⁻¹ m(x, y)⁻¹` is trivial. -/
theorem higmanVCOrbitMulti_pi_eq_one {d : ℕ} {C : Finset (List (Fin d))} {x y x₀ y₀ : ↥C}
    (hlen : x.1.length ≠ y.1.length) (hx₀ : x₀.1.length = x.1.length)
    (hy₀ : y₀.1.length = y.1.length) :
    higmanVCOrbit_pi C (FreeGroup.of (y₀, y) * FreeGroup.of (x₀, x) * FreeGroup.of (x₀, y₀) *
      (FreeGroup.of (y₀, y) * FreeGroup.of (x₀, x))⁻¹ * (FreeGroup.of (x, y))⁻¹) = 1 := by
  have hxy : x ≠ y := fun e => hlen (congrArg (fun z : ↥C => z.1.length) e)
  have hxy₀ : x ≠ y₀ := fun e => hlen ((congrArg (fun z : ↥C => z.1.length) e).trans hy₀)
  have hy₀x : y₀ ≠ x := fun e =>
    hlen ((hy₀.symm.trans (congrArg (fun z : ↥C => z.1.length) e)).symm)
  have hy₀x₀ : y₀ ≠ x₀ := fun e =>
    hlen (hx₀.symm.trans ((congrArg (fun z : ↥C => z.1.length) e).symm.trans hy₀))
  have hσx : (Equiv.swap y₀ y * Equiv.swap x₀ x) x₀ = x := by
    rw [Equiv.Perm.mul_apply, Equiv.swap_apply_left, Equiv.swap_apply_of_ne_of_ne hxy₀ hxy]
  have hσy : (Equiv.swap y₀ y * Equiv.swap x₀ x) y₀ = y := by
    rw [Equiv.Perm.mul_apply, Equiv.swap_apply_of_ne_of_ne hy₀x₀ hy₀x, Equiv.swap_apply_left]
  have e := Equiv.swap_apply_apply (Equiv.swap y₀ y * Equiv.swap x₀ x) x₀ y₀
  rw [hσx, hσy] at e
  simp only [map_mul, map_inv, higmanVCOrbit_pi_of]
  rw [mul_inv_eq_one]
  exact e.symm

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.higmanVCOrbitMulti_pi_eq_one

/-- **Canonical conjugation.**  `m(y₀, y) m(x₀, x) · m(x₀, y₀) · (m(y₀, y) m(x₀, x))⁻¹ =
m(x, y)` whenever `|x₀| = |x| ≠ |y| = |y₀|`, all four on the antichain `C`. -/
theorem higmanVCOrbitMulti_conj {d : ℕ} {C : Finset (List (Fin d))}
    (hC : higmanVCTreeNFWitPivot_IsAC C) {x y x₀ y₀ : ↥C} (hlen : x.1.length ≠ y.1.length)
    (hx₀ : x₀.1.length = x.1.length) (hy₀ : y₀.1.length = y.1.length) :
    higmanVCCommon_mk d (FreeGroup.of (y₀.1, y.1)) *
        higmanVCCommon_mk d (FreeGroup.of (x₀.1, x.1)) *
        higmanVCCommon_mk d (FreeGroup.of (x₀.1, y₀.1)) *
        (higmanVCCommon_mk d (FreeGroup.of (y₀.1, y.1)) *
          higmanVCCommon_mk d (FreeGroup.of (x₀.1, x.1)))⁻¹ =
      higmanVCCommon_mk d (FreeGroup.of (x.1, y.1)) := by
  have key := higmanVCOrbit_mk_eq_one hC (higmanVCOrbitMulti_pi_eq_one hlen hx₀ hy₀)
  simp only [map_mul, map_inv, higmanVCAll_iota_of] at key
  exact mul_inv_eq_one.mp key

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Envelope.higmanVCOrbitMulti_conj

end GroupApproximation.BooneHigman.Metabelian.Envelope
