import GroupApproximation.BooneHigman.Primary.Coprimary
import GroupApproximation.BooneHigman.Metabelian.PureCharPrimeEHighMixed
import GroupApproximation.BooneHigman.Metabelian.PureCharPrimeEHighETwoUnits
import GroupApproximation.Meta.AxiomGuard

/-!
# The infinite mixed case at `e = 2`: reduction to a unit-group embedding (bh-met-87)

**Target.**  `EHighETwoStatement` is `eHighMixed_InfiniteStatement`
(`PureCharPrimeEHighMixed.lean:51`) with `e` fixed to `2`.  So `M` is a finitely generated
coprimary `(ℤ/p²)[Q]`-module with prime `P ∋ p`, exponent `k ≥ 2`, `p • M ≠ 0` and `M`
infinite.  The goal is a faithful conjugation representation over a field of characteristic `p`.
`eHighETwo_of_infinite` records that it is a special case of the bh-met-84 residual.

**Not proved: the target itself.**  What is proved is the reduction `eHighETwo_of_units` to
`EHighETwoUnitsStatement`.  The residual asks for a *finite-dimensional* commutative `K`-algebra
`B` (`ringChar K = p`), an injective `θ : Multiplicative M →* B`, and an action of `Q` on `B`
by `K`-algebra automorphisms with `θ (q • m) = σ q (θ m)`.  The reduction is the
linearization `eHighETwo_exists_gl_of_units` (`PureCharPrimeEHighETwoUnits`): left
multiplication and `σ`, written in a basis of `B`.

**LOUD: the suggested Greenberg route is false as stated.**  The suggestion was that the
Greenberg functor turns a `W₂(k)`-module of rank `r` into a `k`-vector space of dimension `2r`.
The Greenberg transform of `W₂(k)` is the 2-dimensional commutative unipotent group `W₂` over
`k`, and it is **not** a vector group.  In `W₂(k)`, `p • (1, 0) = (0, 1) ≠ 0`, so its group of
points has exponent `p²`.  A group of exponent `p²` cannot embed additively into any vector
space over a field of characteristic `p`, which has exponent `p`.  In particular no additive
`Q`-equivariant `M ↪ K^d` exists here, because `p • M ≠ 0`.  So the `e = 1` form
(`PureCharPrimeEOneStatement`, an additive `ι : M →+ K^d`) cannot be the intermediate step,
and neither can "2×2 block-triangular `k`-linear maps".  Faithful linear representations of
`W₂` have dimension at least `p + 1`: `ℤ/p² ↪ U_n(F_p)` iff `n ≥ p + 1`, as recorded in
`PureCharPrimeEHighDevissageStatement`.  The correct intermediate object is
**multiplicative**, a unit group.  This is why the residual is phrased with
`θ : Multiplicative M →* B`.  The model is the truncated Artin–Hasse exponential
`W₂(A) → (A[ε]/(ε^(p+1)))ˣ` for a ring `A` of characteristic `p`.  (For `p = 2` this is
`(a₀, a₁) ↦ 1 + a₀ ε + a₁ ε²`, and the multiplication
`(1 + a₀ε + a₁ε²)(1 + b₀ε + b₁ε²) = 1 + (a₀+b₀)ε + (a₁+b₁+a₀b₀)ε²` matches the Witt addition.)

**Truth check.**  The residual is true.  Assume the target, which holds by Wehrfritz as
recorded for `eHighMixed_InfiniteStatement`.  Given `κ` and `ρ`, let `B ⊆ M_d(K)` be the
`K`-subalgebra generated by `κ(M)`.  It is commutative because `M` is abelian, and it is
finite-dimensional.  Conjugation by `ρ q` maps the generator `κ m` to `κ (q • m)`, so it
restricts to an algebra automorphism of `B`, with inverse coming from `q⁻¹`.  Take `θ = κ`.
(This converse is argued on paper, not formalized.)

**LOUD: the residual is only EQUIVALENT to the target (interderivable), not strictly weaker in
logical strength.**  The target implies the residual by the paper argument above, and the
residual implies the target by `eHighETwo_of_units`.  The gain is proof content: the whole
passage from a unit-group embedding to matrices (basis choice, faithfulness, the conjugation
identity `L_{σ b} ∘ σ = σ ∘ L_b`) is discharged.  The residual also isolates the correct
multiplicative interface for the Artin–Hasse route, where the additive/Greenberg interface
suggested for it is impossible.

**Remaining mathematical gap (the Artin–Hasse route, not formalized).**  Build `B` from `M`.
1. Localize at `P`.  Elements outside `P` act injectively, so `M ↪ M_P`, a finite-length module
   over the Artinian local ring `R_P`.
2. Give `R_P` a coefficient ring: a Cohen ring of `κ(P)` modulo `p²`, or `W₂(L)` after passing
   to a perfect field `L ⊇ κ(P)`.
3. Present `M_P` inside a finite free `W₂(L)`-module on which the images of `Q` act.
4. Apply Artin–Hasse coordinatewise, enlarging `B` so that non-Teichmüller units still act by
   algebra automorphisms.  Teichmüller units `(λ, 0)` act through `ε ↦ λ ε`.  For a general
   unit `(λ, μ)` of `W₂`, the naive substitution `ε ↦ λ ε + μ ε^p` does **not** induce the
   multiplication: in degree `p` it produces `μ a₀` where `μ a₀^p` is needed.  This is the
   delicate step.
-/

namespace GroupApproximation.BooneHigman.Metabelian.Coprimary

/-- **Target (e = 2).**  `eHighMixed_InfiniteStatement` with `e = 2`. -/
def EHighETwoStatement : Prop :=
  ∀ p : ℕ, p.Prime → ∀ (Q : Type) [CommGroup Q], Group.FG Q →
    ∀ (M : Type) [AddCommGroup M] [Module (MonoidAlgebra (ZMod (p ^ 2)) Q) M],
      Module.Finite (MonoidAlgebra (ZMod (p ^ 2)) Q) M →
      ∀ (P : Ideal (MonoidAlgebra (ZMod (p ^ 2)) Q)) (k : ℕ),
        Primary.IsCoprimaryWith (MonoidAlgebra (ZMod (p ^ 2)) Q) M P k →
        ((p : ℕ) : MonoidAlgebra (ZMod (p ^ 2)) Q) ∈ P →
        2 ≤ k → (∃ m : M, p • m ≠ 0) → Infinite M →
      ∃ (K : Type) (_ : Field K) (d : ℕ)
        (κ : Multiplicative M →* Matrix.GeneralLinearGroup (Fin d) K)
        (ρ : Q →* Matrix.GeneralLinearGroup (Fin d) K),
        ringChar K = p ∧ Function.Injective κ ∧
          ∀ (q : Q) (m : M),
            κ (Multiplicative.ofAdd (MonoidAlgebra.of (ZMod (p ^ 2)) Q q • m)) =
              ρ q * κ (Multiplicative.ofAdd m) * (ρ q)⁻¹

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Coprimary.EHighETwoStatement

/-- The `e = 2` target is a special case of the bh-met-84 residual. -/
theorem eHighETwo_of_infinite (h : eHighMixed_InfiniteStatement) : EHighETwoStatement := by
  intro p hp Q _ hfg M _ _ hfin P k hM hpP hk hne hinf
  exact h p hp 2 le_rfl Q hfg M hfin P k hM hpP hk hne hinf

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Coprimary.eHighETwo_of_infinite
