import GroupApproximation.BooneHigman.Metabelian.SuslinCongVacStatement
import GroupApproximation.BooneHigman.Metabelian.AbsorptionSuslinReduction
import GroupApproximation.Meta.AxiomGuard

/-!
# Deciding `SuslinCongVacIncl`, part 1: the unipotent subgroup `U₂(S)`

Lane `bh-met-92i`.

* `suslinCongDecide_unipSet S`: the units `1 + N` of `M₂(S)` with `N * N = 0`.
* `suslinCongDecide_unipGen S = U₂(S)`: the subgroup they generate.  It is NORMAL in `GL₂(S)`
  (`suslinCongDecide_unipGen_eq`: it equals the normal closure of its generators).
* `suslinCongDecide_locGen_le` (**the key inclusion**): if `SL₂(A) = E₂(A)`, then
  `SuslinCongLocGen A S ≤ U₂(S)`.  Proof: each of the three generator families is unipotent
  (`E₂(S)` is generated by `1 + e_{ij}(a)`, `(e_{ij}(a))² = 0`; `(x yᵀ)² = (y ⬝ᵥ x) x yᵀ = 0`;
  `ψ(τ) ∈ ψ(E₂(A)) ≤ E₂(S)`), and `U₂(S)` is normal.

So for `A = 𝔽_p[t]` (where `SL₂(A) = E₂(A)` is proved in the repo) the residual class
`SuslinCongLocGen A A_𝔪[X]` is contained in `U₂(A_𝔪[X])`.  Part 3 uses this to refute
`SuslinCongVacIncl (𝔽_p[t])` from a free-quotient theorem for `SL₂(R[x]) / U₂(R[x])`.
-/

namespace GroupApproximation
namespace BooneHigman
namespace Metabelian
namespace Absorption

/-- The unipotent units `1 + N`, `N * N = 0`, of `M₂(S)`. -/
def suslinCongDecide_unipSet (S : Type*) [CommRing S] : Set (Matrix (Fin 2) (Fin 2) S)ˣ :=
  {σ | ∃ N : Matrix (Fin 2) (Fin 2) S, N * N = 0 ∧ (σ : Matrix (Fin 2) (Fin 2) S) = 1 + N}

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Absorption.suslinCongDecide_unipSet

/-- `U₂(S)`: the subgroup of `GL₂(S)` generated by the unipotent units. -/
def suslinCongDecide_unipGen (S : Type*) [CommRing S] : Subgroup (Matrix (Fin 2) (Fin 2) S)ˣ :=
  Subgroup.closure (suslinCongDecide_unipSet S)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Absorption.suslinCongDecide_unipGen

/-- Conjugation preserves square-zero elements. -/
theorem suslinCongDecide_sq_conj {M : Type*} [Ring M] {g gi N : M} (h : gi * g = 1)
    (hN : N * N = 0) : g * N * gi * (g * N * gi) = 0 := by
  calc g * N * gi * (g * N * gi) = g * N * (gi * g) * N * gi := by simp only [mul_assoc]
    _ = 0 := by rw [h, mul_one, mul_assoc g N N, hN, mul_zero, zero_mul]

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Absorption.suslinCongDecide_sq_conj

/-- Conjugating `1 + N`. -/
theorem suslinCongDecide_one_add_conj {M : Type*} [Ring M] {g gi : M} (h : g * gi = 1)
    (N : M) : g * (1 + N) * gi = 1 + g * N * gi := by
  rw [mul_add, mul_one, add_mul, h]

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Absorption.suslinCongDecide_one_add_conj

/-- The unipotent units are closed under conjugation. -/
theorem suslinCongDecide_unipSet_conj {S : Type*} [CommRing S]
    (g σ : (Matrix (Fin 2) (Fin 2) S)ˣ) (hσ : σ ∈ suslinCongDecide_unipSet S) :
    g * σ * g⁻¹ ∈ suslinCongDecide_unipSet S := by
  obtain ⟨N, hN, hval⟩ := hσ
  refine ⟨(g : Matrix (Fin 2) (Fin 2) S) * N *
      ((g⁻¹ : (Matrix (Fin 2) (Fin 2) S)ˣ) : Matrix (Fin 2) (Fin 2) S),
    suslinCongDecide_sq_conj (Units.inv_mul g) hN, ?_⟩
  rw [Units.val_mul, Units.val_mul, hval]
  exact suslinCongDecide_one_add_conj (Units.mul_inv g) N

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Absorption.suslinCongDecide_unipSet_conj

/-- `U₂(S)` is the normal closure of the unipotent units. -/
theorem suslinCongDecide_unipGen_eq (S : Type*) [CommRing S] :
    suslinCongDecide_unipGen S = Subgroup.normalClosure (suslinCongDecide_unipSet S) := by
  refine le_antisymm Subgroup.closure_le_normalClosure ?_
  rw [Subgroup.normalClosure, Subgroup.closure_le]
  intro x hx
  obtain ⟨a, ha, hax⟩ := Group.mem_conjugatesOfSet_iff.mp hx
  obtain ⟨c, rfl⟩ := isConj_iff.mp hax
  exact Subgroup.subset_closure (k := suslinCongDecide_unipSet S)
    (suslinCongDecide_unipSet_conj c a ha)

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Absorption.suslinCongDecide_unipGen_eq

/-- `U₂(S)` is normal in `GL₂(S)`. -/
theorem suslinCongDecide_unipGen_normal (S : Type*) [CommRing S] :
    (suslinCongDecide_unipGen S).Normal := by
  rw [suslinCongDecide_unipGen_eq]
  exact Subgroup.normalClosure_normal

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Absorption.suslinCongDecide_unipGen_normal

/-- `E₂(S) ≤ U₂(S)`. -/
theorem suslinCongDecide_elementary_le (S : Type*) [CommRing S] :
    elementaryGroup (Fin 2) S ≤ suslinCongDecide_unipGen S := by
  rw [elementaryGroup, Subgroup.closure_le]
  rintro _ ⟨i, j, h, a, rfl⟩
  exact Subgroup.subset_closure (k := suslinCongDecide_unipSet S)
    ⟨Matrix.single i j a, single_mul_self_eq_zero i j h a, rfl⟩

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Absorption.suslinCongDecide_elementary_le

/-- Every elementary unit lies in `U₂(S)`. -/
theorem suslinCongDecide_elementaryUnit_mem {S : Type*} [CommRing S] (i j : Fin 2) (h : i ≠ j)
    (a : S) : elementaryUnit i j h a ∈ suslinCongDecide_unipGen S :=
  suslinCongDecide_elementary_le S (elementaryUnit_mem i j h a)

#audit_axioms
  GroupApproximation.BooneHigman.Metabelian.Absorption.suslinCongDecide_elementaryUnit_mem

/-- **The key inclusion**: if `SL₂(A) = E₂(A)`, then `SuslinCongLocGen A S ≤ U₂(S)`. -/
theorem suslinCongDecide_locGen_le {A S : Type*} [CommRing A] [CommRing S]
    (hA : SpecialLinearInElementary A 2) :
    SuslinCongLocGen A S ≤ suslinCongDecide_unipGen S := by
  haveI : (suslinCongDecide_unipGen S).Normal := suslinCongDecide_unipGen_normal S
  rw [SuslinCongLocGen]
  refine Subgroup.normalClosure_le_normal ?_
  rintro σ ((hσ | ⟨x, y, hyx, hσ⟩) | ⟨ψ, τ, hτ, rfl⟩)
  · have hσ' : σ ∈ elementaryGroup (Fin 2) S := hσ
    exact suslinCongDecide_elementary_le S hσ'
  · refine Subgroup.subset_closure (k := suslinCongDecide_unipSet S)
      ⟨Matrix.vecMulVec x y, ?_, hσ⟩
    rw [Matrix.vecMulVec_mul_vecMulVec, hyx, zero_smul, Matrix.vecMulVec_zero]
  · exact suslinCongDecide_elementary_le S
      (elementaryGroup_map_le ψ (Subgroup.mem_map_of_mem _ (hA τ hτ)))

#audit_axioms GroupApproximation.BooneHigman.Metabelian.Absorption.suslinCongDecide_locGen_le

end Absorption
end Metabelian
end BooneHigman
end GroupApproximation
