import GroupApproximation.Kazhdan.GHWFiniteReduction
import GroupApproximation.Algebra.BoundedIntegralFinite
import GroupApproximation.Algebra.GHWFrobeniusSeparable
import Mathlib.RingTheory.NoetherNormalization
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.FieldTheory.IntermediateField.Algebraic
import Mathlib.Algebra.Algebra.ZMod
import Mathlib.RingTheory.FiniteType
import Mathlib.RingTheory.Finiteness.Cardinality
import Mathlib.Algebra.CharP.Algebra
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
import Mathlib.Algebra.MvPolynomial.Equiv
import GroupApproximation.Meta.AxiomGuard

/-!
# GHW Theorem 4 in positive characteristic

`non_mf_groups_exist.tex`, the remark after `prop:torsion-defect-ring` (tex lines 1146--1147):

> Every countable subgroup of `GL_2` over a field has the Haagerup property …

This module proves the statement over a field `F` of prime characteristic `p`
(`printedGHWTheoremFourCharP`).  By `hasHaagerupProperty_of_closure_finite` it is enough to treat
the subgroup generated by a finite set `s ⊆ GL_2(F)`.

* The entries of the elements of `s` and of their inverses generate a finitely generated
  `𝔽_p`-algebra `A ⊆ F`, and every element of the subgroup has its entries in `A`
  (`entries_mem_of_mem_closure`).
* Noether normalization gives an injective `B = 𝔽_p[t_1, …, t_d] → A` with `A` integral over `B`.
  Let `L = Frac B`; the field `K = L(entries)` is finite over `L`, and the subgroup lies in
  `GL_2(K)`.
* `K / L` may be inseparable, but an iterated Frobenius `x ↦ x^{p^e}` maps `K` into a separable
  intermediate field `K'` (`exists_separable_frobenius_embedding`).  So the subgroup embeds in
  `GL_2(K')`, and the entries there are still integral over `B`.
* Over a finite separable extension of `L`, the places at infinity leave only finitely many
  integral elements of bounded valuation (`BoundedIntegralFinite.finite_bounded_integral`).  That is
  the finiteness hypothesis of `hasHaagerupProperty_of_places` with no archimedean places
  (`hasHaagerupProperty_of_isIntegral`).
-/

namespace GroupApproximation
namespace GHW

open Haagerup WithZero

/-- The places at infinity of a finite separable extension of `k(t_1, …, t_d)`, also for `d = 0`,
where the extension is itself finite. -/
theorem exists_places_bounded_integral {k : Type*} [Field k] [Finite k] (d : ℕ) (K : Type*)
    [Field K] [Algebra (MvPolynomial (Fin d) k) K]
    [Algebra (FractionRing (MvPolynomial (Fin d) k)) K]
    [IsScalarTower (MvPolynomial (Fin d) k) (FractionRing (MvPolynomial (Fin d) k)) K]
    [FiniteDimensional (FractionRing (MvPolynomial (Fin d) k)) K]
    [Algebra.IsSeparable (FractionRing (MvPolynomial (Fin d) k)) K] :
    ∃ (r : ℕ) (u : Fin r → Valuation K ℤᵐ⁰), (∀ j, ∃ ϖ : K, u j ϖ = exp (-1 : ℤ)) ∧
      ∀ N : ℕ,
        {a : K | IsIntegral (MvPolynomial (Fin d) k) a ∧ ∀ j, u j a ≤ exp (N : ℤ)}.Finite := by
  rcases Nat.eq_zero_or_pos d with hd | hd
  · subst hd
    haveI : Finite (MvPolynomial (Fin 0) k) :=
      Finite.of_equiv k (MvPolynomial.isEmptyAlgEquiv (R := k) (σ := Fin 0)).toEquiv.symm
    haveI : Finite (FractionRing (MvPolynomial (Fin 0) k)) :=
      Finite.of_surjective _ (IsLocalization.mk'_surjective
        (M := nonZeroDivisors (MvPolynomial (Fin 0) k)) (S := FractionRing (MvPolynomial (Fin 0) k)))
    haveI : Finite K := Module.finite_of_finite (FractionRing (MvPolynomial (Fin 0) k))
    exact ⟨0, Fin.elim0, fun j ↦ j.elim0, fun N ↦ Set.toFinite _⟩
  · exact BoundedIntegralFinite.finite_bounded_integral hd K

/-- **Integral entries give the Haagerup property.**  If `Γ ≤ GL_2(K)` for a finite separable
extension `K` of `k(t_1, …, t_d)` and every entry is integral over `k[t_1, …, t_d]`, then `Γ` has
the Haagerup property. -/
theorem hasHaagerupProperty_of_isIntegral {k : Type} [Field k] [Finite k] {d : ℕ} {K : Type}
    [Field K] [Algebra (FractionRing (MvPolynomial (Fin d) k)) K]
    [FiniteDimensional (FractionRing (MvPolynomial (Fin d) k)) K]
    [Algebra.IsSeparable (FractionRing (MvPolynomial (Fin d) k)) K]
    {Γ : Type} [Group Γ] (ρ : Γ →* GL (Fin 2) K) (hρ : Function.Injective ρ)
    (hint : ∀ (γ : Γ) (a b : Fin 2),
      ((algebraMap (FractionRing (MvPolynomial (Fin d) k)) K).comp
        (algebraMap (MvPolynomial (Fin d) k) (FractionRing (MvPolynomial (Fin d) k)))).IsIntegralElem
        (((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) a b)) :
    HasHaagerupProperty.{0, 0} Γ := by
  classical
  letI : Algebra (MvPolynomial (Fin d) k) K :=
    ((algebraMap (FractionRing (MvPolynomial (Fin d) k)) K).comp
      (algebraMap (MvPolynomial (Fin d) k) (FractionRing (MvPolynomial (Fin d) k)))).toAlgebra
  haveI : IsScalarTower (MvPolynomial (Fin d) k) (FractionRing (MvPolynomial (Fin d) k)) K :=
    IsScalarTower.of_algebraMap_eq' rfl
  obtain ⟨r, u, hunif, hfin⟩ := exists_places_bounded_integral (k := k) d K
  choose ϖ hϖ using hunif
  refine hasHaagerupProperty_of_places ρ hρ (k := r) (m := 0)
    (fun j ↦ ValuationWithTopInt.addVal (u j)) ϖ
    (fun j ↦ ValuationWithTopInt.addVal_eq_one (u j) (hϖ j)) Fin.elim0 Fin.elim0
    (fun i ↦ i.elim0) {a | IsIntegral (MvPolynomial (Fin d) k) a} hint ?_
  intro C N
  refine (hfin N).subset ?_
  rintro a ⟨ha, -, hv⟩
  refine ⟨ha, fun j ↦ ?_⟩
  by_cases ha0 : a = 0
  · rw [ha0, Valuation.map_zero]
    exact zero_le
  · exact (ValuationWithTopInt.neg_le_addVal_iff (u j) ha0 (N : ℤ)).mp (hv j)

/-- The entries of the elements of `s` and of their inverses. -/
def entrySet {F : Type*} [Field F] (s : Set (GL (Fin 2) F)) : Set F :=
  ⋃ g ∈ s,
    (Set.range fun ab : Fin 2 × Fin 2 ↦ ((g : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) ab.1 ab.2) ∪
      Set.range fun ab : Fin 2 × Fin 2 ↦ ((g⁻¹ : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) ab.1 ab.2

theorem entrySet_finite {F : Type*} [Field F] {s : Set (GL (Fin 2) F)} (hs : s.Finite) :
    (entrySet s).Finite := by
  unfold entrySet
  exact hs.biUnion fun _ _ ↦ (Set.finite_range _).union (Set.finite_range _)

theorem mem_entrySet {F : Type*} [Field F] {s : Set (GL (Fin 2) F)} {g : GL (Fin 2) F}
    (hg : g ∈ s) (a b : Fin 2) :
    ((g : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) a b ∈ entrySet s ∧
      ((g⁻¹ : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) a b ∈ entrySet s := by
  unfold entrySet
  exact ⟨Set.mem_biUnion hg (Set.mem_union_left _ ⟨(a, b), rfl⟩),
    Set.mem_biUnion hg (Set.mem_union_right _ ⟨(a, b), rfl⟩)⟩

theorem one_entry_mem {R F : Type*} [CommRing R] [Field F] [Algebra R F] (S : Subalgebra R F)
    (a b : Fin 2) : ((1 : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) a b ∈ S := by
  rw [Units.val_one, Matrix.one_apply]
  split_ifs
  · exact one_mem S
  · exact zero_mem S

/-- Every element of the subgroup generated by `s` has its entries, and those of its inverse, in
the algebra generated by `entrySet s`. -/
theorem entries_mem_of_mem_closure {R F : Type*} [CommRing R] [Field F] [Algebra R F]
    {s : Set (GL (Fin 2) F)} {h : GL (Fin 2) F} (hh : h ∈ Subgroup.closure s) (a b : Fin 2) :
    ((h : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) a b ∈ Algebra.adjoin R (entrySet s) ∧
      ((h⁻¹ : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) a b ∈ Algebra.adjoin R (entrySet s) := by
  induction hh using Subgroup.closure_induction generalizing a b with
  | mem g hg =>
    exact ⟨Algebra.subset_adjoin (mem_entrySet hg a b).1,
      Algebra.subset_adjoin (mem_entrySet hg a b).2⟩
  | one =>
    refine ⟨one_entry_mem _ a b, ?_⟩
    rw [inv_one]
    exact one_entry_mem _ a b
  | mul x y _ _ hx hy =>
    refine ⟨?_, ?_⟩
    · rw [Units.val_mul, Matrix.mul_apply]
      exact sum_mem fun c _ ↦ mul_mem (hx a c).1 (hy c b).1
    · rw [mul_inv_rev, Units.val_mul, Matrix.mul_apply]
      exact sum_mem fun c _ ↦ mul_mem (hy a c).2 (hx c b).2
  | inv x _ hx =>
    refine ⟨(hx a b).2, ?_⟩
    rw [inv_inv]
    exact (hx a b).1

theorem glMap_injective {R S : Type*} [CommRing R] [CommRing S] {f : R →+* S}
    (hf : Function.Injective f) :
    Function.Injective (Matrix.GeneralLinearGroup.map (n := Fin 2) f) := by
  intro x y hxy
  refine Units.ext (Matrix.ext fun a b ↦ hf ?_)
  exact congrArg (fun z : GL (Fin 2) S ↦ (z : Matrix (Fin 2) (Fin 2) S) a b) hxy

/-- A matrix whose entries and inverse entries come from a subring comes from that subring. -/
theorem mem_range_glMap_of_entries {R S : Type*} [CommRing R] [CommRing S] (f : R →+* S)
    (hf : Function.Injective f) (g : GL (Fin 2) S)
    (hg : ∀ a b, ∃ r, f r = ((g : GL (Fin 2) S) : Matrix (Fin 2) (Fin 2) S) a b)
    (hg' : ∀ a b, ∃ r, f r = ((g⁻¹ : GL (Fin 2) S) : Matrix (Fin 2) (Fin 2) S) a b) :
    g ∈ (Matrix.GeneralLinearGroup.map (n := Fin 2) f).range := by
  choose M hM using hg
  choose N hN using hg'
  have hM' : (Matrix.of M).map f = ((g : GL (Fin 2) S) : Matrix (Fin 2) (Fin 2) S) :=
    Matrix.ext fun a b ↦ hM a b
  have hN' : (Matrix.of N).map f = ((g⁻¹ : GL (Fin 2) S) : Matrix (Fin 2) (Fin 2) S) :=
    Matrix.ext fun a b ↦ hN a b
  have hMN : Matrix.of M * Matrix.of N = 1 := by
    refine Matrix.map_injective hf ?_
    show (Matrix.of M * Matrix.of N).map f = (1 : Matrix (Fin 2) (Fin 2) R).map f
    rw [Matrix.map_mul, Matrix.map_one f (map_zero f) (map_one f), hM', hN', Units.mul_inv]
  have hNM : Matrix.of N * Matrix.of M = 1 := by
    refine Matrix.map_injective hf ?_
    show (Matrix.of N * Matrix.of M).map f = (1 : Matrix (Fin 2) (Fin 2) R).map f
    rw [Matrix.map_mul, Matrix.map_one f (map_zero f) (map_one f), hM', hN', Units.inv_mul]
  refine MonoidHom.mem_range.mpr
    ⟨⟨Matrix.of M, Matrix.of N, hMN, hNM⟩, Units.ext (Matrix.ext fun a b ↦ ?_)⟩
  exact hM a b

/-- **Finitely generated subgroups in positive characteristic.** -/
theorem hasHaagerupProperty_closure_of_charP {F : Type} [Field F] (p : ℕ) [Fact p.Prime]
    [CharP F p] (s : Set (GL (Fin 2) F)) (hs : s.Finite) :
    HasHaagerupProperty.{0, 0} (Subgroup.closure s) := by
  classical
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  letI : Algebra (ZMod p) F := ZMod.algebra F p
  -- the finitely generated algebra of entries and its Noether normalization
  let A : Subalgebra (ZMod p) F := Algebra.adjoin (ZMod p) (entrySet s)
  haveI : Algebra.FiniteType (ZMod p) A :=
    Algebra.FiniteType.adjoin_of_finite (R := ZMod p) (entrySet_finite hs)
  obtain ⟨d, g₀, hg₀, hg₀int⟩ := exists_integral_inj_algHom_of_fg (ZMod p) A
  let B := MvPolynomial (Fin d) (ZMod p)
  let ι : B →+* F := A.val.toRingHom.comp g₀.toRingHom
  have hι : Function.Injective ι := by
    intro x y hxy
    apply hg₀
    apply Subtype.val_injective
    exact hxy
  letI : Algebra B F := ι.toAlgebra
  have hintA : ∀ t : A, IsIntegral B (t : F) := by
    intro t
    obtain ⟨q, hqm, hq⟩ := hg₀int t
    refine ⟨q, hqm, ?_⟩
    have h := Polynomial.hom_eval₂ (p := q) (f := g₀.toRingHom) (g := A.val.toRingHom) (x := t)
    rw [hq, map_zero] at h
    exact h.symm
  -- the field of fractions `L` of `B` and the finite extension `K = L(entries)`
  let L := FractionRing B
  letI : Algebra L F := (IsFractionRing.lift (K := L) hι).toAlgebra
  have hLF : ∀ b : B, algebraMap L F (algebraMap B L b) = ι b := fun b ↦
    IsFractionRing.lift_algebraMap (K := L) hι b
  have hcomp : (algebraMap L F).comp (algebraMap B L) = algebraMap B F := RingHom.ext hLF
  have hintL : ∀ x ∈ entrySet s, IsIntegral L x := by
    intro x hx
    obtain ⟨q, hqm, hq⟩ := hintA ⟨x, Algebra.subset_adjoin hx⟩
    refine ⟨q.map (algebraMap B L), hqm.map _, ?_⟩
    rw [Polynomial.eval₂_map, hcomp]
    exact hq
  let K : IntermediateField L F := IntermediateField.adjoin L (entrySet s)
  haveI : Finite (entrySet s) := (entrySet_finite hs).to_subtype
  haveI : FiniteDimensional L K := IntermediateField.finiteDimensional_adjoin hintL
  haveI : CharP L p :=
    (IsFractionRing.lift (K := L) hι).charP (IsFractionRing.lift (K := L) hι).injective p
  -- a separable intermediate field `K'` receiving `K` by an iterated Frobenius
  obtain ⟨K', e, φ, hsep, hφ⟩ := exists_separable_frobenius_embedding L K p
  haveI := hsep
  let ψ : K' →+* F := (K.val : K →+* F).comp (K'.val : K' →+* K)
  have hψcomp : ψ.comp ((algebraMap L K').comp (algebraMap B L)) = algebraMap B F := by
    refine RingHom.ext fun b ↦ ?_
    show algebraMap L F (algebraMap B L b) = ι b
    exact hLF b
  -- the subgroup inside `GL_2(K)`
  have hinjK : Function.Injective (Matrix.GeneralLinearGroup.map (n := Fin 2) (K.val : K →+* F)) :=
    glMap_injective (K.val : K →+* F).injective
  have hle : Subgroup.closure s ≤
      (Matrix.GeneralLinearGroup.map (n := Fin 2) (K.val : K →+* F)).range := by
    rw [Subgroup.closure_le]
    intro g hg
    exact mem_range_glMap_of_entries _ (K.val : K →+* F).injective g
      (fun a b ↦ ⟨⟨((g : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) a b,
        IntermediateField.subset_adjoin L _ (mem_entrySet hg a b).1⟩, rfl⟩)
      (fun a b ↦ ⟨⟨((g⁻¹ : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) a b,
        IntermediateField.subset_adjoin L _ (mem_entrySet hg a b).2⟩, rfl⟩)
  let ρ₁ : Subgroup.closure s →* GL (Fin 2) K :=
    (MonoidHom.ofInjective hinjK).symm.toMonoidHom.comp (Subgroup.inclusion hle)
  have hρ₁ : Function.Injective ρ₁ := by
    intro x y hxy
    have h2 : (MonoidHom.ofInjective hinjK).symm (Subgroup.inclusion hle x) =
        (MonoidHom.ofInjective hinjK).symm (Subgroup.inclusion hle y) := hxy
    exact Subgroup.inclusion_injective hle ((MonoidHom.ofInjective hinjK).symm.injective h2)
  have hρ₁entry : ∀ (γ : Subgroup.closure s) (a b : Fin 2),
      ((((ρ₁ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) a b : K) : F) =
        ((γ : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) a b := by
    intro γ a b
    have h1 : Matrix.GeneralLinearGroup.map (n := Fin 2) (K.val : K →+* F) (ρ₁ γ) =
        (γ : GL (Fin 2) F) := by
      rw [← MonoidHom.ofInjective_apply hinjK]
      exact congrArg Subtype.val
        (MulEquiv.apply_symm_apply (MonoidHom.ofInjective hinjK) (Subgroup.inclusion hle γ))
    exact congrArg (fun z : GL (Fin 2) F ↦ (z : Matrix (Fin 2) (Fin 2) F) a b) h1
  -- the representation in `GL_2(K')`
  let ρ : Subgroup.closure s →* GL (Fin 2) K' :=
    (Matrix.GeneralLinearGroup.map (n := Fin 2) φ).comp ρ₁
  have hρ : Function.Injective ρ := by
    intro x y hxy
    have h2 : Matrix.GeneralLinearGroup.map (n := Fin 2) φ (ρ₁ x) =
        Matrix.GeneralLinearGroup.map (n := Fin 2) φ (ρ₁ y) := hxy
    exact hρ₁ (glMap_injective φ.injective h2)
  have hψ : ∀ (γ : Subgroup.closure s) (a b : Fin 2),
      ψ (((ρ γ : GL (Fin 2) K') : Matrix (Fin 2) (Fin 2) K') a b) =
        ((γ : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) a b ^ p ^ e := by
    intro γ a b
    show (((φ (((ρ₁ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) a b) : K') : K) : F) = _
    rw [hφ, IntermediateField.coe_pow, hρ₁entry]
  have hint : ∀ (γ : Subgroup.closure s) (a b : Fin 2),
      ((algebraMap L K').comp (algebraMap B L)).IsIntegralElem
        (((ρ γ : GL (Fin 2) K') : Matrix (Fin 2) (Fin 2) K') a b) := by
    intro γ a b
    obtain ⟨q, hqm, hq⟩ :=
      (show IsIntegral B (((γ : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) a b) from
        hintA ⟨_, (entries_mem_of_mem_closure (R := ZMod p) γ.2 a b).1⟩).pow (p ^ e)
    refine ⟨q, hqm, ψ.injective ?_⟩
    rw [Polynomial.hom_eval₂, map_zero, hψcomp, hψ γ a b]
    exact hq
  exact hasHaagerupProperty_of_isIntegral (k := ZMod p) (d := d) (K := ↥K') ρ hρ hint

/-- `non_mf_groups_exist.tex`, tex lines 1146--1147, over a field of prime characteristic. -/
def PrintedGHWTheoremFourCharP : Prop :=
  ∀ (F : Type) [Field F] (p : ℕ) [Fact p.Prime] [CharP F p] (Γ : Subgroup (GL (Fin 2) F)),
    Countable Γ → HasHaagerupProperty.{0, 0} Γ

/-- **GHW Theorem 4 in prime characteristic.** -/
theorem printedGHWTheoremFourCharP : PrintedGHWTheoremFourCharP := by
  intro F _ p _ _ Γ _
  exact hasHaagerupProperty_of_closure_finite Γ fun t ht ↦
    hasHaagerupProperty_closure_of_charP p t ht

end GHW
end GroupApproximation

#audit_axioms GroupApproximation.GHW.exists_places_bounded_integral
#audit_axioms GroupApproximation.GHW.hasHaagerupProperty_of_isIntegral
#audit_axioms GroupApproximation.GHW.entrySet_finite
#audit_axioms GroupApproximation.GHW.mem_entrySet
#audit_axioms GroupApproximation.GHW.one_entry_mem
#audit_axioms GroupApproximation.GHW.entries_mem_of_mem_closure
#audit_axioms GroupApproximation.GHW.glMap_injective
#audit_axioms GroupApproximation.GHW.mem_range_glMap_of_entries
#audit_axioms GroupApproximation.GHW.hasHaagerupProperty_closure_of_charP
#audit_closed_axioms GroupApproximation.GHW.printedGHWTheoremFourCharP
