import GroupApproximation.Kazhdan.GHWCharP
import GroupApproximation.Kazhdan.GHWTheoremFour
import GroupApproximation.Meta.AxiomGuard

/-!
# GHW Theorem 4 in prime characteristic, closed

`non_mf_groups_exist.tex`, the remark after `prop:torsion-defect-ring` (tex lines 1146--1147):

> Every countable subgroup of `GL_2` over a field has the Haagerup property~[GHW, Theorem 4], …

`GHWTheoremFour` reduces the sentence to its finitely generated cases in prime characteristic
(`GHWFinitelyGeneratedCharP`) and in characteristic zero.  `GHWCharP` proves the prime
characteristic case (`hasHaagerupProperty_closure_of_charP`), so `ghwFinitelyGeneratedCharP` is
that case, closed, at the proposition the reduction consumes.
-/

namespace GroupApproximation
namespace GHW

/-- **GHW Theorem 4, finitely generated subgroups in prime characteristic**, closed.  Over a field
`F` of prime characteristic `p`, every subgroup of `GL_2(F)` generated by a finite set has the
Haagerup property. -/
theorem ghwFinitelyGeneratedCharP : GHWFinitelyGeneratedCharP := by
  intro F _ p _ _ s hs
  exact hasHaagerupProperty_closure_of_charP p s hs

end GHW
end GroupApproximation

#audit_closed_axioms GroupApproximation.GHW.ghwFinitelyGeneratedCharP
