import GroupApproximation.Kazhdan.GHWPlaces
import GroupApproximation.Meta.AxiomGuard

/-!
# GHW Theorem 4: reduction to finitely generated subgroups

`non_mf_groups_exist.tex`, the remark after `prop:torsion-defect-ring` (tex lines 1146--1147):

> Every countable subgroup of `GL_2` over a field has the Haagerup property …

A countable group is the increasing union of the subgroups generated by its finite subsets
(`hasHaagerupProperty_of_closure_finset`).  For a countable subgroup `Γ ≤ G` and a finite
`s ⊆ Γ`, the subgroup of `Γ` generated by `s` embeds into the subgroup of `G` generated by the
image of `s`.  So if every subgroup of `G` generated by a finite set has the Haagerup property,
then so does `Γ` (`hasHaagerupProperty_of_closure_finite`).
-/

namespace GroupApproximation
namespace GHW

open Haagerup

/-- **Finitely generated subgroups suffice.** -/
theorem hasHaagerupProperty_of_closure_finite {G : Type} [Group G] (Γ : Subgroup G) [Countable Γ]
    (h : ∀ t : Set G, t.Finite → HasHaagerupProperty.{0, 0} (Subgroup.closure t)) :
    HasHaagerupProperty.{0, 0} Γ := by
  refine hasHaagerupProperty_of_closure_finset fun s ↦ ?_
  have hmem : ∀ x : Subgroup.closure (s : Set Γ),
      Γ.subtype.comp (Subgroup.closure (s : Set Γ)).subtype x ∈
        Subgroup.closure (Γ.subtype '' (s : Set Γ)) := by
    intro x
    rw [← Subgroup.map_closure]
    exact Subgroup.mem_map_of_mem _ x.2
  refine HasHaagerupProperty.comap (h (Γ.subtype '' (s : Set Γ)) (s.finite_toSet.image _))
    ((Γ.subtype.comp (Subgroup.closure (s : Set Γ)).subtype).codRestrict _ hmem) ?_
  intro x y hxy
  apply Subtype.val_injective
  apply Subtype.val_injective
  exact congrArg Subtype.val hxy

end GHW
end GroupApproximation

#audit_axioms GroupApproximation.GHW.hasHaagerupProperty_of_closure_finite
