import GroupApproximation.Kazhdan.HaagerupAffineSums
import GroupApproximation.Kazhdan.HaagerupUnion
import GroupApproximation.Kazhdan.BruhatTitsTwoTree
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.Complex.Basic
import GroupApproximation.Meta.AxiomGuard

/-!
# The Guentner--Higson--Weinberger assembly over finitely many places

`non_mf_groups_exist.tex`, the remark after `prop:torsion-defect-ring` (tex lines 1146--1147):

> Every countable subgroup of `GL_2` over a field has the Haagerup property …

This module is the assembly step of that theorem.  Let `ρ : Γ →* GL_2(K)` be injective, with all
matrix entries in a set `S ⊆ K`.  Suppose given

* finitely many additive discrete valuations `v_j` of `K`, each with a uniformizer;
* finitely many ring homomorphisms `σ_i : K →+* ℂ`, each with an affine action `A_i` of `Γ`
  dominating the entries, `|σ_i(g_ab)|² ≤ 2 |σ_i(det g)| exp ‖b_i γ‖²` (the archimedean input);
* the finiteness of `{a ∈ S : |σ_i a| ≤ C for all i, v_j a ≥ -N for all j}` for all `C, N`.

Then `Γ` has the Haagerup property (`hasHaagerupProperty_of_places`): the `ℓ²`-sum of the tree
actions at the `v_j`, the translations by the determinant valuations at the `v_j`, the actions
`A_i`, and the translations by `log |σ_i(det)|` is proper.  Bounded translation parts bound the
displacement on each tree and the determinant at each place, so every entry has valuation at
least `-N` at every `v_j` and absolute value at most `C` at every `σ_i`.

Finitely generated subgroups suffice (`hasHaagerupProperty_of_closure_finset`): a countable group
is the increasing union of the subgroups generated by the first `n` elements of an enumeration.
-/

namespace GroupApproximation
namespace GHW

open ValuedMatrixTwo Haagerup

universe u

/-! ## Translations of the real line -/

/-- The translation action on the real line of a homomorphism to `ℝ`. -/
noncomputable def realAction {G : Type u} [Group G] (f : G →* Multiplicative ℝ) :
    AffineAction.{u, 0} G where
  E := ℝ
  π := 1
  b g := Multiplicative.toAdd (f g)
  isCocycle g h := by
    show Multiplicative.toAdd (f (g * h)) =
      Multiplicative.toAdd (f g) + Multiplicative.toAdd (f h)
    rw [map_mul, toAdd_mul]

theorem norm_realAction_b {G : Type u} [Group G] (f : G →* Multiplicative ℝ) (g : G) :
    ‖(realAction f).b g‖ = |Multiplicative.toAdd (f g)| :=
  Real.norm_eq_abs _

section Places

variable {K : Type} [Field K] {Γ : Type} [Group Γ] (ρ : Γ →* GL (Fin 2) K)

/-! ## A non-archimedean place -/

section NonArchimedean

variable (v : AddValuation K (WithTop ℤ)) {π : K} (hπ : v π = 1)

/-- `Γ` acting on the Bruhat--Tits tree of `v` through `ρ`. -/
noncomputable def valTreeAction : AffineAction.{0, 0} Γ := by
  letI : MulAction Γ (Vertex v) := MulAction.compHom _ ρ
  exact treeAction (btGraph_isTree v hπ) (fun γ x y ↦ btGraph_isGraphAction v (ρ γ) x y)
    (QuotientGroup.mk 1 : Vertex v)

/-- The displacement on the tree is at most the squared translation part. -/
theorem dispInt_le_norm_sq_valTreeAction (γ : Γ) :
    (dispInt v (ρ γ) : ℝ) ≤ ‖(valTreeAction ρ v hπ).b γ‖ ^ 2 := by
  letI : MulAction Γ (Vertex v) := MulAction.compHom _ ρ
  have h1 := dist_le_norm_sq_treeAction (btGraph_isTree v hπ)
    (fun γ x y ↦ btGraph_isGraphAction v (ρ γ) x y) (QuotientGroup.mk 1 : Vertex v) γ
  have hsmul : γ • (QuotientGroup.mk 1 : Vertex v) = QuotientGroup.mk (ρ γ) := by
    show ρ γ • (QuotientGroup.mk 1 : Vertex v) = _
    rw [MulAction.Quotient.smul_mk, smul_eq_mul, mul_one]
  have h2 := LevelTree.level_le_add_dist (level v) (fun _ _ h ↦ level_adj v h)
    (btGraph_connected v hπ) (QuotientGroup.mk 1 : Vertex v) (QuotientGroup.mk (ρ γ))
  rw [level_mk, level_mk, dispInt_one, Int.toNat_zero, zero_add] at h2
  have hnn := dispInt_nonneg v (ρ γ)
  have h3 : (dispInt v (ρ γ) : ℝ) ≤
      ((btGraph v).dist (QuotientGroup.mk 1) (γ • (QuotientGroup.mk 1 : Vertex v)) : ℕ) := by
    rw [hsmul]
    have h4 : dispInt v (ρ γ) ≤
        ((btGraph v).dist (QuotientGroup.mk 1) (QuotientGroup.mk (ρ γ)) : ℤ) := by
      omega
    exact_mod_cast h4
  exact h3.trans h1

/-- The valuation of the determinant at `v`, as a homomorphism to `ℤ`. -/
noncomputable def detValHom : Γ →* Multiplicative ℤ where
  toFun γ := Multiplicative.ofAdd (vz v ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K).det)
  map_one' := by
    rw [map_one, Units.val_one, Matrix.det_one, vz_one, ofAdd_zero]
  map_mul' g h := by
    rw [map_mul, vz_det_mul, ofAdd_add]

include hπ in
/-- Bounded translation parts at `v` bound the valuations of the entries from below. -/
theorem neg_le_vz_entry_of_bounds {γ : Γ} {R : ℝ} {N : ℕ} (hRN : R ^ 2 ≤ N ∧ R ≤ N)
    (htree : ‖(valTreeAction ρ v hπ).b γ‖ ≤ R) (hdetb : ‖(intAction (detValHom ρ v)).b γ‖ ≤ R)
    (i j : Fin 2) (hij : ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) i j ≠ 0) :
    -(N : ℤ) ≤ vz v (((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) i j) := by
  have hd : (dispInt v (ρ γ) : ℝ) ≤ N :=
    (dispInt_le_norm_sq_valTreeAction ρ v hπ γ).trans
      ((pow_le_pow_left₀ (norm_nonneg _) htree 2).trans hRN.1)
  have hd' : dispInt v (ρ γ) ≤ N := by exact_mod_cast hd
  have habs := (norm_intAction_b (detValHom ρ v) γ).symm.trans_le hdetb
  have hdetR : -(N : ℝ) ≤ ((Multiplicative.toAdd (detValHom ρ v γ) : ℤ) : ℝ) := by
    linarith [(abs_le.mp habs).1, hRN.2]
  have hdet : -(N : ℤ) ≤ vz v ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K).det := by
    exact_mod_cast hdetR
  have hmin := entriesGe_entryMin v (ρ γ) i j hij
  unfold dispInt at hd'
  omega

end NonArchimedean

/-! ## An archimedean place -/

section Archimedean

variable (σ : K →+* ℂ)

theorem sigma_det_ne_zero (γ : Γ) :
    σ ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K).det ≠ 0 :=
  (map_ne_zero σ).mpr (det_ne_zero (ρ γ))

/-- `log |σ(det)|`, as a homomorphism to `ℝ`. -/
noncomputable def logDetHom : Γ →* Multiplicative ℝ where
  toFun γ := Multiplicative.ofAdd
    (Real.log ‖σ ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K).det‖)
  map_one' := by
    rw [map_one, Units.val_one, Matrix.det_one, map_one, norm_one, Real.log_one, ofAdd_zero]
  map_mul' g h := by
    rw [map_mul, Units.val_mul, Matrix.det_mul, map_mul, norm_mul,
      Real.log_mul (norm_ne_zero_iff.mpr (sigma_det_ne_zero ρ σ g))
        (norm_ne_zero_iff.mpr (sigma_det_ne_zero ρ σ h)), ofAdd_add]

/-- Bounded translation parts at `σ` bound the entries. -/
theorem norm_sigma_entry_le_of_bounds (A : AffineAction.{0, 0} Γ)
    (hA : ∀ (γ : Γ) (a b : Fin 2),
      ‖σ (((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) a b)‖ ^ 2 ≤
        2 * ‖σ ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K).det‖ * Real.exp (‖A.b γ‖ ^ 2))
    {γ : Γ} {R : ℝ} (h1 : ‖A.b γ‖ ≤ R) (h2 : ‖(realAction (logDetHom ρ σ)).b γ‖ ≤ R)
    (a b : Fin 2) :
    ‖σ (((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) a b)‖ ≤
      max 1 (2 * Real.exp R * Real.exp (R ^ 2)) := by
  have hpos : 0 < ‖σ ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K).det‖ :=
    norm_pos_iff.mpr (sigma_det_ne_zero ρ σ γ)
  have h2' : |Real.log ‖σ ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K).det‖| ≤ R := by
    have e := norm_realAction_b (logDetHom ρ σ) γ
    rw [e] at h2
    exact h2
  have hdet : ‖σ ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K).det‖ ≤ Real.exp R := by
    calc ‖σ ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K).det‖
        = Real.exp (Real.log ‖σ ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K).det‖) :=
          (Real.exp_log hpos).symm
      _ ≤ Real.exp R := Real.exp_le_exp.mpr ((le_abs_self _).trans h2')
  have hexp : Real.exp (‖A.b γ‖ ^ 2) ≤ Real.exp (R ^ 2) :=
    Real.exp_le_exp.mpr (pow_le_pow_left₀ (norm_nonneg _) h1 2)
  have hbound : ‖σ (((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) a b)‖ ^ 2 ≤
      2 * Real.exp R * Real.exp (R ^ 2) := by
    refine (hA γ a b).trans ?_
    have e1 := Real.exp_pos (‖A.b γ‖ ^ 2)
    have e2 := Real.exp_pos R
    nlinarith [mul_le_mul hdet hexp e1.le e2.le]
  rcases le_or_gt ‖σ (((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) a b)‖ 1 with h | h
  · exact h.trans (le_max_left _ _)
  · refine le_trans ?_ (le_max_right _ _)
    nlinarith

end Archimedean

/-! ## The assembly -/

/-- **The GHW assembly over finitely many places.** -/
theorem hasHaagerupProperty_of_places (hρ : Function.Injective ρ) {k m : ℕ}
    (v : Fin k → AddValuation K (WithTop ℤ)) (π : Fin k → K) (hπ : ∀ j, v j (π j) = 1)
    (σ : Fin m → (K →+* ℂ)) (A : Fin m → AffineAction.{0, 0} Γ)
    (hA : ∀ (i : Fin m) (γ : Γ) (a b : Fin 2),
      ‖σ i (((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) a b)‖ ^ 2 ≤
        2 * ‖σ i ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K).det‖ *
          Real.exp (‖(A i).b γ‖ ^ 2))
    (S : Set K) (hS : ∀ (γ : Γ) (a b : Fin 2), ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) a b ∈ S)
    (hfin : ∀ (C : ℝ) (N : ℕ), {a : K | a ∈ S ∧ (∀ i, ‖σ i a‖ ≤ C) ∧
      ∀ j, (((-(N : ℤ)) : ℤ) : WithTop ℤ) ≤ v j a}.Finite) :
    HasHaagerupProperty.{0, 0} Γ := by
  classical
  let fam : (Fin k ⊕ Fin k) ⊕ (Fin m ⊕ Fin m) → AffineAction.{0, 0} Γ :=
    Sum.elim (Sum.elim (fun j ↦ valTreeAction ρ (v j) (hπ j)) fun j ↦ intAction (detValHom ρ (v j)))
      (Sum.elim A fun i ↦ realAction (logDetHom ρ (σ i)))
  refine hasHaagerupProperty_of_finite_sum fam fun R ↦ ?_
  obtain ⟨N, hN⟩ := exists_nat_gt (R ^ 2 + R)
  let F : Set K := {a : K | a ∈ S ∧ (∀ i, ‖σ i a‖ ≤ max 1 (2 * Real.exp R * Real.exp (R ^ 2))) ∧
    ∀ j, (((-(N : ℤ)) : ℤ) : WithTop ℤ) ≤ v j a}
  haveI : Finite F := (hfin _ N).to_subtype
  have hmem : ∀ γ : Γ, (∀ idx, ‖(fam idx).b γ‖ ≤ R) →
      ∀ a b : Fin 2, ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) a b ∈ F := by
    intro γ hγ a b
    refine Set.mem_setOf.mpr ⟨hS γ a b, fun i ↦ ?_, fun j ↦ ?_⟩
    · exact norm_sigma_entry_le_of_bounds ρ (σ i) (A i) (hA i) (hγ (Sum.inr (Sum.inl i)))
        (hγ (Sum.inr (Sum.inr i))) a b
    · have ht : ‖(valTreeAction ρ (v j) (hπ j)).b γ‖ ≤ R := hγ (Sum.inl (Sum.inl j))
      have hd : ‖(intAction (detValHom ρ (v j))).b γ‖ ≤ R := hγ (Sum.inl (Sum.inr j))
      have hR0 : 0 ≤ R := (norm_nonneg _).trans ht
      have hRN : R ^ 2 ≤ N ∧ R ≤ N := ⟨by nlinarith, by nlinarith⟩
      by_cases hab : ((ρ γ : GL (Fin 2) K) : Matrix (Fin 2) (Fin 2) K) a b = 0
      · rw [hab, AddValuation.map_zero]
        exact le_top
      · have h := neg_le_vz_entry_of_bounds ρ (v j) (hπ j) hRN ht hd a b hab
        rw [← coe_vz (v j) hab]
        exact WithTop.coe_le_coe.mpr h
  have hfinSet : Finite {γ : Γ | ∀ idx, ‖(fam idx).b γ‖ ≤ R} := by
    refine Finite.of_injective (fun γ ↦ fun a b : Fin 2 ↦ (⟨_, hmem γ.1 γ.2 a b⟩ : F)) ?_
    intro γ δ h
    apply Subtype.ext
    apply hρ
    refine Matrix.GeneralLinearGroup.ext fun a b ↦ ?_
    exact congrArg Subtype.val (congrFun (congrFun h a) b)
  exact Set.finite_coe_iff.mp hfinSet

end Places

/-! ## Finitely generated subgroups suffice -/

/-- **Finitely generated subgroups suffice.**  A countable group all of whose finitely generated
subgroups have the Haagerup property has the Haagerup property. -/
theorem hasHaagerupProperty_of_closure_finset {G : Type} [Group G] [Countable G]
    (h : ∀ s : Finset G, HasHaagerupProperty.{0, 0} (Subgroup.closure (s : Set G))) :
    HasHaagerupProperty.{0, 0} G := by
  classical
  obtain ⟨e, he⟩ := exists_surjective_nat G
  let Γ : ℕ → Subgroup G := fun n ↦ Subgroup.closure (((Finset.range (n + 1)).image e : Finset G) : Set G)
  have hmono : Monotone Γ := by
    intro a b hab
    refine Subgroup.closure_mono ?_
    intro x hx
    simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe, Finset.mem_range] at hx ⊢
    obtain ⟨i, hi, rfl⟩ := hx
    exact ⟨i, by omega, rfl⟩
  have hcover : ∀ g : G, ∃ n, g ∈ Γ n := by
    intro g
    obtain ⟨i, rfl⟩ := he g
    exact ⟨i, Subgroup.subset_closure (Finset.mem_coe.mpr
      (Finset.mem_image.mpr ⟨i, Finset.mem_range.mpr (Nat.lt_succ_self i), rfl⟩))⟩
  exact hasHaagerupProperty_of_iUnion Γ hmono hcover fun n ↦ h _

end GHW
end GroupApproximation

#audit_axioms GroupApproximation.GHW.hasHaagerupProperty_of_places
#audit_axioms GroupApproximation.GHW.hasHaagerupProperty_of_closure_finset
