import GroupApproximation.Manuscript.NonMFNotes.Full.TWWUCT.HKTAffineAction
import Mathlib.Analysis.CStarAlgebra.Classes
import Mathlib.Analysis.InnerProductSpace.Projection.Basic
import Mathlib.Algebra.Star.Subalgebra

/-!
# Covariant Clifford systems and the geometry of finite-dimensional affine subspaces

Lane TWWUCT-C (WO-TWWUCT-C).  Higson--Kasparov--Trout (Adv. Math. 135 (1998), §2--§4) build
`A(H)` out of the Clifford algebras `Cliff(V)` of finite-dimensional subspaces `V ⊆ H`.  We use
one ambient C⋆-algebra `C` which contains a *Clifford variable* for `ℝ ⊕ H`: a real-linear
self-adjoint map `c : ℝ × H → C` with `c(t, h)² = (t² + ‖h‖²)·1`.  The extra coordinate `ℝ`
is the odd generator `ε` which realises the graded tensor product `𝒮 ⊗̂ -`: the odd function
`x ↦ x e^{-x²}` of the unbounded multiplier `X ⊗̂ 1 + 1 ⊗̂ C_W` becomes
`(t, w) ↦ e^{-(t² + ‖w‖²)} c(t, w)` (HKT 1998, Def. 3.1 and §4).  The orthogonal group of `H`
acts on `C` compatibly with `c` (second quantisation), and `C` is graded with `c` odd.

This file supplies the interface and the elementary geometry.

* `CliffordSystem H C`: the covariant, graded Clifford variable.
* `CliffordSystem.cliffordSub V`: the C⋆-algebra `Cliff(V) ⊆ C` generated by `c(0, V)`.
* `FinDimAffine H`: a finite-dimensional affine subspace `a + V` of `H`.
* `FinDimAffine.foot`, `FinDimAffine.perp`, `FinDimAffine.radiusSq`: for `h ∈ H`, the foot
  `P_V(h - a) ∈ V`, the perpendicular part `(h - a) - P_V(h - a) ∈ V⊥` and
  `t² + ‖perp h‖²`, with continuity.
* `exp_neg_mul_le_one`: `e^{-(t² + u²)} (|t| + u) ≤ 1`, the bound behind the odd generator.
-/

namespace GroupApproximation.Full.TWWUCT

noncomputable section

universe v w

/-- A **covariant graded Clifford system** for a real Hilbert space `H` in a unital C⋆-algebra
`C`: a continuous real-linear self-adjoint map `c : ℝ × H → C` with `c(x)² = ‖x‖²·1`, a
compatible action of the orthogonal group of `H`, and a grading for which `c` is odd
(HKT 1998, §2; the ambient CAR algebra of `ℝ ⊕ H`). -/
class CliffordSystem (H : Type v) [NormedAddCommGroup H] [InnerProductSpace ℝ H]
    (C : Type w) [CStarAlgebra C] where
  /-- The Clifford variable; the first coordinate is the extra odd generator `ε`. -/
  clifford : ℝ × H → C
  clifford_add : ∀ x y : ℝ × H, clifford (x + y) = clifford x + clifford y
  clifford_smul : ∀ (r : ℝ) (x : ℝ × H), clifford (r • x) = (r : ℂ) • clifford x
  star_clifford : ∀ x : ℝ × H, star (clifford x) = clifford x
  clifford_mul_self :
    ∀ x : ℝ × H, clifford x * clifford x = ((x.1 ^ 2 + ‖x.2‖ ^ 2 : ℝ) : ℂ) • (1 : C)
  continuous_clifford : Continuous clifford
  norm_clifford_le : ∀ x : ℝ × H, ‖clifford x‖ ≤ |x.1| + ‖x.2‖
  /-- Second quantisation of orthogonal transformations. -/
  orth : (H ≃ₗᵢ[ℝ] H) → (C ≃⋆ₐ[ℂ] C)
  orth_one : ∀ a : C, orth 1 a = a
  orth_mul : ∀ (U V : H ≃ₗᵢ[ℝ] H) (a : C), orth (U * V) a = orth U (orth V a)
  orth_clifford : ∀ (U : H ≃ₗᵢ[ℝ] H) (x : ℝ × H), orth U (clifford x) = clifford (x.1, U x.2)
  /-- The grading automorphism. -/
  grading : C ≃⋆ₐ[ℂ] C
  grading_grading : ∀ a : C, grading (grading a) = a
  grading_clifford : ∀ x : ℝ × H, grading (clifford x) = -clifford x
  grading_orth : ∀ (U : H ≃ₗᵢ[ℝ] H) (a : C), grading (orth U a) = orth U (grading a)

namespace CliffordSystem

variable {H : Type v} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
variable {C : Type w} [CStarAlgebra C] [CliffordSystem H C]

variable (H) in
/-- The Clifford algebra `Cliff(V) ⊆ C` of a subspace `V ⊆ H`: the unital ⋆-subalgebra generated
by the Clifford variables `c(0, v)`, `v ∈ V`. -/
def cliffordSub (V : Submodule ℝ H) : StarSubalgebra ℂ C :=
  StarAlgebra.adjoin ℂ (Set.range fun v : V => (clifford ((0 : ℝ), (v : H)) : C))

theorem clifford_mem_cliffordSub (V : Submodule ℝ H) (v : V) :
    (clifford ((0 : ℝ), (v : H)) : C) ∈ cliffordSub (C := C) H V :=
  StarAlgebra.subset_adjoin ℂ _ ⟨v, rfl⟩

end CliffordSystem

/-- A finite-dimensional affine subspace `base + dir` of a real Hilbert space. -/
structure FinDimAffine (H : Type v) [NormedAddCommGroup H] [InnerProductSpace ℝ H] where
  /-- A base point. -/
  base : H
  /-- The direction. -/
  dir : Submodule ℝ H
  finiteDimensional : FiniteDimensional ℝ dir
  hasOrthogonalProjection : dir.HasOrthogonalProjection

attribute [instance] FinDimAffine.finiteDimensional FinDimAffine.hasOrthogonalProjection

namespace FinDimAffine

variable {H : Type v} [NormedAddCommGroup H] [InnerProductSpace ℝ H] (E : FinDimAffine H)

/-- The foot `P_V(h - a) ∈ V` of `h` on `E = a + V`, in coordinates centred at `a`. -/
def foot (h : H) : E.dir :=
  E.dir.orthogonalProjectionOnto (h - E.base)

/-- The perpendicular part `(h - a) - P_V(h - a) ∈ V⊥` of `h` relative to `E = a + V`. -/
def perp (h : H) : H :=
  (h - E.base) - E.dir.starProjection (h - E.base)

/-- `t² + ‖perp h‖²`: the square of the radial variable of the odd generator. -/
def radiusSq (x : ℝ × H) : ℝ :=
  x.1 ^ 2 + ‖E.perp x.2‖ ^ 2

theorem continuous_sub_base : Continuous fun h : H => h - E.base :=
  continuous_id.sub continuous_const

theorem continuous_foot : Continuous E.foot :=
  E.dir.orthogonalProjectionOnto.continuous.comp E.continuous_sub_base

theorem continuous_perp : Continuous E.perp :=
  E.continuous_sub_base.sub (E.dir.starProjection.continuous.comp E.continuous_sub_base)

theorem continuous_radiusSq : Continuous E.radiusSq :=
  (continuous_fst.pow 2).add ((continuous_norm.comp (E.continuous_perp.comp continuous_snd)).pow 2)

theorem perp_mem_orthogonal (h : H) : E.perp h ∈ E.dirᗮ :=
  Submodule.sub_starProjection_mem_orthogonal (K := E.dir) (h - E.base)

end FinDimAffine

/-- The elementary bound `e^{-(t² + u²)} (|t| + u) ≤ 1`. -/
theorem exp_neg_mul_le_one (t u : ℝ) :
    Real.exp (-(t ^ 2 + u ^ 2)) * (|t| + u) ≤ 1 := by
  have h1 : |t| + u ≤ t ^ 2 + u ^ 2 + 1 := by
    nlinarith [sq_nonneg (|t| - 1 / 2), sq_nonneg (u - 1 / 2), sq_abs t]
  have h2 : t ^ 2 + u ^ 2 + 1 ≤ Real.exp (t ^ 2 + u ^ 2) := Real.add_one_le_exp _
  have h3 : 0 < Real.exp (-(t ^ 2 + u ^ 2)) := Real.exp_pos _
  calc Real.exp (-(t ^ 2 + u ^ 2)) * (|t| + u)
      ≤ Real.exp (-(t ^ 2 + u ^ 2)) * Real.exp (t ^ 2 + u ^ 2) :=
        mul_le_mul_of_nonneg_left (h1.trans h2) h3.le
    _ = 1 := by rw [← Real.exp_add, neg_add_cancel, Real.exp_zero]

/-- `e^{-s} ≤ 1` for `s ≥ 0`, in the form used for the even generator. -/
theorem exp_neg_le_one {s : ℝ} (hs : 0 ≤ s) : Real.exp (-s) ≤ 1 :=
  Real.exp_le_one_iff.2 (neg_nonpos.2 hs)

end

end GroupApproximation.Full.TWWUCT
