name = "GroupApproximation"
version = "0.1.0"
defaultTargets = ["PalomarSTWProblemXXIIChallenge", "PalomarSTWProblemXXIISolution", "PalomarSTWProblemXXIIModelTests"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.0"

[[lean_lib]]
name = "GroupApproximation"
roots = ["GroupApproximation.PalomarBridges.XXII"]
globs = ["GroupApproximation.+"]
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_lib]]
name = "PalomarSTWProblemXXIIChallenge"
roots = ["Palomar.STWProblemXXIIChallenge"]

[[lean_lib]]
name = "PalomarSTWProblemXXIISolution"
roots = ["Palomar.STWProblemXXIISolution"]

[[lean_lib]]
name = "PalomarSTWProblemXXIIModelTests"
roots = ["Palomar.STWProblemXXIIModelTests"]
