import GroupApproximation.Manuscript.ChainCore.BilateralThreeZSentences
import GroupApproximation.Meta.AxiomGuard

/-!
# `prop:bilateral-three`: the cycle `r`, the compressor `W`, and the printed elements

`non_mf_groups_exist.tex`, proof of Proposition `prop:bilateral-three` (tex 1560–1575):

> (tex 1560) Let $r$ cycle the three negative levels $-1\mapsto-2\mapsto-3\mapsto-1$:
> \[ r=1-\sum_{j=1}^3 f_{-j,-j}+f_{-2,-1}+f_{-3,-2}+f_{-1,-3},
>    \qquad W=\operatorname{diag}(u,u,u)\operatorname{diag}(1,1,r). \]
> (tex 1566) The correction $r$ acts outside $P$ and centralizes $L$.  Thus $W$
> conjugates $L$ into $L$, sending a root coefficient $a\in S$ to
> $uau^{-1}=sat$.  On its third coordinate $W$ fixes the negative
> levels $-1$ and $-2$ individually.  Put
> \[ c=e_{13}(f_{-1,-2}),\ \ell=e_{21}(p),\ y=e_{32}(f_{-1,0}),\
>    z=1+E_{33}f_{-1,-2},\ B=\langle L,W,c,y\rangle. \]

Standing objects (tex 1550–1558): `X` a space with a homeomorphism `T`, `k` a finite field, a clopen
`P` with `T(P) ⊆ P`, `R_X = ClopenCrossedProduct T k`, the cell `bilateralCell T k hP hTP`
(`u` the implementing unit, `p = 1_P`, `f_{ab} = u^a d u^{-b}`), the printed coefficient ring
`S = cellRing T k hP hTP` (generated by `s`, `t`, `kp` in `pR_Xp`), its coefficient set
`bilateralCellSet T k hP hTP ⊆ R_X`, and `L = coreGroup (bilateralCellSet …)`, the image of
`EL_3(S)` under the corner embedding (`range_cornerEmbed`).  Coordinates are 0-indexed.

Proof route: everything is ring arithmetic with `f_{ab} f_{ce} = δ_{bc} f_{ae}` (`Cell.f_mul_f`),
plus `f_{c,e} a = a f_{c,e} = 0` for corner elements `a` and negative levels (`Cell.corner_mul_f`,
`Cell.f_mul_corner`), and `u a u⁻¹ = s a t` (`Cell.unit_conj_eq_s_mul_t`).

* `manuscriptSentence_bilateralThreeCycleR` (tex 1560)
* `manuscriptSentence_bilateralThreeRActsOutsidePCentralizesL` (tex 1566)
* `manuscriptSentence_bilateralThreeWConjugatesL` (tex 1566)
* `manuscriptSentence_bilateralThreeWFixesLevels` (tex 1566)
* `manuscriptSentence_bilateralThreePut` (tex 1566–1575)
-/

namespace GroupApproximation.Manuscript.NonMF.BilateralB

open GroupApproximation.BilateralThreeCell GroupApproximation.ClopenCrossedProduct
open GroupApproximation.Manuscript.ChainCore.BilateralThree
open scoped commutatorElement

/-! ## Cycle arithmetic for any cell -/

section Generic

variable {R : Type*} [Ring R] (C : Cell R)

/-- `r f_{-2,b} = f_{-3,b}`. -/
theorem r_mul_f_neg_two (b : ℤ) : C.r * C.f (-2) b = C.f (-3) b := by
  simp only [Cell.r, add_mul, sub_mul, one_mul, C.f_mul_f]
  norm_num

/-- `r f_{-3,b} = f_{-1,b}`. -/
theorem r_mul_f_neg_three (b : ℤ) : C.r * C.f (-3) b = C.f (-1) b := by
  simp only [Cell.r, add_mul, sub_mul, one_mul, C.f_mul_f]
  norm_num

/-- `f_{a,-2} r = f_{a,-1}`. -/
theorem f_neg_two_mul_r (a : ℤ) : C.f a (-2) * C.r = C.f a (-1) := by
  simp only [Cell.r, mul_add, mul_sub, mul_one, C.f_mul_f]
  norm_num

/-- `f_{a,-1} r⁻¹ = f_{a,-2}`. -/
theorem f_neg_one_mul_rInv (a : ℤ) : C.f a (-1) * C.rInv = C.f a (-2) := by
  simp only [Cell.rInv, mul_add, mul_sub, mul_one, C.f_mul_f]
  norm_num

/-- `f_{a,-2} r⁻¹ = f_{a,-3}`. -/
theorem f_neg_two_mul_rInv (a : ℤ) : C.f a (-2) * C.rInv = C.f a (-3) := by
  simp only [Cell.rInv, mul_add, mul_sub, mul_one, C.f_mul_f]
  norm_num

/-- `f_{a,-3} r⁻¹ = f_{a,-1}`. -/
theorem f_neg_three_mul_rInv (a : ℤ) : C.f a (-3) * C.rInv = C.f a (-1) := by
  simp only [Cell.rInv, mul_add, mul_sub, mul_one, C.f_mul_f]
  norm_num

/-- `r` moves the level `-1` to the level `-2`. -/
theorem r_conj_level_neg_one : C.r * C.f (-1) (-1) * C.rInv = C.f (-2) (-2) := by
  rw [C.r_mul_f_neg_one, f_neg_one_mul_rInv C]

/-- `r` moves the level `-2` to the level `-3`. -/
theorem r_conj_level_neg_two : C.r * C.f (-2) (-2) * C.rInv = C.f (-3) (-3) := by
  rw [r_mul_f_neg_two C, f_neg_two_mul_rInv C]

/-- `r` moves the level `-3` back to the level `-1`. -/
theorem r_conj_level_neg_three : C.r * C.f (-3) (-3) * C.rInv = C.f (-1) (-1) := by
  rw [r_mul_f_neg_three C, f_neg_three_mul_rInv C]

theorem p_mul_p_mul_p : C.p * C.p * C.p = C.p := by
  rw [C.p_mul_p, C.p_mul_p]

/-- `p (r - 1) = 0`: `r` is the identity on `P`. -/
theorem p_mul_r_sub_one : C.p * (C.r - 1) = 0 := by
  rw [mul_sub, mul_one, C.corner_mul_r (p_mul_p_mul_p C), sub_self]

/-- `(r - 1) p = 0`. -/
theorem r_sub_one_mul_p : (C.r - 1) * C.p = 0 := by
  rw [sub_mul, one_mul, C.r_mul_corner (p_mul_p_mul_p C), sub_self]

/-- The correction `diag(1,1,r)` as an element of `GL_3(R)`. -/
def rDiag : (Matrix (Fin 3) (Fin 3) R)ˣ where
  val := Matrix.diagonal ![1, 1, C.r]
  inv := Matrix.diagonal ![1, 1, C.rInv]
  val_inv := by
    rw [Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
    congr 1
    funext i
    fin_cases i <;> simp [C.r_mul_rInv]
  inv_val := by
    rw [Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
    congr 1
    funext i
    fin_cases i <;> simp [C.rInv_mul_r]

theorem rDiagEntry_mul_corner {a : R} (ha : C.p * a * C.p = a) (i : Fin 3) :
    (![1, 1, C.r] : Fin 3 → R) i * a = a := by
  fin_cases i <;> simp [C.r_mul_corner ha]

theorem corner_mul_rDiagEntry {a : R} (ha : C.p * a * C.p = a) (j : Fin 3) :
    a * (![1, 1, C.r] : Fin 3 → R) j = a := by
  fin_cases j <;> simp [C.corner_mul_r ha]

/-- `diag(1,1,r)` commutes with every root with corner coefficient. -/
theorem rDiag_commute_root {a : R} (ha : C.p * a * C.p = a) (i j : Fin 3) (h : i ≠ j) :
    Commute (rDiag C) (elementaryUnit i j h a) := by
  show rDiag C * elementaryUnit i j h a = elementaryUnit i j h a * rDiag C
  apply Units.ext
  change Matrix.diagonal ![1, 1, C.r] * (1 + Matrix.single i j a) =
    (1 + Matrix.single i j a) * Matrix.diagonal ![1, 1, C.r]
  rw [mul_add, add_mul, mul_one, one_mul, diag_mul_single, single_mul_diag,
    rDiagEntry_mul_corner C ha, corner_mul_rDiagEntry C ha]

/-- `diag(1,1,r)` centralizes `L = coreGroup S` for a corner coefficient set `S`. -/
theorem rDiag_commute_coreGroup {S : Set R} (hS : ∀ a ∈ S, C.p * a * C.p = a) :
    ∀ x ∈ coreGroup S, Commute (rDiag C) x :=
  commute_coreGroup fun i j h a ha => rDiag_commute_root C (hS a ha) i j h

/-- `W = diag(u,u,u) diag(1,1,r)`. -/
theorem W_eq_diag_mul_rDiag :
    (C.W : Matrix (Fin 3) (Fin 3) R) =
      Matrix.diagonal ![(C.u : R), (C.u : R), (C.u : R)] * (rDiag C : Matrix (Fin 3) (Fin 3) R) := by
  change Matrix.diagonal C.w =
    Matrix.diagonal ![(C.u : R), (C.u : R), (C.u : R)] * Matrix.diagonal ![1, 1, C.r]
  rw [Matrix.diagonal_mul_diagonal]
  congr 1
  funext i
  fin_cases i <;> simp [Cell.w]

/-- The third coordinate `ur` of `W` commutes with the level `f_{-1,-1}`. -/
theorem uR_commute_f_neg_one :
    ↑C.u * C.r * C.f (-1) (-1) = C.f (-1) (-1) * (↑C.u * C.r) := by
  have h1 : ↑C.u * C.f (-2) (-1) = C.f (-1) (-1) := by
    rw [C.unit_mul_f]
    norm_num
  have h2 : C.f (-1) (-1) * ↑C.u = C.f (-1) (-2) := by
    rw [C.f_mul_unit]
    norm_num
  rw [mul_assoc, C.r_mul_f_neg_one, h1, ← mul_assoc, h2, f_neg_two_mul_r C]

/-- The third coordinate `ur` of `W` commutes with the level `f_{-2,-2}`. -/
theorem uR_commute_f_neg_two :
    ↑C.u * C.r * C.f (-2) (-2) = C.f (-2) (-2) * (↑C.u * C.r) := by
  have h1 : ↑C.u * C.f (-3) (-2) = C.f (-2) (-2) := by
    rw [C.unit_mul_f]
    norm_num
  have h2 : C.f (-2) (-2) * ↑C.u = C.f (-2) (-3) := by
    rw [C.f_mul_unit]
    norm_num
  rw [mul_assoc, r_mul_f_neg_two C, h1, ← mul_assoc, h2, C.f_neg_three_mul_r]

end Generic

/-! ## The printed sentences at `R_X` -/

section Clopen

variable {X : Type} [TopologicalSpace X] (T : X ≃ₜ X) (k : Type) [Field k] [Finite k] {P : Set X}
  (hP : IsClopen P) (hTP : T '' P ⊆ P)

omit [Finite k] in
/-- **tex 1560**, "Let $r$ cycle the three negative levels $-1\mapsto-2\mapsto-3\mapsto-1$:
$r=1-\sum_{j=1}^3 f_{-j,-j}+f_{-2,-1}+f_{-3,-2}+f_{-1,-3}$,
$W=\operatorname{diag}(u,u,u)\operatorname{diag}(1,1,r)$."
The printed formula for `r`, `r` is invertible, `r` sends the levels `-1 ↦ -2 ↦ -3 ↦ -1`
(on the left and by conjugation of the level projections `f_{-j,-j}`), and the printed
factorization of `W`. -/
theorem manuscriptSentence_bilateralThreeCycleR :
    (bilateralCell T k hP hTP).r =
        1 - ((bilateralCell T k hP hTP).f (-1) (-1) + (bilateralCell T k hP hTP).f (-2) (-2) +
          (bilateralCell T k hP hTP).f (-3) (-3)) +
        (bilateralCell T k hP hTP).f (-2) (-1) + (bilateralCell T k hP hTP).f (-3) (-2) +
        (bilateralCell T k hP hTP).f (-1) (-3) ∧
      ((bilateralCell T k hP hTP).r * (bilateralCell T k hP hTP).rInv = 1 ∧
        (bilateralCell T k hP hTP).rInv * (bilateralCell T k hP hTP).r = 1) ∧
      (∀ b : ℤ, (bilateralCell T k hP hTP).r * (bilateralCell T k hP hTP).f (-1) b =
          (bilateralCell T k hP hTP).f (-2) b ∧
        (bilateralCell T k hP hTP).r * (bilateralCell T k hP hTP).f (-2) b =
          (bilateralCell T k hP hTP).f (-3) b ∧
        (bilateralCell T k hP hTP).r * (bilateralCell T k hP hTP).f (-3) b =
          (bilateralCell T k hP hTP).f (-1) b) ∧
      (bilateralCell T k hP hTP).r * (bilateralCell T k hP hTP).f (-1) (-1) *
          (bilateralCell T k hP hTP).rInv = (bilateralCell T k hP hTP).f (-2) (-2) ∧
      (bilateralCell T k hP hTP).r * (bilateralCell T k hP hTP).f (-2) (-2) *
          (bilateralCell T k hP hTP).rInv = (bilateralCell T k hP hTP).f (-3) (-3) ∧
      (bilateralCell T k hP hTP).r * (bilateralCell T k hP hTP).f (-3) (-3) *
          (bilateralCell T k hP hTP).rInv = (bilateralCell T k hP hTP).f (-1) (-1) ∧
      ((bilateralCell T k hP hTP).W : Matrix (Fin 3) (Fin 3) (ClopenCrossedProduct T k)) =
        Matrix.diagonal ![((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k),
            ((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k),
            ((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k)] *
          Matrix.diagonal ![1, 1, (bilateralCell T k hP hTP).r] := by
  refine ⟨?_, ⟨(bilateralCell T k hP hTP).r_mul_rInv, (bilateralCell T k hP hTP).rInv_mul_r⟩,
    fun b => ⟨(bilateralCell T k hP hTP).r_mul_f_neg_one b, r_mul_f_neg_two _ b,
      r_mul_f_neg_three _ b⟩,
    r_conj_level_neg_one _, r_conj_level_neg_two _, r_conj_level_neg_three _,
    W_eq_diag_mul_rDiag _⟩
  rw [Cell.r]
  abel

/-- **tex 1566**, "The correction $r$ acts outside $P$ and centralizes $L$."
`p(r-1) = (r-1)p = 0`; `r a = a r = a` for every coefficient `a ∈ S`; and `diag(1,1,r)`
commutes with every element of `L = EL_3(S)` embedded in `GL_3(R_X)`. -/
theorem manuscriptSentence_bilateralThreeRActsOutsidePCentralizesL :
    (bilateralCell T k hP hTP).p * ((bilateralCell T k hP hTP).r - 1) = 0 ∧
      ((bilateralCell T k hP hTP).r - 1) * (bilateralCell T k hP hTP).p = 0 ∧
      (∀ a ∈ bilateralCellSet T k hP hTP,
        (bilateralCell T k hP hTP).r * a = a ∧ a * (bilateralCell T k hP hTP).r = a) ∧
      ∀ x ∈ coreGroup (bilateralCellSet T k hP hTP),
        Commute (rDiag (bilateralCell T k hP hTP)) x := by
  have hS := (bilateralCell T k hP hTP).corner_of_mem_range (S := cellRing T k hP hTP)
  exact ⟨p_mul_r_sub_one _, r_sub_one_mul_p _,
    fun a ha => ⟨(bilateralCell T k hP hTP).r_mul_corner (hS a ha),
      (bilateralCell T k hP hTP).corner_mul_r (hS a ha)⟩,
    rDiag_commute_coreGroup _ hS⟩

/-- **tex 1566**, "Thus $W$ conjugates $L$ into $L$, sending a root coefficient $a\in S$ to
$uau^{-1}=sat$."  `W L W⁻¹ ⊆ L`, and for `a ∈ S` every root `e_{ij}(a)` is conjugated to
`e_{ij}(uau⁻¹)` with `uau⁻¹ = sat ∈ S`. -/
theorem manuscriptSentence_bilateralThreeWConjugatesL :
    (∀ x ∈ coreGroup (bilateralCellSet T k hP hTP),
        (bilateralCell T k hP hTP).W * x * (bilateralCell T k hP hTP).W⁻¹ ∈
          coreGroup (bilateralCellSet T k hP hTP)) ∧
      ∀ a ∈ bilateralCellSet T k hP hTP,
        (∀ (i j : Fin 3) (h : i ≠ j),
          (bilateralCell T k hP hTP).W * elementaryUnit i j h a * (bilateralCell T k hP hTP).W⁻¹ =
            elementaryUnit i j h (((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k) * a *
              (((bilateralCell T k hP hTP).u⁻¹ : (ClopenCrossedProduct T k)ˣ) :
                ClopenCrossedProduct T k))) ∧
        ((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k) * a *
            (((bilateralCell T k hP hTP).u⁻¹ : (ClopenCrossedProduct T k)ˣ) :
              ClopenCrossedProduct T k) =
          (bilateralCell T k hP hTP).s * a * (bilateralCell T k hP hTP).t ∧
        ((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k) * a *
            (((bilateralCell T k hP hTP).u⁻¹ : (ClopenCrossedProduct T k)ˣ) :
              ClopenCrossedProduct T k) ∈ bilateralCellSet T k hP hTP := by
  have hS := (bilateralCell T k hP hTP).corner_of_mem_range (S := cellRing T k hP hTP)
  have hu := (bilateralCell T k hP hTP).unit_conj_mem_range (sCorner_mem_cellRing T k hP hTP)
    (tCorner_mem_cellRing T k hP hTP)
  exact ⟨(bilateralCell T k hP hTP).W_conj_mem_coreGroup hS hu,
    fun a ha => ⟨fun i j h => (bilateralCell T k hP hTP).W_conj_root (hS a ha) i j h,
      (bilateralCell T k hP hTP).unit_conj_eq_s_mul_t (hS a ha), hu a ha⟩⟩

omit [Finite k] in
/-- **tex 1566**, "On its third coordinate $W$ fixes the negative levels $-1$ and $-2$
individually."  The third diagonal entry of `W` is `ur`, and it commutes with the level projections
`f_{-1,-1}` and `f_{-2,-2}` and with the coefficient `f_{-1,-2}` joining them. -/
theorem manuscriptSentence_bilateralThreeWFixesLevels :
    ((bilateralCell T k hP hTP).W : Matrix (Fin 3) (Fin 3) (ClopenCrossedProduct T k)) 2 2 =
        ((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k) * (bilateralCell T k hP hTP).r ∧
      ((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k) * (bilateralCell T k hP hTP).r *
          (bilateralCell T k hP hTP).f (-1) (-1) =
        (bilateralCell T k hP hTP).f (-1) (-1) *
          (((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k) *
            (bilateralCell T k hP hTP).r) ∧
      ((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k) * (bilateralCell T k hP hTP).r *
          (bilateralCell T k hP hTP).f (-2) (-2) =
        (bilateralCell T k hP hTP).f (-2) (-2) *
          (((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k) *
            (bilateralCell T k hP hTP).r) ∧
      ((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k) * (bilateralCell T k hP hTP).r *
          (bilateralCell T k hP hTP).f (-1) (-2) =
        (bilateralCell T k hP hTP).f (-1) (-2) *
          (((bilateralCell T k hP hTP).u : ClopenCrossedProduct T k) *
            (bilateralCell T k hP hTP).r) := by
  refine ⟨?_, uR_commute_f_neg_one _, uR_commute_f_neg_two _,
    (bilateralCell T k hP hTP).W_z_scalar⟩
  show Matrix.diagonal (bilateralCell T k hP hTP).w 2 2 = _
  rw [Matrix.diagonal_apply_eq]
  rfl

/-- **tex 1566–1575**, "Put $c=e_{13}(f_{-1,-2})$, $\ell=e_{21}(p)$, $y=e_{32}(f_{-1,0})$,
$z=1+E_{33}f_{-1,-2}$, $B=\langle L,W,c,y\rangle$."  The printed elements, with
`L = coreGroup S` the image of `EL_3(S)` under the corner embedding. -/
theorem manuscriptSentence_bilateralThreePut :
    (bilateralCell T k hP hTP).c =
        elementaryUnit (0 : Fin 3) 2 (by decide) ((bilateralCell T k hP hTP).f (-1) (-2)) ∧
      (bilateralCell T k hP hTP).ell =
        elementaryUnit (1 : Fin 3) 0 (by decide) (bilateralCell T k hP hTP).p ∧
      (bilateralCell T k hP hTP).y =
        elementaryUnit (2 : Fin 3) 1 (by decide) ((bilateralCell T k hP hTP).f (-1) 0) ∧
      ((bilateralCell T k hP hTP).z : Matrix (Fin 3) (Fin 3) (ClopenCrossedProduct T k)) =
        1 + Matrix.single (2 : Fin 3) (2 : Fin 3) ((bilateralCell T k hP hTP).f (-1) (-2)) ∧
      (bilateralCell T k hP hTP).B (bilateralCellSet T k hP hTP) =
        Subgroup.closure ((coreGroup (bilateralCellSet T k hP hTP) :
            Set (Matrix (Fin 3) (Fin 3) (ClopenCrossedProduct T k))ˣ) ∪
          {(bilateralCell T k hP hTP).W, (bilateralCell T k hP hTP).c,
            (bilateralCell T k hP hTP).y}) ∧
      coreGroup (bilateralCellSet T k hP hTP) =
        ((bilateralCell T k hP hTP).cornerEmbed (cellRing T k hP hTP)).range :=
  ⟨rfl, rfl, rfl, rfl, rfl, ((bilateralCell T k hP hTP).range_cornerEmbed (cellRing T k hP hTP)).symm⟩

end Clopen

end GroupApproximation.Manuscript.NonMF.BilateralB

#audit_axioms GroupApproximation.Manuscript.NonMF.BilateralB.manuscriptSentence_bilateralThreeCycleR
#audit_axioms GroupApproximation.Manuscript.NonMF.BilateralB.manuscriptSentence_bilateralThreeRActsOutsidePCentralizesL
#audit_axioms GroupApproximation.Manuscript.NonMF.BilateralB.manuscriptSentence_bilateralThreeWConjugatesL
#audit_axioms GroupApproximation.Manuscript.NonMF.BilateralB.manuscriptSentence_bilateralThreeWFixesLevels
#audit_axioms GroupApproximation.Manuscript.NonMF.BilateralB.manuscriptSentence_bilateralThreePut
