import GroupApproximation.KOne.ToeplitzWordSpace
import GroupApproximation.Leavitt.AryLeavitt

/-!
# The Leavitt relations hold on words modulo finite rank

`non_mf_groups_exist.tex`, `cor:leavitt-mf-quotient`.  The free algebra on
`s₀,…,s_{d-1},t₀,…,t_{d-1}` acts on the Toeplitz space of words
(`KOne/ToeplitzWordSpace.lean`) by `sⱼ ↦ S_j`, `tⱼ ↦ T_j` (`rho`).

* `tame_rho` --- every element of the free algebra acts by a **tame** operator
  for the first-letter splitting: the tame operators form a subalgebra and both
  families of generators are tame.
* `finiteRank_rho_sub_of_quotientMap_eq` --- **if two free-algebra elements have
  the same image in `L_k(1,d)`, their actions on words differ by a finite-rank
  operator.**  The kernel of `Free → L_k(1,d)` is the congruence generated by
  `tᵢsⱼ = δᵢⱼ` and `∑ sᵢtᵢ = 1`; `rho` satisfies the first exactly and the second
  up to the rank-one projection `Q`, and finite-rank operators form a two-sided
  ideal, so the induction over the congruence goes through.

No basis theorem for `L_k(1,d)` and no faithfulness of any representation is
used.
-/

namespace GroupApproximation

namespace FiniteRankDet

section Congruence

/-! ### Finite rank modulo differences, as lemmas

Over the word space `rw` does not always see the ring structure of `Module.End` through
the subtraction a statement elaborates, so the congruence steps are stated once here,
for an arbitrary vector space, and applied with `exact`. -/

variable {k : Type*} [Field k] {V : Type*} [AddCommGroup V] [Module k V]

theorem finiteRank_sub_of_eq {f g : Module.End k V} (h : f = g) : FiniteRank (f - g) := by
  rw [h, sub_self]
  exact finiteRank_zero

theorem FiniteRank.sub_symm {a b : Module.End k V} (h : FiniteRank (a - b)) :
    FiniteRank (b - a) := by
  rw [← neg_sub]
  exact h.neg

theorem FiniteRank.sub_trans {a b c : Module.End k V} (h1 : FiniteRank (a - b))
    (h2 : FiniteRank (b - c)) : FiniteRank (a - c) := by
  rw [← sub_add_sub_cancel a b c]
  exact h1.add h2

theorem FiniteRank.add_sub_add {a b c e : Module.End k V} (h1 : FiniteRank (a - b))
    (h2 : FiniteRank (c - e)) : FiniteRank (a + c - (b + e)) := by
  rw [add_sub_add_comm]
  exact h1.add h2

theorem FiniteRank.mul_sub_mul {a b c e : Module.End k V} (h1 : FiniteRank (a - b))
    (h2 : FiniteRank (c - e)) : FiniteRank (a * c - b * e) := by
  have h : a * c - b * e = (a - b) * c + b * (c - e) := by noncomm_ring
  rw [h]
  exact (h1.mul_right c).add (h2.mul_left b)

theorem one_add_mul_one_sub_of_mul_self {E : Module.End k V} (h : E * E = 0) :
    (1 + E) * (1 - E) = 1 := by
  rw [mul_sub, mul_one, add_mul, one_mul, h]
  abel

theorem one_sub_mul_one_add_of_mul_self {E : Module.End k V} (h : E * E = 0) :
    (1 - E) * (1 + E) = 1 := by
  rw [sub_mul, one_mul, mul_add, mul_one, h]
  abel

theorem FiniteRank.inv_mul_sub_one (u : (Module.End k V)ˣ) {Z : Module.End k V}
    (h : FiniteRank (Z - (u : Module.End k V))) :
    FiniteRank (((u⁻¹ : (Module.End k V)ˣ) : Module.End k V) * Z - 1) := by
  have heq : ((u⁻¹ : (Module.End k V)ˣ) : Module.End k V) * Z - 1
      = ((u⁻¹ : (Module.End k V)ˣ) : Module.End k V) * (Z - (u : Module.End k V)) := by
    rw [mul_sub, Units.inv_mul]
  rw [heq]
  exact h.mul_left _

end Congruence

end FiniteRankDet

namespace ToeplitzWords

open FiniteRankDet RegularizedDet AryLeavitt

variable {k : Type*} [Field k] {d : ℕ}

variable (k d) in
/-- **The action of the free algebra on words**: `sⱼ ↦ S_j`, `tⱼ ↦ T_j`. -/
noncomputable def rho : Free k d →ₐ[k] Module.End k (Space k d) :=
  FreeAlgebra.lift k (Sum.elim (opS k d) (opT k d))

theorem rho_freeS (i : Fin d) : rho k d (freeS k d i) = opS k d i := by
  simp [rho, freeS]

theorem rho_freeT (i : Fin d) : rho k d (freeT k d i) = opT k d i := by
  simp [rho, freeT]

/-- **Every element of the free algebra acts by a tame operator.** -/
theorem tame_rho (a : Free k d) : Tame (split k d) (rho k d a) := by
  induction a using FreeAlgebra.induction with
  | grade0 c =>
    rw [AlgHom.commutes, Algebra.algebraMap_eq_smul_one]
    exact Tame.smul _ c (tame_one _)
  | grade1 x =>
    cases x with
    | inl i =>
      show Tame (split k d) (rho k d (freeS k d i))
      rw [rho_freeS]
      exact tame_opS i
    | inr i =>
      show Tame (split k d) (rho k d (freeT k d i))
      rw [rho_freeT]
      exact tame_opT i
  | mul a b ha hb =>
    rw [map_mul]
    exact Tame.mul _ ha hb
  | add a b ha hb =>
    rw [map_add]
    exact Tame.add _ ha hb

/-- The defining relations act up to finite rank. -/
theorem finiteRank_rho_sub_of_relation {x y : Free k d} (h : Relation k d x y) :
    FiniteRank (rho k d x - rho k d y) := by
  cases h with
  | orthogonal i j =>
    have hxy : rho k d (freeT k d i * freeS k d j) = rho k d (if i = j then 1 else 0) := by
      rw [map_mul, rho_freeT, rho_freeS, opT_mul_opS]
      split_ifs <;> simp
    exact finiteRank_sub_of_eq hxy
  | complete =>
    have hxy : rho k d (∑ i : Fin d, freeS k d i * freeT k d i) - rho k d 1 = -opQ k d := by
      rw [map_sum, map_one]
      simp only [map_mul, rho_freeS, rho_freeT]
      rw [sum_opS_mul_opT]
      abel
    rw [hxy]
    exact finiteRank_opQ.neg

theorem finiteRank_rho_sub_of_rel {x y : Free k d} (h : RingQuot.Rel (Relation k d) x y) :
    FiniteRank (rho k d x - rho k d y) := by
  induction h with
  | of hr => exact finiteRank_rho_sub_of_relation hr
  | add_left _ ih =>
    rw [map_add, map_add]
    exact ih.add_sub_add (finiteRank_sub_of_eq rfl)
  | mul_left _ ih =>
    rw [map_mul, map_mul]
    exact ih.mul_sub_mul (finiteRank_sub_of_eq rfl)
  | mul_right _ ih =>
    rw [map_mul, map_mul]
    exact (finiteRank_sub_of_eq rfl).mul_sub_mul ih

theorem finiteRank_rho_sub_of_eqvGen {x y : Free k d}
    (h : Relation.EqvGen (RingQuot.Rel (Relation k d)) x y) :
    FiniteRank (rho k d x - rho k d y) := by
  induction h with
  | rel _ _ hr => exact finiteRank_rho_sub_of_rel hr
  | refl => exact finiteRank_sub_of_eq rfl
  | symm _ _ _ ih => exact ih.sub_symm
  | trans _ _ _ _ _ ih ih' => exact ih.sub_trans ih'

/-- **Equal images in `L_k(1,d)` act on words up to finite rank.** -/
theorem finiteRank_rho_sub_of_quotientMap_eq {x y : Free k d}
    (h : quotientMap k d x = quotientMap k d y) :
    FiniteRank (rho k d x - rho k d y) := by
  apply finiteRank_rho_sub_of_eqvGen
  have h1 : RingQuot.mkRingHom (Relation k d) x = RingQuot.mkRingHom (Relation k d) y := by
    rw [← RingQuot.mkAlgHom_coe k]
    exact h
  rw [RingQuot.mkRingHom_def] at h1
  simp only [RingHom.coe_mk, MonoidHom.coe_mk, OneHom.coe_mk, RingQuot.mk.injEq] at h1
  exact Quot.eqvGen_exact h1

end ToeplitzWords
end GroupApproximation

/-! ### Axiom audit -/

#audit_axioms GroupApproximation.ToeplitzWords.tame_rho
#audit_axioms GroupApproximation.ToeplitzWords.finiteRank_rho_sub_of_relation
#audit_axioms GroupApproximation.ToeplitzWords.finiteRank_rho_sub_of_quotientMap_eq
