import GroupApproximation.Manuscript.SimpleKazhdanSofic.Full.Fibonacci.Generation
import GroupApproximation.Manuscript.SimpleKazhdanSofic.ElementaryGroupFacts
import GroupApproximation.KOne.FieldKOneDeterminant
import GroupApproximation.Leavitt.ElementaryGroup
import GroupApproximation.Algebra.FinitaryLinearBinarySimple
import Mathlib.Algebra.Field.ZMod
import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
import GroupApproximation.Meta.AxiomGuard

/-!
# The Fibonacci example: the `e_ij(φ(s))` generate `SL_15(F₂)`

`simple_kazhdan_sofic_group.tex`, subsection "An example", l.438–440:

> So $\varphi(S)$ generates $M_5(\F_2)$, and the $e_{ij}(\varphi(s))$ with $s\in S$ generate
> $\SL_{15}(\F_2)$, as in Section~\ref{sec:proof}.

The route of Section `sec:proof` (tex 153–157) is: if the images generate the ring, the
`e_ij` of the images generate `EL_3` (`SimpleKazhdanSofic.printedElementaryGeneration`, tex
94–95), and block flattening carries `EL_3(M_5(F₂))` onto `ker det = SL_{3·5}(F₂)`
(`elementaryBlockGroup_map`, `AlgebraicK.ker_detUnits`).

* `fibonacciElementaryGeneration`: `EL_3(M_5(F₂))` is generated by the `e_ij(φ(s))`, `s ∈ S`.
* `fibonacciBlockSpecialLinear`: block flattening carries `EL_3(M_5(F₂))` onto `ker det`.
* `fibonacciElementaryGroup_eq_top`: `EL_3(M_5(F₂)) = GL_3(M_5(F₂))`, since over `F₂` every
  invertible matrix has determinant one.
* `fibonacciGeneratesMatrices`: the conjunction of the three generation statements.
* `fibonacciSL15`: `EL_3(M_5(F₂)) ≃* SL_15(F₂)`, by block flattening and `Fin 3 × Z/5 ≃ Fin 15`.
* `fibonacciGeneratesSL15`: the images `fibFlatten (e_ij(φ(s)))`, `s ∈ S`, generate `SL_15(F₂)`.
-/

namespace GroupApproximation.Full.SK08

open SymbolicDynamics.FullShift

/-- The ring `R_X = LC(X, F₂) ⋊_T ℤ` of the Fibonacci subshift. -/
local notation "𝓡" => SimpleKazhdanSofic.R fibonacciSubshift

/-- The matrix ring `M_5(F₂)`, rows and columns indexed by `t ∈ Z/5`. -/
local notation "𝓜" => Matrix (ZMod 5) (ZMod 5) (ZMod 2)

/-- Block flattening `GL_3(M_5(F₂)) ≃* GL_{3 × 5}(F₂)`. -/
local notation "𝓑" => elementaryBlockUnitEquiv (ι := Fin 3) (κ := ZMod 5) (R := ZMod 2)

section Endpoints

/-- The printed generators `e_ij(φ(s))`, `i ≠ j` in `{1, 2, 3}`, `s ∈ S` (tex l.439). -/
def fibElementaryGenerators : Set (Matrix (Fin 3) (Fin 3) 𝓜)ˣ :=
  {z | ∃ (i j : Fin 3) (h : i ≠ j) (s : 𝓡), s ∈ fibGenerators ∧
    elementaryUnit i j h (fibonacciModel s) = z}

/-- **tex l.439, first half of "as in Section `sec:proof`".** Since `φ(S)` generates `M_5(F₂)`
(`fibonacciModelGeneratesMatrixRing`), the `e_ij(φ(s))` with `s ∈ S` generate `EL_3(M_5(F₂))`. -/
theorem fibonacciElementaryGeneration :
    elementaryGroup (Fin 3) 𝓜 = Subgroup.closure fibElementaryGenerators := by
  rw [SimpleKazhdanSofic.printedElementaryGeneration 𝓜 (fibonacciModel '' fibGenerators)
    fibonacciModelGeneratesMatrixRing]
  congr 1
  ext z
  constructor
  · rintro ⟨i, j, h, s, hs, rfl⟩
    rcases hs with rfl | ⟨r, hr, rfl⟩
    · exact ⟨i, j, h, 1, Set.mem_insert _ _, by rw [fibonacciModel_one]⟩
    · exact ⟨i, j, h, r, hr, rfl⟩
  · rintro ⟨i, j, h, s, hs, rfl⟩
    exact ⟨i, j, h, fibonacciModel s, Set.mem_insert_of_mem _ ⟨s, hs, rfl⟩, rfl⟩

/-- **tex l.440 via tex 153–157.** Block flattening carries `EL_3(M_5(F₂))` onto the kernel of
the determinant on `GL_{3 × 5}(F₂)`: transvections generate `SL`, and in-block roots are
commutators of cross-block roots. -/
theorem fibonacciBlockSpecialLinear :
    (elementaryGroup (Fin 3) 𝓜).map (𝓑).toMonoidHom =
      (AlgebraicK.detUnits (ι := Fin 3 × ZMod 5) (k := ZMod 2)).ker :=
  (elementaryBlockGroup_map (ι := Fin 3) (κ := ZMod 5) (R := ZMod 2)).trans
    (AlgebraicK.ker_detUnits (ι := Fin 3 × ZMod 5) (k := ZMod 2)).symm

/-- `EL_3(M_5(F₂))` is all of `GL_3(M_5(F₂))`: its flattening is `EL_{3 × 5}(F₂) = GL_{3 × 5}(F₂)`
(`FinitaryLinear.elementaryGroup_zmodTwo_eq_top`), and flattening is an isomorphism. -/
theorem fibonacciElementaryGroup_eq_top : elementaryGroup (Fin 3) 𝓜 = ⊤ := by
  have hmap : (elementaryGroup (Fin 3) 𝓜).map (𝓑).toMonoidHom = ⊤ :=
    (elementaryBlockGroup_map (ι := Fin 3) (κ := ZMod 5) (R := ZMod 2)).trans
      (FinitaryLinear.elementaryGroup_zmodTwo_eq_top (Fin 3 × ZMod 5))
  apply Subgroup.map_injective (f := (𝓑).toMonoidHom) (𝓑).injective
  rw [hmap, Subgroup.map_top_of_surjective (𝓑).toMonoidHom (𝓑).surjective]

/-- **Sentence l.438–440 (tex l.438–440), generation part.** `φ(S)` generates `M_5(F₂)`,
`EL_3(M_5(F₂))` is everything, and it is generated by the `e_ij(φ(s))` with `s ∈ S`. -/
theorem fibonacciGeneratesMatrices :
    Subring.closure (fibonacciModel '' fibGenerators) = ⊤ ∧
      elementaryGroup (Fin 3) 𝓜 = ⊤ ∧
      Subgroup.closure fibElementaryGenerators = ⊤ :=
  ⟨fibonacciModelGeneratesMatrixRing, fibonacciElementaryGroup_eq_top,
    fibonacciElementaryGeneration.symm.trans fibonacciElementaryGroup_eq_top⟩

/-- Every invertible matrix over `F₂` has determinant one. -/
theorem fibDet_units_zmodTwo {n : Type*} [Fintype n] [DecidableEq n]
    (u : (Matrix n n (ZMod 2))ˣ) : (u : Matrix n n (ZMod 2)).det = 1 := by
  rw [← IsUnit.unit_spec (Matrix.isUnits_det_units u)]
  exact Units.val_eq_one.mpr (Subsingleton.elim _ _)

/-- `GL_n(F₂) ≃* SL_n(F₂)`, the identity on underlying matrices. -/
noncomputable def fibUnitsEquivSpecialLinear (n : Type*) [Fintype n] [DecidableEq n] :
    (Matrix n n (ZMod 2))ˣ ≃* Matrix.SpecialLinearGroup n (ZMod 2) where
  toFun u := ⟨(u : Matrix n n (ZMod 2)), fibDet_units_zmodTwo u⟩
  invFun A := Matrix.SpecialLinearGroup.toGL A
  left_inv _ := Units.ext rfl
  right_inv _ := Subtype.ext rfl
  map_mul' _ _ := Subtype.ext rfl

/-- `Fin 3 × Z/5 ≃ Fin 15`: the index set of the flattened matrices has `3 · 5 = 15` elements. -/
noncomputable def fibFin15Equiv : Fin 3 × ZMod 5 ≃ Fin 15 :=
  Fintype.equivFinOfCardEq (by simp)

/-- Flattening `GL_3(M_5(F₂)) ≃* SL_15(F₂)`: block flattening, reindexing along
`Fin 3 × Z/5 ≃ Fin 15`, and `GL_15(F₂) = SL_15(F₂)`. -/
noncomputable def fibFlatten :
    (Matrix (Fin 3) (Fin 3) 𝓜)ˣ ≃* Matrix.SpecialLinearGroup (Fin 15) (ZMod 2) :=
  (𝓑).trans ((elementaryReindexUnitEquiv (R := ZMod 2) fibFin15Equiv).trans
    (fibUnitsEquivSpecialLinear (Fin 15)))

/-- **tex l.440.** `EL_3(M_5(F₂)) ≃* SL_15(F₂)`, by flattening. -/
noncomputable def fibonacciSL15 :
    elementaryGroup (Fin 3) 𝓜 ≃* Matrix.SpecialLinearGroup (Fin 15) (ZMod 2) :=
  (MulEquiv.subgroupCongr fibonacciElementaryGroup_eq_top).trans
    (Subgroup.topEquiv.trans fibFlatten)

theorem fibonacciSL15_apply (g : elementaryGroup (Fin 3) 𝓜) :
    fibonacciSL15 g = fibFlatten (g : (Matrix (Fin 3) (Fin 3) 𝓜)ˣ) :=
  rfl

/-- **Sentence l.438–440 (tex l.439–440).** The `e_ij(φ(s))` with `s ∈ S`, flattened, generate
`SL_15(F₂)`. -/
theorem fibonacciGeneratesSL15 :
    Subgroup.closure (fibFlatten '' fibElementaryGenerators) = ⊤ := by
  have hc := MonoidHom.map_closure fibFlatten.toMonoidHom fibElementaryGenerators
  rw [MulEquiv.coe_toMonoidHom] at hc
  rw [← hc, ← fibonacciElementaryGeneration, fibonacciElementaryGroup_eq_top,
    Subgroup.map_top_of_surjective fibFlatten.toMonoidHom fibFlatten.surjective]

#audit_closed_axioms GroupApproximation.Full.SK08.fibonacciElementaryGeneration
#audit_closed_axioms GroupApproximation.Full.SK08.fibonacciBlockSpecialLinear
#audit_closed_axioms GroupApproximation.Full.SK08.fibonacciGeneratesMatrices
#audit_closed_axioms GroupApproximation.Full.SK08.fibonacciGeneratesSL15

end Endpoints

end GroupApproximation.Full.SK08
