import GroupApproximation.Manuscript.SimpleKazhdanSofic.Full.LVExcision.Units

/-!
# The relative Steinberg subgroup and its `e`-small pieces (lane LVExcision)

`simple_kazhdan_sofic_group.tex` l.733-735 (`sec:questions`), leaf T1b.iii.  Stable `K₂`
excision (Suslin–Wodzicki, Ann. Math. 136 (1992), Thm A; Keune, J. Algebra 54 (1978); ABC
thm:skewyao, `yaoseq6.tex` l.558-640).  Let `I` be an ideal of `R` contained in a subring `A`.

* `rel I A N ≤ St_N(A)` is generated by the `x_{ij}(b)`, `b ∈ I`;
* `small I A N e ≤ rel I A N` is generated by those `x_{ij}(b)` with `b e = b` and `f b = b`,
  `e f = f` for some `f ∈ I`; every element of `rel` is eventually `E`-small (`mem_small_ev`);
* `commute_small`: `x_{kl}(d)` commutes with `small e` whenever `d f = 0` for all `f` with
  `e f = f` and `b d = 0` for all `b` with `b e = b` (Lemma C);
* `conj_eq_of_dom`: on `small e`, conjugation by `x_{kl}(phi e r)` equals conjugation by
  `x_{kl}(phi E r)` for every `E` dominating `e`.
-/

namespace GroupApproximation.Full.LVExcision

open SteinbergGroup

variable {R : Type*} [Ring R] (I : TwoSidedIdeal R) (A : Subring R) (N : ℕ)

/-- Generators `x_{ij}(b)` of `St_N(A)` with `b ∈ I`, `b e = b`, and `f b = b`, `e f = f` for some
`f ∈ I`.  (`simple_kazhdan_sofic_group.tex` l.733-735, leaf T1b.iii; Suslin–Wodzicki 1992,
Thm A.) -/
def smallGens (e : R) : Set (SteinbergGroup (Fin N) A) :=
  {g | ∃ (i j : Fin N) (hij : i ≠ j) (b : R) (hbA : b ∈ A), b ∈ I ∧ b * e = b ∧
    (∃ f ∈ I, f * b = b ∧ e * f = f) ∧ g = x i j hij ⟨b, hbA⟩}

/-- The subgroup generated by the `e`-small generators.
(`simple_kazhdan_sofic_group.tex` l.733-735, leaf T1b.iii; Suslin–Wodzicki 1992, Thm A.) -/
abbrev small (e : R) : Subgroup (SteinbergGroup (Fin N) A) :=
  Subgroup.closure (smallGens I A N e)

/-- Generators `x_{ij}(b)` of `St_N(A)` with `b ∈ I`.
(`simple_kazhdan_sofic_group.tex` l.733-735, leaf T1b.iii; Suslin–Wodzicki 1992, Thm A.) -/
def relGens : Set (SteinbergGroup (Fin N) A) :=
  {g | ∃ (i j : Fin N) (hij : i ≠ j) (b : R) (hbA : b ∈ A), b ∈ I ∧ g = x i j hij ⟨b, hbA⟩}

/-- The relative subgroup of `St_N(A)` generated by the `x_{ij}(b)`, `b ∈ I`.
(`simple_kazhdan_sofic_group.tex` l.733-735, leaf T1b.iii; Suslin–Wodzicki 1992, Thm A.) -/
abbrev rel : Subgroup (SteinbergGroup (Fin N) A) :=
  Subgroup.closure (relGens I A N)

variable {I A N}

/-- `small e ≤ small e'` when `e'` dominates `e`.
(`simple_kazhdan_sofic_group.tex` l.733-735, leaf T1b.iii; Suslin–Wodzicki 1992, Thm A.) -/
theorem small_mono {e e' : R} (h : Dom e' e) : small I A N e ≤ small I A N e' := by
  apply Subgroup.closure_mono
  intro g hg
  obtain ⟨i, j, hij, b, hbA, hb, hbe, ⟨f, hf, hfb, hef⟩, rfl⟩ := hg
  exact ⟨i, j, hij, b, hbA, hb, h.right hbe, ⟨f, hf, hfb, h.left hef⟩, rfl⟩

/-- `small e ≤ rel`.
(`simple_kazhdan_sofic_group.tex` l.733-735, leaf T1b.iii; Suslin–Wodzicki 1992, Thm A.) -/
theorem small_le_rel (e : R) : small I A N e ≤ rel I A N := by
  apply Subgroup.closure_mono
  intro g hg
  obtain ⟨i, j, hij, b, hbA, hb, -, -, rfl⟩ := hg
  exact ⟨i, j, hij, b, hbA, hb, rfl⟩

/-- `x_{ij}(b) ∈ rel` for `b ∈ I`.
(`simple_kazhdan_sofic_group.tex` l.733-735, leaf T1b.iii; Suslin–Wodzicki 1992, Thm A.) -/
theorem x_mem_rel {i j : Fin N} (hij : i ≠ j) {b : R} (hbA : b ∈ A) (hb : b ∈ I) :
    x i j hij (⟨b, hbA⟩ : A) ∈ rel I A N :=
  Subgroup.subset_closure ⟨i, j, hij, b, hbA, hb, rfl⟩

/-- Every element of `rel` is eventually `E`-small.
(`simple_kazhdan_sofic_group.tex` l.733-735, leaf T1b.iii; Suslin–Wodzicki 1992, Thm A.) -/
theorem mem_small_ev (hI : IsSUnital I) {y : SteinbergGroup (Fin N) A} (hy : y ∈ rel I A N) :
    Ev I (fun E => y ∈ small I A N E) := by
  induction hy using Subgroup.closure_induction with
  | mem g hg =>
    obtain ⟨i, j, hij, b, hbA, hb, rfl⟩ := hg
    obtain ⟨f, hf, hfb, -, -⟩ := exists_unit₃ hI hb hb hb
    obtain ⟨e, he, heb, hef, -⟩ := exists_unit₃ hI hb hf hb
    exact ⟨e, he, fun E _ hEe => Subgroup.subset_closure
      ⟨i, j, hij, b, hbA, hb, (hEe.trans heb).2, ⟨f, hf, hfb.1, (hEe.trans hef).1⟩, rfl⟩⟩
  | one => exact ⟨0, I.zero_mem, fun E _ _ => (small I A N E).one_mem⟩
  | mul _ _ _ _ ha hb =>
    exact (Ev.and hI ha hb).mono (fun E _ h => (small I A N E).mul_mem h.1 h.2)
  | inv _ _ ha => exact ha.mono (fun E _ h => (small I A N E).inv_mem h)

/-- Lemma C for `small e`: `x_{kl}(d)` commutes with `small e` when `d f = 0` for all `f` with
`e f = f` and `b d = 0` for all `b` with `b e = b`.
(`simple_kazhdan_sofic_group.tex` l.733-735, leaf T1b.iii; Suslin–Wodzicki 1992, Thm A.) -/
theorem commute_small (hN : 3 ≤ N) (hIA : ∀ a ∈ I, a ∈ A) {e d : R} (hdA : d ∈ A)
    (hdf : ∀ f, e * f = f → d * f = 0) (hbd : ∀ b, b * e = b → b * d = 0) (k l : Fin N)
    (hkl : k ≠ l) {y : SteinbergGroup (Fin N) A} (hy : y ∈ small I A N e) :
    Commute (x k l hkl (⟨d, hdA⟩ : A)) y := by
  induction hy using Subgroup.closure_induction with
  | mem g hg =>
    obtain ⟨i, j, hij, b, hbA, -, hbe, ⟨f, hf, hfb, hef⟩, rfl⟩ := hg
    exact commute_x_of_annihilate hN (b := (⟨b, hbA⟩ : A)) (d := (⟨d, hdA⟩ : A))
      (f := (⟨f, hIA f hf⟩ : A)) (Subtype.ext hfb) (Subtype.ext (hdf f hef))
      (Subtype.ext (hbd b hbe)) i j k l hij hkl
  | one => exact Commute.one_right _
  | mul _ _ _ _ ha hb => exact ha.mul_right hb
  | inv _ _ ha => exact ha.inv_right

/-- Conjugation by `a c` equals conjugation by `a` on an element commuting with `c`.
(`simple_kazhdan_sofic_group.tex` l.733-735, leaf T1b.iii; Suslin–Wodzicki 1992, Thm A.) -/
theorem conj_mul_of_commute {G : Type*} [Group G] {a c y : G} (h : Commute c y) :
    a * c * y * (a * c)⁻¹ = a * y * a⁻¹ := by
  calc a * c * y * (a * c)⁻¹ = a * (c * y) * c⁻¹ * a⁻¹ := by group
    _ = a * (y * c) * c⁻¹ * a⁻¹ := by rw [h.eq]
    _ = a * y * a⁻¹ := by group

/-- On `small e`, conjugation by `x_{kl}(phi e r)` equals conjugation by `x_{kl}(phi E r)` when
`E` dominates `e`.
(`simple_kazhdan_sofic_group.tex` l.733-735, leaf T1b.iii; Suslin–Wodzicki 1992, Thm A.) -/
theorem conj_eq_of_dom (hN : 3 ≤ N) (hIA : ∀ a ∈ I, a ∈ A) {e E : R} (he : e ∈ I) (hE : E ∈ I)
    (hEe : Dom E e) (r : R) (k l : Fin N) (hkl : k ≠ l) {y : SteinbergGroup (Fin N) A}
    (hy : y ∈ small I A N e) :
    x k l hkl (⟨phi e r, hIA _ (phi_mem he r)⟩ : A) * y *
        (x k l hkl (⟨phi e r, hIA _ (phi_mem he r)⟩ : A))⁻¹ =
      x k l hkl (⟨phi E r, hIA _ (phi_mem hE r)⟩ : A) * y *
        (x k l hkl (⟨phi E r, hIA _ (phi_mem hE r)⟩ : A))⁻¹ := by
  have hdA : phi e r - phi E r ∈ A := A.sub_mem (hIA _ (phi_mem he r)) (hIA _ (phi_mem hE r))
  have hC := commute_small hN hIA hdA
    (fun f hef => by rw [sub_mul, phi_mul_of hef, phi_mul_of (hEe.left hef), sub_self])
    (fun b hbe => by rw [mul_sub, mul_phi_of hbe, mul_phi_of (hEe.right hbe), sub_self])
    k l hkl hy
  have hsplit : x k l hkl (⟨phi e r, hIA _ (phi_mem he r)⟩ : A) =
      x k l hkl (⟨phi E r, hIA _ (phi_mem hE r)⟩ : A) * x k l hkl ⟨phi e r - phi E r, hdA⟩ := by
    rw [x_mul]
    exact congrArg (x k l hkl) (Subtype.ext (show phi e r = phi E r + (phi e r - phi E r) by abel))
  rw [hsplit]
  exact conj_mul_of_commute hC

end GroupApproximation.Full.LVExcision
