import GroupApproximation.Manuscript.OneSidedMFRadical.UniversalGroupSigma
import GroupApproximation.Manuscript.OneSidedMFRadical.RankDescentPrintedLemmas
import GroupApproximation.Leavitt.FullIdempotentNormalGeneration
import GroupApproximation.Meta.AxiomGuard

/-!
# The printed proof of Theorem `thm:full-defect-ring`, one carrier per sentence

`non_mf_groups_exist.tex`, the proof environment of `thm:full-defect-ring`.
The printed argument runs in three parts -- *The group `B`*, *Rank two*,
*All ranks* -- and this module gives every printed sentence of it a named
carrier, so that the census can cite a declaration for each one instead of
citing the theorem as a block.

Nothing is proved here twice.  Every carrier is either a verbatim restatement
of a lemma that is already on `origin/main`, or a one-line application of one;
the docstring of each carrier names the lemma it spends.  Two exceptions are
flagged in their docstrings and are small computations that no existing lemma
states on its own:

* `manuscriptSentence_intertwineEntries`, the two entry computations that the
  printed text gives as the *reason* for `eq:intertwine`;
* `manuscriptSentence_fullnessRootRewrite`, the rewrite of the printed
  `e₄₂(1) = e₄₂(t₁ e s₁)` along the single fullness witness.

Three printed sentences are carried only in part, and say so:

* the `σ` conjugation identities, which live inside the proof of
  `UniversalGroupSigma.elGen_mem_normalClosure` and have no separate name;
* the passage to the *subring* `S ≤ R` generated by the `vᵢ, wᵢ`, which the
  formal proof does not make: it works at `R` itself;
* the two appeals to *signed permutation matrices*, for which the formal
  proofs substitute a Steinberg route.

Nothing in this module is specific to a characteristic, and nothing here
assumes property `(T)`: the `(T)` input is spent once, in
`FullDefectRingEJZUnconditional`.
-/

namespace GroupApproximation
namespace Manuscript
namespace OneSidedMFRadical
namespace FullDefectRingSentences

open OneSidedCompressor
open scoped commutatorElement

/-! ## Part one: the group `B` -/

/-- > In `𝒞` put `s = s₀`, `t = t₀`, and `e = 1 - st`.

The assignment `s = s₀`, `t = t₀` is the definition
`UniversalPair.pairInverse := UniversalPair.unit.toOneSidedInverse`; what the
sentence asserts on top of that definition is the value of `e`, which is
`OneSidedInverse.e_eq`. -/
theorem manuscriptSentence_ringData :
    UniversalPair.pairInverse.e
      = 1 - UniversalPair.pairInverse.s * UniversalPair.pairInverse.t :=
  UniversalPair.pairInverse.e_eq

/-- > Then `ts = 1`, `e² = e`, `es = te = 0`, and `t₁ e s₁ = 1`.

The first four are `OneSidedInverse.t_mul_s`, `e_mul_e`, `e_mul_s`, `t_mul_e`
at `UniversalPair.pairInverse`; the fifth is the single printed fullness
witness `UniversalPair.printedFullnessWitness`. -/
theorem manuscriptSentence_ringRelations :
    UniversalPair.pairInverse.t * UniversalPair.pairInverse.s = 1 ∧
      UniversalPair.pairInverse.e * UniversalPair.pairInverse.e
        = UniversalPair.pairInverse.e ∧
      UniversalPair.pairInverse.e * UniversalPair.pairInverse.s = 0 ∧
      UniversalPair.pairInverse.t * UniversalPair.pairInverse.e = 0 ∧
      UniversalPair.unit.w 1 * UniversalPair.pairInverse.e *
          UniversalPair.unit.v 1 = 1 :=
  ⟨UniversalPair.pairInverse.t_mul_s, UniversalPair.pairInverse.e_mul_e,
    UniversalPair.pairInverse.e_mul_s, UniversalPair.pairInverse.t_mul_e,
    UniversalPair.printedFullnessWitness⟩

/-- > Put `G = B = EL₄(𝒞)` and `L = EL₃(𝒞)` on coordinates `1,2,3`.

`G = B` is the definition `UniversalGroupB.B`.  The content of the second half
is that the printed `L` really is the copy of `EL₃(𝒞)` on the first three
coordinates, which is `OneSidedCompressor.coreEmbedding_range`. -/
theorem manuscriptSentence_groupsGandL :
    (coreEmbedding (R := UniversalPair.UniversalPairRing)).range
      = core UniversalPair.UniversalPairRing :=
  coreEmbedding_range

/-- > The ring `𝒞` is finitely generated, so both groups have
> property~(T) by [EJZ, Theorem 1.1], and `B` is finitely
> generated [BHV, Theorem 1.3.1].

Four named lemmas: `UniversalPair.isFinitelyGeneratedRing`,
`UniversalGroupB.hasKazhdanPropertyT`,
`UniversalGroupB.corner_hasKazhdanPropertyT` and
`UniversalGroupSigma.finitelyGenerated`.  The Ershov--Jaikin-Zapirain input is
`FullDefectRingEJZUnconditional.ejz` and the Bekka--de la Harpe--Valette input
is `elementaryGroup_finitelyGenerated_of_isFinitelyGeneratedRing`; neither is
re-proved here. -/
theorem manuscriptSentence_finitelyGeneratedPropertyT :
    IsFinitelyGeneratedRing UniversalPair.UniversalPairRing ∧
      HasKazhdanPropertyT.{0, 0} UniversalGroupB.B ∧
      HasKazhdanPropertyT.{0, 0}
        (elementaryGroup (Fin 3) UniversalPair.UniversalPairRing) ∧
      Group.FG UniversalGroupB.B :=
  ⟨UniversalPair.isFinitelyGeneratedRing, UniversalGroupB.hasKazhdanPropertyT,
    UniversalGroupB.corner_hasKazhdanPropertyT,
    UniversalGroupSigma.finitelyGenerated⟩

/-- > For `i = 1,2,3`, set `uᵢ = e₄ᵢ(t-1) e_{i4}(1) e₄ᵢ(s-1) e_{i4}(-t)`.

Definitional: this is `OneSidedCompressor.compressorPiece`, with the printed
`4` as `lastIdx` and the printed `i` as `coreIdx i`. -/
theorem manuscriptSentence_compressorPieceDef (i : Fin 3) :
    compressorPiece UniversalPair.pairInverse i
      = elementaryRoot lastIdx (coreIdx i) (last_ne_coreIdx i)
            (UniversalPair.pairInverse.t - 1) *
          elementaryRoot (coreIdx i) lastIdx (coreIdx_ne_last i) 1 *
            elementaryRoot lastIdx (coreIdx i) (last_ne_coreIdx i)
              (UniversalPair.pairInverse.s - 1) *
              elementaryRoot (coreIdx i) lastIdx (coreIdx_ne_last i)
                (-UniversalPair.pairInverse.t) :=
  rfl

/-- > Its block on coordinates `(i,4)` is `(s e; 0 t)`.

`OneSidedCompressor.compressorPiece_val`, whose right-hand side
`compressorPieceMatrix` is exactly the printed sparse matrix: the block
`(s e; 0 t)` on `(i,4)` and the identity elsewhere. -/
theorem manuscriptSentence_compressorPieceBlock (i : Fin 3) :
    (↑(↑(compressorPiece UniversalPair.pairInverse i) :
          (Matrix (Fin 4) (Fin 4) UniversalPair.UniversalPairRing)ˣ) :
        Matrix (Fin 4) (Fin 4) UniversalPair.UniversalPairRing)
      = compressorPieceMatrix UniversalPair.pairInverse i :=
  compressorPiece_val _ i

/-- > so `u = u₃u₂u₁ ∈ EL₄(𝒞)` is the matrix
> `(s 0 0 e; 0 s 0 et; 0 0 s et²; 0 0 0 t³)`,

Membership in `EL₄(𝒞)` is the type of `OneSidedCompressor.compressor`; the
displayed matrix is `OneSidedCompressor.compressor_val`, stated here against
the printed literal rather than against the abbreviation
`compressorMatrix`. -/
theorem manuscriptSentence_compressorMatrix :
    (↑(↑(compressor UniversalPair.pairInverse) :
          (Matrix (Fin 4) (Fin 4) UniversalPair.UniversalPairRing)ˣ) :
        Matrix (Fin 4) (Fin 4) UniversalPair.UniversalPairRing)
      = !![UniversalPair.pairInverse.s, 0, 0, UniversalPair.pairInverse.e;
           0, UniversalPair.pairInverse.s, 0,
             UniversalPair.pairInverse.e * UniversalPair.pairInverse.t;
           0, 0, UniversalPair.pairInverse.s,
             UniversalPair.pairInverse.e * UniversalPair.pairInverse.t *
               UniversalPair.pairInverse.t;
           0, 0, 0, UniversalPair.pairInverse.t * UniversalPair.pairInverse.t *
             UniversalPair.pairInverse.t] :=
  compressor_val _

/-- > invertible as a product of elementary matrices.

`OneSidedCompressor.compressorMatrix_mul_inv` and
`compressorInvMatrix_mul`: the printed matrix has a two-sided inverse, itself
the matrix of `u⁻¹`. -/
theorem manuscriptSentence_compressorInvertible :
    compressorMatrix UniversalPair.pairInverse *
        compressorInvMatrix UniversalPair.pairInverse = 1 ∧
      compressorInvMatrix UniversalPair.pairInverse *
        compressorMatrix UniversalPair.pairInverse = 1 :=
  ⟨compressorMatrix_mul_inv _, compressorInvMatrix_mul _⟩

/-- > For `1 ≤ i ≠ j ≤ 3` and `a ∈ 𝒞`,
> `u e_{ij}(a) = e_{ij}(sat) u`.

This is `eq:intertwine`, and it is
`OneSidedCompressor.compressor_mul_coreRoot`. -/
theorem manuscriptSentence_intertwine (i j : Fin 3) (hij : i ≠ j)
    (a : UniversalPair.UniversalPairRing) :
    compressor UniversalPair.pairInverse *
        elementaryRoot (coreIdx i) (coreIdx j) (coreIdx_injective.ne hij) a
      = elementaryRoot (coreIdx i) (coreIdx j) (coreIdx_injective.ne hij)
            (UniversalPair.pairInverse.s * a * UniversalPair.pairInverse.t) *
          compressor UniversalPair.pairInverse :=
  compressor_mul_coreRoot _ i j hij a

/-- > both sides differ from `u` by one entry, `sa` in position `(i,j)`, since
> on the right the increment `sat·(s,…,et^{j-1})` from row `j` of `u`
> contributes `sa·ts = sa` in position `(i,j)` and `sa·te·t^{j-1} = 0` in
> position `(i,4)`.

The two entry computations the printed text gives as the reason for
`eq:intertwine`.  No lemma on `origin/main` states them separately -- the
`fin_cases` proof of `compressor_mul_coreRoot` uses `t_mul_s` and `t_mul_e`
inline -- so they are proved here, over an arbitrary ring and an arbitrary
one-sided pair.  This is one of the two genuinely new statements in this
module. -/
theorem manuscriptSentence_intertwineEntries {R : Type*} [Ring R]
    (P : OneSidedInverse R) (a : R) :
    P.s * a * P.t * P.s = P.s * a ∧ ∀ x : R, P.s * a * P.t * (P.e * x) = 0 := by
  refine ⟨by rw [mul_assoc, P.t_mul_s, mul_one], fun x ↦ ?_⟩
  rw [mul_assoc, P.assoc_t_mul_e, mul_zero]

/-- > So `uLu⁻¹ ≤ L`.

`OneSidedCompressor.compressor_compresses_core`, in the printed form: `u` lies
in the compression set of `L`. -/
theorem manuscriptSentence_compressesCore :
    compressor UniversalPair.pairInverse ∈
      compressionSet (core UniversalPair.UniversalPairRing) :=
  compressor_mem_compressionSet _

/-- > The element `c = [e₄₁(e), e₁₄(t)] = diag(1,1,1,1+et)`

`OneSidedCompressor.centralMark_eq_commutator` for the commutator form and
`centralMark_val` for the printed diagonal value. -/
theorem manuscriptSentence_centralMark :
    centralMark UniversalPair.pairInverse
        = ⁅elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0)
              UniversalPair.pairInverse.e,
            elementaryRoot (coreIdx 0) lastIdx (coreIdx_ne_last 0)
              UniversalPair.pairInverse.t⁆ ∧
      (↑(↑(centralMark UniversalPair.pairInverse) :
            (Matrix (Fin 4) (Fin 4) UniversalPair.UniversalPairRing)ˣ) :
          Matrix (Fin 4) (Fin 4) UniversalPair.UniversalPairRing)
        = !![1, 0, 0, 0;
             0, 1, 0, 0;
             0, 0, 1, 0;
             0, 0, 0, 1 + UniversalPair.pairInverse.e *
               UniversalPair.pairInverse.t] :=
  ⟨centralMark_eq_commutator _, centralMark_val _⟩

/-- > is computed in the block on coordinates `(1,4)` using `te = 0`, and a
> diagonal matrix of this shape commutes with every `diag(A,1)`, so
> `c ∈ C_G(L)`.

`OneSidedCompressor.centralMark_commute_core`, whose per-root step
`centralMark_commute_coreRoot` is the printed "commutes with every
`diag(A,1)`". -/
theorem manuscriptSentence_centralMarkCentral :
    ∀ g ∈ core UniversalPair.UniversalPairRing,
      Commute (centralMark UniversalPair.pairInverse) g :=
  centralMark_commute_core _

/-- > Both `uc` and `e₁₂(e)u` equal `u + et E₁₄`: the last column of `uc` is
> `(e,et,et²,t³)ᵀ(1+et)` and `e² = e`, `te = 0`, while
> `e₁₂(e)u = u + e(s,0,0,et)E_{1∗}` and `es = 0`.  So `ucu⁻¹ = e₁₂(e)`.

`OneSidedCompressor.compressor_mul_centralMark` is the printed equality of the
two products; `compressor_conj_centralMark` is the displayed conclusion. -/
theorem manuscriptSentence_conjCentralMark :
    compressor UniversalPair.pairInverse * centralMark UniversalPair.pairInverse
        = elementaryRoot (coreIdx 0) (coreIdx 1)
            (coreIdx_injective.ne zeroNeOne) UniversalPair.pairInverse.e *
          compressor UniversalPair.pairInverse ∧
      compressor UniversalPair.pairInverse *
            centralMark UniversalPair.pairInverse *
            (compressor UniversalPair.pairInverse)⁻¹
        = elementaryRoot (coreIdx 0) (coreIdx 1)
            (coreIdx_injective.ne zeroNeOne) UniversalPair.pairInverse.e :=
  ⟨compressor_mul_centralMark _, compressor_conj_centralMark _⟩

/-- > For `ℓ = e₂₃(1)` the Steinberg relation `[e₁₂(e), e₂₃(1)] = e₁₃(e)` gives
> `d = [ucu⁻¹, ℓ] = e₁₃(e) ∈ 𝔇_G(L)`.

`OneSidedCompressor.printedEll` is the printed `ℓ`, `defect_eq` is the
displayed commutator, and `printedDefectRoot_mem_printedDefect` is the
membership in `𝔇_G(L)` of `eq:intrinsic-defect`.  The Steinberg relation it
uses is the general `elementaryRoot_commutator`. -/
theorem manuscriptSentence_defect :
    ⁅compressor UniversalPair.pairInverse *
          centralMark UniversalPair.pairInverse *
          (compressor UniversalPair.pairInverse)⁻¹,
        printedEll UniversalPair.UniversalPairRing⁆
        = printedDefectRoot UniversalPair.pairInverse ∧
      printedDefectRoot UniversalPair.pairInverse ∈
        printedDefect (core UniversalPair.UniversalPairRing) :=
  ⟨defect_eq _, printedDefectRoot_mem_printedDefect _⟩

/-- > Let `N` be the normal closure of `d` in `G`.

Definitional; the formal counterpart is the `N` bound in
`FullIdempotent.elementaryGroup_normal_eq_top_of_full`, which is stated for an
arbitrary normal `N` containing the root and so covers the printed choice.
This row has no lemma of its own. -/
theorem manuscriptSentence_normalClosureOfDefect :
    printedDefectRoot UniversalPair.pairInverse ∈
      Subgroup.normalClosure
        ({printedDefectRoot UniversalPair.pairInverse} :
          Set UniversalGroupB.B) :=
  Subgroup.subset_normalClosure rfl

/-- > For arbitrary `a, b ∈ 𝒞`, the Steinberg relations give
> `[e₄₁(a), e₁₃(e)] = e₄₃(ae)`, `[e₄₃(ae), e₃₂(b)] = e₄₂(aeb)`.

Both displays are instances of the single general lemma
`elementaryRoot_commutator`; this is the pair of instances the printed proof
takes, at the printed indices.  `FullIdempotent.elementaryGroup_normal_eq_top_of_full`
takes the same two steps. -/
theorem manuscriptSentence_steinbergPair
    (a b : UniversalPair.UniversalPairRing) :
    ⁅elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0) a,
        elementaryRoot (coreIdx 0) (coreIdx 2)
          (coreIdx_injective.ne zeroNeTwo) UniversalPair.pairInverse.e⁆
        = elementaryRoot lastIdx (coreIdx 2) (last_ne_coreIdx 2)
            (a * UniversalPair.pairInverse.e) ∧
      ⁅elementaryRoot lastIdx (coreIdx 2) (last_ne_coreIdx 2)
            (a * UniversalPair.pairInverse.e),
          elementaryRoot (coreIdx 2) (coreIdx 1)
            (coreIdx_injective.ne (by decide)) b⁆
        = elementaryRoot lastIdx (coreIdx 1) (last_ne_coreIdx 1)
            (a * UniversalPair.pairInverse.e * b) :=
  ⟨elementaryRoot_commutator _ _ _ _ _ _ _ _,
    elementaryRoot_commutator _ _ _ _ _ _ _ _⟩

/-- > So `e₄₂(1) = e₄₂(t₁ e s₁) ∈ N`.

The printed rewrite along the single fullness witness
`UniversalPair.printedFullnessWitness`.  No lemma on `origin/main` states the
rewrite by itself: `FullIdempotent.elementaryGroup_normal_eq_top_of_full`
takes the general indexed-sum witness `∑ a k · x · b k = 1` and never singles
out the one-term case, so the equality of roots is proved here.  This is the
second of the two genuinely new statements in this module. -/
theorem manuscriptSentence_fullnessRootRewrite :
    elementaryRoot lastIdx (coreIdx 1) (last_ne_coreIdx 1)
        (UniversalPair.unit.w 1 * UniversalPair.pairInverse.e *
          UniversalPair.unit.v 1)
      = elementaryRoot lastIdx (coreIdx 1) (last_ne_coreIdx 1) 1 :=
  congrArg _ UniversalPair.printedFullnessWitness

/-- > Elementary signed permutation matrices conjugate this element to every
> off-diagonal position, up to a sign, so `e_{ij}(1) ∈ N` whenever `i ≠ j`.

**Partial.**  The conclusion is carried, inside
`FullIdempotent.elementaryGroup_normal_eq_top_of_full`; the printed *route* is
not.  That lemma reaches every off-diagonal position by
`exists_two_further_indices` and Steinberg conjugation, using the four indices
the printed proof also needs, and never forms a signed permutation matrix.
The repository does have the signed permutations, as `ElementaryWeyl.weyl`,
but the full-defect proof does not spend them.  This row therefore has no
lemma of its own. -/
theorem manuscriptSentence_signedPermutationsReachEveryPosition
    (hfull : ∃ (m : ℕ) (a b : Fin m → UniversalPair.UniversalPairRing),
      ∑ k, a k * UniversalPair.pairInverse.e * b k = 1)
    (N : Subgroup UniversalGroupB.B) [N.Normal]
    (hmem : printedDefectRoot UniversalPair.pairInverse ∈ N) :
    N = ⊤ :=
  FullIdempotent.elementaryGroup_normal_eq_top_of_full (by simp) N
    (coreIdx_injective.ne zeroNeTwo) hmem hfull

/-- > For distinct `i, j, k` and every `r ∈ 𝒞`,
> `[e_{ij}(1), e_{jk}(r)] = e_{ik}(r) ∈ N`.

The general Steinberg relation `elementaryRoot_commutator`, at coefficient
`1 * r`. -/
theorem manuscriptSentence_steinbergSpreadsCoefficients
    (i j k : Fin 4) (hij : i ≠ j) (hjk : j ≠ k) (hik : i ≠ k)
    (r : UniversalPair.UniversalPairRing) :
    ⁅elementaryRoot i j hij (1 : UniversalPair.UniversalPairRing),
        elementaryRoot j k hjk r⁆
      = elementaryRoot i k hik r := by
  rw [elementaryRoot_commutator i j k hij hjk hik 1 r, one_mul]

/-- > So `N = G`, and `𝔇_G(L) = G`.

`FullIdempotent.printedDefect_eq_top`, at the printed pair over `𝒞` and the
printed fullness witness. -/
theorem manuscriptSentence_defectIsEverything :
    printedDefect (core UniversalPair.UniversalPairRing) = ⊤ :=
  FullIdempotent.printedDefect_eq_top UniversalPair.pairInverse
    UniversalGroupB.printedFullness

/-- > By Theorem `thm:compression-criterion` with `K = G`, every homomorphism
> from `G` to an MF group is trivial.

`UniversalGroupB.hom_eq_one`.  The compression criterion enters there through
`FullDefectRingEJZUnconditional.manuscriptFullComplementaryIdempotentsAllCharacteristics`,
which is where the property `(T)` input is spent. -/
theorem manuscriptSentence_homFromBTrivial (M : Type) [Group M]
    (hM : IsOperatorMF M) (f : UniversalGroupB.B →* M) (x : UniversalGroupB.B) :
    f x = 1 :=
  UniversalGroupB.hom_eq_one M hM f x

/-! The current manuscript uses the positive double transposition
`w₀₁ w₂₃ w₀₂²`. Its matrix, order, two commutators, and normal generation
are proved directly in `ElementaryDoubleSwap`. The sentence map names
those reusable declarations. The old sentence aliases for the single
order-four Weyl generator were removed because they did not state these
involution claims. -/

/-! ## Part two: rank two -/

section RankTwo

variable {R : Type} [Ring R] (Q : RankDescent.ProperlyInfiniteUnit R)

include Q

/-- > Now let `R` satisfy the hypothesis.  By Lemma `lem:two-copies` choose
> `v₀, v₁, w₀, w₁ ∈ R` with `wᵢvⱼ = δᵢⱼ`.

`RankDescentPrinted.manuscriptTwoCopiesLemma` is the printed lemma as a closed
proposition; `RankDescent.ProperlyInfiniteUnit` is the chosen data, and
`RankDescent.ofFull` is the construction the lemma runs. -/
theorem manuscriptSentence_twoCopies (i j : Fin 2) :
    Q.w i * Q.v j = if i = j then 1 else 0 :=
  Q.w_mul_v i j

/-- > Then `sᵢ ↦ vᵢ`, `tᵢ ↦ wᵢ` defines a unital ring homomorphism from `𝒞`
> onto the subring `S` of `R` generated by these elements,

**Partial.**  `UniversalPair.lift` is the printed homomorphism and
`UniversalPair.lift_v`, `lift_w` are the printed assignments.  What is not
carried is the corestriction to the subring `S ≤ R` generated by the `vᵢ, wᵢ`:
the formal proof takes the map into `R` itself and never names `S`, and the
rest of the printed argument goes through unchanged at `R`, because every
later step uses only the `Sᵢ, Tⱼ` built from the `vᵢ, wᵢ`. -/
theorem manuscriptSentence_universalProperty (i : Fin 2) :
    UniversalPair.lift Q (UniversalPair.unit.v i) = Q.v i ∧
      UniversalPair.lift Q (UniversalPair.unit.w i) = Q.w i :=
  ⟨UniversalPair.lift_v Q i, UniversalPair.lift_w Q i⟩

/-- > so `EL₄(S)` is a homomorphic image of `B`, and every homomorphism from
> `EL₄(S)` to an MF group is trivial.

**Partial**, for the same reason as the preceding sentence: the target is
`EL₄(R)`, not `EL₄(S)`.  `UniversalGroupB.toElementaryFour` and
`toElementaryFour_root` are the homomorphism and its value on roots; the
triviality is the rank-four theorem at `R`,
`FullDefectRingEJZUnconditional.manuscriptFullComplementaryIdempotentsAllCharacteristics`. -/
theorem manuscriptSentence_imageOfB [Countable R] (i j : Fin 4) (hij : i ≠ j)
    (a : UniversalPair.UniversalPairRing) (M : Type) [Group M]
    (hM : IsOperatorMF M) (f : elementaryGroup (Fin 4) R →* M)
    (x : elementaryGroup (Fin 4) R) :
    UniversalGroupB.toElementaryFour Q (elementaryRoot i j hij a)
        = elementaryRoot i j hij (UniversalPair.lift Q a) ∧
      f x = 1 :=
  ⟨UniversalGroupB.toElementaryFour_root Q i j hij a,
    FullDefectRingEJZUnconditional.manuscriptFullComplementaryIdempotentsAllCharacteristics
      R (Q.v 0) (Q.w 0) (Q.w_mul_v_self 0) Q.toOneSidedInverse_isFull 4
      (by norm_num) M hM f x⟩

/-- > Put `S₁ = v₀v₀`, `S₂ = v₀v₁`, `S₃ = v₁v₀`, `S₄ = v₁v₁`,
> `T₁ = w₀w₀`, `T₂ = w₁w₀`, `T₃ = w₀w₁`, `T₄ = w₁w₁`, so that `TᵢSⱼ = δᵢⱼ`,

`RankDescent.wordS` and `RankDescent.wordT` are the printed lists, in the
printed order, and `RankDescent.wordT_mul_wordS` is the printed
orthogonality. -/
theorem manuscriptSentence_lengthTwoWords (i j : Fin 4) :
    RankDescent.wordS Q = ![Q.v 0 * Q.v 0, Q.v 0 * Q.v 1, Q.v 1 * Q.v 0,
        Q.v 1 * Q.v 1] ∧
      RankDescent.wordT Q = ![Q.w 0 * Q.w 0, Q.w 1 * Q.w 0, Q.w 0 * Q.w 1,
        Q.w 1 * Q.w 1] ∧
      RankDescent.wordT Q i * RankDescent.wordS Q j = if i = j then 1 else 0 :=
  ⟨rfl, rfl, RankDescent.wordT_mul_wordS Q i j⟩

/-- > and put `p = ∑ᵢ SᵢTᵢ`.

Definitional: `RankDescent.pIdem`.  This row has no lemma of its own. -/
theorem manuscriptSentence_pIdem :
    RankDescent.pIdem (RankDescent.wordS Q) (RankDescent.wordT Q)
      = ∑ i, RankDescent.wordS Q i * RankDescent.wordT Q i :=
  rfl

/-- > For a `4×4` matrix `A` over `S` put
> `ȷ(A) = 1 - p + ∑_{i,j} Sᵢ A_{ij} Tⱼ ∈ R`.

Definitional: `RankDescent.jMap`, whose body `RankDescent.jBody` is the
printed double sum.  This row has no lemma of its own. -/
theorem manuscriptSentence_jMapDef (A : Matrix (Fin 4) (Fin 4) R) :
    RankDescent.jMap (RankDescent.wordS Q) (RankDescent.wordT Q) A
      = 1 - RankDescent.pIdem (RankDescent.wordS Q) (RankDescent.wordT Q)
          + ∑ i, ∑ j, RankDescent.wordS Q i * A i j * RankDescent.wordT Q j :=
  rfl

/-- > Since `(1-p)Sᵢ = 0` and `Tⱼ(1-p) = 0`, we have `ȷ(AB) = ȷ(A)ȷ(B)` and
> `ȷ(I) = 1`,

`RankDescent.one_sub_pIdem_mul_wordS`, `wordT_mul_one_sub_pIdem`, `jMap_mul`
and `jMap_one`, in the printed order. -/
theorem manuscriptSentence_jMapMultiplicative
    (i j : Fin 4) (A B : Matrix (Fin 4) (Fin 4) R) :
    (1 - RankDescent.pIdem (RankDescent.wordS Q) (RankDescent.wordT Q)) *
          RankDescent.wordS Q j = 0 ∧
      RankDescent.wordT Q i *
          (1 - RankDescent.pIdem (RankDescent.wordS Q)
            (RankDescent.wordT Q)) = 0 ∧
      RankDescent.jMap (RankDescent.wordS Q) (RankDescent.wordT Q) (A * B)
        = RankDescent.jMap (RankDescent.wordS Q) (RankDescent.wordT Q) A *
          RankDescent.jMap (RankDescent.wordS Q) (RankDescent.wordT Q) B ∧
      RankDescent.jMap (RankDescent.wordS Q) (RankDescent.wordT Q) 1 = 1 :=
  ⟨RankDescent.one_sub_pIdem_mul_wordS _ _ (RankDescent.wordT_mul_wordS Q) j,
    RankDescent.wordT_mul_one_sub_pIdem _ _ (RankDescent.wordT_mul_wordS Q) i,
    RankDescent.jMap_mul _ _ (RankDescent.wordT_mul_wordS Q) A B,
    RankDescent.jMap_one _ _⟩

/-- > so `Ψ(A) = diag(ȷ(A),1)` defines a homomorphism `GL₄(S) → GL₂(R)`,

`RankDescent.blockDiagHom` is `x ↦ diag(x,1)` and `RankDescent.psiUnits` is
the printed `Ψ` on invertible matrices; being a homomorphism is its bundled
type.  Stated here as the value of `Ψ` on a unit. -/
theorem manuscriptSentence_psiIsDiag (g : (Matrix (Fin 4) (Fin 4) R)ˣ) :
    (↑(RankDescent.psiUnits (RankDescent.wordS Q) (RankDescent.wordT Q)
          (RankDescent.wordT_mul_wordS Q) g) : Matrix (Fin 2) (Fin 2) R)
      = RankDescent.blockDiagHom R
          (RankDescent.jMap (RankDescent.wordS Q) (RankDescent.wordT Q) g) :=
  rfl

/-- > and for `i ≠ j` and `r ∈ S`,
> `Ψ(e_{ij}(r)) = diag(1 + Sᵢ r Tⱼ, 1) = [e₁₂(Sᵢr), e₂₁(Tⱼ)]`
> by the computation in Lemma `lem:rank-two`, since `TⱼSᵢ = 0`.

`RankDescent.psi_elementaryRoot` gives the commutator form
`RankDescent.gen (Sᵢ r) (Tⱼ)`, which is `⁅e₁₂(Sᵢr), e₂₁(Tⱼ)⁆` by
`RankDescentPrinted.gen_eq_printed_commutator`; `RankDescent.gen_val`, the
computation of `lem:rank-two`, gives the printed matrix `1 + Sᵢ r Tⱼ`. -/
theorem manuscriptSentence_psiOnRoots (i j : Fin 4) (hij : i ≠ j) (r : R) :
    RankDescent.psi (RankDescent.wordS Q) (RankDescent.wordT Q)
          (RankDescent.wordT_mul_wordS Q) (elementaryRoot i j hij r)
        = ⁅RankDescent.upperRoot (RankDescent.wordS Q i * r),
            RankDescent.lowerRoot (RankDescent.wordT Q j)⁆ ∧
      RankDescent.wordT Q j * (RankDescent.wordS Q i * r) = 0 := by
  have hTS : RankDescent.wordT Q j * RankDescent.wordS Q i =
      if j = i then 1 else 0 := RankDescent.wordT_mul_wordS Q j i
  rw [if_neg (Ne.symm hij)] at hTS
  exact ⟨RankDescent.psi_elementaryRoot _ _ _ i j hij r,
    by rw [← mul_assoc, hTS, zero_mul]⟩

/-- > So `Ψ(EL₄(S)) ≤ EL₂(R)`.

`RankDescent.psiUnits_mem`; `RankDescent.psi` is the corestriction it
licenses. -/
theorem manuscriptSentence_psiLandsInEL2 (g : elementaryGroup (Fin 4) R) :
    RankDescent.psiUnits (RankDescent.wordS Q) (RankDescent.wordT Q)
        (RankDescent.wordT_mul_wordS Q) (g : (Matrix (Fin 4) (Fin 4) R)ˣ)
      ∈ elementaryGroup (Fin 2) R :=
  RankDescent.psiUnits_mem _ _ _ g

/-- > Let `ρ` be a homomorphism from `EL₂(R)` to an MF group.  Then `ρ ∘ Ψ` is
> trivial on `EL₄(S)`, so `ρ` kills `Ψ(e₁₂(1)) = diag(1 + S₁T₂, 1)`,

`RankDescent.descent` is `Ψ` at the length-two words and
`RankDescent.descent_elementaryRoot` is its value at the printed root, in the
printed form `gen(S₁, T₂)`. -/
theorem manuscriptSentence_rhoKillsGenerator :
    RankDescent.descent Q (elementaryRoot 0 1 (by decide) 1)
      = RankDescent.gen (RankDescent.wordS Q 0 * 1) (RankDescent.wordT Q 1) :=
  RankDescent.descent_elementaryRoot Q 0 1 (by decide) 1

/-- > which normally generates `EL₂(R)` by Lemma `lem:rank-two` with `v = S₁`,
> `w = T₁`, `a = S₂`, `b = T₂`.

`RankDescent.normalClosure_descent_root_eq_top`, whose proof feeds
`RankDescent.normalClosure_gen_eq_top` exactly the printed four arguments.
The closed form of `lem:rank-two` is
`RankDescentPrinted.manuscriptRankTwoNormalGeneration`. -/
theorem manuscriptSentence_generatorNormallyGeneratesEL2 :
    Subgroup.normalClosure
        ({RankDescent.descent Q (elementaryRoot 0 1 (by decide) 1)} :
          Set (elementaryGroup (Fin 2) R)) = ⊤ :=
  RankDescent.normalClosure_descent_root_eq_top Q

/-- > So `ρ` is trivial,

`FullDefectRankTwo.hom_eq_one_of_rankFour` at `n = 2`: every homomorphism from
`EL₂(R)` to an MF group is trivial, once the rank-four conclusion is
available. -/
theorem manuscriptSentence_rhoTrivial (M : Type) [Group M]
    (h4 : ∀ (f : elementaryGroup (Fin 4) R →* M)
      (x : elementaryGroup (Fin 4) R), f x = 1)
    (ρ : elementaryGroup (Fin 2) R →* M) (x : elementaryGroup (Fin 2) R) :
    ρ x = 1 :=
  FullDefectRankTwo.hom_eq_one_of_rankFour (Q.v 0) (Q.w 0) (Q.w_mul_v_self 0)
    (Classical.choose (Classical.choose_spec Q.toOneSidedInverse_isFull))
    (Classical.choose (Classical.choose_spec
      (Classical.choose_spec Q.toOneSidedInverse_isFull)))
    (Classical.choose_spec (Classical.choose_spec
      (Classical.choose_spec Q.toOneSidedInverse_isFull))) h4 2 (by norm_num) ρ x

/-- > and the image of `B` in `EL₂(R)` contains `Ψ(e₁₂(1))`, so it normally
> generates `EL₂(R)`.

`UniversalGroupB.toRankTwo_root_one` for the containment and
`UniversalGroupB.normalClosure_toRankTwo_range` for the normal generation. -/
theorem manuscriptSentence_imageOfBNormallyGeneratesEL2 :
    UniversalGroupB.toRankTwo Q (elementaryRoot 0 1 (by decide) 1)
        = RankDescent.descent Q (elementaryRoot 0 1 (by decide) 1) ∧
      Subgroup.normalClosure
          ((UniversalGroupB.toRankTwo Q).range :
            Set (elementaryGroup (Fin 2) R)) = ⊤ :=
  ⟨UniversalGroupB.toRankTwo_root_one Q,
    UniversalGroupB.normalClosure_toRankTwo_range Q⟩

/-! ## Part three: all ranks -/

omit Q in
/-- > For `n ≥ 3`, signed permutation matrices conjugate `e₁₂(r)` to
> `e_{ij}(±r)` for all `i ≠ j`, so the copy of `EL₂(R)` on coordinates `1,2`
> normally generates `EL_n(R)`.

**Partial.**  The conclusion is carried, by
`FullDefectRankTwo.blockEmbed` together with the normal-generation step inside
`FullDefectRankTwo.hom_eq_one_of_rankFour`; the printed *route* is not.  The
formal proof reaches every off-diagonal position by Steinberg conjugation
rather than by signed permutation matrices, exactly as in part one.  Stated
here as the printed copy of `EL₂(R)` on coordinates `1,2`. -/
theorem manuscriptSentence_copyOfEL2 (k : ℕ) (r : R) :
    FullDefectRankTwo.blockEmbed R k (RankDescent.upperRoot r)
      = elementaryRoot (finSumFinEquiv (Sum.inl (0 : Fin 2)))
          (finSumFinEquiv (Sum.inl (1 : Fin 2)))
          (FullDefectRankTwo.blockEmbed_ne k) r :=
  FullDefectRankTwo.blockEmbed_upperRoot R k r

/-- > A homomorphism from `EL_n(R)` to an MF group is trivial on that copy,
> hence trivial,

`FullDefectRankTwo.hom_eq_one_of_rankFour`, at every `n ≥ 2` (the printed
`n ≥ 3` plus the rank-two case just settled). -/
theorem manuscriptSentence_homFromELnTrivial (M : Type) [Group M]
    (h4 : ∀ (f : elementaryGroup (Fin 4) R →* M)
      (x : elementaryGroup (Fin 4) R), f x = 1)
    (n : ℕ) (hn : 2 ≤ n) (f : elementaryGroup (Fin n) R →* M)
    (x : elementaryGroup (Fin n) R) :
    f x = 1 :=
  FullDefectRankTwo.hom_eq_one_of_rankFour (Q.v 0) (Q.w 0) (Q.w_mul_v_self 0)
    (Classical.choose (Classical.choose_spec Q.toOneSidedInverse_isFull))
    (Classical.choose (Classical.choose_spec
      (Classical.choose_spec Q.toOneSidedInverse_isFull)))
    (Classical.choose_spec (Classical.choose_spec
      (Classical.choose_spec Q.toOneSidedInverse_isFull))) h4 n hn f x

/-- > and the image of `B` in that copy normally generates `EL_n(R)`.

`UniversalGroupB.exists_hom_normallyGenerating`, at every `n ≥ 2`. -/
theorem manuscriptSentence_imageOfBNormallyGeneratesELn (n : ℕ) (hn : 2 ≤ n) :
    ∃ φ : UniversalGroupB.B →* elementaryGroup (Fin n) R,
      Subgroup.normalClosure (φ.range : Set (elementaryGroup (Fin n) R)) = ⊤ :=
  UniversalGroupB.exists_hom_normallyGenerating Q n hn

end RankTwo

end FullDefectRingSentences
end OneSidedMFRadical
end Manuscript
end GroupApproximation

open GroupApproximation
open GroupApproximation.Manuscript.OneSidedMFRadical

#audit_axioms FullDefectRingSentences.manuscriptSentence_ringData
#audit_axioms FullDefectRingSentences.manuscriptSentence_ringRelations
#audit_axioms FullDefectRingSentences.manuscriptSentence_groupsGandL
#audit_axioms FullDefectRingSentences.manuscriptSentence_finitelyGeneratedPropertyT
#audit_axioms FullDefectRingSentences.manuscriptSentence_compressorPieceDef
#audit_axioms FullDefectRingSentences.manuscriptSentence_compressorPieceBlock
#audit_axioms FullDefectRingSentences.manuscriptSentence_compressorMatrix
#audit_axioms FullDefectRingSentences.manuscriptSentence_compressorInvertible
#audit_axioms FullDefectRingSentences.manuscriptSentence_intertwine
#audit_axioms FullDefectRingSentences.manuscriptSentence_intertwineEntries
#audit_axioms FullDefectRingSentences.manuscriptSentence_compressesCore
#audit_axioms FullDefectRingSentences.manuscriptSentence_centralMark
#audit_axioms FullDefectRingSentences.manuscriptSentence_centralMarkCentral
#audit_axioms FullDefectRingSentences.manuscriptSentence_conjCentralMark
#audit_axioms FullDefectRingSentences.manuscriptSentence_defect
#audit_axioms FullDefectRingSentences.manuscriptSentence_normalClosureOfDefect
#audit_axioms FullDefectRingSentences.manuscriptSentence_steinbergPair
#audit_axioms FullDefectRingSentences.manuscriptSentence_fullnessRootRewrite
#audit_axioms FullDefectRingSentences.manuscriptSentence_signedPermutationsReachEveryPosition
#audit_axioms FullDefectRingSentences.manuscriptSentence_steinbergSpreadsCoefficients
#audit_axioms FullDefectRingSentences.manuscriptSentence_defectIsEverything
#audit_axioms FullDefectRingSentences.manuscriptSentence_homFromBTrivial
#audit_axioms FullDefectRingSentences.manuscriptSentence_twoCopies
#audit_axioms FullDefectRingSentences.manuscriptSentence_universalProperty
#audit_axioms FullDefectRingSentences.manuscriptSentence_imageOfB
#audit_axioms FullDefectRingSentences.manuscriptSentence_lengthTwoWords
#audit_axioms FullDefectRingSentences.manuscriptSentence_pIdem
#audit_axioms FullDefectRingSentences.manuscriptSentence_jMapDef
#audit_axioms FullDefectRingSentences.manuscriptSentence_jMapMultiplicative
#audit_axioms FullDefectRingSentences.manuscriptSentence_psiIsDiag
#audit_axioms FullDefectRingSentences.manuscriptSentence_psiOnRoots
#audit_axioms FullDefectRingSentences.manuscriptSentence_psiLandsInEL2
#audit_axioms FullDefectRingSentences.manuscriptSentence_rhoKillsGenerator
#audit_axioms FullDefectRingSentences.manuscriptSentence_generatorNormallyGeneratesEL2
#audit_axioms FullDefectRingSentences.manuscriptSentence_rhoTrivial
#audit_axioms FullDefectRingSentences.manuscriptSentence_imageOfBNormallyGeneratesEL2
#audit_axioms FullDefectRingSentences.manuscriptSentence_copyOfEL2
#audit_axioms FullDefectRingSentences.manuscriptSentence_homFromELnTrivial
#audit_axioms FullDefectRingSentences.manuscriptSentence_imageOfBNormallyGeneratesELn
