import GroupApproximation.Analysis.StrictCompressionFromPrinted
import GroupApproximation.Manuscript.OneSidedMFRadical.FullDefectRingSimple

/-!
# `cor:one-sided-ring-maximal`, first sentence

`non_mf_groups_exist.tex`, Corollary `cor:one-sided-ring-maximal`:

> If a countable unital ring `R` is not directly finite, then
> `C*_max(EL_n(R))` contains a proper isometry for every `n ≥ 4`.

and Proposition `prop:max-infinite`, whose conclusion it instantiates:

> In particular, `C*_max(G)` is not stably finite, admits no faithful tracial
> state, and is neither residually finite-dimensional nor MF.

## What this clause needs, and what it does not

This sentence is **not** a consequence of `thm:full-defect-ring`.  It does not
mention the ideal generated by `1 - st`, and it does not use the saturation of
the printed defect.  What it uses is the *compressor* alone: a property-`(T)`
subgroup `Γ ≤ EL_n(R)` and one element `u` with `uΓu⁻¹ ⊊ Γ`, the strictness
being where `st ≠ 1` is spent.  So the module is separate from
`FullDefectRingMaximal`, which carries the reduced-algebra sentence of the same
corollary and does depend on the theorem.

`Analysis/StrictCompressionFromPrinted` already turns exactly those two
hypotheses into the whole printed conclusion, with the Kazhdan set, its
tolerance and the generating set chosen internally, so
`properIsometry_of_strictCompression` below is a repackaging: it adds the
proper isometry itself to the six negative clauses, taking it from the
`ProperProjectionCompression` the datum carries.

## The one input

`OneSidedCompressorStrictContainment` is the group-theoretic content of the
printed proof, and it is the compressor calculation rather than anything
analytic:

> an explicit element `u ∈ EL₄(R)` conjugates `EL₃(R)` into itself by
> `e_{ij}(a) ↦ e_{ij}(sat)`

together with the strictness, which is the printed reason `st ≠ 1` is assumed:
every off-diagonal entry of an element of `uΓu⁻¹` has the form `s a t`, and
`(1-st)·sat = 0` because `(1-st)s = s - s(ts) = 0`, whereas `(1-st)·1 = 1-st`
is nonzero.  So `e_{01}(1) ∈ Γ \ uΓu⁻¹`.

The property-`(T)` hypothesis is stated over the finitely generated subrings of
`R`, as in `FullDefectRingCountable`, because that is what the printed proof
uses: `Γ` is the copy of `EL₃(S)` for the subring `S` generated by `s` and `t`,
which is finitely generated by construction, and `R` itself is not assumed to
be.
-/

namespace GroupApproximation
namespace Manuscript
namespace OneSidedMFRadical
namespace FullDefectRing

open scoped BigOperators

/-! ## From a strict compression to the printed conclusion -/

/-- **The printed conclusion of `prop:max-infinite`, with the proper isometry
named.**

`Analysis/StrictCompressionFromPrinted` proves the six negative clauses from
the same two hypotheses; what is added here is the first printed clause,
"`C*_max(G)` contains a proper isometry", as an explicit element with
`v*v = 1` that is not a unit. -/
theorem properIsometry_of_strictCompression {G : Type} [Group G]
    (Γ : Subgroup G) (u : G)
    (hT : HasKazhdanPropertyT.{0, 0} ↥Γ)
    (hlt : Γ.map (MulAut.conj u).toMonoidHom < Γ) :
    (∃ v : MaximalGroupCStar G, star v * v = 1 ∧ ¬ IsUnit v) ∧
      ¬ IsDedekindFiniteMonoid (MaximalGroupCStar G) ∧
      ¬ IsStablyFiniteRing (MaximalGroupCStar G) ∧
      ¬ Nonempty (FaithfulTracialState (MaximalGroupCStar G)) ∧
      ¬ IsResiduallyFiniteDimensional (MaximalGroupCStar G) ∧
      ¬ HasMFEmbedding (MaximalGroupCStar G) ∧
      ¬ IsMFAlgebra (MaximalGroupCStar G) := by
  obtain ⟨D, -⟩ :=
    MaximalCStarPrintedHypotheses.exists_strictKazhdanCompression Γ u hT hlt
  exact ⟨⟨D.toProperProjectionCompression.isometry,
      D.toProperProjectionCompression.star_isometry_mul_isometry,
      D.toProperProjectionCompression.isometry_not_isUnit⟩,
    D.maximalCStar_not_isDedekindFiniteMonoid,
    D.maximalCStar_not_isStablyFiniteRing,
    D.maximalCStar_no_faithfulTracialState,
    D.toProperProjectionCompression.not_isResiduallyFiniteDimensional,
    D.toProperProjectionCompression.not_hasMFEmbedding,
    D.toProperProjectionCompression.not_isMFAlgebra⟩

/-! ## The compressor input -/

/-- **The compressor calculation of `cor:one-sided-ring-maximal`, as a named
proposition.**

For a countable ring with a one-sided inverse pair `ts = 1 ≠ st`, every rank
`n ≥ 4` carries a property-`(T)` subgroup of `EL_n(R)` strictly compressed by a
single element.  The property-`(T)` hypothesis is asked only of the elementary
groups of the finitely generated subrings of `R`, because the subgroup the
printed proof uses is the copy of `EL₃(S)` for the subring `S` generated by `s`
and `t`.

This is the ring-theoretic half of the corollary and is the only thing the
theorem below does not prove. -/
def OneSidedCompressorStrictContainment : Prop :=
  ∀ (R : Type) [Ring R] [Countable R] (s t : R), t * s = 1 → s * t ≠ 1 →
    (∀ (S : Subring R), IsFinitelyGeneratedRing ↥S → ∀ (k : ℕ), 3 ≤ k →
        HasKazhdanPropertyT.{0, 0} (elementaryGroup (Fin k) ↥S)) →
      ∀ (n : ℕ), 4 ≤ n →
        ∃ (Γ : Subgroup (elementaryGroup (Fin n) R))
          (u : elementaryGroup (Fin n) R),
          HasKazhdanPropertyT.{0, 0} ↥Γ ∧
            Γ.map (MulAut.conj u).toMonoidHom < Γ

/-! ## The printed corollary -/

/-- **`cor:one-sided-ring-maximal`, first sentence, as one proposition.**  For
a countable unital ring that is not directly finite and every `n ≥ 4`, the
maximal group C⋆-algebra of `EL_n(R)` contains a proper isometry, and with it
the four further failures `prop:max-infinite` records. -/
def PrintedOneSidedRingMaximalIsometry : Prop :=
  ∀ (R : Type) [Ring R] [Countable R], ¬ IsDedekindFiniteMonoid R →
    ∀ (n : ℕ), 4 ≤ n →
      (∃ v : MaximalGroupCStar (elementaryGroup (Fin n) R),
          star v * v = 1 ∧ ¬ IsUnit v) ∧
        ¬ IsDedekindFiniteMonoid (MaximalGroupCStar (elementaryGroup (Fin n) R)) ∧
        ¬ IsStablyFiniteRing (MaximalGroupCStar (elementaryGroup (Fin n) R)) ∧
        ¬ Nonempty (FaithfulTracialState
          (MaximalGroupCStar (elementaryGroup (Fin n) R))) ∧
        ¬ IsResiduallyFiniteDimensional
          (MaximalGroupCStar (elementaryGroup (Fin n) R)) ∧
        ¬ HasMFEmbedding (MaximalGroupCStar (elementaryGroup (Fin n) R)) ∧
        ¬ IsMFAlgebra (MaximalGroupCStar (elementaryGroup (Fin n) R))

/-- **The printed first sentence, from the compressor calculation and the
printed Ershov--Jaikin-Zapirain input.** -/
theorem manuscriptOneSidedRingMaximalIsometry
    (hstrict : OneSidedCompressorStrictContainment)
    (hEJZ : FinitelyGeneratedRingGeneralRankElementaryPropertyT) :
    PrintedOneSidedRingMaximalIsometry := by
  intro R _ _ hdf n hn
  obtain ⟨s, t, hts, hst⟩ := exists_oneSidedInverse_of_not_isDedekindFinite hdf
  obtain ⟨Γ, u, hT, hlt⟩ :=
    hstrict R s t hts hst (fun S hfg k hk ↦ hEJZ (↥S) hfg k hk) n hn
  exact properIsometry_of_strictCompression Γ u hT hlt

/-- **The printed first sentence in prime characteristic**, with no
property-`(T)` hypothesis. -/
def PrintedOneSidedRingMaximalIsometryPrimeChar : Prop :=
  ∀ (p : ℕ), p.Prime → ∀ (R : Type) [Ring R] [Countable R] [CharP R p],
    ¬ IsDedekindFiniteMonoid R →
      ∀ (n : ℕ), 4 ≤ n →
        (∃ v : MaximalGroupCStar (elementaryGroup (Fin n) R),
            star v * v = 1 ∧ ¬ IsUnit v) ∧
          ¬ IsDedekindFiniteMonoid
            (MaximalGroupCStar (elementaryGroup (Fin n) R)) ∧
          ¬ IsStablyFiniteRing (MaximalGroupCStar (elementaryGroup (Fin n) R)) ∧
          ¬ Nonempty (FaithfulTracialState
            (MaximalGroupCStar (elementaryGroup (Fin n) R))) ∧
          ¬ IsResiduallyFiniteDimensional
            (MaximalGroupCStar (elementaryGroup (Fin n) R)) ∧
          ¬ HasMFEmbedding (MaximalGroupCStar (elementaryGroup (Fin n) R)) ∧
          ¬ IsMFAlgebra (MaximalGroupCStar (elementaryGroup (Fin n) R))

theorem manuscriptOneSidedRingMaximalIsometryPrimeChar
    (hstrict : OneSidedCompressorStrictContainment) :
    PrintedOneSidedRingMaximalIsometryPrimeChar := by
  intro p hp R _ _ _ hdf n hn
  obtain ⟨s, t, hts, hst⟩ := exists_oneSidedInverse_of_not_isDedekindFinite hdf
  obtain ⟨Γ, u, hT, hlt⟩ :=
    hstrict R s t hts hst
      (fun S hfg k hk ↦
        primeCharFinitelyGeneratedRingElementary_hasKazhdanPropertyT p hp (↥S)
          hfg k hk)
      n hn
  exact properIsometry_of_strictCompression Γ u hT hlt

end FullDefectRing
end OneSidedMFRadical
end Manuscript
end GroupApproximation
