import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceAbstractClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceAdjointCoronaHomClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceAmbientKazhdanCriterionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceAnalyticAlgebraComparisonClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceCamouflageConstructionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceCamouflageFactorizationConsequencesClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceCompressionCriterionIntroductionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceCentralizerCommutatorClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceConfigurationConsequencesClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceDefectFunctorialityClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceDoubleCommutatorExtractionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceElementaryNormalGenerationClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceImageKazhdanRadicalClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceImageNormalGenerationClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceIntroductionDefinitionsClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceIntroClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceLeavittClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceLeavittHeadlineIntroductionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceMFCamouflageClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceNormalKazhdanClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceNormalizedAlmostRepresentationClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceOneWordQuotientTailClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceOperativePureInfinitenessClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentencePQSetupClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceRankTwelveDefectHeadlineClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceRankTwelveProvenanceClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceRootDetectionChoiceClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceRootDetectionCompositionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceSimpleIntersectionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceSimpleDefectInferenceClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceShiftMatricesClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceStableFiniteProofClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceTauWhiteheadConclusionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceTauDefinitionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceTransportClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceTransportCoreSetupClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceTransportPreliminariesClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceWhiteheadEntryInsertionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.NormalKazhdanSentenceAudit
import GroupApproximation.Manuscript.OneSidedMFRadical.CorrectedCornerProjectionZeroTransport
import GroupApproximation.Manuscript.OneSidedMFRadical.CorrectedCornerProvenanceData
import GroupApproximation.Manuscript.OneSidedMFRadical.CorrectedCornerSubgroupRestriction
import GroupApproximation.Manuscript.OneSidedMFRadical.MaximalCStarTrivialCharacter
import GroupApproximation.Manuscript.OneSidedMFRadical.FaithfulCornerCoronaRepresentation
import GroupApproximation.Manuscript.OneSidedMFRadical.FaithfulCornerNormBridge
import GroupApproximation.Manuscript.OneSidedMFRadical.CorrectedCornerGramSequence
import GroupApproximation.Manuscript.OneSidedMFRadical.CorrectedCornerKazhdanQuadraticBridge
import GroupApproximation.Manuscript.OneSidedMFRadical.UnconditionalCornerTraceAssembly

/-!
# Aggregate sentence-closure audit

This module wires the Lean declarations that formalize the unchanged
manuscript's individual proof sentences.  Its sole purpose is to put every
sentence-level module in one build and axiom-audit closure.
-/
