import GroupApproximation.Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotentsCentral
import GroupApproximation.Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotentsIdeal
import GroupApproximation.Manuscript.OneSidedMFRadical.PrintedCriterion
import GroupApproximation.Manuscript.OneSidedMFRadical.FullDefectRingCore
import GroupApproximation.Leavitt.OneSidedCompressorStabilized
import GroupApproximation.Sofic.NormalKazhdanMFRadical
import GroupApproximation.Meta.AxiomGuard

/-!
# `B = ⟨L,v,c,y⟩`, the finite central `⟨z⟩`, and the compression criterion

`non_mf_groups_exist.tex`, Proposition `prop:torsion-defect-ring`, the proof:

> So `⟨z⟩` is a nontrivial finite central subgroup of `B` inside `𝔇_B(L)`, and
> Theorem `thm:compression-criterion` applied to `B` kills `z` under every
> homomorphism from `B`, hence from `EL_n(R)`, to an MF group.  Then
> `[z, e_{41}(f_{20})] = e_{41}(f_{10})`, `[e_{24}(t), e_{41}(f_{10})] = e_{21}(e)`
> are killed.

This module assembles the printed cell into that application.

## Why the criterion is run inside `B` and not inside `EL_n(R)`

`z` is *not* central in `EL_n(R)`, so `⟨z⟩` is not normal there and the
criterion, which asks for a normal Kazhdan subgroup of the defect, does not
apply.  It is central in the subgroup `B = ⟨L, v, c, y⟩` generated by exactly
the printed data, which is why the printed proof introduces `B`.  Everything
the criterion needs is then available in `B`:

* `B` is countable, being a subgroup of `EL₄(R)` over a countable ring;
* `L = EL₃(S)` sits inside `B` and has property `(T)`, transported along
  `Subgroup.subgroupOfEquivOfLe`;
* `⟨z⟩` is normal because `z` is central, and Kazhdan because it is finite
  (`z^m = 1`), by `hasKazhdanPropertyT_of_finite`;
* `⟨z⟩ ≤ 𝔇_B(L)` because `z^{-1} = [y, [vcv^{-1}, ℓ]]` and the printed defect is
  the *normal* closure of the elements `[ucu^{-1}, ℓ]`.

Nothing in the criterion needs `z ≠ 1`; that clause is what turns the
conclusion into a failure of MF-ness, and it is spent in the endpoint module.

## From `B` back to `EL_n(R)`

A homomorphism `f : EL_n(R) → M` restricts to `B` along the inclusion, so the
criterion's conclusion inside `B` says `f z = 1`.  The two printed commutators
then move that to `e_{21}(e)`, using nothing but the normality of `ker f`.
The rank-`n` statement is the rank-four one transported along the printed
"extended by `I_{n-4}`" block embedding.
-/

namespace GroupApproximation
namespace Manuscript
namespace OneSidedMFRadical
namespace TorsionComplementaryIdempotents

open GroupApproximation.OneSidedCompressor
open scoped commutatorElement

/-! ## The pointwise form of the criterion's conclusion -/

/-- An element of the manuscript's MF radical is killed by every homomorphism
to an MF group.  This is `manuscriptFullRadicalKillsMFTargets` with the
hypothesis `Rad = ⊤` weakened to membership, proved the same way. -/
theorem killed_of_mem_manuscriptCoronaMFResidual {G : Type} [Group G] [Countable G]
    {M : Type} [Group M] (hM : IsOperatorMF M) (f : G →* M) {x : G}
    (hx : x ∈ manuscriptCoronaMFResidual G) : f x = 1 := by
  letI : Countable f.range :=
    Function.Surjective.countable f.rangeRestrict_surjective
  have hRangeMF : IsOperatorMF f.range := by
    obtain ⟨X, hX, ρ, hρ⟩ := hM
    exact ⟨X, hX, ρ.comp f.range.subtype, hρ.comp (fun _ _ h ↦ Subtype.ext h)⟩
  have hRangeCDE : IsCDEOperatorMF f.range :=
    (isCDEOperatorMF_iff_isOperatorMF f.range).mpr hRangeMF
  have hRangeBot : manuscriptCoronaMFResidual f.range = ⊥ :=
    (isCDEOperatorMF_iff_manuscriptCoronaMFResidual_eq_bot).mp hRangeCDE
  have hmem : f.rangeRestrict x ∈
      (manuscriptCoronaMFResidual G).map f.rangeRestrict :=
    Subgroup.mem_map_of_mem _ hx
  have hle := map_manuscriptCoronaMFResidual_le f.rangeRestrict hmem
  rw [hRangeBot] at hle
  have hkilled : f.rangeRestrict x = 1 := by simpa using hle
  have hval := congrArg Subtype.val hkilled
  simpa using hval

/-! ## The printed group `B` -/

section FixedRing

variable {R : Type} [Ring R] (P : OneSidedInverse R)

/-- **Printed:** `B = ⟨L, v, c, y⟩`. -/
def printedB : Subgroup (elementaryGroup (Fin 4) R) :=
  Subgroup.closure ((core R : Set (elementaryGroup (Fin 4) R)) ∪
    {printedV P, printedC P, printedY P})

theorem core_le_printedB : core R ≤ printedB P := by
  calc core R = Subgroup.closure ((core R : Set (elementaryGroup (Fin 4) R))) :=
        (Subgroup.closure_eq _).symm
    _ ≤ printedB P := Subgroup.closure_mono Set.subset_union_left

theorem printedV_mem_printedB : printedV P ∈ printedB P :=
  Subgroup.subset_closure (Or.inr (by simp))

theorem printedC_mem_printedB : printedC P ∈ printedB P :=
  Subgroup.subset_closure (Or.inr (by simp))

theorem printedY_mem_printedB : printedY P ∈ printedB P :=
  Subgroup.subset_closure (Or.inr (by simp))

theorem printedEllTwoOne_mem_printedB : printedEllTwoOne R ∈ printedB P :=
  core_le_printedB P printedEllTwoOne_mem_core

/-- **Printed:** `⟨z⟩` is central in `B`, because `z` commutes with `L`, `v`,
`c` and `y`. -/
theorem printedZ_commute_printedB :
    ∀ b ∈ printedB P, Commute (printedZ P) b := by
  have hsub : printedB P ≤
      Subgroup.centralizer ({printedZ P} : Set (elementaryGroup (Fin 4) R)) := by
    rw [printedB, Subgroup.closure_le]
    rintro g (hg | hg)
    · rw [SetLike.mem_coe, Subgroup.mem_centralizer_iff]
      rintro h hh
      rw [Set.mem_singleton_iff] at hh
      subst hh
      exact printedZ_commute_core P g hg
    · rw [SetLike.mem_coe, Subgroup.mem_centralizer_iff]
      rintro h hh
      rw [Set.mem_singleton_iff] at hh
      subst hh
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
      rcases hg with rfl | rfl | rfl
      · exact printedZ_commute_printedV P
      · exact printedZ_commute_printedC P
      · exact printedZ_commute_printedY P
  intro b hb
  have hc := hsub hb
  rw [Subgroup.mem_centralizer_iff] at hc
  exact hc (printedZ P) rfl

/-- `d = e_{24}(-f_{02})` lies in `B`. -/
theorem printedDefectElt_mem_printedB : printedDefectElt P ∈ printedB P := by
  have hv := printedV_mem_printedB P
  have hc := printedC_mem_printedB P
  have hl := printedEllTwoOne_mem_printedB P
  have hx : printedV P * printedC P * (printedV P)⁻¹ ∈ printedB P :=
    (printedB P).mul_mem ((printedB P).mul_mem hv hc) ((printedB P).inv_mem hv)
  rw [← printedDefectElt_eq P, ← printedV_conj_printedC P, commutatorElement_def]
  exact (printedB P).mul_mem
    ((printedB P).mul_mem ((printedB P).mul_mem hx hl) ((printedB P).inv_mem hx))
    ((printedB P).inv_mem hl)

/-- `z` lies in `B`, because `z^{-1} = [y, d]`. -/
theorem printedZ_mem_printedB : printedZ P ∈ printedB P := by
  have hy := printedY_mem_printedB P
  have hd := printedDefectElt_mem_printedB P
  have hcomm : ⁅printedY P, printedDefectElt P⁆ ∈ printedB P := by
    rw [commutatorElement_def]
    exact (printedB P).mul_mem
      ((printedB P).mul_mem ((printedB P).mul_mem hy hd) ((printedB P).inv_mem hy))
      ((printedB P).inv_mem hd)
  rw [printedY_printedDefectElt_commutator P] at hcomm
  simpa using (printedB P).inv_mem hcomm

/-- `z` as an element of `B`. -/
def printedBZ : ↥(printedB P) := ⟨printedZ P, printedZ_mem_printedB P⟩

/-- The printed core, as a subgroup of `B`. -/
def coreOfB : Subgroup ↥(printedB P) := (core R).subgroupOf (printedB P)

theorem printedBZ_central (b : ↥(printedB P)) : Commute (printedBZ P) b :=
  Subtype.ext (printedZ_commute_printedB P b b.2)

instance printedBZ_zpowers_normal :
    (Subgroup.zpowers (printedBZ P)).Normal := by
  constructor
  intro x hx g
  obtain ⟨k, rfl⟩ := hx
  have hc : printedBZ P ^ k * g = g * printedBZ P ^ k :=
    (printedBZ_central P g).zpow_left k
  have hconj : g * printedBZ P ^ k * g⁻¹ = printedBZ P ^ k := by
    rw [← hc, mul_assoc, mul_inv_cancel, mul_one]
  rw [hconj]
  exact Subgroup.zpow_mem _ (Subgroup.mem_zpowers _) k

/-- **Printed:** `⟨z⟩` is finite, because `z^m = 1`. -/
theorem printedBZ_zpowers_finite {m : ℕ} (hm : 0 < m) (hz : m • P.e = 0) :
    Finite ↥(Subgroup.zpowers (printedBZ P)) := by
  have hpow : printedBZ P ^ m = 1 :=
    Subtype.ext (by
      show printedZ P ^ m = 1
      exact printedZ_pow_eq_one P hz)
  have hfo : IsOfFinOrder (printedBZ P) :=
    isOfFinOrder_iff_pow_eq_one.mpr ⟨m, hm, hpow⟩
  exact Set.Finite.to_subtype hfo.finite_zpowers

/-- Property `(T)` for the printed core read inside `B`. -/
theorem coreOfB_hasKazhdanPropertyT
    (hT : HasKazhdanPropertyT.{0, 0} (elementaryGroup (Fin 3) R)) :
    HasKazhdanPropertyT.{0, 0} ↥(coreOfB P) :=
  HasKazhdanPropertyT.of_mulEquiv
    (Subgroup.subgroupOfEquivOfLe (core_le_printedB P))
    (core_hasKazhdanPropertyT hT)

/-- **Printed:** `z ∈ 𝔇_B(L)`, from `d = [vcv^{-1}, ℓ]` and `z^{-1} = [y, d]`. -/
theorem printedBZ_mem_printedDefect :
    printedBZ P ∈ printedDefect (coreOfB P) := by
  set v' : ↥(printedB P) := ⟨printedV P, printedV_mem_printedB P⟩
  set c' : ↥(printedB P) := ⟨printedC P, printedC_mem_printedB P⟩
  set y' : ↥(printedB P) := ⟨printedY P, printedY_mem_printedB P⟩
  set l' : ↥(printedB P) := ⟨printedEllTwoOne R, printedEllTwoOne_mem_printedB P⟩
  have hvcomp : ∀ δ ∈ coreOfB P, v' * δ * v'⁻¹ ∈ coreOfB P := by
    intro δ hδ
    rw [coreOfB, Subgroup.mem_subgroupOf] at hδ ⊢
    exact printedV_compresses_core P _ hδ
  have hccomm : ∀ δ ∈ coreOfB P, Commute c' δ := by
    intro δ hδ
    rw [coreOfB, Subgroup.mem_subgroupOf] at hδ
    exact Subtype.ext (printedC_commute_core P _ hδ)
  have hlmem : l' ∈ coreOfB P := by
    rw [coreOfB, Subgroup.mem_subgroupOf]
    exact printedEllTwoOne_mem_core
  have hd : ⁅v' * c' * v'⁻¹, l'⁆ ∈ printedDefect (coreOfB P) :=
    printedDefect_generator_mem (coreOfB P) hvcomp hccomm hlmem
  have hyd : y' * ⁅v' * c' * v'⁻¹, l'⁆ * y'⁻¹ * (⁅v' * c' * v'⁻¹, l'⁆)⁻¹
      ∈ printedDefect (coreOfB P) :=
    commutatorRight_mem y' hd
  have hval : y' * ⁅v' * c' * v'⁻¹, l'⁆ * y'⁻¹ * (⁅v' * c' * v'⁻¹, l'⁆)⁻¹
      = (printedBZ P)⁻¹ := by
    refine Subtype.ext ?_
    show printedY P * ⁅printedV P * printedC P * (printedV P)⁻¹,
        printedEllTwoOne R⁆ * (printedY P)⁻¹ *
        (⁅printedV P * printedC P * (printedV P)⁻¹, printedEllTwoOne R⁆)⁻¹
      = (printedZ P)⁻¹
    rw [printedV_conj_printedC P, printedDefectElt_eq P, ← commutatorElement_def,
      printedY_printedDefectElt_commutator P]
  rw [hval] at hyd
  simpa using (printedDefect (coreOfB P)).inv_mem hyd

/-! ## The criterion, applied -/

/-- **Printed:** every homomorphism from `EL₄(R)` to an MF group kills `z`. -/
theorem printedZ_killed [Countable R]
    (hT : HasKazhdanPropertyT.{0, 0} (elementaryGroup (Fin 3) R))
    {m : ℕ} (hm : 0 < m) (hme : m • P.e = 0)
    {M : Type} [Group M] (hM : IsOperatorMF M)
    (f : elementaryGroup (Fin 4) R →* M) : f (printedZ P) = 1 := by
  haveI : Countable (elementaryGroup (Fin 4) R) :=
    FullDefectRing.countable_elementaryGroup
  haveI : Countable ↥(printedB P) := Subtype.countable
  haveI : Finite ↥(Subgroup.zpowers (printedBZ P)) :=
    printedBZ_zpowers_finite P hm hme
  have hKT : HasKazhdanPropertyT.{0, 0} ↥(Subgroup.zpowers (printedBZ P)) :=
    hasKazhdanPropertyT_of_finite _
  have hKD : Subgroup.zpowers (printedBZ P) ≤ printedDefect (coreOfB P) :=
    Subgroup.zpowers_le.mpr (printedBZ_mem_printedDefect P)
  have hres := (manuscriptOneSidedCompressionCriterion ↥(printedB P) (coreOfB P)
      (coreOfB_hasKazhdanPropertyT P hT)).1 (Subgroup.zpowers (printedBZ P))
      hKT hKD
  have hmemres : printedBZ P ∈ manuscriptCoronaMFResidual ↥(printedB P) :=
    hres (Subgroup.mem_zpowers _)
  exact killed_of_mem_manuscriptCoronaMFResidual hM
    (f.comp (printedB P).subtype) hmemres

/-- **Printed:** `[z, e_{41}(f_{20})] = e_{41}(f_{10})` and
`[e_{24}(t), e_{41}(f_{10})] = e_{21}(e)` are killed too. -/
theorem printedE21_killed [Countable R]
    (hT : HasKazhdanPropertyT.{0, 0} (elementaryGroup (Fin 3) R))
    {m : ℕ} (hm : 0 < m) (hme : m • P.e = 0)
    {M : Type} [Group M] (hM : IsOperatorMF M)
    (f : elementaryGroup (Fin 4) R →* M) :
    f (elementaryRoot (coreIdx 1) (coreIdx 0)
        (coreIdx_injective.ne oneNeZeroFin) P.e) = 1 := by
  have hz : printedZ P ∈ f.ker :=
    MonoidHom.mem_ker.mpr (printedZ_killed P hT hm hme hM f)
  have h41 : elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0) (fUnit P 1 0)
      ∈ f.ker := by
    have := commutatorLeft_mem (N := f.ker) hz
      (elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0) (fUnit P 2 0))
    rwa [← commutatorElement_def, printedZ_commutator_root P] at this
  have h21 := commutatorRight_mem (N := f.ker)
    (elementaryRoot (coreIdx 1) lastIdx (coreIdx_ne_last 1) P.t) h41
  rw [← commutatorElement_def, printedT_commutator_root P] at h21
  exact MonoidHom.mem_ker.mp h21

/-! ## The rank-`n` form -/

/-- **The printed rank-`n` conclusion at a fixed ring.**  For every `n ≥ 4`,
every homomorphism from `EL_n(R)` to an MF group kills the printed
`e_{21}(e)`. -/
theorem printedE21_killed_rank [Countable R]
    (hT : HasKazhdanPropertyT.{0, 0} (elementaryGroup (Fin 3) R))
    {m : ℕ} (hm : 0 < m) (hme : m • P.e = 0)
    {n : ℕ} (hn : 4 ≤ n) {M : Type} [Group M] (hM : IsOperatorMF M)
    (f : elementaryGroup (Fin n) R →* M) :
    f (elementaryRoot (bigIdx hn (coreIdx 1)) (bigIdx hn (coreIdx 0))
        ((bigIdx_injective hn).ne (coreIdx_injective.ne oneNeZeroFin)) P.e) = 1 := by
  have h := printedE21_killed P hT hm hme hM (f.comp (blockEmbedding (R := R) hn))
  rwa [MonoidHom.comp_apply, blockEmbedding_elementaryRoot] at h

end FixedRing

end TorsionComplementaryIdempotents
end OneSidedMFRadical
end Manuscript
end GroupApproximation
