import GroupApproximation.Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents
import GroupApproximation.Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotentsSignedPermutations
import GroupApproximation.Meta.AxiomGuard

/-!
# The proof of `prop:torsion-defect-ring`, sentence by sentence

`non_mf_groups_exist.tex`, Proposition `prop:torsion-defect-ring` (tex lines
1072--1120).  One closed `manuscriptSentence_*` theorem per printed sentence of the
proof, stated at the printed generality and proved along the printed route, citing
the declarations of the modules

* `TorsionComplementaryIdempotentsMatrixUnits` (`f_{ij}`),
* `TorsionComplementaryIdempotentsWeyl` (`w_{ij}`, `r`),
* `TorsionComplementaryIdempotentsDiagonal` (`D(a)`),
* `TorsionComplementaryIdempotentsCell` (`v`, `c`, `y`, `z`, `ℓ`),
* `TorsionComplementaryIdempotentsCentral` (`d`, `[y,d]`, the order of `z`),
* `TorsionComplementaryIdempotentsDefect` (`B`, the criterion applied to `B`),
* `TorsionComplementaryIdempotentsSignedPermutations` (the Steinberg relations and
  signed permutations),
* `TorsionComplementaryIdempotents` (the printed proposition).

Coordinates are 0-indexed as everywhere in `OneSidedCompressor`: the printed
coordinates `1,2,3` are `coreIdx 0, coreIdx 1, coreIdx 2`, the printed fourth is
`lastIdx`.  The printed `S` is `Subring.closure {s, t}` and the printed pair inside
it is `pairSubringInverse s t hts`; the printed passage from `EL₄(S)` to `EL_n(R)`
is `pairToRank`, the block embedding followed by the coefficient inclusion.
-/

namespace GroupApproximation
namespace Manuscript
namespace OneSidedMFRadical
namespace TorsionComplementaryIdempotents

open GroupApproximation.OneSidedCompressor
open scoped commutatorElement

/-! ## The printed `S`, the pair inside it, and the passage to `EL_n(R)` -/

/-- **Printed:** "let `S` be the unital subring generated by `s,t`"; the printed pair
`s, t` with `ts = 1`, read inside `S`. -/
def pairSubringInverse {R : Type} [Ring R] (s t : R) (hts : t * s = 1) :
    OneSidedInverse ↥(Subring.closure ({s, t} : Set R)) :=
  ⟨⟨s, Subring.subset_closure (by simp)⟩, ⟨t, Subring.subset_closure (by simp)⟩,
    Subtype.ext hts⟩

theorem pairSubringInverse_e_coe {R : Type} [Ring R] (s t : R) (hts : t * s = 1) :
    (((pairSubringInverse s t hts).e : ↥(Subring.closure ({s, t} : Set R))) : R)
      = 1 - s * t := by
  rw [OneSidedInverse.e_eq]
  push_cast
  rfl

theorem pairSubringInverse_nsmul_e {R : Type} [Ring R] (s t : R) (hts : t * s = 1)
    {m : ℕ} (hme : m • (1 - s * t) = 0) : m • (pairSubringInverse s t hts).e = 0 := by
  refine Subtype.ext ?_
  have hcoe : ((m • (pairSubringInverse s t hts).e : ↥(Subring.closure ({s, t} : Set R))) : R)
      = m • (((pairSubringInverse s t hts).e : ↥(Subring.closure ({s, t} : Set R))) : R) := by
    simp
  rw [hcoe, pairSubringInverse_e_coe, hme]
  simp

/-- The printed passage from `EL₄(S)` to `EL_n(R)`: "extended by `I_{n-4}`", then the
coefficient inclusion `S → R`. -/
noncomputable def pairToRank {R : Type} [Ring R] (s t : R) {n : ℕ} (hn : 4 ≤ n) :
    elementaryGroup (Fin 4) ↥(Subring.closure ({s, t} : Set R)) →*
      elementaryGroup (Fin n) R :=
  (elementaryGroupMap (ι := Fin n) (Subring.closure ({s, t} : Set R)).subtype).comp
    (blockEmbedding (R := ↥(Subring.closure ({s, t} : Set R))) hn)

/-! ## Two facts about `B` the printed proof uses implicitly -/

section FixedRing

variable {R : Type} [Ring R] (P : OneSidedInverse R)

/-- **Printed:** `d = [vcv^{-1}, ℓ]` lies in `𝔇_B(L)`. -/
theorem printedDefectElt_mem_printedDefect :
    (⟨printedDefectElt P, printedDefectElt_mem_printedB P⟩ : ↥(printedB P)) ∈
      printedDefect (coreOfB P) := by
  set v' : ↥(printedB P) := ⟨printedV P, printedV_mem_printedB P⟩
  set c' : ↥(printedB P) := ⟨printedC P, printedC_mem_printedB P⟩
  set l' : ↥(printedB P) := ⟨printedEllTwoOne R, printedEllTwoOne_mem_printedB P⟩
  have hvcomp : ∀ δ ∈ coreOfB P, v' * δ * v'⁻¹ ∈ coreOfB P := by
    intro δ hδ
    rw [coreOfB, Subgroup.mem_subgroupOf] at hδ ⊢
    exact printedV_compresses_core P _ hδ
  have hccomm : ∀ δ ∈ coreOfB P, Commute c' δ := by
    intro δ hδ
    rw [coreOfB, Subgroup.mem_subgroupOf] at hδ
    exact Subtype.ext (printedC_commute_core P _ hδ)
  have hlmem : l' ∈ coreOfB P := by
    rw [coreOfB, Subgroup.mem_subgroupOf]
    exact printedEllTwoOne_mem_core
  have hd : ⁅v' * c' * v'⁻¹, l'⁆ ∈ printedDefect (coreOfB P) :=
    printedDefect_generator_mem (coreOfB P) hvcomp hccomm hlmem
  have hval : ⁅v' * c' * v'⁻¹, l'⁆ =
      (⟨printedDefectElt P, printedDefectElt_mem_printedB P⟩ : ↥(printedB P)) := by
    refine Subtype.ext ?_
    show ⁅printedV P * printedC P * (printedV P)⁻¹, printedEllTwoOne R⁆ = printedDefectElt P
    rw [printedV_conj_printedC P, printedDefectElt_eq P]
  rwa [hval] at hd

/-- **Printed:** "Theorem `thm:compression-criterion` applied to `B` kills `z` under
every homomorphism from `B` … to an MF group." -/
theorem printedBZ_killed [Countable R]
    (hT : HasKazhdanPropertyT.{0, 0} (elementaryGroup (Fin 3) R))
    {m : ℕ} (hm : 0 < m) (hme : m • P.e = 0)
    {M : Type} [Group M] (hM : IsOperatorMF M) (f : ↥(printedB P) →* M) :
    f (printedBZ P) = 1 := by
  haveI : Countable (elementaryGroup (Fin 4) R) :=
    FullDefectRing.countable_elementaryGroup
  haveI : Countable ↥(printedB P) := Subtype.countable
  haveI : Finite ↥(Subgroup.zpowers (printedBZ P)) :=
    printedBZ_zpowers_finite P hm hme
  have hKT : HasKazhdanPropertyT.{0, 0} ↥(Subgroup.zpowers (printedBZ P)) :=
    hasKazhdanPropertyT_of_finite _
  have hKD : Subgroup.zpowers (printedBZ P) ≤ printedDefect (coreOfB P) :=
    Subgroup.zpowers_le.mpr (printedBZ_mem_printedDefect P)
  have hres := (manuscriptOneSidedCompressionCriterion ↥(printedB P) (coreOfB P)
      (coreOfB_hasKazhdanPropertyT P hT)).1 (Subgroup.zpowers (printedBZ P)) hKT hKD
  exact killed_of_mem_manuscriptCoronaMFResidual hM f (hres (Subgroup.mem_zpowers _))

end FixedRing

/-! ## The sentences -/

/-- > If `e=0`, then `ReR=0` and `EL_n(R,ReR)=1`, so assume `e≠0`.

(tex line 1084) -/
theorem manuscriptSentence_zeroIdempotentCase :
    ∀ (R : Type) [Ring R] (s t : R) (n : ℕ), (1 : R) - s * t = 0 →
      TwoSidedIdeal.span ({1 - s * t} : Set R) = ⊥ ∧
        relativeElementary (Fin n) (TwoSidedIdeal.span ({1 - s * t} : Set R)) = ⊥ := by
  intro R _ s t n he
  rw [he]
  exact ⟨twoSidedIdeal_span_zero, relativeElementary_span_zero⟩

/-- > Let `S` be the unital subring generated by `s,t`, and let `L=EL_3(S)` occupy
> coordinates `1,2,3` of `EL_4(S)`; it has property (T) [EJZ, Theorem 1.1].

(tex lines 1085--1087)  `S` is finitely generated and Ershov--Jaikin-Zapirain is
proved in this repository, at rank three over `S`, then transported to the core. -/
theorem manuscriptSentence_pairSubringCoreKazhdan :
    ∀ (R : Type) [Ring R] (s t : R),
      HasKazhdanPropertyT.{0, 0} ↥(core ↥(Subring.closure ({s, t} : Set R))) := by
  intro R _ s t
  exact core_hasKazhdanPropertyT
    (NonMFSentences.HeadlineCitationSentences.manuscriptSentence_pairSubringElementaryPropertyT
      R s t).2

/-- > The criterion is applied to a subgroup `B ≤ EL_4(S)` with a central element of
> finite order inside `𝔇_B(L)`.

(tex lines 1087--1089)  At every one-sided inverse pair with `me = 0`, `m > 0`. -/
theorem manuscriptSentence_centralFiniteOrderInDefect :
    ∀ (R : Type) [Ring R] (P : OneSidedInverse R) (m : ℕ), 0 < m → m • P.e = 0 →
      ∃ z : ↥(printedB P), (∀ b : ↥(printedB P), Commute z b) ∧ IsOfFinOrder z ∧
        z ∈ printedDefect (coreOfB P) := by
  intro R _ P m hm hme
  refine ⟨printedBZ P, printedBZ_central P, ?_, printedBZ_mem_printedDefect P⟩
  exact isOfFinOrder_iff_pow_eq_one.mpr ⟨m, hm, Subtype.ext (printedZ_pow_eq_one P hme)⟩

/-- > Put `f_{ij}=s^iet^j`.  Since `es=te=0`, `f_{ij}f_{kl}=δ_{jk}f_{il}`, so
> `f_{ij}^2=0` for `i≠j`.

(tex lines 1089--1091) -/
theorem manuscriptSentence_matrixUnits :
    ∀ (R : Type) [Ring R] (P : OneSidedInverse R),
      (∀ i j : ℕ, fUnit P i j = P.s ^ i * P.e * P.t ^ j) ∧
        P.e * P.s = 0 ∧ P.t * P.e = 0 ∧
        (∀ i j k l : ℕ, fUnit P i j * fUnit P k l = if j = k then fUnit P i l else 0) ∧
        ∀ i j : ℕ, i ≠ j → fUnit P i j * fUnit P i j = 0 :=
  fun _ _ P ↦ ⟨fUnit_def P, P.e_mul_s, P.t_mul_e, fUnit_mul P,
    fun _ _ h ↦ fUnit_mul_self P h⟩

/-- > Write `D(a)=diag(1,1,1,a)`; for `i≠j`,
> `D(1±f_{ij})=[e_{41}(f_{ii}),e_{14}(±f_{ij})]` lies in `EL_4(S)`.

(tex lines 1091--1092)  The commutators are elements of `EL₄` by construction. -/
theorem manuscriptSentence_diagonalCommutators :
    ∀ (R : Type) [Ring R] (P : OneSidedInverse R) (i j : ℕ), i ≠ j →
      (((⁅elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0) (fUnit P i i),
          elementaryRoot (coreIdx 0) lastIdx (coreIdx_ne_last 0) (fUnit P i j)⁆ :
          elementaryGroup (Fin 4) R) : (Matrix (Fin 4) (Fin 4) R)ˣ) :
          Matrix (Fin 4) (Fin 4) R) = lastDiag (1 + fUnit P i j) ∧
      (((⁅elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0) (fUnit P i i),
          elementaryRoot (coreIdx 0) lastIdx (coreIdx_ne_last 0) (-fUnit P i j)⁆ :
          elementaryGroup (Fin 4) R) : (Matrix (Fin 4) (Fin 4) R)ˣ) :
          Matrix (Fin 4) (Fin 4) R) = lastDiag (1 - fUnit P i j) :=
  fun _ _ P _ _ h ↦ ⟨diagPlus_matrix P h, diagMinus_matrix P h⟩

/-- > Let `u` be the compressor of Lemma `lem:ring-compression-cell`, put
> `w_{ij}=(1+f_{ji})(1-f_{ij})(1+f_{ji})`, `r=w_{14}w_{25}`, and `v=uD(r)`.

(tex lines 1093--1094)  `compressor P` is the `u` of
`RankFourCompressionCellPrinted.manuscriptRankFourCompressionCell`, with the displayed
matrix. -/
theorem manuscriptSentence_compressorWeylAndV :
    ∀ (R : Type) [Ring R] (P : OneSidedInverse R),
      ((compressor P : (Matrix (Fin 4) (Fin 4) R)ˣ) : Matrix (Fin 4) (Fin 4) R) =
          compressorMatrix P ∧
        (∀ (i j : ℕ) (hij : i ≠ j), ((weylUnit P hij : Rˣ) : R) =
          (1 + fUnit P j i) * (1 - fUnit P i j) * (1 + fUnit P j i)) ∧
        rUnit P = weylUnit P one_ne_four * weylUnit P two_ne_five ∧
        ((printedV P : (Matrix (Fin 4) (Fin 4) R)ˣ) : Matrix (Fin 4) (Fin 4) R) =
          compressorMatrix P * lastDiag ((rUnit P : Rˣ) : R) := by
  intro R _ P
  refine ⟨compressor_val P, fun _ _ hij ↦ weylUnit_val_word P hij, rfl, ?_⟩
  rw [printedV, elementaryGroup_val_mul, compressor_val, diagR_matrix]

/-- > Since `D(r)` centralizes `L`, `vLv^{-1}≤L`.

(tex line 1095) -/
theorem manuscriptSentence_vCompressesCore :
    ∀ (R : Type) [Ring R] (P : OneSidedInverse R),
      (∀ g ∈ core R, Commute (diagR P) g) ∧
        ∀ g ∈ core R, printedV P * g * (printedV P)⁻¹ ∈ core R :=
  fun _ _ P ↦ ⟨diagR_commute_core P, printedV_compresses_core P⟩

/-- > Put `c=D(1+f_{02})`, `y=e_{42}(f_{10})`, `z=D(1+f_{12})`, `ℓ=e_{21}(1)`,
> `B=⟨L,v,c,y⟩`.

(tex lines 1095--1099) -/
theorem manuscriptSentence_printedCell :
    ∀ (R : Type) [Ring R] (P : OneSidedInverse R),
      ((printedC P : (Matrix (Fin 4) (Fin 4) R)ˣ) : Matrix (Fin 4) (Fin 4) R) =
          lastDiag (1 + fUnit P 0 2) ∧
        printedY P = elementaryRoot lastIdx (coreIdx 1) (last_ne_coreIdx 1) (fUnit P 1 0) ∧
        ((printedZ P : (Matrix (Fin 4) (Fin 4) R)ˣ) : Matrix (Fin 4) (Fin 4) R) =
          lastDiag (1 + fUnit P 1 2) ∧
        printedEllTwoOne R =
          elementaryRoot (coreIdx 1) (coreIdx 0) (coreIdx_injective.ne oneNeZeroFin) 1 ∧
        printedB P = Subgroup.closure ((core R : Set (elementaryGroup (Fin 4) R)) ∪
          {printedV P, printedC P, printedY P}) :=
  fun _ _ P ↦ ⟨printedC_matrix P, rfl, printedZ_matrix P, rfl, rfl⟩

/-- > Then `c∈C_B(L)`, and from `rf_{02}r^{-1}=f_{05}`, `rf_{12}r^{-1}=f_{45}`,
> `f_{02}t^3=f_{05}`, and `t^3f_{45}=f_{12}t^3`, direct multiplication with the
> displayed `u` gives `vcv^{-1}=e_{14}(f_{02})` and `vzv^{-1}=z`.

(tex lines 1100--1102) -/
theorem manuscriptSentence_conjugationsByV :
    ∀ (R : Type) [Ring R] (P : OneSidedInverse R),
      (⟨printedC P, printedC_mem_printedB P⟩ : ↥(printedB P)) ∈
          Subgroup.centralizer ((coreOfB P : Subgroup ↥(printedB P)) : Set ↥(printedB P)) ∧
        ((rUnit P : Rˣ) : R) * fUnit P 0 2 * (((rUnit P)⁻¹ : Rˣ) : R) = fUnit P 0 5 ∧
        ((rUnit P : Rˣ) : R) * fUnit P 1 2 * (((rUnit P)⁻¹ : Rˣ) : R) = fUnit P 4 5 ∧
        fUnit P 0 2 * P.t ^ 3 = fUnit P 0 5 ∧
        P.t ^ 3 * fUnit P 4 5 = fUnit P 1 2 * P.t ^ 3 ∧
        printedV P * printedC P * (printedV P)⁻¹ =
          elementaryRoot (coreIdx 0) lastIdx (coreIdx_ne_last 0) (fUnit P 0 2) ∧
        printedV P * printedZ P * (printedV P)⁻¹ = printedZ P := by
  intro R _ P
  refine ⟨?_, rUnit_conj_fUnit_zero_two P, rUnit_conj_fUnit_one_two P,
    fUnit_zero_two_mul_t_cube P, t_cube_mul_fUnit_four_five P,
    printedV_conj_printedC P, printedV_conj_printedZ P⟩
  rw [Subgroup.mem_centralizer_iff]
  intro h hh
  rw [SetLike.mem_coe, coreOfB, Subgroup.mem_subgroupOf] at hh
  exact Subtype.ext (printedC_commute_core P _ hh).symm.eq

/-- > So `d=[vcv^{-1},ℓ]=e_{24}(-f_{02})` lies in `𝔇_B(L)`, and
> `[y,d]=D(1-f_{12})=z^{-1}` since `f_{02}f_{10}=0` and `f_{10}f_{02}=f_{12}`;
> hence `z∈𝔇_B(L)`.

(tex lines 1102--1105) -/
theorem manuscriptSentence_defectElementAndZ :
    ∀ (R : Type) [Ring R] (P : OneSidedInverse R),
      ⁅printedV P * printedC P * (printedV P)⁻¹, printedEllTwoOne R⁆ = printedDefectElt P ∧
        (⟨printedDefectElt P, printedDefectElt_mem_printedB P⟩ : ↥(printedB P)) ∈
          printedDefect (coreOfB P) ∧
        fUnit P 0 2 * fUnit P 1 0 = 0 ∧ fUnit P 1 0 * fUnit P 0 2 = fUnit P 1 2 ∧
        (((⁅printedY P, printedDefectElt P⁆ : elementaryGroup (Fin 4) R) :
            (Matrix (Fin 4) (Fin 4) R)ˣ) : Matrix (Fin 4) (Fin 4) R) =
          lastDiag (1 - fUnit P 1 2) ∧
        ⁅printedY P, printedDefectElt P⁆ = (printedZ P)⁻¹ ∧
        printedBZ P ∈ printedDefect (coreOfB P) := by
  intro R _ P
  refine ⟨?_, printedDefectElt_mem_printedDefect P, fUnit_mul_of_ne P 0 0 (by decide),
    fUnit_mul_of_eq P 1 0 2, ?_, printedY_printedDefectElt_commutator P,
    printedBZ_mem_printedDefect P⟩
  · rw [printedV_conj_printedC P, printedDefectElt_eq P]
  · have hyx : -fUnit P 0 2 * fUnit P 1 0 = 0 := by
      rw [neg_mul, fUnit_mul_of_ne P 0 0 (by decide), neg_zero]
    have h := commutator_last_eq_lastDiag (R := R) (last_ne_coreIdx 1) hyx
    rw [mul_neg, fUnit_mul_of_eq P 1 0 2, ← sub_eq_add_neg] at h
    exact h

/-- > The element `z` commutes with `L` and `v`, and with `c` and `y` because
> `f_{12}f_{02}=f_{02}f_{12}=f_{12}f_{10}=0`, so `⟨z⟩` is central in `B`.

(tex lines 1105--1107) -/
theorem manuscriptSentence_zCentral :
    ∀ (R : Type) [Ring R] (P : OneSidedInverse R),
      (∀ g ∈ core R, Commute (printedZ P) g) ∧ Commute (printedZ P) (printedV P) ∧
        fUnit P 1 2 * fUnit P 0 2 = 0 ∧ fUnit P 0 2 * fUnit P 1 2 = 0 ∧
        fUnit P 1 2 * fUnit P 1 0 = 0 ∧
        Commute (printedZ P) (printedC P) ∧ Commute (printedZ P) (printedY P) ∧
        Subgroup.zpowers (printedBZ P) ≤ Subgroup.center ↥(printedB P) := by
  intro R _ P
  refine ⟨printedZ_commute_core P, printedZ_commute_printedV P,
    fUnit_mul_of_ne P 1 2 (by decide), fUnit_mul_of_ne P 0 2 (by decide),
    fUnit_mul_of_ne P 1 0 (by decide), printedZ_commute_printedC P,
    printedZ_commute_printedY P, ?_⟩
  rw [Subgroup.zpowers_le, Subgroup.mem_center_iff]
  intro b
  exact (printedBZ_central P b).symm.eq

/-- > If `me=0` then `z^m=D(1+mf_{12})=1`, and `z≠1` because `tf_{12}s^2=e≠0`.

(tex lines 1107--1108) -/
theorem manuscriptSentence_zOrderAndNontrivial :
    ∀ (R : Type) [Ring R] (P : OneSidedInverse R) (m : ℕ),
      (((printedZ P ^ m : elementaryGroup (Fin 4) R) : (Matrix (Fin 4) (Fin 4) R)ˣ) :
          Matrix (Fin 4) (Fin 4) R) = lastDiag (1 + m • fUnit P 1 2) ∧
        (m • P.e = 0 → printedZ P ^ m = 1) ∧
        P.t * fUnit P 1 2 * P.s ^ 2 = P.e ∧
        (P.e ≠ 0 → printedZ P ≠ 1) := by
  intro R _ P m
  refine ⟨?_, printedZ_pow_eq_one P, t_mul_fUnit_one_two_mul_s_sq P, printedZ_ne_one P⟩
  rw [elementaryGroup_val_pow, printedZ_matrix, lastDiag_pow,
    one_add_pow_of_sq_zero (fUnit_mul_self P (by decide : (1 : ℕ) ≠ 2)) m]

/-- > So `⟨z⟩` is a nontrivial finite central subgroup of `B` inside `𝔇_B(L)`, and
> Theorem `thm:compression-criterion` applied to `B` kills `z` under every
> homomorphism from `B`, hence from `EL_n(R)`, to an MF group.

(tex lines 1108--1112)  At the printed `S`, for every countable ring `R`. -/
theorem manuscriptSentence_criterionKillsCentralElement :
    ∀ (R : Type) [Ring R] [Countable R] (s t : R) (hts : t * s = 1) (m : ℕ), 0 < m →
      m • (1 - s * t) = 0 →
        (Subgroup.zpowers (printedBZ (pairSubringInverse s t hts))).Normal ∧
        Finite ↥(Subgroup.zpowers (printedBZ (pairSubringInverse s t hts))) ∧
        ((1 : R) - s * t ≠ 0 →
          Subgroup.zpowers (printedBZ (pairSubringInverse s t hts)) ≠ ⊥) ∧
        Subgroup.zpowers (printedBZ (pairSubringInverse s t hts)) ≤
          printedDefect (coreOfB (pairSubringInverse s t hts)) ∧
        (∀ (M : Type) [Group M], IsOperatorMF M →
          ∀ f : ↥(printedB (pairSubringInverse s t hts)) →* M,
            f (printedBZ (pairSubringInverse s t hts)) = 1) ∧
        ∀ (n : ℕ) (hn : 4 ≤ n) (M : Type) [Group M], IsOperatorMF M →
          ∀ f : elementaryGroup (Fin n) R →* M,
            f (pairToRank s t hn (printedZ (pairSubringInverse s t hts))) = 1 := by
  intro R _ _ s t hts m hm hme
  haveI : Countable ↥(Subring.closure ({s, t} : Set R)) := Subtype.countable
  have hT :=
    (NonMFSentences.HeadlineCitationSentences.manuscriptSentence_pairSubringElementaryPropertyT
      R s t).2
  have hmeS := pairSubringInverse_nsmul_e s t hts hme
  refine ⟨printedBZ_zpowers_normal _, printedBZ_zpowers_finite _ hm hmeS, ?_,
    Subgroup.zpowers_le.mpr (printedBZ_mem_printedDefect _),
    fun M _ hM f ↦ printedBZ_killed _ hT hm hmeS hM f,
    fun n hn M _ hM f ↦ printedZ_killed _ hT hm hmeS hM (f.comp (pairToRank s t hn))⟩
  intro he hbot
  have heS : (pairSubringInverse s t hts).e ≠ 0 := by
    intro h0
    apply he
    rw [← pairSubringInverse_e_coe s t hts, h0]
    simp
  rw [Subgroup.zpowers_eq_bot] at hbot
  exact printedZ_ne_one _ heS (congrArg Subtype.val hbot)

/-- > Then `[z,e_{41}(f_{20})]=e_{41}(f_{10})`, `[e_{24}(t),e_{41}(f_{10})]=e_{21}(e)`
> are killed,

(tex lines 1112--1117)  The two identities over every one-sided inverse pair, and the
killing at the printed `S`, in `EL_n(R)`. -/
theorem manuscriptSentence_twoCommutatorsKilled :
    (∀ (R : Type) [Ring R] (P : OneSidedInverse R),
      ⁅printedZ P, elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0) (fUnit P 2 0)⁆ =
          elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0) (fUnit P 1 0) ∧
        ⁅elementaryRoot (coreIdx 1) lastIdx (coreIdx_ne_last 1) P.t,
          elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0) (fUnit P 1 0)⁆ =
          elementaryRoot (coreIdx 1) (coreIdx 0) (coreIdx_injective.ne oneNeZeroFin) P.e) ∧
    ∀ (R : Type) [Ring R] [Countable R] (s t : R) (hts : t * s = 1) (m : ℕ), 0 < m →
      m • (1 - s * t) = 0 → ∀ (n : ℕ) (hn : 4 ≤ n) (M : Type) [Group M], IsOperatorMF M →
        ∀ f : elementaryGroup (Fin n) R →* M,
          f (pairToRank s t hn (elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0)
              (fUnit (pairSubringInverse s t hts) 1 0))) = 1 ∧
          f (pairToRank s t hn (elementaryRoot (coreIdx 1) (coreIdx 0)
              (coreIdx_injective.ne oneNeZeroFin) (pairSubringInverse s t hts).e)) = 1 := by
  refine ⟨fun _ _ P ↦ ⟨printedZ_commutator_root P, printedT_commutator_root P⟩, ?_⟩
  intro R _ _ s t hts m hm hme n hn M _ hM f
  haveI : Countable ↥(Subring.closure ({s, t} : Set R)) := Subtype.countable
  have hT :=
    (NonMFSentences.HeadlineCitationSentences.manuscriptSentence_pairSubringElementaryPropertyT
      R s t).2
  have hmeS := pairSubringInverse_nsmul_e s t hts hme
  have hz : printedZ (pairSubringInverse s t hts) ∈ (f.comp (pairToRank s t hn)).ker :=
    MonoidHom.mem_ker.mpr
      (printedZ_killed _ hT hm hmeS hM (f.comp (pairToRank s t hn)))
  have h41 : elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0)
      (fUnit (pairSubringInverse s t hts) 1 0) ∈ (f.comp (pairToRank s t hn)).ker := by
    have := commutatorLeft_mem (N := (f.comp (pairToRank s t hn)).ker) hz
      (elementaryRoot lastIdx (coreIdx 0) (last_ne_coreIdx 0)
        (fUnit (pairSubringInverse s t hts) 2 0))
    rwa [← commutatorElement_def, printedZ_commutator_root] at this
  have h21 := commutatorRight_mem (N := (f.comp (pairToRank s t hn)).ker)
    (elementaryRoot (coreIdx 1) lastIdx (coreIdx_ne_last 1) (pairSubringInverse s t hts).t) h41
  rw [← commutatorElement_def, printedT_commutator_root] at h21
  exact ⟨MonoidHom.mem_ker.mp h41, MonoidHom.mem_ker.mp h21⟩

/-- > hence every `e_{ij}(aeb)` by the Steinberg relations and signed permutations,
> hence `EL_n(R,ReR)`.

(tex lines 1116--1117)  Along the printed route (`TorsionComplementaryIdempotentsSignedPermutations`):
two Steinberg commutators and at most two signed permutation matrices put every
`e_{ij}(aeb)` in the kernel, and `ReR` is the additive span of the `aeb`. -/
theorem manuscriptSentence_sandwichesAndRelativeElementaryKilled :
    ∀ (R : Type) [Ring R] [Countable R] (s t : R), t * s = 1 → ∀ m : ℕ, 0 < m →
      m • (1 - s * t) = 0 → ∀ n : ℕ, 4 ≤ n → ∀ (M : Type) [Group M], IsOperatorMF M →
        ∀ f : elementaryGroup (Fin n) R →* M,
          (∀ (i j : Fin n) (hij : i ≠ j) (a b : R),
            f (elGen i j hij (a * (1 - s * t) * b)) = 1) ∧
          relativeElementary (Fin n) (TwoSidedIdeal.span ({1 - s * t} : Set R)) ≤ f.ker := by
  intro R _ _ s t hts m hm hme n hn M _ hM f
  have hroot : elGen (bigIdx hn (coreIdx 1)) (bigIdx hn (coreIdx 0)) (torsionIndexNe hn)
      (1 - s * t) ∈ f.ker :=
    MonoidHom.mem_ker.mpr (printedRoot_killed s t hts hm hme hn hM f)
  have hthree := TorsionComplementaryIdempotents.exists_third_index (by omega : 3 ≤ n)
  exact ⟨fun i j hij a b ↦ MonoidHom.mem_ker.mp
      (elGen_sandwich_mem_of_elGen_mem hthree (torsionIndexNe hn) hroot i j hij a b),
    relativeElementary_span_le_of_elGen_mem hthree (torsionIndexNe hn) hroot⟩

/-- > For `e≠0`, `e_{21}(e)≠1`.

(tex line 1117) -/
theorem manuscriptSentence_rootNeOne :
    ∀ (R : Type) [Ring R] (n : ℕ) (hn : 4 ≤ n) (e : R), e ≠ 0 →
      elementaryRoot (bigIdx hn (coreIdx 1)) (bigIdx hn (coreIdx 0)) (torsionIndexNe hn) e
        ≠ 1 := by
  intro R _ n hn e he h
  apply he
  have hval : elementaryUnit (bigIdx hn (coreIdx 1)) (bigIdx hn (coreIdx 0))
      (torsionIndexNe hn) e
      = elementaryUnit (bigIdx hn (coreIdx 1)) (bigIdx hn (coreIdx 0))
        (torsionIndexNe hn) 0 := by
    rw [elementaryUnit_zero]
    exact congrArg
      (fun g : elementaryGroup (Fin n) R ↦ (g : (Matrix (Fin n) (Fin n) R)ˣ)) h
  exact elementaryUnit_injective _ _ (torsionIndexNe hn) hval

/-- > If `R` has characteristic `p>0` then `pe=0` for every such `e`, and the
> contrapositive gives direct finiteness.

(tex lines 1118--1119) -/
theorem manuscriptSentence_positiveCharacteristic :
    (∀ (R : Type) [Ring R] (p : ℕ) [CharP R p] (e : R), p • e = 0) ∧
      PrintedPositiveCharacteristicDirectFiniteness :=
  ⟨fun _ _ _ _ _ ↦ by rw [nsmul_eq_mul, CharP.cast_eq_zero, zero_mul],
    manuscriptPositiveCharacteristicDirectFiniteness⟩

end TorsionComplementaryIdempotents
end OneSidedMFRadical
end Manuscript
end GroupApproximation

open GroupApproximation

#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_zeroIdempotentCase
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_pairSubringCoreKazhdan
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_centralFiniteOrderInDefect
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_matrixUnits
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_diagonalCommutators
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_compressorWeylAndV
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_vCompressesCore
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_printedCell
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_conjugationsByV
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_defectElementAndZ
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_zCentral
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_zOrderAndNontrivial
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_criterionKillsCentralElement
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_twoCommutatorsKilled
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_sandwichesAndRelativeElementaryKilled
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_rootNeOne
#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptSentence_positiveCharacteristic
