import GroupApproximation.Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotentsDefect
import GroupApproximation.Manuscript.OneSidedMFRadical.MFHomKernel
import GroupApproximation.Manuscript.NonMFSentences.HeadlineCitationSentences
import GroupApproximation.Meta.AxiomGuard

/-!
# `prop:torsion-defect-ring`, as printed

`non_mf_groups_exist.tex`, Proposition `prop:torsion-defect-ring` (torsion
complementary idempotents), line 1059:

> Let `R` be a countable unital ring, let `s,t ∈ R` satisfy `ts = 1`, and
> suppose that `e = 1-st` has finite additive order.  Then for every `n ≥ 4`,
> `EL_n(R,ReR) ≤ Rad_MF(EL_n(R))`, where `EL_n(R,ReR)` is the normal closure of
> the `e_{ij}(a)` with `a ∈ ReR`.  In particular `EL_n(R)` is not MF when
> `e ≠ 0`, and if `R` has positive characteristic, then `EL_4(R)` MF implies
> that `R` is directly finite.

## `Rad_MF`

The Introduction (lines 116--120) defines
`Rad_MF(G) = ⋂ {ker f : f : G → M, M an MF group}`.  That is literally
`MFQuotientUnits.mfHomKernel`.  `manuscriptCoronaMFResidual` and
`actualCoronaMFResidual` quantify over corona *representations* instead, a
different quantification; the criterion is applied through them inside the
proof and converted pointwise, but the printed statement uses `mfHomKernel`.

## What the proof of this module still has to do

The compressor cell, the central `z`, the criterion and the Steinberg descent
are already proved.  Two steps remain.

* **The descent to the printed `S`.**  The printed proof takes `S` to be the
  unital subring generated by `s` and `t`, precisely so that
  Ershov--Jaikin-Zapirain applies to `EL₃(S)`; `R` itself is never required to
  be finitely generated and property `(T)` is never asked of it.  Since the
  conclusion at each `f` is about a single elementary matrix, the descent is
  one application of `elementaryGroupMap` along `S → R` and needs no covering
  argument.
* **The two "in particular" clauses.**  `e ≠ 0` makes `e_{21}(e) ≠ 1`, by
  injectivity of `a ↦ x_{ij}(a)`, so the radical is nontrivial and the group is
  not MF.  In positive characteristic `p e = 0` holds for *every* `e = 1 - st`,
  so the contrapositive of the second clause is direct finiteness — a statement
  about `R` alone, recorded separately as
  `PrintedPositiveCharacteristicDirectFiniteness`.
-/

namespace GroupApproximation
namespace Manuscript
namespace OneSidedMFRadical
namespace TorsionComplementaryIdempotents

open GroupApproximation.OneSidedCompressor

/-! ## Elementary roots along a coefficient map -/

theorem elementaryGroupMap_elementaryRoot {ι : Type*} [Fintype ι] [DecidableEq ι]
    {R S : Type*} [Ring R] [Ring S] (f : R →+* S) (i j : ι) (hij : i ≠ j)
    (a : R) :
    elementaryGroupMap (ι := ι) f (elementaryRoot i j hij a)
      = elementaryRoot i j hij (f a) := by
  apply Subtype.ext
  rw [elementaryGroupMap_apply]
  exact elementaryMatrixUnitMap_elementaryUnit f i j hij a

/-! ## The printed descent to `S = ⟨s,t⟩` -/

section Descent

variable {R : Type} [Ring R] [Countable R]

/-- The printed index pair `(2,1)` of `e_{21}(e)`, inside `Fin n`. -/
theorem torsionIndexNe {n : ℕ} (hn : 4 ≤ n) :
    bigIdx hn (coreIdx 1) ≠ bigIdx hn (coreIdx 0) :=
  (bigIdx_injective hn).ne (coreIdx_injective.ne oneNeZeroFin)

/-- **The printed proof, at every countable ring and every rank `n ≥ 4`.**
Every homomorphism from `EL_n(R)` to an MF group kills `e_{21}(e)`.

The printed `S` is `Subring.closure {s,t}`, which is finitely generated by
construction, so the Ershov--Jaikin-Zapirain theorem gives property `(T)` for
`EL₃(S)`; `R` itself is neither finitely generated nor Kazhdan. -/
theorem printedRoot_killed (s t : R) (hts : t * s = 1) {m : ℕ} (hm : 0 < m)
    (hme : m • (1 - s * t) = 0) {n : ℕ} (hn : 4 ≤ n) {M : Type} [Group M]
    (hM : IsOperatorMF M) (f : elementaryGroup (Fin n) R →* M) :
    f (elementaryRoot (bigIdx hn (coreIdx 1)) (bigIdx hn (coreIdx 0))
        (torsionIndexNe hn) (1 - s * t)) = 1 := by
  have hsS : s ∈ Subring.closure ({s, t} : Set R) :=
    Subring.subset_closure (by simp)
  have htS : t ∈ Subring.closure ({s, t} : Set R) :=
    Subring.subset_closure (by simp)
  haveI : Countable ↥(Subring.closure ({s, t} : Set R)) := Subtype.countable
  let PS : OneSidedInverse ↥(Subring.closure ({s, t} : Set R)) :=
    ⟨⟨s, hsS⟩, ⟨t, htS⟩, Subtype.ext hts⟩
  have hePS : ((PS.e : ↥(Subring.closure ({s, t} : Set R))) : R) = 1 - s * t := by
    rw [OneSidedInverse.e_eq]
    push_cast
    rfl
  have hmeS : m • PS.e = 0 := by
    refine Subtype.ext ?_
    have hcoe : ((m • PS.e : ↥(Subring.closure ({s, t} : Set R))) : R)
        = m • ((PS.e : ↥(Subring.closure ({s, t} : Set R))) : R) := by simp
    rw [hcoe, hePS, hme]
    simp
  have hT : HasKazhdanPropertyT.{0, 0}
      (elementaryGroup (Fin 3) ↥(Subring.closure ({s, t} : Set R))) :=
    (NonMFSentences.HeadlineCitationSentences
      .manuscriptSentence_pairSubringElementaryPropertyT R s t).2
  have hkill := printedE21_killed_rank PS hT hm hmeS hn hM
    (f.comp (elementaryGroupMap (ι := Fin n)
      (Subring.closure ({s, t} : Set R)).subtype))
  rw [MonoidHom.comp_apply, elementaryGroupMap_elementaryRoot] at hkill
  have hsub : (Subring.closure ({s, t} : Set R)).subtype PS.e = 1 - s * t := hePS
  rwa [hsub] at hkill

/-- **The printed display**, at a fixed pair: `EL_n(R, ReR) ≤ Rad_MF(EL_n(R))`. -/
theorem relativeElementary_le_mfHomKernel (s t : R) (hts : t * s = 1) {m : ℕ}
    (hm : 0 < m) (hme : m • (1 - s * t) = 0) {n : ℕ} (hn : 4 ≤ n) :
    relativeElementary (Fin n) (TwoSidedIdeal.span {1 - s * t}) ≤
      MFQuotientUnits.mfHomKernel (elementaryGroup (Fin n) R) := by
  intro x hx
  rw [MFQuotientUnits.mem_mfHomKernel_iff]
  intro M _ hM f
  have hroot : elGen (bigIdx hn (coreIdx 1)) (bigIdx hn (coreIdx 0))
      (torsionIndexNe hn) (1 - s * t) ∈ f.ker :=
    MonoidHom.mem_ker.mpr (printedRoot_killed s t hts hm hme hn hM f)
  have hle := relativeElementary_span_le_fin (by omega : 3 ≤ n) f.ker
    (torsionIndexNe hn) hroot
  exact MonoidHom.mem_ker.mp (hle hx)

/-- **The printed "in particular":** `EL_n(R)` is not MF when `e ≠ 0`. -/
theorem not_isCDEOperatorMF_of_pair (s t : R) (hts : t * s = 1) {m : ℕ}
    (hm : 0 < m) (hme : m • (1 - s * t) = 0) (he : (1 : R) - s * t ≠ 0)
    {n : ℕ} (hn : 4 ≤ n) : ¬ IsCDEOperatorMF (elementaryGroup (Fin n) R) := by
  intro hMF
  haveI : Countable (elementaryGroup (Fin n) R) :=
    FullDefectRing.countable_elementaryGroup
  have hMFop : IsOperatorMF (elementaryGroup (Fin n) R) :=
    (isCDEOperatorMF_iff_isOperatorMF _).mp hMF
  have h1 := printedRoot_killed s t hts hm hme hn hMFop
    (MonoidHom.id (elementaryGroup (Fin n) R))
  have hval : elementaryUnit (bigIdx hn (coreIdx 1)) (bigIdx hn (coreIdx 0))
      (torsionIndexNe hn) (1 - s * t)
      = elementaryUnit (bigIdx hn (coreIdx 1)) (bigIdx hn (coreIdx 0))
        (torsionIndexNe hn) 0 := by
    rw [elementaryUnit_zero]
    exact congrArg
      (fun g : elementaryGroup (Fin n) R ↦ (g : (Matrix (Fin n) (Fin n) R)ˣ)) h1
  exact he (elementaryUnit_injective _ _ (torsionIndexNe hn) hval)

end Descent

/-! ## The printed proposition -/

/-- **`prop:torsion-defect-ring` exactly as printed.**

> Let `R` be a countable unital ring, let `s,t ∈ R` satisfy `ts = 1`, and
> suppose that `e = 1-st` has finite additive order.  Then for every `n ≥ 4`,
> `EL_n(R,ReR) ≤ Rad_MF(EL_n(R))`, where `EL_n(R,ReR)` is the normal closure of
> the `e_{ij}(a)` with `a ∈ ReR`.  In particular `EL_n(R)` is not MF when
> `e ≠ 0`, and if `R` has positive characteristic, then `EL_4(R)` MF implies
> that `R` is directly finite.

`Rad_MF` is the Introduction's `⋂ {ker f : f : G → M, M an MF group}`,
`MFQuotientUnits.mfHomKernel`; `EL_n(R, ReR)` is `relativeElementary`, the
normal closure inside `EL_n(R)` of the elementary matrices with coefficients in
the two-sided ideal generated by `e`; "finite additive order" is
`∃ m ≥ 1, m • e = 0`. -/
def PrintedTorsionComplementaryIdempotents : Prop :=
  ∀ (R : Type) [Ring R] [Countable R] (s t : R), t * s = 1 →
    (∃ m : ℕ, 1 ≤ m ∧ m • (1 - s * t) = 0) →
      (∀ n : ℕ, 4 ≤ n →
          relativeElementary (Fin n) (TwoSidedIdeal.span {1 - s * t}) ≤
            MFQuotientUnits.mfHomKernel (elementaryGroup (Fin n) R)) ∧
        ((1 : R) - s * t ≠ 0 → ∀ n : ℕ, 4 ≤ n →
          ¬ IsCDEOperatorMF (elementaryGroup (Fin n) R)) ∧
        ((∃ p : ℕ, 0 < p ∧ CharP R p) →
          IsCDEOperatorMF (elementaryGroup (Fin 4) R) → IsDedekindFiniteMonoid R)

/-- **The printed positive-characteristic clause on its own.**

> if `R` has positive characteristic, then `EL_4(R)` MF implies that `R` is
> directly finite.

The clause mentions neither `s`, `t` nor `e`: in characteristic `p > 0` every
complementary idempotent `1 - st` already has `p(1-st) = 0`, so the standing
torsion hypothesis is automatic and the statement is about `R` alone. -/
def PrintedPositiveCharacteristicDirectFiniteness : Prop :=
  ∀ (R : Type) [Ring R] [Countable R] (p : ℕ), 0 < p → CharP R p →
    IsCDEOperatorMF (elementaryGroup (Fin 4) R) → IsDedekindFiniteMonoid R

/-- Closed proof of the printed positive-characteristic clause. -/
theorem manuscriptPositiveCharacteristicDirectFiniteness :
    PrintedPositiveCharacteristicDirectFiniteness := by
  intro R _ _ p hp hchar hMF
  haveI := hchar
  refine ⟨?_⟩
  intro a b hab
  by_contra hba
  have hne : (1 : R) - b * a ≠ 0 := sub_ne_zero.mpr (Ne.symm hba)
  have hpe : p • ((1 : R) - b * a) = 0 := by
    rw [nsmul_eq_mul, CharP.cast_eq_zero, zero_mul]
  exact not_isCDEOperatorMF_of_pair b a hab hp hpe hne le_rfl hMF

/-- **Closed proof of `prop:torsion-defect-ring`.** -/
theorem manuscriptTorsionComplementaryIdempotents :
    PrintedTorsionComplementaryIdempotents := by
  intro R _ _ s t hts hfin
  obtain ⟨m, hm, hme⟩ := hfin
  refine ⟨?_, ?_, ?_⟩
  · intro n hn
    exact relativeElementary_le_mfHomKernel s t hts hm hme hn
  · intro he n hn
    exact not_isCDEOperatorMF_of_pair s t hts hm hme he hn
  · rintro ⟨p, hp, hchar⟩ hMF
    exact manuscriptPositiveCharacteristicDirectFiniteness R p hp hchar hMF

end TorsionComplementaryIdempotents
end OneSidedMFRadical
end Manuscript
end GroupApproximation

open GroupApproximation

#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptTorsionComplementaryIdempotents

#audit_closed_axioms
  Manuscript.OneSidedMFRadical.TorsionComplementaryIdempotents.manuscriptPositiveCharacteristicDirectFiniteness
