#!/usr/bin/env python3
"""Exact finite checks for reuse-information compression.

These checks test finite measure and graph accounting.  They do not prove
Fixed Price, the infinite measurable constructions, or novelty of the note.
Only Python's standard library is required.
"""
from __future__ import annotations
from collections import deque
from fractions import Fraction as F
from itertools import product
from pathlib import Path
import json


def partitions(n: int):
    """All set partitions, represented by canonical block-label tuples."""
    def rec(a):
        if len(a) == n:
            yield tuple(a)
            return
        for x in range(max(a, default=-1) + 2):
            yield from rec(a + [x])
    yield from rec([])


def conditional(values, blocks, masses):
    out = [F(0)] * len(values)
    for b in set(blocks):
        ix = [i for i, bb in enumerate(blocks) if bb == b]
        mass = sum((masses[i] for i in ix), F(0))
        mean = sum((masses[i] * values[i] for i in ix), F(0)) / mass
        for i in ix:
            out[i] = mean
    return out


def expectation(values, masses):
    return sum((m * v for m, v in zip(masses, values)), F(0))


def scalar_checks():
    ps = list(partitions(4))
    masses = [F(1, 10), F(2, 10), F(3, 10), F(4, 10)]
    cases = 0
    chain_cases = 0
    for values in product(range(4), repeat=4):
        tv_source = expectation([abs(v-1) for v in values], masses)
        for coarse in ps:
            mean = conditional(values, coarse, masses)
            present = conditional([int(v > 0) for v in values], coarse, masses)
            gap = expectation([min(F(1), m)-p for m,p in zip(mean,present)], masses)
            tv_target = expectation([abs(m-1) for m in mean], masses)
            assert gap == (tv_source-tv_target)/2
            positive = conditional([max(0,v-1) for v in values], coarse,masses)
            negative = conditional([int(v==0) for v in values], coarse,masses)
            assert gap == expectation([min(a,b) for a,b in zip(positive,negative)],masses)
            assert gap >= 0
            # Revealing the positive-sign bit precludes conditional cancellation.
            refined = [(coarse[i], int(values[i]>=2)) for i in range(4)]
            rm = conditional(values, refined, masses)
            rp = conditional([int(v>0) for v in values], refined,masses)
            assert expectation([min(F(1),a)-b for a,b in zip(rm,rp)],masses)==0
            cases += 1
            for fine in ps:
                if not all(fine[i]!=fine[j] or coarse[i]==coarse[j]
                           for i in range(4) for j in range(4)):
                    continue
                fm=conditional(values,fine,masses)
                fp=conditional([int(v>0) for v in values],fine,masses)
                gap_fine=expectation([min(F(1),a)-b for a,b in zip(fm,fp)],masses)
                recovered=(expectation([abs(a-1) for a in fm],masses)-tv_target)/2
                assert gap==gap_fine+recovered
                assert recovered>=0
                chain_cases+=1
    return {'weighted_traffic_partition_cases':cases,
            'nested_information_cases':chain_cases}


def finite_action_checks():
    # Y = C3 x {0,1}, with C3 acting freely by addition in the first coordinate.
    n=6
    def move(y,g):
        return 3*(y//3)+(y%3+g)%3
    gs=(1,-1)
    checked=0
    for mask0 in range(1<<n):
      for mask1 in range(1<<n):
        masks=(mask0,mask1)
        adj=[[] for _ in range(n)]
        for j,g in enumerate(gs):
            for y in range(n):
                if masks[j]>>y & 1:
                    z=move(y,g)
                    adj[y].append((z,(j,y)))
                    adj[z].append((y,(j,y)))
        for aa in adj:
            aa.sort()
        traffic=[[0]*n for _ in gs]
        routes={}
        uncovered=0
        for y in range(n):
            goal=move(y,1)
            parent={y:None}
            queue=deque([y])
            while queue and goal not in parent:
                v=queue.popleft()
                for w,edge in adj[v]:
                    if w not in parent:
                        parent[w]=(v,edge)
                        queue.append(w)
            if goal not in parent:
                uncovered+=1
                continue
            path=[]
            z=goal
            while z!=y:
                prev,edge=parent[z]
                path.append(edge)
                z=prev
            path.reverse()
            routes[y]=path
            for j,z in path:
                traffic[j][z]+=1
        B=F(uncovered+sum(v>0 for row in traffic for v in row),n)
        # Factor generated by the base x and *all translates* of the reuse bits.
        keys=[]
        for y in range(n):
            name=tuple(int(traffic[j][move(y,g)]>=2)
                       for j in range(2) for g in range(3))
            keys.append((y%3,name))
        uniq=list(dict.fromkeys(keys))
        index={key:i for i,key in enumerate(uniq)}
        fibers=[[y for y in range(n) if keys[y]==key] for key in uniq]
        z_of=[index[key] for key in keys]
        weights=[F(len(fiber),n) for fiber in fibers]
        zadj=[set() for _ in uniq]
        retained_cost=F(0)
        for zi,fiber in enumerate(fibers):
            for g in (1,-1):
                assert len({z_of[move(y,g)] for y in fiber})==1
            for j,g in enumerate(gs):
                bit=int(traffic[j][fiber[0]]>=2)
                assert all(int(traffic[j][y]>=2)==bit for y in fiber)
                if bit:
                    target=z_of[move(fiber[0],g)]
                    zadj[zi].add(target)
                    zadj[target].add(zi)
                    retained_cost+=weights[zi]
        target_uncovered=F(0)
        for zi,fiber in enumerate(fibers):
            target=z_of[move(fiber[0],1)]
            seen={zi}
            todo=[zi]
            while todo:
                v=todo.pop()
                for w in zadj[v]:
                    if w not in seen:
                        seen.add(w);todo.append(w)
            if target not in seen:
                target_uncovered+=weights[zi]
        assert retained_cost+target_uncovered<=B
        # Conditional gap at this intermediate factor is identically zero.
        masses=[F(1,n)]*n
        for row in traffic:
            cm=conditional(row,z_of,masses)
            cp=conditional([int(v>0) for v in row],z_of,masses)
            assert all(min(F(1),m)==p for m,p in zip(cm,cp))
        checked+=1
    return {'two_sheet_free_action_domain_configurations':checked}


def main():
    result={'scope':'Finite accounting only; not a proof of either universal conjecture.',
            'scalar':scalar_checks(), 'action':finite_action_checks(), 'passed':True}
    destination=Path(__file__).with_name('fixed-price-reuse-compression-checks.json')
    destination.write_text(json.dumps(result,indent=2)+'\n')
    print(json.dumps(result,indent=2))

if __name__=='__main__':
    main()
