import GroupApproximation.BooneHigmanLinear.LSCore.PDef
import Mathlib.Algebra.BigOperators.NatAntidiagonal
import GroupApproximation.Meta.AxiomGuard

/-!
# The invariant `p_α : P̃_α(*) → (M, +)` (Lavrenov–Sinchuk, Lemma 5.9), type A

For `α = (i, j)` put `pAlpha i j g = ((π g)_{ji}).coeff 1 ∈ A`: the `X`-coefficient of the
`(j, i)` entry of the matrix of `g ∈ St_I(A[X])`. This gives L–S's map `p_α` of Lemma 5.9.
* Every `g ∈ P̃_α(*)` has `π(g)(0)` equal to the identity in row `j` and column `i`
  (`rowCol_ev_of_mem_pStar`). Evaluating at `X = 0` sends `P̃_α(*)` into the subgroup generated
  by the `x_pq(c)` with `p ≠ j`, `q ≠ i`.
* On such elements `pAlpha` is additive (`pAlpha_mul`), since
  `(PQ)₁ = P₀ Q₁ + P₁ Q₀` for the coefficients of `X`.
* `pAlpha` vanishes on `P̃_α(0)` (`pAlpha_eq_zero`), and `pAlpha (x_ji(m X)) = m` (`pAlpha_x`).
-/

namespace GroupApproximation
namespace BooneHigmanLinear
namespace LSCore

open GroupApproximation.SteinbergGroup
open GroupApproximation.BooneHigman.SteinbergBasic
open GroupApproximation.BooneHigmanLinear.RelGen (zElt polyIdeal)
open Polynomial (X C)

variable {I : Type*} [Fintype I] [DecidableEq I]

section Mat

variable {R : Type*} [CommRing R]

/-- The matrix of `π(g) ∈ E_I(R)`. -/
abbrev mat (g : SteinbergGroup I R) : Matrix I I R :=
  (((projection g : elementaryGroup I R) : (Matrix I I R)ˣ) : Matrix I I R)

theorem mat_mul (g h : SteinbergGroup I R) : mat (g * h) = mat g * mat h := by
  simp only [mat, map_mul, Subgroup.coe_mul, Units.val_mul]

theorem mat_one : mat (1 : SteinbergGroup I R) = 1 := by
  simp only [mat, map_one, OneMemClass.coe_one, Units.val_one]

theorem mat_x {i j : I} (hij : i ≠ j) (c : R) : mat (x i j hij c) = 1 + Matrix.single i j c := by
  rw [mat, projection_x]
  rfl

theorem mat_ringMap {S : Type*} [CommRing S] (f : R →+* S) (g : SteinbergGroup I R) :
    mat (ringMap f g) = f.mapMatrix (mat g) := by
  rw [mat, projection_ringMap]
  rfl

/-- Row `j` and column `i` of `U` are those of the identity. -/
def RowCol (i j : I) (U : Matrix I I R) : Prop :=
  (∀ k, U j k = (1 : Matrix I I R) j k) ∧ ∀ k, U k i = (1 : Matrix I I R) k i

theorem RowCol.mul {i j : I} {U V : Matrix I I R} (hU : RowCol i j U) (hV : RowCol i j V) :
    RowCol i j (U * V) := by
  refine ⟨fun k => ?_, fun k => ?_⟩
  · rw [Matrix.mul_apply]
    simp_rw [hU.1]
    rw [← Matrix.mul_apply, one_mul, hV.1]
  · rw [Matrix.mul_apply]
    simp_rw [hV.2]
    rw [← Matrix.mul_apply, mul_one, hU.2]

theorem rowCol_x {i j p q : I} (hpq : p ≠ q) (hp : p ≠ j) (hq : q ≠ i) (c : R) :
    RowCol i j (mat (x p q hpq c)) := by
  rw [mat_x]
  refine ⟨fun k => ?_, fun k => ?_⟩
  · rw [Matrix.add_apply, Matrix.single_apply_of_ne (fun h => hp h.1), add_zero]
  · rw [Matrix.add_apply, Matrix.single_apply_of_ne (fun h => hq h.2), add_zero]

/-- The root elements `x_pq(c)` with `p ≠ j`, `q ≠ i`. -/
def fixGens (i j : I) : Set (SteinbergGroup I R) :=
  {g | ∃ (p q : I) (hpq : p ≠ q) (c : R), p ≠ j ∧ q ≠ i ∧ x p q hpq c = g}

theorem rowCol_of_mem_closure {i j : I} {g : SteinbergGroup I R}
    (hg : g ∈ Subgroup.closure (fixGens i j)) : RowCol i j (mat g) := by
  induction hg using Subgroup.closure_induction'' with
  | mem g hg =>
    obtain ⟨p, q, hpq, c, hp, hq, rfl⟩ := hg
    exact rowCol_x hpq hp hq c
  | inv_mem g hg =>
    obtain ⟨p, q, hpq, c, hp, hq, rfl⟩ := hg
    rw [← x_neg]
    exact rowCol_x hpq hp hq (-c)
  | one =>
    rw [mat_one]
    exact ⟨fun _ => rfl, fun _ => rfl⟩
  | mul g h _ _ hg hh =>
    rw [mat_mul]
    exact hg.mul hh

end Mat

variable {A : Type*} [CommRing A]

theorem ringMap_zElt {S : Type*} [CommRing S] (f : A →+* S) {p q : I} (hpq : p ≠ q) (s ξ : A) :
    ringMap f (zElt p q hpq s ξ) = zElt p q hpq (f s) (f ξ) := by
  rw [zElt, zElt, map_mul, map_mul, ringMap_x, ringMap_x, ringMap_x, map_neg]

theorem zElt_zero_right' {p q : I} (hpq : p ≠ q) (s : A) : zElt p q hpq s 0 = x p q hpq s := by
  rw [zElt, neg_zero, x_zero, one_mul, mul_one]

theorem zElt_zero_left {p q : I} (hpq : p ≠ q) (ξ : A) : zElt p q hpq 0 ξ = 1 := by
  rw [zElt, x_zero, mul_one, x_mul, neg_add_cancel, x_zero]

/-- Evaluation at `X = 0` sends `P̃_α(*)` into the group generated by `fixGens i j`. -/
theorem ev_mem_of_mem_pStar {M : Ideal A} {i j : I} {hij : i ≠ j}
    {g : SteinbergGroup I (Polynomial A)} (hg : g ∈ pStar M i j hij) :
    ringMap (Polynomial.evalRingHom 0 : Polynomial A →+* A) g ∈
      Subgroup.closure (fixGens (R := A) i j) := by
  have hX : ∀ f : Polynomial A, Polynomial.evalRingHom 0 (X * f) = 0 := fun f => by simp
  have hX2 : ∀ f : Polynomial A, Polynomial.evalRingHom 0 (X ^ 2 * f) = 0 := fun f => by simp
  have hCX : ∀ m : A, Polynomial.evalRingHom 0 (C m * X) = 0 := fun m => by simp
  have hle : (pStar M i j hij).map (ringMap (Polynomial.evalRingHom 0 : Polynomial A →+* A)) ≤
      Subgroup.closure (fixGens (R := A) i j) := by
    rw [pStar, MonoidHom.map_closure, Subgroup.closure_le]
    rintro _ ⟨g, hg, rfl⟩
    rw [Set.mem_union] at hg
    rcases hg with hg | ⟨m, -, rfl⟩
    · unfold pGens at hg
      rcases hg with (((hg | hg) | hg) | hg) | hg
      · obtain ⟨p, q, hpq, f, ξ, -, -, rfl⟩ := hg
        rw [ringMap_zElt, hX, zElt_zero_left]
        exact one_mem _
      · obtain ⟨p, q, hpq, f, ξ, -, hA, rfl⟩ := hg
        rw [ringMap_zElt, hX, zElt_zero_right']
        have hpj : p ≠ j := by
          rcases hA with ⟨hp, -⟩ | ⟨hq, -⟩
          · exact fun h => hij (hp.symm.trans h)
          · exact fun h => hpq (h.trans hq.symm)
        have hqi : q ≠ i := by
          rcases hA with ⟨hp, -⟩ | ⟨hq, -⟩
          · exact fun h => hpq (hp.trans h.symm)
          · exact fun h => hij (h.symm.trans hq)
        exact Subgroup.subset_closure ⟨p, q, hpq, _, hpj, hqi, rfl⟩
      · obtain ⟨p, q, hpq, f, ξ, -, hO, rfl⟩ := hg
        rw [ringMap_zElt, zElt]
        exact mul_mem (mul_mem
          (Subgroup.subset_closure ⟨q, p, hpq.symm, _, hO.2.2.2, hO.1, rfl⟩)
          (Subgroup.subset_closure ⟨p, q, hpq, _, hO.2.1, hO.2.2.1, rfl⟩))
          (Subgroup.subset_closure ⟨q, p, hpq.symm, _, hO.2.2.2, hO.1, rfl⟩)
      · obtain ⟨f, -, rfl⟩ := hg
        rw [ringMap_x, hX2, x_zero]
        exact one_mem _
      · obtain ⟨f, -, rfl⟩ := hg
        rw [ringMap_x]
        exact Subgroup.subset_closure ⟨i, j, hij, _, hij, hij.symm, rfl⟩
    · rw [ringMap_x, hCX, x_zero]
      exact one_mem _
  exact hle ⟨g, hg, rfl⟩

#audit_axioms ev_mem_of_mem_pStar

/-- `π(g)(0)` is the identity in row `j` and column `i`, for `g ∈ P̃_α(*)`. -/
theorem rowCol_ev_of_mem_pStar {M : Ideal A} {i j : I} {hij : i ≠ j}
    {g : SteinbergGroup I (Polynomial A)} (hg : g ∈ pStar M i j hij) :
    RowCol i j ((Polynomial.evalRingHom 0 : Polynomial A →+* A).mapMatrix (mat g)) := by
  rw [← mat_ringMap]
  exact rowCol_of_mem_closure (ev_mem_of_mem_pStar hg)

/-- **L–S `p_α`**: the `X`-coefficient of the `(j, i)` entry. -/
def pAlpha (i j : I) (g : SteinbergGroup I (Polynomial A)) : A :=
  ((mat g) j i).coeff 1

theorem coeff_mul_one (P Q : Polynomial A) :
    (P * Q).coeff 1 = P.coeff 0 * Q.coeff 1 + P.coeff 1 * Q.coeff 0 := by
  rw [Polynomial.coeff_mul, Finset.Nat.sum_antidiagonal_succ]
  simp

/-- `p_α` is additive on elements whose value at `0` fixes row `j` and column `i`. -/
theorem pAlpha_mul_of_rowCol {i j : I} {g h : SteinbergGroup I (Polynomial A)}
    (hg : RowCol i j ((Polynomial.evalRingHom 0 : Polynomial A →+* A).mapMatrix (mat g)))
    (hh : RowCol i j ((Polynomial.evalRingHom 0 : Polynomial A →+* A).mapMatrix (mat h))) :
    pAlpha i j (g * h) = pAlpha i j g + pAlpha i j h := by
  have h0g : ∀ k, ((mat g) j k).coeff 0 = (1 : Matrix I I A) j k := fun k => by
    rw [Polynomial.coeff_zero_eq_eval_zero, ← hg.1 k]
    rfl
  have h0h : ∀ k, ((mat h) k i).coeff 0 = (1 : Matrix I I A) k i := fun k => by
    rw [Polynomial.coeff_zero_eq_eval_zero, ← hh.2 k]
    rfl
  simp only [pAlpha, mat_mul, Matrix.mul_apply, Polynomial.finsetSum_coeff, coeff_mul_one, h0g,
    h0h, Finset.sum_add_distrib, Matrix.one_apply, ite_mul, one_mul, zero_mul, mul_ite, mul_one,
    mul_zero, Finset.sum_ite_eq, Finset.sum_ite_eq', Finset.mem_univ, ite_true]
  exact add_comm _ _

#audit_axioms pAlpha_mul_of_rowCol

/-- **`p_α` is a homomorphism on `P̃_α(*)`.** -/
theorem pAlpha_mul {M : Ideal A} {i j : I} {hij : i ≠ j} {g h : SteinbergGroup I (Polynomial A)}
    (hg : g ∈ pStar M i j hij) (hh : h ∈ pStar M i j hij) :
    pAlpha i j (g * h) = pAlpha i j g + pAlpha i j h :=
  pAlpha_mul_of_rowCol (rowCol_ev_of_mem_pStar hg) (rowCol_ev_of_mem_pStar hh)

theorem pAlpha_one (i j : I) (hij : i ≠ j) : pAlpha (A := A) i j 1 = 0 := by
  rw [pAlpha, mat_one, Matrix.one_apply_ne hij.symm, Polynomial.coeff_zero]

theorem pAlpha_inv {M : Ideal A} {i j : I} {hij : i ≠ j} {g : SteinbergGroup I (Polynomial A)}
    (hg : g ∈ pStar M i j hij) : pAlpha i j g⁻¹ = -pAlpha i j g := by
  have h := pAlpha_mul (inv_mem hg) hg
  rw [inv_mul_cancel, pAlpha_one i j hij] at h
  exact eq_neg_of_add_eq_zero_left h.symm

/-- **`p_α(x_{-α}(m X)) = m`.** -/
theorem pAlpha_x (i j : I) (hij : i ≠ j) (m : A) : pAlpha i j (x j i hij.symm (C m * X)) = m := by
  rw [pAlpha, mat_x, Matrix.add_apply, Matrix.one_apply_ne hij.symm, Matrix.single_apply_same,
    zero_add, Polynomial.coeff_C_mul_X, if_pos rfl]

/-- Matrices that are the identity outside the block `{p, q}`. -/
def Block (p q : I) (U : Matrix I I A) : Prop :=
  ∀ k l, (k ≠ p ∧ k ≠ q) ∨ (l ≠ p ∧ l ≠ q) → U k l = (1 : Matrix I I A) k l

theorem Block.mul {p q : I} {U V : Matrix I I A} (hU : Block p q U) (hV : Block p q V) :
    Block p q (U * V) := by
  intro k l hkl
  rcases hkl with hk | hl
  · rw [Matrix.mul_apply]
    simp_rw [hU k _ (Or.inl hk)]
    rw [← Matrix.mul_apply, one_mul, hV k l (Or.inl hk)]
  · rw [Matrix.mul_apply]
    simp_rw [hV _ l (Or.inr hl)]
    rw [← Matrix.mul_apply, mul_one, hU k l (Or.inr hl)]

theorem block_x {p q : I} (hpq : p ≠ q) (c : A) : Block p q (mat (x p q hpq c)) := by
  intro k l hkl
  rw [mat_x, Matrix.add_apply, Matrix.single_apply_of_ne, add_zero]
  rintro ⟨rfl, rfl⟩
  rcases hkl with ⟨h1, -⟩ | ⟨-, h2⟩
  · exact h1 rfl
  · exact h2 rfl

theorem block_x' {p q : I} (hpq : p ≠ q) (c : A) : Block p q (mat (x q p hpq.symm c)) := by
  intro k l hkl
  rw [mat_x, Matrix.add_apply, Matrix.single_apply_of_ne, add_zero]
  rintro ⟨rfl, rfl⟩
  rcases hkl with ⟨-, h1⟩ | ⟨h2, -⟩
  · exact h1 rfl
  · exact h2 rfl

theorem block_zElt {p q : I} (hpq : p ≠ q) (s ξ : A) : Block p q (mat (zElt p q hpq s ξ)) := by
  rw [zElt, mat_mul, mat_mul]
  exact ((block_x' hpq (-ξ)).mul (block_x hpq s)).mul (block_x' hpq ξ)

theorem pAlpha_zElt {i j p q : I} (hij : i ≠ j) (hpq : p ≠ q)
    (h : ¬ (p = i ∧ q = j) ∧ ¬ (p = j ∧ q = i)) (s ξ : Polynomial A) :
    pAlpha i j (zElt p q hpq s ξ) = 0 := by
  have hb := block_zElt hpq s ξ
  have hji : (j ≠ p ∧ j ≠ q) ∨ (i ≠ p ∧ i ≠ q) := by
    by_contra hc
    simp only [not_or, not_and_or, not_not] at hc
    obtain ⟨h1, h2⟩ := hc
    rcases h1 with h1 | h1 <;> rcases h2 with h2 | h2 <;> subst h1 <;> subst h2 <;> simp_all
  rw [pAlpha, hb j i hji, Matrix.one_apply_ne hij.symm, Polynomial.coeff_zero]

/-- **`p_α` vanishes on `P̃_α(0)`.** -/
theorem pAlpha_eq_zero {M : Ideal A} {i j : I} {hij : i ≠ j} {g : SteinbergGroup I (Polynomial A)}
    (hg : g ∈ pZero M i j hij) : pAlpha i j g = 0 := by
  have hgen : ∀ g ∈ pGens M i j hij, pAlpha i j g = 0 := by
    intro g hg
    unfold pGens at hg
    rcases hg with (((hg | hg) | hg) | hg) | hg
    · obtain ⟨p, q, hpq, f, ξ, -, hA, rfl⟩ := hg
      exact pAlpha_zElt hij hpq hA.2 _ _
    · obtain ⟨p, q, hpq, f, ξ, -, hA, rfl⟩ := hg
      exact pAlpha_zElt hij hpq (hA.adj hpq).2 _ _
    · obtain ⟨p, q, hpq, f, ξ, -, hO, rfl⟩ := hg
      exact pAlpha_zElt hij hpq ⟨fun h => hO.1 h.1, fun h => hO.2.1 h.1⟩ _ _
    · obtain ⟨f, -, rfl⟩ := hg
      rw [pAlpha, mat_x, Matrix.add_apply, Matrix.one_apply_ne hij.symm, Matrix.single_apply_same,
        zero_add, Polynomial.coeff_X_pow_mul', if_neg (by norm_num)]
    · obtain ⟨f, -, rfl⟩ := hg
      rw [pAlpha, mat_x, Matrix.add_apply, Matrix.one_apply_ne hij.symm,
        Matrix.single_apply_of_ne (fun h => hij h.1), zero_add, Polynomial.coeff_zero]
  have hsub : ∀ g ∈ pGens M i j hij, g ∈ pStar M i j hij := fun g hg =>
    pZero_le_pStar M i j hij (Subgroup.subset_closure hg)
  unfold pZero at hg
  induction hg using Subgroup.closure_induction'' with
  | mem g hg => exact hgen g hg
  | inv_mem g hg => rw [pAlpha_inv (hsub g hg), hgen g hg, neg_zero]
  | one => exact pAlpha_one i j hij
  | mul g h hg' hh' hg hh =>
    rw [pAlpha_mul (pZero_le_pStar M i j hij hg') (pZero_le_pStar M i j hij hh'), hg, hh,
      add_zero]

#audit_axioms pAlpha_eq_zero

end LSCore
end BooneHigmanLinear
end GroupApproximation
