import GroupApproximation.BooneHigmanLinear.LSCore.ZC5
import GroupApproximation.BooneHigman.SteinbergBasic.Naturality
import GroupApproximation.Meta.AxiomGuard

/-!
# The subgroups `P̃_α(0)` and `P̃_α(*)` (Lavrenov–Sinchuk, Definition 5.7), type A

A. Lavrenov, S. Sinchuk, *A Horrocks-type theorem for even orthogonal K₂*, Def 5.7 and Remarks
5.8, 5.10, 5.11 (piece H.L4 of k2-poly). Fix `α = (i, j)` and an ideal `M` of `A`. The roots
`β = (p, q)` fall into:
* `Adj i j p q`: `β` shares exactly one index with `α` (`α + β ∈ Φ` or `α - β ∈ Φ`);
* `Acute i j p q`: `α - β ∈ Φ`, i.e. `β = (i, l)` or `β = (k, j)`;
* `Orth i j p q`: `β ⊥ α`, i.e. `β` is disjoint from `α`;
* `β = ±α`.

`P̃_α(0) = pZero M i j hij ≤ St_I(A[X])` is generated by (`f ∈ M[X]`, `ξ ∈ A[X]`):
* (P1) `z_β(X f, ξ)` for `Adj`;
* (P2) `z_β(f, X ξ)` for `Acute`;
* (P3) `z_β(f, ξ)` for `Orth`;
* (P4) `x_{-α}(X² f)`;
* (P5) `x_α(f)`.
`P̃_α(*) = pStar M i j hij` also contains `x_{-α}(m X)`, `m ∈ M`.

Membership lemmas take the coefficient as a hypothesis (`hs : s = X * f`), so callers only
supply `f` and a `ring` identity.
-/

namespace GroupApproximation
namespace BooneHigmanLinear
namespace LSCore

open scoped commutatorElement
open GroupApproximation.SteinbergGroup
open GroupApproximation.BooneHigman.SteinbergBasic
open GroupApproximation.BooneHigmanLinear.RelGen (zElt cElt polyIdeal)
open Polynomial (X C)

variable {I : Type*} [Fintype I] [DecidableEq I] {A : Type*} [CommRing A]

section Roots

/-- `β = (p, q)` shares exactly one index with `α = (i, j)`. -/
def Adj (i j p q : I) : Prop :=
  (p = i ∨ p = j ∨ q = i ∨ q = j) ∧ ¬ (p = i ∧ q = j) ∧ ¬ (p = j ∧ q = i)

/-- `α - β ∈ Φ`: `β = (i, l)` with `l ≠ j`, or `β = (k, j)` with `k ≠ i`. -/
def Acute (i j p q : I) : Prop :=
  (p = i ∧ q ≠ j) ∨ (q = j ∧ p ≠ i)

/-- `β ⊥ α`: `β` is disjoint from `α`. -/
def Orth (i j p q : I) : Prop :=
  p ≠ i ∧ p ≠ j ∧ q ≠ i ∧ q ≠ j

theorem Acute.adj {i j p q : I} (hpq : p ≠ q) (h : Acute i j p q) : Adj i j p q := by
  rcases h with ⟨rfl, hq⟩ | ⟨rfl, hp⟩
  · exact ⟨Or.inl rfl, fun h => hq h.2, fun h => hpq h.2.symm⟩
  · exact ⟨Or.inr (Or.inr (Or.inr rfl)), fun h => hp h.1, fun h => hpq h.1⟩

end Roots

section Defs

variable (M : Ideal A) (i j : I) (hij : i ≠ j)

/-- The generators P1–P5 of `P̃_α(0)`, `α = (i, j)`. -/
def pGens : Set (SteinbergGroup I (Polynomial A)) :=
  {g | ∃ (p q : I) (hpq : p ≠ q) (f ξ : Polynomial A), f ∈ polyIdeal M ∧ Adj i j p q ∧
      zElt p q hpq (X * f) ξ = g} ∪
    {g | ∃ (p q : I) (hpq : p ≠ q) (f ξ : Polynomial A), f ∈ polyIdeal M ∧ Acute i j p q ∧
      zElt p q hpq f (X * ξ) = g} ∪
    {g | ∃ (p q : I) (hpq : p ≠ q) (f ξ : Polynomial A), f ∈ polyIdeal M ∧ Orth i j p q ∧
      zElt p q hpq f ξ = g} ∪
    {g | ∃ f : Polynomial A, f ∈ polyIdeal M ∧ x j i hij.symm (X ^ 2 * f) = g} ∪
    {g | ∃ f : Polynomial A, f ∈ polyIdeal M ∧ x i j hij f = g}

/-- **L–S Definition 5.7**: `P̃_α(0)`. -/
def pZero : Subgroup (SteinbergGroup I (Polynomial A)) :=
  Subgroup.closure (pGens M i j hij)

/-- The elements `x_{-α}(m X)`, `m ∈ M`. -/
def negGens : Set (SteinbergGroup I (Polynomial A)) :=
  {g | ∃ m : A, m ∈ M ∧ x j i hij.symm (C m * X) = g}

/-- **L–S Definition 5.7**: `P̃_α(*)`, generated by `P̃_α(0)` and the `x_{-α}(m X)`. -/
def pStar : Subgroup (SteinbergGroup I (Polynomial A)) :=
  Subgroup.closure (pGens M i j hij ∪ negGens M i j hij)

theorem pZero_le_pStar : pZero M i j hij ≤ pStar M i j hij :=
  Subgroup.closure_mono Set.subset_union_left

theorem neg_mem_pStar {m : A} (hm : m ∈ M) : x j i hij.symm (C m * X) ∈ pStar M i j hij :=
  Subgroup.subset_closure (Or.inr ⟨m, hm, rfl⟩)

end Defs

section Mem

variable {M : Ideal A} {i j : I} (hij : i ≠ j)

theorem zElt_zero_right {p q : I} (hpq : p ≠ q) (s : Polynomial A) :
    zElt p q hpq s 0 = x p q hpq s := by
  rw [zElt, neg_zero, x_zero, one_mul, mul_one]

theorem mem_P1 {p q : I} (hpq : p ≠ q) (hA : Adj i j p q) {f s : Polynomial A}
    (hf : f ∈ polyIdeal M) (hs : s = X * f) (ξ : Polynomial A) :
    zElt p q hpq s ξ ∈ pZero M i j hij :=
  Subgroup.subset_closure
    (Or.inl (Or.inl (Or.inl (Or.inl ⟨p, q, hpq, f, ξ, hf, hA, by rw [hs]⟩))))

theorem mem_P2 {p q : I} (hpq : p ≠ q) (hA : Acute i j p q) {f t : Polynomial A}
    (hf : f ∈ polyIdeal M) (ξ : Polynomial A) (ht : t = X * ξ) :
    zElt p q hpq f t ∈ pZero M i j hij :=
  Subgroup.subset_closure
    (Or.inl (Or.inl (Or.inl (Or.inr ⟨p, q, hpq, f, ξ, hf, hA, by rw [ht]⟩))))

theorem mem_P3 {p q : I} (hpq : p ≠ q) (hO : Orth i j p q) {f : Polynomial A}
    (hf : f ∈ polyIdeal M) (ξ : Polynomial A) : zElt p q hpq f ξ ∈ pZero M i j hij :=
  Subgroup.subset_closure (Or.inl (Or.inl (Or.inr ⟨p, q, hpq, f, ξ, hf, hO, rfl⟩)))

theorem mem_P4 {f c : Polynomial A} (hf : f ∈ polyIdeal M) (hc : c = X ^ 2 * f) :
    x j i hij.symm c ∈ pZero M i j hij :=
  Subgroup.subset_closure (Or.inl (Or.inr ⟨f, hf, by rw [hc]⟩))

theorem mem_P5 {f : Polynomial A} (hf : f ∈ polyIdeal M) : x i j hij f ∈ pZero M i j hij :=
  Subgroup.subset_closure (Or.inr ⟨f, hf, rfl⟩)

/-- **L–S Remark 5.8**: `x_β(X f) ∈ P̃_α(0)` for `Adj` roots. -/
theorem x_mem_P1 {p q : I} (hpq : p ≠ q) (hA : Adj i j p q) {f s : Polynomial A}
    (hf : f ∈ polyIdeal M) (hs : s = X * f) : x p q hpq s ∈ pZero M i j hij := by
  rw [← zElt_zero_right]
  exact mem_P1 hij hpq hA hf hs 0

/-- **L–S Remark 5.8**: `x_β(f) ∈ P̃_α(0)` for `Acute` roots. -/
theorem x_mem_P2 {p q : I} (hpq : p ≠ q) (hA : Acute i j p q) {f : Polynomial A}
    (hf : f ∈ polyIdeal M) : x p q hpq f ∈ pZero M i j hij := by
  rw [← zElt_zero_right]
  exact mem_P2 hij hpq hA hf 0 (by rw [mul_zero])

/-- `x_β(f) ∈ P̃_α(0)` for `Orth` roots. -/
theorem x_mem_P3 {p q : I} (hpq : p ≠ q) (hO : Orth i j p q) {f : Polynomial A}
    (hf : f ∈ polyIdeal M) : x p q hpq f ∈ pZero M i j hij := by
  rw [← zElt_zero_right]
  exact mem_P3 hij hpq hO hf 0

/-- `c_β(s, t) = x_β(s) z_β(-s, -t)`. -/
theorem cElt_eq {p q : I} (hpq : p ≠ q) (s t : Polynomial A) :
    cElt p q hpq s t = x p q hpq s * zElt p q hpq (-s) (-t) := by
  rw [cElt, commutatorElement_def, zElt, neg_neg, x_neg, x_neg]
  group

/-- **L–S Remark 5.10**: `c_β(f, X ξ) ∈ P̃_α(0)` for `Acute` roots. -/
theorem cElt_mem_acute {p q : I} (hpq : p ≠ q) (hA : Acute i j p q) {f : Polynomial A}
    (hf : f ∈ polyIdeal M) (ξ : Polynomial A) : cElt p q hpq f (X * ξ) ∈ pZero M i j hij := by
  rw [cElt_eq]
  exact mul_mem (x_mem_P2 hij hpq hA hf)
    (mem_P2 hij hpq hA (neg_mem hf) (-ξ) (by rw [mul_neg]))

/-- **L–S Remark 5.10**: `c_β(f, ξ) ∈ P̃_α(0)` for `Orth` roots. -/
theorem cElt_mem_orth {p q : I} (hpq : p ≠ q) (hO : Orth i j p q) {f : Polynomial A}
    (hf : f ∈ polyIdeal M) (ξ : Polynomial A) : cElt p q hpq f ξ ∈ pZero M i j hij := by
  rw [cElt_eq]
  exact mul_mem (x_mem_P3 hij hpq hO hf) (mem_P3 hij hpq hO (neg_mem hf) (-ξ))

end Mem

section ZAlpha

variable (M : Ideal A) (i j : I) (hij : i ≠ j)

/-- L–S `Z_α(A, M) ≤ St̄(A, M)`: generated by `x_β(m)` for `β = α` or `β` acute, and
`z_γ(m, ζ)` for `γ ⊥ α` (`m ∈ M`, `ζ ∈ A`). -/
def zAlpha : Subgroup (SteinbergGroup I A) :=
  Subgroup.closure
    ({g | ∃ (p q : I) (hpq : p ≠ q) (m : A), m ∈ M ∧ ((p = i ∧ q = j) ∨ Acute i j p q) ∧
        x p q hpq m = g} ∪
      {g | ∃ (p q : I) (hpq : p ≠ q) (m ζ : A), m ∈ M ∧ Orth i j p q ∧ zElt p q hpq m ζ = g})

/-- **L–S Remark 5.11**: the image of `Z_α(A, M)` in `St(A[X])` lies in `P̃_α(0)`. -/
theorem map_zAlpha_le :
    (zAlpha M i j).map (ringMap (C : A →+* Polynomial A)) ≤ pZero M i j hij := by
  rw [zAlpha, MonoidHom.map_closure, Subgroup.closure_le]
  rintro _ ⟨g, hg | hg, rfl⟩
  · obtain ⟨p, q, hpq, m, hm, hr, rfl⟩ := hg
    have hCm : C m ∈ polyIdeal M := Ideal.mem_map_of_mem _ hm
    rw [ringMap_x]
    rcases hr with ⟨rfl, rfl⟩ | hr
    · exact mem_P5 hpq hCm
    · exact x_mem_P2 hij hpq hr hCm
  · obtain ⟨p, q, hpq, m, ζ, hm, hO, rfl⟩ := hg
    have hCm : C m ∈ polyIdeal M := Ideal.mem_map_of_mem _ hm
    rw [zElt, map_mul, map_mul, ringMap_x, ringMap_x, ringMap_x, map_neg]
    exact mem_P3 hij hpq hO hCm (C ζ)

#audit_axioms map_zAlpha_le

end ZAlpha

end LSCore
end BooneHigmanLinear
end GroupApproximation
