import GroupApproximation.PropertyT.A2MagicHilbert
import GroupApproximation.PropertyT.ExponentFreeClassTwoOrthogonality
import GroupApproximation.PropertyT.IntegralCharacterMass
import GroupApproximation.Steinberg.GeneralRankElementaryPropertyT

/-!
# The magic-graph Kazhdan-subset theorem with no bounded exponent

`A2MagicHilbert.exists_rootSet_isKazhdan` proves that the union of the six
`A₂` root subgroups is a Kazhdan subset, but only when all root elements
share one positive exponent `n`.  Over a torsion-free coefficient ring no
such exponent exists, so the theorem as stated says nothing in
characteristic zero.

The exponent is an artifact of the tree's proof, not of the printed
theorem.  Tracing `hexp` through the chain

  `A2MagicHilbert.exists_rootSet_isKazhdan`
    ← `exists_vertexCodistanceBound` ← `exists_constantProjectionBound`
    ← `norm_le_inverseGap_mul_norm_compressedLaplacian`
    ← `compressedLaplacian_quadratic_gap`
    ← `A2MagicEnergy.vertexMovingLaplacianEnergy_lt_two_mul_edgeEnergy`
    ← `A2MagicEnergy.vertexMovingLaplacianEnergy_le_with_defect`
    ← `A2MagicGraph.incidentMovingLaplacian_norm_sq_le_with_defect`
    ← `A2MagicGraph.incidentMovingProjection_norm_sq_le_with_defect`
    ← `A2MagicGraph.vertex_four_fixed_norm_sq_le_restricted_with_defect`
    ← `A2System.rootFixedSubspaces_epsilonOrthogonal_restricted_of_root_boundedExponent`

shows that `n`, `hn` and `hexp` are inert parameters in every link but the
last, where they are spent on `ClassTwoOrthogonality.epsilonOrthogonal` to
obtain the `1 / sqrt 2` vertex angle.  That angle is available with no
exponent at all from `ExponentFreeClassTwoOrthogonality.epsilonOrthogonality`,
whose hypotheses are exactly the ones the vertex already satisfies.  This
matches the printed statement: Ershov--Jaikin-Zapirain, *Property (T) for
noncommutative universal lattices*, Proposition 4.8, asserts the `1 / sqrt 2`
bound for **any** group of nilpotency class two generated by two abelian
subgroups, with no exponent and no finiteness.

This file re-derives the chain with the hypothesis deleted.  Nothing is
edited; every statement below is the corresponding statement of
`A2MagicGraphEstimates`, `A2MagicEnergy` or `A2MagicHilbert` with `n`, `hn`,
`hexp` removed, and every proof is the corresponding proof with the vertex
angle supplied exponent-freely.

## Main results

* `rootFixedSubspaces_epsilonOrthogonal` -- the `1 / sqrt 2` vertex angle for
  an arbitrary `A₂` system, no exponent.
* `exists_rootSet_isKazhdan` -- **the union of the six `A₂` root subgroups is
  a Kazhdan subset of any group carrying a strongly graded `A₂` system.**  No
  hypothesis whatsoever beyond the system itself.
* `elementary_exists_rootSet_isKazhdan` -- the rank-three elementary
  instance, for **every** ring, characteristic zero included.
* `blockElementary_exists_rootSet_isKazhdan` -- the rank-`n` rectangular
  block instance, for every `n ≥ 3` and every ring.

## What this does and does not give in characteristic zero

It gives the *Kazhdan-subset* half of the Ershov--Jaikin-Zapirain
certificate over `ℤ⟨X⟩`.  It does **not** give property `(T)`: the second,
independent half is a finite control set, and
`PropertyT/IntegralCharacterMass.lean` isolates exactly what is missing
there (`ColumnPlaneMassBound` over `FreeAlgebra ℤ X`, an equidistribution
estimate for the shear action on the dual torus).  In the printed proof that
half is Kassabov's relative property `(T)` for `(EL₂(R) ⋉ R², R²)`, which is
not in this repository in any form.  Nothing here bears on it.
-/

namespace GroupApproximation

universe u v

namespace A2MagicExponentFree

open scoped commutatorElement
open A2MagicGraph
open A2MagicEnergy
open A2MagicHilbert

variable {G : Type u} [Group G]
variable {E : Type v} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [CompleteSpace E]

/-! ### The vertex angle, exponent-free -/

/-- **The `1 / sqrt 2` angle between the two root fixed spaces at an `A₂`
vertex, with no bounded-exponent hypothesis.**  This is
`A2System.rootFixedSubspaces_epsilonOrthogonal_restricted_of_root_boundedExponent`
with `n`, `hn`, `hexp` deleted; the two root subgroups still generate the
vertex group and their cross-commutator is still central, which is all that
`ExponentFreeClassTwoOrthogonality.epsilonOrthogonality` needs. -/
theorem rootFixedSubspaces_epsilonOrthogonal_restricted
    (A : A2System G) (r : A2Root)
    (rho : A.vertexGroup r →* (E ≃ₗᵢ[ℝ] E))
    (hno : IsKazhdanPair.HasNoInvariantVectors (A.vertexGroup r) rho) :
    HilbertEpsilonOrthogonality.EpsilonOrthogonal
      (KazhdanFixedSpace.fixedSubspace rho
        ((A.leftRootGroup r).subgroupOf (A.vertexGroup r)))
      (KazhdanFixedSpace.fixedSubspace rho
        ((A.rightRootGroup r).subgroupOf (A.vertexGroup r)))
      (Real.sqrt 2)⁻¹ := by
  let i := r.1.1
  let j := r.1.2
  let k := a2ThirdIndex i j
  have hik : i ≠ k := (a2ThirdIndex_ne_left i j r.2).symm
  have hkj : k ≠ j := a2ThirdIndex_ne_right i j r.2
  let X := A.leftRootGroup r
  let Y := A.rightRootGroup r
  let L := A.vertexGroup r
  let XL := X.subgroupOf L
  let YL := Y.subgroupOf L
  let ZL := (A.rootAt r).subgroupOf L
  have hgen : XL ⊔ YL = ⊤ :=
    ClassTwoNormalForm.subgroupOf_sup_eq_top X Y L
      (A.leftRoot_le_vertexGroup r) (A.rightRoot_le_vertexGroup r) rfl
  have hcomm : ⁅YL, XL⁆ ≤ ZL := by
    apply Subgroup.commutator_le.mpr
    intro y hy x hx
    apply Subgroup.mem_subgroupOf.mpr
    have hxy : ⁅x.1, y.1⁆ ∈ A.rootAt r :=
      A.commutator_mem i k j hik hkj r.2 x.1
        (Subgroup.mem_subgroupOf.mp hx) y.1
        (Subgroup.mem_subgroupOf.mp hy)
    change ⁅y.1, x.1⁆ ∈ A.rootAt r
    rw [← commutatorElement_inv x.1 y.1]
    exact (A.rootAt r).inv_mem hxy
  have hcentral : ⁅YL, XL⁆ ≤ Subgroup.center L :=
    hcomm.trans (A.rootAt_subgroupOf_le_center r)
  exact ExponentFreeClassTwoOrthogonality.epsilonOrthogonality rho XL YL hgen
    hcentral hno

/-! ### The local defect estimates -/

/-- `A2MagicGraph.vertex_four_fixed_norm_sq_le_restricted_with_defect`
without the exponent. -/
theorem vertex_four_fixed_norm_sq_le_restricted_with_defect
    (A : A2System G) (r : A2Root)
    (rho : A.vertexGroup r →* (E ≃ₗᵢ[ℝ] E))
    (hno : IsKazhdanPair.HasNoInvariantVectors (A.vertexGroup r) rho)
    {p q s t : E}
    (hp : p ∈ KazhdanFixedSpace.fixedSubspace rho
      ((A.leftEdgeGroup r).subgroupOf (A.vertexGroup r)))
    (hq : q ∈ KazhdanFixedSpace.fixedSubspace rho
      ((A.rightEdgeGroup r).subgroupOf (A.vertexGroup r)))
    (hs : s ∈ KazhdanFixedSpace.fixedSubspace rho
      ((A.leftRootGroup r).subgroupOf (A.vertexGroup r)))
    (ht : t ∈ KazhdanFixedSpace.fixedSubspace rho
      ((A.rightRootGroup r).subgroupOf (A.vertexGroup r))) :
    let Z := (A.rootAt r).subgroupOf (A.vertexGroup r)
    let sN := s - KazhdanFixedSpace.fixedProjection rho Z s
    let tN := t - KazhdanFixedSpace.fixedProjection rho Z t
    ‖p + q + s + t‖ ^ 2 ≤
      2 * (‖p‖ ^ 2 + ‖q‖ ^ 2 + ‖s‖ ^ 2 + ‖t‖ ^ 2) -
        (1 - (Real.sqrt 2)⁻¹) * (‖sN‖ ^ 2 + ‖tN‖ ^ 2) := by
  let L := A.vertexGroup r
  let X := (A.leftRootGroup r).subgroupOf L
  let Y := (A.rightRootGroup r).subgroupOf L
  let Z := (A.rootAt r).subgroupOf L
  let H := (A.leftEdgeGroup r).subgroupOf L
  let K := (A.rightEdgeGroup r).subgroupOf L
  have hXZ : X ⊔ Z = H := by
    rw [← Subgroup.subgroupOf_sup (A.leftRoot_le_vertexGroup r)
      (A.rootAt_le_vertexGroup r)]
    rfl
  have hYZ : Y ⊔ Z = K := by
    rw [← Subgroup.subgroupOf_sup (A.rightRoot_le_vertexGroup r)
      (A.rootAt_le_vertexGroup r)]
    rfl
  have hZcenter : Z ≤ Subgroup.center L := A.rootAt_subgroupOf_le_center r
  have hXnorm : X ≤ Subgroup.normalizer (Z : Set L) := by
    intro x hx
    apply Subgroup.centralizer_le_normalizer (Z : Set L)
    rw [Subgroup.mem_centralizer_iff]
    intro z hz
    exact (Subgroup.mem_center_iff.mp (hZcenter hz) x).symm
  have hYnorm : Y ≤ Subgroup.normalizer (Z : Set L) := by
    intro y hy
    apply Subgroup.centralizer_le_normalizer (Z : Set L)
    rw [Subgroup.mem_centralizer_iff]
    intro z hz
    exact (Subgroup.mem_center_iff.mp (hZcenter hz) y).symm
  letI : H.Normal := A.leftEdgeGroup_normalIn_vertexGroup r
  have hedgeHK := KazhdanFixedSpace.fixedSubspaces_isOrtho_of_normal_generate
    rho H K (A.edgeSubgroups_sup_top r) hno
  have hedge : KazhdanFixedSpace.fixedSubspace rho (X ⊔ Z) ⟂
      KazhdanFixedSpace.fixedSubspace rho (Y ⊔ Z) := by
    simpa [hXZ, hYZ] using hedgeHK
  have hangle := rootFixedSubspaces_epsilonOrthogonal_restricted A r rho hno
  apply NormalEdgeCodistance.four_fixed_norm_sq_le_with_defect
    rho X Y Z (by positivity) hXnorm hYnorm hedge
  · simpa [X, Y] using hangle
  · simpa [hXZ] using hp
  · simpa [hYZ] using hq
  · exact hs
  · exact ht

/-- `A2MagicGraph.incidentMovingProjection_norm_sq_le_with_defect` without
the exponent. -/
theorem incidentMovingProjection_norm_sq_le_with_defect
    (A : A2System G) (rho : G →* (E ≃ₗᵢ[ℝ] E))
    (f : A2Root → E)
    (hf : ∀ r, f r ∈ KazhdanFixedSpace.fixedSubspace rho (A.vertexGroup r))
    (r : A2Root) :
    let L := A.vertexGroup r
    let W := KazhdanFixedSpace.subgroupMovingSubspace rho L
    let d : Fin 4 → E := fun n ↦ f r - f (neighbor r n)
    let p : Fin 4 → W := fun n ↦
      ⟨KazhdanFixedSpace.subgroupMovingProjection rho L (d n),
        KazhdanFixedSpace.subgroupMovingProjection_mem rho L (d n)⟩
    ‖∑ n : Fin 4, p n‖ ^ 2 ≤
      2 * ∑ n : Fin 4, ‖p n‖ ^ 2 -
        (1 - (Real.sqrt 2)⁻¹) *
          (‖centralMovingIncidentComponent A rho f r 2‖ ^ 2 +
            ‖centralMovingIncidentComponent A rho f r 3‖ ^ 2) := by
  let L := A.vertexGroup r
  let W := KazhdanFixedSpace.subgroupMovingSubspace rho L
  letI : CompleteSpace W := by
    dsimp [W, KazhdanFixedSpace.subgroupMovingSubspace]
    exact (KazhdanFixedSpace.fixedSubspace rho L).isClosed_orthogonal.completeSpace_coe
  let rhoW := KazhdanFixedSpace.subgroupMovingRepresentation rho L
  let d : Fin 4 → E := fun n ↦ f r - f (neighbor r n)
  let p : Fin 4 → W := fun n ↦
    ⟨KazhdanFixedSpace.subgroupMovingProjection rho L (d n),
      KazhdanFixedSpace.subgroupMovingProjection_mem rho L (d n)⟩
  let Z := (A.rootAt r).subgroupOf L
  let sN : W := p 2 - KazhdanFixedSpace.fixedProjection rhoW Z (p 2)
  let tN : W := p 3 - KazhdanFixedSpace.fixedProjection rhoW Z (p 3)
  have hd (n : Fin 4) : d n ∈
      KazhdanFixedSpace.fixedSubspace rho (edgeGroup A r n) :=
    vertexFixed_sub_neighbor_mem_edgeFixed A rho f hf r n
  have hp (n : Fin 4) : p n ∈ KazhdanFixedSpace.fixedSubspace rhoW
      ((edgeGroup A r n).subgroupOf L) := by
    exact KazhdanFixedSpace.subgroupMovingProjection_mem_restricted_fixedSubspace
      rho (edgeGroup A r n) L (edgeGroup_le_sourceVertex A r n) (hd n)
  have hlocal := vertex_four_fixed_norm_sq_le_restricted_with_defect
    A r rhoW
    (KazhdanFixedSpace.subgroupMovingRepresentation_hasNoInvariantVectors rho L)
    (p := p 0) (q := p 1) (s := p 2) (t := p 3)
    (by simpa [edgeGroup] using hp 0)
    (by simpa [edgeGroup] using hp 1)
    (by simpa [edgeGroup, A2System.leftRootGroup] using hp 2)
    (by simpa [edgeGroup, A2System.rightRootGroup] using hp 3)
  simpa [Fin.sum_univ_succ, add_assoc, Z, sN, tN,
    centralMovingIncidentComponent, KazhdanFixedSpace.nestedMovingProjection,
    L, W, rhoW, d, p] using hlocal

/-- `A2MagicGraph.incidentMovingLaplacian_norm_sq_le_with_defect` without the
exponent. -/
theorem incidentMovingLaplacian_norm_sq_le_with_defect
    (A : A2System G) (rho : G →* (E ≃ₗᵢ[ℝ] E))
    (f : A2Root → E)
    (hf : ∀ r, f r ∈ KazhdanFixedSpace.fixedSubspace rho (A.vertexGroup r))
    (r : A2Root) :
    let L := A.vertexGroup r
    let d : Fin 4 → E := fun n ↦ f r - f (neighbor r n)
    ‖KazhdanFixedSpace.subgroupMovingProjection rho L (∑ n, d n)‖ ^ 2 ≤
      2 * ∑ n, ‖KazhdanFixedSpace.subgroupMovingProjection rho L (d n)‖ ^ 2 -
        (1 - (Real.sqrt 2)⁻¹) *
          (‖centralMovingIncidentComponent A rho f r 2‖ ^ 2 +
            ‖centralMovingIncidentComponent A rho f r 3‖ ^ 2) := by
  have h := incidentMovingProjection_norm_sq_le_with_defect A rho f hf r
  simpa [KazhdanFixedSpace.subgroupMovingProjection] using h

/-! ### The summed energy estimates -/

/-- `A2MagicEnergy.vertexMovingLaplacianEnergy_le_with_defect` without the
exponent. -/
theorem vertexMovingLaplacianEnergy_le_with_defect
    (A : A2System G) (rho : G →* (E ≃ₗᵢ[ℝ] E))
    (f : A2Root → E)
    (hf : ∀ r, f r ∈ KazhdanFixedSpace.fixedSubspace rho (A.vertexGroup r)) :
    vertexMovingLaplacianEnergy A rho f ≤
      2 * vertexMovingEdgeEnergy A rho f -
        (1 - (Real.sqrt 2)⁻¹) * centralMovingEdgeEnergy A rho f := by
  unfold vertexMovingLaplacianEnergy vertexMovingEdgeEnergy
    centralMovingEdgeEnergy vertexMovingLaplacian vertexMovingEdgeComponent
    edgeDifference
  calc
    ∑ r : A2Root,
        ‖KazhdanFixedSpace.subgroupMovingProjection rho (A.vertexGroup r)
          (∑ n : Fin 4, (f r - f (neighbor r n)))‖ ^ 2 ≤
      ∑ r : A2Root,
        (2 * ∑ n : Fin 4,
            ‖KazhdanFixedSpace.subgroupMovingProjection rho (A.vertexGroup r)
              (f r - f (neighbor r n))‖ ^ 2 -
          (1 - (Real.sqrt 2)⁻¹) *
            (‖centralMovingIncidentComponent A rho f r 2‖ ^ 2 +
              ‖centralMovingIncidentComponent A rho f r 3‖ ^ 2)) := by
        apply Finset.sum_le_sum
        intro r hr
        exact incidentMovingLaplacian_norm_sq_le_with_defect A rho f hf r
    _ = 2 * ∑ r : A2Root, ∑ n : Fin 4,
          ‖KazhdanFixedSpace.subgroupMovingProjection rho (A.vertexGroup r)
            (f r - f (neighbor r n))‖ ^ 2 -
        (1 - (Real.sqrt 2)⁻¹) *
          ∑ r : A2Root,
            (‖centralMovingIncidentComponent A rho f r 2‖ ^ 2 +
              ‖centralMovingIncidentComponent A rho f r 3‖ ^ 2) := by
      rw [Finset.sum_sub_distrib, Finset.mul_sum, Finset.mul_sum]

/-- `A2MagicEnergy.vertexMovingLaplacianEnergy_lt_two_mul_edgeEnergy` without
the exponent. -/
theorem vertexMovingLaplacianEnergy_lt_two_mul_edgeEnergy
    (A : A2System G) (rho : G →* (E ≃ₗᵢ[ℝ] E))
    (f : A2Root → E)
    (hf : ∀ r, f r ∈ KazhdanFixedSpace.fixedSubspace rho (A.vertexGroup r)) :
    vertexMovingLaplacianEnergy A rho f ≤
      (2 - (1 - (Real.sqrt 2)⁻¹) / 3) * edgeEnergy f := by
  let c : ℝ := 1 - (Real.sqrt 2)⁻¹
  let D := edgeEnergy f
  let M := vertexMovingEdgeEnergy A rho f
  let F := vertexFixedEdgeEnergy A rho f
  let R := centralMovingEdgeEnergy A rho f
  have hsqrt0 : 0 < Real.sqrt 2 := Real.sqrt_pos.2 (by norm_num)
  have hsqrtSq : (Real.sqrt 2) ^ 2 = 2 := Real.sq_sqrt (by norm_num)
  have hsqrt1 : (1 : ℝ) ≤ Real.sqrt 2 := by
    have hsqrtNonneg := Real.sqrt_nonneg 2
    nlinarith
  have hinv0 : 0 ≤ (Real.sqrt 2)⁻¹ := inv_nonneg.mpr hsqrt0.le
  have hinv1 : (Real.sqrt 2)⁻¹ ≤ 1 :=
    (inv_le_one₀ hsqrt0).2 hsqrt1
  have hc0 : 0 ≤ c := by dsimp [c]; linarith
  have hc1 : c ≤ 1 := by dsimp [c]; linarith
  have hF0 : 0 ≤ F := by
    dsimp [F, vertexFixedEdgeEnergy]
    positivity
  have hclaim : D ≤ 3 * R + 5 * F := by
    exact edgeEnergy_le_three_root_add_five_vertex A rho f hf
  have hscaled : (c / 3) * D ≤ (c / 3) * (3 * R + 5 * F) :=
    mul_le_mul_of_nonneg_left hclaim (div_nonneg hc0 (by norm_num))
  have hcoef : 5 * (c / 3) ≤ 2 := by nlinarith
  have hcoefF : 5 * (c / 3) * F ≤ 2 * F :=
    mul_le_mul_of_nonneg_right hcoef hF0
  have hdefect : (c / 3) * D ≤ c * R + 2 * F := by
    calc
      (c / 3) * D ≤ (c / 3) * (3 * R + 5 * F) := hscaled
      _ = c * R + 5 * (c / 3) * F := by ring
      _ ≤ c * R + 2 * F := by linarith
  have hsplit : D = M + F := edgeEnergy_eq_moving_add_fixed A rho f
  have hlocal : vertexMovingLaplacianEnergy A rho f ≤ 2 * M - c * R := by
    exact vertexMovingLaplacianEnergy_le_with_defect A rho f hf
  change vertexMovingLaplacianEnergy A rho f ≤ (2 - c / 3) * D
  nlinarith

/-! ### The spectral gap and the Kazhdan subset -/

/-- `A2MagicHilbert.compressedLaplacian_quadratic_gap` without the
exponent. -/
theorem compressedLaplacian_quadratic_gap
    (A : A2System G) (rho : G →* (E ≃ₗᵢ[ℝ] E))
    (f : vertexFixedSubspace A rho) :
    (2 * (1 - (Real.sqrt 2)⁻¹) / 3) *
        inner ℝ f (compressedLaplacian A rho f) ≤
      ‖compressedLaplacian A rho f‖ ^ 2 := by
  let D := A2MagicLaplacian.directedEnergy (f : Family E)
  let B := vertexMovingLaplacianEnergy A rho (rootReindex (f : Family E))
  let d : ℝ := 1 - (Real.sqrt 2)⁻¹
  let beta : ℝ := 2 - d / 3
  have hfixed (r : A2Root) :
      rootReindex (f : Family E) r ∈
        KazhdanFixedSpace.fixedSubspace rho (A.vertexGroup r) :=
    rootReindex_mem_vertexFixedSubspace A rho f r
  have hstrict : B ≤ beta * D := by
    have h := vertexMovingLaplacianEnergy_lt_two_mul_edgeEnergy
      A rho (rootReindex (f : Family E)) hfixed
    rw [edgeEnergy_rootReindex] at h
    exact h
  have hgraph : 2 * D ≤ ‖laplacianFamily (f : Family E)‖ ^ 2 := by
    have h := A2MagicLaplacian.two_directedEnergy_le_sum_laplacian_norm_sq_general
      (fun i ↦ (f : Family E) i)
    calc
      2 * D ≤ ∑ i : Fin 6,
          ‖A2MagicLaplacian.laplacian (f : Family E) i‖ ^ 2 := h
      _ = ‖laplacianFamily (f : Family E)‖ ^ 2 :=
        (norm_laplacianFamily_sq _).symm
  have hsplit := norm_laplacianFamily_sq_eq_compressed_add_moving A rho f
  have henergy := directedEnergy_eq_two_inner_compressedLaplacian A rho f
  have hcombine : 2 * D ≤
      ‖compressedLaplacian A rho f‖ ^ 2 + beta * D := by
    calc
      2 * D ≤ ‖laplacianFamily (f : Family E)‖ ^ 2 := hgraph
      _ = ‖compressedLaplacian A rho f‖ ^ 2 + B := hsplit
      _ ≤ ‖compressedLaplacian A rho f‖ ^ 2 + beta * D := by
        simpa [add_comm] using
          add_le_add_right hstrict (‖compressedLaplacian A rho f‖ ^ 2)
  have hcomp : (2 - beta) * D ≤
      ‖compressedLaplacian A rho f‖ ^ 2 := by
    calc
      (2 - beta) * D = 2 * D - beta * D := by ring
      _ ≤ ‖compressedLaplacian A rho f‖ ^ 2 := by linarith
  have hcoef : 2 - beta = d / 3 := by
    dsimp [beta]
    ring
  change (2 * d / 3) * inner ℝ f (compressedLaplacian A rho f) ≤ _
  have henergyD : D = 2 * inner ℝ f (compressedLaplacian A rho f) := henergy
  calc
    (2 * d / 3) * inner ℝ f (compressedLaplacian A rho f) =
        (d / 3) * D := by rw [henergyD]; ring
    _ = (2 - beta) * D := by rw [hcoef]
    _ ≤ ‖compressedLaplacian A rho f‖ ^ 2 := hcomp

/-- `A2MagicHilbert.norm_le_inverseGap_mul_norm_compressedLaplacian` without
the exponent. -/
theorem norm_le_inverseGap_mul_norm_compressedLaplacian
    (A : A2System G) (rho : G →* (E ≃ₗᵢ[ℝ] E))
    (hno : IsKazhdanPair.HasNoInvariantVectors G rho)
    (f : vertexFixedSubspace A rho) :
    let c : ℝ := 2 * (1 - (Real.sqrt 2)⁻¹) / 3
    ‖f‖ ≤ (c * (1 - Real.sqrt (1 - c / 8)))⁻¹ *
      ‖compressedLaplacian A rho f‖ := by
  let W := vertexFixedSubspace A rho
  letI : CompleteSpace W :=
    (isClosed_vertexFixedSubspace A rho).completeSpace_coe
  let c : ℝ := 2 * (1 - (Real.sqrt 2)⁻¹) / 3
  have hsqrt0 : 0 < Real.sqrt 2 := Real.sqrt_pos.2 (by norm_num)
  have hsqrtSq : (Real.sqrt 2) ^ 2 = 2 := Real.sq_sqrt (by norm_num)
  have hsqrt1 : (1 : ℝ) < Real.sqrt 2 := by
    have hsqrtNonneg := Real.sqrt_nonneg 2
    nlinarith
  have hinv0 : 0 ≤ (Real.sqrt 2)⁻¹ := inv_nonneg.mpr hsqrt0.le
  have hinv1 : (Real.sqrt 2)⁻¹ < 1 :=
    (inv_lt_one₀ hsqrt0).2 hsqrt1
  have hc : 0 < c := by
    dsimp [c]
    nlinarith
  have hc8 : c ≤ 8 := by
    dsimp [c]
    nlinarith
  apply PositiveOperatorGap.norm_le_of_quadratic_gap
    (compressedLaplacian A rho) hc (by norm_num) hc8
  · intro x y
    exact inner_compressedLaplacian_comm A rho x y
  · intro x
    simpa [PositiveOperatorGap.energy] using
      compressedLaplacian_energy_nonneg A rho x
  · intro x
    simpa [c, PositiveOperatorGap.energy] using
      compressedLaplacian_quadratic_gap A rho x
  · intro x
    simpa [PositiveOperatorGap.energy] using
      compressedLaplacian_energy_le_eight_norm_sq A rho x
  · intro x
    simpa [PositiveOperatorGap.energy] using
      norm_compressedLaplacian_sq_le_eight_energy A rho x
  · intro x hx
    exact compressedLaplacian_eq_zero_imp A rho hno x hx

/-- `A2MagicHilbert.exists_constantProjectionBound` without the exponent. -/
theorem exists_constantProjectionBound (A : A2System G) :
    ∃ gamma : ℝ, 0 ≤ gamma ∧ gamma < 1 ∧
      ConstantProjectionBound.{u, v} A gamma := by
  let c : ℝ := 2 * (1 - (Real.sqrt 2)⁻¹) / 3
  let K : ℝ := (c * (1 - Real.sqrt (1 - c / 8)))⁻¹
  let a : ℝ := 8 * K
  let gamma : ℝ := a ^ 2 / (1 + a ^ 2)
  have hsqrt0 : 0 < Real.sqrt 2 := Real.sqrt_pos.2 (by norm_num)
  have hsqrtSq : (Real.sqrt 2) ^ 2 = 2 := Real.sq_sqrt (by norm_num)
  have hsqrt1 : (1 : ℝ) < Real.sqrt 2 := by
    have hsqrtNonneg := Real.sqrt_nonneg 2
    nlinarith
  have hinv0 : 0 ≤ (Real.sqrt 2)⁻¹ := inv_nonneg.mpr hsqrt0.le
  have hinv1 : (Real.sqrt 2)⁻¹ < 1 :=
    (inv_lt_one₀ hsqrt0).2 hsqrt1
  have hc : 0 < c := by
    dsimp [c]
    nlinarith
  have hc8 : c ≤ 8 := by
    dsimp [c]
    nlinarith
  have hr0 : 0 ≤ 1 - c / 8 := by nlinarith
  have hr1 : 1 - c / 8 < 1 := by nlinarith
  have hs0 : 0 ≤ Real.sqrt (1 - c / 8) := Real.sqrt_nonneg _
  have hsSq : (Real.sqrt (1 - c / 8)) ^ 2 = 1 - c / 8 :=
    Real.sq_sqrt hr0
  have hs1 : Real.sqrt (1 - c / 8) < 1 := by
    nlinarith
  have hden : 0 < c * (1 - Real.sqrt (1 - c / 8)) :=
    mul_pos hc (sub_pos.mpr hs1)
  have hK0 : 0 ≤ K := inv_nonneg.mpr hden.le
  have ha0 : 0 ≤ a := mul_nonneg (by norm_num) hK0
  have hgamma0 : 0 ≤ gamma := by
    dsimp [gamma]
    positivity
  have hgamma1 : gamma < 1 := by
    dsimp [gamma]
    apply (div_lt_one (by positivity : 0 < 1 + a ^ 2)).2
    linarith
  refine ⟨gamma, hgamma0, hgamma1, ?_⟩
  intro E _ _ _ rho hno x
  let W := vertexFixedSubspace A rho
  letI : CompleteSpace W :=
    (isClosed_vertexFixedSubspace A rho).completeSpace_coe
  let y : Family E := constantFamily x
  let p₀ : Family E := vertexProjectionFamily A rho y
  let p : W := ⟨p₀, vertexProjectionFamily_mem A rho y⟩
  let q : Family E := y - p₀
  have hprojection : W.starProjection y = p₀ := by
    exact starProjection_vertexFixedSubspace A rho y
  have hqOrth : q ∈ Wᗮ := by
    change y - p₀ ∈ Wᗮ
    rw [← hprojection]
    exact W.sub_starProjection_mem_orthogonal y
  have hpOrth : inner ℝ p₀ q = 0 :=
    Submodule.inner_right_of_mem_orthogonal p.property hqOrth
  have hpyth : ‖y‖ ^ 2 = ‖p₀‖ ^ 2 + ‖q‖ ^ 2 := by
    have hsplit : y = p₀ + q := by
      dsimp [q]
      abel
    calc
      ‖y‖ ^ 2 = ‖p₀ + q‖ ^ 2 :=
        congrArg (fun z : Family E ↦ ‖z‖ ^ 2) hsplit
      _ = ‖p₀‖ ^ 2 + ‖q‖ ^ 2 := by
        simpa [pow_two] using
          norm_add_sq_eq_norm_sq_add_norm_sq_real hpOrth
  have hLy : laplacianFamily y = 0 := by
    apply PiLp.ext
    intro i
    change A2MagicLaplacian.laplacian (fun _ : Fin 6 ↦ x) i = 0
    exact A2MagicLaplacian.laplacian_const x i
  have hnormL : ‖laplacianFamily p₀‖ = ‖laplacianFamily q‖ := by
    have hLq : laplacianFamily q = -laplacianFamily p₀ := by
      dsimp [q]
      rw [map_sub, hLy, zero_sub]
    simpa using (congrArg norm hLq).symm
  have hop : ‖compressedLaplacian A rho p‖ ≤ 8 * ‖q‖ := by
    calc
      ‖compressedLaplacian A rho p‖ ≤
          ‖laplacianFamily (p : Family E)‖ := by
        exact W.norm_orthogonalProjectionOnto_apply_le _
      _ = ‖laplacianFamily p₀‖ := rfl
      _ = ‖laplacianFamily q‖ := hnormL
      _ ≤ 8 * ‖q‖ := norm_laplacianFamily_le_eight q
  have hinverse := norm_le_inverseGap_mul_norm_compressedLaplacian
    A rho hno p
  change ‖p₀‖ ≤ K * ‖compressedLaplacian A rho p‖ at hinverse
  have hpq : ‖p₀‖ ≤ a * ‖q‖ := by
    calc
      ‖p₀‖ ≤ K * ‖compressedLaplacian A rho p‖ := hinverse
      _ ≤ K * (8 * ‖q‖) := mul_le_mul_of_nonneg_left hop hK0
      _ = a * ‖q‖ := by dsimp [a]; ring
  have hpqSq : ‖p₀‖ ^ 2 ≤ a ^ 2 * ‖q‖ ^ 2 := by
    have hsq := (sq_le_sq₀ (norm_nonneg _)
      (mul_nonneg ha0 (norm_nonneg _))).2 hpq
    nlinarith
  change ‖p₀‖ ^ 2 ≤ gamma * ‖y‖ ^ 2
  rw [hpyth]
  dsimp [gamma]
  rw [div_mul_eq_mul_div]
  apply (le_div_iff₀ (by positivity : 0 < 1 + a ^ 2)).2
  nlinarith

/-- `A2MagicHilbert.exists_vertexCodistanceBound` without the exponent. -/
theorem exists_vertexCodistanceBound (A : A2System G) :
    ∃ gamma : ℝ, 0 ≤ gamma ∧ gamma < 1 ∧
      A2System.VertexCodistanceBound.{u, v} A gamma := by
  obtain ⟨gamma, hgamma0, hgamma1, hprojection⟩ :=
    exists_constantProjectionBound A
  exact ⟨gamma, hgamma0, hgamma1,
    A.vertexCodistanceBound_of_projectionBound hgamma0
      (vertexProjectionBound_of_constantProjectionBound A hprojection)⟩

/-- **The union of the six `A₂` root subgroups is a Kazhdan subset, with no
hypothesis at all.**

This is `A2MagicHilbert.exists_rootSet_isKazhdan` with the bounded-exponent
input deleted.  It is the Ershov--Jaikin-Zapirain graded-group theorem in the
generality of the printed statement: the only fact used about the ambient
group is that it carries a strongly graded `A₂` root system. -/
theorem exists_rootSet_isKazhdan (A : A2System G) :
    ∃ kappa : ℝ, IsKazhdanSubset.{u, v} G A.rootSet kappa := by
  obtain ⟨gamma, hgamma0, hgamma1, hcodistance⟩ :=
    exists_vertexCodistanceBound A
  exact ⟨(1 - gamma) / 32,
    A.rootSet_isKazhdan_of_vertexCodistanceBound
      hgamma0 hgamma1 hcodistance⟩

end A2MagicExponentFree

/-! ### The elementary instances, over every ring -/

/-- **For every ring, with no characteristic hypothesis, the union of the six
elementary rank-three root subgroups is a Kazhdan subset.**  This is
`A2MagicHilbert.elementary_exists_rootSet_isKazhdan` with `CharP R p` and
`0 < p` deleted; in particular it applies to `ℤ⟨X⟩`. -/
theorem elementary_exists_rootSet_isKazhdan (R : Type u) [Ring R] :
    ∃ kappa : ℝ,
      IsKazhdanSubset.{u, v}
        (elementaryGroup (Fin 3) R)
        (elementaryA2System R).rootSet kappa :=
  A2MagicExponentFree.exists_rootSet_isKazhdan.{u, v} (elementaryA2System R)

/-- **For every `n ≥ 3` and every ring, with no characteristic hypothesis,
the union of the six rectangular block roots of `EL_n(R)` is a Kazhdan
subset.**  This is
`BlockElementary.blockElementary_exists_rootSet_isKazhdan` with `CharP R p`
and `0 < p` deleted. -/
theorem blockElementary_exists_rootSet_isKazhdan (R : Type u) [Ring R]
    (n : ℕ) (hn : 3 ≤ n) :
    ∃ kappa : ℝ, IsKazhdanSubset.{u, v} (elementaryGroup (Fin n) R)
      (BlockElementary.blockElementaryA2System R n hn).rootSet kappa :=
  A2MagicExponentFree.exists_rootSet_isKazhdan.{u, v}
    (BlockElementary.blockElementaryA2System R n hn)

/-- The general-coefficient form of the Ershov--Jaikin-Zapirain graded-group
theorem proved in this file: for **every** ring, with no characteristic and
no finiteness hypothesis, and in every rank `n ≥ 3`, the union of the six
rectangular block roots of `EL_n(R)` is a Kazhdan subset.

This is the Kazhdan-subset half of the Ershov--Jaikin-Zapirain certificate.
It is not property `(T)`: the second, independent half is a finite control
set, and over a torsion-free coefficient ring that half is open.  See the
module docstring. -/
def GeneralCoefficientBlockRootSetKazhdan : Prop :=
  ∀ (R : Type) [Ring R] (n : ℕ) (hn : 3 ≤ n),
    ∃ kappa : ℝ, IsKazhdanSubset.{0, 0} (elementaryGroup (Fin n) R)
      (BlockElementary.blockElementaryA2System R n hn).rootSet kappa

theorem generalCoefficientBlockRootSetKazhdan :
    GeneralCoefficientBlockRootSetKazhdan := by
  intro R _ n hn
  exact blockElementary_exists_rootSet_isKazhdan.{0, 0} R n hn

/-! ### What this leaves open in characteristic zero -/

/-- **The characteristic-zero base case now rests on a single open input.**

`IntegralCharacterMass.integral_hasKazhdanPropertyT_of_columnPlaneMassBound`
carries two hypotheses: the plane estimate `ColumnPlaneMassBound` over
`ℤ⟨X⟩`, and the Kazhdan-subset property of the root set.  The second is now
a theorem (`elementary_exists_rootSet_isKazhdan`), so only the first
remains.

That residue is exactly the input Ershov and Jaikin-Zapirain import rather
than prove: Kassabov's relative property `(T)` for `(EL₂(R) ⋉ R², R²)`.  It
is not in this repository, and this file does not supply it. -/
theorem integral_hasKazhdanPropertyT_of_columnPlaneMassBound
    (X : Type u) [Fintype X] {C : ℝ} (hC : 0 ≤ C)
    (hplane : IntegralCharacterMass.ColumnPlaneMassBound.{u, v}
      (FreeAlgebra ℤ X) (IntegralCharacterMass.integralControlSet X) C) :
    HasKazhdanPropertyT.{u, v}
      (elementaryGroup (Fin 3) (FreeAlgebra ℤ X)) := by
  obtain ⟨kappa, hkappa⟩ :=
    elementary_exists_rootSet_isKazhdan.{u, v} (FreeAlgebra ℤ X)
  exact IntegralCharacterMass.integral_hasKazhdanPropertyT_of_columnPlaneMassBound
    X hC hplane hkappa

end GroupApproximation
