import GroupApproximation.Endpoint.MainResults
import GroupApproximation.Endpoint.ManuscriptStatements
import GroupApproximation.Sofic.SoficSequential
import GroupApproximation.Sofic.FreeLampReduction
import GroupApproximation.Sofic.PushoutEmbedding
import GroupApproximation.Sofic.FreeLampDoubleEmbedding
import GroupApproximation.Sofic.WeakMFTransfer
import GroupApproximation.Sofic.WeakMFRegularTrace
import GroupApproximation.Sofic.RegularCharacterGNS
import GroupApproximation.Sofic.WeakMFNonsoficDouble
import GroupApproximation.Sofic.SymmetricDoubleFlip
import GroupApproximation.Sofic.LineDouble
import GroupApproximation.Sofic.DoubleSoficTransfer
import GroupApproximation.Sofic.CentralCoverInheritance
import GroupApproximation.Sofic.ChosenNonMFTheorem
import GroupApproximation.Sofic.ChosenUniversalHorn
import GroupApproximation.Sofic.FiniteNormalCoronaObstruction
import GroupApproximation.Sofic.NormMFPrintedConsequences
import GroupApproximation.Sofic.NormallyGeneratedMFObstruction
import GroupApproximation.Sofic.OperatorMFPositiveControls
import GroupApproximation.Sofic.OperatorMFIncreasingDimensions
import GroupApproximation.Sofic.MarkedGroupWordBall
import GroupApproximation.Sofic.MarkedMFClosed
import GroupApproximation.Sofic.OperatorMFQuotientNonclosure
import GroupApproximation.Sofic.OperatorMFFreeProductConsequences
import GroupApproximation.Analysis.FaithfulTracialMatrix
import GroupApproximation.Analysis.ProperIsometryFromCompression
import GroupApproximation.Analysis.NormMatrixCorona
import GroupApproximation.Analysis.ReducedGroupCStarTrace
import GroupApproximation.Analysis.ReducedGroupCStarTraceFaithful
import GroupApproximation.Analysis.ReducedGroupCStarMFObstruction
import GroupApproximation.Analysis.UniversalKazhdanCStarConsequences
import GroupApproximation.Computability.OperatorMFMarkovWitness
import GroupApproximation.Kazhdan.KazhdanTextbook
import GroupApproximation.Kazhdan.FixedSpaceStabilizer
import GroupApproximation.Monsters.AffineSL3Doubling
import GroupApproximation.Monsters.AffineSL3Scaling
import GroupApproximation.Sofic.MarkedGroupTopology
import GroupApproximation.Sofic.LiteralMarkedCylinderTopology
import GroupApproximation.Sofic.TensorPowerAmplification
import GroupApproximation.Criterion.CompressionCentralizerDefect
import GroupApproximation.Criterion.FiniteDimensionalKill
import GroupApproximation.Monsters.CliffordAlgebraLamp
import GroupApproximation.Monsters.ExplicitLinearModel
import GroupApproximation.Monsters.LiteralCyclicCalibration
import GroupApproximation.Sofic.CompressionDefectSquare
import GroupApproximation.Sofic.IntrinsicCompressionDefect
import GroupApproximation.Sofic.LiteralFiniteDimensionalObstruction
import GroupApproximation.Sofic.LiteralNonMFLinearWitness
import GroupApproximation.Sofic.LiteralNonMFPresentation
import GroupApproximation.Sofic.LiteralBaseRelations
import GroupApproximation.Sofic.LiteralBaseTranslationNormal
import GroupApproximation.Sofic.LiteralBaseRotationRetract
import GroupApproximation.Sofic.LiteralPresentationRadius
import GroupApproximation.Sofic.LiteralUniversalHorn
import GroupApproximation.Sofic.NormalKazhdanCompressionObstruction
import GroupApproximation.Sofic.NormalKazhdanMFRadical
import GroupApproximation.Sofic.NormMFResidualExactQuotient
import GroupApproximation.KOne.ClassicalKOne
import GroupApproximation.KOne.FactorizationCertificate
import GroupApproximation.KOne.PaperStatements
import GroupApproximation.Sofic.FinitelyPresentedLEF
import GroupApproximation.Leavitt.UnitsGLProfile
import GroupApproximation.KOne.AllRanksElementary
import GroupApproximation.Sofic.SoficPositiveControl
import GroupApproximation.Sofic.ExteriorMFProfile
import GroupApproximation.Sofic.HyperlinearNonScalar
import GroupApproximation.Sofic.HyperlinearReduction
import GroupApproximation.Sofic.HyperlinearUltraproduct
import GroupApproximation.Sofic.PhasePropagation
import GroupApproximation.Kun.KunDecomposition
import GroupApproximation.KunThom.KunThomTheorem
import GroupApproximation.PropertyT.FreeElementaryPropertyT
import GroupApproximation.PropertyTT.PaperStatements
import GroupApproximation.PropertyTT.NonsoficCorollary
import GroupApproximation.Kazhdan.KazhdanComplex
import GroupApproximation.Kazhdan.KazhdanUniverse
import GroupApproximation.Kazhdan.InvariantSubsetRounding
import GroupApproximation.Kazhdan.FixedSpaceStabilizer
import GroupApproximation.Kazhdan.FixedSpaceDefect
import GroupApproximation.Kazhdan.DiagonalInvariantRelation
import GroupApproximation.KOne.RefineLoopDischarge
import GroupApproximation.Kazhdan.ShalomFinitePresentation
import GroupApproximation.Covers.KazhdanCover
import GroupApproximation.Leavitt.FamilyRankFour
import GroupApproximation.Matching.AsymptoticPartialGroupoid
import GroupApproximation.Matching.AsymptoticBlockArrow
import GroupApproximation.Matching.FinitePartialClusterGroupoid
import GroupApproximation.Matching.PartialEquivarianceBoundary
import GroupApproximation.Matching.PartialTaggedExpansion
import GroupApproximation.Matching.EditedGeneratorExpansion
import GroupApproximation.Matching.ComponentLabelCompletion
import GroupApproximation.Matching.ComponentCompletedMultiplicativity
import GroupApproximation.Matching.ComponentCompletedAction
import GroupApproximation.Matching.ComponentCompletedSofic
import GroupApproximation.Matching.ComponentClusterScale
import GroupApproximation.Matching.PartialClusterCandidates
import GroupApproximation.Matching.PartialEquivarianceComposition
import GroupApproximation.Matching.PartialClusterPresentation
import GroupApproximation.Matching.PartialBijectionSwap
import GroupApproximation.Matching.PartialSwapEquivariance
import GroupApproximation.Matching.PartialBijectionExtraction
import GroupApproximation.Matching.ExactPartialKazhdanRepair
import GroupApproximation.Matching.ExactKazhdanPartialClusterSystem
import GroupApproximation.Matching.PartialBijectionSandwich
import GroupApproximation.Sofic.InvolutiveCentralizerComponents
import GroupApproximation.Leavitt.StrictCentralCoverWitness
import GroupApproximation.Leavitt.IntegralGeneration
import GroupApproximation.Leavitt.RawSwapCompressors
import GroupApproximation.Leavitt.SelfSimilarityAlgebra
import GroupApproximation.Leavitt.PlaneEmbedding
import GroupApproximation.Leavitt.GeneralRankWords
import GroupApproximation.Leavitt.GeneralScheme
import GroupApproximation.Leavitt.GeneralCornerTheorem
import GroupApproximation.Sofic.Normalization
import GroupApproximation.Leavitt.FamilyVEmbedding
import GroupApproximation.Sofic.FreeGroupResiduallyFinite
import GroupApproximation.Endpoint.QuotientNonclosure
import GroupApproximation.Steinberg.Basic
import GroupApproximation.Steinberg.Perfect
import GroupApproximation.Steinberg.FinitelyGenerated
import GroupApproximation.Steinberg.A2System
import GroupApproximation.Steinberg.A2Kazhdan
import GroupApproximation.Steinberg.BinaryLeavitt
import GroupApproximation.Steinberg.FiniteControl
import GroupApproximation.Steinberg.KervaireSteinberg
import GroupApproximation.Steinberg.RootFiltration
import GroupApproximation.Steinberg.RootActions
import GroupApproximation.Steinberg.RootPlane
import GroupApproximation.Steinberg.RootPlaneFourier
import GroupApproximation.Steinberg.RootCharacterValuationBase
import GroupApproximation.Steinberg.RootCharacterValuation
import GroupApproximation.Steinberg.FreePropertyT
import GroupApproximation.Steinberg.Functoriality
import GroupApproximation.Steinberg.FiniteTypePropertyT

/-!
# Human-readable axiom report

This module pins the axiom reports for the public results and the three most
load-bearing mathematical inputs.  It is imported by the library root, so a
normal `lake build` prints these reports.  The stricter executable gate in
`scripts/Audit.lean` independently traverses the transitive axiom closure of
the entire project namespace and fails on anything beyond classical Lean.
-/

#print axioms GroupApproximation.nonsofic_groups_exist
#print axioms GroupApproximation.countable_nonsofic_groups_exist
#print axioms GroupApproximation.isSofic_iff_admitsEssentiallyFreeNearAction
#print axioms GroupApproximation.universalLeavittEL4_not_admitsEssentiallyFreeNearAction
#print axioms GroupApproximation.countable_group_without_essentiallyFreeNearAction_exists
#print axioms GroupApproximation.universalLeavittEL4_not_isSofic
#print axioms GroupApproximation.universalLeavittEL3_not_isSofic
#print axioms GroupApproximation.universalLeavittUnits_not_isSofic
#print axioms GroupApproximation.universalLeavittGL_not_isSofic
#print axioms GroupApproximation.ambient_profile
#print axioms GroupApproximation.ambient_full_profile
#print axioms GroupApproximation.universalLeavitt_profile
#print axioms GroupApproximation.binaryLeavitt_finiteField_profile
#print axioms GroupApproximation.exists_finitelyPresented_nonsofic_group
#print axioms GroupApproximation.exists_infinite_finitelyPresented_nonsofic_ambient_cover
#print axioms GroupApproximation.KunDecomposition.exists_expanderDecomposition
#print axioms GroupApproximation.KunSelectiveRepairExpansion.refined_bad_component_expands_at_every_positive_constant
#print axioms GroupApproximation.KunThomTheorem.isLEF_of_exactProductExpansion
#print axioms GroupApproximation.commute_of_perfect_quotient
#print axioms GroupApproximation.subgroup_eq_top_of_surjects_mod_central
#print axioms GroupApproximation.CentralExtension.lift_centralizes_perfect_preimage
#print axioms GroupApproximation.SteinbergGroup.projection_surjective
#print axioms GroupApproximation.SteinbergGroup.centralExtension
#print axioms GroupApproximation.SteinbergGroup.fin_isPerfect
#print axioms GroupApproximation.SteinbergGroup.finitelyGenerated
#print axioms GroupApproximation.SteinbergGroup.x_injective
#print axioms GroupApproximation.SteinbergGroup.a2System
#print axioms GroupApproximation.SteinbergGroup.binaryLeavitt_exists_rootSet_isKazhdan
#print axioms GroupApproximation.KervaireSteinberg.commutator_commutes_of_commutators_mem_center
#print axioms GroupApproximation.KervaireSteinberg.commutator_eq_of_eq_mod_center
#print axioms GroupApproximation.KervaireSteinberg.commutator_eq_of_same_projection
#print axioms GroupApproximation.KervaireSteinberg.commutator_commutator_eq
#print axioms GroupApproximation.KervaireSteinberg.lifts_commute_of_spare_index
#print axioms GroupApproximation.KervaireSteinberg.fin_lifts_commute
#print axioms GroupApproximation.KervaireSteinberg.projection_correctedRoot
#print axioms GroupApproximation.KervaireSteinberg.correctedRoot_eq_commutator_of_lifts
#print axioms GroupApproximation.KervaireSteinberg.fin_correctedRoot_eq_of_middle_ne
#print axioms GroupApproximation.KervaireSteinberg.fin_correctedRoot_eq
#print axioms GroupApproximation.KervaireSteinberg.projection_canonicalRoot
#print axioms GroupApproximation.KervaireSteinberg.canonicalRoot_eq_correctedRoot
#print axioms GroupApproximation.KervaireSteinberg.fin_canonicalRoot_commute
#print axioms GroupApproximation.KervaireSteinberg.fin_canonicalRoot_commutator
#print axioms GroupApproximation.KervaireSteinberg.fin_correctedRoot_mul
#print axioms GroupApproximation.KervaireSteinberg.fin_canonicalRoot_mul
#print axioms GroupApproximation.KervaireSteinberg.splittingHom_isSection
#print axioms GroupApproximation.KervaireSteinberg.every_centralExtension_splits
#print axioms GroupApproximation.KervaireSteinberg.correctedRoot_zero
#print axioms GroupApproximation.KervaireSteinberg.fin_correctedRoot_commute
#print axioms GroupApproximation.BinaryLeavittSteinberg.projection_surjective
#print axioms GroupApproximation.BinaryLeavittSteinberg.isPerfect
#print axioms GroupApproximation.BinaryLeavittSteinberg.finitelyGenerated
#print axioms GroupApproximation.BinaryLeavittSteinberg.elementaryBase_hasKazhdanPropertyT
#print axioms GroupApproximation.BinaryLeavittSteinberg.elementaryBase_not_isSofic
#print axioms GroupApproximation.LeavittStrictCentralCoverWitness.witness_strict
#print axioms GroupApproximation.BinaryLeavittSteinberg.everyCentralExtensionSplits
#print axioms GroupApproximation.BinaryLeavittSteinberg.rankThree_hasKazhdanPropertyT
#print axioms GroupApproximation.BinaryLeavittSteinberg.hasKazhdanPropertyT
#print axioms GroupApproximation.FreeElementaryPropertyT.freeElementary_hasKazhdanPropertyT
#print axioms GroupApproximation.FiniteTypeLeavittTT.elementaryGroup_hasTTmodT
#print axioms GroupApproximation.PropertyTTPaper.freeCharacteristicTwo_root_hasRelativeTT
#print axioms GroupApproximation.PropertyTTPaper.freeCharacteristicTwo_localizedPlaneEstimate
#print axioms GroupApproximation.PropertyTTPaper.freeCharacteristicTwo_planeEnergyEstimate
#print axioms GroupApproximation.PropertyTTPaper.freeCharacteristicTwo_rowEmbedding_controlRoot
#print axioms GroupApproximation.PropertyTTPaper.freeCharacteristicTwo_inverseTranspose_root
#print axioms GroupApproximation.PropertyTTPaper.freeCharacteristicTwo_rowEmbedding_elementaryRoot
#print axioms GroupApproximation.PropertyTTPaper.coordinateBlock_factorization
#print axioms GroupApproximation.PropertyTTPaper.threeMove_diagonalPivot
#print axioms GroupApproximation.PropertyTTPaper.elementaryGroup_eq_generalLinear
#print axioms GroupApproximation.PropertyTTPaper.leavitt_elementaryRankEquivalence
#print axioms GroupApproximation.PropertyTTPaper.elementaryBlockFlattening
#print axioms GroupApproximation.PropertyTTPaper.kazhdan_normalizedSet_globalization
#print axioms GroupApproximation.PropertyTTPaper.finiteFreeQuotient_rankFour_hasTTmodT
#print axioms GroupApproximation.PropertyTTPaper.quasiCocycle_list_product_bound
#print axioms GroupApproximation.PropertyTTPaper.finiteFreeQuotient_elementaryGroup_hasTTmodT
#print axioms GroupApproximation.PropertyTTPaper.finiteType_elementaryGroup_hasTTmodT
#print axioms GroupApproximation.PropertyTTPaper.binaryLeavitt_elementaryGroup_hasTTmodT
#print axioms GroupApproximation.PropertyTTPaper.binaryLeavitt_elementaryEquivUnits
#print axioms GroupApproximation.PropertyTTPaper.binaryLeavittUnits_hasTTmodT
#print axioms GroupApproximation.PropertyTTPaper.binaryLeavitt_elementaryGroup_hasTTmodT_and_not_isSofic
#print axioms GroupApproximation.UniversalRankFour.witness_not_isLEF
#print axioms GroupApproximation.ThompsonFObstruction.finite_image_generatorCommutator_eq_one
#print axioms GroupApproximation.isSofic_of_finite
#print axioms GroupApproximation.isSofic_semidirectProduct_of_finite
#print axioms GroupApproximation.freeLampMulEquivSymmetricDoubleFlip
#print axioms GroupApproximation.doubleToLine_injective
#print axioms GroupApproximation.isSofic_freeLamp_flip_of_isSofic_lineDouble
#print axioms GroupApproximation.not_isSofic_lineDouble_of_not_isSofic_freeLamp_flip
#print axioms GroupApproximation.isSofic_multiplicative_int
#print axioms GroupApproximation.isSofic_iff_productRestricted
#print axioms GroupApproximation.isSofic_of_soficApproximation
#print axioms GroupApproximation.isSofic_iff_nonempty_soficApproximation
#print axioms GroupApproximation.isLEF_of_finite
#print axioms GroupApproximation.isLEF_multiplicative_int
#print axioms GroupApproximation.isLEF_iff_textbook
#print axioms GroupApproximation.isKazhdanPair_iff_complex
#print axioms GroupApproximation.hasKazhdanPropertyT_iff_complex
#print axioms GroupApproximation.IsKazhdanPair.liftUniverse
#print axioms GroupApproximation.HasKazhdanPropertyT.liftUniverse
#print axioms GroupApproximation.IsKazhdanPair.lowerUniverse
#print axioms GroupApproximation.hasKazhdanPropertyT_universe_iff
#print axioms GroupApproximation.hasKazhdanPropertyT_iff_textbook

-- The unconditional K₁-vanishing chain (session 54): narrow reduction,
-- scalar reduction, checkpoint B4, GL = EL, and the Whitehead-form
-- headline.  All must report only the three standard axioms.
#print axioms GroupApproximation.BinaryLeavitt.narrowReduction_holds
#print axioms GroupApproximation.BinaryLeavitt.scalarReduction_holds
#print axioms GroupApproximation.BinaryLeavitt.stableUnits_eq_top_holds
#print axioms GroupApproximation.BinaryLeavitt.glTwo_eq_elementary_holds
#print axioms GroupApproximation.BinaryLeavitt.glFour_eq_elementary_holds

-- The exact manuscript endpoints: one declaration per printed headline
-- statement, so the report records what each printed theorem rests on.
#print axioms GroupApproximation.Manuscript.theoremA_exact
#print axioms GroupApproximation.Manuscript.theoremB_exact
#print axioms GroupApproximation.Manuscript.theoremC_exact
#print axioms GroupApproximation.Manuscript.theoremC_covers_theoremB_groups
#print axioms GroupApproximation.Manuscript.theoremD_subgroups
#print axioms GroupApproximation.Manuscript.cor_fgring_printed
#print axioms GroupApproximation.Manuscript.cor_fgring_exact
#print axioms GroupApproximation.Manuscript.cor_fgring_countableFree
#print axioms GroupApproximation.binaryLeavittWhiteheadK1_subsingleton
#print axioms GroupApproximation.binaryLeavittElementaryColim_eq_top
#print axioms GroupApproximation.binaryLeavittClassicalK1_subsingleton
#print axioms GroupApproximation.BinaryLeavitt.exists_elementaryCertificate
#print axioms GroupApproximation.BinaryLeavitt.exists_moveList
#print axioms GroupApproximation.BinaryLeavitt.Move.eval_mem_stableUnits
#print axioms GroupApproximation.BinaryLeavitt.K1_trivial
#print axioms GroupApproximation.KOnePaper.diagUnit_mem_elementary
#print axioms GroupApproximation.KOnePaper.elementaryGroup_two_eq_top

-- The unit-group and general-linear profiles (Theorem B(i) closed): finite
-- generation, infinitude, property (T), and nonsoficity of `L_k(1,2)ˣ` and
-- of every positive-rank `GL_r` over every finite field.
#print axioms GroupApproximation.binaryLeavittUnits_profile
#print axioms GroupApproximation.binaryLeavittGL_profile

-- Theorem C's Kazhdan half, proved internally and included explicitly in the
-- public axiom report.
#print axioms GroupApproximation.Shalom.exists_presented_kazhdan_cover
#print axioms GroupApproximation.Shalom.exists_finitelyPresented_kazhdan_cover
#print axioms GroupApproximation.exists_kazhdan_finitelyPresented_cover_of_not_isSofic

-- All-ranks collapse, perfectness, and the rank-two compression over
-- `L_k(1,2)`: `GL_n = EL_n` for every `n ≥ 2` over every field, the unit
-- group is perfect, and the two-by-two Leavitt-corner theorem closes over
-- every finite field.
#print axioms GroupApproximation.BinaryLeavitt.elementaryGroup_eq_top
#print axioms GroupApproximation.BinaryLeavitt.glAll_eq_elementary
#print axioms GroupApproximation.BinaryLeavitt.binaryLeavittUnits_perfect
#print axioms GroupApproximation.binaryLeavittRankTwo_not_isSofic

-- The coefficient ring in the explicit Steinberg endpoint has an absolute
-- associative-ring presentation: four generators, the five Leavitt
-- equations, and the characteristic-two equation.  The equivalence is
-- constructed in both directions rather than assumed.
#print axioms GroupApproximation.BinaryLeavittAbsolute.ringEquiv

-- `lem:fplef`, closed: finitely presented LEF groups are residually finite.
#print axioms GroupApproximation.finitelyPresented_isLEF_residuallyFinite

-- `cor:fgring` at the generality the corollary is stated in: any nontrivial
-- countable finite-type algebra over a finite field carrying a binary Leavitt
-- family.  The manuscript's margin note names these, so an ordinary build
-- reports their axioms rather than leaving them to the whole-namespace scan.
#print axioms GroupApproximation.FamilyRankFour.ambient_not_isSofic
#print axioms GroupApproximation.FamilyRankFour.elementary_not_isSofic
#print axioms GroupApproximation.FamilyRankFour.units_not_isSofic
#print axioms GroupApproximation.FamilyRankFour.gl_not_isSofic

-- `thm:corner` at every adjacent pair `(m, m + 1)` with `m ≥ 2`, at the
-- printed hypotheses, and its characteristic-two discharge of the
-- membership hypothesis (ii).
#print axioms GroupApproximation.GeneralCornerTheorem.corner_not_isSofic
#print axioms GroupApproximation.GeneralCornerTheorem.corner_not_isSofic_of_charTwo

-- `lem:normalization`: the inverse-compatible normalization of a sofic
-- approximation is constructed, not just estimated.
#print axioms GroupApproximation.SoficApproximation.exists_normalization

-- `prop:vembed`: Thompson's `V` embeds into the unit group of any
-- nontrivial ring carrying a binary Leavitt family, with `eq:Ug` on tables.
#print axioms GroupApproximation.LeavittFamily.vEmbeddingOfFamily_injective
#print axioms GroupApproximation.LeavittFamily.vEmbeddingOfFamily_tableEquiv

-- `rem:quotients`: free groups are residually finite, and none of the
-- classes of sofic, LEF, or residually finite groups is closed under
-- quotients.
#print axioms GroupApproximation.freeGroup_residuallyFinite
#print axioms GroupApproximation.isSofic_freeGroup
#print axioms GroupApproximation.exists_sofic_group_with_nonsofic_quotient
#print axioms GroupApproximation.exists_isLEF_group_with_non_isLEF_quotient
#print axioms GroupApproximation.exists_residuallyFinite_group_with_non_residuallyFinite_quotient

-- Internally proved operator-norm MF transfer mechanisms.
#print axioms GroupApproximation.isWeakMF_of_injective
#print axioms GroupApproximation.isWeakMF_of_residuallyFinite
#print axioms GroupApproximation.exists_regularTraceWeakMFApproximation_of_isLEF
#print axioms GroupApproximation.exists_regularTraceWeakMFApproximation_of_residuallyFinite
#print axioms GroupApproximation.RegularTraceWeakMFApproximation.matrixGroupRing_trace_pairing_eventually
#print axioms GroupApproximation.RegularCharacterGNS.regularCharacter_isPositiveDefinite
#print axioms GroupApproximation.RegularCharacterGNS.representation_injective
#print axioms GroupApproximation.PushoutEmbedding.map_injective_of_reflects_range
#print axioms GroupApproximation.freeLampToProductDouble_injective
#print axioms GroupApproximation.isWeakMF_freeLamp_of_productDouble

-- Cluster-groupoid carrier: composition and negligible-disagreement setoid
-- are derived from concrete finite partial bijections.
#print axioms GroupApproximation.FinitePartialBijection.sourceDefect_trans_le
#print axioms GroupApproximation.FinitePartialBijection.trans_assoc
#print axioms GroupApproximation.AsymptoticPartialBijection.near_trans
#print axioms GroupApproximation.AsymptoticPartialBijection.trans_assoc
#print axioms GroupApproximation.asymptoticPartialGroupoidPresentation
#print axioms GroupApproximation.ExpanderDecomposition.refinementAsymptoticPartialBijection
#print axioms GroupApproximation.FiniteGroupoid.fullOfFaithfulOfCardinalPreserving
#print axioms GroupApproximation.GroupoidPresentation.homFintype
#print axioms GroupApproximation.FiniteGroupoid.pullbackBisectionOfCardinalPreserving
#print axioms GroupApproximation.FinitePartialClusterData.presentation
#print axioms GroupApproximation.FinitePartialBijection.agreement_or_disagreement_small
#print axioms GroupApproximation.FinitePartialBijection.twoSidedDisagreement_lt_two_mul_or_eight_radius_le
#print axioms GroupApproximation.hasTaggedExpansionAtScale_of_hasDirectedExpansionAtScale
#print axioms GroupApproximation.hasTaggedExpansionAtScale_of_editDistance
#print axioms GroupApproximation.ExpanderDecomposition.componentCompletedAction_taggedExpansion
#print axioms GroupApproximation.ExpanderDecomposition.componentCompletedAction_disagreement_sum_negligible
#print axioms GroupApproximation.ExpanderDecomposition.componentMultiplicationError_sum_negligible
#print axioms GroupApproximation.ExpanderDecomposition.componentIdentityError_sum_negligible
#print axioms GroupApproximation.ExpanderDecomposition.completedComponentEquiv
#print axioms GroupApproximation.ExpanderDecomposition.completedComponentPerm_multiplicationError_negligible
#print axioms GroupApproximation.ExpanderDecomposition.completedComponentPerm_identityError_negligible
#print axioms GroupApproximation.ExpanderDecomposition.completedAmbientPerm_disagreement_negligible
#print axioms GroupApproximation.ExpanderDecomposition.completedSoficApproximation
#print axioms GroupApproximation.ExpanderDecomposition.completedComponentSoficApproximation
#print axioms GroupApproximation.ExpanderDecomposition.componentLabelEditBudget_sum_negligible
#print axioms GroupApproximation.ExpanderDecomposition.badClusterComponentMass_negligible
#print axioms GroupApproximation.FinitePartialBijection.IsClusterCandidate.gap
#print axioms GroupApproximation.FinitePartialBijection.card_mul_sourceDefect_le_card_equivarianceDefect
#print axioms GroupApproximation.FinitePartialBijection.card_mul_targetDefect_le_card_symm_equivarianceDefect
#print axioms GroupApproximation.FinitePartialBijection.IsClusterCandidate.sourceDefect_lt_scale
#print axioms GroupApproximation.FinitePartialBijection.IsClusterCandidate.targetDefect_lt_scale
#print axioms GroupApproximation.FinitePartialBijection.card_equivarianceDefect_trans_le
#print axioms GroupApproximation.FinitePartialBijection.graph_ofBiuniqueRelation
#print axioms GroupApproximation.FinitePartialBijection.source_eq_univ_of_graph_mapsTo_of_transitive
#print axioms GroupApproximation.FinitePartialBijection.target_eq_univ_of_graph_mapsTo_of_transitive
#print axioms GroupApproximation.FinitePartialBijection.apply_action_eq_of_graph_mapsTo
#print axioms GroupApproximation.PartialClusterSystem.presentation
#print axioms GroupApproximation.FinitePartialBijection.card_swapEquivarianceDefect_le
#print axioms GroupApproximation.FinitePartialBijection.card_extractCrossing_equivarianceDefect_le
#print axioms GroupApproximation.FinitePartialBijection.card_extractCrossing_symm_equivarianceDefect_le
#print axioms GroupApproximation.FinitePartialBijection.isClusterCandidate_extractCrossing_of_bounds
#print axioms GroupApproximation.FinitePartialBijection.card_sumCommutationDefect_le_card_mul_badArcs
#print axioms GroupApproximation.FinitePartialBijection.extractCrossing_swapPerm
#print axioms GroupApproximation.FinitePartialBijection.sourceDefect_extractCrossing_le
#print axioms GroupApproximation.FinitePartialBijection.targetDefect_extractCrossing_le
#print axioms GroupApproximation.FinitePartialBijection.twoSidedDisagreement_extractCrossing_le_self_add_two_mul
#print axioms GroupApproximation.ExpanderDecomposition.repairedComponentBisection
#print axioms GroupApproximation.ExpanderDecomposition.normalizedCentralizer_componentBisection

-- Exact finite Kazhdan rounding: invariant projection followed by thresholding
-- produces an exactly invariant subset, quantitatively controlled by its
-- labelled boundary.
#print axioms GroupApproximation.KazhdanInvariantRounding.roundedInvariantSet_map
#print axioms GroupApproximation.KazhdanInvariantRounding.card_symmDiff_roundedInvariantSet_le
#print axioms GroupApproximation.KazhdanInvariantRounding.kazhdan_mul_card_symmDiff_rounded_le_boundary
#print axioms GroupApproximation.DiagonalInvariantRelation.roundedDiagonalRelation_map
#print axioms GroupApproximation.DiagonalInvariantRelation.mem_roundedDiagonalRelation_map_iff
#print axioms GroupApproximation.DiagonalInvariantRelation.rowDegree_roundedDiagonalRelation_eq
#print axioms GroupApproximation.DiagonalInvariantRelation.columnDegree_roundedDiagonalRelation_eq
#print axioms GroupApproximation.DiagonalInvariantRelation.relationCore_roundedDiagonalRelation_mapsTo
#print axioms GroupApproximation.DiagonalInvariantRelation.kazhdan_mul_card_graph_symmDiff_rounded_le_defect
#print axioms GroupApproximation.DiagonalInvariantRelation.relationBoundary_roundedDiagonalRelation_eq_empty
#print axioms GroupApproximation.DiagonalInvariantRelation.card_badArcs_roundedDiagonalPermutation_le
#print axioms GroupApproximation.DiagonalInvariantRelation.card_hammingDisagreement_roundedDiagonalPermutation_le
#print axioms GroupApproximation.DiagonalInvariantRelation.kazhdan_mul_card_badArcs_roundedDiagonalPermutation_le
#print axioms GroupApproximation.DiagonalInvariantRelation.kazhdan_mul_card_hammingDisagreement_roundedDiagonalPermutation_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.kazhdan_mul_twoSidedDisagreement_repair_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.sourceDefect_repair_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.targetDefect_repair_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.missingMass_repair_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.kazhdan_mul_missingMass_repair_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.kazhdan_mul_card_badArcs_repairedSwap_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.totalCommutationDefect_swap_le_partialTotalDefect
#print axioms GroupApproximation.ExactPartialKazhdanRepair.kazhdan_mul_twoSidedDisagreement_repair_le_partialDefect
#print axioms GroupApproximation.ExactPartialKazhdanRepair.card_taggedSumCommutationDefect_le_card_mul_badArcs
#print axioms GroupApproximation.ExactPartialKazhdanRepair.kazhdan_mul_card_taggedSumCommutationDefect_repaired_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.kazhdan_mul_card_taggedSumCommutationDefect_repaired_inv_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.kazhdan_mul_sourceDefect_repair_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.kazhdan_mul_targetDefect_repair_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.repair_isClusterCandidate_and_close_of_bounds
#print axioms GroupApproximation.ExactPartialKazhdanRepair.graph_coreCrossing
#print axioms GroupApproximation.ExactPartialKazhdanRepair.exactCoreRepair_graph_mapsTo
#print axioms GroupApproximation.ExactPartialKazhdanRepair.exactCoreRepair_source_target_eq_univ_of_transitive
#print axioms GroupApproximation.KazhdanImprovement.card_missingSources_relationCore_le_three_edits
#print axioms GroupApproximation.KazhdanImprovement.card_sdiff_add_card_sdiff_eq_symmDiff
#print axioms GroupApproximation.ExactPartialKazhdanRepair.exactCoreRepair_source_nonempty_of_three_mul_edits_lt
#print axioms GroupApproximation.ExactPartialKazhdanRepair.exactCoreRepair_source_target_eq_univ_of_kazhdan
#print axioms GroupApproximation.FinitePartialBijection.symm_graph_mapsTo_of_graph_mapsTo
#print axioms GroupApproximation.FinitePartialBijection.equivarianceDefect_eq_empty_of_graph_mapsTo_of_source_eq_univ
#print axioms GroupApproximation.ExactPartialKazhdanRepair.exactCoreRepair_equivarianceDefect_eq_empty
#print axioms GroupApproximation.ExactPartialKazhdanRepair.exactCoreRepair_symm_equivarianceDefect_eq_empty
#print axioms GroupApproximation.ExactPartialKazhdanRepair.exactCoreRepair_isClusterCandidate_of_source_target_eq_univ
#print axioms GroupApproximation.ExactPartialKazhdanRepair.card_disagreement_exactCoreRepair_le_core_edits
#print axioms GroupApproximation.ExactPartialKazhdanRepair.card_symm_disagreement_exactCoreRepair_le_core_edits
#print axioms GroupApproximation.ExactPartialKazhdanRepair.twoSidedDisagreement_exactCoreRepair_le_six_mul_edits
#print axioms GroupApproximation.ExactPartialKazhdanRepair.kazhdan_mul_twoSidedDisagreement_exactCoreRepair_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.twoSidedDisagreement_exactCoreRepair_lt_two_mul_of_kazhdan
#print axioms GroupApproximation.ExactPartialKazhdanRepair.exactCoreRepair_candidate_and_close_of_kazhdan
#print axioms GroupApproximation.ExactPartialKazhdanRepair.card_taggedEquivarianceDefect_eq_sum_singleton
#print axioms GroupApproximation.ExactPartialKazhdanRepair.partialTotalDefect_eq_tagged
#print axioms GroupApproximation.ExactPartialKazhdanRepair.partialTotalDefect_trans_le
#print axioms GroupApproximation.ExactPartialKazhdanRepair.partialTotalDefect_trans_lt_two_mul
#print axioms GroupApproximation.ExactPartialKazhdanRepair.exactCoreRepair_trans_candidate_and_close
#print axioms GroupApproximation.PartialClusterSystem.ofExactTransitiveKazhdanActions
#print axioms GroupApproximation.PartialClusterSystem.exactKazhdanPresentation
#print axioms GroupApproximation.FinitePartialBijection.twoSidedDisagreement_sandwich_le
#print axioms GroupApproximation.FinitePartialBijection.twoSidedDisagreement_sandwich_trans_le
#print axioms GroupApproximation.FinitePartialBijection.twoSidedDisagreement_sandwich_roundtrip_le
#print axioms GroupApproximation.MultiplicativeApproximation.map_one_close
#print axioms GroupApproximation.MultiplicativeApproximation.inv_mul_close_eventually
#print axioms GroupApproximation.KunThomCorrelation.finiteAveragingDisplacementNormSq_eventually_lt
#print axioms GroupApproximation.KunThomRounding.exists_pairProduct_relation_eventually
#print axioms GroupApproximation.ChosenNonMFTheorem.mark_normMFInvisible
#print axioms GroupApproximation.ChosenNonMFTheorem.chosenFinitelyPresented_not_isWeakMF
#print axioms GroupApproximation.ChosenNonMFTheorem.exists_countable_not_isWeakMF
#print axioms GroupApproximation.ChosenNonMFTheorem.exists_finitelyPresented_not_isWeakMF
#print axioms GroupApproximation.ChosenNonMFTheorem.chosenFinitelyPresented_not_isOperatorMF
#print axioms GroupApproximation.ChosenNonMFTheorem.exists_finitelyPresented_not_isOperatorMF
#print axioms GroupApproximation.ChosenNonMFTheorem.not_every_group_isOperatorMF
#print axioms GroupApproximation.ChosenNonMFTheorem.not_every_finitelyPresented_group_isOperatorMF
#print axioms GroupApproximation.ChosenUniversalHorn.isOperatorMF_satisfies_chosenQuasiIdentity
#print axioms GroupApproximation.ChosenUniversalHorn.markedGroup_not_satisfies_chosenQuasiIdentity
#print axioms GroupApproximation.normMatrixCoronaMk_eq_zero_iff
#print axioms GroupApproximation.c0MatrixSequenceIdeal_star_mem
#print axioms GroupApproximation.KazhdanCompressionCore.finiteNormal_le_normMFResidual
#print axioms GroupApproximation.KazhdanCompressionCore.not_isOperatorMF_of_finiteNormal_le_defect
#print axioms GroupApproximation.isOperatorMF_iff_normMFResidual_eq_bot
#print axioms GroupApproximation.normMFQuotient_isOperatorMF
#print axioms GroupApproximation.exists_normMatrixCoronaRepresentation_ker_eq_normMFResidual
#print axioms GroupApproximation.existsUnique_normMFQuotient_factorization_to_isOperatorMF
#print axioms GroupApproximation.coronaMFResidual_eq_normMFResidual
#print axioms GroupApproximation.map_coronaMFResidual_le
#print axioms GroupApproximation.isOperatorMF_iff_coronaMFResidual_eq_bot
#print axioms GroupApproximation.coronaMFQuotient_isOperatorMF
#print axioms GroupApproximation.exists_normMatrixCoronaRepresentation_ker_eq_coronaMFResidual
#print axioms GroupApproximation.existsUnique_coronaMFQuotient_factorization_to_isOperatorMF
#print axioms GroupApproximation.KazhdanCompressionCore.finiteNormal_le_normMatrixCoronaKernel
#print axioms GroupApproximation.isOperatorMF_of_residuallyFinite
#print axioms GroupApproximation.IsOperatorMF.subgroup
#print axioms GroupApproximation.isOperatorMFIncreasing_iff
#print axioms GroupApproximation.MarkedGroupSpace.cylinder_wordBall_subset_cylinder
#print axioms GroupApproximation.MarkedGroupSpace.exists_wordBall_cylinder_subset_compl_operatorMFLocus
#print axioms GroupApproximation.MarkedGroupSpace.isClosed_operatorMFLocus
#print axioms GroupApproximation.MarkedGroupSpace.isOperatorMF_of_tendsto
#print axioms GroupApproximation.OperatorMFQuotientNonclosure.operatorMF_not_closed_under_this_quotient
#print axioms GroupApproximation.LiteralOperatorMFQuotientControls.source_isOperatorMF
#print axioms GroupApproximation.LiteralOperatorMFQuotientControls.quotientMap_surjective
#print axioms GroupApproximation.not_isOperatorMF_coprod_left
#print axioms GroupApproximation.normMFResidual_eq_top_of_mem_normalClosure_eq_top
#print axioms GroupApproximation.FixedSpaceStabilizer.compressionGroup_map_mem
#print axioms GroupApproximation.FixedSpaceDefect.compressionCentralizerDefect_le_ker
#print axioms GroupApproximation.not_injective_of_coronaMFInvisible
#print axioms GroupApproximation.KazhdanCompressionCore.finiteNormal_uniform_invisibility
#print axioms GroupApproximation.FaithfulTracialState.matrix_mul_star_eq_one_of_star_mul_eq_one
#print axioms GroupApproximation.ProperProjectionCompression.star_isometry_mul_eq_one_and_reverse_ne
#print axioms GroupApproximation.ProperProjectionCompression.not_isStablyFiniteRing
#print axioms GroupApproximation.ReducedGroupCStarTrace.canonicalFaithfulTracialState
#print axioms GroupApproximation.no_faithfulReducedCoronaUnitaryRestriction_of_residual_eq_top
#print axioms GroupApproximation.ReducedGroupCStarTrace.reduced_matrix_mul_star_eq_one_of_star_mul_eq_one
#print axioms GroupApproximation.InjectiveCStarEmbedding.properIsometry_spec
#print axioms GroupApproximation.InjectiveCStarEmbedding.target_not_isStablyFiniteRing
#print axioms GroupApproximation.CliffordAlgebraLamp.cliffordLamp_group_package
#print axioms GroupApproximation.CliffordAlgebraLamp.cliffordLamp_permutation_package
#print axioms GroupApproximation.compressionCentralizerDefect_le_ker
#print axioms GroupApproximation.FixedSpaceStabilizer.compressionGroup_le_stabilizer
#print axioms GroupApproximation.FixedSpaceStabilizer.compressionGroup_map_mem
#print axioms GroupApproximation.commutator_conjugate_eq_commutator_sq_of_sq_eq_one
#print axioms GroupApproximation.ExplicitLinearModel.doubling_linear_model_package
#print axioms GroupApproximation.LiteralCyclicCalibration.mark_ne_one
#print axioms GroupApproximation.LiteralCyclicCalibration.mark_central
#print axioms GroupApproximation.LiteralCyclicCalibration.quotientMap_mark_val
#print axioms GroupApproximation.LiteralCyclicCalibration.quotientMap_mark_central
#print axioms GroupApproximation.LiteralCyclicCalibration.finiteDimensional_kill
#print axioms GroupApproximation.LiteralCyclicCalibration.realizedQuotient_finiteDimensional_kill
#print axioms GroupApproximation.map_marked_commutator_eq_one
#print axioms GroupApproximation.map_marked_commutator_eq_one_units
#print axioms GroupApproximation.KazhdanCompressionCore.defectNormal_le_orbitDefectNormal
#print axioms GroupApproximation.KazhdanCompressionCore.orbitDefectNormal_le_compressionCentralizerDefect
#print axioms GroupApproximation.LiteralNonMFPresentation.literal_algebraic_package
#print axioms GroupApproximation.LiteralNonMFLinearWitness.literal_mark_ne_one
#print axioms GroupApproximation.LiteralNonMFLinearWitness.matrixBaseHom_surjective
#print axioms GroupApproximation.LiteralBaseRelations.baseRelator_eq_one
#print axioms GroupApproximation.LiteralBaseRelations.x_conj_v1
#print axioms GroupApproximation.LiteralBaseRelations.z_conj_v3
#print axioms GroupApproximation.LiteralBaseTranslationNormal.normalizer_translations_eq_top
#print axioms GroupApproximation.LiteralBaseRotationRetract.rotationToBase_injective
#print axioms GroupApproximation.LiteralBaseRotationRetract.baseToRotation_ker_eq_translations
#print axioms GroupApproximation.LiteralBaseRotationRetract.translations_inf_rotations
#print axioms GroupApproximation.LiteralBaseRotationRetract.translations_isComplement_rotations
#print axioms GroupApproximation.LiteralBaseRotationRetract.internalSemidirectEquiv
#print axioms GroupApproximation.LiteralFiniteDimensionalObstruction.literal_finiteDimensional_rep_not_injective
#print axioms GroupApproximation.LiteralUniversalHorn.literalMarkedGroup_not_satisfies_literalQuasiIdentity
#print axioms GroupApproximation.LiteralPresentationRadius.markedWord_length_le
#print axioms GroupApproximation.LiteralPresentationRadius.relator_wordLength_le_34
#print axioms GroupApproximation.LiteralPresentationRadius.relators_or_markedWord_length_le_34
#print axioms GroupApproximation.OperatorMFMarkovWitness.positive_punit
#print axioms GroupApproximation.OperatorMFMarkovWitness.chosen_forbidden_subgroup
#print axioms GroupApproximation.OperatorMFMarkovWitness.exists_finitelyPresented_forbidden_subgroup
#print axioms GroupApproximation.existsUnique_quotient_factorization_to_normMatrixCorona
#print axioms GroupApproximation.coronaMFResidual_eq_of_le_and_quotient_isOperatorMF
#print axioms GroupApproximation.KazhdanCompressionCore.not_isWeakMF_of_normalKazhdan_le_defect
#print axioms GroupApproximation.KazhdanCompressionCore.normalKazhdan_le_normMFResidual
#print axioms GroupApproximation.KazhdanCompressionCore.normalKazhdanDefectPart_le_normMFResidual
#print axioms GroupApproximation.KazhdanCompressionCore.normMFResidual_eq_defectNormal
#print axioms GroupApproximation.AffineSL3Scaling.scaling_package
#print axioms GroupApproximation.ambient_hasKazhdanPropertyTComplex
#print axioms GroupApproximation.universalLeavitt_profile_textbook
#print axioms GroupApproximation.AffineSL3Doubling.doubling_package
#print axioms GroupApproximation.MarkedGroupSpace.tendsto_iff_eventually_relation
#print axioms GroupApproximation.exists_opTensorPow_norm_sub_one_gt_one_of_diagonal_gap
