import GroupApproximation.Sofic.ChosenNonMFTheorem
import GroupApproximation.Sofic.FiniteNormalCoronaObstruction
import GroupApproximation.Sofic.LiteralFiniteDimensionalObstruction
import GroupApproximation.Sofic.LiteralNonMFLinearWitness
import GroupApproximation.Sofic.LiteralNonMFPresentation
import GroupApproximation.Sofic.LiteralUniversalHorn
import GroupApproximation.Sofic.OperatorMFQuotientNonclosure
import GroupApproximation.Monsters.LiteralCyclicCalibration

/-!
# Lightweight axiom audit for the chosen non-MF endpoint

This deliberately imports the public chosen-witness theorem module together with
the finite-normal criterion whose endpoints are printed below.  It gives
reviewers and CI a fast audit target without replaying the much larger
project-wide endpoint audit.  The reported closure contains only Lean's
standard `propext`, `Classical.choice`, and `Quot.sound`; no mathematical or
literature theorem is accepted as an axiom or premise of the closed non-MF
endpoint.

The literal eight-generator group is also printed below, but only at the
boundary actually proved: its algebraic package, nontrivial mark, and
finite-dimensional obstruction are unconditional.  No conditional analytic
endpoint for that literal presentation is admitted to this audit surface.
-/

#print axioms GroupApproximation.ChosenNonMFTheorem.mark_normMFInvisible
#print axioms GroupApproximation.ChosenNonMFTheorem.chosenFinitelyPresented_not_isWeakMF
#print axioms GroupApproximation.ChosenNonMFTheorem.chosenFinitelyPresented_not_isOperatorMF
#print axioms GroupApproximation.ChosenNonMFTheorem.countableWitness_not_isOperatorMF
#print axioms GroupApproximation.ChosenNonMFTheorem.exists_finitelyPresented_not_isOperatorMF
#print axioms GroupApproximation.ChosenNonMFTheorem.not_every_group_isOperatorMF
#print axioms GroupApproximation.ChosenNonMFTheorem.not_every_finitelyPresented_group_isOperatorMF
#print axioms GroupApproximation.KazhdanCompressionCore.finiteNormal_le_normMFResidual
#print axioms GroupApproximation.KazhdanCompressionCore.not_isOperatorMF_of_finiteNormal_le_defect
#print axioms GroupApproximation.isOperatorMF_iff_normMFResidual_eq_bot
#print axioms GroupApproximation.KazhdanCompressionCore.finiteNormal_le_normMatrixCoronaKernel
#print axioms GroupApproximation.coronaMFResidual_eq_normMFResidual
#print axioms GroupApproximation.map_coronaMFResidual_le
#print axioms GroupApproximation.isOperatorMF_iff_coronaMFResidual_eq_bot
#print axioms GroupApproximation.LiteralNonMFPresentation.literal_algebraic_package
#print axioms GroupApproximation.LiteralNonMFLinearWitness.literal_mark_ne_one
#print axioms GroupApproximation.LiteralFiniteDimensionalObstruction.literal_finiteDimensional_rep_not_injective
#print axioms GroupApproximation.LiteralOperatorMFQuotientControls.source_isOperatorMF
#print axioms GroupApproximation.LiteralOperatorMFQuotientControls.quotientMap_surjective
#print axioms GroupApproximation.LiteralCyclicCalibration.mark_ne_one
#print axioms GroupApproximation.LiteralCyclicCalibration.finiteDimensional_kill
#print axioms GroupApproximation.LiteralCyclicCalibration.exists_coronaRepresentation_mark_ne_one
#print axioms GroupApproximation.LiteralUniversalHorn.literalMarkedGroup_not_satisfies_literalQuasiIdentity
