import GroupApproximation.Meta.AxiomGuard
import GroupApproximation.Computability.MFRadicalComputer
import GroupApproximation.Computability.SeededSelfAwareMFCompiler
import GroupApproximation.Sofic.ChosenNonMFTheorem
import GroupApproximation.Sofic.MarkedMFClosed
import GroupApproximation.Sofic.FiniteNormalCoronaObstruction
import GroupApproximation.Sofic.LiteralFiniteDimensionalObstruction
import GroupApproximation.Sofic.LiteralNonMFLinearWitness
import GroupApproximation.Sofic.LiteralNonMFPresentation
import GroupApproximation.Sofic.LiteralTheoremAPackage
import GroupApproximation.Sofic.NoRenormalizationCapacity
import GroupApproximation.Sofic.OpToHSShadowResidual
import GroupApproximation.Sofic.SimpleSoficEnvelopeUnconditional

/-!
# Lightweight axiom audit for the chosen non-MF endpoint

This deliberately imports the public chosen-witness theorem module together with
the finite-normal criterion whose endpoints are printed below.  It gives
reviewers and CI a fast audit target without replaying the much larger
project-wide endpoint audit.  The reported closure contains only Lean's
standard `propext`, `Classical.choice`, and `Quot.sound`; no mathematical or
literature theorem is accepted as an axiom or premise of the closed non-MF
endpoint.

The literal eight-generator group is also printed below, but only at the
boundary actually proved: its algebraic package, nontrivial mark, and
finite-dimensional obstruction are unconditional.  No conditional analytic
endpoint for that literal presentation is admitted to this audit surface.

The final block audits the separately labelled compiler interfaces.  The
closure report establishes that their proofs contain no hidden postulates; it
does not erase their displayed hypotheses.  In particular, the shadow
saturation theorem still requires a routing homomorphism and the
no-renormalization diagonal still requires a uniformly authenticated
challenge family.
-/

#audit_axioms GroupApproximation.ChosenNonMFTheorem.mark_normMFInvisible
#audit_axioms GroupApproximation.ChosenNonMFTheorem.chosenFinitelyPresented_not_isWeakMF
#audit_closed_axioms GroupApproximation.ChosenNonMFTheorem.chosenFinitelyPresented_not_isOperatorMF
#audit_axioms GroupApproximation.ChosenNonMFTheorem.countableWitness_not_isOperatorMF
#audit_closed_axioms GroupApproximation.ChosenNonMFTheorem.exists_finitelyPresented_not_isOperatorMF
#audit_axioms GroupApproximation.ChosenNonMFTheorem.not_every_group_isOperatorMF
#audit_axioms GroupApproximation.ChosenNonMFTheorem.not_every_finitelyPresented_group_isOperatorMF
#audit_axioms GroupApproximation.ChosenMarkedPresentation.chosenFinitelyPresented_markedPackage
#audit_axioms GroupApproximation.ChosenNonMFEndpoint.chosenFinitelyPresented_inclusionPackage
#audit_axioms GroupApproximation.KazhdanCompressionCore.finiteNormal_le_normMFResidual
#audit_axioms GroupApproximation.KazhdanCompressionCore.not_isOperatorMF_of_finiteNormal_le_defect
#audit_axioms GroupApproximation.isOperatorMF_iff_normMFResidual_eq_bot
#audit_axioms GroupApproximation.KazhdanCompressionCore.finiteNormal_le_normMatrixCoronaKernel
#audit_axioms GroupApproximation.coronaMFResidual_eq_normMFResidual
#audit_axioms GroupApproximation.map_coronaMFResidual_le
#audit_axioms GroupApproximation.isOperatorMF_iff_coronaMFResidual_eq_bot
#audit_axioms GroupApproximation.LiteralNonMFPresentation.literal_algebraic_package
#audit_axioms GroupApproximation.LiteralNonMFLinearWitness.literal_mark_ne_one
#audit_axioms GroupApproximation.LiteralFiniteDimensionalObstruction.literal_finiteDimensional_rep_not_injective
#audit_axioms GroupApproximation.OperatorNormAmplification.exists_tensorPower_pair_far
#audit_axioms GroupApproximation.OperatorMFLocalNormalization.isOperatorMF_iff_isNormApproximable_one
#audit_axioms GroupApproximation.MarkedGroupSpace.exists_wordBall_cylinder_subset_compl_operatorMFLocus
#audit_axioms GroupApproximation.MarkedGroupSpace.isClosed_operatorMFLocus
#audit_axioms GroupApproximation.MarkedGroupSpace.isOpen_compl_operatorMFLocus
#audit_axioms GroupApproximation.MarkedGroupSpace.isOperatorMF_of_tendsto
#audit_axioms GroupApproximation.SeededSelfAwareMFCompiler.reverseKleene_fixedPoint_logic
#audit_axioms GroupApproximation.SeededSelfAwareMFCompiler.logicalSelfAwareMFCompiler_iff_seed
#audit_closed_axioms GroupApproximation.SeededSelfAwareMFCompiler.literal_hasMarkedMFSeed
#audit_closed_axioms GroupApproximation.SeededSelfAwareMFCompiler.literal_hasLogicalSelfAwareMFCompiler
#audit_closed_axioms GroupApproximation.MFRadicalComputer.closed_package
#audit_closed_axioms GroupApproximation.MFRadicalComputer.promised_word_problem_not_computable
#audit_closed_axioms GroupApproximation.LiteralTheoremAPackage.manuscriptTheoremA_package
#audit_closed_axioms GroupApproximation.LiteralNonMFEndpoint.literal_not_isOperatorMF
#audit_closed_axioms GroupApproximation.SimpleSoficEnvelopeUnconditional.manuscript_simpleSoficEnvelope
#audit_closed_axioms GroupApproximation.SimpleSoficEnvelopeUnconditional.manuscript_simpleSoficEnvelope_no_torsionFree_image
#audit_axioms GroupApproximation.SeededSelfAwareMFCompiler.primeCodedMark_blackHole
#audit_axioms GroupApproximation.SeededSelfAwareMFCompiler.quotient_not_isOperatorMF_of_invisible_mark_survives
#audit_axioms GroupApproximation.map_opToHSShadowResidual_le
#audit_axioms GroupApproximation.normalClosure_le_opToHSShadowResidual
#audit_axioms GroupApproximation.normalKazhdan_le_normMFResidual_of_le_opToHSShadowResidual
#audit_axioms GroupApproximation.normMFResidual_eq_top_of_shadow_bug_saturation
#audit_axioms GroupApproximation.shadowKleene_fixedPoint_logic
#audit_axioms GroupApproximation.logicalShadowKleeneEndpoint_iff_bug
#audit_axioms GroupApproximation.NoRenormalizationCapacity.collision_kills_phase
#audit_axioms GroupApproximation.NoRenormalizationCapacity.phase_close_of_palette_overflow
#audit_axioms GroupApproximation.NoRenormalizationCapacity.no_model_of_uniform_unbounded_capacity
#audit_axioms GroupApproximation.NoRenormalizationCapacity.exists_positive_power_opNorm_sub_one_lt
#audit_axioms GroupApproximation.NoRenormalizationCapacity.recurrent_power_far_from_unitary_conjugate
#audit_axioms GroupApproximation.NoRenormalizationCapacity.no_model_of_recurrent_uniform_power_return
#audit_axioms GroupApproximation.NoRenormalizationCapacity.no_model_of_uniform_power_return
#audit_axioms GroupApproximation.NoRenormalizationCapacity.projection_rank_rigid
#audit_axioms GroupApproximation.NoRenormalizationCapacity.rank_zero_of_power_monodromy
#audit_axioms GroupApproximation.repCommutant_eq_map_sandwich_of_compression
#audit_axioms GroupApproximation.mem_repCommutant_of_commutes_compressed
#audit_axioms GroupApproximation.map_commutator_eq_one_of_commutes_compressed
#audit_axioms GroupApproximation.map_commutator_eq_one_of_commutes_compressed_units
