import GroupApproximation.Sofic.ExplicitNonMFTheorem
import GroupApproximation.Sofic.FiniteNormalCoronaObstruction
import GroupApproximation.Sofic.LiteralFiniteDimensionalObstruction
import GroupApproximation.Sofic.LiteralKazhdanCompression
import GroupApproximation.Sofic.LiteralNonMFLinearWitness
import GroupApproximation.Sofic.LiteralNonMFPresentation
import GroupApproximation.Sofic.LiteralUniversalHorn
import GroupApproximation.Monsters.LiteralCyclicCalibration

/-!
# Lightweight axiom audit for the explicit non-MF endpoint

This deliberately imports the public explicit theorem module together with
the finite-normal criterion whose endpoints are printed below.  It gives
reviewers and CI a fast audit target without replaying the much larger
project-wide endpoint audit.  The reported closure contains only Lean's
standard `propext`, `Classical.choice`, and `Quot.sound`; no mathematical or
literature theorem is accepted as an axiom or premise of the closed non-MF
endpoint.

The literal eight-generator group is also printed below, but only at the
boundary actually proved: its algebraic package, nontrivial mark, and
finite-dimensional obstruction are unconditional; its operator-MF conclusion
retains either a property-`(T)` premise or an exact rational SOS certificate.
-/

#print axioms GroupApproximation.ExplicitNonMFTheorem.mark_normMFInvisible
#print axioms GroupApproximation.ExplicitNonMFTheorem.chosenFinitelyPresented_not_isWeakMF
#print axioms GroupApproximation.ExplicitNonMFTheorem.chosenFinitelyPresented_not_isOperatorMF
#print axioms GroupApproximation.ExplicitNonMFTheorem.countableWitness_not_isOperatorMF
#print axioms GroupApproximation.ExplicitNonMFTheorem.exists_finitelyPresented_not_isOperatorMF
#print axioms GroupApproximation.ExplicitNonMFTheorem.not_every_group_isOperatorMF
#print axioms GroupApproximation.ExplicitNonMFTheorem.not_every_finitelyPresented_group_isOperatorMF
#print axioms GroupApproximation.KazhdanCompressionCore.finiteNormal_le_normMFResidual
#print axioms GroupApproximation.KazhdanCompressionCore.not_isOperatorMF_of_finiteNormal_le_defect
#print axioms GroupApproximation.isOperatorMF_iff_normMFResidual_eq_bot
#print axioms GroupApproximation.KazhdanCompressionCore.finiteNormal_le_normMatrixCoronaKernel
#print axioms GroupApproximation.coronaMFResidual_eq_normMFResidual
#print axioms GroupApproximation.map_coronaMFResidual_le
#print axioms GroupApproximation.isOperatorMF_iff_coronaMFResidual_eq_bot
#print axioms GroupApproximation.LiteralNonMFPresentation.literal_algebraic_package
#print axioms GroupApproximation.LiteralNonMFLinearWitness.literal_mark_ne_one
#print axioms GroupApproximation.LiteralFiniteDimensionalObstruction.literal_finiteDimensional_rep_not_injective
#print axioms GroupApproximation.LiteralCyclicCalibration.mark_ne_one
#print axioms GroupApproximation.LiteralCyclicCalibration.finiteDimensional_kill
#print axioms GroupApproximation.LiteralCyclicCalibration.exists_coronaRepresentation_mark_ne_one
#print axioms GroupApproximation.LiteralKazhdanCompression.not_isOperatorMF_of_hasKazhdanPropertyT
#print axioms GroupApproximation.LiteralKazhdanCompression.not_isOperatorMF_of_base_equiv_affine
#print axioms GroupApproximation.LiteralKazhdanCompression.not_isOperatorMF_of_isRationalCertificate
#print axioms GroupApproximation.LiteralUniversalHorn.literalMarkedGroup_not_satisfies_literalQuasiIdentity
#print axioms GroupApproximation.LiteralUniversalHorn.literalQuasiIdentity_separates_of_isRationalCertificate
