import GroupApproximation.Meta.AxiomGuard
import GroupApproximation.Sofic.FinitePacketCovariance
import GroupApproximation.Sofic.FiniteGroupUlamStep
import GroupApproximation.Sofic.FiniteGroupUlamIteration
import GroupApproximation.Sofic.FiniteGroupCoronaExactification
import GroupApproximation.Sofic.FinitePacketCoronaCovariance
import GroupApproximation.Sofic.FinitePacketCoronaCollapse
import GroupApproximation.Sofic.FinitePacketRankWeight
import GroupApproximation.Sofic.StarTranspositionRankMass
import GroupApproximation.Sofic.FinitePacketDelormeCenter
import GroupApproximation.Sofic.FinitePacketDelormeDiagonalization
import GroupApproximation.Sofic.FinitePacketDisplacementCocycle
import GroupApproximation.Sofic.FinitePacketWordCovariance
import GroupApproximation.Sofic.FinitePacketCollapseCore
import GroupApproximation.Sofic.FinitePacketFullCollapse
import GroupApproximation.Sofic.FinitePacketStarAmalgam
import GroupApproximation.Sofic.LiteralFinitePacketStarCollapse
import GroupApproximation.Manuscript.NonMF.LiteralFinitePacketCollapse

/-!
# Kernel audit for the formalized finite-packet collapse layers

These are the unconditional finite-packet declarations, including the full
generic corona-collapse endpoint, its star-packet PushoutI carrier, and the
premise-free literal affine specialization.
-/

#audit_axioms GroupApproximation.FinitePacketCovariance.exists_near_identity_exact_covariance
#audit_axioms GroupApproximation.FiniteGroupUlamStep.multiplicationError_cocycle
#audit_axioms GroupApproximation.FiniteGroupUlamStep.norm_averagedError_le
#audit_axioms GroupApproximation.FiniteGroupUlamStep.norm_correctedTable_sub_le
#audit_axioms GroupApproximation.FiniteGroupUlamStep.correctedTable_multiplicativeDefectAtMost
#audit_axioms GroupApproximation.FiniteGroupUlamIteration.exactifiedRepresentation
#audit_axioms GroupApproximation.FiniteGroupUlamIteration.norm_exactifiedRepresentation_sub_le
#audit_axioms GroupApproximation.FiniteGroupCoronaExactification.exists_exact_coordinate_lift
#audit_axioms GroupApproximation.FinitePacketCoronaCovariance.exists_exact_covariant_coordinate_lifts
#audit_axioms GroupApproximation.FinitePacketCoronaCovariance.exists_exact_covariant_coordinate_lifts_of_ambient
#audit_axioms GroupApproximation.FinitePacketCoronaCollapse.exists_exact_covariant_coordinates_with_terminal_collapse
#audit_axioms GroupApproximation.FinitePacketCoronaCollapse.exists_exact_generator_packet_with_rank_bounds
#audit_axioms GroupApproximation.FinitePacketRankWeight.displacementRank_le_wordNorm_mul
#audit_axioms GroupApproximation.FinitePacketRankWeight.displacementMass_le_four_mul_wordNorm_mul_weight
#audit_axioms GroupApproximation.StarTranspositionRankMass.matMass_sub_eq_three_mul_rank
#audit_axioms GroupApproximation.FinitePacketDelormeCenter.exists_approximate_coboundary
#audit_axioms GroupApproximation.FinitePacketDelormeDiagonalization.exists_cofinal_vanishing_coboundary_primitive
#audit_axioms GroupApproximation.FinitePacketDelormeDiagonalization.scaledMassVanishing_rankScaled_unitary
#audit_axioms GroupApproximation.FinitePacketDisplacementCocycle.isBoundedSeq_normalizedDisplacement
#audit_axioms GroupApproximation.FinitePacketDisplacementCocycle.seqNorm_cocycleDefect_eq_zero
#audit_axioms GroupApproximation.FinitePacketDisplacementCocycle.exists_uniform_profile_bound
#audit_axioms GroupApproximation.FinitePacketWordCovariance.covariance_wordMover
#audit_axioms GroupApproximation.FinitePacketWordCovariance.wordMoverFamily_lifts
#audit_axioms GroupApproximation.FinitePacketWordCovariance.wordMoverFamily_opNormVanishing
#audit_axioms GroupApproximation.FinitePacketWordCovariance.wordMoverFamily_scaled_conjugation
#audit_axioms GroupApproximation.FinitePacketCollapseCore.eventually_packetRankWeight_eq_zero_of_scaled_vanishing
#audit_axioms GroupApproximation.FinitePacketCollapseCore.eventually_generator_eq_base_of_scaled_vanishing
#audit_axioms GroupApproximation.FinitePacketFullCollapse.rankScaled_normalizedDisplacement_eq
#audit_axioms GroupApproximation.FinitePacketFullCollapse.exists_cofinal_exact_packet_collapse
#audit_axioms GroupApproximation.FinitePacketStarAmalgam.packetAction_orbit
#audit_axioms GroupApproximation.FinitePacketStarAmalgam.orbit_sq
#audit_axioms GroupApproximation.FinitePacketStarAmalgam.orbit_braid
#audit_axioms GroupApproximation.FinitePacketStarAmalgam.orbit_alpha
#audit_axioms GroupApproximation.FinitePacketStarAmalgam.covariance
#audit_axioms GroupApproximation.FinitePacketStarAmalgam.compresses
#audit_axioms GroupApproximation.FinitePacketStarAmalgam.coordinateCollapse
#audit_axioms GroupApproximation.LiteralFinitePacketStarCollapse.gamma_hasKazhdanPropertyT
#audit_axioms GroupApproximation.LiteralFinitePacketStarCollapse.packetDegree_eq_index_add_one
#audit_axioms GroupApproximation.LiteralFinitePacketStarCollapse.packetDegree_eq_nine_iff_index_eq_eight
#audit_axioms GroupApproximation.LiteralAffineRangeIndexEight.doubledBase_index_eq_eight
#audit_axioms GroupApproximation.LiteralAffineRangeIndexEight.conjD_range_index_eq_eight
#audit_axioms GroupApproximation.LiteralFinitePacketStarCollapse.packetDegree_eq_nine
#audit_axioms GroupApproximation.LiteralFinitePacketStarCollapse.packetEquivS9
#audit_axioms GroupApproximation.LiteralFinitePacketStarCollapse.manuscriptLiteralAffineStarPacketCollapse
#audit_axioms GroupApproximation.ManuscriptNonMF.manuscriptLiteralFinitePacketCollapse
