import GroupApproximation.Sofic.FinitePacketCovariance
import GroupApproximation.Sofic.FiniteGroupUlamStep
import GroupApproximation.Sofic.FiniteGroupUlamIteration
import GroupApproximation.Sofic.FiniteGroupCoronaExactification
import GroupApproximation.Sofic.FinitePacketCoronaCovariance
import GroupApproximation.Sofic.FinitePacketCoronaCollapse
import GroupApproximation.Sofic.FinitePacketRankWeight
import GroupApproximation.Sofic.StarTranspositionRankMass
import GroupApproximation.Sofic.FinitePacketDelormeCenter
import GroupApproximation.Sofic.FinitePacketDelormeDiagonalization
import GroupApproximation.Sofic.FinitePacketDisplacementCocycle
import GroupApproximation.Sofic.FinitePacketWordCovariance
import GroupApproximation.Sofic.FinitePacketCollapseCore

/-!
# Kernel audit for the formalized finite-packet collapse layers

These are the new unconditional declarations.  The full corona-collapse and
concrete `S₉` carrier are intentionally absent until their remaining inputs
are formalized.
-/

#print axioms GroupApproximation.FinitePacketCovariance.exists_near_identity_exact_covariance
#print axioms GroupApproximation.FiniteGroupUlamStep.multiplicationError_cocycle
#print axioms GroupApproximation.FiniteGroupUlamStep.norm_averagedError_le
#print axioms GroupApproximation.FiniteGroupUlamStep.norm_correctedTable_sub_le
#print axioms GroupApproximation.FiniteGroupUlamStep.correctedTable_multiplicativeDefectAtMost
#print axioms GroupApproximation.FiniteGroupUlamIteration.exactifiedRepresentation
#print axioms GroupApproximation.FiniteGroupUlamIteration.norm_exactifiedRepresentation_sub_le
#print axioms GroupApproximation.FiniteGroupCoronaExactification.exists_exact_coordinate_lift
#print axioms GroupApproximation.FinitePacketCoronaCovariance.exists_exact_covariant_coordinate_lifts
#print axioms GroupApproximation.FinitePacketCoronaCovariance.exists_exact_covariant_coordinate_lifts_of_ambient
#print axioms GroupApproximation.FinitePacketCoronaCollapse.exists_exact_covariant_coordinates_with_terminal_collapse
#print axioms GroupApproximation.FinitePacketCoronaCollapse.exists_exact_generator_packet_with_rank_bounds
#print axioms GroupApproximation.FinitePacketRankWeight.displacementRank_le_wordNorm_mul
#print axioms GroupApproximation.FinitePacketRankWeight.displacementMass_le_four_mul_wordNorm_mul_weight
#print axioms GroupApproximation.StarTranspositionRankMass.matMass_sub_eq_three_mul_rank
#print axioms GroupApproximation.FinitePacketDelormeCenter.exists_approximate_coboundary
#print axioms GroupApproximation.FinitePacketDelormeDiagonalization.exists_cofinal_vanishing_coboundary_primitive
#print axioms GroupApproximation.FinitePacketDisplacementCocycle.isBoundedSeq_normalizedDisplacement
#print axioms GroupApproximation.FinitePacketDisplacementCocycle.seqNorm_cocycleDefect_eq_zero
#print axioms GroupApproximation.FinitePacketDisplacementCocycle.exists_uniform_profile_bound
#print axioms GroupApproximation.FinitePacketWordCovariance.covariance_wordMover
#print axioms GroupApproximation.FinitePacketWordCovariance.wordMoverFamily_lifts
#print axioms GroupApproximation.FinitePacketWordCovariance.wordMoverFamily_opNormVanishing
#print axioms GroupApproximation.FinitePacketWordCovariance.wordMoverFamily_scaled_conjugation
#print axioms GroupApproximation.FinitePacketCollapseCore.eventually_packetRankWeight_eq_zero_of_scaled_vanishing
#print axioms GroupApproximation.FinitePacketCollapseCore.eventually_generator_eq_base_of_scaled_vanishing
