import GroupApproximation.Meta.AxiomGuard
import GroupApproximation.Sofic.InvisibleExtensions

/-!
# Axiom audit for invisible extensions

The closed black-hole and stable-non-MF existence packages must use only
Lean's standard logical axioms.  Parameterized construction theorems are
audited with their displayed group and relation inputs intact.
-/

#audit_closed_axioms GroupApproximation.InvisibleExtensions.fixed_black_hole
#audit_axioms GroupApproximation.InvisibleExtensions.invisible_extension
#audit_axioms GroupApproximation.InvisibleExtensions.corona_observers_see_only_the_quotient
#audit_axioms GroupApproximation.InvisibleExtensions.exact_radical_of_visible_mf
#audit_axioms GroupApproximation.InvisibleExtensions.extension_isFinitelyPresented
#audit_axioms GroupApproximation.InvisibleExtensions.defect_quotient_equiv
#audit_axioms GroupApproximation.InvisibleExtensions.mf_visible_quotient_equiv
#audit_axioms GroupApproximation.InvisibleExtensions.black_hole_attachment_gadget
#audit_axioms GroupApproximation.InvisibleExtensions.black_hole_attachment_isFinitelyPresented
#audit_axioms GroupApproximation.InvisibleExtensions.one_word_relation_cell
#audit_axioms GroupApproximation.InvisibleExtensions.semantic_relation_calculus
#audit_axioms GroupApproximation.InvisibleExtensions.universal_source_relation_calculus
#audit_axioms GroupApproximation.InvisibleExtensions.universal_source_isFinitelyPresented
#audit_axioms GroupApproximation.InvisibleExtensions.universal_source_profile
#audit_axioms GroupApproximation.InvisibleExtensions.universal_defect_quotient_equiv
#audit_axioms GroupApproximation.InvisibleExtensions.universal_source_isPointNormMatriciallyStable
#audit_axioms GroupApproximation.InvisibleExtensions.extension_stable_iff
#audit_closed_axioms GroupApproximation.InvisibleExtensions.stable_nonMF_invisible_extension_exists
