import GroupApproximation.Meta.AxiomGuard
import GroupApproximation.Computability.FiniteDimensionalApproximationIncomplete

/-!
# Axiom audit for the MF computability and incompleteness paper

The two closed headline packages must depend only on Lean's standard logical
axioms.  The remaining declarations are audited with their displayed group or
presentation parameters intact.
-/

#audit_closed_axioms GroupApproximation.FiniteDimensionalApproximationIncomplete.fixed_MF_radical_computer
#audit_closed_axioms GroupApproximation.FiniteDimensionalApproximationIncomplete.fixed_MF_radical_computer_on_program_codes
#audit_closed_axioms GroupApproximation.FiniteDimensionalApproximationIncomplete.fixed_finite_dimensional_camouflage
#audit_axioms GroupApproximation.FiniteDimensionalApproximationIncomplete.fixed_camouflage_observers_blind
#audit_axioms GroupApproximation.FiniteDimensionalApproximationIncomplete.fixed_camouflage_corona_observers_blind
#audit_closed_axioms GroupApproximation.FiniteDimensionalApproximationIncomplete.closed_camouflage_package
#audit_closed_axioms GroupApproximation.MFRecognitionImpossible.mf_recognition_impossible
#audit_closed_axioms GroupApproximation.FiniteDimensionalApproximationIncomplete.closed_core
#audit_axioms GroupApproximation.FiniteDimensionalApproximationIncomplete.finite_scale_normal_form
#audit_axioms GroupApproximation.FiniteDimensionalApproximationIncomplete.mem_radical_iff_visible_quotient_eq_one
#audit_axioms GroupApproximation.FiniteDimensionalApproximationIncomplete.universal_MF_visible_quotient
#audit_axioms GroupApproximation.FiniteDimensionalApproximationIncomplete.incompleteness_in_the_fixed_MF_radical
