import GroupApproximation.Meta.AxiomGuard
import GroupApproximation.Analysis.MaximalCStarKazhdanProjection
import GroupApproximation.Manuscript.OneSidedMFRadical.LiteralMFClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.PrintedDefinitions
import GroupApproximation.Manuscript.OneSidedMFRadical.ResidualCalculus
import GroupApproximation.Manuscript.OneSidedMFRadical.FiniteDimensionalCommutant
import GroupApproximation.Manuscript.OneSidedMFRadical.StableFiniteness
import GroupApproximation.Manuscript.OneSidedMFRadical.UniversalFactorization
import GroupApproximation.Manuscript.OneSidedMFRadical.PrescribedQuotients
import GroupApproximation.Manuscript.OneSidedMFRadical.ClosurePullback
import GroupApproximation.Manuscript.OneSidedMFRadical.DefectHS
import GroupApproximation.Manuscript.OneSidedMFRadical.TransportAssembly
import GroupApproximation.Manuscript.OneSidedMFRadical.NormalKazhdan
import GroupApproximation.Manuscript.OneSidedMFRadical.KazhdanProjectionOrder
import GroupApproximation.Manuscript.OneSidedMFRadical.CentralCoronaCorner
import GroupApproximation.Manuscript.OneSidedMFRadical.CornerCoronaClass
import GroupApproximation.Manuscript.OneSidedMFRadical.PrintedSectorProof
import GroupApproximation.Manuscript.OneSidedMFRadical.CompressionCriterion
import GroupApproximation.Manuscript.OneSidedMFRadical.DefectSaturation
import GroupApproximation.Manuscript.OneSidedMFRadical.ShadowResidual
import GroupApproximation.Manuscript.OneSidedMFRadical.PrintedDefectShadow
import GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveConfiguration
import GroupApproximation.Leavitt.LeavittMarkNontrivial
import GroupApproximation.Leavitt.LeavittMatrixCompression
import GroupApproximation.Leavitt.BinaryLeavittSimple
import GroupApproximation.Leavitt.ExchangePrerequisite
import GroupApproximation.Leavitt.ElementaryTransvectionExtraction
import GroupApproximation.Leavitt.CongruenceSubgroups
import GroupApproximation.Manuscript.OneSidedMFRadical.HeadlineTheorem
import GroupApproximation.Manuscript.OneSidedMFRadical.PrintedLeavittEquations
import GroupApproximation.Manuscript.OneSidedMFRadical.CountableNonMF
import GroupApproximation.Manuscript.OneSidedMFRadical.CanonicalSector
import GroupApproximation.Manuscript.OneSidedMFRadical.PrintedRemarks
import GroupApproximation.Manuscript.OneSidedMFRadical.PrintedFullKernelPullback
import GroupApproximation.Manuscript.OneSidedMFRadical.PrintedOneWordQuotientTest
import GroupApproximation.Manuscript.OneSidedMFRadical.PrintedResidualCalculusProof
import GroupApproximation.Manuscript.OneSidedMFRadical.PartialClosureQuotients
import GroupApproximation.Manuscript.OneSidedMFRadical.PartialClosureAnalysis
import GroupApproximation.Manuscript.OneSidedMFRadical.PartialClosureLeavitt
import GroupApproximation.Manuscript.OneSidedMFRadical.CornerCoronaKazhdanOrder
import GroupApproximation.Manuscript.OneSidedMFRadical.FaithfulCornerCoronaRepresentation
import GroupApproximation.Manuscript.OneSidedMFRadical.FaithfulCornerNormBridge
import GroupApproximation.Manuscript.OneSidedMFRadical.PrintedDefect
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceAbstractClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceAmbientKazhdanCriterionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceCamouflageConstructionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceCamouflageFactorizationConsequencesClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceCompressionCriterionIntroductionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceDefectFunctorialityClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceDoubleCommutatorExtractionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceElementaryNormalGenerationClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceImageKazhdanRadicalClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceImageNormalGenerationClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceIntroductionDefinitionsClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceOneWordQuotientTailClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceOperativePureInfinitenessClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentencePQSetupClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceRankTwelveProvenanceClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceRootDetectionCompositionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceShiftMatricesClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceSimpleDefectInferenceClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceSimpleIntersectionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceStableFiniteProofClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceTauDefinitionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceTauWhiteheadConclusionClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceWhiteheadEntryInsertionClosure
import GroupApproximation.Leavitt.ElementaryRoots
import GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoints
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceIntroClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceLeavittClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceMFCamouflageClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceNormalKazhdanClosure
import GroupApproximation.Manuscript.OneSidedMFRadical.SentenceTransportClosure
import GroupApproximation.Sofic.MFRelationClosure
import GroupApproximation.Sofic.UniversalFactorization
import GroupApproximation.Kazhdan.AmenableKazhdanFinite
import GroupApproximation.Kazhdan.KazhdanSeparableDescent

/-!
# Kernel audit for *One-sided Kazhdan transport and MF radicals*

Every numbered statement and every displayed equation of
`non_mf_groups_exist.tex` is printed here, and
`metadata/ONESIDED_TRANSPORT_LEDGER.md` has one row for each.
`scripts/check_onesided_transport_ledger.py` keeps the two in step in both
directions: a row may not name a declaration this file does not print, and
this file may not print a closed endpoint the ledger does not list.

`#audit_closed_axioms` does two things.  It fails the build if the axiom
closure of the proof contains anything beyond `propext`, `Classical.choice`
and `Quot.sound`, and it rejects any declaration whose type begins with a
caller-supplied binder.  The second half is what matters for an existence
headline: it is the machine check that a theorem is not quietly carrying
`(hSimple : IsSimpleGroup H)` or `(hConfiguration : ...)` as an
innocuous-looking manuscript parameter.  The manuscript's own quantifiers
therefore live inside named propositions -- `OneSidedCompressionCriterion`,
`PrescribedMFQuotients`, `PropositionDefect`, ... -- where the binder check is
supposed to find them, and not in front.

Two groups of declarations are printed with the weaker `#audit_axioms`,
which reports the closure without the binder check:

* the **printed definitions and the lemmas over arbitrary data** -- the
  compression-centralizer defect, the compression `Psi`, the corner
  conjugation, the amalgam.  These take the manuscript's own data (a group, a
  Leavitt family, a homomorphism) as leading binders, so they cannot have an
  empty telescope; they assume nothing, and each is consumed by a closed
  endpoint above.
* the **implementation lemmas** the closed endpoints are assembled from,
  audited at their own statements so that the manuscript rows are not the only
  place their closure is checked.
-/

/-! ## Section 1: the MF radical, the defect, and the three theorems -/

#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptMFResidualCalculusLiteral
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptMFResidualCalculus
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptLiteralMFClosureIsQuotientPullback
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptMFRadicalIsLiteralClosureOfTrivial
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptFullRadicalKillsMFTargets
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCoronaDenominator
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptMFUnitaryModels
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCoronaImagesAndTargets

-- Theorem A, printed as one theorem with four clauses, and its two exact
-- constituents.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCompleteOneSidedCompressionCriterion
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptOneSidedCompressionCriterion
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedDefectFiniteDimensionalSterility

-- The sterility paragraph.  The amenable case is not claimed: only the
-- group-theoretic half, `L` finite, is proved.  See the ledger.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedDefectSterility

-- Theorem B.  The displayed conclusion, structural clauses, and the printed
-- adjective "simple" are closed; the simplicity and full headline audits
-- appear below.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.leavittFamily
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.rankTwelve_actualCoronaMFResidual_eq_top
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.closedStructuralProfile
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptBinaryLeavittFullRadical
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCountableNonMFGroupExists
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptNotEveryCountableGroupIsMF
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCountableNonOperatorMFGroupExists
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCountableKazhdanFullMFRadicalGroupExists
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSaturatedDefectKillsMFTargets

-- `eq:basic-defect`: the introduction's display of Corollary `cor:defect-hs`.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCompressionDefectHSInvisible

-- Theorem C.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrescribedMFQuotients

/-! ## Section 2: one-sided compression in finite dimension -/

#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptFiniteDimensionalCommutantRigidity
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCommutantFiniteDimensionalHypothesisIsEssential
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedAmenableCaseChain
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSoficityIsNotObstructedByFullRadicals
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptFullRadicalsDoNotEntailNonsoficity
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntersectionOfKernelsIsNormal

/-! ## Section 3: Kazhdan transport in normalized Hilbert--Schmidt norm -/

#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptShadowResidualIsIntersectionOfHSKernels
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptShadowResidualIsNormal
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptNormMatrixCoronaStableFinite
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptOneSidedKazhdanProjectionOrder
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptMaximalCStarKazhdanProjectionOrder
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptOneSidedKazhdanTransport
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptOneSidedKazhdanTransportPackage
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCompressionGroupKazhdanTransport
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptOneSidedKazhdanTransportAnyAmbient

/-! ## Section 4: the canonical Kazhdan sector and the MF radical -/

#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCentralCoronaCorner
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCornerCoronaClass
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedNormalKazhdanCornerSteps
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptNormalKazhdanRadical
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedDefectShadowInclusion
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedDefectNormalKazhdanRadical
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptDefectSaturation

/-! ## Section 5: the binary Leavitt self-compression -/

#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.q_ne_zero
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.printedTauGL
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tauUnit_eq_six_elementary
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.printedTauGL_mem
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.corner_hasKazhdanPropertyT
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.printedDefectConfiguration
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedLeavittAlgebraEquations
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCompressorEquations
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSectionFiveEquations

-- Property `(T)` at every representation universe.  The first two are general
-- transport results over caller-supplied data; the final profile is
-- hypothesis-free but universe-polymorphic rather than a closed `Prop`
-- package.  The ordinary audits are therefore intentional.
#audit_axioms GroupApproximation.hasKazhdanPropertyT_type0_iff
#audit_axioms GroupApproximation.HasKazhdanPropertyT.ofType0Model
#audit_axioms GroupApproximation.rankTwelve_propertyT_universe_profile

/-! ## Section 6: the full MF radical -/

#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptPropositionDefect
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tau_conj_c

/-! ## Section 7: prescribed MF quotients -/

#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSplitPrescribedProjection
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptUniversalFactorization
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrescribedQuotientRelationCalculus
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.ClosurePullback.manuscriptMFClosurePullbackAlongFactorization

/-! ## Simplicity and the complete headline -/

#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptPropositionSimple
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptBinaryLeavittHeadline

/-! ## Printed definitions and statements over arbitrary manuscript data

These carry no assumption.  Their types begin with the group, the ring, the
Leavitt family or the homomorphism that the manuscript itself quantifies over,
which is why the closed macro cannot accept them. -/

#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printedDefect
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.map_printedDefect_to_range_le
#audit_axioms GroupApproximation.LeavittFamily.matrixCompression
#audit_axioms GroupApproximation.RankTwelve.tau_fullCorner_tauInv
#audit_axioms GroupApproximation.MFCamouflage.Camouflage
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.ClosurePullback.literalMFClosure_eq_comap_of_factors
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.ClosurePullback.isCDEOperatorMF_quotient_iff_of_factors
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.ClosurePullback.camouflage_literalMFClosure_eq_comap
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.ClosurePullback.camouflage_isCDEOperatorMF_quotient_iff

/-! ## Implementation lemmas

Audited at their own statements, so that the manuscript rows above are not the
only place their axiom closure is checked. -/

-- The printed defect: its generating set, its generators, and the containment
-- in the development's larger compressor-group defect.
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printedDefectSet
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printedDefect_generator_mem
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printedDefect_le_compressionCentralizerDefect

-- The ordinary-limit `K_2(V)` and the printed MF closure.
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.hsKernel
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.literalMFClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.ClosurePullback.FactorsMFTargets
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.ClosurePullback.factorsMFTargets_iff_ker_le
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.ClosurePullback.manuscriptCoronaMFResidual_eq_comap_of_factors
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.ClosurePullback.factorsMFTargets_projection
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.ClosurePullback.camouflage_manuscriptCoronaMFResidual_eq_comap

-- `eq:pq`: the two Leavitt relations behind `q ≠ 0`.
#audit_axioms GroupApproximation.LeavittFamily.p0_add_p1
#audit_axioms GroupApproximation.LeavittFamily.t1_mul_p1_mul_s1

-- The ring-side centre computation used by the manuscript's simplicity proof.
-- These theorems quantify over a field or a unit, so they are support audits,
-- not zero-input manuscript endpoints.
#audit_axioms GroupApproximation.BinaryLeavitt.center_eq_bot
#audit_axioms GroupApproximation.BinaryLeavitt.central_units_trivial
#audit_axioms GroupApproximation.BinaryLeavitt.hasRightExchange

-- The four new Section 6 displays and generic root extraction support.  The
-- exact coefficient ring has closed single-sandwich division; coefficient
-- separation and the two reusable double-commutator facts are generic, so
-- their ordinary audits intentionally retain caller-supplied data.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.coefficientRing_hasSingleSandwichDivision
#audit_axioms GroupApproximation.exists_annihilate_preserve_reverse
#audit_axioms GroupApproximation.doubleCommutator_mem
#audit_axioms GroupApproximation.doubleCommutator_eq_sqZeroUnit
#audit_axioms GroupApproximation.exists_elGen_mem_of_conjSingle_eq
#audit_axioms GroupApproximation.exists_elGen_mem_of_inv_entry_zero
#audit_axioms GroupApproximation.exists_elGen_mem_of_dense_entries
#audit_axioms GroupApproximation.exists_noncommuting_single_of_not_central
#audit_axioms GroupApproximation.rootDetection_of_leavittFamily

-- The two congruence-level endpoints, the full-linear-group centre
-- computation, and the optional reduction of simplicity to Preusser's
-- sandwich.  That final support theorem retains the general upper sandwich as
-- a visible leading hypothesis; the exact manuscript simplicity theorem above
-- instead uses the unconditional direct root-extraction route.
#audit_axioms GroupApproximation.relativeElementary_top
#audit_axioms GroupApproximation.congruenceSubgroup_bot
#audit_axioms GroupApproximation.center_eq_bot_of_central_units_trivial
#audit_axioms GroupApproximation.isSimpleGroup_of_preusser_sandwich

-- `eq:matrix-compression`: unitality, multiplicativity, the recovery identity
-- that gives injectivity, and the elementary-matrix formula.
#audit_axioms GroupApproximation.LeavittFamily.matrixCompression_one
#audit_axioms GroupApproximation.LeavittFamily.matrixCompression_mul
#audit_axioms GroupApproximation.LeavittFamily.matrixCompression_recover
#audit_axioms GroupApproximation.LeavittFamily.matrixCompressionHom_injective
#audit_axioms GroupApproximation.LeavittFamily.matrixCompression_elementaryUnit

-- `X`, `Y`, `XY = YX = I`, the nested `tau`, the Whitehead factorization and
-- the corner conjugation, over an arbitrary Leavitt family.
#audit_axioms GroupApproximation.RankTwelve.shift
#audit_axioms GroupApproximation.RankTwelve.shiftInv
#audit_axioms GroupApproximation.RankTwelve.shift_mul_shiftInv
#audit_axioms GroupApproximation.RankTwelve.shiftInv_mul_shift
#audit_axioms GroupApproximation.RankTwelve.tau
#audit_axioms GroupApproximation.RankTwelve.tau_eq_whitehead_product
#audit_axioms GroupApproximation.RankTwelve.shift_halfCorner_shiftInv

-- The concrete rank-twelve configuration behind `prop:defect`.
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tau_conj_corner_elementaryRoot
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tau_compresses_corner
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.c_commutes_corner
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tau_c_commutator_ell
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.defect_ne_one
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.normalClosure_defect_eq_top

-- The amalgam of Section 7.
#audit_axioms GroupApproximation.MFCamouflage.projection
#audit_axioms GroupApproximation.MFCamouflage.blackHole_injective
#audit_axioms GroupApproximation.MFCamouflage.productVertex_injective
#audit_axioms GroupApproximation.MFCamouflage.defect_ne_one

/-! ## Rows added by the consolidation pass -/

-- Section 4, on the printed defect and the printed natural-dimension radical.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptNormalKazhdanPrintedRadical
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptNormalKazhdanCoronaVanishing
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCriterionAssembly
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedDefectCoronaVanishing

-- The Introduction's amenable clause.  `finite_of_isAmenable_of_kazhdan` proves
-- the Bekka--de la Harpe--Valette step the manuscript cites, so this row carries
-- no literature dependence.
#audit_closed_axioms GroupApproximation.manuscriptAmenableKazhdanSterility

/-! ## Section 7, `prop:full-kernel-pullback` and its closing paragraph

The general statements live in `Sofic/FullMFRadicalClosurePullback.lean`,
`Sofic/FullMFRadicalQuotientLattice.lean` and
`Sofic/FullMFRadicalVisibleLocalization.lean` with the group, the surjection
and the normal subgroup in front; the printed sentences are restated with
those quantifiers inside a named `Prop` in
`Manuscript/OneSidedMFRadical/PrintedFullKernelPullback.lean`, which is what
makes the closed macro applicable. -/

#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedFullKernelPullback
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedFullKernelPullbackFromFullKernel
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedMFQuotientCorrespondence
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedVisibleQuotientIsomorphism
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCorrespondenceRespectsComposition
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedFullKernelPullbackParagraph

-- Section 7, the closing one-word quotient test at the visible group Z.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedOneWordQuotientTest
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedOneWordQuotientJustification
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedOneWordQuotientParagraph

/-! ## Sentence-level rows added by the printed-proof sweep

Each line below names a declaration that carries one printed sentence of a
manuscript proof.  Most quantify over the manuscript's data (the group, the
model sequence, the coefficient ring) in front, so the ordinary audit is the
only macro the binder check permits; the closed ones are stated at a named
`Prop`. -/

#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroEnumerateNonidentityAndPairs
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroCoronaDetectorPerNonidentity
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroPositiveCoronaNormDistance
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroEveryDetectorDescends
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroCoordinateUnitaryLifts
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroExistsFiniteDiagonalStage
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroDiagonalSumDefect
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroDiagonalSumHalfSeparation
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroArbitrarilyFarCoordinate
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroQuotientNormIsLimsup
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroDiagonalEventuallySeparates
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.introDiagonalCoronaHom_injective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroUniversalQuotientDiagonalAlternative
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptIntroDiagonalRepresentationFaithful
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence100_commutantComputation
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence101_inverseConjugation_maps_commutant
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence116_anyLift_gramDefect_tendsto
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence122_cornerExtension_isometry
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentences124_138_139_maximalCStarImage
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence124_maximalCStarKazhdanProjection
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence139_imageOfMaximalKazhdanProjection
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence138_maximalCStarExtension
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence126_representedKazhdanProjection_range
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence129_faithfulRepresentation_reflectsProjectionOrder
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence141_identity_before_nonfaithfulRepresentation
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence150_tripleConjugationDefect
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence155_cornerOwnNormalizedTrace
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence156_cornerKazhdanDetection
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence169_quotientImageRetainsNormalKazhdan
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence171_maximalProjectionImageIsFixedProjection
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence173_conjugateProjectionRangeArgument
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence177_cornerKazhdanProjectionZero
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence178_179_positiveAverageLowerBound
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence180_coordinateElementFormula
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence180_181_negativePartToCornerTrace
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence182_fixedElementSubsequence
#audit_axioms GroupApproximation.manuscriptRelationClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.printedDefect_eq_top_of_configuration
#audit_axioms GroupApproximation.elementaryRoot_commutator
#audit_axioms GroupApproximation.UniversalFactorization.exists_comp_eq
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscript_s0_t1_factorization
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscript_s0_mul_t1_ne_zero
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscript_reversing_zero_product_zero
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscript_reversing_zero_product_nonzero
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscript_coefficient_separation_explicit
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscript_choose_nonidentity_normal_element
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscript_choose_nonzero_off_diagonal_entry
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscript_camouflage_restriction_to_blackHole
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscript_camouflage_restriction_to_edge

-- The printed proof of `prop:mf-residual-calculus`, sentence by sentence, each
-- stated at a named `Prop` so the closed macro applies.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedIntersectionOfKernelsIsNormal
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedFullInvarianceThroughComposition
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedEnumerationsOfTheQuotient
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCoronaDetectorAtEachMarkedClass
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedDetectorKillsRadicalAndDescends
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedPolarCoordinateUnitaryLifts
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedStageDirectSum
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCoordinatesExistArbitrarilyFarOut
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedQuotientDetectedAndMF
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedClosureCriterion
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedResidualCalculusProof

/-! ## Axiom closure of every landed sentence-level endpoint

Each line below names a declaration that carries one printed sentence.  The
ordinary audit is what applies: these quantify over the manuscript's data in
front, and the closed macro rejects any leading binder.  What a green build
proves here is that no sentence endpoint reaches beyond `propext`,
`Classical.choice` and `Quot.sound` -- in particular that none of them is
resting on a `sorry`. -/

-- FaithfulCornerCoronaRepresentation
#audit_axioms GroupApproximation.CStarState.universalGNSLinear_apply
#audit_axioms GroupApproximation.CStarState.universalGNSOperator_apply
#audit_axioms GroupApproximation.CStarState.universalGNSStarAlgHom_apply
#audit_axioms GroupApproximation.CStarState.universalGNSStarAlgHom_eq_zero_iff
#audit_axioms GroupApproximation.CStarState.universalGNSStarAlgHom_injective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.cornerCoronaFaithfulRepresentation_injective

-- FaithfulCornerNormBridge
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.sectorGram_isSelfAdjoint
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.normFormLowerBound_of_faithful_quadraticForm
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.exists_coordinateNormBound_of_faithful_cornerKazhdan
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.eventually_printed_corner_trace_inequality_of_faithful

-- PrintedDefect
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printedDefectSet_subset

-- PrintedDefectShadow
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printedDefect_le_opToHSShadowResidual_direct
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.normalKazhdan_le_actualCoronaMFResidual_of_le_printedDefect

-- PrintedDefinitions
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.mem_nullMatrixSequenceIdeal_iff
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.mem_nullMatrixSequenceIdeal_cofinite_iff
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.normMatrixCStarCoronaMk_eq_zero_iff_tendsto
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.isCDEOperatorMF_iff_nonempty_weakMFApproximation
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.isCDEOperatorMF_exists_separating_unitary_models
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.coronaImage_countable
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.coronaImage_isOperatorMF
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.isCDEOperatorMF_of_coronaEmbedding
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.isCDEOperatorMF_exists_coronaEmbedding

-- PrintedFullKernelPullback
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedFullKernelPullbackAtPrintedObjects

-- PrintedLeavittEquations
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_leavitt_delta
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_q_eq
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_p_eq
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_q_mul_s0
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_t0_mul_q
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_matrixCompression_injective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_scalarDiagonal_image_of_one
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_p0_ne_one
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_scalarDiagonal_p0_ne_one
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_halfCorner_injective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_fullCorner_injective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_tau_conj_corner_subset
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_f2_unit_eq_one
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_f2_units_subsingleton

-- PrintedRemarks
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.commutant_surjective_of_injective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.fixedSubmodule_bot_eq_top
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.shiftConjugation_apply
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.shiftConjugation_injective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.shiftConjugation_not_surjective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.sInf_normal_of_forall_normal
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.iInf_ker_normal

-- PrintedSectorProof
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.complement_mul_kazhdanProjection
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.kazhdanProjection_mul_complement
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.corner_compression_kazhdanProjection
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.eq_zero_of_mem_corner_of_fixed
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.kazhdan_sum_sq_ge_of_noInvariant
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.kazhdan_average_sq_ge_of_noInvariant
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.corner_kazhdan_average_sq_ge
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.hsNormSq_sum_ge_of_corner_quadratic_form
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.printed_corner_trace_inequality
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.exists_persistent_index
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.exists_persistent_index_atTop
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.exists_persistent_subsequence
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.mul_eq_of_isStarProjection_le
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.le_of_le_in_faithful_rep

-- SentenceAbstractClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence1_countableNonMF_exists
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence2_MFRadical_membership
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence3_oneSidedCompression_forces_radical
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence4_normalGeneration_forces_fullRadical
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence5_binaryLeavitt_realization
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence6_resultingGroup_simple
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence7_resultingGroup_propertyT
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence8_everyHomToMF_trivial
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence9_notEveryCountableGroupIsMF
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence10_prescribedMFQuotients

-- SentenceAmbientKazhdanCriterionClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptTopSubgroupHasKazhdanPropertyT
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCompressionCriterionWithAmbientKazhdanSubgroup

-- SentenceCamouflageConstructionClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence269_cyclicEdge
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence270_camouflage_is_amalgam
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence271_projectionFamily_agreesOnEdge
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence272_projection_epimorphism
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence273_projection_split
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence274_vertexMaps_injective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence275_defect_survives
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence276_universalFactorization
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence277_projectionKernel

-- SentenceCamouflageFactorizationConsequencesClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence279_productVertex_factorization
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentences280_281_factorThroughProjection
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence282_factor_unique
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence283_defect_mem_kernel
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence284_quotientKernel
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence285_blackHoleCoronaHom_eq_one
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence286_MFTarget_precomp_bijective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence287_corona_precomp_bijective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence288_radicalPullback
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence289_camouflage_not_MF
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence290_radical_eq_kernel_eq_normalClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence291_closurePullback
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence292_factoredMap_kills_iff
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence293_quotient_MF_iff
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence294_preimageOfImage

-- SentenceCompressionCriterionIntroductionClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence38_quotientMF_iff_kernelIntersectionFixed
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence39_mem_compressionSet_iff
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence40_printedDefect_display
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence41_printedDefect_depends_only_on_pair
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence42_normalKazhdan_defect_le_radical
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence43_nontrivial_defectKazhdan_obstructs_MF
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence44_full_defect_gives_full_radical
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence45_finiteDimensional_representation_kills_defect
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence46_defectGenerator_HS_invisible
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence47_normality_makes_KazhdanProjection_commute
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence48_central_complementary_corner
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence50_compressionCriterion_conclusion
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence51_finiteDimensional_commutant_route

-- SentenceDefectFunctorialityClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.map_commutesWithSubgroup
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptMapCentralizerToRangeCentralizer
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.map_printedDefectGenerator_mem
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptMapPrintedDefectGeneratorToRange

-- SentenceDoubleCommutatorExtractionClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence246_sparseDoubleCommutator_extractsRoot
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence247_sparseDefect_extractsRoot
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence248_denseCoefficients_extractRoot
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentences249_250_denseDoubleCommutator_extractsRoot
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence251_rowExtraction
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence252_extractedRoot_closesSimplicity
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence253_explicitNontrivialRoot

-- SentenceElementaryNormalGenerationClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence228_centralUnit_eq_one
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence229_sandwichedRoot_normalGenerates
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence229_simplicity_reduces_to_rootDetection
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence230_unitRootCommutators
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence231_sourceTargetMoves
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence232_movesGiveEveryElementaryGenerator

-- SentenceImageKazhdanRadicalClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptMappedSubgroupHasKazhdanPropertyT
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSurjectiveImageHasKazhdanPropertyT
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptMappedFullDefectGivesFullMFRadical
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptImageSaturationFullMFRadicalRoute

-- SentenceImageNormalGenerationClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSimpleImageLeMappedPrintedDefect
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptNormalClosureSimpleImageLeMappedPrintedDefect
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSimpleImageNormalGenerationRoute

-- SentenceIntroductionDefinitionsClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence11_MFDefinition
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentences12_14_corona_and_c0Denominator
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence15_MFUnitaryModels
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence17_MFRadicalDisplay
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence18_MF_iff_radical_bot
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence19_fullRadical_kills_MFTargets
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence20_MFClosureDisplay
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentences21_22_coronaImages_and_MFTargets
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence23_radical_is_closure_bot
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence24_quotientMF_iff_closureFixed
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentences25_28_basicResidualCalculus
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence29_intersectionOfKernels_normal
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence30_endomorphism_preserves_radical

-- SentenceOneWordQuotientTailClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence295_oneWordQuotientTest
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence296_oneWordJustification
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentenceTailClosure

-- SentenceOperativePureInfinitenessClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptSentence227_operativePureInfiniteness
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.operativePureInfinitenessInput_iff

-- SentencePQSetupClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptPQDefinitions
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptPQEquations

-- SentenceRankTwelveProvenanceClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptSentence223_rankTwelveProvenance

-- SentenceRootDetectionCompositionClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence233_coefficientSeparation
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence234_reversingZeroProduct
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence240_explicitSeparationConclusion
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence242_inverseOfDiagonal_isDiagonal
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence243_elementaryCenter_eq_bot
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence244_diagonalBranch_extractsRoot
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentences233_245_rootDetection

-- SentenceShiftMatricesClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptShiftMatrixX
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptShiftMatrixY
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptShiftMatricesAreMutualInverses

-- SentenceSimpleDefectInferenceClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.top_le_normal_of_simple_of_nontrivial_mem
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence67_simplicity_gives_defect_normalGeneration
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence68_simplicity_saturates_printedDefect

-- SentenceSimpleIntersectionClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedDefectIntersectionNormalInSubgroup
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSimplePrintedDefectIntersectionEqTop
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSimpleSubgroupLePrintedDefectViaIntersection
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptNormalClosureSimpleSubgroupLePrintedDefect
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedDefectEqTopViaSimpleIntersection

-- SentenceStableFiniteProofClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptStableFiniteBoundedLiftGramDefect
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptStableFiniteGramDefectEventuallyHalf
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptComplementedCornerIsometryProducts
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptCornerFiniteViaComplementedIsometry
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptStableFiniteProofSentenceCluster

-- SentenceTauDefinitionClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptTauDefinitionAndInvertibility

-- SentenceTauWhiteheadConclusionClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptTauElementaryViaWhiteheadFactorization

-- SentenceTransportClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentenceTransportClosure

-- SentenceWhiteheadEntryInsertionClosure
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptWhiteheadOffDiagonalBlocksPairwiseZero
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptFlattenedWhiteheadBlocksPairwiseZero
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptWhiteheadEntryInsertionProduct
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptWhiteheadEntrywiseElementaryRoute

-- The printed passage from the Kazhdan inequality to the operator order
-- inside the corner corona, which `CornerCoordinatePassage` states it does not
-- claim and takes as a hypothesis.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCornerCoronaKazhdanOrder
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.kazhdan_quadraticForm_universalGNS
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.cornerCorona_kazhdan_normForm
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.noInvariantVectors_of_kazhdanProjectionImageZero
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.exists_coordinateNormBound_of_cornerCoronaKazhdan
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.eventually_sector_quadratic_form_ge_of_cornerCoronaKazhdan

-- Printed proof steps that a sentence-level audit had graded `partial`: the
-- Leavitt coefficient calculations of `prop:simple`, the camouflage quotient
-- paragraph, and the commutant conjugation display.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedReversedProductVanishingImplication
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCoefficientSeparationFactorizations
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCoefficientSeparationRecipe
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCoefficientSeparation
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCoefficientSeparationAtBinaryLeavitt
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedDiagonalConjugationMovesRoot
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedDiagonalConjugationMovesRootAtBinaryLeavitt
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedSparseDefectEntryNonzero
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedDenseAnnihilatingProduct
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedLeavittCoefficientCalculations
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCamouflageQuotientKillsBothVertices
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCamouflageQuotientIsVisibleGroup
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCommutantConjugationDisplay
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCommutantConjugationInclusion

-- The analysis half of the same sweep: the printed polar correction, the
-- unitary representatives, the corona commutation vanishing, both corner
-- unitarity defects, and pure infiniteness proved rather than cited.
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCommutantConjugationChain
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCommutantConjugateInclusion
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedOneSidedPolarCorrection
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedOneSidedUnitaryRepresentatives
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedCoronaCommutationVanishing
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedBothCornerUnitarityDefects
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptPrintedBinaryLeavittPurelyInfiniteSimple
