import GroupApproximation.Meta.AxiomGuard
import GroupApproximation.Sofic.PropertyTFreeMFCollapse

/-!
# Property-(T)-free MF-collapse audit

The closed package contains only unconditional universal implications.  In
particular it does not treat the concrete Leavitt authentication predicate as
proved.
-/

#audit_axioms GroupApproximation.PropertyTFreeMFCollapse.rectangular_leakage_eq_one
#audit_axioms GroupApproximation.PropertyTFreeMFCollapse.binary_rectangular_leakage_eq_one
#audit_axioms GroupApproximation.PropertyTFreeMFCollapse.mem_coronaMFResidual_of_mem_fdUnitaryResidual_of_stableAtMark
#audit_axioms GroupApproximation.PropertyTFreeMFCollapse.authenticatedRectangularReturn_totalCollapse
#audit_axioms GroupApproximation.PropertyTFreeMFCollapse.stable_compression_criterion
#audit_closed_axioms GroupApproximation.PropertyTFreeMFCollapse.unconditionalPropertyTFreeMFCollapsePackage
