import Mathlib.Algebra.Field.ZMod
import Mathlib.Algebra.RingQuot
import GroupApproximation.Leavitt.UniversalLeavittOver

/-!
# The Cohn algebra `C₂(𝔽₂)` and its surjection onto `L_{𝔽₂}(1,2)`

Step W1 of `simple_kazhdan_sofic_group.tex` l.733-735 (stable `K₂(L_{𝔽₂}(1,2)) = 0`)
goes through the Cohn algebra `C₂(𝔽₂)`: the free `𝔽₂`-algebra on `x₀,x₁,y₀,y₁`
subject only to `yᵢ xⱼ = δᵢⱼ` (no range relation).  The Leavitt algebra is its quotient
by the ideal generated by `p = 1 - x₀y₀ - x₁y₁` (Ara-Brustenga-Cortiñas 2009).

We reuse the generator type and the free algebra of `BinaryLeavitt`, so that the
quotient map `C₂(𝔽₂) → L_{𝔽₂}(1,2)` is induced by the identity of free algebras.
-/

namespace GroupApproximation.Full.LVCohnRelK1

open GroupApproximation.BinaryLeavitt

noncomputable section

/-- The four Cohn relations `tᵢ sⱼ = δᵢⱼ` on the free algebra over `𝔽₂`
(`simple_kazhdan_sofic_group.tex` l.733-735). -/
inductive CohnRel : Free (ZMod 2) → Free (ZMod 2) → Prop
  | t0_s0 : CohnRel (FreeAlgebra.ι (ZMod 2) t0 * FreeAlgebra.ι (ZMod 2) s0) 1
  | t0_s1 : CohnRel (FreeAlgebra.ι (ZMod 2) t0 * FreeAlgebra.ι (ZMod 2) s1) 0
  | t1_s0 : CohnRel (FreeAlgebra.ι (ZMod 2) t1 * FreeAlgebra.ι (ZMod 2) s0) 0
  | t1_s1 : CohnRel (FreeAlgebra.ι (ZMod 2) t1 * FreeAlgebra.ι (ZMod 2) s1) 1

/-- The Cohn algebra `C₂(𝔽₂)` (`simple_kazhdan_sofic_group.tex` l.733-735). -/
abbrev CohnTwoF2 : Type := RingQuot CohnRel

/-- The quotient map from the free algebra onto the Cohn algebra. -/
def mk : Free (ZMod 2) →ₐ[ZMod 2] CohnTwoF2 := RingQuot.mkAlgHom (ZMod 2) CohnRel

theorem mk_surjective : Function.Surjective mk :=
  RingQuot.mkAlgHom_surjective (ZMod 2) CohnRel

theorem mk_rel {a b : Free (ZMod 2)} (h : CohnRel a b) : mk a = mk b :=
  RingQuot.mkAlgHom_rel (ZMod 2) h

/-- A named generator of the Cohn algebra. -/
def gen (g : Generator) : CohnTwoF2 := mk (FreeAlgebra.ι (ZMod 2) g)

/-- The generators `x₀, x₁`. -/
def cx : Bool → CohnTwoF2
  | false => gen s0
  | true => gen s1

/-- The generators `y₀, y₁`. -/
def cy : Bool → CohnTwoF2
  | false => gen t0
  | true => gen t1

theorem y0_x0 : cy false * cx false = 1 := by
  have h := mk_rel CohnRel.t0_s0
  rw [map_mul, map_one] at h
  exact h

theorem y0_x1 : cy false * cx true = 0 := by
  have h := mk_rel CohnRel.t0_s1
  rw [map_mul, map_zero] at h
  exact h

theorem y1_x0 : cy true * cx false = 0 := by
  have h := mk_rel CohnRel.t1_s0
  rw [map_mul, map_zero] at h
  exact h

theorem y1_x1 : cy true * cx true = 1 := by
  have h := mk_rel CohnRel.t1_s1
  rw [map_mul, map_one] at h
  exact h

theorem cy_cx_self : ∀ i : Bool, cy i * cx i = 1
  | false => y0_x0
  | true => y1_x1

theorem cy_cx_ne : ∀ {i j : Bool}, i ≠ j → cy i * cx j = 0
  | false, false, h => absurd rfl h
  | false, true, _ => y0_x1
  | true, false, _ => y1_x0
  | true, true, h => absurd rfl h

/-- The unit map `𝔽₂ → C₂(𝔽₂)` (`simple_kazhdan_sofic_group.tex` l.733-735). -/
def cohnUnit : ZMod 2 →+* CohnTwoF2 := algebraMap (ZMod 2) CohnTwoF2

theorem toLeavitt_respects :
    ∀ ⦃a b : Free (ZMod 2)⦄, CohnRel a b →
      quotientMap (ZMod 2) a = quotientMap (ZMod 2) b := by
  intro a b h
  cases h with
  | t0_s0 => exact RingQuot.mkAlgHom_rel (ZMod 2) (Relation.t0_s0 (k := ZMod 2))
  | t0_s1 => exact RingQuot.mkAlgHom_rel (ZMod 2) (Relation.t0_s1 (k := ZMod 2))
  | t1_s0 => exact RingQuot.mkAlgHom_rel (ZMod 2) (Relation.t1_s0 (k := ZMod 2))
  | t1_s1 => exact RingQuot.mkAlgHom_rel (ZMod 2) (Relation.t1_s1 (k := ZMod 2))

/-- The quotient `C₂(𝔽₂) → L_{𝔽₂}(1,2)` as an algebra map. -/
def toLeavittAlg : CohnTwoF2 →ₐ[ZMod 2] BinaryLeavittAlgebra (ZMod 2) :=
  RingQuot.liftAlgHom (ZMod 2) ⟨quotientMap (ZMod 2), toLeavitt_respects⟩

/-- The quotient ring map `C₂(𝔽₂) → L_{𝔽₂}(1,2)`
(`simple_kazhdan_sofic_group.tex` l.733-735). -/
def toLeavitt : CohnTwoF2 →+* BinaryLeavittAlgebra (ZMod 2) := toLeavittAlg.toRingHom

theorem toLeavitt_mk (a : Free (ZMod 2)) : toLeavitt (mk a) = quotientMap (ZMod 2) a :=
  RingQuot.liftAlgHom_mkAlgHom_apply (ZMod 2) (quotientMap (ZMod 2)) toLeavitt_respects a

theorem toLeavitt_smul (c : ZMod 2) (z : CohnTwoF2) : toLeavitt (c • z) = c • toLeavitt z :=
  map_smul toLeavittAlg c z

/-- The quotient map is surjective (`simple_kazhdan_sofic_group.tex` l.733-735). -/
theorem toLeavitt_surjective : Function.Surjective toLeavitt := by
  intro z
  obtain ⟨a, rfl⟩ := RingQuot.mkAlgHom_surjective (ZMod 2) (Relation (ZMod 2)) z
  exact ⟨mk a, toLeavitt_mk a⟩

end

end GroupApproximation.Full.LVCohnRelK1
