import GroupApproximation.BooneHigmanLinear.CharZero.K2Found.Relative
import GroupApproximation.Manuscript.SimpleKazhdanSofic.SkRows.SteinbergWeyl.Defs
import Mathlib.RingTheory.Ideal.Quotient.Defs
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Defs
import GroupApproximation.Meta.AxiomGuard

/-!
# Relative Steinberg groups of type A: the objects of Lavrenov–Sinchuk §4 (k2-poly H.L3)

Lane bh-pal-wire. These are the definitions shared by H.L3 (RelGen, bh-pal-wire) and H.L4
(LSCore, bh-pal-linear-char0), following A. Lavrenov and S. Sinchuk, *A Horrocks-type theorem for
even orthogonal K₂*, arXiv:1909.02637, §4, in type A over the index type `I`. The root
`α = (i, j)` is written `x_ij`. L–S conjugation is right conjugation, `h^g = g⁻¹ h g`.

* `zElt i j hij s ξ = x_ji(-ξ) · x_ij(s) · x_ji(ξ)`, L–S (4.1): `z_α(s, ξ) = x_α(s)^{x_{-α}(ξ)}`.
* `cElt i j hij s t = ⁅x_ij(s), x_ji(t)⁆`, L–S (4.2).
* `relKer I J = ker (St_I(R) → St_I(R/J))`, L–S's `St̄(Φ, R, J)`.
* `xSet`, `xGroup`: the root elements with coefficient in `J` and the group they generate, L–S
  `St(Φ, J)`.
* `zSet I J U`: the `z`'s over the roots in `U`. `zGen I J U` is generated by `x(J)` and
  `zSet I J U`, L–S `𝒵(U, R, J)`.
* `polyIdeal M = M[X]`, `xPolyIdeal M = X·M[X]`, and `polyKer I M = K(A[X], M[X])`, the kernel of
  evaluation at `0` on `St̄(A[X], M[X])`.
* `hBar I A J`: L–S `H̄(Φ, A, J)`, generated by `h_ij(u)`, `u ∈ (1 + J)ˣ`, and the symbols
  `h_ij(uv) h_ij(u)⁻¹ h_ij(v)⁻¹` with one of `u, v` in `(1 + J)ˣ` (L–S `{u, v}`, either order).
-/

namespace GroupApproximation.BooneHigmanLinear.RelGen

open scoped commutatorElement
open GroupApproximation.SteinbergGroup
open GroupApproximation.SimpleKazhdanSofic.SkRows.SteinbergWeyl (h)

section Elements

variable {I : Type*} [Fintype I] [DecidableEq I] {R : Type*} [CommRing R]

/-- L–S (4.1): `z_ij(s, ξ) = x_ij(s)^{x_ji(ξ)} = x_ji(-ξ) · x_ij(s) · x_ji(ξ)`. -/
def zElt (i j : I) (hij : i ≠ j) (s ξ : R) : SteinbergGroup I R :=
  x j i hij.symm (-ξ) * x i j hij s * x j i hij.symm ξ

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.zElt

/-- L–S (4.2): `c_ij(s, t) = ⁅x_ij(s), x_ji(t)⁆`. -/
def cElt (i j : I) (hij : i ≠ j) (s t : R) : SteinbergGroup I R :=
  ⁅x i j hij s, x j i hij.symm t⁆

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.cElt

end Elements

section Groups

variable (I : Type*) [Fintype I] [DecidableEq I] {R : Type*} [CommRing R]

/-- `St̄(R, J) = ker (St_I(R) → St_I(R/J))`. -/
def relKer (J : Ideal R) : Subgroup (SteinbergGroup I R) :=
  K2Found.relSt I (Ideal.Quotient.mk J)

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.relKer

/-- The root elements `x_ij(s)` with `s ∈ J`. -/
def xSet (J : Ideal R) : Set (SteinbergGroup I R) :=
  {g | ∃ (i j : I) (hij : i ≠ j) (s : R), s ∈ J ∧ x i j hij s = g}

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.xSet

/-- L–S `St(Φ, J)`: the subgroup generated by the root elements with coefficient in `J`. -/
def xGroup (J : Ideal R) : Subgroup (SteinbergGroup I R) :=
  Subgroup.closure (xSet I J)

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.xGroup

/-- The elements `z_ij(s, ξ)` with `s ∈ J`, for the roots `(i, j)` in `U`. -/
def zSet (J : Ideal R) (U : I → I → Prop) : Set (SteinbergGroup I R) :=
  {g | ∃ (i j : I) (hij : i ≠ j) (s ξ : R), U i j ∧ s ∈ J ∧ zElt i j hij s ξ = g}

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.zSet

/-- L–S `𝒵(U, R, J)`: generated by `x(J)` and the `z`'s over `U`. -/
def zGen (J : Ideal R) (U : I → I → Prop) : Subgroup (SteinbergGroup I R) :=
  Subgroup.closure (xSet I J ∪ zSet I J U)

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.zGen

/-- The units `u ∈ Aˣ` with `u ≡ 1 mod J`. -/
def unitsOneAdd (J : Ideal R) : Set Rˣ :=
  {u | (u : R) - 1 ∈ J}

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.unitsOneAdd

/-- L–S `H̄(Φ, R, J)`: generated by `h_ij(u)` with `u ∈ (1 + J)ˣ` and the symbols
`h_ij(uv) h_ij(u)⁻¹ h_ij(v)⁻¹` with `u ∈ (1 + J)ˣ` or `v ∈ (1 + J)ˣ`. -/
def hBar (J : Ideal R) : Subgroup (SteinbergGroup I R) :=
  Subgroup.closure
    ({g | ∃ (i j : I) (hij : i ≠ j) (u : Rˣ), u ∈ unitsOneAdd J ∧ h i j hij u = g} ∪
      {g | ∃ (i j : I) (hij : i ≠ j) (u v : Rˣ), (u ∈ unitsOneAdd J ∨ v ∈ unitsOneAdd J) ∧
        h i j hij (u * v) * (h i j hij u)⁻¹ * (h i j hij v)⁻¹ = g})

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.hBar

/-- `U(S, J)`: generated by the root elements `x_ij(s)`, `s ∈ J`, for the roots in `S`. -/
def rootGroup (J : Ideal R) (S : I → I → Prop) : Subgroup (SteinbergGroup I R) :=
  Subgroup.closure {g | ∃ (i j : I) (hij : i ≠ j) (s : R), S i j ∧ s ∈ J ∧ x i j hij s = g}

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.rootGroup

end Groups

section Poly

variable (I : Type*) [Fintype I] [DecidableEq I] {A : Type*} [CommRing A]

/-- `M[X] ⊆ A[X]`. -/
abbrev polyIdeal (M : Ideal A) : Ideal (Polynomial A) :=
  M.map Polynomial.C

/-- `X·M[X] ⊆ A[X]`. -/
abbrev xPolyIdeal (M : Ideal A) : Ideal (Polynomial A) :=
  Ideal.span {Polynomial.X} * polyIdeal M

/-- `K(A[X], M[X])`, the kernel of evaluation at `0` on `St̄(A[X], M[X])`. -/
def polyKer (M : Ideal A) : Subgroup (SteinbergGroup I (Polynomial A)) :=
  relKer I (polyIdeal M) ⊓ (ringMap (Polynomial.evalRingHom 0 : Polynomial A →+* A)).ker

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.polyKer

end Poly

end GroupApproximation.BooneHigmanLinear.RelGen
