import GroupApproximation.BooneHigmanLinear.RelGen.TitsCases
import GroupApproximation.BooneHigmanLinear.RelGen.Statements
import GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwoRootSpan
import GroupApproximation.Meta.AxiomGuard

/-!
# Stein–Tits–Vaserstein, part 2: L–S Theorem 4.2 in type A

Lane bh-pal-wire, k2-poly H.L3. `thm42 : Thm42Statement`: given a third index for every pair,
`St̄(R, J) = ker (St_I(R) → St_I(R/J))` is generated by the `z_ij(s, ξ)`, `s ∈ J`.

Write `Z = 𝒵(Φ, R, J)`. It contains `x(J)`, since `z(s, 0) = x(s)`, and it lies in the kernel. The
kernel is the normal closure of `x(J)` (`K2Found.relSt_eq_normalClosure`), so it suffices that `Z`
is normal. By `RelGen.TitsCases`, conjugation by `x_kl(η)` keeps every generator in `Z`, except in
the case `x_ab` acting on `z_ab`. For that case:

* `z_mem_zGen_ne`: with a third index `m`, `z_ab(s, ξ)` lies in `⟨x(J), z_cd : (c, d) ≠ (a, b)⟩`.
  Write `x_ab(s) = ⁅x_am(s), x_mb(1)⁆` and conjugate by `X = x_ba(-ξ)`. Then `X x_am(s) X⁻¹ ∈ x(J)`,
  and `X x_mb(1) X⁻¹ = x_ma(·) x_mb(1)`. Expanding the commutator leaves only `x(J)`-elements,
  `z_am` and a conjugate of `z_bm` by `x_ma`.
* `conj_ab_mem_zAll`: `x_ab(η)` conjugates that subgroup into `Z` (`TitsCases`).
-/

namespace GroupApproximation.BooneHigmanLinear.RelGen

open scoped commutatorElement
open GroupApproximation.SteinbergGroup
open GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo (rootSpan_induction
  mem_rootSpan_true)

variable {I : Type*} [Fintype I] [DecidableEq I] {R : Type*} [CommRing R] {J : Ideal R}

/-- **The hard case.** With `m ∉ {a, b}`, `z_ab(s, ξ)` lies in `⟨x(J), z_cd : (c, d) ≠ (a, b)⟩`. -/
theorem z_mem_zGen_ne {a b m : I} (hab : a ≠ b) (ham : a ≠ m) (hbm : b ≠ m) (ξ : R) {s : R}
    (hs : s ∈ J) : zElt a b hab s ξ ∈ zGen I J (fun c d => ¬(c = a ∧ d = b)) := by
  have hmb : m ≠ b := hbm.symm
  have hma : m ≠ a := ham.symm
  have hZ : ∀ {c d : I} (hcd : c ≠ d), (c = a → d ≠ b) →
      zGen I J (fun i j => i = c ∧ j = d) ≤ zGen I J (fun c d => ¬(c = a ∧ d = b)) :=
    fun _ h => zGen_mono fun i j hij hne => h (hij.1 ▸ hne.1) (hij.2 ▸ hne.2)
  have hxab : x a b hab s = ⁅x a m ham s, x m b hmb 1⁆ := by
    rw [x_commutator a m b ham hmb hab, mul_one]
  have hP : x b a hab.symm (-ξ) * x a m ham s * (x b a hab.symm (-ξ))⁻¹ =
      x b m hbm (-ξ * s) * x a m ham s := by
    rw [conj_eq_commutator_mul, x_commutator b a m hab.symm ham hbm]
  have hQ : x b a hab.symm (-ξ) * x m b hmb 1 * (x b a hab.symm (-ξ))⁻¹ =
      x m a hma (-(1 * -ξ)) * x m b hmb 1 := by
    rw [conj_eq_commutator_mul, ← commutatorElement_inv, x_commutator m b a hmb hab.symm hma,
      ← x_neg m a hma (1 * -ξ)]
  have hz : zElt a b hab s ξ =
      ⁅x b a hab.symm (-ξ) * x a m ham s * (x b a hab.symm (-ξ))⁻¹,
        x b a hab.symm (-ξ) * x m b hmb 1 * (x b a hab.symm (-ξ))⁻¹⁆ := by
    rw [zElt_eq_conj, hxab]
    simp only [commutatorElement_def]
    group
  -- The three pieces of the expanded commutator.
  have hA : x m b hmb 1 * (x a m ham s)⁻¹ * (x m b hmb 1)⁻¹ =
      x a b hab (-(-s * 1)) * x a m ham (-s) := by
    rw [← x_neg a m ham s, conj_eq_commutator_mul, ← commutatorElement_inv,
      x_commutator a m b ham hmb hab (-s) 1, ← x_neg a b hab (-s * 1)]
  have hB : x m b hmb 1 * (x b m hbm (-ξ * s))⁻¹ * (x m b hmb 1)⁻¹ =
      zElt b m hbm (-(-ξ * s)) (-1) := by
    rw [← x_neg b m hbm (-ξ * s), zElt, neg_neg, ← x_neg m b hmb 1]
  have hs1 : -(-s * 1) ∈ J := neg_mem (J.mul_mem_right 1 (neg_mem hs))
  have hs2 : -(-ξ * s) ∈ J := neg_mem (J.mul_mem_left (-ξ) hs)
  set U := x m a hma (-(1 * -ξ))
  have hmemA : U * (x a b hab (-(-s * 1)) * x a m ham (-s)) * U⁻¹ ∈
      zGen I J (fun c d => ¬(c = a ∧ d = b)) := by
    rw [show U * (x a b hab (-(-s * 1)) * x a m ham (-s)) * U⁻¹ =
      (U * x a b hab (-(-s * 1)) * U⁻¹) * (U * x a m ham (-s) * U⁻¹) by group]
    refine Subgroup.mul_mem _ (xGroup_le_zGen _ ?_) (hZ ham (fun _ e => hmb e) ?_)
    · exact conj_x_mem_xGroup hma hab _ hs1 (fun h => hbm h.2)
    · exact conj_ba_x_ab ham hma _ (neg_mem hs)
  have hmemB : U * zElt b m hbm (-(-ξ * s)) (-1) * U⁻¹ ∈
      zGen I J (fun c d => ¬(c = a ∧ d = b)) :=
    hZ hbm (fun e => absurd e hab.symm) (conj_z_mem hbm hma _ (-1) hs2 (fun h => hmb h.1))
  have hmemP : x b m hbm (-ξ * s) * x a m ham s ∈ zGen I J (fun c d => ¬(c = a ∧ d = b)) :=
    xGroup_le_zGen _ (Subgroup.mul_mem _ (x_mem_xGroup hbm (J.mul_mem_left (-ξ) hs))
      (x_mem_xGroup ham hs))
  rw [hz, hP, hQ]
  have e : ⁅x b m hbm (-ξ * s) * x a m ham s, U * x m b hmb 1⁆ =
      (x b m hbm (-ξ * s) * x a m ham s) *
        (U * (x m b hmb 1 * (x a m ham s)⁻¹ * (x m b hmb 1)⁻¹) * U⁻¹) *
        (U * (x m b hmb 1 * (x b m hbm (-ξ * s))⁻¹ * (x m b hmb 1)⁻¹) * U⁻¹) := by
    rw [commutatorElement_def]
    group
  rw [e, hA, hB]
  exact Subgroup.mul_mem _ (Subgroup.mul_mem _ hmemP hmemA) hmemB

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.z_mem_zGen_ne

/-- `x_ab(η)` conjugates `⟨x(J), z_cd : (c, d) ≠ (a, b)⟩` into `Z`. -/
theorem conj_ab_mem_zAll {a b : I} (hab : a ≠ b) (η : R) {g : SteinbergGroup I R}
    (hg : g ∈ zGen I J (fun c d => ¬(c = a ∧ d = b))) :
    x a b hab η * g * (x a b hab η)⁻¹ ∈ zGen I J (fun _ _ => True) := by
  have hT : ∀ {c d : I}, zGen I J (fun i j => i = c ∧ j = d) ≤ zGen I J (fun _ _ => True) :=
    zGen_mono fun _ _ _ => trivial
  rw [zGen] at hg
  induction hg using Subgroup.closure_induction with
  | mem g hg =>
    rcases hg with ⟨c, d, hcd, s, hs, rfl⟩ | ⟨c, d, hcd, s, ζ, hU, hs, rfl⟩
    · by_cases hc : c = b ∧ d = a
      · obtain ⟨hcb, hda⟩ := hc
        subst hcb
        subst hda
        exact hT (conj_ba_x_ab hcd hab η hs)
      · exact xGroup_le_zGen _ (conj_x_mem_xGroup hab hcd η hs hc)
    · exact hT (conj_z_mem hcd hab η ζ hs (fun h => hU ⟨h.1.symm, h.2.symm⟩))
  | one => simp only [mul_one, mul_inv_cancel, Subgroup.one_mem]
  | mul g₁ g₂ _ _ h₁ h₂ =>
    rw [show x a b hab η * (g₁ * g₂) * (x a b hab η)⁻¹ =
      (x a b hab η * g₁ * (x a b hab η)⁻¹) * (x a b hab η * g₂ * (x a b hab η)⁻¹) by group]
    exact Subgroup.mul_mem _ h₁ h₂
  | inv g _ h =>
    rw [show x a b hab η * g⁻¹ * (x a b hab η)⁻¹ = (x a b hab η * g * (x a b hab η)⁻¹)⁻¹ by
      group]
    exact Subgroup.inv_mem _ h

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.conj_ab_mem_zAll

/-- The hard case, conjugating `z_ab` by `x_ab`. -/
theorem conj_self_z_mem_zAll (third : ThirdIndex I) {a b : I} (hab : a ≠ b) (η ζ : R) {s : R}
    (hs : s ∈ J) :
    x a b hab η * zElt a b hab s ζ * (x a b hab η)⁻¹ ∈ zGen I J (fun _ _ => True) := by
  obtain ⟨m, ham, hbm⟩ := third a b
  exact conj_ab_mem_zAll hab η (z_mem_zGen_ne hab ham hbm ζ hs)

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.conj_self_z_mem_zAll

/-- Conjugation by any root element preserves `Z`. -/
theorem conj_x_mem_zAll (third : ThirdIndex I) {k l : I} (hkl : k ≠ l) (η : R)
    {g : SteinbergGroup I R} (hg : g ∈ zGen I J (fun _ _ => True)) :
    x k l hkl η * g * (x k l hkl η)⁻¹ ∈ zGen I J (fun _ _ => True) := by
  have hT : ∀ {c d : I}, zGen I J (fun i j => i = c ∧ j = d) ≤ zGen I J (fun _ _ => True) :=
    zGen_mono fun _ _ _ => trivial
  rw [zGen] at hg
  induction hg using Subgroup.closure_induction with
  | mem g hg =>
    rcases hg with ⟨c, d, hcd, s, hs, rfl⟩ | ⟨c, d, hcd, s, ζ, -, hs, rfl⟩
    · by_cases hc : c = l ∧ d = k
      · obtain ⟨hcl, hdk⟩ := hc
        subst hcl
        subst hdk
        exact hT (conj_ba_x_ab hcd hkl η hs)
      · exact xGroup_le_zGen _ (conj_x_mem_xGroup hkl hcd η hs hc)
    · by_cases hc : k = c ∧ l = d
      · obtain ⟨hkc, hld⟩ := hc
        subst hkc
        subst hld
        exact conj_self_z_mem_zAll third hkl η ζ hs
      · exact hT (conj_z_mem hcd hkl η ζ hs hc)
  | one => simp only [mul_one, mul_inv_cancel, Subgroup.one_mem]
  | mul g₁ g₂ _ _ h₁ h₂ =>
    rw [show x k l hkl η * (g₁ * g₂) * (x k l hkl η)⁻¹ =
      (x k l hkl η * g₁ * (x k l hkl η)⁻¹) * (x k l hkl η * g₂ * (x k l hkl η)⁻¹) by group]
    exact Subgroup.mul_mem _ h₁ h₂
  | inv g _ h =>
    rw [show x k l hkl η * g⁻¹ * (x k l hkl η)⁻¹ = (x k l hkl η * g * (x k l hkl η)⁻¹)⁻¹ by
      group]
    exact Subgroup.inv_mem _ h

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.conj_x_mem_zAll

/-- **`Z` is normal.** -/
theorem zAll_normal (third : ThirdIndex I) : (zGen I J (fun _ _ => True)).Normal := by
  refine ⟨fun n hn g => ?_⟩
  refine rootSpan_induction (p := fun _ _ => True)
    (Q := fun g => ∀ n ∈ zGen I J (fun _ _ => True), g * n * g⁻¹ ∈ zGen I J (fun _ _ => True))
    (fun i j hij a _ n hn => conj_x_mem_zAll third hij a hn)
    (fun n hn => by simpa only [one_mul, inv_one, mul_one] using hn)
    (fun g₁ g₂ _ _ h₁ h₂ n hn => by
      rw [show g₁ * g₂ * n * (g₁ * g₂)⁻¹ = g₁ * (g₂ * n * g₂⁻¹) * g₁⁻¹ by group]
      exact h₁ _ (h₂ n hn))
    (mem_rootSpan_true g) n hn

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.zAll_normal

theorem mem_relKer_of_x {i j : I} (hij : i ≠ j) {s : R} (hs : s ∈ J) :
    x i j hij s ∈ relKer I J := by
  refine K2Found.mem_relSt.mpr ?_
  rw [ringMap_x, Ideal.Quotient.eq_zero_iff_mem.mpr hs, x_zero]

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.mem_relKer_of_x

theorem mem_relKer_of_z {i j : I} (hij : i ≠ j) {s : R} (hs : s ∈ J) (ξ : R) :
    zElt i j hij s ξ ∈ relKer I J := by
  rw [zElt_eq_conj]
  exact (K2Found.relSt_normal I (Ideal.Quotient.mk J)).conj_mem _ (mem_relKer_of_x hij hs) _

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.mem_relKer_of_z

/-- **L–S Theorem 4.2 (Stein–Tits–Vaserstein), type A.** -/
theorem thm42 : Thm42Statement := by
  intro I _ _ third R _ J
  have hZ : Subgroup.closure (zSet I J fun _ _ => True) = zGen I J fun _ _ => True := by
    refine le_antisymm (Subgroup.closure_mono Set.subset_union_right)
      ((Subgroup.closure_le _).mpr (Set.union_subset ?_ Subgroup.subset_closure))
    rintro _ ⟨i, j, hij, s, hs, rfl⟩
    exact Subgroup.subset_closure ⟨i, j, hij, s, 0, trivial, hs, zElt_zero hij s⟩
  rw [hZ]
  refine le_antisymm ?_ ((Subgroup.closure_le _).mpr (Set.union_subset ?_ ?_))
  · haveI := zAll_normal (J := J) third
    rw [relKer, K2Found.relSt_eq_normalClosure (Ideal.Quotient.mk J) Ideal.Quotient.mk_surjective]
    refine Subgroup.normalClosure_le_normal ?_
    rintro _ ⟨i, j, hij, a, ha, rfl⟩
    exact xGroup_le_zGen _ (x_mem_xGroup hij (Ideal.Quotient.eq_zero_iff_mem.mp ha))
  · rintro _ ⟨i, j, hij, s, hs, rfl⟩
    exact mem_relKer_of_x hij hs
  · rintro _ ⟨i, j, hij, s, ξ, -, hs, rfl⟩
    exact mem_relKer_of_z hij hs ξ

#audit_axioms GroupApproximation.BooneHigmanLinear.RelGen.thm42

end GroupApproximation.BooneHigmanLinear.RelGen
