import GroupApproximation.Manuscript.SimpleKazhdanSofic.BooneHigman.Statement
import GroupApproximation.Higman.NormalClosureProduct
import GroupApproximation.Higman.RelatorSearch
import GroupApproximation.Higman.REPredNormalForm
import GroupApproximation.Computability.WordProblemRE
import GroupApproximation.Meta.AxiomGuard
import Mathlib.Computability.RE
import Mathlib.Computability.Primrec.List

/-!
# Kuznetsov's argument: a subgroup of a simple subgroup of a recursively presented group

`simple_kazhdan_sofic_group.tex`, tex l.447–450:

> the theorem of Boone and Higman that a finitely generated group has solvable
> word problem if and only if it embeds in a simple subgroup of a finitely
> presented group

This file proves the direction "embeds ⇒ solvable word problem", for any recursively presented
overgroup.

## Proof route

* `mem_normalClosure_iff_exists_conjRaw`: in a group generated by `x : ℕ → H`, the normal closure
  of the value of a raw word `v` consists of the values of the raw words `conjRaw v L`, products of
  conjugates of `v^{±1}` (from `Higman.mem_normalClosure_iff_conjProd`).
* `rePred_mem_normalClosure`: for a recursive presentation, `x₀ ∈ ⟪evalRaw v⟫` is recursively
  enumerable in `v` (Kleene normal form, then a search over `(L, n)`).
* `mem_normalClosure_iff_ne_one`: for a simple subgroup `S` and `x₀ ∈ S`, `x₀ ≠ 1`, an element
  `h ∈ S` is nontrivial if and only if `x₀ ∈ ⟪h⟫`.
* `computablePred_evalRaw_eq_one`: triviality of words landing in `S` is r.e. and co-r.e., so
  computable (Post).
* `hasSolvableWordProblem_of_simpleSubgroup`: translate words in generators of `G` into raw words of
  the presentation, and decide the word problem of `G` (`partrec_wordProblemOracle_of_computablePred`).
-/

namespace GroupApproximation
namespace SimpleKazhdanSofic
namespace BooneHigman

open Encodable Higman

/-! ## Recursively enumerable predicates -/

theorem rePred_comp {α β : Type} [Primcodable α] [Primcodable β] {p : β → Prop}
    (hp : REPred p) {f : α → β} (hf : Computable f) : REPred fun a ↦ p (f a) :=
  Partrec.comp hp hf

/-! ## Products of conjugates as raw words -/

/-- The raw word `∏ (w_i v^{±1} w_i⁻¹)` for a list of conjugators with signs. -/
def conjRaw (v : RawWord) (L : List (RawWord × Bool)) : RawWord :=
  L.flatMap fun p => p.1 ++ ((bif p.2 then v else invRaw v) ++ invRaw p.1)

theorem primrec_conjRaw :
    Primrec fun q : RawWord × List (RawWord × Bool) => conjRaw q.1 q.2 := by
  have hg : Primrec fun a : (RawWord × List (RawWord × Bool)) × (RawWord × Bool) =>
      a.2.1 ++ ((bif a.2.2 then a.1.1 else invRaw a.1.1) ++ invRaw a.2.1) :=
    Primrec.list_append.comp (Primrec.fst.comp Primrec.snd)
      (Primrec.list_append.comp
        (Primrec.cond (Primrec.snd.comp Primrec.snd) (Primrec.fst.comp Primrec.fst)
          (primrec_invRaw.comp (Primrec.fst.comp Primrec.fst)))
        (primrec_invRaw.comp (Primrec.fst.comp Primrec.snd)))
  exact (Primrec.list_flatMap
    (g := fun (q : RawWord × List (RawWord × Bool)) (p : RawWord × Bool) =>
      p.1 ++ ((bif p.2 then q.1 else invRaw q.1) ++ invRaw p.1))
    Primrec.snd hg).of_eq fun _ => rfl

section Group

variable {H : Type} [Group H]

theorem evalRaw_conjRaw_cons (x : ℕ → H) (v w : RawWord) (b : Bool)
    (L : List (RawWord × Bool)) :
    evalRaw x (conjRaw v ((w, b) :: L)) =
      evalRaw x w * (if b then evalRaw x v else (evalRaw x v)⁻¹) * (evalRaw x w)⁻¹ *
        evalRaw x (conjRaw v L) := by
  cases b <;> simp [conjRaw, List.flatMap_cons, mul_assoc]

theorem evalRaw_conjRaw_mem (x : ℕ → H) (v : RawWord) (L : List (RawWord × Bool)) :
    evalRaw x (conjRaw v L) ∈ Subgroup.normalClosure ({evalRaw x v} : Set H) := by
  induction L with
  | nil => exact Subgroup.one_mem _
  | cons p L ih =>
    obtain ⟨w, b⟩ := p
    rw [evalRaw_conjRaw_cons]
    refine Subgroup.mul_mem _ ?_ ih
    have hv : evalRaw x v ∈ Subgroup.normalClosure ({evalRaw x v} : Set H) :=
      Subgroup.subset_normalClosure (Set.mem_singleton _)
    have hb : (if b then evalRaw x v else (evalRaw x v)⁻¹) ∈
        Subgroup.normalClosure ({evalRaw x v} : Set H) := by
      cases b
      · exact Subgroup.inv_mem _ hv
      · exact hv
    exact Subgroup.Normal.conj_mem Subgroup.normalClosure_normal _ hb _

theorem exists_conjRaw_of_conjProd (x : ℕ → H) (hspan : Subgroup.closure (Set.range x) = ⊤)
    (v : RawWord) :
    ∀ l : List (H × H), (∀ p ∈ l, p.2 ∈ ({evalRaw x v, (evalRaw x v)⁻¹} : Set H)) →
      ∃ L : List (RawWord × Bool), evalRaw x (conjRaw v L) = conjProd l := by
  intro l
  induction l with
  | nil => exact fun _ => ⟨[], rfl⟩
  | cons p l ih =>
    intro hl
    obtain ⟨c, d⟩ := p
    obtain ⟨L, hL⟩ := ih fun q hq => hl q (List.mem_cons.mpr (Or.inr hq))
    obtain ⟨w, hw⟩ := (spans_iff_forall_exists_evalRaw x).mp hspan c
    have hd : d = evalRaw x v ∨ d = (evalRaw x v)⁻¹ :=
      hl (c, d) (List.mem_cons.mpr (Or.inl rfl))
    rcases hd with rfl | rfl
    · exact ⟨(w, true) :: L, by simp [evalRaw_conjRaw_cons, hL, hw]⟩
    · exact ⟨(w, false) :: L, by simp [evalRaw_conjRaw_cons, hL, hw]⟩

theorem normalClosure_singleton_eq_pair (h : H) :
    Subgroup.normalClosure ({h} : Set H) = Subgroup.normalClosure ({h, h⁻¹} : Set H) := by
  refine le_antisymm (Subgroup.normalClosure_mono ?_) (Subgroup.normalClosure_le_normal ?_)
  · exact Set.singleton_subset_iff.mpr (Set.mem_insert _ _)
  · rintro y (rfl | rfl)
    · exact Subgroup.subset_normalClosure (Set.mem_singleton _)
    · exact Subgroup.inv_mem _ (Subgroup.subset_normalClosure (Set.mem_singleton _))

/-- **The normal closure of a word, as raw words.** -/
theorem mem_normalClosure_iff_exists_conjRaw (x : ℕ → H)
    (hspan : Subgroup.closure (Set.range x) = ⊤) (v : RawWord) (g : H) :
    g ∈ Subgroup.normalClosure ({evalRaw x v} : Set H) ↔
      ∃ L : List (RawWord × Bool), evalRaw x (conjRaw v L) = g := by
  constructor
  · intro hg
    have hsymm : ∀ y ∈ ({evalRaw x v, (evalRaw x v)⁻¹} : Set H),
        y⁻¹ ∈ ({evalRaw x v, (evalRaw x v)⁻¹} : Set H) := by
      rintro y (rfl | rfl)
      · exact Set.mem_insert_of_mem _ (Set.mem_singleton _)
      · rw [inv_inv]
        exact Set.mem_insert _ _
    rw [normalClosure_singleton_eq_pair, mem_normalClosure_iff_conjProd hsymm] at hg
    obtain ⟨l, hl, rfl⟩ := hg
    exact exists_conjRaw_of_conjProd x hspan v l hl
  · rintro ⟨L, rfl⟩
    exact evalRaw_conjRaw_mem x v L

/-- **Kuznetsov's observation.** In a simple subgroup `S`, a nontrivial `x₀ ∈ S` lies in the normal
closure of `h ∈ S` exactly when `h ≠ 1`. -/
theorem mem_normalClosure_iff_ne_one {S : Subgroup H} [IsSimpleGroup S] {x₀ : H}
    (hx₀S : x₀ ∈ S) (hx₀ : x₀ ≠ 1) {h : H} (hS : h ∈ S) :
    x₀ ∈ Subgroup.normalClosure ({h} : Set H) ↔ h ≠ 1 := by
  constructor
  · rintro hxN rfl
    have hbot : Subgroup.normalClosure ({1} : Set H) = ⊥ :=
      Subgroup.normalClosure_eq_bot_iff.mpr fun _ hy => hy
    rw [hbot, Subgroup.mem_bot] at hxN
    exact hx₀ hxN
  · intro hne
    have hN : ((Subgroup.normalClosure ({h} : Set H)).comap S.subtype).Normal :=
      Subgroup.Normal.comap Subgroup.normalClosure_normal S.subtype
    rcases IsSimpleGroup.eq_bot_or_eq_top_of_normal _ hN with hbot | htop
    · exfalso
      have hmem : (⟨h, hS⟩ : S) ∈ (Subgroup.normalClosure ({h} : Set H)).comap S.subtype :=
        Subgroup.mem_comap.mpr (Subgroup.subset_normalClosure (Set.mem_singleton h))
      rw [hbot, Subgroup.mem_bot] at hmem
      exact hne (congrArg Subtype.val hmem)
    · have hmem : (⟨x₀, hx₀S⟩ : S) ∈ (Subgroup.normalClosure ({h} : Set H)).comap S.subtype := by
        rw [htop]
        exact Subgroup.mem_top _
      exact Subgroup.mem_comap.mp hmem

end Group

/-! ## Recursive enumerability of normal closures -/

section Presentation

variable {H : Type} [Group H]

/-- For a recursive presentation, membership of a fixed element in the normal closure of a word is
recursively enumerable. -/
theorem rePred_mem_normalClosure (rp : RecursivePresentation H) (a : RawWord) :
    REPred fun v : RawWord =>
      evalRaw rp.gen a ∈ Subgroup.normalClosure ({evalRaw rp.gen v} : Set H) := by
  have hF : Primrec fun q : RawWord × List (RawWord × Bool) => invRaw a ++ conjRaw q.1 q.2 :=
    Primrec.list_append.comp (Primrec.const _) primrec_conjRaw
  have hq : REPred fun q : RawWord × List (RawWord × Bool) =>
      evalRaw rp.gen (invRaw a ++ conjRaw q.1 q.2) = 1 :=
    rePred_comp rp.re hF.to_comp
  obtain ⟨f, hf, hspec⟩ := exists_primrec_of_rePred hq
  have hg : Computable₂ fun (v : RawWord) (b : List (RawWord × Bool) × ℕ) => f (v, b.1) b.2 :=
    Primrec.to_comp
      (hf.comp (Primrec.pair Primrec.fst (Primrec.fst.comp Primrec.snd))
        (Primrec.snd.comp Primrec.snd))
  refine (WordProblemRE.rePred_exists_eq_true hg).of_eq fun v => ?_
  rw [mem_normalClosure_iff_exists_conjRaw rp.gen rp.spans v]
  constructor
  · rintro ⟨⟨L, n⟩, hn⟩
    refine ⟨L, ?_⟩
    have h1 : evalRaw rp.gen (invRaw a ++ conjRaw v L) = 1 := (hspec (v, L)).2 ⟨n, hn⟩
    rw [evalRaw_append, evalRaw_invRaw] at h1
    exact (inv_mul_eq_one.mp h1).symm
  · rintro ⟨L, hL⟩
    obtain ⟨n, hn⟩ := (hspec (v, L)).1 (by
      show evalRaw rp.gen (invRaw a ++ conjRaw v L) = 1
      rw [evalRaw_append, evalRaw_invRaw, hL, inv_mul_cancel])
    exact ⟨(L, n), hn⟩

/-- **Kuznetsov's decision procedure.** Let `S` be a simple subgroup of a recursively presented
group. Triviality of raw words that are computed from inputs and land in `S` is decidable. -/
theorem computablePred_evalRaw_eq_one {α : Type} [Primcodable α]
    (rp : RecursivePresentation H) (S : Subgroup H) [IsSimpleGroup S] {τ : α → RawWord}
    (hτ : Computable τ) (hS : ∀ u, evalRaw rp.gen (τ u) ∈ S) :
    ComputablePred fun u => evalRaw rp.gen (τ u) = 1 := by
  obtain ⟨y, hy⟩ := exists_ne (1 : S)
  obtain ⟨a, ha⟩ := (spans_iff_forall_exists_evalRaw rp.gen).mp rp.spans (y : H)
  have hy' : (y : H) ≠ 1 := fun h => hy (Subtype.ext h)
  have hre : REPred fun u => evalRaw rp.gen (τ u) = 1 := rePred_comp rp.re hτ
  have hco : REPred fun u => ¬ evalRaw rp.gen (τ u) = 1 :=
    (rePred_comp (rePred_mem_normalClosure rp a) hτ).of_eq fun u => by
      rw [ha]
      exact mem_normalClosure_iff_ne_one y.2 hy' (hS u)
  exact ComputablePred.computable_iff_re_compl_re'.mpr ⟨hre, hco⟩

end Presentation

/-! ## Deciding the word problem -/

section Oracle

variable {Γ : Type} [Group Γ] {ι : Type} [Primcodable ι]

variable (ι) in
/-- The answer on a code: `1` on codes of words accepted by `d`, `0` otherwise. -/
def wordAnswer (d : List (ι × Bool) → Bool) (n : ℕ) : ℕ :=
  cond (Option.casesOn (decode n : Option (List (ι × Bool))) false d) 1 0

theorem computable_wordAnswer {d : List (ι × Bool) → Bool} (hd : Computable d) :
    Computable (wordAnswer ι d) :=
  (Computable.cond
    (Computable.option_casesOn Computable.decode (Computable.const false)
      (hd.comp Computable.snd).to₂)
    (Computable.const 1) (Computable.const 0)).of_eq fun _ => rfl

theorem wordProblemOracle_eq_wordAnswer (s : ι → Γ) (d : List (ι × Bool) → Bool)
    (hd : ∀ w, d w = true ↔ wordValue s w = 1) :
    wordProblemOracle s = fun n => Part.some (wordAnswer ι d n) := by
  funext n
  unfold wordProblemOracle wordAnswer
  congr 1
  cases hn : (decode n : Option (List (ι × Bool))) with
  | none =>
    rw [if_neg (by rintro ⟨w, hw, -⟩; cases hw)]
    rfl
  | some w =>
    by_cases hw : wordValue s w = 1
    · rw [if_pos ⟨w, rfl, hw⟩]
      simp [(hd w).2 hw]
    · rw [if_neg (by rintro ⟨w', hw', hv⟩; cases Option.some_injective _ hw'; exact hw hv)]
      simp [Bool.eq_false_iff.2 fun h => hw ((hd w).1 h)]

/-- A decidable word problem gives a partial recursive oracle. -/
theorem partrec_wordProblemOracle_of_computablePred (s : ι → Γ)
    (hp : ComputablePred fun w : List (ι × Bool) => wordValue s w = 1) :
    Partrec (wordProblemOracle s) := by
  obtain ⟨_, hdec⟩ := hp
  rw [wordProblemOracle_eq_wordAnswer s (fun w => decide (wordValue s w = 1))
    fun _ => decide_eq_true_iff]
  exact (computable_wordAnswer hdec).partrec

end Oracle

/-! ## Translating words of `G` into raw words -/

section Translate

variable {ι : Type}

/-- A word in finitely many letters, each replaced by a raw word from `table`. -/
def translateRaw (table : ι → RawWord) (w : List (ι × Bool)) : RawWord :=
  w.flatMap fun p => bif p.2 then table p.1 else invRaw (table p.1)

theorem translateRaw_cons (table : ι → RawWord) (p : ι × Bool) (w : List (ι × Bool)) :
    translateRaw table (p :: w) =
      (bif p.2 then table p.1 else invRaw (table p.1)) ++ translateRaw table w := by
  simp [translateRaw, List.flatMap_cons]

theorem evalRaw_translateRaw {A : Type} [Group A] (x : ℕ → A) (table : ι → RawWord)
    (w : List (ι × Bool)) :
    evalRaw x (translateRaw table w) = wordValue (fun i => evalRaw x (table i)) w := by
  induction w with
  | nil => rfl
  | cons p w ih =>
    obtain ⟨i, b⟩ := p
    rw [translateRaw_cons, evalRaw_append, ih, wordValue_cons]
    cases b <;> simp

theorem primrec_translateRaw [Primcodable ι] [Finite ι] (table : ι → RawWord) :
    Primrec (translateRaw table) := by
  have hg : Primrec fun a : List (ι × Bool) × (ι × Bool) =>
      bif a.2.2 then table a.2.1 else invRaw (table a.2.1) :=
    Primrec.cond (Primrec.snd.comp Primrec.snd)
      ((Primrec.dom_finite table).comp (Primrec.fst.comp Primrec.snd))
      (primrec_invRaw.comp ((Primrec.dom_finite table).comp (Primrec.fst.comp Primrec.snd)))
  exact (Primrec.list_flatMap
    (g := fun (_ : List (ι × Bool)) (p : ι × Bool) =>
      bif p.2 then table p.1 else invRaw (table p.1))
    Primrec.id hg).of_eq fun _ => rfl

end Translate

/-! ## The endpoint of this file -/

/-- **Kuznetsov.** A finitely generated subgroup of a simple subgroup of a recursively presented
group has solvable word problem. -/
theorem hasSolvableWordProblem_of_simpleSubgroup {G H : Type} [Group G] [Group H]
    (hG : Group.FG G) (rp : RecursivePresentation H) (S : Subgroup H) [IsSimpleGroup S]
    (φ : G →* S) (hφ : Function.Injective φ) : HasSolvableWordProblem G := by
  obtain ⟨n, t, ht⟩ := exists_fin_generators G hG
  have htab : ∀ i : Fin n, ∃ w : RawWord, evalRaw rp.gen w = (φ (t i) : H) := fun i =>
    (spans_iff_forall_exists_evalRaw rp.gen).mp rp.spans _
  choose table htable using htab
  have hval : ∀ w, evalRaw rp.gen (translateRaw table w) = (φ (wordValue t w) : H) := by
    intro w
    rw [evalRaw_translateRaw]
    refine Eq.trans ?_ (wordValue_map t (S.subtype.comp φ) w)
    exact congrArg (fun f => wordValue f w) (funext htable)
  have hmem : ∀ w, evalRaw rp.gen (translateRaw table w) ∈ S := fun w => by
    rw [hval]
    exact (φ (wordValue t w)).2
  have hiff : ∀ w, evalRaw rp.gen (translateRaw table w) = 1 ↔ wordValue t w = 1 := fun w => by
    rw [hval]
    constructor
    · intro h1
      apply hφ
      rw [map_one]
      exact Subtype.ext h1
    · intro h1
      simp [h1]
  have hp : ComputablePred fun w : List (Fin n × Bool) => wordValue t w = 1 :=
    (computablePred_evalRaw_eq_one rp S (primrec_translateRaw table).to_comp hmem).of_eq hiff
  exact ⟨Fin n, inferInstance, inferInstance, t, ht, partrec_wordProblemOracle_of_computablePred t hp⟩

#audit_axioms GroupApproximation.SimpleKazhdanSofic.BooneHigman.mem_normalClosure_iff_exists_conjRaw
#audit_axioms GroupApproximation.SimpleKazhdanSofic.BooneHigman.mem_normalClosure_iff_ne_one
#audit_axioms GroupApproximation.SimpleKazhdanSofic.BooneHigman.computablePred_evalRaw_eq_one
#audit_axioms GroupApproximation.SimpleKazhdanSofic.BooneHigman.partrec_wordProblemOracle_of_computablePred
#audit_axioms GroupApproximation.SimpleKazhdanSofic.BooneHigman.hasSolvableWordProblem_of_simpleSubgroup

end BooneHigman
end SimpleKazhdanSofic
end GroupApproximation
