import GroupApproximation.GGT.VanKampen.CombMap
import GroupApproximation.GGT.VanKampen.DiscDiagram
import GroupApproximation.GGT.VanKampen.CombMapStars
import GroupApproximation.GGT.VanKampen.SurgeryMap
import GroupApproximation.GGT.KazhdanHypGirthEightVKInterface

/-!
# Rooted paths and face-boundary homotopy

This module gives the path vocabulary used by the girth-eight Cayley-label
construction without importing the higher-level girth-eight primitives.  A
path is an inductive list of oriented darts with typed endpoints.  The
homotopy relation is generated by insertion or erasure of an inner-face
boundary and by immediate edge backtracking.

The exact planar completeness assertion is exposed as
`RootedPathsFaceComplete`, the name consumed by the girth-eight interface.
`FaceDeletionStep` gives the local induction data: it names the inner region
deleted by a surgery, supplies the lower-rank common path, and supplies the
two elementary path moves to that path.  The induction theorem uses
`Surgery.MapCollapse.replaceGRegion_planar` to retain planarity of the
deleted region.  The elementary model below uses the canonical face boundary
of the committed six-dart one-triangle map.
-/

namespace GroupApproximation
namespace GGT
namespace GirthEightPrimitives2

open GroupApproximation.GGT.VanKampen
open GroupApproximation.GGT.GirthEightVKInterface
open GroupApproximation.KazhdanHyp

universe u w v

/-! ## Typed dart paths -/

/-- A directed edge path in the one-skeleton of a combinatorial map. -/
inductive DartPath (M : CombMap.{u}) : M.Vertex → M.Vertex → Type u
  | nil (vertex : M.Vertex) : DartPath M vertex vertex
  | cons (dart : M.Dart) {finish : M.Vertex}
      (rest : DartPath M (M.vertexOf (M.alpha dart)) finish) :
      DartPath M (M.vertexOf dart) finish

namespace DartPath

variable {M : CombMap.{u}}

/-- Concatenate two typed dart paths. -/
def append {x y z : M.Vertex} :
    DartPath M x y → DartPath M y z → DartPath M x z
  | .nil _, q => q
  | .cons d rest, q => .cons d (rest.append q)

/-- The one-edge path in the direction of a dart. -/
def single (d : M.Dart) :
    DartPath M (M.vertexOf d) (M.vertexOf (M.alpha d)) :=
  .cons d (.nil _)

/-- The ordered darts traversed by a typed path. -/
def darts {x y : M.Vertex} : DartPath M x y → List M.Dart
  | .nil _ => []
  | .cons d rest => d :: rest.darts

@[simp]
theorem darts_append {x y z : M.Vertex}
    (p : DartPath M x y) (q : DartPath M y z) :
    (p.append q).darts = p.darts ++ q.darts := by
  induction p with
  | nil => rfl
  | cons d rest ih => simp [append, darts, ih]

@[simp]
theorem darts_single (d : M.Dart) : (single d).darts = [d] :=
  rfl

end DartPath

/-! ## Root choices and elementary face moves -/

/-- A chosen path from one root vertex to every vertex of a connected map. -/
structure RootedPathSystem (M : CombMap.{u}) where
  /-- The common initial vertex. -/
  root : M.Vertex
  /-- The selected path from the root to a target vertex. -/
  pathTo : ∀ vertex, DartPath M root vertex

/-- Inserting or erasing a complete inner-face boundary, or an immediate
edge backtrack, is the elementary planar path move.  The relation is on dart
words because the endpoint typing is supplied by the surrounding paths. -/
inductive InnerFaceWordHomotopy
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    (Delta : DiscDiagram.{u, w, v} W) :
    List Delta.toCombMap.Dart → List Delta.toCombMap.Dart → Prop
  | refl (word) : InnerFaceWordHomotopy Delta word word
  | erase (face : Delta.toCombMap.Face) (hface : face ≠ Delta.outerFace)
      (before after : List Delta.toCombMap.Dart) :
      InnerFaceWordHomotopy Delta
        (before ++ (Delta.faceBoundary face).darts ++ after) (before ++ after)
  | eraseBacktrack (dart : Delta.toCombMap.Dart)
      (before after : List Delta.toCombMap.Dart) :
      InnerFaceWordHomotopy Delta
        (before ++ dart :: Delta.toCombMap.alpha dart :: after) (before ++ after)
  | symm {a b} : InnerFaceWordHomotopy Delta a b →
      InnerFaceWordHomotopy Delta b a
  | trans {a b c} : InnerFaceWordHomotopy Delta a b →
      InnerFaceWordHomotopy Delta b c → InnerFaceWordHomotopy Delta a c

namespace InnerFaceWordHomotopy

variable {G : Type u} [Group G] {Lambda : Type w}
  {W : Set (List (GGT.RelLetter G Lambda))}
  {Delta : DiscDiagram.{u, w, v} W}

/-- Every word is homotopic to itself. -/
theorem refl_word (word : List Delta.toCombMap.Dart) :
    InnerFaceWordHomotopy Delta word word :=
  .refl word

/-- Elementary face erasure can be reversed to insertion. -/
theorem insert_innerFace
    (face : Delta.toCombMap.Face) (hface : face ≠ Delta.outerFace)
    (before after : List Delta.toCombMap.Dart) :
    InnerFaceWordHomotopy Delta
      (before ++ after)
      (before ++ (Delta.faceBoundary face).darts ++ after) :=
  .symm (.erase face hface before after)

/-- Homotopy is an equivalence relation. -/
theorem equivalence : Equivalence (@InnerFaceWordHomotopy G _ Lambda _ Delta) := by
  refine ⟨refl_word, ?_, ?_⟩
  · intro a b h
    exact .symm h
  · intro a b c hab hbc
    exact .trans hab hbc

end InnerFaceWordHomotopy

/-! ## Single deletion moves -/

/-- One face-boundary erasure or edge backtrack exposed by a deletion step. -/
inductive ElementaryPathMove
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    (Delta : DiscDiagram.{u, w, v} W) :
    List Delta.toCombMap.Dart → List Delta.toCombMap.Dart → Prop
  | faceErase (face : Delta.toCombMap.Face) (hface : face ≠ Delta.outerFace)
      (before after : List Delta.toCombMap.Dart) :
      ElementaryPathMove Delta
        (before ++ (Delta.faceBoundary face).darts ++ after)
        (before ++ after)
  | backtrackErase (dart : Delta.toCombMap.Dart)
      (before after : List Delta.toCombMap.Dart) :
      ElementaryPathMove Delta
        (before ++ dart :: Delta.toCombMap.alpha dart :: after)
        (before ++ after)

namespace ElementaryPathMove

variable {G : Type u} [Group G] {Lambda : Type w}
  {W : Set (List (GGT.RelLetter G Lambda))}
  {Delta : DiscDiagram.{u, w, v} W}

/-- Every single deletion move is an allowed inner-face word homotopy. -/
theorem toHomotopy {a b : List Delta.toCombMap.Dart}
    (h : ElementaryPathMove Delta a b) :
    InnerFaceWordHomotopy Delta a b := by
  cases h with
  | faceErase face hface before after =>
      exact InnerFaceWordHomotopy.erase face hface before after
  | backtrackErase dart before after =>
      exact InnerFaceWordHomotopy.eraseBacktrack dart before after

end ElementaryPathMove

/-! ## The exact consumer proposition -/

/-- Two rooted edge paths to the same vertex differ by inner-face boundary
insertions/erasures and immediate backtracks.  This is the exact proposition
expected by the girth-eight path-integral consumer. -/
abbrev RootedPathsFaceComplete
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    (Delta : DiscDiagram.{u, w, v} W)
    (R : RootedPathSystem Delta.toCombMap) : Prop :=
  ∀ (vertex : Delta.toCombMap.Vertex)
    (p q : DartPath Delta.toCombMap R.root vertex),
    InnerFaceWordHomotopy Delta p.darts q.darts

/-! ## The surgery induction interface -/

/-- One planar face-deletion step for a pair of rooted paths.  The selected
faces are inner faces, `region` says that they form a disc, and `common` is
the path left after deleting a face adjacent to one of the two paths.  The
single elementary move is the boundary insertion or erasure used to lift
the induction result back to the original diagram. -/
structure FaceDeletionStep
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    (Delta : DiscDiagram.{u, w, v} W)
    (R : RootedPathSystem Delta.toCombMap) where
  /-- The number of enclosed faces used by the induction. -/
  rank : ∀ (vertex : Delta.toCombMap.Vertex),
    DartPath Delta.toCombMap R.root vertex → ℕ
  /-- Delete a nonempty inner disc and expose a lower-rank common path. -/
  delete : ∀ (vertex : Delta.toCombMap.Vertex)
    (p q : DartPath Delta.toCombMap R.root vertex), p ≠ q →
    ∃ (faces : Finset Delta.toCombMap.Face)
      (region : VanKampen.Surgery.MapCollapse.IsDiscRegion
        Delta.toCombMap faces)
      (common : DartPath Delta.toCombMap R.root vertex),
      (∀ f, f ∈ faces → f ≠ Delta.outerFace) ∧
      region.toBoundaryCycle.cycle ≠ [] ∧
      ElementaryPathMove Delta p.darts common.darts ∧
      rank vertex common < rank vertex p

namespace FaceDeletionStep

variable {G : Type u} [Group G] {Lambda : Type w}
  {W : Set (List (GGT.RelLetter G Lambda))}
  {Delta : DiscDiagram.{u, w, v} W}
  {R : RootedPathSystem Delta.toCombMap}

/-- The map obtained by deleting the selected inner region is planar. -/
theorem replacement_planar
    (S : FaceDeletionStep Delta R)
    (vertex : Delta.toCombMap.Vertex)
    (p q : DartPath Delta.toCombMap R.root vertex) (hpq : p ≠ q) :
    ∃ (faces : Finset Delta.toCombMap.Face)
      (region : VanKampen.Surgery.MapCollapse.IsDiscRegion
        Delta.toCombMap faces),
      (VanKampen.Surgery.MapCollapse.replaceGRegion
        Delta.toCombMap faces region).IsPlanar := by
  obtain ⟨faces, region, common, _hinner, _hcycle, _hp, _hrp⟩ :=
    S.delete vertex p q hpq
  exact ⟨faces, region,
    VanKampen.Surgery.MapCollapse.replaceGRegion_planar
      Delta.toCombMap faces region Delta.planar⟩

end FaceDeletionStep

/-! ## The one-face deletion certificate -/

/-- The local topological certificate used by the planar path induction.  The
selected region is one inner face, and its map-collapse boundary is required
to be the canonical face boundary.  The equality is important: it is what
turns the map deletion into the `faceErase` move on the original dart word.

`Surgery.MapCollapse.IsDiscRegion` intentionally stores connectedness and
Euler preservation rather than pretending that they follow from a bare
finite set of faces.  This is therefore the exact small certificate needed
from the planar face-deletion lemma. -/
structure SingleFaceDiscRegionCertificate
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    (Delta : DiscDiagram.{u, w, v} W) where
  face : Delta.toCombMap.Face
  inner : face ≠ Delta.outerFace
  region : VanKampen.Surgery.MapCollapse.IsDiscRegion
    Delta.toCombMap {face}
  boundary_eq : region.toBoundaryCycle.cycle =
    (Delta.faceBoundary face).darts

/-- A singleton face certificate is exactly a valid elementary deletion move.
The theorem is kept separate from the path induction so the topological
producer can be replaced without changing the algebraic consumer. -/
theorem SingleFaceDiscRegionCertificate.face_move
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    {Delta : DiscDiagram.{u, w, v} W}
    (C : SingleFaceDiscRegionCertificate Delta)
    (before after : List Delta.toCombMap.Dart) :
    ElementaryPathMove Delta
      (before ++ C.region.toBoundaryCycle.cycle ++ after)
      (before ++ after) := by
  rw [C.boundary_eq]
  exact .faceErase C.face C.inner before after

/-! ## Induction with the narrowed topological input -/

/-- The path-deletion plan required by the strong induction, with the
`IsDiscRegion` witness narrowed to a single adjacent inner face. -/
structure SingleFaceDeletionPlan
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    (Delta : DiscDiagram.{u, w, v} W)
    (R : RootedPathSystem Delta.toCombMap) where
  rank : ∀ (vertex : Delta.toCombMap.Vertex),
    DartPath Delta.toCombMap R.root vertex → ℕ
  delete : ∀ (vertex : Delta.toCombMap.Vertex)
    (p q : DartPath Delta.toCombMap R.root vertex), p ≠ q →
    ∃ (C : SingleFaceDiscRegionCertificate Delta)
      (common : DartPath Delta.toCombMap R.root vertex),
      ∃ (before after : List Delta.toCombMap.Dart),
        p.darts = before ++ C.region.toBoundaryCycle.cycle ++ after ∧
        common.darts = before ++ after ∧
      rank vertex common < rank vertex p

/-- A one-face deletion plan is the general `FaceDeletionStep` consumed by
`rootedPathsFaceComplete_of_faceDeletionStep`. -/
def SingleFaceDeletionPlan.toFaceDeletionStep
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    {Delta : DiscDiagram.{u, w, v} W}
    {R : RootedPathSystem Delta.toCombMap}
    (P : SingleFaceDeletionPlan Delta R) : FaceDeletionStep Delta R where
  rank := P.rank
  delete vertex p q hpq := by
    obtain ⟨C, common, before, after, hp, hc, hlt⟩ :=
      P.delete vertex p q hpq
    refine ⟨{C.face}, C.region, common, ?_, ?_, ?_, hlt⟩
    · intro f hf
      have hf' : f = C.face := by simpa using hf
      subst f
      exact C.inner
    · simpa [C.boundary_eq] using C.region.toBoundaryCycle.cycle_nonempty
    · rw [hp, hc]
      exact C.face_move before after

/-- A face-deletion implementation supplies the local induction data needed
by `RootedPathsFaceComplete`. -/
structure FaceDeletionCompletenessWitness
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    (Delta : DiscDiagram.{u, w, v} W)
    (R : RootedPathSystem Delta.toCombMap) where
  /-- The lower-rank face-deletion step. -/
  step : FaceDeletionStep Delta R

/-- Strong induction on the enclosed-face rank gives the path homotopy. -/
theorem rootedPathsFaceComplete_of_faceDeletionStep
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    (Delta : DiscDiagram.{u, w, v} W)
    (R : RootedPathSystem Delta.toCombMap)
    (S : FaceDeletionStep Delta R) :
    RootedPathsFaceComplete Delta R := by
  intro vertex p q
  generalize htotal : S.rank vertex p + S.rank vertex q = total
  induction total using Nat.strong_induction_on generalizing vertex p q with
  | h total ih =>
      by_cases hpq : p = q
      · subst q
        exact InnerFaceWordHomotopy.refl p.darts
      · obtain ⟨_faces, _region, common, _hinner, _hcycle, hp, hpc⟩ :=
          S.delete vertex p q hpq
        have hpc_lt : S.rank vertex common + S.rank vertex q < total := by
          rw [← htotal]
          omega
        have hpc' := ih (S.rank vertex common + S.rank vertex q)
          hpc_lt vertex common q rfl
        exact (ElementaryPathMove.toHomotopy hp).trans
          hpc'

/-- The strong induction closes once the one-face planar deletion plan is
available. -/
theorem rootedPathsFaceComplete_of_singleFaceDeletionPlan
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    (Delta : DiscDiagram.{u, w, v} W)
    (R : RootedPathSystem Delta.toCombMap)
    (P : SingleFaceDeletionPlan Delta R) :
    RootedPathsFaceComplete Delta R :=
  rootedPathsFaceComplete_of_faceDeletionStep Delta R
    P.toFaceDeletionStep

/-- The clean interface turns a face-deletion witness into the exact named
path-completeness proposition. -/
theorem rootedPathsFaceComplete_of_faceDeletion
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    (Delta : DiscDiagram.{u, w, v} W)
    (R : RootedPathSystem Delta.toCombMap)
    (H : FaceDeletionCompletenessWitness Delta R) :
    RootedPathsFaceComplete Delta R :=
  rootedPathsFaceComplete_of_faceDeletionStep Delta R H.step

/-! ## Path integration for the clean girth-eight closure -/

section Cayley

variable {Generator TriangleIndex : Type}
  [Fintype Generator] [DecidableEq Generator]
  [Fintype TriangleIndex] [DecidableEq TriangleIndex]
  {T : TriangleIndex → TriangularHodgeLayer.Triangle Generator}

/-- Evaluate a diagram path in the triangularly presented Cayley group. -/
def cayleyPathValue
    (Delta : VanKampen.DiscDiagram (triangleRelatorWords T))
    {x y : Delta.toCombMap.Vertex} (p : DartPath Delta.toCombMap x y) :
    TriangularHodgeLayer.Presented T :=
  (p.darts.map fun d ↦ presentedLetterValue T (Delta.label d)).prod

omit [Fintype Generator] [DecidableEq TriangleIndex] in
theorem cayleyPathValue_append
    (Delta : VanKampen.DiscDiagram (triangleRelatorWords T))
    {x y z : Delta.toCombMap.Vertex}
    (p : DartPath Delta.toCombMap x y) (q : DartPath Delta.toCombMap y z) :
    cayleyPathValue Delta (p.append q) =
      cayleyPathValue Delta p * cayleyPathValue Delta q := by
  simp [cayleyPathValue, List.map_append, List.prod_append]

omit [Fintype Generator] [DecidableEq TriangleIndex] in
theorem cayleyPathValue_single
    (Delta : VanKampen.DiscDiagram (triangleRelatorWords T))
    (d : Delta.toCombMap.Dart) :
    cayleyPathValue Delta (DartPath.single d) =
      presentedLetterValue T (Delta.label d) := by
  simp [cayleyPathValue]

omit [Fintype Generator] [DecidableEq TriangleIndex] in
theorem presentedLetterValue_inv
    (a : GGT.RelLetter (FreeGroup Generator) PEmpty) :
    presentedLetterValue T (HullSC.RelWord.inv a) =
      (presentedLetterValue T a)⁻¹ := by
  cases a with
  | base x => simp [presentedLetterValue, HullSC.RelWord.inv]
  | comp i _ => exact PEmpty.elim i

omit [Fintype Generator] [DecidableEq TriangleIndex] in
theorem pathValue_erase_backtrack
    (Delta : VanKampen.DiscDiagram (triangleRelatorWords T))
    (d : Delta.toCombMap.Dart)
    (before after : List Delta.toCombMap.Dart) :
    ((before ++ d :: Delta.toCombMap.alpha d :: after).map (fun e ↦
      presentedLetterValue T (Delta.label e))).prod =
      ((before ++ after).map (fun e ↦
        presentedLetterValue T (Delta.label e))).prod := by
  have halpha : presentedLetterValue T
      (Delta.label (Delta.toCombMap.alpha d)) =
        (presentedLetterValue T (Delta.label d))⁻¹ := by
    rw [Delta.label_alpha]
    exact presentedLetterValue_inv (T := T) (Delta.label d)
  simp only [List.map_append, List.map_cons, List.prod_append,
    List.prod_cons]
  rw [halpha]
  simp

theorem innerFace_presentedValue_eq_one
    (Delta : VanKampen.DiscDiagram (triangleRelatorWords T))
    (R : RelatorOnly T Delta) (f : Delta.toCombMap.Face)
    (hf : f ≠ Delta.outerFace) :
    ((Delta.faceWord f).map (fun d ↦ presentedLetterValue T d)).prod = 1 := by
  obtain ⟨j, hj⟩ := R.exists_faceWord_eq f hf
  rw [hj, triangleRelatorWord, List.map_map]
  have hletter : ∀ u : TriangularHodgeLayer.SignedGenerator Generator,
      presentedLetterValue T
          (signedFreeRelLetter u :
            GGT.RelLetter (FreeGroup Generator) PEmpty) =
        FoxBoundary.letterValue (TriangularHodgeLayer.generator T) u := by
    intro u
    rcases u with ⟨generator, positive⟩
    cases positive with
    | false =>
        change PresentedGroup.mk
            (TriangularHodgeLayer.relators T : Set (FreeGroup Generator))
            ((FreeGroup.of generator)⁻¹) =
          (PresentedGroup.of generator)⁻¹
        rw [map_inv]
        rfl
    | true =>
        change PresentedGroup.mk
            (TriangularHodgeLayer.relators T : Set (FreeGroup Generator))
            (FreeGroup.of generator) = PresentedGroup.of generator
        rfl
  have hmap : (TriangularHodgeLayer.letters (T j)).map (fun u ↦
      presentedLetterValue T
        (signedFreeRelLetter u :
          GGT.RelLetter (FreeGroup Generator) PEmpty)) =
      (TriangularHodgeLayer.letters (T j)).map
        (FoxBoundary.letterValue (TriangularHodgeLayer.generator T)) := by
    induction TriangularHodgeLayer.letters (T j) with
    | nil => rfl
    | cons u us ih =>
        rw [List.map_cons, List.map_cons, hletter u, ih]
  calc
    (List.map ((fun d ↦ presentedLetterValue T d) ∘ signedFreeRelLetter)
        (TriangularHodgeLayer.letters (T j))).prod =
        ((TriangularHodgeLayer.letters (T j)).map (fun u ↦
          presentedLetterValue T
            (signedFreeRelLetter u :
              GGT.RelLetter (FreeGroup Generator) PEmpty))).prod := by
      apply congrArg List.prod
      induction TriangularHodgeLayer.letters (T j) with
      | nil => rfl
      | cons u us ih =>
          simp only [List.map_cons, Function.comp_apply]
          exact congrArg (List.cons
            (presentedLetterValue T (signedFreeRelLetter u))) ih
    _ = ((TriangularHodgeLayer.letters (T j)).map
        (FoxBoundary.letterValue (TriangularHodgeLayer.generator T))).prod := by
      rw [hmap]
    _ = 1 := TriangularHodgeLayer.wordValue_triangle_eq_one T j

theorem pathValue_erase_innerFace
    (Delta : VanKampen.DiscDiagram (triangleRelatorWords T))
    (R : RelatorOnly T Delta) (f : Delta.toCombMap.Face)
    (hf : f ≠ Delta.outerFace)
    (before after : List Delta.toCombMap.Dart) :
    ((before ++ (Delta.faceBoundary f).darts ++ after).map (fun d ↦
      presentedLetterValue T (Delta.label d))).prod =
      ((before ++ after).map (fun d ↦
        presentedLetterValue T (Delta.label d))).prod := by
  have hface : ((Delta.faceBoundary f).darts.map
      (fun d ↦ presentedLetterValue T (Delta.label d))).prod = 1 := by
    have hmap : (Delta.faceBoundary f).darts.map
        (fun d ↦ presentedLetterValue T (Delta.label d)) =
        (Delta.faceWord f).map (presentedLetterValue T) := by
      rw [DiscDiagram.faceWord]
      induction (Delta.faceBoundary f).darts with
      | nil => rfl
      | cons d ds ih => simp only [List.map_cons, ih]
    rw [hmap]
    exact innerFace_presentedValue_eq_one Delta R f hf
  simp only [List.map_append, List.prod_append]
  rw [hface]
  simp

theorem innerFaceWordHomotopy_value_eq
    (Delta : VanKampen.DiscDiagram (triangleRelatorWords T))
    (R : RelatorOnly T Delta) {a b : List Delta.toCombMap.Dart}
    (h : InnerFaceWordHomotopy Delta a b) :
    (a.map (fun d ↦ presentedLetterValue T (Delta.label d))).prod =
      (b.map (fun d ↦ presentedLetterValue T (Delta.label d))).prod := by
  induction h with
  | refl => rfl
  | erase f hf before after =>
      exact pathValue_erase_innerFace Delta R f hf before after
  | eraseBacktrack d before after =>
      exact pathValue_erase_backtrack Delta d before after
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Path integration is well-defined once the rooted path completeness
certificate has been supplied. -/
abbrev PathIntegralWellDefined
    (Delta : VanKampen.DiscDiagram (triangleRelatorWords T))
    (R : RootedPathSystem Delta.toCombMap) : Prop :=
  ∀ (v : Delta.toCombMap.Vertex)
    (p q : DartPath Delta.toCombMap R.root v),
    cayleyPathValue Delta p = cayleyPathValue Delta q

theorem pathIntegralWellDefined_of_faceComplete
    (Delta : VanKampen.DiscDiagram (triangleRelatorWords T))
    (relatorOnly : RelatorOnly T Delta)
    (R : RootedPathSystem Delta.toCombMap)
    (hcomplete : RootedPathsFaceComplete Delta R) :
    PathIntegralWellDefined Delta R := by
  intro v p q
  exact innerFaceWordHomotopy_value_eq Delta relatorOnly
    (hcomplete v p q)

/-- Construct the Cayley vertex labelling used by successive stars from the
rooted path certificate. -/
noncomputable def cayleyVertexLabelling_of_faceComplete
    (Delta : VanKampen.DiscDiagram (triangleRelatorWords T))
    (relatorOnly : RelatorOnly T Delta)
    (R : RootedPathSystem Delta.toCombMap)
    (hcomplete : RootedPathsFaceComplete Delta R) :
    CayleyVertexLabelling T Delta where
  value v := cayleyPathValue Delta (R.pathTo v)
  edge d := by
    let extended := (R.pathTo (Delta.toCombMap.vertexOf d)).append
      (DartPath.single d)
    calc
      cayleyPathValue Delta
          (R.pathTo (Delta.toCombMap.vertexOf (Delta.toCombMap.alpha d))) =
          cayleyPathValue Delta extended := by
        exact (pathIntegralWellDefined_of_faceComplete Delta relatorOnly R
          hcomplete _ extended (R.pathTo _)).symm
      _ = cayleyPathValue Delta (R.pathTo
            (Delta.toCombMap.vertexOf d)) *
          presentedLetterValue T (Delta.label d) := by
        rw [cayleyPathValue_append, cayleyPathValue_single]

end Cayley

/-! ## One-triangle model checks -/

noncomputable section OneTriangleModel

local instance oneTriangleDartDecidableEq : DecidableEq OneTriangleDart :=
  Classical.decEq _

local instance oneTriangleCombMapDartDecidableEq :
    DecidableEq oneTriangleCombMap.Dart :=
  Classical.decEq _

/-- The canonical ordered boundary of the one-triangle model is the closed
orbit list supplied by the Van Kampen boundary API. -/
theorem oneTriangle_faceBoundary_model (d : OneTriangleDart) :
    (FaceBoundary.based oneTriangleCombMap d).darts =
      closedOrbitList oneTriangleCombMap.facePerm d :=
  rfl

/-- The elementary insertion/erasure constructor is inhabited on the
one-triangle face boundary.  This tests the exact face-move relation on the
six-dart one-triangle disc skeleton. -/
theorem oneTriangle_faceMove_model
    {G : Type u} [Group G] {Lambda : Type w}
    {W : Set (List (GGT.RelLetter G Lambda))}
    (Delta : DiscDiagram.{u, w, v} W)
    (face : Delta.toCombMap.Face) (hface : face ≠ Delta.outerFace)
    (before after : List Delta.toCombMap.Dart) :
    InnerFaceWordHomotopy Delta
      (before ++ (Delta.faceBoundary face).darts ++ after)
      (before ++ after) :=
  .erase face hface before after

end OneTriangleModel

end GirthEightPrimitives2
end GGT
end GroupApproximation
