import GroupApproximation.Manuscript.SimpleKazhdanSofic.RingGeneration
import GroupApproximation.Manuscript.SimpleKazhdanSofic.MinimalDenseOrbits
import GroupApproximation.Manuscript.SimpleKazhdanSofic.FiniteModelsForwardOrbit
import GroupApproximation.Meta.AxiomGuard
import Mathlib.Topology.Perfect

/-!
# Proof of `thm:main`: the dynamical and ring-theoretic opening sentences

`simple_kazhdan_sofic_group.tex`, section `sec:main` ("Proof of Theorem~\ref{thm:main}"), tex l.359–377:

> Let $\Z$ act on $X$ by powers of $T$, where $(Tx)_t=x_{t+1}$, and write $u=u_1$, so
> $ufu^{-1}=f\circ T^{-1}$. Minimality and infiniteness imply that $X$ has no isolated points and $T$
> has no periodic points, so $X$ is a Cantor set and the action is topologically free. The ring
> $R=\LC(X,\F_2)\rtimes_T\Z$ is generated by $S=\{1,u,u^{-1}\}\cup\{e_a:a\in A\}$, where
> $e_a=e_{\{x:x_0=a\}}$, since products of the translates $u^je_au^{-j}$ are the indicators of the
> cylinders [...]
>
> Fix $x\in X$ and $\ell\ge0$. By minimality the forward orbit of $x$ is dense, so every word of $X$
> occurs in $x_{[0,\infty)}$, and $x_{[-\ell,\ell]}$ recurs at arbitrarily large positions. [...]
> so $y_\ell$ has the same words of length $2\ell+1$ as $X$.

This file uses only modules already compiled from the library root, and proves these sentences
for every infinite minimal subshift `X = S.carrier` over a finite discrete alphabet.

* `covariance`: `u f u⁻¹ = f ∘ T⁻¹`;
* `perfectSpace_subshift`: `X` has no isolated points;
* `zpow_apply_ne_self_of_dense`: `T` has no periodic points;
* `isCantorSpace_subshift`: `X` is a nonempty compact Hausdorff totally disconnected perfect space;
* `subring_closure_printedGenerators_eq_top`: `S = {1, u, u⁻¹} ∪ {e_a}` generates `R`;
* `unit_zpow_mul_letterIndicator_mul_inv`: the translate `u^j e_a u^{-j}` is `[x_{-j} = a]`;
* `prod_coordIndicator_apply`: products of translates are the cylinder indicators;
* `forwardOrbit_dense`, `exists_recurrence_segment`, `exists_periodic_sameWords_carrier`: the periodic
  sequences `y_ℓ` with the same words of length `2ℓ + 1` as `X`;
* `PrintedMainProofOpening`, `printedMainProofOpening`: the closed bundle of these sentences.

The least period `N_ℓ`, the maps `φ_ℓ` and the matrix units (tex l.377–391) are not treated here.
-/

namespace GroupApproximation.Full.SK05

open GroupApproximation.SimpleKazhdanSofic
open GroupApproximation.ClopenCrossedProduct
open GroupApproximation.WordGraph
open SymbolicDynamics.FullShift

section Periodic

variable {Y : Type*} [TopologicalSpace Y] (T : Y ≃ₜ Y)

/-- A fixed point of `T^j` is a fixed point of every `T^{jq}`. -/
theorem periodicPt_zpow_mul {j : ℤ} {y : Y} (hy : (T ^ j) y = y) (q : ℤ) :
    (T ^ (j * q)) y = y := by
  rw [zpow_mul]
  induction q using Int.induction_on with
  | zero => rw [zpow_zero, Homeomorph.one_apply]
  | succ i ih => rw [zpow_add_one, Homeomorph.mul_apply, hy, ih]
  | pred i ih =>
    have hinv : (T ^ j)⁻¹ y = y := by
      calc (T ^ j)⁻¹ y = (T ^ j)⁻¹ ((T ^ j) y) := by rw [hy]
        _ = y := by rw [Homeomorph.inv_apply, Homeomorph.symm_apply_apply]
    rw [zpow_sub_one, Homeomorph.mul_apply, hinv, ih]

/-- On a periodic point of period `j`, `T^i` only depends on `i % j`. -/
theorem periodicPt_zpow_emod {j : ℤ} {y : Y} (hy : (T ^ j) y = y) (i : ℤ) :
    (T ^ i) y = (T ^ (i % j)) y := by
  conv_lhs => rw [← Int.emod_add_mul_ediv i j]
  rw [zpow_add, Homeomorph.mul_apply, periodicPt_zpow_mul T hy]

/-- **No periodic points** (tex l.360–361): if every orbit of `T` is dense and `Y` is an infinite
Hausdorff space, then `T^j y ≠ y` for `j ≠ 0`. A periodic orbit is finite, hence closed. -/
theorem zpow_apply_ne_self_of_dense [T2Space Y] [Infinite Y]
    (hmin : ∀ y : Y, Dense (Set.range fun j : ℤ => (T ^ j) y)) {j : ℤ} (hj : j ≠ 0) (y : Y) :
    (T ^ j) y ≠ y := by
  intro hy
  classical
  obtain ⟨F, hFdef⟩ : ∃ F : Finset Y,
      F = (Finset.range j.natAbs).image fun n : ℕ => (T ^ (n : ℤ)) y := ⟨_, rfl⟩
  have hsub : Set.range (fun i : ℤ => (T ^ i) y) ⊆ (F : Set Y) := by
    rintro _ ⟨i, rfl⟩
    show (T ^ i) y ∈ (F : Set Y)
    rw [periodicPt_zpow_emod T hy i, hFdef]
    have h0 : 0 ≤ i % j := Int.emod_nonneg i hj
    have h1 : i % j < |j| := Int.emod_lt_abs i hj
    rw [Int.abs_eq_natAbs] at h1
    obtain ⟨r, hr⟩ : ∃ r : ℤ, r = i % j := ⟨_, rfl⟩
    rw [← hr] at h0 h1 ⊢
    obtain ⟨n, hn⟩ : ∃ n : ℕ, (n : ℤ) = r := ⟨r.toNat, Int.toNat_of_nonneg h0⟩
    refine Finset.mem_coe.2 (Finset.mem_image.2 ⟨n, Finset.mem_range.2 (by omega), ?_⟩)
    show (T ^ ((n : ℕ) : ℤ)) y = (T ^ r) y
    rw [hn]
  have huniv : (Set.univ : Set Y) ⊆ F := by
    rw [← (hmin y).closure_eq]
    exact closure_minimal hsub F.finite_toSet.isClosed
  exact absurd (F.finite_toSet.subset huniv) Set.infinite_univ

end Periodic

section Subshift

variable {A : Type} [TopologicalSpace A] [DiscreteTopology A] [Finite A]

/-- **`u f u⁻¹ = f ∘ T⁻¹`** (tex l.360), for the shift `T` of a subshift. -/
theorem covariance (S : Subshift A ℤ) (f : LocallyConstant S.carrier (ZMod 2)) :
    (unit (subshiftHomeo S) (ZMod 2) : R S) * coeff (subshiftHomeo S) (ZMod 2) f *
        (((unit (subshiftHomeo S) (ZMod 2))⁻¹ : (R S)ˣ) : R S) =
      coeff (subshiftHomeo S) (ZMod 2)
        (LocallyConstant.comap ⟨⇑(subshiftHomeo S).symm, (subshiftHomeo S).symm.continuous⟩ f) :=
  unit_mul_coeff_mul_inv (subshiftHomeo S) (ZMod 2) f

/-- A subshift over a finite discrete alphabet is compact. -/
theorem compactSpace_subshift (S : Subshift A ℤ) : CompactSpace S.carrier :=
  isCompact_iff_compactSpace.mp S.isClosed.isCompact

/-- **No isolated points** (tex l.360–361): an isolated point with a dense orbit would make every
point isolated, so the compact space `X` would be discrete, hence finite. -/
theorem perfectSpace_subshift (S : Subshift A ℤ) (hinf : Infinite S.carrier) (hmin : IsMinimal S) :
    PerfectSpace S.carrier := by
  refine ⟨preperfect_iff_nhds.2 fun x _ U hU => ?_⟩
  by_contra hno
  have hsub : U ⊆ {x} := by
    intro y hy
    rw [Set.mem_singleton_iff]
    by_contra hne
    exact hno ⟨y, Set.mem_inter hy (Set.mem_univ y), hne⟩
  obtain ⟨t, htU, htopen, hxt⟩ := mem_nhds_iff.1 hU
  have heq : t = {x} := Set.Subset.antisymm (htU.trans hsub) (Set.singleton_subset_iff.2 hxt)
  have hsingle : IsOpen ({x} : Set S.carrier) := by
    rw [← heq]
    exact htopen
  haveI : DiscreteTopology S.carrier := discreteTopology_iff_isOpen_singleton.2 fun y => by
    obtain ⟨z, ⟨j, hjz⟩, hzx⟩ :=
      (minimalSubshift_dense_orbits S hmin y).exists_mem_open hsingle (Set.singleton_nonempty x)
    have hxy : (subshiftHomeo S ^ j) y = x := hjz.trans (Set.mem_singleton_iff.1 hzx)
    have hpre : (⇑(subshiftHomeo S ^ j)) ⁻¹' {x} = {y} := by
      ext w
      rw [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_singleton_iff, ← hxy]
      exact (subshiftHomeo S ^ j).injective.eq_iff
    rw [← hpre]
    exact hsingle.preimage (subshiftHomeo S ^ j).continuous
  haveI := compactSpace_subshift S
  haveI := hinf
  haveI : Finite S.carrier := finite_of_compact_of_discrete
  exact not_finite S.carrier

/-- **`T` has no periodic points** (tex l.361): for an infinite minimal subshift and `j ≠ 0`,
`T^j x ≠ x`. -/
theorem subshiftHomeo_zpow_apply_ne_self (S : Subshift A ℤ) (hinf : Infinite S.carrier)
    (hmin : IsMinimal S) {j : ℤ} (hj : j ≠ 0) (x : S.carrier) : (subshiftHomeo S ^ j) x ≠ x := by
  haveI := hinf
  exact zpow_apply_ne_self_of_dense (subshiftHomeo S) (minimalSubshift_dense_orbits S hmin) hj x

/-- **`X` is a Cantor set** (tex l.361–362): an infinite minimal subshift over a finite alphabet is
a nonempty compact Hausdorff totally disconnected space without isolated points. -/
theorem isCantorSpace_subshift (S : Subshift A ℤ) (hinf : Infinite S.carrier) (hmin : IsMinimal S) :
    CompactSpace S.carrier ∧ T2Space S.carrier ∧ TotallyDisconnectedSpace S.carrier ∧
      PerfectSpace S.carrier ∧ Nonempty S.carrier :=
  ⟨compactSpace_subshift S, inferInstance, inferInstance, perfectSpace_subshift S hinf hmin,
    (Set.infinite_coe_iff.1 hinf).nonempty.to_subtype⟩

variable [DecidableEq A]

/-- **`R` is generated by `S = {1, u, u⁻¹} ∪ {e_a : a ∈ A}`** (tex l.362–364). -/
theorem subring_closure_printedGenerators_eq_top (S : Subshift A ℤ) :
    Subring.closure (insert (1 : R S) (ringGenerators S)) = ⊤ :=
  eq_top_iff.2 ((subring_closure_eq_top S).symm.le.trans
    (Subring.closure_mono (Set.subset_insert (1 : R S) (ringGenerators S))))

/-- **The translates `u^j e_a u^{-j}`** (tex l.365): `u^j e_a u^{-j} = [x_{-j} = a]`. -/
theorem unit_zpow_mul_letterIndicator_mul_inv (S : Subshift A ℤ) (j : ℤ) (a : A) :
    ((unit (subshiftHomeo S) (ZMod 2) ^ j : (R S)ˣ) : R S) *
        coeff (subshiftHomeo S) (ZMod 2) (letterIndicator S a) *
        (((unit (subshiftHomeo S) (ZMod 2) ^ j)⁻¹ : (R S)ˣ) : R S) =
      coeff (subshiftHomeo S) (ZMod 2) (coordIndicator S (-j) a) :=
  (unit_zpow_mul_coeff_mul_inv (subshiftHomeo S) (ZMod 2) j (letterIndicator S a)).trans
    (congrArg (coeff (subshiftHomeo S) (ZMod 2)) (comap_letterIndicator S j a))

/-- **Products of translates are cylinder indicators** (tex l.365–367): the product of the coordinate
indicators `[x_t = w_t]`, `t ∈ I`, is the indicator of the cylinder `{x : x_t = w_t for t ∈ I}`. -/
theorem prod_coordIndicator_apply (S : Subshift A ℤ) (I : Finset ℤ) (w : ℤ → A) (x : S.carrier) :
    (∏ t ∈ I, coordIndicator S t (w t)) x = if ∀ t ∈ I, x.1 t = w t then 1 else 0 := by
  induction I using Finset.induction_on with
  | empty =>
      have hall : ∀ t ∈ (∅ : Finset ℤ), x.1 t = w t := fun t ht => absurd ht (Finset.notMem_empty t)
      rw [Finset.prod_empty, LocallyConstant.one_apply, if_pos hall]
  | insert i s hi ih =>
      rw [Finset.prod_insert hi, LocallyConstant.mul_apply, ih, coordIndicator_apply]
      by_cases h1 : x.1 i = w i
      · by_cases h2 : ∀ t ∈ s, x.1 t = w t
        · have hall : ∀ t ∈ insert i s, x.1 t = w t := by
            intro t ht
            rcases Finset.mem_insert.1 ht with hti | ht'
            · rw [hti]
              exact h1
            · exact h2 t ht'
          rw [if_pos h1, if_pos h2, if_pos hall, one_mul]
        · have hnot : ¬ ∀ t ∈ insert i s, x.1 t = w t := fun h =>
            h2 fun t ht => h t (Finset.mem_insert_of_mem ht)
          rw [if_neg h2, if_neg hnot, mul_zero]
      · have hnot : ¬ ∀ t ∈ insert i s, x.1 t = w t := fun h =>
          h1 (h i (Finset.mem_insert_self i s))
        rw [if_neg h1, if_neg hnot, zero_mul]

end Subshift

section Words

variable {A : Type} [TopologicalSpace A] [DiscreteTopology A] [Finite A]

/-- **The forward orbit is dense** (tex l.369–370): by minimality, every point of `X` is a limit of
forward shifts of `x`. -/
theorem forwardOrbit_dense (S : Subshift A ℤ) (hmin : IsMinimal S) {x : ℤ → A}
    (hx : x ∈ S.carrier) :
    S.carrier ⊆ closure (Set.range fun n : ℕ => shift (n : ℤ) x) :=
  subset_closure_forwardOrbit_of_minimal S.isClosed S.mapsTo hmin hx

/-- **Recurrence and a segment with every word** (tex l.370–373): the word `x_{[0,2ℓ)}` occurs again
at a position `m ≥ m₀`, and every word of length `2ℓ + 1` of `X` starts in `[0, m)`. -/
theorem exists_recurrence_segment (S : Subshift A ℤ) (hmin : IsMinimal S) {x : ℤ → A}
    (hx : x ∈ S.carrier) (ℓ m₀ : ℕ) :
    ∃ m : ℕ, m₀ ≤ m ∧ 2 * ℓ + 1 ≤ m ∧ word x 0 (2 * ℓ) = word x m (2 * ℓ) ∧
      ∀ u ∈ language S.carrier (2 * ℓ + 1),
        ∃ i : ℕ, i + (2 * ℓ + 1) ≤ m ∧ word x i (2 * ℓ + 1) = u :=
  exists_occurrences_of_mem S.isClosed S.mapsTo hmin hx ℓ m₀

/-- **The periodic sequences `y_ℓ`** (tex l.373–377): for every `ℓ` and `m₀` there is a periodic
sequence `y : ℤ/m → A` of period `m ≥ m₀` with the same words of length `2ℓ + 1` as `X`. -/
theorem exists_periodic_sameWords_carrier (S : Subshift A ℤ) (hinf : Infinite S.carrier)
    (hmin : IsMinimal S) (ℓ m₀ : ℕ) :
    ∃ (m : ℕ) (_ : NeZero m) (y : ZMod m → A), m₀ ≤ m ∧
      (∀ n : ZMod m,
        (fun j : Fin (2 * ℓ + 1) => y (n + (j : ℕ))) ∈ language S.carrier (2 * ℓ + 1)) ∧
      ∀ u ∈ language S.carrier (2 * ℓ + 1),
        ∃ n : ZMod m, (fun j : Fin (2 * ℓ + 1) => y (n + (j : ℕ))) = u :=
  exists_periodic_sameWords S.isClosed S.mapsTo (Set.infinite_coe_iff.1 hinf).nonempty hmin ℓ m₀

end Words

/-- The opening sentences of the proof of `thm:main` (tex l.359–377), as one closed statement: for
every infinite minimal subshift `X` over a finite alphabet, `X` is a Cantor set, `T` has no periodic
points, `S = {1, u, u⁻¹} ∪ {e_a}` generates `R`, and for every `ℓ` there are periodic sequences of
arbitrarily large period with the same words of length `2ℓ + 1` as `X`. -/
def PrintedMainProofOpening : Prop :=
  ∀ (A : Type) [TopologicalSpace A] [DiscreteTopology A] [DecidableEq A] [Finite A]
    (S : Subshift A ℤ), Infinite S.carrier → IsMinimal S →
    (CompactSpace S.carrier ∧ T2Space S.carrier ∧ TotallyDisconnectedSpace S.carrier ∧
      PerfectSpace S.carrier ∧ Nonempty S.carrier) ∧
    (∀ j : ℤ, j ≠ 0 → ∀ x : S.carrier, (subshiftHomeo S ^ j) x ≠ x) ∧
    Subring.closure (insert (1 : R S) (ringGenerators S)) = ⊤ ∧
    ∀ ℓ m₀ : ℕ, ∃ (m : ℕ) (_ : NeZero m) (y : ZMod m → A), m₀ ≤ m ∧
      (∀ n : ZMod m,
        (fun j : Fin (2 * ℓ + 1) => y (n + (j : ℕ))) ∈ language S.carrier (2 * ℓ + 1)) ∧
      ∀ u ∈ language S.carrier (2 * ℓ + 1),
        ∃ n : ZMod m, (fun j : Fin (2 * ℓ + 1) => y (n + (j : ℕ))) = u

/-- **The opening of the proof of `thm:main`** (tex l.359–377), unconditionally. -/
theorem printedMainProofOpening : PrintedMainProofOpening := by
  intro _ _ _ _ _ S hinf hmin
  exact ⟨isCantorSpace_subshift S hinf hmin,
    fun _ hj x => subshiftHomeo_zpow_apply_ne_self S hinf hmin hj x,
    subring_closure_printedGenerators_eq_top S, exists_periodic_sameWords_carrier S hinf hmin⟩

end GroupApproximation.Full.SK05

/-! ### Axiom audit -/

#audit_axioms GroupApproximation.Full.SK05.perfectSpace_subshift
#audit_axioms GroupApproximation.Full.SK05.zpow_apply_ne_self_of_dense
#audit_axioms GroupApproximation.Full.SK05.prod_coordIndicator_apply
#audit_closed_axioms GroupApproximation.Full.SK05.printedMainProofOpening
