import GroupApproximation.Manuscript.NonMFNotes.Full.TWWSchafhauser.ExtensionAbsorbLocalCone

/-!
# The orthogonal inductive choice of the local compressions

Lane `TWWSch3c2-C3c`, work order `WO-TWWSch-3c2-C3c`, second part. Sources: G. A. Elliott and
D. Kucerovsky, Pacific J. Math. 198 (2001), proof of Thm. 6 (the inductive choice of the `vₙ`)
and Lemma 7; G. G. Kasparov, J. Operator Theory 4 (1980), §7; J. Gabe, J. Funct. Anal. 271
(2016), Thm. 2.1. Manuscript label: `non_mf_group_notes.tex`, `thm:fixed-radical-membership`
(the absorption step).

The Elliott–Kucerovsky diagonal argument chooses compact local compressions `vₙ` one at a time,
the `n`-th one almost orthogonal to a finite set of compacts produced from the earlier ones
(`vₘ` itself and `ℓ(s) vₘ`, `ℓ(s)⋆ vₘ` for `s` in a finite set). This file makes the recursion
explicit:

* `exists_orthogonal_choice`: the abstract dependent choice. Given a property `Q`, a step
  relation `P n C v` that can always be met by some `v ∈ Q` past any finite `C ⊆ Q`, and a
  generator `gen n v` of new constraints (preserving `Q`), there are `vₙ ∈ Q` and finite `Cₙ`
  with `P n Cₙ vₙ` and `gen m vₘ ⊆ Cₙ` for `m < n`;
* `exists_diagonal_compressions`: its instance for `IsLocallyCompressible` (lane C2): compact
  `vₙ` compressing `ℓ` onto `s ↦ kₙ⋆ σ(s) kₙ` on `Gₙ` up to `δₙ`, almost orthogonal to the
  compacts `Dₙ`, to the earlier `vₘ`, and to `ℓ(s) vₘ`, `ℓ(s)⋆ vₘ` for `s ∈ Hₘ`.
-/

noncomputable section

namespace GroupApproximation.Full.TWWSchafhauser

open GroupApproximation.HilbertModule

/-! ## Abstract orthogonal choice -/

/-- One step of the orthogonal choice: a `v ∈ Q` meeting `P n C` past the constraint set `C`
(Elliott–Kucerovsky 2001, proof of Thm. 6; `non_mf_group_notes.tex`,
`thm:fixed-radical-membership`). -/
def orthPick {X : Type*} (Q : X → Prop) (P : ℕ → Finset X → X → Prop)
    (h : ∀ (n : ℕ) (C : Finset X), (∀ c ∈ C, Q c) → ∃ v, Q v ∧ P n C v) (n : ℕ)
    (C : {C : Finset X // ∀ c ∈ C, Q c}) : X :=
  (h n C.1 C.2).choose

/-- The step choice meets its specification (`non_mf_group_notes.tex`,
`thm:fixed-radical-membership`). -/
theorem orthPick_spec {X : Type*} (Q : X → Prop) (P : ℕ → Finset X → X → Prop)
    (h : ∀ (n : ℕ) (C : Finset X), (∀ c ∈ C, Q c) → ∃ v, Q v ∧ P n C v) (n : ℕ)
    (C : {C : Finset X // ∀ c ∈ C, Q c}) :
    Q (orthPick Q P h n C) ∧ P n C.1 (orthPick Q P h n C) :=
  (h n C.1 C.2).choose_spec

/-- The constraint set after step `n`: the old constraints together with those generated by the
new choice (`non_mf_group_notes.tex`, `thm:fixed-radical-membership`). -/
def orthStep {X : Type*} [DecidableEq X] (Q : X → Prop) (P : ℕ → Finset X → X → Prop)
    (gen : ℕ → X → Finset X) (hgen : ∀ (n : ℕ) (v : X), Q v → ∀ c ∈ gen n v, Q c)
    (h : ∀ (n : ℕ) (C : Finset X), (∀ c ∈ C, Q c) → ∃ v, Q v ∧ P n C v) (n : ℕ)
    (C : {C : Finset X // ∀ c ∈ C, Q c}) : {C : Finset X // ∀ c ∈ C, Q c} :=
  ⟨C.1 ∪ gen n (orthPick Q P h n C), fun c hc => by
    rcases Finset.mem_union.mp hc with hc | hc
    · exact C.2 c hc
    · exact hgen n _ (orthPick_spec Q P h n C).1 c hc⟩

/-- The constraint sets of the orthogonal choice, by recursion (`non_mf_group_notes.tex`,
`thm:fixed-radical-membership`). -/
def orthChoiceState {X : Type*} [DecidableEq X] (Q : X → Prop) (P : ℕ → Finset X → X → Prop)
    (gen : ℕ → X → Finset X) (hgen : ∀ (n : ℕ) (v : X), Q v → ∀ c ∈ gen n v, Q c)
    (h : ∀ (n : ℕ) (C : Finset X), (∀ c ∈ C, Q c) → ∃ v, Q v ∧ P n C v) :
    ℕ → {C : Finset X // ∀ c ∈ C, Q c}
  | 0 => ⟨∅, fun c hc => absurd hc (Finset.notMem_empty c)⟩
  | n + 1 => orthStep Q P gen hgen h n (orthChoiceState Q P gen hgen h n)

/-- The recursion equation of the constraint sets (`non_mf_group_notes.tex`,
`thm:fixed-radical-membership`). -/
theorem orthChoiceState_succ {X : Type*} [DecidableEq X] (Q : X → Prop)
    (P : ℕ → Finset X → X → Prop) (gen : ℕ → X → Finset X)
    (hgen : ∀ (n : ℕ) (v : X), Q v → ∀ c ∈ gen n v, Q c)
    (h : ∀ (n : ℕ) (C : Finset X), (∀ c ∈ C, Q c) → ∃ v, Q v ∧ P n C v) (n : ℕ) :
    (orthChoiceState Q P gen hgen h (n + 1)).1 = (orthChoiceState Q P gen hgen h n).1 ∪
      gen n (orthPick Q P h n (orthChoiceState Q P gen hgen h n)) :=
  rfl

/-- The constraint sets grow (`non_mf_group_notes.tex`, `thm:fixed-radical-membership`). -/
theorem orthChoiceState_mono {X : Type*} [DecidableEq X] (Q : X → Prop)
    (P : ℕ → Finset X → X → Prop) (gen : ℕ → X → Finset X)
    (hgen : ∀ (n : ℕ) (v : X), Q v → ∀ c ∈ gen n v, Q c)
    (h : ∀ (n : ℕ) (C : Finset X), (∀ c ∈ C, Q c) → ∃ v, Q v ∧ P n C v) {m n : ℕ}
    (hmn : m ≤ n) :
    (orthChoiceState Q P gen hgen h m).1 ⊆ (orthChoiceState Q P gen hgen h n).1 := by
  obtain ⟨d, rfl⟩ := Nat.exists_eq_add_of_le hmn
  clear hmn
  induction d with
  | zero => exact Finset.Subset.refl _
  | succ d ih =>
    rw [← Nat.add_assoc, orthChoiceState_succ Q P gen hgen h (m + d)]
    exact Finset.Subset.trans ih Finset.subset_union_left

/-- **Orthogonal inductive choice** (Elliott–Kucerovsky 2001, proof of Thm. 6;
`non_mf_group_notes.tex`, `thm:fixed-radical-membership`): if every finite constraint set `C ⊆ Q`
admits a `v ∈ Q` with `P n C v`, and the generated constraints `gen n v` stay in `Q`, then there
are `vₙ ∈ Q` and finite `Cₙ` with `P n Cₙ vₙ`, such that `gen m vₘ ⊆ Cₙ` whenever `m < n`. -/
theorem exists_orthogonal_choice {X : Type*} (Q : X → Prop) (P : ℕ → Finset X → X → Prop)
    (gen : ℕ → X → Finset X) (hgen : ∀ (n : ℕ) (v : X), Q v → ∀ c ∈ gen n v, Q c)
    (h : ∀ (n : ℕ) (C : Finset X), (∀ c ∈ C, Q c) → ∃ v, Q v ∧ P n C v) :
    ∃ (v : ℕ → X) (C : ℕ → Finset X), (∀ n, Q (v n)) ∧ (∀ n, P n (C n) (v n)) ∧
      ∀ m n : ℕ, m < n → gen m (v m) ⊆ C n := by
  classical
  refine ⟨fun n => orthPick Q P h n (orthChoiceState Q P gen hgen h n),
    fun n => (orthChoiceState Q P gen hgen h n).1,
    fun n => (orthPick_spec Q P h n (orthChoiceState Q P gen hgen h n)).1,
    fun n => (orthPick_spec Q P h n (orthChoiceState Q P gen hgen h n)).2, ?_⟩
  intro m n hmn
  have h1 : gen m (orthPick Q P h m (orthChoiceState Q P gen hgen h m)) ⊆
      (orthChoiceState Q P gen hgen h (m + 1)).1 := by
    rw [orthChoiceState_succ Q P gen hgen h m]
    exact Finset.subset_union_right
  exact Finset.Subset.trans h1 (orthChoiceState_mono Q P gen hgen h (Nat.succ_le_of_lt hmn))

/-! ## The diagonal compressions -/

variable {J : Type} [NonUnitalCStarAlgebra J] [PartialOrder J] [StarOrderedRing J]
variable {S : Type*}

/-- **The diagonal compressions** (Elliott–Kucerovsky 2001, proof of Thm. 6 with Lemma 7;
`non_mf_group_notes.tex`, `thm:fixed-radical-membership`): if each `s ↦ kₙ⋆ σ(s) kₙ` is locally
compressible into `ℓ`, there are compact `vₙ` with `‖vₙ⋆ ℓ(s) vₙ − kₙ⋆ σ(s) kₙ‖ ≤ δₙ` on `Gₙ`,
`‖c⋆ vₙ‖ ≤ δₙ` for the compacts `c ∈ Dₙ`, and, for `m < n`, `‖vₘ⋆ vₙ‖ ≤ δₙ` and
`‖vₘ⋆ ℓ(s) vₙ‖, ‖vₘ⋆ ℓ(s)⋆ vₙ‖ ≤ δₙ` for `s ∈ Hₘ`. -/
theorem exists_diagonal_compressions (ℓ σ : S → StdBdd J) (k : ℕ → StdBdd J)
    (hloc : ∀ n : ℕ, IsLocallyCompressible ℓ (fun s => star (k n) * σ s * k n))
    (G H : ℕ → Finset S) (D : ℕ → Finset (StdBdd J))
    (hD : ∀ n : ℕ, ∀ c ∈ D n, IsStdCompact c) (δ : ℕ → ℝ) (hδ : ∀ n : ℕ, 0 < δ n) :
    ∃ v : ℕ → StdBdd J, (∀ n, IsStdCompact (v n)) ∧
      (∀ n, ∀ s ∈ G n, ‖star (v n) * ℓ s * v n - star (k n) * σ s * k n‖ ≤ δ n) ∧
      (∀ n, ∀ c ∈ D n, ‖star c * v n‖ ≤ δ n) ∧
      (∀ m n : ℕ, m < n → ‖star (v m) * v n‖ ≤ δ n) ∧
      (∀ m n : ℕ, m < n → ∀ s ∈ H m, ‖star (v m) * ℓ s * v n‖ ≤ δ n) ∧
      (∀ m n : ℕ, m < n → ∀ s ∈ H m, ‖star (v m) * star (ℓ s) * v n‖ ≤ δ n) := by
  classical
  have hgen : ∀ (m : ℕ) (v : StdBdd J), IsStdCompact v → ∀ c ∈ insert v
      ((H m).image (fun s => star (ℓ s) * v) ∪ (H m).image (fun s => ℓ s * v)),
      IsStdCompact c := by
    intro m v hv c hc
    rcases Finset.mem_insert.mp hc with rfl | hc
    · exact hv
    · rcases Finset.mem_union.mp hc with hc | hc
      · obtain ⟨s, _, rfl⟩ := Finset.mem_image.mp hc
        exact hv.mul_left _
      · obtain ⟨s, _, rfl⟩ := Finset.mem_image.mp hc
        exact hv.mul_left _
  have hstep : ∀ (n : ℕ) (C : Finset (StdBdd J)), (∀ c ∈ C, IsStdCompact c) →
      ∃ v, IsStdCompact v ∧
        CompressesOn ℓ (fun s => star (k n) * σ s * k n) (G n) (C ∪ D n) (δ n) v := by
    intro n C hC
    have hCD : ∀ c ∈ C ∪ D n, IsStdCompact c := by
      intro c hc
      rcases Finset.mem_union.mp hc with hc | hc
      · exact hC c hc
      · exact hD n c hc
    obtain ⟨v, hv, hG', hC'⟩ := hloc n (G n) (C ∪ D n) hCD (δ n) (hδ n)
    exact ⟨v, hv, ⟨hv, hG', hC'⟩⟩
  obtain ⟨v, C, hQ, hP, hsub⟩ := exists_orthogonal_choice (X := StdBdd J)
    (IsStdCompact (J := J))
    (fun n C v => CompressesOn ℓ (fun s => star (k n) * σ s * k n) (G n) (C ∪ D n) (δ n) v)
    (fun m v => insert v
      ((H m).image (fun s => star (ℓ s) * v) ∪ (H m).image (fun s => ℓ s * v)))
    hgen hstep
  have hP' : ∀ n : ℕ, IsStdCompact (v n) ∧
      (∀ s ∈ G n, ‖star (v n) * ℓ s * v n - star (k n) * σ s * k n‖ ≤ δ n) ∧
      ∀ c ∈ C n ∪ D n, ‖star c * v n‖ ≤ δ n := fun n => hP n
  refine ⟨v, hQ, fun n => (hP' n).2.1,
    fun n c hc => (hP' n).2.2 c (Finset.mem_union_right _ hc), ?_, ?_, ?_⟩
  · intro m n hmn
    exact (hP' n).2.2 (v m)
      (Finset.mem_union_left _ (hsub m n hmn (Finset.mem_insert_self _ _)))
  · intro m n hmn s hs
    have h1 := (hP' n).2.2 (star (ℓ s) * v m)
      (Finset.mem_union_left _ (hsub m n hmn (Finset.mem_insert_of_mem
        (Finset.mem_union_left _ (Finset.mem_image_of_mem (fun s => star (ℓ s) * v m) hs)))))
    rwa [star_mul, star_star] at h1
  · intro m n hmn s hs
    have h1 := (hP' n).2.2 (ℓ s * v m)
      (Finset.mem_union_left _ (hsub m n hmn (Finset.mem_insert_of_mem
        (Finset.mem_union_right _ (Finset.mem_image_of_mem (fun s => ℓ s * v m) hs)))))
    rwa [star_mul] at h1

end GroupApproximation.Full.TWWSchafhauser
