import GroupApproximation.Manuscript.NonMF.GerasimovaOsinLemma45

/-!
# Gerasimova–Osin's generalized combing, Lemmas 4.6 and 4.7

Gerasimova–Osin (arXiv:1910.14524v3), §4:

> We construct the required generalized combing `C : G × G → 𝒫(G)` as follows.  Let
> `Ω = {t^{±1}} ∪ F^{±1} ∪ {h ∈ H | d̂(1,h) ≤ 5C}`.  The set `Ω` is finite as `H ↪h G`.
> For a subgraph `Δ` of `Γ(G, 𝒜)`, we denote by `V(Δ)` the set of its vertices considered
> as a subset of `G`.  Recall that `S` denotes the free subsemigroup of `G` generated by
> `tF`.  For each `g ∈ G`, we fix a geodesic path `γ_g` in `Γ(G, 𝒜)` connecting `g` to `1`
> such that (∗) for every `s ∈ S ∖ {1}`, `Lab(γ_s) = t f₁ … t fₙ`, where
> `f₁, …, fₙ ∈ F`.  Note that we can always ensure (∗) by Lemma 4.4.  Further, we define
> `C(1, g) = V(γ_g ∪ g γ_{g⁻¹}) · Ω · Ω` (20) … `C(f, g) = f C(1, f⁻¹g)` (21) …
> `ℓ(g) = |g|_𝒜`.
>
> **Lemma 4.6.** The generalized combing `C` is symmetric and `G`-equivariant.
>
> **Lemma 4.7.** Let `M = max_{u ∈ Ω²} |u|_𝒜`.  Then the growth functions associated to
> `C` and `ℓ` satisfy `γ(n) ≤ 2(n + M + 1)|Ω|²` (22) and `ρ(n) ≤ n + M` (23).

## Repository form

* `γ_g` is `goGamma`, read from `1` to `g` (its vertex set is orientation-free): the word
  `t f₁ ⋯ t fₙ` when `g` is the value of such a word with `n ≥ 1`, and a chosen geodesic word
  otherwise.  It is geodesic in both cases by Lemma 4.4.  The vertex set of `g γ_{g⁻¹}` is
  `g · V(γ_{g⁻¹})`.
* `Ω` is the finite set `goOmega`, with `5C` the radius at the Proposition 3.6 constant of
  `GOSetting`.
* Lemma 4.7 is stated with the linear bounds the assembly consumes:
  `|C(1,g) ∩ B(n)| ≤ 2(n + M + 1)|Ω|²` and `|x| ≤ |g| + M` on `C(1,g)`.

## Manuscript status

Infrastructure for `cor:regular-nonmf-algebra` (Gerasimova–Osin's Proposition 4.1).
Certifies no printed sentence on its own.
-/

namespace GroupApproximation
namespace Manuscript
namespace NonMF
namespace GerasimovaOsinWords

open GroupApproximation.GGT
open GroupApproximation.GGT.OsinComponents
open GroupApproximation.WordMetric
open Classical

universe u

section Definitions

variable {G : Type u} [Group G]

/-- **`γ_g`**, read from `1` to `g`, satisfying (∗). -/
noncomputable def goGamma (D : RelGenSet G Unit) (F : Set G) (t g : G) :
    List (RelLetter G Unit) :=
  if h : ∃ fs : List G, fs ≠ [] ∧ (∀ f ∈ fs, f ∈ F) ∧ RelLetter.listVal (altWord t fs) = g then
    altWord t (Classical.choose h)
  else Classical.choose (existsGeodesicWord D 1 g)

/-- The vertex set `V(γ)` of a word read from `1`. -/
def goVerts (γ : List (RelLetter G Unit)) : Set G :=
  {x | ∃ i : ℕ, i ≤ γ.length ∧ vertex (1 : G) γ i = x}

/-- **`Ω = {t^{±1}} ∪ F^{±1} ∪ {h ∈ H | d̂(1,h) ≤ 5C}`.** -/
noncomputable def goOmega (D : RelGenSet G Unit) (F : Finset G) (t : G) (C : ℕ)
    (hfin : (D.relBall () (5 * C)).Finite) : Finset G :=
  insert t (insert t⁻¹ (F ∪ F.image (fun f => f⁻¹) ∪ hfin.toFinset))

/-- `M = max_{u ∈ Ω²} |u|_𝒜`. -/
noncomputable def goOmegaM (D : RelGenSet G Unit) (F : Finset G) (t : G) (C : ℕ)
    (hfin : (D.relBall () (5 * C)).Finite) : ℕ :=
  (goOmega D F t C hfin ×ˢ goOmega D F t C hfin).sup
    (fun p => wordNorm D.alphabet.carrier (p.1 * p.2))

/-- **(20)**: `C(1,g) = V(γ_g ∪ g γ_{g⁻¹}) · Ω · Ω`. -/
def goCone (D : RelGenSet G Unit) (F : Finset G) (t : G) (C : ℕ)
    (hfin : (D.relBall () (5 * C)).Finite) (g : G) : Set G :=
  {x | ∃ b : G, (b ∈ goVerts (goGamma D (F : Set G) t g) ∨
      ∃ c ∈ goVerts (goGamma D (F : Set G) t g⁻¹), b = g * c) ∧
    ∃ ω₁ ∈ goOmega D F t C hfin, ∃ ω₂ ∈ goOmega D F t C hfin, x = b * ω₁ * ω₂}

/-- **(21)**: `C(f,g) = f C(1, f⁻¹g)`. -/
def goComb (D : RelGenSet G Unit) (F : Finset G) (t : G) (C : ℕ)
    (hfin : (D.relBall () (5 * C)).Finite) (x y : G) : Set G :=
  (fun z => x * z) '' goCone D F t C hfin (x⁻¹ * y)

end Definitions

section Lemma46

variable {G : Type u} [Group G] {D : RelGenSet G Unit} {F : Finset G} {t : G} {C : ℕ}
  {hfin : (D.relBall () (5 * C)).Finite}

theorem goCone_eq_image_inv (g : G) :
    goCone D F t C hfin g = (fun z => g * z) '' goCone D F t C hfin g⁻¹ := by
  ext x
  constructor
  · rintro ⟨b, hb, ω₁, hω₁, ω₂, hω₂, rfl⟩
    refine ⟨g⁻¹ * b * ω₁ * ω₂, ⟨g⁻¹ * b, ?_, ω₁, hω₁, ω₂, hω₂, rfl⟩, ?_⟩
    · rcases hb with hb | ⟨c, hc, rfl⟩
      · right
        exact ⟨b, by rwa [inv_inv], rfl⟩
      · left
        rwa [show g⁻¹ * (g * c) = c by group]
    · simp only [mul_assoc, mul_inv_cancel_left]
  · rintro ⟨y, ⟨b, hb, ω₁, hω₁, ω₂, hω₂, rfl⟩, rfl⟩
    refine ⟨g * b, ?_, ω₁, hω₁, ω₂, hω₂, ?_⟩
    · rcases hb with hb | ⟨c, hc, rfl⟩
      · right
        exact ⟨b, hb, rfl⟩
      · left
        rw [show g * (g⁻¹ * c) = c by group]
        rwa [inv_inv] at hc
    · simp only [mul_assoc]

/-- **Gerasimova–Osin, Lemma 4.6**, symmetry. -/
theorem goComb_symm (x y : G) : goComb D F t C hfin x y = goComb D F t C hfin y x := by
  unfold goComb
  rw [goCone_eq_image_inv (y⁻¹ * x), Set.image_image,
    show (y⁻¹ * x)⁻¹ = x⁻¹ * y by group]
  congr 1
  funext z
  simp only [mul_assoc, mul_inv_cancel_left]

/-- **Gerasimova–Osin, Lemma 4.6**, `G`-equivariance. -/
theorem goComb_equivariant (g x y : G) :
    goComb D F t C hfin (g * x) (g * y) = (fun z => g * z) '' goComb D F t C hfin x y := by
  unfold goComb
  rw [Set.image_image, show (g * x)⁻¹ * (g * y) = x⁻¹ * y by group]
  congr 1
  funext z
  simp only [mul_assoc]

theorem goComb_one (g : G) : goComb D F t C hfin 1 g = goCone D F t C hfin g := by
  unfold goComb
  simp only [inv_one, one_mul, Set.image_id']

end Lemma46

section Lemma47

variable {G : Type u} [Group G] {D : RelGenSet G Unit} {F : Finset G} {t : G} {C : ℕ}
  {hfin : (D.relBall () (5 * C)).Finite}

theorem goGamma_isGeodesicWord (hS : GOSetting D (F : Set G) t C) (g : G) :
    IsGeodesicWord D 1 g (goGamma D (F : Set G) t g) := by
  unfold goGamma
  split_ifs with h
  · have hspec := Classical.choose_spec h
    have hgeo := isGeodesicWord_altWord hS hspec.2.1
    rwa [hspec.2.2] at hgeo
  · exact Classical.choose_spec (existsGeodesicWord D 1 g)

/-- **(∗)**: for `s = (t f₁)⋯(t fₙ)` with `n ≥ 1`, `γ_s` is some word `t f₁' ⋯ t fₙ'`. -/
theorem exists_goGamma_eq_altWord {g : G}
    (h : ∃ fs : List G, fs ≠ [] ∧ (∀ f ∈ fs, f ∈ (F : Set G)) ∧
      RelLetter.listVal (altWord t fs) = g) :
    ∃ fs : List G, fs ≠ [] ∧ (∀ f ∈ fs, f ∈ (F : Set G)) ∧
      RelLetter.listVal (altWord t fs) = g ∧ goGamma D (F : Set G) t g = altWord t fs := by
  refine ⟨Classical.choose h, (Classical.choose_spec h).1, (Classical.choose_spec h).2.1,
    (Classical.choose_spec h).2.2, ?_⟩
  unfold goGamma
  rw [dif_pos h]

theorem wordNorm_vertex_of_isGeodesicWord {g : G} {w : List (RelLetter G Unit)}
    (hw : IsGeodesicWord D 1 g w) {i : ℕ} (hi : i ≤ w.length) :
    wordNorm D.alphabet.carrier (vertex (1 : G) w i) = i := by
  have h1 := sub_le_wordDist_vertex D hw 0 i (Nat.zero_le i) hi
  have h2 := wordDist_vertex_le D hw.1 (Nat.zero_le i) hi
  rw [vertex_zero] at h1 h2
  have e : wordDist D.alphabet.carrier 1 (vertex (1 : G) w i)
      = wordNorm D.alphabet.carrier (vertex (1 : G) w i) := by
    unfold wordDist
    rw [inv_one, one_mul]
  omega

theorem wordNorm_mul_vertex_of_isGeodesicWord_inv {g : G} {w : List (RelLetter G Unit)}
    (hw : IsGeodesicWord D 1 g⁻¹ w) {i : ℕ} (hi : i ≤ w.length) :
    wordNorm D.alphabet.carrier (g * vertex (1 : G) w i) = w.length - i := by
  have hend := hw.vertex_length_eq
  have h1 := sub_le_wordDist_vertex D hw i w.length hi le_rfl
  have h2 := wordDist_vertex_le D hw.1 hi le_rfl
  rw [hend] at h1 h2
  have e : wordDist D.alphabet.carrier (vertex (1 : G) w i) g⁻¹
      = wordNorm D.alphabet.carrier (g * vertex (1 : G) w i) := by
    rw [wordDist_comm D.alphabet.symmetricGenerating]
    unfold wordDist
    rw [inv_inv]
  omega

theorem wordNorm_le_of_isGeodesicWord {g : G} {w : List (RelLetter G Unit)}
    (hw : IsGeodesicWord D 1 g w) : w.length = wordNorm D.alphabet.carrier g := by
  rw [hw.2.2]
  unfold wordDist
  rw [inv_one, one_mul]

/-- `|b ω₁ ω₂| ≤ |b| + M` and `|b| ≤ |b ω₁ ω₂| + M`. -/
theorem wordNorm_mul_omega_le {b ω₁ ω₂ : G} (hω₁ : ω₁ ∈ goOmega D F t C hfin)
    (hω₂ : ω₂ ∈ goOmega D F t C hfin) :
    wordNorm D.alphabet.carrier (b * ω₁ * ω₂)
        ≤ wordNorm D.alphabet.carrier b + goOmegaM D F t C hfin ∧
      wordNorm D.alphabet.carrier b
        ≤ wordNorm D.alphabet.carrier (b * ω₁ * ω₂) + goOmegaM D F t C hfin := by
  have hM : wordNorm D.alphabet.carrier (ω₁ * ω₂) ≤ goOmegaM D F t C hfin := by
    unfold goOmegaM
    exact Finset.le_sup (f := fun p : G × G => wordNorm D.alphabet.carrier (p.1 * p.2))
      (b := (ω₁, ω₂)) (Finset.mem_product.mpr ⟨hω₁, hω₂⟩)
  have hS := D.alphabet.symmetricGenerating
  constructor
  · have h := wordNorm_mul_le hS b (ω₁ * ω₂)
    rw [← mul_assoc] at h
    omega
  · have h := wordNorm_mul_le hS (b * ω₁ * ω₂) (ω₁ * ω₂)⁻¹
    rw [wordNorm_inv hS, show b * ω₁ * ω₂ * (ω₁ * ω₂)⁻¹ = b by group] at h
    omega

/-- **(23)**: `|x|_𝒜 ≤ |g|_𝒜 + M` on `C(1,g)`. -/
theorem wordNorm_le_of_mem_goCone (hS : GOSetting D (F : Set G) t C) {g x : G}
    (hx : x ∈ goCone D F t C hfin g) :
    wordNorm D.alphabet.carrier x
      ≤ wordNorm D.alphabet.carrier g + goOmegaM D F t C hfin := by
  obtain ⟨b, hb, ω₁, hω₁, ω₂, hω₂, rfl⟩ := hx
  have hbx := (wordNorm_mul_omega_le (b := b) hω₁ hω₂).1
  have hbg : wordNorm D.alphabet.carrier b ≤ wordNorm D.alphabet.carrier g := by
    rcases hb with ⟨i, hi, rfl⟩ | ⟨c, ⟨i, hi, rfl⟩, rfl⟩
    · have hgeo := goGamma_isGeodesicWord hS g
      rw [wordNorm_vertex_of_isGeodesicWord hgeo hi, ← wordNorm_le_of_isGeodesicWord hgeo]
      exact hi
    · have hgeo := goGamma_isGeodesicWord hS g⁻¹
      rw [wordNorm_mul_vertex_of_isGeodesicWord_inv hgeo hi,
        wordNorm_le_of_isGeodesicWord hgeo, wordNorm_inv D.alphabet.symmetricGenerating]
      omega
  omega

/-- The finite set of candidates for `C(1,g) ∩ B(m)`: a vertex index `≤ m` on one of the
two geodesics, and two letters of `Ω`. -/
noncomputable def goGrowthImage (D : RelGenSet G Unit) (F : Finset G) (t : G) (C : ℕ)
    (hfin : (D.relBall () (5 * C)).Finite) (g : G) (m : ℕ) : Finset G :=
  ((Finset.range (m + 1) ×ˢ (Finset.univ : Finset Bool)) ×ˢ
      (goOmega D F t C hfin ×ˢ goOmega D F t C hfin)).image
    (fun p => (if p.1.2 then
        g * vertex (1 : G) (goGamma D (F : Set G) t g⁻¹)
          ((goGamma D (F : Set G) t g⁻¹).length - p.1.1)
      else vertex (1 : G) (goGamma D (F : Set G) t g) p.1.1) * p.2.1 * p.2.2)

theorem goCone_inter_ball_subset (hS : GOSetting D (F : Set G) t C) (g : G) (n : ℕ) :
    goCone D F t C hfin g ∩ {x | wordNorm D.alphabet.carrier x ≤ n}
      ⊆ (goGrowthImage D F t C hfin g (n + goOmegaM D F t C hfin) : Set G) := by
  rintro x ⟨⟨b, hb, ω₁, hω₁, ω₂, hω₂, rfl⟩, hxn⟩
  have hxn' : wordNorm D.alphabet.carrier (b * ω₁ * ω₂) ≤ n := hxn
  have hbx := (wordNorm_mul_omega_le (b := b) hω₁ hω₂).2
  rw [goGrowthImage, Finset.coe_image]
  rcases hb with ⟨i, hi, rfl⟩ | ⟨c, ⟨i, hi, rfl⟩, rfl⟩
  · have hgeo := goGamma_isGeodesicWord hS g
    rw [wordNorm_vertex_of_isGeodesicWord hgeo hi] at hbx
    refine ⟨((i, false), (ω₁, ω₂)), ?_, by simp⟩
    simp only [Finset.coe_product, Set.mem_prod, Finset.mem_coe, Finset.mem_range,
      Finset.mem_univ, and_true]
    exact ⟨by omega, hω₁, hω₂⟩
  · have hgeo := goGamma_isGeodesicWord hS g⁻¹
    rw [wordNorm_mul_vertex_of_isGeodesicWord_inv hgeo hi] at hbx
    refine ⟨(((goGamma D (F : Set G) t g⁻¹).length - i, true), (ω₁, ω₂)), ?_, ?_⟩
    · simp only [Finset.coe_product, Set.mem_prod, Finset.mem_coe, Finset.mem_range,
        Finset.mem_univ, and_true]
      exact ⟨by omega, hω₁, hω₂⟩
    · simp only [if_true]
      rw [show (goGamma D (F : Set G) t g⁻¹).length -
          ((goGamma D (F : Set G) t g⁻¹).length - i) = i by omega]

/-- **(22)**: `|C(1,g) ∩ B(n)| ≤ 2(n + M + 1)|Ω|²`, with finiteness. -/
theorem goCone_inter_ball_finite_ncard (hS : GOSetting D (F : Set G) t C) (g : G) (n : ℕ) :
    (goCone D F t C hfin g ∩ {x | wordNorm D.alphabet.carrier x ≤ n}).Finite ∧
      (goCone D F t C hfin g ∩ {x | wordNorm D.alphabet.carrier x ≤ n}).ncard
        ≤ 2 * (n + goOmegaM D F t C hfin + 1) * (goOmega D F t C hfin).card ^ 2 := by
  have hsub := goCone_inter_ball_subset (hfin := hfin) hS g n
  refine ⟨(Finset.finite_toSet _).subset hsub, ?_⟩
  calc (goCone D F t C hfin g ∩ {x | wordNorm D.alphabet.carrier x ≤ n}).ncard
      ≤ ((goGrowthImage D F t C hfin g (n + goOmegaM D F t C hfin) : Finset G) : Set G).ncard :=
        Set.ncard_le_ncard hsub (Finset.finite_toSet _)
    _ = (goGrowthImage D F t C hfin g (n + goOmegaM D F t C hfin)).card :=
        Set.ncard_coe_finset _
    _ ≤ ((Finset.range (n + goOmegaM D F t C hfin + 1) ×ˢ (Finset.univ : Finset Bool)) ×ˢ
          (goOmega D F t C hfin ×ˢ goOmega D F t C hfin)).card := Finset.card_image_le
    _ = 2 * (n + goOmegaM D F t C hfin + 1) * (goOmega D F t C hfin).card ^ 2 := by
        simp only [Finset.card_product, Finset.card_range, Finset.card_univ, Fintype.card_bool]
        ring

end Lemma47

end GerasimovaOsinWords
end NonMF
end Manuscript
end GroupApproximation

open GroupApproximation.Manuscript.NonMF.GerasimovaOsinWords

#audit_axioms goComb_symm
#audit_axioms goComb_equivariant
#audit_axioms wordNorm_le_of_mem_goCone
#audit_axioms goCone_inter_ball_finite_ncard
