import GroupApproximation.Manuscript.NonMF.AcylindricallyHyperbolic

/-!
# Hull's small cancellation theorem, and the three literature inputs it comes with

This module states, and only states, the results that
`non_mf_groups_exist.tex` cites but does not prove in the section *"A
torsion-free group with full MF radical"*.  Each is a `theorem` with a `sorry`
body carrying a `-- LITERATURE INPUT (sorry): …` marker naming the source
result, and each is stated in exactly the form the manuscript uses it.

## What is stated

* `hull_smallCancellation` — `thm:hull`, **Hull, Theorem 7.1**, in the
  finite-set formulation the manuscript records.  The manuscript's preamble
  explains the reduction: *"Given a finite set `F ⊆ G`, choose a ball in
  `Γ(G,A)` containing `F` and apply Hull's injectivity-radius formulation.  This
  gives the finite-set version recorded below."*  Only the finite-set version is
  stated, because only it is used.
* `HullQuotient.ker_normallyGenerated` — the manuscript's separate remark,
  *"inspection of Hull's construction, applied successively to `t₁, …, t_m`,
  shows that `ker q` is normally generated by `m` elements."*  It is a distinct
  literature input, not a consequence of `thm:hull`, and it is what makes the
  saturation quotient finitely presented.
* `osin_actsNonElementarily_of_isSNormal` — **Osin, Lemma 7.1**, used by the
  proof of `lem:saturation` in the form *"`N ∩ gNg⁻¹` infinite for every `g`
  implies `N` acts non-elementarily on `Γ(G,A)`"*.  The hypothesis is exactly
  the repository's `HullSuitable.IsSNormal`, whose docstring already records
  that its geometric half is this lemma of Osin's.
* `hull_exists_two_generated_suitable` — **Hull, Corollary 5.7 and Lemma 5.8**,
  used in the form *"`N` contains two elements `h₁, h₂` such that
  `N₀ = ⟨h₁,h₂⟩` is again suitable"*.

## The shape of `thm:hull`

The conclusion of Hull's theorem asserts the existence of a group, so it is
carried by a structure — `HullQuotient` — whose fields are the printed clauses
one for one, and the theorem is the `Nonempty` of that structure.  The group
structure on the target is an instance-implicit field, following
`Sofic/TorsionFreeFullMFRadical.lean`'s `DefectRoutingData`, so that the
remaining fields can be stated about it.
-/

namespace GroupApproximation
namespace Manuscript
namespace NonMF
namespace TorsionFree

open GroupApproximation.HullGeometry

universe u

/-! ## The conclusion of Hull's theorem -/

/-- **The output of `thm:hull`.**  Its fields are the printed clauses of Hull's
small cancellation theorem, one for one:

> Then there is a surjective homomorphism `q : G → Q` such that `Q` is
> acylindrically hyperbolic, `q|_F` is injective, `q(tᵢ) ∈ q(N)` for all `i`,
> and every element of finite order in `Q` is the image of an element of the
> same order in `G`.

The hypotheses of the theorem — that `G` is acylindrically hyperbolic and that
`N` is suitable with respect to `A` — are hypotheses of
`hull_smallCancellation`, not fields here, so this structure records precisely
the conclusion. -/
structure HullQuotient {G : Type u} [Group G] (N : Subgroup G) {m : ℕ}
    (t : Fin m → G) (F : Set G) where
  /-- The target group `Q`. -/
  Q : Type u
  /-- Its group structure. -/
  [group : Group Q]
  /-- The homomorphism `q : G → Q`. -/
  q : G →* Q
  /-- `q` is surjective. -/
  surjective : Function.Surjective q
  /-- `Q` is acylindrically hyperbolic. -/
  [acylindricallyHyperbolic : IsAcylindricallyHyperbolic Q]
  /-- `q|_F` is injective. -/
  injOn : Set.InjOn q F
  /-- `q(tᵢ) ∈ q(N)` for every `i`. -/
  mem_map : ∀ i : Fin m, q (t i) ∈ N.map q
  /-- Every element of finite order in `Q` is the image of an element of the
  same order in `G`. -/
  finiteOrder_lift :
    ∀ y : Q, IsOfFinOrder y → ∃ g : G, q g = y ∧ orderOf g = orderOf y

namespace HullQuotient

variable {G : Type u} [Group G] {N : Subgroup G} {m : ℕ} {t : Fin m → G}
  {F : Set G}

instance instGroup (H : HullQuotient N t F) : Group H.Q := H.group

instance instIsAcylindricallyHyperbolic (H : HullQuotient N t F) :
    IsAcylindricallyHyperbolic H.Q :=
  H.acylindricallyHyperbolic

end HullQuotient

/-! ## `thm:hull` -/

-- LITERATURE INPUT (sorry): Hull, Theorem 7.1
/-- **`thm:hull`, Hull's small cancellation theorem.**

> Let `G` be acylindrically hyperbolic, let `N ≤ G` be suitable with respect to
> `A`, and let `t₁, …, t_m ∈ G` and a finite subset `F ⊆ G` be given.  Then
> there is a surjective homomorphism `q : G → Q` such that `Q` is acylindrically
> hyperbolic, `q|_F` is injective, `q(tᵢ) ∈ q(N)` for all `i`, and every element
> of finite order in `Q` is the image of an element of the same order in `G`.

This is the finite-set formulation the manuscript records; Hull's published
theorem is the injectivity-radius formulation, and the reduction is the
manuscript's preamble sentence about choosing a ball of `Γ(G,A)` containing
`F`. -/
theorem hull_smallCancellation {G : Type u} [Group G]
    [IsAcylindricallyHyperbolic G] (A : HullGeneratingSet G) {N : Subgroup G}
    (_hN : Suitable A.alphabet N) {m : ℕ} (t : Fin m → G) {F : Set G}
    (_hF : F.Finite) :
    Nonempty (HullQuotient N t F) :=
  sorry

-- LITERATURE INPUT (sorry): Hull, Theorem 7.1 (inspection of the construction)
/-- **The manuscript's separate remark on Hull's construction.**

> Separately, inspection of Hull's construction, applied successively to
> `t₁, …, t_m`, shows that `ker q` is normally generated by `m` elements.

This is a property of Hull's construction rather than a consequence of the
statement of `thm:hull`, so it is a literature input of its own.  It is the sole
reason the saturation quotient of `lem:saturation` is finitely presented. -/
theorem HullQuotient.ker_normallyGenerated {G : Type u} [Group G]
    {N : Subgroup G} {m : ℕ} {t : Fin m → G} {F : Set G}
    (H : HullQuotient N t F) :
    ∃ S : Finset G, S.card ≤ m ∧ H.q.ker = Subgroup.normalClosure (S : Set G) :=
  sorry

/-! ## The two inputs used inside the proof of `lem:saturation` -/

-- LITERATURE INPUT (sorry): Osin, Lemma 7.1
/-- **Osin, Lemma 7.1**, in the form the proof of `lem:saturation` uses it:

> Thus `N` acts non-elementarily on `Γ(G,A)` by Osin [Lemma 7.1].

The hypothesis is that `N ∩ gNg⁻¹` is infinite for every `g ∈ G`, which is
Osin's `s`-normality; the repository already carries it as
`HullSuitable.IsSNormal`, written with the conjugation on the element rather
than on the subgroup — the same condition, since `g` ranges over all of `G`.
`Sofic/HullSuitableDefectSubgroup.lean` proves the group-theoretic half of the
argument and records in its docstring that this geometric half is exactly Osin's
Lemma 7.1, which is stated here for the first time. -/
theorem osin_actsNonElementarily_of_isSNormal {G : Type u} [Group G]
    (A : HullGeneratingSet G) (N : Subgroup G)
    (_hN : HullSuitable.IsSNormal N) :
    ActsNonElementarily N (Cayley.base A.alphabet) :=
  sorry

-- LITERATURE INPUT (sorry): Hull, Corollary 5.7 and Lemma 5.8
/-- **Hull, Corollary 5.7 and Lemma 5.8**, in the form the proof of
`lem:saturation` uses them:

> By Hull [Corollary 5.7 and Lemma 5.8], `N` contains two elements `h₁, h₂` such
> that `N₀ = ⟨h₁, h₂⟩` is again suitable.

`Sofic/HullSuitableDefectSubgroup.lean` proves the non-geometric hypotheses of
Hull's Lemma 5.8 — an element of infinite order generating a proper cyclic
subgroup — over a torsion-free ambient group; what is quoted here is the
conclusion of the lemma, whose content is the hyperbolic embedding of `⟨h⟩`. -/
theorem hull_exists_two_generated_suitable {G : Type u} [Group G]
    (A : HullGeneratingSet G) {N : Subgroup G} (_hN : Suitable A.alphabet N) :
    ∃ h₁ ∈ N, ∃ h₂ ∈ N,
      Suitable A.alphabet (Subgroup.closure ({h₁, h₂} : Set G)) :=
  sorry

end TorsionFree
end NonMF
end Manuscript
end GroupApproximation
