import GroupApproximation.GGT.HyperbolicFreeGroupAH
import GroupApproximation.Manuscript.NonMF.FournierFacioInput
import GroupApproximation.Manuscript.NonMF.HullSmallCancellation

/-!
# The kernel clause of Hull's theorem, as recorded, is refuted

`HullInputs.kerNormallyGenerated` records the manuscript's remark

> Separately, inspection of Hull's construction, applied successively to
> `t₁, …, t_m`, shows that `ker q` is normally generated by `m` elements.

as a statement about **every** term of `HullQuotient N t F`:

```
∀ {G} [Group G] {N : Subgroup G} {m} {t : Fin m → G} {F : Set G}
  (H : HullQuotient N t F),
    ∃ S : Finset G, S.card ≤ m ∧ H.q.ker = Subgroup.normalClosure S
```

The manuscript's remark is about the quotient Hull's construction produces.  The
field quantifies over every group `Q` and every surjection onto it meeting the
four printed clauses, and no such surjection is required to come from Hull's
construction, so the field says something the remark does not: that a quotient
map is determined up to normal generation by `m` elements by its own conclusion.
That is false, and this module refutes it.

## The counterexample

Let `Q` be any acylindrically hyperbolic group and take

* `G = Q × Q`, `q = pr₁`, `N = ⊥`, `m = 0`, `F = ∅`.

Every clause of `HullQuotient` holds: `pr₁` is surjective, `Q` is acylindrically
hyperbolic, injectivity on `∅` is vacuous, there is no `tᵢ`, and an element of
finite order `y ∈ Q` lifts to `(y,1)`, whose order is `orderOf y` because
`x ↦ (x,1)` is an injective homomorphism.  With `m = 0` the field forces
`S = ∅`, so it forces `ker pr₁ = ⊥`; but `ker pr₁ = 1 × Q`, which is nontrivial
because an acylindrically hyperbolic group contains a loxodromic element and a
loxodromic element is not the identity (`ne_one_of_isLoxodromic`).

`splitQuotient` is that Hull quotient and `not_kerNormallyGeneratedStatement` is
the refutation.  The case `m = 0` is the sharp one: there the field asserts that
the four printed clauses alone force `q` to be injective, and they do not.

## What it costs

The refutation needs one acylindrically hyperbolic group and nothing further:
the kernel clause is false outright, not false relative to some competing
citation.  `false_of_hullInputs_of_isAcylindricallyHyperbolic` takes that group
as an argument, and any acylindrically hyperbolic group whatever would serve.
`TheoremC.LiteratureInputs.minasyanOsin` is only the cheapest supplier of one
inside this repository: its statement is quantified over all `P` and `S`, so at
`P = S = PUnit` it asserts that the double HNN extension of the trivial group —
the free group on the two stable letters — is acylindrically hyperbolic.
Minasyan–Osin's theorem is not in question here, and nothing below casts doubt
on it.

`not_nonempty_hullInputs` is the refutation with nothing assumed at all.
`GGT/HyperbolicFreeGroupAH.lean` proves that a free group of rank two is
acylindrically hyperbolic — the first instance of the class in this repository —
so the group the argument needs is now available outright, and
`TorsionFree.HullInputs` is **false**, not merely incompatible with a
neighbouring bundle.  `false_of_literatureInputs_of_hullInputs` is the weaker
statement, kept because it is the one that does not depend on that instance.

That dependency is worth stating plainly: everything else in this module rests
only on the definitions of `HullQuotient` and `HullInputs`, while
`not_nonempty_hullInputs` rests on
`GGT.instIsAcylindricallyHyperbolicFreeGroupFinTwo`.  If that instance ever
moves or is restated, this is the declaration that follows it.

The consequence for the development is unchanged in kind and sharper in degree:
the two bundles of `Manuscript.NonMF.TheoremCDebts` cannot both be paid, and the
Hull one cannot be paid at all, so the closed forms of Theorem C cannot stand on
`TorsionFree.HullInputs`.  The clause
to repair is the kernel one: it belongs to Hull's construction, not to its
output, so it belongs inside the quotient — as a further field of the structure
that the small cancellation theorem produces — rather than as a statement about
arbitrary terms of that structure.
`Manuscript.NonMF.HullFillCorrectedInputs` carries that repair and shows it
still proves `lem:saturation`, and `Manuscript.NonMF.TheoremCDebts` closes
Theorem C on the repaired bundle.
-/

namespace GroupApproximation
namespace Manuscript
namespace NonMF
namespace HullKernelRefutation

open GroupApproximation.HullGeometry
open GroupApproximation.Manuscript.NonMF.TorsionFree

universe u

/-! ## An acylindrically hyperbolic group is nontrivial -/

/-- A loxodromic element is not the identity: the identity moves nothing, while
a loxodromic element moves the basepoint linearly far. -/
theorem ne_one_of_isLoxodromic {G : Type u} [Group G] {X : Type*}
    [PseudoMetricSpace X] [MulAction G X] {g : G} {x : X}
    (hg : IsLoxodromic g x) : g ≠ 1 := by
  rintro rfl
  obtain ⟨l, hl, B, -, hlin⟩ := hg
  obtain ⟨n, hn⟩ := exists_nat_gt (B / l)
  have hdist := hlin n
  rw [one_pow, one_smul, dist_self] at hdist
  have hBn : B < l * (n : ℝ) := by
    have h := (div_lt_iff₀ hl).mp hn
    linarith [h, mul_comm (n : ℝ) l]
  linarith

/-- An acylindrically hyperbolic group is nontrivial: its own non-elementarity
clause hands out a loxodromic element. -/
theorem nontrivial_of_isAcylindricallyHyperbolic (Q : Type u) [Group Q]
    [hQ : IsAcylindricallyHyperbolic Q] : Nontrivial Q := by
  obtain ⟨_, _, _, _, hne⟩ := hQ.out
  obtain ⟨g, _, _, _, hlox, _, _⟩ := hne
  exact ⟨⟨g, 1, ne_one_of_isLoxodromic hlox⟩⟩

/-! ## A Hull quotient with `m = 0` and a nontrivial kernel -/

/-- **The counterexample.**  For an acylindrically hyperbolic `Q`, the first
projection `Q × Q → Q` is a Hull quotient of `G = Q × Q` for `N = ⊥`, `m = 0`
and `F = ∅`: it is surjective, its target is acylindrically hyperbolic, it is
injective on `∅`, there is no `tᵢ` to send into `N`, and `y` of finite order
lifts to `(y,1)`, of the same order. -/
def splitQuotient (Q : Type u) [Group Q] [IsAcylindricallyHyperbolic Q] :
    HullQuotient (⊥ : Subgroup (Q × Q)) (Fin.elim0 : Fin 0 → Q × Q)
      (∅ : Set (Q × Q)) where
  Q := Q
  q := MonoidHom.fst Q Q
  surjective := fun y => ⟨(y, 1), rfl⟩
  injOn := Set.injOn_empty _
  mem_map := fun i => i.elim0
  finiteOrder_lift := by
    intro y _
    have hinj : Function.Injective (MonoidHom.inl Q Q) := by
      intro a b hab
      have h := congrArg Prod.fst hab
      simpa using h
    refine ⟨MonoidHom.inl Q Q y, rfl, ?_⟩
    exact orderOf_injective (MonoidHom.inl Q Q) hinj y

@[simp] theorem splitQuotient_q (Q : Type u) [Group Q]
    [IsAcylindricallyHyperbolic Q] :
    (splitQuotient Q).q = MonoidHom.fst Q Q := rfl

/-! ## The refutation -/

/-- **The statement of `HullInputs.kerNormallyGenerated`**, on its own, so that
it can be refuted without naming the other three fields. -/
def KerNormallyGeneratedStatement : Prop :=
  ∀ {G : Type u} [Group G] {N : Subgroup G} {m : ℕ} {t : Fin m → G} {F : Set G}
    (H : HullQuotient N t F),
      ∃ S : Finset G, S.card ≤ m ∧ H.q.ker = Subgroup.normalClosure (S : Set G)

/-- **The kernel clause, as recorded, is false**, as soon as one acylindrically
hyperbolic group exists.  At `m = 0` the clause forces the kernel of every Hull
quotient to be trivial, and `splitQuotient` is one whose kernel is not. -/
theorem not_kerNormallyGeneratedStatement (Q : Type u) [Group Q]
    [IsAcylindricallyHyperbolic Q] : ¬ KerNormallyGeneratedStatement.{u} := by
  intro h
  obtain ⟨S, hcard, hker⟩ := h (splitQuotient Q)
  have hS : S = ∅ := Finset.card_eq_zero.mp (Nat.le_zero.mp hcard)
  have hnc : Subgroup.normalClosure (∅ : Set (Q × Q)) = ⊥ :=
    le_antisymm (Subgroup.normalClosure_le_normal (Set.empty_subset _)) bot_le
  rw [hS, Finset.coe_empty, hnc] at hker
  haveI := nontrivial_of_isAcylindricallyHyperbolic Q
  obtain ⟨x, hx⟩ := exists_ne (1 : Q)
  have hmem : ((1 : Q), x) ∈ (splitQuotient Q).q.ker :=
    MonoidHom.mem_ker.mpr rfl
  rw [hker, Subgroup.mem_bot] at hmem
  exact hx (by simpa using congrArg Prod.snd hmem)

/-- **`HullInputs` is refuted by the existence of an acylindrically hyperbolic
group**, through its kernel clause alone. -/
theorem false_of_hullInputs_of_isAcylindricallyHyperbolic (h : HullInputs.{u})
    (Q : Type u) [Group Q] [IsAcylindricallyHyperbolic Q] : False :=
  not_kerNormallyGeneratedStatement Q h.kerNormallyGenerated

/-! ## The acylindrically hyperbolic group the paragraph already cites -/

/-- **Minasyan–Osin at the trivial group.**  `MinasyanOsinStatement` is
quantified over all `P` and `S`, so it asserts in particular that the double HNN
extension of the trivial group along the two trivial factors is acylindrically
hyperbolic.  That group is the free group on the two stable letters. -/
theorem isAcylindricallyHyperbolic_trivialSkeleton
    (hMO : TheoremC.MinasyanOsinStatement)
    (hinj : Function.Injective (1 : (PUnit × PUnit × PUnit) →* PUnit)) :
    IsAcylindricallyHyperbolic (TheoremC.Skeleton
      (1 : (PUnit × PUnit × PUnit) →* PUnit) hinj) :=
  hMO PUnit PUnit inferInstance inferInstance 1 hinj

/-- The trivial homomorphism out of a one-element group is injective. -/
theorem injective_trivial_hom :
    Function.Injective (1 : (PUnit × PUnit × PUnit) →* PUnit) := by
  intro a b _
  obtain ⟨⟨⟩, ⟨⟩, ⟨⟩⟩ := a
  obtain ⟨⟨⟩, ⟨⟩, ⟨⟩⟩ := b
  rfl

/-- **Minasyan–Osin's statement and Hull's inputs are contradictory.** -/
theorem false_of_minasyanOsin_of_hullInputs
    (hMO : TheoremC.MinasyanOsinStatement) (h : HullInputs.{0}) : False := by
  haveI := isAcylindricallyHyperbolic_trivialSkeleton hMO injective_trivial_hom
  exact false_of_hullInputs_of_isAcylindricallyHyperbolic h
    (TheoremC.Skeleton (1 : (PUnit × PUnit × PUnit) →* PUnit)
      injective_trivial_hom)

/-- **The two debts of `Manuscript.NonMF.TheoremCDebts` cannot both be paid.**
`TheoremC.LiteratureInputs` carries Minasyan–Osin's statement as one of its five
fields, and that field alone contradicts `TorsionFree.HullInputs`. -/
theorem false_of_literatureInputs_of_hullInputs (I : TheoremC.LiteratureInputs)
    (h : HullInputs.{0}) : False :=
  false_of_minasyanOsin_of_hullInputs I.minasyanOsin h

/-- The same, as an impossibility statement about the Hull bundle. -/
theorem not_nonempty_hullInputs_of_literatureInputs
    (I : TheoremC.LiteratureInputs) : ¬ Nonempty HullInputs.{0} := by
  rintro ⟨h⟩
  exact false_of_literatureInputs_of_hullInputs I h

/-! ## The refutation, with nothing assumed -/

/-- **`TorsionFree.HullInputs` is false.**

The bundle asserts, through its kernel clause, that the four printed clauses of
`thm:hull` force `q` to be injective at `m = 0`; `splitQuotient` refutes that as
soon as one acylindrically hyperbolic group exists, and
`GGT.instIsAcylindricallyHyperbolicFreeGroupFinTwo` supplies one — the free
group of rank two, with its basis as alphabet, its Cayley graph a tree, and two
basis letters as independent loxodromics.

So no hypothesis is needed: not `TheoremC.LiteratureInputs`, not
Minasyan–Osin's statement, nothing.  This is the sharp form of everything above,
and the reason the Hull bundle had to be restated rather than proved. -/
theorem not_nonempty_hullInputs : ¬ Nonempty HullInputs.{0} := by
  rintro ⟨h⟩
  exact false_of_hullInputs_of_isAcylindricallyHyperbolic h (FreeGroup (Fin 2))

end HullKernelRefutation
end NonMF
end Manuscript
end GroupApproximation
