import GroupApproximation.Manuscript.NonMF.HullBallForm
import GroupApproximation.Manuscript.NonMF.HullInputsProved
import GroupApproximation.Manuscript.NonMF.Saturation

/-!
# Hull's inputs, restated so that they are not false, and `lem:saturation` from
them

`Manuscript.NonMF.HullFillKernelRefutation` refutes
`TorsionFree.HullInputs.kerNormallyGenerated`: the field quantifies over every
term of `HullQuotient N t F`, and at `m = 0` that asserts that the four printed
clauses of `thm:hull` force `q` to be injective, which the first projection
`Q × Q → Q` of an acylindrically hyperbolic `Q` refutes.  The manuscript's remark

> Separately, inspection of Hull's construction, applied successively to
> `t₁, …, t_m`, shows that `ker q` is normally generated by `m` elements.

is about the quotient Hull's construction produces, so it is a property of that
quotient and belongs with it.  `HullQuotientNG` is the pair — Hull's quotient
together with the normal generation of its kernel — and `HullInputsCorrected` is
the citation bundle stated with it.

## Two fields, not four

* `HullInputsCorrected.smallCancellation` — **Hull, Theorem 7.1** with the
  construction's kernel datum.  `smallCancellation_of_ballFormNG` reduces it to
  Hull's published injectivity-radius formulation exactly as
  `HullBallForm.smallCancellation_of_ballForm` does for the weaker form, and
  `smallCancellation_of_corrected` recovers `HullInputs.smallCancellation`
  from it, so nothing is lost.
* `HullInputsCorrected.osinNonElementary` — **Osin, Lemma 7.1**, restricted to
  a normal subgroup of a torsion-free group, which is the case
  `lem:saturation` applies it in and the case the repository's partial
  machinery is stated for.  `osinNonElementary_of_osinLemma71` derives it from
  the general lemma, so the restriction removes hypotheses to prove rather than
  changing what is cited.

`HullInputs.twoGeneratedSuitable` is not a field here.  Over a torsion-free
ambient group it is a theorem of this repository
(`HullInputsProved.exists_pair_suitable_of_torsionFree`), and `lem:saturation`
applies it only there, with `hG : IsPowerTorsionFree G` in scope.

`saturation_of_corrected` is `Saturation.saturation` reproved from this bundle,
with the same conclusion `Nonempty (SaturationQuotient N F)`, so the repair
costs nothing downstream: `Saturation.saturation` and everything above it can
take `HullInputsCorrected` in place of `HullInputs`.  The `S.card ≤ m` bound is
carried but unused there — only the finiteness of `S` enters the finite
presentation of the quotient.
-/

namespace GroupApproximation
namespace Manuscript
namespace NonMF
namespace HullCorrectedInputs

open GroupApproximation.HullGeometry
open GroupApproximation.Manuscript.NonMF.TorsionFree

universe u

/-! ## The quotient of `thm:hull`, with the datum of its construction -/

/-- **The output of Hull's Theorem 7.1, as his construction produces it.**  The
printed clauses are `quotient`; the manuscript's separate remark on `ker q` is
`kerNormallyGenerated`.  Recording the remark here rather than as a statement
about arbitrary Hull quotients is what
`HullFillKernelRefutation.not_kerNormallyGeneratedStatement` forces. -/
structure HullQuotientNG {G : Type u} [Group G] (N : Subgroup G) {m : ℕ}
    (t : Fin m → G) (F : Set G) where
  /-- The quotient, with the four printed clauses of `thm:hull`. -/
  quotient : HullQuotient N t F
  /-- "`ker q` is normally generated by `m` elements." -/
  kerNormallyGenerated : ∃ S : Finset G, S.card ≤ m ∧
    quotient.q.ker = Subgroup.normalClosure (S : Set G)

/-- A Hull quotient with its kernel datum, restricted to a subset, keeps the
datum: `HullQuotient.mono` leaves `q` unchanged. -/
def HullQuotientNG.mono {G : Type u} [Group G] {N : Subgroup G} {m : ℕ}
    {t : Fin m → G} {F F' : Set G} (H : HullQuotientNG N t F') (hFF' : F ⊆ F') :
    HullQuotientNG N t F where
  quotient := H.quotient.mono hFF'
  kerNormallyGenerated := H.kerNormallyGenerated

/-! ## The two citations -/

/-- **The group-theoretic literature the manuscript cites**, in the two
statements that survive the refutation of `TorsionFree.HullInputs`: Hull's
Theorem 7.1 with the kernel datum of its construction, and Osin's Lemma 7.1.

Hull's Corollary 5.7 with Lemma 5.8 is not among them: over a torsion-free
ambient group it is `HullInputsProved.exists_pair_suitable_of_torsionFree`, and
that is the only case `lem:saturation` uses. -/
structure HullInputsCorrected : Type where
  /-- **`thm:hull`, Hull's small cancellation theorem** — Hull, Theorem 7.1, in
  the finite-set formulation the manuscript records, with the kernel of the
  quotient map normally generated by `m` elements. -/
  smallCancellation : ∀ {G : Type u} [Group G] [IsAcylindricallyHyperbolic G]
    (A : HullGeneratingSet G) {N : Subgroup G}, Suitable A.alphabet N →
      ∀ {m : ℕ} (t : Fin m → G) {F : Set G}, F.Finite →
        Nonempty (HullQuotientNG N t F)
  /-- **Osin, Lemma 7.1**: an `s`-normal subgroup acts non-elementarily on
  `Γ(G,A)`, in the case `lem:saturation` uses it — a normal subgroup of a
  torsion-free group.

  That is also the case the repository's partial machinery is stated for:
  `HullGeometry.exists_escaping_or_noncommuting_of_isSNormal` carries
  `IsPowerTorsionFree G` as a hypothesis and
  `HullGeometry.actsNonElementarily_of_normal_conjugate` carries `[S.Normal]`,
  so narrowing the citation to those two hypotheses costs the saturation lemma
  nothing and lines the debt up with what is already proved.
  `osinNonElementary_of_osinLemma71` checks that this is a special case of
  Osin's lemma as `HullInputs` states it. -/
  osinNonElementary : ∀ {G : Type u} [Group G] (A : HullGeneratingSet G),
    IsPowerTorsionFree G → ∀ (N : Subgroup G) [N.Normal],
      HullSuitable.IsSNormal N →
        ActsNonElementarily N (Cayley.base A.alphabet)

/-- The corrected bundle proves the first field of `TorsionFree.HullInputs`:
forgetting the kernel datum gives back the plain Hull quotient. -/
theorem smallCancellation_of_corrected (h : HullInputsCorrected.{u}) :
    ∀ {G : Type u} [Group G] [IsAcylindricallyHyperbolic G]
      (A : HullGeneratingSet G) {N : Subgroup G}, Suitable A.alphabet N →
        ∀ {m : ℕ} (t : Fin m → G) {F : Set G}, F.Finite →
          Nonempty (HullQuotient N t F) := by
  intro G _ _ A N hN m t F hF
  obtain ⟨H⟩ := h.smallCancellation A hN t hF
  exact ⟨H.quotient⟩

/-! ## Osin's Lemma 7.1, and the case that is cited -/

/-- **Osin, Lemma 7.1**, in the general form `HullInputs.osinNonElementary`
records: every `s`-normal subgroup of an acylindrically hyperbolic group acts
non-elementarily on `Γ(G,A)`. -/
def OsinLemma71 : Prop :=
  ∀ {G : Type u} [Group G] (A : HullGeneratingSet G) (N : Subgroup G),
    HullSuitable.IsSNormal N → ActsNonElementarily N (Cayley.base A.alphabet)

/-- The field of `HullInputsCorrected` is a special case of Osin's lemma:
nothing has been substituted for it, only the hypotheses `lem:saturation`
supplies have been added. -/
theorem osinNonElementary_of_osinLemma71 (h : OsinLemma71.{u}) :
    ∀ {G : Type u} [Group G] (A : HullGeneratingSet G), IsPowerTorsionFree G →
      ∀ (N : Subgroup G) [N.Normal], HullSuitable.IsSNormal N →
        ActsNonElementarily N (Cayley.base A.alphabet) := by
  intro G _ A _ N _ hsn
  exact h A N hsn

/-! ## Hull's published form -/

/-- **Hull's Theorem 7.1 in its published form**, with the kernel datum:
injectivity on the ball of a given radius. -/
def HullBallFormStatementNG : Prop :=
  ∀ {G : Type u} [Group G] [IsAcylindricallyHyperbolic G]
    (A : HullGeneratingSet G) {N : Subgroup G}, Suitable A.alphabet N →
      ∀ {m : ℕ} (t : Fin m → G) (R : ℕ),
        Nonempty (HullQuotientNG N t (cayleyBall A.alphabet R))

/-- **"a ball containing a given finite set gives the following form"**, with
the kernel datum carried along: a finite subset of `G` lies in a ball, and
restricting to a subset leaves `q` — so its kernel — unchanged. -/
theorem smallCancellation_of_ballFormNG (hball : HullBallFormStatementNG.{u}) :
    ∀ {G : Type u} [Group G] [IsAcylindricallyHyperbolic G]
      (A : HullGeneratingSet G) {N : Subgroup G}, Suitable A.alphabet N →
        ∀ {m : ℕ} (t : Fin m → G) {F : Set G}, F.Finite →
          Nonempty (HullQuotientNG N t F) := by
  intro G _ _ A N hN m t F hF
  obtain ⟨R, hR⟩ := exists_subset_cayleyBall A.alphabet hF
  obtain ⟨H⟩ := hball A hN t R
  exact ⟨H.mono hR⟩

/-! ## `lem:saturation`, from the corrected bundle -/

/-- **`lem:saturation` from `HullInputsCorrected`.**

> Let `G` be finitely presented, torsion-free, and acylindrically hyperbolic,
> let `N ⊴ G` be nontrivial, and let `F ⊆ G` be finite.  Then there is a
> surjective homomorphism `q : G → Q` such that `Q` is two-generated, finitely
> presented, torsion-free, and acylindrically hyperbolic, `q|_F` is injective,
> and `q(N) = Q`.

The printed proof, unchanged, with two substitutions: Hull's Corollary 5.7 with
Lemma 5.8 is `HullInputsProved.exists_pair_suitable_of_torsionFree`, and the
kernel of `q` is normally generated by `m` elements because the quotient carries
that datum. -/
theorem saturation_of_corrected {G : Type u} [Group G]
    [Group.IsFinitelyPresented G] [IsAcylindricallyHyperbolic G]
    (hHull : HullInputsCorrected.{u}) (hG : IsPowerTorsionFree G)
    (N : Subgroup G) [N.Normal] (hN : N ≠ ⊥) {F : Set G} (hF : F.Finite) :
    Nonempty (SaturationQuotient N F) := by
  classical
  -- The generating set `A` of the section preamble.
  obtain ⟨A⟩ := exists_hullGeneratingSet G
  -- "Because `N ⊴ G`, one has `N ∩ gNg⁻¹ = N` for every `g ∈ G`; this group is
  -- infinite because `G` is torsion-free and `N ≠ 1`."
  have hsn : HullSuitable.IsSNormal N := isSNormal_of_torsionFree hG N hN
  -- "Thus `N` acts non-elementarily on `Γ(G,A)` by Osin, Lemma 7.1."
  have hnonelem : ActsNonElementarily N (Cayley.base A.alphabet) :=
    hHull.osinNonElementary A hG N hsn
  -- "Torsion-freeness makes `N` suitable."
  have hsuit : Suitable A.alphabet N := suitable_of_torsionFree hG hnonelem
  -- "`N` contains two elements `h₁, h₂` such that `N₀ = ⟨h₁, h₂⟩` is again
  -- suitable", which over a torsion-free `G` is proved.
  obtain ⟨h₁, hh₁, h₂, hh₂, hsuit₀⟩ :=
    exists_pair_suitable_of_torsionFree hG hsuit
  have hN₀le : Subgroup.closure ({h₁, h₂} : Set G) ≤ N := by
    rw [Subgroup.closure_le]
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl
    · exact hh₁
    · exact hh₂
  -- "Apply Theorem `thm:hull` to `N₀` with `t₁, …, t_m` a finite generating set
  -- of `G` and with the set `F`."
  obtain ⟨m, t, htop⟩ := exists_finite_generating_family G
  obtain ⟨⟨H, hkerNG⟩⟩ := hHull.smallCancellation A hsuit₀ t hF
  -- The display `Q = ⟨q(t₁), …, q(t_m)⟩ ≤ q(N₀) ≤ q(N) ≤ Q`.
  have hN₀top : (Subgroup.closure ({h₁, h₂} : Set G)).map H.q = ⊤ :=
    map_eq_top_of_generators_mem H.q H.surjective htop H.mem_map
  -- "so `Q = q(N₀)` and `q(N) = Q`."
  have hNtop : N.map H.q = ⊤ := map_eq_top_of_le H.q hN₀le hN₀top
  -- "…`= ⟨q(h₁), q(h₂)⟩`."
  have hgen : Subgroup.closure ({H.q h₁, H.q h₂} : Set H.Q) = ⊤ := by
    rw [← closure_pair_map H.q h₁ h₂]
    exact hN₀top
  -- "The quotient is torsion-free by Theorem `thm:hull`."
  have htf : IsPowerTorsionFree H.Q :=
    torsionFree_of_finiteOrder_lift hG H.q H.finiteOrder_lift
  -- "…and finitely presented because `ker q` is normally generated by `m`
  -- elements."
  obtain ⟨S, -, hker⟩ := hkerNG
  have hfp : Group.IsFinitelyPresented H.Q :=
    Group.IsFinitelyPresented.of_surjective H.q H.surjective
      ⟨(S : Set G), S.finite_toSet, hker.symm⟩
  exact ⟨{ Q := H.Q
           group := H.group
           q := H.q
           surjective := H.surjective
           generatorOne := H.q h₁
           generatorTwo := H.q h₂
           twoGenerated := hgen
           finitelyPresented := hfp
           torsionFree := htf
           acylindricallyHyperbolic := H.acylindricallyHyperbolic
           injOn := H.injOn
           map_eq_top := hNtop }⟩

end HullCorrectedInputs
end NonMF
end Manuscript
end GroupApproximation
