import GroupApproximation.Manuscript.NonMF.SimpleInDefect
import GroupApproximation.Manuscript.OneSidedMFRadical.PrintedDefectFunctorial

/-!
# The paragraph that puts `S` in the defect of `Γ`

`non_mf_groups_exist.tex`, section `sec:torsion-free`, the paragraph that
follows the Fournier-Facio citation:

> For `c ∈ J` and `ℓ ∈ S`, the commutator `[tct⁻¹, ℓ]` lies in `𝔇_{G₀}(Γ)` by
> `eq:intrinsic-defect`, since `t` conjugates `Γ` into itself, `c` centralizes
> `Γ`, and `S ≤ Γ`.  As `c` ranges over `J`, the element `tct⁻¹` ranges over
> `S`, so `[S,S] ≤ 𝔇_{G₀}(Γ)`, and `S` is perfect, so `S ≤ 𝔇_{G₀}(Γ)`.

Three sentences, three theorems:

| printed sentence | Lean |
| --- | --- |
| "the commutator `[tct⁻¹, ℓ]` lies in `𝔇_{G₀}(Γ)` by `eq:intrinsic-defect`" | `defect_generator_mem_of_simpleFactor` |
| "As `c` ranges over `J` … so `[S,S] ≤ 𝔇_{G₀}(Γ)`" | `commutator_conjFactor_le_printedDefect` |
| "and `S` is perfect, so `S ≤ 𝔇_{G₀}(Γ)`" | `conjFactor_le_printedDefect` |

## This replaces `lem:commutator-in-defect`

The manuscript used to prove a lemma — *for every homomorphism `ρ : G₀ → Ḡ`,
`ρ(S) ≤ 𝔇_Ḡ(ρ(Γ))`* — and apply it to the saturation quotient map.  That lemma
is **deleted from the print**.  In its place the argument is made once, inside
`G₀`, and transported by the displayed inequality `eq:defect-functorial`.
`map_conjFactor_le_printedDefect_of_functorial` is that transport, and it is what
the proof of `thm:torsion-free` now cites.

`SimpleInDefect.manuscriptLemmaCommutatorInDefect` is untouched.  It is still
true, and its proof is still the perfectness argument; it is simply no longer
the route the manuscript takes.  Nothing here supersedes it and nothing deletes
it.

The perfectness of `S` is `PrintedFournierFacioData.commutator_conjFactor_eq`,
already proved in `SimpleInDefect` from simplicity and nonabelianness of `J`.
That step is unchanged by the rewrite: what moved is only *where* the
containment is proved and *how* it reaches the quotient.
-/

namespace GroupApproximation
namespace Manuscript
namespace NonMF
namespace TorsionFreePrinted

open scoped commutatorElement

universe u v

/-! ## The three printed sentences -/

/-- **"For `c ∈ J` and `ℓ ∈ S`, the commutator `[tct⁻¹, ℓ]` lies in
`𝔇_{G₀}(Γ)` by `eq:intrinsic-defect`, since `t` conjugates `Γ` into itself, `c`
centralizes `Γ`, and `S ≤ Γ`."**

The three "since" clauses are the three arguments of
`printedDefect_generator_mem`, in the printed order: `conj_core_mem` is *`t`
conjugates `Γ` into itself*, `simpleFactor_centralizes` is *`c` centralizes
`Γ`*, and `conjFactor_le_core` is *`S ≤ Γ`*, which is where `ℓ` has to live for
`eq:intrinsic-defect` to apply. -/
theorem defect_generator_mem_of_simpleFactor {E : Type u} [Group E]
    (F : PrintedFournierFacioData E) {c : E} (hc : c ∈ F.simpleFactor)
    {ℓ : E} (hℓ : ℓ ∈ F.conjFactor) :
    ⁅F.t * c * F.t⁻¹, ℓ⁆ ∈ OneSidedMFRadical.printedDefect F.core :=
  OneSidedMFRadical.printedDefect_generator_mem F.core F.conj_core_mem
    (F.simpleFactor_centralizes c hc) (F.conjFactor_le_core hℓ)

/-- **"As `c` ranges over `J`, the element `tct⁻¹` ranges over `S`, so
`[S,S] ≤ 𝔇_{G₀}(Γ)`."**

`S = tJt⁻¹` is `PrintedFournierFacioData.conjFactor`, the image of `J` under
conjugation by `t`, so an element of `S` *is* a `tct⁻¹` with `c ∈ J`; that is
the whole content of "ranges over".  The commutator subgroup is generated by
the commutators just placed in the defect. -/
theorem commutator_conjFactor_le_printedDefect {E : Type u} [Group E]
    (F : PrintedFournierFacioData E) :
    ⁅F.conjFactor, F.conjFactor⁆ ≤ OneSidedMFRadical.printedDefect F.core := by
  rw [Subgroup.commutator_le]
  intro x hx y hy
  rw [F.conjFactor_def, Subgroup.mem_map] at hx
  obtain ⟨c, hc, rfl⟩ := hx
  have hxeq : (MulAut.conj F.t).toMonoidHom c = F.t * c * F.t⁻¹ := by simp
  rw [hxeq]
  exact defect_generator_mem_of_simpleFactor F hc hy

/-- **"and `S` is perfect, so `S ≤ 𝔇_{G₀}(Γ)`."**

Perfectness is `PrintedFournierFacioData.commutator_conjFactor_eq`: `S` is an
isomorphic image of the simple nonabelian `J`, so `⁅S,S⁆ = S`. -/
theorem conjFactor_le_printedDefect {E : Type u} [Group E]
    (F : PrintedFournierFacioData E) :
    F.conjFactor ≤ OneSidedMFRadical.printedDefect F.core :=
  calc F.conjFactor = ⁅F.conjFactor, F.conjFactor⁆ :=
        F.commutator_conjFactor_eq.symm
    _ ≤ OneSidedMFRadical.printedDefect F.core :=
        commutator_conjFactor_le_printedDefect F

/-! ## The paragraph, as one closed proposition -/

/-- **The displayed conclusion of the paragraph, with no declaration inputs.**

> `S ≤ 𝔇_{G₀}(Γ)`.

The Fournier-Facio datum is universally quantified inside the proposition, so
what remains conditional is exactly the citation and nothing else. -/
def PrintedSimpleFactorInDefect : Prop :=
  ∀ {E : Type} [Group E] (F : PrintedFournierFacioData E),
    F.conjFactor ≤ OneSidedMFRadical.printedDefect F.core

/-- **The paragraph, proved.** -/
theorem manuscriptSimpleFactorInDefect : PrintedSimpleFactorInDefect := by
  intro E _ F
  exact conjFactor_le_printedDefect F

/-! ## The transport `thm:torsion-free` cites -/

/-- **"By `eq:defect-functorial`, `φ(S) ≤ 𝔇_Q(φ(Γ))`."**

The printed route in two steps: the paragraph above puts `S` inside
`𝔇_{G₀}(Γ)`, and the displayed inequality carries the image of a defect into the
defect of the image.  This is what replaced the deleted
`lem:commutator-in-defect`, whose statement was this conclusion proved directly
at every `ρ`. -/
theorem map_conjFactor_le_printedDefect_of_functorial {E : Type} [Group E]
    (F : PrintedFournierFacioData E) {L : Type} [Group L] (rho : E →* L) :
    F.conjFactor.map rho ≤
      OneSidedMFRadical.printedDefect (F.core.map rho) :=
  (Subgroup.map_mono (conjFactor_le_printedDefect F)).trans
    (OneSidedMFRadical.manuscriptPrintedDefectFunctorial E L rho F.core)

end TorsionFreePrinted
end NonMF
end Manuscript
end GroupApproximation
