import Mathlib.Logic.Relation
import GroupApproximation.Meta.AxiomGuard

/-!
# Ordered 2-complexes, edge paths and combinatorial simple connectivity (leaf T1c)

`simple_kazhdan_sofic_group.tex`, `sec:questions`, l.733-735.  The input still missing there is
`K₂(4, L) = ⊥` (Khanh, arXiv:2609.08428, Thm 5.1).  Its proof applies Brown's presentation theorem
to the frame complex `X₄(L)`, and that application needs `X₄(L)` to be simply connected
(leaf **T1c**).

This file fixes the *combinatorial* notion of simple connectivity that the Brown presentation
lane (LVBrown) consumes.  No topology is involved.

Khanh, tex l.424: "A $(k-1)$-simplex ... is an ordered tuple $(v_1,\ldots,v_k)$ ... Faces delete a
vector."  Khanh, tex l.460: "Homotopies of edge paths are generated by backtracking and passages
across individual triangles. ... the two ordered edge cells $(u,v)$ and $(v,u)$ remain distinct."

* `OrderedTwoComplex V`: ordered edges `edge u v` and ordered triangles `tri a b c`, where the
  faces `(a,b)`, `(b,c)` and `(a,c)` of every triangle are edges.
* `OrderedTwoComplex.EdgePath X a b`: at each step a path traverses an ordered edge either
  forwards (`fwd`) or backwards (`bwd`).
* `EdgePath.Move`: the elementary moves, applied inside an arbitrary context.  They are
  backtracking `(u,v)·(u,v)⁻¹ ↦ ∅` and `(u,v)⁻¹·(u,v) ↦ ∅`, and the triangle passage
  `(a,b)·(b,c) ↦ (a,c)`.
* `EdgePath.Homotopic`: the equivalence closure of the moves.
* `OrderedTwoComplex.SimplyConnected`: the complex is connected and every edge loop is homotopic
  to the constant path.

This is a self-contained port of the unwired foreign modules `LeavittK2/TwoComplex/{Basic,Homotopy}`.
-/

namespace GroupApproximation.Full.LVFrame

universe u

/-- An abstract ordered 2-complex on `V` (Khanh, tex l.424): ordered edges, and ordered triangles
whose three faces are edges. -/
structure OrderedTwoComplex (V : Type u) where
  /-- The ordered edges (1-simplices). -/
  edge : V → V → Prop
  /-- The ordered triangles (2-simplices). -/
  tri : V → V → V → Prop
  /-- Deleting the last vertex of a triangle gives an edge. -/
  tri_edge01 : ∀ {a b c : V}, tri a b c → edge a b
  /-- Deleting the first vertex of a triangle gives an edge. -/
  tri_edge12 : ∀ {a b c : V}, tri a b c → edge b c
  /-- Deleting the middle vertex of a triangle gives an edge. -/
  tri_edge02 : ∀ {a b c : V}, tri a b c → edge a c

namespace OrderedTwoComplex

variable {V : Type u} (X : OrderedTwoComplex V)

/-- Edge paths from `a` to `c`.  `fwd e p` traverses the ordered edge `e : edge a b` forwards and
then follows `p`.  `bwd e p` traverses the ordered edge `e : edge b a` backwards, i.e. from `a` to
`b`, and then follows `p`. -/
inductive EdgePath : V → V → Type u
  | nil (v : V) : EdgePath v v
  | fwd {a b c : V} (e : X.edge a b) (p : EdgePath b c) : EdgePath a c
  | bwd {a b c : V} (e : X.edge b a) (p : EdgePath b c) : EdgePath a c

/-- Any two vertices are joined by an edge path. -/
def Connected : Prop := ∀ a b : V, Nonempty (X.EdgePath a b)

namespace EdgePath

variable {X}

/-- Concatenation of edge paths. -/
def append : {a b c : V} → X.EdgePath a b → X.EdgePath b c → X.EdgePath a c
  | _, _, _, nil _, q => q
  | _, _, _, fwd e p, q => fwd e (append p q)
  | _, _, _, bwd e p, q => bwd e (append p q)

@[simp] theorem nil_append {a b : V} (p : X.EdgePath a b) : (nil a).append p = p := rfl

@[simp] theorem fwd_append {a b c d : V} (e : X.edge a b) (p : X.EdgePath b c)
    (q : X.EdgePath c d) : (fwd e p).append q = fwd e (p.append q) := rfl

@[simp] theorem bwd_append {a b c d : V} (e : X.edge b a) (p : X.EdgePath b c)
    (q : X.EdgePath c d) : (bwd e p).append q = bwd e (p.append q) := rfl

@[simp] theorem append_nil : ∀ {a b : V} (p : X.EdgePath a b), p.append (nil b) = p
  | _, _, nil _ => rfl
  | _, _, fwd e p => congrArg (fwd e) (append_nil p)
  | _, _, bwd e p => congrArg (bwd e) (append_nil p)

theorem append_assoc : ∀ {a b c d : V} (p : X.EdgePath a b) (q : X.EdgePath b c)
    (r : X.EdgePath c d), (p.append q).append r = p.append (q.append r)
  | _, _, _, _, nil _, _, _ => rfl
  | _, _, _, _, fwd e p, q, r => congrArg (fwd e) (append_assoc p q r)
  | _, _, _, _, bwd e p, q, r => congrArg (bwd e) (append_assoc p q r)

/-- The reverse path: a forward traversal of an ordered edge becomes a backward traversal of the
same ordered edge, and a backward traversal becomes a forward one. -/
def reverse : {a b : V} → X.EdgePath a b → X.EdgePath b a
  | _, _, nil v => nil v
  | _, _, fwd e p => (reverse p).append (bwd e (nil _))
  | _, _, bwd e p => (reverse p).append (fwd e (nil _))

@[simp] theorem reverse_nil (v : V) : (nil v : X.EdgePath v v).reverse = nil v := rfl

@[simp] theorem reverse_fwd {a b c : V} (e : X.edge a b) (p : X.EdgePath b c) :
    (fwd e p).reverse = p.reverse.append (bwd e (nil a)) := rfl

@[simp] theorem reverse_bwd {a b c : V} (e : X.edge b a) (p : X.EdgePath b c) :
    (bwd e p).reverse = p.reverse.append (fwd e (nil a)) := rfl

theorem reverse_append : ∀ {a b c : V} (p : X.EdgePath a b) (q : X.EdgePath b c),
    (p.append q).reverse = q.reverse.append p.reverse
  | _, _, _, nil _, q => (append_nil q.reverse).symm
  | _, _, _, fwd e p, q => by
      rw [fwd_append, reverse_fwd, reverse_fwd, reverse_append p q, append_assoc]
  | _, _, _, bwd e p, q => by
      rw [bwd_append, reverse_bwd, reverse_bwd, reverse_append p q, append_assoc]

@[simp] theorem reverse_reverse : ∀ {a b : V} (p : X.EdgePath a b), p.reverse.reverse = p
  | _, _, nil _ => rfl
  | _, _, fwd e p =>
      (reverse_append p.reverse (bwd e (nil _))).trans
        (congrArg (fun r => EdgePath.append (bwd e (nil _)).reverse r) (reverse_reverse p))
  | _, _, bwd e p =>
      (reverse_append p.reverse (fwd e (nil _))).trans
        (congrArg (fun r => EdgePath.append (fwd e (nil _)).reverse r) (reverse_reverse p))

/-- Elementary homotopy moves of edge paths, applied inside an arbitrary context `p · _ · q`
(Khanh, tex l.460): backtracking in either orientation, and passage across one ordered
triangle `(b₀,b₁,b₂)`, `(b₀,b₁)·(b₁,b₂) ↦ (b₀,b₂)`. -/
inductive Move {a d : V} : X.EdgePath a d → X.EdgePath a d → Prop
  | backtrackFwd {b c : V} (p : X.EdgePath a b) (e : X.edge b c) (q : X.EdgePath b d) :
      Move (p.append (fwd e (bwd e q))) (p.append q)
  | backtrackBwd {b c : V} (p : X.EdgePath a b) (e : X.edge c b) (q : X.EdgePath b d) :
      Move (p.append (bwd e (fwd e q))) (p.append q)
  | triangle {b₀ b₁ b₂ : V} (p : X.EdgePath a b₀) (t : X.tri b₀ b₁ b₂) (q : X.EdgePath b₂ d) :
      Move (p.append (fwd (X.tri_edge01 t) (fwd (X.tri_edge12 t) q)))
        (p.append (fwd (X.tri_edge02 t) q))

/-- Combinatorial homotopy rel endpoints: the equivalence relation generated by backtracking and
passages across individual ordered triangles (Khanh, tex l.460). -/
def Homotopic {a b : V} (p q : X.EdgePath a b) : Prop := Relation.EqvGen Move p q

theorem Move.homotopic {a b : V} {p q : X.EdgePath a b} (h : Move p q) : Homotopic p q :=
  Relation.EqvGen.rel _ _ h

theorem Homotopic.refl {a b : V} (p : X.EdgePath a b) : Homotopic p p :=
  Relation.EqvGen.refl _

theorem Homotopic.symm {a b : V} {p q : X.EdgePath a b} (h : Homotopic p q) : Homotopic q p :=
  Relation.EqvGen.symm _ _ h

theorem Homotopic.trans {a b : V} {p q r : X.EdgePath a b} (h₁ : Homotopic p q)
    (h₂ : Homotopic q r) : Homotopic p r :=
  Relation.EqvGen.trans _ _ _ h₁ h₂

theorem Homotopic.of_eq {a b : V} {p q : X.EdgePath a b} (h : p = q) : Homotopic p q := by
  subst h
  exact Homotopic.refl p

theorem Move.append_right {a b c : V} {p p' : X.EdgePath a b} (h : Move p p')
    (r : X.EdgePath b c) : Move (p.append r) (p'.append r) := by
  cases h with
  | backtrackFwd s e q =>
      simp only [append_assoc]
      exact Move.backtrackFwd s e (q.append r)
  | backtrackBwd s e q =>
      simp only [append_assoc]
      exact Move.backtrackBwd s e (q.append r)
  | triangle s t q =>
      simp only [append_assoc]
      exact Move.triangle s t (q.append r)

theorem Move.append_left {a b c : V} {q q' : X.EdgePath b c} (h : Move q q')
    (s : X.EdgePath a b) : Move (s.append q) (s.append q') := by
  cases h with
  | backtrackFwd p e r =>
      simp only [← append_assoc]
      exact Move.backtrackFwd (s.append p) e r
  | backtrackBwd p e r =>
      simp only [← append_assoc]
      exact Move.backtrackBwd (s.append p) e r
  | triangle p t r =>
      simp only [← append_assoc]
      exact Move.triangle (s.append p) t r

theorem Homotopic.append_right {a b c : V} {p p' : X.EdgePath a b} (h : Homotopic p p')
    (r : X.EdgePath b c) : Homotopic (p.append r) (p'.append r) := by
  have h' : Relation.EqvGen Move p p' := h
  clear h
  induction h' with
  | rel _ _ hm => exact Relation.EqvGen.rel _ _ (hm.append_right r)
  | refl _ => exact Relation.EqvGen.refl _
  | symm _ _ _ ih => exact Relation.EqvGen.symm _ _ ih
  | trans _ _ _ _ _ ih₁ ih₂ => exact Relation.EqvGen.trans _ _ _ ih₁ ih₂

theorem Homotopic.append_left {a b c : V} {q q' : X.EdgePath b c} (h : Homotopic q q')
    (s : X.EdgePath a b) : Homotopic (s.append q) (s.append q') := by
  have h' : Relation.EqvGen Move q q' := h
  clear h
  induction h' with
  | rel _ _ hm => exact Relation.EqvGen.rel _ _ (hm.append_left s)
  | refl _ => exact Relation.EqvGen.refl _
  | symm _ _ _ ih => exact Relation.EqvGen.symm _ _ ih
  | trans _ _ _ _ _ ih₁ ih₂ => exact Relation.EqvGen.trans _ _ _ ih₁ ih₂

/-- Homotopy is a congruence for concatenation. -/
theorem Homotopic.congr_append {a b c : V} {p p' : X.EdgePath a b} {q q' : X.EdgePath b c}
    (hp : Homotopic p p') (hq : Homotopic q q') : Homotopic (p.append q) (p'.append q') :=
  (hp.append_right q).trans (hq.append_left p')

theorem Homotopic.congr_fwd {a b d : V} (e : X.edge a b) {q q' : X.EdgePath b d}
    (h : Homotopic q q') : Homotopic (fwd e q) (fwd e q') :=
  h.append_left (fwd e (nil b))

theorem Homotopic.congr_bwd {a b d : V} (e : X.edge b a) {q q' : X.EdgePath b d}
    (h : Homotopic q q') : Homotopic (bwd e q) (bwd e q') :=
  h.append_left (bwd e (nil b))

/-- Backtracking along a forward-then-backward traversal. -/
theorem homotopic_backtrackFwd {a b d : V} (e : X.edge a b) (q : X.EdgePath a d) :
    Homotopic (fwd e (bwd e q)) q :=
  (Move.backtrackFwd (nil a) e q).homotopic

/-- Backtracking along a backward-then-forward traversal. -/
theorem homotopic_backtrackBwd {a b d : V} (e : X.edge b a) (q : X.EdgePath a d) :
    Homotopic (bwd e (fwd e q)) q :=
  (Move.backtrackBwd (nil a) e q).homotopic

/-- Passage across one ordered triangle `(a,b,c)`: `(a,b)·(b,c) ≃ (a,c)`. -/
theorem homotopic_triangle {a b c d : V} (t : X.tri a b c) (q : X.EdgePath c d) :
    Homotopic (fwd (X.tri_edge01 t) (fwd (X.tri_edge12 t) q)) (fwd (X.tri_edge02 t) q) :=
  (Move.triangle (nil a) t q).homotopic

/-- Passage across one ordered triangle `(a,b,c)`: `(a,c)·(b,c)⁻¹ ≃ (a,b)`.  A fan over a
backward traversal uses this move (Khanh, tex l.539). -/
theorem homotopic_triangle_fwd02_bwd12 {a b c d : V} (t : X.tri a b c) (q : X.EdgePath b d) :
    Homotopic (fwd (X.tri_edge02 t) (bwd (X.tri_edge12 t) q)) (fwd (X.tri_edge01 t) q) :=
  (homotopic_triangle t (bwd (X.tri_edge12 t) q)).symm.trans
    ((homotopic_backtrackFwd (X.tri_edge12 t) q).congr_fwd (X.tri_edge01 t))

/-- A path followed by its reverse is null-homotopic. -/
theorem append_reverse_homotopic : ∀ {a b : V} (p : X.EdgePath a b),
    Homotopic (p.append p.reverse) (nil a)
  | _, _, nil v => Homotopic.refl (nil v)
  | _, _, fwd e p => by
      rw [reverse_fwd, fwd_append, ← append_assoc]
      exact Homotopic.trans
        (((append_reverse_homotopic p).append_right (bwd e (nil _))).congr_fwd e)
        (homotopic_backtrackFwd e (nil _))
  | _, _, bwd e p => by
      rw [reverse_bwd, bwd_append, ← append_assoc]
      exact Homotopic.trans
        (((append_reverse_homotopic p).append_right (fwd e (nil _))).congr_bwd e)
        (homotopic_backtrackBwd e (nil _))

end EdgePath

/-- **Combinatorial simple connectivity** (the form used by the Brown presentation lane LVBrown).
An ordered 2-complex is simply connected when it is connected and every edge loop is homotopic
to the constant path by backtracking and passages across triangles (Khanh, tex l.460). -/
def SimplyConnected : Prop :=
  X.Connected ∧ ∀ (v : V) (loop : X.EdgePath v v), EdgePath.Homotopic loop (EdgePath.nil v)

variable {X} in
/-- In a simply connected complex any two edge paths with the same endpoints are homotopic. -/
theorem SimplyConnected.homotopic (hX : X.SimplyConnected) {a b : V} (p q : X.EdgePath a b) :
    EdgePath.Homotopic p q := by
  have hq : EdgePath.Homotopic (q.reverse.append q) (EdgePath.nil b) := by
    have h := EdgePath.append_reverse_homotopic q.reverse
    rwa [EdgePath.reverse_reverse] at h
  have h1 : EdgePath.Homotopic (p.append (q.reverse.append q)) p := by
    have h := hq.symm.append_left p
    rw [EdgePath.append_nil] at h
    exact h.symm
  rw [← EdgePath.append_assoc] at h1
  exact h1.symm.trans ((hX.2 a (p.append q.reverse)).append_right q)

end OrderedTwoComplex

#audit_axioms GroupApproximation.Full.LVFrame.OrderedTwoComplex.SimplyConnected

end GroupApproximation.Full.LVFrame
