import GroupApproximation.Pestov91.LEFCrossedProduct
import GroupApproximation.Meta.AxiomGuard
import Mathlib.Data.Matrix.Basis
import Mathlib.Data.ZMod.Basic
import Mathlib.LinearAlgebra.Matrix.Reindex

/-!
# `simple_kazhdan_sofic_group.tex`, proof of `thm:main`: the periodic models generate `M_N(F₂)`

`simple_kazhdan_sofic_group.tex` at 696c4b602, "Proof of Theorem~\ref{thm:main}", tex 268–271:

> The shifts $T^ty_\ell$, $0\le t<N_\ell$, are distinct, so products of the $P^iD_\ell(e_a)P^{-i}$
> give every diagonal matrix unit, and with $P$ every matrix unit. So $\varphi_\ell(S)$ generates
> $M_{N_\ell}(\F_2)$, and Theorem~\ref{thm:general} applies.

For a cyclic word `c : ZMod N → A` with pairwise distinct translates, `P = shiftMatrix 1` and the
letter indicators `D(e_a) = diag(1_{c(t) = a})` are considered.

* `shiftMatrix_mem_closure`: every power `P^i`, `i ∈ ℤ`, lies in the subring generated by
  `P, P⁻¹` and the `D(e_a)`;
* `shiftMatrix_mul_diagonal_mul_shiftMatrix_neg`: `P^i D(d) P^{-i} = D(d(· - i))`;
* `diagonal_prod_mem_closure`: products of the conjugates `P^iD(e_a)P^{-i}` are diagonal indicators
  of finite intersections of translated letter conditions;
* `single_self_mem_closure`: distinct translates give every diagonal matrix unit;
* `single_mem_closure`: with `P`, every matrix unit;
* `subring_closure_periodicGenerators_eq_top`: the generated subring is `M_N(F₂)`;
* `subring_closure_image_eq_top`: generation passes through a ring isomorphism, for the reindexing
  `ZMod N ≃ Fin N`.
-/

namespace GroupApproximation

namespace SimpleKazhdanSofic

open Matrix Pestov91

section PeriodicUnits

variable {A : Type*} [DecidableEq A] {N : ℕ} [NeZero N]

/-- The letter indicator `D(e_a) = diag(1_{c(t) = a})` along a cyclic word `c`. -/
def letterDiagonal (c : ZMod N → A) (a : A) : Matrix (ZMod N) (ZMod N) (ZMod 2) :=
  diagonal fun t => if c t = a then 1 else 0

/-- The images of `u`, `u⁻¹` and the letter indicators: `P`, `P⁻¹` and the `D(e_a)`. -/
def periodicGenerators (c : ZMod N → A) : Set (Matrix (ZMod N) (ZMod N) (ZMod 2)) :=
  {shiftMatrix (ZMod 2) N 1, shiftMatrix (ZMod 2) N (-1)} ∪ Set.range (letterDiagonal c)

variable (c : ZMod N → A)

theorem shiftMatrix_mem_closure (i : ℤ) :
    shiftMatrix (ZMod 2) N i ∈ Subring.closure (periodicGenerators c) := by
  induction i using Int.induction_on with
  | zero =>
      rw [shiftMatrix_zero]
      exact Subring.one_mem _
  | succ i ih =>
      rw [shiftMatrix_add (i : ℤ) 1]
      exact Subring.mul_mem _ ih (Subring.subset_closure (Or.inl (Or.inl rfl)))
  | pred i ih =>
      rw [show -(i : ℤ) - 1 = -(i : ℤ) + (-1) by ring, shiftMatrix_add]
      exact Subring.mul_mem _ ih (Subring.subset_closure (Or.inl (Or.inr rfl)))

/-- `P^i D(d) P^{-i} = D(d(· - i))`. -/
theorem shiftMatrix_mul_diagonal_mul_shiftMatrix_neg (i : ℤ) (d : ZMod N → ZMod 2) :
    shiftMatrix (ZMod 2) N i * diagonal d * shiftMatrix (ZMod 2) N (-i) =
      diagonal fun t => d (t - (i : ZMod N)) := by
  rw [shiftMatrix_mul_diagonal, mul_assoc, ← shiftMatrix_add, add_neg_cancel, shiftMatrix_zero,
    mul_one]

/-- The conjugate `P^{-i} D(e_a) P^{i}` is the indicator `diag(1_{c(t + i) = a})` (tex 269). -/
theorem translatedLetter_mem_closure (i : ZMod N) (a : A) :
    (diagonal fun t => if c (t + i) = a then (1 : ZMod 2) else 0) ∈
      Subring.closure (periodicGenerators c) := by
  have h := shiftMatrix_mul_diagonal_mul_shiftMatrix_neg (N := N) (-((i.val : ℕ) : ℤ))
    (fun t => if c t = a then (1 : ZMod 2) else 0)
  have hfun : (fun t : ZMod N =>
      (fun t => if c t = a then (1 : ZMod 2) else 0) (t - (((-((i.val : ℕ) : ℤ)) : ℤ) : ZMod N))) =
      fun t => if c (t + i) = a then (1 : ZMod 2) else 0 := by
    funext t
    simp only [Int.cast_neg, Int.cast_natCast, ZMod.natCast_zmod_val, sub_neg_eq_add]
  rw [hfun] at h
  rw [← h]
  exact Subring.mul_mem _ (Subring.mul_mem _ (shiftMatrix_mem_closure c _)
    (Subring.subset_closure (Or.inr ⟨a, rfl⟩))) (shiftMatrix_mem_closure c _)

/-- Products of the conjugates are the diagonal indicators of finite intersections (tex 269). -/
theorem diagonal_prod_mem_closure (t₀ : ZMod N) (s : Finset (ZMod N)) :
    (diagonal fun t => ∏ i ∈ s, if c (t + i) = c (t₀ + i) then (1 : ZMod 2) else 0) ∈
      Subring.closure (periodicGenerators c) := by
  induction s using Finset.induction_on with
  | empty =>
      simp only [Finset.prod_empty]
      rw [diagonal_one]
      exact Subring.one_mem _
  | insert i s hi ih =>
      have hsplit : (diagonal fun t => ∏ j ∈ insert i s,
          if c (t + j) = c (t₀ + j) then (1 : ZMod 2) else 0) =
          (diagonal fun t => if c (t + i) = c (t₀ + i) then (1 : ZMod 2) else 0) *
            diagonal fun t => ∏ j ∈ s, if c (t + j) = c (t₀ + j) then (1 : ZMod 2) else 0 := by
        rw [diagonal_mul_diagonal]
        congr 1
        funext t
        rw [Finset.prod_insert hi]
      rw [hsplit]
      exact Subring.mul_mem _ (translatedLetter_mem_closure c i _) ih

/-- tex 268–269: "The shifts $T^ty_\ell$ are distinct, so products of the $P^iD_\ell(e_a)P^{-i}$ give
every diagonal matrix unit". -/
theorem single_self_mem_closure (hdist : ∀ t t' : ZMod N, (∀ i : ZMod N, c (t + i) = c (t' + i)) → t = t')
    (t₀ : ZMod N) : single t₀ t₀ (1 : ZMod 2) ∈ Subring.closure (periodicGenerators c) := by
  have hd : (fun t => ∏ i ∈ (Finset.univ : Finset (ZMod N)),
      if c (t + i) = c (t₀ + i) then (1 : ZMod 2) else 0) = Pi.single t₀ 1 := by
    funext t
    by_cases ht : t = t₀
    · subst ht
      simp
    · obtain ⟨i, hi⟩ : ∃ i : ZMod N, c (t + i) ≠ c (t₀ + i) := by
        by_contra hcon
        exact ht (hdist t t₀ fun i => not_not.1 fun h => hcon ⟨i, h⟩)
      rw [Pi.single_eq_of_ne ht, Finset.prod_eq_zero (Finset.mem_univ i) (if_neg hi)]
  have h := diagonal_prod_mem_closure c t₀ Finset.univ
  rw [hd, diagonal_single] at h
  exact h

/-- tex 269–270: "and with $P$ every matrix unit". -/
theorem single_mem_closure (hdist : ∀ t t' : ZMod N, (∀ i : ZMod N, c (t + i) = c (t' + i)) → t = t')
    (s t : ZMod N) : single s t (1 : ZMod 2) ∈ Subring.closure (periodicGenerators c) := by
  set j : ℤ := (((s - t).val : ℕ) : ℤ)
  have hj : t + (j : ZMod N) = s := by
    simp only [j, Int.cast_natCast, ZMod.natCast_zmod_val, add_sub_cancel]
  have heq : shiftMatrix (ZMod 2) N j * single t t (1 : ZMod 2) = single s t 1 := by
    rw [← diagonal_single, shiftMatrix_mul_diagonal]
    ext a b
    rw [diagonal_mul_shiftMatrix_apply]
    simp only [single, of_apply]
    by_cases hab : b + (j : ZMod N) = a
    · rw [if_pos hab]
      subst hab
      rw [add_sub_cancel_right]
      by_cases hbt : b = t
      · subst hbt
        rw [Pi.single_eq_same, if_pos ⟨hj.symm, rfl⟩]
      · rw [Pi.single_eq_of_ne hbt, if_neg fun h => hbt h.2.symm]
    · rw [if_neg hab, if_neg]
      rintro ⟨rfl, rfl⟩
      exact hab hj
  rw [← heq]
  exact Subring.mul_mem _ (shiftMatrix_mem_closure c j) (single_self_mem_closure c hdist t)

/-- tex 270: "So $\varphi_\ell(S)$ generates $M_{N_\ell}(\F_2)$": `P`, `P⁻¹` and the letter indicators
of a cyclic word with distinct translates generate `M_N(F₂)`. -/
theorem subring_closure_periodicGenerators_eq_top
    (hdist : ∀ t t' : ZMod N, (∀ i : ZMod N, c (t + i) = c (t' + i)) → t = t') :
    Subring.closure (periodicGenerators c) = ⊤ := by
  refine eq_top_iff.2 fun x _ => ?_
  rw [matrix_eq_sum_single x]
  refine Subring.sum_mem _ fun i _ => Subring.sum_mem _ fun j _ => ?_
  have hr : ∀ r : ZMod 2, r = 0 ∨ r = 1 := by decide
  rcases hr (x i j) with h | h
  · rw [h, single_zero]
    exact Subring.zero_mem _
  · rw [h]
    exact single_mem_closure c hdist i j

end PeriodicUnits

/-- Generation passes through a ring isomorphism, used for the reindexing `ZMod N ≃ Fin N`. -/
theorem subring_closure_image_eq_top {R S : Type*} [Ring R] [Ring S] (f : R ≃+* S) {s : Set R}
    (hs : Subring.closure s = ⊤) : Subring.closure (f '' s) = ⊤ := by
  have h := RingHom.map_closure (f : R →+* S) s
  rw [hs] at h
  refine eq_top_iff.2 fun y _ => ?_
  have hy : y ∈ (⊤ : Subring R).map (f : R →+* S) :=
    Subring.mem_map.2 ⟨f.symm y, Subring.mem_top _, f.apply_symm_apply y⟩
  rw [h] at hy
  exact hy

end SimpleKazhdanSofic

end GroupApproximation

#audit_axioms GroupApproximation.SimpleKazhdanSofic.single_mem_closure
#audit_axioms GroupApproximation.SimpleKazhdanSofic.subring_closure_periodicGenerators_eq_top
#audit_axioms GroupApproximation.SimpleKazhdanSofic.subring_closure_image_eq_top
