import GroupApproximation.Manuscript.SimpleKazhdanSofic.Host.Setup
import GroupApproximation.Meta.AxiomGuard

/-!
# `lem:host`: the objects, the action and the ring generators

`simple_kazhdan_sofic_group.tex`, `lem:host` (tex l.527–537) and the first paragraph of its proof
(tex l.540–550).

> (l.528–532) For a finitely generated group `Δ`, let `Δ` act on `Ω = F_2^Δ` by
> `(δx)(η) = x(δ⁻¹η)`, let `Λ` be the group of maps `x ↦ δx + c` with `δ ∈ Δ` and `c` finitely
> supported, and put `R_Δ = LC(Ω, F_2) ⋊ Λ` and `G_Δ = EL_3(R_Δ)`.
>
> (l.541–550) The group `Λ` is generated by `Δ` and the map `z` adding `1` at `e`, and its orbits
> contain the dense sets `x + ⊕_Δ F_2`. If `(δ,c) ≠ (e,0)`, the fixed points of `x ↦ δx + c`
> satisfy `x(η) = x(δ⁻¹η) + c(η)` for all `η`. In every cylinder over a finite set `W` this fails
> at some point [...]. So the action is minimal and topologically free. The ring `R_Δ` is generated
> by `1`, the units `u_ξ^{±1}` for `ξ` in a finite generating set of `Λ`, and the indicator `e_U`
> of `U = {x : x(e) = 1}`.
>
> (l.585–586) As `Δ ≤ Λ`, the group `[Λ,Λ]` contains `[Δ,Δ]`.

## Objects

* `Ω` is `Lamplighter.LampSpace Δ = Δ → ZMod 2` with the product topology.
* `Λ` is `Lamplighter.LampAffine Δ = Multiplicative (Δ →₀ ZMod 2) ⋊ Δ`, where `ξ = (c, δ)` acts by
  `x ↦ δx + c`. The action is faithful, so `Λ` is the printed group of maps.
* `R_Δ` is `Lamplighter.LampRing Δ = ClopenGroupCrossedProduct Λ Ω (ZMod 2)`, and `u_ξ` is
  `ClopenGroupCrossedProduct.unit Λ Ω (ZMod 2) ξ`.
* `z` is `Lamplighter.lampAdd Δ`, and `Δ ≤ Λ` is `SemidirectProduct.inr`.

## Contents

* `lamplighterHostObjects`: the action formulas, every map `x ↦ δx + c` lies in `Λ`, and faithfulness.
* `lamplighterMinimalTopologicallyFree`: the generation of `Λ` by `Δ` and `z`, the dense orbit sets,
  the fixed-point equation, the moved point in every cylinder, minimality and topological freeness.
* `lamplighterRingGeneration`: the printed generators of `R_Δ`.
* `lamplighterCommutatorContainment`: `Δ ≤ Λ` and `[Δ,Δ] ≤ [Λ,Λ]`.

All four come from `Host.Setup` and `LamplighterAction`.
-/

namespace GroupApproximation.Full.SK10

open GroupApproximation.SimpleKazhdanSofic
open GroupApproximation.SimpleKazhdanSofic.Lamplighter

/-- **The objects of `lem:host`** (`simple_kazhdan_sofic_group.tex`, tex l.528–532). `δ ∈ Δ` acts on
`Ω = F_2^Δ` by `(δx)(η) = x(δ⁻¹η)`. Every map `x ↦ δx + c` with `c` finitely supported is the action
of an element of `Λ`, and every element `ξ` of `Λ` acts by such a map, with `δ = ξ.right` and
`c = ξ.left`. Distinct elements of `Λ` act by distinct maps. -/
theorem lamplighterHostObjects (Δ : Type) [Group Δ] :
    (∀ (δ : Δ) (x : LampSpace Δ) (η : Δ),
      ((SemidirectProduct.inr : Δ →* LampAffine Δ) δ • x) η = x (δ⁻¹ * η)) ∧
    (∀ (δ : Δ) (c : Δ →₀ ZMod 2), ∃ ξ : LampAffine Δ,
      ∀ (x : LampSpace Δ) (η : Δ), (ξ • x) η = x (δ⁻¹ * η) + c η) ∧
    (∀ (ξ : LampAffine Δ) (x : LampSpace Δ) (η : Δ),
      (ξ • x) η = x (ξ.right⁻¹ * η) + Multiplicative.toAdd ξ.left η) ∧
    Function.Injective (fun (ξ : LampAffine Δ) (x : LampSpace Δ) => ξ • x) := by
  obtain ⟨hinr, hmaps, hformula, hinj, -⟩ := Host.manuscriptSentence_hostDefinitions Δ
  exact ⟨hinr, hmaps, hformula, hinj⟩

#audit_axioms GroupApproximation.Full.SK10.lamplighterHostObjects

/-- **`Λ` acts minimally and topologically freely on `Ω`** (`simple_kazhdan_sofic_group.tex`,
tex l.541–547), for an infinite group `Δ`. The clauses follow the printed proof:
* `Λ` is generated by `Δ` and the map `z` adding `1` at `e`;
* the orbit of every `x` contains the dense set `x + ⊕_Δ F_2`;
* `ξ = (c, δ)` fixes `x` exactly when `x(η) = x(δ⁻¹η) + c(η)` for all `η`;
* for `ξ ≠ 1`, every cylinder over a finite set `W` contains a point moved by `ξ`;
* so the action is minimal and topologically free (no nontrivial element fixes a nonempty open
  set pointwise). -/
theorem lamplighterMinimalTopologicallyFree (Δ : Type) [Group Δ] [Infinite Δ] :
    Subgroup.closure
        (insert (lampAdd Δ) (Set.range (SemidirectProduct.inr : Δ →* LampAffine Δ))) = ⊤ ∧
    (∀ (x : LampSpace Δ) (η : Δ),
      (lampAdd Δ • x) η = x η + Finsupp.single (1 : Δ) (1 : ZMod 2) η) ∧
    (∀ x : LampSpace Δ,
      Dense {y : LampSpace Δ | ∃ c : Δ →₀ ZMod 2, ∀ η, y η = x η + c η} ∧
        {y : LampSpace Δ | ∃ c : Δ →₀ ZMod 2, ∀ η, y η = x η + c η} ⊆
          MulAction.orbit (LampAffine Δ) x) ∧
    (∀ (ξ : LampAffine Δ) (x : LampSpace Δ),
      ξ • x = x ↔ ∀ η, x η = x (ξ.right⁻¹ * η) + Multiplicative.toAdd ξ.left η) ∧
    (∀ ξ : LampAffine Δ, ξ ≠ 1 → ∀ (y : LampSpace Δ) (W : Finset Δ),
      ∃ x : LampSpace Δ, (∀ a ∈ W, x a = y a) ∧ ξ • x ≠ x) ∧
    MulAction.IsMinimal (LampAffine Δ) (LampSpace Δ) ∧
    IsTopologicallyFreeAction (LampAffine Δ) (LampSpace Δ) := by
  obtain ⟨hgen, hz, hdense⟩ := Host.manuscriptSentence_lambdaGenerationDenseOrbits Δ
  exact ⟨hgen, hz, hdense, Lamplighter.smul_eq_self_iff Δ,
    fun ξ hξ y W => Lamplighter.exists_moved_of_cylinder Δ ξ hξ y W, Lamplighter.isMinimal Δ,
    Lamplighter.isTopologicallyFree Δ⟩

#audit_axioms GroupApproximation.Full.SK10.lamplighterMinimalTopologicallyFree

/-- **The generators of `R_Δ`** (`simple_kazhdan_sofic_group.tex`, tex l.548–550), for a finitely
generated group `Δ`. `Λ` has a finite generating set. For every generating set `T` of `Λ`, the ring
`R_Δ = LC(Ω, F_2) ⋊ Λ` is generated by `1`, the units `u_ξ^{±1}` with `ξ ∈ T`, and the indicator
`e_U` of `U = {x : x(e) = 1}`. -/
theorem lamplighterRingGeneration (Δ : Type) [Group Δ] (hΔ : Group.FG Δ) :
    (∃ T : Set (LampAffine Δ), T.Finite ∧ Subgroup.closure T = ⊤) ∧
    ∀ T : Set (LampAffine Δ), Subgroup.closure T = ⊤ →
      Subring.closure
        (insert (1 : LampRing Δ)
          ((fun s => (ClopenGroupCrossedProduct.unit (LampAffine Δ) (LampSpace Δ) (ZMod 2) s :
              LampRing Δ)) '' T ∪
            (fun s => (((ClopenGroupCrossedProduct.unit (LampAffine Δ) (LampSpace Δ) (ZMod 2) s)⁻¹ :
              (LampRing Δ)ˣ) : LampRing Δ)) '' T ∪
            {ClopenGroupCrossedProduct.coeff (LampAffine Δ) (LampSpace Δ) (ZMod 2)
              (LocallyConstant.charFn (ZMod 2) (Lamplighter.isClopen_coordOne Δ))})) = ⊤ :=
  Host.manuscriptSentence_ringGenerators Δ hΔ

#audit_axioms GroupApproximation.Full.SK10.lamplighterRingGeneration

/-- **`Δ ≤ Λ`, and `[Λ,Λ]` contains `[Δ,Δ]`** (`simple_kazhdan_sofic_group.tex`, tex l.585–586). -/
theorem lamplighterCommutatorContainment (Δ : Type) [Group Δ] :
    Function.Injective (SemidirectProduct.inr : Δ →* LampAffine Δ) ∧
      (commutator Δ).map (SemidirectProduct.inr : Δ →* LampAffine Δ) ≤
        commutator (LampAffine Δ) :=
  Host.manuscriptSentence_commutatorContainment Δ

#audit_axioms GroupApproximation.Full.SK10.lamplighterCommutatorContainment

end GroupApproximation.Full.SK10
