import GroupApproximation.Manuscript.SimpleKazhdanSofic.Full.LemmaNN.LevelAction
import GroupApproximation.Manuscript.SimpleKazhdanSofic.Full.LemmaNN.Ultraproduct
import Mathlib.Order.Filter.Cofinite
import Mathlib.Order.Filter.AtTopBot.Defs
import Mathlib.Order.Interval.Finset.Nat
import Mathlib.Data.Countable.Defs
import Mathlib.Data.Fintype.Perm
import Mathlib.Data.Finite.Prod
import Mathlib.Algebra.Group.Pi.Lemmas
import Mathlib.Algebra.Group.Hom.Basic
import Mathlib.Algebra.Group.Subgroup.Lattice
import Mathlib.Tactic.Choose

/-!
# `lem:nn`: the level embedding of `Γ` into `[Δ, Δ]`

`simple_kazhdan_sofic_group.tex`, proof of `lem:nn` (l.494–525):

> There are finite groups Q_k and maps μ_k : Γ → Q_k that are injective on {1, γ_1, …, γ_k} and preserve the products
> that stay in this set. […] In the algebraic ultraproduct over ω of the symmetric groups of these sets, sending γ to the
> class of the permutations multiplying the first coordinate on the level 0 by μ_k(γ) and acting trivially elsewhere is
> a homomorphism, injective as μ_k(γ) ≠ 1 for γ ≠ 1 and large k. It sends γ_j to w_j(a,b), where a = (a_k)_k and
> b = (b_k)_k, so Γ ≤ [Δ,Δ] for the group Δ generated by a and b. […] Δ is LEF, and Δ is infinite because it contains Γ.

This file provides:

* `Models`: an enumeration `Γ = {γ_1, γ_2, …}` and the finite models `μ_k : Γ → Q_k` on `{1, γ_1, …, γ_k}`
  (`models_nonempty`, from textbook LEF and countability);
* `embedding`: the homomorphism `Γ → ∏_ω Sym(Q_k × ℤ/m_k × ℤ/4^{k+1})`, `embedding_injective`, and `embedding_γ`:
  it sends `γ_j` to `w_j(a, b)`;
* `Delta`, the subgroup generated by `a` and `b`, with `closure_generators`, `embeddingΔ_injective`,
  `embeddingΔ_mem_commutator` (`Γ ≤ [Δ, Δ]`), `isLEF_delta` and `infinite_delta`.

The ultrafilter `ω` is any ultrafilter on `ℕ` finer than the cofinite filter, so that "large `k`" holds `ω`-almost
everywhere.
-/

namespace GroupApproximation.Full.SK09

open Filter
open scoped commutatorElement

section Models

variable {Γ : Type} [Group Γ]

/-- The test set `{1, γ_1, …, γ_k}` (`lem:nn`, simple_kazhdan_sofic_group.tex l.497–498). -/
noncomputable def testSet (γ : ℕ → Γ) (k : ℕ) : Finset Γ := by
  classical exact insert 1 ((Finset.Icc 1 k).image γ)

theorem one_mem_testSet (γ : ℕ → Γ) (k : ℕ) : 1 ∈ testSet γ k := by
  classical
  unfold testSet
  exact Finset.mem_insert_self _ _

theorem mem_testSet (γ : ℕ → Γ) {j k : ℕ} (h1 : 1 ≤ j) (h2 : j ≤ k) : γ j ∈ testSet γ k := by
  classical
  unfold testSet
  exact Finset.mem_insert_of_mem (Finset.mem_image_of_mem γ (Finset.mem_Icc.2 ⟨h1, h2⟩))

end Models

/-- **An enumeration `Γ = {γ_1, γ_2, …}` and finite groups `Q_k` with maps `μ_k : Γ → Q_k` that are injective on
`{1, γ_1, …, γ_k}` and preserve the products that stay in this set** (`lem:nn`, simple_kazhdan_sofic_group.tex
l.495–499). -/
structure Models (Γ : Type) [Group Γ] where
  γ : ℕ → Γ
  surj : ∀ x : Γ, ∃ j, 1 ≤ j ∧ γ j = x
  Q : ℕ → FiniteGroupModel
  μ : ∀ k, Γ → Q k
  inj : ∀ k, Set.InjOn (μ k) (testSet γ k : Set Γ)
  mul : ∀ k, ∀ x ∈ testSet γ k, ∀ y ∈ testSet γ k, x * y ∈ testSet γ k →
    μ k (x * y) = μ k x * μ k y

section ModelsNonempty

variable {Γ : Type} [Group Γ]

/-- A countable LEF group has an enumeration and finite models on its test sets (`lem:nn`, l.495–499). -/
theorem models_nonempty [Countable Γ] (hΓ : IsTextbookLEF Γ) : Nonempty (Models Γ) := by
  obtain ⟨e, he⟩ := exists_surjective_nat Γ
  have surj : ∀ x : Γ, ∃ j, 1 ≤ j ∧ e (j - 1) = x := by
    intro x
    obtain ⟨n, rfl⟩ := he x
    refine ⟨n + 1, Nat.le_add_left 1 n, ?_⟩
    rw [Nat.add_sub_cancel]
  choose Q μ inj mul using fun k => hΓ (testSet (fun j => e (j - 1)) k)
  exact ⟨⟨fun j => e (j - 1), surj, Q, μ, inj, mul⟩⟩

/-- The models send `1` to `1`, as `1 * 1 = 1` stays in the test set. -/
theorem Models.μ_one (M : Models Γ) (k : ℕ) : M.μ k 1 = 1 := by
  have h1 : (1 : Γ) * 1 ∈ testSet M.γ k := by
    rw [one_mul]
    exact one_mem_testSet _ _
  have h := M.mul k 1 (one_mem_testSet _ _) 1 (one_mem_testSet _ _) h1
  have h2 : M.μ k 1 = M.μ k 1 * M.μ k 1 := (congrArg (M.μ k) (one_mul (1 : Γ)).symm).trans h
  exact mul_left_cancel (h2.symm.trans (mul_one _).symm)

end ModelsNonempty

/-- "Large `k`" holds almost everywhere for an ultrafilter finer than the cofinite filter. -/
theorem eventually_ge_of_le_cofinite {ω : Ultrafilter ℕ} (hω : (ω : Filter ℕ) ≤ cofinite) (K : ℕ) :
    ∀ᶠ k in (ω : Filter ℕ), K ≤ k := by
  have h : ∀ᶠ k in (cofinite : Filter ℕ), K ≤ k := by
    rw [Nat.cofinite_eq_atTop]
    exact eventually_ge_atTop K
  exact Filter.Eventually.filter_mono hω h

section Embedding

variable {Γ : Type} [Group Γ] (M : Models Γ) (ω : Ultrafilter ℕ)

/-- The set `Q_k × ℤ/m_k × ℤ/4^{k+1}` (`lem:nn`, simple_kazhdan_sofic_group.tex l.504–505). -/
abbrev LevelSet (k : ℕ) : Type :=
  (M.Q k × ZMod (Fintype.card (M.Q k))) × ZMod (4 ^ (k + 1))

/-- The symmetric group of `Q_k × ℤ/m_k × ℤ/4^{k+1}` (`lem:nn`, l.518). -/
abbrev SymX (k : ℕ) : Type :=
  Equiv.Perm (LevelSet M k)

/-- `a = (a_k)_k` (`lem:nn`, l.505–508, l.521). -/
def aSeq : ∀ k, SymX M k :=
  fun k => aPerm (M.Q k) k fun j => M.μ k (M.γ j)

/-- `b = (b_k)_k` (`lem:nn`, l.504–505, l.521). -/
def bSeq : ∀ k, SymX M k :=
  fun k => bPerm (M.Q k) k

/-- The permutations multiplying the first coordinate on the level `0` by `μ_k(x)` and acting trivially elsewhere
(`lem:nn`, l.518–520). -/
def embedSeq (x : Γ) : ∀ k, SymX M k :=
  fun k => levelZeroMul (M.Q k) k (M.μ k x)

/-- **Sending `γ` to the class of the permutations multiplying the first coordinate on the level `0` by `μ_k(γ)` is a
homomorphism** (`lem:nn`, simple_kazhdan_sofic_group.tex l.517–520). -/
noncomputable def embedding (hω : (ω : Filter ℕ) ≤ cofinite) : Γ →* Ultraproduct ω (SymX M) where
  toFun x := QuotientGroup.mk (embedSeq M x)
  map_one' := by
    refine (mk_eq_mk_iff ω (SymX M) (g := embedSeq M 1) (h := 1)).2
      (Filter.Eventually.of_forall fun k => ?_)
    show levelZeroMul (M.Q k) k (M.μ k 1) = 1
    rw [M.μ_one, levelZeroMul_one]
  map_mul' x y := by
    obtain ⟨j₁, hj₁, rfl⟩ := M.surj x
    obtain ⟨j₂, hj₂, rfl⟩ := M.surj y
    obtain ⟨j₃, hj₃, h₃⟩ := M.surj (M.γ j₁ * M.γ j₂)
    show (QuotientGroup.mk (embedSeq M (M.γ j₁ * M.γ j₂)) : Ultraproduct ω (SymX M)) =
      QuotientGroup.mk (embedSeq M (M.γ j₁) * embedSeq M (M.γ j₂))
    refine (mk_eq_mk_iff ω (SymX M) (g := embedSeq M (M.γ j₁ * M.γ j₂))
      (h := embedSeq M (M.γ j₁) * embedSeq M (M.γ j₂))).2
      ((eventually_ge_of_le_cofinite hω (j₁ + j₂ + j₃)).mono fun k hk => ?_)
    show levelZeroMul (M.Q k) k (M.μ k (M.γ j₁ * M.γ j₂)) =
      levelZeroMul (M.Q k) k (M.μ k (M.γ j₁)) * levelZeroMul (M.Q k) k (M.μ k (M.γ j₂))
    have hm₁ : M.γ j₁ ∈ testSet M.γ k := mem_testSet M.γ (k := k) hj₁ (by omega)
    have hm₂ : M.γ j₂ ∈ testSet M.γ k := mem_testSet M.γ (k := k) hj₂ (by omega)
    have hm₃ : M.γ j₁ * M.γ j₂ ∈ testSet M.γ k := by
      rw [← h₃]
      exact mem_testSet M.γ (k := k) hj₃ (by omega)
    rw [M.mul k (M.γ j₁) hm₁ (M.γ j₂) hm₂ hm₃, levelZeroMul_mul]

/-- **Injective as `μ_k(γ) ≠ 1` for `γ ≠ 1` and large `k`** (`lem:nn`, simple_kazhdan_sofic_group.tex l.520–521). -/
theorem embedding_injective (hω : (ω : Filter ℕ) ≤ cofinite) :
    Function.Injective (embedding M ω hω) := by
  refine (injective_iff_map_eq_one (embedding M ω hω)).2 fun x hx => ?_
  obtain ⟨j, hj, rfl⟩ := M.surj x
  have h' : (QuotientGroup.mk (embedSeq M (M.γ j)) : Ultraproduct ω (SymX M)) =
      QuotientGroup.mk 1 := hx
  have h : ∀ᶠ k in (ω : Filter ℕ), levelZeroMul (M.Q k) k (M.μ k (M.γ j)) = 1 :=
    (mk_eq_mk_iff ω (SymX M) (g := embedSeq M (M.γ j)) (h := 1)).1 h'
  obtain ⟨k, hk, hk1⟩ := ((eventually_ge_of_le_cofinite hω j).and h).exists
  have hμ : M.μ k (M.γ j) = M.μ k 1 := by
    rw [eq_one_of_levelZeroMul_eq_one (M.Q k) k hk1, M.μ_one]
  exact M.inj k (mem_testSet M.γ (k := k) hj hk) (one_mem_testSet M.γ k) hμ

/-- **It sends `γ_j` to `w_j(a, b)`, where `a = (a_k)_k` and `b = (b_k)_k`** (`lem:nn`, simple_kazhdan_sofic_group.tex
l.521), since `w_j(a_k, b_k)` multiplies the first coordinate on the level `0` by `μ_k(γ_j)` for `k ≥ j`. -/
theorem embedding_γ (hω : (ω : Filter ℕ) ≤ cofinite) {j : ℕ} (hj : 1 ≤ j) :
    embedding M ω hω (M.γ j) =
      word j (QuotientGroup.mk (aSeq M) : Ultraproduct ω (SymX M)) (QuotientGroup.mk (bSeq M)) := by
  have hw : word j (QuotientGroup.mk (aSeq M) : Ultraproduct ω (SymX M)) (QuotientGroup.mk (bSeq M)) =
      QuotientGroup.mk (word j (aSeq M) (bSeq M)) :=
    (map_word (QuotientGroup.mk' (nullSubgroup ω (SymX M))) j (aSeq M) (bSeq M)).symm
  rw [hw]
  refine (mk_eq_mk_iff ω (SymX M) (g := embedSeq M (M.γ j)) (h := word j (aSeq M) (bSeq M))).2
    ((eventually_ge_of_le_cofinite hω j).mono fun k hk => ?_)
  have hk' : word j (aSeq M) (bSeq M) k = word j (aSeq M k) (bSeq M k) :=
    map_word (Pi.evalMonoidHom (SymX M) k) j (aSeq M) (bSeq M)
  show levelZeroMul (M.Q k) k (M.μ k (M.γ j)) = word j (aSeq M) (bSeq M) k
  rw [hk']
  exact (word_aPerm_bPerm (M.Q k) k (fun i => M.μ k (M.γ i)) hj hk).symm

/-- **`Δ`, the group generated by `a` and `b`** (`lem:nn`, simple_kazhdan_sofic_group.tex l.522). -/
def Delta : Subgroup (Ultraproduct ω (SymX M)) :=
  Subgroup.closure {QuotientGroup.mk (aSeq M), QuotientGroup.mk (bSeq M)}

theorem aSeq_mem_delta : (QuotientGroup.mk (aSeq M) : Ultraproduct ω (SymX M)) ∈ Delta M ω :=
  Subgroup.mem_closure_of_mem (Set.mem_insert _ _)

theorem bSeq_mem_delta : (QuotientGroup.mk (bSeq M) : Ultraproduct ω (SymX M)) ∈ Delta M ω :=
  Subgroup.mem_closure_of_mem (Set.mem_insert_of_mem _ (Set.mem_singleton _))

theorem conjPow_mem_delta (n : ℕ) :
    conjPow (QuotientGroup.mk (aSeq M) : Ultraproduct ω (SymX M)) (QuotientGroup.mk (bSeq M)) n ∈
      Delta M ω := by
  have ha := aSeq_mem_delta M ω
  have hb := bSeq_mem_delta M ω
  unfold conjPow
  exact mul_mem (mul_mem (inv_mem (pow_mem hb n)) ha) (pow_mem hb n)

theorem embedding_mem_delta (hω : (ω : Filter ℕ) ≤ cofinite) (x : Γ) :
    embedding M ω hω x ∈ Delta M ω := by
  obtain ⟨j, hj, rfl⟩ := M.surj x
  rw [embedding_γ M ω hω hj, word, commutatorElement_def]
  have hp := conjPow_mem_delta M ω (2 ^ (2 * j - 1))
  have hq := conjPow_mem_delta M ω (4 ^ j)
  exact mul_mem (mul_mem (mul_mem hp hq) (inv_mem hp)) (inv_mem hq)

/-- The embedding, with values in `Δ`. -/
noncomputable def embeddingΔ (hω : (ω : Filter ℕ) ≤ cofinite) : Γ →* Delta M ω where
  toFun x := ⟨embedding M ω hω x, embedding_mem_delta M ω hω x⟩
  map_one' := Subtype.ext (map_one (embedding M ω hω))
  map_mul' x y := Subtype.ext (map_mul (embedding M ω hω) x y)

theorem embeddingΔ_injective (hω : (ω : Filter ℕ) ≤ cofinite) :
    Function.Injective (embeddingΔ M ω hω) := by
  intro x y h
  have h' : embedding M ω hω x = embedding M ω hω y := congrArg Subtype.val h
  exact embedding_injective M ω hω h'

/-- **`Γ ≤ [Δ, Δ]`** (`lem:nn`, simple_kazhdan_sofic_group.tex l.521–522): `γ_j` goes to the commutator `w_j(a, b)` of
two elements of `Δ`. -/
theorem embeddingΔ_mem_commutator (hω : (ω : Filter ℕ) ≤ cofinite) (x : Γ) :
    embeddingΔ M ω hω x ∈ commutator (Delta M ω) := by
  obtain ⟨j, hj, rfl⟩ := M.surj x
  have hp := conjPow_mem_delta M ω (2 ^ (2 * j - 1))
  have hq := conjPow_mem_delta M ω (4 ^ j)
  have he : embeddingΔ M ω hω (M.γ j) = ⁅(⟨_, hp⟩ : Delta M ω), (⟨_, hq⟩ : Delta M ω)⁆ :=
    Subtype.ext (embedding_γ M ω hω hj)
  rw [he, commutator_def]
  exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)

/-- **`Δ` is generated by the two elements `a` and `b`** (`lem:nn`, l.522). -/
theorem closure_generators :
    Subgroup.closure ({⟨_, aSeq_mem_delta M ω⟩, ⟨_, bSeq_mem_delta M ω⟩} : Set (Delta M ω)) = ⊤ := by
  have hs : ({⟨_, aSeq_mem_delta M ω⟩, ⟨_, bSeq_mem_delta M ω⟩} : Set (Delta M ω)) =
      ((↑) : Delta M ω → Ultraproduct ω (SymX M)) ⁻¹'
        {QuotientGroup.mk (aSeq M), QuotientGroup.mk (bSeq M)} := by
    ext x
    rw [Set.mem_insert_iff, Set.mem_singleton_iff, Set.mem_preimage, Set.mem_insert_iff,
      Set.mem_singleton_iff]
    constructor
    · rintro (h | h)
      · exact Or.inl (congrArg Subtype.val h)
      · exact Or.inr (congrArg Subtype.val h)
    · rintro (h | h)
      · exact Or.inl (Subtype.ext h)
      · exact Or.inr (Subtype.ext h)
  rw [hs]
  exact Subgroup.closure_closure_coe_preimage

/-- **`Δ` is LEF** (`lem:nn`, simple_kazhdan_sofic_group.tex l.523–524): finitely many equations and inequalities that
hold in the ultraproduct hold in some coordinate. -/
theorem isLEF_delta : IsLEF (Delta M ω) :=
  isLEF_subgroup_ultraproduct ω (SymX M) (Delta M ω)

/-- **`Δ` is infinite because it contains `Γ`** (`lem:nn`, simple_kazhdan_sofic_group.tex l.524–525). -/
theorem infinite_delta [Infinite Γ] (hω : (ω : Filter ℕ) ≤ cofinite) : Infinite (Delta M ω) :=
  Infinite.of_injective _ (embeddingΔ_injective M ω hω)

end Embedding

end GroupApproximation.Full.SK09
