import GroupApproximation.Sofic.CentralInvolutionFinite
import GroupApproximation.Sofic.CliffordLampGroup

/-!
# Approximation properties of the Clifford lamp group

The presented Clifford lamp group is locally finite.  A finite collection of
lamps consists of involutions whose commutators lie in the order-two central
subgroup generated by the sign, so the generic central-involution finiteness
theorem applies.  Consequently the countable lamp groups used by the literal
witness are LEF, sofic, and operator-MF.
-/

namespace GroupApproximation
namespace CliffordLamp

open scoped commutatorElement

universe u

variable (X : Type u)

/-- **The Clifford lamp group is locally finite.** -/
theorem isLocallyFiniteGroup_cliffordLamp :
    IsLocallyFiniteGroup (LampGroup X) := by
  refine isLocallyFiniteGroup_of_central_involution
    (z := sign X) (T := Set.range (lamp X)) (sign_sq X) (sign_commute X) ?_ ?_ ?_
  · refine top_unique fun g _ ↦ mem_subgroup_of_sign_mem_of_lamp_mem X _ ?_ ?_ g
    · exact Subgroup.subset_closure (Set.mem_insert (sign X) _)
    · intro x
      exact Subgroup.subset_closure
        (Set.mem_insert_of_mem _ ⟨x, rfl⟩)
  · rintro _ ⟨x, rfl⟩
    exact lamp_sq X x
  · rintro _ ⟨x, rfl⟩ _ ⟨y, rfl⟩
    by_cases hxy : x = y
    · subst y
      change ⁅lamp X x, lamp X x⁆ ∈ Subgroup.zpowers (sign X)
      rw [commutatorElement_self]
      exact Subgroup.one_mem _
    · change ⁅lamp X x, lamp X y⁆ ∈ Subgroup.zpowers (sign X)
      rw [commutator_lamp_lamp X hxy]
      exact Subgroup.mem_zpowers (sign X)

end CliffordLamp
end GroupApproximation
