import GroupApproximation.Sofic.GreendlingerDehnCritical
import GroupApproximation.Computability.FreeGroupRedNil

/-!
# Free cancellation is nested

Both routes to the Greendlinger gate end at the same place: a count over the
cancellation pattern of a product of conjugates, of the kind a reduced van Kampen
diagram supplies.  What such a count stands on is *planarity* --- that the matched
pairs of a free reduction never cross --- and this file proves exactly that, in
the form the count can consume and with no hypothesis at all.

## The statement

`Dyck` is generated by two rules: the empty word is nested, and if `A` and `B`
are nested then so is `x :: (A ++ invLetter x :: B)` --- a letter, a nested block,
that letter's inverse, another nested block.  The theorem is

  `dyck_iff_mk_eq_one : Dyck W ↔ FreeGroup.mk W = 1`

so a word dies freely **exactly when** its cancellation is nested.  The forward
direction is a two-line induction.  The content is the converse, and it is one
lemma: `exists_split`, that a word `x :: W'` spelling the identity has its first
letter matched, with the two sides of the match each spelling the identity.

## Why this is planarity

A free reduction deletes adjacent inverse pairs, so when a pair is deleted
everything strictly between its two letters has already gone.  Two matched pairs
are therefore nested or disjoint, never interleaved --- which is the combinatorial
content of "the diagram of a product of conjugates can be drawn in the plane".
`exists_split` is that statement pulled back to the outermost pair, and `Dyck` is
its closure: the nesting forest of the whole word.

The proof of `exists_split` is an induction on length.  The first step of a
`FreeGroup.Red` derivation deletes some pair; if it is the pair at the very front
the split is immediate, and otherwise the induction hypothesis splits the
shortened word and the deleted pair is put back on whichever side of the split it
came from.  `mk` does not see it go back (`mk_pair_cancel`), which is what keeps
both sides spelling the identity.

Unconditional throughout: no small cancellation, no relators, nothing about
`DehnStep`.  This is a fact about free groups.
-/

namespace GroupApproximation
namespace SmallCancellationRouter

variable {α : Type*}

/-! ## Deleting a pair is invisible to `mk` -/

/-- A letter beside its inverse spells nothing. -/
theorem mk_pair_cancel (x : α × Bool) (B : List (α × Bool)) :
    FreeGroup.mk (x :: invLetter x :: B) = FreeGroup.mk B := by
  rw [mk_cons x (invLetter x :: B), mk_cons (invLetter x) B, ← mk_singleton_inv]
  group

/-- The same in context. -/
theorem mk_pair_cancel_append (A : List (α × Bool)) (x : α × Bool)
    (B : List (α × Bool)) :
    FreeGroup.mk (A ++ (x :: invLetter x :: B)) = FreeGroup.mk (A ++ B) := by
  rw [mk_append_mul, mk_append_mul, mk_pair_cancel]

/-! ## Mathlib's reduction step, inverted -/

/-- **The reduction step, as data.**  Stating it this way keeps the induction
below free of index unification, exactly as `dehnStep_iff` does for the Dehn
system. -/
theorem redStep_iff {W Z : List (α × Bool)} :
    FreeGroup.Red.Step W Z ↔
      ∃ L₁ L₂ : List (α × Bool), ∃ x : α × Bool,
        W = L₁ ++ (x :: invLetter x :: L₂) ∧ Z = L₁ ++ L₂ := by
  constructor
  · intro h
    cases h with
    | @not L₁ L₂ a b => exact ⟨L₁, L₂, (a, b), rfl, rfl⟩
  · rintro ⟨L₁, L₂, x, rfl, rfl⟩
    exact redStep_of_pair L₁ L₂ x

/-! ## The first letter is matched -/

/-- **The outermost pair.**  A word spelling the identity has its first letter
matched somewhere inside, and the two sides of that match each spell the identity.

This is the planarity statement: what lies between a matched pair is itself a
word that dies, so the pair encloses a complete block rather than interleaving
with another. -/
theorem exists_split_aux :
    ∀ (n : ℕ) (x : α × Bool) (W' : List (α × Bool)), (x :: W').length ≤ n →
      FreeGroup.mk (x :: W') = 1 →
        ∃ A B : List (α × Bool), W' = A ++ (invLetter x :: B) ∧
          FreeGroup.mk A = 1 ∧ FreeGroup.mk B = 1 := by
  intro n
  induction n with
  | zero =>
      intro x W' hlen _
      simp only [List.length_cons] at hlen
      exact absurd hlen (by omega)
  | succ n ih =>
      intro x W' hlen h
      have hred : FreeGroup.Red (x :: W') [] :=
        Computability.mk_eq_one_iff_red_nil.mp h
      rcases Relation.ReflTransGen.cases_head hred with hnil | ⟨Z, hstep, hZ⟩
      · exact absurd hnil (List.cons_ne_nil _ _)
      · obtain ⟨L₁, L₂, y, hWeq, hZeq⟩ := redStep_iff.mp hstep
        have hZone : FreeGroup.mk Z = 1 := Computability.mk_eq_one_of_red_nil hZ
        rcases L₁ with _ | ⟨c, L₁'⟩
        · -- the deleted pair is the very front of the word
          rw [List.nil_append] at hWeq hZeq
          simp only [List.cons.injEq] at hWeq
          obtain ⟨hxy, hW'⟩ := hWeq
          refine ⟨[], L₂, ?_, by rw [← FreeGroup.one_eq_mk], ?_⟩
          · rw [hW', hxy, List.nil_append]
          · rw [← hZeq]
            exact hZone
        · -- the deleted pair is further in; split the shortened word instead
          rw [List.cons_append] at hWeq
          simp only [List.cons.injEq] at hWeq
          obtain ⟨hxc, hW'⟩ := hWeq
          have hZshape : Z = x :: (L₁' ++ L₂) := by
            rw [hZeq, hxc, List.cons_append]
          have hZlen : (x :: (L₁' ++ L₂)).length ≤ n := by
            have hl := congrArg List.length hW'
            simp only [List.length_append, List.length_cons] at hl hlen ⊢
            omega
          have hZone' : FreeGroup.mk (x :: (L₁' ++ L₂)) = 1 := by
            rw [← hZshape]
            exact hZone
          obtain ⟨A', B', hsplit, hA', hB'⟩ := ih x (L₁' ++ L₂) hZlen hZone'
          rcases List.append_eq_append_iff.mp hsplit with ⟨e, hA, hL₂⟩ | ⟨e, hL₁, hrest⟩
          · -- the match lies inside `L₂`, past the deleted pair
            refine ⟨L₁' ++ (y :: invLetter y :: e), B', ?_, ?_, hB'⟩
            · rw [hW', hL₂]
              simp only [List.append_assoc, List.cons_append]
            · rw [mk_pair_cancel_append, ← hA]
              exact hA'
          · -- the match lies inside `L₁'`, before the deleted pair
            rcases e with _ | ⟨d, e'⟩
            · -- the match is exactly at the junction
              rw [List.append_nil] at hL₁
              rw [List.nil_append] at hrest
              refine ⟨L₁' ++ (y :: invLetter y :: []), B', ?_, ?_, hB'⟩
              · rw [hW', ← hrest]
                simp only [List.append_assoc, List.cons_append, List.nil_append]
              · rw [mk_pair_cancel_append, List.append_nil, hL₁]
                exact hA'
            · simp only [List.cons_append, List.cons.injEq] at hrest
              obtain ⟨hd, hB⟩ := hrest
              refine ⟨A', e' ++ (y :: invLetter y :: L₂), ?_, hA', ?_⟩
              · rw [hW', hL₁, ← hd]
                simp only [List.append_assoc, List.cons_append]
              · rw [mk_pair_cancel_append, ← hB]
                exact hB'

/-- The outermost pair, with the induction's bookkeeping hidden. -/
theorem exists_split {x : α × Bool} {W' : List (α × Bool)}
    (h : FreeGroup.mk (x :: W') = 1) :
    ∃ A B : List (α × Bool), W' = A ++ (invLetter x :: B) ∧
      FreeGroup.mk A = 1 ∧ FreeGroup.mk B = 1 :=
  exists_split_aux (x :: W').length x W' le_rfl h

/-! ## Nested words -/

/-- **A nested word.**  The empty word is nested, and a letter, a nested block,
that letter's inverse and another nested block is nested.  This is the shape of a
cancellation pattern that never crosses itself. -/
inductive Dyck : List (α × Bool) → Prop
  | nil : Dyck []
  | wrap (x : α × Bool) (A B : List (α × Bool)) :
      Dyck A → Dyck B → Dyck (x :: (A ++ invLetter x :: B))

/-- A nested word spells the identity. -/
theorem mk_eq_one_of_dyck {W : List (α × Bool)} (h : Dyck W) :
    FreeGroup.mk W = 1 := by
  induction h with
  | nil => rw [← FreeGroup.one_eq_mk]
  | wrap x A B _ _ ihA ihB =>
      rw [mk_cons x (A ++ invLetter x :: B), mk_append_mul, ihA,
        mk_cons (invLetter x) B, ihB, ← mk_singleton_inv]
      group

/-- **The converse, and the planarity theorem.**  Every word spelling the
identity is nested: peel the outermost pair with `exists_split` and recurse on
the two sides, both of which are shorter. -/
theorem dyck_of_mk_eq_one_aux :
    ∀ (n : ℕ) (W : List (α × Bool)), W.length ≤ n → FreeGroup.mk W = 1 → Dyck W := by
  intro n
  induction n with
  | zero =>
      intro W hlen _
      have hW : W = [] := List.length_eq_zero_iff.mp (by omega)
      rw [hW]
      exact Dyck.nil
  | succ n ih =>
      intro W hlen h
      rcases W with _ | ⟨x, W'⟩
      · exact Dyck.nil
      · obtain ⟨A, B, hW', hA, hB⟩ := exists_split h
        have hlenAB : A.length + B.length + 2 = (x :: W').length := by
          rw [hW']
          simp only [List.length_cons, List.length_append]
          omega
        rw [hW']
        exact Dyck.wrap x A B (ih A (by omega) hA) (ih B (by omega) hB)

/-- **Free cancellation is nested.**  A word dies freely exactly when its
cancellation pattern is a nesting: the matched pairs of a free reduction never
cross.

This is the planarity input a curvature count over a product of conjugates needs,
and it costs no hypothesis. -/
theorem dyck_iff_mk_eq_one {W : List (α × Bool)} :
    Dyck W ↔ FreeGroup.mk W = 1 :=
  ⟨mk_eq_one_of_dyck, dyck_of_mk_eq_one_aux W.length W le_rfl⟩

/-- The nesting of a word that reduces to another: apply the theorem to the word
against the formal inverse of its reduct. -/
theorem dyck_append_invRev_of_mk_eq {W V : List (α × Bool)}
    (h : FreeGroup.mk W = FreeGroup.mk V) :
    Dyck (W ++ FreeGroup.invRev V) := by
  refine dyck_iff_mk_eq_one.mpr ?_
  rw [mk_append_mul, mk_invRev_eq_inv, h]
  group

end SmallCancellationRouter
end GroupApproximation
