import GroupApproximation.Sofic.FullRadicalClosureProperties
import GroupApproximation.Sofic.KazhdanCompressionFunctorial

/-!
# The largest intrinsically full-MF-radical subgroup

The MF residual of an ambient group consists of elements killed by every
matrix-corona representation of that ambient group.  A subgroup can satisfy a
stronger property: every matrix-corona representation of the subgroup itself
is trivial.

The subgroup generated by all such subgroups is again full-MF-radical.  It is
therefore the largest subgroup with this intrinsic property.  It is functorial
under arbitrary homomorphisms and lies inside the ambient MF residual.
-/

namespace GroupApproximation

universe u v

variable {G : Type u} [Group G]

/-- The subgroup generated by all subgroups whose own genuine-corona MF
residual is the whole subgroup. -/
def fullMFRadicalCore (G : Type u) [Group G] : Subgroup G :=
  ⨆ K : {K : Subgroup G // actualCoronaMFResidual K = ⊤}, K.1

/-- Every intrinsically full subgroup lies in `fullMFRadicalCore`. -/
theorem le_fullMFRadicalCore (K : Subgroup G)
    (hK : actualCoronaMFResidual K = ⊤) :
    K ≤ fullMFRadicalCore G :=
  le_iSup (fun L : {L : Subgroup G // actualCoronaMFResidual L = ⊤} ↦ L.1)
    ⟨K, hK⟩

/-- The core is itself intrinsically full: arbitrary generation preserves
full MF radical. -/
theorem actualCoronaMFResidual_fullMFRadicalCore_eq_top :
    actualCoronaMFResidual (fullMFRadicalCore G) = ⊤ := by
  refine actualCoronaMFResidual_eq_top_of_forall_eq_one ?_
  intro x X hX
  letI : ∀ n, Nonempty (X n) :=
    fun n ↦ Fintype.card_pos_iff.mp (hX n)
  intro rho
  have hle : fullMFRadicalCore G ≤
      rho.ker.map (fullMFRadicalCore G).subtype := by
    unfold fullMFRadicalCore
    apply iSup_le
    intro K y hy
    have hKC : K.1 ≤ fullMFRadicalCore G := le_fullMFRadicalCore K.1 K.2
    have hkill := forall_eq_one_of_actualCoronaMFResidual_eq_top
      K.2 (⟨y, hy⟩ : K.1) X hX
      (rho.comp (Subgroup.inclusion hKC))
    refine ⟨⟨y, hKC hy⟩, MonoidHom.mem_ker.mpr ?_, rfl⟩
    convert hkill using 1
  obtain ⟨y, hy, hxy⟩ := hle x.property
  have hy' : rho y = 1 := MonoidHom.mem_ker.mp hy
  have hyx : (y : fullMFRadicalCore G) = x := Subtype.ext hxy
  rw [← hyx]
  exact hy'

/-- The intrinsic core lies inside the ambient MF residual. -/
theorem fullMFRadicalCore_le_actualCoronaMFResidual :
    fullMFRadicalCore G ≤ actualCoronaMFResidual G := by
  unfold fullMFRadicalCore
  apply iSup_le
  intro K x hx
  have hx' : (⟨x, hx⟩ : K.1) ∈ actualCoronaMFResidual K.1 := by
    rw [K.2]
    exact Subgroup.mem_top _
  exact map_actualCoronaMFResidual_le K.1.subtype
    (Subgroup.mem_map_of_mem K.1.subtype hx')

/-- The image of an intrinsically full subgroup under any homomorphism is
again intrinsically full. -/
theorem actualCoronaMFResidual_map_eq_top
    {H : Type v} [Group H] (K : Subgroup G) (f : G →* H)
    (hK : actualCoronaMFResidual K = ⊤) :
    actualCoronaMFResidual (K.map f) = ⊤ :=
  actualCoronaMFResidual_eq_top_of_surjective
    (KazhdanCompressionCore.subgroupMapHom K f)
    (KazhdanCompressionCore.subgroupMapHom_surjective K f) hK

/-- The intrinsic core is functorial under arbitrary group homomorphisms. -/
theorem map_fullMFRadicalCore_le
    {H : Type v} [Group H] (f : G →* H) :
    (fullMFRadicalCore G).map f ≤ fullMFRadicalCore H :=
  le_fullMFRadicalCore _
    (actualCoronaMFResidual_map_eq_top
      (fullMFRadicalCore G) f
      actualCoronaMFResidual_fullMFRadicalCore_eq_top)

/-- The intrinsic core is normal. -/
instance fullMFRadicalCore_normal : (fullMFRadicalCore G).Normal := by
  constructor
  intro x hx g
  have hmem := map_fullMFRadicalCore_le
    (G := G) (H := G) (MulAut.conj g).toMonoidHom
    (Subgroup.mem_map_of_mem (MulAut.conj g).toMonoidHom hx)
  simpa using hmem

/-- The intrinsic core is characteristic. -/
instance fullMFRadicalCore_characteristic :
    (fullMFRadicalCore G).Characteristic := by
  constructor
  intro φ
  ext x
  simp only [Subgroup.mem_comap]
  constructor
  · intro hx
    have hmem := map_fullMFRadicalCore_le
      (G := G) (H := G) φ.symm.toMonoidHom
      (Subgroup.mem_map_of_mem φ.symm.toMonoidHom hx)
    simpa using hmem
  · intro hx
    exact map_fullMFRadicalCore_le
      (G := G) (H := G) φ.toMonoidHom
      (Subgroup.mem_map_of_mem φ.toMonoidHom hx)

/-- A group has full MF radical exactly when its intrinsic full-radical core
is the whole group. -/
theorem fullMFRadicalCore_eq_top_iff :
    fullMFRadicalCore G = ⊤ ↔ actualCoronaMFResidual G = ⊤ := by
  constructor
  · intro hcore
    apply top_unique
    rw [← hcore]
    exact fullMFRadicalCore_le_actualCoronaMFResidual
  · intro hfull
    have htop : actualCoronaMFResidual (⊤ : Subgroup G) = ⊤ :=
      actualCoronaMFResidual_eq_top_of_mulEquiv Subgroup.topEquiv.symm hfull
    exact top_unique (le_fullMFRadicalCore (⊤ : Subgroup G) htop)

/-- Applying the intrinsic-core construction to the core itself gives the
whole core. -/
theorem fullMFRadicalCore_idempotent :
    fullMFRadicalCore (fullMFRadicalCore G) = ⊤ :=
  fullMFRadicalCore_eq_top_iff.mpr
    actualCoronaMFResidual_fullMFRadicalCore_eq_top

end GroupApproximation
