import GroupApproximation.Sofic.FullRadicalClosureProperties
import GroupApproximation.Sofic.KazhdanCompressionFunctorial

/-!
# The largest intrinsically full-MF-radical subgroup

The MF residual of an ambient group consists of elements killed by every
matrix-corona representation of that ambient group.  A subgroup can satisfy a
stronger property: every matrix-corona representation of the subgroup itself
is trivial.

The subgroup generated by all such subgroups is again full-MF-radical.  It is
therefore the largest subgroup with this intrinsic property.  It is functorial
under arbitrary homomorphisms and lies inside the ambient MF residual.
-/

namespace GroupApproximation

universe u v

variable {G : Type u} [Group G]

/-- The subgroup generated by all subgroups whose own genuine-corona MF
residual is the whole subgroup. -/
def fullMFRadicalCore (G : Type u) [Group G] : Subgroup G :=
  ⨆ K : {K : Subgroup G // actualCoronaMFResidual K = ⊤}, K.1

/-- Every intrinsically full subgroup lies in `fullMFRadicalCore`. -/
theorem le_fullMFRadicalCore (K : Subgroup G)
    (hK : actualCoronaMFResidual K = ⊤) :
    K ≤ fullMFRadicalCore G :=
  le_iSup (fun L : {L : Subgroup G // actualCoronaMFResidual L = ⊤} ↦ L.1)
    ⟨K, hK⟩

/-- The core is itself intrinsically full: arbitrary generation preserves
full MF radical. -/
theorem actualCoronaMFResidual_fullMFRadicalCore_eq_top :
    actualCoronaMFResidual (fullMFRadicalCore G) = ⊤ := by
  refine actualCoronaMFResidual_eq_top_of_forall_eq_one ?_
  intro x X hX
  letI : ∀ n, Nonempty (X n) :=
    fun n ↦ Fintype.card_pos_iff.mp (hX n)
  intro rho
  have hle : fullMFRadicalCore G ≤
      rho.ker.map (fullMFRadicalCore G).subtype := by
    unfold fullMFRadicalCore
    apply iSup_le
    intro K y hy
    have hKC : K.1 ≤ fullMFRadicalCore G := le_fullMFRadicalCore K.1 K.2
    have hkill := forall_eq_one_of_actualCoronaMFResidual_eq_top
      K.2 (⟨y, hy⟩ : K.1) X hX
      (rho.comp (Subgroup.inclusion hKC))
    refine ⟨⟨y, hKC hy⟩, MonoidHom.mem_ker.mpr ?_, rfl⟩
    convert hkill using 1
    rfl
  obtain ⟨y, hy, hxy⟩ := hle x.property
  have hy' : rho y = 1 := MonoidHom.mem_ker.mp hy
  have hyx : (y : fullMFRadicalCore G) = x := Subtype.ext hxy
  rw [← hyx]
  exact hy'

/-- The intrinsic core lies inside the ambient MF residual. -/
theorem fullMFRadicalCore_le_actualCoronaMFResidual :
    fullMFRadicalCore G ≤ actualCoronaMFResidual G := by
  unfold fullMFRadicalCore
  apply iSup_le
  intro K x hx
  have hx' : (⟨x, hx⟩ : K.1) ∈ actualCoronaMFResidual K.1 := by
    rw [K.2]
    exact Subgroup.mem_top _
  exact map_actualCoronaMFResidual_le K.1.subtype
    (Subgroup.mem_map_of_mem K.1.subtype hx')

/-- The image of an intrinsically full subgroup under any homomorphism is
again intrinsically full. -/
theorem actualCoronaMFResidual_map_eq_top
    {H : Type v} [Group H] (K : Subgroup G) (f : G →* H)
    (hK : actualCoronaMFResidual K = ⊤) :
    actualCoronaMFResidual (K.map f) = ⊤ :=
  actualCoronaMFResidual_eq_top_of_surjective
    (KazhdanCompressionCore.subgroupMapHom K f)
    (KazhdanCompressionCore.subgroupMapHom_surjective K f) hK

/-- The intrinsic core is functorial under arbitrary group homomorphisms. -/
theorem map_fullMFRadicalCore_le
    {H : Type v} [Group H] (f : G →* H) :
    (fullMFRadicalCore G).map f ≤ fullMFRadicalCore H :=
  le_fullMFRadicalCore _
    (actualCoronaMFResidual_map_eq_top
      (fullMFRadicalCore G) f
      actualCoronaMFResidual_fullMFRadicalCore_eq_top)

/-- The intrinsic core is normal. -/
instance fullMFRadicalCore_normal : (fullMFRadicalCore G).Normal := by
  constructor
  intro x hx g
  have hmem := map_fullMFRadicalCore_le
    (G := G) (H := G) (MulAut.conj g).toMonoidHom
    (Subgroup.mem_map_of_mem (MulAut.conj g).toMonoidHom hx)
  simpa using hmem

/-- The intrinsic core is characteristic. -/
instance fullMFRadicalCore_characteristic :
    (fullMFRadicalCore G).Characteristic := by
  constructor
  intro φ
  ext x
  simp only [Subgroup.mem_comap]
  constructor
  · intro hx
    have hmem := map_fullMFRadicalCore_le
      (G := G) (H := G) φ.symm.toMonoidHom
      (Subgroup.mem_map_of_mem φ.symm.toMonoidHom hx)
    simpa using hmem
  · intro hx
    exact map_fullMFRadicalCore_le
      (G := G) (H := G) φ.toMonoidHom
      (Subgroup.mem_map_of_mem φ.toMonoidHom hx)

/-- A group has full MF radical exactly when its intrinsic full-radical core
is the whole group. -/
theorem fullMFRadicalCore_eq_top_iff :
    fullMFRadicalCore G = ⊤ ↔ actualCoronaMFResidual G = ⊤ := by
  constructor
  · intro hcore
    apply top_unique
    rw [← hcore]
    exact fullMFRadicalCore_le_actualCoronaMFResidual
  · intro hfull
    have htop : actualCoronaMFResidual (⊤ : Subgroup G) = ⊤ :=
      actualCoronaMFResidual_eq_top_of_mulEquiv Subgroup.topEquiv.symm hfull
    exact top_unique (le_fullMFRadicalCore (⊤ : Subgroup G) htop)

/-- Applying the intrinsic-core construction to the core itself gives the
whole core. -/
theorem fullMFRadicalCore_idempotent :
    fullMFRadicalCore (fullMFRadicalCore G) = ⊤ :=
  fullMFRadicalCore_eq_top_iff.mpr
    actualCoronaMFResidual_fullMFRadicalCore_eq_top

/-- The quotient by the intrinsic core has no nontrivial intrinsically
full-MF-radical subgroup.  Thus `fullMFRadicalCore` is a group radical in the
classical sense: it is functorial, idempotent, and its quotient is semisimple. -/
theorem fullMFRadicalCore_quotient_eq_bot :
    fullMFRadicalCore (G ⧸ fullMFRadicalCore G) = ⊥ := by
  letI : (fullMFRadicalCore G).Normal := fullMFRadicalCore_normal
  let q : G →* G ⧸ fullMFRadicalCore G :=
    QuotientGroup.mk' (fullMFRadicalCore G)
  have hq : Function.Surjective q :=
    QuotientGroup.mk'_surjective (fullMFRadicalCore G)
  apply le_antisymm _ bot_le
  change (⨆ K : {K : Subgroup (G ⧸ fullMFRadicalCore G) //
      actualCoronaMFResidual K = ⊤}, K.1) ≤ ⊥
  apply iSup_le
  intro K
  let P : Subgroup G := K.1.comap q
  have hCP : fullMFRadicalCore G ≤ P := by
    intro x hx
    change q x ∈ K.1
    have hqx : q x = 1 := by
      apply (QuotientGroup.eq_one_iff x).mpr
      show x ∈ fullMFRadicalCore G
      exact hx
    rw [hqx]
    exact K.1.one_mem
  let φ : P →* P.map q := KazhdanCompressionCore.subgroupMapHom P q
  have hφ : Function.Surjective φ :=
    KazhdanCompressionCore.subgroupMapHom_surjective P q
  let j : fullMFRadicalCore G →* φ.ker :=
    { toFun := fun x ↦ ⟨⟨x, hCP x.property⟩, by
        rw [MonoidHom.mem_ker]
        apply Subtype.ext
        change q (x : G) = 1
        apply (QuotientGroup.eq_one_iff (x : G)).mpr
        show (x : G) ∈ fullMFRadicalCore G
        exact x.property⟩
      map_one' := by ext; rfl
      map_mul' := by intro x y; ext; rfl }
  have hj : Function.Surjective j := by
    rintro ⟨⟨x, hxP⟩, hxker⟩
    have hqx : q x = 1 := by
      have hxone := MonoidHom.mem_ker.mp hxker
      exact congrArg Subtype.val hxone
    have hxC : x ∈ fullMFRadicalCore G :=
      (QuotientGroup.eq_one_iff x).mp hqx
    refine ⟨⟨x, hxC⟩, ?_⟩
    ext
    rfl
  have hker : actualCoronaMFResidual φ.ker = ⊤ :=
    actualCoronaMFResidual_eq_top_of_surjective j hj
      actualCoronaMFResidual_fullMFRadicalCore_eq_top
  have hPK : P.map q = K.1 := by
    dsimp [P]
    exact Subgroup.map_comap_eq_self_of_surjective hq K.1
  have htarget : actualCoronaMFResidual (P.map q) = ⊤ := by
    rw [hPK]
    exact K.2
  have hP : actualCoronaMFResidual P = ⊤ :=
    actualCoronaMFResidual_eq_top_of_surjective_kernel φ hφ hker htarget
  have hPC : P ≤ fullMFRadicalCore G := le_fullMFRadicalCore P hP
  intro z hz
  rw [Subgroup.mem_bot]
  obtain ⟨x, rfl⟩ := hq z
  apply (QuotientGroup.eq_one_iff x).mpr
  apply hPC
  exact hz

/-- Every homomorphism to a group with trivial intrinsic core kills the source
core.  Thus the quotient by `fullMFRadicalCore G` is universal among
homomorphisms from `G` to core-free groups. -/
theorem fullMFRadicalCore_le_ker_of_target_eq_bot
    {H : Type v} [Group H] (f : G →* H)
    (hH : fullMFRadicalCore H = ⊥) :
    fullMFRadicalCore G ≤ f.ker := by
  intro x hx
  rw [MonoidHom.mem_ker]
  have hfx : f x ∈ fullMFRadicalCore H :=
    map_fullMFRadicalCore_le f (Subgroup.mem_map_of_mem f hx)
  rw [hH] at hfx
  exact Subgroup.mem_bot.mp hfx

/-- A group with full intrinsic core has no nontrivial homomorphism to a
core-free group. -/
theorem hom_eq_one_of_fullMFRadicalCore_eq_top_of_target_eq_bot
    {H : Type v} [Group H] (f : G →* H)
    (hG : fullMFRadicalCore G = ⊤)
    (hH : fullMFRadicalCore H = ⊥) :
    f = 1 := by
  ext x
  have hx : x ∈ fullMFRadicalCore G := by
    rw [hG]
    exact Subgroup.mem_top x
  exact MonoidHom.mem_ker.mp
    (fullMFRadicalCore_le_ker_of_target_eq_bot f hH hx)

/-- The intrinsic core is the unique normal intrinsically full subgroup whose
quotient is core-free. -/
theorem eq_fullMFRadicalCore_of_residual_eq_top_of_quotient_core_eq_bot
    (N : Subgroup G) [N.Normal]
    (hN : actualCoronaMFResidual N = ⊤)
    (hquot : fullMFRadicalCore (G ⧸ N) = ⊥) :
    N = fullMFRadicalCore G := by
  apply le_antisymm
  · exact le_fullMFRadicalCore N hN
  · let q : G →* G ⧸ N := QuotientGroup.mk' N
    have hker : fullMFRadicalCore G ≤ q.ker :=
      fullMFRadicalCore_le_ker_of_target_eq_bot q hquot
    intro x hx
    apply (QuotientGroup.eq_one_iff x).mp
    exact MonoidHom.mem_ker.mp (hker hx)

end GroupApproximation
