import GroupApproximation.Sofic.ThreeRadicalsCoincide

/-!
# Section 46: the all-fields linear residual

`linearResidual G` collects the elements killed by *every* finite-dimensional
linear representation over every field.  Following the dossier's remark after
(46.1), the definition is elementwise, so no indexing over a proper class of
fields is needed; the fields range over `Type`, which contains `ℂ`, `ℚ`, every
finite field, and every field generated by countably many elements.

Unitary representations are linear, so the linear residual sits at the bottom
of the chain already established:

`Rad_lin ≤ Res_MF-free bound: Rad_lin ≤ Rad_fd ≤ Res_fin`.

The reverse inclusion `Res_fin ≤ Rad_lin` is Mal'cev's theorem (46.2), which is
a statement about finitely generated linear groups and is not proved here.
-/

namespace GroupApproximation

open MatricialStabilityRadical

universe u

variable {G : Type u} [Group G]

/-- The linear residual: invisible to every finite-dimensional linear
representation over every field. -/
def linearResidual (G : Type u) [Group G] : Subgroup G where
  carrier := {x | ∀ (F : Type) (_ : Field F) (d : ℕ)
    (ρ : G →* Matrix (Fin d) (Fin d) F), ρ x = 1}
  one_mem' := by
    intro F _ d ρ
    exact map_one ρ
  mul_mem' := by
    intro x y hx hy F hF d ρ
    rw [map_mul, hx F hF d ρ, hy F hF d ρ, one_mul]
  inv_mem' := by
    intro x hx F hF d ρ
    have hone : ρ x = 1 := hx F hF d ρ
    have : ρ x * ρ x⁻¹ = 1 := by rw [← map_mul, mul_inv_cancel, map_one]
    rw [hone, one_mul] at this
    exact this

theorem mem_linearResidual_iff {x : G} :
    x ∈ linearResidual G ↔ ∀ (F : Type) (_ : Field F) (d : ℕ)
      (ρ : G →* Matrix (Fin d) (Fin d) F), ρ x = 1 := Iff.rfl

/-- **Unitary representations are linear.**  The linear residual is contained
in the finite-dimensional unitary residual. -/
theorem linearResidual_le_fdUnitaryResidual :
    linearResidual G ≤ fdUnitaryResidual G := by
  classical
  intro x hx
  rw [mem_fdUnitaryResidual_iff]
  intro Y phi
  -- transport the coordinate set to `Fin d` and forget unitarity
  set d : ℕ := Fintype.card Y with hd
  set e : Y ≃ Fin d := Fintype.equivFin Y with he
  set reind : Matrix Y Y ℂ ≃ₐ[ℂ] Matrix (Fin d) (Fin d) ℂ :=
    Matrix.reindexAlgEquiv ℂ ℂ e with hreind
  set ρ : G →* Matrix (Fin d) (Fin d) ℂ :=
    (reind.toRingEquiv.toRingHom.toMonoidHom).comp
      ((unitary (Matrix Y Y ℂ)).subtype.comp phi) with hρ
  have hone : ρ x = 1 := hx ℂ inferInstance d ρ
  have hval : ((phi x : Matrix.unitaryGroup Y ℂ) : Matrix Y Y ℂ) = 1 := by
    have hstep : reind ((phi x : Matrix.unitaryGroup Y ℂ) : Matrix Y Y ℂ) = 1 :=
      hone
    have := congrArg reind.symm hstep
    simpa using this
  exact Subtype.ext hval

/-- The linear residual is contained in the finite residual: the full chain of
Section 46 read from the linear end. -/
theorem linearResidual_le_finiteResidual :
    linearResidual G ≤ finiteResidual G :=
  le_trans linearResidual_le_fdUnitaryResidual fdUnitaryResidual_le_finiteResidual

end GroupApproximation
