import GroupApproximation.Sofic.CommutingLampCollapse
import GroupApproximation.Monsters.LiteralBaseCompleteness

/-!
# The sign-free quotient of the literal group is not MF

Killing the central sign `w` in the literal eight-generator group does
not restore MF: the moved lamp `d = t c t⁻¹` becomes an involutive
compression witness in `E/⟨w⟩`, so the commutator `[v₁, d]` — the
unsquared defect — lies in the MF radical of the quotient, while the
certified witness model keeps it nontrivial there.  Consequently
`E/⟨w⟩` admits no injective corona representation, the unsquared defect
`u` lies in the MF radical of `E` itself, and `⟨w⟩` is a *proper*
subgroup of that radical: the Clifford sign is the cleanest certificate
in Theorem A, but not the whole obstruction.

The only new group theory is the commutation of the `B`-conjugates of
`d` in the quotient.  Conjugates of `d` depend only on the translation
parity class in `(ℤ/2)³`, because the rotation letters and the
translation squares centralize `d` by literal relators (`t x t⁻¹ = x`,
`t vᵢ t⁻¹ = vᵢ²`, and `[c, ·] = 1` conjugated by `t`).  The rotation
relators act transitively on the seven nonzero parity classes by the
explicit words `x, x², z, yz, yx, y²x` — validated numerically over
`GL₃(𝔽₂)` before transcription — so every conjugate commutator reduces
to a conjugate of the central `w`, which dies in the quotient.
-/

namespace GroupApproximation
namespace LiteralSignFreeQuotient

open LiteralNonMFPresentation LiteralNonMFLinearWitness
open LiteralBaseRelations LiteralBaseTranslationNormal
open LiteralBaseCompleteness
open InvolutionCollapseEndpoint CommutingLampCollapse
open scoped commutatorElement

noncomputable section

private abbrev Base := LiteralNonMFPresentation.Base

private abbrev v1 : Base := LiteralBaseRelations.v1
private abbrev v2 : Base := LiteralBaseRelations.v2
private abbrev v3 : Base := LiteralBaseRelations.v3
private abbrev x : Base := LiteralBaseRelations.x
private abbrev y : Base := LiteralBaseRelations.y
private abbrev z : Base := LiteralBaseRelations.z

/-! ## The quotient by the central sign -/

/-- The central subgroup generated by the marked sign. -/
abbrev markSubgroup : Subgroup MarkedGroup := Subgroup.zpowers mark

instance markSubgroup_normal : markSubgroup.Normal := by
  constructor
  intro a ha g
  obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp ha
  have hc : mark ^ n * g = g * mark ^ n :=
    ((mark_central g).zpow_left n).eq
  have h1 : g * mark ^ n * g⁻¹ = mark ^ n := by
    rw [← hc, mul_assoc, mul_inv_cancel, mul_one]
  rw [h1]
  exact Subgroup.zpow_mem _ (Subgroup.mem_zpowers _) n

/-- The sign-free quotient `E/⟨w⟩` of the literal group. -/
abbrev SignFreeQuotient : Type := MarkedGroup ⧸ markSubgroup

/-- The quotient projection. -/
abbrev proj : MarkedGroup →* SignFreeQuotient :=
  QuotientGroup.mk' markSubgroup

/-- Centrality makes the cyclic subgroup generated by the sign exactly its
normal closure.  This identifies the sign-free group as the result of adding
one literal relator to the finite presentation of `MarkedGroup`; it is not an
external finite-presentation input. -/
theorem markSubgroup_eq_normalClosure_singleton :
    markSubgroup = Subgroup.normalClosure ({mark} : Set MarkedGroup) := by
  apply le_antisymm
  · apply Subgroup.zpowers_le.mpr
    exact Subgroup.subset_normalClosure (Set.mem_singleton mark)
  · apply Subgroup.normalClosure_le_normal
    intro g hg
    rw [Set.mem_singleton_iff] at hg
    subst g
    exact Subgroup.mem_zpowers mark

/-- **The sign-free quotient is finitely presented.**  It is obtained from
the literal finite presentation by adjoining the single relator `mark = 1`.
The proof is internal: the preceding theorem identifies the kernel with the
normal closure required by the finite-presentation quotient theorem. -/
instance signFreeQuotient_finitelyPresented :
    Group.IsFinitelyPresented SignFreeQuotient :=
  Group.IsFinitelyPresented.quotient markSubgroup
    ⟨({mark} : Set MarkedGroup), Set.finite_singleton mark,
      markSubgroup_eq_normalClosure_singleton.symm⟩

/-! ## The moved lamp and its literal centralizers -/

/-- The moved lamp `d = t c t⁻¹`. -/
def dee : MarkedGroup := stable * lamp * stable⁻¹

theorem dee_sq : dee * dee = 1 := by
  have h : dee * dee = stable * (lamp * lamp) * stable⁻¹ := by
    rw [dee]; group
  have hl : lamp * lamp = 1 := by
    have := lamp_sq
    rwa [pow_two] at this
  rw [h, hl, mul_one, mul_inv_cancel]

/-- Conjugating a lamp-commuting element by the stable letter produces a
`dee`-commuting element. -/
theorem commute_dee_stable_conj {g : MarkedGroup} (h : Commute lamp g) :
    Commute dee (stable * g * stable⁻¹) := by
  have h1 : dee * (stable * g * stable⁻¹) =
      stable * (lamp * g) * stable⁻¹ := by
    rw [dee]; group
  have h2 : (stable * g * stable⁻¹) * dee =
      stable * (g * lamp) * stable⁻¹ := by
    rw [dee]; group
  unfold Commute SemiconjBy
  rw [h1, h2, h.eq]

/-- The moved lamp commutes with the compressed copy of the whole base. -/
theorem dee_commutes_compressed (g : Base) :
    Commute dee (stable * baseMap g * stable⁻¹) :=
  commute_dee_stable_conj (lamp_commutes_base g)

/-- The stable letter fixes each rotation letter. -/
theorem stable_conj_x : stable * baseMap x * stable⁻¹ = baseMap x := by
  rw [stable_relation xIndex]
  show wordInMarkedGroup (embedBaseWord (compressedBaseWord xIndex)) =
    baseMap x
  rw [← baseMap_mk]
  rfl

theorem stable_conj_y : stable * baseMap y * stable⁻¹ = baseMap y := by
  rw [stable_relation yIndex]
  show wordInMarkedGroup (embedBaseWord (compressedBaseWord yIndex)) =
    baseMap y
  rw [← baseMap_mk]
  rfl

theorem stable_conj_z : stable * baseMap z * stable⁻¹ = baseMap z := by
  rw [stable_relation zIndex]
  show wordInMarkedGroup (embedBaseWord (compressedBaseWord zIndex)) =
    baseMap z
  rw [← baseMap_mk]
  rfl

/-- The stable letter squares each translation letter. -/
theorem stable_conj_v1 :
    stable * baseMap v1 * stable⁻¹ = baseMap v1 ^ 2 := by
  rw [stable_relation v1Index]
  show wordInMarkedGroup (embedBaseWord (compressedBaseWord v1Index)) =
    baseMap v1 ^ 2
  rw [← baseMap_mk]
  show baseMap (PresentedGroup.mk _ (bv1 ^ 2)) = baseMap v1 ^ 2
  rw [map_pow, map_pow]
  rfl

theorem stable_conj_v2 :
    stable * baseMap v2 * stable⁻¹ = baseMap v2 ^ 2 := by
  rw [stable_relation v2Index]
  show wordInMarkedGroup (embedBaseWord (compressedBaseWord v2Index)) =
    baseMap v2 ^ 2
  rw [← baseMap_mk]
  show baseMap (PresentedGroup.mk _ (bv2 ^ 2)) = baseMap v2 ^ 2
  rw [map_pow, map_pow]
  rfl

theorem stable_conj_v3 :
    stable * baseMap v3 * stable⁻¹ = baseMap v3 ^ 2 := by
  rw [stable_relation v3Index]
  show wordInMarkedGroup (embedBaseWord (compressedBaseWord v3Index)) =
    baseMap v3 ^ 2
  rw [← baseMap_mk]
  show baseMap (PresentedGroup.mk _ (bv3 ^ 2)) = baseMap v3 ^ 2
  rw [map_pow, map_pow]
  rfl

theorem dee_commutes_x : Commute dee (baseMap x) := by
  have h := dee_commutes_compressed x
  rwa [stable_conj_x] at h

theorem dee_commutes_y : Commute dee (baseMap y) := by
  have h := dee_commutes_compressed y
  rwa [stable_conj_y] at h

theorem dee_commutes_z : Commute dee (baseMap z) := by
  have h := dee_commutes_compressed z
  rwa [stable_conj_z] at h

theorem dee_commutes_v1_sq : Commute dee (baseMap v1 ^ 2) := by
  have h := dee_commutes_compressed v1
  rwa [stable_conj_v1] at h

theorem dee_commutes_v2_sq : Commute dee (baseMap v2 ^ 2) := by
  have h := dee_commutes_compressed v2
  rwa [stable_conj_v2] at h

theorem dee_commutes_v3_sq : Commute dee (baseMap v3 ^ 2) := by
  have h := dee_commutes_compressed v3
  rwa [stable_conj_v3] at h

/-! ## Parity reduction of the conjugates -/

/-- The double base: rotations and translation squares. -/
def doubledBase : Subgroup Base :=
  Subgroup.closure
    ({LiteralBaseRelations.x, LiteralBaseRelations.y,
      LiteralBaseRelations.z, LiteralBaseRelations.v1 ^ 2,
      LiteralBaseRelations.v2 ^ 2, LiteralBaseRelations.v3 ^ 2} :
      Set Base)

theorem dee_commutes_doubledBase {h : Base} (hh : h ∈ doubledBase) :
    Commute dee (baseMap h) := by
  induction hh using Subgroup.closure_induction with
  | mem u hu =>
      rcases hu with rfl | rfl | rfl | rfl | rfl | rfl
      · exact dee_commutes_x
      · exact dee_commutes_y
      · exact dee_commutes_z
      · simpa only [map_pow] using dee_commutes_v1_sq
      · simpa only [map_pow] using dee_commutes_v2_sq
      · simpa only [map_pow] using dee_commutes_v3_sq
  | one => simp only [map_one]; exact Commute.one_right dee
  | mul a b _ _ ha hb => simpa [map_mul] using ha.mul_right hb
  | inv a _ ha => simpa [map_inv] using ha.inv_right

theorem rotations_le_doubledBase : rotations ≤ doubledBase := by
  rw [rotations]
  apply Subgroup.closure_mono
  intro g hg
  rcases hg with rfl | rfl | rfl
  · exact Or.inl rfl
  · exact Or.inr (Or.inl rfl)
  · exact Or.inr (Or.inr (Or.inl rfl))

theorem v_sq_mem_doubledBase :
    v1 ^ 2 ∈ doubledBase ∧ v2 ^ 2 ∈ doubledBase ∧ v3 ^ 2 ∈ doubledBase :=
  ⟨Subgroup.subset_closure (by simp),
   Subgroup.subset_closure (by simp),
   Subgroup.subset_closure (by simp)⟩

/-- Conjugation of the moved lamp only sees the base element modulo the
doubled base: elements of the doubled base can be absorbed. -/
theorem conj_dee_absorb {g : Base} {h : Base} (hh : h ∈ doubledBase) :
    baseMap (g * h) * dee * (baseMap (g * h))⁻¹ =
      baseMap g * dee * (baseMap g)⁻¹ := by
  have hc := dee_commutes_doubledBase hh
  rw [map_mul, mul_inv_rev]
  calc baseMap g * baseMap h * dee * ((baseMap h)⁻¹ * (baseMap g)⁻¹)
      = baseMap g * (baseMap h * dee * (baseMap h)⁻¹) * (baseMap g)⁻¹ := by
        group
    _ = baseMap g * dee * (baseMap g)⁻¹ := by
        rw [hc.symm.eq]
        group

/-- Exponent split of a power along parity. -/
private theorem zpow_parity_split (u : Base) (n : ℤ) :
    u ^ n = u ^ (n % 2) * (u ^ 2) ^ (n / 2) := by
  have h2 : ((u ^ 2 : Base)) ^ (n / 2) = u ^ (2 * (n / 2)) := by
    rw [← zpow_natCast u 2, ← zpow_mul]
    congr 1
  rw [h2, ← zpow_add]
  congr 1
  omega

/-- A translation word reduces, modulo the doubled base, to its parity. -/
private theorem vword_parity_decomp (a b c : ℤ) :
    ∃ s ∈ doubledBase,
      (v1 : Base) ^ a * v2 ^ b * v3 ^ c =
        v1 ^ (a % 2) * v2 ^ (b % 2) * v3 ^ (c % 2) * s := by
  have h12 : Commute (v1 : Base) v2 :=
    v1_commutes_translations v2_mem_translations
  have h13 : Commute (v1 : Base) v3 :=
    v1_commutes_translations v3_mem_translations
  have h23 : Commute (v2 : Base) v3 :=
    v2_commutes_translations v3_mem_translations
  refine ⟨(v1 ^ 2) ^ (a / 2) * ((v2 ^ 2) ^ (b / 2) * (v3 ^ 2) ^ (c / 2)),
    Subgroup.mul_mem _
      (Subgroup.zpow_mem _ v_sq_mem_doubledBase.1 _)
      (Subgroup.mul_mem _
        (Subgroup.zpow_mem _ v_sq_mem_doubledBase.2.1 _)
        (Subgroup.zpow_mem _ v_sq_mem_doubledBase.2.2 _)), ?_⟩
  have hS12 : Commute (((v1 : Base) ^ 2) ^ (a / 2)) (v2 ^ (b % 2)) :=
    (h12.pow_left 2).zpow_zpow _ _
  have hS13 : Commute (((v1 : Base) ^ 2) ^ (a / 2)) (v3 ^ (c % 2)) :=
    (h13.pow_left 2).zpow_zpow _ _
  have hS23 : Commute (((v2 : Base) ^ 2) ^ (b / 2)) (v3 ^ (c % 2)) :=
    (h23.pow_left 2).zpow_zpow _ _
  calc (v1 : Base) ^ a * v2 ^ b * v3 ^ c
      = (v1 ^ (a % 2) * (v1 ^ 2) ^ (a / 2)) *
          (v2 ^ (b % 2) * (v2 ^ 2) ^ (b / 2)) *
          (v3 ^ (c % 2) * (v3 ^ 2) ^ (c / 2)) := by
        rw [← zpow_parity_split, ← zpow_parity_split, ← zpow_parity_split]
    _ = v1 ^ (a % 2) * ((v1 ^ 2) ^ (a / 2) * v2 ^ (b % 2)) *
          ((v2 ^ 2) ^ (b / 2) * v3 ^ (c % 2)) *
          (v3 ^ 2) ^ (c / 2) := by group
    _ = v1 ^ (a % 2) * (v2 ^ (b % 2) * (v1 ^ 2) ^ (a / 2)) *
          ((v2 ^ 2) ^ (b / 2) * v3 ^ (c % 2)) *
          (v3 ^ 2) ^ (c / 2) := by rw [hS12.eq]
    _ = v1 ^ (a % 2) * (v2 ^ (b % 2) * (v1 ^ 2) ^ (a / 2)) *
          (v3 ^ (c % 2) * (v2 ^ 2) ^ (b / 2)) *
          (v3 ^ 2) ^ (c / 2) := by rw [hS23.eq]
    _ = v1 ^ (a % 2) * v2 ^ (b % 2) *
          ((v1 ^ 2) ^ (a / 2) * v3 ^ (c % 2)) *
          ((v2 ^ 2) ^ (b / 2) * (v3 ^ 2) ^ (c / 2)) := by group
    _ = v1 ^ (a % 2) * v2 ^ (b % 2) *
          (v3 ^ (c % 2) * (v1 ^ 2) ^ (a / 2)) *
          ((v2 ^ 2) ^ (b / 2) * (v3 ^ 2) ^ (c / 2)) := by rw [hS13.eq]
    _ = v1 ^ (a % 2) * v2 ^ (b % 2) * v3 ^ (c % 2) *
          ((v1 ^ 2) ^ (a / 2) *
            ((v2 ^ 2) ^ (b / 2) * (v3 ^ 2) ^ (c / 2))) := by group

/-- Every base element factors as a translation-parity word times an
element of the doubled base. -/
theorem parity_factorization (g : Base) :
    ∃ (e₁ e₂ e₃ : ℤ) (h : Base), (e₁ = 0 ∨ e₁ = 1) ∧ (e₂ = 0 ∨ e₂ = 1) ∧
      (e₃ = 0 ∨ e₃ = 1) ∧ h ∈ doubledBase ∧
      g = v1 ^ e₁ * v2 ^ e₂ * v3 ^ e₃ * h := by
  obtain ⟨τ, hτ, r, hr, hprod⟩ := exists_translation_mul_rotation g
  obtain ⟨a, b, c, rfl⟩ :=
    LiteralBaseCompleteness.exists_translation_form hτ
  obtain ⟨sdb, hsdb, hsplit⟩ := vword_parity_decomp a b c
  refine ⟨a % 2, b % 2, c % 2, sdb * r,
    Int.emod_two_eq_zero_or_one a, Int.emod_two_eq_zero_or_one b,
    Int.emod_two_eq_zero_or_one c,
    Subgroup.mul_mem _ hsdb (rotations_le_doubledBase hr), ?_⟩
  rw [← hprod]
  rw [hsplit]
  group

/-- Conjugates of the moved lamp are classified by translation parity. -/
theorem conj_dee_parity (g : Base) :
    ∃ e₁ e₂ e₃ : ℤ, (e₁ = 0 ∨ e₁ = 1) ∧ (e₂ = 0 ∨ e₂ = 1) ∧
      (e₃ = 0 ∨ e₃ = 1) ∧
      baseMap g * dee * (baseMap g)⁻¹ =
        baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) * dee *
          (baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃))⁻¹ := by
  obtain ⟨e₁, e₂, e₃, h, he₁, he₂, he₃, hmem, rfl⟩ := parity_factorization g
  exact ⟨e₁, e₂, e₃, he₁, he₂, he₃, by
    rw [show ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃ * h : Base) =
        ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) * h from by group]
    exact conj_dee_absorb hmem⟩

/-! ## The marked commutator -/

/-- The marked word is the commutator of the moved lamp with its
`v₁`-conjugate. -/
theorem mark_eq_dee_commutator :
    mark = ⁅dee, baseMap (v1 : Base) * dee * (baseMap (v1 : Base))⁻¹⁆ := by
  have hb : wordInMarkedGroup v1Word = baseMap (v1 : Base) :=
    (baseMap_generator v1Index).symm
  have hd : wordInMarkedGroup displacedLampWord = dee := rfl
  simp only [mark, markedWord, commutatorWord, map_mul, map_inv,
    commutatorElement_def, hb, hd]

/-! ## Conjugation transport of the commutator -/

private theorem commutator_conj_transport_generic (A X Y : MarkedGroup) :
    ⁅A * X * A⁻¹, A * Y * A⁻¹⁆ = A * ⁅X, Y⁆ * A⁻¹ := by
  simp only [commutatorElement_def]
  group

private theorem commutator_conj_transport {r : Base}
    (hr : Commute dee (baseMap r)) (X : MarkedGroup) :
    ⁅dee, baseMap r * X * (baseMap r)⁻¹⁆ =
      baseMap r * ⁅dee, X⁆ * (baseMap r)⁻¹ := by
  have hd : baseMap r * dee * (baseMap r)⁻¹ = dee := by
    rw [hr.symm.eq]
    group
  calc ⁅dee, baseMap r * X * (baseMap r)⁻¹⁆
      = ⁅baseMap r * dee * (baseMap r)⁻¹,
          baseMap r * X * (baseMap r)⁻¹⁆ := by rw [hd]
    _ = baseMap r * ⁅dee, X⁆ * (baseMap r)⁻¹ :=
        commutator_conj_transport_generic _ _ _

/-! ## The seven orbit words -/

private theorem orb001 : (x : Base) * v1 * x⁻¹ = v3 := x_conj_v1

private theorem orb010 :
    ((x : Base) * x) * v1 * (x * x)⁻¹ = v2 := by
  have h1 := x_conj_v1
  have h3 := x_conj_v3
  calc ((x : Base) * x) * v1 * (x * x)⁻¹
      = x * (x * v1 * x⁻¹) * x⁻¹ := by group
    _ = x * v3 * x⁻¹ := by rw [h1]
    _ = v2 := h3

private theorem orb011 :
    (z : Base) * v1 * z⁻¹ = v2 * v3 * ((v3 : Base) ^ 2)⁻¹ := by
  rw [z_conj_v1]
  rw [show ((v3 : Base) ^ 2) = v3 * v3 from sq v3]
  group

private theorem orb101 :
    ((y : Base) * z) * v1 * (y * z)⁻¹ =
      v1 * v3 * ((v1 : Base) ^ 2)⁻¹ := by
  have h13 : Commute (v1 : Base) v3 :=
    v1_commutes_translations v3_mem_translations
  have hz := z_conj_v1
  have hy2 := y_conj_v2
  have hy3 := y_conj_v3
  have hstep : ((y : Base) * z) * v1 * (y * z)⁻¹ =
      y * (v2 * v3⁻¹) * y⁻¹ := by
    rw [show ((y : Base) * z) * v1 * (y * z)⁻¹ =
      y * (z * v1 * z⁻¹) * y⁻¹ from by group, hz]
  rw [hstep,
    show (y : Base) * (v2 * v3⁻¹) * y⁻¹ =
      (y * v2 * y⁻¹) * (y * v3 * y⁻¹)⁻¹ from by group, hy2, hy3]
  have h23 : Commute (v2 : Base) v3 :=
    v2_commutes_translations v3_mem_translations
  calc ((v2 : Base)⁻¹ * v3) * (v1 * v2⁻¹)⁻¹
      = v2⁻¹ * (v3 * v2) * v1⁻¹ := by group
    _ = v2⁻¹ * (v2 * v3) * v1⁻¹ := by rw [h23.symm.eq]
    _ = v3 * v1⁻¹ := by group
    _ = v1 * v3 * ((v1 : Base) ^ 2)⁻¹ := by
        rw [h13.eq]; group

private theorem orb110 :
    ((y : Base) * x) * v1 * (y * x)⁻¹ =
      v1 * v2 * ((v2 : Base) ^ 2)⁻¹ := by
  have hstep : ((y : Base) * x) * v1 * (y * x)⁻¹ =
      y * v3 * y⁻¹ := by
    rw [show ((y : Base) * x) * v1 * (y * x)⁻¹ =
      y * (x * v1 * x⁻¹) * y⁻¹ from by group, x_conj_v1]
  rw [hstep, y_conj_v3, show ((v2 : Base) ^ 2)⁻¹ = v2⁻¹ * v2⁻¹ from by
    rw [sq]; group]
  group

private theorem orb111 :
    ((y : Base) * y * x) * v1 * (y * y * x)⁻¹ =
      v1 * v2 * v3 * ((v3 : Base) ^ 2)⁻¹ := by
  have h23 : Commute (v2 : Base) v3 :=
    v2_commutes_translations v3_mem_translations
  have hstep : ((y : Base) * y * x) * v1 * (y * y * x)⁻¹ =
      y * (v1 * v2⁻¹) * y⁻¹ := by
    rw [show ((y : Base) * y * x) * v1 * (y * y * x)⁻¹ =
      y * (y * (x * v1 * x⁻¹) * y⁻¹) * y⁻¹ from by group, x_conj_v1,
      y_conj_v3]
  rw [hstep,
    show (y : Base) * (v1 * v2⁻¹) * y⁻¹ =
      (y * v1 * y⁻¹) * (y * v2 * y⁻¹)⁻¹ from by group,
    y_conj_v1, y_conj_v2]
  rw [show ((v3 : Base) ^ 2)⁻¹ = v3⁻¹ * v3⁻¹ from by rw [sq]; group]
  calc (v1 : Base) * (v2⁻¹ * v3)⁻¹
      = v1 * (v3⁻¹ * v2) := by group
    _ = v1 * (v2 * v3⁻¹) := by
        rw [show (v3 : Base)⁻¹ * v2 = v2 * v3⁻¹ from
          (h23.inv_right.symm.eq)]
    _ = v1 * v2 * v3 * (v3⁻¹ * v3⁻¹) := by group

/-! ## The eight commutator reductions -/

private theorem conj_word_transport {r : Base}
    (hr : Commute dee (baseMap r)) (V : MarkedGroup) :
    (baseMap r * V * (baseMap r)⁻¹) * dee *
        (baseMap r * V * (baseMap r)⁻¹)⁻¹ =
      baseMap r * (V * dee * V⁻¹) * (baseMap r)⁻¹ := by
  have hd : (baseMap r)⁻¹ * dee * baseMap r = dee := by
    calc (baseMap r)⁻¹ * dee * baseMap r
        = (baseMap r)⁻¹ * (dee * baseMap r) := by group
      _ = (baseMap r)⁻¹ * (baseMap r * dee) := by rw [hr.eq]
      _ = dee := by group
  calc (baseMap r * V * (baseMap r)⁻¹) * dee *
      (baseMap r * V * (baseMap r)⁻¹)⁻¹
      = baseMap r * V * ((baseMap r)⁻¹ * dee * baseMap r) * V⁻¹ *
          (baseMap r)⁻¹ := by group
    _ = baseMap r * V * dee * V⁻¹ * (baseMap r)⁻¹ := by rw [hd]
    _ = baseMap r * (V * dee * V⁻¹) * (baseMap r)⁻¹ := by group

private theorem mark_conj_mem {g : MarkedGroup} :
    g * mark * g⁻¹ ∈ markSubgroup := by
  rw [show g * mark * g⁻¹ = mark from by
    rw [← (mark_central g).eq]; group]
  exact Subgroup.mem_zpowers _

/-- Reduction of a single parity-conjugate commutator via a centralizing
rotation word and an orbit identity. -/
private theorem commutator_via_orbit {r vγ : Base}
    (hr : Commute dee (baseMap r)) {s : Base} (hs : s ∈ doubledBase)
    (horb : r * v1 * r⁻¹ = vγ * s) :
    ⁅dee, baseMap vγ * dee * (baseMap vγ)⁻¹⁆ ∈ markSubgroup := by
  have habs : baseMap vγ * dee * (baseMap vγ)⁻¹ =
      baseMap (r * v1 * r⁻¹) * dee * (baseMap (r * v1 * r⁻¹))⁻¹ := by
    rw [horb]
    exact (conj_dee_absorb hs).symm
  have hrw : baseMap (r * v1 * r⁻¹) * dee *
      (baseMap (r * v1 * r⁻¹))⁻¹ =
      baseMap r * (baseMap v1 * dee * (baseMap v1)⁻¹) * (baseMap r)⁻¹ := by
    rw [map_mul, map_mul, map_inv]
    exact conj_word_transport hr (baseMap v1)
  rw [habs, hrw, commutator_conj_transport hr, ← mark_eq_dee_commutator]
  exact mark_conj_mem

/-- The parity-indexed commutators all lie in the marked subgroup. -/
theorem commutator_parity {e₁ e₂ e₃ : ℤ}
    (he₁ : e₁ = 0 ∨ e₁ = 1) (he₂ : e₂ = 0 ∨ e₂ = 1)
    (he₃ : e₃ = 0 ∨ e₃ = 1) :
    ⁅dee, baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) * dee *
      (baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃))⁻¹⁆ ∈
      markSubgroup := by
  have hxx : Commute dee (baseMap ((x : Base) * x)) := by
    rw [map_mul]
    exact dee_commutes_x.mul_right dee_commutes_x
  have hyz : Commute dee (baseMap ((y : Base) * z)) := by
    rw [map_mul]
    exact dee_commutes_y.mul_right dee_commutes_z
  have hyx : Commute dee (baseMap ((y : Base) * x)) := by
    rw [map_mul]
    exact dee_commutes_y.mul_right dee_commutes_x
  have hyyx : Commute dee (baseMap ((y : Base) * y * x)) := by
    rw [map_mul, map_mul]
    exact (dee_commutes_y.mul_right dee_commutes_y).mul_right
      dee_commutes_x
  have hone : Commute dee (baseMap (1 : Base)) := by
    rw [map_one]
    exact Commute.one_right dee
  rcases he₁ with rfl | rfl <;> rcases he₂ with rfl | rfl <;>
    rcases he₃ with rfl | rfl <;>
    simp only [zpow_zero, zpow_one, one_mul, mul_one]
  · -- (0,0,0)
    rw [map_one]
    simp
  · -- (0,0,1) : v3 = x v1 x⁻¹
    exact commutator_via_orbit dee_commutes_x
      (Subgroup.one_mem doubledBase) (by rw [orb001, mul_one])
  · -- (0,1,0) : v2 = x² v1 x⁻²
    exact commutator_via_orbit hxx
      (Subgroup.one_mem doubledBase) (by rw [orb010, mul_one])
  · -- (0,1,1) : v2 v3 correction v3⁻²
    exact commutator_via_orbit dee_commutes_z
      (Subgroup.inv_mem _ v_sq_mem_doubledBase.2.2) orb011
  · -- (1,0,0) : the marked word itself
    rw [← mark_eq_dee_commutator]
    exact Subgroup.mem_zpowers _
  · -- (1,0,1) : v1 v3 correction v1⁻²
    exact commutator_via_orbit hyz
      (Subgroup.inv_mem _ v_sq_mem_doubledBase.1) orb101
  · -- (1,1,0) : v1 v2 correction v2⁻²
    exact commutator_via_orbit hyx
      (Subgroup.inv_mem _ v_sq_mem_doubledBase.2.1) orb110
  · -- (1,1,1) : v1 v2 v3 correction v3⁻²
    exact commutator_via_orbit hyyx
      (Subgroup.inv_mem _ v_sq_mem_doubledBase.2.2) orb111

/-! ## Arbitrary pairs of conjugates commute in the quotient -/

private theorem vword_difference (e₁ e₂ e₃ d₁ d₂ d₃ : ℤ) :
    (v1 : Base) ^ d₁ * v2 ^ d₂ * v3 ^ d₃ =
      ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) *
        ((v1 : Base) ^ (d₁ - e₁) * v2 ^ (d₂ - e₂) * v3 ^ (d₃ - e₃)) := by
  have h12 : Commute (v1 : Base) v2 :=
    v1_commutes_translations v2_mem_translations
  have h13 : Commute (v1 : Base) v3 :=
    v1_commutes_translations v3_mem_translations
  have h23 : Commute (v2 : Base) v3 :=
    v2_commutes_translations v3_mem_translations
  have c1 : Commute ((v1 : Base) ^ (d₁ - e₁)) ((v2 : Base) ^ e₂) :=
    h12.zpow_zpow _ _
  have c2 : Commute ((v1 : Base) ^ (d₁ - e₁)) ((v3 : Base) ^ e₃) :=
    h13.zpow_zpow _ _
  have c3 : Commute ((v2 : Base) ^ (d₂ - e₂)) ((v3 : Base) ^ e₃) :=
    h23.zpow_zpow _ _
  have E1 : (v1 : Base) ^ d₁ = v1 ^ e₁ * v1 ^ (d₁ - e₁) := by
    rw [← zpow_add]; congr 1; ring
  have E2 : (v2 : Base) ^ d₂ = v2 ^ e₂ * v2 ^ (d₂ - e₂) := by
    rw [← zpow_add]; congr 1; ring
  have E3 : (v3 : Base) ^ d₃ = v3 ^ e₃ * v3 ^ (d₃ - e₃) := by
    rw [← zpow_add]; congr 1; ring
  rw [E1, E2, E3]
  calc ((v1 : Base) ^ e₁ * v1 ^ (d₁ - e₁)) *
      (v2 ^ e₂ * v2 ^ (d₂ - e₂)) * (v3 ^ e₃ * v3 ^ (d₃ - e₃))
      = (((v1 : Base) ^ e₁ * v2 ^ e₂) *
          (v1 ^ (d₁ - e₁) * v2 ^ (d₂ - e₂))) *
          (v3 ^ e₃ * v3 ^ (d₃ - e₃)) := by
        rw [c1.mul_mul_mul_comm]
    _ = ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) *
          ((v1 : Base) ^ (d₁ - e₁) * v2 ^ (d₂ - e₂) *
            v3 ^ (d₃ - e₃)) :=
        (c2.mul_left c3).mul_mul_mul_comm _ _
/-- **Orbit commutation modulo the sign.**  Any two base conjugates of
the moved lamp commute modulo the marked subgroup. -/
theorem orbit_commutator_mem (g₁ g₂ : Base) :
    ⁅baseMap g₁ * dee * (baseMap g₁)⁻¹,
      baseMap g₂ * dee * (baseMap g₂)⁻¹⁆ ∈ markSubgroup := by
  obtain ⟨e₁, e₂, e₃, he₁, he₂, he₃, hEc⟩ := conj_dee_parity g₁
  obtain ⟨d₁, d₂, d₃, hd₁, hd₂, hd₃, hDc⟩ := conj_dee_parity g₂
  rw [hEc, hDc]
  rw [show baseMap ((v1 : Base) ^ d₁ * v2 ^ d₂ * v3 ^ d₃) =
      baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) *
        baseMap ((v1 : Base) ^ (d₁ - e₁) * v2 ^ (d₂ - e₂) *
          v3 ^ (d₃ - e₃)) from by
    rw [← map_mul, ← vword_difference e₁ e₂ e₃ d₁ d₂ d₃]]
  rw [show (baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) *
      baseMap ((v1 : Base) ^ (d₁ - e₁) * v2 ^ (d₂ - e₂) *
        v3 ^ (d₃ - e₃))) * dee *
      (baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) *
        baseMap ((v1 : Base) ^ (d₁ - e₁) * v2 ^ (d₂ - e₂) *
          v3 ^ (d₃ - e₃)))⁻¹ =
      baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) *
        (baseMap ((v1 : Base) ^ (d₁ - e₁) * v2 ^ (d₂ - e₂) *
          v3 ^ (d₃ - e₃)) * dee *
          (baseMap ((v1 : Base) ^ (d₁ - e₁) * v2 ^ (d₂ - e₂) *
            v3 ^ (d₃ - e₃)))⁻¹) *
        (baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃))⁻¹ from by
    group]
  rw [show ⁅baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) * dee *
      (baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃))⁻¹,
      baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) *
        (baseMap ((v1 : Base) ^ (d₁ - e₁) * v2 ^ (d₂ - e₂) *
          v3 ^ (d₃ - e₃)) * dee *
          (baseMap ((v1 : Base) ^ (d₁ - e₁) * v2 ^ (d₂ - e₂) *
            v3 ^ (d₃ - e₃)))⁻¹) *
        (baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃))⁻¹⁆ =
      baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃) *
        ⁅dee, baseMap ((v1 : Base) ^ (d₁ - e₁) * v2 ^ (d₂ - e₂) *
          v3 ^ (d₃ - e₃)) * dee *
          (baseMap ((v1 : Base) ^ (d₁ - e₁) * v2 ^ (d₂ - e₂) *
            v3 ^ (d₃ - e₃)))⁻¹⁆ *
        (baseMap ((v1 : Base) ^ e₁ * v2 ^ e₂ * v3 ^ e₃))⁻¹ from by
    simp only [commutatorElement_def]
    group]
  refine markSubgroup_normal.conj_mem _ ?_ _
  obtain ⟨sW, hsW, hWsplit⟩ :=
    vword_parity_decomp (d₁ - e₁) (d₂ - e₂) (d₃ - e₃)
  rw [hWsplit, conj_dee_absorb hsW]
  exact commutator_parity (Int.emod_two_eq_zero_or_one _)
    (Int.emod_two_eq_zero_or_one _) (Int.emod_two_eq_zero_or_one _)

/-! ## The involutive witness in the quotient -/

/-- The image of the base in the sign-free quotient. -/
def Lbar : Subgroup SignFreeQuotient := (proj.comp baseMap).range

theorem Lbar_hasKazhdanPropertyT : HasKazhdanPropertyT.{0, 0} ↥Lbar :=
  HasKazhdanPropertyT.of_surjective (proj.comp baseMap).rangeRestrict
    (proj.comp baseMap).rangeRestrict_surjective
    LiteralBaseP13PropertyTBridge.manuscriptBaseHasKazhdanPropertyT.{0}.1

theorem Lbar_compressed : ∀ γ ∈ Lbar,
    proj stable * γ * (proj stable)⁻¹ ∈ Lbar := by
  rintro γ ⟨g, rfl⟩
  obtain ⟨g', hg'⟩ := stable_conjugates_base_into_base g
  refine ⟨g', ?_⟩
  show proj (baseMap g') = _
  rw [hg']
  simp [map_mul, map_inv, MonoidHom.comp_apply]

theorem witness_dee :
    InvolutionCollapseEndpoint.IsInvolutiveCompressionWitness Lbar
      (proj stable) (proj dee) := by
  refine ⟨?_, ?_, ?_⟩
  · rw [← map_mul, dee_sq, map_one]
  · rintro γ ⟨g, rfl⟩
    have h := (dee_commutes_compressed g).symm
    have h2 := h.map proj
    simpa only [map_mul, map_inv, MonoidHom.comp_apply] using h2
  · rintro γ₁ ⟨g₁, rfl⟩ γ₂ ⟨g₂, rfl⟩
    have hmem := orbit_commutator_mem g₁ g₂
    have h1 : proj ⁅baseMap g₁ * dee * (baseMap g₁)⁻¹,
        baseMap g₂ * dee * (baseMap g₂)⁻¹⁆ = 1 :=
      (QuotientGroup.eq_one_iff _).mpr hmem
    rw [map_commutatorElement] at h1
    have h2 := commutatorElement_eq_one_iff_commute.mp h1
    simpa only [map_mul, map_inv, MonoidHom.comp_apply] using h2

/-! ## Nontriviality of the collapsed commutator -/

open ExplicitLinearModel MarkedCompression CliffordLamp SemidirectProduct in
theorem commutator_not_mem_markSubgroup :
    ⁅baseMap (v1 : Base), dee⁆ ∉ markSubgroup := by
  intro hmem
  obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp hmem
  have himg := congrArg witnessHom hn
  rw [map_zpow, witnessHom_mark, map_commutatorElement] at himg
  have hv1 : witnessHom (baseMap (v1 : Base)) =
      iotaAmbient alpha conjD_injective v1G := by
    have := witnessHom_base_generator
      LiteralNonMFPresentation.v1Index
    rw [show (v1 : Base) =
      PresentedGroup.of LiteralNonMFPresentation.v1Index from rfl]
    rw [this, matrixBaseGenerator_v1]
  have hdee : witnessHom dee =
      tAmbient alpha conjD_injective * cAmbient alpha conjD_injective *
        (tAmbient alpha conjD_injective)⁻¹ := by
    rw [dee, map_mul, map_mul, map_inv]
    rw [show witnessHom stable = tAmbient alpha conjD_injective from by
      rw [witnessHom]; exact realizationHom_stable _]
    rw [show witnessHom lamp = cAmbient alpha conjD_injective from by
      rw [witnessHom]; exact realizationHom_lamp _]
  rw [hv1, hdee] at himg
  have hlamp := CommutingLampCollapse.commutator_iota_lampConj
    alpha conjD_injective v1G
  rw [hlamp] at himg
  have hx12 : (iotaVertical alpha conjD_injective v1G *
      tVertical alpha conjD_injective) •
        rootCoset alpha conjD_injective ≠
      tVertical alpha conjD_injective •
        rootCoset alpha conjD_injective :=
    (moved_cosets_ne alpha conjD_injective
      v1G_not_mem_range).symm
  have hlampne := CommutingLampCollapse.lamp_mul_lamp_inv_ne
    (X := Cosets alpha conjD_injective) hx12
  rcases CommutingLampCollapse.zpow_mem_pair
      (signAmbient_sq alpha conjD_injective) n with h0 | h0 <;>
    rw [h0] at himg
  · have h2 : (inl (lamp (Cosets alpha conjD_injective)
        ((iotaVertical alpha conjD_injective v1G *
          tVertical alpha conjD_injective) •
            rootCoset alpha conjD_injective) *
        (lamp (Cosets alpha conjD_injective)
          (tVertical alpha conjD_injective •
            rootCoset alpha conjD_injective))⁻¹) :
        Ambient alpha conjD_injective) = inl 1 := by
      rw [map_one]
      exact himg.symm
    exact hlampne.1 (inl_injective h2)
  · have h2 : (inl (lamp (Cosets alpha conjD_injective)
        ((iotaVertical alpha conjD_injective v1G *
          tVertical alpha conjD_injective) •
            rootCoset alpha conjD_injective) *
        (lamp (Cosets alpha conjD_injective)
          (tVertical alpha conjD_injective •
            rootCoset alpha conjD_injective))⁻¹) :
        Ambient alpha conjD_injective) =
        inl (sign (Cosets alpha conjD_injective)) := himg.symm
    exact hlampne.2 (inl_injective h2)

theorem collapsed_commutator_ne_one :
    ⁅proj (baseMap (v1 : Base)), proj dee⁆ ≠ 1 := by
  intro hc
  rw [← map_commutatorElement] at hc
  exact commutator_not_mem_markSubgroup
    ((QuotientGroup.eq_one_iff _).mp hc)

/-! ## Endpoints -/

instance signFreeQuotient_countable : Countable SignFreeQuotient :=
  Quotient.countable

theorem proj_baseMap_v1_mem : proj (baseMap (v1 : Base)) ∈ Lbar :=
  ⟨v1, rfl⟩

/-- **The unsquared defect survives and is invisible**: the collapsed
commutator lies in the MF radical of the sign-free quotient and is
nontrivial there. -/
theorem signFree_collapse :
    ActualCoronaMFInvisible
      ⁅proj (baseMap (v1 : Base)), proj dee⁆ ∧
    ⁅proj (baseMap (v1 : Base)), proj dee⁆ ≠ 1 :=
  ⟨InvolutionCollapseEndpoint.actualCoronaMFInvisible_of_involutiveWitness
      Lbar_hasKazhdanPropertyT Lbar_compressed witness_dee
      proj_baseMap_v1_mem,
    collapsed_commutator_ne_one⟩

/-- **The sign-free quotient of the literal group is not MF.**  Killing
the central sign does not restore an injective corona representation. -/
theorem signFreeQuotient_not_isCDEOperatorMF :
    ¬ IsCDEOperatorMF SignFreeQuotient :=
  ProjectionCompressionCollapse.not_isCDEOperatorMF_of_involutiveWitness
    Lbar_hasKazhdanPropertyT Lbar_compressed witness_dee
    proj_baseMap_v1_mem collapsed_commutator_ne_one

/-- **Standard operator-MF endpoint.**  The direct involutive-compression
argument is stated above in the genuine-corona convention; the proved
equivalence of conventions gives the ordinary operator-MF conclusion. -/
theorem signFreeQuotient_not_isOperatorMF :
    ¬ IsOperatorMF SignFreeQuotient := by
  rw [← isCDEOperatorMF_iff_isOperatorMF]
  exact signFreeQuotient_not_isCDEOperatorMF

/-- **Premise-free finitely presented non-MF existence theorem from the
sign-free route.**  Its witness is `SignFreeQuotient`, and its obstruction is
the surviving unsquared commutator in `signFree_collapse`; it does not invoke
the central-sign non-MF endpoint. -/
theorem exists_finitelyPresented_signFree_not_isOperatorMF :
    ∃ (G : Type) (_ : Group G),
      Group.IsFinitelyPresented G ∧ ¬ IsOperatorMF G :=
  ⟨SignFreeQuotient, inferInstance,
    signFreeQuotient_finitelyPresented,
    signFreeQuotient_not_isOperatorMF⟩

/-- **The sign is not the whole radical**: the unsquared commutator is
not a power of the marked word, so the subgroup generated by the sign
is properly contained in what every corona representation must kill. -/
theorem commutator_not_zpow_mark :
    ⁅baseMap (v1 : Base), dee⁆ ∉ Subgroup.zpowers mark :=
  commutator_not_mem_markSubgroup

/-- **The sign-free quotient has a nontrivial MF radical.**  The subgroup
every corona representation of `E/⟨w⟩` must kill is not the trivial one:
the collapsed defect lies in it and is not the identity.  This is the
radical form of `signFreeQuotient_not_isCDEOperatorMF`, and the formal
counterpart of the manuscript's assertion that the MF radical of `E`
properly contains `{1, w}`. -/
theorem actualCoronaMFResidual_ne_bot :
    actualCoronaMFResidual SignFreeQuotient ≠ ⊥ := by
  intro hbot
  have hmem : ⁅proj (baseMap (v1 : Base)), proj dee⁆ ∈
      actualCoronaMFResidual SignFreeQuotient :=
    mem_actualCoronaMFResidual_iff.mpr signFree_collapse.1
  rw [hbot, Subgroup.mem_bot] at hmem
  exact signFree_collapse.2 hmem

/-- **The trivial subgroup sits strictly below the radical.**  The order
form of `actualCoronaMFResidual_ne_bot`. -/
theorem bot_lt_actualCoronaMFResidual :
    ⊥ < actualCoronaMFResidual SignFreeQuotient :=
  lt_of_le_of_ne bot_le (Ne.symm actualCoronaMFResidual_ne_bot)

end

end LiteralSignFreeQuotient
end GroupApproximation
