import GroupApproximation.Sofic.LiteralBaseRelations

/-!
# The translation subgroup of the literal base is normal

The three printed translation generators generate an abelian subgroup.  The
nine printed action relations show intrinsically that each rotation generator
normalizes it.  This module carries that calculation out in the presented
group, without using the affine matrix quotient.
-/

namespace GroupApproximation
namespace LiteralBaseTranslationNormal

open LiteralBaseRelations
open scoped Pointwise

noncomputable section

private abbrev Base := LiteralNonMFPresentation.Base
private abbrev BaseGenerator := LiteralNonMFPresentation.BaseGenerator
private abbrev baseRelators := LiteralNonMFPresentation.baseRelators

/-- The subgroup generated by the three literal translations. -/
def translations : Subgroup Base :=
  Subgroup.closure ({v1, v2, v3} : Set Base)

/-- The subgroup generated by the three literal rotation letters. -/
def rotations : Subgroup Base :=
  Subgroup.closure ({x, y, z} : Set Base)

theorem v1_mem_translations : v1 ∈ translations :=
  Subgroup.subset_closure (by simp)

theorem v2_mem_translations : v2 ∈ translations :=
  Subgroup.subset_closure (by simp)

theorem v3_mem_translations : v3 ∈ translations :=
  Subgroup.subset_closure (by simp)

theorem x_mem_rotations : x ∈ rotations :=
  Subgroup.subset_closure (by simp)

theorem y_mem_rotations : y ∈ rotations :=
  Subgroup.subset_closure (by simp)

theorem z_mem_rotations : z ∈ rotations :=
  Subgroup.subset_closure (by simp)

theorem v1_commutes_translations {u : Base} (hu : u ∈ translations) :
    Commute v1 u := by
  induction hu using Subgroup.closure_induction with
  | mem u hu =>
      rcases hu with rfl | rfl | rfl
      · exact Commute.refl v1
      · exact commute_v1_v2
      · exact commute_v1_v3
  | one => exact Commute.one_right v1
  | mul a b _ _ ha hb => exact ha.mul_right hb
  | inv a _ ha => exact ha.inv_right

theorem v2_commutes_translations {u : Base} (hu : u ∈ translations) :
    Commute v2 u := by
  induction hu using Subgroup.closure_induction with
  | mem u hu =>
      rcases hu with rfl | rfl | rfl
      · exact commute_v1_v2.symm
      · exact Commute.refl v2
      · exact commute_v2_v3
  | one => exact Commute.one_right v2
  | mul a b _ _ ha hb => exact ha.mul_right hb
  | inv a _ ha => exact ha.inv_right

theorem v3_commutes_translations {u : Base} (hu : u ∈ translations) :
    Commute v3 u := by
  induction hu using Subgroup.closure_induction with
  | mem u hu =>
      rcases hu with rfl | rfl | rfl
      · exact commute_v1_v3.symm
      · exact commute_v2_v3.symm
      · exact Commute.refl v3
  | one => exact Commute.one_right v3
  | mul a b _ _ ha hb => exact ha.mul_right hb
  | inv a _ ha => exact ha.inv_right

/-- The subgroup generated by the three printed translations is abelian. -/
theorem translations_commute {a b : Base}
    (ha : a ∈ translations) (hb : b ∈ translations) : Commute a b := by
  induction ha using Subgroup.closure_induction with
  | mem a ha =>
      rcases ha with rfl | rfl | rfl
      · exact v1_commutes_translations hb
      · exact v2_commutes_translations hb
      · exact v3_commutes_translations hb
  | one => exact Commute.one_left b
  | mul a c _ _ ha hc => exact ha.mul_left hc
  | inv a _ ha => exact ha.inv_left

/-- A conjugation which preserves the three translation generators preserves
their entire generated subgroup. -/
theorem conj_mem_translations_of_generators
    (g : Base)
    (hgen : ∀ u ∈ ({v1, v2, v3} : Set Base),
      g * u * g⁻¹ ∈ translations) :
    ∀ {u : Base}, u ∈ translations → g * u * g⁻¹ ∈ translations := by
  intro u hu
  induction hu using Subgroup.closure_induction with
  | mem u hu => exact hgen u hu
  | one => simp
  | mul a b _ _ ha hb =>
      rw [show g * (a * b) * g⁻¹ = (g * a * g⁻¹) * (g * b * g⁻¹) by group]
      exact translations.mul_mem ha hb
  | inv a _ ha =>
      rw [show g * a⁻¹ * g⁻¹ = (g * a * g⁻¹)⁻¹ by group]
      exact translations.inv_mem ha

theorem x_conj_mem_translations {u : Base} (hu : u ∈ translations) :
    x * u * x⁻¹ ∈ translations := by
  refine conj_mem_translations_of_generators x ?_ hu
  intro a ha
  rcases ha with rfl | rfl | rfl
  · rw [x_conj_v1]; exact v3_mem_translations
  · rw [x_conj_v2]; exact v1_mem_translations
  · exact x_conj_v3.symm ▸ v2_mem_translations

theorem y_conj_mem_translations {u : Base} (hu : u ∈ translations) :
    y * u * y⁻¹ ∈ translations := by
  refine conj_mem_translations_of_generators y ?_ hu
  intro a ha
  rcases ha with rfl | rfl | rfl
  · rw [y_conj_v1]; exact v1_mem_translations
  · rw [y_conj_v2]
    exact translations.mul_mem (translations.inv_mem v2_mem_translations)
      v3_mem_translations
  · rw [y_conj_v3]
    exact translations.mul_mem v1_mem_translations
      (translations.inv_mem v2_mem_translations)

theorem z_conj_mem_translations {u : Base} (hu : u ∈ translations) :
    z * u * z⁻¹ ∈ translations := by
  refine conj_mem_translations_of_generators z ?_ hu
  intro a ha
  rcases ha with rfl | rfl | rfl
  · rw [z_conj_v1]
    exact translations.mul_mem v2_mem_translations
      (translations.inv_mem v3_mem_translations)
  · rw [z_conj_v2]
    exact translations.mul_mem v1_mem_translations
      (translations.inv_mem v3_mem_translations)
  · exact z_conj_v3.symm ▸ translations.inv_mem v3_mem_translations

theorem x_mem_normalizer : x ∈ Subgroup.normalizer translations := by
  rw [Subgroup.mem_normalizer_iff]
  intro u
  constructor
  · exact x_conj_mem_translations
  · intro hu
    have h := x_conj_mem_translations (x_conj_mem_translations hu)
    have heq : x * (x * (x * u * x⁻¹) * x⁻¹) * x⁻¹ =
        u := by
      calc
        _ = (x * x * x) * u * (x * x * x)⁻¹ := by group
        _ = u := by
          have hx : x * x * x = 1 := by simpa [pow_succ] using x_cube
          rw [hx, inv_one, one_mul, mul_one]
    rw [heq] at h
    exact h

theorem y_mem_normalizer : y ∈ Subgroup.normalizer translations := by
  rw [Subgroup.mem_normalizer_iff]
  intro u
  constructor
  · exact y_conj_mem_translations
  · intro hu
    have h := y_conj_mem_translations (y_conj_mem_translations hu)
    have heq : y * (y * (y * u * y⁻¹) * y⁻¹) * y⁻¹ =
        u := by
      calc
        _ = (y * y * y) * u * (y * y * y)⁻¹ := by group
        _ = u := by
          have hy : y * y * y = 1 := by simpa [pow_succ] using y_cube
          rw [hy, inv_one, one_mul, mul_one]
    rw [heq] at h
    exact h

theorem z_mem_normalizer : z ∈ Subgroup.normalizer translations := by
  rw [Subgroup.mem_normalizer_iff]
  intro u
  constructor
  · exact z_conj_mem_translations
  · intro hu
    have h := z_conj_mem_translations hu
    have heq : z * (z * u * z⁻¹) * z⁻¹ =
        u := by
      calc
        _ = (z * z) * u * (z * z)⁻¹ := by group
        _ = u := by
          have hz : z * z = 1 := by simpa [pow_two] using z_sq
          rw [hz, inv_one, one_mul, mul_one]
    rw [heq] at h
    exact h

/-- Every element of the literal base normalizes its translation subgroup. -/
theorem normalizer_translations_eq_top :
    Subgroup.normalizer (translations : Set Base) = ⊤ := by
  refine top_unique fun g _ => ?_
  refine PresentedGroup.generated_by
    (baseRelators : Set (FreeGroup BaseGenerator))
    (Subgroup.normalizer (translations : Set Base)) ?_ g
  intro i
  fin_cases i
  · exact translations.le_normalizer v1_mem_translations
  · exact translations.le_normalizer v2_mem_translations
  · exact translations.le_normalizer v3_mem_translations
  · exact x_mem_normalizer
  · exact y_mem_normalizer
  · exact z_mem_normalizer

/-- The translation and rotation subgroups generate the whole literal base. -/
theorem translations_sup_rotations : translations ⊔ rotations = ⊤ := by
  refine top_unique fun g _ => ?_
  refine PresentedGroup.generated_by
    (baseRelators : Set (FreeGroup BaseGenerator))
    (translations ⊔ rotations) ?_ g
  intro i
  fin_cases i
  · exact (show translations ≤ translations ⊔ rotations from le_sup_left)
      v1_mem_translations
  · exact (show translations ≤ translations ⊔ rotations from le_sup_left)
      v2_mem_translations
  · exact (show translations ≤ translations ⊔ rotations from le_sup_left)
      v3_mem_translations
  · exact (show rotations ≤ translations ⊔ rotations from le_sup_right) x_mem_rotations
  · exact (show rotations ≤ translations ⊔ rotations from le_sup_right) y_mem_rotations
  · exact (show rotations ≤ translations ⊔ rotations from le_sup_right) z_mem_rotations

/-- Every element has a translation--rotation factorization.  Uniqueness is
the remaining algebraic ingredient required for presentation completeness. -/
theorem exists_translation_mul_rotation (g : Base) :
    ∃ a ∈ translations, ∃ r ∈ rotations, a * r = g := by
  have hnorm : rotations ≤ Subgroup.normalizer (translations : Set Base) := by
    rw [normalizer_translations_eq_top]
    exact le_top
  have hg : g ∈ translations ⊔ rotations := by
    rw [translations_sup_rotations]
    exact Subgroup.mem_top g
  change g ∈ (↑(translations ⊔ rotations) : Set Base) at hg
  rw [show (↑(translations ⊔ rotations) : Set Base) =
      (translations : Set Base) * (rotations : Set Base) from
    Subgroup.coe_mul_of_right_le_normalizer_left translations rotations hnorm] at hg
  rcases hg with ⟨a, ha, r, hr, harg⟩
  exact ⟨a, ha, r, hr, harg⟩

end

end LiteralBaseTranslationNormal
end GroupApproximation
