import GroupApproximation.Algebra.ProductFinitePresentation
import GroupApproximation.Higman.AmalgamPushout

/-!
# The camouflage amalgam

This file isolates the group-theoretic compiler behind MF camouflage.  Given a
group `B`, an element `d : B`, and a visible group `Q`, it forms the amalgam

`B *_<d> (Q × <d>)`.

The main result is target-independent: if every homomorphism `B → T` is
trivial, then precomposition with the canonical projection to `Q` is a
bijection on `T`-valued homomorphisms.  If `d` normally generates `B`, the
kernel of that projection is exactly the normal closure of the image of `d`.
No approximation-theoretic input occurs in this file.
-/

namespace GroupApproximation
namespace MFCamouflage

open Monoid

variable {B Q : Type} [Group B] [Group Q]

/-- The cyclic edge group generated by the distinguished element. -/
abbrev Edge (d : B) : Subgroup B := Subgroup.closure ({d} : Set B)

/-- The edge embedding into the black-hole vertex. -/
abbrev leftEdge (d : B) : Edge d →* B := (Edge d).subtype

/-- The edge embedding as the second coordinate of the visible vertex. -/
abbrev rightEdge (d : B) (Q : Type) [Group Q] : Edge d →* Q × Edge d :=
  MonoidHom.inr Q (Edge d)

/-- The camouflage amalgam `B *_<d> (Q × <d>)`. -/
abbrev Camouflage (d : B) (Q : Type) [Group Q] : Type :=
  Higman.Amalgam.Push (leftEdge d) (rightEdge d Q)

/-- Inclusion of the black-hole vertex. -/
abbrev blackHole (d : B) (Q : Type) [Group Q] : B →* Camouflage d Q :=
  PushoutI.of (φ := Higman.Amalgam.famHom (leftEdge d) (rightEdge d Q)) false

/-- Inclusion of the product vertex. -/
abbrev productVertex (d : B) (Q : Type) [Group Q] :
    Q × Edge d →* Camouflage d Q :=
  PushoutI.of (φ := Higman.Amalgam.famHom (leftEdge d) (rightEdge d Q)) true

/-- The visible copy of `Q` inside the amalgam. -/
def visible (d : B) (Q : Type) [Group Q] : Q →* Camouflage d Q :=
  (productVertex d Q).comp (MonoidHom.inl Q (Edge d))

/-- The two vertex maps defining the projection. -/
def projectionFamily (d : B) (Q : Type) [Group Q] :
    ∀ b, Higman.Amalgam.fam B (Q × Edge d) b →* Q
  | false => 1
  | true => MonoidHom.fst Q (Edge d)

/-- The split projection which kills `B` and forgets the edge coordinate. -/
def projection (d : B) (Q : Type) [Group Q] : Camouflage d Q →* Q := by
  refine PushoutI.lift
    (projectionFamily d Q)
    (1 : Edge d →* Q) ?_
  intro b
  cases b <;> ext x <;> rfl

@[simp] theorem projection_blackHole (d : B) (Q : Type) [Group Q]
    (b : B) : projection d Q (blackHole d Q b) = 1 := by
  exact PushoutI.lift_of _ _ _ _

@[simp] theorem projection_productVertex (d : B) (Q : Type) [Group Q]
    (x : Q × Edge d) : projection d Q (productVertex d Q x) = x.1 := by
  exact PushoutI.lift_of _ _ _ _

@[simp] theorem projection_visible (d : B) (Q : Type) [Group Q]
    (q : Q) : projection d Q (visible d Q q) = q := by
  rfl

theorem projection_comp_visible (d : B) (Q : Type) [Group Q] :
    (projection d Q).comp (visible d Q) = MonoidHom.id Q := by
  ext q
  exact projection_visible d Q q

theorem projection_surjective (d : B) (Q : Type) [Group Q] :
    Function.Surjective (projection d Q) :=
  fun q ↦ ⟨visible d Q q, projection_visible d Q q⟩

theorem visible_injective (d : B) (Q : Type) [Group Q] :
    Function.Injective (visible d Q) :=
  Function.LeftInverse.injective (projection_visible d Q)

/-- The distinguished relation in the amalgam. -/
abbrev defect (d : B) (Q : Type) [Group Q] : Camouflage d Q :=
  blackHole d Q d

theorem blackHole_injective (d : B) (Q : Type) [Group Q] :
    Function.Injective (blackHole d Q) :=
  Higman.Amalgam.of_injective_push (leftEdge d) (rightEdge d Q)
    Subtype.val_injective (fun _ _ h ↦ congrArg Prod.snd h) false

theorem productVertex_injective (d : B) (Q : Type) [Group Q] :
    Function.Injective (productVertex d Q) :=
  Higman.Amalgam.of_injective_push (leftEdge d) (rightEdge d Q)
    Subtype.val_injective (fun _ _ h ↦ congrArg Prod.snd h) true

theorem defect_ne_one (d : B) (Q : Type) [Group Q] (hd : d ≠ 1) :
    defect d Q ≠ 1 := by
  intro h
  have h' : blackHole d Q d = blackHole d Q 1 := by simpa using h
  exact hd (blackHole_injective d Q h')

/-- The edge relation, expressed between the two vertex inclusions. -/
theorem product_edge_eq_blackHole (d : B) (Q : Type) [Group Q]
    (z : Edge d) :
    productVertex d Q (1, z) = blackHole d Q z.1 := by
  calc
    productVertex d Q (1, z) =
        PushoutI.base (Higman.Amalgam.famHom (leftEdge d) (rightEdge d Q)) z :=
      PushoutI.of_apply_eq_base
        (Higman.Amalgam.famHom (leftEdge d) (rightEdge d Q)) true z
    _ = blackHole d Q z.1 :=
      (PushoutI.of_apply_eq_base
        (Higman.Amalgam.famHom (leftEdge d) (rightEdge d Q)) false z).symm

/-- Every product-vertex element is its visible part times its edge part. -/
theorem productVertex_eq_visible_mul_blackHole (d : B) (Q : Type) [Group Q]
    (x : Q × Edge d) :
    productVertex d Q x = visible d Q x.1 * blackHole d Q x.2.1 := by
  calc
    productVertex d Q x =
        productVertex d Q ((x.1, 1) * (1, x.2)) := by simp
    _ = productVertex d Q (x.1, 1) * productVertex d Q (1, x.2) :=
      map_mul _ _ _
    _ = visible d Q x.1 * blackHole d Q x.2.1 := by
      rw [product_edge_eq_blackHole]
      rfl

section Target

variable {T : Type} [Monoid T]

/-- A map out of the amalgam factors through `Q` as soon as it kills the
black-hole vertex.  The factor is restriction to the canonical section. -/
theorem factor_through_projection (d : B) (Q : Type) [Group Q]
    (f : Camouflage d Q →* T) (hf : f.comp (blackHole d Q) = 1) :
    (f.comp (visible d Q)).comp (projection d Q) = f := by
  refine PushoutI.hom_ext_nonempty (fun b ↦ ?_)
  cases b with
  | false =>
      ext x
      have hx : f (blackHole d Q x) = 1 :=
        DFunLike.congr_fun hf x
      change f (visible d Q (projection d Q (blackHole d Q x))) =
        f (blackHole d Q x)
      rw [projection_blackHole, map_one, map_one, hx]
  | true =>
      ext x
      have hx : f (blackHole d Q x.2.1) = 1 :=
        DFunLike.congr_fun hf x.2.1
      change f (visible d Q (projection d Q (productVertex d Q x))) =
        f (productVertex d Q x)
      rw [projection_productVertex, productVertex_eq_visible_mul_blackHole,
        map_mul, hx, mul_one]

/-- **Black-hole amalgam factorization.**  If `B` has no nontrivial map to
`T`, precomposition with the projection is a natural bijection
`Hom(Q,T) ≃ Hom(W,T)`. -/
theorem precomp_bijective (d : B) (Q : Type) [Group Q]
    (hT : ∀ f : B →* T, f = 1) :
    Function.Bijective
      (fun f : Q →* T ↦ f.comp (projection d Q)) := by
  constructor
  · intro f g h
    ext q
    have hq := DFunLike.congr_fun h (visible d Q q)
    simpa using hq
  · intro f
    refine ⟨f.comp (visible d Q), ?_⟩
    exact factor_through_projection d Q f (hT (f.comp (blackHole d Q)))

end Target

/-- If `d` normally generates `B`, the projection kernel is the normal
closure of the one distinguished relation in the camouflage group. -/
theorem projection_ker_eq_normalClosure (d : B) (Q : Type) [Group Q]
    (hgen : Subgroup.normalClosure ({d} : Set B) = ⊤) :
    (projection d Q).ker =
      Subgroup.normalClosure ({defect d Q} : Set (Camouflage d Q)) := by
  let N := Subgroup.normalClosure ({defect d Q} : Set (Camouflage d Q))
  apply le_antisymm
  · intro x hx
    let qN : Camouflage d Q →* (Camouflage d Q ⧸ N) := QuotientGroup.mk' N
    have hkill : qN.comp (blackHole d Q) = 1 := by
      ext b
      have hb : b ∈ Subgroup.normalClosure ({d} : Set B) := by
        rw [hgen]
        exact Subgroup.mem_top b
      have hle : Subgroup.normalClosure ({d} : Set B) ≤
          (qN.comp (blackHole d Q)).ker := by
        refine Subgroup.normalClosure_le_normal (Set.singleton_subset_iff.mpr ?_)
        apply MonoidHom.mem_ker.mpr
        exact (QuotientGroup.eq_one_iff (defect d Q)).mpr
          (Subgroup.subset_closure (Set.mem_singleton _))
      exact MonoidHom.mem_ker.mp (hle hb)
    have hfactor := factor_through_projection d Q qN hkill
    apply (QuotientGroup.eq_one_iff x).mp
    rw [← DFunLike.congr_fun hfactor x, MonoidHom.comp_apply, hx, map_one]
  · refine Subgroup.normalClosure_le_normal (Set.singleton_subset_iff.mpr ?_)
    exact MonoidHom.mem_ker.mpr (projection_blackHole d Q d)

/-- Countability is preserved by the two-vertex pushout. -/
instance instCountable (d : B) (Q : Type) [Group Q]
    [Countable B] [Countable Q] : Countable (Camouflage d Q) := by
  haveI hEdge : Countable (Edge d) := Subtype.countable
  haveI hFamily : ∀ b : Bool,
      Countable (Higman.Amalgam.fam B (Q × Edge d) b) := by
    intro b
    cases b with
    | false =>
        change Countable B
        infer_instance
    | true =>
        change Countable (Q × Edge d)
        infer_instance
  haveI h0 : Countable
      (FreeMonoid (Σ b : Bool, Higman.Amalgam.fam B (Q × Edge d) b)) :=
    inferInstanceAs
      (Countable (List (Σ b : Bool, Higman.Amalgam.fam B (Q × Edge d) b)))
  haveI h1 : Countable (CoprodI (Higman.Amalgam.fam B (Q × Edge d))) :=
    Con.mk'_surjective.countable
  haveI h2 : Countable
      (FreeMonoid (CoprodI (Higman.Amalgam.fam B (Q × Edge d)) ⊕ Edge d)) :=
    inferInstanceAs
      (Countable (List
        (CoprodI (Higman.Amalgam.fam B (Q × Edge d)) ⊕ Edge d)))
  haveI h3 : Countable
      (Coprod (CoprodI (Higman.Amalgam.fam B (Q × Edge d))) (Edge d)) :=
    Con.mk'_surjective.countable
  exact Con.mk'_surjective.countable

/-- The compiler preserves finite presentability when the visible group is
finitely presented. -/
theorem isFinitelyPresented (d : B) (Q : Type) [Group Q]
    [Group.IsFinitelyPresented B] [Group.IsFinitelyPresented Q]
    [Group.IsFinitelyPresented (Edge d)] :
    Group.IsFinitelyPresented (Camouflage d Q) := by
  letI : Group.FG (Edge d) :=
    (Group.fg_iff_subgroup_fg _).mpr
      ((Subgroup.fg_iff _).mpr
        ⟨{d}, rfl, Set.finite_singleton d⟩)
  letI : Group.IsFinitelyPresented (Q × Edge d) := inferInstance
  exact Higman.Amalgam.isFinitelyPresented_push (leftEdge d) (rightEdge d Q)

end MFCamouflage
end GroupApproximation
