import GroupApproximation.Sofic.NormalKazhdanMFRadical
import GroupApproximation.Sofic.NormMFResidualFunctorial
import GroupApproximation.Sofic.NormallyGeneratedMFObstruction
import GroupApproximation.Sofic.CDEMFRadical
import GroupApproximation.Sofic.OperatorMFIncreasingDimensions
import Mathlib.GroupTheory.FinitelyPresentedGroup
import Mathlib.GroupTheory.Subgroup.Simple

/-!
# The torsion-free full-MF-radical construction

This file formalizes the algebraic and operator-MF part of the proposed
Fournier-Facio--Hull construction.  There are two deliberately explicit
interfaces.

Here **MF group** has the precise Carrión--Dadarlat--Eckhardt meaning.  The
literal predicate `IsCDEOperatorMF G` asks for an embedding into the unitary
group of a genuine cofinite norm-matrix C-star corona.  The equivalent
unitary-sequence predicate is `IsOperatorMF G`; their equivalence is proved by
formal polar correction in `CDEOperatorMF`.  Strictly increasing matrix sizes
are also proved equivalent in `OperatorMFIncreasingDimensions`.

Neither predicate is a definition of MF-ness of the reduced group C-star
algebra or of the full group C-star algebra.  Those are separate notions.

* `FournierFacioDefectData` records the HNN relations used to expose a marked
  Kazhdan-compression pattern, together with the simple subgroup and one
  noncommuting witness.  From these data Lean proves that the simple subgroup
  is contained in the compression defect.
* `DefectRoutingData` records the output of the relative common-quotient
  construction.  The existence of this output is the literature-dependent
  acylindrical-small-cancellation step and is not postulated as an axiom here.

Once routing is supplied, the mapped compression defect is the whole quotient.
The already formalized normal-Kazhdan compression theorem then proves that the
whole quotient is its MF radical.  The quotient-hereditary and MF-target
consequences are proved as well.

Mathlib currently has no formal theory of acylindrically hyperbolic groups or
Hull's suitable-subgroup small cancellation.  Accordingly this file does not
encode those words as opaque predicates and does not claim an unconditional
existence theorem for the routed data.  It formalizes exactly the part of the
argument whose definitions and theorems exist in the present trust surface.
-/

namespace GroupApproximation

open scoped commutatorElement

universe u v

/-! ## Elementary profile predicates -/

/-- A group is generated by two specified elements. -/
def IsTwoGenerated (G : Type u) [Group G] : Prop :=
  ∃ x y : G, Subgroup.closure ({x, y} : Set G) = ⊤

/-- The power formulation of torsion-freeness used by the construction. -/
def IsPowerTorsionFree (G : Type u) [Group G] : Prop :=
  ∀ (g : G) (n : ℕ), 0 < n → g ^ n = 1 → g = 1

/-! ## The hidden Fournier-Facio defect -/

/-- Proof-carrying algebraic input extracted from the Fournier-Facio HNN
skeleton.

`u` is the first stable letter, `s` is the selected element of the simple
factor, and `iota` is the property-`(T)` base map.  The field
`commutesAfterCompression` is precisely `[S,P₁]=1` in the paper.  The
element `witness` is the base element called `r` there. -/
structure FournierFacioDefectData
    (P : Type) (E : Type u) [Group P] [Group E] where
  /-- The property-`(T)` base map. -/
  iota : P →* E
  /-- The first stable letter. -/
  u : E
  /-- A selected nonidentity element of the simple factor. -/
  s : E
  /-- Property `(T)` of the base. -/
  kazhdan : HasKazhdanPropertyT.{0, 0} P
  /-- Conjugation by `u` compresses the base into itself. -/
  compresses : ∀ p : P, ∃ q : P, u * iota p * u⁻¹ = iota q
  /-- The selected simple-factor element commutes with the compressed base. -/
  commutesAfterCompression :
    ∀ p : P, Commute s (u * iota p * u⁻¹)
  /-- The embedded simple factor. -/
  simpleSubgroup : Subgroup E
  [simple : IsSimpleGroup simpleSubgroup]
  /-- The selected element belongs to the simple factor. -/
  s_mem : s ∈ simpleSubgroup
  /-- A base element witnessing that `s` is not central in the simple factor. -/
  witness : P
  /-- The witness also belongs to the simple factor. -/
  witness_mem : iota witness ∈ simpleSubgroup
  /-- The chosen commutator is nontrivial. -/
  witness_commutator_ne_one : ⁅s, iota witness⁆ ≠ 1

namespace FournierFacioDefectData

variable {P : Type} {E : Type u} [Group P] [Group E]
    (D : FournierFacioDefectData P E)

local instance : IsSimpleGroup D.simpleSubgroup := D.simple

/-- The marked Kazhdan-compression core hidden in the HNN skeleton.  Its root
is `u⁻¹ s u`, so transporting the root by `u` recovers `s`. -/
def core : KazhdanCompressionCore P E where
  iota := D.iota
  t := D.u
  c := D.u⁻¹ * D.s * D.u
  kazhdan := D.kazhdan
  compresses := D.compresses
  comm_c p := by
    show D.u⁻¹ * D.s * D.u * D.iota p =
      D.iota p * (D.u⁻¹ * D.s * D.u)
    have h := (D.commutesAfterCompression p).eq
    calc
      D.u⁻¹ * D.s * D.u * D.iota p =
          D.u⁻¹ * (D.s * (D.u * D.iota p * D.u⁻¹)) * D.u := by
            group
      _ = D.u⁻¹ * ((D.u * D.iota p * D.u⁻¹) * D.s) * D.u := by
            rw [h]
      _ = D.iota p * (D.u⁻¹ * D.s * D.u) := by
            group

/-- The transported root of the hidden pattern is the chosen simple-factor
element `s`. -/
@[simp] theorem core_transported : D.core.transported = D.s := by
  unfold core KazhdanCompressionCore.transported
  dsimp
  group

/-- The defect is exactly the normal closure of the displayed commutators
`[s,ι(p)]`. -/
theorem core_defectNormal_eq :
    D.core.defectNormal =
      Subgroup.normalClosure (Set.range fun p : P ↦ ⁅D.s, D.iota p⁆) := by
  unfold KazhdanCompressionCore.defectNormal
    KazhdanCompressionCore.defectSet
  rw [D.core_transported]
  rfl

/-- The chosen nontrivial commutator lies in the hidden compression defect. -/
theorem witness_commutator_mem_defectNormal :
    ⁅D.s, D.iota D.witness⁆ ∈ D.core.defectNormal := by
  rw [← D.core_transported]
  exact D.core.defect_mem_defectNormal D.witness

/-- The selected simple-factor element is nontrivial.  Otherwise its chosen
commutator witness would be trivial. -/
theorem s_ne_one : D.s ≠ 1 := by
  intro hs
  apply D.witness_commutator_ne_one
  rw [hs]
  simp

/-- **Defect saturation.**  The embedded simple factor is contained in the
normal closure of the compression defects.

The proof takes the preimage of the defect in the simple subgroup.  It is a
normal subgroup containing the selected nontrivial commutator, hence it is
the whole simple subgroup. -/
theorem simpleSubgroup_le_defectNormal :
    D.simpleSubgroup ≤ D.core.defectNormal := by
  let N : Subgroup D.simpleSubgroup :=
    D.core.defectNormal.comap D.simpleSubgroup.subtype
  letI : N.Normal := inferInstance
  have hcomm_mem_simple : ⁅D.s, D.iota D.witness⁆ ∈ D.simpleSubgroup := by
    rw [commutatorElement_def]
    exact D.simpleSubgroup.mul_mem
      (D.simpleSubgroup.mul_mem
        (D.simpleSubgroup.mul_mem D.s_mem D.witness_mem)
        (D.simpleSubgroup.inv_mem D.s_mem))
      (D.simpleSubgroup.inv_mem D.witness_mem)
  let x : D.simpleSubgroup :=
    ⟨⁅D.s, D.iota D.witness⁆, hcomm_mem_simple⟩
  have hxN : x ∈ N := by
    change ⁅D.s, D.iota D.witness⁆ ∈ D.core.defectNormal
    exact D.witness_commutator_mem_defectNormal
  have hxne : x ≠ 1 := by
    intro hx
    apply D.witness_commutator_ne_one
    exact congrArg Subtype.val hx
  have hNtop : N = ⊤ := by
    rcases IsSimpleGroup.eq_bot_or_eq_top_of_normal N inferInstance with
      hNbot | hNtop
    · exfalso
      have hxone : x = 1 := Subgroup.mem_bot.mp (hNbot ▸ hxN)
      exact hxne hxone
    · exact hNtop
  intro y hy
  have hyN : (⟨y, hy⟩ : D.simpleSubgroup) ∈ N := by
    rw [hNtop]
    exact Subgroup.mem_top _
  exact hyN

end FournierFacioDefectData

/-! ## The relative common-quotient output -/

/-- The algebraic output of the relative two-stage common-quotient theorem,
including both epimorphisms.

`source` is the map from the Fournier--Facio HNN skeleton, while `kazhdanMap`
is the map from the torsion-free hyperbolic Kazhdan input.  The finite
protected set used by the manuscript is `{1,s}`.  Acylindrical hyperbolicity
is deliberately absent: the present library has no definition of that
notion. -/
structure RelativeCommonQuotientData
    {P : Type} {E : Type u} [Group P] [Group E]
    (D : FournierFacioDefectData P E)
    (B : Type) [Group B] where
  Quotient : Type
  [groupQuotient : Group Quotient]
  source : E →* Quotient
  source_surjective : Function.Surjective source
  kazhdanMap : B →* Quotient
  kazhdanMap_surjective : Function.Surjective kazhdanMap
  [finitelyPresented : Group.IsFinitelyPresented Quotient]
  defect_surjective : D.core.defectNormal.map source = ⊤
  protected_injective : Set.InjOn source ({1, D.s} : Set E)
  generatorOne : Quotient
  generatorTwo : Quotient
  generates :
    Subgroup.closure ({generatorOne, generatorTwo} : Set Quotient) = ⊤
  torsionFree : IsPowerTorsionFree Quotient

/-- Proof-carrying output of the two-stage defect-routing construction.

This is data rather than an existence axiom.  In the intended application,
Hull's relative small-cancellation argument supplies `Quotient`, `quotient`,
the two generators, torsion preservation, finite presentation, and the fact
that the original defect maps onto the entire quotient. -/
structure DefectRoutingData
    {P : Type} {E : Type u} [Group P] [Group E]
    (D : FournierFacioDefectData P E) where
  /-- The routed common quotient. -/
  Quotient : Type
  [groupQuotient : Group Quotient]
  /-- The quotient map from the HNN skeleton. -/
  quotient : E →* Quotient
  /-- The map is onto. -/
  quotient_surjective : Function.Surjective quotient
  /-- The routed quotient is finitely presented. -/
  [finitelyPresented : Group.IsFinitelyPresented Quotient]
  /-- Property `(T)`, obtained from the second common-quotient map. -/
  kazhdan : HasKazhdanPropertyT.{0, 0} Quotient
  /-- The original compression defect maps onto the whole quotient. -/
  defect_surjective : D.core.defectNormal.map quotient = ⊤
  /-- The protected simple-factor element survives. -/
  protected_ne_one : quotient D.s ≠ 1
  /-- First generator produced by the second routing stage. -/
  generatorOne : Quotient
  /-- Second generator produced by the second routing stage. -/
  generatorTwo : Quotient
  /-- The two routed elements generate the quotient. -/
  generates :
    Subgroup.closure ({generatorOne, generatorTwo} : Set Quotient) = ⊤
  /-- Hull's torsion-preservation conclusion, in power form. -/
  torsionFree : IsPowerTorsionFree Quotient

namespace RelativeCommonQuotientData

variable {P : Type} {E : Type u} {B : Type}
    [Group P] [Group E] [Group B]
    {D : FournierFacioDefectData P E}
    (C : RelativeCommonQuotientData D B)

local instance : Group C.Quotient := C.groupQuotient
local instance : Group.IsFinitelyPresented C.Quotient := C.finitelyPresented

/-- A Kazhdan common-quotient input produces precisely the routed data used by
the MF-radical argument.  In particular, property `(T)` is derived through
the second epimorphism rather than postulated for the quotient. -/
def toDefectRoutingData (hB : HasKazhdanPropertyT.{0, 0} B) :
    DefectRoutingData D where
  Quotient := C.Quotient
  groupQuotient := C.groupQuotient
  quotient := C.source
  quotient_surjective := C.source_surjective
  finitelyPresented := C.finitelyPresented
  kazhdan := HasKazhdanPropertyT.of_surjective
    C.kazhdanMap C.kazhdanMap_surjective hB
  defect_surjective := C.defect_surjective
  protected_ne_one := by
    intro hs
    apply D.s_ne_one
    apply C.protected_injective
    · simp
    · simp
    · simpa using hs
  generatorOne := C.generatorOne
  generatorTwo := C.generatorTwo
  generates := C.generates
  torsionFree := C.torsionFree

end RelativeCommonQuotientData

namespace DefectRoutingData

variable {P : Type} {E : Type u} [Group P] [Group E]
    {D : FournierFacioDefectData P E}
    (R : DefectRoutingData.{u} D)

local instance : Group R.Quotient := R.groupQuotient
local instance : Group.IsFinitelyPresented R.Quotient := R.finitelyPresented

/-- A finitely presented routed quotient is countable. -/
theorem quotientCountable : Countable R.Quotient := by
  obtain ⟨n, f, hsurj, -⟩ := R.finitelyPresented.out
  letI : Countable (FreeGroup (Fin n)) := by
    have hfree : Function.Surjective
        (FreeGroup.mk : List (Fin n × Bool) → FreeGroup (Fin n)) := by
      intro g
      obtain ⟨L, hL⟩ := Quot.exists_rep g
      exact ⟨L, by rw [← FreeGroup.quot_mk_eq_mk, hL]⟩
    exact hfree.countable
  exact hsurj.countable

local instance : Countable R.Quotient := R.quotientCountable

/-- The routed quotient is nontrivial because the protected element survives. -/
theorem quotientNontrivial : Nontrivial R.Quotient :=
  ⟨⟨R.quotient D.s, 1, R.protected_ne_one⟩⟩

/-- The structure's two chosen elements witness two-generation. -/
theorem isTwoGenerated : IsTwoGenerated R.Quotient :=
  ⟨R.generatorOne, R.generatorTwo, R.generates⟩

/-- Defect routing commutes with descent of the marked pattern: the defect of
the mapped core is the whole quotient. -/
theorem mapped_defectNormal_eq_top :
    (D.core.map R.quotient).defectNormal = ⊤ := by
  apply top_unique
  rw [← R.defect_surjective]
  exact D.core.map_subgroup_le_defectNormal R.quotient
    D.core.defectNormal le_rfl

/-- **Full MF radical.**  Every element of the routed quotient is invisible
in every standard cofinite norm-matrix corona. -/
theorem coronaMFResidual_eq_top :
    coronaMFResidual R.Quotient = ⊤ := by
  letI : Countable R.Quotient := R.quotientCountable
  have hTtop :
      HasKazhdanPropertyT.{0, 0} (⊤ : Subgroup R.Quotient) :=
    HasKazhdanPropertyT.of_mulEquiv Subgroup.topEquiv R.kazhdan
  have htop_le : (⊤ : Subgroup R.Quotient) ≤
      coronaMFResidual R.Quotient := by
    apply KazhdanCompressionCore.normalKazhdan_le_coronaMFResidual
      (D.core.map R.quotient) (⊤ : Subgroup R.Quotient) hTtop
    rw [R.mapped_defectNormal_eq_top]
  exact top_unique htop_le

/-- **Literal CDE full radical.**  Every element is killed by every
homomorphism into the unitary group of every genuine norm-matrix C-star
corona. -/
theorem cdeMFResidual_eq_top : cdeMFResidual R.Quotient = ⊤ := by
  rw [cdeMFResidual_eq_coronaMFResidual]
  exact R.coronaMFResidual_eq_top

/-- Ultraproduct-language form of the full-radical theorem. -/
theorem normMFResidual_eq_top :
    normMFResidual R.Quotient = ⊤ := by
  letI : Countable R.Quotient := R.quotientCountable
  rw [← coronaMFResidual_eq_normMFResidual]
  exact R.coronaMFResidual_eq_top

/-- Every representation of the routed quotient in a standard cofinite
norm-matrix corona is the trivial homomorphism. -/
theorem coronaRepresentation_eq_one
    (X : ℕ → FiniteModel) (hX : ∀ n, 0 < Fintype.card (X n))
    (rho : R.Quotient →* NormMatrixCoronaUnitary X) : rho = 1 := by
  apply MonoidHom.ext
  intro g
  have hg : g ∈ coronaMFResidual R.Quotient := by
    rw [R.coronaMFResidual_eq_top]
    exact Subgroup.mem_top g
  exact hg X hX rho

/-- Every representation into the unitary group of a genuine CDE
norm-matrix C-star corona is trivial. -/
theorem cdeCoronaRepresentation_eq_one
    (X : ℕ → FiniteModel) [∀ n, Nonempty (X n)]
    (hX : ∀ n, 0 < Fintype.card (X n))
    (rho : R.Quotient →*
      unitary (NormMatrixCStarCorona (fun n ↦ X n))) : rho = 1 := by
  let sigma : R.Quotient →* NormMatrixCoronaUnitary X :=
    (normMatrixCoronaUnitaryEquiv X).symm.toMonoidHom.comp rho
  have hsigma : sigma = 1 := R.coronaRepresentation_eq_one X hX sigma
  apply MonoidHom.ext
  intro g
  apply (normMatrixCoronaUnitaryEquiv X).symm.injective
  simpa [sigma] using DFunLike.congr_fun hsigma g

/-- Every homomorphism from the routed quotient to any operator-MF group is
trivial.  The target need not be countable. -/
theorem hom_eq_one_to_isOperatorMF
    {M : Type*} [Group M] (hM : IsOperatorMF M)
    (f : R.Quotient →* M) : f = 1 := by
  letI : Countable R.Quotient := R.quotientCountable
  apply MonoidHom.ext
  intro g
  exact map_eq_one_of_normMFResidual_eq_top_to_isOperatorMF
    R.normMFResidual_eq_top hM f g

/-- Every homomorphism from the routed quotient to a finite group is
trivial. -/
theorem hom_eq_one_to_finite
    (M : Type) [Group M] [Finite M] (f : R.Quotient →* M) : f = 1 :=
  hom_eq_one_of_residual_eq_top_to_finite R.normMFResidual_eq_top M f

/-- Every homomorphism from the routed quotient to a countable residually
finite group is trivial. -/
theorem hom_eq_one_to_residuallyFinite
    {M : Type*} [Group M] [Countable M] [Group.ResiduallyFinite M]
    (f : R.Quotient →* M) : f = 1 :=
  hom_eq_one_of_residual_eq_top_to_residuallyFinite
    R.normMFResidual_eq_top f

/-- The routed quotient has no nontrivial finite quotient. -/
theorem no_nontrivial_finite_quotient
    (M : Type) [Group M] [Finite M] [Nontrivial M]
    (f : R.Quotient →* M) : ¬ Function.Surjective f :=
  not_surjective_of_residual_eq_top_to_finite
    R.normMFResidual_eq_top M f

/-- The routed quotient is not operator-MF. -/
theorem not_isOperatorMF : ¬ IsOperatorMF R.Quotient := by
  intro hMF
  have htrivial : MonoidHom.id R.Quotient = 1 :=
    R.hom_eq_one_to_isOperatorMF hMF (MonoidHom.id R.Quotient)
  apply R.protected_ne_one
  simpa using DFunLike.congr_fun htrivial (R.quotient D.s)

/-- Literal Carrión--Dadarlat--Eckhardt formulation of the non-MF theorem. -/
theorem not_isCDEOperatorMF : ¬ IsCDEOperatorMF R.Quotient := by
  rw [isCDEOperatorMF_iff_isOperatorMF]
  exact R.not_isOperatorMF

/-- The non-MF theorem is unchanged when the CDE convention requires the
matrix dimensions to be strictly increasing. -/
theorem not_isOperatorMFIncreasing : ¬ IsOperatorMFIncreasing R.Quotient := by
  rw [isOperatorMFIncreasing_iff]
  exact R.not_isOperatorMF

/-- The part of the proposed main theorem fully covered by the present Lean
library: finite presentation, two-generation, torsion-freeness, property
`(T)`, full MF radical, and failure of operator-MF. -/
theorem consequence_package :
    Group.IsFinitelyPresented R.Quotient ∧
      IsTwoGenerated R.Quotient ∧
      IsPowerTorsionFree R.Quotient ∧
      HasKazhdanPropertyT.{0, 0} R.Quotient ∧
      cdeMFResidual R.Quotient = ⊤ ∧
      ¬ IsOperatorMF R.Quotient ∧
      ¬ IsCDEOperatorMF R.Quotient :=
  ⟨R.finitelyPresented, R.isTwoGenerated, R.torsionFree, R.kazhdan,
    R.cdeMFResidual_eq_top, R.not_isOperatorMF, R.not_isCDEOperatorMF⟩

end DefectRoutingData

/-! ## Quotient-hereditary full radical -/

/-- Full corona MF radical passes through every surjective homomorphism.  The
target's countability is derived from the countable source. -/
theorem coronaMFResidual_eq_top_of_surjective
    {G : Type u} {H : Type v} [Group G] [Group H] [Countable G]
    (hG : coronaMFResidual G = ⊤) (f : G →* H)
    (hf : Function.Surjective f) : coronaMFResidual H = ⊤ := by
  letI : Countable H := hf.countable
  apply top_unique
  intro y _
  obtain ⟨x, rfl⟩ := hf y
  have hx : x ∈ coronaMFResidual G := by
    rw [hG]
    exact Subgroup.mem_top x
  exact map_coronaMFResidual_le f ⟨x, hx, rfl⟩

namespace DefectRoutingData

variable {P : Type} {E : Type u} [Group P] [Group E]
    {D : FournierFacioDefectData P E}
    (R : DefectRoutingData.{u} D)

local instance : Group R.Quotient := R.groupQuotient
local instance : Group.IsFinitelyPresented R.Quotient := R.finitelyPresented
local instance : Countable R.Quotient := R.quotientCountable

/-- Every quotient of the routed group again has full corona MF radical. -/
theorem quotient_coronaMFResidual_eq_top
    {H : Type*} [Group H] (q : R.Quotient →* H)
    (hq : Function.Surjective q) : coronaMFResidual H = ⊤ := by
  letI : Countable R.Quotient := R.quotientCountable
  exact coronaMFResidual_eq_top_of_surjective
    R.coronaMFResidual_eq_top q hq

/-- Every quotient of the routed group has full ultraproduct norm-MF
residual as well. -/
theorem quotient_normMFResidual_eq_top
    {H : Type*} [Group H] (q : R.Quotient →* H)
    (hq : Function.Surjective q) : normMFResidual H = ⊤ := by
  letI : Countable R.Quotient := R.quotientCountable
  letI : Countable H := hq.countable
  rw [← coronaMFResidual_eq_normMFResidual]
  exact R.quotient_coronaMFResidual_eq_top q hq

/-- Every nontrivial quotient of the routed group is non-MF. -/
theorem quotient_not_isOperatorMF
    {H : Type*} [Group H] [Nontrivial H]
    (q : R.Quotient →* H) (hq : Function.Surjective q) :
    ¬ IsOperatorMF H := by
  letI : Countable R.Quotient := R.quotientCountable
  letI : Countable H := hq.countable
  intro hMF
  have htop : coronaMFResidual H = ⊤ :=
    R.quotient_coronaMFResidual_eq_top q hq
  have hbot : coronaMFResidual H = ⊥ :=
    isOperatorMF_iff_coronaMFResidual_eq_bot.mp hMF
  obtain ⟨x, hx⟩ := exists_ne (1 : H)
  have hxres : x ∈ coronaMFResidual H := by
    rw [htop]
    exact Subgroup.mem_top x
  rw [hbot] at hxres
  exact hx (Subgroup.mem_bot.mp hxres)

/-- Literal CDE form: every nontrivial quotient of the routed group fails to
embed in the unitary group of a norm-matrix C-star corona. -/
theorem quotient_not_isCDEOperatorMF
    {H : Type*} [Group H] [Countable H] [Nontrivial H]
    (q : R.Quotient →* H) (hq : Function.Surjective q) :
    ¬ IsCDEOperatorMF H := by
  rw [isCDEOperatorMF_iff_isOperatorMF]
  exact R.quotient_not_isOperatorMF q hq

end DefectRoutingData

end GroupApproximation
