import GroupApproximation.Computability.BooneBaseWords
import GroupApproximation.Computability.BooneGroupTower
import GroupApproximation.Computability.BooneGroupGoodness
import GroupApproximation.Algebra.HNNCongr
import GroupApproximation.Algebra.PresentedGroupRelabel
import GroupApproximation.Computability.PresentationCodeList
import GroupApproximation.Algebra.HNNPresentation

/-!
# Carrying a presentation up the tower

The tower's stages are HNN extensions of each other, and each stage's
associated subgroups are generated by three explicit elements of the *base*
group: `Gsub a b M N = ⟨tw (a,b), sh (M,0), sh (0,N)⟩`.  So a presentation for
one stage should give a presentation for the next, by adjoining one letter and
three relators.

What makes that an induction rather than a sequence of ad-hoc steps is a
dictionary carried alongside: at every stage we must know *which word* names a
given base element, because the next stage's relators are built from the words
naming the three generators.  `StagePres` bundles the presentation with that
dictionary, and `compat` is the dictionary's defining property, stated for all
of the base at once by quantifying over words rather than elements.

`basePres` is the bottom: the base group is its own presentation, and the
dictionary is the identity.  `mk_word_tw` and `mk_word_sh` are the two
instances of `compat` the tower actually consumes, and `map_Gsub` is the image
of an associated subgroup, in the shape `HNNPresentation.srcSub` wants.
-/

namespace GroupApproximation
namespace BooneTowerPresentation

open BooneGroup Base BooneBaseWords

/-- A three-element range is the members of a three-element list. -/
theorem range_fin3 {α : Type} (f : Fin 3 → α) : Set.range f = {x | x ∈ [f 0, f 1, f 2]} := by
  ext x
  simp only [Set.mem_range, Set.mem_setOf_eq, List.mem_cons, List.not_mem_nil, or_false]
  constructor
  · rintro ⟨i, rfl⟩
    fin_cases i
    · exact Or.inl rfl
    · exact Or.inr (Or.inl rfl)
    · exact Or.inr (Or.inr rfl)
  · rintro (rfl | rfl | rfl)
    · exact ⟨0, rfl⟩
    · exact ⟨1, rfl⟩
    · exact ⟨2, rfl⟩

/-- The HNN relator attached to the `i`-th pair of generator words. -/
def hnnRelator {X : Type} (w v : Fin 3 → FreeGroup X) (i : Fin 3) :
    FreeGroup (Option X) :=
  HNNPresentation.stableWord * HNNPresentation.emb (w i) *
    (HNNPresentation.stableWord)⁻¹ * (HNNPresentation.emb (v i))⁻¹

/-- **The step's relators, as a list.**  The old relators pushed through the
inclusion of letters, then one new relator per generator. -/
theorem hnnRels_eq_list {X : Type} (rels : Set (FreeGroup X)) (L : List (FreeGroup X))
    (hL : {x | x ∈ L} = rels) (w v : Fin 3 → FreeGroup X) :
    HNNPresentation.hnnRels rels w v
      = {x | x ∈ L.map (fun r => HNNPresentation.emb r) ++
          [hnnRelator w v 0, hnnRelator w v 1, hnnRelator w v 2]} := by
  rw [HNNPresentation.hnnRels, ← hL,
    show (fun i => HNNPresentation.stableWord * HNNPresentation.emb (w i) *
        (HNNPresentation.stableWord)⁻¹ * (HNNPresentation.emb (v i))⁻¹)
      = hnnRelator w v from rfl,
    range_fin3]
  ext x
  simp only [Set.mem_union, Set.mem_image, Set.mem_setOf_eq, List.mem_append,
    List.mem_map, List.mem_cons, List.not_mem_nil, or_false]

/-- The subgroup generated by a list of words, read in a presentation. -/
def wordsSub {X : Type} (rels : Set (FreeGroup X)) (L : List (FreeGroup X)) :
    Subgroup (PresentedGroup rels) :=
  Subgroup.closure (PresentedGroup.mk rels '' {x | x ∈ L})

theorem wordsSub_append {X : Type} (rels : Set (FreeGroup X)) (L₁ L₂ : List (FreeGroup X)) :
    wordsSub rels (L₁ ++ L₂) = wordsSub rels L₁ ⊔ wordsSub rels L₂ := by
  rw [wordsSub, wordsSub, wordsSub, ← Subgroup.closure_union, ← Set.image_union]
  congr 1
  congr 1
  ext x
  simp only [Set.mem_setOf_eq, List.mem_append, Set.mem_union]

/-- Pushing the words forward along a map of free groups pushes the subgroup
forward along the induced map of presented groups. -/
theorem wordsSub_map {X Y : Type} {rels : Set (FreeGroup X)} {rels' : Set (FreeGroup Y)}
    (f : FreeGroup X →* FreeGroup Y) (g : PresentedGroup rels →* PresentedGroup rels')
    (hg : ∀ u, g (PresentedGroup.mk rels u) = PresentedGroup.mk rels' (f u))
    (L : List (FreeGroup X)) :
    wordsSub rels' (L.map f) = (wordsSub rels L).map g := by
  rw [wordsSub, wordsSub, MonoidHom.map_closure]
  congr 1
  ext x
  simp only [Set.mem_image, Set.mem_setOf_eq, List.mem_map]
  constructor
  · rintro ⟨-, ⟨u, hu, rfl⟩, rfl⟩
    exact ⟨PresentedGroup.mk rels u, ⟨u, hu, rfl⟩, hg u⟩
  · rintro ⟨-, ⟨u, hu, rfl⟩, rfl⟩
    exact ⟨f u, ⟨u, hu, rfl⟩, (hg u).symm⟩

/-- A presentation of a stage, together with the dictionary saying which word
names which base element. -/
structure StagePres (S : Stage) where
  /-- The generators of this stage's presentation. -/
  Letters : Type
  /-- Its relators, as a finite list. -/
  relList : List (FreeGroup Letters)
  /-- Its relators. -/
  rels : Set (FreeGroup Letters)
  /-- The list spells the relator set. -/
  relList_spec : {x | x ∈ relList} = rels
  /-- The stage is the group these relators present. -/
  equiv : S.Carrier ≃* PresentedGroup rels
  /-- Where a word in the base's three letters goes. -/
  word : FreeGroup BooneGroup.Gen →* FreeGroup Letters
  /-- The dictionary: a base element named by a word is named at this stage by
  the transported word. -/
  compat : ∀ v : FreeGroup BooneGroup.Gen,
    equiv (S.ι (presentedEquiv (PresentedGroup.mk BooneGroup.rels v)))
      = PresentedGroup.mk rels (word v)
  /-- The subgroup generated by the base's `t` together with the stable letters
  adjoined so far --- the tower's `⟨t⟩'`. -/
  tsub : Subgroup S.Carrier
  /-- Words naming its generators: one for the base's `t`, one per stage. -/
  tsubWords : List (FreeGroup Letters)
  /-- Those words do generate it. -/
  tsub_spec : tsub.map equiv.toMonoidHom = wordsSub rels tsubWords
  /-- The alphabet size, stored offset by one as a code's is. -/
  gpred : ℕ
  /-- The generators, numbered.  Carried rather than derived: the letters are
  `Option`-nested, and an equality of types would have to be transported. -/
  enum : Letters ≃ Fin (gpred + 1)
  /-- Which letter each of the base's three generators became. -/
  letterOfGen : BooneGroup.Gen → Letters
  /-- The dictionary sends a generator to a generator. -/
  word_of : ∀ i, word (FreeGroup.of i) = FreeGroup.of (letterOfGen i)

/-- **The bottom of the tower.**  The base group is its own presentation, and
the dictionary is the identity. -/
def basePres : StagePres Stage.base where
  Letters := BooneGroup.Gen
  relList := [FreeGroup.of 1 * FreeGroup.of 2 * (FreeGroup.of 1)⁻¹ * (FreeGroup.of 2)⁻¹]
  rels := BooneGroup.rels
  relList_spec := by
    ext x
    simp only [Set.mem_setOf_eq, List.mem_cons, List.not_mem_nil, or_false,
      BooneGroup.rels, Set.mem_singleton_iff]
  equiv := presentedEquiv.symm
  word := MonoidHom.id _
  compat := by
    intro v
    show presentedEquiv.symm (presentedEquiv (PresentedGroup.mk BooneGroup.rels v)) = _
    rw [MulEquiv.symm_apply_apply]
    rfl
  tsub := Subgroup.closure {tGen}
  tsubWords := [FreeGroup.of 0]
  tsub_spec := by
    rw [MonoidHom.map_closure, wordsSub]
    congr 1
    ext x
    simp only [Set.mem_image, Set.mem_setOf_eq, List.mem_cons,
      List.not_mem_nil, or_false]
    constructor
    · rintro ⟨-, rfl, rfl⟩
      exact ⟨FreeGroup.of 0, rfl, (ofBase_tGen).symm⟩
    · rintro ⟨-, rfl, rfl⟩
      exact ⟨tGen, rfl, ofBase_tGen⟩
  gpred := 2
  enum := Equiv.refl _
  letterOfGen := fun i => i
  word_of := fun _ => rfl

variable {S : Stage} (P : StagePres S)

/-- The word naming `tw p` at this stage. -/
theorem mk_word_tw (p : ℤ × ℤ) :
    P.equiv (S.ι (tw p)) = PresentedGroup.mk P.rels (P.word (twWord p)) := by
  have h := P.compat (twWord p)
  rwa [presentedEquiv_twWord] at h

/-- The word naming `sh p` at this stage. -/
theorem mk_word_sh (p : ℤ × ℤ) :
    P.equiv (S.ι (sh p)) = PresentedGroup.mk P.rels (P.word (shWord p)) := by
  have h := P.compat (shWord p)
  rwa [presentedEquiv_shWord] at h

/-- The three words naming the generators of `Gsub a b M N`. -/
def gsubWords (a b M N : ℤ) : Fin 3 → FreeGroup P.Letters :=
  ![P.word (twWord (a, b)), P.word (shWord (M, 0)), P.word (shWord (0, N))]

/-- **The associated subgroup, transported.**  Its image at this stage is the
subgroup generated by the three words, which is the shape
`HNNPresentation.srcSub` asks for. -/
theorem map_Gsub (a b M N : ℤ) :
    ((Gsub a b M N).map S.ι).map P.equiv.toMonoidHom
      = Subgroup.closure
          (Set.range (fun i => PresentedGroup.mk P.rels (gsubWords P a b M N i))) := by
  rw [Gsub_eq_closure, MonoidHom.map_closure, MonoidHom.map_closure]
  congr 1
  simp only [Set.image_insert_eq, Set.image_singleton]
  ext x
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff, Set.mem_range,
    MulEquiv.coe_toMonoidHom]
  rw [mk_word_tw, mk_word_sh, mk_word_sh]
  constructor
  · rintro (rfl | rfl | rfl)
    · exact ⟨0, rfl⟩
    · exact ⟨1, rfl⟩
    · exact ⟨2, rfl⟩
  · rintro ⟨i, rfl⟩
    fin_cases i
    · exact Or.inl rfl
    · exact Or.inr (Or.inl rfl)
    · exact Or.inr (Or.inr rfl)

/-! ## The identification's action on the three generators

`BooneGroupGoodness.quadEquiv_coe_tw` already says where the `tw` generator
goes.  The two shift generators need the same treatment, and it is the same
proof: the identification is `emb⁻¹` followed by `emb'`, and `emb_sh` says what
each does to a shift. -/

theorem quadEquiv_coe_sh (a b c M : ℤ) (hM : M ≠ 0) (h : ℤ × ℤ)
    (hmem : sh (scaleIdx M M h) ∈ Gsub a b M M) :
    ((quadEquiv a b c M hM ⟨sh (scaleIdx M M h), hmem⟩ : Gsub c 0 (M ^ 2) 1) : BaseGroup)
      = sh (scaleIdx (M ^ 2) 1 h) := by
  have he₁ : Function.Injective (emb a b M M) := emb_injective hM hM
  have hsym : (MonoidHom.ofInjective he₁).symm ⟨sh (scaleIdx M M h), hmem⟩ = sh h := by
    apply (MonoidHom.ofInjective he₁).injective
    rw [MulEquiv.apply_symm_apply]
    exact Subtype.ext (emb_sh a b M M h).symm
  show emb c 0 (M ^ 2) 1
      ((MonoidHom.ofInjective he₁).symm ⟨sh (scaleIdx M M h), hmem⟩) = _
  rw [hsym, emb_sh]

theorem quadEquivLeft_coe_sh (a b c M : ℤ) (hM : M ≠ 0) (h : ℤ × ℤ)
    (hmem : sh (scaleIdx M M h) ∈ Gsub a b M M) :
    ((quadEquivLeft a b c M hM ⟨sh (scaleIdx M M h), hmem⟩ : Gsub 0 c 1 (M ^ 2)) : BaseGroup)
      = sh (scaleIdx 1 (M ^ 2) h) := by
  have he₁ : Function.Injective (emb a b M M) := emb_injective hM hM
  have hsym : (MonoidHom.ofInjective he₁).symm ⟨sh (scaleIdx M M h), hmem⟩ = sh h := by
    apply (MonoidHom.ofInjective he₁).injective
    rw [MulEquiv.apply_symm_apply]
    exact Subtype.ext (emb_sh a b M M h).symm
  show emb 0 c 1 (M ^ 2)
      ((MonoidHom.ofInjective he₁).symm ⟨sh (scaleIdx M M h), hmem⟩) = _
  rw [hsym, emb_sh]

/-- The three generators lie in the subgroup they generate.  The `tw` case is
not restated here: it is `BooneGroup.Base.tw_mem_Gsub`, reached unqualified
through the `open Base` above, and a second copy is the same proposition under
a second name. -/
theorem sh_fst_mem_Gsub (a b M N : ℤ) : sh (M, 0) ∈ Gsub a b M N := by
  rw [Gsub_eq_closure]
  exact Subgroup.subset_closure (by simp)

theorem sh_snd_mem_Gsub (a b M N : ℤ) : sh (0, N) ∈ Gsub a b M N := by
  rw [Gsub_eq_closure]
  exact Subgroup.subset_closure (by simp)

/-- The `tw` generator: `tw (a,b) ↦ tw (c,0)`. -/
theorem quadEquiv_gen_zero (a b c M : ℤ) (hM : M ≠ 0)
    (hmem : tw (a, b) ∈ Gsub a b M M) :
    ((quadEquiv a b c M hM ⟨tw (a, b), hmem⟩ : Gsub c 0 (M ^ 2) 1) : BaseGroup)
      = tw (c, 0) := by
  have hs : embIdx a b M M (0, 0) = (a, b) := by
    simp [embIdx]
  have hmem' : tw (embIdx a b M M (0, 0)) ∈ Gsub a b M M := by rw [hs]; exact hmem
  have h := quadEquiv_coe_tw a b c M hM (0, 0) hmem'
  have heq : (⟨tw (embIdx a b M M (0, 0)), hmem'⟩ : Gsub a b M M) = ⟨tw (a, b), hmem⟩ :=
    Subtype.ext (show tw (embIdx a b M M (0, 0)) = tw (a, b) by rw [hs])
  rw [heq] at h
  rw [h]
  congr 1
  simp [embIdx]

/-- The first shift generator: `sh (M,0) ↦ sh (M², 0)`. -/
theorem quadEquiv_gen_one (a b c M : ℤ) (hM : M ≠ 0)
    (hmem : sh (M, 0) ∈ Gsub a b M M) :
    ((quadEquiv a b c M hM ⟨sh (M, 0), hmem⟩ : Gsub c 0 (M ^ 2) 1) : BaseGroup)
      = sh (M ^ 2, 0) := by
  have hs : scaleIdx M M (1, 0) = (M, 0) := by
    simp [scaleIdx]
  have hmem' : sh (scaleIdx M M (1, 0)) ∈ Gsub a b M M := by rw [hs]; exact hmem
  have h := quadEquiv_coe_sh a b c M hM (1, 0) hmem'
  have heq : (⟨sh (scaleIdx M M (1, 0)), hmem'⟩ : Gsub a b M M) = ⟨sh (M, 0), hmem⟩ :=
    Subtype.ext (show sh (scaleIdx M M (1, 0)) = sh (M, 0) by rw [hs])
  rw [heq] at h
  rw [h]
  congr 1
  simp [scaleIdx]

/-- The second shift generator: `sh (0,M) ↦ sh (0, 1)`. -/
theorem quadEquiv_gen_two (a b c M : ℤ) (hM : M ≠ 0)
    (hmem : sh (0, M) ∈ Gsub a b M M) :
    ((quadEquiv a b c M hM ⟨sh (0, M), hmem⟩ : Gsub c 0 (M ^ 2) 1) : BaseGroup)
      = sh (0, 1) := by
  have hs : scaleIdx M M (0, 1) = (0, M) := by
    simp [scaleIdx]
  have hmem' : sh (scaleIdx M M (0, 1)) ∈ Gsub a b M M := by rw [hs]; exact hmem
  have h := quadEquiv_coe_sh a b c M hM (0, 1) hmem'
  have heq : (⟨sh (scaleIdx M M (0, 1)), hmem'⟩ : Gsub a b M M) = ⟨sh (0, M), hmem⟩ :=
    Subtype.ext (show sh (scaleIdx M M (0, 1)) = sh (0, M) by rw [hs])
  rw [heq] at h
  rw [h]
  congr 1
  simp [scaleIdx]

/-! ## The inductive step

Given a stage's presentation and words naming the generators of the two
associated subgroups, the next stage is presented by adjoining one letter and
the HNN relators.  The identification on the presentation side is the transport
of the stage's own identification, so the intertwining `HNNCongr` asks for holds
by construction; what has to be supplied from outside is where the
identification sends each of the three generators, which is the only
machine-dependent input. -/

section Step

variable {A B : Subgroup BaseGroup} (ψ : A ≃* B) (w v : Fin 3 → FreeGroup P.Letters)
  (hA : ((A.map S.ι).map P.equiv.toMonoidHom) = HNNPresentation.srcSub P.rels w)

include hA in
/-- Membership transports along the presentation. -/
theorem mem_srcSub_iff (g : S.Carrier) :
    g ∈ A.map S.ι ↔ P.equiv g ∈ HNNPresentation.srcSub P.rels w := by
  rw [← hA, Subgroup.mem_map_equiv, MulEquiv.symm_apply_apply]

variable (hB : ((B.map S.ι).map P.equiv.toMonoidHom) = HNNPresentation.tgtSub P.rels v)

/-- The identification, transported to the presentation. -/
noncomputable def stepPhi :
    HNNPresentation.srcSub P.rels w ≃* HNNPresentation.tgtSub P.rels v :=
  (((MulEquiv.subgroupCongr hA).symm.trans
      (P.equiv.subgroupMap (A.map S.ι)).symm).trans (S.stepEquiv ψ)).trans
    ((P.equiv.subgroupMap (B.map S.ι)).trans (MulEquiv.subgroupCongr hB))

/-- The transported identification agrees with the original, which is what
`HNNCongr` asks for.  Both sides are the stage's identification read through
the presentation, so the content is that the transport is by definition that
reading. -/
theorem stepPhi_intertwines :
    HNNCongr.Intertwines (S.stepEquiv ψ) (stepPhi P ψ w v hA hB) P.equiv
      (mem_srcSub_iff P w hA) := by
  intro a ha
  have hsub : (⟨P.equiv.symm (P.equiv a),
      by rw [MulEquiv.symm_apply_apply]; exact ha⟩ : (A.map S.ι)) = ⟨a, ha⟩ :=
    Subtype.ext (P.equiv.symm_apply_apply a)
  show P.equiv ((S.stepEquiv ψ ⟨P.equiv.symm (P.equiv a), _⟩ : B.map S.ι) : S.Carrier)
    = P.equiv ((S.stepEquiv ψ ⟨a, ha⟩ : B.map S.ι) : S.Carrier)
  rw [hsub]

/-- **The generator condition, reduced to the base.**  `HNNPresentation` asks
that the identification carry the `i`-th source generator to the `i`-th target
generator; this says it is enough to know that on the base element the word
names, which is where the machine's data enters. -/
theorem stepPhi_gen (a : BaseGroup) (ha : a ∈ A) (i : Fin 3)
    (hw : PresentedGroup.mk P.rels (w i) = P.equiv (S.ι a))
    (hv : PresentedGroup.mk P.rels (v i)
      = P.equiv (S.ι ((ψ ⟨a, ha⟩ : B) : BaseGroup))) :
    ((stepPhi P ψ w v hA hB
        ⟨HNNPresentation.srcGen P.rels w i, HNNPresentation.srcGen_mem P.rels w i⟩ :
          HNNPresentation.tgtSub P.rels v) : PresentedGroup P.rels)
      = HNNPresentation.tgtGen P.rels v i := by
  have hmem : S.ι a ∈ A.map S.ι := ⟨a, ha, rfl⟩
  have hsub : (⟨HNNPresentation.srcGen P.rels w i,
      HNNPresentation.srcGen_mem P.rels w i⟩ : HNNPresentation.srcSub P.rels w)
      = ⟨P.equiv (S.ι a), (mem_srcSub_iff P w hA (S.ι a)).1 hmem⟩ :=
    Subtype.ext hw
  rw [hsub, stepPhi_intertwines P ψ w v hA hB (S.ι a) hmem,
    S.coe_stepEquiv ψ a ha hmem]
  exact hv.symm

variable (hphi : ∀ i, ((stepPhi P ψ w v hA hB
    ⟨HNNPresentation.srcGen P.rels w i, HNNPresentation.srcGen_mem P.rels w i⟩ :
      HNNPresentation.tgtSub P.rels v) : PresentedGroup P.rels)
    = HNNPresentation.tgtGen P.rels v i)

/-- The step's isomorphism, named so its action on `of` and on `t` can be
computed once and reused. -/
noncomputable def stepEquivPres :
    (S.step ψ).Carrier ≃* PresentedGroup (HNNPresentation.hnnRels P.rels w v) :=
  (HNNCongr.congrEquiv (S.stepEquiv ψ) (stepPhi P ψ w v hA hB) P.equiv
      (mem_srcSub_iff P w hA) (stepPhi_intertwines P ψ w v hA hB)).trans
    (HNNPresentation.equivPres P.rels w v (stepPhi P ψ w v hA hB) hphi).symm

theorem stepEquivPres_of (a : S.Carrier) :
    stepEquivPres P ψ w v hA hB hphi (HNNExtension.of a)
      = HNNPresentation.bwdBase P.rels w v (P.equiv a) := by
  show (HNNPresentation.equivPres P.rels w v (stepPhi P ψ w v hA hB) hphi).symm
      (HNNCongr.congrEquiv (S.stepEquiv ψ) (stepPhi P ψ w v hA hB) P.equiv
        (mem_srcSub_iff P w hA) (stepPhi_intertwines P ψ w v hA hB)
        (HNNExtension.of a)) = _
  rw [show (HNNCongr.congrEquiv (S.stepEquiv ψ) (stepPhi P ψ w v hA hB) P.equiv
        (mem_srcSub_iff P w hA) (stepPhi_intertwines P ψ w v hA hB)
        (HNNExtension.of a)) = HNNExtension.of (P.equiv a) from
      HNNCongr.congrHom_of (S.stepEquiv ψ) (stepPhi P ψ w v hA hB) P.equiv
        (mem_srcSub_iff P w hA) (stepPhi_intertwines P ψ w v hA hB) a]
  show HNNPresentation.bwd P.rels w v (stepPhi P ψ w v hA hB) hphi
      (HNNExtension.of (P.equiv a)) = _
  rw [HNNPresentation.bwd, HNNExtension.lift_of]

theorem stepEquivPres_t :
    stepEquivPres P ψ w v hA hB hphi (HNNExtension.t : (S.step ψ).Carrier)
      = PresentedGroup.of none := by
  show (HNNPresentation.equivPres P.rels w v (stepPhi P ψ w v hA hB) hphi).symm
      (HNNCongr.congrEquiv (S.stepEquiv ψ) (stepPhi P ψ w v hA hB) P.equiv
        (mem_srcSub_iff P w hA) (stepPhi_intertwines P ψ w v hA hB)
        HNNExtension.t) = _
  rw [show (HNNCongr.congrEquiv (S.stepEquiv ψ) (stepPhi P ψ w v hA hB) P.equiv
        (mem_srcSub_iff P w hA) (stepPhi_intertwines P ψ w v hA hB)
        (HNNExtension.t : (S.step ψ).Carrier)) = HNNExtension.t from
      HNNCongr.congrHom_t (S.stepEquiv ψ) (stepPhi P ψ w v hA hB) P.equiv
        (mem_srcSub_iff P w hA) (stepPhi_intertwines P ψ w v hA hB)]
  show HNNPresentation.bwd P.rels w v (stepPhi P ψ w v hA hB) hphi HNNExtension.t = _
  rw [HNNPresentation.bwd, HNNExtension.lift_t]

/-- **The next stage's presentation.**  One letter and the HNN relators are
adjoined; the dictionary composes with the inclusion of the old letters, and the
new stable letter joins the generators of `⟨t⟩'`. -/
noncomputable def stepPres : StagePres (S.step ψ) where
  Letters := Option P.Letters
  relList := P.relList.map (fun r => HNNPresentation.emb r) ++
    [hnnRelator w v 0, hnnRelator w v 1, hnnRelator w v 2]
  rels := HNNPresentation.hnnRels P.rels w v
  relList_spec := (hnnRels_eq_list P.rels P.relList P.relList_spec w v).symm
  equiv := stepEquivPres P ψ w v hA hB hphi
  word := HNNPresentation.emb.comp P.word
  compat := by
    intro u
    show stepEquivPres P ψ w v hA hB hphi
      (HNNExtension.of (S.ι (presentedEquiv (PresentedGroup.mk BooneGroup.rels u)))) = _
    rw [stepEquivPres_of, P.compat u, HNNPresentation.bwdBase_mk]
    rfl
  tsub := liftedSubgroup (S.stepEquiv ψ) P.tsub
  tsubWords := P.tsubWords.map (fun z => HNNPresentation.emb z) ++ [FreeGroup.of none]
  gpred := P.gpred + 1
  enum := (Equiv.optionCongr P.enum).trans
    (PresentedGroupRelabel.optionFinEquiv (P.gpred + 1))
  letterOfGen := fun i => some (P.letterOfGen i)
  word_of := by
    intro i
    show HNNPresentation.emb (P.word (FreeGroup.of i)) = _
    rw [P.word_of, HNNPresentation.emb, FreeGroup.map.of]
  tsub_spec := by
    have h1 : (liftedSubgroup (S.stepEquiv ψ) P.tsub).map
        (stepEquivPres P ψ w v hA hB hphi).toMonoidHom
        = Subgroup.closure ((stepEquivPres P ψ w v hA hB hphi).toMonoidHom ''
            ((HNNExtension.of '' (P.tsub : Set S.Carrier)) ∪ {HNNExtension.t})) :=
      MonoidHom.map_closure _ _
    have h2 : ((stepEquivPres P ψ w v hA hB hphi).toMonoidHom ''
          (HNNExtension.of '' (P.tsub : Set S.Carrier)))
        = (HNNPresentation.bwdBase P.rels w v) ''
            ((P.equiv : S.Carrier →* PresentedGroup P.rels) '' (P.tsub : Set S.Carrier)) := by
      rw [Set.image_image, Set.image_image]
      exact congrArg (fun f => f '' (P.tsub : Set S.Carrier))
        (funext (stepEquivPres_of P ψ w v hA hB hphi))
    have h3 : Subgroup.closure ((P.equiv : S.Carrier →* PresentedGroup P.rels) ''
          (P.tsub : Set S.Carrier))
        = wordsSub P.rels P.tsubWords := by
      rw [show ((P.equiv : S.Carrier →* PresentedGroup P.rels) '' (P.tsub : Set S.Carrier))
          = ((P.tsub.map P.equiv.toMonoidHom : Subgroup (PresentedGroup P.rels)) :
              Set (PresentedGroup P.rels)) from (Subgroup.coe_map _ _).symm,
        Subgroup.closure_eq, P.tsub_spec]
    have h4 : Subgroup.closure
          ((stepEquivPres P ψ w v hA hB hphi).toMonoidHom '' {HNNExtension.t})
        = wordsSub (HNNPresentation.hnnRels P.rels w v) [FreeGroup.of none] := by
      rw [wordsSub]
      congr 1
      ext x
      simp only [Set.mem_image, Set.mem_setOf_eq, List.mem_cons,
        List.not_mem_nil, or_false]
      constructor
      · rintro ⟨-, rfl, rfl⟩
        exact ⟨FreeGroup.of none, rfl, stepEquivPres_t P ψ w v hA hB hphi⟩
      · rintro ⟨-, rfl, rfl⟩
        exact ⟨HNNExtension.t, rfl, (stepEquivPres_t P ψ w v hA hB hphi).symm⟩
    rw [h1, Set.image_union, Subgroup.closure_union, h2,
      ← MonoidHom.map_closure, h3, h4, wordsSub_append,
      wordsSub_map (rels := P.rels) HNNPresentation.emb
        (HNNPresentation.bwdBase P.rels w v) (HNNPresentation.bwdBase_mk P.rels w v)
        P.tsubWords]

end Step

/-! ## A right-moving quadruple's identification, instantiated

All three inputs the step needs are now available: the two subgroup images are
`map_Gsub`, and the generator condition reduces by `stepPhi_gen` to where the
identification sends the three base generators, which is exactly
`quadEquiv_gen_zero`, `quadEquiv_gen_one` and `quadEquiv_gen_two`. -/

theorem quad_hphi (a b c M : ℤ) (hM : M ≠ 0) (i : Fin 3) :
    ((stepPhi P (quadEquiv a b c M hM) (gsubWords P a b M M) (gsubWords P c 0 (M ^ 2) 1)
        (map_Gsub P a b M M) (map_Gsub P c 0 (M ^ 2) 1)
        ⟨HNNPresentation.srcGen P.rels (gsubWords P a b M M) i,
          HNNPresentation.srcGen_mem P.rels (gsubWords P a b M M) i⟩ :
          HNNPresentation.tgtSub P.rels (gsubWords P c 0 (M ^ 2) 1))
        : PresentedGroup P.rels)
      = HNNPresentation.tgtGen P.rels (gsubWords P c 0 (M ^ 2) 1) i := by
  fin_cases i
  · exact stepPhi_gen P _ _ _ _ _ (tw (a, b)) (tw_mem_Gsub a b M M) 0
      (mk_word_tw P (a, b)).symm
      (by rw [quadEquiv_gen_zero]; exact (mk_word_tw P (c, 0)).symm)
  · exact stepPhi_gen P _ _ _ _ _ (sh (M, 0)) (sh_fst_mem_Gsub a b M M) 1
      (mk_word_sh P (M, 0)).symm
      (by rw [quadEquiv_gen_one]; exact (mk_word_sh P (M ^ 2, 0)).symm)
  · exact stepPhi_gen P _ _ _ _ _ (sh (0, M)) (sh_snd_mem_Gsub a b M M) 2
      (mk_word_sh P (0, M)).symm
      (by rw [quadEquiv_gen_two]; exact (mk_word_sh P (0, 1)).symm)

/-- **The presentation of the next stage, for a right-moving quadruple.** -/
noncomputable def quadStepPres (a b c M : ℤ) (hM : M ≠ 0) :
    StagePres (S.step (quadEquiv a b c M hM)) :=
  stepPres P (quadEquiv a b c M hM) (gsubWords P a b M M) (gsubWords P c 0 (M ^ 2) 1)
    (map_Gsub P a b M M) (map_Gsub P c 0 (M ^ 2) 1) (quad_hphi P a b c M hM)

/-! ## The left-moving variant

Identical, with the target subgroup `G_{0c}^{1,M²}` in place of
`G_{c0}^{M²,1}`; the direction of the quadruple is visible only in where the
three generators land. -/

theorem quadEquivLeft_gen_zero (a b c M : ℤ) (hM : M ≠ 0)
    (hmem : tw (a, b) ∈ Gsub a b M M) :
    ((quadEquivLeft a b c M hM ⟨tw (a, b), hmem⟩ : Gsub 0 c 1 (M ^ 2)) : BaseGroup)
      = tw (0, c) := by
  have hs : embIdx a b M M (0, 0) = (a, b) := by simp [embIdx]
  have hmem' : tw (embIdx a b M M (0, 0)) ∈ Gsub a b M M := by rw [hs]; exact hmem
  have h := quadEquivLeft_coe_tw a b c M hM (0, 0) hmem'
  have heq : (⟨tw (embIdx a b M M (0, 0)), hmem'⟩ : Gsub a b M M) = ⟨tw (a, b), hmem⟩ :=
    Subtype.ext (show tw (embIdx a b M M (0, 0)) = tw (a, b) by rw [hs])
  rw [heq] at h
  rw [h]
  congr 1
  simp [embIdx]

theorem quadEquivLeft_gen_one (a b c M : ℤ) (hM : M ≠ 0)
    (hmem : sh (M, 0) ∈ Gsub a b M M) :
    ((quadEquivLeft a b c M hM ⟨sh (M, 0), hmem⟩ : Gsub 0 c 1 (M ^ 2)) : BaseGroup)
      = sh (1, 0) := by
  have hs : scaleIdx M M (1, 0) = (M, 0) := by simp [scaleIdx]
  have hmem' : sh (scaleIdx M M (1, 0)) ∈ Gsub a b M M := by rw [hs]; exact hmem
  have h := quadEquivLeft_coe_sh a b c M hM (1, 0) hmem'
  have heq : (⟨sh (scaleIdx M M (1, 0)), hmem'⟩ : Gsub a b M M) = ⟨sh (M, 0), hmem⟩ :=
    Subtype.ext (show sh (scaleIdx M M (1, 0)) = sh (M, 0) by rw [hs])
  rw [heq] at h
  rw [h]
  congr 1
  simp [scaleIdx]

theorem quadEquivLeft_gen_two (a b c M : ℤ) (hM : M ≠ 0)
    (hmem : sh (0, M) ∈ Gsub a b M M) :
    ((quadEquivLeft a b c M hM ⟨sh (0, M), hmem⟩ : Gsub 0 c 1 (M ^ 2)) : BaseGroup)
      = sh (0, M ^ 2) := by
  have hs : scaleIdx M M (0, 1) = (0, M) := by simp [scaleIdx]
  have hmem' : sh (scaleIdx M M (0, 1)) ∈ Gsub a b M M := by rw [hs]; exact hmem
  have h := quadEquivLeft_coe_sh a b c M hM (0, 1) hmem'
  have heq : (⟨sh (scaleIdx M M (0, 1)), hmem'⟩ : Gsub a b M M) = ⟨sh (0, M), hmem⟩ :=
    Subtype.ext (show sh (scaleIdx M M (0, 1)) = sh (0, M) by rw [hs])
  rw [heq] at h
  rw [h]
  congr 1
  simp [scaleIdx]

theorem quadLeft_hphi (a b c M : ℤ) (hM : M ≠ 0) (i : Fin 3) :
    ((stepPhi P (quadEquivLeft a b c M hM) (gsubWords P a b M M) (gsubWords P 0 c 1 (M ^ 2))
        (map_Gsub P a b M M) (map_Gsub P 0 c 1 (M ^ 2))
        ⟨HNNPresentation.srcGen P.rels (gsubWords P a b M M) i,
          HNNPresentation.srcGen_mem P.rels (gsubWords P a b M M) i⟩ :
          HNNPresentation.tgtSub P.rels (gsubWords P 0 c 1 (M ^ 2)))
        : PresentedGroup P.rels)
      = HNNPresentation.tgtGen P.rels (gsubWords P 0 c 1 (M ^ 2)) i := by
  fin_cases i
  · exact stepPhi_gen P _ _ _ _ _ (tw (a, b)) (tw_mem_Gsub a b M M) 0
      (mk_word_tw P (a, b)).symm
      (by rw [quadEquivLeft_gen_zero]; exact (mk_word_tw P (0, c)).symm)
  · exact stepPhi_gen P _ _ _ _ _ (sh (M, 0)) (sh_fst_mem_Gsub a b M M) 1
      (mk_word_sh P (M, 0)).symm
      (by rw [quadEquivLeft_gen_one]; exact (mk_word_sh P (1, 0)).symm)
  · exact stepPhi_gen P _ _ _ _ _ (sh (0, M)) (sh_snd_mem_Gsub a b M M) 2
      (mk_word_sh P (0, M)).symm
      (by rw [quadEquivLeft_gen_two]; exact (mk_word_sh P (0, M ^ 2)).symm)

/-- **The presentation of the next stage, for a left-moving quadruple.** -/
noncomputable def quadLeftStepPres (a b c M : ℤ) (hM : M ≠ 0) :
    StagePres (S.step (quadEquivLeft a b c M hM)) :=
  stepPres P (quadEquivLeft a b c M hM) (gsubWords P a b M M) (gsubWords P 0 c 1 (M ^ 2))
    (map_Gsub P a b M M) (map_Gsub P 0 c 1 (M ^ 2)) (quadLeft_hphi P a b c M hM)

/-! ## The whole tower

Recursion over `List Identification` cannot see that each entry is a quadruple's
identification, and destructuring an equality of sigma types to recover that is
worse than not needing it.  So the recursion runs over the quadruple *data*
instead, and `tower` is applied to its image --- at which point each step is
definitionally the right one and `quadStepPres` applies without any unpacking. -/

/-- A quadruple's contribution, as data: which residue pair, which new state,
and which direction. -/
inductive QuadData where
  | right (a b c : ℤ)
  | left (a b c : ℤ)

/-- The identification a quadruple contributes. -/
noncomputable def QuadData.toIdent (M : ℤ) (hM : M ≠ 0) : QuadData → Identification
  | .right a b c => quadIdentification a b c M hM
  | .left a b c => quadIdentificationLeft a b c M hM

/-- **The tower's presentation.**  One letter and three relators per quadruple,
carried up by `stepPres`. -/
noncomputable def towerPres (M : ℤ) (hM : M ≠ 0) :
    (qs : List QuadData) → StagePres (tower (qs.map (QuadData.toIdent M hM)))
  | [] => basePres
  | .right a b c :: qs => quadStepPres (towerPres M hM qs) a b c M hM
  | .left a b c :: qs => quadLeftStepPres (towerPres M hM qs) a b c M hM

/-- The quadruple data a machine contributes, in the same order as
`machineIdentifications`. -/
def machineQuads (mm : ModularMachine) : List QuadData :=
  (residuePairs mm).filterMap fun p =>
    (mm.quad p.1 p.2).map fun q =>
      cond q.2 (QuadData.right (p.1 : ℤ) (p.2 : ℤ) (q.1 : ℤ))
        (QuadData.left (p.1 : ℤ) (p.2 : ℤ) (q.1 : ℤ))

/-- The data reproduces the machine's identifications. -/
theorem map_machineQuads (mm : ModularMachine) (hM : (mm.size : ℤ) ≠ 0) :
    (machineQuads mm).map (QuadData.toIdent (mm.size : ℤ) hM)
      = machineIdentifications mm hM := by
  rw [machineQuads, machineIdentifications, List.map_filterMap]
  congr 1
  funext p
  rcases h : mm.quad p.1 p.2 with _ | q
  · rfl
  · rcases q with ⟨c, dir⟩
    cases dir <;> rfl

/-- Transport a stage presentation along an equality of identification lists.
Stated with both lists variable so `subst` reaches it --- a `cast` on the
structure type cannot be reasoned about afterwards, and the tower's `⟨t⟩'` has
to be recoverable from the transported presentation. -/
noncomputable def ofListEq {l l' : List Identification} (h : l = l')
    (P : StagePres (tower l)) : StagePres (tower l') := h ▸ P

theorem ofListEq_tsub {l l' : List Identification} (h : l = l')
    (P : StagePres (tower l)) : (ofListEq h P).tsub = h ▸ P.tsub := by
  subst h
  rfl

theorem towerTSub_congr {l l' : List Identification} (h : l = l') :
    h ▸ towerTSub l = towerTSub l' := by
  subst h
  rfl

/-- **The machine tower is presented.** -/
noncomputable def machineTowerPres (mm : ModularMachine) (hM : (mm.size : ℤ) ≠ 0) :
    StagePres (machineTower mm hM) :=
  ofListEq (map_machineQuads mm hM) (towerPres (mm.size : ℤ) hM (machineQuads mm))


/-! ## The tower's `⟨t⟩'`, identified

The recursion sets `tsub` to exactly the tower's `towerTSub`, definitionally at
each step; this records it. -/

theorem towerPres_tsub (M : ℤ) (hM : M ≠ 0) :
    ∀ qs : List QuadData,
      (towerPres M hM qs).tsub = towerTSub (qs.map (QuadData.toIdent M hM))
  | [] => rfl
  | .right a b c :: qs =>
      congrArg (liftedSubgroup ((tower (qs.map (QuadData.toIdent M hM))).stepEquiv
        (quadEquiv a b c M hM))) (towerPres_tsub M hM qs)
  | .left a b c :: qs =>
      congrArg (liftedSubgroup ((tower (qs.map (QuadData.toIdent M hM))).stepEquiv
        (quadEquivLeft a b c M hM))) (towerPres_tsub M hM qs)

/-- **The presented tower's `⟨t⟩'` is the tower's.** -/
theorem machineTowerPres_tsub (mm : ModularMachine) (hM : (mm.size : ℤ) ≠ 0) :
    (machineTowerPres mm hM).tsub = towerTSub (machineIdentifications mm hM) := by
  rw [machineTowerPres, ofListEq_tsub,
    show (towerPres (mm.size : ℤ) hM (machineQuads mm)).tsub
      = towerTSub ((machineQuads mm).map (QuadData.toIdent (mm.size : ℤ) hM)) from
      towerPres_tsub _ hM _]
  exact towerTSub_congr _

/-! ## The last layer

`FinalGroup` adjoins `k` along `⟨t⟩'` with the *identity* identification, so it
is not an instance of `stepPres` --- the associated subgroup is not the image of
a subgroup of the base.  It is the same construction with `A = B` and `φ = id`,
and the new relators are the commutators of `k` with each generator. -/

section Final

/-- The generators of `⟨t⟩'`, as a family. -/
def finalWords : Fin P.tsubWords.length → FreeGroup P.Letters :=
  fun i => P.tsubWords.get i

theorem srcSub_finalWords :
    HNNPresentation.srcSub P.rels (finalWords P) = wordsSub P.rels P.tsubWords := by
  rw [HNNPresentation.srcSub, wordsSub]
  congr 1
  ext x
  simp only [Set.mem_range, Set.mem_image, Set.mem_setOf_eq, HNNPresentation.srcGen,
    finalWords]
  constructor
  · rintro ⟨i, rfl⟩
    exact ⟨P.tsubWords.get i, List.get_mem _ _, rfl⟩
  · rintro ⟨u, hu, rfl⟩
    obtain ⟨i, rfl⟩ := List.mem_iff_get.1 hu
    exact ⟨i, rfl⟩

theorem final_mem_iff (g : S.Carrier) :
    g ∈ P.tsub ↔ P.equiv g ∈ HNNPresentation.srcSub P.rels (finalWords P) := by
  rw [srcSub_finalWords, ← P.tsub_spec, Subgroup.mem_map_equiv, MulEquiv.symm_apply_apply]

@[simp] theorem final_intertwines :
    HNNCongr.Intertwines (MulEquiv.refl P.tsub)
      (MulEquiv.refl (HNNPresentation.srcSub P.rels (finalWords P))) P.equiv
      (final_mem_iff P) := by
  intro a ha
  rfl

@[simp] theorem final_hphi (i : Fin P.tsubWords.length) :
    ((MulEquiv.refl (HNNPresentation.srcSub P.rels (finalWords P))
        ⟨HNNPresentation.srcGen P.rels (finalWords P) i,
          HNNPresentation.srcGen_mem P.rels (finalWords P) i⟩ :
          HNNPresentation.tgtSub P.rels (finalWords P)) : PresentedGroup P.rels)
      = HNNPresentation.tgtGen P.rels (finalWords P) i := rfl

/-- **The last layer, presented.** -/
noncomputable def finalEquivPres :
    HNNExtension S.Carrier P.tsub P.tsub (MulEquiv.refl _)
      ≃* PresentedGroup (HNNPresentation.hnnRels P.rels (finalWords P) (finalWords P)) :=
  (HNNCongr.congrEquiv (MulEquiv.refl P.tsub)
      (MulEquiv.refl (HNNPresentation.srcSub P.rels (finalWords P))) P.equiv
      (final_mem_iff P) (final_intertwines P)).trans
    (HNNPresentation.equivPres P.rels (finalWords P) (finalWords P)
      (MulEquiv.refl _) (final_hphi P)).symm

/-- The relators of the last layer, as a list: the old ones, then one
commutator `k g k⁻¹ g⁻¹` per generator of `⟨t⟩'`. -/
def finalRelList : List (FreeGroup (Option P.Letters)) :=
  P.relList.map (fun r => HNNPresentation.emb r) ++
    P.tsubWords.map (fun u =>
      HNNPresentation.stableWord * HNNPresentation.emb u *
        (HNNPresentation.stableWord)⁻¹ * (HNNPresentation.emb u)⁻¹)

theorem finalRelList_spec :
    {x | x ∈ finalRelList P} = HNNPresentation.hnnRels P.rels (finalWords P) (finalWords P) := by
  rw [HNNPresentation.hnnRels, finalRelList, ← P.relList_spec]
  ext x
  simp only [Set.mem_setOf_eq, List.mem_append, List.mem_map, Set.mem_union, Set.mem_image,
    Set.mem_range, finalWords]
  constructor
  · rintro (⟨r, hr, rfl⟩ | ⟨u, hu, rfl⟩)
    · exact Or.inl ⟨r, hr, rfl⟩
    · obtain ⟨i, rfl⟩ := List.mem_iff_get.1 hu
      exact Or.inr ⟨i, rfl⟩
  · rintro (⟨r, hr, rfl⟩ | ⟨i, rfl⟩)
    · exact Or.inl ⟨r, hr, rfl⟩
    · exact Or.inr ⟨P.tsubWords.get i, List.get_mem _ _, rfl⟩

/-- The last layer, as a stage: adjoin `k` along `⟨t⟩'`.  The base still
embeds, so this is a `Stage` and the presentation machinery applies unchanged. -/
noncomputable def finalStage (S : Stage) (T : Subgroup S.Carrier) : Stage where
  Carrier := HNNExtension S.Carrier T T (MulEquiv.refl _)
  group := inferInstance
  ι := (HNNExtension.of).comp S.ι
  ι_injective := by
    intro x y h
    apply S.ι_injective
    apply HNNExtension.of_injective
    exact h

theorem finalEquivPres_of (a : S.Carrier) :
    finalEquivPres P (HNNExtension.of a)
      = HNNPresentation.bwdBase P.rels (finalWords P) (finalWords P) (P.equiv a) := by
  show (HNNPresentation.equivPres P.rels (finalWords P) (finalWords P)
      (MulEquiv.refl _) (final_hphi P)).symm
      (HNNCongr.congrEquiv (MulEquiv.refl P.tsub)
        (MulEquiv.refl (HNNPresentation.srcSub P.rels (finalWords P))) P.equiv
        (final_mem_iff P) (final_intertwines P) (HNNExtension.of a)) = _
  rw [show (HNNCongr.congrEquiv (MulEquiv.refl P.tsub)
        (MulEquiv.refl (HNNPresentation.srcSub P.rels (finalWords P))) P.equiv
        (final_mem_iff P) (final_intertwines P) (HNNExtension.of a))
      = HNNExtension.of (P.equiv a) from
    HNNCongr.congrHom_of (MulEquiv.refl P.tsub)
      (MulEquiv.refl (HNNPresentation.srcSub P.rels (finalWords P))) P.equiv
      (final_mem_iff P) (final_intertwines P) a]
  show HNNPresentation.bwd P.rels (finalWords P) (finalWords P) (MulEquiv.refl _)
      (final_hphi P) (HNNExtension.of (P.equiv a)) = _
  rw [HNNPresentation.bwd, HNNExtension.lift_of]

theorem finalEquivPres_t :
    finalEquivPres P
        (HNNExtension.t : HNNExtension S.Carrier P.tsub P.tsub (MulEquiv.refl _))
      = PresentedGroup.of none := by
  show (HNNPresentation.equivPres P.rels (finalWords P) (finalWords P)
      (MulEquiv.refl _) (final_hphi P)).symm
      (HNNCongr.congrEquiv (MulEquiv.refl P.tsub)
        (MulEquiv.refl (HNNPresentation.srcSub P.rels (finalWords P))) P.equiv
        (final_mem_iff P) (final_intertwines P) HNNExtension.t) = _
  rw [show (HNNCongr.congrEquiv (MulEquiv.refl P.tsub)
        (MulEquiv.refl (HNNPresentation.srcSub P.rels (finalWords P))) P.equiv
        (final_mem_iff P) (final_intertwines P)
        (HNNExtension.t : HNNExtension S.Carrier P.tsub P.tsub (MulEquiv.refl _)))
      = HNNExtension.t from
    HNNCongr.congrHom_t (MulEquiv.refl P.tsub)
      (MulEquiv.refl (HNNPresentation.srcSub P.rels (finalWords P))) P.equiv
      (final_mem_iff P) (final_intertwines P)]
  show HNNPresentation.bwd P.rels (finalWords P) (finalWords P) (MulEquiv.refl _)
      (final_hphi P) HNNExtension.t = _
  rw [HNNPresentation.bwd, HNNExtension.lift_t]

/-- **The whole group, presented.**  The tower's presentation with `k` and its
commutators adjoined. -/
noncomputable def finalPres : StagePres (finalStage S P.tsub) where
  Letters := Option P.Letters
  relList := finalRelList P
  rels := HNNPresentation.hnnRels P.rels (finalWords P) (finalWords P)
  relList_spec := finalRelList_spec P
  equiv := finalEquivPres P
  word := HNNPresentation.emb.comp P.word
  compat := by
    intro u
    show finalEquivPres P
      (HNNExtension.of (S.ι (presentedEquiv (PresentedGroup.mk BooneGroup.rels u)))) = _
    rw [finalEquivPres_of, P.compat u, HNNPresentation.bwdBase_mk]
    rfl
  tsub := ⊥
  tsubWords := []
  tsub_spec := by
    have hempty : (PresentedGroup.mk
        (HNNPresentation.hnnRels P.rels (finalWords P) (finalWords P)) ''
        {x | x ∈ ([] : List (FreeGroup (Option P.Letters)))}) = ∅ := by
      ext x
      simp
    rw [Subgroup.map_bot, wordsSub, hempty, Subgroup.closure_empty]
  gpred := P.gpred + 1
  enum := (Equiv.optionCongr P.enum).trans
    (PresentedGroupRelabel.optionFinEquiv (P.gpred + 1))
  letterOfGen := fun i => some (P.letterOfGen i)
  word_of := by
    intro i
    show HNNPresentation.emb (P.word (FreeGroup.of i)) = _
    rw [P.word_of, HNNPresentation.emb, FreeGroup.map.of]

end Final

/-! ## The code

With the numbering carried in the structure, the code is the relator list read
through it, and the group it presents is the stage itself. -/

/-- **The code of a stage's presentation.** -/
noncomputable def stageCode (P : StagePres S) : PresentationCodes.PresentationCode :=
  PresentationCodeList.codeOfList
    (P.relList.map (PresentedGroupRelabel.relabel (P.enum : P.Letters → Fin (P.gpred + 1))))

theorem stageCode_relSet (P : StagePres S) :
    {x | x ∈ P.relList.map
        (PresentedGroupRelabel.relabel (P.enum : P.Letters → Fin (P.gpred + 1)))}
      = PresentedGroupRelabel.relabelRels (P.enum : P.Letters → Fin (P.gpred + 1)) P.rels := by
  rw [setOf_mem_map, P.relList_spec]
  rfl

/-- **The code presents the stage.** -/
noncomputable def stageCodeEquiv (P : StagePres S) :
    PresentationCodes.Carrier (stageCode P) ≃* S.Carrier :=
  (((PresentationCodeList.carrierOfList _).trans
      (PresentationCodeList.presCongrSet (stageCode_relSet P))).trans
    (PresentedGroupRelabel.congrEquiv P.enum P.rels).symm).trans P.equiv.symm

@[simp] theorem genCount_stageCode (P : StagePres S) :
    PresentationCodes.genCount (stageCode P) = P.gpred + 1 := rfl

end BooneTowerPresentation
end GroupApproximation
