import GroupApproximation.Computability.RawWord
import GroupApproximation.Computability.AdianRabinWordProblem
import GroupApproximation.Sofic.WeakMFUltraproduct

/-!
# Microstates of a presentation code

A **microstate** for a presentation code is finite data: a nonempty finite
model together with one unitary matrix per generator.  It induces a genuine
homomorphism on the free group --- no approximation is involved in the
induction, only in what the homomorphism does to the relators --- and that is
what makes the microstate the right carrier for an arithmetical statement about
MF-ness.  A `NormModel` is a map out of the *group*, so its very statement
mentions equality in the group; a microstate mentions only the alphabet.

The file supplies three things.

* `ev`, the group element a raw word names, as the composite of `wordOf` with
  the presentation quotient, together with the two facts that make raw words a
  usable calculus for it: `ev` turns concatenation into multiplication and
  `RawWord.invWord` into inversion.
* `Microstate`, its induced homomorphism `Microstate.hom`, and the
  displacement `Microstate.flen` of a free-group element.  Displacement is
  `opLength` of the image, so it inherits the four properties that matter:
  it vanishes at one, is subadditive, is inversion-invariant, and is
  conjugation-invariant.
* `exists_area_bound`: **approximate relators force approximate triviality**.
  If a free-group element lies in the normal closure of a set `S`, there is a
  natural number `N` --- an area count, depending on the element and not on
  the microstate --- with `flen x ≤ N * δ` in every microstate that displaces
  every member of `S` by at most `δ`.

The area bound is what replaces a van Kampen diagram here.  It is proved
without any diagram: the elements admitting such a bound form a subgroup, that
subgroup contains every conjugate of every member of `S` by conjugation
invariance, and the normal closure is by definition the subgroup generated by
those conjugates.

## Manuscript status

Machinery.  Certifies no manuscript step on its own.
-/

namespace GroupApproximation
namespace MFMicrostate

open PresentationCodes AdianRabinWordProblem RawWord

/-! ## The coded group, and raw words as a calculus for it -/

/-- Coded groups are countable: they are quotients of a free group on a
finite alphabet. -/
instance carrierCountable (c : PresentationCode) : Countable (Carrier c) := by
  unfold Carrier PresentedGroup
  exact Function.Surjective.countable (QuotientGroup.mk'_surjective _)

/-- The presentation quotient of a code, packaged as a homomorphism.  The two
`rfl`s are the quotient's own multiplication. -/
def evHom (c : PresentationCode) :
    FreeGroup (Fin (genCount c)) →* Carrier c where
  toFun := PresentedGroup.mk (relatorSet c)
  map_one' := rfl
  map_mul' _ _ := rfl

/-- The group element a raw word names. -/
def ev (c : PresentationCode) (w : List (ℕ × Bool)) : Carrier c :=
  evHom c (wordOf c w)

/-- Naming the identity is exactly the word problem. -/
theorem ev_eq_one_iff (c : PresentationCode) (w : List (ℕ × Bool)) :
    ev c w = 1 ↔ WordProblem c w := Iff.rfl

@[simp] theorem ev_nil (c : PresentationCode) : ev c [] = 1 := by
  rw [ev, wordOf_nil, map_one]

theorem ev_append (c : PresentationCode) (u v : List (ℕ × Bool)) :
    ev c (u ++ v) = ev c u * ev c v := by
  rw [ev, ev, ev, wordOf_append, map_mul]

theorem ev_invWord (c : PresentationCode) (u : List (ℕ × Bool)) :
    ev c (invWord u) = (ev c u)⁻¹ := by
  rw [ev, ev, wordOf_invWord, map_inv]

/-- Every element of a coded group is named by a raw word. -/
theorem ev_surjective (c : PresentationCode) : Function.Surjective (ev c) := by
  intro g
  obtain ⟨x, hx⟩ :=
    QuotientGroup.mk'_surjective (Subgroup.normalClosure (relatorSet c))
      (show FreeGroup (Fin (genCount c)) ⧸
        Subgroup.normalClosure (relatorSet c) from g)
  obtain ⟨u, hu⟩ := wordOf_surjective c x
  exact ⟨u, by rw [ev, hu]; exact hx⟩

/-- A trivial word lands in the normal closure of the relator set.  This is
the form the area bound consumes. -/
theorem wordOf_mem_normalClosure {c : PresentationCode} {w : List (ℕ × Bool)}
    (hw : WordProblem c w) :
    wordOf c w ∈ Subgroup.normalClosure (relatorSet c) :=
  (QuotientGroup.eq_one_iff (N := Subgroup.normalClosure (relatorSet c))
    (wordOf c w)).1 hw

/-- Reducing a letter twice is reducing it once. -/
theorem letterOf_val_letterOf (c : PresentationCode) (i : ℕ) :
    letterOf c ((letterOf c i : Fin (genCount c)) : ℕ) = letterOf c i := by
  apply Fin.ext
  simp [letterOf]

/-! ## Microstates -/

/-- **A microstate for a presentation code.**  A nonempty finite model
together with one unitary per generator: finite data, and no reference to the
coded group. -/
structure Microstate (c : PresentationCode) where
  /-- The finite model the unitaries act on. -/
  model : FiniteModel
  /-- The model is nonempty; a microstate on no coordinates separates nothing. -/
  card_pos : 0 < Fintype.card model
  /-- One unitary per generator. -/
  gen : Fin (genCount c) → Matrix.unitaryGroup model ℂ

namespace Microstate

variable {c : PresentationCode}

/-- The homomorphism a microstate induces on the free group.  This is exact:
a microstate is a genuine representation of the *free* group, and only its
behaviour on the relators is approximate. -/
noncomputable def hom (M : Microstate c) :
    FreeGroup (Fin (genCount c)) →* Matrix.unitaryGroup M.model ℂ :=
  FreeGroup.lift M.gen

/-- Operator-norm displacement of a free-group element in a microstate. -/
noncomputable def flen (M : Microstate c)
    (x : FreeGroup (Fin (genCount c))) : ℝ :=
  opLength M.model (M.hom x)

/-- Operator-norm displacement of a raw word in a microstate. -/
noncomputable def len (M : Microstate c) (w : List (ℕ × Bool)) : ℝ :=
  M.flen (wordOf c w)

theorem flen_def (M : Microstate c) (x : FreeGroup (Fin (genCount c))) :
    M.flen x = opLength M.model (M.hom x) := rfl

theorem len_def (M : Microstate c) (w : List (ℕ × Bool)) :
    M.len w = opLength M.model (M.hom (wordOf c w)) := rfl

/-- Reverse triangle inequality for displacement: an element is displaced no
more than any comparison element plus the gap between them. -/
theorem opLength_le_gap {Y : FiniteModel} (X Z : Matrix.unitaryGroup Y ℂ) :
    opLength Y X ≤ opLength Y Z + opLength Y (X⁻¹ * Z) := by
  have hsplit : X = Z * (X⁻¹ * Z)⁻¹ := by group
  calc opLength Y X = opLength Y (Z * (X⁻¹ * Z)⁻¹) := by rw [← hsplit]
    _ ≤ opLength Y Z + opLength Y (X⁻¹ * Z)⁻¹ := opLength_mul_le _ _ _
    _ = opLength Y Z + opLength Y (X⁻¹ * Z) := by rw [opLength_inv]

/-- The gap is symmetric in its two arguments. -/
theorem opLength_gap_symm {Y : FiniteModel} (X Z : Matrix.unitaryGroup Y ℂ) :
    opLength Y (X⁻¹ * Z) = opLength Y (Z⁻¹ * X) := by
  rw [← opLength_inv]
  congr 1
  group

@[simp] theorem flen_one (M : Microstate c) : M.flen 1 = 0 := by
  rw [flen, map_one, opLength_one]

theorem flen_nonneg (M : Microstate c) (x : FreeGroup (Fin (genCount c))) :
    0 ≤ M.flen x := opLength_nonneg _ _

theorem flen_mul_le (M : Microstate c) (x y : FreeGroup (Fin (genCount c))) :
    M.flen (x * y) ≤ M.flen x + M.flen y := by
  rw [flen, flen, flen, map_mul]
  exact opLength_mul_le _ _ _

theorem flen_inv (M : Microstate c) (x : FreeGroup (Fin (genCount c))) :
    M.flen x⁻¹ = M.flen x := by
  rw [flen, flen, map_inv]
  exact opLength_inv _ _

theorem flen_conj (M : Microstate c) (t x : FreeGroup (Fin (genCount c))) :
    M.flen (t * x * t⁻¹) = M.flen x := by
  rw [flen, flen, map_mul, map_mul, map_inv]
  exact opLength_conj _ _ _

@[simp] theorem len_nil (M : Microstate c) : M.len [] = 0 := by
  rw [len, wordOf_nil, flen_one]

theorem len_nonneg (M : Microstate c) (w : List (ℕ × Bool)) :
    0 ≤ M.len w := flen_nonneg _ _

theorem len_append (M : Microstate c) (u v : List (ℕ × Bool)) :
    M.len (u ++ v) ≤ M.len u + M.len v := by
  rw [len, len, len, wordOf_append]
  exact flen_mul_le _ _ _

end Microstate

/-! ## The area bound -/

/-- The free-group elements whose displacement is bounded by a fixed multiple
of the relator displacement, uniformly over microstates.

The multiple is the subgroup's witness, so the carrier is stated with the
natural number existentially quantified; the three closure proofs are the
three properties of `Microstate.flen`. -/
def areaSubgroup (c : PresentationCode)
    (S : Set (FreeGroup (Fin (genCount c)))) :
    Subgroup (FreeGroup (Fin (genCount c))) where
  carrier := {x | ∃ N : ℕ, ∀ (M : Microstate c) (δ : ℝ), 0 ≤ δ →
    (∀ r ∈ S, M.flen r ≤ δ) → M.flen x ≤ (N : ℝ) * δ}
  one_mem' := by
    refine ⟨0, fun M δ hδ _ => ?_⟩
    rw [M.flen_one, Nat.cast_zero, zero_mul]
  mul_mem' := by
    rintro x y ⟨Nx, hx⟩ ⟨Ny, hy⟩
    refine ⟨Nx + Ny, fun M δ hδ hrel => ?_⟩
    refine (M.flen_mul_le x y).trans ?_
    have := add_le_add (hx M δ hδ hrel) (hy M δ hδ hrel)
    rwa [← add_mul, ← Nat.cast_add] at this
  inv_mem' := by
    rintro x ⟨N, hx⟩
    refine ⟨N, fun M δ hδ hrel => ?_⟩
    rw [M.flen_inv]
    exact hx M δ hδ hrel

/-- Displacement is conjugation-invariant, so the area subgroup is normal.
This is what lets the normal closure be compared with it directly, without
touching the generating set of conjugates. -/
instance areaSubgroup_normal (c : PresentationCode)
    (S : Set (FreeGroup (Fin (genCount c)))) : (areaSubgroup c S).Normal where
  conj_mem := by
    rintro x ⟨N, hx⟩ g
    refine ⟨N, fun M δ hδ hrel => ?_⟩
    rw [M.flen_conj]
    exact hx M δ hδ hrel

theorem mem_areaSubgroup_iff {c : PresentationCode}
    {S : Set (FreeGroup (Fin (genCount c)))}
    {x : FreeGroup (Fin (genCount c))} :
    x ∈ areaSubgroup c S ↔ ∃ N : ℕ, ∀ (M : Microstate c) (δ : ℝ), 0 ≤ δ →
      (∀ r ∈ S, M.flen r ≤ δ) → M.flen x ≤ (N : ℝ) * δ := Iff.rfl

/-- A member of `S` has area one. -/
theorem subset_areaSubgroup (c : PresentationCode)
    (S : Set (FreeGroup (Fin (genCount c)))) :
    S ⊆ (areaSubgroup c S : Set (FreeGroup (Fin (genCount c)))) := by
  intro r hr
  refine mem_areaSubgroup_iff.2 ⟨1, fun M δ hδ hrel => ?_⟩
  rw [Nat.cast_one, one_mul]
  exact hrel r hr

/-- **Approximate relators force approximate triviality.**  An element of the
normal closure of `S` carries an area count that bounds its displacement in
every microstate, in terms of the displacement of `S`. -/
theorem exists_area_bound (c : PresentationCode)
    {S : Set (FreeGroup (Fin (genCount c)))}
    {x : FreeGroup (Fin (genCount c))}
    (hx : x ∈ Subgroup.normalClosure S) :
    ∃ N : ℕ, ∀ (M : Microstate c) (δ : ℝ), 0 ≤ δ →
      (∀ r ∈ S, M.flen r ≤ δ) → M.flen x ≤ (N : ℝ) * δ :=
  mem_areaSubgroup_iff.1
    (Subgroup.normalClosure_le_normal (N := areaSubgroup c S)
      (subset_areaSubgroup c S) hx)

/-- Relator displacement measured on the listed relator words bounds it on the
whole relator set. -/
theorem flen_relatorSet_le {c : PresentationCode} {M : Microstate c} {δ : ℝ}
    (h : ∀ u ∈ c.2, M.len u ≤ δ) :
    ∀ r ∈ relatorSet c, M.flen r ≤ δ := by
  intro r hr
  obtain ⟨u, hu, rfl⟩ := mem_relatorSet_iff.1 hr
  exact h u hu

/-- **The area bound, for a finite list of trivial words at once.**  One area
count works for the whole list, which is what a finite multiplicativity check
needs. -/
theorem exists_area_bound_list (c : PresentationCode)
    (L : List (List (ℕ × Bool))) (hL : ∀ u ∈ L, WordProblem c u) :
    ∃ N : ℕ, ∀ (M : Microstate c) (δ : ℝ), 0 ≤ δ →
      (∀ r ∈ c.2, M.len r ≤ δ) → ∀ u ∈ L, M.len u ≤ (N : ℝ) * δ := by
  induction L with
  | nil => exact ⟨0, by simp⟩
  | cons a t ih =>
      obtain ⟨Nt, hNt⟩ := ih fun u hu => hL u (List.mem_cons_of_mem _ hu)
      obtain ⟨Na, hNa⟩ :=
        exists_area_bound c (wordOf_mem_normalClosure (hL a List.mem_cons_self))
      refine ⟨max Na Nt, fun M δ hδ hrel u hu => ?_⟩
      have hmono : ∀ N : ℕ, N ≤ max Na Nt →
          ∀ y : ℝ, y ≤ (N : ℝ) * δ → y ≤ ((max Na Nt : ℕ) : ℝ) * δ := by
        intro N hN y hy
        refine hy.trans (mul_le_mul_of_nonneg_right ?_ hδ)
        exact_mod_cast hN
      rcases List.mem_cons.1 hu with rfl | hu'
      · exact hmono Na (le_max_left _ _) _
          (hNa M δ hδ (flen_relatorSet_le hrel))
      · exact hmono Nt (le_max_right _ _) _ (hNt M δ hδ hrel u hu')

end MFMicrostate
end GroupApproximation
