import GroupApproximation.Computability.FreeEdgeTowerCode
import GroupApproximation.Algebra.HNNCongr
import GroupApproximation.Algebra.HNNPresentation
import GroupApproximation.Algebra.PresentedGroupRelabel
import GroupApproximation.Higman.ExplicitFreeEdge

/-!
# One-edge semantics for the raw free-edge compiler

This file connects one `FreeEdgeTowerCode.edgeCode` layer to the honest HNN
extension built by `Higman.ExplicitFreeEdge`.  The only algebraic hypotheses
are injectivity of the two displayed evaluations from the free group on the
finite edge list.  No MF permanence claim is made here.
-/

namespace GroupApproximation
namespace FreeEdgeTowerSemantics

open PresentationCodes FreeEdgeTowerCode
open Higman ExplicitFreeEdge

/-- The relator set presented by a code, named for use with
`HNNPresentation`. -/
abbrev codeRels (c : PresentationCode) :
    Set (FreeGroup (Fin (genCount c))) :=
  ((relatorFinset c : Finset (FreeGroup (Fin (genCount c)))) :
    Set (FreeGroup (Fin (genCount c))))

/-- The source word of the `i`-th raw edge. -/
def sourceWord (c : PresentationCode) (edges : List (Raw × Raw))
    (i : Fin edges.length) : FreeGroup (Fin (genCount c)) :=
  wordOf c (edges.get i).1

/-- The target word of the `i`-th raw edge. -/
def targetWord (c : PresentationCode) (edges : List (Raw × Raw))
    (i : Fin edges.length) : FreeGroup (Fin (genCount c)) :=
  wordOf c (edges.get i).2

/-- Evaluate the free source tuple in the group presented by `c`. -/
def sourceEval (c : PresentationCode) (edges : List (Raw × Raw)) :
    FreeGroup (Fin edges.length) →* Carrier c :=
  FreeGroup.lift fun i => PresentedGroup.mk (codeRels c) (sourceWord c edges i)

/-- Evaluate the free target tuple in the group presented by `c`. -/
def targetEval (c : PresentationCode) (edges : List (Raw × Raw)) :
    FreeGroup (Fin edges.length) →* Carrier c :=
  FreeGroup.lift fun i => PresentedGroup.mk (codeRels c) (targetWord c edges i)

@[simp] theorem sourceEval_of (c : PresentationCode)
    (edges : List (Raw × Raw)) (i : Fin edges.length) :
    sourceEval c edges (FreeGroup.of i) =
      PresentedGroup.mk (codeRels c) (sourceWord c edges i) := by
  simp [sourceEval]

@[simp] theorem targetEval_of (c : PresentationCode)
    (edges : List (Raw × Raw)) (i : Fin edges.length) :
    targetEval c edges (FreeGroup.of i) =
      PresentedGroup.mk (codeRels c) (targetWord c edges i) := by
  simp [targetEval]

/-- The honest free-edge data.  These two injectivity arguments are precisely
the semantic freeness obligations left by the raw compiler. -/
def edgeData (c : PresentationCode) (edges : List (Raw × Raw))
    (hsource : Function.Injective (sourceEval c edges))
    (htarget : Function.Injective (targetEval c edges)) :
    Data (Fin edges.length) (Carrier c) where
  source := sourceEval c edges
  target := targetEval c edges
  source_injective := hsource
  target_injective := htarget

/-- The explicitly embedded source free group is exactly the subgroup used by
the word-level HNN presentation. -/
theorem sourceSubgroup_edgeData (c : PresentationCode)
    (edges : List (Raw × Raw))
    (hsource : Function.Injective (sourceEval c edges))
    (htarget : Function.Injective (targetEval c edges)) :
    sourceSubgroup (edgeData c edges hsource htarget) =
      HNNPresentation.srcSub (codeRels c) (sourceWord c edges) := by
  rw [sourceSubgroup, HNNPresentation.srcSub,
    ← FreeGroup.closure_range_of, MonoidHom.map_closure]
  congr 1
  ext x
  simp [edgeData, HNNPresentation.srcGen]

/-- The explicitly embedded target free group is exactly the subgroup used by
the word-level HNN presentation. -/
theorem targetSubgroup_edgeData (c : PresentationCode)
    (edges : List (Raw × Raw))
    (hsource : Function.Injective (sourceEval c edges))
    (htarget : Function.Injective (targetEval c edges)) :
    targetSubgroup (edgeData c edges hsource htarget) =
      HNNPresentation.tgtSub (codeRels c) (targetWord c edges) := by
  rw [targetSubgroup, HNNPresentation.tgtSub,
    ← FreeGroup.closure_range_of, MonoidHom.map_closure]
  congr 1
  ext x
  simp [edgeData, HNNPresentation.tgtGen]

/-- The edge equivalence, transported to the literal source and target
subgroups generated by the presentation words. -/
noncomputable def presentedEdgeEquiv (c : PresentationCode)
    (edges : List (Raw × Raw))
    (hsource : Function.Injective (sourceEval c edges))
    (htarget : Function.Injective (targetEval c edges)) :
    HNNPresentation.srcSub (codeRels c) (sourceWord c edges) ≃*
      HNNPresentation.tgtSub (codeRels c) (targetWord c edges) :=
  ((MulEquiv.subgroupCongr
      (sourceSubgroup_edgeData c edges hsource htarget).symm).trans
    (edgeEquiv (edgeData c edges hsource htarget))).trans
  (MulEquiv.subgroupCongr
    (targetSubgroup_edgeData c edges hsource htarget))

/-- On each displayed generator, the transported edge equivalence sends the
source word to the corresponding target word. -/
theorem presentedEdgeEquiv_gen (c : PresentationCode)
    (edges : List (Raw × Raw))
    (hsource : Function.Injective (sourceEval c edges))
    (htarget : Function.Injective (targetEval c edges))
    (i : Fin edges.length) :
    ((presentedEdgeEquiv c edges hsource htarget
        ⟨HNNPresentation.srcGen (codeRels c) (sourceWord c edges) i,
          HNNPresentation.srcGen_mem (codeRels c) (sourceWord c edges) i⟩ :
        HNNPresentation.tgtSub (codeRels c) (targetWord c edges)) : Carrier c) =
      HNNPresentation.tgtGen (codeRels c) (targetWord c edges) i := by
  let E := edgeData c edges hsource htarget
  have hsrc :
      (MulEquiv.subgroupCongr
          (sourceSubgroup_edgeData c edges hsource htarget).symm)
        ⟨HNNPresentation.srcGen (codeRels c) (sourceWord c edges) i,
          HNNPresentation.srcGen_mem (codeRels c) (sourceWord c edges) i⟩ =
        sourceElement E (FreeGroup.of i) := by
    apply Subtype.ext
    change HNNPresentation.srcGen (codeRels c) (sourceWord c edges) i =
      ((sourceEquiv E (FreeGroup.of i) : sourceSubgroup E) : Carrier c)
    rw [coe_sourceEquiv]
    change PresentedGroup.mk (codeRels c) (sourceWord c edges i) =
      sourceEval c edges (FreeGroup.of i)
    rw [sourceEval_of]
  change (((MulEquiv.subgroupCongr
      (targetSubgroup_edgeData c edges hsource htarget))
        (edgeEquiv E ((MulEquiv.subgroupCongr
          (sourceSubgroup_edgeData c edges hsource htarget).symm)
            ⟨HNNPresentation.srcGen (codeRels c) (sourceWord c edges) i,
              HNNPresentation.srcGen_mem (codeRels c) (sourceWord c edges) i⟩)) :
      HNNPresentation.tgtSub (codeRels c) (targetWord c edges)) : Carrier c) = _
  rw [hsrc]
  change ((edgeEquiv E (sourceElement E (FreeGroup.of i)) :
    targetSubgroup E) : Carrier c) = _
  simpa [E, edgeData, HNNPresentation.tgtGen] using
    coe_edgeEquiv_sourceElement E (FreeGroup.of i)

/-- Membership in the presentation source subgroup is membership in the
explicitly evaluated source subgroup. -/
theorem mem_sourceSubgroup_edgeData_iff (c : PresentationCode)
    (edges : List (Raw × Raw))
    (hsource : Function.Injective (sourceEval c edges))
    (htarget : Function.Injective (targetEval c edges)) (g : Carrier c) :
    g ∈ HNNPresentation.srcSub (codeRels c) (sourceWord c edges) ↔
      g ∈ sourceSubgroup (edgeData c edges hsource htarget) := by
  rw [sourceSubgroup_edgeData c edges hsource htarget]

/-- The transported presentation equivalence really is the explicit edge
equivalence after forgetting subgroup proof fields. -/
theorem presentedEdgeEquiv_intertwines (c : PresentationCode)
    (edges : List (Raw × Raw))
    (hsource : Function.Injective (sourceEval c edges))
    (htarget : Function.Injective (targetEval c edges)) :
    HNNCongr.Intertwines
      (presentedEdgeEquiv c edges hsource htarget)
      (edgeEquiv (edgeData c edges hsource htarget))
      (MulEquiv.refl (Carrier c))
      (fun g => by
        simpa using mem_sourceSubgroup_edgeData_iff
          c edges hsource htarget g) := by
  intro a ha
  change ((edgeEquiv (edgeData c edges hsource htarget)
      ⟨a, (mem_sourceSubgroup_edgeData_iff c edges hsource htarget a).1 ha⟩ :
        targetSubgroup (edgeData c edges hsource htarget)) : Carrier c) =
    ((presentedEdgeEquiv c edges hsource htarget ⟨a, ha⟩ :
        HNNPresentation.tgtSub (codeRels c) (targetWord c edges)) : Carrier c)
  rfl

/-- The HNN extension appearing in the word-level presentation is the honest
`ExplicitFreeEdge.Extension`. -/
noncomputable def presentedHNNEquiv (c : PresentationCode)
    (edges : List (Raw × Raw))
    (hsource : Function.Injective (sourceEval c edges))
    (htarget : Function.Injective (targetEval c edges)) :
    HNNPresentation.Ext (codeRels c) (sourceWord c edges) (targetWord c edges)
        (presentedEdgeEquiv c edges hsource htarget) ≃*
      Extension (edgeData c edges hsource htarget) :=
  HNNCongr.congrEquiv
    (presentedEdgeEquiv c edges hsource htarget)
    (edgeEquiv (edgeData c edges hsource htarget))
    (MulEquiv.refl (Carrier c))
    (fun g => by
      simpa using mem_sourceSubgroup_edgeData_iff c edges hsource htarget g)
    (presentedEdgeEquiv_intertwines c edges hsource htarget)

end FreeEdgeTowerSemantics
end GroupApproximation
