import GroupApproximation.GroupTheory.AlgebraicUltraproductLEF
import GroupApproximation.GroupTheory.LevelCommutatorWordsLevels
import GroupApproximation.Manuscript.SimpleKazhdanSofic.LEFCharacterization
import GroupApproximation.Meta.AxiomGuard
import Mathlib.Order.Filter.Ultrafilter.Basic
import Mathlib.Order.Filter.Cofinite
import Mathlib.GroupTheory.Finiteness
import Mathlib.Data.Countable.Defs

/-!
# A countable LEF group lies in the commutator subgroup of a finitely generated LEF group

`simple_kazhdan_sofic_group.tex` at origin/main 696c4b602 (md5 0648e5f8…), section "LEF groups", the proof of `cor:lef`
and `cor:host`, tex l.332–356:

> Conversely, let Γ = {γ_1, γ_2, …} be a countable LEF group, replaced by Γ × ℤ so that it is infinite. There are finite
> groups Q_k and maps μ_k : Γ → Q_k that are injective on {1, γ_1, …, γ_k} and preserve the products that stay in this
> set. […] In the algebraic ultraproduct over ω of the symmetric groups of these sets, sending γ to the class of the
> permutations multiplying the first coordinate on the level 0 by μ_k(γ) and acting trivially elsewhere is a
> homomorphism, injective as μ_k(γ) ≠ 1 for γ ≠ 1 and large k. It sends γ_j to w_j(a,b), where a = (a_k)_k and
> b = (b_k)_k, so Γ ≤ [Δ,Δ] for the group Δ generated by a and b. Finitely many products and inequalities in the
> ultraproduct hold in some coordinate, so Δ is infinite, finitely generated and LEF.

The permutations `t_k`, `f_jk`, `a_k`, `b_k` and the words `w_j` are `GroupTheory/LevelCommutatorWords` and
`LevelCommutatorWordsLevels`. The ultraproduct is `GroupTheory/AlgebraicUltraproductLEF`. This file assembles the
paragraph:

* `Models`: an enumeration `γ_1, γ_2, …` and the finite models `μ_k` on `{1, γ_1, …, γ_k}` (`models_nonempty`);
* `embedding`: the homomorphism into `∏_ω Sym(X_k)` for a nonprincipal `ω`, with `embedding_injective`;
* `embedding_γ`: `γ_j ↦ w_j(a,b)`;
* `Delta`, the subgroup generated by `a` and `b`, which is infinite, finitely generated and LEF, and contains the image in
  its commutator subgroup (`embeddingΔ_mem_commutator`);
* `exists_levelCommutatorEmbedding`: the whole paragraph, with the replacement of `Γ` by `Γ × ℤ`.

The closed endpoints are the named propositions at the end.
-/

namespace GroupApproximation
namespace SimpleKazhdanSofic

open scoped commutatorElement

namespace LEFLevelEmbedding

open Filter AlgebraicUltraproduct LevelCommutatorWords

variable {Γ : Type} [Group Γ]

/-- The test set `{1, γ_1, …, γ_k}` (tex l.335). -/
noncomputable def testSet (γ : ℕ → Γ) (k : ℕ) : Finset Γ := by
  classical exact insert 1 ((Finset.Icc 1 k).image γ)

theorem one_mem_testSet (γ : ℕ → Γ) (k : ℕ) : 1 ∈ testSet γ k := by
  classical
  unfold testSet
  exact Finset.mem_insert_self _ _

theorem mem_testSet (γ : ℕ → Γ) {j k : ℕ} (h1 : 1 ≤ j) (h2 : j ≤ k) : γ j ∈ testSet γ k := by
  classical
  unfold testSet
  exact Finset.mem_insert_of_mem (Finset.mem_image_of_mem γ (Finset.mem_Icc.2 ⟨h1, h2⟩))

/-- An enumeration `Γ = {γ_1, γ_2, …}` and finite models `μ_k : Γ → Q_k` that are injective on `{1, γ_1, …, γ_k}` and
preserve the products that stay in this set (tex l.332–336). -/
structure Models (Γ : Type) [Group Γ] where
  γ : ℕ → Γ
  surj : ∀ x : Γ, ∃ j, 1 ≤ j ∧ γ j = x
  Q : ℕ → FiniteGroupModel
  μ : ∀ k, Γ → Q k
  inj : ∀ k, Set.InjOn (μ k) (testSet γ k : Set Γ)
  mul : ∀ k, ∀ x ∈ testSet γ k, ∀ y ∈ testSet γ k, x * y ∈ testSet γ k →
    μ k (x * y) = μ k x * μ k y

/-- A countable LEF group has an enumeration and finite models on its test sets. -/
theorem models_nonempty (hc : Countable Γ) (hΓ : IsTextbookLEF Γ) : Nonempty (Models Γ) := by
  haveI : Countable Γ := hc
  obtain ⟨e, he⟩ := exists_surjective_nat Γ
  have surj : ∀ x : Γ, ∃ j, 1 ≤ j ∧ (fun j => e (j - 1)) j = x := by
    intro x
    obtain ⟨n, rfl⟩ := he x
    exact ⟨n + 1, by omega, by simp⟩
  choose Q μ inj mul using fun k => hΓ (testSet (fun j => e (j - 1)) k)
  exact ⟨⟨fun j => e (j - 1), surj, Q, μ, inj, mul⟩⟩

namespace Models

variable (M : Models Γ)

theorem μ_one (k : ℕ) : M.μ k 1 = 1 := by
  have h := M.mul k 1 (one_mem_testSet _ _) 1 (one_mem_testSet _ _)
    (by rw [one_mul]; exact one_mem_testSet _ _)
  rw [one_mul] at h
  exact mul_left_cancel (h.symm.trans (mul_one _).symm)

end Models

theorem eventually_ge {ω : Ultrafilter ℕ} (hω : (ω : Filter ℕ) ≤ cofinite) (K : ℕ) :
    ∀ᶠ k in (ω : Filter ℕ), K ≤ k :=
  hω (by rw [Nat.cofinite_eq_atTop]; exact eventually_ge_atTop K)

variable (M : Models Γ) (ω : Ultrafilter ℕ)

/-- The set `X_k = Q_k × ℤ/m_k × ℤ/4^{k+1}` (tex l.340). -/
abbrev LevelSet (k : ℕ) : Type :=
  (M.Q k × ZMod (Fintype.card (M.Q k))) × ZMod (4 ^ (k + 1))

/-- The symmetric group `Sym(X_k)` (tex l.349). -/
abbrev SymX (k : ℕ) : Type :=
  Equiv.Perm (LevelSet M k)

/-- `(a_k)_k` (tex l.353). -/
def aSeq : ∀ k, SymX M k :=
  fun k => aPerm (M.Q k) k fun j => M.μ k (M.γ j)

/-- `(b_k)_k` (tex l.353). -/
def bSeq : ∀ k, SymX M k :=
  fun k => bPerm (M.Q k) k

/-- The permutations multiplying the first coordinate on the level `0` by `μ_k(x)` (tex l.349–351). -/
def embedSeq (x : Γ) : ∀ k, SymX M k :=
  fun k => levelZeroMul (M.Q k) k (M.μ k x)

/-- **The homomorphism into the algebraic ultraproduct** (tex l.348–351). -/
noncomputable def embedding (hω : (ω : Filter ℕ) ≤ cofinite) : Γ →* Ultraproduct ω (SymX M) where
  toFun x := QuotientGroup.mk (embedSeq M x)
  map_one' := by
    refine ((mk_eq_mk_iff ω (SymX M)).2 (Filter.Eventually.of_forall fun k => ?_)).trans
      (QuotientGroup.mk_one (AlgebraicUltraproduct.nullSubgroup ω (SymX M)))
    show levelZeroMul (M.Q k) k (M.μ k 1) = 1
    rw [M.μ_one, levelZeroMul_one]
  map_mul' x y := by
    obtain ⟨j₁, hj₁, rfl⟩ := M.surj x
    obtain ⟨j₂, hj₂, rfl⟩ := M.surj y
    obtain ⟨j₃, hj₃, h₃⟩ := M.surj (M.γ j₁ * M.γ j₂)
    show (QuotientGroup.mk (embedSeq M (M.γ j₁ * M.γ j₂)) : Ultraproduct ω (SymX M)) =
      QuotientGroup.mk (embedSeq M (M.γ j₁) * embedSeq M (M.γ j₂))
    refine (mk_eq_mk_iff ω (SymX M)).2 ((eventually_ge hω (j₁ + j₂ + j₃)).mono fun k hk => ?_)
    show levelZeroMul (M.Q k) k (M.μ k (M.γ j₁ * M.γ j₂)) =
      levelZeroMul (M.Q k) k (M.μ k (M.γ j₁)) * levelZeroMul (M.Q k) k (M.μ k (M.γ j₂))
    have hm₃ : M.γ j₁ * M.γ j₂ ∈ testSet M.γ k := h₃ ▸ mem_testSet M.γ (k := k) hj₃ (by omega)
    rw [M.mul k _ (mem_testSet M.γ (k := k) hj₁ (by omega)) _
      (mem_testSet M.γ (k := k) hj₂ (by omega)) hm₃, levelZeroMul_mul]

variable {ω}

/-- **Injective as `μ_k(γ) ≠ 1` for `γ ≠ 1` and large `k`** (tex l.351–352). -/
theorem embedding_injective (hω : (ω : Filter ℕ) ≤ cofinite) :
    Function.Injective (embedding M ω hω) := by
  refine (injective_iff_map_eq_one _).2 fun x hx => ?_
  obtain ⟨j, hj, rfl⟩ := M.surj x
  have h' : (QuotientGroup.mk (embedSeq M (M.γ j)) : Ultraproduct ω (SymX M)) =
      QuotientGroup.mk 1 :=
    hx.trans (QuotientGroup.mk_one (AlgebraicUltraproduct.nullSubgroup ω (SymX M))).symm
  have h : ∀ᶠ k in (ω : Filter ℕ), levelZeroMul (M.Q k) k (M.μ k (M.γ j)) = 1 :=
    (mk_eq_mk_iff ω (SymX M)).1 h'
  obtain ⟨k, hk, hk1⟩ := ((eventually_ge hω j).and h).exists
  have hμ : M.μ k (M.γ j) = M.μ k 1 := by
    rw [eq_one_of_levelZeroMul_eq_one (M.Q k) k hk1, M.μ_one]
  exact M.inj k (mem_testSet M.γ (k := k) hj hk) (one_mem_testSet M.γ k) hμ

/-- **It sends `γ_j` to `w_j(a,b)`** (tex l.352–353). -/
theorem embedding_γ (hω : (ω : Filter ℕ) ≤ cofinite) {j : ℕ} (hj : 1 ≤ j) :
    embedding M ω hω (M.γ j) =
      word j (QuotientGroup.mk (aSeq M) : Ultraproduct ω (SymX M)) (QuotientGroup.mk (bSeq M)) := by
  have hw : word j (QuotientGroup.mk (aSeq M) : Ultraproduct ω (SymX M)) (QuotientGroup.mk (bSeq M)) =
      QuotientGroup.mk (word j (aSeq M) (bSeq M)) :=
    (map_word (QuotientGroup.mk' (AlgebraicUltraproduct.nullSubgroup ω (SymX M))) j (aSeq M) (bSeq M)).symm
  rw [hw]
  refine (mk_eq_mk_iff ω (SymX M)).2 ((eventually_ge hω j).mono fun k hk => ?_)
  have hk' : word j (aSeq M) (bSeq M) k = word j (aSeq M k) (bSeq M k) :=
    map_word (Pi.evalMonoidHom (SymX M) k) j (aSeq M) (bSeq M)
  show levelZeroMul (M.Q k) k (M.μ k (M.γ j)) = word j (aSeq M) (bSeq M) k
  rw [hk']
  exact (word_aPerm_bPerm (M.Q k) k (fun j => M.μ k (M.γ j)) hj hk).symm

variable (ω)

/-- `Δ`, the subgroup generated by `a` and `b` (tex l.354). -/
def Delta : Subgroup (Ultraproduct ω (SymX M)) :=
  Subgroup.closure {QuotientGroup.mk (aSeq M), QuotientGroup.mk (bSeq M)}

theorem conjPow_mem_delta (n : ℕ) :
    conjPow (QuotientGroup.mk (aSeq M) : Ultraproduct ω (SymX M)) (QuotientGroup.mk (bSeq M)) n ∈
      Delta M ω := by
  have ha : (QuotientGroup.mk (aSeq M) : Ultraproduct ω (SymX M)) ∈ Delta M ω :=
    Subgroup.subset_closure (Set.mem_insert _ _)
  have hb : (QuotientGroup.mk (bSeq M) : Ultraproduct ω (SymX M)) ∈ Delta M ω :=
    Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
  unfold conjPow
  exact (Delta M ω).mul_mem ((Delta M ω).mul_mem ((Delta M ω).inv_mem ((Delta M ω).pow_mem hb n)) ha)
    ((Delta M ω).pow_mem hb n)

variable {ω}

theorem embedding_mem_delta (hω : (ω : Filter ℕ) ≤ cofinite) (x : Γ) : embedding M ω hω x ∈ Delta M ω := by
  obtain ⟨j, hj, rfl⟩ := M.surj x
  rw [embedding_γ M hω hj, word, commutatorElement_def]
  have hp := conjPow_mem_delta M ω (2 ^ (2 * j - 1))
  have hq := conjPow_mem_delta M ω (4 ^ j)
  exact (Delta M ω).mul_mem ((Delta M ω).mul_mem ((Delta M ω).mul_mem hp hq) ((Delta M ω).inv_mem hp))
    ((Delta M ω).inv_mem hq)

/-- The homomorphism into `Δ`. -/
noncomputable def embeddingΔ (hω : (ω : Filter ℕ) ≤ cofinite) : Γ →* Delta M ω :=
  (embedding M ω hω).codRestrict (Delta M ω) (embedding_mem_delta M hω)

theorem embeddingΔ_injective (hω : (ω : Filter ℕ) ≤ cofinite) : Function.Injective (embeddingΔ M hω) :=
  fun _ _ h => embedding_injective M hω (congrArg Subtype.val h)

/-- **`Γ ≤ [Δ,Δ]`** (tex l.353–354). -/
theorem embeddingΔ_mem_commutator (hω : (ω : Filter ℕ) ≤ cofinite) (x : Γ) :
    embeddingΔ M hω x ∈ commutator (Delta M ω) := by
  obtain ⟨j, hj, rfl⟩ := M.surj x
  have hp := conjPow_mem_delta M ω (2 ^ (2 * j - 1))
  have hq := conjPow_mem_delta M ω (4 ^ j)
  have he : embeddingΔ M hω (M.γ j) = ⁅(⟨_, hp⟩ : Delta M ω), ⟨_, hq⟩⁆ :=
    Subtype.ext (embedding_γ M hω hj)
  rw [he]
  exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)

/-- **`Δ` is infinite** (tex l.356), as it contains an injective image of the infinite group `Γ`. -/
theorem infinite_delta [Infinite Γ] (hω : (ω : Filter ℕ) ≤ cofinite) : Infinite (Delta M ω) :=
  Infinite.of_injective _ (embeddingΔ_injective M hω)

variable (ω)

/-- **`Δ` is finitely generated** (tex l.354–356). -/
theorem fg_delta : Group.FG (Delta M ω) :=
  Group.closure_finite_fg _

/-- **`Δ` is LEF** (tex l.355–356): finitely many products and inequalities hold in one coordinate. -/
theorem isLEF_delta : IsLEF (Delta M ω) :=
  isLEF_subgroup_ultraproduct ω (SymX M) (Delta M ω)

/-- **The paragraph** (tex l.332–356): a countable LEF group embeds, through `Γ × ℤ`, in the commutator subgroup of an
infinite finitely generated LEF group. -/
theorem exists_levelCommutatorEmbedding (Γ : Type) [Group Γ] (hc : Countable Γ) (hΓ : IsLEF Γ) :
    ∃ (Δ : Type) (_ : Group Δ), Infinite Δ ∧ Group.FG Δ ∧ IsLEF Δ ∧
      ∃ f : Γ →* Δ, Function.Injective f ∧ ∀ γ, f γ ∈ commutator Δ := by
  haveI : Countable Γ := hc
  haveI : Countable (Multiplicative ℤ) := inferInstanceAs (Countable ℤ)
  haveI : Infinite (Multiplicative ℤ) := inferInstanceAs (Infinite ℤ)
  have hΓ' : IsTextbookLEF (Γ × Multiplicative ℤ) :=
    isTextbookLEF_prod ((isLEF_iff_textbook Γ).1 hΓ) isTextbookLEF_multiplicative_int
  obtain ⟨M⟩ := models_nonempty (inferInstance : Countable (Γ × Multiplicative ℤ)) hΓ'
  have hω : ((Filter.hyperfilter ℕ : Ultrafilter ℕ) : Filter ℕ) ≤ cofinite :=
    Filter.hyperfilter_le_cofinite
  refine ⟨Delta M (Filter.hyperfilter ℕ), inferInstance, infinite_delta M hω,
    fg_delta M (Filter.hyperfilter ℕ), isLEF_delta M (Filter.hyperfilter ℕ),
    (embeddingΔ M hω).comp (MonoidHom.inl Γ (Multiplicative ℤ)), ?_,
    fun x => embeddingΔ_mem_commutator M hω _⟩
  exact (embeddingΔ_injective M hω).comp fun _ _ h => congrArg Prod.fst h

end LEFLevelEmbedding

open LevelCommutatorWords AlgebraicUltraproduct

/-- tex l.339–340: `[f_jk, t_k]` multiplies the first coordinate by `μ_k(γ_j)`. -/
def PrintedCommutatorMultipliesFirstCoordinate : Prop :=
  ∀ (Q : Type) [Group Q] [Fintype Q] (x : Q), ⁅fPerm Q x, tPerm Q⁆ = levelwise fun _ => Equiv.mulLeft x

theorem printedCommutatorMultipliesFirstCoordinate : PrintedCommutatorMultipliesFirstCoordinate :=
  fun Q _ _ x => commutator_fPerm_tPerm Q x

/-- tex l.343–344: `b_k^{−n} a_k b_k^n` acts on the level `i` as `a_k` acts on the level `i + n`. -/
def PrintedConjugateMovesLevels : Prop :=
  ∀ (Q : Type) [Group Q] [Fintype Q] (k : ℕ) (g : ℕ → Q) (n : ℕ),
    conjPow (aPerm Q k g) (bPerm Q k) n = levelwise fun i => levelAction Q k g (i + (n : ZMod (4 ^ (k + 1))))

theorem printedConjugateMovesLevels : PrintedConjugateMovesLevels :=
  fun Q _ _ k g n => conjPow_aPerm_bPerm Q k g n

/-- tex l.344–345: distinct pairs of powers of `2` have distinct differences. -/
def PrintedDistinctPowerOfTwoDifferences : Prop :=
  ∀ r s r' s' : ℕ, r < s → r' < s' → 2 ^ s - 2 ^ r = 2 ^ s' - 2 ^ r' → r = r' ∧ s = s'

theorem printedDistinctPowerOfTwoDifferences : PrintedDistinctPowerOfTwoDifferences :=
  two_pow_sub_two_pow_inj

/-- tex l.344–348: `w_j(a_k, b_k)` acts by `[f_jk, t_k]` on the level `0` and trivially elsewhere, for `j ≤ k`. -/
def PrintedWordActsOnLevelZero : Prop :=
  ∀ (Q : Type) [Group Q] [Fintype Q] (k : ℕ) (g : ℕ → Q) (j : ℕ), 1 ≤ j → j ≤ k →
    word j (aPerm Q k g) (bPerm Q k) = levelZeroMul Q k (g j)

theorem printedWordActsOnLevelZero : PrintedWordActsOnLevelZero :=
  fun Q _ _ k g _ hj hjk => word_aPerm_bPerm Q k g hj hjk

/-- tex l.355–356: every subgroup of an algebraic ultraproduct of finite groups is LEF. -/
def PrintedUltraproductSubgroupsLEF : Prop :=
  ∀ (G : ℕ → Type) [∀ k, Group (G k)] [∀ k, Finite (G k)] (ω : Ultrafilter ℕ)
    (H : Subgroup (Ultraproduct ω G)), IsLEF H

theorem printedUltraproductSubgroupsLEF : PrintedUltraproductSubgroupsLEF :=
  fun G _ _ ω H => isLEF_subgroup_ultraproduct ω G H

/-- tex l.332–356: a countable LEF group lies in the commutator subgroup of an infinite finitely generated LEF group. -/
def PrintedLEFLevelEmbeddingParagraph : Prop :=
  ∀ (Γ : Type) [Group Γ], Countable Γ → IsLEF Γ →
    ∃ (Δ : Type) (_ : Group Δ), Infinite Δ ∧ Group.FG Δ ∧ IsLEF Δ ∧
      ∃ f : Γ →* Δ, Function.Injective f ∧ ∀ γ, f γ ∈ commutator Δ

theorem printedLEFLevelEmbeddingParagraph : PrintedLEFLevelEmbeddingParagraph :=
  fun Γ _ hc hΓ => LEFLevelEmbedding.exists_levelCommutatorEmbedding Γ hc hΓ

/-- **The piece `LEFUltraproductEmbeddingStatement`** of `cor:lef` and `cor:host` (declared by sk-lef-assembly in
`LEFCharacterization`), proved along tex l.332–356. -/
theorem lefUltraproductEmbeddingStatement : LEFUltraproductEmbeddingStatement :=
  fun Γ _ hc hΓ => LEFLevelEmbedding.exists_levelCommutatorEmbedding Γ hc hΓ

#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedCommutatorMultipliesFirstCoordinate
#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedConjugateMovesLevels
#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedDistinctPowerOfTwoDifferences
#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedWordActsOnLevelZero
#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedUltraproductSubgroupsLEF
#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.printedLEFLevelEmbeddingParagraph
#audit_closed_axioms GroupApproximation.SimpleKazhdanSofic.lefUltraproductEmbeddingStatement

end SimpleKazhdanSofic
end GroupApproximation
