import GroupApproximation.Manuscript.NonMF.HullCitationSentences
import GroupApproximation.Manuscript.NonMF.HullTheorem312Lemma58
import GroupApproximation.Meta.AxiomGuard

/-!
# `lem:saturation`: the pair `h₁, h₂` along Hull's printed route

`non_mf_groups_exist.tex`, proof of `lem:saturation`, line 2144:

> By Hull [Corollary 5.7 and Lemma 5.8], `N` contains two elements `h₁,h₂` such
> that `N₀ = ⟨h₁,h₂⟩` is suitable with respect to a generating set `A' ⊇ A` to
> which Hull's small cancellation theorem again applies.

The corpus already proves this sentence with `A' = A`
(`HullCitationSentences.printedSaturationHullPair`). That proof only works over a
torsion-free group, where the finite-normalizer clause of Hull's Definition 1.4
holds automatically. This module follows the route the sentence prints instead,
and the result holds at every group:

1. **Hull, Corollary 5.7** (`HullCitationSentences.printedHullCorollary57`, closed)
   with `k = 2` gives loxodromic, pairwise non-commensurable `h₀, h₁ ∈ N` with
   `E(hᵢ) = ⟨hᵢ⟩`.
2. **Hull, Theorem 3.16**, at the one-element family
   (`HullSC.isHyperbolicallyEmbedded_zpowers_of_elementaryClosure_eq_unconditional`,
   closed), gives `⟨h₀⟩ ↪h (G, A)`.
3. `h₀` has infinite order because it is loxodromic
   (`HullGeometry.not_isOfFinOrder_of_isLoxodromic`).
4. `⟨h₀⟩ < ⟨h₀, h₁⟩`. If `h₁ = h₀ⁿ`, then either `n = 0` and `h₁ = 1` has finite
   order, or `h₀ⁿ = h₁¹` contradicts non-commensurability.
5. **Hull, Lemma 5.8** (`HullTheorem312Lemma58.printedHullLemma58`, closed) gives a
   Hull generating set `A' ⊇ A` for which `N₀ = ⟨h₀, h₁⟩` is suitable.

"To which Hull's small cancellation theorem again applies" means that `A'` is again
a `HullGeneratingSet`: this is clause (1) of Hull's Definition 1.4, the only datum
`thm:hull` takes. The inclusion `N₀ ≤ N` used later in the proof is also returned.
-/

namespace GroupApproximation
namespace Manuscript
namespace NonMF
namespace Saturation

open GroupApproximation.HullGeometry
open GroupApproximation.WordMetric
open GroupApproximation.Manuscript.NonMF.TorsionFree

universe u

/-- **Hull, Corollary 5.7**, restated at this lane (tex line 2144). It is the
closed `HullCitationSentences.printedHullCorollary57`. -/
theorem manuscriptSentence_hullCorollary57 :
    HullCitationSentences.PrintedHullCorollary57 :=
  HullCitationSentences.printedHullCorollary57

#audit_axioms manuscriptSentence_hullCorollary57

/-- **Hull, Lemma 5.8**, restated at this lane (tex line 2144). It is the closed
`HullTheorem312Lemma58.printedHullLemma58`. -/
theorem manuscriptSentence_hullLemma58 : HullTheorem312Lemma58.PrintedHullLemma58.{u} :=
  HullTheorem312Lemma58.printedHullLemma58.{u}

#audit_axioms manuscriptSentence_hullLemma58

/-- A loxodromic element with `E(g) = ⟨g⟩` generates a subgroup that is
hyperbolically embedded over Hull's alphabet: Theorem 3.16 applied to the
one-element family. -/
theorem isHypEmbeddedOf_zpowers_of_isLoxodromic {G : Type u} [Group G]
    (A : HullGeneratingSet G) {g : G}
    (hlox : IsLoxodromic g (Cayley.base A.alphabet))
    (hcyc : GGT.Elementary.elementaryClosure g = Subgroup.zpowers g) :
    GGT.IsHypEmbeddedOf G A.alphabet.carrier (Subgroup.zpowers g) :=
  ⟨HullSC.coneOffFamily A.alphabet (fun _ : Unit => Subgroup.zpowers g), rfl, rfl,
    HullSC.isHyperbolicallyEmbedded_zpowers_of_elementaryClosure_eq_unconditional
      (Λ := Unit) A (fun _ => g) (HullSC.pairwiseNonCommensurable_of_subsingleton _)
      (fun _ => hlox) (fun _ => hcyc)⟩

/-- The two elements from Corollary 5.7 give a proper inclusion
`⟨h₀⟩ < ⟨h₀, h₁⟩`: this is the hypothesis `⟨h⟩ < S` of Lemma 5.8. -/
theorem zpowers_lt_closure_pair {G : Type u} [Group G] (A : HullGeneratingSet G)
    {h : Fin 2 → G} (hlox : IsLoxodromic (h 1) (Cayley.base A.alphabet))
    (hncom : HullSC.PairwiseNonCommensurable h) :
    Subgroup.zpowers (h 0) < Subgroup.closure ({h 0, h 1} : Set G) := by
  refine lt_of_le_of_ne ?_ ?_
  · rw [Subgroup.zpowers_le]
    exact Subgroup.subset_closure (Set.mem_insert _ _)
  · intro heq
    have h1mem : h 1 ∈ Subgroup.zpowers (h 0) := by
      rw [heq]
      exact Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_singleton _))
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp h1mem
    by_cases hn0 : n = 0
    · subst hn0
      rw [zpow_zero] at hn
      apply HullGeometry.not_isOfFinOrder_of_isLoxodromic hlox
      rw [← hn]
      exact IsOfFinOrder.one
    · refine hncom 0 1 (by decide) n 1 hn0 one_ne_zero 1 ?_
      rw [one_mul, inv_one, mul_one, zpow_one, hn]

/-- A subgroup generated by two elements of `N` lies in `N`. -/
theorem closure_pair_le_of_mem {G : Type u} [Group G] {N : Subgroup G} {a b : G}
    (ha : a ∈ N) (hb : b ∈ N) : Subgroup.closure ({a, b} : Set G) ≤ N := by
  rw [Subgroup.closure_le]
  intro x hx
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
  rcases hx with rfl | rfl
  · exact ha
  · exact hb

/-- **"By Hull [Corollary 5.7 and Lemma 5.8], `N` contains two elements `h₁,h₂`
such that `N₀ = ⟨h₁,h₂⟩` is suitable with respect to a generating set `A' ⊇ A` to
which Hull's small cancellation theorem again applies."** (tex line 2144, proof
of `lem:saturation`).

Proved along the printed route (Corollary 5.7, then Lemma 5.8) at every group
`G`, with no torsion-freeness. `A'` is a `HullGeneratingSet`, which is the datum
`thm:hull` applies to, and `N₀ ≤ N` is returned as well. -/
theorem manuscriptSentence_saturationHullPair {G : Type} [Group G]
    (A : HullGeneratingSet G) {N : Subgroup G} (hN : Suitable A.alphabet N) :
    ∃ A' : HullGeneratingSet G, A.alphabet.carrier ⊆ A'.alphabet.carrier ∧
      ∃ h₁ ∈ N, ∃ h₂ ∈ N, Subgroup.closure ({h₁, h₂} : Set G) ≤ N ∧
        Suitable A'.alphabet (Subgroup.closure ({h₁, h₂} : Set G)) := by
  obtain ⟨h, hmem, hlox, hncom, hcyc, -⟩ :=
    HullCitationSentences.printedHullCorollary57 A hN 2
  have hemb : GGT.IsHypEmbeddedOf G A.alphabet.carrier (Subgroup.zpowers (h 0)) :=
    isHypEmbeddedOf_zpowers_of_isLoxodromic A (hlox 0) (hcyc 0)
  have hlt : Subgroup.zpowers (h 0) < Subgroup.closure ({h 0, h 1} : Set G) :=
    zpowers_lt_closure_pair A (hlox 1) hncom
  obtain ⟨A', hAA', hsuit⟩ :=
    HullTheorem312Lemma58.printedHullLemma58.{0} A.alphabet.carrier
      (Subgroup.closure ({h 0, h 1} : Set G)) (h 0)
      (Subgroup.subset_closure (Set.mem_insert _ _))
      (HullGeometry.not_isOfFinOrder_of_isLoxodromic (hlox 0)) hlt hemb
  exact ⟨A', hAA', h 0, hmem 0, h 1, hmem 1, closure_pair_le_of_mem (hmem 0) (hmem 1),
    hsuit⟩

#audit_axioms manuscriptSentence_saturationHullPair

end Saturation
end NonMF
end Manuscript
end GroupApproximation
