import Mathlib.GroupTheory.Perm.Closure
import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.GroupTheory.Perm.Fin
import Mathlib.GroupTheory.SpecificGroups.Alternating
import Mathlib.GroupTheory.SpecificGroups.Alternating.Simple
import Mathlib.Tactic.Group

/-!
# `Alt(n)` is generated by a three-cycle and an `n`-cycle, for odd `n ≥ 5`

`Monsters/NeumannSimpleSocle` records that the one remaining input for `UN.07`
--- the printed clause *"for instance Neumann's two-generator groups"* --- is the
classical generation lemma

  `⟨(1 2 3), (1 2 … n)⟩ = Alt(n)`  for odd `n ≥ 5`,

from which the hypotheses of `normalFactorSet_eq_of_subsetProduct` for Neumann's
`G_S ≤ ∏_{n ∈ S} Alt(n)` are meant to follow.  Mathlib has `alternatingGroup`,
three-cycle generation and simplicity, but nothing about this pair.  This module
supplies it.

## The route

The obvious proof --- conjugate `(1 2 3)` by powers of the `n`-cycle to reach
every consecutive triple `(k, k+1, k+2)`, then induct to reach every three-cycle
--- is a genuine induction on index arithmetic mod `n`.  It is not the route
taken here, because a shorter one reuses two theorems Mathlib already has.

Write `s = (x, σx)` for the transposition adjacent to the cycle `σ`, and let

  `τ = s · (σ s σ⁻¹) = (x, σx)(σx, σ²x)`,

which is the three-cycle `(x, σx, σ²x)` and is also the commutator
`s σ s⁻¹ σ⁻¹`.  Then `⟨σ, τ⟩` is normalized by `σ`, which lies in it, and by `s`,
because conjugation by the involution `s` sends the two generators to `τσ` and
`τ⁻¹`.  Since `σ` and `s` generate the *whole* symmetric group
(`Equiv.Perm.closure_cycle_adjacent_swap`), `⟨σ, τ⟩` is normal in `Perm α`.  It
lies inside `alternatingGroup α`, because a three-cycle is even and an `n`-cycle
with `n` odd is even, and it is nontrivial.  Simplicity of the alternating group
on at least five points (`alternatingGroup.isSimpleGroup`) then forces it to be
everything.

Oddness of `n` enters in exactly one place and is essential there: it is what
puts the `n`-cycle inside the alternating group at all.  For even `n` the
`n`-cycle is an odd permutation and the same pair generates the whole symmetric
group.

## Main results

* `closure_pair_eq_alternatingGroup` --- the theorem, for an arbitrary
  full-support cycle `σ` on a type of odd cardinality at least five and an
  arbitrary base point `x`.  Reading `σ = (1 2 … n)` and `x = 1`, the second
  generator is literally `(1 2 3)`.
* `isThreeCycle_swapPair` --- that second generator really is a three-cycle, so
  the statement above is the printed one and not a lookalike.
* `closure_finRotate_pair_eq_alternatingGroup` --- the same for `Fin n` and the
  standard rotation, which discharges the cycle hypotheses concretely.
* `exists_pair_closure_eq_top` --- the alternating group is two-generated, in
  the shape of the repository's `IsTwoGenerated` (which this module deliberately
  does not import: it lives in `Sofic/`, and inverting the layering to reach it
  would pull that file into `Algebra/`).

What this does and does not give `UN.07` is set out at the end of the file.
-/

namespace GroupApproximation
namespace AlternatingPairGeneration

open Equiv Equiv.Perm

universe u

/-! ## Conjugation by an involution

Three general lemmas, with no permutations in them.  They isolate the only
group-theoretic content of the descent: a subgroup generated by two elements
that an involution moves back into that subgroup is normalized by the
involution, hence by everything the involution generates together with it. -/

section Conjugation

variable {G : Type u} [Group G]

/-- **Conjugation is determined on generators.**  If conjugation by `g` carries
a generating set into the subgroup it generates, it carries the whole subgroup
into itself. -/
theorem conj_mem_closure_of_gen {g : G} {S : Set G}
    (h : ∀ y ∈ S, g * y * g⁻¹ ∈ Subgroup.closure S) :
    ∀ y ∈ Subgroup.closure S, g * y * g⁻¹ ∈ Subgroup.closure S := by
  intro y hy
  induction hy using Subgroup.closure_induction with
  | mem z hz => exact h z hz
  | one => simp
  | mul a b _ _ ha hb =>
      have hab : g * (a * b) * g⁻¹ = (g * a * g⁻¹) * (g * b * g⁻¹) := by group
      rw [hab]
      exact (Subgroup.closure S).mul_mem ha hb
  | inv a _ ha =>
      have hainv : g * a⁻¹ * g⁻¹ = (g * a * g⁻¹)⁻¹ := by group
      rw [hainv]
      exact (Subgroup.closure S).inv_mem ha

/-- **An involution conjugating a subgroup into itself normalizes it.**  Only
one inclusion has to be checked: conjugation by `g` is its own inverse, so the
reverse inclusion is the forward one applied twice. -/
theorem mem_normalizer_of_involutive {g : G} {H : Subgroup G} (hg : g * g = 1)
    (h : ∀ y ∈ H, g * y * g⁻¹ ∈ H) :
    g ∈ Subgroup.normalizer (H : Set G) := by
  have hginv : g⁻¹ = g := inv_eq_of_mul_eq_one_right hg
  rw [Subgroup.mem_normalizer_iff]
  intro y
  refine ⟨fun hy => h y hy, fun hy => ?_⟩
  have h2 := h _ hy
  have hcalc : g * (g * y * g⁻¹) * g⁻¹ = y := by
    rw [hginv, ← mul_assoc, ← mul_assoc, hg, one_mul, mul_assoc, hg, mul_one]
  rwa [hcalc] at h2

/-- **The normality step.**  If `s` is an involution which conjugates `σ` to
`τσ` and `τ` to `τ⁻¹`, and if `σ` and `s` generate the whole group, then
`⟨σ, τ⟩` is normal.

The two displayed equations are exactly what the pair of the alternating-group
theorem satisfies, with `τ` the commutator `s σ s⁻¹ σ⁻¹`. -/
theorem closure_pair_normal {σ s τ : G} (hs : s * s = 1)
    (hcσ : s * σ * s⁻¹ = τ * σ) (hcτ : s * τ * s⁻¹ = τ⁻¹)
    (htop : Subgroup.closure ({σ, s} : Set G) = ⊤) :
    (Subgroup.closure ({σ, τ} : Set G)).Normal := by
  rw [← Subgroup.normalizer_eq_top_iff, eq_top_iff, ← htop, Subgroup.closure_le]
  intro g hg
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
  rcases hg with rfl | rfl
  · exact Subgroup.le_normalizer (Subgroup.subset_closure (Set.mem_insert _ _))
  · refine mem_normalizer_of_involutive hs (conj_mem_closure_of_gen ?_)
    intro y hy
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hy
    rcases hy with rfl | rfl
    · rw [hcσ]
      exact Subgroup.mul_mem _
        (Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl))
        (Subgroup.subset_closure (Set.mem_insert _ _))
    · rw [hcτ]
      exact Subgroup.inv_mem _
        (Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl))

end Conjugation

/-! ## The pair, and the theorem -/

section Alternating

variable {α : Type*} [DecidableEq α] [Fintype α] {σ : Perm α}

/-- The base point of a full-support cycle is moved by it. -/
theorem apply_ne (hsupp : σ.support = Finset.univ) (x : α) : σ x ≠ x := by
  have hxmem : x ∈ σ.support := by rw [hsupp]; exact Finset.mem_univ x
  exact Equiv.Perm.mem_support.mp hxmem

/-- A full-support cycle on at least three points does not return after two
steps: `x`, `σ x` and `σ (σ x)` are three distinct points. -/
theorem apply_apply_ne (hcyc : σ.IsCycle) (hsupp : σ.support = Finset.univ)
    (hcard : 3 ≤ Fintype.card α) (x : α) : σ (σ x) ≠ x := by
  intro hcon
  have hx1 : σ x ≠ x := apply_ne hsupp x
  have hsq : (σ ^ 2) x = x := by
    rw [pow_two, Equiv.Perm.mul_apply]
    exact hcon
  have hone : σ ^ 2 = 1 := (hcyc.pow_eq_one_iff' hx1).mpr hsq
  have hdvd : orderOf σ ∣ 2 := orderOf_dvd_of_pow_eq_one hone
  have hord : orderOf σ = Fintype.card α := by
    rw [hcyc.orderOf, hsupp, Finset.card_univ]
  rw [hord] at hdvd
  have hle := Nat.le_of_dvd (by norm_num) hdvd
  omega

/-- **The second generator is a three-cycle.**  With `σ = (1 2 … n)` and `x = 1`
this is the permutation the manuscript writes `(1 2 3)`, so the generation
theorem below is the printed statement and not a lookalike. -/
theorem isThreeCycle_swapPair (hcyc : σ.IsCycle) (hsupp : σ.support = Finset.univ)
    (hcard : 3 ≤ Fintype.card α) (x : α) :
    (Equiv.swap x (σ x) * Equiv.swap (σ x) (σ (σ x))).IsThreeCycle := by
  have hx1 : σ x ≠ x := apply_ne hsupp x
  have hx2 : σ (σ x) ≠ σ x := fun hcon => hx1 (σ.injective hcon)
  have hx3 : σ (σ x) ≠ x := apply_apply_ne hcyc hsupp hcard x
  rw [Equiv.swap_comm x (σ x)]
  exact Equiv.Perm.isThreeCycle_swap_mul_swap_same hx1 (Ne.symm hx2) (Ne.symm hx3)

/-- **`Alt(n)` is generated by a three-cycle and an `n`-cycle, for odd `n ≥ 5`.**

`σ` is an arbitrary cycle moving every point --- read `(1 2 … n)` --- and the
second generator is the three-cycle `(x, σx, σ²x)`, written as a product of two
transpositions; reading `x = 1` it is `(1 2 3)`.  `isThreeCycle_swapPair`
certifies that it is a three-cycle.

The oddness hypothesis is used exactly once, to place `σ` in the alternating
group, and it cannot be dropped: for even `n` the `n`-cycle is odd and the same
pair generates the whole symmetric group. -/
theorem closure_pair_eq_alternatingGroup (hcyc : σ.IsCycle)
    (hsupp : σ.support = Finset.univ) (hodd : Odd (Fintype.card α))
    (hcard : 5 ≤ Fintype.card α) (x : α) :
    Subgroup.closure
        ({σ, Equiv.swap x (σ x) * Equiv.swap (σ x) (σ (σ x))} : Set (Perm α))
      = alternatingGroup α := by
  have hx1 : σ x ≠ x := apply_ne hsupp x
  have hx2 : σ (σ x) ≠ σ x := fun hcon => hx1 (σ.injective hcon)
  -- the transposition adjacent to the cycle, and the identities it satisfies
  have hs2 : Equiv.swap x (σ x) * Equiv.swap x (σ x) = 1 := Equiv.swap_mul_self _ _
  have hsinv : (Equiv.swap x (σ x))⁻¹ = Equiv.swap x (σ x) := Equiv.swap_inv _ _
  have hs'inv : (Equiv.swap (σ x) (σ (σ x)))⁻¹ = Equiv.swap (σ x) (σ (σ x)) :=
    Equiv.swap_inv _ _
  have hA : σ * Equiv.swap x (σ x) = Equiv.swap (σ x) (σ (σ x)) * σ :=
    Equiv.mul_swap_eq_swap_mul σ x (σ x)
  -- conjugation by that transposition, on the two generators
  have hcσ : Equiv.swap x (σ x) * σ * (Equiv.swap x (σ x))⁻¹
      = Equiv.swap x (σ x) * Equiv.swap (σ x) (σ (σ x)) * σ := by
    rw [hsinv, mul_assoc, mul_assoc, hA]
  have hcτ : Equiv.swap x (σ x) *
        (Equiv.swap x (σ x) * Equiv.swap (σ x) (σ (σ x))) * (Equiv.swap x (σ x))⁻¹
      = (Equiv.swap x (σ x) * Equiv.swap (σ x) (σ (σ x)))⁻¹ := by
    rw [hsinv, ← mul_assoc, hs2, one_mul, mul_inv_rev, hsinv, hs'inv]
  -- normality, from `⟨σ, (x, σx)⟩ = Perm α`
  have hnormal := closure_pair_normal hs2 hcσ hcτ
    (Equiv.Perm.closure_cycle_adjacent_swap hcyc hsupp x)
  -- both generators are even
  have hσalt : σ ∈ alternatingGroup α := by
    rw [Equiv.Perm.mem_alternatingGroup, hcyc.sign, hsupp, Finset.card_univ,
      hodd.neg_one_pow, neg_neg]
  have hτalt : Equiv.swap x (σ x) * Equiv.swap (σ x) (σ (σ x)) ∈ alternatingGroup α := by
    rw [Equiv.Perm.mem_alternatingGroup, map_mul,
      Equiv.Perm.sign_swap (Ne.symm hx1), Equiv.Perm.sign_swap (Ne.symm hx2),
      neg_mul_neg, one_mul]
  have hle : Subgroup.closure
      ({σ, Equiv.swap x (σ x) * Equiv.swap (σ x) (σ (σ x))} : Set (Perm α))
      ≤ alternatingGroup α := by
    rw [Subgroup.closure_le]
    intro g hg
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
    rcases hg with rfl | rfl
    · exact hσalt
    · exact hτalt
  -- simplicity of the alternating group finishes it
  haveI : IsSimpleGroup (alternatingGroup α) :=
    alternatingGroup.isSimpleGroup (by rwa [Nat.card_eq_fintype_card])
  rcases (Subgroup.isSimpleGroup_iff.mp inferInstance).2 _ hle
      (hnormal.subgroupOf (alternatingGroup α)) with hbot | htop
  · exfalso
    have hσmem : σ ∈ Subgroup.closure
        ({σ, Equiv.swap x (σ x) * Equiv.swap (σ x) (σ (σ x))} : Set (Perm α)) :=
      Subgroup.subset_closure (Set.mem_insert _ _)
    rw [hbot, Subgroup.mem_bot] at hσmem
    exact hx1 (by simp [hσmem])
  · exact htop

/-- **The alternating group on an odd number of at least five points is
two-generated.**  This is `closure_pair_eq_alternatingGroup` transported into
the subtype, in the shape of the repository's `IsTwoGenerated` predicate. -/
theorem exists_pair_closure_eq_top (hcyc : σ.IsCycle)
    (hsupp : σ.support = Finset.univ) (hodd : Odd (Fintype.card α))
    (hcard : 5 ≤ Fintype.card α) :
    ∃ a b : alternatingGroup α,
      Subgroup.closure ({a, b} : Set (alternatingGroup α)) = ⊤ := by
  obtain ⟨x⟩ : Nonempty α := Fintype.card_pos_iff.mp (by omega)
  have hmain := closure_pair_eq_alternatingGroup hcyc hsupp hodd hcard x
  have hσalt : σ ∈ alternatingGroup α := by
    rw [← hmain]
    exact Subgroup.subset_closure (Set.mem_insert _ _)
  have hτalt : Equiv.swap x (σ x) * Equiv.swap (σ x) (σ (σ x)) ∈ alternatingGroup α := by
    rw [← hmain]
    exact Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
  refine ⟨⟨σ, hσalt⟩, ⟨_, hτalt⟩, ?_⟩
  rw [← Subgroup.map_subtype_inj, MonoidHom.map_closure, Set.image_pair,
    ← MonoidHom.range_eq_map, Subgroup.range_subtype]
  exact hmain

/-! ## The standard rotation of `Fin n`

`finRotate n` is the `n`-cycle `i ↦ i + 1`.  These two statements discharge the
cycle hypotheses concretely, which is what a consumer instantiates.  The base
point stays a parameter rather than the literal `0`, because `(0 : Fin n)`
needs a `NeZero n` instance that `5 ≤ n` supplies only inside a proof. -/

/-- **The theorem for `Fin n` and the standard `n`-cycle.** -/
theorem closure_finRotate_pair_eq_alternatingGroup {n : ℕ} (hodd : Odd n)
    (hcard : 5 ≤ n) (x : Fin n) :
    Subgroup.closure
        ({finRotate n,
          Equiv.swap x (finRotate n x) *
            Equiv.swap (finRotate n x) (finRotate n (finRotate n x))} :
          Set (Perm (Fin n)))
      = alternatingGroup (Fin n) :=
  closure_pair_eq_alternatingGroup
    (_root_.isCycle_finRotate_of_le (by omega))
    (_root_.support_finRotate_of_le (by omega))
    (by rwa [Fintype.card_fin]) (by rwa [Fintype.card_fin]) x

/-- **The second `Fin n` generator is a three-cycle.** -/
theorem isThreeCycle_finRotate_swapPair {n : ℕ} (hcard : 3 ≤ n) (x : Fin n) :
    (Equiv.swap x (finRotate n x) *
        Equiv.swap (finRotate n x) (finRotate n (finRotate n x))).IsThreeCycle :=
  isThreeCycle_swapPair
    (_root_.isCycle_finRotate_of_le (by omega))
    (_root_.support_finRotate_of_le (by omega))
    (by rwa [Fintype.card_fin]) x

end Alternating

/-!
## What this does and does not give `UN.07`

`normalFactorSet_eq_of_subsetProduct` of `Monsters/NeumannSimpleSocle` consumes
two facts about Neumann's `G_S ≤ ∏_{n ∈ S} Alt(n)`: that it is subdirect, and
that it contains each factor.

The first follows from the theorem above with no further work once Neumann's
group is built, because the `n`-th coordinate of `⟨t, c⟩` is `⟨t_n, c_n⟩` and the
image of a closure is the closure of the image (`MonoidHom.map_closure`).

The second does **not**.  It is the statement that a subdirect product of
pairwise nonisomorphic nonabelian finite simple groups is the whole product ---
a Goursat-type theorem that is not in Mathlib and is not proved here.  Neumann's
group itself is also not yet in this development: `Monsters/NeumannAlternatingFamily`
builds a different continuum (wreath products over coset spaces), and nothing in
the tree constructs the pair `(t, c)` inside `∏_{n ∈ S} Alt(n)`.  So `UN.07`
still has two named gaps; this module closes the one the ledger called the only
genuinely finite-group-theoretic input, and neither of the other two is a
statement about a *pair* of permutations.
-/

end AlternatingPairGeneration
end GroupApproximation
