import GroupApproximation.Algebra.AmenableInt
import GroupApproximation.Sofic.LocallyFiniteMF

/-!
# Locally finite by `ℤ`

This connects the general amenability development to the shape the
manuscript actually uses: a locally finite normal subgroup with quotient
`ℤ`, and subgroups of the result.

Everything here is composition of results already proved --- local
finiteness gives a mean, `ℤ` gives a mean, extensions combine them, means
give measures, and measures pass to subgroups.  The only new content is
transport along an isomorphism and the bridge to the repository's own
`IsLocallyFiniteGroup` predicate, whose formulation (a finite subgroup
containing each finite set) differs from the one the amenability proof
consumes (the subgroup generated by a finite set is finite).

Nothing here says anything about MF.  Amenable implies MF is
Tikuisis--White--Winter, it is not formalized anywhere, and it remains the
single external input for the manuscript sentences that use this chain.
-/

namespace GroupApproximation
namespace Amenability

/-! ## Transport along an isomorphism -/

/-- An invariant mean transports along a group isomorphism. -/
noncomputable def FunctionMean.congr {G H : Type*} [Group G] [Group H]
    (e : G ≃* H) (m : FunctionMean H) : FunctionMean G where
  eval f := m.eval fun y ↦ f (e.symm y)
  eval_add f g hf hg := by
    obtain ⟨C, hC⟩ := hf
    obtain ⟨D, hD⟩ := hg
    exact m.eval_add _ _ ⟨C, fun y ↦ hC _⟩ ⟨D, fun y ↦ hD _⟩
  eval_nonneg f hf hpos := by
    obtain ⟨C, hC⟩ := hf
    exact m.eval_nonneg _ ⟨C, fun y ↦ hC _⟩ fun y ↦ hpos _
  eval_const c := m.eval_const c
  eval_invariant g f hf := by
    obtain ⟨C, hC⟩ := hf
    have hfun : (fun y ↦ f (g * e.symm y)) =
        fun y ↦ (fun z ↦ f (e.symm z)) (e g * y) := by
      funext y
      show f (g * e.symm y) = f (e.symm (e g * y))
      congr 1
      rw [map_mul, MulEquiv.symm_apply_apply]
    show m.eval (fun y ↦ f (g * e.symm y)) = m.eval fun y ↦ f (e.symm y)
    rw [hfun]
    exact m.eval_invariant (e g) (fun z ↦ f (e.symm z)) ⟨C, fun y ↦ hC _⟩

theorem hasInvariantMean_congr {G H : Type*} [Group G] [Group H]
    (e : G ≃* H) (h : HasInvariantMean H) : HasInvariantMean G := by
  obtain ⟨m⟩ := h
  exact ⟨FunctionMean.congr e m⟩

/-! ## The repository's local finiteness predicate -/

/-- The repository states local finiteness as "every finite set sits in a
finite subgroup"; the amenability proof consumes "the subgroup generated
by a finite set is finite".  They agree. -/
theorem hasInvariantMean_of_isLocallyFiniteGroup {G : Type} [Group G]
    (h : IsLocallyFiniteGroup G) : HasInvariantMean G := by
  classical
  refine hasInvariantMean_of_locallyFinite fun S ↦ ?_
  obtain ⟨H, hHfin, hSH⟩ := h S
  have hle : Subgroup.closure (S : Set G) ≤ H := by
    rw [Subgroup.closure_le]
    intro g hg
    exact hSH g (by exact_mod_cast hg)
  refine Finite.of_injective
    (fun x : Subgroup.closure (S : Set G) ↦ (⟨x.1, hle x.2⟩ : H)) ?_
  intro x y hxy
  have hval : (x : G) = (y : G) := congrArg (fun z : H ↦ (z : G)) hxy
  exact Subtype.ext hval

/-! ## Locally finite by an amenable quotient -/

/-- **Locally finite by amenable is amenable.**  This is the general shape;
the manuscript's instance has quotient `BS(1,2)`, not `ℤ`. -/
theorem hasInvariantMean_of_locallyFinite_by_amenable {G : Type} [Group G]
    (N : Subgroup G) [N.Normal] (hN : IsLocallyFiniteGroup N)
    (hQ : HasInvariantMean (G ⧸ N)) : HasInvariantMean G :=
  hasInvariantMean_of_extension N (hasInvariantMean_of_isLocallyFiniteGroup hN) hQ

/-- A group exhausted by a directed family of infinite cyclic subgroups is
amenable.  This is the shape of `ℤ[1/2]`, the kernel of `BS(1,2)`. -/
theorem hasInvariantMean_of_directed_cyclic {ι : Type} (hι : Nonempty ι)
    [SemilatticeSup ι] {G : Type} [Group G] (K : ι → Subgroup G)
    (hmono : Monotone K) (hcover : ∀ g : G, ∃ i, g ∈ K i)
    (hiso : ∀ i, Nonempty ((K i) ≃* Multiplicative ℤ)) :
    HasInvariantMean G := by
  haveI := hι
  exact hasInvariantMean_of_directed K
    (fun i ↦ (hasInvariantMean_congr (hiso i).some hasInvariantMean_int).some)
    hι hmono hcover

/-! ## Locally finite by the integers -/

/-- **A locally finite group extended by `ℤ` is amenable.**  Every step is
elementary and machine-checked; nothing here concerns MF. -/
theorem hasInvariantMean_of_locallyFinite_by_int {G : Type} [Group G]
    (N : Subgroup G) [N.Normal] (hN : IsLocallyFiniteGroup N)
    (e : (G ⧸ N) ≃* Multiplicative ℤ) : HasInvariantMean G :=
  hasInvariantMean_of_extension N (hasInvariantMean_of_isLocallyFiniteGroup hN)
    (hasInvariantMean_congr e hasInvariantMean_int)

/-- Every subgroup of a locally-finite-by-amenable group is amenable.
This is the shape the manuscript's sharpness sentence uses --- with the
realized quotient as the subgroup and `BS(1,2)` as the amenable quotient,
which the two results above assemble from a directed union of infinite
cyclic groups extended by `ℤ`. -/
theorem isAmenable_subgroup_of_locallyFinite_by_amenable {G : Type} [Group G]
    (N : Subgroup G) [N.Normal] (hN : IsLocallyFiniteGroup N)
    (hQ : HasInvariantMean (G ⧸ N)) (H : Subgroup G) : IsAmenable H :=
  IsAmenable.subgroup
    (isAmenable_of_hasInvariantMean
      (hasInvariantMean_of_locallyFinite_by_amenable N hN hQ)) H

/-- The `ℤ` special case. -/
theorem isAmenable_subgroup_of_locallyFinite_by_int {G : Type} [Group G]
    (N : Subgroup G) [N.Normal] (hN : IsLocallyFiniteGroup N)
    (e : (G ⧸ N) ≃* Multiplicative ℤ) (H : Subgroup G) : IsAmenable H :=
  IsAmenable.subgroup
    (isAmenable_of_hasInvariantMean
      (hasInvariantMean_of_locallyFinite_by_int N hN e)) H

end Amenability
end GroupApproximation
