import GroupApproximation.Algebra.BilateralThreeCellLevels
import GroupApproximation.Leavitt.ElementaryGroup
import Mathlib.Data.Matrix.Basis
import Mathlib.Tactic.Group

/-!
# The three-coordinate bilateral cell in `GL₃`

`non_mf_groups_exist.tex`, proof of Proposition `prop:bilateral-three`
(`\label{prop:bilateral-three}`, tex 1556–1593 at origin/main 68481e4d7):

> It is finitely generated, so $L=\EL_3(S)$ has property~\textup{(T)}.  Embed it in
> $\GL_3(R_X)$ by adjoining identity on $1-p$.
> [...] $W=\operatorname{diag}(u,u,u)\operatorname{diag}(1,1,r)$.
> The correction $r$ acts outside $P$ and centralizes $L$.  Thus $W$ conjugates $L$ into $L$,
> sending a root coefficient $a\in S$ to $uau^{-1}=sat$.  On its third coordinate $W$ fixes the
> negative levels $-1$ and $-2$ individually.  Put
> $c=e_{13}(f_{-1,-2})$, $\ell=e_{21}(p)$, $y=e_{32}(f_{-1,0})$, $z=1+E_{33}f_{-1,-2}$,
> $B=\langle L,W,c,y\rangle$.
> Then $c\in C_B(L)$ and
> $WcW^{-1}=e_{13}(f_{0,-2})$, $\delta=[WcW^{-1},\ell]=e_{23}(-f_{0,-2})$, $[y,\delta]=z^{-1}$.
> Hence $z\in\mathfrak D_B(L)$.  It commutes with $L$, since both its supports lie outside $P$;
> with $W$, since its two levels are fixed; and with $c,y$, by the matrix-unit products.
> [...] The identities $[z,e_{31}(f_{-2,0})]=e_{31}(f_{-1,0})$,
> $[e_{23}(f_{0,-1}),e_{31}(f_{-1,0})]=e_{21}(d)$ then kill the defect root.

Coordinates are 0-indexed: the printed `e₁₃` is `elementaryUnit 0 2`, `E₃₃` is `Matrix.single 2 2`.
The commutator is Mathlib's `⁅g, h⁆ = g h g⁻¹ h⁻¹`, and every printed sign holds in that
convention.

The embedded `L` over a coefficient set `S ⊆ pRp` is `coreGroup S`, generated by the roots
`e_{ij}(a)`, `a ∈ S`; adjoining the identity on `1 - p` sends the root `1_S + a E_{ij}` of
`EL₃(S)` to `1 + a E_{ij}`.  Everything holds for every `Cell` in every ring:

* `W_conj_c`, `delta_eq`, `commutator_y_delta`: the display (tex 1579–1581);
* `W_conj_root`: `W e_{ij}(a) W⁻¹ = e_{ij}(u a u⁻¹)` on the corner, with `u a u⁻¹ = s a t`
  (`Cell.unit_conj_eq_s_mul_t`), so `W_conj_mem_coreGroup`;
* `c_commute_coreGroup` (`c ∈ C_B(L)`), `z_commute_coreGroup`, `z_commute_W`, `z_commute_c`,
  `z_commute_y`, and `z_commute_B`: `z` is central in `B`; `z_mem_B`;
* `commutator_z_root`, `commutator_roots_defect`: the two identities killing the defect root;
* the closed endpoint `printedBilateralThreeCellIdentities`.
-/

namespace GroupApproximation
namespace BilateralThreeCell

open scoped commutatorElement

section MatrixUnits

variable {R : Type*} [Ring R]

theorem single_mul_single_eq_zero {i j k l : Fin 3} {x y : R} (h : j ≠ k ∨ x * y = 0) :
    Matrix.single i j x * Matrix.single k l y = 0 := by
  by_cases hjk : j = k
  · subst hjk
    rw [Matrix.single_mul_single_same, h.resolve_left (not_not.mpr rfl), Matrix.single_zero]
  · exact Matrix.single_mul_single_of_ne (c := x) i j k hjk y

theorem single_neg' (i j : Fin 3) (x : R) : Matrix.single i j (-x) = -Matrix.single i j x :=
  eq_neg_of_add_eq_zero_left (by rw [← Matrix.single_add, neg_add_cancel, Matrix.single_zero])

theorem diag_mul_single (w : Fin 3 → R) (i j : Fin 3) (x : R) :
    Matrix.diagonal w * Matrix.single i j x = Matrix.single i j (w i * x) := by
  ext a b
  rw [Matrix.diagonal_mul]
  by_cases ha : i = a
  · subst ha
    by_cases hb : j = b
    · subst hb
      rw [Matrix.single_apply_same, Matrix.single_apply_same]
    · rw [Matrix.single_apply_of_col_ne _ _ hb, Matrix.single_apply_of_col_ne _ _ hb, mul_zero]
  · rw [Matrix.single_apply_of_row_ne ha, Matrix.single_apply_of_row_ne ha, mul_zero]

theorem single_mul_diag (w : Fin 3 → R) (i j : Fin 3) (x : R) :
    Matrix.single i j x * Matrix.diagonal w = Matrix.single i j (x * w j) := by
  ext a b
  rw [Matrix.mul_diagonal]
  by_cases ha : i = a
  · subst ha
    by_cases hb : j = b
    · subst hb
      rw [Matrix.single_apply_same, Matrix.single_apply_same]
    · rw [Matrix.single_apply_of_col_ne _ _ hb, Matrix.single_apply_of_col_ne _ _ hb, zero_mul]
  · rw [Matrix.single_apply_of_row_ne ha, Matrix.single_apply_of_row_ne ha, zero_mul]

/-- `[1 + A, 1 + B] = 1 + AB` when `A² = B² = BA = 0`. -/
theorem one_add_commutator {M : Type*} [Ring M] (A B : M) (hA : A * A = 0) (hB : B * B = 0)
    (hBA : B * A = 0) : (1 + A) * (1 + B) * (1 - A) * (1 - B) = 1 + A * B := by
  have h1 : (1 + A) * (1 + B) * (1 - A) = 1 + B + A * B - A * A - B * A - A * (B * A) := by
    noncomm_ring
  have h2 : (1 + B + A * B) * (1 - B) = 1 + A * B - B * B - A * (B * B) := by noncomm_ring
  rw [h1, hA, hBA]
  simp only [mul_zero, sub_zero]
  rw [h2, hB]
  simp only [mul_zero, sub_zero]

/-- `1 + A` and `1 + B` commute when `AB = BA = 0`. -/
theorem one_add_commute {M : Type*} [Ring M] (A B : M) (hAB : A * B = 0) (hBA : B * A = 0) :
    (1 + A) * (1 + B) = (1 + B) * (1 + A) := by
  have h1 : (1 + A) * (1 + B) = 1 + A + B + A * B := by noncomm_ring
  have h2 : (1 + B) * (1 + A) = 1 + B + A + B * A := by noncomm_ring
  rw [h1, h2, hAB, hBA]
  abel

theorem elementaryUnit_inv' (i j : Fin 3) (h : i ≠ j) (a : R) :
    (elementaryUnit i j h a)⁻¹ = elementaryUnit i j h (-a) :=
  inv_eq_of_mul_eq_one_right (by rw [elementaryUnit_mul, add_neg_cancel, elementaryUnit_zero])

theorem comm_mem {G : Type*} [Group G] {H : Subgroup G} {g h : G} (hg : g ∈ H) (hh : h ∈ H) :
    ⁅g, h⁆ ∈ H := by
  rw [commutatorElement_def]
  exact H.mul_mem (H.mul_mem (H.mul_mem hg hh) (H.inv_mem hg)) (H.inv_mem hh)

/-- The embedded `L = EL₃(S)` over a coefficient set `S`: the subgroup of `GL₃(R)` generated by
the roots `e_{ij}(a)`, `a ∈ S` (tex 1556–1558). -/
def coreGroup (S : Set R) : Subgroup (Matrix (Fin 3) (Fin 3) R)ˣ :=
  Subgroup.closure {g | ∃ (i j : Fin 3) (h : i ≠ j) (a : R), a ∈ S ∧ elementaryUnit i j h a = g}

theorem root_mem_coreGroup {S : Set R} {a : R} (ha : a ∈ S) (i j : Fin 3) (h : i ≠ j) :
    elementaryUnit i j h a ∈ coreGroup S :=
  Subgroup.subset_closure ⟨i, j, h, a, ha, rfl⟩

theorem commute_coreGroup {S : Set R} {g : (Matrix (Fin 3) (Fin 3) R)ˣ}
    (hg : ∀ (i j : Fin 3) (h : i ≠ j) (a : R), a ∈ S → Commute g (elementaryUnit i j h a)) :
    ∀ x ∈ coreGroup S, Commute g x := by
  intro x hx
  induction hx using Subgroup.closure_induction with
  | mem x hx =>
      obtain ⟨i, j, h, a, ha, rfl⟩ := hx
      exact hg i j h a ha
  | one => exact Commute.one_right _
  | mul x y _ _ hx hy => exact hx.mul_right hy
  | inv x _ hx => exact hx.inv_right

end MatrixUnits

namespace Cell

variable {R : Type*} [Ring R] (C : Cell R)

/-! ### The compressor `W` -/

/-- The diagonal of `W = diag(u,u,u) diag(1,1,r)`. -/
def w : Fin 3 → R := ![↑C.u, ↑C.u, ↑C.u * C.r]

/-- `W = diag(u,u,u) diag(1,1,r)` (tex 1564). -/
def W : (Matrix (Fin 3) (Fin 3) R)ˣ where
  val := Matrix.diagonal C.w
  inv := Matrix.diagonal ![↑C.u⁻¹, ↑C.u⁻¹, C.rInv * ↑C.u⁻¹]
  val_inv := by
    rw [Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
    congr 1
    funext i
    fin_cases i <;> simp [w, mul_assoc, C.r_mul_rInv_cancel_left]
  inv_val := by
    rw [Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
    congr 1
    funext i
    fin_cases i <;> simp [w, mul_assoc, C.rInv_mul_r]

theorem w_mul_corner {a : R} (ha : C.p * a * C.p = a) (i : Fin 3) : C.w i * a = ↑C.u * a := by
  fin_cases i <;> simp [w, mul_assoc, C.r_mul_corner ha]

theorem conj_mul_w {a : R} (ha : C.p * a * C.p = a) (j : Fin 3) :
    ↑C.u * a * ↑C.u⁻¹ * C.w j = ↑C.u * a := by
  fin_cases j <;> simp [w, mul_assoc, C.corner_mul_r ha]

/-- "$W$ conjugates $L$ into $L$, sending a root coefficient $a\in S$ to $uau^{-1}=sat$"
(tex 1566–1568), multiplicative form. -/
theorem W_mul_root {a : R} (ha : C.p * a * C.p = a) (i j : Fin 3) (h : i ≠ j) :
    C.W * elementaryUnit i j h a = elementaryUnit i j h (↑C.u * a * ↑C.u⁻¹) * C.W := by
  apply Units.ext
  change Matrix.diagonal C.w * (1 + Matrix.single i j a) =
    (1 + Matrix.single i j (↑C.u * a * ↑C.u⁻¹)) * Matrix.diagonal C.w
  rw [mul_add, add_mul, mul_one, one_mul, diag_mul_single, single_mul_diag, C.w_mul_corner ha,
    C.conj_mul_w ha]

theorem W_conj_root {a : R} (ha : C.p * a * C.p = a) (i j : Fin 3) (h : i ≠ j) :
    C.W * elementaryUnit i j h a * C.W⁻¹ = elementaryUnit i j h (↑C.u * a * ↑C.u⁻¹) := by
  rw [C.W_mul_root ha, mul_inv_cancel_right]

/-- `W` compresses `L` into itself when `S ⊆ pRp` is stable under `a ↦ u a u⁻¹ = s a t`. -/
theorem W_conj_mem_coreGroup {S : Set R} (hS : ∀ a ∈ S, C.p * a * C.p = a)
    (hu : ∀ a ∈ S, ↑C.u * a * ↑C.u⁻¹ ∈ S) :
    ∀ x ∈ coreGroup S, C.W * x * C.W⁻¹ ∈ coreGroup S := by
  intro x hx
  induction hx using Subgroup.closure_induction with
  | mem x hx =>
      obtain ⟨i, j, h, a, ha, rfl⟩ := hx
      rw [C.W_conj_root (hS a ha)]
      exact root_mem_coreGroup (hu a ha) i j h
  | one => simp
  | mul x y _ _ hx hy =>
      have e : C.W * (x * y) * C.W⁻¹ = (C.W * x * C.W⁻¹) * (C.W * y * C.W⁻¹) := by group
      rw [e]
      exact (coreGroup S).mul_mem hx hy
  | inv x _ hx =>
      have e : C.W * x⁻¹ * C.W⁻¹ = (C.W * x * C.W⁻¹)⁻¹ := by group
      rw [e]
      exact (coreGroup S).inv_mem hx

/-! ### The elements `c`, `ℓ`, `y`, `z`, `δ` -/

/-- `c = e₁₃(f_{-1,-2})` (tex 1572). -/
def c : (Matrix (Fin 3) (Fin 3) R)ˣ := elementaryUnit 0 2 (by decide) (C.f (-1) (-2))

/-- `ℓ = e₂₁(p)` (tex 1572). -/
def ell : (Matrix (Fin 3) (Fin 3) R)ˣ := elementaryUnit 1 0 (by decide) C.p

/-- `y = e₃₂(f_{-1,0})` (tex 1573). -/
def y : (Matrix (Fin 3) (Fin 3) R)ˣ := elementaryUnit 2 1 (by decide) (C.f (-1) 0)

/-- `δ = e₂₃(-f_{0,-2})` (tex 1580). -/
def delta : (Matrix (Fin 3) (Fin 3) R)ˣ := elementaryUnit 1 2 (by decide) (-C.f 0 (-2))

theorem f_mul_self_neg_one_neg_two : C.f (-1) (-2) * C.f (-1) (-2) = 0 := by
  rw [C.f_mul_f]
  norm_num

/-- `z = 1 + E₃₃ f_{-1,-2}` (tex 1574). -/
def z : (Matrix (Fin 3) (Fin 3) R)ˣ where
  val := 1 + Matrix.single 2 2 (C.f (-1) (-2))
  inv := 1 - Matrix.single 2 2 (C.f (-1) (-2))
  val_inv := by
    have hx : Matrix.single (2 : Fin 3) (2 : Fin 3) (C.f (-1) (-2)) *
        Matrix.single (2 : Fin 3) (2 : Fin 3) (C.f (-1) (-2)) = 0 :=
      single_mul_single_eq_zero (Or.inr C.f_mul_self_neg_one_neg_two)
    noncomm_ring [hx]
  inv_val := by
    have hx : Matrix.single (2 : Fin 3) (2 : Fin 3) (C.f (-1) (-2)) *
        Matrix.single (2 : Fin 3) (2 : Fin 3) (C.f (-1) (-2)) = 0 :=
      single_mul_single_eq_zero (Or.inr C.f_mul_self_neg_one_neg_two)
    noncomm_ring [hx]

theorem W_c_scalar : ↑C.u * C.f (-1) (-2) = C.f 0 (-2) * (↑C.u * C.r) := by
  have h1 : ↑C.u * C.f (-1) (-2) = C.f 0 (-2) := by
    rw [C.unit_mul_f]
    norm_num
  have h2 : C.f 0 (-2) * ↑C.u = C.f 0 (-3) := by
    rw [C.f_mul_unit]
    norm_num
  rw [h1, ← mul_assoc, h2, C.f_neg_three_mul_r]

theorem W_mul_c : C.W * C.c = elementaryUnit (0 : Fin 3) 2 (by decide) (C.f 0 (-2)) * C.W := by
  apply Units.ext
  change Matrix.diagonal C.w * (1 + Matrix.single 0 2 (C.f (-1) (-2))) =
    (1 + Matrix.single 0 2 (C.f 0 (-2))) * Matrix.diagonal C.w
  rw [mul_add, add_mul, mul_one, one_mul, diag_mul_single, single_mul_diag]
  congr 2
  exact C.W_c_scalar

/-- **`WcW⁻¹ = e₁₃(f_{0,-2})`** (tex 1579). -/
theorem W_conj_c : C.W * C.c * C.W⁻¹ = elementaryUnit (0 : Fin 3) 2 (by decide) (C.f 0 (-2)) := by
  rw [C.W_mul_c, mul_inv_cancel_right]

theorem commutator_W_conj_c_ell :
    ⁅elementaryUnit (0 : Fin 3) 2 (by decide) (C.f 0 (-2)), C.ell⁆ = C.delta := by
  rw [← commutatorElement_inv, ell,
    elementaryUnit_commutator (1 : Fin 3) 0 2 (by decide) (by decide) (by decide),
    C.p_mul_f_zero, elementaryUnit_inv', delta]

/-- **`δ = [WcW⁻¹, ℓ] = e₂₃(-f_{0,-2})`** (tex 1580). -/
theorem delta_eq : ⁅C.W * C.c * C.W⁻¹, C.ell⁆ = C.delta := by
  rw [C.W_conj_c]
  exact C.commutator_W_conj_c_ell

/-- **`[y, δ] = z⁻¹`** (tex 1581). -/
theorem commutator_y_delta : ⁅C.y, C.delta⁆ = C.z⁻¹ := by
  apply Units.ext
  change (1 + Matrix.single (2 : Fin 3) 1 (C.f (-1) 0)) *
      (1 + Matrix.single (1 : Fin 3) 2 (-C.f 0 (-2))) *
      (1 - Matrix.single (2 : Fin 3) 1 (C.f (-1) 0)) *
      (1 - Matrix.single (1 : Fin 3) 2 (-C.f 0 (-2))) =
    1 - Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2))
  have hab : C.f (-1) 0 * -C.f 0 (-2) = -C.f (-1) (-2) := by
    rw [mul_neg, C.f_mul_f, if_pos rfl]
  have hba : -C.f 0 (-2) * C.f (-1) 0 = 0 := by
    rw [neg_mul, C.f_mul_f]
    norm_num
  rw [one_add_commutator (Matrix.single (2 : Fin 3) 1 (C.f (-1) 0))
      (Matrix.single (1 : Fin 3) 2 (-C.f 0 (-2)))
      (single_mul_single_eq_zero (Or.inl (by decide)))
      (single_mul_single_eq_zero (Or.inl (by decide)))
      (single_mul_single_eq_zero (Or.inr hba)),
    Matrix.single_mul_single_same, hab, single_neg', ← sub_eq_add_neg]

theorem W_z_scalar : ↑C.u * C.r * C.f (-1) (-2) = C.f (-1) (-2) * (↑C.u * C.r) := by
  have h1 : ↑C.u * C.f (-2) (-2) = C.f (-1) (-2) := by
    rw [C.unit_mul_f]
    norm_num
  have h2 : C.f (-1) (-2) * ↑C.u = C.f (-1) (-3) := by
    rw [C.f_mul_unit]
    norm_num
  rw [mul_assoc, C.r_mul_f_neg_one, h1, ← mul_assoc, h2, C.f_neg_three_mul_r]

/-- "[z commutes] with $W$, since its two levels are fixed" (tex 1584). -/
theorem z_commute_W : Commute C.z C.W := by
  show C.z * C.W = C.W * C.z
  apply Units.ext
  change (1 + Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2))) * Matrix.diagonal C.w =
    Matrix.diagonal C.w * (1 + Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2)))
  rw [add_mul, mul_add, one_mul, mul_one, single_mul_diag, diag_mul_single]
  congr 2
  exact C.W_z_scalar.symm

/-- "[z commutes] with $c$ [...] by the matrix-unit products" (tex 1585). -/
theorem z_commute_c : Commute C.z C.c := by
  show C.z * C.c = C.c * C.z
  apply Units.ext
  change (1 + Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2))) *
      (1 + Matrix.single (0 : Fin 3) 2 (C.f (-1) (-2))) =
    (1 + Matrix.single (0 : Fin 3) 2 (C.f (-1) (-2))) *
      (1 + Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2)))
  exact one_add_commute _ _ (single_mul_single_eq_zero (Or.inl (by decide)))
    (single_mul_single_eq_zero (Or.inr C.f_mul_self_neg_one_neg_two))

/-- "[z commutes] with [...] $y$, by the matrix-unit products" (tex 1585). -/
theorem z_commute_y : Commute C.z C.y := by
  show C.z * C.y = C.y * C.z
  apply Units.ext
  change (1 + Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2))) *
      (1 + Matrix.single (2 : Fin 3) 1 (C.f (-1) 0)) =
    (1 + Matrix.single (2 : Fin 3) 1 (C.f (-1) 0)) *
      (1 + Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2)))
  have hxa : C.f (-1) (-2) * C.f (-1) 0 = 0 := by
    rw [C.f_mul_f]
    norm_num
  exact one_add_commute _ _ (single_mul_single_eq_zero (Or.inr hxa))
    (single_mul_single_eq_zero (Or.inl (by decide)))

/-- "It commutes with $L$, since both its supports lie outside $P$" (tex 1583–1584), on roots. -/
theorem z_commute_root {a : R} (ha : C.p * a * C.p = a) (i j : Fin 3) (h : i ≠ j) :
    Commute C.z (elementaryUnit i j h a) := by
  show C.z * elementaryUnit i j h a = elementaryUnit i j h a * C.z
  apply Units.ext
  change (1 + Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2))) * (1 + Matrix.single i j a) =
    (1 + Matrix.single i j a) * (1 + Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2)))
  exact one_add_commute _ _
    (single_mul_single_eq_zero (Or.inr (C.f_mul_corner ha (-1) (by norm_num))))
    (single_mul_single_eq_zero (Or.inr (C.corner_mul_f ha (by norm_num) (-2))))

/-- "$c\in C_B(L)$" (tex 1577), on roots. -/
theorem c_commute_root {a : R} (ha : C.p * a * C.p = a) (i j : Fin 3) (h : i ≠ j) :
    Commute C.c (elementaryUnit i j h a) := by
  show C.c * elementaryUnit i j h a = elementaryUnit i j h a * C.c
  apply Units.ext
  change (1 + Matrix.single (0 : Fin 3) 2 (C.f (-1) (-2))) * (1 + Matrix.single i j a) =
    (1 + Matrix.single i j a) * (1 + Matrix.single (0 : Fin 3) 2 (C.f (-1) (-2)))
  exact one_add_commute _ _
    (single_mul_single_eq_zero (Or.inr (C.f_mul_corner ha (-1) (by norm_num))))
    (single_mul_single_eq_zero (Or.inr (C.corner_mul_f ha (by norm_num) (-2))))

theorem c_commute_coreGroup {S : Set R} (hS : ∀ a ∈ S, C.p * a * C.p = a) :
    ∀ x ∈ coreGroup S, Commute C.c x :=
  commute_coreGroup fun i j h a ha => C.c_commute_root (hS a ha) i j h

theorem z_commute_coreGroup {S : Set R} (hS : ∀ a ∈ S, C.p * a * C.p = a) :
    ∀ x ∈ coreGroup S, Commute C.z x :=
  commute_coreGroup fun i j h a ha => C.z_commute_root (hS a ha) i j h

theorem ell_mem_coreGroup {S : Set R} (hp : C.p ∈ S) : C.ell ∈ coreGroup S :=
  root_mem_coreGroup hp 1 0 (by decide)

/-- **`[z, e₃₁(f_{-2,0})] = e₃₁(f_{-1,0})`** (tex 1591). -/
theorem commutator_z_root :
    ⁅C.z, elementaryUnit (2 : Fin 3) 0 (by decide) (C.f (-2) 0)⁆ =
      elementaryUnit (2 : Fin 3) 0 (by decide) (C.f (-1) 0) := by
  apply Units.ext
  change (1 + Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2))) *
      (1 + Matrix.single (2 : Fin 3) 0 (C.f (-2) 0)) *
      (1 - Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2))) *
      (1 - Matrix.single (2 : Fin 3) 0 (C.f (-2) 0)) =
    1 + Matrix.single (2 : Fin 3) 0 (C.f (-1) 0)
  rw [one_add_commutator (Matrix.single (2 : Fin 3) 2 (C.f (-1) (-2)))
      (Matrix.single (2 : Fin 3) 0 (C.f (-2) 0))
      (single_mul_single_eq_zero (Or.inr C.f_mul_self_neg_one_neg_two))
      (single_mul_single_eq_zero (Or.inl (by decide)))
      (single_mul_single_eq_zero (Or.inl (by decide))),
    Matrix.single_mul_single_same, C.f_mul_f, if_pos rfl]

/-- **`[e₂₃(f_{0,-1}), e₃₁(f_{-1,0})] = e₂₁(d)`** (tex 1592). -/
theorem commutator_roots_defect :
    ⁅elementaryUnit (1 : Fin 3) 2 (by decide) (C.f 0 (-1)),
        elementaryUnit (2 : Fin 3) 0 (by decide) (C.f (-1) 0)⁆ =
      elementaryUnit (1 : Fin 3) 0 (by decide) C.d := by
  rw [elementaryUnit_commutator (1 : Fin 3) 2 0 (by decide) (by decide) (by decide), C.f_mul_f,
    if_pos rfl, C.f_zero_zero]

/-! ### The group `B = ⟨L, W, c, y⟩` -/

/-- `B = ⟨L, W, c, y⟩` (tex 1574). -/
def B (S : Set R) : Subgroup (Matrix (Fin 3) (Fin 3) R)ˣ :=
  Subgroup.closure ((coreGroup S : Set (Matrix (Fin 3) (Fin 3) R)ˣ) ∪ {C.W, C.c, C.y})

theorem coreGroup_le_B (S : Set R) : coreGroup S ≤ C.B S :=
  fun _ hx => Subgroup.subset_closure (Or.inl hx)

theorem W_mem_B (S : Set R) : C.W ∈ C.B S :=
  Subgroup.subset_closure (by simp)

theorem c_mem_B (S : Set R) : C.c ∈ C.B S :=
  Subgroup.subset_closure (by simp)

theorem y_mem_B (S : Set R) : C.y ∈ C.B S :=
  Subgroup.subset_closure (by simp)

/-- `z` is central in `B` (tex 1583–1586). -/
theorem z_commute_B {S : Set R} (hS : ∀ a ∈ S, C.p * a * C.p = a) :
    ∀ x ∈ C.B S, Commute C.z x := by
  intro x hx
  induction hx using Subgroup.closure_induction with
  | mem x hx =>
      rcases hx with hx | rfl | rfl | rfl
      · exact C.z_commute_coreGroup hS x hx
      · exact C.z_commute_W
      · exact C.z_commute_c
      · exact C.z_commute_y
  | one => exact Commute.one_right _
  | mul x y _ _ hx hy => exact hx.mul_right hy
  | inv x _ hx => exact hx.inv_right

theorem z_mem_B {S : Set R} (hp : C.p ∈ S) : C.z ∈ C.B S := by
  have hδ : C.delta ∈ C.B S := by
    rw [← C.delta_eq]
    exact comm_mem ((C.B S).mul_mem ((C.B S).mul_mem (C.W_mem_B S) (C.c_mem_B S))
      ((C.B S).inv_mem (C.W_mem_B S))) (C.coreGroup_le_B S (C.ell_mem_coreGroup hp))
  have h := comm_mem (C.y_mem_B S) hδ
  rw [C.commutator_y_delta] at h
  simpa using (C.B S).inv_mem h

end Cell

/-- The printed identities of the three-coordinate bilateral cell (tex 1552–1592), for every cell
of every ring: `ts = p`, `st = p - d`, wandering, `WcW⁻¹ = e₁₃(f_{0,-2})`,
`[WcW⁻¹, ℓ] = e₂₃(-f_{0,-2})`, `[y, δ] = z⁻¹`, `z` commutes with `W`, `c`, `y`,
`[z, e₃₁(f_{-2,0})] = e₃₁(f_{-1,0})` and `[e₂₃(f_{0,-1}), e₃₁(f_{-1,0})] = e₂₁(d)`. -/
def PrintedBilateralThreeCellIdentities : Prop :=
  ∀ (R : Type) [Ring R] (C : Cell R),
    C.t * C.s = C.p ∧ C.s * C.t = C.p - C.d ∧
    (∀ a b c e : ℤ, C.f a b * C.f c e = if b = c then C.f a e else 0) ∧
    C.W * C.c * C.W⁻¹ = elementaryUnit (0 : Fin 3) 2 (by decide) (C.f 0 (-2)) ∧
    ⁅C.W * C.c * C.W⁻¹, C.ell⁆ = C.delta ∧ ⁅C.y, C.delta⁆ = C.z⁻¹ ∧
    Commute C.z C.W ∧ Commute C.z C.c ∧ Commute C.z C.y ∧
    ⁅C.z, elementaryUnit (2 : Fin 3) 0 (by decide) (C.f (-2) 0)⁆ =
      elementaryUnit (2 : Fin 3) 0 (by decide) (C.f (-1) 0) ∧
    ⁅elementaryUnit (1 : Fin 3) 2 (by decide) (C.f 0 (-1)),
        elementaryUnit (2 : Fin 3) 0 (by decide) (C.f (-1) 0)⁆ =
      elementaryUnit (1 : Fin 3) 0 (by decide) C.d

theorem printedBilateralThreeCellIdentities : PrintedBilateralThreeCellIdentities := by
  intro R _ C
  exact ⟨C.t_mul_s, C.s_mul_t, C.f_mul_f, C.W_conj_c, C.delta_eq, C.commutator_y_delta,
    C.z_commute_W, C.z_commute_c, C.z_commute_y, C.commutator_z_root, C.commutator_roots_defect⟩

end BilateralThreeCell
end GroupApproximation

open GroupApproximation

#audit_closed_axioms GroupApproximation.BilateralThreeCell.printedBilateralThreeCellIdentities
#audit_axioms GroupApproximation.BilateralThreeCell.Cell.z_commute_B
#audit_axioms GroupApproximation.BilateralThreeCell.Cell.z_mem_B
#audit_axioms GroupApproximation.BilateralThreeCell.Cell.W_conj_mem_coreGroup
#audit_axioms GroupApproximation.BilateralThreeCell.Cell.c_commute_coreGroup
