import Mathlib.GroupTheory.FinitelyPresentedGroup

/-!
# Finite subpresentations

**Lemma 54.4 of the dossier, the bookkeeping half.**  The non-finite-presentability
argument for the lamp wreath products needs one classical fact that Mathlib does
not have: a finitely presented group presented by an *infinite* family of
relators over a finite generating set is already presented by *finitely many* of
those relators.  Without it, "the group is finitely presented" says nothing about
the relator family one actually wrote down, and the argument that a relator
outside a finite subfamily can be violated has nothing to contradict.

Two ingredients, both proved here.

* **Normal generation is compact** (`exists_finite_subset_mem_normalClosure`).
  An element of a normal closure lies in the normal closure of finitely many of
  the generators, because it is a finite product of conjugates.  The finite-set
  version `exists_finite_subset_subset_normalClosure` follows by taking a union.

* **Presentations are independent** (`isFinitelyNormallyGenerated_ker`).  If `G`
  is finitely presented, then *every* surjection onto `G` from a free group of
  finite rank has finitely normally generated kernel -- not just the one the
  definition happens to name.  This is the Tietze content: lifting the
  generators of each free group through the other gives maps `A` and `B` with
  `ψ ∘ A = φ` and `φ ∘ B = ψ`, and then `ker φ` is normally generated by the
  finitely many elements `B(T)` together with the finitely many "round trip"
  corrections `x⁻¹ · B(A(x))`.

Together they give `exists_finite_subpresentation`, and its indexed form
`exists_finite_subfamily`, which is the shape the wreath-product argument
consumes: relators indexed by pairs of sites, of which only finitely many can
matter.
-/

namespace GroupApproximation
namespace Tietze

universe u v

/-! ## Normal generation is compact -/

section Compact

variable {G : Type u} [Group G]

/-- **Compactness of normal generation.**  An element of a normal closure already
lies in the normal closure of a finite part of the generating set: it is a finite
product of conjugates, and only finitely many generators occur. -/
theorem exists_finite_subset_mem_normalClosure {R : Set G} {g : G}
    (hg : g ∈ Subgroup.normalClosure R) :
    ∃ R₀ ⊆ R, R₀.Finite ∧ g ∈ Subgroup.normalClosure R₀ := by
  induction hg using Subgroup.closure_induction with
  | mem x hx =>
      obtain ⟨a, ha, hconj⟩ := Group.mem_conjugatesOfSet_iff.mp hx
      refine ⟨{a}, Set.singleton_subset_iff.mpr ha, Set.finite_singleton a, ?_⟩
      exact Subgroup.conjugatesOfSet_subset_normalClosure
        (Group.mem_conjugatesOfSet_iff.mpr ⟨a, rfl, hconj⟩)
  | one => exact ⟨∅, Set.empty_subset R, Set.finite_empty, one_mem _⟩
  | mul x y _ _ ihx ihy =>
      obtain ⟨R₁, hR₁, hf₁, hx⟩ := ihx
      obtain ⟨R₂, hR₂, hf₂, hy⟩ := ihy
      refine ⟨R₁ ∪ R₂, Set.union_subset hR₁ hR₂, hf₁.union hf₂, mul_mem ?_ ?_⟩
      · exact Subgroup.normalClosure_mono Set.subset_union_left hx
      · exact Subgroup.normalClosure_mono Set.subset_union_right hy
  | inv x _ ih =>
      obtain ⟨R₀, hR₀, hf, hx⟩ := ih
      exact ⟨R₀, hR₀, hf, inv_mem hx⟩

/-- The same for a finite set of elements at once. -/
theorem exists_finite_subset_subset_normalClosure {R T : Set G} (hT : T.Finite)
    (hsub : T ⊆ Subgroup.normalClosure R) :
    ∃ R₀ ⊆ R, R₀.Finite ∧ T ⊆ Subgroup.normalClosure R₀ := by
  classical
  choose! F hFsub hFfin hFmem using fun t (ht : t ∈ T) =>
    exists_finite_subset_mem_normalClosure (hsub ht)
  refine ⟨⋃ t ∈ T, F t, Set.iUnion₂_subset fun t ht => hFsub t ht,
    hT.biUnion fun t ht => hFfin t ht, fun t ht => ?_⟩
  exact Subgroup.normalClosure_mono (Set.subset_biUnion_of_mem ht) (hFmem t ht)

end Compact

/-! ## Presentations are independent -/

section Independence

variable {α : Type v} {G : Type u} [Group G]

/-- **The Tietze step.**  For a finitely presented group, *every* surjection from
a free group of finite rank has finitely normally generated kernel.  The
definition of finite presentability names one such surjection; this says the
property does not depend on which one.

The proof lifts the generators of each free group through the other, giving `A`
and `B` with `ψ ∘ A = φ` and `φ ∘ B = ψ`.  Modulo the normal closure of the
round-trip corrections `x⁻¹ · B(A(x))`, the composite `B ∘ A` is the identity;
so a word killed by `φ` is congruent to `B(A(w))`, and `A(w)` lies in `ker ψ`,
which `B` carries into the normal closure of `B(T)`. -/
theorem isFinitelyNormallyGenerated_ker [Finite α] [hG : Group.IsFinitelyPresented G]
    (φ : FreeGroup α →* G) (hφ : Function.Surjective φ) :
    φ.ker.IsFinitelyNormallyGenerated := by
  classical
  obtain ⟨n, ψ, hψ, T, hTfin, hTker⟩ := hG.out
  -- lift the generators of `FreeGroup α` through `ψ`
  choose a ha using fun x : α => hψ (φ (FreeGroup.of x))
  set A : FreeGroup α →* FreeGroup (Fin n) := FreeGroup.lift a with hAdef
  have hA : ∀ w, ψ (A w) = φ w := by
    intro w
    have : ψ.comp A = φ := by
      refine FreeGroup.ext_hom _ _ fun x => ?_
      simp [hAdef, ha x]
    exact congrArg (fun f : FreeGroup α →* G => f w) this
  -- and the generators of `FreeGroup (Fin n)` through `φ`
  choose b hb using fun i : Fin n => hφ (ψ (FreeGroup.of i))
  set B : FreeGroup (Fin n) →* FreeGroup α := FreeGroup.lift b with hBdef
  have hB : ∀ w, φ (B w) = ψ w := by
    intro w
    have : φ.comp B = ψ := by
      refine FreeGroup.ext_hom _ _ fun i => ?_
      simp [hBdef, hb i]
    exact congrArg (fun f : FreeGroup (Fin n) →* G => f w) this
  -- the finite normal generating set
  set S : Set (FreeGroup α) :=
    B '' T ∪ Set.range fun x : α => (FreeGroup.of x)⁻¹ * B (A (FreeGroup.of x)) with hSdef
  refine ⟨S, (hTfin.image B).union (Set.finite_range _), ?_⟩
  have hSker : S ⊆ (φ.ker : Set (FreeGroup α)) := by
    rintro z (⟨t, ht, rfl⟩ | ⟨x, rfl⟩)
    · have : φ (B t) = 1 := by
        rw [hB]
        exact MonoidHom.mem_ker.mp (hTker ▸ Subgroup.subset_normalClosure ht)
      exact this
    · show φ ((FreeGroup.of x)⁻¹ * B (A (FreeGroup.of x))) = 1
      rw [map_mul, map_inv, hB, hA, inv_mul_cancel]
  refine le_antisymm (Subgroup.normalClosure_le_normal hSker) ?_
  -- the reverse inclusion
  intro w hw
  set N : Subgroup (FreeGroup α) := Subgroup.normalClosure S with hNdef
  have hround : ∀ v : FreeGroup α,
      (QuotientGroup.mk' N) (B (A v)) = (QuotientGroup.mk' N) v := by
    intro v
    have hgen : (QuotientGroup.mk' N).comp (B.comp A) = QuotientGroup.mk' N := by
      refine FreeGroup.ext_hom _ _ fun x => ?_
      have hmem : (FreeGroup.of x)⁻¹ * B (A (FreeGroup.of x)) ∈ N :=
        Subgroup.subset_normalClosure (Or.inr ⟨x, rfl⟩)
      have := (QuotientGroup.eq (s := N)).mpr hmem
      simpa using this.symm
    exact congrArg (fun f : FreeGroup α →* FreeGroup α ⧸ N => f v) hgen
  have hAw : A w ∈ Subgroup.normalClosure T := by
    rw [hTker, MonoidHom.mem_ker, hA]
    exact MonoidHom.mem_ker.mp hw
  have hBAw : B (A w) ∈ Subgroup.normalClosure (B '' T) := by
    have : B (A w) ∈ (Subgroup.normalClosure T).map B := ⟨A w, hAw, rfl⟩
    exact Subgroup.map_normalClosure_le T B this
  have hmemN : B (A w) ∈ N :=
    Subgroup.normalClosure_mono Set.subset_union_left hBAw
  have : (QuotientGroup.mk' N) w = 1 := by
    rw [← hround w]
    exact (QuotientGroup.eq_one_iff _).mpr hmemN
  exact (QuotientGroup.eq_one_iff _).mp this

end Independence

/-! ## Finite subpresentations -/

section Subpresentation

variable {α : Type v} [Finite α]

/-- **Finite subpresentation.**  If the group presented by a relator family over
a finite generating set is finitely presented, then finitely many of those
relators already present it.  This is what lets a non-finite-presentability
argument fix a finite subfamily and violate a relator outside it. -/
theorem exists_finite_subpresentation (R : Set (FreeGroup α))
    [Group.IsFinitelyPresented (PresentedGroup R)] :
    ∃ R₀ ⊆ R, R₀.Finite ∧
      Subgroup.normalClosure R₀ = Subgroup.normalClosure R := by
  have hker : (PresentedGroup.mk R).ker.IsFinitelyNormallyGenerated :=
    isFinitelyNormallyGenerated_ker (PresentedGroup.mk R)
      (PresentedGroup.mk_surjective R)
  rw [show (PresentedGroup.mk R).ker = Subgroup.normalClosure R from
    QuotientGroup.ker_mk' _] at hker
  obtain ⟨T, hTfin, hTeq⟩ := hker
  have hTsub : T ⊆ Subgroup.normalClosure R :=
    hTeq ▸ Subgroup.subset_normalClosure
  obtain ⟨R₀, hR₀sub, hR₀fin, hR₀⟩ :=
    exists_finite_subset_subset_normalClosure hTfin hTsub
  refine ⟨R₀, hR₀sub, hR₀fin, le_antisymm (Subgroup.normalClosure_mono hR₀sub) ?_⟩
  rw [← hTeq]
  exact Subgroup.normalClosure_le_normal hR₀

/-- The indexed form: only finitely many members of a relator *family* matter.
This is the shape the wreath-product argument consumes, where the family is
indexed by pairs of sites. -/
theorem exists_finite_subfamily {ι : Type*} (r : ι → FreeGroup α)
    [Group.IsFinitelyPresented (PresentedGroup (Set.range r))] :
    ∃ s : Set ι, s.Finite ∧
      Subgroup.normalClosure (r '' s) = Subgroup.normalClosure (Set.range r) := by
  classical
  rcases isEmpty_or_nonempty ι with hι | hι
  · refine ⟨∅, Set.finite_empty, ?_⟩
    rw [Set.image_empty, Set.range_eq_empty r]
  obtain ⟨R₀, hsub, hfin, heq⟩ := exists_finite_subpresentation (Set.range r)
  choose! j hj using fun z (hz : z ∈ R₀) => hsub hz
  refine ⟨j '' R₀, hfin.image j, ?_⟩
  have himg : r '' (j '' R₀) = R₀ := by
    refine Set.Subset.antisymm ?_ ?_
    · rintro _ ⟨_, ⟨z, hz, rfl⟩, rfl⟩
      rw [hj z hz]
      exact hz
    · intro z hz
      exact ⟨j z, ⟨z, hz, rfl⟩, hj z hz⟩
  rw [himg]
  exact heq

end Subpresentation

end Tietze
end GroupApproximation
