import Mathlib.GroupTheory.HNNExtension
import Mathlib.GroupTheory.FreeGroup.Basic
import Mathlib.GroupTheory.Coprod.Basic

/-!
# Retractions of HNN extensions that kill the base

`HNNExtension.lift f x hx` needs the compatibility condition
`x * f a = f (φ a) * x` for every `a` in the associated subgroup.  When `f` is
the trivial homomorphism both sides are `x`, so the condition is vacuous: an
HNN extension admits a homomorphism killing its base and sending the stable
letter *anywhere*.

That single observation replaces Britton's Lemma in several places where it is
the obvious tool, because a retraction proves injectivity in the cheap
direction.  Two consequences are recorded here:

* `zpow_t_ne_one` --- the stable letter has infinite order, in every HNN
  extension whatsoever, with no hypothesis on `A`, `B` or `φ`.
* `stableLetters_free_of_le_range` --- if a second HNN layer is adjoined along
  associated subgroups that live in the *original* base, then the two stable
  letters generate a free group of rank two.  This is the shape the
  Adian--Rabin construction's `t`-layer has, where the `E3`/`E4` entries of the
  roadmap in `Computability.RabinConstruction` ask exactly for freeness of the
  subgroup the stable letters generate.

The point in both cases is that the map *out* is free and the map *in* is the
one that costs: to know `⟨t₀, t₁⟩` is free it is enough to exhibit a
homomorphism to `FreeGroup (Fin 2)` sending `tᵢ` to the `i`th generator, since
the composite with `FreeGroup (Fin 2) → ⟨t₀, t₁⟩` is then the identity.
-/

namespace GroupApproximation
namespace HNNRetraction

open HNNExtension

variable {G : Type*} [Group G] {A B : Subgroup G} (φ : A ≃* B)

/-- **The retraction.**  A homomorphism out of an HNN extension that kills the
base and sends the stable letter wherever one likes.  The compatibility
condition `lift` asks for is vacuous because both sides are `x`. -/
def killBase {K : Type*} [Group K] (x : K) : HNNExtension G A B φ →* K :=
  HNNExtension.lift 1 x (by intro a; simp)

@[simp] theorem killBase_of {K : Type*} [Group K] (x : K) (g : G) :
    killBase φ x (HNNExtension.of g) = 1 := by
  simp [killBase]

@[simp] theorem killBase_t {K : Type*} [Group K] (x : K) :
    killBase φ x (HNNExtension.t : HNNExtension G A B φ) = x := by
  simp [killBase]

/-- **The stable letter has infinite order**, in every HNN extension.  No
hypothesis on the associated subgroups is needed: the retraction to
`Multiplicative ℤ` sees only the stable letter. -/
theorem zpow_t_ne_one {n : ℤ} (hn : n ≠ 0) :
    (HNNExtension.t : HNNExtension G A B φ) ^ n ≠ 1 := by
  intro h
  have h' : (Multiplicative.ofAdd (1 : ℤ)) ^ n = 1 := by
    have hz := congrArg (killBase φ (Multiplicative.ofAdd (1 : ℤ))) h
    rw [map_zpow, killBase_t] at hz
    simpa using hz
  have h2 := congrArg Multiplicative.toAdd h'
  simp [toAdd_zpow] at h2
  exact hn h2

theorem t_ne_one : (HNNExtension.t : HNNExtension G A B φ) ≠ 1 := by
  intro h
  exact zpow_t_ne_one φ (n := 1) one_ne_zero (by simpa using h)

/-- **The change of generators, for an HNN base.**  `t·g` has infinite order for
every `g` in the base, whatever the order of `g` --- the retraction kills the
base and sees only the stable letter.  This is what makes the variant
construction's `sᵢ = s·xᵢ` usable without any hypothesis on the source
generators. -/
theorem zpow_t_mul_of_ne_one (g : G) {n : ℤ} (hn : n ≠ 0) :
    ((HNNExtension.t : HNNExtension G A B φ) * HNNExtension.of g) ^ n ≠ 1 := by
  intro h
  have h' : (Multiplicative.ofAdd (1 : ℤ)) ^ n = 1 := by
    have hz := congrArg (killBase φ (Multiplicative.ofAdd (1 : ℤ))) h
    rw [map_zpow, map_mul, killBase_t, killBase_of, mul_one] at hz
    simpa using hz
  have h2 := congrArg Multiplicative.toAdd h'
  simp [toAdd_zpow] at h2
  exact hn h2

/-! ## Freeness from a retraction

The roadmap in `Computability.RabinConstruction` asks, at `E3`, `E4` and `E5`,
for subgroups generated by finitely many named elements to be free on those
elements.  Each is an instance of the following, and each therefore costs a
homomorphism rather than a Britton argument: a set of elements that some
homomorphism carries to a free basis is itself a free basis. -/

/-- **Freeness is witnessed by a retraction.**  If some homomorphism sends
`h i` to the `i`th free generator, then `h` freely generates: the induced map
out of the free group is injective. -/
theorem freeGroupLift_injective {H ι : Type*} [Group H] (f : H →* FreeGroup ι)
    (h : ι → H) (hf : ∀ i, f (h i) = FreeGroup.of i) :
    Function.Injective (FreeGroup.lift h) := by
  have hcomp : f.comp (FreeGroup.lift h) = MonoidHom.id (FreeGroup ι) := by
    refine FreeGroup.ext_hom _ _ fun i => ?_
    simp [hf i]
  intro x y hxy
  have : (f.comp (FreeGroup.lift h)) x = (f.comp (FreeGroup.lift h)) y := by
    simp only [MonoidHom.comp_apply, hxy]
  rwa [hcomp] at this

/-- The stable letter of an HNN extension freely generates: `⟨t⟩` is infinite
cyclic.  This is `freeGroupLift_injective` with one generator, and
`killBase` supplying the retraction. -/
theorem freeGroupLift_t_injective :
    Function.Injective
      (FreeGroup.lift fun _ : Unit => (HNNExtension.t : HNNExtension G A B φ)) := by
  refine freeGroupLift_injective
    (killBase φ (FreeGroup.of ())) _ fun i => ?_
  cases i
  simp

/-! ## The same trick over a free product

`E2` of the same roadmap asks that every `sᵢ = s₀xᵢ` have infinite order in
`G = Γ * ⟨s₀⟩`, and prices it against the free-product normal form
(`CoprodI.Word`, `NeWord`).  It is again a retraction: the homomorphism
`G → ⟨s₀⟩` that kills `Γ` and is the identity on `⟨s₀⟩` sends every `sᵢ` to
`s₀`, whatever the `xᵢ` do --- which is exactly the property the change of
generators was made for. -/

/-- Killing the left factor of a free product. -/
def killLeft {Γ K : Type*} [Group Γ] [Group K] : (Monoid.Coprod Γ K) →* K :=
  Monoid.Coprod.lift 1 (MonoidHom.id K)

@[simp] theorem killLeft_inl {Γ K : Type*} [Group Γ] [Group K] (x : Γ) :
    killLeft (Monoid.Coprod.inl x : Monoid.Coprod Γ K) = 1 := by
  simp [killLeft]

@[simp] theorem killLeft_inr {Γ K : Type*} [Group Γ] [Group K] (k : K) :
    killLeft (Monoid.Coprod.inr k : Monoid.Coprod Γ K) = k := by
  simp [killLeft]

/-- **`E2`.**  In `Γ * ⟨s₀⟩`, the element `s₀x` has infinite order for every
`x ∈ Γ`.  No hypothesis on `x`, and in particular none on the order of `x` in
`Γ`: the retraction does not see `Γ` at all. -/
theorem zpow_inr_mul_inl_ne_one {Γ : Type*} [Group Γ] (x : Γ) {n : ℤ} (hn : n ≠ 0) :
    ((Monoid.Coprod.inr (Multiplicative.ofAdd (1 : ℤ)) * Monoid.Coprod.inl x :
        Monoid.Coprod Γ (Multiplicative ℤ))) ^ n ≠ 1 := by
  intro h
  have h' : (Multiplicative.ofAdd (1 : ℤ)) ^ n = 1 := by
    have hz := congrArg (killLeft (Γ := Γ) (K := Multiplicative ℤ)) h
    rw [map_zpow, map_mul, killLeft_inl, killLeft_inr, mul_one] at hz
    simpa using hz
  have h2 := congrArg Multiplicative.toAdd h'
  simp [toAdd_zpow] at h2
  exact hn h2

/-- **A retraction onto a free group on a generating family makes the group
free.**  This is the last step of the collapse half: after the cascade has
killed the base, what is left is generated by the stable letters, and a
homomorphism sending them to a free basis exhibits it as free --- hence
residually finite, hence MF, which is all the collapse side needs. -/
theorem freeGroupLift_bijective {H ι : Type*} [Group H] (f : H →* FreeGroup ι)
    (h : ι → H) (hf : ∀ i, f (h i) = FreeGroup.of i)
    (hgen : ∀ x : H, x ∈ Subgroup.closure (Set.range h)) :
    Function.Bijective (FreeGroup.lift h) := by
  refine ⟨freeGroupLift_injective f h hf, fun x => ?_⟩
  have hrange : (FreeGroup.lift h).range = Subgroup.closure (Set.range h) := by
    rw [MonoidHom.range_eq_map, ← FreeGroup.closure_range_of, MonoidHom.map_closure]
    congr 1
    ext y
    constructor
    · rintro ⟨z, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, by simp⟩
    · rintro ⟨i, rfl⟩
      exact ⟨FreeGroup.of i, ⟨i, rfl⟩, by simp⟩
  have : x ∈ (FreeGroup.lift h).range := by rw [hrange]; exact hgen x
  exact this

/-- The isomorphism the previous theorem gives. -/
noncomputable def freeGroupEquiv {H ι : Type*} [Group H] (f : H →* FreeGroup ι)
    (h : ι → H) (hf : ∀ i, f (h i) = FreeGroup.of i)
    (hgen : ∀ x : H, x ∈ Subgroup.closure (Set.range h)) :
    FreeGroup ι ≃* H :=
  MulEquiv.ofBijective (FreeGroup.lift h) (freeGroupLift_bijective f h hf hgen)

end HNNRetraction
end GroupApproximation
