import Mathlib.GroupTheory.HNNExtension
import Mathlib.GroupTheory.FreeGroup.Basic

/-!
# Retractions of HNN extensions that kill the base

`HNNExtension.lift f x hx` needs the compatibility condition
`x * f a = f (φ a) * x` for every `a` in the associated subgroup.  When `f` is
the trivial homomorphism both sides are `x`, so the condition is vacuous: an
HNN extension admits a homomorphism killing its base and sending the stable
letter *anywhere*.

That single observation replaces Britton's Lemma in several places where it is
the obvious tool, because a retraction proves injectivity in the cheap
direction.  Two consequences are recorded here:

* `zpow_t_ne_one` --- the stable letter has infinite order, in every HNN
  extension whatsoever, with no hypothesis on `A`, `B` or `φ`.
* `stableLetters_free_of_le_range` --- if a second HNN layer is adjoined along
  associated subgroups that live in the *original* base, then the two stable
  letters generate a free group of rank two.  This is the shape the
  Adian--Rabin construction's `t`-layer has, where the `E3`/`E4` entries of the
  roadmap in `Computability.RabinConstruction` ask exactly for freeness of the
  subgroup the stable letters generate.

The point in both cases is that the map *out* is free and the map *in* is the
one that costs: to know `⟨t₀, t₁⟩` is free it is enough to exhibit a
homomorphism to `FreeGroup (Fin 2)` sending `tᵢ` to the `i`th generator, since
the composite with `FreeGroup (Fin 2) → ⟨t₀, t₁⟩` is then the identity.
-/

namespace GroupApproximation
namespace HNNRetraction

open HNNExtension

variable {G : Type*} [Group G] {A B : Subgroup G} (φ : A ≃* B)

/-- **The retraction.**  A homomorphism out of an HNN extension that kills the
base and sends the stable letter wherever one likes.  The compatibility
condition `lift` asks for is vacuous because both sides are `x`. -/
def killBase {K : Type*} [Group K] (x : K) : HNNExtension G A B φ →* K :=
  HNNExtension.lift 1 x (by intro a; simp)

@[simp] theorem killBase_of {K : Type*} [Group K] (x : K) (g : G) :
    killBase φ x (HNNExtension.of g) = 1 := by
  simp [killBase]

@[simp] theorem killBase_t {K : Type*} [Group K] (x : K) :
    killBase φ x (HNNExtension.t : HNNExtension G A B φ) = x := by
  simp [killBase]

/-- **The stable letter has infinite order**, in every HNN extension.  No
hypothesis on the associated subgroups is needed: the retraction to
`Multiplicative ℤ` sees only the stable letter. -/
theorem zpow_t_ne_one {n : ℤ} (hn : n ≠ 0) :
    (HNNExtension.t : HNNExtension G A B φ) ^ n ≠ 1 := by
  intro h
  have h' : (Multiplicative.ofAdd (1 : ℤ)) ^ n = 1 := by
    have hz := congrArg (killBase φ (Multiplicative.ofAdd (1 : ℤ))) h
    rw [map_zpow, killBase_t] at hz
    simpa using hz
  have h2 := congrArg Multiplicative.toAdd h'
  simp [toAdd_zpow] at h2
  exact hn h2

theorem t_ne_one : (HNNExtension.t : HNNExtension G A B φ) ≠ 1 := by
  intro h
  exact zpow_t_ne_one φ (n := 1) one_ne_zero (by simpa using h)

/-! ## Freeness from a retraction

The roadmap in `Computability.RabinConstruction` asks, at `E3`, `E4` and `E5`,
for subgroups generated by finitely many named elements to be free on those
elements.  Each is an instance of the following, and each therefore costs a
homomorphism rather than a Britton argument: a set of elements that some
homomorphism carries to a free basis is itself a free basis. -/

/-- **Freeness is witnessed by a retraction.**  If some homomorphism sends
`h i` to the `i`th free generator, then `h` freely generates: the induced map
out of the free group is injective. -/
theorem freeGroupLift_injective {H ι : Type*} [Group H] (f : H →* FreeGroup ι)
    (h : ι → H) (hf : ∀ i, f (h i) = FreeGroup.of i) :
    Function.Injective (FreeGroup.lift h) := by
  have hcomp : f.comp (FreeGroup.lift h) = MonoidHom.id (FreeGroup ι) := by
    refine FreeGroup.ext_hom _ _ fun i => ?_
    simp [hf i]
  intro x y hxy
  have : (f.comp (FreeGroup.lift h)) x = (f.comp (FreeGroup.lift h)) y := by
    simp only [MonoidHom.comp_apply, hxy]
  rwa [hcomp] at this

/-- The stable letter of an HNN extension freely generates: `⟨t⟩` is infinite
cyclic.  This is `freeGroupLift_injective` with one generator, and
`killBase` supplying the retraction. -/
theorem freeGroupLift_t_injective :
    Function.Injective
      (FreeGroup.lift fun _ : Unit => (HNNExtension.t : HNNExtension G A B φ)) := by
  refine freeGroupLift_injective
    (killBase φ (FreeGroup.of ())) _ fun i => ?_
  cases i
  simp

end HNNRetraction
end GroupApproximation
