import GroupApproximation.Algebra.WordMetric

/-!
# Hyperbolic groups, through Gromov's four-point condition

Mathlib carries no notion of a word-hyperbolic group at this revision, and
neither did this repository: the docstring of `HyperbolicKazhdanPartner` in
`Sofic/SmallCancellationKazhdanEnvelope.lean` used to record that *"Hyperbolicity
is not a field: this library cannot state it"*.  This module supplies the missing
statement, on top of the word metric of `Algebra/WordMetric.lean`, and that
interface now carries hyperbolicity as a field.

## The definition

For an alphabet `S ⊆ G` write `d_S` for the word metric `d_S(x,y) = |x⁻¹y|_S`.
`IsFourPointHyperbolic S δ` is **Gromov's four-point condition**

```
    d(w,x) + d(y,z) ≤ max ( d(w,y) + d(x,z) , d(w,z) + d(x,y) ) + 2δ
```

for all `w x y z : G`, and `IsHyperbolicGroup G` says that *some* finite
symmetric generating set satisfies it for *some* `δ`.

Two conventions are worth spelling out, because both are load-bearing.

* **Four points, not thin triangles.**  The four-point condition is the
  Gromov-product definition `(x·y)_w ≥ min ((x·z)_w, (y·z)_w) - δ` with the
  products cleared, which is what lets it be stated with no subtraction at all
  and hence entirely inside `ℕ`.  For a geodesic space --- and the Cayley graph
  of a group with a finite generating set is geodesic --- it is equivalent, up
  to a change of the constant, to the thin-triangles condition; that equivalence
  is the content of the chapter on hyperbolic spaces in Bridson and Haefliger,
  *Metric Spaces of Non-Positive Curvature*, Part III.H, and of Ghys and de la
  Harpe, *Sur les groupes hyperboliques d'apres Mikhael Gromov*.  Nothing below
  uses the equivalence: the four-point condition is taken as *the* definition,
  so no unproved comparison is smuggled in.

* **A finite generating set is part of the data.**  `IsHyperbolicGroup`
  quantifies over `S : Finset G`, so a hyperbolic group is finitely generated by
  construction.  Hyperbolicity does not depend on which finite generating set is
  chosen --- that is quasi-isometry invariance --- but that theorem is *not*
  proved here, which is why the definition asks only for the existence of one
  good alphabet.  Every consumer in this repository is served by the existential
  form.  `Algebra/WordMetricComparison.lean` proves what that theorem is built
  on --- the two word metrics are bi-Lipschitz equivalent, and geodesic words
  have the subword property --- and says precisely which input is still
  missing.

## What is proved here

* `isFourPointHyperbolic_of_bounded` --- a bounded word metric is hyperbolic,
  with the bound itself as the constant.
* `isHyperbolicGroup_of_finite`, `isHyperbolicGroup_of_finite'` --- every finite
  group is hyperbolic, taking the whole group as the alphabet.
* `isHyperbolicGroup_of_subsingleton` --- the trivial group is `0`-hyperbolic on
  the empty alphabet.
* `isFourPointHyperbolic_iff_gromovProduct` --- the four-point condition is
  exactly Gromov's condition on the products `(x·y)_w`, at the same constant.

`Algebra/HyperbolicInteger.lean` proves that the infinite cyclic group is
`0`-hyperbolic, which is what stops the definition from being a statement about
bounded metrics only, and `Algebra/HyperbolicTransport.lean` proves that
hyperbolicity is an isomorphism invariant.
-/

namespace GroupApproximation
namespace Hyperbolic

open WordMetric

universe u

/-- **Gromov's four-point condition** at constant `δ`, for the word metric of
the alphabet `S`: for all four points, the largest of the three pairings
`d(w,x) + d(y,z)`, `d(w,y) + d(x,z)`, `d(w,z) + d(x,y)` exceeds the second
largest by at most `2δ`.  Stated as the displayed inequality for every ordering
of the four points, which is the subtraction-free form. -/
def IsFourPointHyperbolic {G : Type u} [Group G] (S : Set G) (δ : ℕ) : Prop :=
  ∀ w x y z : G,
    wordDist S w x + wordDist S y z ≤
      max (wordDist S w y + wordDist S x z) (wordDist S w z + wordDist S x y) + 2 * δ

/-- **A word-hyperbolic group**: some finite symmetric generating set has a word
metric satisfying the four-point condition at some constant. -/
def IsHyperbolicGroup (G : Type u) [Group G] : Prop :=
  ∃ S : Finset G, IsSymmetricGeneratingSet (S : Set G) ∧
    ∃ δ : ℕ, IsFourPointHyperbolic (S : Set G) δ

/-- The four-point condition only weakens as the constant grows. -/
theorem IsFourPointHyperbolic.mono {G : Type u} [Group G] {S : Set G} {δ δ' : ℕ}
    (hδ : δ ≤ δ') (h : IsFourPointHyperbolic S δ) : IsFourPointHyperbolic S δ' := by
  intro w x y z
  have h' := h w x y z
  omega

/-- **A bounded word metric is hyperbolic**, with the bound as the constant: the
left side of the four-point inequality is at most `2B`, and the right side is at
least `2B` because word distances are nonnegative. -/
theorem isFourPointHyperbolic_of_bounded {G : Type u} [Group G] {S : Set G} {B : ℕ}
    (hB : ∀ x y : G, wordDist S x y ≤ B) : IsFourPointHyperbolic S B := by
  intro w x y z
  have h₁ := hB w x
  have h₂ := hB y z
  omega

/-- The packaging of `isFourPointHyperbolic_of_bounded` at a finite alphabet. -/
theorem isHyperbolicGroup_of_bounded {G : Type u} [Group G] {S : Finset G} {B : ℕ}
    (hS : IsSymmetricGeneratingSet (S : Set G))
    (hB : ∀ x y : G, wordDist (S : Set G) x y ≤ B) : IsHyperbolicGroup G :=
  ⟨S, hS, B, isFourPointHyperbolic_of_bounded hB⟩

/-- The whole of a finite group is a symmetric generating set. -/
theorem isSymmetricGeneratingSet_univ {G : Type u} [Group G] [Fintype G] :
    IsSymmetricGeneratingSet ((Finset.univ : Finset G) : Set G) := by
  refine ⟨fun x _ => ?_, ?_⟩
  · simp
  · rw [Finset.coe_univ]
    exact Subgroup.closure_univ

/-- With the whole group as alphabet every element is a single letter, so the
word metric is bounded by one. -/
theorem wordDist_univ_le_one {G : Type u} [Group G] [Fintype G] (x y : G) :
    wordDist ((Finset.univ : Finset G) : Set G) x y ≤ 1 := by
  have h : wordNorm ((Finset.univ : Finset G) : Set G) (x⁻¹ * y) ≤ 1 :=
    wordNorm_le_one_of_mem (by simp)
  simpa [wordDist] using h

/-- **Every finite group is hyperbolic.**  Its word metric with respect to the
whole group is bounded by one, so the four-point condition holds at `δ = 1`. -/
theorem isHyperbolicGroup_of_finite {G : Type u} [Group G] [Fintype G] :
    IsHyperbolicGroup G :=
  isHyperbolicGroup_of_bounded isSymmetricGeneratingSet_univ wordDist_univ_le_one

/-- `isHyperbolicGroup_of_finite` under the propositional finiteness class. -/
theorem isHyperbolicGroup_of_finite' {G : Type u} [Group G] [Finite G] :
    IsHyperbolicGroup G := by
  classical
  have : Fintype G := Fintype.ofFinite G
  exact isHyperbolicGroup_of_finite

/-- The empty alphabet generates a trivial group. -/
theorem isSymmetricGeneratingSet_empty_of_subsingleton {G : Type u} [Group G]
    [Subsingleton G] : IsSymmetricGeneratingSet ((∅ : Finset G) : Set G) := by
  refine ⟨fun x hx => ?_, ?_⟩
  · simp at hx
  · rw [Subgroup.eq_top_iff']
    intro x
    rw [Subsingleton.elim x 1]
    exact one_mem _

/-- **The trivial group is `0`-hyperbolic.**  Every word distance vanishes, so
the four-point inequality reads `0 ≤ 0`. -/
theorem isHyperbolicGroup_of_subsingleton {G : Type u} [Group G] [Subsingleton G] :
    IsHyperbolicGroup G := by
  refine isHyperbolicGroup_of_bounded (B := 0)
    isSymmetricGeneratingSet_empty_of_subsingleton ?_
  intro x y
  have h : wordDist ((∅ : Finset G) : Set G) x y = 0 := by
    rw [Subsingleton.elim x y]
    exact wordDist_self _ _
  omega

/-! ## The Gromov-product form

The four-point condition is a rearrangement of the inequality Gromov states for
the product `(x·y)_w = (d(w,x) + d(w,y) - d(x,y)) / 2`.  Doubling clears the
denominator, and working in `ℤ` avoids truncated subtraction; the constant is
the same on both sides, so this is an exact restatement rather than a
comparison up to a factor. -/

/-- Twice the **Gromov product** `(x·y)_w`, as an integer. -/
noncomputable def twiceGromovProduct {G : Type u} [Group G] (S : Set G)
    (w x y : G) : ℤ :=
  (wordDist S w x : ℤ) + (wordDist S w y : ℤ) - (wordDist S x y : ℤ)

/-- **The four-point condition is Gromov's product condition.**  Both say that
the largest of the three pairings of four points beats the second largest by at
most `2δ`; symmetry of the metric is what lets the quantifiers be matched up. -/
theorem isFourPointHyperbolic_iff_gromovProduct {G : Type u} [Group G] {S : Set G}
    (hS : IsSymmetricGeneratingSet S) (δ : ℕ) :
    IsFourPointHyperbolic S δ ↔
      ∀ w x y z : G,
        min (twiceGromovProduct S w x z) (twiceGromovProduct S w y z) - 2 * δ
          ≤ twiceGromovProduct S w x y := by
  constructor
  · intro h4 w x y z
    have h := h4 x y w z
    have c1 := wordDist_comm hS x w
    have c2 := wordDist_comm hS y w
    simp only [twiceGromovProduct]
    omega
  · intro hg w x y z
    have h := hg y w x z
    have c1 := wordDist_comm hS y w
    have c2 := wordDist_comm hS y x
    simp only [twiceGromovProduct] at h
    omega

/-- A hyperbolic group is finitely generated: the alphabet in the definition is
a `Finset`. -/
theorem IsHyperbolicGroup.exists_symmetric_generating_finset {G : Type u} [Group G]
    (h : IsHyperbolicGroup G) :
    ∃ S : Finset G, IsSymmetricGeneratingSet (S : Set G) := by
  obtain ⟨S, hS, -⟩ := h
  exact ⟨S, hS⟩

end Hyperbolic
end GroupApproximation
