import GroupApproximation.Algebra.Malcev

/-!
# Section 46.2 in its original form, and Section 46.4

A finitely generated subgroup of `GL_d(F)`, for an arbitrary field `F`, lies in
`GL_d(R)` for the subring `R` generated by the entries of a symmetric generating
set: matrices with entries in `R` whose inverses also have entries in `R` form a
subgroup, and that subgroup contains the generators.  Mal'cev's theorem for
finitely generated domains then applies.

The contrapositive is the nonlinearity mechanism of Section 46.4: a finitely
generated group that is not residually finite has no faithful finite-dimensional
linear representation over any field.
-/

namespace GroupApproximation

namespace MalcevLinear

open Matrix

universe u

variable {F : Type u} [Field F] {d : ℕ}

/-- Invertible matrices whose entries, and whose inverse's entries, lie in a
subring. -/
def entriesSubgroup (R : Subring F) : Subgroup (GeneralLinearGroup (Fin d) F) where
  carrier := {g | (∀ i j, g.val i j ∈ R) ∧ ∀ i j, g.inv i j ∈ R}
  one_mem' := by
    constructor
    · intro i j
      show (1 : Matrix (Fin d) (Fin d) F) i j ∈ R
      rw [Matrix.one_apply]
      by_cases hij : i = j
      · rw [if_pos hij]; exact R.one_mem
      · rw [if_neg hij]; exact R.zero_mem
    · intro i j
      show (1 : Matrix (Fin d) (Fin d) F) i j ∈ R
      rw [Matrix.one_apply]
      by_cases hij : i = j
      · rw [if_pos hij]; exact R.one_mem
      · rw [if_neg hij]; exact R.zero_mem
  mul_mem' := by
    rintro a b ⟨ha, ha'⟩ ⟨hb, hb'⟩
    constructor
    · intro i j
      show (a.val * b.val) i j ∈ R
      rw [Matrix.mul_apply]
      exact R.sum_mem fun k _ => R.mul_mem (ha i k) (hb k j)
    · intro i j
      show (b.inv * a.inv) i j ∈ R
      rw [Matrix.mul_apply]
      exact R.sum_mem fun k _ => R.mul_mem (hb' i k) (ha' k j)
  inv_mem' := by
    rintro a ⟨ha, ha'⟩
    exact ⟨ha', ha⟩

theorem mem_entriesSubgroup {R : Subring F} {g : GeneralLinearGroup (Fin d) F} :
    g ∈ entriesSubgroup R ↔
      (∀ i j, g.val i j ∈ R) ∧ ∀ i j, g.inv i j ∈ R := Iff.rfl

/-- The entries of such a matrix, as a matrix over the subring. -/
def toMatrixSubring (R : Subring F) (g : entriesSubgroup (d := d) R) :
    Matrix (Fin d) (Fin d) R :=
  Matrix.of fun i j => ⟨(g : GeneralLinearGroup (Fin d) F).val i j,
    (mem_entriesSubgroup.mp g.2).1 i j⟩

/-- The entries of its inverse, as a matrix over the subring. -/
def toMatrixSubringInv (R : Subring F) (g : entriesSubgroup (d := d) R) :
    Matrix (Fin d) (Fin d) R :=
  Matrix.of fun i j => ⟨(g : GeneralLinearGroup (Fin d) F).inv i j,
    (mem_entriesSubgroup.mp g.2).2 i j⟩

@[simp] theorem coe_toMatrixSubring (R : Subring F) (g : entriesSubgroup (d := d) R)
    (i j : Fin d) : ((toMatrixSubring R g i j : R) : F)
      = (g : GeneralLinearGroup (Fin d) F).val i j := rfl

@[simp] theorem coe_toMatrixSubringInv (R : Subring F)
    (g : entriesSubgroup (d := d) R) (i j : Fin d) :
    ((toMatrixSubringInv R g i j : R) : F)
      = (g : GeneralLinearGroup (Fin d) F).inv i j := rfl

theorem subring_matrix_ext {R : Subring F} {A B : Matrix (Fin d) (Fin d) R}
    (h : ∀ i j, ((A i j : R) : F) = ((B i j : R) : F)) : A = B := by
  funext i j
  exact Subtype.ext (h i j)

/-- The general linear group of the subring receives the entries subgroup. -/
def toGL (R : Subring F) (g : entriesSubgroup (d := d) R) :
    GeneralLinearGroup (Fin d) R where
  val := toMatrixSubring R g
  inv := toMatrixSubringInv R g
  val_inv := by
    refine subring_matrix_ext fun i j => ?_
    have hF : ∑ k, (g : GeneralLinearGroup (Fin d) F).val i k
          * (g : GeneralLinearGroup (Fin d) F).inv k j
        = (1 : Matrix (Fin d) (Fin d) F) i j := by
      have h := congrArg (fun M : Matrix (Fin d) (Fin d) F => M i j)
        (g : GeneralLinearGroup (Fin d) F).val_inv
      rw [Matrix.mul_apply] at h
      exact h
    rw [Matrix.mul_apply]
    push_cast
    simp only [coe_toMatrixSubring, coe_toMatrixSubringInv]
    rw [hF, Matrix.one_apply, Matrix.one_apply]
    by_cases hij : i = j
    · rw [if_pos hij, if_pos hij]
      norm_num
    · rw [if_neg hij, if_neg hij]
      norm_num
  inv_val := by
    refine subring_matrix_ext fun i j => ?_
    have hF : ∑ k, (g : GeneralLinearGroup (Fin d) F).inv i k
          * (g : GeneralLinearGroup (Fin d) F).val k j
        = (1 : Matrix (Fin d) (Fin d) F) i j := by
      have h := congrArg (fun M : Matrix (Fin d) (Fin d) F => M i j)
        (g : GeneralLinearGroup (Fin d) F).inv_val
      rw [Matrix.mul_apply] at h
      exact h
    rw [Matrix.mul_apply]
    push_cast
    simp only [coe_toMatrixSubring, coe_toMatrixSubringInv]
    rw [hF, Matrix.one_apply, Matrix.one_apply]
    by_cases hij : i = j
    · rw [if_pos hij, if_pos hij]
      norm_num
    · rw [if_neg hij, if_neg hij]
      norm_num

theorem toGL_injective (R : Subring F) :
    Function.Injective (toGL (d := d) R) := by
  intro g h hgh
  refine Subtype.ext (Units.ext ?_)
  funext i j
  have hval := congrArg
    (fun u : GeneralLinearGroup (Fin d) R => ((u.val i j : R) : F)) hgh
  simpa [toGL] using hval

/-- Residual finiteness pulls back along injective homomorphisms. -/
theorem residuallyFinite_of_injective {G G' : Type*} [Group G] [Group G']
    [Group.ResiduallyFinite G'] (φ : G →* G') (hφ : Function.Injective φ) :
    Group.ResiduallyFinite G := by
  rw [Group.residuallyFinite_iff_forall_finiteIndexNormalSubgroup]
  intro g hg
  apply hφ
  rw [map_one]
  refine Group.eq_one_iff_forall_finiteIndexNormalSubroup (φ g) fun K => ?_
  exact hg (K.comap φ)

/-- The passage to the subring is a homomorphism. -/
def toGLHom (R : Subring F) :
    entriesSubgroup (d := d) R →* GeneralLinearGroup (Fin d) R where
  toFun := toGL R
  map_one' := by
    refine Units.ext ?_
    refine subring_matrix_ext fun i j => ?_
    show (1 : GeneralLinearGroup (Fin d) F).val i j
      = (((1 : GeneralLinearGroup (Fin d) R).val i j : R) : F)
    show (1 : Matrix (Fin d) (Fin d) F) i j
      = (((1 : Matrix (Fin d) (Fin d) R) i j : R) : F)
    rw [Matrix.one_apply, Matrix.one_apply]
    by_cases hij : i = j
    · rw [if_pos hij, if_pos hij]
      norm_num
    · rw [if_neg hij, if_neg hij]
      norm_num
  map_mul' g h := by
    refine Units.ext ?_
    refine subring_matrix_ext fun i j => ?_
    show ((g * h : entriesSubgroup (d := d) R) :
        GeneralLinearGroup (Fin d) F).val i j
      = (((toGL R g * toGL R h : GeneralLinearGroup (Fin d) R).val i j : R) : F)
    rw [show ((g * h : entriesSubgroup (d := d) R) :
        GeneralLinearGroup (Fin d) F).val
        = (g : GeneralLinearGroup (Fin d) F).val
          * (h : GeneralLinearGroup (Fin d) F).val from rfl]
    show ((g : GeneralLinearGroup (Fin d) F).val
        * (h : GeneralLinearGroup (Fin d) F).val) i j
      = (((toMatrixSubring R g * toMatrixSubring R h) i j : R) : F)
    rw [Matrix.mul_apply, Matrix.mul_apply]
    push_cast
    simp only [coe_toMatrixSubring]

theorem toGLHom_injective (R : Subring F) :
    Function.Injective (toGLHom (d := d) R) := toGL_injective R

/-- **Theorem 46.2 in the dossier's form.**  A finitely generated subgroup of
the general linear group of any field is residually finite. -/
theorem residuallyFinite_of_fg (H : Subgroup (GeneralLinearGroup (Fin d) F))
    (hfg : H.FG) : Group.ResiduallyFinite H := by
  classical
  obtain ⟨S, hS⟩ := hfg
  -- the entries of the generators and of their inverses
  set E : Set F := ⋃ s ∈ (S : Set (GeneralLinearGroup (Fin d) F)),
    ((Set.range fun p : Fin d × Fin d => s.val p.1 p.2) ∪
      (Set.range fun p : Fin d × Fin d => s.inv p.1 p.2)) with hEdef
  have hEfin : E.Finite := by
    refine Set.Finite.biUnion S.finite_toSet fun s _ => ?_
    exact (Set.finite_range _).union (Set.finite_range _)
  set R : Subring F := Subring.closure E with hRdef
  haveI : Algebra.FiniteType ℤ R := by
    have hequiv : (Subring.closure E : Subring F) ≃ₐ[ℤ] Algebra.adjoin ℤ E :=
      Subring.closureEquivAdjoinInt E
    haveI : Algebra.FiniteType ℤ (Algebra.adjoin ℤ E) :=
      Algebra.FiniteType.adjoin_of_finite hEfin
    exact Algebra.FiniteType.of_surjective hequiv.symm.toAlgHom
      hequiv.symm.surjective
  -- the whole group has entries in that subring
  have hHle : H ≤ entriesSubgroup (d := d) R := by
    rw [← hS, Subgroup.closure_le]
    intro s hs
    refine ⟨fun i j => ?_, fun i j => ?_⟩
    · refine Subring.subset_closure ?_
      rw [hEdef]
      refine Set.mem_biUnion hs ?_
      exact Or.inl ⟨(i, j), rfl⟩
    · refine Subring.subset_closure ?_
      rw [hEdef]
      refine Set.mem_biUnion hs ?_
      exact Or.inr ⟨(i, j), rfl⟩
  -- transport residual finiteness back
  haveI := residuallyFinite_generalLinearGroup R d
  exact residuallyFinite_of_injective ((toGLHom R).comp (Subgroup.inclusion hHle))
    (fun a b hab => Subgroup.inclusion_injective hHle (toGLHom_injective R hab))

/-- **Section 46.4, mechanism.**  A finitely generated group that is not
residually finite has no faithful finite-dimensional linear representation over
any field. -/
theorem not_injective_of_not_residuallyFinite {G : Type*} [Group G]
    [hfg : Group.FG G] (hnrf : ¬ Group.ResiduallyFinite G)
    (ρ : G →* GeneralLinearGroup (Fin d) F) : ¬ Function.Injective ρ := by
  intro hinj
  apply hnrf
  have hrange : (ρ.range).FG := by
    classical
    obtain ⟨S, hS⟩ : (⊤ : Subgroup G).FG := hfg.out
    refine ⟨S.image ρ, ?_⟩
    rw [MonoidHom.range_eq_map, ← hS, Finset.coe_image,
      MonoidHom.map_closure]
  haveI := residuallyFinite_of_fg ρ.range hrange
  refine residuallyFinite_of_injective ρ.rangeRestrict ?_
  intro a b hab
  exact hinj (congrArg Subtype.val hab)

end MalcevLinear

end GroupApproximation
