import GroupApproximation.Algebra.FinitePresentationTietze

/-!
# Partial commutation, and the non-finite-presentability mechanism

**Lemma 54.4 of the dossier, the obstruction half**, by a route that does not
need graph products.

The dossier obtains non-finite-presentability from Cornulier's criterion, whose
necessity direction is proved with a graph product interpolating between the
free product and the restricted direct product.  Mathlib has no graph products,
and building Green's normal form to reach one nonvanishing commutator is a large
detour.  For **involutive** lamps it is unnecessary: the group

    P(X, E) = ⟨ x ∈ X | x² , [x,y] for (x,y) ∈ E ⟩,

in which exactly the pairs listed in `E` are made to commute, admits an explicit
retraction onto the infinite dihedral group whenever a pair is *missing* from
`E` -- send the two sites of that pair to the two reflections `n ↦ -n` and
`n ↦ 1-n` of `ℤ`, and every other site to the identity.  Every relator dies, and
the missing commutator does not: it acts as the translation `n ↦ n-2`.

That is `commutator_ne_one_of_notMem`, and it is the retraction the obstruction
needs.  `not_isFinitelyPresented_of_violable` is the obstruction itself, stated
for an arbitrary relator family over a *finite* generating set: if every finite
subfamily can be violated -- some further relator survives a homomorphism that
kills the subfamily -- the presented group is not finitely presented.  The
Tietze step of `Algebra/FinitePresentationTietze` is what makes that
contradiction available.

The generating set must be finite, which is exactly why this cannot be applied
to the lamp base directly: over an infinite site set `K^{(X)}` is not finitely
generated, so it is trivially not finitely presented and the interesting
statement is about the wreath product `K^{(X)} ⋊ G`, which *is* finitely
generated by one lamp and the generators of `G`.  What remains is therefore the
presentation of the wreath product on that finite generating set, trading the
lamp generators indexed by `X` for a single lamp conjugated by group words.
That is bookkeeping about a specific presentation, and it is not done here.
-/

namespace GroupApproximation
namespace PartialCommutation

open scoped commutatorElement

universe u

variable {X : Type u}

/-! ## The presentation -/

/-- The relators of the partial-commutation group on sites `X`: every site is an
involution, and the pairs listed in `E` commute. -/
def relators (X : Type u) (E : Set (X × X)) : Set (FreeGroup X) :=
  (Set.range fun x : X => FreeGroup.of x * FreeGroup.of x) ∪
    ((fun p : X × X => ⁅FreeGroup.of p.1, FreeGroup.of p.2⁆) '' E)

/-- The partial-commutation group: involutive generators, commuting exactly along
the prescribed set of pairs. -/
abbrev PartialLamp (X : Type u) (E : Set (X × X)) := PresentedGroup (relators X E)

/-- The full relator set, in which every pair of sites commutes.  This is the
presentation the lamp base of an involutive wreath product carries. -/
abbrev lampRelators (X : Type u) : Set (FreeGroup X) := relators X Set.univ

/-! ## The dihedral retraction -/

/-- The reflection `n ↦ -n` of `ℤ`. -/
def refl0 : Equiv.Perm ℤ := Equiv.neg ℤ

/-- The reflection `n ↦ 1 - n` of `ℤ`. -/
def refl1 : Equiv.Perm ℤ := (Equiv.neg ℤ).trans (Equiv.addLeft (1 : ℤ))

@[simp] theorem refl0_apply (n : ℤ) : refl0 n = -n := rfl

@[simp] theorem refl1_apply (n : ℤ) : refl1 n = 1 + -n := rfl

theorem refl0_mul_self : refl0 * refl0 = 1 := by
  refine Equiv.ext fun n => ?_
  show refl0 (refl0 n) = n
  simp

theorem refl1_mul_self : refl1 * refl1 = 1 := by
  refine Equiv.ext fun n => ?_
  show refl1 (refl1 n) = n
  simp

/-- **The two reflections do not commute**: their commutator translates by `-2`. -/
theorem commutator_refl_ne_one : ⁅refl0, refl1⁆ ≠ 1 := by
  intro h
  have h0 : (⁅refl0, refl1⁆ : Equiv.Perm ℤ) 0 = (1 : Equiv.Perm ℤ) 0 := by rw [h]
  have hval : (⁅refl0, refl1⁆ : Equiv.Perm ℤ) 0 = -2 := by
    show refl0 (refl1 (refl0⁻¹ (refl1⁻¹ 0))) = -2
    have hi0 : refl0⁻¹ = refl0 := inv_eq_of_mul_eq_one_right refl0_mul_self
    have hi1 : refl1⁻¹ = refl1 := inv_eq_of_mul_eq_one_right refl1_mul_self
    rw [hi0, hi1]
    simp
  rw [hval] at h0
  simp at h0

/-! ## The retraction kills every relator but one -/

section Retraction

variable [DecidableEq X] {E : Set (X × X)} {x₀ y₀ : X}

/-- The generator assignment: the two chosen sites go to the two reflections,
every other site to the identity. -/
noncomputable def toDihedral (x₀ y₀ : X) : X → Equiv.Perm ℤ := fun x =>
  if x = x₀ then refl0 else if x = y₀ then refl1 else 1

theorem toDihedral_sq (x : X) : toDihedral x₀ y₀ x * toDihedral x₀ y₀ x = 1 := by
  unfold toDihedral
  split_ifs
  · exact refl0_mul_self
  · exact refl1_mul_self
  · exact one_mul 1

/-- Away from the chosen pair the assignment is trivial, so any prescribed
commuting pair is respected. -/
theorem commute_toDihedral (hne : x₀ ≠ y₀) (h₁ : (x₀, y₀) ∉ E) (h₂ : (y₀, x₀) ∉ E)
    {p : X × X} (hp : p ∈ E) :
    Commute (toDihedral x₀ y₀ p.1) (toDihedral x₀ y₀ p.2) := by
  obtain ⟨u, v⟩ := p
  simp only at hp ⊢
  by_cases hu : u = x₀
  · subst hu
    by_cases hv : v = u
    · subst hv; exact Commute.refl _
    by_cases hv2 : v = y₀
    · exact absurd (by subst hv2; exact hp) h₁
    · have hone : toDihedral u y₀ v = 1 := by unfold toDihedral; simp [hv, hv2]
      rw [hone]; exact Commute.one_right _
  by_cases hu2 : u = y₀
  · subst hu2
    by_cases hv : v = x₀
    · exact absurd (by subst hv; exact hp) h₂
    by_cases hv2 : v = u
    · subst hv2; exact Commute.refl _
    · have hone : toDihedral x₀ u v = 1 := by unfold toDihedral; simp [hv, hv2]
      rw [hone]; exact Commute.one_right _
  · have hone : toDihedral x₀ y₀ u = 1 := by unfold toDihedral; simp [hu, hu2]
    rw [hone]; exact Commute.one_left _

/-- **The retraction.**  A pair of distinct sites that `E` does not make commute
survives to the infinite dihedral group. -/
noncomputable def retract (hne : x₀ ≠ y₀) (h₁ : (x₀, y₀) ∉ E) (h₂ : (y₀, x₀) ∉ E) :
    PartialLamp X E →* Equiv.Perm ℤ := by
  refine PresentedGroup.toGroup (f := toDihedral x₀ y₀) ?_
  rintro r (⟨x, rfl⟩ | ⟨p, hp, rfl⟩)
  · show FreeGroup.lift (toDihedral x₀ y₀) (FreeGroup.of x * FreeGroup.of x) = 1
    rw [map_mul, FreeGroup.lift_apply_of]
    exact toDihedral_sq x
  · show FreeGroup.lift (toDihedral x₀ y₀)
      ⁅FreeGroup.of p.1, FreeGroup.of p.2⁆ = 1
    rw [map_commutatorElement, FreeGroup.lift_apply_of, FreeGroup.lift_apply_of]
    exact commutatorElement_eq_one_iff_commute.mpr (commute_toDihedral hne h₁ h₂ hp)

/-- **The missing commutator is nontrivial.**  In the partial-commutation group,
two distinct sites that `E` does not list do not commute. -/
theorem commutator_ne_one_of_notMem (hne : x₀ ≠ y₀) (h₁ : (x₀, y₀) ∉ E)
    (h₂ : (y₀, x₀) ∉ E) :
    ⁅(PresentedGroup.of x₀ : PartialLamp X E),
      (PresentedGroup.of y₀ : PartialLamp X E)⁆ ≠ 1 := by
  intro hcon
  have hmap := congrArg (retract hne h₁ h₂) hcon
  rw [map_one, map_commutatorElement] at hmap
  have hx : retract hne h₁ h₂ (PresentedGroup.of x₀) = refl0 := by
    show PresentedGroup.toGroup _ (PresentedGroup.of x₀) = refl0
    rw [PresentedGroup.toGroup.of]
    simp [toDihedral]
  have hy : retract hne h₁ h₂ (PresentedGroup.of y₀) = refl1 := by
    show PresentedGroup.toGroup _ (PresentedGroup.of y₀) = refl1
    rw [PresentedGroup.toGroup.of]
    simp [toDihedral, hne.symm]
  rw [hx, hy] at hmap
  exact commutator_refl_ne_one hmap

end Retraction

/-! ## The obstruction criterion -/

section Obstruction

/-- **The criterion.**  A group presented on a *finite* generating set by a
relator family is not finitely presented as soon as every finite subfamily can
be violated: some further relator survives a homomorphism that kills the
subfamily.

This is the mechanism of the non-finite-presentability argument, separated from
any particular family.  The Tietze step supplies the finite subfamily; the
hypothesis supplies the retraction that distinguishes it from the whole; and
`commutator_ne_one_of_notMem` is the retraction in the case the lamp base
needs, where the surviving relator is a commutator of two sites the subfamily
does not make commute. -/
theorem not_isFinitelyPresented_of_violable {α : Type u} [Finite α] {ι : Type*}
    (r : ι → FreeGroup α)
    (hviolable : ∀ s : Set ι, s.Finite → ∃ (i : ι) (H : Type u) (_ : Group H)
      (f : α → H), (∀ j ∈ s, FreeGroup.lift f (r j) = 1) ∧
        FreeGroup.lift f (r i) ≠ 1) :
    ¬ Group.IsFinitelyPresented (PresentedGroup (Set.range r)) := by
  intro hfp
  obtain ⟨s, hsfin, hs⟩ := Tietze.exists_finite_subfamily r
  obtain ⟨i, H, _, f, hkill, hsurvive⟩ := hviolable s hsfin
  refine hsurvive ?_
  have hle : Subgroup.normalClosure (r '' s) ≤ (FreeGroup.lift f).ker := by
    refine Subgroup.normalClosure_le_normal ?_
    rintro _ ⟨j, hj, rfl⟩
    exact hkill j hj
  have hmem : r i ∈ Subgroup.normalClosure (r '' s) := by
    rw [hs]
    exact Subgroup.subset_normalClosure ⟨i, rfl⟩
  exact hle hmem

end Obstruction

end PartialCommutation
end GroupApproximation
