import NonsoficGroupsExist.Endpoint.MainResults
import NonsoficGroupsExist.Endpoint.ManuscriptStatements
import NonsoficGroupsExist.Sofic.SoficSequential
import NonsoficGroupsExist.Sofic.FreeLampReduction
import NonsoficGroupsExist.Sofic.WeakMFTransfer
import NonsoficGroupsExist.Sofic.WeakMFNonsoficDouble
import NonsoficGroupsExist.Sofic.SymmetricDoubleFlip
import NonsoficGroupsExist.Sofic.LineDouble
import NonsoficGroupsExist.Sofic.DoubleSoficTransfer
import NonsoficGroupsExist.Sofic.CentralCoverInheritance
import NonsoficGroupsExist.KOne.ClassicalKOne
import NonsoficGroupsExist.KOne.FactorizationCertificate
import NonsoficGroupsExist.Sofic.FinitelyPresentedLEF
import NonsoficGroupsExist.Leavitt.UnitsGLProfile
import NonsoficGroupsExist.KOne.AllRanksElementary
import NonsoficGroupsExist.Sofic.SoficPositiveControl
import NonsoficGroupsExist.Sofic.ExteriorMFProfile
import NonsoficGroupsExist.Sofic.HyperlinearNonScalar
import NonsoficGroupsExist.Sofic.HyperlinearReduction
import NonsoficGroupsExist.Sofic.HyperlinearUltraproduct
import NonsoficGroupsExist.Sofic.PhasePropagation
import NonsoficGroupsExist.Kun.KunDecomposition
import NonsoficGroupsExist.KunThom.KunThomTheorem
import NonsoficGroupsExist.PropertyT.FreeElementaryPropertyT
import NonsoficGroupsExist.Kazhdan.KazhdanComplex
import NonsoficGroupsExist.Kazhdan.KazhdanUniverse
import NonsoficGroupsExist.Kazhdan.InvariantSubsetRounding
import NonsoficGroupsExist.Kazhdan.DiagonalInvariantRelation
import NonsoficGroupsExist.KOne.RefineLoopDischarge
import NonsoficGroupsExist.Kazhdan.ShalomFinitePresentation
import NonsoficGroupsExist.Covers.KazhdanCover
import NonsoficGroupsExist.Leavitt.FamilyRankFour
import NonsoficGroupsExist.Matching.AsymptoticPartialGroupoid
import NonsoficGroupsExist.Matching.AsymptoticBlockArrow
import NonsoficGroupsExist.Matching.FinitePartialClusterGroupoid
import NonsoficGroupsExist.Matching.PartialEquivarianceBoundary
import NonsoficGroupsExist.Matching.PartialTaggedExpansion
import NonsoficGroupsExist.Matching.EditedGeneratorExpansion
import NonsoficGroupsExist.Matching.ComponentLabelCompletion
import NonsoficGroupsExist.Matching.ComponentCompletedMultiplicativity
import NonsoficGroupsExist.Matching.ComponentCompletedAction
import NonsoficGroupsExist.Matching.ComponentCompletedSofic
import NonsoficGroupsExist.Matching.ComponentClusterScale
import NonsoficGroupsExist.Matching.PartialClusterCandidates
import NonsoficGroupsExist.Matching.PartialEquivarianceComposition
import NonsoficGroupsExist.Matching.PartialClusterPresentation
import NonsoficGroupsExist.Matching.PartialBijectionSwap
import NonsoficGroupsExist.Matching.PartialSwapEquivariance
import NonsoficGroupsExist.Matching.PartialBijectionExtraction
import NonsoficGroupsExist.Matching.ExactPartialKazhdanRepair
import NonsoficGroupsExist.Matching.ExactKazhdanPartialClusterSystem
import NonsoficGroupsExist.Matching.RelationPartialClusterRepair
import NonsoficGroupsExist.Matching.FiniteGroupoidPartialBisection
import NonsoficGroupsExist.Matching.FiniteGroupoidFunctor
import NonsoficGroupsExist.Matching.PartialBijectionSandwich
import NonsoficGroupsExist.Matching.PartialClusterBridgeFunctor
import NonsoficGroupsExist.Sofic.InvolutiveCentralizerComponents
import NonsoficGroupsExist.Leavitt.StrictCentralCoverWitness
import NonsoficGroupsExist.Leavitt.IntegralGeneration
import NonsoficGroupsExist.Leavitt.RawSwapCompressors
import NonsoficGroupsExist.Leavitt.SelfSimilarityAlgebra
import NonsoficGroupsExist.Leavitt.PlaneEmbedding
import NonsoficGroupsExist.Leavitt.GeneralRankWords
import NonsoficGroupsExist.Leavitt.GeneralScheme
import NonsoficGroupsExist.Leavitt.GeneralCornerTheorem
import NonsoficGroupsExist.Sofic.Normalization
import NonsoficGroupsExist.Leavitt.FamilyVEmbedding
import NonsoficGroupsExist.Sofic.FreeGroupResiduallyFinite
import NonsoficGroupsExist.Endpoint.QuotientNonclosure
import NonsoficGroupsExist.Steinberg.Basic
import NonsoficGroupsExist.Steinberg.Perfect
import NonsoficGroupsExist.Steinberg.FinitelyGenerated
import NonsoficGroupsExist.Steinberg.A2System
import NonsoficGroupsExist.Steinberg.A2Kazhdan
import NonsoficGroupsExist.Steinberg.BinaryLeavitt
import NonsoficGroupsExist.Steinberg.FiniteControl
import NonsoficGroupsExist.Steinberg.KervaireSteinberg
import NonsoficGroupsExist.Steinberg.RootFiltration
import NonsoficGroupsExist.Steinberg.RootActions
import NonsoficGroupsExist.Steinberg.RootPlane
import NonsoficGroupsExist.Steinberg.RootPlaneFourier
import NonsoficGroupsExist.Steinberg.RootCharacterValuationBase
import NonsoficGroupsExist.Steinberg.RootCharacterValuation
import NonsoficGroupsExist.Steinberg.FreePropertyT
import NonsoficGroupsExist.Steinberg.Functoriality
import NonsoficGroupsExist.Steinberg.FiniteTypePropertyT

/-!
# Human-readable axiom report

This module pins the axiom reports for the public results and the three most
load-bearing mathematical inputs.  It is imported by the library root, so a
normal `lake build` prints these reports.  The stricter executable gate in
`scripts/Audit.lean` independently traverses the transitive axiom closure of
the entire project namespace and fails on anything beyond classical Lean.
-/

#print axioms NonsoficGroupsExist.nonsofic_groups_exist
#print axioms NonsoficGroupsExist.countable_nonsofic_groups_exist
#print axioms NonsoficGroupsExist.isSofic_iff_admitsEssentiallyFreeNearAction
#print axioms NonsoficGroupsExist.universalLeavittEL4_not_admitsEssentiallyFreeNearAction
#print axioms NonsoficGroupsExist.countable_group_without_essentiallyFreeNearAction_exists
#print axioms NonsoficGroupsExist.universalLeavittEL4_not_isSofic
#print axioms NonsoficGroupsExist.universalLeavittEL3_not_isSofic
#print axioms NonsoficGroupsExist.universalLeavittUnits_not_isSofic
#print axioms NonsoficGroupsExist.universalLeavittGL_not_isSofic
#print axioms NonsoficGroupsExist.ambient_profile
#print axioms NonsoficGroupsExist.ambient_full_profile
#print axioms NonsoficGroupsExist.universalLeavitt_profile
#print axioms NonsoficGroupsExist.binaryLeavitt_finiteField_profile
#print axioms NonsoficGroupsExist.exists_finitelyPresented_nonsofic_group
#print axioms NonsoficGroupsExist.exists_infinite_finitelyPresented_nonsofic_ambient_cover
#print axioms NonsoficGroupsExist.KunDecomposition.exists_expanderDecomposition
#print axioms NonsoficGroupsExist.KunSelectiveRepairExpansion.refined_bad_component_expands_at_every_positive_constant
#print axioms NonsoficGroupsExist.KunThomTheorem.isLEF_of_exactProductExpansion
#print axioms NonsoficGroupsExist.commute_of_perfect_quotient
#print axioms NonsoficGroupsExist.subgroup_eq_top_of_surjects_mod_central
#print axioms NonsoficGroupsExist.CentralExtension.lift_centralizes_perfect_preimage
#print axioms NonsoficGroupsExist.SteinbergGroup.projection_surjective
#print axioms NonsoficGroupsExist.SteinbergGroup.centralExtension
#print axioms NonsoficGroupsExist.SteinbergGroup.fin_isPerfect
#print axioms NonsoficGroupsExist.SteinbergGroup.finitelyGenerated
#print axioms NonsoficGroupsExist.SteinbergGroup.x_injective
#print axioms NonsoficGroupsExist.SteinbergGroup.a2System
#print axioms NonsoficGroupsExist.SteinbergGroup.binaryLeavitt_exists_rootSet_isKazhdan
#print axioms NonsoficGroupsExist.KervaireSteinberg.commutator_commutes_of_commutators_mem_center
#print axioms NonsoficGroupsExist.KervaireSteinberg.commutator_eq_of_eq_mod_center
#print axioms NonsoficGroupsExist.KervaireSteinberg.commutator_eq_of_same_projection
#print axioms NonsoficGroupsExist.KervaireSteinberg.commutator_commutator_eq
#print axioms NonsoficGroupsExist.KervaireSteinberg.lifts_commute_of_spare_index
#print axioms NonsoficGroupsExist.KervaireSteinberg.fin_lifts_commute
#print axioms NonsoficGroupsExist.KervaireSteinberg.projection_correctedRoot
#print axioms NonsoficGroupsExist.KervaireSteinberg.correctedRoot_eq_commutator_of_lifts
#print axioms NonsoficGroupsExist.KervaireSteinberg.fin_correctedRoot_eq_of_middle_ne
#print axioms NonsoficGroupsExist.KervaireSteinberg.fin_correctedRoot_eq
#print axioms NonsoficGroupsExist.KervaireSteinberg.projection_canonicalRoot
#print axioms NonsoficGroupsExist.KervaireSteinberg.canonicalRoot_eq_correctedRoot
#print axioms NonsoficGroupsExist.KervaireSteinberg.fin_canonicalRoot_commute
#print axioms NonsoficGroupsExist.KervaireSteinberg.fin_canonicalRoot_commutator
#print axioms NonsoficGroupsExist.KervaireSteinberg.fin_correctedRoot_mul
#print axioms NonsoficGroupsExist.KervaireSteinberg.fin_canonicalRoot_mul
#print axioms NonsoficGroupsExist.KervaireSteinberg.splittingHom_isSection
#print axioms NonsoficGroupsExist.KervaireSteinberg.every_centralExtension_splits
#print axioms NonsoficGroupsExist.KervaireSteinberg.correctedRoot_zero
#print axioms NonsoficGroupsExist.KervaireSteinberg.fin_correctedRoot_commute
#print axioms NonsoficGroupsExist.BinaryLeavittSteinberg.projection_surjective
#print axioms NonsoficGroupsExist.BinaryLeavittSteinberg.isPerfect
#print axioms NonsoficGroupsExist.BinaryLeavittSteinberg.finitelyGenerated
#print axioms NonsoficGroupsExist.BinaryLeavittSteinberg.elementaryBase_hasKazhdanPropertyT
#print axioms NonsoficGroupsExist.BinaryLeavittSteinberg.elementaryBase_not_isSofic
#print axioms NonsoficGroupsExist.LeavittStrictCentralCoverWitness.witness_strict
#print axioms NonsoficGroupsExist.BinaryLeavittSteinberg.everyCentralExtensionSplits
#print axioms NonsoficGroupsExist.BinaryLeavittSteinberg.rankThree_hasKazhdanPropertyT
#print axioms NonsoficGroupsExist.BinaryLeavittSteinberg.hasKazhdanPropertyT
#print axioms NonsoficGroupsExist.FreeElementaryPropertyT.freeElementary_hasKazhdanPropertyT
#print axioms NonsoficGroupsExist.UniversalRankFour.witness_not_isLEF
#print axioms NonsoficGroupsExist.ThompsonFObstruction.finite_image_generatorCommutator_eq_one
#print axioms NonsoficGroupsExist.isSofic_of_finite
#print axioms NonsoficGroupsExist.isSofic_semidirectProduct_of_finite
#print axioms NonsoficGroupsExist.freeLampMulEquivSymmetricDoubleFlip
#print axioms NonsoficGroupsExist.doubleToLine_injective
#print axioms NonsoficGroupsExist.isSofic_freeLamp_flip_of_isSofic_lineDouble
#print axioms NonsoficGroupsExist.not_isSofic_lineDouble_of_not_isSofic_freeLamp_flip
#print axioms NonsoficGroupsExist.isSofic_multiplicative_int
#print axioms NonsoficGroupsExist.isSofic_iff_productRestricted
#print axioms NonsoficGroupsExist.isSofic_of_soficApproximation
#print axioms NonsoficGroupsExist.isSofic_iff_nonempty_soficApproximation
#print axioms NonsoficGroupsExist.isLEF_of_finite
#print axioms NonsoficGroupsExist.isLEF_multiplicative_int
#print axioms NonsoficGroupsExist.isLEF_iff_textbook
#print axioms NonsoficGroupsExist.isKazhdanPair_iff_complex
#print axioms NonsoficGroupsExist.hasKazhdanPropertyT_iff_complex
#print axioms NonsoficGroupsExist.IsKazhdanPair.liftUniverse
#print axioms NonsoficGroupsExist.HasKazhdanPropertyT.liftUniverse
#print axioms NonsoficGroupsExist.IsKazhdanPair.lowerUniverse
#print axioms NonsoficGroupsExist.hasKazhdanPropertyT_universe_iff
#print axioms NonsoficGroupsExist.hasKazhdanPropertyT_iff_textbook

-- The unconditional K₁-vanishing chain (session 54): narrow reduction,
-- scalar reduction, checkpoint B4, GL = EL, and the Whitehead-form
-- headline.  All must report only the three standard axioms.
#print axioms NonsoficGroupsExist.BinaryLeavitt.narrowReduction_holds
#print axioms NonsoficGroupsExist.BinaryLeavitt.scalarReduction_holds
#print axioms NonsoficGroupsExist.BinaryLeavitt.stableUnits_eq_top_holds
#print axioms NonsoficGroupsExist.BinaryLeavitt.glTwo_eq_elementary_holds
#print axioms NonsoficGroupsExist.BinaryLeavitt.glFour_eq_elementary_holds

-- The exact manuscript endpoints: one declaration per printed headline
-- statement, so the report records what each printed theorem rests on.
#print axioms NonsoficGroupsExist.Manuscript.theoremA_exact
#print axioms NonsoficGroupsExist.Manuscript.theoremB_exact
#print axioms NonsoficGroupsExist.Manuscript.theoremC_exact
#print axioms NonsoficGroupsExist.Manuscript.theoremC_covers_theoremB_groups
#print axioms NonsoficGroupsExist.Manuscript.theoremD_subgroups
#print axioms NonsoficGroupsExist.Manuscript.cor_fgring_printed
#print axioms NonsoficGroupsExist.Manuscript.cor_fgring_exact
#print axioms NonsoficGroupsExist.Manuscript.cor_fgring_countableFree
#print axioms NonsoficGroupsExist.binaryLeavittWhiteheadK1_subsingleton
#print axioms NonsoficGroupsExist.binaryLeavittElementaryColim_eq_top
#print axioms NonsoficGroupsExist.binaryLeavittClassicalK1_subsingleton
#print axioms NonsoficGroupsExist.BinaryLeavitt.exists_elementaryCertificate
#print axioms NonsoficGroupsExist.BinaryLeavitt.exists_moveList
#print axioms NonsoficGroupsExist.BinaryLeavitt.Move.eval_mem_stableUnits
#print axioms NonsoficGroupsExist.BinaryLeavitt.K1_trivial

-- The unit-group and general-linear profiles (Theorem B(i) closed): finite
-- generation, infinitude, property (T), and nonsoficity of `L_k(1,2)ˣ` and
-- of every positive-rank `GL_r` over every finite field.
#print axioms NonsoficGroupsExist.binaryLeavittUnits_profile
#print axioms NonsoficGroupsExist.binaryLeavittGL_profile

-- Theorem C's Kazhdan half, proved internally and included explicitly in the
-- public axiom report.
#print axioms NonsoficGroupsExist.Shalom.exists_presented_kazhdan_cover
#print axioms NonsoficGroupsExist.Shalom.exists_finitelyPresented_kazhdan_cover
#print axioms NonsoficGroupsExist.exists_kazhdan_finitelyPresented_cover_of_not_isSofic

-- All-ranks collapse, perfectness, and the rank-two compression over
-- `L_k(1,2)`: `GL_n = EL_n` for every `n ≥ 2` over every field, the unit
-- group is perfect, and the two-by-two Leavitt-corner theorem closes over
-- every finite field.
#print axioms NonsoficGroupsExist.BinaryLeavitt.elementaryGroup_eq_top
#print axioms NonsoficGroupsExist.BinaryLeavitt.glAll_eq_elementary
#print axioms NonsoficGroupsExist.BinaryLeavitt.binaryLeavittUnits_perfect
#print axioms NonsoficGroupsExist.binaryLeavittRankTwo_not_isSofic

-- The coefficient ring in the explicit Steinberg endpoint has an absolute
-- associative-ring presentation: four generators, the five Leavitt
-- equations, and the characteristic-two equation.  The equivalence is
-- constructed in both directions rather than assumed.
#print axioms NonsoficGroupsExist.BinaryLeavittAbsolute.ringEquiv

-- `lem:fplef`, closed: finitely presented LEF groups are residually finite.
#print axioms NonsoficGroupsExist.finitelyPresented_isLEF_residuallyFinite

-- `cor:fgring` at the generality the corollary is stated in: any nontrivial
-- countable finite-type algebra over a finite field carrying a binary Leavitt
-- family.  The manuscript's margin note names these, so an ordinary build
-- reports their axioms rather than leaving them to the whole-namespace scan.
#print axioms NonsoficGroupsExist.FamilyRankFour.ambient_not_isSofic
#print axioms NonsoficGroupsExist.FamilyRankFour.elementary_not_isSofic
#print axioms NonsoficGroupsExist.FamilyRankFour.units_not_isSofic
#print axioms NonsoficGroupsExist.FamilyRankFour.gl_not_isSofic

-- `thm:corner` at every adjacent pair `(m, m + 1)` with `m ≥ 2`, at the
-- printed hypotheses, and its characteristic-two discharge of the
-- membership hypothesis (ii).
#print axioms NonsoficGroupsExist.GeneralCornerTheorem.corner_not_isSofic
#print axioms NonsoficGroupsExist.GeneralCornerTheorem.corner_not_isSofic_of_charTwo

-- `lem:normalization`: the inverse-compatible normalization of a sofic
-- approximation is constructed, not just estimated.
#print axioms NonsoficGroupsExist.SoficApproximation.exists_normalization

-- `prop:vembed`: Thompson's `V` embeds into the unit group of any
-- nontrivial ring carrying a binary Leavitt family, with `eq:Ug` on tables.
#print axioms NonsoficGroupsExist.LeavittFamily.vEmbeddingOfFamily_injective
#print axioms NonsoficGroupsExist.LeavittFamily.vEmbeddingOfFamily_tableEquiv

-- `rem:quotients`: free groups are residually finite, and none of the
-- classes of sofic, LEF, or residually finite groups is closed under
-- quotients.
#print axioms NonsoficGroupsExist.freeGroup_residuallyFinite
#print axioms NonsoficGroupsExist.isSofic_freeGroup
#print axioms NonsoficGroupsExist.exists_sofic_group_with_nonsofic_quotient
#print axioms NonsoficGroupsExist.exists_isLEF_group_with_non_isLEF_quotient
#print axioms NonsoficGroupsExist.exists_residuallyFinite_group_with_non_residuallyFinite_quotient

-- Internally proved operator-norm MF transfer mechanisms.
#print axioms NonsoficGroupsExist.isWeakMF_of_injective
#print axioms NonsoficGroupsExist.isWeakMF_of_residuallyFinite

-- Cluster-groupoid carrier: composition and negligible-disagreement setoid
-- are derived from concrete finite partial bijections.
#print axioms NonsoficGroupsExist.FinitePartialBijection.sourceDefect_trans_le
#print axioms NonsoficGroupsExist.FinitePartialBijection.trans_assoc
#print axioms NonsoficGroupsExist.AsymptoticPartialBijection.near_trans
#print axioms NonsoficGroupsExist.AsymptoticPartialBijection.trans_assoc
#print axioms NonsoficGroupsExist.asymptoticPartialGroupoidPresentation
#print axioms NonsoficGroupsExist.ExpanderDecomposition.refinementAsymptoticPartialBijection
#print axioms NonsoficGroupsExist.FiniteGroupoid.fullOfFaithfulOfCardinalPreserving
#print axioms NonsoficGroupsExist.GroupoidPresentation.homFintype
#print axioms NonsoficGroupsExist.FiniteGroupoid.pullbackBisectionOfCardinalPreserving
#print axioms NonsoficGroupsExist.FinitePartialClusterData.presentation
#print axioms NonsoficGroupsExist.FinitePartialBijection.agreement_or_disagreement_small
#print axioms NonsoficGroupsExist.FinitePartialBijection.twoSidedDisagreement_lt_two_mul_or_eight_radius_le
#print axioms NonsoficGroupsExist.hasTaggedExpansionAtScale_of_hasDirectedExpansionAtScale
#print axioms NonsoficGroupsExist.hasTaggedExpansionAtScale_of_editDistance
#print axioms NonsoficGroupsExist.ExpanderDecomposition.componentCompletedAction_taggedExpansion
#print axioms NonsoficGroupsExist.ExpanderDecomposition.componentCompletedAction_disagreement_sum_negligible
#print axioms NonsoficGroupsExist.ExpanderDecomposition.componentMultiplicationError_sum_negligible
#print axioms NonsoficGroupsExist.ExpanderDecomposition.componentIdentityError_sum_negligible
#print axioms NonsoficGroupsExist.ExpanderDecomposition.completedComponentEquiv
#print axioms NonsoficGroupsExist.ExpanderDecomposition.completedComponentPerm_multiplicationError_negligible
#print axioms NonsoficGroupsExist.ExpanderDecomposition.completedComponentPerm_identityError_negligible
#print axioms NonsoficGroupsExist.ExpanderDecomposition.completedAmbientPerm_disagreement_negligible
#print axioms NonsoficGroupsExist.ExpanderDecomposition.completedSoficApproximation
#print axioms NonsoficGroupsExist.ExpanderDecomposition.completedComponentSoficApproximation
#print axioms NonsoficGroupsExist.ExpanderDecomposition.componentLabelEditBudget_sum_negligible
#print axioms NonsoficGroupsExist.ExpanderDecomposition.badClusterComponentMass_negligible
#print axioms NonsoficGroupsExist.FinitePartialBijection.IsClusterCandidate.gap
#print axioms NonsoficGroupsExist.FinitePartialBijection.card_mul_sourceDefect_le_card_equivarianceDefect
#print axioms NonsoficGroupsExist.FinitePartialBijection.card_mul_targetDefect_le_card_symm_equivarianceDefect
#print axioms NonsoficGroupsExist.FinitePartialBijection.IsClusterCandidate.sourceDefect_lt_scale
#print axioms NonsoficGroupsExist.FinitePartialBijection.IsClusterCandidate.targetDefect_lt_scale
#print axioms NonsoficGroupsExist.FinitePartialBijection.card_equivarianceDefect_trans_le
#print axioms NonsoficGroupsExist.FinitePartialBijection.graph_ofBiuniqueRelation
#print axioms NonsoficGroupsExist.FinitePartialBijection.source_eq_univ_of_graph_mapsTo_of_transitive
#print axioms NonsoficGroupsExist.FinitePartialBijection.target_eq_univ_of_graph_mapsTo_of_transitive
#print axioms NonsoficGroupsExist.FinitePartialBijection.apply_action_eq_of_graph_mapsTo
#print axioms NonsoficGroupsExist.PartialClusterSystem.presentation
#print axioms NonsoficGroupsExist.FinitePartialBijection.card_swapEquivarianceDefect_le
#print axioms NonsoficGroupsExist.FinitePartialBijection.card_extractCrossing_equivarianceDefect_le
#print axioms NonsoficGroupsExist.FinitePartialBijection.card_extractCrossing_symm_equivarianceDefect_le
#print axioms NonsoficGroupsExist.FinitePartialBijection.isClusterCandidate_extractCrossing_of_bounds
#print axioms NonsoficGroupsExist.FinitePartialBijection.card_sumCommutationDefect_le_card_mul_badArcs
#print axioms NonsoficGroupsExist.FinitePartialBijection.extractCrossing_swapPerm
#print axioms NonsoficGroupsExist.FinitePartialBijection.sourceDefect_extractCrossing_le
#print axioms NonsoficGroupsExist.FinitePartialBijection.targetDefect_extractCrossing_le
#print axioms NonsoficGroupsExist.FinitePartialBijection.twoSidedDisagreement_extractCrossing_le_self_add_two_mul
#print axioms NonsoficGroupsExist.ExpanderDecomposition.repairedComponentBisection
#print axioms NonsoficGroupsExist.ExpanderDecomposition.normalizedCentralizer_componentBisection

-- Exact finite Kazhdan rounding: invariant projection followed by thresholding
-- produces an exactly invariant subset, quantitatively controlled by its
-- labelled boundary.
#print axioms NonsoficGroupsExist.KazhdanInvariantRounding.roundedInvariantSet_map
#print axioms NonsoficGroupsExist.KazhdanInvariantRounding.card_symmDiff_roundedInvariantSet_le
#print axioms NonsoficGroupsExist.KazhdanInvariantRounding.kazhdan_mul_card_symmDiff_rounded_le_boundary
#print axioms NonsoficGroupsExist.DiagonalInvariantRelation.roundedDiagonalRelation_map
#print axioms NonsoficGroupsExist.DiagonalInvariantRelation.mem_roundedDiagonalRelation_map_iff
#print axioms NonsoficGroupsExist.DiagonalInvariantRelation.rowDegree_roundedDiagonalRelation_eq
#print axioms NonsoficGroupsExist.DiagonalInvariantRelation.columnDegree_roundedDiagonalRelation_eq
#print axioms NonsoficGroupsExist.DiagonalInvariantRelation.relationCore_roundedDiagonalRelation_mapsTo
#print axioms NonsoficGroupsExist.DiagonalInvariantRelation.kazhdan_mul_card_graph_symmDiff_rounded_le_defect
#print axioms NonsoficGroupsExist.DiagonalInvariantRelation.relationBoundary_roundedDiagonalRelation_eq_empty
#print axioms NonsoficGroupsExist.DiagonalInvariantRelation.card_badArcs_roundedDiagonalPermutation_le
#print axioms NonsoficGroupsExist.DiagonalInvariantRelation.card_hammingDisagreement_roundedDiagonalPermutation_le
#print axioms NonsoficGroupsExist.DiagonalInvariantRelation.kazhdan_mul_card_badArcs_roundedDiagonalPermutation_le
#print axioms NonsoficGroupsExist.DiagonalInvariantRelation.kazhdan_mul_card_hammingDisagreement_roundedDiagonalPermutation_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.kazhdan_mul_twoSidedDisagreement_repair_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.sourceDefect_repair_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.targetDefect_repair_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.missingMass_repair_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.kazhdan_mul_missingMass_repair_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.kazhdan_mul_card_badArcs_repairedSwap_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.totalCommutationDefect_swap_le_partialTotalDefect
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.kazhdan_mul_twoSidedDisagreement_repair_le_partialDefect
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.card_taggedSumCommutationDefect_le_card_mul_badArcs
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.kazhdan_mul_card_taggedSumCommutationDefect_repaired_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.kazhdan_mul_card_taggedSumCommutationDefect_repaired_inv_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.kazhdan_mul_sourceDefect_repair_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.kazhdan_mul_targetDefect_repair_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.repair_isClusterCandidate_and_close_of_bounds
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.graph_coreCrossing
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.exactCoreRepair_graph_mapsTo
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.exactCoreRepair_source_target_eq_univ_of_transitive
#print axioms NonsoficGroupsExist.KazhdanImprovement.card_missingSources_relationCore_le_three_edits
#print axioms NonsoficGroupsExist.KazhdanImprovement.card_sdiff_add_card_sdiff_eq_symmDiff
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.exactCoreRepair_source_nonempty_of_three_mul_edits_lt
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.exactCoreRepair_source_target_eq_univ_of_kazhdan
#print axioms NonsoficGroupsExist.FinitePartialBijection.symm_graph_mapsTo_of_graph_mapsTo
#print axioms NonsoficGroupsExist.FinitePartialBijection.equivarianceDefect_eq_empty_of_graph_mapsTo_of_source_eq_univ
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.exactCoreRepair_equivarianceDefect_eq_empty
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.exactCoreRepair_symm_equivarianceDefect_eq_empty
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.exactCoreRepair_isClusterCandidate_of_source_target_eq_univ
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.card_disagreement_exactCoreRepair_le_core_edits
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.card_symm_disagreement_exactCoreRepair_le_core_edits
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.twoSidedDisagreement_exactCoreRepair_le_six_mul_edits
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.kazhdan_mul_twoSidedDisagreement_exactCoreRepair_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.twoSidedDisagreement_exactCoreRepair_lt_two_mul_of_kazhdan
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.exactCoreRepair_candidate_and_close_of_kazhdan
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.card_taggedEquivarianceDefect_eq_sum_singleton
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.partialTotalDefect_eq_tagged
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.partialTotalDefect_trans_le
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.partialTotalDefect_trans_lt_two_mul
#print axioms NonsoficGroupsExist.ExactPartialKazhdanRepair.exactCoreRepair_trans_candidate_and_close
#print axioms NonsoficGroupsExist.PartialClusterSystem.ofExactTransitiveKazhdanActions
#print axioms NonsoficGroupsExist.PartialClusterSystem.exactKazhdanPresentation
#print axioms NonsoficGroupsExist.RelationPartialClusterRepair.card_hammingDisagreement_repair_le
#print axioms NonsoficGroupsExist.RelationPartialClusterRepair.card_badArcs_repair_le
#print axioms NonsoficGroupsExist.RelationPartialClusterRepair.repair_candidate_and_close_of_bounds
#print axioms NonsoficGroupsExist.PartialClusterSystem.ofRelationRepairs
#print axioms NonsoficGroupsExist.FiniteGroupoid.PartialBisection.completionObjEquiv_apply_of_mem
#print axioms NonsoficGroupsExist.FiniteGroupoid.PartialBisection.complete
#print axioms NonsoficGroupsExist.FiniteGroupoid.PartialBisection.complete_hom_of_mem
#print axioms NonsoficGroupsExist.FiniteGroupoid.partialPullbackBisectionOfCardinalPreserving
#print axioms NonsoficGroupsExist.FiniteGroupoid.completePartialPullbackBisectionOfCardinalPreserving
#print axioms NonsoficGroupsExist.GroupoidPresentation.FunctorData.toFunctor
#print axioms NonsoficGroupsExist.GroupoidPresentation.FunctorData.faithful
#print axioms NonsoficGroupsExist.FinitePartialBijection.twoSidedDisagreement_sandwich_le
#print axioms NonsoficGroupsExist.FinitePartialBijection.twoSidedDisagreement_sandwich_trans_le
#print axioms NonsoficGroupsExist.FinitePartialBijection.twoSidedDisagreement_sandwich_roundtrip_le
#print axioms NonsoficGroupsExist.PartialClusterBridgeData.map_respects
#print axioms NonsoficGroupsExist.PartialClusterBridgeData.map_comp
#print axioms NonsoficGroupsExist.PartialClusterBridgeData.map_reflects
#print axioms NonsoficGroupsExist.PartialClusterBridgeData.toFunctorData
#print axioms NonsoficGroupsExist.PartialClusterBridgeData.faithful
