import GroupApproximation.PropertyT.FinitelyGeneratedRing
import GroupApproximation.PropertyT.IntegralColumnPlaneClosure
import GroupApproximation.Kazhdan.KazhdanFiniteGeneration
import GroupApproximation.Manuscript.OneSidedMFRadical.FullDefectRingDescent
import GroupApproximation.Manuscript.OneSidedMFRadical.RankFourEJZInstance
import GroupApproximation.Meta.AxiomGuard

/-!
# The two citation-backed sentences of the headline proof, and the corollary's

`non_mf_groups_exist.tex`, proof of Theorem `thm:headline` (lines 1128--1130):

> The ring `R` is finitely generated, so `H` has property~\textup{(T)}
> by~\cite[Theorem~1.1]{EJZ}, and hence is finitely
> generated~\cite[Theorem~1.3.1]{BHV}.

and the proof of Corollary `cor:one-sided-ring-maximal` (lines 1041--1044):

> Choose `s, t ∈ R` with `ts = 1 ≠ st`, and let `S` be the unital subring they
> generate.  Let `u` and `L = EL₃(S)` be as in Lemma `lem:ring-compression-cell`
> for `S`; then `L` has property~\textup{(T)}~\cite[Theorem~1.1]{EJZ} ...

Both citations are **proved** in this repository, so neither is an input here:

* Ershov--Jaikin-Zapirain is
  `IntegralColumnPlaneClosure.finitelyGeneratedRingGeneralRankElementaryPropertyT`
  --- property `(T)` for `EL_n(A)`, every `n ≥ 3`, over every finitely
  generated unital ring, in every characteristic;
* Bekka--de la Harpe--Valette, Theorem 1.3.1 is
  `KazhdanFiniteGeneration.fg_of_hasKazhdanPropertyT` --- a group with property
  `(T)` is finitely generated, by the coset-`ℓ²` argument.

## What this module adds

The two printed hypotheses, in the **printed vocabulary**, and the printed
inferences drawn from them with no binder left standing.

* `IsFinitelyGeneratedRing` is the manuscript's phrase "the ring `R` is
  finitely generated"; the rank-four development states the same hypothesis as
  `Algebra.FiniteType (ZMod 2) R` (`RankFourEndpoint.coefficientRing_finiteType`).
  `isFinitelyGeneratedRing_binaryLeavitt` supplies the printed phrase itself,
  and does so over **every** base field that is finitely generated as a ring,
  not only `𝔽₂`.
* The base-field hypothesis there is not removable.  `L_k(1,2)` contains `k`,
  so it is a finitely generated ring only when `k` is one: over `k = ℚ` the
  statement is false.  Every finite field, and every prime field, qualifies.
* `manuscriptSentence_pairSubringElementaryPropertyT` closes the corollary's
  own property-`(T)` sentence outright.  The subring generated by a pair is
  finitely generated (`FullDefectRing.isFinitelyGeneratedRing_subringClosure` at
  the two-element finset), and Ershov--Jaikin-Zapirain then applies at rank
  three with nothing assumed --- not even `ts = 1`, which the printed sentence
  has in hand but which the property-`(T)` conclusion does not use.
-/

namespace GroupApproximation
namespace Manuscript
namespace NonMFSentences
namespace HeadlineCitationSentences

open OneSidedMFRadical

/-! ### "The ring `R` is finitely generated" -/

/-- **`L_k(1,2)` is a finitely generated ring**, for every base field that is
itself finitely generated as a ring.

The generators are `s₀, s₁, t₀, t₁` together with generators of `k`; the proof
routes through `Algebra.FiniteType ℤ`, over which the printed notion and
Mathlib's are the same (`isFinitelyGeneratedRing_iff_finiteType_int`), and the
`k`-algebra of `L_k(1,2)` is of finite type by its presentation. -/
theorem isFinitelyGeneratedRing_binaryLeavitt (k : Type) [Field k]
    (hk : IsFinitelyGeneratedRing k) :
    IsFinitelyGeneratedRing (BinaryLeavitt.BinaryLeavittAlgebra k) := by
  rw [isFinitelyGeneratedRing_iff_finiteType_int] at hk ⊢
  exact Algebra.FiniteType.trans hk inferInstance

/-- **The printed hypothesis at the manuscript's ring**: `R = L_{𝔽₂}(1,2)` is a
finitely generated ring, in the printed sense. -/
theorem isFinitelyGeneratedRing_coefficientRing :
    IsFinitelyGeneratedRing RankFourEndpoint.R :=
  isFinitelyGeneratedRing_binaryLeavitt (ZMod 2) (isFinitelyGeneratedRing_zmod 2)

/-! ### "so `H` has property (T) by [EJZ, Theorem 1.1]" -/

/-- **Printed:** "The ring `R` is finitely generated, so `H` has
property~\textup{(T)} by~\cite[Theorem~1.1]{EJZ}."

Both clauses, in the printed vocabulary, at `H = EL₄(R)`. -/
def PrintedFinitelyGeneratedGivesPropertyT : Prop :=
  IsFinitelyGeneratedRing RankFourEndpoint.R ∧
    HasKazhdanPropertyT.{0, 0} RankFourEndpoint.H

/-- Closed proof of the printed sentence.  The implication is the formalized
Ershov--Jaikin-Zapirain theorem at rank four, not a citation. -/
theorem manuscriptSentence_finitelyGeneratedGivesPropertyT :
    PrintedFinitelyGeneratedGivesPropertyT :=
  ⟨isFinitelyGeneratedRing_coefficientRing,
    IntegralColumnPlaneClosure.finitelyGeneratedRingGeneralRankElementaryPropertyT
      RankFourEndpoint.R isFinitelyGeneratedRing_coefficientRing 4 (by norm_num)⟩

/-! ### "and hence is finitely generated [BHV, Theorem 1.3.1]" -/

/-- **Printed:** "and hence is finitely generated~\cite[Theorem~1.3.1]{BHV}."

The printed inference itself: property `(T)` implies finite generation, for
every group.  This is Bekka--de la Harpe--Valette Theorem 1.3.1, and it is
proved in this repository rather than assumed. -/
def PrintedPropertyTGivesFinitelyGenerated : Prop :=
  ∀ (G : Type) [Group G], HasKazhdanPropertyT.{0, 0} G → Group.FG G

/-- Closed proof of the printed implication. -/
theorem manuscriptSentence_propertyTGivesFinitelyGenerated :
    PrintedPropertyTGivesFinitelyGenerated := by
  intro G _ hT
  exact KazhdanFiniteGeneration.fg_of_hasKazhdanPropertyT G hT

/-- The printed inference drawn at the printed group: `H` is finitely
generated **because** it has property `(T)`.

`RankFourEndpoint.finitelyGenerated` proves the same conclusion by a different
and independent route, direct generation by the elementary matrices; this is
the printed route, with both of its steps proved. -/
theorem headlineGroup_finitelyGenerated_via_propertyT :
    Group.FG RankFourEndpoint.H :=
  manuscriptSentence_propertyTGivesFinitelyGenerated RankFourEndpoint.H
    manuscriptSentence_finitelyGeneratedGivesPropertyT.2

/-! ### The corollary: the subring generated by the pair -/

/-- **The subring generated by two elements is a finitely generated ring.**

`FullDefectRing.isFinitelyGeneratedRing_subringClosure` at the two-element
finset; the statement is phrased with a `Set` literal so that no
`DecidableEq` hypothesis appears. -/
theorem isFinitelyGeneratedRing_pairSubring {A : Type*} [Ring A] (s t : A) :
    IsFinitelyGeneratedRing ↥(Subring.closure ({s, t} : Set A)) := by
  classical
  have hcoe : ((({s, t} : Finset A) : Set A)) = ({s, t} : Set A) := by simp
  have h := FullDefectRing.isFinitelyGeneratedRing_subringClosure
    ({s, t} : Finset A)
  rwa [hcoe] at h

/-- **Printed:** "let `S` be the unital subring they generate.  Let `u` and
`L = EL₃(S)` be as in Lemma `lem:ring-compression-cell` for `S`; then `L` has
property~\textup{(T)}~\cite[Theorem~1.1]{EJZ}."

The printed `S` is `Subring.closure {s, t}`, and the property-`(T)` clause is
the formalized Ershov--Jaikin-Zapirain theorem at rank three over it.  The
printed context also has `ts = 1 ≠ st`; neither equation is needed for this
conclusion, so neither appears. -/
def PrintedPairSubringElementaryPropertyT : Prop :=
  ∀ (A : Type) [Ring A] (s t : A),
    IsFinitelyGeneratedRing ↥(Subring.closure ({s, t} : Set A)) ∧
      HasKazhdanPropertyT.{0, 0}
        (elementaryGroup (Fin 3) ↥(Subring.closure ({s, t} : Set A)))

/-- Closed proof of the corollary's property-`(T)` sentence. -/
theorem manuscriptSentence_pairSubringElementaryPropertyT :
    PrintedPairSubringElementaryPropertyT := by
  intro A _ s t
  refine ⟨isFinitelyGeneratedRing_pairSubring s t, ?_⟩
  exact IntegralColumnPlaneClosure.finitelyGeneratedRingGeneralRankElementaryPropertyT
    ↥(Subring.closure ({s, t} : Set A)) (isFinitelyGeneratedRing_pairSubring s t)
    3 le_rfl

end HeadlineCitationSentences
end NonMFSentences
end Manuscript
end GroupApproximation

/-! ### Axiom audit -/

#audit_axioms
  GroupApproximation.Manuscript.NonMFSentences.HeadlineCitationSentences.isFinitelyGeneratedRing_binaryLeavitt
#audit_closed_axioms
  GroupApproximation.Manuscript.NonMFSentences.HeadlineCitationSentences.manuscriptSentence_finitelyGeneratedGivesPropertyT
#audit_closed_axioms
  GroupApproximation.Manuscript.NonMFSentences.HeadlineCitationSentences.manuscriptSentence_propertyTGivesFinitelyGenerated
#audit_closed_axioms
  GroupApproximation.Manuscript.NonMFSentences.HeadlineCitationSentences.headlineGroup_finitelyGenerated_via_propertyT
#audit_closed_axioms
  GroupApproximation.Manuscript.NonMFSentences.HeadlineCitationSentences.manuscriptSentence_pairSubringElementaryPropertyT
