import GroupApproximation.Analysis.NormMatrixCorona
import GroupApproximation.Sofic.MarkedCompressionGroup
import GroupApproximation.Monsters.AffineSL3Doubling
import Mathlib.Topology.Sequences

/-!
# Introduction conventions: bounded products, the witness `W`, commutators

Three definition sentences of the Introduction of `non_mf_groups_exist.tex` had no carrier
in the census.  None of them sits in a labelled environment.

* tex line 112, census key `be1769283b2f`:
  "Here and below, products of $C^*$-algebras mean bounded products, and
  $\bigoplus$ denotes the ideal of norm-null sequences."
* tex line 134, census key `651e122a919e`, completing the display
  `W=\operatorname{Cl}(X)\rtimes V`:
  "where $V$ is the ascending HNN extension of
  $\mathbb Z^3\rtimes\mathrm{SL}_3(\mathbb Z)$ along $(v,A)\mapsto(2v,A)$, the set $X$ is the
  coset space of $\mathbb Z^3\rtimes\mathrm{SL}_3(\mathbb Z)$ in $V$, and
  $\operatorname{Cl}(X)$ is generated by involutions $c_x$, $x\in X$, and a central involution
  $\varepsilon$, with $[c_x,c_y]=\varepsilon$ for $x\ne y$."
* tex line 156, census key `ec81a8c16b64`:
  "We use the group commutator convention $[g,h]=ghg^{-1}h^{-1}$."

Each is a named proposition with a closed proof.
-/

namespace GroupApproximation
namespace Manuscript
namespace NonMFSentences
namespace IntroConventionSentences

open scoped commutatorElement

universe u v

noncomputable section

/-! ## tex line 112, `be1769283b2f`: bounded products and norm-null sequences -/

section BoundedProducts

open Filter
open scoped Matrix.Norms.L2Operator ENNReal

/-- `⨁_n A_n` inside the bounded product `∏_n A_n = lp A ∞`: the sequences whose norms tend
to zero. -/
def normNullSequences (A : ℕ → Type u) [∀ n, NormedAddCommGroup (A n)] : Set (lp A ∞) :=
  {a | Tendsto (fun n ↦ ‖a n‖) cofinite (nhds 0)}

section NormNull

variable (A : ℕ → Type u) [∀ n, NonUnitalNormedRing (A n)]

theorem zero_mem_normNullSequences : (0 : lp A ∞) ∈ normNullSequences A := by
  have heq : (fun n ↦ ‖(0 : lp A ∞) n‖) = fun _ ↦ (0 : ℝ) := by
    funext n
    simp
  show Tendsto (fun n ↦ ‖(0 : lp A ∞) n‖) cofinite (nhds 0)
  rw [heq]
  exact tendsto_const_nhds

theorem add_mem_normNullSequences {a b : lp A ∞} (ha : a ∈ normNullSequences A)
    (hb : b ∈ normNullSequences A) : a + b ∈ normNullSequences A := by
  have ha' : Tendsto (fun n ↦ ‖a n‖) cofinite (nhds 0) := ha
  have hb' : Tendsto (fun n ↦ ‖b n‖) cofinite (nhds 0) := hb
  have hlim : Tendsto (fun n ↦ ‖a n‖ + ‖b n‖) cofinite (nhds 0) := by
    have h := ha'.add hb'
    rwa [add_zero] at h
  show Tendsto (fun n ↦ ‖(a + b) n‖) cofinite (nhds 0)
  refine squeeze_zero' (Eventually.of_forall fun n ↦ norm_nonneg ((a + b) n))
    (Eventually.of_forall fun n ↦ ?_) hlim
  exact norm_add_le (a n) (b n)

theorem neg_mem_normNullSequences {a : lp A ∞} (ha : a ∈ normNullSequences A) :
    -a ∈ normNullSequences A := by
  have ha' : Tendsto (fun n ↦ ‖a n‖) cofinite (nhds 0) := ha
  have heq : (fun n ↦ ‖(-a) n‖) = fun n ↦ ‖a n‖ := by
    funext n
    simp
  show Tendsto (fun n ↦ ‖(-a) n‖) cofinite (nhds 0)
  rw [heq]
  exact ha'

theorem mul_left_mem_normNullSequences (b : lp A ∞) {a : lp A ∞}
    (ha : a ∈ normNullSequences A) : b * a ∈ normNullSequences A := by
  have ha' : Tendsto (fun n ↦ ‖a n‖) cofinite (nhds 0) := ha
  have hlim : Tendsto (fun n ↦ ‖b‖ * ‖a n‖) cofinite (nhds 0) := by
    have h := (tendsto_const_nhds : Tendsto (fun _ : ℕ ↦ ‖b‖) cofinite (nhds ‖b‖)).mul ha'
    rwa [mul_zero] at h
  show Tendsto (fun n ↦ ‖(b * a) n‖) cofinite (nhds 0)
  refine squeeze_zero' (Eventually.of_forall fun n ↦ norm_nonneg ((b * a) n))
    (Eventually.of_forall fun n ↦ ?_) hlim
  exact (norm_mul_le (b n) (a n)).trans
    (mul_le_mul_of_nonneg_right (lp.norm_apply_le_norm ENNReal.top_ne_zero b n)
      (norm_nonneg _))

theorem mul_right_mem_normNullSequences {a : lp A ∞} (ha : a ∈ normNullSequences A)
    (b : lp A ∞) : a * b ∈ normNullSequences A := by
  have ha' : Tendsto (fun n ↦ ‖a n‖) cofinite (nhds 0) := ha
  have hlim : Tendsto (fun n ↦ ‖a n‖ * ‖b‖) cofinite (nhds 0) := by
    have h := ha'.mul (tendsto_const_nhds : Tendsto (fun _ : ℕ ↦ ‖b‖) cofinite (nhds ‖b‖))
    rwa [zero_mul] at h
  show Tendsto (fun n ↦ ‖(a * b) n‖) cofinite (nhds 0)
  refine squeeze_zero' (Eventually.of_forall fun n ↦ norm_nonneg ((a * b) n))
    (Eventually.of_forall fun n ↦ ?_) hlim
  exact (norm_mul_le (a n) (b n)).trans
    (mul_le_mul_of_nonneg_left (lp.norm_apply_le_norm ENNReal.top_ne_zero b n)
      (norm_nonneg _))

theorem star_mem_normNullSequences [∀ n, StarRing (A n)] [∀ n, NormedStarGroup (A n)]
    {a : lp A ∞} (ha : a ∈ normNullSequences A) : star a ∈ normNullSequences A := by
  have ha' : Tendsto (fun n ↦ ‖a n‖) cofinite (nhds 0) := ha
  have heq : (fun n ↦ ‖(star a) n‖) = fun n ↦ ‖a n‖ := by
    funext n
    simp
  show Tendsto (fun n ↦ ‖(star a) n‖) cofinite (nhds 0)
  rw [heq]
  exact ha'

/-- The norm-null sequences form a closed subset of the bounded product. -/
theorem isClosed_normNullSequences : IsClosed (normNullSequences A) := by
  apply IsSeqClosed.isClosed
  intro s a hs hsa
  show Tendsto (fun n ↦ ‖a n‖) cofinite (nhds 0)
  rw [Metric.tendsto_nhds]
  intro ε hε
  have hclose : ∀ᶠ k in atTop, dist (s k) a < ε / 2 :=
    (Metric.tendsto_nhds.mp hsa) (ε / 2) (half_pos hε)
  obtain ⟨k, hk⟩ := hclose.exists
  have hsk : Tendsto (fun n ↦ ‖s k n‖) cofinite (nhds 0) := hs k
  have htail : ∀ᶠ n in cofinite, ‖s k n‖ < ε / 2 :=
    ((Metric.tendsto_nhds.mp hsk) (ε / 2) (half_pos hε)).mono fun n hn ↦ by
      rwa [Real.dist_eq, sub_zero, abs_norm] at hn
  filter_upwards [htail] with n hn
  rw [Real.dist_eq, sub_zero, abs_norm]
  have hcoord : ‖a n - s k n‖ < ε / 2 :=
    calc
      ‖a n - s k n‖ = ‖(a - s k) n‖ := rfl
      _ ≤ ‖a - s k‖ := lp.norm_apply_le_norm ENNReal.top_ne_zero (a - s k) n
      _ = dist (s k) a := by rw [dist_comm, dist_eq_norm]
      _ < ε / 2 := hk
  have htri := norm_sub_norm_le (a n) (s k n)
  linarith

end NormNull

/-- **Printed sentence** (tex line 112, census key `be1769283b2f`).

> Here and below, products of $C^*$-algebras mean bounded products, and $\bigoplus$ denotes
> the ideal of norm-null sequences.

For every sequence `A n` of C⋆-algebras:

* the product `∏_n A_n` is mathlib's `lp A ∞`, whose members are exactly the sequences with
  bounded norms, and which is again a C⋆-ring under pointwise operations;
* `⨁_n A_n` is the set `normNullSequences A` of norm-null sequences.  It contains `0` and is
  closed under addition, negation, multiplication on either side by arbitrary bounded
  sequences, and the adjoint, and it is norm-closed: a closed two-sided `*`-ideal.

The last clause records that the norm matrix corona
`𝒬_d = ∏_n M_{d_n}(ℂ) / ⨁_n M_{d_n}(ℂ)` of tex line 110 (`NormMatrixCStarCorona`) is formed
with exactly this ideal.  `nullMatrixSequenceIdeal X cofinite` is the set of norm-null
sequences, and it is the kernel of the quotient map. -/
def PrintedBoundedProductsNullIdeal : Prop :=
  (∀ (A : ℕ → Type u) [∀ n, NonUnitalCStarAlgebra (A n)],
    (∀ f : ∀ n, A n, Memℓp f ∞ ↔ BddAbove (Set.range fun n ↦ ‖f n‖)) ∧
      CStarRing (lp A ∞) ∧
      (0 : lp A ∞) ∈ normNullSequences A ∧
      (∀ a ∈ normNullSequences A, ∀ b ∈ normNullSequences A, a + b ∈ normNullSequences A) ∧
      (∀ a ∈ normNullSequences A, -a ∈ normNullSequences A) ∧
      (∀ b : lp A ∞, ∀ a ∈ normNullSequences A, b * a ∈ normNullSequences A) ∧
      (∀ a ∈ normNullSequences A, ∀ b : lp A ∞, a * b ∈ normNullSequences A) ∧
      (∀ a ∈ normNullSequences A, star a ∈ normNullSequences A) ∧
      IsClosed (normNullSequences A)) ∧
  ∀ (X : ℕ → Type u) [∀ n, Fintype (X n)] [∀ n, DecidableEq (X n)] [∀ n, Nonempty (X n)],
    (nullMatrixSequenceIdeal X cofinite : Set (BoundedMatrixSequence X)) =
        normNullSequences (fun n ↦ Matrix (X n) (X n) ℂ) ∧
      ∀ a : BoundedMatrixSequence X,
        normMatrixCStarCoronaMk X a = 0 ↔ a ∈ normNullSequences (fun n ↦ Matrix (X n) (X n) ℂ)

theorem manuscriptSentence_boundedProductsNullIdeal : PrintedBoundedProductsNullIdeal.{u} := by
  refine ⟨fun A _ ↦ ?_, fun X _ _ _ ↦ ?_⟩
  · exact ⟨fun _ ↦ memℓp_infty_iff, inferInstance, zero_mem_normNullSequences A,
      fun _ ha _ hb ↦ add_mem_normNullSequences A ha hb,
      fun _ ha ↦ neg_mem_normNullSequences A ha,
      fun b _ ha ↦ mul_left_mem_normNullSequences A b ha,
      fun _ ha b ↦ mul_right_mem_normNullSequences A ha b,
      fun _ ha ↦ star_mem_normNullSequences A ha, isClosed_normNullSequences A⟩
  · exact ⟨rfl, fun a ↦ normMatrixCStarCoronaMk_eq_zero_iff X a⟩

end BoundedProducts

/-! ## tex line 134, `651e122a919e`: the witness `W = Cl(X) ⋊ V` -/

section Witness

open MarkedCompression CliffordLamp
open AffineSL3Doubling (alpha alpha_injective)

/-- `ℤ³ ⋊ SL₃(ℤ)`, with `SL₃(ℤ)` acting on `ℤ³` by mathlib's action `A • v = A.1 • v`, the
matrix-vector product. -/
abbrev PrintedGamma : Type := AffineSL3Doubling.Gamma

/-- `V`, the ascending HNN extension of `ℤ³ ⋊ SL₃(ℤ)` along `(v,A) ↦ (2v,A)`. -/
abbrev PrintedV : Type := Vertical alpha alpha_injective

/-- `X`, the coset space of `ℤ³ ⋊ SL₃(ℤ)` in `V`. -/
abbrev PrintedX : Type := Cosets alpha alpha_injective

/-- `W = Cl(X) ⋊ V`.  This is `MarkedCompression.Ambient alpha alpha_injective`
definitionally. -/
abbrev PrintedW : Type :=
  CliffordLamp PrintedX ⋊[lampAction alpha alpha_injective] PrintedV

/-- Every lamp generator `c_x` of `Cl(X)` is nontrivial.  The signed finite-support model
sends it to `(0, δ_x)`. -/
theorem cliffordLamp_lamp_ne_one (X : Type u) (x : X) : lamp X x ≠ 1 := by
  letI : LinearOrder X := IsWellOrder.linearOrder WellOrderingRel
  intro hlamp
  have h1 : toModel X (lamp X x) = 1 := by rw [hlamp, map_one]
  rw [toModel_lamp] at h1
  have h2 : (Finsupp.single x 1 : X →₀ ZMod 2) = 0 := congrArg SignedModel.config h1
  exact absurd (Finsupp.single_eq_zero.mp h2) (by decide)

/-- The relations `ε² = c_x² = 1`, `[ε,c_x] = 1` and `[c_x,c_y] = ε` (`x ≠ y`) present `Cl(X)`.
If elements of a group satisfy them, they are the images of `ε` and the `c_x` under exactly
one homomorphism. -/
theorem cliffordLamp_presentation (X : Type u) (G : Type v) [Group G] (e : G) (c : X → G)
    (he : e ^ 2 = 1) (hc : ∀ x, c x ^ 2 = 1) (hec : ∀ x, Commute e (c x))
    (hcc : ∀ x y, x ≠ y → ⁅c x, c y⁆ = e) :
    ∃! φ : CliffordLamp X →* G, φ (sign X) = e ∧ ∀ x, φ (lamp X x) = c x := by
  have hkill : ∀ r ∈ relators X, FreeGroup.lift (Sum.elim (fun _ ↦ e) c) r = 1 := by
    intro w hw
    change IsRelator X w at hw
    cases hw with
    | sign_sq =>
        rw [map_pow, FreeGroup.lift_apply_of]
        exact he
    | lamp_sq x =>
        rw [map_pow, FreeGroup.lift_apply_of]
        exact hc x
    | sign_comm x =>
        rw [map_commutatorElement, FreeGroup.lift_apply_of, FreeGroup.lift_apply_of]
        exact (hec x).commutator_eq
    | @braiding x y h =>
        rw [map_mul, map_inv, map_commutatorElement, FreeGroup.lift_apply_of,
          FreeGroup.lift_apply_of, FreeGroup.lift_apply_of]
        show ⁅c x, c y⁆ * e⁻¹ = 1
        rw [hcc x y h]
        exact mul_inv_cancel e
  refine ⟨PresentedGroup.toGroup hkill,
    ⟨PresentedGroup.toGroup.of hkill (x := Sum.inl ()),
      fun x ↦ PresentedGroup.toGroup.of hkill (x := Sum.inr x)⟩,
    fun ψ hψ ↦ PresentedGroup.ext fun j ↦ ?_⟩
  cases j with
  | inl u =>
      cases u
      exact hψ.1.trans (PresentedGroup.toGroup.of hkill (x := Sum.inl ())).symm
  | inr x => exact (hψ.2 x).trans (PresentedGroup.toGroup.of hkill (x := Sum.inr x)).symm

/-- **Printed sentence** (tex line 134, census key `651e122a919e`, completing the display
`W=\operatorname{Cl}(X)\rtimes V`).

> where $V$ is the ascending HNN extension of $\mathbb Z^3\rtimes\mathrm{SL}_3(\mathbb Z)$
> along $(v,A)\mapsto(2v,A)$, the set $X$ is the coset space of
> $\mathbb Z^3\rtimes\mathrm{SL}_3(\mathbb Z)$ in $V$, and $\operatorname{Cl}(X)$ is generated
> by involutions $c_x$, $x\in X$, and a central involution $\varepsilon$, with
> $[c_x,c_y]=\varepsilon$ for $x\ne y$.

The groups are the literal ones: `PrintedGamma = (Fin 3 → ℤ) ⋊ SL(3,ℤ)`,
`AffineSL3Doubling.alpha`, `PrintedV = Vertical alpha _`, `PrintedX = V ⧸ ι(Γ)`,
`Cl(X) = CliffordLamp PrintedX` with `ε = sign` and `c_x = lamp x`, and
`PrintedW = Cl(X) ⋊[lampAction] V`.  The clauses, in order:

1. `SL₃(ℤ)` acts on `ℤ³` by its matrix action, and `α(v,A) = (2v,A)`;
2. `V` is the ascending HNN extension of `Γ` along `α`.  The map `ι : Γ → V` is injective, and
   the stable letter satisfies `t ι(g) t⁻¹ = ι(α(g))`.  A homomorphism `f : Γ → H` together
   with an element `c` satisfying `f(α(x)) = c f(x) c⁻¹` extends uniquely to `V` with `t ↦ c`;
3. `X` is the left coset space `V/ι(Γ)`, and `V` acts on it by left multiplication;
4. `Cl(X)` is generated by `ε` and the `c_x`.  `ε` and every `c_x` are involutions, `ε` is
   central, `[c_x,c_y] = ε` for `x ≠ y`, and these relations present `Cl(X)`;
5. `V` acts on `Cl(X)` through `X`, fixing `ε` and sending `c_x` to `c_{vx}`, and `W` is the
   semidirect product for this action. -/
def PrintedCliffordWitnessGroup : Prop :=
  (∀ (A : Matrix.SpecialLinearGroup (Fin 3) ℤ) (v : Fin 3 → ℤ),
      AffineSL3Doubling.action A (Multiplicative.ofAdd v) = Multiplicative.ofAdd (A • v)) ∧
  (∀ (v : Fin 3 → ℤ) (A : Matrix.SpecialLinearGroup (Fin 3) ℤ),
      alpha (⟨Multiplicative.ofAdd v, A⟩ : PrintedGamma) =
        ⟨Multiplicative.ofAdd ((2 : ℕ) • v), A⟩) ∧
  Function.Injective (iotaVertical alpha alpha_injective) ∧
  (∀ g : PrintedGamma,
      tVertical alpha alpha_injective * iotaVertical alpha alpha_injective g *
          (tVertical alpha alpha_injective)⁻¹ =
        iotaVertical alpha alpha_injective (alpha g)) ∧
  (∀ (H : Type v) [Group H] (f : PrintedGamma →* H) (c : H),
      (∀ x, f (alpha x) = c * f x * c⁻¹) →
      ∃! φ : PrintedV →* H, (∀ x, φ (iotaVertical alpha alpha_injective x) = f x) ∧
        φ (tVertical alpha alpha_injective) = c) ∧
  (∀ v w : PrintedV, (QuotientGroup.mk v : PrintedX) = QuotientGroup.mk w ↔
      v⁻¹ * w ∈ (iotaVertical alpha alpha_injective).range) ∧
  (∀ x : PrintedX, ∃ v : PrintedV, (QuotientGroup.mk v : PrintedX) = x) ∧
  (∀ v w : PrintedV, v • (QuotientGroup.mk w : PrintedX) = QuotientGroup.mk (v * w)) ∧
  (∀ K : Subgroup (CliffordLamp PrintedX), sign PrintedX ∈ K → (∀ x, lamp PrintedX x ∈ K) →
      K = ⊤) ∧
  sign PrintedX ^ 2 = 1 ∧ sign PrintedX ≠ 1 ∧ (∀ g, Commute (sign PrintedX) g) ∧
  (∀ x : PrintedX, lamp PrintedX x ^ 2 = 1 ∧ lamp PrintedX x ≠ 1) ∧
  (∀ x y : PrintedX, x ≠ y → ⁅lamp PrintedX x, lamp PrintedX y⁆ = sign PrintedX) ∧
  (∀ (G : Type v) [Group G] (e : G) (c : PrintedX → G), e ^ 2 = 1 → (∀ x, c x ^ 2 = 1) →
      (∀ x, Commute e (c x)) → (∀ x y, x ≠ y → ⁅c x, c y⁆ = e) →
      ∃! φ : CliffordLamp PrintedX →* G,
        φ (sign PrintedX) = e ∧ ∀ x, φ (lamp PrintedX x) = c x) ∧
  (∀ (v : PrintedV) (x : PrintedX),
      lampAction alpha alpha_injective v (lamp PrintedX x) = lamp PrintedX (v • x)) ∧
  (∀ v : PrintedV, lampAction alpha alpha_injective v (sign PrintedX) = sign PrintedX) ∧
  (∀ (v : PrintedV) (g : CliffordLamp PrintedX),
      (SemidirectProduct.inr v : PrintedW) * SemidirectProduct.inl g *
          (SemidirectProduct.inr v)⁻¹ =
        SemidirectProduct.inl (lampAction alpha alpha_injective v g))

theorem manuscriptSentence_cliffordWitnessGroup : PrintedCliffordWitnessGroup.{v} := by
  refine ⟨fun _ _ ↦ rfl, fun _ _ ↦ rfl, iotaVertical_injective alpha alpha_injective,
    vertical_compress alpha alpha_injective, ?_, fun _ _ ↦ QuotientGroup.eq,
    fun x ↦ QuotientGroup.mk_surjective x, fun _ _ ↦ rfl,
    fun K hs hl ↦ eq_top_iff.mpr fun g _ ↦
      mem_subgroup_of_sign_mem_of_lamp_mem PrintedX K hs hl g,
    sign_sq PrintedX, sign_ne_one PrintedX, sign_commute PrintedX,
    fun x ↦ ⟨lamp_sq PrintedX x, cliffordLamp_lamp_ne_one PrintedX x⟩,
    fun _ _ h ↦ commutator_lamp_lamp PrintedX h,
    fun G _ e c he hc hec hcc ↦ cliffordLamp_presentation PrintedX G e c he hc hec hcc,
    lampAction_apply_lamp alpha alpha_injective, lampAction_apply_sign alpha alpha_injective,
    fun _ _ ↦ by rw [← map_inv, ← SemidirectProduct.inl_aut]⟩
  intro _ _ f c hc
  refine ⟨verticalLift alpha alpha_injective f c hc,
    ⟨verticalLift_iota alpha alpha_injective f c hc,
      verticalLift_t alpha alpha_injective f c hc⟩,
    fun ψ hψ ↦ MonoidHom.ext fun w ↦ ?_⟩
  exact vertical_mem_subgroup_of_iota_mem_of_t_mem alpha alpha_injective
    (MonoidHom.eqLocus ψ (verticalLift alpha alpha_injective f c hc))
    (fun x ↦ (hψ.1 x).trans (verticalLift_iota alpha alpha_injective f c hc x).symm)
    (hψ.2.trans (verticalLift_t alpha alpha_injective f c hc).symm) w

end Witness

/-! ## tex line 156, `ec81a8c16b64`: the commutator convention -/

/-- **Printed sentence** (tex line 156, census key `ec81a8c16b64`).

> We use the group commutator convention $[g,h]=ghg^{-1}h^{-1}$.

In every group, mathlib's bracket `⁅g, h⁆` (`commutatorElement`) is `g h g⁻¹ h⁻¹`.  Every
Lean statement of this paper uses this bracket for commutators. -/
def PrintedCommutatorConvention : Prop :=
  ∀ (G : Type u) [Group G] (g h : G), ⁅g, h⁆ = g * h * g⁻¹ * h⁻¹

theorem manuscriptSentence_commutatorConvention : PrintedCommutatorConvention.{u} :=
  fun _ _ g h ↦ commutatorElement_def g h

end

end IntroConventionSentences
end NonMFSentences
end Manuscript
end GroupApproximation
