import GroupApproximation.Manuscript.OneSidedMFRadical.KazhdanTransportSentences
import GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveConfiguration
import GroupApproximation.Meta.AxiomGuard

/-!
# Axiom audits for `KazhdanTransportSentences` and `RankTwelveConfiguration`

Neither module carries an axiom audit in its own source. Several census rows of
`non_mf_groups_exist.tex` name their theorems, in the proofs of `thm:transport`,
`cor:defect-hs`, `thm:compression-criterion` and `prop:max-infinite`. Some theorems were
already audited in `Manuscript/NonMF/Audit/Intro.lean`, `Audit/Sec2.lean` or
`Endpoint/OneSidedTransportAudit.lean`, but not all of them. This module audits every
theorem of both modules. Each line fails the build unless the theorem's axiom closure is
within `propext`, `Classical.choice` and `Quot.sound`.

`#audit_axioms` is used rather than `#audit_closed_axioms`, since most of these theorems
are sentence lemmas with ordinary binders. The closed endpoints of `RankTwelveConfiguration`
are also audited closed.
-/

#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence_defectAsymptoticallyTrivialInHS
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence_coronaKazhdanComplementIsInvariantCorner
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence_kazhdanInequalityKillsCornerOnDefect
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence_residuallyFiniteKazhdanGroupsAreMF
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence_movedFixedSpaceInclusionAndProjectionOrder
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence_conjugationActionsMultiplicativeModC0
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence_sigmaTildeIsHomomorphism
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence_restrictionExtendsToMaximalCStar
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence_compressorSatisfiesProjectionOrder
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence_stableFinitenessGivesProjectionEquality
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.manuscriptSentence_commutatorHilbertSchmidtVanishing

#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.flat12_apply
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.flat12_single
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.flat12Units_elementary_single_mem
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.flat12Units_elementary_mem
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.outerElementary01_val
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.outerElementary10_val
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tauUnit_eq_six_elementary
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.printedTauGL_eq_flat12Units
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.printedTauGL_mem
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.flat12_fullCorner_elementary
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.flatCornerUnits_elementaryUnit
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.flatCornerUnits_mem_elementary
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.cornerEmbedding_range
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.cornerEmbeddingToCorner_surjective
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.corner_hasKazhdanPropertyT
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tauUnit_conj_fullCorner
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tau_conj_corner_elementaryRoot
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tau_compresses_corner
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.mark3_central
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.shift_mul_blockMark
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.shift_conj_mark
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tau_conj_rawC
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.flat12_rawC
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.flat12_rawMovedC
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tau_conj_c
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.tau_c_commutator_ell
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.printedDefectConfiguration
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptPropositionDefect
#audit_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.rankTwelve_actualCoronaMFResidual_eq_top

#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.printedDefectConfiguration
#audit_closed_axioms GroupApproximation.Manuscript.OneSidedMFRadical.RankTwelveEndpoint.manuscriptPropositionDefect
