import GroupApproximation.Dynamics.TransientCellsClosed
import GroupApproximation.Dynamics.TransientIdealDefectSpan
import GroupApproximation.Topology.LocallyConstantClosedExtension
import GroupApproximation.Meta.AxiomGuard

/-!
# `lem:transient-matrices`: the printed assembly

`non_mf_groups_exist.tex`, Lemma `lem:transient-matrices` (`\label{lem:transient-matrices}`, tex 1469–1477
at origin/main `68481e4d7`):

> Restriction fits into an exact sequence
> `0 → I → R_X → R_Y → 0`, `I = LC_c(X∖Y,k) ⋊_T ℤ`.
> The ideal `I` is locally matricial and is generated by the indicators `1_{P∖T(P)}` of the defects
> in Lemma `lem:chain-core-models`.

and the first paragraph of its proof (tex 1479–1484):

> Locally constant functions on a closed subset extend by finite clopen partitions.  Their restriction
> kernel consists exactly of functions compactly supported in the complement.  Laurent normal forms
> give exactness.

Standing hypotheses of `sec:chain-core` (tex 1344–1347): `X` compact metrizable zero-dimensional, `T`
a homeomorphism, `k` a finite field, `Y = CR(T)`.

`I = LC_c(X∖Y,k) ⋊_T ℤ` is spelled coefficientwise: an element of `R_X` lies in `I` exactly when each
Laurent coefficient is compactly supported in `X ∖ Y`.  The clauses:

* kernel of restriction: `ClopenCrossedProduct.mem_transientIdeal` (`transientIdeal` is `ker (restrict)`);
* restriction onto `R_Y`: the named `RestrictSurjectiveStatement`, whose producer is in flight as
  ct-return-tower's `restrict_surjective_of_isClosed`;
* `I = LC_c(X∖Y,k) ⋊_T ℤ`: `mem_transientIdeal_iff_compactSupport`, over
  `ClopenCrossedProduct.mem_transientIdeal_iff_forall_coeff` and `ChainCore.isCompact_support`;
* locally matricial: `ClopenCrossedProduct.transientIdealLocallyMatricialStatement_holds` (closed);
* generated by the defects: `ClopenCrossedProduct.printedTransientIdealGeneratedByDefects` (closed).

Closed endpoints: `printedTransientMatricesIdealClauses` (every clause but surjectivity),
`printedClosedSubsetExtension`, `printedRestrictionKernelCompactSupport`,
`printedLaurentExactnessMiddle`.  Over the named surjectivity premise:
`printedTransientMatrices_of_restrictSurjective`.
-/

namespace GroupApproximation
namespace Manuscript
namespace NonMFSentences
namespace TransientMatrices

/-! ## Coefficients compactly supported in the complement -/

section Coefficients

variable {X : Type*} [TopologicalSpace X] [CompactSpace X]

/-- **The restriction kernel of locally constant functions** (tex 1480–1481): `g` restricts to `0`
on `Y` exactly when its support is a compact subset of `X ∖ Y`. -/
theorem restrictRingHom_eq_zero_iff_compactSupport (k : Type*) [Ring k] (Y : Set X)
    (g : LocallyConstant X k) :
    ChainCore.restrictRingHom Y g = 0 ↔
      Function.support ⇑g ⊆ Yᶜ ∧ IsCompact (Function.support ⇑g) := by
  rw [ChainCore.restrictRingHom_apply, ChainCore.comap_val_eq_zero_iff_support_subset_compl]
  exact ⟨fun h => ⟨h, ChainCore.isCompact_support g⟩, fun h => h.1⟩

/-- **`I = LC_c(X∖Y,k) ⋊_T ℤ`** (tex 1472): an element of `R_X` lies in the kernel of restriction to
`Y` exactly when every Laurent coefficient is compactly supported in `X ∖ Y`. -/
theorem mem_transientIdeal_iff_compactSupport (T : X ≃ₜ X) (k : Type*) [Ring k] {Y : Set X}
    (hY : T '' Y = Y) (x : ClopenCrossedProduct T k) :
    x ∈ ClopenCrossedProduct.transientIdeal T k hY ↔
      ∀ g : Multiplicative ℤ,
        Function.support ⇑((ClopenCoeff.of T k).symm (SkewMonoidAlgebra.coeff x g)) ⊆ Yᶜ ∧
          IsCompact
            (Function.support ⇑((ClopenCoeff.of T k).symm (SkewMonoidAlgebra.coeff x g))) := by
  rw [ClopenCrossedProduct.mem_transientIdeal_iff_forall_coeff T k hY]
  refine forall_congr' fun g => ⟨fun h => ⟨?_, ChainCore.isCompact_support _⟩, fun h y hy => ?_⟩
  · intro z hz hzY
    exact hz (h z hzY)
  · by_contra hne
    exact h.1 hne hy

end Coefficients

/-! ## The proof sentences (tex 1479–1484) -/

/-- **Printed (tex 1479–1480).**  "Locally constant functions on a closed subset extend by finite
clopen partitions": restriction `LC(X,k) → LC(Y,k)` is onto for closed `Y`. -/
def PrintedClosedSubsetExtension : Prop :=
  ∀ (X : Type) [MetricSpace X] [CompactSpace X] [TotallyDisconnectedSpace X] (k : Type) [Ring k]
    (Y : Set X), IsClosed Y → Function.Surjective (ChainCore.restrictRingHom (k := k) Y)

theorem printedClosedSubsetExtension : PrintedClosedSubsetExtension :=
  fun _ _ _ _ _ _ _ hY => ChainCore.restrictRingHom_surjective hY

/-- **Printed (tex 1480–1481).**  "Their restriction kernel consists exactly of functions compactly
supported in the complement." -/
def PrintedRestrictionKernelCompactSupport : Prop :=
  ∀ (X : Type) [MetricSpace X] [CompactSpace X] (k : Type) [Ring k] (Y : Set X)
    (g : LocallyConstant X k),
    ChainCore.restrictRingHom Y g = 0 ↔
      Function.support ⇑g ⊆ Yᶜ ∧ IsCompact (Function.support ⇑g)

theorem printedRestrictionKernelCompactSupport : PrintedRestrictionKernelCompactSupport :=
  fun _ _ _ k _ Y g => restrictRingHom_eq_zero_iff_compactSupport k Y g

/-- **Printed (tex 1481), exactness in the middle.**  "Laurent normal forms give exactness": `x` is
in the kernel of restriction to `Y = CR(T)` exactly when every Laurent coefficient of `x` vanishes on
`Y`. -/
def PrintedLaurentExactnessMiddle : Prop :=
  ∀ (X : Type) [MetricSpace X] [CompactSpace X] [TotallyDisconnectedSpace X] (T : X ≃ₜ X)
    (k : Type) [Ring k] (x : ClopenCrossedProduct T k),
    x ∈ ClopenCrossedProduct.transientIdeal T k (Dynamics.image_chainRecurrentSet T) ↔
      ∀ (g : Multiplicative ℤ), ∀ y ∈ Dynamics.chainRecurrentSet ⇑T,
        (ClopenCoeff.of T k).symm (SkewMonoidAlgebra.coeff x g) y = 0

theorem printedLaurentExactnessMiddle : PrintedLaurentExactnessMiddle :=
  fun _ _ _ _ T k _ _ =>
    ClopenCrossedProduct.mem_transientIdeal_iff_forall_coeff T k (Dynamics.image_chainRecurrentSet T)

/-! ## The printed lemma -/

/-- Restriction of `R_X` to a closed invariant set is onto (the right end of the exact sequence,
tex 1470–1471).  The producer is in flight: ct-return-tower's `restrict_surjective_of_isClosed`, by
extension of locally constant functions coefficient by coefficient. -/
def RestrictSurjectiveStatement : Prop :=
  ∀ (X : Type) [UniformSpace X] [CompactSpace X] [T2Space X] [TotallyDisconnectedSpace X]
    (T : X ≃ₜ X) (k : Type) [Ring k] (Y : Set X) (hY : T '' Y = Y), IsClosed Y →
      Function.Surjective (ClopenCrossedProduct.restrict T k hY)

/-- **`lem:transient-matrices`, every clause but the surjectivity of restriction** (tex 1469–1477):
`I` is the kernel of restriction to `Y = CR(T)`; `I = LC_c(X∖Y,k) ⋊_T ℤ` coefficientwise; `I` is
locally matricial; `I` is generated by the defect indicators `1_{P∖T(P)}`. -/
def PrintedTransientMatricesIdealClauses : Prop :=
  ∀ (X : Type) [MetricSpace X] [CompactSpace X] [TotallyDisconnectedSpace X] (T : X ≃ₜ X)
    (k : Type) [Field k] [Finite k],
    (∀ x : ClopenCrossedProduct T k,
        x ∈ ClopenCrossedProduct.transientIdeal T k (Dynamics.image_chainRecurrentSet T) ↔
          ClopenCrossedProduct.restrict T k (Dynamics.image_chainRecurrentSet T) x = 0) ∧
      (∀ x : ClopenCrossedProduct T k,
        x ∈ ClopenCrossedProduct.transientIdeal T k (Dynamics.image_chainRecurrentSet T) ↔
          ∀ g : Multiplicative ℤ,
            Function.support ⇑((ClopenCoeff.of T k).symm (SkewMonoidAlgebra.coeff x g)) ⊆
                (Dynamics.chainRecurrentSet ⇑T)ᶜ ∧
              IsCompact
                (Function.support ⇑((ClopenCoeff.of T k).symm (SkewMonoidAlgebra.coeff x g)))) ∧
      ChainCore.IsLocallyMatricialIn k
        ((ClopenCrossedProduct.transientIdeal T k (Dynamics.image_chainRecurrentSet T) :
            TwoSidedIdeal (ClopenCrossedProduct T k)) : Set (ClopenCrossedProduct T k)) ∧
      ClopenCrossedProduct.transientIdeal T k (Dynamics.image_chainRecurrentSet T) =
        TwoSidedIdeal.span (ClopenCrossedProduct.compressedDefectSet T k)

theorem printedTransientMatricesIdealClauses : PrintedTransientMatricesIdealClauses := by
  intro X _ _ _ T k _ _
  exact ⟨fun _ => ClopenCrossedProduct.mem_transientIdeal T k _,
    fun x => mem_transientIdeal_iff_compactSupport T k (Dynamics.image_chainRecurrentSet T) x,
    ClopenCrossedProduct.transientIdealLocallyMatricialStatement_holds X T k,
    ClopenCrossedProduct.printedTransientIdealGeneratedByDefects X T k⟩

/-- **`lem:transient-matrices` as printed** (tex 1469–1477), all five clauses: the kernel, the
surjectivity of restriction, `I = LC_c(X∖Y,k) ⋊_T ℤ`, local matriciality, generation by the defects. -/
def PrintedTransientMatrices : Prop :=
  ∀ (X : Type) [MetricSpace X] [CompactSpace X] [TotallyDisconnectedSpace X] (T : X ≃ₜ X)
    (k : Type) [Field k] [Finite k],
    Function.Surjective (ClopenCrossedProduct.restrict T k (Dynamics.image_chainRecurrentSet T)) ∧
      (∀ x : ClopenCrossedProduct T k,
        x ∈ ClopenCrossedProduct.transientIdeal T k (Dynamics.image_chainRecurrentSet T) ↔
          ClopenCrossedProduct.restrict T k (Dynamics.image_chainRecurrentSet T) x = 0) ∧
      (∀ x : ClopenCrossedProduct T k,
        x ∈ ClopenCrossedProduct.transientIdeal T k (Dynamics.image_chainRecurrentSet T) ↔
          ∀ g : Multiplicative ℤ,
            Function.support ⇑((ClopenCoeff.of T k).symm (SkewMonoidAlgebra.coeff x g)) ⊆
                (Dynamics.chainRecurrentSet ⇑T)ᶜ ∧
              IsCompact
                (Function.support ⇑((ClopenCoeff.of T k).symm (SkewMonoidAlgebra.coeff x g)))) ∧
      ChainCore.IsLocallyMatricialIn k
        ((ClopenCrossedProduct.transientIdeal T k (Dynamics.image_chainRecurrentSet T) :
            TwoSidedIdeal (ClopenCrossedProduct T k)) : Set (ClopenCrossedProduct T k)) ∧
      ClopenCrossedProduct.transientIdeal T k (Dynamics.image_chainRecurrentSet T) =
        TwoSidedIdeal.span (ClopenCrossedProduct.compressedDefectSet T k)

/-- The printed lemma over the surjectivity of restriction; every other clause is closed. -/
theorem printedTransientMatrices_of_restrictSurjective (hsurj : RestrictSurjectiveStatement) :
    PrintedTransientMatrices := by
  intro X _ _ _ T k _ _
  exact ⟨hsurj X T k _ (Dynamics.image_chainRecurrentSet T)
      (Dynamics.isClosed_chainRecurrentSet T.continuous),
    (printedTransientMatricesIdealClauses X T k)⟩

end TransientMatrices
end NonMFSentences
end Manuscript
end GroupApproximation

open GroupApproximation.Manuscript.NonMFSentences

#audit_closed_axioms TransientMatrices.printedClosedSubsetExtension
#audit_closed_axioms TransientMatrices.printedRestrictionKernelCompactSupport
#audit_closed_axioms TransientMatrices.printedLaurentExactnessMiddle
#audit_closed_axioms TransientMatrices.printedTransientMatricesIdealClauses
#audit_axioms TransientMatrices.printedTransientMatrices_of_restrictSurjective
#audit_axioms TransientMatrices.mem_transientIdeal_iff_compactSupport
#audit_axioms TransientMatrices.restrictRingHom_eq_zero_iff_compactSupport
