import Mathlib.Algebra.Group.Subgroup.Pointwise
import Mathlib.Tactic.Group
import GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.Weyl.Corner
import GroupApproximation.Meta.AxiomGuard

/-!
# Root spans in Steinberg groups (lane sk-leavitt-23)

For a predicate `p` on index pairs, `rootSpan p` is the subgroup of `St_I(R)` generated by
the roots `x_ij(a)` with `p i j`.  This file collects generic tools:

* induction over generators (`rootSpan_induction`), monotonicity, conjugation and
  normalization criteria, commuting with a span;
* `exists_split`: split one root `x_{i₀j₀}` off an element, when it commutes with the rest;
* `mem_rootSpan_true`: every element lies in the span of all roots.
-/

namespace GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo

open GroupApproximation.SteinbergGroup

variable {I R : Type*} [Fintype I] [DecidableEq I] [Ring R]

/-- The subgroup generated by the roots `x_ij(a)` with `p i j`. -/
def rootSpan (p : I → I → Prop) : Subgroup (SteinbergGroup I R) :=
  Subgroup.closure {g | ∃ (i j : I) (h : i ≠ j) (a : R), p i j ∧ x i j h a = g}

#audit_axioms GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo.rootSpan

theorem x_mem_rootSpan {p : I → I → Prop} {i j : I} (h : i ≠ j) (a : R) (hp : p i j) :
    x i j h a ∈ rootSpan (R := R) p :=
  Subgroup.subset_closure ⟨i, j, h, a, hp, rfl⟩

#audit_axioms GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo.x_mem_rootSpan

/-- Induction over the generating roots of a root span. -/
theorem rootSpan_induction {p : I → I → Prop} {Q : SteinbergGroup I R → Prop}
    (gen : ∀ (i j : I) (h : i ≠ j) (a : R), p i j → Q (x i j h a)) (one : Q 1)
    (mul : ∀ g k, g ∈ rootSpan (R := R) p → k ∈ rootSpan (R := R) p → Q g → Q k →
      Q (g * k))
    {g : SteinbergGroup I R} (hg : g ∈ rootSpan (R := R) p) : Q g := by
  unfold rootSpan at hg
  induction hg using Subgroup.closure_induction'' with
  | mem g hx =>
    obtain ⟨i, j, h, a, hp, rfl⟩ := hx
    exact gen i j h a hp
  | inv_mem g hx =>
    obtain ⟨i, j, h, a, hp, rfl⟩ := hx
    rw [← x_neg]
    exact gen i j h (-a) hp
  | one => exact one
  | mul g k hg hk ihg ihk => exact mul g k hg hk ihg ihk

#audit_axioms GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo.rootSpan_induction

theorem rootSpan_mono {p q : I → I → Prop} (hpq : ∀ i j, i ≠ j → p i j → q i j)
    {g : SteinbergGroup I R} (hg : g ∈ rootSpan (R := R) p) : g ∈ rootSpan (R := R) q :=
  rootSpan_induction (Q := fun g => g ∈ rootSpan (R := R) q)
    (fun _ _ h a hp => x_mem_rootSpan h a (hpq _ _ h hp)) (Subgroup.one_mem _)
    (fun _ _ _ _ h1 h2 => Subgroup.mul_mem _ h1 h2) hg

#audit_axioms GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo.rootSpan_mono

/-- If `c` conjugates every generating root into `H`, it conjugates the whole span into `H`. -/
theorem rootSpan_conj_mem {p : I → I → Prop} {H : Subgroup (SteinbergGroup I R)}
    {c : SteinbergGroup I R}
    (hgen : ∀ (i j : I) (h : i ≠ j) (a : R), p i j → c * x i j h a * c⁻¹ ∈ H)
    {g : SteinbergGroup I R} (hg : g ∈ rootSpan (R := R) p) : c * g * c⁻¹ ∈ H := by
  refine rootSpan_induction (Q := fun g => c * g * c⁻¹ ∈ H) hgen ?_ ?_ hg
  · show c * 1 * c⁻¹ ∈ H
    rw [mul_one, mul_inv_cancel]
    exact H.one_mem
  · intro g k _ _ hg hk
    show c * (g * k) * c⁻¹ ∈ H
    have e : c * (g * k) * c⁻¹ = (c * g * c⁻¹) * (c * k * c⁻¹) := by group
    rw [e]
    exact H.mul_mem hg hk

#audit_axioms GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo.rootSpan_conj_mem

/-- If every `p`-root conjugates every `q`-root into `rootSpan q`, then `rootSpan p`
normalizes `rootSpan q`. -/
theorem rootSpan_normalizes {p q : I → I → Prop}
    (hgen : ∀ (i j : I) (h : i ≠ j) (a : R), p i j → ∀ (k l : I) (h' : k ≠ l) (b : R),
      q k l → x i j h a * x k l h' b * (x i j h a)⁻¹ ∈ rootSpan (R := R) q)
    {s : SteinbergGroup I R} (hs : s ∈ rootSpan (R := R) p)
    {u : SteinbergGroup I R} (hu : u ∈ rootSpan (R := R) q) :
    s * u * s⁻¹ ∈ rootSpan (R := R) q := by
  refine (rootSpan_induction
    (Q := fun s => ∀ u, u ∈ rootSpan (R := R) q → s * u * s⁻¹ ∈ rootSpan (R := R) q)
    ?_ ?_ ?_ hs) u hu
  · intro i j h a hp u hu
    exact rootSpan_conj_mem (fun k l h' b hq => hgen i j h a hp k l h' b hq) hu
  · intro u hu
    show 1 * u * 1⁻¹ ∈ rootSpan (R := R) q
    rw [one_mul, inv_one, mul_one]
    exact hu
  · intro g k _ _ hg hk u hu
    show g * k * u * (g * k)⁻¹ ∈ rootSpan (R := R) q
    have e : g * k * u * (g * k)⁻¹ = g * (k * u * k⁻¹) * g⁻¹ := by group
    rw [e]
    exact hg _ (hk u hu)

#audit_axioms GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo.rootSpan_normalizes

theorem commute_of_rootSpan {q : I → I → Prop} {c : SteinbergGroup I R}
    (hc : ∀ (i j : I) (h : i ≠ j) (a : R), q i j → Commute c (x i j h a))
    {g : SteinbergGroup I R} (hg : g ∈ rootSpan (R := R) q) : Commute c g :=
  rootSpan_induction (Q := fun g => Commute c g) hc (Commute.one_right c)
    (fun _ _ _ _ h1 h2 => h1.mul_right h2) hg

#audit_axioms GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo.commute_of_rootSpan

/-- Split the root `x_{i₀j₀}` off an element of `rootSpan p`, when every other generating
root lies in `q` and commutes with `x_{i₀j₀}`. -/
theorem exists_split {p q : I → I → Prop} {i₀ j₀ : I} (h₀ : i₀ ≠ j₀)
    (hsplit : ∀ i j, i ≠ j → p i j → (i = i₀ ∧ j = j₀) ∨ q i j)
    (hcomm : ∀ (i j : I) (h : i ≠ j) (a b : R), q i j →
      Commute (x i₀ j₀ h₀ b) (x i j h a))
    {g : SteinbergGroup I R} (hg : g ∈ rootSpan (R := R) p) :
    ∃ d : R, ∃ g' ∈ rootSpan (R := R) q, g = x i₀ j₀ h₀ d * g' := by
  refine rootSpan_induction
    (Q := fun g => ∃ d : R, ∃ g' ∈ rootSpan (R := R) q, g = x i₀ j₀ h₀ d * g')
    ?_ ?_ ?_ hg
  · intro i j h a hp
    rcases hsplit i j h hp with ⟨rfl, rfl⟩ | hq
    · exact ⟨a, 1, Subgroup.one_mem _, (mul_one _).symm⟩
    · exact ⟨0, x i j h a, x_mem_rootSpan h a hq, by rw [x_zero, one_mul]⟩
  · exact ⟨0, 1, Subgroup.one_mem _, by rw [x_zero, one_mul]⟩
  · rintro g k _ _ ⟨d, g', hg', rfl⟩ ⟨e, k', hk', rfl⟩
    refine ⟨d + e, g' * k', Subgroup.mul_mem _ hg' hk', ?_⟩
    have hc : Commute g' (x i₀ j₀ h₀ e) :=
      (commute_of_rootSpan (fun i j h a hq => hcomm i j h a e hq) hg').symm
    rw [← x_mul]
    calc x i₀ j₀ h₀ d * g' * (x i₀ j₀ h₀ e * k')
        = x i₀ j₀ h₀ d * (g' * x i₀ j₀ h₀ e) * k' := by simp only [mul_assoc]
      _ = x i₀ j₀ h₀ d * (x i₀ j₀ h₀ e * g') * k' := by rw [hc.eq]
      _ = x i₀ j₀ h₀ d * x i₀ j₀ h₀ e * (g' * k') := by simp only [mul_assoc]

#audit_axioms GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo.exists_split

/-- Every element of `St_I(R)` lies in the span of all roots. -/
theorem mem_rootSpan_true (g : SteinbergGroup I R) :
    g ∈ rootSpan (R := R) (fun _ _ : I => True) := by
  refine PresentedGroup.generated_by _ (rootSpan (R := R) (fun _ _ : I => True)) ?_ g
  rintro ⟨i, j, hij, a⟩
  exact x_mem_rootSpan hij a trivial

#audit_axioms GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo.mem_rootSpan_true

end GroupApproximation.Manuscript.SimpleKazhdanSofic.LeavittK2.FieldTwo
