import GroupApproximation.Manuscript.SimpleKazhdanSofic.SubshiftMatricial
import GroupApproximation.Manuscript.SimpleKazhdanSofic.PeriodicMatrixUnits
import GroupApproximation.Meta.AxiomGuard

/-!
# Audit repair: products of the conjugated letter indicators are the matrix units

`simple_kazhdan_sofic_group.tex` at 1eefb3bbbf0eafe710276b85dbf87512c6ddc95a, proof of
`thm:main` (census key `769f446cc3f5`, tex l.388–390):

> The shifts $T^ty_\ell$, $0\le t<N_\ell$, are distinct, so products of the $P^iD_\ell(e_a)P^{-i}$
> give every diagonal matrix unit, and with $P$ every matrix unit.

The existing `single_self_mem_closure` and `single_mem_closure` show only that the matrix units lie in
the subring generated by `P`, `P⁻¹` and the `D(e_a)`. That is weaker than the sentence, which says
that *products* of conjugates give the diagonal units, and that multiplying by powers of `P` gives
the rest. This module proves the stronger form.

* `list_prod_map_diagonal`, `toList_prod_map_diagonal`: a product of diagonal matrices is the
  diagonal matrix of the pointwise products.
* `conj_letterDiagonal`: `P^{-i} D(e_a) P^{i} = diag(1_{c(t + i) = a})`. The proof uses the corpus
  lemma `shiftMatrix_mul_diagonal_mul_shiftMatrix_neg`.
* `single_self_eq_prod`: when a cyclic word `c` has distinct translates, `E_{t₀t₀}` is the ordered
  product over `i ∈ ZMod N` of `P^{-i} D(e_{c(t₀+i)}) P^{i}`.
* `shiftMatrix_mul_single_self`: `P^{s-t} E_{tt} = E_{st}`.
* `manuscriptSentence_distinctShiftsGiveMatrixUnits`: the sentence, along a sequence `y` with least
  period `N`, for the cyclic word `t ↦ y t` on `ZMod N`. Distinctness of the translates comes from
  `translates_distinct_of_leastPeriod`.
-/

namespace GroupApproximation
namespace SimpleKazhdanSofic
namespace Audit2

open Matrix Pestov91

section Products

variable {N : ℕ} [NeZero N]

/-- A product of diagonal matrices is the diagonal matrix of the pointwise products. -/
theorem list_prod_map_diagonal {ι : Type*} (l : List ι) (d : ι → ZMod N → ZMod 2) :
    (l.map fun i => diagonal (d i)).prod = diagonal fun t => (l.map fun i => d i t).prod := by
  induction l with
  | nil => simp only [List.map_nil, List.prod_nil, diagonal_one]
  | cons i l ih => simp only [List.map_cons, List.prod_cons, ih, diagonal_mul_diagonal]

/-- The same, along the list of a finite set. -/
theorem toList_prod_map_diagonal {ι : Type*} (s : Finset ι) (d : ι → ZMod N → ZMod 2) :
    (s.toList.map fun i => diagonal (d i)).prod = diagonal fun t => ∏ i ∈ s, d i t := by
  rw [list_prod_map_diagonal]
  exact congrArg diagonal (funext fun t => Finset.prod_map_toList s fun i => d i t)

end Products

section Units

variable {A : Type*} [DecidableEq A] {N : ℕ} [NeZero N] (c : ZMod N → A)

/-- `P^{-i} D(e_a) P^{i} = diag(1_{c(t + i) = a})`. -/
theorem conj_letterDiagonal (i : ZMod N) (a : A) :
    shiftMatrix (ZMod 2) N (-((i.val : ℕ) : ℤ)) * letterDiagonal c a *
        shiftMatrix (ZMod 2) N ((i.val : ℕ) : ℤ) =
      diagonal fun t => if c (t + i) = a then (1 : ZMod 2) else 0 := by
  have h := shiftMatrix_mul_diagonal_mul_shiftMatrix_neg (N := N) (-((i.val : ℕ) : ℤ))
    (fun t => if c t = a then (1 : ZMod 2) else 0)
  have hfun : (fun t : ZMod N =>
      (fun t => if c t = a then (1 : ZMod 2) else 0) (t - (((-((i.val : ℕ) : ℤ)) : ℤ) : ZMod N))) =
      fun t => if c (t + i) = a then (1 : ZMod 2) else 0 := by
    funext t
    simp only [Int.cast_neg, Int.cast_natCast, ZMod.natCast_zmod_val, sub_neg_eq_add]
  rw [hfun, neg_neg] at h
  exact h

/-- tex l.388–389: "products of the $P^iD_\ell(e_a)P^{-i}$ give every diagonal matrix unit". If the
translates of `c` are distinct, `E_{t₀t₀}` is the ordered product over `i ∈ ZMod N` of the conjugates
`P^{-i} D(e_{c(t₀+i)}) P^{i}`. -/
theorem single_self_eq_prod
    (hdist : ∀ t t' : ZMod N, (∀ i : ZMod N, c (t + i) = c (t' + i)) → t = t') (t₀ : ZMod N) :
    single t₀ t₀ (1 : ZMod 2) =
      ((Finset.univ : Finset (ZMod N)).toList.map fun i =>
        shiftMatrix (ZMod 2) N (-((i.val : ℕ) : ℤ)) * letterDiagonal c (c (t₀ + i)) *
          shiftMatrix (ZMod 2) N ((i.val : ℕ) : ℤ)).prod := by
  have hd : (fun t => ∏ i ∈ (Finset.univ : Finset (ZMod N)),
      if c (t + i) = c (t₀ + i) then (1 : ZMod 2) else 0) = Pi.single t₀ 1 := by
    funext t
    by_cases ht : t = t₀
    · subst ht
      simp
    · obtain ⟨i, hi⟩ : ∃ i : ZMod N, c (t + i) ≠ c (t₀ + i) := by
        by_contra hcon
        exact ht (hdist t t₀ fun i => not_not.1 fun h => hcon ⟨i, h⟩)
      rw [Pi.single_eq_of_ne ht]
      exact Finset.prod_eq_zero (Finset.mem_univ i) (if_neg hi)
  simp only [conj_letterDiagonal c]
  rw [toList_prod_map_diagonal, hd, diagonal_single]

/-- tex l.389–390: "and with $P$ every matrix unit": `P^{s-t} E_{tt} = E_{st}`. -/
theorem shiftMatrix_mul_single_self (s t : ZMod N) :
    shiftMatrix (ZMod 2) N (((s - t).val : ℕ) : ℤ) * single t t (1 : ZMod 2) = single s t 1 := by
  set j : ℤ := (((s - t).val : ℕ) : ℤ)
  have hj : t + (j : ZMod N) = s := by
    simp only [j, Int.cast_natCast, ZMod.natCast_zmod_val, add_sub_cancel]
  rw [← diagonal_single, shiftMatrix_mul_diagonal]
  ext a b
  rw [diagonal_mul_shiftMatrix_apply]
  simp only [single, of_apply]
  by_cases hab : b + (j : ZMod N) = a
  · rw [if_pos hab]
    subst hab
    rw [add_sub_cancel_right]
    by_cases hbt : b = t
    · subst hbt
      rw [Pi.single_eq_same, if_pos (And.intro hj.symm rfl)]
    · rw [Pi.single_eq_of_ne hbt,
        if_neg (show ¬(s = b + (j : ZMod N) ∧ t = b) from fun h => hbt h.2.symm)]
  · rw [if_neg hab, if_neg]
    rintro ⟨rfl, rfl⟩
    exact hab hj

end Units

/-- **tex l.388–390.**  Let `y : ℤ → A` have least period `N`, and let `c t = y t` on `ZMod N`.

1. The shifts are distinct.
2. Every diagonal matrix unit `E_{t₀t₀}` is a product of the conjugates `P^{-i} D(e_a) P^{i}`,
   namely the ordered product over `i ∈ ZMod N` with `a = c(t₀ + i)`.
3. Every matrix unit `E_{st}` is a power of `P` times a diagonal matrix unit. -/
theorem manuscriptSentence_distinctShiftsGiveMatrixUnits {A : Type*} [DecidableEq A] {N : ℕ}
    [NeZero N] (y : ℤ → A) (hN : leastPeriod y = N) :
    (∀ t t' : ZMod N, (∀ i : ZMod N, y ((t + i).val : ℕ) = y ((t' + i).val : ℕ)) → t = t') ∧
      (∀ t₀ : ZMod N, single t₀ t₀ (1 : ZMod 2) =
        ((Finset.univ : Finset (ZMod N)).toList.map fun i =>
          shiftMatrix (ZMod 2) N (-((i.val : ℕ) : ℤ)) *
              letterDiagonal (fun t : ZMod N => y ((t.val : ℕ) : ℤ)) (y (((t₀ + i).val : ℕ) : ℤ)) *
            shiftMatrix (ZMod 2) N ((i.val : ℕ) : ℤ)).prod) ∧
        ∀ s t : ZMod N, ∃ j : ℤ,
          shiftMatrix (ZMod 2) N j * single t t (1 : ZMod 2) = single s t 1 := by
  have hdist := translates_distinct_of_leastPeriod y hN
  exact ⟨hdist, fun t₀ => single_self_eq_prod (fun t : ZMod N => y ((t.val : ℕ) : ℤ)) hdist t₀,
    fun s t => ⟨_, shiftMatrix_mul_single_self s t⟩⟩

end Audit2
end SimpleKazhdanSofic
end GroupApproximation

#audit_axioms GroupApproximation.SimpleKazhdanSofic.Audit2.list_prod_map_diagonal
#audit_axioms GroupApproximation.SimpleKazhdanSofic.Audit2.toList_prod_map_diagonal
#audit_axioms GroupApproximation.SimpleKazhdanSofic.Audit2.conj_letterDiagonal
#audit_axioms GroupApproximation.SimpleKazhdanSofic.Audit2.single_self_eq_prod
#audit_axioms GroupApproximation.SimpleKazhdanSofic.Audit2.shiftMatrix_mul_single_self
#audit_axioms GroupApproximation.SimpleKazhdanSofic.Audit2.manuscriptSentence_distinctShiftsGiveMatrixUnits
