import GroupApproximation.GGT.HullSCRelatorSeparation2BaseCount
#check List.countP_eq_length_filter
#check List.countP_eq_card_filter
#check List.countP_eq_count_filter
#check List.countP_eq_sum_map
#check Finset.card_filter
#check Finset.card_range
#check List.ofFn_getElem
#check List.countP_eq_countP_attach
#check List.zipIdx
#check List.length_zipIdx
#check List.mem_zipIdx
#check List.getElem_zipIdx
#check List.map_fst_zipIdx
#check List.Pairwise
#check List.toFinset_card_of_nodup
#check List.card_toFinset
#check Finset.card_erase_le
#check Finset.card_erase_lt_iff_mem
#check Finset.card_erase_add_one
#check Finset.card_erase_of_mem
#check Finset.mem_erase
