import GroupApproximation.BooneHigmanLinear.K2Poly.FieldSymbolGen
import GroupApproximation.BooneHigmanLinear.K2Poly.SymbolCentral
import GroupApproximation.BooneHigmanLinear.K2Poly.FieldNF.Check
import GroupApproximation.Meta.AxiomGuard

/-!
# A5.1: the constant `K₂` is central in `St_I(F[X])`

k2-poly piece A5.1 (lane bh-pal-wire). For a field `F` and a third index for every pair of
`I`, every `z ∈ fnZ F = C(K₂(I, F))` is central in `St_I(F[X])` (`fnZ_central`). This is
k2-field-a's `FieldNF.FieldZCentralAt F` (`fieldZCentralAt`), the only centrality input of
`FieldNF.fieldStab_of_coset`.

Proof: `K₂(I, F)` is generated by symbols (`fsg_K2_le_Z`, Steinberg's theorem). The map
`C : St_I(F) → St_I(F[X])` sends `symbol(u, v)` to the symbol `csym(C u, C v)` over `F[X]`
(`k2PolyDeg_ringMap_h`), and symbols are central over any commutative ring
(`csym_commute`).
-/

namespace GroupApproximation.BooneHigmanLinear.K2Poly

open GroupApproximation.SteinbergGroup
open GroupApproximation.BooneHigman.Metabelian.ElemFP.FieldK2
open GroupApproximation.BooneHigman.SteinbergBasic (K2)

variable {I : Type} [Fintype I] [DecidableEq I] {F : Type} [Field F]

/-- `C` maps each symbol over `F` to the symbol of the constant units over `F[X]`. -/
theorem fsg_ringMap_C_symbol (i j : I) (hij : i ≠ j) (u v : Fˣ) :
    ringMap (I := I) (Polynomial.C : F →+* Polynomial F) (symbol i j hij u v) =
      csym i j hij (Units.map (Polynomial.C : F →+* Polynomial F).toMonoidHom u)
        (Units.map (Polynomial.C : F →+* Polynomial F).toMonoidHom v) := by
  simp only [symbol, csym, map_mul, map_inv,
    GroupApproximation.BooneHigman.Metabelian.ElemFP.k2PolyDeg_ringMap_h]

#audit_axioms GroupApproximation.BooneHigmanLinear.K2Poly.fsg_ringMap_C_symbol

/-- **A5.1.** `C(K₂(I, F))` is central in `St_I(F[X])`. -/
theorem fnZ_central (third : ∀ a b : I, ∃ k, a ≠ k ∧ b ≠ k)
    {z : SteinbergGroup I (Polynomial F)} (hz : z ∈ fnZ (I := I) F)
    (g : SteinbergGroup I (Polynomial F)) : z * g = g * z := by
  have hle : (fsgZ (I := I) F).map (ringMap (I := I) (Polynomial.C : F →+* Polynomial F)) ≤
      Subgroup.center (SteinbergGroup I (Polynomial F)) := by
    rw [fsgZ, MonoidHom.map_closure, Subgroup.closure_le]
    rintro _ ⟨_, ⟨i, j, hij, u, v, rfl⟩, rfl⟩
    rw [SetLike.mem_coe, Subgroup.mem_center_iff]
    intro g'
    obtain ⟨n, hin, hjn⟩ := third i j
    rw [fsg_ringMap_C_symbol]
    exact (csym_commute i j hij ⟨n, hin, hjn⟩ _ _ g').eq.symm
  obtain ⟨k, hk, rfl⟩ := Subgroup.mem_map.mp hz
  exact ((Subgroup.mem_center_iff.mp
    (hle (Subgroup.mem_map_of_mem _ (fsg_K2_le_Z third hk)))) g).symm

#audit_axioms GroupApproximation.BooneHigmanLinear.K2Poly.fnZ_central

/-- k2-field-a's `FieldZCentralAt F` holds for every field `F`. -/
theorem fieldZCentralAt (F : Type) [Field F] : FieldNF.FieldZCentralAt F :=
  fun third _ hz g => fnZ_central third hz g

#audit_axioms GroupApproximation.BooneHigmanLinear.K2Poly.fieldZCentralAt

end GroupApproximation.BooneHigmanLinear.K2Poly
