import GroupApproximation.BooneHigmanLinear.K2Poly.FieldZCentral
import GroupApproximation.BooneHigmanLinear.K2Poly.FiniteFieldSymbol
import GroupApproximation.BooneHigmanLinear.TulenbaevHorrocks.Statements
import GroupApproximation.Meta.AxiomGuard

/-!
# `K₂` of a finite field and of its polynomial ring

k2-poly (lane bh-pal-wire).

* `K2_eq_bot_finiteField`: `K₂(I, F) = 1` for a finite field `F`, given a third index for every
  pair (Steinberg). `K₂(I, F)` is generated by symbols (`fsg_K2_le_Z`), and symbols over a
  finite field are trivial (`symbol_eq_one_finiteField`).
* `finiteFieldPolyK2_of_fieldCoset`: pal-q111's `TulenbaevHorrocks.FiniteFieldPolyK2Statement 3`
  from the coset step A5.2 at finite fields. An element of `K₂(N, k[X])` is a constant `C y`
  (A5, `fieldConst_of_fieldStab`). Evaluating at `0` puts `y` in `K₂(N, k) = 1`.
-/

namespace GroupApproximation.BooneHigmanLinear.K2Poly

open GroupApproximation.SteinbergGroup
open GroupApproximation.BooneHigman.Metabelian.ElemFP.FieldK2
open GroupApproximation.BooneHigman.SteinbergBasic (K2 ringMap_mem_K2 ringMap_ringMap ringMap_id)

/-- **`K₂` of a finite field vanishes**, given a third index for every pair. -/
theorem K2_eq_bot_finiteField {I : Type} [Fintype I] [DecidableEq I] (F : Type) [Field F]
    [Fintype F] (third : ∀ a b : I, ∃ k, a ≠ k ∧ b ≠ k) : K2 I F = ⊥ := by
  refine eq_bot_iff.mpr (le_trans (fsg_K2_le_Z third) ?_)
  rw [fsgZ, Subgroup.closure_le]
  rintro _ ⟨i, j, hij, u, v, rfl⟩
  obtain ⟨k, hik, hjk⟩ := third i j
  rw [SetLike.mem_coe, Subgroup.mem_bot]
  exact symbol_eq_one_finiteField i j k hij hik hjk u v

#audit_axioms GroupApproximation.BooneHigmanLinear.K2Poly.K2_eq_bot_finiteField

/-- **`K₂(N, k[X]) = 1` over finite fields, for `N ≥ 3`**, from the coset step A5.2. -/
theorem finiteFieldPolyK2_of_fieldCoset
    (hC : ∀ (F : Type) [Field F] [Finite F], FieldNF.FieldCosetAt F) :
    TulenbaevHorrocks.FiniteFieldPolyK2Statement 3 := by
  intro k _ _ N hN
  haveI := Fintype.ofFinite k
  have hthird : ∀ a b : Fin N, ∃ c, a ≠ c ∧ b ≠ c :=
    bruhatBigCell_third (by rw [Fintype.card_fin]; omega)
  have hconst := fieldConst_of_fieldStab (FieldNF.fieldStab_of_coset (fieldZCentralAt k) (hC k)) hN
  have hev : (Polynomial.evalRingHom 0 : Polynomial k →+* k).comp Polynomial.C = RingHom.id k :=
    RingHom.ext fun a => by
      rw [RingHom.comp_apply, Polynomial.coe_evalRingHom, Polynomial.eval_C, RingHom.id_apply]
  refine eq_bot_iff.mpr fun g hg => ?_
  obtain ⟨y, rfl⟩ := MonoidHom.mem_range.mp (hconst g hg)
  have hy : y ∈ K2 (Fin N) k := by
    have h := ringMap_mem_K2 (Polynomial.evalRingHom 0 : Polynomial k →+* k) hg
    rw [ringMap_ringMap, hev, ringMap_id, MonoidHom.id_apply] at h
    exact h
  rw [K2_eq_bot_finiteField k hthird, Subgroup.mem_bot] at hy
  rw [Subgroup.mem_bot, hy, map_one]

#audit_axioms GroupApproximation.BooneHigmanLinear.K2Poly.finiteFieldPolyK2_of_fieldCoset

end GroupApproximation.BooneHigmanLinear.K2Poly
