import GroupApproximation.RotationAlgebra.DirectSummand
import Mathlib.AlgebraicTopology.FundamentalGroupoid.FundamentalGroup

/-!
# The unit retraction splits torus loops

This is the topological half of research node `stw50-unit-retraction-splits-torus-loops`. The proof
is in `research/artifacts/stw50-rotation-loop-retraction-2026-09-04.md` and is re-derived in §3.6
of `research/artifacts/fz-stw-l-review-2026-09-13.md`.

A point-norm continuous torus action `γ : 𝕋² → Aut(A)` with `γ_z(u_j) = z_j u_j` gives two loops
`ℓ_1, ℓ_2` in `π_1(Aut(A), id)`. The evaluations `e_j : α ↦ α(u_j) u_j^*` are based maps
`Aut(A) → U(A)`. The loop `e_j ∘ ℓ_k` is the scalar loop `z ↦ z · 1` when `j = k`, and is
constant otherwise. Take a homomorphism `W : π_1(U(A), 1) → ℤ` sending the scalar loop to `1`; for
`A_θ` this is `ε ∘ Bott`. Then `ρ = (W ∘ e_{1*}, W ∘ e_{2*})` is a retraction onto `ℤ²`, so the
two loops span a direct summand.

This file proves the topological part for arbitrary based spaces. The loops are based maps
`ℓ_k : S → T` applied to one class `g ∈ π_1(S, s₀)`. For the circle, `g` is the generator.

* `mapOfEq_comp`, `mapOfEq_congr`, `mapOfEq_const`: functoriality of `FundamentalGroup.mapOfEq`.
* `mapOfEq_mapOfEq_of_comp_eq`, `mapOfEq_mapOfEq_of_comp_eq_const`: `e_* (ℓ_* g) = c_* g` when
  `e ∘ ℓ = c`, and `e_* (ℓ_* g) = 1` when `e ∘ ℓ` is constant.
* `torusRetraction`: `ρ = (W ∘ e_{1*}, W ∘ e_{2*})`.
* `torusRetraction_loop₁`, `torusRetraction_loop₂`: `ρ(ℓ_1) = (1, 0)` and `ρ(ℓ_2) = (0, 1)`.
* `isCompl_closure_torusLoops`: `ker ρ` is a complement of the subgroup generated by `ℓ_1, ℓ_2`.
* `torusLoops_injective`: `(m, n) ↦ ℓ_1^m ℓ_2^n` is injective, so that subgroup is `ℤ²`.
-/

namespace GroupApproximation
namespace RotationAlgebra

open Multiplicative

section MapOfEq

variable {X Y Z : Type*} [TopologicalSpace X] [TopologicalSpace Y] [TopologicalSpace Z]

/-- `FundamentalGroup.mapOfEq` respects composition. -/
theorem mapOfEq_comp (f : C(X, Y)) (g : C(Y, Z)) {x : X} {y : Y} {z : Z} (hf : f x = y)
    (hg : g y = z) (p : FundamentalGroup X x) :
    FundamentalGroup.mapOfEq (g.comp f) (by rw [ContinuousMap.comp_apply, hf, hg]) p =
      FundamentalGroup.mapOfEq g hg (FundamentalGroup.mapOfEq f hf p) := by
  subst hf hg
  simp only [FundamentalGroup.mapOfEq_apply]
  obtain ⟨q, rfl⟩ := Quot.exists_rep (p : Path.Homotopic.Quotient x x)
  rfl

/-- `FundamentalGroup.mapOfEq` depends only on the map. -/
theorem mapOfEq_congr {f f' : C(X, Y)} (hff : f = f') {x : X} {y : Y} (h : f x = y)
    (h' : f' x = y) (p : FundamentalGroup X x) :
    FundamentalGroup.mapOfEq f h p = FundamentalGroup.mapOfEq f' h' p := by
  subst hff
  rfl

/-- A constant map induces the trivial homomorphism on fundamental groups. -/
theorem mapOfEq_const (y : Y) {x : X} (h : ContinuousMap.const X y x = y)
    (p : FundamentalGroup X x) : FundamentalGroup.mapOfEq (ContinuousMap.const X y) h p = 1 := by
  simp only [FundamentalGroup.mapOfEq_apply]
  obtain ⟨q, rfl⟩ := Quot.exists_rep (p : Path.Homotopic.Quotient x x)
  rfl

end MapOfEq

variable {S T U : Type*} [TopologicalSpace S] [TopologicalSpace T] [TopologicalSpace U]
  {s₀ : S} {t₀ : T} {u₀ : U}

/-- If `e ∘ ℓ = c`, then `e_* (ℓ_* g) = c_* g`. -/
theorem mapOfEq_mapOfEq_of_comp_eq {ℓ : C(S, T)} (hℓ : ℓ s₀ = t₀) {e : C(T, U)}
    (he : e t₀ = u₀) {c : C(S, U)} (hc : c s₀ = u₀) (h : e.comp ℓ = c)
    (g : FundamentalGroup S s₀) :
    FundamentalGroup.mapOfEq e he (FundamentalGroup.mapOfEq ℓ hℓ g) =
      FundamentalGroup.mapOfEq c hc g := by
  rw [← mapOfEq_comp ℓ e hℓ he]
  exact mapOfEq_congr h _ hc g

/-- If `e ∘ ℓ` is constant, then `e_* (ℓ_* g) = 1`. -/
theorem mapOfEq_mapOfEq_of_comp_eq_const {ℓ : C(S, T)} (hℓ : ℓ s₀ = t₀) {e : C(T, U)}
    (he : e t₀ = u₀) (h : e.comp ℓ = ContinuousMap.const S u₀) (g : FundamentalGroup S s₀) :
    FundamentalGroup.mapOfEq e he (FundamentalGroup.mapOfEq ℓ hℓ g) = 1 :=
  (mapOfEq_mapOfEq_of_comp_eq (c := ContinuousMap.const S u₀) hℓ he
    (ContinuousMap.const_apply u₀ s₀) h g).trans (mapOfEq_const u₀ _ g)

/-- The retraction `ρ = (W ∘ e_{1*}, W ∘ e_{2*}) : π_1(T, t₀) → ℤ²` of the unit retraction
lemma. -/
noncomputable def torusRetraction (W : FundamentalGroup U u₀ →* Multiplicative ℤ) (e₁ e₂ : C(T, U))
    (he₁ : e₁ t₀ = u₀) (he₂ : e₂ t₀ = u₀) :
    FundamentalGroup T t₀ →* Multiplicative ℤ × Multiplicative ℤ :=
  (W.comp (FundamentalGroup.mapOfEq e₁ he₁)).prod (W.comp (FundamentalGroup.mapOfEq e₂ he₂))

/-- `ρ(ℓ_1) = (1, 0)`: `e_1 ∘ ℓ_1` is the scalar loop and `e_2 ∘ ℓ_1` is constant. -/
theorem torusRetraction_loop₁ (W : FundamentalGroup U u₀ →* Multiplicative ℤ) {e₁ e₂ : C(T, U)}
    (he₁ : e₁ t₀ = u₀) (he₂ : e₂ t₀ = u₀) {ℓ₁ : C(S, T)} (h₁ : ℓ₁ s₀ = t₀) {c : C(S, U)}
    (hc : c s₀ = u₀) (g : FundamentalGroup S s₀)
    (hW : W (FundamentalGroup.mapOfEq c hc g) = ofAdd (1 : ℤ)) (h11 : e₁.comp ℓ₁ = c)
    (h21 : e₂.comp ℓ₁ = ContinuousMap.const S u₀) :
    torusRetraction W e₁ e₂ he₁ he₂ (FundamentalGroup.mapOfEq ℓ₁ h₁ g) = (ofAdd (1 : ℤ), 1) := by
  simp only [torusRetraction, MonoidHom.prod_apply, MonoidHom.comp_apply]
  rw [mapOfEq_mapOfEq_of_comp_eq h₁ he₁ hc h11 g, mapOfEq_mapOfEq_of_comp_eq_const h₁ he₂ h21 g,
    map_one W, hW]

/-- `ρ(ℓ_2) = (0, 1)`: `e_1 ∘ ℓ_2` is constant and `e_2 ∘ ℓ_2` is the scalar loop. -/
theorem torusRetraction_loop₂ (W : FundamentalGroup U u₀ →* Multiplicative ℤ) {e₁ e₂ : C(T, U)}
    (he₁ : e₁ t₀ = u₀) (he₂ : e₂ t₀ = u₀) {ℓ₂ : C(S, T)} (h₂ : ℓ₂ s₀ = t₀) {c : C(S, U)}
    (hc : c s₀ = u₀) (g : FundamentalGroup S s₀)
    (hW : W (FundamentalGroup.mapOfEq c hc g) = ofAdd (1 : ℤ))
    (h12 : e₁.comp ℓ₂ = ContinuousMap.const S u₀) (h22 : e₂.comp ℓ₂ = c) :
    torusRetraction W e₁ e₂ he₁ he₂ (FundamentalGroup.mapOfEq ℓ₂ h₂ g) = (1, ofAdd (1 : ℤ)) := by
  simp only [torusRetraction, MonoidHom.prod_apply, MonoidHom.comp_apply]
  rw [mapOfEq_mapOfEq_of_comp_eq_const h₂ he₁ h12 g, mapOfEq_mapOfEq_of_comp_eq h₂ he₂ hc h22 g,
    map_one W, hW]

/-- **Unit retraction lemma.** `ker ρ` is a complement in `π_1(T, t₀)` of the subgroup generated
by the two torus loops. -/
theorem isCompl_closure_torusLoops (W : FundamentalGroup U u₀ →* Multiplicative ℤ)
    {e₁ e₂ : C(T, U)} (he₁ : e₁ t₀ = u₀) (he₂ : e₂ t₀ = u₀) {ℓ₁ ℓ₂ : C(S, T)}
    (h₁ : ℓ₁ s₀ = t₀) (h₂ : ℓ₂ s₀ = t₀) {c : C(S, U)} (hc : c s₀ = u₀)
    (g : FundamentalGroup S s₀) (hW : W (FundamentalGroup.mapOfEq c hc g) = ofAdd (1 : ℤ))
    (h11 : e₁.comp ℓ₁ = c) (h12 : e₁.comp ℓ₂ = ContinuousMap.const S u₀)
    (h21 : e₂.comp ℓ₁ = ContinuousMap.const S u₀) (h22 : e₂.comp ℓ₂ = c)
    (hcomm : Commute (FundamentalGroup.mapOfEq ℓ₁ h₁ g) (FundamentalGroup.mapOfEq ℓ₂ h₂ g)) :
    IsCompl
      (Subgroup.closure {FundamentalGroup.mapOfEq ℓ₁ h₁ g, FundamentalGroup.mapOfEq ℓ₂ h₂ g})
      (torusRetraction W e₁ e₂ he₁ he₂).ker :=
  isCompl_closure_pair_ker _ _ hcomm _ (torusRetraction_loop₁ W he₁ he₂ h₁ hc g hW h11 h21)
    (torusRetraction_loop₂ W he₁ he₂ h₂ hc g hW h12 h22)

/-- The summand is `ℤ²`: `(m, n) ↦ ℓ_1^m ℓ_2^n` is injective. -/
theorem torusLoops_injective (W : FundamentalGroup U u₀ →* Multiplicative ℤ) {e₁ e₂ : C(T, U)}
    (he₁ : e₁ t₀ = u₀) (he₂ : e₂ t₀ = u₀) {ℓ₁ ℓ₂ : C(S, T)} (h₁ : ℓ₁ s₀ = t₀)
    (h₂ : ℓ₂ s₀ = t₀) {c : C(S, U)} (hc : c s₀ = u₀) (g : FundamentalGroup S s₀)
    (hW : W (FundamentalGroup.mapOfEq c hc g) = ofAdd (1 : ℤ)) (h11 : e₁.comp ℓ₁ = c)
    (h12 : e₁.comp ℓ₂ = ContinuousMap.const S u₀) (h21 : e₂.comp ℓ₁ = ContinuousMap.const S u₀)
    (h22 : e₂.comp ℓ₂ = c)
    (hcomm : Commute (FundamentalGroup.mapOfEq ℓ₁ h₁ g) (FundamentalGroup.mapOfEq ℓ₂ h₂ g)) :
    Function.Injective (pairHom _ _ hcomm) :=
  pairHom_injective _ _ hcomm _ (torusRetraction_loop₁ W he₁ he₂ h₁ hc g hW h11 h21)
    (torusRetraction_loop₂ W he₁ he₂ h₂ hc g hW h12 h22)

end RotationAlgebra
end GroupApproximation
