import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Tactic.Group

/-!
# The explicit linear model for the eight-generator non-MF group

The explicit non-MF group has eight generators. Its consistency witness is a
linear model:
the six base generators are realized by explicit integer matrices in
`GL₄(ℚ)` (block form `[[A, v], [0, 1]]` for the affine action of
`SL₃(ℤ)` on `ℤ³`), and the stable letter by the doubling matrix
`D = diag(2,2,2,1)`.  This file records the model and the three facts the
witness construction consumes:

* the twenty base relations of the displayed presentation hold for the matrices;
* conjugation by `D` is an injective endomorphism `conjD` of the subgroup
  `gammaBar` generated by the six matrices, squaring the translation
  generators and fixing the rotation generators; and
* the marked generator `v₁` is **not** in the range of `conjD`, by the
  integrality invariant: every element of `gammaBar` has integer entries,
  while `D⁻¹ v₁ D` has a `1/2` entry.

No completeness statement for any presentation is used or asserted here;
this is pure matrix algebra over `ℚ`.
-/

namespace GroupApproximation
namespace ExplicitLinearModel

open Matrix

/-- The ambient matrix ring of the model. -/
abbrev Mat : Type := Matrix (Fin 4) (Fin 4) ℚ

/-- The rotation generator `x`: the 3-cycle permutation matrix, extended by
`1`. -/
def xM : Mat := !![0,1,0,0; 0,0,1,0; 1,0,0,0; 0,0,0,1]

/-- The rotation generator `y`. -/
def yM : Mat := !![1,0,1,0; 0,-1,-1,0; 0,1,0,0; 0,0,0,1]

/-- The rotation generator `z`. -/
def zM : Mat := !![0,1,0,0; 1,0,0,0; -1,-1,-1,0; 0,0,0,1]

/-- The translation generator `v₁`. -/
def v1M : Mat := !![1,0,0,1; 0,1,0,0; 0,0,1,0; 0,0,0,1]

/-- The translation generator `v₂`. -/
def v2M : Mat := !![1,0,0,0; 0,1,0,1; 0,0,1,0; 0,0,0,1]

/-- The translation generator `v₃`. -/
def v3M : Mat := !![1,0,0,0; 0,1,0,0; 0,0,1,1; 0,0,0,1]

/-- The doubling matrix `D`. -/
def dM : Mat := !![2,0,0,0; 0,2,0,0; 0,0,2,0; 0,0,0,1]

/-- The inverse of the doubling matrix. -/
def dInvM : Mat := !![1/2,0,0,0; 0,1/2,0,0; 0,0,1/2,0; 0,0,0,1]

/-- The inverse of `v₁`. -/
def v1InvM : Mat := !![1,0,0,-1; 0,1,0,0; 0,0,1,0; 0,0,0,1]

/-- The inverse of `v₂`. -/
def v2InvM : Mat := !![1,0,0,0; 0,1,0,-1; 0,0,1,0; 0,0,0,1]

/-- The inverse of `v₃`. -/
def v3InvM : Mat := !![1,0,0,0; 0,1,0,0; 0,0,1,-1; 0,0,0,1]

/-- Close an equality between the explicit `4 × 4` rational matrices by
checking its sixteen scalar entries in the kernel. -/
macro "verify_explicit_matrix" : tactic =>
  `(tactic|
    exact Matrix.ext fun i j => by
      fin_cases i <;> fin_cases j <;>
        norm_num [Matrix.mul_apply, Matrix.one_apply, Fin.sum_univ_succ, xM, yM, zM,
          v1M, v2M, v3M, dM, dInvM, v1InvM, v2InvM, v3InvM] <;> simp)

/-! ## The unit-group inverses

The rotation generators have small orders, so their inverses are positive
words: `x⁻¹ = x²`, `y⁻¹ = y²`, `z⁻¹ = z`. -/

theorem xM_orderThree : xM * (xM * xM) = 1 := by verify_explicit_matrix
theorem xM_orderThree' : (xM * xM) * xM = 1 := by verify_explicit_matrix
theorem yM_orderThree : yM * (yM * yM) = 1 := by verify_explicit_matrix
theorem yM_orderThree' : (yM * yM) * yM = 1 := by verify_explicit_matrix
theorem zM_orderTwo : zM * zM = 1 := by verify_explicit_matrix
theorem v1M_inv : v1M * v1InvM = 1 := by verify_explicit_matrix
theorem v1M_inv' : v1InvM * v1M = 1 := by verify_explicit_matrix
theorem v2M_inv : v2M * v2InvM = 1 := by verify_explicit_matrix
theorem v2M_inv' : v2InvM * v2M = 1 := by verify_explicit_matrix
theorem v3M_inv : v3M * v3InvM = 1 := by verify_explicit_matrix
theorem v3M_inv' : v3InvM * v3M = 1 := by verify_explicit_matrix
theorem dM_inv : dM * dInvM = 1 := by verify_explicit_matrix
theorem dM_inv' : dInvM * dM = 1 := by verify_explicit_matrix

/-- `x` as a unit. -/
def xU : Matˣ := ⟨xM, xM * xM, xM_orderThree, xM_orderThree'⟩

/-- `y` as a unit. -/
def yU : Matˣ := ⟨yM, yM * yM, yM_orderThree, yM_orderThree'⟩

/-- `z` as a unit. -/
def zU : Matˣ := ⟨zM, zM, zM_orderTwo, zM_orderTwo⟩

/-- `v₁` as a unit. -/
def v1U : Matˣ := ⟨v1M, v1InvM, v1M_inv, v1M_inv'⟩

/-- `v₂` as a unit. -/
def v2U : Matˣ := ⟨v2M, v2InvM, v2M_inv, v2M_inv'⟩

/-- `v₃` as a unit. -/
def v3U : Matˣ := ⟨v3M, v3InvM, v3M_inv, v3M_inv'⟩

/-- `D` as a unit. -/
def dU : Matˣ := ⟨dM, dInvM, dM_inv, dM_inv'⟩

/-! ## The twenty base relations

The eight relations of the displayed `SL₃(ℤ)` presentation
(`eq:sl3presentation`), with the negative letters eliminated through
`x⁻¹ = x²`, `y⁻¹ = y²`, `z⁻¹ = z`; the three commutation relations among
the translations; and the nine action relations, in the inverse-free form
`g · vᵢ = (target) · g`. -/

theorem rel_xz_cube : (xM * zM) * (xM * zM) * (xM * zM) = 1 := by
  verify_explicit_matrix
theorem rel_yz_cube : (yM * zM) * (yM * zM) * (yM * zM) = 1 := by
  verify_explicit_matrix
theorem rel_xzxy_sq :
    (xM * xM * zM * xM * yM) * (xM * xM * zM * xM * yM) = 1 := by
  verify_explicit_matrix
theorem rel_yzyx_sq :
    (yM * yM * zM * yM * xM) * (yM * yM * zM * yM * xM) = 1 := by
  verify_explicit_matrix
theorem rel_xy_six :
    ((xM * yM) * (xM * yM) * (xM * yM)) *
      ((xM * yM) * (xM * yM) * (xM * yM)) = 1 := by
  verify_explicit_matrix

theorem rel_v12 : v1M * v2M = v2M * v1M := by verify_explicit_matrix
theorem rel_v13 : v1M * v3M = v3M * v1M := by verify_explicit_matrix
theorem rel_v23 : v2M * v3M = v3M * v2M := by verify_explicit_matrix

theorem rel_x_v1 : xM * v1M = v3M * xM := by verify_explicit_matrix
theorem rel_x_v2 : xM * v2M = v1M * xM := by verify_explicit_matrix
theorem rel_x_v3 : xM * v3M = v2M * xM := by verify_explicit_matrix
theorem rel_y_v1 : yM * v1M = v1M * yM := by verify_explicit_matrix
theorem rel_y_v2 : yM * v2M = v2InvM * v3M * yM := by verify_explicit_matrix
theorem rel_y_v3 : yM * v3M = v1M * v2InvM * yM := by verify_explicit_matrix
theorem rel_z_v1 : zM * v1M = v2M * v3InvM * zM := by verify_explicit_matrix
theorem rel_z_v2 : zM * v2M = v1M * v3InvM * zM := by verify_explicit_matrix
theorem rel_z_v3 : zM * v3M = v3InvM * zM := by verify_explicit_matrix

/-! ## The doubling conjugation -/

theorem rel_d_x : dM * xM = xM * dM := by verify_explicit_matrix
theorem rel_d_y : dM * yM = yM * dM := by verify_explicit_matrix
theorem rel_d_z : dM * zM = zM * dM := by verify_explicit_matrix
theorem rel_d_v1 : dM * v1M = v1M * v1M * dM := by verify_explicit_matrix
theorem rel_d_v2 : dM * v2M = v2M * v2M * dM := by verify_explicit_matrix
theorem rel_d_v3 : dM * v3M = v3M * v3M * dM := by verify_explicit_matrix

/-- The moved marked generator: `D⁻¹ v₁ D` has the non-integral entry
`1/2`. -/
theorem dInv_v1_d_entry : (dInvM * v1M * dM) 0 3 = 1 / 2 := by
  simp [Matrix.mul_apply, Fin.sum_univ_succ, dInvM, v1M, dM]

/-! ## The base subgroup and its integrality invariant -/

/-- The base subgroup: the copy of (the image of) `Γ` inside `GL₄(ℚ)`. -/
def gammaBar : Subgroup Matˣ :=
  Subgroup.closure {xU, yU, zU, v1U, v2U, v3U}

/-- A matrix has integer entries when each entry lies in the image of
`ℤ`. -/
def IsIntegral (m : Mat) : Prop :=
  ∀ i j, m i j ∈ (Int.castRingHom ℚ).range

theorem isIntegral_one : IsIntegral 1 := by
  intro i j
  by_cases h : i = j
  · subst h
    rw [Matrix.one_apply_eq]
    exact ⟨1, by norm_num⟩
  · rw [Matrix.one_apply_ne h]
    exact ⟨0, by norm_num⟩

theorem isIntegral_mul {m n : Mat} (hm : IsIntegral m) (hn : IsIntegral n) :
    IsIntegral (m * n) := by
  intro i j
  rw [Matrix.mul_apply]
  exact Subring.sum_mem _ fun k _ =>
    Subring.mul_mem _ (hm i k) (hn k j)

/-- Integrality of both a unit and its inverse, the invariant preserved by
the subgroup operations. -/
def IsIntegralUnit (u : Matˣ) : Prop :=
  IsIntegral (u : Mat) ∧ IsIntegral ((u⁻¹ : Matˣ) : Mat)

theorem isIntegralUnit_one : IsIntegralUnit 1 :=
  ⟨by simpa using isIntegral_one, by simpa using isIntegral_one⟩

theorem isIntegralUnit_mul {u v : Matˣ} (hu : IsIntegralUnit u)
    (hv : IsIntegralUnit v) : IsIntegralUnit (u * v) := by
  refine ⟨?_, ?_⟩
  · simpa using isIntegral_mul hu.1 hv.1
  · rw [mul_inv_rev]
    simpa using isIntegral_mul hv.2 hu.2

theorem isIntegralUnit_inv {u : Matˣ} (hu : IsIntegralUnit u) :
    IsIntegralUnit u⁻¹ := by
  refine ⟨hu.2, ?_⟩
  simpa using hu.1

/-- Entry-level integrality check for the explicit generators. -/
theorem isIntegral_of_decide {m : Mat}
    (h : ∀ i j, (m i j).den = 1) : IsIntegral m := by
  intro i j
  exact ⟨(m i j).num, (Rat.den_eq_one_iff (m i j)).mp (h i j)⟩

/-- Verify integrality of an explicit matrix unit and its displayed inverse
entry by entry. -/
macro "verify_explicit_integral_unit" : tactic =>
  `(tactic|
    constructor <;> apply isIntegral_of_decide <;>
      intro i j <;> fin_cases i <;> fin_cases j <;>
        norm_num [xU, yU, zU, v1U, v2U, v3U, xM, yM, zM,
          v1M, v2M, v3M, v1InvM, v2InvM, v3InvM,
          Matrix.mul_apply, Fin.sum_univ_succ])

theorem generators_isIntegralUnit :
    ∀ u ∈ ({xU, yU, zU, v1U, v2U, v3U} : Set Matˣ), IsIntegralUnit u := by
  intro u hu
  have hx : IsIntegralUnit xU := by
    verify_explicit_integral_unit
  have hy : IsIntegralUnit yU := by
    verify_explicit_integral_unit
  have hz : IsIntegralUnit zU := by
    verify_explicit_integral_unit
  have hv1 : IsIntegralUnit v1U := by
    verify_explicit_integral_unit
  have hv2 : IsIntegralUnit v2U := by
    verify_explicit_integral_unit
  have hv3 : IsIntegralUnit v3U := by
    verify_explicit_integral_unit
  rcases hu with h | h | h | h | h | h
  · exact h ▸ hx
  · exact h ▸ hy
  · exact h ▸ hz
  · exact h ▸ hv1
  · exact h ▸ hv2
  · exact h ▸ hv3

/-- Every element of the base subgroup has integer entries, together with
its inverse. -/
theorem gammaBar_isIntegralUnit {u : Matˣ} (hu : u ∈ gammaBar) :
    IsIntegralUnit u := by
  induction hu using Subgroup.closure_induction with
  | mem u hu => exact generators_isIntegralUnit u hu
  | one => exact isIntegralUnit_one
  | mul u v _ _ hu hv => exact isIntegralUnit_mul hu hv
  | inv u _ hu => exact isIntegralUnit_inv hu

/-! ## Conjugation by the doubling matrix -/

theorem dU_conj_mem {u : Matˣ} (hu : u ∈ gammaBar) :
    dU * u * dU⁻¹ ∈ gammaBar := by
  induction hu using Subgroup.closure_induction with
  | mem u hu =>
      have hx : dU * xU * dU⁻¹ = xU := by
        apply Units.ext
        change dM * xM * dInvM = xM
        rw [rel_d_x, mul_assoc]
        show xM * (dM * dInvM) = xM
        rw [dM_inv, mul_one]
      have hy : dU * yU * dU⁻¹ = yU := by
        apply Units.ext
        change dM * yM * dInvM = yM
        rw [rel_d_y, mul_assoc]
        show yM * (dM * dInvM) = yM
        rw [dM_inv, mul_one]
      have hz : dU * zU * dU⁻¹ = zU := by
        apply Units.ext
        change dM * zM * dInvM = zM
        rw [rel_d_z, mul_assoc]
        show zM * (dM * dInvM) = zM
        rw [dM_inv, mul_one]
      have hv1 : dU * v1U * dU⁻¹ = v1U * v1U := by
        apply Units.ext
        change dM * v1M * dInvM = v1M * v1M
        rw [rel_d_v1, mul_assoc]
        show v1M * v1M * (dM * dInvM) = v1M * v1M
        rw [dM_inv, mul_one]
      have hv2 : dU * v2U * dU⁻¹ = v2U * v2U := by
        apply Units.ext
        change dM * v2M * dInvM = v2M * v2M
        rw [rel_d_v2, mul_assoc]
        show v2M * v2M * (dM * dInvM) = v2M * v2M
        rw [dM_inv, mul_one]
      have hv3 : dU * v3U * dU⁻¹ = v3U * v3U := by
        apply Units.ext
        change dM * v3M * dInvM = v3M * v3M
        rw [rel_d_v3, mul_assoc]
        show v3M * v3M * (dM * dInvM) = v3M * v3M
        rw [dM_inv, mul_one]
      rcases hu with h | h | h | h | h | h
      · subst h; rw [hx]; exact Subgroup.subset_closure (by simp)
      · subst h; rw [hy]
        exact Subgroup.subset_closure (by simp)
      · subst h; rw [hz]
        exact Subgroup.subset_closure (by simp)
      · subst h; rw [hv1]
        exact Subgroup.mul_mem _ (Subgroup.subset_closure (by simp))
          (Subgroup.subset_closure (by simp))
      · subst h; rw [hv2]
        exact Subgroup.mul_mem _ (Subgroup.subset_closure (by simp))
          (Subgroup.subset_closure (by simp))
      · subst h; rw [hv3]
        exact Subgroup.mul_mem _ (Subgroup.subset_closure (by simp))
          (Subgroup.subset_closure (by simp))
  | one => simp
  | mul u v _ _ hu hv =>
      have h : dU * (u * v) * dU⁻¹ = (dU * u * dU⁻¹) * (dU * v * dU⁻¹) := by
        group
      rw [h]
      exact Subgroup.mul_mem _ hu hv
  | inv u _ hu =>
      have h : dU * u⁻¹ * dU⁻¹ = (dU * u * dU⁻¹)⁻¹ := by group
      rw [h]
      exact Subgroup.inv_mem _ hu

/-- Conjugation by `D` as an endomorphism of the base subgroup. -/
def conjD : gammaBar →* gammaBar where
  toFun u := ⟨dU * u * dU⁻¹, dU_conj_mem u.2⟩
  map_one' := by
    apply Subtype.ext
    change dU * 1 * dU⁻¹ = 1
    group
  map_mul' u v := Subtype.ext (by
    show dU * (↑u * ↑v) * dU⁻¹ = (dU * ↑u * dU⁻¹) * (dU * ↑v * dU⁻¹)
    group)

theorem conjD_injective : Function.Injective conjD := by
  intro u v h
  have h' : dU * (u : Matˣ) * dU⁻¹ = dU * (v : Matˣ) * dU⁻¹ :=
    congrArg Subtype.val h
  exact Subtype.ext (mul_left_cancel (mul_right_cancel h'))

/-- The marked generator, as an element of the base subgroup. -/
def v1G : gammaBar := ⟨v1U, Subgroup.subset_closure (by simp)⟩

/-- The rotation generators, as elements of the base subgroup. -/
def xG : gammaBar := ⟨xU, Subgroup.subset_closure (by simp)⟩

def yG : gammaBar := ⟨yU, Subgroup.subset_closure (by simp)⟩

def zG : gammaBar := ⟨zU, Subgroup.subset_closure (by simp)⟩

def v2G : gammaBar := ⟨v2U, Subgroup.subset_closure (by simp)⟩

def v3G : gammaBar := ⟨v3U, Subgroup.subset_closure (by simp)⟩

/-- **The marked generator escapes the doubled copy.**  `v₁` is not in the
range of conjugation by `D`, because a preimage would be the non-integral
matrix `D⁻¹ v₁ D`. -/
theorem v1G_not_mem_range : v1G ∉ Set.range conjD := by
  rintro ⟨g, hg⟩
  have hval : dU * (g : Matˣ) * dU⁻¹ = v1U := Subtype.ext_iff.mp hg
  have hgval : (g : Matˣ) = dU⁻¹ * v1U * dU := by
    rw [← hval]
    group
  have hint : IsIntegral ((g : Matˣ) : Mat) := (gammaBar_isIntegralUnit g.2).1
  rw [hgval] at hint
  have hentry : (((dU⁻¹ * v1U * dU : Matˣ) : Mat)) 0 3 = 1 / 2 := by
    show (dInvM * v1M * dM) 0 3 = 1 / 2
    exact dInv_v1_d_entry
  obtain ⟨k, hk⟩ := hint 0 3
  rw [hentry] at hk
  have h2k : (2 * k : ℤ) = 1 := by
    have h2 : ((2 * k : ℤ) : ℚ) = 1 := by
      change (k : ℚ) = 1 / 2 at hk
      norm_num [Int.cast_mul, hk]
    exact_mod_cast h2
  omega

/-! ## Countability -/

end ExplicitLinearModel
end GroupApproximation
