import GroupApproximation.Algebra.AmenableConstructions
import GroupApproximation.Algebra.DyadicRationals
import GroupApproximation.Monsters.CliffordLampLocallyFinite
import GroupApproximation.Monsters.CyclicBaseLEFObstruction
import GroupApproximation.Monsters.LiteralCyclicCalibration
import Mathlib.GroupTheory.GroupAction.Quotient
import Mathlib.GroupTheory.Solvable

/-!
# The cyclic comparison in the literal affine group `ℤ[1/2] ⋊ ℤ`

The manuscript's proof of Theorem `\ref{thm:cyclic}` (cited as `thm:C` in older
notes; that alias is no longer a `\label`), inside
`\section{The cyclic comparison}` (`\ref{sec:necessity}`) of
`non_mf_groups_exist.tex`, reads:

> For nontriviality, use the affine realization of `BS(1,2)` and its coset
> action.  The root site is fixed by the cyclic base, while the two sites
> represented by `t` and `γ₀t` are distinct.  Attach Clifford generators to
> these sites and map `c` to the root lamp.  All seven relators hold, and
> `w_BS ↦ [c_{t⟨γ₀⟩}, c_{γ₀t⟨γ₀⟩}] = -1`.

This file runs exactly that argument in exactly that group.  The ambient group
is `DyadicRationals.Affine = ℤ[1/2] ⋊ ℤ`, proved isomorphic to the presented
group `BS(1,2) = ⟨a, t | t a t⁻¹ = a²⟩` in `Algebra.DyadicRationals`; the sites
are the literal left cosets of the cyclic base `⟨γ₀⟩`; the lamps are the
literal Clifford generators indexed by those cosets.

`Monsters.CyclicBaseCalibration` runs the same calculation in the larger
ambient group `ℚ ⋊ ℤ` and says so in its own header.  That module is left
untouched and stands as the rational-overgroup auxiliary; this one is the
manuscript's group.

The presentation `E_BS` itself is ambient-free, so it is *not* duplicated: the
seven relators, the marked word `w_BS`, and the presented group are the ones
already formalized in `Monsters.LiteralCyclicCalibration`, and so is the
finite-dimensional kill (`LiteralCyclicCalibration.finiteDimensional_kill`),
which uses only the stable relation and the lamp commutation.  What is new
here is the *literal* nontriviality witness and the literal realized quotient,
together with the amenability chain of the sharpness paragraph.

As in `Sofic.CliffordBSAmenable`, the final step of that paragraph -- amenable
implies MF, Tikuisis--White--Winter -- is not proved and cannot be proved here;
everything before it is.
-/

set_option linter.unusedSectionVars false

namespace GroupApproximation
namespace LiteralDyadicCalibration

open scoped commutatorElement
open Amenability
open CliffordAlgebraLamp
open DyadicRationals
open LiteralCyclicCalibration

noncomputable section

/-! ## The literal cyclic base and its coset space -/

/-- The cyclic base `⟨γ₀⟩` inside `ℤ[1/2] ⋊ ℤ`: the copy of `ℤ` generated by
translation by `1`. -/
def Gamma0 : Subgroup Affine := Subgroup.zpowers gammaZero

/-- **The literal site set**: the coset space `BS(1,2)/⟨γ₀⟩`. -/
abbrev Sites : Type := Affine ⧸ Gamma0

/-- The root site `⟨γ₀⟩`. -/
def basepoint : Sites := QuotientGroup.mk 1

/-- **The root site is fixed by the cyclic base.** -/
theorem gammaZero_smul_basepoint : gammaZero • basepoint = basepoint := by
  rw [basepoint, MulAction.Quotient.smul_mk, smul_eq_mul, mul_one]
  exact (QuotientGroup.eq).mpr
    (by rw [mul_one]; exact Gamma0.inv_mem (Subgroup.mem_zpowers gammaZero))

/-- **The two lamp sites of the marked word are distinct**: `t⟨γ₀⟩ ≠ γ₀t⟨γ₀⟩`.
Concretely, equality would force `2n = -1` in `ℤ`, because `t⁻¹γ₀t` is
translation by `1/2`, which is not an integer translation. -/
theorem gammaZero_moves :
    gammaZero • (tZero • basepoint) ≠ tZero • basepoint := by
  intro h
  rw [smul_smul, basepoint, MulAction.Quotient.smul_mk,
    MulAction.Quotient.smul_mk, smul_eq_mul, smul_eq_mul, mul_one,
    mul_one] at h
  obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp ((QuotientGroup.eq).mp h)
  -- `hn : γ₀ ^ n = (γ₀ t)⁻¹ t`, so conjugating by `t` gives `γ₀ ^ (2n) = γ₀⁻¹`.
  have hconj : tZero * gammaZero ^ n * tZero⁻¹ = gammaZero⁻¹ := by
    rw [hn, mul_inv_rev]
    calc tZero * (tZero⁻¹ * gammaZero⁻¹ * tZero) * tZero⁻¹
        = tZero * tZero⁻¹ * gammaZero⁻¹ * (tZero * tZero⁻¹) := by
          simp only [mul_assoc]
      _ = gammaZero⁻¹ := by rw [mul_inv_cancel, one_mul, mul_one]
  have h2n : gammaZero ^ (2 * n) = gammaZero⁻¹ := by
    rw [← conj_zpow_of_rel conj_gammaZero n]
    exact hconj
  have hone : gammaZero ^ (2 * n + 1) = 1 := by
    rw [zpow_add_one, h2n, inv_mul_cancel]
  have hz : ((2 * n + 1 : ℤ) : ℚ) = 0 := by
    have h1 : SemidirectProduct.inl (Multiplicative.ofAdd (ofInt (2 * n + 1)))
        = (1 : Affine) := by
      rw [← gammaZero_zpow, hone]
    have h2 : Multiplicative.ofAdd (ofInt (2 * n + 1))
        = (1 : Multiplicative DyadicRationals.Dyadic) := by
      have h1' : (SemidirectProduct.inl
            (Multiplicative.ofAdd (ofInt (2 * n + 1))) : Affine)
          = SemidirectProduct.inl 1 := by
        rw [h1, map_one]
      exact SemidirectProduct.inl_injective h1'
    have h3 : ofInt (2 * n + 1) = (0 : DyadicRationals.Dyadic) :=
      congrArg Multiplicative.toAdd h2
    exact congrArg (fun d : DyadicRationals.Dyadic => (d : ℚ)) h3
  have hz' : 2 * n + 1 = 0 := by exact_mod_cast hz
  omega

/-- The two sites of the marked word, in the manuscript's order. -/
theorem marked_sites_ne :
    tZero • basepoint ≠ (gammaZero * tZero) • basepoint := by
  intro h
  exact gammaZero_moves (by simpa only [smul_smul] using h.symm)

/-! ## The literal Clifford lamp extension -/

/-- The left action of `ℤ[1/2] ⋊ ℤ` on its coset space, transported to the
Clifford lamp group by relabelling lamp sites. -/
noncomputable def lampAction : Affine →* MulAut (lampGroup Sites) :=
  (permHom Sites).comp (MulAction.toPermHom Affine Sites)

/-- The action relabels the lamps along the coset action. -/
@[simp] theorem lampAction_lampGen (g : Affine) (x : Sites) :
    lampAction g (lampGen Sites x) = lampGen Sites (g • x) := by
  change permHom Sites (MulAction.toPermHom Affine Sites g)
      (lampGen Sites x) = lampGen Sites (g • x)
  rw [permHom_lampGen]
  rfl

/-- The action fixes the Clifford sign. -/
@[simp] theorem lampAction_zGen (g : Affine) :
    lampAction g (zGen Sites) = zGen Sites := by
  change permHom Sites (MulAction.toPermHom Affine Sites g) (zGen Sites) = _
  exact permHom_zGen Sites _

/-- **The literal Clifford lamp extension** of the affine group:
`lamps(BS(1,2)/⟨γ₀⟩) ⋊ (ℤ[1/2] ⋊ ℤ)`. -/
noncomputable abbrev CliffordDyadic : Type :=
  SemidirectProduct (lampGroup Sites) Affine lampAction

/-- The group structure on the literal Clifford extension. -/
noncomputable instance : Group CliffordDyadic :=
  inferInstanceAs (Group (SemidirectProduct (lampGroup Sites) Affine lampAction))

/-- The cyclic base generator inside the Clifford extension. -/
noncomputable def gammaD : CliffordDyadic := SemidirectProduct.inr gammaZero

/-- The stable letter inside the Clifford extension. -/
noncomputable def tD : CliffordDyadic := SemidirectProduct.inr tZero

/-- The root Clifford lamp, the image of `c`. -/
noncomputable def cD : CliffordDyadic :=
  SemidirectProduct.inl (lampGen Sites basepoint)

/-- The surviving central Clifford sign. -/
noncomputable def zD : CliffordDyadic := SemidirectProduct.inl (zGen Sites)

/-- Conjugation by a base-group element relabels a Clifford lamp. -/
theorem conj_lamp (g : Affine) (x : Sites) :
    (SemidirectProduct.inr g : CliffordDyadic) *
        SemidirectProduct.inl (lampGen Sites x) *
          (SemidirectProduct.inr g)⁻¹ =
      SemidirectProduct.inl (lampGen Sites (g • x)) := by
  rw [← map_inv, ← SemidirectProduct.inl_aut, lampAction_lampGen]

/-- The cyclic base generator fixes the root lamp. -/
theorem gammaD_conj_cD : gammaD * cD * gammaD⁻¹ = cD := by
  rw [gammaD, cD, conj_lamp, gammaZero_smul_basepoint]

/-- The root lamp commutes with the cyclic base generator. -/
theorem cD_comm_gammaD : Commute cD gammaD := by
  have h : gammaD * cD = cD * gammaD :=
    mul_inv_eq_iff_eq_mul.mp gammaD_conj_cD
  exact h.symm

/-- The stable letter compresses the cyclic base generator by doubling. -/
theorem tD_conj_gammaD : tD * gammaD * tD⁻¹ = gammaD ^ 2 := by
  show SemidirectProduct.inr tZero * SemidirectProduct.inr gammaZero *
      (SemidirectProduct.inr tZero : CliffordDyadic)⁻¹ =
        (SemidirectProduct.inr gammaZero : CliffordDyadic) ^ 2
  rw [← map_inv, ← map_mul, ← map_mul, conj_gammaZero, map_pow]

/-- **The manuscript's displayed evaluation**: the marked word maps to the
commutator of the two lamps at the sites `t⟨γ₀⟩` and `γ₀t⟨γ₀⟩`, which is the
Clifford sign. -/
theorem markedWord_eq_zD :
    markedCompressionWord tD gammaD cD = zD := by
  have ht : tD * cD * tD⁻¹ =
      SemidirectProduct.inl (lampGen Sites (tZero • basepoint)) := by
    rw [tD, cD, conj_lamp]
  have hgt : gammaD *
      SemidirectProduct.inl (lampGen Sites (tZero • basepoint)) * gammaD⁻¹ =
        SemidirectProduct.inl
          (lampGen Sites ((gammaZero * tZero) • basepoint)) := by
    rw [gammaD, conj_lamp, smul_smul]
  rw [markedCompressionWord, ht, hgt, ← map_commutatorElement,
    commutator_lampGen Sites marked_sites_ne]
  rfl

/-- The marked sign is nontrivial. -/
theorem zD_ne_one : zD ≠ 1 := by
  intro h
  apply zGen_ne_one Sites
  have hleft := congrArg SemidirectProduct.left h
  simpa [zD] using hleft

/-- **`w_BS ≠ 1`** in the literal affine witness. -/
theorem markedWord_ne_one :
    markedCompressionWord tD gammaD cD ≠ 1 := by
  rw [markedWord_eq_zD]
  exact zD_ne_one

/-- The surviving sign has order two. -/
theorem zD_sq : zD ^ 2 = 1 := by
  rw [zD, ← map_pow, zGen_sq, map_one]

/-- The surviving sign is central in the whole extension. -/
theorem zD_central (g : CliffordDyadic) : Commute zD g := by
  obtain ⟨n, v⟩ := g
  show zD * ⟨n, v⟩ = ⟨n, v⟩ * zD
  show (⟨zGen Sites, 1⟩ : CliffordDyadic) * ⟨n, v⟩ =
    ⟨n, v⟩ * ⟨zGen Sites, 1⟩
  apply SemidirectProduct.ext
  · change zGen Sites * lampAction 1 n = n * lampAction v (zGen Sites)
    rw [map_one, lampAction_zGen]
    exact ((Subgroup.mem_center_iff.mp (zGen_mem_center Sites)) n).symm
  · change (1 : Affine) * v = v * 1
    simp

/-- The marked word is an involution. -/
theorem markedWord_sq : markedCompressionWord tD gammaD cD ^ 2 = 1 := by
  rw [markedWord_eq_zD]
  exact zD_sq

/-- The marked word is central in the extension. -/
theorem markedWord_central (g : CliffordDyadic) :
    Commute (markedCompressionWord tD gammaD cD) g := by
  rw [markedWord_eq_zD]
  exact zD_central g

/-! ## The seven relators, and the literal realized quotient

The presentation is the one already formalized in
`Monsters.LiteralCyclicCalibration`; only the target changes. -/

/-- The three displayed images: `γ₀ ↦ γ₀`, `t ↦ t`, `c ↦` the root lamp. -/
noncomputable def dyadicTarget : Generator → CliffordDyadic
  | 0 => gammaD
  | 1 => tD
  | 2 => cD

/-- The image of the letter `γ₀`. -/
@[simp] theorem dyadicTarget_gamma : dyadicTarget gammaIndex = gammaD := rfl
/-- The image of the letter `t`. -/
@[simp] theorem dyadicTarget_stable : dyadicTarget stableIndex = tD := rfl
/-- The image of the letter `c`. -/
@[simp] theorem dyadicTarget_lamp : dyadicTarget lampIndex = cD := rfl

/-- The marked free word evaluates to the marked compression word. -/
theorem dyadicTarget_eval_marked :
    FreeGroup.lift dyadicTarget markedWord =
      markedCompressionWord tD gammaD cD := by
  simp [markedWord, displacedLampWord, commutatorWord,
    markedCompressionWord, commutatorElement_def]

/-- **All seven relators hold** in the literal affine Clifford model. -/
theorem dyadicTarget_kills_relators :
    ∀ r ∈ relators, FreeGroup.lift dyadicTarget r = 1 := by
  intro r hr
  simp [relators] at hr
  rcases hr with rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · simpa only [stableRelator, stableWord, gammaWord, map_mul, map_inv,
      map_pow, FreeGroup.lift_apply_of, dyadicTarget_stable,
      dyadicTarget_gamma] using mul_inv_eq_one.mpr tD_conj_gammaD
  · simp only [lampSqRelator, lampWord, map_pow, FreeGroup.lift_apply_of,
      dyadicTarget_lamp]
    rw [cD, ← map_pow, CliffordAlgebraLamp.lampGen_sq, map_one]
  · simpa only [lampGammaRelator, lampWord, gammaWord, commutatorWord,
      commutatorElement_def, map_mul, map_inv, FreeGroup.lift_apply_of,
      dyadicTarget_lamp, dyadicTarget_gamma] using
        commutatorElement_eq_one_iff_commute.mpr cD_comm_gammaD
  · simpa only [markedSqRelator, markedWord, displacedLampWord,
      commutatorWord, markedCompressionWord, commutatorElement_def,
      stableWord, lampWord, gammaWord, map_mul, map_inv, map_pow,
      FreeGroup.lift_apply_of, dyadicTarget_stable,
      dyadicTarget_lamp, dyadicTarget_gamma] using markedWord_sq
  · simpa only [markedGammaRelator, markedWord, displacedLampWord,
      commutatorWord, markedCompressionWord, commutatorElement_def,
      stableWord, lampWord, gammaWord, map_mul, map_inv,
      FreeGroup.lift_apply_of, dyadicTarget_stable,
      dyadicTarget_lamp, dyadicTarget_gamma] using
        commutatorElement_eq_one_iff_commute.mpr (markedWord_central gammaD)
  · simpa only [markedStableRelator, markedWord, displacedLampWord,
      commutatorWord, markedCompressionWord, commutatorElement_def,
      stableWord, lampWord, gammaWord, map_mul, map_inv,
      FreeGroup.lift_apply_of, dyadicTarget_stable,
      dyadicTarget_lamp, dyadicTarget_gamma] using
        commutatorElement_eq_one_iff_commute.mpr (markedWord_central tD)
  · simpa only [markedLampRelator, markedWord, displacedLampWord,
      commutatorWord, markedCompressionWord, commutatorElement_def,
      stableWord, lampWord, gammaWord, map_mul, map_inv,
      FreeGroup.lift_apply_of, dyadicTarget_stable,
      dyadicTarget_lamp, dyadicTarget_gamma] using
        commutatorElement_eq_one_iff_commute.mpr (markedWord_central cD)

/-- **The literal realization**: the manuscript's `E_BS` maps to the Clifford
lamp extension of the affine group `ℤ[1/2] ⋊ ℤ`. -/
noncomputable def dyadicRealization : LiteralGroup →* CliffordDyadic :=
  PresentedGroup.toGroup dyadicTarget_kills_relators

/-- The realization, on generators. -/
@[simp] theorem dyadicRealization_generator (i : Generator) :
    dyadicRealization (PresentedGroup.of i) = dyadicTarget i :=
  PresentedGroup.toGroup.of _

/-- The realization of the marked element. -/
theorem dyadicRealization_mark :
    dyadicRealization mark = markedCompressionWord tD gammaD cD := by
  change PresentedGroup.toGroup _ (PresentedGroup.mk _ markedWord) = _
  rw [presentedToGroup_mk]
  exact dyadicTarget_eval_marked
/-- The realized quotient of the manuscript: the subgroup of the literal
Clifford extension generated by the three displayed images. -/
abbrev DyadicRealizedQuotient : Type := dyadicRealization.range

/-- The manuscript's surjection onto the realized quotient. -/
noncomputable def dyadicQuotientMap : LiteralGroup →* DyadicRealizedQuotient :=
  dyadicRealization.rangeRestrict

/-- The realized quotient really is a quotient of `E_BS`. -/
theorem dyadicQuotientMap_surjective : Function.Surjective dyadicQuotientMap :=
  dyadicRealization.rangeRestrict_surjective

/-- The marked element survives in the realized quotient. -/
theorem dyadicQuotientMap_mark_ne_one : dyadicQuotientMap mark ≠ 1 := by
  intro h
  apply markedWord_ne_one
  have hv := congrArg Subtype.val h
  simpa [dyadicQuotientMap, dyadicRealization_mark] using hv

/-- The marked word maps to the distinguished Clifford sign. -/
theorem dyadicQuotientMap_mark_val :
    ((dyadicQuotientMap mark : DyadicRealizedQuotient) : CliffordDyadic)
      = zD := by
  change dyadicRealization mark = zD
  rw [dyadicRealization_mark, markedWord_eq_zD]

/-- Its image in the realized quotient is an involution. -/
theorem dyadicQuotientMap_mark_sq : dyadicQuotientMap mark ^ 2 = 1 := by
  rw [← map_pow, mark_sq, map_one]

/-- Its image in the realized quotient is central. -/
theorem dyadicQuotientMap_mark_central (g : DyadicRealizedQuotient) :
    Commute (dyadicQuotientMap mark) g := by
  apply Subtype.ext
  change ((dyadicQuotientMap mark : DyadicRealizedQuotient) : CliffordDyadic) *
      (g : CliffordDyadic) =
    (g : CliffordDyadic) *
      ((dyadicQuotientMap mark : DyadicRealizedQuotient) : CliffordDyadic)
  rw [dyadicQuotientMap_mark_val]
  exact (zD_central (g : CliffordDyadic)).eq

/-- The realized quotient is countable, being a quotient of the finitely
presented group `E_BS`.  Every operator-MF statement downstream needs this
instance, so it is exported rather than assumed. -/
instance dyadicRealizedQuotient_countable : Countable DyadicRealizedQuotient :=
  dyadicQuotientMap_surjective.countable

/-- The realized quotient is finitely generated. -/
theorem dyadicRealizedQuotient_fg : Group.FG DyadicRealizedQuotient := by
  letI : Group.FG LiteralGroup :=
    Group.fg_of_surjective
      (PresentedGroup.mk_surjective
        ((relators : Finset (FreeGroup Generator)) :
          Set (FreeGroup Generator)))
  exact Group.fg_of_surjective dyadicQuotientMap_surjective

/-! ## No exact finite model, for the literal witness

The manuscript's last paragraph of the section observes that the detecting
corona representation is necessarily approximate: neither `E_BS` nor its
realized Clifford quotient is LEF, because "the same equations transport
through any exact local embedding of a finite test set containing the
defining relators and the marked word".  That test set is built inside
`CyclicBaseLEFObstruction.not_isLEF_of_markedCompression`, which is where the
manuscript's sentence is discharged; for `E_BS` itself the conclusion is
`CyclicBaseLEFObstruction.literalGroup_not_isLEF`, a statement about the
presentation alone.  Here is the literal-model half, the clause "nor its
realized Clifford quotient". -/

/-- The literal Clifford extension admits no exact finite local model. -/
theorem cliffordDyadic_not_isLEF : ¬ IsLEF CliffordDyadic :=
  CyclicBaseLEFObstruction.not_isLEF_of_markedCompression tD gammaD cD
    tD_conj_gammaD cD_comm_gammaD markedWord_ne_one

/-- **The literal realized quotient is not LEF.** -/
theorem dyadicRealizedQuotient_not_isLEF : ¬ IsLEF DyadicRealizedQuotient := by
  refine CyclicBaseLEFObstruction.not_isLEF_of_markedCompression
    (dyadicQuotientMap stable) (dyadicQuotientMap gamma)
    (dyadicQuotientMap lamp) ?_ (lamp_comm_gamma.map dyadicQuotientMap) ?_
  · rw [← map_inv, ← map_mul, ← map_mul, stable_relation, map_pow]
  · rw [← map_markedCompressionWord, ← mark_eq_markedCompressionWord]
    exact dyadicQuotientMap_mark_ne_one

/-- The literal realized quotient is not residually finite. -/
theorem dyadicRealizedQuotient_not_residuallyFinite :
    ¬ Group.ResiduallyFinite DyadicRealizedQuotient := by
  intro h
  haveI := h
  exact dyadicRealizedQuotient_not_isLEF isLEF_of_residuallyFinite

/-! ## The sharpness paragraph: amenability of the literal model

`BS(1,2) ≅ ℤ[1/2] ⋊ ℤ` is solvable (`affine_isSolvable`), and it is amenable.
Amenability is obtained on the nose rather than routed through solvability,
because this repository's amenability API has no "solvable implies amenable"
theorem: `ℤ[1/2]` is the directed union of the cyclic groups generated by
`1/2ⁿ`, hence amenable, and `ℤ` is amenable, so the semidirect product is.
The Clifford lamp group on the coset space is locally finite, hence amenable,
so the extension is amenable and so is every one of its subgroups -- in
particular the realized quotient.  The manuscript's final step, "amenable
hence MF" by Tikuisis--White--Winter, is not formalized anywhere and is *not*
claimed here; `Sofic.CliffordBSAmenable` records that citation explicitly. -/

/-- **The literal affine group is solvable**, as the manuscript asserts: it is
an extension of `ℤ` by the abelian group `ℤ[1/2]`, so the kernel of the
projection to `ℤ` is the abelian image of `ℤ[1/2]`. -/
instance affine_isSolvable : IsSolvable Affine :=
  solvable_of_ker_le_range
    (SemidirectProduct.inl : Multiplicative DyadicRationals.Dyadic →* Affine)
    (SemidirectProduct.rightHom : Affine →* Multiplicative ℤ)
    (le_of_eq
      (SemidirectProduct.range_inl_eq_ker_rightHom (φ := actingHom)).symm)

/-- The generator `1 / 2ⁿ` of the `n`-th step of the exhaustion of
`ℤ[1/2]`. -/
noncomputable def dyadicStep (n : ℕ) : Multiplicative DyadicRationals.Dyadic :=
  Multiplicative.ofAdd (dyadicOf 1 n)

/-- The `n`-th step of the exhaustion of `ℤ[1/2]` by cyclic groups. -/
noncomputable def dyadicK (n : ℕ) : Subgroup (Multiplicative DyadicRationals.Dyadic) :=
  Subgroup.zpowers (dyadicStep n)

/-- Integer powers of the `n`-th step of the exhaustion. -/
theorem dyadicStep_zpow (k : ℤ) (n : ℕ) :
    dyadicStep n ^ k = Multiplicative.ofAdd (dyadicOf k n) := by
  rw [dyadicStep, ← ofAdd_zsmul, zsmul_dyadicOf_one]

/-- Squaring the `(n+1)`-st step returns the `n`-th. -/
theorem dyadicStep_succ (n : ℕ) :
    dyadicStep (n + 1) ^ (2 : ℤ) = dyadicStep n := by
  rw [dyadicStep_zpow, dyadicOf_two_succ, dyadicStep]

/-- The exhaustion is increasing. -/
theorem dyadicK_mono : Monotone dyadicK := by
  refine monotone_nat_of_le_succ fun n ↦ ?_
  intro x hx
  have hx' : x ∈ Subgroup.zpowers (dyadicStep n) := hx
  obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hx'
  show x ∈ Subgroup.zpowers (dyadicStep (n + 1))
  rw [Subgroup.mem_zpowers_iff]
  refine ⟨2 * k, ?_⟩
  rw [zpow_mul, dyadicStep_succ]
  exact hk

/-- The exhaustion covers `ℤ[1/2]`. -/
theorem dyadicK_cover (g : Multiplicative DyadicRationals.Dyadic) : ∃ n, g ∈ dyadicK n := by
  obtain ⟨k, n, hk⟩ := exists_rep g.toAdd
  refine ⟨n, ?_⟩
  show g ∈ Subgroup.zpowers (dyadicStep n)
  rw [Subgroup.mem_zpowers_iff]
  refine ⟨k, ?_⟩
  rw [dyadicStep_zpow]
  apply Multiplicative.toAdd.injective
  apply Subtype.ext
  exact hk.symm

/-- **`ℤ[1/2]` is amenable**: it is the directed union of the cyclic groups
generated by `1/2ⁿ`. -/
theorem hasInvariantMean_dyadic : HasInvariantMean (Multiplicative DyadicRationals.Dyadic) :=
  hasInvariantMean_of_directed dyadicK
    (fun n ↦ (hasInvariantMean_zpowers (dyadicStep n)).some) ⟨0⟩ dyadicK_mono
    dyadicK_cover

/-- **The literal affine group `ℤ[1/2] ⋊ ℤ` is amenable.** -/
theorem hasInvariantMean_affine : HasInvariantMean Affine :=
  hasInvariantMean_semidirectProduct hasInvariantMean_dyadic
    hasInvariantMean_int

/-- The Clifford lamp group on the literal coset space is amenable, being
locally finite. -/
theorem hasInvariantMean_lampGroup :
    HasInvariantMean (CliffordAlgebraLamp.lampGroup Sites) :=
  hasInvariantMean_of_isLocallyFiniteGroup
    (CliffordAlgebraLamp.isLocallyFiniteGroup_lampGroup Sites)

/-- **The literal Clifford extension is amenable.** -/
theorem hasInvariantMean_cliffordDyadic : HasInvariantMean CliffordDyadic :=
  hasInvariantMean_semidirectProduct hasInvariantMean_lampGroup
    hasInvariantMean_affine

/-- Every subgroup of the literal Clifford extension is amenable --- in
particular the realized quotient of Theorem C. -/
theorem isAmenable_subgroup_cliffordDyadic (H : Subgroup CliffordDyadic) :
    IsAmenable H :=
  IsAmenable.subgroup
    (isAmenable_of_hasInvariantMean hasInvariantMean_cliffordDyadic) H

/-- **The realized quotient is amenable.** -/
theorem isAmenable_dyadicRealizedQuotient :
    IsAmenable DyadicRealizedQuotient :=
  isAmenable_subgroup_cliffordDyadic _

/-! ## The manuscript package -/

/-- **The cyclic comparison, in the manuscript's own group.**

Every clause is about the literal objects: the group is `ℤ[1/2] ⋊ ℤ` (proved
isomorphic to the presented `BS(1,2)` in `Algebra.DyadicRationals`), the sites
are its literal cosets modulo the cyclic base, the lamps are Clifford
generators at those sites, and the marked word evaluates to the Clifford sign.

The finite-dimensional half of Theorem C is
`LiteralCyclicCalibration.finiteDimensional_kill`, which is a statement about
the presented group alone and is reused verbatim.  Amenability of the realized
quotient is included; the manuscript's concluding "hence MF" is
Tikuisis--White--Winter and is deliberately absent. -/
theorem manuscriptDyadicCalibration :
    Nonempty (BS ≃* Affine) ∧
      gammaZero • basepoint = basepoint ∧
      tZero • basepoint ≠ (gammaZero * tZero) • basepoint ∧
      (∀ r ∈ relators, FreeGroup.lift dyadicTarget r = 1) ∧
      dyadicTarget lampIndex = SemidirectProduct.inl (lampGen Sites basepoint) ∧
      markedCompressionWord tD gammaD cD =
        SemidirectProduct.inl
          (⁅lampGen Sites (tZero • basepoint),
            lampGen Sites ((gammaZero * tZero) • basepoint)⁆) ∧
      markedCompressionWord tD gammaD cD = zD ∧
      zD ≠ 1 ∧
      mark ≠ 1 ∧
      Function.Surjective dyadicQuotientMap ∧
      dyadicQuotientMap mark ≠ 1 ∧
      (((dyadicQuotientMap mark : DyadicRealizedQuotient) : CliffordDyadic)
        = zD) ∧
      (∀ g : DyadicRealizedQuotient, Commute (dyadicQuotientMap mark) g) ∧
      IsSolvable Affine ∧
      IsAmenable DyadicRealizedQuotient ∧
      (∀ {k V : Type*} [Field k] [AddCommGroup V] [Module k V]
        [FiniteDimensional k V]
        (pi : LiteralGroup →* (Module.End k V)ˣ), pi mark = 1) := by
  refine ⟨⟨bsEquivAffine⟩, gammaZero_smul_basepoint, marked_sites_ne,
    dyadicTarget_kills_relators, rfl, ?_, markedWord_eq_zD, zD_ne_one,
    GroupApproximation.LiteralCyclicCalibration.mark_ne_one, dyadicQuotientMap_surjective,
    dyadicQuotientMap_mark_ne_one, dyadicQuotientMap_mark_val,
    dyadicQuotientMap_mark_central, affine_isSolvable,
    isAmenable_dyadicRealizedQuotient, ?_⟩
  · have ht : tD * cD * tD⁻¹ =
        SemidirectProduct.inl (lampGen Sites (tZero • basepoint)) := by
      rw [tD, cD, conj_lamp]
    have hgt : gammaD *
        SemidirectProduct.inl (lampGen Sites (tZero • basepoint)) * gammaD⁻¹ =
          SemidirectProduct.inl
            (lampGen Sites ((gammaZero * tZero) • basepoint)) := by
      rw [gammaD, conj_lamp, smul_smul]
    rw [markedCompressionWord, ht, hgt, ← map_commutatorElement]
  · intro k V _ _ _ _ pi
    exact finiteDimensional_kill pi

end

end LiteralDyadicCalibration
end GroupApproximation
