import GroupApproximation.GroupTheory.PresentedGroupRelatorReplay
import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup

/-!
# The braid presentation of rank two

The two-generator, two-relator presentation

  `SL2P = ⟨a, b ∣ aba = bab, (aba)⁴ = 1⟩`

is the Steinberg-type presentation of rank two: under `a ↦ e₁₂(1)`,
`b ↦ e₂₁(-1)` the braid relator becomes the defining relation of the
signed permutation `w = e₁₂(1) e₂₁(-1) e₁₂(1)`, and the second relator
kills `w⁴`.  This file realizes the presentation on `SL₂(ℤ)` and proves
that the canonical homomorphism `toSL2 : SL2P →* SL₂(ℤ)` is surjective,
by the same Euclidean reduction as in rank three: transvections lie in
the subgroup generated by the two elementary matrices, a signed swap is
a three-transvection word, and strong induction on the absolute value
of the lower-left entry clears it, leaving a sign diagonal that is the
square of the signed swap.

The rank-two presentation is the seed of the completeness programme:
`P13` contains the braid relation and the fourth-power relator among
`x₁₂(1)` and `x₂₁(-1)` (`P13WeylCalculus`), so `SL2P` maps into `P13`
compatibly with the matrix models.
-/

namespace GroupApproximation
namespace SL2BraidPresentation

open PresentedGroupRelatorReplay

noncomputable section

/-- The two elementary letters `a = e₁₂(1)` and `b = e₂₁(-1)`. -/
abbrev SL2BraidGenerator := Fin 2

/-- Literal signed words for the two relators: the braid word
`a b a b⁻¹ a⁻¹ b⁻¹` and the fourth power `(a b a)⁴`. -/
def sl2RelatorLetters : Fin 2 → SignedWord SL2BraidGenerator
  | 0 => [(0, true), (1, true), (0, true),
      (1, false), (0, false), (1, false)]
  | 1 =>
      [(0, true), (1, true), (0, true),
       (0, true), (1, true), (0, true),
       (0, true), (1, true), (0, true),
       (0, true), (1, true), (0, true)]

/-- The indexed relator interface. -/
def sl2Relator : Fin 2 → FreeGroup SL2BraidGenerator
  | i => word (sl2RelatorLetters i)

/-- Exactly the two relators, with the indexed order above. -/
def sl2Relators : Finset (FreeGroup SL2BraidGenerator) :=
  Finset.univ.image sl2Relator

theorem mem_sl2Relators_iff (r : FreeGroup SL2BraidGenerator) :
    r ∈ sl2Relators ↔ ∃ i : Fin 2, sl2Relator i = r := by
  simp [sl2Relators, eq_comm]

/-- The braid-presented group of rank two. -/
abbrev SL2P : Type :=
  PresentedGroup (sl2Relators : Set (FreeGroup SL2BraidGenerator))

/-- The concrete rank-two special linear group over the integers. -/
abbrev SL2 : Type := Matrix.SpecialLinearGroup (Fin 2) ℤ

/-- The two elementary matrices `e₁₂(1)` and `e₂₁(-1)`. -/
def sl2Elem : Fin 2 → SL2
  | 0 => ⟨!![1, 1; 0, 1], by decide⟩
  | 1 => ⟨!![1, 0; -1, 1], by decide⟩

/-- Both relators die under the elementary assignment.  Each instance is
a closed identity of `2 × 2` integer matrices, checked by the kernel. -/
theorem lift_sl2Elem_relator_eq_one (i : Fin 2) :
    FreeGroup.lift sl2Elem (sl2Relator i) = 1 := by
  fin_cases i <;>
    · simp only [sl2Relator, sl2RelatorLetters, word, FreeGroup.lift_mk]
      decide

theorem lift_sl2Elem_eq_one_of_mem {r : FreeGroup SL2BraidGenerator}
    (hr : r ∈ (sl2Relators : Set (FreeGroup SL2BraidGenerator))) :
    FreeGroup.lift sl2Elem r = 1 := by
  obtain ⟨i, rfl⟩ := (mem_sl2Relators_iff r).mp hr
  exact lift_sl2Elem_relator_eq_one i

/-- The canonical homomorphism from the braid presentation to the actual
special linear group. -/
noncomputable def toSL2 : SL2P →* SL2 :=
  PresentedGroup.toGroup (f := sl2Elem) fun _ hr =>
    lift_sl2Elem_eq_one_of_mem hr

@[simp] theorem toSL2_of (i : SL2BraidGenerator) :
    toSL2 (PresentedGroup.of i) = sl2Elem i :=
  PresentedGroup.toGroup.of _

/-! ## Transvections lie in the elementary subgroup -/

/-! ## Row operations, at the level of matrix entries -/

/-! ## The signed swap -/

/-! ## The Euclidean reduction -/

/-! ## Generation and surjectivity -/

end

end SL2BraidPresentation
end GroupApproximation
