import Mathlib.GroupTheory.FinitelyPresentedGroup
import GroupApproximation.GroupTheory.PresentedGroupRelatorReplay
import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup
import Mathlib.LinearAlgebra.Matrix.Transvection

/-!
# The braid presentation of rank two

The two-generator, two-relator presentation

  `SL2P = ⟨a, b ∣ aba = bab, (aba)⁴ = 1⟩`

is the Steinberg-type presentation of rank two: under `a ↦ e₁₂(1)`,
`b ↦ e₂₁(-1)` the braid relator becomes the defining relation of the
signed permutation `w = e₁₂(1) e₂₁(-1) e₁₂(1)`, and the second relator
kills `w⁴`.  This file realizes the presentation on `SL₂(ℤ)` and proves
that the canonical homomorphism `toSL2 : SL2P →* SL₂(ℤ)` is surjective,
by the same Euclidean reduction as in rank three: transvections lie in
the subgroup generated by the two elementary matrices, a signed swap is
a three-transvection word, and strong induction on the absolute value
of the lower-left entry clears it, leaving a sign diagonal that is the
square of the signed swap.

The rank-two presentation is the seed of the completeness programme:
`P13` contains the braid relation and the fourth-power relator among
`x₁₂(1)` and `x₂₁(-1)` (`P13WeylCalculus`), so `SL2P` maps into `P13`
compatibly with the matrix models.
-/

namespace GroupApproximation
namespace SL2BraidPresentation

open PresentedGroupRelatorReplay

noncomputable section

local instance sl2DecidableEq {A : Type*} : DecidableEq A := Classical.decEq A

/-- The two elementary letters `a = e₁₂(1)` and `b = e₂₁(-1)`. -/
abbrev SL2BraidGenerator := Fin 2

/-- Literal signed words for the two relators: the braid word
`a b a b⁻¹ a⁻¹ b⁻¹` and the fourth power `(a b a)⁴`. -/
def sl2RelatorLetters : Fin 2 → SignedWord SL2BraidGenerator
  | 0 => [(0, true), (1, true), (0, true),
      (1, false), (0, false), (1, false)]
  | 1 =>
      [(0, true), (1, true), (0, true),
       (0, true), (1, true), (0, true),
       (0, true), (1, true), (0, true),
       (0, true), (1, true), (0, true)]

/-- The indexed relator interface. -/
def sl2Relator : Fin 2 → FreeGroup SL2BraidGenerator
  | i => word (sl2RelatorLetters i)

/-- Exactly the two relators, with the indexed order above. -/
def sl2Relators : Finset (FreeGroup SL2BraidGenerator) :=
  Finset.univ.image sl2Relator

theorem mem_sl2Relators_iff (r : FreeGroup SL2BraidGenerator) :
    r ∈ sl2Relators ↔ ∃ i : Fin 2, sl2Relator i = r := by
  simp [sl2Relators, eq_comm]

/-- The braid-presented group of rank two. -/
abbrev SL2P : Type :=
  PresentedGroup (sl2Relators : Set (FreeGroup SL2BraidGenerator))

/-- The concrete rank-two special linear group over the integers. -/
abbrev SL2 : Type := Matrix.SpecialLinearGroup (Fin 2) ℤ

/-- The two elementary matrices `e₁₂(1)` and `e₂₁(-1)`. -/
def sl2Elem : Fin 2 → SL2
  | 0 => ⟨!![1, 1; 0, 1], by decide⟩
  | 1 => ⟨!![1, 0; -1, 1], by decide⟩

/-- Both relators die under the elementary assignment.  Each instance is
a closed identity of `2 × 2` integer matrices, checked by the kernel. -/
theorem lift_sl2Elem_relator_eq_one (i : Fin 2) :
    FreeGroup.lift sl2Elem (sl2Relator i) = 1 := by
  fin_cases i <;>
    · simp only [sl2Relator, sl2RelatorLetters, word, FreeGroup.lift_mk]
      decide

theorem lift_sl2Elem_eq_one_of_mem {r : FreeGroup SL2BraidGenerator}
    (hr : r ∈ (sl2Relators : Set (FreeGroup SL2BraidGenerator))) :
    FreeGroup.lift sl2Elem r = 1 := by
  obtain ⟨i, rfl⟩ := (mem_sl2Relators_iff r).mp hr
  exact lift_sl2Elem_relator_eq_one i

/-- The canonical homomorphism from the braid presentation to the actual
special linear group. -/
noncomputable def toSL2 : SL2P →* SL2 :=
  PresentedGroup.toGroup (f := sl2Elem) fun _ hr =>
    lift_sl2Elem_eq_one_of_mem hr

@[simp] theorem toSL2_of (i : SL2BraidGenerator) :
    toSL2 (PresentedGroup.of i) = sl2Elem i :=
  PresentedGroup.toGroup.of _

/-! ## Transvections lie in the elementary subgroup -/

/-- The subgroup generated by the two elementary matrices. -/
def H2 : Subgroup SL2 := Subgroup.closure (Set.range sl2Elem)

/-- The transvection `1 + c·E i j` as an element of the special linear
group. -/
def tv2 (i j : Fin 2) (hij : i ≠ j) (c : ℤ) : SL2 :=
  ⟨Matrix.transvection i j c, by
    rw [Matrix.det_transvection_of_ne i j hij]⟩

@[simp] theorem tv2_coe (i j : Fin 2) (hij : i ≠ j) (c : ℤ) :
    (tv2 i j hij c : Matrix (Fin 2) (Fin 2) ℤ) =
      Matrix.transvection i j c :=
  rfl

theorem tv2_mul_tv2 (i j : Fin 2) (hij : i ≠ j) (c d : ℤ) :
    tv2 i j hij c * tv2 i j hij d = tv2 i j hij (c + d) := by
  apply Subtype.ext
  simpa using Matrix.transvection_mul_transvection_same i j hij c d

theorem tv2_zero (i j : Fin 2) (hij : i ≠ j) : tv2 i j hij 0 = 1 := by
  apply Subtype.ext
  simp [tv2]

theorem tv2_neg (i j : Fin 2) (hij : i ≠ j) (c : ℤ) :
    tv2 i j hij (-c) = (tv2 i j hij c)⁻¹ := by
  apply eq_inv_of_mul_eq_one_left
  rw [tv2_mul_tv2, neg_add_cancel, tv2_zero]

theorem tv2_one_mem (i j : Fin 2) (hij : i ≠ j) : tv2 i j hij 1 ∈ H2 := by
  match i, j, hij with
  | 0, 0, hij => exact absurd rfl hij
  | 0, 1, hij =>
      have h : sl2Elem 0 = tv2 0 1 hij 1 := Subtype.ext (by
        show (sl2Elem 0 : Matrix (Fin 2) (Fin 2) ℤ) =
          Matrix.transvection 0 1 1
        decide)
      rw [← h]
      exact Subgroup.subset_closure ⟨0, rfl⟩
  | 1, 0, hij =>
      rw [(by norm_num : (1 : ℤ) = -(-1)), tv2_neg]
      have h : tv2 1 0 hij (-1) = sl2Elem 1 := Subtype.ext (by
        show Matrix.transvection 1 0 (-1) =
          (sl2Elem 1 : Matrix (Fin 2) (Fin 2) ℤ)
        decide)
      rw [h]
      exact H2.inv_mem (Subgroup.subset_closure ⟨1, rfl⟩)
  | 1, 1, hij => exact absurd rfl hij

theorem tv2_natCast_mem (i j : Fin 2) (hij : i ≠ j) (n : ℕ) :
    tv2 i j hij (n : ℤ) ∈ H2 := by
  induction n with
  | zero =>
      have h0 : ((0 : ℕ) : ℤ) = 0 := rfl
      rw [h0, tv2_zero]
      exact H2.one_mem
  | succ m ih =>
      have hcast : ((m + 1 : ℕ) : ℤ) = (m : ℤ) + 1 := by push_cast; ring
      rw [hcast, ← tv2_mul_tv2 i j hij (m : ℤ) 1]
      exact H2.mul_mem ih (tv2_one_mem i j hij)

theorem tv2_mem (i j : Fin 2) (hij : i ≠ j) (c : ℤ) :
    tv2 i j hij c ∈ H2 := by
  obtain ⟨n, rfl | rfl⟩ := c.eq_nat_or_neg
  · exact tv2_natCast_mem i j hij n
  · rw [tv2_neg]
    exact H2.inv_mem (tv2_natCast_mem i j hij n)

/-! ## Row operations, at the level of matrix entries -/

theorem tv2_mul_apply_same (i j : Fin 2) (hij : i ≠ j) (c : ℤ)
    (M : Matrix (Fin 2) (Fin 2) ℤ) (q : Fin 2) :
    ((tv2 i j hij c : Matrix (Fin 2) (Fin 2) ℤ) * M) i q =
      M i q + c * M j q := by
  rw [tv2_coe]
  exact Matrix.transvection_mul_apply_same i j q c M

theorem tv2_mul_apply_of_ne (i j : Fin 2) (hij : i ≠ j) (c : ℤ)
    (M : Matrix (Fin 2) (Fin 2) ℤ) (p q : Fin 2) (hp : p ≠ i) :
    ((tv2 i j hij c : Matrix (Fin 2) (Fin 2) ℤ) * M) p q = M p q := by
  rw [tv2_coe]
  exact Matrix.transvection_mul_apply_of_ne i j p q hp c M

/-! ## The signed swap -/

/-- The signed swap `e₁₂(1) e₂₁(-1) e₁₂(1)` in the matrix group. -/
def sw2 : SL2 :=
  tv2 0 1 (by decide) 1 * tv2 1 0 (by decide) (-1) * tv2 0 1 (by decide) 1

theorem sw2_mem : sw2 ∈ H2 :=
  H2.mul_mem (H2.mul_mem (tv2_mem 0 1 (by decide) 1)
    (tv2_mem 1 0 (by decide) (-1))) (tv2_mem 0 1 (by decide) 1)

theorem sw2_coe : ((sw2 : SL2) : Matrix (Fin 2) (Fin 2) ℤ) =
    !![0, 1; -1, 0] := by
  show ((tv2 0 1 (by decide) 1 * tv2 1 0 (by decide) (-1) *
    tv2 0 1 (by decide) 1 : SL2) : Matrix (Fin 2) (Fin 2) ℤ) = _
  rw [Matrix.SpecialLinearGroup.coe_mul, Matrix.SpecialLinearGroup.coe_mul]
  decide

theorem sw2_row (M : Matrix (Fin 2) (Fin 2) ℤ) (q : Fin 2) :
    ((sw2 : Matrix (Fin 2) (Fin 2) ℤ) * M) 0 q = M 1 q ∧
      ((sw2 : Matrix (Fin 2) (Fin 2) ℤ) * M) 1 q = -(M 0 q) := by
  rw [sw2_coe]
  constructor <;> simp [Matrix.mul_apply, Fin.sum_univ_two]

/-! ## The Euclidean reduction -/

private theorem emod_shrink (a : ℤ) {b : ℤ} (hb : b ≠ 0) :
    (a % b).natAbs < b.natAbs := by
  have h0 : 0 ≤ a % b := Int.emod_nonneg a hb
  have h1 : a % b < |b| := by
    rw [← Int.emod_abs]
    exact Int.emod_lt_of_pos a (abs_pos.mpr hb)
  have h2 : a % b < (b.natAbs : ℤ) := by
    rwa [Int.abs_eq_natAbs] at h1
  omega

/-- Euclidean clearing of the lower-left entry: a product of elementary
operations sends any determinant-one matrix to one whose lower-left
entry vanishes. -/
theorem lower_left_reduce (A : SL2) :
    ∃ L : SL2, L ∈ H2 ∧
      ((L : Matrix (Fin 2) (Fin 2) ℤ) *
        (A : Matrix (Fin 2) (Fin 2) ℤ)) 1 0 = 0 := by
  suffices h : ∀ (n : ℕ) (A : SL2),
      ((A : Matrix (Fin 2) (Fin 2) ℤ) 1 0).natAbs ≤ n →
      ∃ L : SL2, L ∈ H2 ∧
        ((L : Matrix (Fin 2) (Fin 2) ℤ) *
          (A : Matrix (Fin 2) (Fin 2) ℤ)) 1 0 = 0 by
    exact h _ A le_rfl
  intro n
  induction n with
  | zero =>
      intro A hn
      have h0 : (A : Matrix (Fin 2) (Fin 2) ℤ) 1 0 = 0 :=
        Int.natAbs_eq_zero.mp (Nat.le_zero.mp hn)
      exact ⟨1, H2.one_mem, by simp [h0]⟩
  | succ m ih =>
      intro A hn
      by_cases hz : (A : Matrix (Fin 2) (Fin 2) ℤ) 1 0 = 0
      · exact ⟨1, H2.one_mem, by simp [hz]⟩
      · -- Subtract the integer quotient of the upper-left entry by the
        -- lower-left entry from the top row, then swap the rows with a
        -- sign; the new lower-left entry is minus the remainder,
        -- strictly smaller in absolute value.
        set c : ℤ := -((A : Matrix (Fin 2) (Fin 2) ℤ) 0 0 /
          (A : Matrix (Fin 2) (Fin 2) ℤ) 1 0) with hc
        set L1 : SL2 := sw2 * tv2 0 1 (by decide) c with hL1
        set B : SL2 := L1 * A with hBdef
        have hBcoe : (B : Matrix (Fin 2) (Fin 2) ℤ) =
            (sw2 : Matrix (Fin 2) (Fin 2) ℤ) *
              ((tv2 0 1 (by decide) c : Matrix (Fin 2) (Fin 2) ℤ) *
                (A : Matrix (Fin 2) (Fin 2) ℤ)) := by
          rw [hBdef, hL1]
          simp [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_assoc]
        set M1 : Matrix (Fin 2) (Fin 2) ℤ :=
          (tv2 0 1 (by decide) c : Matrix (Fin 2) (Fin 2) ℤ) *
            (A : Matrix (Fin 2) (Fin 2) ℤ) with hM1def
        have hM10 : M1 0 0 = (A : Matrix (Fin 2) (Fin 2) ℤ) 0 0 +
            c * (A : Matrix (Fin 2) (Fin 2) ℤ) 1 0 := by
          rw [hM1def, tv2_mul_apply_same]
        have hB10 : (B : Matrix (Fin 2) (Fin 2) ℤ) 1 0 =
            -((A : Matrix (Fin 2) (Fin 2) ℤ) 0 0 %
              (A : Matrix (Fin 2) (Fin 2) ℤ) 1 0) := by
          rw [hBcoe, (sw2_row M1 0).2, hM10, hc, Int.emod_def]
          ring
        have hBsmall : ((B : Matrix (Fin 2) (Fin 2) ℤ) 1 0).natAbs ≤ m := by
          rw [hB10, Int.natAbs_neg]
          have hlt :=
            emod_shrink ((A : Matrix (Fin 2) (Fin 2) ℤ) 0 0) hz
          omega
        obtain ⟨L2, hL2mem, hL2z⟩ := ih B hBsmall
        have hcomp : ((L2 * L1 : SL2) : Matrix (Fin 2) (Fin 2) ℤ) *
            (A : Matrix (Fin 2) (Fin 2) ℤ) =
            (L2 : Matrix (Fin 2) (Fin 2) ℤ) *
              (B : Matrix (Fin 2) (Fin 2) ℤ) := by
          rw [hBdef]
          simp [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_assoc]
        refine ⟨L2 * L1, H2.mul_mem hL2mem
          (H2.mul_mem sw2_mem (tv2_mem 0 1 (by decide) c)), ?_⟩
        rw [hcomp]
        exact hL2z

/-! ## Generation and surjectivity -/

/-- **Elementary generation of rank two.**  Every determinant-one
integer matrix lies in the subgroup generated by the two elementary
matrices. -/
theorem mem_H2 (A : SL2) : A ∈ H2 := by
  obtain ⟨L, hL, hz⟩ := lower_left_reduce A
  set B : SL2 := L * A with hBdef
  have hzB : (B : Matrix (Fin 2) (Fin 2) ℤ) 1 0 = 0 := by
    rw [hBdef]
    simpa [Matrix.SpecialLinearGroup.coe_mul] using hz
  have hAB : A = L⁻¹ * B := by rw [hBdef]; group
  have hdet : (B : Matrix (Fin 2) (Fin 2) ℤ) 0 0 *
      (B : Matrix (Fin 2) (Fin 2) ℤ) 1 1 = 1 := by
    have hd : (B : Matrix (Fin 2) (Fin 2) ℤ).det = 1 := B.property
    rw [Matrix.det_fin_two, hzB, mul_zero, sub_zero] at hd
    exact hd
  rcases Int.mul_eq_one_iff_eq_one_or_neg_one.mp hdet with
    ⟨h00, h11⟩ | ⟨h00, h11⟩
  · -- `B` is upper unitriangular, a single transvection.
    have hB : B = tv2 0 1 (by decide)
        ((B : Matrix (Fin 2) (Fin 2) ℤ) 0 1) := by
      apply Subtype.ext
      rw [tv2_coe]
      ext p q
      fin_cases p <;> fin_cases q <;>
        simp [Matrix.transvection, Matrix.single, h00, h11, hzB]
    rw [hAB, hB]
    exact H2.mul_mem (H2.inv_mem hL) (tv2_mem 0 1 (by decide) _)
  · -- `B` is minus a transvection, the square of the signed swap
    -- times a transvection.
    have hB : B = sw2 * sw2 * tv2 0 1 (by decide)
        (-((B : Matrix (Fin 2) (Fin 2) ℤ) 0 1)) := by
      apply Subtype.ext
      conv_rhs => rw [Matrix.SpecialLinearGroup.coe_mul,
        Matrix.SpecialLinearGroup.coe_mul, sw2_coe, tv2_coe]
      ext p q
      fin_cases p <;> fin_cases q <;>
        (simp [Matrix.mul_apply, Fin.sum_univ_two, Matrix.transvection,
          Matrix.single, Matrix.one_apply, h00, h11, hzB]; try ring)
    rw [hAB, hB]
    exact H2.mul_mem (H2.inv_mem hL)
      (H2.mul_mem (H2.mul_mem sw2_mem sw2_mem)
        (tv2_mem 0 1 (by decide) _))

theorem H2_eq_top : H2 = ⊤ :=
  top_unique fun A _ => mem_H2 A

/-- **Elementary generation.**  The canonical homomorphism from the
rank-two braid presentation onto the special linear group is
surjective. -/
theorem toSL2_surjective : Function.Surjective toSL2 := by
  intro A
  have hle : Subgroup.closure (Set.range sl2Elem) ≤
      MonoidHom.range toSL2 :=
    (Subgroup.closure_le _).mpr (by
      rintro _ ⟨k, rfl⟩
      exact ⟨PresentedGroup.of k, toSL2_of k⟩)
  obtain ⟨g, hg⟩ := hle (mem_H2 A)
  exact ⟨g, hg⟩

end

end SL2BraidPresentation
end GroupApproximation
