import GroupApproximation.Monsters.LiteralP13MatrixModel
import Mathlib.LinearAlgebra.Matrix.Transvection
import Mathlib.Tactic.LinearCombination

/-!
# Elementary generation of `SL₃(ℤ)`

The six elementary matrices of the P13 matrix model generate the whole
special linear group: every integer matrix of determinant one reduces to
the identity by integer row and column operations.  The argument is the
classical Euclidean reduction, phrased so that every step happens inside
the subgroup generated by the six elementary matrices:

* every transvection `1 + c·E i j` is an integer power of an elementary
  matrix, hence lies in the subgroup;
* a signed swap of two rows is a three-transvection word;
* the Euclidean algorithm on a pair of rows, by strong induction on the
  absolute value of one entry, clears one entry of a chosen column while
  fixing every other row and preserving columns on which both rows
  vanish;
* two column stages and two row stages reduce any determinant-one matrix
  to a diagonal of signs with product one, and each such diagonal is the
  square of a signed swap.

The endpoint is surjectivity of the canonical homomorphism
`toSL3 : P13 →* SL₃(ℤ)` from the thirteen-relator Steinberg-type
presentation.  Injectivity of the same map — completeness of the
presentation, classically the unstable `K₂(3,ℤ) = ℤ/2` computation — is
a separate, deeper target and is not touched here.
-/

namespace GroupApproximation
namespace SL3ElementaryGeneration

open LiteralP13MatrixModel Matrix

/-- The subgroup generated by the six elementary matrices. -/
def H : Subgroup SL3 := Subgroup.closure (Set.range elem)

/-! ## Transvections lie in the elementary subgroup -/

/-- The transvection `1 + c·E i j` as an element of the special linear
group. -/
def tv (i j : Fin 3) (hij : i ≠ j) (c : ℤ) : SL3 :=
  ⟨Matrix.transvection i j c, by rw [Matrix.det_transvection_of_ne i j hij]⟩

@[simp] theorem tv_coe (i j : Fin 3) (hij : i ≠ j) (c : ℤ) :
    (tv i j hij c : Matrix (Fin 3) (Fin 3) ℤ) = Matrix.transvection i j c :=
  rfl

theorem tv_mul_tv (i j : Fin 3) (hij : i ≠ j) (c d : ℤ) :
    tv i j hij c * tv i j hij d = tv i j hij (c + d) := by
  apply Subtype.ext
  simpa using Matrix.transvection_mul_transvection_same i j hij c d

theorem tv_zero (i j : Fin 3) (hij : i ≠ j) : tv i j hij 0 = 1 := by
  apply Subtype.ext
  simp [tv]

theorem tv_neg (i j : Fin 3) (hij : i ≠ j) (c : ℤ) :
    tv i j hij (-c) = (tv i j hij c)⁻¹ := by
  apply eq_inv_of_mul_eq_one_left
  rw [tv_mul_tv, neg_add_cancel, tv_zero]

/-- Each unit transvection is one of the six elementary matrices, at the
level of matrix values. -/
theorem tv_one_val (i j : Fin 3) (hij : i ≠ j) :
    ∃ k : Fin 6, (elem k : Matrix (Fin 3) (Fin 3) ℤ) =
      Matrix.transvection i j 1 := by
  fin_cases i <;> fin_cases j <;> first
    | exact absurd rfl hij
    | decide

theorem tv_one_mem (i j : Fin 3) (hij : i ≠ j) : tv i j hij 1 ∈ H := by
  obtain ⟨k, hk⟩ := tv_one_val i j hij
  have : elem k = tv i j hij 1 := Subtype.ext (by simpa using hk)
  rw [← this]
  exact Subgroup.subset_closure ⟨k, rfl⟩

theorem tv_natCast_mem (i j : Fin 3) (hij : i ≠ j) (n : ℕ) :
    tv i j hij (n : ℤ) ∈ H := by
  induction n with
  | zero =>
      have h0 : ((0 : ℕ) : ℤ) = 0 := rfl
      rw [h0, tv_zero]
      exact H.one_mem
  | succ m ih =>
      have hcast : ((m + 1 : ℕ) : ℤ) = (m : ℤ) + 1 := by push_cast; ring
      rw [hcast, ← tv_mul_tv i j hij (m : ℤ) 1]
      exact H.mul_mem ih (tv_one_mem i j hij)

theorem tv_mem (i j : Fin 3) (hij : i ≠ j) (c : ℤ) : tv i j hij c ∈ H := by
  obtain ⟨n, rfl | rfl⟩ := c.eq_nat_or_neg
  · exact tv_natCast_mem i j hij n
  · rw [tv_neg]
    exact H.inv_mem (tv_natCast_mem i j hij n)

/-! ## Row and column operations, at the level of matrix entries -/

theorem tv_mul_apply_same (i j : Fin 3) (hij : i ≠ j) (c : ℤ)
    (M : Matrix (Fin 3) (Fin 3) ℤ) (q : Fin 3) :
    ((tv i j hij c : Matrix (Fin 3) (Fin 3) ℤ) * M) i q =
      M i q + c * M j q := by
  rw [tv_coe]
  exact Matrix.transvection_mul_apply_same i j q c M

theorem tv_mul_apply_of_ne (i j : Fin 3) (hij : i ≠ j) (c : ℤ)
    (M : Matrix (Fin 3) (Fin 3) ℤ) (p q : Fin 3) (hp : p ≠ i) :
    ((tv i j hij c : Matrix (Fin 3) (Fin 3) ℤ) * M) p q = M p q := by
  rw [tv_coe]
  exact Matrix.transvection_mul_apply_of_ne i j p q hp c M

theorem mul_tv_apply_same (i j : Fin 3) (hij : i ≠ j) (c : ℤ)
    (M : Matrix (Fin 3) (Fin 3) ℤ) (p : Fin 3) :
    (M * (tv i j hij c : Matrix (Fin 3) (Fin 3) ℤ)) p j =
      M p j + c * M p i := by
  rw [tv_coe]
  exact Matrix.mul_transvection_apply_same i j p c M

theorem mul_tv_apply_of_ne (i j : Fin 3) (hij : i ≠ j) (c : ℤ)
    (M : Matrix (Fin 3) (Fin 3) ℤ) (p q : Fin 3) (hq : q ≠ j) :
    (M * (tv i j hij c : Matrix (Fin 3) (Fin 3) ℤ)) p q = M p q := by
  rw [tv_coe]
  exact Matrix.mul_transvection_apply_of_ne i j p q hq c M

/-! ## The signed swap -/

/-- The signed swap of rows `i` and `j`: it replaces row `i` by row `j`
and row `j` by the negative of row `i`. -/
def sw (i j : Fin 3) (hij : i ≠ j) : SL3 :=
  tv i j hij 1 * tv j i hij.symm (-1) * tv i j hij 1

theorem sw_mem (i j : Fin 3) (hij : i ≠ j) : sw i j hij ∈ H :=
  H.mul_mem (H.mul_mem (tv_mem i j hij 1) (tv_mem j i hij.symm (-1)))
    (tv_mem i j hij 1)

theorem sw_row (i j : Fin 3) (hij : i ≠ j)
    (M : Matrix (Fin 3) (Fin 3) ℤ) (q : Fin 3) :
    ((sw i j hij : Matrix (Fin 3) (Fin 3) ℤ) * M) i q = M j q ∧
      ((sw i j hij : Matrix (Fin 3) (Fin 3) ℤ) * M) j q = -(M i q) ∧
      ∀ p, p ≠ i → p ≠ j →
        ((sw i j hij : Matrix (Fin 3) (Fin 3) ℤ) * M) p q = M p q := by
  have hcoe : (sw i j hij : Matrix (Fin 3) (Fin 3) ℤ) * M =
      (tv i j hij 1 : Matrix (Fin 3) (Fin 3) ℤ) *
        ((tv j i hij.symm (-1) : Matrix (Fin 3) (Fin 3) ℤ) *
          ((tv i j hij 1 : Matrix (Fin 3) (Fin 3) ℤ) * M)) := by
    simp [sw, Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_assoc]
  have h1i : ∀ r, ((tv i j hij 1 : Matrix (Fin 3) (Fin 3) ℤ) * M) i r =
      M i r + M j r := fun r => by
    rw [tv_mul_apply_same]; ring
  have h1j : ∀ r, ((tv i j hij 1 : Matrix (Fin 3) (Fin 3) ℤ) * M) j r =
      M j r := fun r => tv_mul_apply_of_ne i j hij 1 M j r hij.symm
  have h1p : ∀ p, p ≠ i → ∀ r,
      ((tv i j hij 1 : Matrix (Fin 3) (Fin 3) ℤ) * M) p r = M p r :=
    fun p hp r => tv_mul_apply_of_ne i j hij 1 M p r hp
  set M1 : Matrix (Fin 3) (Fin 3) ℤ :=
    (tv i j hij 1 : Matrix (Fin 3) (Fin 3) ℤ) * M
  have h2j : ∀ r, ((tv j i hij.symm (-1) : Matrix (Fin 3) (Fin 3) ℤ) * M1)
      j r = -(M i r) := fun r => by
    rw [tv_mul_apply_same, h1j, h1i]; ring
  have h2i : ∀ r, ((tv j i hij.symm (-1) : Matrix (Fin 3) (Fin 3) ℤ) * M1)
      i r = M i r + M j r := fun r => by
    rw [tv_mul_apply_of_ne j i hij.symm (-1) M1 i r hij, h1i]
  have h2p : ∀ p, p ≠ i → p ≠ j → ∀ r,
      ((tv j i hij.symm (-1) : Matrix (Fin 3) (Fin 3) ℤ) * M1) p r =
        M p r := fun p hpi hpj r => by
    rw [tv_mul_apply_of_ne j i hij.symm (-1) M1 p r hpj, h1p p hpi]
  set M2 : Matrix (Fin 3) (Fin 3) ℤ :=
    (tv j i hij.symm (-1) : Matrix (Fin 3) (Fin 3) ℤ) * M1
  refine ⟨?_, ?_, ?_⟩
  · rw [hcoe]
    show ((tv i j hij 1 : Matrix (Fin 3) (Fin 3) ℤ) * M2) i q = M j q
    rw [tv_mul_apply_same, h2i, h2j]; ring
  · rw [hcoe]
    show ((tv i j hij 1 : Matrix (Fin 3) (Fin 3) ℤ) * M2) j q = -(M i q)
    rw [tv_mul_apply_of_ne i j hij 1 M2 j q hij.symm, h2j]
  · intro p hpi hpj
    rw [hcoe]
    show ((tv i j hij 1 : Matrix (Fin 3) (Fin 3) ℤ) * M2) p q = M p q
    rw [tv_mul_apply_of_ne i j hij 1 M2 p q hpi, h2p p hpi hpj]

/-! ## The Euclidean pair reduction -/

private theorem emod_shrink (a : ℤ) {b : ℤ} (hb : b ≠ 0) :
    (a % b).natAbs < b.natAbs := by
  have h0 : 0 ≤ a % b := Int.emod_nonneg a hb
  have h1 : a % b < |b| := by
    rw [← Int.emod_abs]
    exact Int.emod_lt_of_pos a (abs_pos.mpr hb)
  have h2 : a % b < (b.natAbs : ℤ) := by
    rwa [Int.abs_eq_natAbs] at h1
  omega

/-- Euclidean reduction of the pair of rows `i, j` in column `k`: a
product of elementary operations clears the `(j,k)` entry, fixes every
row other than `i` and `j`, and preserves the vanishing of any column on
which both rows vanish. -/
theorem pair_reduce (k i j : Fin 3) (hij : i ≠ j) (A : SL3) :
    ∃ L : SL3, L ∈ H ∧
      (((L : Matrix (Fin 3) (Fin 3) ℤ) * A) j k = 0 ∧
        (∀ p, p ≠ i → p ≠ j → ∀ q,
          ((L : Matrix (Fin 3) (Fin 3) ℤ) * A) p q =
            (A : Matrix (Fin 3) (Fin 3) ℤ) p q) ∧
        (∀ q, (A : Matrix (Fin 3) (Fin 3) ℤ) i q = 0 →
          (A : Matrix (Fin 3) (Fin 3) ℤ) j q = 0 →
          ((L : Matrix (Fin 3) (Fin 3) ℤ) * A) i q = 0 ∧
            ((L : Matrix (Fin 3) (Fin 3) ℤ) * A) j q = 0)) := by
  suffices h : ∀ (n : ℕ) (A : SL3),
      ((A : Matrix (Fin 3) (Fin 3) ℤ) j k).natAbs ≤ n →
      ∃ L : SL3, L ∈ H ∧
        (((L : Matrix (Fin 3) (Fin 3) ℤ) * A) j k = 0 ∧
          (∀ p, p ≠ i → p ≠ j → ∀ q,
            ((L : Matrix (Fin 3) (Fin 3) ℤ) * A) p q =
              (A : Matrix (Fin 3) (Fin 3) ℤ) p q) ∧
          (∀ q, (A : Matrix (Fin 3) (Fin 3) ℤ) i q = 0 →
            (A : Matrix (Fin 3) (Fin 3) ℤ) j q = 0 →
            ((L : Matrix (Fin 3) (Fin 3) ℤ) * A) i q = 0 ∧
              ((L : Matrix (Fin 3) (Fin 3) ℤ) * A) j q = 0)) by
    exact h _ A le_rfl
  intro n
  induction n with
  | zero =>
      intro A hn
      have h0 : (A : Matrix (Fin 3) (Fin 3) ℤ) j k = 0 :=
        Int.natAbs_eq_zero.mp (Nat.le_zero.mp hn)
      exact ⟨1, H.one_mem, by simp [h0], fun p _ _ q => by simp,
        fun q h1 h2 => by simp [h1, h2]⟩
  | succ m ih =>
      intro A hn
      by_cases hz : (A : Matrix (Fin 3) (Fin 3) ℤ) j k = 0
      · exact ⟨1, H.one_mem, by simp [hz], fun p _ _ q => by simp,
          fun q h1 h2 => by simp [h1, h2]⟩
      · -- Subtract the integer quotient of the `(i,k)` entry by the
        -- `(j,k)` entry from row `i`, then swap the rows with a sign;
        -- the new `(j,k)` entry is minus the remainder, strictly
        -- smaller in absolute value.
        have hane : (A : Matrix (Fin 3) (Fin 3) ℤ) j k ≠ 0 := hz
        set c : ℤ := -((A : Matrix (Fin 3) (Fin 3) ℤ) i k /
          (A : Matrix (Fin 3) (Fin 3) ℤ) j k) with hc
        set L1 : SL3 := sw i j hij * tv i j hij c with hL1
        set B : SL3 := L1 * A with hBdef
        have hBcoe : (B : Matrix (Fin 3) (Fin 3) ℤ) =
            (sw i j hij : Matrix (Fin 3) (Fin 3) ℤ) *
              ((tv i j hij c : Matrix (Fin 3) (Fin 3) ℤ) *
                (A : Matrix (Fin 3) (Fin 3) ℤ)) := by
          rw [hBdef, hL1]
          simp [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_assoc]
        set M1 : Matrix (Fin 3) (Fin 3) ℤ :=
          (tv i j hij c : Matrix (Fin 3) (Fin 3) ℤ) *
            (A : Matrix (Fin 3) (Fin 3) ℤ) with hM1def
        have hM1i : ∀ q, M1 i q =
            (A : Matrix (Fin 3) (Fin 3) ℤ) i q +
              c * (A : Matrix (Fin 3) (Fin 3) ℤ) j q := fun q => by
          rw [hM1def, tv_mul_apply_same]
        have hM1other : ∀ p, p ≠ i → ∀ q, M1 p q =
            (A : Matrix (Fin 3) (Fin 3) ℤ) p q := fun p hp q => by
          rw [hM1def, tv_mul_apply_of_ne i j hij c _ p q hp]
        have hBi : ∀ q, (B : Matrix (Fin 3) (Fin 3) ℤ) i q = M1 j q :=
          fun q => by rw [hBcoe]; exact (sw_row i j hij M1 q).1
        have hBj : ∀ q, (B : Matrix (Fin 3) (Fin 3) ℤ) j q = -(M1 i q) :=
          fun q => by rw [hBcoe]; exact (sw_row i j hij M1 q).2.1
        have hBother : ∀ p, p ≠ i → p ≠ j → ∀ q,
            (B : Matrix (Fin 3) (Fin 3) ℤ) p q =
              (A : Matrix (Fin 3) (Fin 3) ℤ) p q := fun p hpi hpj q => by
          rw [hBcoe]
          rw [(sw_row i j hij M1 q).2.2 p hpi hpj, hM1other p hpi q]
        have hBjk : (B : Matrix (Fin 3) (Fin 3) ℤ) j k =
            -((A : Matrix (Fin 3) (Fin 3) ℤ) i k %
              (A : Matrix (Fin 3) (Fin 3) ℤ) j k) := by
          rw [hBj k, hM1i k, hc, Int.emod_def]
          ring
        have hBsmall : ((B : Matrix (Fin 3) (Fin 3) ℤ) j k).natAbs ≤ m := by
          rw [hBjk, Int.natAbs_neg]
          have hlt : ((A : Matrix (Fin 3) (Fin 3) ℤ) i k %
              (A : Matrix (Fin 3) (Fin 3) ℤ) j k).natAbs <
              ((A : Matrix (Fin 3) (Fin 3) ℤ) j k).natAbs :=
            emod_shrink _ hane
          omega
        obtain ⟨L2, hL2mem, hL2jk, hL2other, hL2zero⟩ := ih B hBsmall
        have hcomp : ((L2 * L1 : SL3) : Matrix (Fin 3) (Fin 3) ℤ) *
            (A : Matrix (Fin 3) (Fin 3) ℤ) =
            (L2 : Matrix (Fin 3) (Fin 3) ℤ) *
              (B : Matrix (Fin 3) (Fin 3) ℤ) := by
          rw [hBdef]
          simp [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_assoc]
        refine ⟨L2 * L1, H.mul_mem hL2mem
          (H.mul_mem (sw_mem i j hij) (tv_mem i j hij c)), ?_, ?_, ?_⟩
        · rw [hcomp]; exact hL2jk
        · intro p hpi hpj q
          rw [hcomp, hL2other p hpi hpj q, hBother p hpi hpj q]
        · intro q h1 h2
          have hBi0 : (B : Matrix (Fin 3) (Fin 3) ℤ) i q = 0 := by
            rw [hBi q, hM1other j hij.symm q, h2]
          have hBj0 : (B : Matrix (Fin 3) (Fin 3) ℤ) j q = 0 := by
            rw [hBj q, hM1i q, h1, h2]; ring
          obtain ⟨hz1, hz2⟩ := hL2zero q hBi0 hBj0
          rw [hcomp]
          exact ⟨hz1, hz2⟩

/-! ## The sign diagonals -/

theorem sw_coe_01 : ((sw 0 1 (by decide) : SL3) :
    Matrix (Fin 3) (Fin 3) ℤ) = !![0,1,0; -1,0,0; 0,0,1] := by
  show ((tv 0 1 (by decide) 1 * tv 1 0 (by decide) (-1) *
    tv 0 1 (by decide) 1 : SL3) : Matrix (Fin 3) (Fin 3) ℤ) = _
  rw [Matrix.SpecialLinearGroup.coe_mul, Matrix.SpecialLinearGroup.coe_mul]
  decide

theorem sw_coe_02 : ((sw 0 2 (by decide) : SL3) :
    Matrix (Fin 3) (Fin 3) ℤ) = !![0,0,1; 0,1,0; -1,0,0] := by
  show ((tv 0 2 (by decide) 1 * tv 2 0 (by decide) (-1) *
    tv 0 2 (by decide) 1 : SL3) : Matrix (Fin 3) (Fin 3) ℤ) = _
  rw [Matrix.SpecialLinearGroup.coe_mul, Matrix.SpecialLinearGroup.coe_mul]
  decide

theorem sw_coe_12 : ((sw 1 2 (by decide) : SL3) :
    Matrix (Fin 3) (Fin 3) ℤ) = !![1,0,0; 0,0,1; 0,-1,0] := by
  show ((tv 1 2 (by decide) 1 * tv 2 1 (by decide) (-1) *
    tv 1 2 (by decide) 1 : SL3) : Matrix (Fin 3) (Fin 3) ℤ) = _
  rw [Matrix.SpecialLinearGroup.coe_mul, Matrix.SpecialLinearGroup.coe_mul]
  decide

theorem sw_sq_01 : ((sw 0 1 (by decide) * sw 0 1 (by decide) : SL3) :
    Matrix (Fin 3) (Fin 3) ℤ) = !![-1,0,0; 0,-1,0; 0,0,1] := by
  rw [Matrix.SpecialLinearGroup.coe_mul, sw_coe_01]
  decide

theorem sw_sq_02 : ((sw 0 2 (by decide) * sw 0 2 (by decide) : SL3) :
    Matrix (Fin 3) (Fin 3) ℤ) = !![-1,0,0; 0,1,0; 0,0,-1] := by
  rw [Matrix.SpecialLinearGroup.coe_mul, sw_coe_02]
  decide

theorem sw_sq_12 : ((sw 1 2 (by decide) * sw 1 2 (by decide) : SL3) :
    Matrix (Fin 3) (Fin 3) ℤ) = !![1,0,0; 0,-1,0; 0,0,-1] := by
  rw [Matrix.SpecialLinearGroup.coe_mul, sw_coe_12]
  decide

/-! ## Every determinant-one matrix lies in the elementary subgroup -/

private theorem sign_cases {x : ℤ} (h : ∃ y, x * y = 1) :
    x = 1 ∨ x = -1 :=
  Int.eq_one_or_neg_one_of_mul_eq_one h.choose_spec

theorem mem_H (A : SL3) : A ∈ H := by
  classical
  -- Stage 1a: clear the (2,0) entry using rows 0 and 2.
  obtain ⟨L1, hL1, h20, hfix1, _⟩ :=
    pair_reduce 0 0 2 (by decide) A
  set A1 : SL3 := L1 * A with hA1def
  have hA1coe : (A1 : Matrix (Fin 3) (Fin 3) ℤ) =
      (L1 : Matrix (Fin 3) (Fin 3) ℤ) * (A : Matrix (Fin 3) (Fin 3) ℤ) := by
    rw [hA1def]; simp [Matrix.SpecialLinearGroup.coe_mul]
  have hA1_20 : (A1 : Matrix (Fin 3) (Fin 3) ℤ) 2 0 = 0 := by
    rw [hA1coe]; exact h20
  -- Stage 1b: clear the (1,0) entry using rows 0 and 1; row 2 is fixed.
  obtain ⟨L2, hL2, h10, hfix2, _⟩ :=
    pair_reduce 0 0 1 (by decide) A1
  set A2 : SL3 := L2 * A1 with hA2def
  have hA2coe : (A2 : Matrix (Fin 3) (Fin 3) ℤ) =
      (L2 : Matrix (Fin 3) (Fin 3) ℤ) * (A1 : Matrix (Fin 3) (Fin 3) ℤ) := by
    rw [hA2def]; simp [Matrix.SpecialLinearGroup.coe_mul]
  have hA2_10 : (A2 : Matrix (Fin 3) (Fin 3) ℤ) 1 0 = 0 := by
    rw [hA2coe]; exact h10
  have hA2_20 : (A2 : Matrix (Fin 3) (Fin 3) ℤ) 2 0 = 0 := by
    rw [hA2coe, hfix2 2 (by decide) (by decide) 0]
    exact hA1_20
  -- The (0,0) entry is a unit.
  have hdet2 : (A2 : Matrix (Fin 3) (Fin 3) ℤ).det = 1 := A2.property
  have hunit0 : (A2 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 = 1 ∨
      (A2 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 = -1 := by
    have hexp := Matrix.det_fin_three (A2 : Matrix (Fin 3) (Fin 3) ℤ)
    rw [hexp, hA2_10, hA2_20] at hdet2
    exact sign_cases ⟨(A2 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 *
      (A2 : Matrix (Fin 3) (Fin 3) ℤ) 2 2 -
      (A2 : Matrix (Fin 3) (Fin 3) ℤ) 1 2 *
      (A2 : Matrix (Fin 3) (Fin 3) ℤ) 2 1, by linear_combination hdet2⟩
  -- Stage 1c: clear the (0,1) and (0,2) entries by column operations,
  -- using that the (0,0) entry squares to one.
  have hsq0 : (A2 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 *
      (A2 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 = 1 := by
    rcases hunit0 with h | h <;> rw [h] <;> ring
  set c1 : ℤ := -((A2 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 *
    (A2 : Matrix (Fin 3) (Fin 3) ℤ) 0 1) with hc1
  set c2 : ℤ := -((A2 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 *
    (A2 : Matrix (Fin 3) (Fin 3) ℤ) 0 2) with hc2
  set R1 : SL3 := tv 0 1 (by decide) c1 * tv 0 2 (by decide) c2 with hR1
  set A3 : SL3 := A2 * R1 with hA3def
  have hA3coe : (A3 : Matrix (Fin 3) (Fin 3) ℤ) =
      ((A2 : Matrix (Fin 3) (Fin 3) ℤ) *
        (tv 0 1 (by decide) c1 : Matrix (Fin 3) (Fin 3) ℤ)) *
        (tv 0 2 (by decide) c2 : Matrix (Fin 3) (Fin 3) ℤ) := by
    rw [hA3def, hR1]
    simp [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_assoc]
  -- entries of A3
  have hA3col0 : ∀ p, (A3 : Matrix (Fin 3) (Fin 3) ℤ) p 0 =
      (A2 : Matrix (Fin 3) (Fin 3) ℤ) p 0 := fun p => by
    rw [hA3coe,
      mul_tv_apply_of_ne 0 2 (by decide) c2 _ p 0 (by decide),
      mul_tv_apply_of_ne 0 1 (by decide) c1 _ p 0 (by decide)]
  have hA3col1 : ∀ p, (A3 : Matrix (Fin 3) (Fin 3) ℤ) p 1 =
      (A2 : Matrix (Fin 3) (Fin 3) ℤ) p 1 +
        c1 * (A2 : Matrix (Fin 3) (Fin 3) ℤ) p 0 := fun p => by
    rw [hA3coe,
      mul_tv_apply_of_ne 0 2 (by decide) c2 _ p 1 (by decide),
      mul_tv_apply_same 0 1 (by decide) c1 _ p]
  have hA3col2 : ∀ p, (A3 : Matrix (Fin 3) (Fin 3) ℤ) p 2 =
      (A2 : Matrix (Fin 3) (Fin 3) ℤ) p 2 +
        c2 * (A2 : Matrix (Fin 3) (Fin 3) ℤ) p 0 := fun p => by
    rw [hA3coe, mul_tv_apply_same 0 2 (by decide) c2 _ p,
      mul_tv_apply_of_ne 0 1 (by decide) c1 _ p 2 (by decide),
      mul_tv_apply_of_ne 0 1 (by decide) c1 _ p 0 (by decide)]
  have hA3_01 : (A3 : Matrix (Fin 3) (Fin 3) ℤ) 0 1 = 0 := by
    rw [hA3col1 0, hc1]
    linear_combination (-((A2 : Matrix (Fin 3) (Fin 3) ℤ) 0 1)) * hsq0
  have hA3_02 : (A3 : Matrix (Fin 3) (Fin 3) ℤ) 0 2 = 0 := by
    rw [hA3col2 0, hc2]
    linear_combination (-((A2 : Matrix (Fin 3) (Fin 3) ℤ) 0 2)) * hsq0
  have hA3_10 : (A3 : Matrix (Fin 3) (Fin 3) ℤ) 1 0 = 0 := by
    rw [hA3col0 1]; exact hA2_10
  have hA3_20 : (A3 : Matrix (Fin 3) (Fin 3) ℤ) 2 0 = 0 := by
    rw [hA3col0 2]; exact hA2_20
  have hA3_00 : (A3 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 =
      (A2 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 := hA3col0 0
  -- Stage 2a: clear the (2,1) entry using rows 1 and 2; row 0 fixed,
  -- and the zero column-0 entries of rows 1 and 2 are preserved.
  obtain ⟨L3, hL3, h21, hfix3, hzero3⟩ :=
    pair_reduce 1 1 2 (by decide) A3
  set A4 : SL3 := L3 * A3 with hA4def
  have hA4coe : (A4 : Matrix (Fin 3) (Fin 3) ℤ) =
      (L3 : Matrix (Fin 3) (Fin 3) ℤ) * (A3 : Matrix (Fin 3) (Fin 3) ℤ) := by
    rw [hA4def]; simp [Matrix.SpecialLinearGroup.coe_mul]
  have hA4row0 : ∀ q, (A4 : Matrix (Fin 3) (Fin 3) ℤ) 0 q =
      (A3 : Matrix (Fin 3) (Fin 3) ℤ) 0 q := fun q => by
    rw [hA4coe]; exact hfix3 0 (by decide) (by decide) q
  have hA4_21 : (A4 : Matrix (Fin 3) (Fin 3) ℤ) 2 1 = 0 := by
    rw [hA4coe]; exact h21
  have hA4_10 : (A4 : Matrix (Fin 3) (Fin 3) ℤ) 1 0 = 0 := by
    rw [hA4coe]
    exact (hzero3 0 hA3_10 hA3_20).1
  have hA4_20 : (A4 : Matrix (Fin 3) (Fin 3) ℤ) 2 0 = 0 := by
    rw [hA4coe]
    exact (hzero3 0 hA3_10 hA3_20).2
  have hA4_01 : (A4 : Matrix (Fin 3) (Fin 3) ℤ) 0 1 = 0 := by
    rw [hA4row0 1]; exact hA3_01
  have hA4_02 : (A4 : Matrix (Fin 3) (Fin 3) ℤ) 0 2 = 0 := by
    rw [hA4row0 2]; exact hA3_02
  have hA4_00 : (A4 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 = 1 ∨
      (A4 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 = -1 := by
    rw [hA4row0 0, hA3_00]; exact hunit0
  -- The (1,1) entry is now a unit as well.
  have hdet4 : (A4 : Matrix (Fin 3) (Fin 3) ℤ).det = 1 := A4.property
  have hexp4 := Matrix.det_fin_three (A4 : Matrix (Fin 3) (Fin 3) ℤ)
  have htriangular : (A4 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 *
      ((A4 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 *
        (A4 : Matrix (Fin 3) (Fin 3) ℤ) 2 2) = 1 := by
    rw [hexp4, hA4_10, hA4_20, hA4_21, hA4_01, hA4_02] at hdet4
    linear_combination hdet4
  have hunit1 : (A4 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 = 1 ∨
      (A4 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 = -1 := by
    exact sign_cases ⟨(A4 : Matrix (Fin 3) (Fin 3) ℤ) 2 2 *
      (A4 : Matrix (Fin 3) (Fin 3) ℤ) 0 0, by linear_combination htriangular⟩
  have hsq1 : (A4 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 *
      (A4 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 = 1 := by
    rcases hunit1 with h | h <;> rw [h] <;> ring
  -- Stage 2b: clear the (1,2) entry by a column operation.
  set c3 : ℤ := -((A4 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 *
    (A4 : Matrix (Fin 3) (Fin 3) ℤ) 1 2) with hc3
  set A5 : SL3 := A4 * tv 1 2 (by decide) c3 with hA5def
  have hA5coe : (A5 : Matrix (Fin 3) (Fin 3) ℤ) =
      (A4 : Matrix (Fin 3) (Fin 3) ℤ) *
        (tv 1 2 (by decide) c3 : Matrix (Fin 3) (Fin 3) ℤ) := by
    rw [hA5def]; simp [Matrix.SpecialLinearGroup.coe_mul]
  have hA5colother : ∀ p q, q ≠ 2 →
      (A5 : Matrix (Fin 3) (Fin 3) ℤ) p q =
        (A4 : Matrix (Fin 3) (Fin 3) ℤ) p q := fun p q hq => by
    rw [hA5coe, mul_tv_apply_of_ne 1 2 (by decide) c3 _ p q hq]
  have hA5col2 : ∀ p, (A5 : Matrix (Fin 3) (Fin 3) ℤ) p 2 =
      (A4 : Matrix (Fin 3) (Fin 3) ℤ) p 2 +
        c3 * (A4 : Matrix (Fin 3) (Fin 3) ℤ) p 1 := fun p => by
    rw [hA5coe, mul_tv_apply_same 1 2 (by decide) c3 _ p]
  -- All off-diagonal entries of A5 vanish.
  have hA5_01 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 0 1 = 0 := by
    rw [hA5colother 0 1 (by decide)]; exact hA4_01
  have hA5_10 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 1 0 = 0 := by
    rw [hA5colother 1 0 (by decide)]; exact hA4_10
  have hA5_20 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 2 0 = 0 := by
    rw [hA5colother 2 0 (by decide)]; exact hA4_20
  have hA5_21 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 2 1 = 0 := by
    rw [hA5colother 2 1 (by decide)]; exact hA4_21
  have hA5_02 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 0 2 = 0 := by
    rw [hA5col2 0, hA4_02, hA4_01]; ring
  have hA5_12 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 1 2 = 0 := by
    rw [hA5col2 1, hc3]
    linear_combination (-((A4 : Matrix (Fin 3) (Fin 3) ℤ) 1 2)) * hsq1
  -- Diagonal entries.
  have hA5_00 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 =
      (A4 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 :=
    hA5colother 0 0 (by decide)
  have hA5_11 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 =
      (A4 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 :=
    hA5colother 1 1 (by decide)
  have hA5_22 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 2 2 =
      (A4 : Matrix (Fin 3) (Fin 3) ℤ) 2 2 +
        c3 * (A4 : Matrix (Fin 3) (Fin 3) ℤ) 2 1 := hA5col2 2
  have hA5_22' : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 2 2 =
      (A4 : Matrix (Fin 3) (Fin 3) ℤ) 2 2 := by
    rw [hA5_22, hA4_21]; ring
  -- The diagonal has determinant one, so the signs pair up.
  have hdet5 : (A5 : Matrix (Fin 3) (Fin 3) ℤ).det = 1 := A5.property
  have hexp5 := Matrix.det_fin_three (A5 : Matrix (Fin 3) (Fin 3) ℤ)
  have hdiagprod : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 *
      ((A5 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 *
        (A5 : Matrix (Fin 3) (Fin 3) ℤ) 2 2) = 1 := by
    rw [hexp5, hA5_10, hA5_20, hA5_21, hA5_01, hA5_02, hA5_12] at hdet5
    linear_combination hdet5
  have hu0 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 = 1 ∨
      (A5 : Matrix (Fin 3) (Fin 3) ℤ) 0 0 = -1 := by
    rw [hA5_00]; exact hA4_00
  have hu1 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 = 1 ∨
      (A5 : Matrix (Fin 3) (Fin 3) ℤ) 1 1 = -1 := by
    rw [hA5_11]; exact hunit1
  -- Identify A5 with one of the four sign diagonals, each of which lies
  -- in the subgroup, then unwind.
  have hA5mem : A5 ∈ H := by
    rcases hu0 with h0 | h0 <;> rcases hu1 with h1 | h1
    · -- (+1, +1, +1): the identity.
      have h2 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 2 2 = 1 := by
        rw [h0, h1] at hdiagprod; linarith
      have : A5 = 1 := by
        apply Subtype.ext
        ext p q
        fin_cases p <;> fin_cases q
        · simpa using h0
        · simpa using hA5_01
        · simpa using hA5_02
        · simpa using hA5_10
        · simpa using h1
        · simpa using hA5_12
        · simpa using hA5_20
        · simpa using hA5_21
        · simpa using h2
      rw [this]; exact H.one_mem
    · -- (+1, -1, -1).
      have h2 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 2 2 = -1 := by
        rw [h0, h1] at hdiagprod; linarith
      have : A5 = sw 1 2 (by decide) * sw 1 2 (by decide) := by
        apply Subtype.ext
        rw [sw_sq_12]
        ext p q
        fin_cases p <;> fin_cases q
        · simpa using h0
        · simpa using hA5_01
        · simpa using hA5_02
        · simpa using hA5_10
        · simpa using h1
        · simpa using hA5_12
        · simpa using hA5_20
        · simpa using hA5_21
        · simpa using h2
      rw [this]
      exact H.mul_mem (sw_mem 1 2 (by decide)) (sw_mem 1 2 (by decide))
    · -- (-1, +1, -1).
      have h2 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 2 2 = -1 := by
        rw [h0, h1] at hdiagprod; linarith
      have : A5 = sw 0 2 (by decide) * sw 0 2 (by decide) := by
        apply Subtype.ext
        rw [sw_sq_02]
        ext p q
        fin_cases p <;> fin_cases q
        · simpa using h0
        · simpa using hA5_01
        · simpa using hA5_02
        · simpa using hA5_10
        · simpa using h1
        · simpa using hA5_12
        · simpa using hA5_20
        · simpa using hA5_21
        · simpa using h2
      rw [this]
      exact H.mul_mem (sw_mem 0 2 (by decide)) (sw_mem 0 2 (by decide))
    · -- (-1, -1, +1).
      have h2 : (A5 : Matrix (Fin 3) (Fin 3) ℤ) 2 2 = 1 := by
        rw [h0, h1] at hdiagprod; linarith
      have : A5 = sw 0 1 (by decide) * sw 0 1 (by decide) := by
        apply Subtype.ext
        rw [sw_sq_01]
        ext p q
        fin_cases p <;> fin_cases q
        · simpa using h0
        · simpa using hA5_01
        · simpa using hA5_02
        · simpa using hA5_10
        · simpa using h1
        · simpa using hA5_12
        · simpa using hA5_20
        · simpa using hA5_21
        · simpa using h2
      rw [this]
      exact H.mul_mem (sw_mem 0 1 (by decide)) (sw_mem 0 1 (by decide))
  -- Unwind: A = L1⁻¹ L2⁻¹ A5 (tv …)⁻¹ R1⁻¹.
  have hA5eq : A5 = L3 * L2 * L1 * A * (R1 * tv 1 2 (by decide) c3) := by
    rw [hA5def, hA4def, hA3def, hA2def, hA1def]
    group
  have hAeq : A = (L3 * L2 * L1)⁻¹ * A5 *
      (R1 * tv 1 2 (by decide) c3)⁻¹ := by
    rw [hA5eq]; group
  rw [hAeq]
  have hR1mem : R1 ∈ H := by
    rw [hR1]
    exact H.mul_mem (tv_mem 0 1 (by decide) c1) (tv_mem 0 2 (by decide) c2)
  exact H.mul_mem
    (H.mul_mem
      (H.inv_mem (H.mul_mem (H.mul_mem hL3 hL2) hL1)) hA5mem)
    (H.inv_mem (H.mul_mem hR1mem (tv_mem 1 2 (by decide) c3)))

/-! ## Surjectivity of the presentation map -/

theorem closure_range_elem_eq_top :
    Subgroup.closure (Set.range elem) = ⊤ :=
  top_unique fun A _ => mem_H A

/-- **Elementary generation.**  The canonical homomorphism from the
thirteen-relator Steinberg-type presentation onto the special linear
group is surjective. -/
theorem toSL3_surjective : Function.Surjective toSL3 := by
  intro A
  have hle : Subgroup.closure (Set.range elem) ≤ MonoidHom.range toSL3 :=
    (Subgroup.closure_le _).mpr (by
      rintro _ ⟨k, rfl⟩
      exact ⟨PresentedGroup.of k, toSL3_of k⟩)
  have hmem : A ∈ Subgroup.closure (Set.range elem) := mem_H A
  obtain ⟨g, hg⟩ := hle hmem
  exact ⟨g, hg⟩

end SL3ElementaryGeneration
end GroupApproximation
