import GroupApproximation.Higman.EvalRaw
import GroupApproximation.Monsters.ChiodoFreeProductAbsorber

/-!
# The generating family of the absorber's direct sum

`Higman.Program`'s split of Chiodo Proposition 3.8 has a first half, **(B1)**:
the restricted direct product `Monsters.CodedDirectSum` is recursively
presented.  A `Higman.RecursivePresentation` is three things --- a family
`gen : ℕ → A`, a proof that it spans, and recursive enumerability of the set
of raw words it kills --- and this file supplies the second.

The family is the obvious one: one generator for each generator of each coded
group, i.e. one for each element of `Monsters.CodedGenerator = Σ c, Fin c.1`,
placed in its own coordinate.  Which enumeration `ℕ → CodedGenerator` is used
is left as a parameter, because the *computability* half of (B1) will want a
specific computable one and the spanning argument does not care: any
surjection will do.

## What is proved

* `sumGen` --- the family, attached to an enumeration.
* `spans_sumGen` --- it spans, for any surjective enumeration.  Two steps: the
  coordinate inclusion of a coded group lands in the closure, because a coded
  group is generated by its own `PresentedGroup.of`
  (`PresentedGroup.closure_range_of`); and every element of a restricted
  direct product is a finite product of coordinate elements
  (`DFinsupp.induction`).

## What is not

Recursive enumerability of `{w | evalRaw (sumGen e) w = 1}`.  `Higman.EvalRaw`
reduces it, algebraically, to a condition on each coordinate
(`evalRaw_codedDirectSum_eq_one_iff`), and `evalRaw_eq_one_of_letters` says
only the finitely many blocks occurring in `w` can contribute; what is left is
to choose `e` computably and to run
`Computability.WordProblemRE.rePred_wordProblemPred` on each block.  None of
that is here.
-/

namespace GroupApproximation
namespace Higman

open GroupApproximation.Monsters

/-! ## 1.  The family -/

/-- The generating family of the restricted direct product attached to an
enumeration `e` of the coded generators: the `n`-th generator is the `(e n).2`
generator of the `(e n).1` coded group, in its own coordinate. -/
noncomputable def sumGen (e : ℕ → CodedGenerator) : ℕ → CodedDirectSum :=
  fun n ↦ codedOf (e n).1 (PresentedGroup.of (e n).2)

theorem sumGen_apply (e : ℕ → CodedGenerator) (n : ℕ) :
    sumGen e n = codedOf (e n).1 (PresentedGroup.of (e n).2) := rfl

/-! ## 2.  It spans -/

/-- Every coordinate inclusion lands in the subgroup generated by the family:
a coded group is generated by its own generators, and each of those is one of
the `sumGen e n`. -/
theorem codedOf_mem_closure_sumGen (e : ℕ → CodedGenerator)
    (he : Function.Surjective e) (c : FinitePresentationCode)
    (a : CodedPresentedGroup c) :
    codedOf c a ∈ Subgroup.closure (Set.range (sumGen e)) := by
  classical
  have hgen : ∀ i : Fin c.1,
      codedOf c (PresentedGroup.of i) ∈
        Subgroup.closure (Set.range (sumGen e)) := by
    intro i
    obtain ⟨n, hn⟩ := he ⟨c, i⟩
    refine Subgroup.subset_closure ⟨n, ?_⟩
    show codedOf (e n).1 (PresentedGroup.of (e n).2) =
      codedOf c (PresentedGroup.of i)
    rw [hn]
  have ha : a ∈ Subgroup.closure
      (Set.range (PresentedGroup.of : Fin c.1 → CodedPresentedGroup c)) := by
    rw [PresentedGroup.closure_range_of]
    exact Subgroup.mem_top a
  induction ha using Subgroup.closure_induction with
  | mem y hy =>
      obtain ⟨i, rfl⟩ := hy
      exact hgen i
  | one =>
      rw [map_one]
      exact Subgroup.one_mem _
  | mul y z _ _ ihy ihz =>
      rw [map_mul]
      exact Subgroup.mul_mem _ ihy ihz
  | inv y _ ihy =>
      rw [map_inv]
      exact Subgroup.inv_mem _ ihy

/-- **The `spans` field of (B1).**  For any surjective enumeration of the
coded generators, the attached family generates the restricted direct
product. -/
theorem spans_sumGen (e : ℕ → CodedGenerator) (he : Function.Surjective e) :
    Subgroup.closure (Set.range (sumGen e)) = ⊤ := by
  classical
  rw [Subgroup.eq_top_iff']
  intro g
  suffices h : ∀ f : Π₀ c : FinitePresentationCode,
      Additive (CodedPresentedGroup c),
      (Multiplicative.ofAdd f : CodedDirectSum) ∈
        Subgroup.closure (Set.range (sumGen e)) by
    exact h (Multiplicative.toAdd g)
  intro f
  refine DFinsupp.induction f ?_ ?_
  · simpa using Subgroup.one_mem (Subgroup.closure (Set.range (sumGen e)))
  · intro c a f' _ _ ih
    have hsplit : (Multiplicative.ofAdd (DFinsupp.single c a + f') :
        CodedDirectSum)
        = codedOf c (Additive.toMul a) * Multiplicative.ofAdd f' := by
      simp [codedOf]
    rw [hsplit]
    exact Subgroup.mul_mem _ (codedOf_mem_closure_sumGen e he c _) ih

/-! ## 3.  What (B1) still owes

Assembling a `RecursivePresentation CodedDirectSum` now needs exactly one
more thing: a *computable* surjection `e : ℕ → CodedGenerator` together with
recursive enumerability of `{w | evalRaw (sumGen e) w = 1}`.  The second is
`Higman.evalRaw_codedDirectSum_eq_one_iff` --- a conjunction over codes ---
cut down to the finitely many blocks occurring in `w` by
`Higman.evalRaw_eq_one_of_letters`, with each remaining conjunct discharged by
`Computability.WordProblemRE.rePred_wordProblemPred`.  It is deliberately not
stated as a structure here: an uninhabited structure at this point would add a
name to the corpus audit's open list without adding information, since
`Higman.AbsorberRecursivePresentation` already carries it. -/

end Higman
end GroupApproximation
