import GroupApproximation.Higman.BridgePresentation
import GroupApproximation.Higman.TransportFiveCoding
import GroupApproximation.Computability.EnumeratedPresentationCodes
import GroupApproximation.Higman.MikhailovaRopeCode

/-!
# A uniform relator program for the rank-three bridge

The effective HNN bridge produces a group generated by `x`, `y`, and the
stable letter `t`.  This file turns that statement into numerical syntax.

There are two stages.  First, `countableCode c` enumerates the numbered HNN
presentation from `BridgePresentation` when the base group is the carrier of
the standard enumerated-presentation code `c`.  Second, `rankThreeCode c`
enumerates exactly the kernel of the map from the free group on `x,y,t` to the
bridge.  The latter code is the finite-rank recursive-presentation input needed
by an effective Higman embedding compiler.

No benign-subgroup or finitely-presented-overgroup witness is an input here.
All programs are obtained by explicit bounded checks and `Code.curry`.
-/

namespace GroupApproximation
namespace Higman
namespace BridgeRelatorCode

open Nat.Partrec
open BridgeEff BridgeWP BridgePresentation
open EnumeratedPresentationCodes
open Transport

abbrev Raw : Type := RawWord
abbrev Certificate : Type := WordCertificate
abbrev Candidate : Type := Raw × Certificate

/-- Total decoding of a candidate word and its normal-closure certificate. -/
def decodeCandidate (n : ℕ) : Candidate :=
  (Encodable.decode (α := Candidate) n).getD ([], ([], [], []))

theorem primrec_decodeCandidate : Primrec decodeCandidate :=
  Primrec.option_getD.comp
    (@Primrec.decode Candidate _)
    (Primrec.const ([], ([], [], [])))

/-- The canonical generating family of a standard enumerated presentation. -/
def sourceGen (c : EnumeratedPresentationCodes.PresentationCode) :
    ℕ → EnumeratedPresentationCodes.Carrier c :=
  fun k => PresentedGroup.of k

theorem sourceGen_spans (c : EnumeratedPresentationCodes.PresentationCode) :
    Subgroup.closure (Set.range (sourceGen c)) = ⊤ :=
  PresentedGroup.closure_range_of _

/-- Raw spelling of a numbered base relator in the bridge presentation. -/
def countableBaseRelator
    (c : EnumeratedPresentationCodes.PresentationCode) (n : ℕ) : Raw :=
  let q := decodeCandidate n
  bif wordCheck (c, q.1) q.2 then
    relabel cycle (relabel (fun k => k + 3) q.1)
  else []

/-- A total enumeration of the countable HNN presentation.  Even addresses
enumerate certified base relations; odd addresses enumerate the stable-letter
relations and their inverses. -/
def countableRawRelator
    (c : EnumeratedPresentationCodes.PresentationCode) (address : ℕ) : Raw :=
  let p := Nat.unpair address
  if p.1 % 2 = 0 then countableBaseRelator c p.2
  else relabel cycle (hnnFam p.2)

theorem primrec_countableBaseRelator :
    Primrec₂ countableBaseRelator := by
  have hc : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      z.1 := Primrec.fst
  have hq : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      decodeCandidate z.2 := primrec_decodeCandidate.comp Primrec.snd
  have hw : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      (decodeCandidate z.2).1 := Primrec.fst.comp hq
  have hcert : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      (decodeCandidate z.2).2 := Primrec.snd.comp hq
  have hcheck : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      wordCheck (z.1, (decodeCandidate z.2).1) (decodeCandidate z.2).2 :=
    primrec_wordCheck.comp (Primrec.pair hc hw) hcert
  have hshift : Primrec fun k : ℕ => k + 3 :=
    Primrec.nat_add.comp Primrec.id (Primrec.const 3)
  have hword : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      relabel cycle (relabel (fun k => k + 3) (decodeCandidate z.2).1) :=
    (primrec_relabel primrec_cycle).comp
      ((primrec_relabel hshift).comp hw)
  exact (Primrec.cond hcheck hword (Primrec.const [])).to₂

theorem primrec_countableRawRelator :
    Primrec₂ countableRawRelator := by
  have hp : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      Nat.unpair z.2 := Primrec.unpair.comp Primrec.snd
  have hindex : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      (Nat.unpair z.2).2 := Primrec.snd.comp hp
  have heven : PrimrecPred fun z :
      EnumeratedPresentationCodes.PresentationCode × ℕ =>
      (Nat.unpair z.2).1 % 2 = 0 :=
    Primrec.eq.comp
      (Primrec.nat_mod.comp (Primrec.fst.comp hp) (Primrec.const 2))
      (Primrec.const 0)
  have hbase : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      countableBaseRelator z.1 (Nat.unpair z.2).2 :=
    primrec_countableBaseRelator.comp Primrec.fst hindex
  have hhnn : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      relabel cycle (hnnFam (Nat.unpair z.2).2) :=
    (primrec_relabel primrec_cycle).comp (primrec_hnnFam.comp hindex)
  exact (Primrec.ite heven hbase hhnn).to₂

/-- The direct relator range before packaging it as a standard program. -/
def countableRelatorSet
    (c : EnumeratedPresentationCodes.PresentationCode) : Set (FreeGroup ℕ) :=
  Set.range fun address => freeEval (countableRawRelator c address)

theorem countableRelatorSet_eq (c : EnumeratedPresentationCodes.PresentationCode) :
    countableRelatorSet c = codedRels (sourceGen c) ∪ {1} := by
  apply Set.eq_of_subset_of_subset
  · rintro z ⟨address, rfl⟩
    let p := Nat.unpair address
    by_cases heven : p.1 % 2 = 0
    · let q := decodeCandidate p.2
      by_cases hcheck : wordCheck (c, q.1) q.2 = true
      · apply Or.inl
        have htrivial : evalRaw (sourceGen c) q.1 = 1 :=
          (wordCheck_complete c q.1).2 ⟨q.2, hcheck⟩
        refine ⟨FreeGroup.map (fun k => k + 3) (freeEval q.1),
          Or.inl ⟨freeEval q.1, (mem_wordSet_iff (sourceGen c) q.1).2 htrivial,
            rfl⟩, ?_⟩
        simp [countableRawRelator, p, heven,
          countableBaseRelator, q, hcheck, freeEval_relabel]
      · apply Or.inr
        simp [countableRawRelator, p, heven, countableBaseRelator, q, hcheck,
          freeEval]
    · apply Or.inl
      refine ⟨freeEval (hnnFam p.2), Or.inr ⟨p.2, rfl⟩, ?_⟩
      simp [countableRawRelator, p, heven, freeEval_relabel]
  · rintro z (hz | hz)
    · obtain ⟨u, hu, rfl⟩ := hz
      rcases hu with ⟨v, hv, rfl⟩ | ⟨n, rfl⟩
      · obtain ⟨w, hw⟩ :=
          (mem_closure_iff_exists_evalRaw FreeGroup.of v).1
            (by rw [FreeGroup.closure_range_of]; exact Subgroup.mem_top v)
        have hw' : freeEval w = v := hw
        have hvw : freeEval w ∈ wordSet (sourceGen c) := by
          rw [hw']
          exact hv
        obtain ⟨cert, hcert⟩ := (wordCheck_complete c w).1
          ((mem_wordSet_iff (sourceGen c) w).1 hvw)
        refine ⟨Nat.pair 0 (Encodable.encode (w, cert)), ?_⟩
        simp [countableRawRelator, countableBaseRelator, decodeCandidate,
          hcert, freeEval_relabel, hw']
      · refine ⟨Nat.pair 1 n, ?_⟩
        simp [countableRawRelator, freeEval_relabel]
    · have hzone : z = 1 := by simpa using hz
      subst z
      obtain ⟨cert, hcert⟩ := (wordCheck_complete c []).1 (by simp)
      refine ⟨Nat.pair 0 (Encodable.encode (([] : Raw), cert)), ?_⟩
      simp [countableRawRelator, countableBaseRelator, decodeCandidate, hcert,
        freeEval]

theorem normalClosure_union_one (S : Set (FreeGroup ℕ)) :
    Subgroup.normalClosure (S ∪ {1}) = Subgroup.normalClosure S := by
  apply le_antisymm
  · apply Subgroup.normalClosure_le_normal
    rintro x (hx | hx)
    · exact Subgroup.subset_normalClosure hx
    · have hxone : x = 1 := by simpa using hx
      subst x
      exact Subgroup.one_mem _
  · exact Subgroup.normalClosure_mono Set.subset_union_left

theorem normalClosure_countableRelatorSet
    (c : EnumeratedPresentationCodes.PresentationCode) :
    Subgroup.normalClosure (countableRelatorSet c) =
      Subgroup.normalClosure (codedRels (sourceGen c)) := by
  rw [countableRelatorSet_eq, normalClosure_union_one]

/-! ## Packaging the countable enumerator as a numerical program -/

def decodeCountableInput (n : ℕ) :
    EnumeratedPresentationCodes.PresentationCode × ℕ :=
  (Encodable.decode
    (α := EnumeratedPresentationCodes.PresentationCode × ℕ) n).getD
      (Code.zero, 0)

theorem primrec_decodeCountableInput : Primrec decodeCountableInput :=
  Primrec.option_getD.comp
    (@Primrec.decode (EnumeratedPresentationCodes.PresentationCode × ℕ) _)
    (Primrec.const (Code.zero, 0))

def encodedCountableEnumerator (input : ℕ) : Part ℕ :=
  let p := decodeCountableInput input
  Part.some (Encodable.encode (countableRawRelator p.1 p.2))

theorem encodedCountableEnumerator_partrec :
    Nat.Partrec encodedCountableEnumerator := by
  have hvalue : Primrec fun input : ℕ => Encodable.encode
      (countableRawRelator (decodeCountableInput input).1
        (decodeCountableInput input).2) :=
    Primrec.encode.comp
      (primrec_countableRawRelator.comp
        (Primrec.fst.comp primrec_decodeCountableInput)
        (Primrec.snd.comp primrec_decodeCountableInput))
  exact Nat.Partrec.of_primrec (Primrec.nat_iff.mp hvalue)

noncomputable def universalCountableCode : Code :=
  (Code.exists_code.mp encodedCountableEnumerator_partrec).choose

theorem eval_universalCountableCode :
    Code.eval universalCountableCode = encodedCountableEnumerator :=
  (Code.exists_code.mp encodedCountableEnumerator_partrec).choose_spec

/-- Uniform standard program for the numbered countable bridge presentation. -/
noncomputable def countableCode
    (c : EnumeratedPresentationCodes.PresentationCode) :
    EnumeratedPresentationCodes.PresentationCode :=
  Code.curry universalCountableCode (Encodable.encode c)

theorem primrec_countableCode : Primrec countableCode :=
  Code.primrec₂_curry.comp
    (Primrec.const universalCountableCode) Primrec.encode

theorem computable_countableCode : Computable countableCode :=
  primrec_countableCode.to_comp

theorem eval_countableCode
    (c : EnumeratedPresentationCodes.PresentationCode) (address : ℕ) :
    Code.eval (countableCode c) address =
      Part.some (Encodable.encode (countableRawRelator c address)) := by
  rw [countableCode, Code.eval_curry, eval_universalCountableCode]
  simp [encodedCountableEnumerator, decodeCountableInput]

theorem standard_countable_relatorSet_eq
    (c : EnumeratedPresentationCodes.PresentationCode) :
    EnumeratedPresentationCodes.relatorSet (countableCode c) =
      countableRelatorSet c ∪ {1} := by
  ext z
  constructor
  · rintro ⟨encodedAddress, rfl⟩
    let p := Nat.unpair encodedAddress
    cases heval : Code.evaln p.2 (countableCode c) p.1 with
    | none =>
        apply Or.inr
        simp [rawRelator, p, heval, freeEval]
    | some y =>
        have hsound : y ∈ Code.eval (countableCode c) p.1 := Code.evaln_sound heval
        rw [eval_countableCode] at hsound
        have hy : y = Encodable.encode (countableRawRelator c p.1) := by
          simpa using hsound
        apply Or.inl
        refine ⟨p.1, ?_⟩
        simp [rawRelator, decodeRawWord, p, heval, hy]
  · rintro (hz | hz)
    · obtain ⟨address, rfl⟩ := hz
      have hmem : Encodable.encode (countableRawRelator c address) ∈
          Code.eval (countableCode c) address := by
        rw [eval_countableCode]
        exact Part.mem_some _
      obtain ⟨stage, hstage⟩ := Code.evaln_complete.mp hmem
      have hstage' : Code.evaln stage (countableCode c) address =
          some (Encodable.encode (countableRawRelator c address)) := hstage
      refine ⟨Nat.pair address stage, ?_⟩
      simp [rawRelator, decodeRawWord, hstage']
    · have hzone : z = 1 := by simpa using hz
      subst z
      refine ⟨Nat.pair 0 0, ?_⟩
      have hnone : Code.evaln 0 (countableCode c) 0 = Option.none := by
        cases h : Code.evaln 0 (countableCode c) 0 with
        | none => rfl
        | some y =>
            have hlt : 0 < 0 := Code.evaln_bound h
            omega
      simp [rawRelator, hnone, freeEval]

theorem normalClosure_standard_countable
    (c : EnumeratedPresentationCodes.PresentationCode) :
    Subgroup.normalClosure
        (EnumeratedPresentationCodes.relatorSet (countableCode c)) =
      Subgroup.normalClosure (codedRels (sourceGen c)) := by
  rw [standard_countable_relatorSet_eq,
    normalClosure_union_one,
    normalClosure_countableRelatorSet]

/-! ## The exact rank-three kernel program -/

/-- Rotate `(x,y,t)` into the numbered presentation convention `(t,x,y)`. -/
def rotateRaw (w : Raw) : Raw := relabel (fun k => (k + 1) % 3) w

/-- Normalize arbitrary natural letter codes to the three-letter alphabet. -/
def normalizeThree (w : Raw) : Raw := relabel (fun k => k % 3) w

theorem primrec_rotateRaw : Primrec rotateRaw :=
  primrec_relabel
    (Primrec.nat_mod.comp
      (Primrec.nat_add.comp Primrec.id (Primrec.const 1)) (Primrec.const 3))

theorem primrec_normalizeThree : Primrec normalizeThree :=
  primrec_relabel
    (Primrec.nat_mod.comp Primrec.id (Primrec.const 3))

theorem rawToFree_normalizeThree (w : Raw) :
    rawToFree 2 (normalizeThree w) = rawToFree 2 w := by
  induction w with
  | nil => rfl
  | cons p w ih =>
      obtain ⟨i, s⟩ := p
      change rawToFree 2 ((i % 3, s) :: normalizeThree w) =
        rawToFree 2 ((i, s) :: w)
      rw [rawToFree_cons, rawToFree_cons, ih]
      congr 2
      simp [letterOfNat]

/-- One attempted kernel relator.  A candidate is emitted precisely when its
rotated spelling has a valid word-problem certificate in the countable bridge
presentation. -/
noncomputable def rankThreeRawRelator
    (c : EnumeratedPresentationCodes.PresentationCode) (address : ℕ) : Raw :=
  let q := decodeCandidate address
  bif wordCheck (countableCode c, rotateRaw q.1) q.2 then
    normalizeThree q.1
  else []

theorem primrec_rankThreeRawRelator :
    Primrec₂ rankThreeRawRelator := by
  have hq : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      decodeCandidate z.2 := primrec_decodeCandidate.comp Primrec.snd
  have hw : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      (decodeCandidate z.2).1 := Primrec.fst.comp hq
  have hcert : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      (decodeCandidate z.2).2 := Primrec.snd.comp hq
  have hcode : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      countableCode z.1 := primrec_countableCode.comp Primrec.fst
  have hrot : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      rotateRaw (decodeCandidate z.2).1 := primrec_rotateRaw.comp hw
  have hcheck : Primrec fun z : EnumeratedPresentationCodes.PresentationCode × ℕ =>
      wordCheck (countableCode z.1, rotateRaw (decodeCandidate z.2).1)
        (decodeCandidate z.2).2 :=
    primrec_wordCheck.comp (Primrec.pair hcode hrot) hcert
  exact (Primrec.cond hcheck (primrec_normalizeThree.comp hw)
    (Primrec.const [])).to₂

/-- The finite-rank relator set emitted by the kernel program. -/
def rankThreeRelatorSet
    (c : EnumeratedPresentationCodes.PresentationCode) :
    Set (FreeGroup (Fin 3)) :=
  Set.range fun address => rawToFree 2 (rankThreeRawRelator c address)

theorem pi3_eq_one_iff_wordCheck
    (c : EnumeratedPresentationCodes.PresentationCode) (w : Raw) :
    pi3 (sourceGen c) (rawToFree 2 w) = 1 ↔
      ∃ cert : Certificate,
        wordCheck (countableCode c, rotateRaw w) cert = true := by
  rw [← (extEquivCoded (sourceGen c) (sourceGen_spans c)).map_eq_one_iff,
    pi3_to_coded]
  change evalRaw
      (fun k => (PresentedGroup.of k : PresentedGroup (codedRels (sourceGen c))))
      (rotateRaw w) = 1 ↔ _
  rw [evalRaw_presentedGroup_eq_one_iff]
  rw [← normalClosure_standard_countable]
  rw [← evalRaw_presentedGroup_eq_one_iff]
  exact wordCheck_complete (countableCode c) (rotateRaw w)

/-- **Exactness of the rank-three program.**  Its relator range is the kernel
of the three-generator bridge map. -/
theorem rankThreeRelatorSet_eq_ker
    (c : EnumeratedPresentationCodes.PresentationCode) :
    rankThreeRelatorSet c =
      (MonoidHom.ker (pi3 (sourceGen c)) : Set (FreeGroup (Fin 3))) := by
  apply Set.eq_of_subset_of_subset
  · rintro z ⟨address, rfl⟩
    let q := decodeCandidate address
    by_cases hcheck :
        wordCheck (countableCode c, rotateRaw q.1) q.2 = true
    · change pi3 (sourceGen c) (rawToFree 2
          (rankThreeRawRelator c address)) = 1
      simp [rankThreeRawRelator, q, hcheck, rawToFree_normalizeThree]
      exact (pi3_eq_one_iff_wordCheck c q.1).2 ⟨q.2, hcheck⟩
    · change pi3 (sourceGen c) (rawToFree 2
          (rankThreeRawRelator c address)) = 1
      simp [rankThreeRawRelator, q, hcheck, rawToFree_nil]
  · intro z hz
    obtain ⟨w, rfl⟩ := rawToFree_surjective 2 z
    obtain ⟨cert, hcert⟩ := (pi3_eq_one_iff_wordCheck c w).1 hz
    refine ⟨Encodable.encode (w, cert), ?_⟩
    simp [rankThreeRawRelator, decodeCandidate, hcert,
      rawToFree_normalizeThree]

/-- The kernel is already normal, so taking the normal closure of the emitted
relators adds nothing. -/
theorem normalClosure_rankThreeRelatorSet
    (c : EnumeratedPresentationCodes.PresentationCode) :
    Subgroup.normalClosure (rankThreeRelatorSet c) =
      MonoidHom.ker (pi3 (sourceGen c)) := by
  rw [rankThreeRelatorSet_eq_ker]
  apply le_antisymm
  · exact Subgroup.normalClosure_le_normal (fun _ h => h)
  · exact Subgroup.subset_normalClosure

/-- The group presented by the emitted rank-three relators is the bridge
itself.  This is the semantic contract required of the input to an effective
finite-output Higman compiler. -/
noncomputable def rankThreePresentedEquiv
    (c : EnumeratedPresentationCodes.PresentationCode) :
    PresentedGroup (rankThreeRelatorSet c) ≃*
      HNNEmb.Ext (sourceGen c) :=
  (QuotientGroup.quotientMulEquivOfEq
      (normalClosure_rankThreeRelatorSet c)).trans
    (QuotientGroup.quotientKerEquivOfSurjective
      (pi3 (sourceGen c))
      (pi3_surjective (sourceGen c) (sourceGen_spans c)))

@[simp] theorem rankThreePresentedEquiv_of
    (c : EnumeratedPresentationCodes.PresentationCode) (j : Fin 3) :
    rankThreePresentedEquiv c (PresentedGroup.of j) =
      gen3 (sourceGen c) j := by
  show QuotientGroup.quotientKerEquivOfSurjective
      (pi3 (sourceGen c))
      (pi3_surjective (sourceGen c) (sourceGen_spans c))
      (QuotientGroup.quotientMulEquivOfEq
        (normalClosure_rankThreeRelatorSet c)
        (PresentedGroup.of j)) = _
  rw [show QuotientGroup.quotientMulEquivOfEq
      (normalClosure_rankThreeRelatorSet c) (PresentedGroup.of j) =
        (QuotientGroup.mk (FreeGroup.of j) :
          FreeGroup (Fin 3) ⧸ MonoidHom.ker (pi3 (sourceGen c))) from rfl]
  rw [show QuotientGroup.quotientKerEquivOfSurjective
      (pi3 (sourceGen c))
      (pi3_surjective (sourceGen c) (sourceGen_spans c))
      (QuotientGroup.mk (FreeGroup.of j) :
        FreeGroup (Fin 3) ⧸ MonoidHom.ker (pi3 (sourceGen c))) =
        pi3 (sourceGen c) (FreeGroup.of j) from rfl]
  exact FreeGroup.lift_apply_of

/-! ## Numerical packaging and the exact downstream interface -/

def decodeRankThreeInput (n : ℕ) :
    EnumeratedPresentationCodes.PresentationCode × ℕ :=
  decodeCountableInput n

noncomputable def encodedRankThreeEnumerator (input : ℕ) : Part ℕ :=
  let p := decodeRankThreeInput input
  Part.some (Encodable.encode (rankThreeRawRelator p.1 p.2))

theorem encodedRankThreeEnumerator_partrec :
    Nat.Partrec encodedRankThreeEnumerator := by
  have hvalue : Primrec fun input : ℕ => Encodable.encode
      (rankThreeRawRelator (decodeRankThreeInput input).1
        (decodeRankThreeInput input).2) :=
    Primrec.encode.comp
      (primrec_rankThreeRawRelator.comp
        (Primrec.fst.comp primrec_decodeCountableInput)
        (Primrec.snd.comp primrec_decodeCountableInput))
  exact Nat.Partrec.of_primrec (Primrec.nat_iff.mp hvalue)

noncomputable def universalRankThreeCode : Code :=
  (Code.exists_code.mp encodedRankThreeEnumerator_partrec).choose

theorem eval_universalRankThreeCode :
    Code.eval universalRankThreeCode = encodedRankThreeEnumerator :=
  (Code.exists_code.mp encodedRankThreeEnumerator_partrec).choose_spec

/-- A numerical program enumerating exactly the rank-three bridge kernel. -/
noncomputable def rankThreeCode
    (c : EnumeratedPresentationCodes.PresentationCode) : Code :=
  Code.curry universalRankThreeCode (Encodable.encode c)

theorem primrec_rankThreeCode : Primrec rankThreeCode :=
  Code.primrec₂_curry.comp
    (Primrec.const universalRankThreeCode) Primrec.encode

theorem computable_rankThreeCode : Computable rankThreeCode :=
  primrec_rankThreeCode.to_comp

theorem eval_rankThreeCode
    (c : EnumeratedPresentationCodes.PresentationCode) (address : ℕ) :
    Code.eval (rankThreeCode c) address =
      Part.some (Encodable.encode (rankThreeRawRelator c address)) := by
  rw [rankThreeCode, Code.eval_curry, eval_universalRankThreeCode]
  simp [encodedRankThreeEnumerator, decodeRankThreeInput,
    decodeCountableInput]

/-- The exact input type for the still-missing finite-output Higman compiler:
a rank-three relator program and the three marked source generators. -/
abbrev RecursiveRankThreeInput : Type := Code × MikhailovaRopeCode.RankThreeWords

/-- Uniform recursive rank-three bridge syntax. -/
noncomputable def recursiveRankThreeInput
    (c : EnumeratedPresentationCodes.PresentationCode) :
    RecursiveRankThreeInput :=
  (rankThreeCode c,
    (MikhailovaRopeCode.rankThreeGeneratorWord 0,
      (MikhailovaRopeCode.rankThreeGeneratorWord 1,
        MikhailovaRopeCode.rankThreeGeneratorWord 2)))

theorem primrec_recursiveRankThreeInput : Primrec recursiveRankThreeInput :=
  Primrec.pair primrec_rankThreeCode (Primrec.const _)

theorem computable_recursiveRankThreeInput :
    Computable recursiveRankThreeInput :=
  primrec_recursiveRankThreeInput.to_comp

end BridgeRelatorCode
end Higman
end GroupApproximation
