import GroupApproximation.Higman.BaseCases

/-!
# The calculus of conjugate subgroups `A(S) = ⟨a^u : u ∈ S⟩`

Higman's Section 4 attaches to a set `B` of sequences the subgroup
`A_B = ⟨a^{b_f} : f ∈ B⟩` of `F₃ = ⟨a, b, c⟩`.  Every one of the nine
operations is, at bottom, an operation on the *index set* `b_f ∈ K = ⟨b, c⟩`,
and the three closures already proved (`ι`, `υ`, `σ`) are the three that
happen to be visible directly on the subgroup.  The remaining ones are not:
they move the index set by multiplication, and to see that one needs a
dictionary between

* subgroups of the shape `A(S) = ⟨a^u : u ∈ S⟩`, `S ⊆ K`, and
* subsets `S` of the conjugating subgroup `K`.

This file is that dictionary.  It is stated for an arbitrary `S ⊆ K` rather
than for `S = b_B`, because the operations `ζ`, `π` and `ωₘ` all produce index
sets that are *not* of the form `b_B` for any `B` until they are cut back down
by an intersection, and the cut is one of the steps.

## Contents

* `retK` --- the retraction `F₃ → F₃` killing `a`, so that `F₃` is the
  semidirect product `ker retK ⋊ K`.  Its kernel is benign for free
  (`benignTF_ker_retK`), by `TorsionFreeBenignWitness.ker`, because `F₃` is
  finitely presented and torsion-free.
* `Aset`, `ASub_eq_Aset` --- the subgroup of a set of conjugators, and the
  identification of Higman's `A_B` with it.
* `Aset_union`, `Aset_inter` --- the lattice dictionary, over arbitrary index
  sets.  `Aset_inter` is `Seq.ASub_inter` with the sequence coding removed;
  both come from `Seq.closure_inter_le`, the statement that coordinate
  subgroups of a free group meet as their index sets do.
* `Aset_mul_subgroup` --- **the lemma the remaining operations run on**:

      (A(S) ⊔ U) ⊓ ker retK  =  A(S · U)         (U ≤ K).

  Right translation of the index set by a *subgroup* of `K` is a join followed
  by one intersection.  Both are benign operations already proved, so
  `benignTF_Aset_mul` follows at once, and it is the only new source of benign
  subgroups the operation closures need beyond Higman's Examples 3.5--3.7.

The proof of `Aset_mul_subgroup` is the semidirect product decomposition and
nothing else.  `A(S·U)` is normalized by `U` (right translation by `U` fixes
`S·U`), so every element of `A(S) ⊔ U` is `n · u` with `n ∈ A(S·U)` and
`u ∈ U`; the retraction reads off `u`, so lying in `ker retK` forces `u = 1`.
That is `retK_mem_and_mem_of_mem_sup`, proved by closure induction with the
pair `(x · (retK x)⁻¹, retK x)` as the invariant.
-/

namespace GroupApproximation
namespace Higman
namespace Coord

open GroupApproximation.Higman.Conj
open scoped Pointwise

/-! ## 1.  The retraction killing `a` -/

/-- The retraction of `F₃` onto `K = ⟨b, c⟩` that kills `a`. -/
def retK : F₃ →* F₃ :=
  FreeGroup.lift (fun i : Fin 3 => if i = 0 then 1 else if i = 1 then b else c)

@[simp] theorem retK_a : retK a = 1 := by
  unfold retK a
  rw [FreeGroup.lift_apply_of]
  simp

@[simp] theorem retK_b : retK b = b := by
  unfold retK b
  rw [FreeGroup.lift_apply_of]
  simp

@[simp] theorem retK_c : retK c = c := by
  unfold retK c
  rw [FreeGroup.lift_apply_of]
  simp

/-- **The retraction is the identity on the conjugating subgroup.** -/
theorem retK_of_mem_K {x : F₃} (hx : x ∈ K) : retK x = x := by
  induction hx using Subgroup.closure_induction with
  | mem y hy =>
      rcases hy with rfl | hy
      · exact retK_b
      · rw [Set.mem_singleton_iff] at hy
        subst hy
        exact retK_c
  | one => exact map_one _
  | mul y z _ _ ihy ihz => rw [map_mul, ihy, ihz]
  | inv y _ ihy => rw [map_inv, ihy]

/-- The kernel of the retraction is benign, with a torsion-free witness: it is
the kernel of a homomorphism between finitely presented torsion-free groups. -/
theorem benignTF_ker_retK : BenignTF (MonoidHom.ker retK) :=
  ⟨TorsionFreeBenignWitness.ker IsPowerTorsionFree.of_isMulTorsionFree
    IsPowerTorsionFree.of_isMulTorsionFree retK⟩

/-! ## 2.  Subgroups generated by conjugates -/

/-- The conjugate of `a` by `u`. -/
def conjA (u : F₃) : F₃ := u⁻¹ * a * u

theorem conjA_mul (u v : F₃) : conjA (u * v) = v⁻¹ * conjA u * v := by
  unfold conjA
  group

/-- **The subgroup generated by a set of conjugates of `a`.** -/
def Aset (S : Set F₃) : Subgroup F₃ := Subgroup.closure (conjA '' S)

theorem conjA_mem_Aset {S : Set F₃} {u : F₃} (hu : u ∈ S) : conjA u ∈ Aset S :=
  Subgroup.subset_closure ⟨u, hu, rfl⟩

theorem Aset_mono {S T : Set F₃} (h : S ⊆ T) : Aset S ≤ Aset T :=
  Subgroup.closure_mono (Set.image_mono h)

theorem Aset_union (S T : Set F₃) : Aset (S ∪ T) = Aset S ⊔ Aset T := by
  unfold Aset
  rw [Set.image_union, Subgroup.closure_union]

/-- **Higman's `A_B` is the conjugate subgroup of the coded index set.** -/
theorem ASub_eq_Aset (B : Set Seq.E) : Seq.ASub B = Aset (Seq.bElt '' B) := by
  unfold Seq.ASub Aset
  congr 1
  rw [Set.image_image]
  rfl

/-! ## 3.  The kernel bound -/

theorem retK_conjA {u : F₃} (hu : u ∈ K) : retK (conjA u) = 1 := by
  unfold conjA
  rw [map_mul, map_mul, map_inv, retK_a, retK_of_mem_K hu, mul_one, inv_mul_cancel]

theorem Aset_le_ker {S : Set F₃} (hS : S ⊆ (K : Set F₃)) :
    Aset S ≤ MonoidHom.ker retK := by
  refine (Subgroup.closure_le _).mpr ?_
  rintro _ ⟨u, hu, rfl⟩
  exact MonoidHom.mem_ker.mpr (retK_conjA (hS hu))

/-! ## 4.  The lattice dictionary -/

/-- The index set, read inside the conjugating subgroup. -/
def toK (S : Set F₃) : Set ↥K := Subtype.val ⁻¹' S

theorem toK_inter (S T : Set F₃) : toK (S ∩ T) = toK S ∩ toK T := rfl

theorem Aset_eq_map {S : Set F₃} (hS : S ⊆ (K : Set F₃)) :
    Aset S = (Subgroup.closure (FreeGroup.of '' toK S)).map cbHom := by
  unfold Aset
  rw [MonoidHom.map_closure]
  congr 1
  refine Set.ext fun x => ?_
  constructor
  · rintro ⟨u, hu, rfl⟩
    refine ⟨FreeGroup.of ⟨u, hS hu⟩, ⟨⟨u, hS hu⟩, hu, rfl⟩, ?_⟩
    rw [cbHom_of]
    rfl
  · rintro ⟨_, ⟨v, hv, rfl⟩, rfl⟩
    refine ⟨(v : F₃), hv, ?_⟩
    rw [cbHom_of]
    rfl

/-- **Conjugate subgroups meet as their index sets do.**  This is
`Seq.ASub_inter` with the sequence coding removed. -/
theorem Aset_inter {S T : Set F₃} (hS : S ⊆ (K : Set F₃)) (hT : T ⊆ (K : Set F₃)) :
    Aset (S ∩ T) = Aset S ⊓ Aset T := by
  refine le_antisymm (le_inf (Aset_mono Set.inter_subset_left)
    (Aset_mono Set.inter_subset_right)) ?_
  rw [Aset_eq_map hS, Aset_eq_map hT, Aset_eq_map (Set.inter_subset_left.trans hS),
    ← Seq.map_inf_of_injective cbHom_injective]
  refine Subgroup.map_mono ?_
  rw [toK_inter]
  exact Seq.closure_inter_le (toK S) (toK T)

/-! ## 5.  Right translation of the index set -/

theorem Aset_conj_mem {S : Set F₃} {v : F₃} {x : F₃} (hx : x ∈ Aset S) :
    v⁻¹ * x * v ∈ Aset (S * ({v} : Set F₃)) := by
  induction hx using Subgroup.closure_induction with
  | mem y hy =>
      obtain ⟨u, hu, rfl⟩ := hy
      have hstep : v⁻¹ * conjA u * v = conjA (u * v) := (conjA_mul u v).symm
      rw [hstep]
      exact conjA_mem_Aset ⟨u, hu, v, rfl, rfl⟩
  | one =>
      have h1 : v⁻¹ * (1 : F₃) * v = 1 := by group
      rw [h1]
      exact Subgroup.one_mem _
  | mul y z _ _ ihy ihz =>
      have hyz : v⁻¹ * (y * z) * v = (v⁻¹ * y * v) * (v⁻¹ * z * v) := by group
      rw [hyz]
      exact Subgroup.mul_mem _ ihy ihz
  | inv y _ ihy =>
      have hy : v⁻¹ * y⁻¹ * v = (v⁻¹ * y * v)⁻¹ := by group
      rw [hy]
      exact Subgroup.inv_mem _ ihy

/-- **A translate by a subgroup is normalized by that subgroup.** -/
theorem Aset_conj_mem_of_subgroup {S : Set F₃} {U : Subgroup F₃} {v : F₃}
    (hv : v ∈ U) {x : F₃} (hx : x ∈ Aset (S * (U : Set F₃))) :
    v⁻¹ * x * v ∈ Aset (S * (U : Set F₃)) := by
  have h := Aset_conj_mem (S := S * (U : Set F₃)) (v := v) hx
  refine Aset_mono ?_ h
  intro w hw
  obtain ⟨y, hy, z, hz, rfl⟩ := hw
  obtain ⟨s, hs, u, hu, rfl⟩ := hy
  rw [Set.mem_singleton_iff] at hz
  subst hz
  exact ⟨s, hs, u * z, U.mul_mem hu hv, (mul_assoc _ _ _).symm⟩

/-- **The semidirect decomposition of a join with a subgroup of `K`.**  Every
element of `A(S) ⊔ U` splits as an element of `A(S·U)` times an element of
`U`, and the retraction reads off the second factor. -/
theorem retK_mem_and_mem_of_mem_sup {S : Set F₃} (hS : S ⊆ (K : Set F₃))
    {U : Subgroup F₃} (hU : U ≤ K) {x : F₃} (hx : x ∈ Aset S ⊔ U) :
    x * (retK x)⁻¹ ∈ Aset (S * (U : Set F₃)) ∧ retK x ∈ U := by
  have hSU : S ⊆ S * (U : Set F₃) := fun s hs => ⟨s, hs, 1, U.one_mem, mul_one s⟩
  have hgen : Aset S ⊔ U = Subgroup.closure ((Aset S : Set F₃) ∪ (U : Set F₃)) := by
    rw [Subgroup.closure_union, Subgroup.closure_eq, Subgroup.closure_eq]
  rw [hgen] at hx
  induction hx using Subgroup.closure_induction with
  | mem y hy =>
      rcases hy with hy | hy
      · have hker : retK y = 1 := MonoidHom.mem_ker.mp (Aset_le_ker hS hy)
        rw [hker, inv_one, mul_one]
        exact ⟨Aset_mono hSU hy, U.one_mem⟩
      · have hret : retK y = y := retK_of_mem_K (hU hy)
        rw [hret, mul_inv_cancel]
        exact ⟨Subgroup.one_mem _, hy⟩
  | one =>
      rw [map_one, inv_one, mul_one]
      exact ⟨Subgroup.one_mem _, U.one_mem⟩
  | mul y z _ _ ihy ihz =>
      obtain ⟨ihy1, ihy2⟩ := ihy
      obtain ⟨ihz1, ihz2⟩ := ihz
      refine ⟨?_, ?_⟩
      · have hsplit : y * z * (retK (y * z))⁻¹
            = (y * (retK y)⁻¹) * ((retK y) * (z * (retK z)⁻¹) * (retK y)⁻¹) := by
          rw [map_mul]
          group
        rw [hsplit]
        refine Subgroup.mul_mem _ ihy1 ?_
        have hconj := Aset_conj_mem_of_subgroup (S := S) (U := U) (v := (retK y)⁻¹)
          (U.inv_mem ihy2) ihz1
        rw [inv_inv] at hconj
        exact hconj
      · rw [map_mul]
        exact U.mul_mem ihy2 ihz2
  | inv y _ ihy =>
      obtain ⟨ihy1, ihy2⟩ := ihy
      refine ⟨?_, ?_⟩
      · have hsplit : y⁻¹ * (retK y⁻¹)⁻¹
            = (retK y)⁻¹ * (y * (retK y)⁻¹)⁻¹ * (retK y) := by
          rw [map_inv]
          group
        rw [hsplit]
        exact Aset_conj_mem_of_subgroup ihy2 (Subgroup.inv_mem _ ihy1)
      · rw [map_inv]
        exact U.inv_mem ihy2

/-- **Right translation of the index set by a subgroup of `K` is a join
followed by one intersection.** -/
theorem Aset_mul_subgroup {S : Set F₃} (hS : S ⊆ (K : Set F₃)) {U : Subgroup F₃}
    (hU : U ≤ K) : (Aset S ⊔ U) ⊓ MonoidHom.ker retK = Aset (S * (U : Set F₃)) := by
  have hSU : S * (U : Set F₃) ⊆ (K : Set F₃) := by
    rintro _ ⟨s, hs, u, hu, rfl⟩
    exact K.mul_mem (hS hs) (hU hu)
  refine le_antisymm ?_ ?_
  · rintro x ⟨hx1, hx2⟩
    have h := retK_mem_and_mem_of_mem_sup hS hU hx1
    have hker : retK x = 1 := MonoidHom.mem_ker.mp hx2
    rw [hker, inv_one, mul_one] at h
    exact h.1
  · refine le_inf ?_ (Aset_le_ker hSU)
    refine (Subgroup.closure_le _).mpr ?_
    rintro _ ⟨w, hw, rfl⟩
    obtain ⟨s, hs, u, hu, rfl⟩ := hw
    rw [conjA_mul]
    refine Subgroup.mul_mem _ (Subgroup.mul_mem _ ?_ ?_) ?_
    · exact Subgroup.mem_sup_right (U.inv_mem hu)
    · exact Subgroup.mem_sup_left (conjA_mem_Aset hs)
    · exact Subgroup.mem_sup_right hu

/-- **Right translation by a benign subgroup of `K` preserves benignness.**
This is the one new construction the operation closures need. -/
theorem benignTF_Aset_mul {S : Set F₃} (hS : S ⊆ (K : Set F₃)) {U : Subgroup F₃}
    (hU : U ≤ K) (hA : BenignTF (Aset S)) (hUb : BenignTF U) :
    BenignTF (Aset (S * (U : Set F₃))) := by
  letI : Group.FG F₃ := ProductFinitePresentation.fg_of_isFinitelyPresented F₃
  rw [← Aset_mul_subgroup hS hU]
  exact BenignTF.inf (BenignTF.sup hA hUb) benignTF_ker_retK

end Coord
end Higman
end GroupApproximation
