import GroupApproximation.Higman.RowBasis
import Mathlib.GroupTheory.Coprod.Basic
import Mathlib.GroupTheory.HNNExtension

/-!
# Every countable group embeds in a three-generator group

This is the Higman--Neumann--Neumann embedding, and it is the bridge Chiodo's
Theorem 2.2 needs over Higman's: Higman's theorem is about finitely generated
groups, while `Monsters.ChiodoAbsorber` is only countably generated.

Let `A` be countable, enumerated by `g : ℕ → A`, and put `P = A ∗ F₂` with
`F₂ = ⟨x, y⟩`.  Set

    aᵢ = x⁻ⁱ y xⁱ,     bᵢ = gᵢ · aᵢ        (i : ℕ).

Both families are free bases of the subgroups they generate, so there is an
isomorphism `aᵢ ↦ bᵢ` between those subgroups, and the HNN extension along it
contains `P`, hence `A`.  In it `t aᵢ t⁻¹ = bᵢ = gᵢ aᵢ`, so

    gᵢ = t aᵢ t⁻¹ aᵢ⁻¹ ∈ ⟨x, y, t⟩,

and since the `gᵢ` exhaust `A`, the whole extension is generated by `x`, `y`
and `t`.

## The freeness proofs

Both are the action device of `Higman.RowBasis`, with the state carrying what
the word has to remember.  For the `aᵢ` the state is `FreeGroup ℕ × ℤ`: `x`
shifts the counter, `y` writes the counter into the word, and `A` acts
trivially.  For the `bᵢ` the state is `FreeGroup ℕ × ℤ × A`: `y` additionally
puts `gₙ⁻¹` into the third coordinate, where `n` is the current counter, and
the left factor `A` multiplies it back, so that the slice `(·, 0, 1)` is
preserved and `bᵢ` acts on it exactly as left multiplication by the `i`-th
generator of `FreeGroup ℕ`.

No normal form theorem for free products is used.
-/

namespace GroupApproximation
namespace Higman
namespace HNNEmb

open scoped Monoid.Coprod

variable {A : Type} [Group A] (g : ℕ → A)

/-- The free product of `A` with a free group of rank two. -/
abbrev P (A : Type) [Group A] : Type := Monoid.Coprod A (FreeGroup (Fin 2))

/-- The left factor. -/
def iA : A →* P A := Monoid.Coprod.inl

/-- The right factor. -/
def iF : FreeGroup (Fin 2) →* P A := Monoid.Coprod.inr

/-- The first free generator. -/
def xg : P A := iF (FreeGroup.of 0)

/-- The second free generator. -/
def yg : P A := iF (FreeGroup.of 1)

/-- The retraction onto the left factor. -/
def retractA : P A →* A := Monoid.Coprod.lift (MonoidHom.id A) 1

@[simp] theorem retractA_iA (α : A) : retractA (iA α) = α := by
  unfold retractA iA
  rw [Monoid.Coprod.lift_apply_inl]
  rfl

theorem iA_injective : Function.Injective (iA : A →* P A) := by
  intro u v huv
  have h := congrArg retractA huv
  rwa [retractA_iA, retractA_iA] at h

/-- The `i`-th free element. -/
def aFam (i : ℕ) : P A := xg ^ (-(i : ℤ)) * yg * xg ^ (i : ℤ)

/-- The `i`-th twisted element. -/
def bFam (i : ℕ) : P A := iA (g i) * aFam i

/-! ## 1.  The action that sees the `aᵢ` -/

/-- The state for the untwisted family. -/
abbrev St : Type := FreeGroup ℕ × ℤ

/-- `x` shifts the counter. -/
def xPerm' : Equiv.Perm St where
  toFun p := (p.1, p.2 + 1)
  invFun p := (p.1, p.2 - 1)
  left_inv p := by
    refine Prod.ext rfl ?_
    show p.2 + 1 - 1 = p.2
    ring
  right_inv p := by
    refine Prod.ext rfl ?_
    show p.2 - 1 + 1 = p.2
    ring

/-- `y` writes the counter. -/
def yPerm' : Equiv.Perm St where
  toFun p := (FreeGroup.of p.2.toNat * p.1, p.2)
  invFun p := ((FreeGroup.of p.2.toNat)⁻¹ * p.1, p.2)
  left_inv p := by
    refine Prod.ext ?_ rfl
    show (FreeGroup.of p.2.toNat)⁻¹ * (FreeGroup.of p.2.toNat * p.1) = p.1
    group
  right_inv p := by
    refine Prod.ext ?_ rfl
    show FreeGroup.of p.2.toNat * ((FreeGroup.of p.2.toNat)⁻¹ * p.1) = p.1
    group

/-- The action of `P` in which `A` does nothing. -/
def act' : P A →* Equiv.Perm St :=
  Monoid.Coprod.lift 1 (FreeGroup.lift (fun i : Fin 2 => if i = 0 then xPerm' else yPerm'))

@[simp] theorem act'_iA (α : A) : act' (iA α : P A) = 1 := by
  unfold act' iA
  rw [Monoid.Coprod.lift_apply_inl]
  rfl

@[simp] theorem act'_x : act' (xg : P A) = xPerm' := by
  simp [act', xg, iF]

@[simp] theorem act'_y : act' (yg : P A) = yPerm' := by
  simp [act', yg, iF]

theorem act'_x_zpow (k : ℤ) (p : St) :
    act' (xg ^ k : P A) p = (p.1, p.2 + k) := by
  rw [map_zpow, act'_x]
  induction k using Int.induction_on generalizing p with
  | zero =>
      show p = (p.1, p.2 + 0)
      rw [add_zero]
  | succ n ih =>
      rw [zpow_add, zpow_one]
      change (xPerm' ^ (n : ℤ)) (xPerm' p) = _
      rw [ih]
      refine Prod.ext rfl ?_
      show p.2 + 1 + (n : ℤ) = p.2 + ((n : ℤ) + 1)
      ring
  | pred n ih =>
      rw [zpow_sub, zpow_one]
      change (xPerm' ^ (-(n : ℤ))) (xPerm'.symm p) = _
      rw [ih]
      refine Prod.ext rfl ?_
      show p.2 - 1 + -(n : ℤ) = p.2 + (-(n : ℤ) - 1)
      ring

/-- **What the untwisted family does on the zero slice.** -/
theorem act'_aFam (i : ℕ) (w : FreeGroup ℕ) :
    act' (aFam i : P A) (w, (0 : ℤ)) = (FreeGroup.of i * w, 0) := by
  unfold aFam
  rw [map_mul, map_mul]
  show act' (xg ^ (-(i : ℤ)) : P A) (act' (yg : P A)
    (act' (xg ^ (i : ℤ) : P A) (w, (0 : ℤ)))) = _
  rw [act'_x_zpow (A := A) (i : ℤ) (w, (0 : ℤ))]
  show act' (xg ^ (-(i : ℤ)) : P A) (act' (yg : P A) (w, (0 : ℤ) + (i : ℤ))) = _
  rw [act'_y]
  show act' (xg ^ (-(i : ℤ)) : P A)
    (FreeGroup.of ((0 : ℤ) + (i : ℤ)).toNat * w, (0 : ℤ) + (i : ℤ)) = _
  rw [act'_x_zpow (A := A) (-(i : ℤ))
    (FreeGroup.of ((0 : ℤ) + (i : ℤ)).toNat * w, (0 : ℤ) + (i : ℤ))]
  refine Prod.ext ?_ ?_
  · show FreeGroup.of ((0 : ℤ) + (i : ℤ)).toNat * w = FreeGroup.of i * w
    congr 2
    rw [zero_add, Int.toNat_natCast]
  · show (0 : ℤ) + (i : ℤ) + -(i : ℤ) = 0
    ring

end HNNEmb
end Higman
end GroupApproximation

namespace GroupApproximation
namespace Higman
namespace HNNEmb

open scoped Monoid.Coprod

variable {A : Type} [Group A] (g : ℕ → A)

/-! ## 2.  The action that sees the `bᵢ` -/

/-- The state for the twisted family. -/
abbrev St₂ (A : Type) : Type := FreeGroup ℕ × ℤ × A

/-- `x` shifts the counter. -/
def xPerm₂ : Equiv.Perm (St₂ A) where
  toFun p := (p.1, p.2.1 + 1, p.2.2)
  invFun p := (p.1, p.2.1 - 1, p.2.2)
  left_inv p := by
    refine Prod.ext rfl (Prod.ext ?_ rfl)
    show p.2.1 + 1 - 1 = p.2.1
    ring
  right_inv p := by
    refine Prod.ext rfl (Prod.ext ?_ rfl)
    show p.2.1 - 1 + 1 = p.2.1
    ring

/-- `y` writes the counter and deposits the inverse of the corresponding group
element. -/
def yPerm₂ : Equiv.Perm (St₂ A) where
  toFun p := (FreeGroup.of p.2.1.toNat * p.1, p.2.1, (g p.2.1.toNat)⁻¹ * p.2.2)
  invFun p := ((FreeGroup.of p.2.1.toNat)⁻¹ * p.1, p.2.1, g p.2.1.toNat * p.2.2)
  left_inv p := by
    refine Prod.ext ?_ (Prod.ext rfl ?_)
    · show (FreeGroup.of p.2.1.toNat)⁻¹ * (FreeGroup.of p.2.1.toNat * p.1) = p.1
      group
    · show g p.2.1.toNat * ((g p.2.1.toNat)⁻¹ * p.2.2) = p.2.2
      group
  right_inv p := by
    refine Prod.ext ?_ (Prod.ext rfl ?_)
    · show FreeGroup.of p.2.1.toNat * ((FreeGroup.of p.2.1.toNat)⁻¹ * p.1) = p.1
      group
    · show (g p.2.1.toNat)⁻¹ * (g p.2.1.toNat * p.2.2) = p.2.2
      group

/-- The left factor acts by left translation of the third coordinate. -/
def aPermHom : A →* Equiv.Perm (St₂ A) where
  toFun α :=
    { toFun := fun p => (p.1, p.2.1, α * p.2.2)
      invFun := fun p => (p.1, p.2.1, α⁻¹ * p.2.2)
      left_inv := fun p => by
        refine Prod.ext rfl (Prod.ext rfl ?_)
        show α⁻¹ * (α * p.2.2) = p.2.2
        group
      right_inv := fun p => by
        refine Prod.ext rfl (Prod.ext rfl ?_)
        show α * (α⁻¹ * p.2.2) = p.2.2
        group }
  map_one' := by
    refine Equiv.ext fun p => ?_
    refine Prod.ext rfl (Prod.ext rfl ?_)
    show (1 : A) * p.2.2 = p.2.2
    rw [one_mul]
  map_mul' := by
    intro α β
    refine Equiv.ext fun p => ?_
    refine Prod.ext rfl (Prod.ext rfl ?_)
    show α * β * p.2.2 = α * (β * p.2.2)
    group

/-- The twisted action. -/
def act₂ : P A →* Equiv.Perm (St₂ A) :=
  Monoid.Coprod.lift (aPermHom)
    (FreeGroup.lift (fun i : Fin 2 => if i = 0 then xPerm₂ else yPerm₂ g))

@[simp] theorem act₂_iA (α : A) : act₂ g (iA α : P A) = aPermHom α := by
  unfold act₂ iA
  rw [Monoid.Coprod.lift_apply_inl]

@[simp] theorem act₂_x : act₂ g (xg : P A) = xPerm₂ := by
  simp [act₂, xg, iF]

@[simp] theorem act₂_y : act₂ g (yg : P A) = yPerm₂ g := by
  simp [act₂, yg, iF]

theorem act₂_x_zpow (k : ℤ) (p : St₂ A) :
    act₂ g (xg ^ k : P A) p = (p.1, p.2.1 + k, p.2.2) := by
  rw [map_zpow, act₂_x]
  induction k using Int.induction_on generalizing p with
  | zero =>
      show p = (p.1, p.2.1 + 0, p.2.2)
      rw [add_zero]
  | succ n ih =>
      rw [zpow_add, zpow_one]
      change ((xPerm₂ : Equiv.Perm (St₂ A)) ^ (n : ℤ)) (xPerm₂ p) = _
      rw [ih]
      refine Prod.ext rfl (Prod.ext ?_ rfl)
      show p.2.1 + 1 + (n : ℤ) = p.2.1 + ((n : ℤ) + 1)
      ring
  | pred n ih =>
      rw [zpow_sub, zpow_one]
      change ((xPerm₂ : Equiv.Perm (St₂ A)) ^ (-(n : ℤ))) (xPerm₂.symm p) = _
      rw [ih]
      refine Prod.ext rfl (Prod.ext ?_ rfl)
      show p.2.1 - 1 + -(n : ℤ) = p.2.1 + (-(n : ℤ) - 1)
      ring

theorem act₂_aFam (i : ℕ) (w : FreeGroup ℕ) (α : A) :
    act₂ g (aFam i : P A) (w, (0 : ℤ), α)
      = (FreeGroup.of i * w, 0, (g i)⁻¹ * α) := by
  unfold aFam
  rw [map_mul, map_mul]
  show act₂ g (xg ^ (-(i : ℤ)) : P A) (act₂ g (yg : P A)
    (act₂ g (xg ^ (i : ℤ) : P A) (w, (0 : ℤ), α))) = _
  rw [act₂_x_zpow g (i : ℤ) (w, (0 : ℤ), α)]
  show act₂ g (xg ^ (-(i : ℤ)) : P A)
    (act₂ g (yg : P A) (w, (0 : ℤ) + (i : ℤ), α)) = _
  rw [act₂_y]
  show act₂ g (xg ^ (-(i : ℤ)) : P A)
    (FreeGroup.of ((0 : ℤ) + (i : ℤ)).toNat * w, (0 : ℤ) + (i : ℤ),
      (g ((0 : ℤ) + (i : ℤ)).toNat)⁻¹ * α) = _
  rw [act₂_x_zpow g (-(i : ℤ))
    (FreeGroup.of ((0 : ℤ) + (i : ℤ)).toNat * w, (0 : ℤ) + (i : ℤ),
      (g ((0 : ℤ) + (i : ℤ)).toNat)⁻¹ * α)]
  have htn : ((0 : ℤ) + (i : ℤ)).toNat = i := by
    rw [zero_add, Int.toNat_natCast]
  refine Prod.ext ?_ (Prod.ext ?_ ?_)
  · show FreeGroup.of ((0 : ℤ) + (i : ℤ)).toNat * w = FreeGroup.of i * w
    rw [htn]
  · show (0 : ℤ) + (i : ℤ) + -(i : ℤ) = 0
    ring
  · show (g ((0 : ℤ) + (i : ℤ)).toNat)⁻¹ * α = (g i)⁻¹ * α
    rw [htn]

theorem act₂_bFam (i : ℕ) (w : FreeGroup ℕ) (α : A) :
    act₂ g (bFam g i : P A) (w, (0 : ℤ), α) = (FreeGroup.of i * w, 0, α) := by
  unfold bFam
  rw [map_mul]
  show act₂ g (iA (g i) : P A) (act₂ g (aFam i : P A) (w, (0 : ℤ), α)) = _
  rw [act₂_aFam, act₂_iA]
  refine Prod.ext rfl (Prod.ext rfl ?_)
  show g i * ((g i)⁻¹ * α) = α
  group

end HNNEmb
end Higman
end GroupApproximation

namespace GroupApproximation
namespace Higman
namespace HNNEmb

open scoped Monoid.Coprod

variable {A : Type} [Group A] (g : ℕ → A)

/-! ## 3.  Both families are free bases -/

/-- The homomorphism onto the untwisted family. -/
def aHom : FreeGroup ℕ →* P A := FreeGroup.lift (aFam (A := A))

@[simp] theorem aHom_of (i : ℕ) : (aHom : FreeGroup ℕ →* P A) (FreeGroup.of i) = aFam i := by
  simp [aHom]

/-- The homomorphism onto the twisted family. -/
def bHom : FreeGroup ℕ →* P A := FreeGroup.lift (bFam g)

@[simp] theorem bHom_of (i : ℕ) : bHom g (FreeGroup.of i) = bFam g i := by
  simp [bHom]

/-- The words on which the untwisted action is left multiplication. -/
def GoodA : Subgroup (FreeGroup ℕ) where
  carrier := {W : FreeGroup ℕ | ∀ w : FreeGroup ℕ,
    act' ((aHom : FreeGroup ℕ →* P A) W) (w, (0 : ℤ)) = (W * w, 0)}
  one_mem' := by
    intro w
    rw [map_one, map_one, one_mul]
    rfl
  mul_mem' := by
    intro u v hu hv w
    rw [map_mul, map_mul]
    show act' ((aHom : FreeGroup ℕ →* P A) u)
      (act' ((aHom : FreeGroup ℕ →* P A) v) (w, (0 : ℤ))) = _
    rw [hv w, hu (v * w)]
    refine Prod.ext ?_ rfl
    show u * (v * w) = u * v * w
    group
  inv_mem' := by
    intro u hu w
    have hkey : act' ((aHom : FreeGroup ℕ →* P A) u) (u⁻¹ * w, (0 : ℤ)) = (w, 0) := by
      rw [hu (u⁻¹ * w)]
      refine Prod.ext ?_ rfl
      show u * (u⁻¹ * w) = w
      group
    rw [map_inv, map_inv]
    have hinv : (act' ((aHom : FreeGroup ℕ →* P A) u))⁻¹ (w, (0 : ℤ)) = (u⁻¹ * w, 0) :=
      by
        apply (act' ((aHom : FreeGroup ℕ →* P A) u)).injective
        simpa using hkey.symm
    show (act' ((aHom : FreeGroup ℕ →* P A) u))⁻¹ (w, (0 : ℤ)) = _
    rw [hinv]

theorem goodA_eq_top : (GoodA (A := A)) = ⊤ := by
  refine top_le_iff.mp ?_
  intro W _hW
  refine FreeGroup.induction_on W ?_ ?_ ?_ ?_
  · exact Subgroup.one_mem _
  · intro i w
    rw [aHom_of]
    exact act'_aFam i w
  · intro i hmem
    exact Subgroup.inv_mem _ hmem
  · intro u v hu hv
    exact Subgroup.mul_mem _ hu hv

/-- **The untwisted family is a free basis.** -/
theorem aHom_injective : Function.Injective (aHom : FreeGroup ℕ →* P A) := by
  rw [injective_iff_map_eq_one]
  intro W hW
  have hgood : W ∈ (GoodA (A := A)) := by
    rw [goodA_eq_top]
    exact Subgroup.mem_top W
  have h := hgood 1
  rw [hW, map_one] at h
  have hfst := congrArg Prod.fst h
  show W = 1
  rw [← mul_one W]
  exact hfst.symm

/-- The words on which the twisted action is left multiplication. -/
def GoodB : Subgroup (FreeGroup ℕ) where
  carrier := {W : FreeGroup ℕ | ∀ (w : FreeGroup ℕ) (α : A),
    act₂ g (bHom g W) (w, (0 : ℤ), α) = (W * w, 0, α)}
  one_mem' := by
    intro w α
    rw [map_one, map_one, one_mul]
    rfl
  mul_mem' := by
    intro u v hu hv w α
    rw [map_mul, map_mul]
    show act₂ g (bHom g u) (act₂ g (bHom g v) (w, (0 : ℤ), α)) = _
    rw [hv w α, hu (v * w) α]
    refine Prod.ext ?_ (Prod.ext rfl rfl)
    show u * (v * w) = u * v * w
    group
  inv_mem' := by
    intro u hu w α
    have hkey : act₂ g (bHom g u) (u⁻¹ * w, (0 : ℤ), α) = (w, 0, α) := by
      rw [hu (u⁻¹ * w) α]
      refine Prod.ext ?_ (Prod.ext rfl rfl)
      show u * (u⁻¹ * w) = w
      group
    rw [map_inv, map_inv]
    have hinv : (act₂ g (bHom g u))⁻¹ (w, (0 : ℤ), α) = (u⁻¹ * w, 0, α) :=
      by
        apply (act₂ g (bHom g u)).injective
        simpa using hkey.symm
    show (act₂ g (bHom g u))⁻¹ (w, (0 : ℤ), α) = _
    rw [hinv]

theorem goodB_eq_top : GoodB g = ⊤ := by
  refine top_le_iff.mp ?_
  intro W _hW
  refine FreeGroup.induction_on W ?_ ?_ ?_ ?_
  · exact Subgroup.one_mem _
  · intro i w α
    rw [bHom_of]
    exact act₂_bFam g i w α
  · intro i hmem
    exact Subgroup.inv_mem _ hmem
  · intro u v hu hv
    exact Subgroup.mul_mem _ hu hv

/-- **The twisted family is a free basis.** -/
theorem bHom_injective : Function.Injective (bHom g) := by
  classical
  rw [injective_iff_map_eq_one]
  intro W hW
  have hgood : W ∈ GoodB g := by
    rw [goodB_eq_top]
    exact Subgroup.mem_top W
  have h := hgood 1 1
  rw [hW, map_one] at h
  have hfst := congrArg Prod.fst h
  show W = 1
  rw [← mul_one W]
  exact hfst.symm

end HNNEmb
end Higman
end GroupApproximation

namespace GroupApproximation
namespace Higman
namespace HNNEmb

open scoped Monoid.Coprod

variable {A : Type} [Group A] (g : ℕ → A)

/-! ## 4.  The extension -/

/-- The subgroup generated by the untwisted family. -/
def Asub : Subgroup (P A) := (aHom (A := A)).range

/-- The subgroup generated by the twisted family. -/
def Bsub : Subgroup (P A) := (bHom g).range

theorem aFam_mem_Asub (i : ℕ) : aFam i ∈ (Asub (A := A)) :=
  ⟨FreeGroup.of i, aHom_of i⟩

theorem bFam_mem_Bsub (i : ℕ) : bFam g i ∈ Bsub g :=
  ⟨FreeGroup.of i, bHom_of g i⟩

/-- The untwisted family, as a basis of the subgroup it generates. -/
noncomputable def aEquiv : FreeGroup ℕ ≃* ↥(Asub (A := A)) :=
  MulEquiv.ofBijective (aHom (A := A)).rangeRestrict
    ⟨fun _ _ hxy => aHom_injective (congrArg Subtype.val hxy),
      (aHom (A := A)).rangeRestrict_surjective⟩

/-- The twisted family, likewise. -/
noncomputable def bEquiv : FreeGroup ℕ ≃* ↥(Bsub g) :=
  MulEquiv.ofBijective (bHom g).rangeRestrict
    ⟨fun _ _ hxy => bHom_injective g (congrArg Subtype.val hxy),
      (bHom g).rangeRestrict_surjective⟩

/-- The identification the stable letter realizes: `aᵢ ↦ bᵢ`. -/
noncomputable def psi : ↥(Asub (A := A)) ≃* ↥(Bsub g) :=
  (aEquiv (A := A)).symm.trans (bEquiv g)

theorem psi_aFam (i : ℕ) :
    ((psi g ⟨aFam i, aFam_mem_Asub i⟩ : ↥(Bsub g)) : P A) = bFam g i := by
  have ha : (aEquiv (A := A)) (FreeGroup.of i) = ⟨aFam i, aFam_mem_Asub i⟩ := by
    refine Subtype.ext ?_
    show (aHom (A := A)) (FreeGroup.of i) = aFam i
    rw [aHom_of]
  have hasymm : (aEquiv (A := A)).symm ⟨aFam i, aFam_mem_Asub i⟩ = FreeGroup.of i := by
    rw [MulEquiv.symm_apply_eq]
    exact ha.symm
  show (((bEquiv g) ((aEquiv (A := A)).symm ⟨aFam i, aFam_mem_Asub i⟩) : ↥(Bsub g)) : P A) = _
  rw [hasymm]
  show (bHom g) (FreeGroup.of i) = bFam g i
  rw [bHom_of]

/-- **The extension.** -/
abbrev Ext : Type := HNNExtension (P A) (Asub (A := A)) (Bsub g) (psi g)

/-- The countable group, inside the extension. -/
noncomputable def embA : A →* Ext g := (HNNExtension.of).comp (iA : A →* P A)

theorem embA_injective : Function.Injective (embA g) :=
  (HNNExtension.of_injective (φ := psi g)).comp iA_injective

/-- **The defining relation of the extension.** -/
theorem conj_aFam (i : ℕ) :
    (HNNExtension.t : Ext g) * HNNExtension.of (aFam i) *
        (HNNExtension.t : Ext g)⁻¹
      = HNNExtension.of (bFam g i) := by
  have h := HNNExtension.equiv_eq_conj (φ := psi g) ⟨aFam i, aFam_mem_Asub i⟩
  rw [psi_aFam] at h
  exact h.symm

/-! ## 5.  Generation -/

/-- The free product is generated by its two factors. -/
theorem coprod_closure_top :
    Subgroup.closure ((Set.range (iA : A →* P A)) ∪
      (Set.range (iF : FreeGroup (Fin 2) →* P A))) = ⊤ := by
  set T := Subgroup.closure ((Set.range (iA : A →* P A)) ∪
    (Set.range (iF : FreeGroup (Fin 2) →* P A))) with hT
  have hAmem : ∀ α : A, (iA α : P A) ∈ T := fun α =>
    Subgroup.subset_closure (Or.inl ⟨α, rfl⟩)
  have hFmem : ∀ v : FreeGroup (Fin 2), (iF v : P A) ∈ T := fun v =>
    Subgroup.subset_closure (Or.inr ⟨v, rfl⟩)
  set fA : A →* ↥T := (iA : A →* P A).codRestrict T hAmem with hfA
  set fF : FreeGroup (Fin 2) →* ↥T := (iF : FreeGroup (Fin 2) →* P A).codRestrict T hFmem
    with hfF
  set φ : P A →* ↥T := Monoid.Coprod.lift fA fF with hφ
  have hsplit : T.subtype.comp φ = MonoidHom.id (P A) := by
    refine Monoid.Coprod.hom_ext ?_ ?_
    · refine MonoidHom.ext fun α => ?_
      show ((φ (iA α) : ↥T) : P A) = iA α
      rw [hφ]
      show ((Monoid.Coprod.lift fA fF) (Monoid.Coprod.inl α) : ↥T).1 = _
      rw [Monoid.Coprod.lift_apply_inl]
      rfl
    · refine MonoidHom.ext fun v => ?_
      show ((φ (iF v) : ↥T) : P A) = iF v
      rw [hφ]
      show ((Monoid.Coprod.lift fA fF) (Monoid.Coprod.inr v) : ↥T).1 = _
      rw [Monoid.Coprod.lift_apply_inr]
      rfl
  refine top_le_iff.mp ?_
  intro p _hp
  have hp := congrArg (fun f : P A →* P A => f p) hsplit
  change ((φ p : ↥T) : P A) = p at hp
  show p ∈ T
  rw [← hp]
  exact (φ p).2

/-- The three generators. -/
def gens : Set (Ext g) :=
  {HNNExtension.of (xg : P A), HNNExtension.of (yg : P A), (HNNExtension.t : Ext g)}

theorem gens_finite : (gens g).Finite :=
  ((Set.finite_singleton _).insert _).insert _

theorem of_iF_mem (v : FreeGroup (Fin 2)) :
    HNNExtension.of (iF v : P A) ∈ Subgroup.closure (gens g) := by
  refine FreeGroup.induction_on v ?_ ?_ ?_ ?_
  · rw [map_one, map_one]
    exact Subgroup.one_mem _
  · intro i
    fin_cases i
    · exact Subgroup.subset_closure (Set.mem_insert _ _)
    · exact Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_insert _ _))
  · intro i hmem
    rw [map_inv, map_inv]
    exact Subgroup.inv_mem _ hmem
  · intro u w hu hw
    rw [map_mul, map_mul]
    exact Subgroup.mul_mem _ hu hw

theorem of_aFam_mem (i : ℕ) :
    HNNExtension.of (aFam i : P A) ∈ Subgroup.closure (gens g) := by
  unfold aFam
  rw [map_mul, map_mul, map_zpow, map_zpow]
  have hx : HNNExtension.of (xg : P A) ∈ Subgroup.closure (gens g) :=
    Subgroup.subset_closure (Set.mem_insert _ _)
  have hy : HNNExtension.of (yg : P A) ∈ Subgroup.closure (gens g) :=
    Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_insert _ _))
  exact Subgroup.mul_mem _
    (Subgroup.mul_mem _ (Subgroup.zpow_mem _ hx _) hy)
    (Subgroup.zpow_mem _ hx _)

theorem of_iA_mem (hg : Function.Surjective g) (α : A) :
    HNNExtension.of (iA α : P A) ∈ Subgroup.closure (gens g) := by
  obtain ⟨i, rfl⟩ := hg α
  have hsplit : (iA (g i) : P A) = bFam g i * (aFam i)⁻¹ := by
    unfold bFam
    group
  rw [hsplit, map_mul, map_inv, ← conj_aFam g i]
  have ht : (HNNExtension.t : Ext g) ∈ Subgroup.closure (gens g) :=
    Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _ rfl))
  refine Subgroup.mul_mem _ ?_ (Subgroup.inv_mem _ (of_aFam_mem g i))
  exact Subgroup.mul_mem _ (Subgroup.mul_mem _ ht (of_aFam_mem g i))
    (Subgroup.inv_mem _ ht)

theorem closure_gens_eq_top (hg : Function.Surjective g) :
    Subgroup.closure (gens g) = ⊤ := by
  refine top_le_iff.mp ?_
  intro z _hz
  clear _hz
  induction z using HNNExtension.induction_on with
  | of p =>
      have hmem : p ∈ Subgroup.closure ((Set.range (iA : A →* P A)) ∪
          (Set.range (iF : FreeGroup (Fin 2) →* P A))) := by
        rw [coprod_closure_top]
        exact Subgroup.mem_top p
      refine Subgroup.closure_induction
        (p := fun q _ => HNNExtension.of (q : P A) ∈ Subgroup.closure (gens g))
        ?_ ?_ ?_ ?_ hmem
      · rintro _ (⟨α, rfl⟩ | ⟨v, rfl⟩)
        · exact of_iA_mem g hg α
        · exact of_iF_mem g v
      · rw [map_one]
        exact Subgroup.one_mem _
      · intro u v _ _ hu hv
        rw [map_mul]
        exact Subgroup.mul_mem _ hu hv
      · intro u _ hu
        rw [map_inv]
        exact Subgroup.inv_mem _ hu
  | t =>
      exact Subgroup.subset_closure
        (Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _ rfl))
  | mul u v hu hv => exact Subgroup.mul_mem _ hu hv
  | inv u hu => exact Subgroup.inv_mem _ hu

theorem fg_ext (hg : Function.Surjective g) : Group.FG (Ext g) :=
  Group.fg_iff.mpr ⟨gens g, closure_gens_eq_top g hg, gens_finite g⟩

/-! ## 6.  The theorem -/

/-- A finitely generated overgroup. -/
structure FGOvergroup (A : Type) [Group A] where
  /-- The overgroup. -/
  Carrier : Type
  /-- Its group structure. -/
  [group : Group Carrier]
  /-- It is finitely generated. -/
  fg : Group.FG Carrier
  /-- The embedding. -/
  emb : A →* Carrier
  /-- ... which is one. -/
  emb_injective : Function.Injective emb

attribute [instance] FGOvergroup.group

/-- **Higman--Neumann--Neumann: every countable group embeds in a
three-generator group.** -/
theorem nonempty_fgOvergroup (A : Type) [Group A] [Countable A] [Nonempty A] :
    Nonempty (FGOvergroup A) := by
  obtain ⟨g, hg⟩ := exists_surjective_nat A
  exact ⟨{ Carrier := Ext g
           fg := fg_ext g hg
           emb := embA g
           emb_injective := embA_injective g }⟩

end HNNEmb
end Higman
end GroupApproximation
