import GroupApproximation.Higman.HNNCentralizer
import GroupApproximation.Higman.OmegaTower

/-!
# Stage one of the `ωₘ` tower

`Higman.OmegaTower` states what the tower of Mikaelian's §4 has to supply
(`Omega.Tower`) and proves everything that follows from it on the sequence
side.  This file builds and discharges the tower's **first stage**, and it is
the stage that needs no Britton argument at all.

The stage is

    Σ = K ∗_P (g, h, k) ,

three new generators, each **centralizing** the same subgroup `P` of the base.
That reading of Mikaelian's `∗_P` is his §2.4 notation for a multiple HNN
extension --- it is not an amalgamated product, and the correction matters:
every stage of the `ωₘ` tower is an HNN extension, so `Higman.CentHNN` covers
this one verbatim and no pushout machinery is needed on this lane.

## What is built

`Cent3 P` is `CentHNN` iterated three times, each time over the image of `P`
under the previous `of`.  Then:

* `emb3_injective` --- the base embeds, three applications of
  `Higman.of_injective_centHNN`;
* `isFinitelyPresented_cent3`, `isPowerTorsionFree_cent3` --- the two
  permanence properties the benignness obligation needs, from
  `Higman.isFinitelyPresented_centHNN` and
  `HNNBritton.isPowerTorsionFree_hnn`;
* `gen1, gen2, gen3` --- the three stable letters `g, h, k`, in the top group;
* `genHom` --- the second copy of Higman's coding, `a, b, c ↦ g, h, k`, so
  that `gen β := genHom (aElt β)` is Mikaelian's `g_β` **by definition**, with
  no freeness of `⟨g, h, k⟩` needed to write it down;
* `commute_genHom` --- **the `Omega.Tower.commute_row` relation.**  Every word
  in `g, h, k` commutes with the image of every element of `P`.  With
  `P` cutting out `B₀ₘ = ⟨bᵢ : i ∉ [0, m)⟩` this is exactly "each of `g, h, k`
  commutes with each `bᵢ` for `i < 0` or `i ≥ m`", which is the fact the
  peeling step of `Omega.emb_aElt_eq_conj` runs on.

## What is deliberately not here

`isFinitelyPresented_cent3` asks for `P.FG`, and the *slim* tower --- the one
built over `⟨b, c⟩` itself, with `P = rowOut m` --- **does not** satisfy it:
the rows are a free basis (`Row.basisHom_injective`), so `rowOut m` is free of
infinite rank.  That is not a defect of this file; it is why Mikaelian's tower
is built over a benign witness `K` with a *finitely generated* `P` cutting out
`B₀ₘ`, and why the slim tower is a normal-form vehicle only.  Both towers are
instances of the constructions below --- the slim one with `P = rowOut m` and
`ι = MonoidHom.id`, the fat one with `P` finitely generated --- which is the
point of stating them over an arbitrary base pair.

Stages two and three, and the two obligations of `Omega.TowerClosure`, are in
`notes/W6_OMEGA_TOWER_STAGE2_2026-08-22.md`.
-/

namespace GroupApproximation
namespace Higman
namespace Omega

open GroupApproximation.Higman.Conj
open GroupApproximation.Higman.Seq
open HNNExtension

/-! ## 0.  Two elementary transfers

Both say the same thing about a relation of the form `u⁻¹ x u = x`: it *is*
commuting, and it survives a homomorphism.  Every centralizing stage of the
tower is read through these two. -/

theorem commute_of_conj_eq {G : Type*} [Group G] {u x : G}
    (h : u⁻¹ * x * u = x) : Commute u x := by
  show u * x = x * u
  calc u * x = u * (u⁻¹ * x * u) := by rw [h]
    _ = x * u := by group

theorem map_conj_eq_self {G H : Type} [Group G] [Group H] (f : G →* H) {u x : G}
    (h : u⁻¹ * x * u = x) : (f u)⁻¹ * f x * f u = f x := by
  have h' : f (u⁻¹ * x * u) = f x := by rw [h]
  rwa [map_mul, map_mul, map_inv] at h'

/-! ## 1.  The rows outside the window

`B₀ₘ` of the source: the rows `bᵢ` with `i < 0` or `i ≥ m`, inside the
rank-two free group `Row.F₀ = ⟨b, c⟩`.  The window `[0, m)` is the one
`Omega.blockSet` is supported on, so the two definitions are complementary by
construction. -/

/-- The subgroup generated by the rows outside the window `[0, m)`. -/
def rowOut (m : ℕ) : Subgroup Row.F₀ :=
  Subgroup.closure (Row.row '' {i : ℤ | i ∉ Finset.Ico (0 : ℤ) (m : ℤ)})

theorem row_mem_rowOut {m : ℕ} {i : ℤ} (hi : i ∉ Finset.Ico (0 : ℤ) (m : ℤ)) :
    Row.row i ∈ rowOut m :=
  Subgroup.subset_closure ⟨i, hi, rfl⟩

/-- The bridge to the `F₃` side: the retraction killing `a` carries the row
`rowElt i` of `F₃` to the row `Row.row i` of `⟨b, c⟩`, so the rows of `F₃`
outside the window land in `rowOut m`. -/
theorem retract_rowElt_mem_rowOut {m : ℕ} {i : ℤ}
    (hi : i ∉ Finset.Ico (0 : ℤ) (m : ℤ)) : retract (rowElt i) ∈ rowOut m := by
  rw [retract_rowElt]
  exact row_mem_rowOut hi

/-! ## 2.  Three stable letters over one centralized subgroup

`Higman.CentHNN L` adjoins one stable letter centralizing `L`.  Doing it three
times, each time over the image of the previous centralized subgroup, is
`Σ = K ∗_P (g, h, k)`. -/

variable {G₀ : Type} [Group G₀]

/-- The first of the three centralizing extensions. -/
abbrev Cent1 (P : Subgroup G₀) : Type := CentHNN P

/-- The base embedded in the first extension. -/
def emb1 (P : Subgroup G₀) : G₀ →* Cent1 P := of

/-- The centralized subgroup, pushed into the first extension. -/
def push1 (P : Subgroup G₀) : Subgroup (Cent1 P) := P.map (emb1 P)

/-- The second of the three centralizing extensions. -/
abbrev Cent2 (P : Subgroup G₀) : Type := CentHNN (push1 P)

/-- The base embedded in the second extension. -/
def emb2 (P : Subgroup G₀) : G₀ →* Cent2 P :=
  (of : Cent1 P →* Cent2 P).comp (emb1 P)

/-- The centralized subgroup, pushed into the second extension. -/
def push2 (P : Subgroup G₀) : Subgroup (Cent2 P) :=
  (push1 P).map (of : Cent1 P →* Cent2 P)

/-- **Mikaelian's `Σ`**, the third and last centralizing extension. -/
abbrev Cent3 (P : Subgroup G₀) : Type := CentHNN (push2 P)

/-- **The base embedded in `Σ`.** -/
def emb3 (P : Subgroup G₀) : G₀ →* Cent3 P :=
  (of : Cent2 P →* Cent3 P).comp (emb2 P)

theorem mem_push1 {P : Subgroup G₀} {x : G₀} (hx : x ∈ P) : emb1 P x ∈ push1 P :=
  ⟨x, hx, rfl⟩

theorem mem_push2 {P : Subgroup G₀} {x : G₀} (hx : x ∈ P) : emb2 P x ∈ push2 P :=
  ⟨emb1 P x, mem_push1 hx, rfl⟩

/-! ### The three permanence properties -/

/-- **The base embeds in `Σ`.**  Three applications of Britton at the level of
the individual stages; nothing about the three letters jointly is claimed. -/
theorem emb3_injective (P : Subgroup G₀) : Function.Injective (emb3 P) := by
  have h1 : Function.Injective (emb1 P) := of_injective_centHNN P
  have h2 : Function.Injective (emb2 P) :=
    (of_injective_centHNN (push1 P)).comp h1
  exact (of_injective_centHNN (push2 P)).comp h2

theorem push1_fg {P : Subgroup G₀} (hP : P.FG) : (push1 P).FG :=
  fg_map hP (emb1 P)

theorem push2_fg {P : Subgroup G₀} (hP : P.FG) : (push2 P).FG :=
  fg_map (push1_fg hP) (of : Cent1 P →* Cent2 P)

/-- **`Σ` is finitely presented** when the base is and the centralized
subgroup is finitely generated.

The hypothesis `P.FG` is the whole reason Mikaelian's first stage is built
over a benign witness `K` rather than over `⟨b, c⟩`: the subgroup that has to
be centralized is `B₀ₘ`, which is free of infinite rank. -/
theorem isFinitelyPresented_cent3 [Group.IsFinitelyPresented G₀] {P : Subgroup G₀}
    (hP : P.FG) : Group.IsFinitelyPresented (Cent3 P) := by
  letI : Group.IsFinitelyPresented (Cent1 P) := isFinitelyPresented_centHNN P hP
  letI : Group.IsFinitelyPresented (Cent2 P) :=
    isFinitelyPresented_centHNN (push1 P) (push1_fg hP)
  exact isFinitelyPresented_centHNN (push2 P) (push2_fg hP)

/-- **`Σ` is torsion-free** when the base is.  Unconditional: the HNN torsion
theorem needs nothing about the associated subgroups. -/
theorem isPowerTorsionFree_cent3 {P : Subgroup G₀} (hG : IsPowerTorsionFree G₀) :
    IsPowerTorsionFree (Cent3 P) :=
  HNNBritton.isPowerTorsionFree_hnn (MulEquiv.refl (push2 P))
    (HNNBritton.isPowerTorsionFree_hnn (MulEquiv.refl (push1 P))
      (HNNBritton.isPowerTorsionFree_hnn (MulEquiv.refl P) hG))

/-! ## 3.  The three letters, and that they centralize the base subgroup -/

/-- Mikaelian's `g`: the stable letter of the first extension, seen in `Σ`. -/
def gen1 (P : Subgroup G₀) : Cent3 P :=
  (of : Cent2 P →* Cent3 P) ((of : Cent1 P →* Cent2 P) (t : Cent1 P))

/-- Mikaelian's `h`: the stable letter of the second extension, seen in `Σ`. -/
def gen2 (P : Subgroup G₀) : Cent3 P := (of : Cent2 P →* Cent3 P) (t : Cent2 P)

/-- Mikaelian's `k`: the stable letter of the third extension. -/
def gen3 (P : Subgroup G₀) : Cent3 P := (t : Cent3 P)

theorem commute_gen1 {P : Subgroup G₀} {x : G₀} (hx : x ∈ P) :
    Commute (gen1 P) (emb3 P x) :=
  commute_of_conj_eq
    (map_conj_eq_self (of : Cent2 P →* Cent3 P)
      (map_conj_eq_self (of : Cent1 P →* Cent2 P) (conj_eq_self_of_mem P hx)))

theorem commute_gen2 {P : Subgroup G₀} {x : G₀} (hx : x ∈ P) :
    Commute (gen2 P) (emb3 P x) :=
  commute_of_conj_eq
    (map_conj_eq_self (of : Cent2 P →* Cent3 P)
      (conj_eq_self_of_mem (push1 P) (mem_push1 hx)))

theorem commute_gen3 {P : Subgroup G₀} {x : G₀} (hx : x ∈ P) :
    Commute (gen3 P) (emb3 P x) :=
  commute_of_conj_eq (conj_eq_self_of_mem (push2 P) (mem_push2 hx))

/-! ## 4.  The second copy of the coding

`genHom` sends `a, b, c` to `g, h, k`, so `genHom (rowElt i)` is Mikaelian's
`hᵢ = h^{kⁱ}`, `genHom (bElt β)` is his `h_β`, and `genHom (aElt β)` is his
`g_β = g^{h_β}`.  Defining `g_β` this way costs nothing --- no freeness of
`⟨g, h, k⟩` is needed to *write* it, and freeness is not what the closure
computation uses. -/

/-- The second copy of Higman's coding: `a, b, c ↦ g, h, k`. -/
def genHom (P : Subgroup G₀) : F₃ →* Cent3 P :=
  FreeGroup.lift (fun i : Fin 3 =>
    if i = 0 then gen1 P else if i = 1 then gen2 P else gen3 P)

@[simp] theorem genHom_a (P : Subgroup G₀) : genHom P a = gen1 P := by
  unfold genHom a
  rw [FreeGroup.lift_apply_of]
  simp

@[simp] theorem genHom_b (P : Subgroup G₀) : genHom P b = gen2 P := by
  unfold genHom b
  rw [FreeGroup.lift_apply_of]
  simp

@[simp] theorem genHom_c (P : Subgroup G₀) : genHom P c = gen3 P := by
  unfold genHom c
  rw [FreeGroup.lift_apply_of]
  simp

/-- **`Omega.Tower.commute_row`, in the form this stage proves it.**  Every
word in `g, h, k` commutes with the image of every element of the centralized
subgroup.

Only the three generator-level facts of §3 are used, propagated over words by
the free group's induction principle. -/
theorem commute_genHom {P : Subgroup G₀} (y : F₃) {x : G₀} (hx : x ∈ P) :
    Commute (genHom P y) (emb3 P x) := by
  refine FreeGroup.induction_on y ?_ ?_ ?_ ?_
  · rw [map_one]
    exact Commute.one_left _
  · intro i
    fin_cases i
    · show Commute (genHom P a) (emb3 P x)
      rw [genHom_a]
      exact commute_gen1 hx
    · show Commute (genHom P b) (emb3 P x)
      rw [genHom_b]
      exact commute_gen2 hx
    · show Commute (genHom P c) (emb3 P x)
      rw [genHom_c]
      exact commute_gen3 hx
  · intro i hi
    rw [map_inv]
    exact hi.inv_left
  · intro u v hu hv
    rw [map_mul]
    exact hu.mul_left hv

/-- **The specialization the tower consumes.**  When the centralized subgroup
cuts out the rows outside the window --- which is the defining property of
Mikaelian's `P`, `⟨b,c⟩ ∩ P = B₀ₘ` --- every `g_β` commutes with every row
outside the window.

For the slim tower take `ι = MonoidHom.id` and `P = rowOut m`, when the
hypothesis is `row_mem_rowOut`. -/
theorem commute_genHom_row {m : ℕ} {P : Subgroup G₀} (ι : Row.F₀ →* G₀)
    (hι : ∀ i : ℤ, i ∉ Finset.Ico (0 : ℤ) (m : ℤ) → ι (Row.row i) ∈ P)
    (y : F₃) {i : ℤ} (hi : i ∉ Finset.Ico (0 : ℤ) (m : ℤ)) :
    Commute (genHom P y) (emb3 P (ι (Row.row i))) :=
  commute_genHom y (hι i hi)

/-- The same for the slim tower, where the base *is* `⟨b, c⟩`. -/
theorem commute_genHom_row_slim {m : ℕ} (y : F₃) {i : ℤ}
    (hi : i ∉ Finset.Ico (0 : ℤ) (m : ℤ)) :
    Commute (genHom (rowOut m) y) (emb3 (rowOut m) (Row.row i)) :=
  commute_genHom y (row_mem_rowOut hi)

end Omega
end Higman
end GroupApproximation
