import GroupApproximation.Higman.OmegaTowerStaticSeamCoordinates

/-!
# Free-coordinate form of the desired Omega range

The second central HNN stage has an injective free-label lift.  This file
identifies the desired embedded `A_(omegaOp m B)` exactly as the lift of a
concrete free-coordinate subgroup, rather than merely showing that it lies in
the retraction kernel.  This is the coordinate target for the matched-link
correlation in the static seam.
-/

namespace GroupApproximation
namespace Higman
namespace Omega

open GroupApproximation.Higman.Conj
open GroupApproximation.Higman.Seq

/-- The literal conjugate-basis coordinate subgroup for `omegaOp m B`. -/
noncomputable def omegaDirectCoordSub (m : ℕ) (B : Set E) :
    Subgroup (FreeGroup ↥Conj.K) :=
  Subgroup.closure (FreeGroup.of '' (Seq.bK '' omegaOp m B))

/-- The literal coset-label index of a conjugating word in `K`. -/
noncomputable def slimLabelIndex (m : ℕ) (q : ↥Conj.K) :
    CentralHNNFreeLabel.Label (slimLink m) (slimTransversal m) :=
  (((slimTransversal m).compl (1 : ℤˣ)).equiv (slimKBase m q)).2

@[simp] theorem slimLabelHom_of (m : ℕ) (q : ↥Conj.K) :
    slimLabelHom m (FreeGroup.of q) = FreeGroup.of (slimLabelIndex m q) := by
  simp [slimLabelHom, slimLabelIndex]

/-- The target label subgroup is generated by the literal labels of the
canonical sequence words in `omegaOp m B`. -/
theorem omegaLabelSub_eq_closure_labels (m : ℕ) (B : Set E) :
    omegaLabelSub m B = Subgroup.closure
      (FreeGroup.of '' (slimLabelIndex m '' (Seq.bK '' omegaOp m B))) := by
  rfl

/-- Exact support reflection for the matched labels of the inner stage.  This
removes the earlier local-subgroup overapproximation: membership in the label
subgroup is equivalent to support on the literal matched `K` indices. -/
theorem slimLabelHom_mem_labelSub_iff (m : ℕ) (B : Set E)
    (w : FreeGroup ↥Conj.K) :
    slimLabelHom m w ∈
        CentralHNNFreeLabel.labelSub (slimLink m) (slimTransversal m)
          (slimGenSub m B) ↔
      w ∈ Subgroup.closure (FreeGroup.of '' slimMatchedK m B) := by
  constructor
  · intro hw
    apply CentralHNNFreeLabel.Coordinate.mem_closure_preimage_of_map_mem
      (slimLabelIndex_injective m)
      (CentralHNNFreeLabel.labelSet (slimLink m) (slimTransversal m)
        (slimGenSub m B))
    exact hw
  · intro hw
    induction hw using Subgroup.closure_induction with
    | mem x hx =>
        obtain ⟨q, hq, rfl⟩ := hx
        rw [slimLabelHom_of]
        apply Subgroup.subset_closure
        exact ⟨slimLabelIndex m q, hq, rfl⟩
    | one => rw [map_one]; exact Subgroup.one_mem _
    | mul x y _ _ hx hy => rw [map_mul]; exact Subgroup.mul_mem _ hx hy
    | inv x _ hx => rw [map_inv]; exact Subgroup.inv_mem _ hx

/-- Direct coordinate test for membership in the desired embedded range. -/
theorem slimPiF3Hom_cbHom_mem_omegaRangeSub_iff (m : ℕ) (B : Set E)
    (w : FreeGroup ↥Conj.K) :
    slimPiF3Hom m (Conj.cbHom w) ∈ omegaRangeSub m B ↔
      w ∈ omegaDirectCoordSub m B := by
  unfold omegaRangeSub
  constructor
  · rintro ⟨x, hx, hxw⟩
    rw [ASub_eq_map] at hx
    obtain ⟨v, hv, hvx⟩ := hx
    have hxc : x = Conj.cbHom w :=
      slimPiF3Hom_injective m hxw
    have hvw : v = w :=
      Conj.cbHom_injective (hvx.trans hxc)
    rwa [hvw] at hv
  · intro hw
    refine ⟨Conj.cbHom w, ?_, rfl⟩
    rw [ASub_eq_map]
    exact ⟨w, hw, rfl⟩

/-- **Exact matched-coordinate characterization of the inner survivor.**
This is the sharp replacement for the earlier local-coordinate
overapproximation. -/
theorem slimPiF3Hom_cbHom_mem_slimWBase_iff (m : ℕ) (B : Set E)
    (w : FreeGroup ↥Conj.K) :
    slimPiF3Hom m (Conj.cbHom w) ∈ slimWBase m B ↔
      w ∈ Subgroup.closure (FreeGroup.of '' slimMatchedK m B) := by
  constructor
  · intro hw
    apply (slimLabelHom_mem_labelSub_iff m B w).mp
    exact slimLabelHom_mem_of_cbHom_survives hw
  · intro hw
    have hlabel := (slimLabelHom_mem_labelSub_iff m B w).mpr hw
    have hlift :
        CentralHNNFreeLabel.stableConjLift
            (slimLink m) (slimTransversal m) (slimLabelHom m w) ∈
          (CentralHNNFreeLabel.labelSub
              (slimLink m) (slimTransversal m) (slimGenSub m B)).map
            (CentralHNNFreeLabel.stableConjLift
              (slimLink m) (slimTransversal m)) :=
      ⟨slimLabelHom m w, hlabel, rfl⟩
    rw [← slimWBase_inf_baseRet_ker] at hlift
    have heq := DFunLike.congr_fun
      (slimPiF3Hom_comp_cbHom_eq_freeLabel m) w
    change (((slimPiF3Hom m).comp Conj.cbHom) w) ∈ slimWBase m B
    rw [heq]
    exact hlift.1

/-- The row-base copy of a literal block is the `K`-copy of its canonical
sequence word. -/
theorem slimKBase_bK (m : ℕ) (f : E) :
    slimKBase m (Seq.bK f) = slimBaseCode m f := by
  unfold slimKBase slimBaseCode Seq.bK Seq.bElt
  change emb3 (rowOut m) (Seq.retract (Seq.rowHom (Seq.elt f))) =
    emb3 (rowOut m) (Row.basisHom (Seq.elt f))
  have h := DFunLike.congr_fun Seq.retract_comp_rowHom (Seq.elt f)
  exact congrArg (emb3 (rowOut m)) h

theorem slimKBase_injective (m : ℕ) : Function.Injective (slimKBase m) := by
  intro q r hqr
  have hret : Seq.retract (q : F₃) = Seq.retract (r : F₃) :=
    emb3_injective (rowOut m) hqr
  apply Subtype.ext
  rw [← rowIntoF3_retract_coe_K q, ← rowIntoF3_retract_coe_K r, hret]

/-- A selected code generator can meet the row-label range only at its own
canonical block index.  This is the one-letter reverse correlation. -/
theorem eq_bK_of_slimGenCode_label_eq {m : ℕ} {f : E}
    (hf : f ∈ blockSet m) (q : ↥Conj.K)
    (hlabel :
      (((slimTransversal m).compl (1 : ℤˣ)).equiv (slimGenCode m f)).2 =
        slimLabelIndex m q) :
    q = Seq.bK f := by
  have hlink : slimGenCode m f * (slimKBase m q)⁻¹ ∈ slimLink m := by
    apply (FiniteHNNFreeLabelAction.source_transversal_eq_iff
      (A := slimLink m) (B := slimLink m) (slimTransversal m)
      (slimGenCode m f * (slimKBase m q)⁻¹) (slimKBase m q)).1
    simpa [slimLabelIndex, mul_assoc] using hlabel
  have hcanonical : slimLinkElem m f ∈ slimLink m :=
    slimLinkElem_mem hf
  have hproj :
      genProjection3 m (slimGenCode m f * (slimKBase m q)⁻¹) =
        genProjection3 m (slimLinkElem m f) := by
    simp only [slimLinkElem, map_mul, map_inv, genProjection3_slimGenCode,
      slimKBase, slimBaseCode, MonoidHom.comp_apply,
      genProjection3_emb3, inv_one, mul_one]
  have heq : slimGenCode m f * (slimKBase m q)⁻¹ = slimLinkElem m f :=
    genProjection3_injOn_slimLink m hlink hcanonical hproj
  have hinv : (slimKBase m q)⁻¹ = (slimBaseCode m f)⁻¹ := by
    apply mul_left_cancel (a := slimGenCode m f)
    simpa [slimLinkElem] using heq
  apply slimKBase_injective m
  rw [slimKBase_bK]
  exact inv_injective hinv

@[simp] theorem slimBaseCode_zero (m : ℕ) :
    slimBaseCode m (0 : E) = 1 := by
  simp [slimBaseCode]

/-- The zero-block code lies in the link subgroup, so it is invisible to the
right-coset label during the reverse spelling induction. -/
theorem slimGenCode_zero_mem_slimLink (m : ℕ) :
    slimGenCode m (0 : E) ∈ slimLink m := by
  have hzero : (0 : E) ∈ blockSet m := by
    intro i hi
    rfl
  have hlink := slimLinkElem_mem hzero
  simpa [slimLinkElem] using hlink

/-- Every selected positive window block gives a literal matched row label.
This is the generator-level sign/order check for the correlation theorem. -/
theorem bK_mem_slimMatchedK {m : ℕ} {B : Set E} {f : E}
    (hf : f ∈ B ∩ blockSet m) : Seq.bK f ∈ slimMatchedK m B := by
  change slimLabelIndex m (Seq.bK f) ∈
    CentralHNNFreeLabel.labelSet (slimLink m) (slimTransversal m)
      (slimGenSub m B)
  refine ⟨slimGenCode m f, ?_, ?_⟩
  · exact Subgroup.subset_closure ⟨f, hf, rfl⟩
  · have hlink : slimLinkElem m f ∈ slimLink m :=
      slimLinkElem_mem hf.2
    have hlabel :=
      (FiniteHNNFreeLabelAction.source_transversal_eq_iff
        (A := slimLink m) (B := slimLink m) (slimTransversal m)
        (slimGenCode m f * (slimBaseCode m f)⁻¹)
        (slimBaseCode m f)).2 hlink
    simpa [slimLabelIndex, slimLinkElem, slimKBase_bK, mul_assoc] using hlabel

/-- The direct coordinate subgroup on the selected zeroth-window alphabet is
contained in the exact matched-coordinate subgroup. -/
theorem selectedDirectCoord_le_matchedCoord (m : ℕ) (B : Set E) :
    Subgroup.closure
        (FreeGroup.of '' (Seq.bK '' (B ∩ blockSet m))) ≤
      Subgroup.closure (FreeGroup.of '' slimMatchedK m B) := by
  apply Subgroup.closure_mono
  rintro _ ⟨_, ⟨f, hf, rfl⟩, rfl⟩
  exact ⟨Seq.bK f, bK_mem_slimMatchedK hf, rfl⟩

/-- A matched index has an exact selected-block spelling whose interleaved
link word factors as the selected `g`-word followed by the inverse row index.
This retains the noncommutative ordering information that the coarse
`localKSub` bound discards. -/
theorem exists_selected_link_spelling_of_mem_slimMatchedK
    {m : ℕ} {B : Set E} {q : ↥Conj.K} (hq : q ∈ slimMatchedK m B) :
    ∃ (s : Cent3 (rowOut m)) (u : FreeGroup ↥(blockSet m)),
      s ∈ slimGenSub m B ∧
      u ∈ Subgroup.closure (FreeGroup.of '' selectedBlocks m B) ∧
      slimLinkLift m u = s * (slimKBase m q)⁻¹ ∧
      blockKInvHom m u = q⁻¹ := by
  obtain ⟨s, u, hs, hu, hAu, hrow⟩ :=
    exists_link_word_of_mem_slimMatchedK hq
  have hselected :
      u ∈ Subgroup.closure (FreeGroup.of '' selectedBlocks m B) :=
    mem_closure_selectedBlocks_of_blockAHom_mem hAu
  have hqword : blockKInvHom m u = q⁻¹ := by
    apply Subtype.ext
    have hmap := congrArg rowIntoF3 hrow
    rw [← MonoidHom.comp_apply, ← Ksubtype_comp_blockKInvHom m,
      MonoidHom.comp_apply] at hmap
    simpa [map_inv, rowIntoF3_retract_coe_K] using hmap
  exact ⟨s, u, hs, hselected, hu, hqword⟩

/-- A single conjugate-basis letter survives the inner stage exactly when its
index is a literal matched row label. -/
theorem slimPiF3Hom_cbHom_of_mem_slimWBase_iff
    (m : ℕ) (B : Set E) (q : ↥Conj.K) :
    slimPiF3Hom m (Conj.cbHom (FreeGroup.of q)) ∈ slimWBase m B ↔
      q ∈ slimMatchedK m B := by
  rw [slimPiF3Hom_cbHom_mem_slimWBase_iff]
  constructor
  · exact CentralHNNFreeLabel.Coordinate.index_mem_of_of_mem_closure
  · intro hq
    exact Subgroup.subset_closure ⟨q, hq, rfl⟩

/-- Injectivity of the free-label lift reflects membership in the desired
Omega range back to the exact coordinate subgroup. -/
theorem stableConjLift_mem_omegaRangeSub_iff (m : ℕ) (B : Set E)
    (w : FreeGroup (CentralHNNFreeLabel.Label
      (slimLink m) (slimTransversal m))) :
    CentralHNNFreeLabel.stableConjLift
        (slimLink m) (slimTransversal m) w ∈ omegaRangeSub m B ↔
      w ∈ omegaLabelSub m B := by
  rw [omegaRangeSub_eq_map_omegaLabelSub]
  constructor
  · rintro ⟨v, hv, hvw⟩
    have : v = w := CentralHNNFreeLabel.stableConjLift_injective
      (slimLink m) (slimTransversal m) hvw
    rwa [this] at hv
  · intro hw
    exact ⟨w, hw, rfl⟩

end Omega
end Higman
end GroupApproximation
