import GroupApproximation.Higman.OmegaTowerConjugateBasisCoordinates

/-!
# The global conjugate-basis invariant for the outer Omega scan

The inner classifier produces a word supported on one window.  During the
outer scan, signed pinches move those coordinates by whole blocks.  The
subgroups below collect all coordinates indexed by `omegaOp m B`, and the
main lemmas prove that both signed coordinate maps preserve them.
-/

namespace GroupApproximation
namespace Higman
namespace Omega

open Conj Seq

/-- The conjugating subgroup generated by every sequence in `omegaOp m B`. -/
noncomputable def omegaKSub (m : ℕ) (B : Set E) : Subgroup ↥K :=
  Subgroup.closure (bK '' omegaOp m B)

/-- The corresponding coordinate subgroup of the free conjugate-basis group. -/
noncomputable def omegaCoordSub (m : ℕ) (B : Set E) :
    Subgroup (FreeGroup ↥K) :=
  Subgroup.closure (FreeGroup.of '' (omegaKSub m B : Set ↥K))

theorem mem_omegaOp_unshift {m : ℕ} {B : Set E} {f : E}
    (hf : f ∈ omegaOp m B) : unshift m f ∈ omegaOp m B := by
  apply (mem_omegaOp_shiftPow m B (unshift m f)).mp
  rwa [shiftPow_unshift]

/-- Positive block shift preserves the global index subgroup. -/
theorem shiftKPowHom_mem_omegaKSub {m : ℕ} {B : Set E} {q : ↥K}
    (hq : q ∈ omegaKSub m B) : shiftKPowHom m q ∈ omegaKSub m B := by
  induction hq using Subgroup.closure_induction with
  | mem q hq =>
      obtain ⟨f, hf, rfl⟩ := hq
      rw [shiftKPowHom_bK]
      exact Subgroup.subset_closure
        ⟨shiftPow m f, (mem_omegaOp_shiftPow m B f).mpr hf, rfl⟩
  | one => rw [map_one]; exact Subgroup.one_mem _
  | mul x y _ _ hx hy => rw [map_mul]; exact Subgroup.mul_mem _ hx hy
  | inv x _ hx => rw [map_inv]; exact Subgroup.inv_mem _ hx

/-- Negative block shift preserves the global index subgroup. -/
theorem unshiftKPowHom_mem_omegaKSub {m : ℕ} {B : Set E} {q : ↥K}
    (hq : q ∈ omegaKSub m B) : unshiftKPowHom m q ∈ omegaKSub m B := by
  induction hq using Subgroup.closure_induction with
  | mem q hq =>
      obtain ⟨f, hf, rfl⟩ := hq
      rw [unshiftKPowHom_bK]
      exact Subgroup.subset_closure ⟨unshift m f, mem_omegaOp_unshift hf, rfl⟩
  | one => rw [map_one]; exact Subgroup.one_mem _
  | mul x y _ _ hx hy => rw [map_mul]; exact Subgroup.mul_mem _ hx hy
  | inv x _ hx => rw [map_inv]; exact Subgroup.inv_mem _ hx

/-- Mapping a coordinate word by the positive outer shift preserves the
global coordinate subgroup. -/
theorem map_shiftKPowHom_mem_omegaCoordSub {m : ℕ} {B : Set E}
    {w : FreeGroup ↥K} (hw : w ∈ omegaCoordSub m B) :
    FreeGroup.map (shiftKPowHom m) w ∈ omegaCoordSub m B := by
  induction hw using Subgroup.closure_induction with
  | mem x hx =>
      obtain ⟨q, hq, rfl⟩ := hx
      rw [FreeGroup.map.of]
      exact Subgroup.subset_closure
        ⟨shiftKPowHom m q, shiftKPowHom_mem_omegaKSub hq, rfl⟩
  | one => rw [map_one]; exact Subgroup.one_mem _
  | mul x y _ _ hx hy => rw [map_mul]; exact Subgroup.mul_mem _ hx hy
  | inv x _ hx => rw [map_inv]; exact Subgroup.inv_mem _ hx

/-- Mapping a coordinate word by the negative outer shift preserves the
global coordinate subgroup. -/
theorem map_unshiftKPowHom_mem_omegaCoordSub {m : ℕ} {B : Set E}
    {w : FreeGroup ↥K} (hw : w ∈ omegaCoordSub m B) :
    FreeGroup.map (unshiftKPowHom m) w ∈ omegaCoordSub m B := by
  induction hw using Subgroup.closure_induction with
  | mem x hx =>
      obtain ⟨q, hq, rfl⟩ := hx
      rw [FreeGroup.map.of]
      exact Subgroup.subset_closure
        ⟨unshiftKPowHom m q, unshiftKPowHom_mem_omegaKSub hq, rfl⟩
  | one => rw [map_one]; exact Subgroup.one_mem _
  | mul x y _ _ hx hy => rw [map_mul]; exact Subgroup.mul_mem _ hx hy
  | inv x _ hx => rw [map_inv]; exact Subgroup.inv_mem _ hx

/-- Either signed coordinate move preserves the outer scan invariant. -/
theorem signedCoordShift_mem_omegaCoordSub {m : ℕ} {B : Set E}
    (u : ℤˣ) {w : FreeGroup ↥K} (hw : w ∈ omegaCoordSub m B) :
    signedCoordShift m u w ∈ omegaCoordSub m B := by
  rcases Int.units_eq_one_or u with rfl | rfl
  · rw [signedCoordShift_one]
    exact map_shiftKPowHom_mem_omegaCoordSub hw
  · rw [signedCoordShift_negOne]
    exact map_unshiftKPowHom_mem_omegaCoordSub hw

end Omega
end Higman
end GroupApproximation
