import GroupApproximation.Higman.OmegaFatShearedCoordinateEdge

/-!
# The fixed-width base of the sheared-coordinate cutter

The coordinate induction is carried out inside one final semantic base
`FatCent3 m × F₃`.  Its initial source is therefore the range of the
width-zero alphabet evaluated in that final base, rather than the separately
constructed subgroup `fatShearedBlockLink 0` in the width-zero base.

This file gives that initial range its literal torsion-free benign witness.
The witness ambient is the final semantic base itself, so its cutter comap is
definitionally the source range.  This is the concrete seed used by the
matched successor construction.
-/

namespace GroupApproximation
namespace Higman
namespace Omega

open GroupApproximation.Higman.Seq
open GroupApproximation.Higman.Conj (F₃)

/-- The source range after the first `j` coordinates have been admitted,
always evaluated in the fixed final width `m`. -/
noncomputable def fatShearedCoordinateRange
    (m j : ℕ) (hjm : j ≤ m) : Subgroup (FatCent3 m × F₃) :=
  (fatShearedCoordinateSource m j hjm).range

/-- Only the zero sequence lies in the width-zero block alphabet.

Stated for a bare `b : E` rather than for `beta.1` with `beta : ↥(blockSet 0)`:
rewriting `blockSet 0` under a hypothesis about `↑beta` would have to abstract
`blockSet 0` out of `beta`'s own type, so the `rw` motive is not type correct
there. -/
theorem eq_zero_of_mem_blockSet_zero {b : E} (hb : b ∈ blockSet 0) : b = 0 := by
  rw [blockSet_zero_eq_Zset] at hb
  simpa [Zset] using hb

/-- The width-zero block alphabet has exactly one element. -/
theorem blockSet_zero_subsingleton :
    Subsingleton ↥(blockSet 0) := by
  constructor
  intro beta gamma
  exact Subtype.ext ((eq_zero_of_mem_blockSet_zero beta.2).trans
    (eq_zero_of_mem_blockSet_zero gamma.2).symm)

/-- The unique width-zero block index. -/
def zeroBlockIndex : ↥(blockSet 0) :=
  ⟨0, by rw [blockSet_zero_eq_Zset]; simp [Zset]⟩

@[simp] theorem fatShearedCoordinateSource_zero_of
    (m : ℕ) (beta : ↥(blockSet 0)) :
    fatShearedCoordinateSource m 0 (Nat.zero_le m) (FreeGroup.of beta) =
      slimFatSemanticBaseEmb m (slimLinkElem m 0) := by
  have hbeta : beta = zeroBlockIndex :=
    @Subsingleton.elim _ blockSet_zero_subsingleton beta zeroBlockIndex
  subst beta
  exact fatShearedCoordinateSource_of m 0 (Nat.zero_le m) zeroBlockIndex

/-- In the fixed final ambient, the initial source is literally the cyclic
subgroup generated by the zero block link. -/
theorem fatShearedCoordinateRange_zero_eq (m : ℕ) :
    fatShearedCoordinateRange m 0 (Nat.zero_le m) =
      Subgroup.closure {slimFatSemanticBaseEmb m (slimLinkElem m 0)} := by
  rw [fatShearedCoordinateRange, MonoidHom.range_eq_map,
    ← FreeGroup.closure_range_of (↥(blockSet 0)), MonoidHom.map_closure]
  congr 1
  ext x
  constructor
  · rintro ⟨_, ⟨beta, rfl⟩, rfl⟩
    exact Set.mem_singleton_iff.mpr
      (fatShearedCoordinateSource_zero_of m beta)
  · intro hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact ⟨FreeGroup.of zeroBlockIndex, ⟨zeroBlockIndex, rfl⟩,
      fatShearedCoordinateSource_zero_of m zeroBlockIndex⟩

/-- The fixed-width initial source range is finitely generated. -/
theorem fatShearedCoordinateRange_zero_fg (m : ℕ) :
    (fatShearedCoordinateRange m 0 (Nat.zero_le m)).FG := by
  rw [fatShearedCoordinateRange_zero_eq]
  exact (Subgroup.fg_iff _).mpr
    ⟨{slimFatSemanticBaseEmb m (slimLinkElem m 0)}, rfl,
      Set.finite_singleton _⟩

/-- The literal matched-cutter seed inside final width `m`.  Its finite
ambient is the semantic base itself and its cutter is the initial source
range, so no transport from a width-zero ambient is involved. -/
noncomputable def fatShearedCoordinateBaseWitness (m : ℕ) :
    TorsionFreeBenignWitness
      (fatShearedCoordinateRange m 0 (Nat.zero_le m)) := by
  letI : Group.IsFinitelyPresented (FatCent3 m) :=
    isFinitelyPresented_fatCent3 m
  letI : Group.IsFinitelyPresented (FatCent3 m × F₃) := inferInstance
  exact TorsionFreeBenignWitness.ofFG
    (IsPowerTorsionFree.prod (isPowerTorsionFree_fatCent3 m)
      IsPowerTorsionFree.of_isMulTorsionFree)
    (fatShearedCoordinateRange_zero_fg m)

/-- The fixed-width initial sheared range is unconditionally torsion-free
benign. -/
theorem benignTF_fatShearedCoordinateRange_zero (m : ℕ) :
    BenignTF (fatShearedCoordinateRange m 0 (Nat.zero_le m)) :=
  ⟨fatShearedCoordinateBaseWitness m⟩

@[simp] theorem fatShearedCoordinateBaseWitness_emb
    (m : ℕ) (x : FatCent3 m × F₃) :
    (fatShearedCoordinateBaseWitness m).witness.emb x = x := rfl

theorem fatShearedCoordinateBaseWitness_cutter (m : ℕ) :
    (fatShearedCoordinateBaseWitness m).witness.L =
      fatShearedCoordinateRange m 0 (Nat.zero_le m) := rfl

end Omega
end Higman
end GroupApproximation
