import GroupApproximation.Higman.HNNStableHull
import GroupApproximation.Higman.OmegaTowerDescent

/-!
# Stable-hull reduction for the outer Omega scan

The outer stage of Mikaelian's Omega tower cannot use the ordinary stable
subgroup descent directly: its stage-two alphabet is not shift-stable.  The
generic stable hull gives the exact unconditional replacement and leaves one
pure base-group computation.
-/

namespace GroupApproximation
namespace Higman
namespace Omega

open GroupApproximation.Higman.Conj
open GroupApproximation.Higman.Seq
open HNNExtension

/-- The concrete Omega subgroup is exactly the generic subgroup generated by
the stage-two alphabet and the final HNN stable letter. -/
theorem slimW_eq_outerClosure (m : ℕ) (B : Set E) :
    W (slimTower m) B =
      Subgroup.closure
        (HNNDescent.genSet (slimShiftRangeEquiv m) (slimWBase m B)) := by
  change Subgroup.closure
      ({slimOmegaEmb m a, slimOmegaStable m} ∪
        slimOmegaGen m '' (B ∩ blockSet m)) = _
  apply le_antisymm
  · exact slimW_le_outerClosure m B
  · let C : Subgroup (SlimOmega m) :=
      Subgroup.closure
        ({slimOmegaEmb m a, slimOmegaStable m} ∪
          slimOmegaGen m '' (B ∩ blockSet m))
    change Subgroup.closure
      (HNNDescent.genSet (slimShiftRangeEquiv m) (slimWBase m B)) ≤ C
    rw [Subgroup.closure_le]
    rintro y (hy | hy)
    · obtain ⟨z, hz, rfl⟩ := hy
      have hle : slimWBase m B ≤ C.comap (slimOmegaOf m) := by
        rw [slimWBase, Subgroup.closure_le]
        rintro z (hz | hz)
        · rw [Set.mem_singleton_iff] at hz
          subst z
          change slimOmegaEmb m a ∈ C
          exact Subgroup.subset_closure
            (Set.mem_union_left _ (Set.mem_insert _ _))
        · obtain ⟨β, hβ, rfl⟩ := hz
          change slimOmegaGen m β ∈ C
          exact Subgroup.subset_closure
            (Set.mem_union_right _ ⟨β, hβ, rfl⟩)
      exact hle hz
    · rw [Set.mem_singleton_iff] at hy
      subst y
      have hr := Subgroup.inv_mem C
        (Subgroup.subset_closure
          (Set.mem_union_left _ (Set.mem_insert_of_mem _ rfl)))
      simpa [slimOmegaStable] using hr

/-- **Exact outer-base computation, before the arithmetic classifier.**
Intersecting the concrete Omega subgroup with the stage-two base is exactly
the stable hull of `slimWBase`. -/
theorem slimW_comap_outerBase (m : ℕ) (B : Set E) :
    (W (slimTower m) B).comap (slimOmegaOf m) =
      HNNDescent.stableHull (slimShiftRangeEquiv m) (slimWBase m B) := by
  rw [slimW_eq_outerClosure]
  symm
  exact HNNDescent.stableHull_eq_generatedBase
    (slimShiftRangeEquiv m) (slimWBase m B)

/-- Elementwise exactness of the stable-hull reduction on the original
rank-three subgroup. -/
theorem slimPiF3Hom_mem_outerStableHull_iff
    {m : ℕ} {B : Set E} {x : F₃} :
    slimPiF3Hom m x ∈
        HNNDescent.stableHull (slimShiftRangeEquiv m) (slimWBase m B) ↔
      slimOmegaEmb m x ∈ W (slimTower m) B := by
  rw [← slimW_comap_outerBase m B]
  rfl

/-- Every original `F₃` element in the concrete Omega subgroup belongs, at
stage two, to the least shift-stable subgroup containing `slimWBase`. -/
theorem slimPiF3Hom_mem_outerStableHull_of_mem_slimW
    {m : ℕ} {B : Set E} {x : F₃}
    (hx : slimOmegaEmb m x ∈ W (slimTower m) B) :
    slimPiF3Hom m x ∈
      HNNDescent.stableHull (slimShiftRangeEquiv m) (slimWBase m B) := by
  apply HNNDescent.mem_stableHull_of_of_mem_closure
    (slimShiftRangeEquiv m)
  change slimOmegaEmb m x ∈
    Subgroup.closure
      (HNNDescent.genSet (slimShiftRangeEquiv m) (slimWBase m B))
  exact slimW_le_outerClosure m B hx

/-- Consequently the remaining hard half of the Omega computation is exactly
the base statement that the stable hull meets the embedded `F₃` inside
`A_(omegaOp m B)`. -/
theorem slimTower_descent_of_outerStableHull
    {m : ℕ} {B : Set E}
    (hbase : ∀ x : F₃,
      slimPiF3Hom m x ∈
          HNNDescent.stableHull (slimShiftRangeEquiv m) (slimWBase m B) →
        x ∈ ASub (omegaOp m B)) :
    ∀ x : F₃, slimOmegaEmb m x ∈ W (slimTower m) B →
      x ∈ ASub (omegaOp m B) := by
  intro x hx
  exact hbase x (slimPiF3Hom_mem_outerStableHull_of_mem_slimW hx)

end Omega
end Higman
end GroupApproximation
