import GroupApproximation.Higman.OmegaBlockWindowBenign
import GroupApproximation.Higman.OmegaTowerDescent
import GroupApproximation.Higman.PairedReturnCutter

/-!
# The selected finite-window cutter in the fat Omega base

The three central stable letters always retain a free rank-three quotient,
independently of the base group and centralized subgroup.  Consequently the
selected block-code subgroup in the finitely presented fat first stage is an
injective image of `ASub (B ∩ blockSet m)`.  The finite-window theorem then
supplies its torsion-free benign witness.
-/

namespace GroupApproximation
namespace Higman
namespace Omega

open GroupApproximation.Higman.Conj
open GroupApproximation.Higman.Seq
open HNNExtension

variable {G₀ : Type} [Group G₀]

/-- Kill the original base and retain the first central stable letter as `a`. -/
def genericGenProjection1 (P : Subgroup G₀) : Cent1 P →* F₃ :=
  HNNExtension.lift 1 a (by intro z; simp)

@[simp] theorem genericGenProjection1_of (P : Subgroup G₀) (x : G₀) :
    genericGenProjection1 P (emb1 P x) = 1 := by
  simp [genericGenProjection1, emb1, HNNExtension.lift_of]

@[simp] theorem genericGenProjection1_t (P : Subgroup G₀) :
    genericGenProjection1 P (t : Cent1 P) = a := by
  simp [genericGenProjection1, HNNExtension.lift_t]

/-- Retain the second central stable letter as `b`. -/
def genericGenProjection2 (P : Subgroup G₀) : Cent2 P →* F₃ :=
  HNNExtension.lift (genericGenProjection1 P) b (by
    intro z
    obtain ⟨x, _, hxz⟩ := z.property
    have hz : genericGenProjection1 P (z : Cent1 P) = 1 := by
      rw [← hxz]
      exact genericGenProjection1_of P x
    change b * genericGenProjection1 P z = genericGenProjection1 P z * b
    rw [hz, mul_one, one_mul])

@[simp] theorem genericGenProjection2_of (P : Subgroup G₀) (x : Cent1 P) :
    genericGenProjection2 P (of x) = genericGenProjection1 P x := by
  simp [genericGenProjection2, HNNExtension.lift_of]

@[simp] theorem genericGenProjection2_t (P : Subgroup G₀) :
    genericGenProjection2 P (t : Cent2 P) = b := by
  simp [genericGenProjection2, HNNExtension.lift_t]

/-- Retain the third central stable letter as `c`. -/
def genericGenProjection3 (P : Subgroup G₀) : Cent3 P →* F₃ :=
  HNNExtension.lift (genericGenProjection2 P) c (by
    intro z
    obtain ⟨x, hx, hxz⟩ := z.property
    have hz : genericGenProjection2 P (z : Cent2 P) = 1 := by
      rw [← hxz, genericGenProjection2_of]
      obtain ⟨y, _, hyx⟩ := hx
      rw [← hyx]
      exact genericGenProjection1_of P y
    change c * genericGenProjection2 P z = genericGenProjection2 P z * c
    rw [hz, mul_one, one_mul])

@[simp] theorem genericGenProjection3_of (P : Subgroup G₀) (x : Cent2 P) :
    genericGenProjection3 P (of x) = genericGenProjection2 P x := by
  simp [genericGenProjection3, HNNExtension.lift_of]

@[simp] theorem genericGenProjection3_t (P : Subgroup G₀) :
    genericGenProjection3 P (t : Cent3 P) = c := by
  simp [genericGenProjection3, HNNExtension.lift_t]

theorem genericGenProjection3_comp_genHom (P : Subgroup G₀) :
    (genericGenProjection3 P).comp (genHom P) = MonoidHom.id F₃ := by
  refine FreeGroup.ext_hom _ _ fun i => ?_
  fin_cases i <;>
    simp [genHom, gen1, gen2, gen3, a, b, c,
      genericGenProjection3, genericGenProjection2, genericGenProjection1]

theorem genHom_injective_generic (P : Subgroup G₀) :
    Function.Injective (genHom P) := by
  intro x y hxy
  have h := congrArg (genericGenProjection3 P) hxy
  rwa [← MonoidHom.comp_apply, ← MonoidHom.comp_apply,
    genericGenProjection3_comp_genHom, MonoidHom.id_apply,
    MonoidHom.id_apply] at h

/-- The selected second-copy code inside the fat first stage. -/
noncomputable def fatGenCode (m : ℕ) (beta : E) : FatCent3 m :=
  genHom (fatOutside m) (aElt beta)

/-- The subgroup generated by the selected finite-window codes. -/
noncomputable def fatGenSub (m : ℕ) (B : Set E) : Subgroup (FatCent3 m) :=
  Subgroup.closure (fatGenCode m '' (B ∩ blockSet m))

theorem fatGenSub_eq_map_ASub (m : ℕ) (B : Set E) :
    fatGenSub m B =
      (ASub (B ∩ blockSet m)).map (genHom (fatOutside m)) := by
  unfold fatGenSub fatGenCode ASub
  rw [MonoidHom.map_closure]
  congr 1
  ext x
  constructor
  · rintro ⟨beta, hbeta, rfl⟩
    exact ⟨aElt beta, ⟨beta, hbeta, rfl⟩, rfl⟩
  · rintro ⟨_, ⟨beta, hbeta, rfl⟩, rfl⟩
    exact ⟨beta, hbeta, rfl⟩

/-- **Finite selected cutter.**  A benign input subgroup gives a benign
selected-code subgroup in the finitely presented fat first stage. -/
theorem benignTF_fatGenSub {m : ℕ} {B : Set E} (hB : BenignTF (ASub B)) :
    BenignTF (fatGenSub m B) := by
  letI : Group.IsFinitelyPresented (FatCent3 m) :=
    isFinitelyPresented_fatCent3 m
  have hinter : BenignTF (ASub (B ∩ blockSet m)) := by
    rw [ASub_inter]
    exact BenignTF.inf hB (benignTF_ASub_blockSet m)
  rw [fatGenSub_eq_map_ASub]
  exact BenignTF.mapEmb (isPowerTorsionFree_fatCent3 m) hinter
    (genHom (fatOutside m)) (genHom_injective_generic (fatOutside m))

/-- A chosen finite cutter for the selected block codes in the fat stage. -/
noncomputable def fatGenWitness {m : ℕ} {B : Set E}
    (hB : BenignTF (ASub B)) : TorsionFreeBenignWitness (fatGenSub m B) :=
  Classical.choice (benignTF_fatGenSub hB)

/-- The finite-rank paired base embeds into the fat semantic product by the
second-copy code on the first coordinate and identically on the return
coordinate. -/
noncomputable def fatGraphBaseEmb (m : ℕ) :
    F₃ × F₃ →* FatCent3 m × F₃ :=
  (genHom (fatOutside m)).prodMap (MonoidHom.id F₃)

@[simp] theorem fatGraphBaseEmb_apply (m : ℕ) (p : F₃ × F₃) :
    fatGraphBaseEmb m p = (genHom (fatOutside m) p.1, p.2) := rfl

theorem fatGraphBaseEmb_injective (m : ℕ) :
    Function.Injective (fatGraphBaseEmb m) := by
  intro p q hpq
  apply Prod.ext
  · apply genHom_injective_generic (fatOutside m)
    exact congrArg (fun z : FatCent3 m × F₃ => z.1) hpq
  · exact congrArg (fun z : FatCent3 m × F₃ => z.2) hpq

/-- The selected paired-return graph in the finitely presented fat semantic
base.  The meet is deliberately formed in finite rank before mapping. -/
noncomputable def fatSelectedGraph (m : ℕ) (B : Set E) :
    Subgroup (FatCent3 m × F₃) :=
  (Star.graphSub ⊓
    (ASub (B ∩ blockSet m)).prod (⊤ : Subgroup F₃)).map
      (fatGraphBaseEmb m)

/-- **Fat finite graph cutter.**  This is the actual benign graph gate, not
only the benignness of its first-coordinate projection. -/
theorem benignTF_fatSelectedGraph {m : ℕ} {B : Set E}
    (hB : BenignTF (ASub B)) : BenignTF (fatSelectedGraph m B) := by
  letI : Group.IsFinitelyPresented (FatCent3 m) :=
    isFinitelyPresented_fatCent3 m
  letI : Group.IsFinitelyPresented (FatCent3 m × F₃) :=
    inferInstance
  have hselected : BenignTF (ASub (B ∩ blockSet m)) := by
    rw [ASub_inter]
    exact BenignTF.inf hB (benignTF_ASub_blockSet m)
  have hprod : BenignTF
      ((ASub (B ∩ blockSet m)).prod (⊤ : Subgroup F₃)) := by
    rw [Star.prod_top_eq_comap_fst]
    exact BenignTF.comap Star.doubleOvergroup (MonoidHom.fst F₃ F₃) hselected
  have hgate : BenignTF
      (Star.graphSub ⊓
        (ASub (B ∩ blockSet m)).prod (⊤ : Subgroup F₃)) :=
    BenignTF.inf PairedReturnCutter.graph_benignTF hprod
  unfold fatSelectedGraph
  exact BenignTF.mapEmb
    (IsPowerTorsionFree.prod (isPowerTorsionFree_fatCent3 m)
      IsPowerTorsionFree.of_isMulTorsionFree)
    hgate (fatGraphBaseEmb m) (fatGraphBaseEmb_injective m)

/-- A chosen finitely generated cutter for the fat selected graph. -/
noncomputable def fatSelectedGraphWitness {m : ℕ} {B : Set E}
    (hB : BenignTF (ASub B)) : TorsionFreeBenignWitness (fatSelectedGraph m B) :=
  Classical.choice (benignTF_fatSelectedGraph hB)

end Omega
end Higman
end GroupApproximation
