import GroupApproximation.Higman.HalfRowEndo
import GroupApproximation.Higman.HNNDescent
import GroupApproximation.Higman.TorsionFreeImageClosure
import GroupApproximation.Higman.OperationClosureTheta

/-!
# Row subgroups of `F₃`, and Higman's Example 3.7

The agreement lane (`Higman.AgreeClosure`, `Higman.OperationClosureTheta`) asks
for benignness --- with a torsion-free witness --- of three subgroups of `F₃`,
all of them of the shape

    Agree.rowSub V = V.map rowHom ,      V ≤ FreeGroup ℤ ,

namely `V = Agree.piV` (the strictly positive half row, Higman's Example 3.7),
`V = Agree.zetaV = ker (killOn (· ≠ 0))` (the normal closure of `b` in the row)
and `V = ker (killOn evenIdx)` (the normal closure of the odd row elements).
This file does three things.

## 1.  One transfer lemma, for all three

`benignTF_rowSub_of_benignTF_map`: if `V.map basisHom` is benign in the rank-two
free group `F₀ = ⟨b, c⟩`, then `Agree.rowSub V` is benign in `F₃ = ⟨a, b, c⟩`.
`F₀` sits inside `F₃` by `inclHom`, which is injective because `Seq.retract`
retracts it, and `rowHom = inclHom ∘ basisHom` on the nose; so the statement is
the image half of Higman's Lemma 3.3 with the torsion clause,
`Higman.BenignTF.mapEmb`, at that one embedding.  **Nothing about `V` is used**,
so the ambient group is not where any of the three leaves is hard: each of them
is a statement about `⟨b, c⟩` alone, and this lemma is the whole of the passage
to `F₃`.

## 2.  One general benign witness, from a stable letter

`stableWitness`: let `P` be finitely presented and torsion-free, let `φ : A ≃ B`
be an isomorphism between subgroups of `P` with `A` finitely generated, and let
`Z ≤ P` be *stable* in the sense of `Higman.HNNDescent` --- `φ` and `φ⁻¹` do not
carry the part of `Z` inside `A`, resp. `B`, out of `Z`.  If moreover a **finite**
set `S ⊆ Z` generates `Z` inside `P ∗_φ t` --- every `x ∈ Z` is a word in `S` and
the stable letter --- then `Z` is benign in `P`, with a torsion-free witness.

The two halves are exactly the two theorems already in the repository:
`HNNDescent.mem_of_mem_closure_subset` for `⟨S, t⟩ ∩ P ≤ Z`, and
`HNNFinitePresentation.isFinitelyPresented_hnnExtension` together with
`HNNBritton.isPowerTorsionFree_hnn` for the two clauses on the overgroup.  The
lemma is stated over an abstract base precisely so that it can be applied at the
*second* floor of a two-letter tower, which is what Example 3.7 needs.

## 3.  Example 3.7, proved

Higman's Example 3.7 is the first leaf, and it is the one whose apparatus
(`Higman.RowKernel`, `Higman.HalfRowEndo`) is complete: the two injective
endomorphisms `ξ₀ : b ↦ b, c ↦ c²` and `ξ₁ : b ↦ b₁, c ↦ c²`, their action
`ξ_l bᵢ = b_{2i+l}` on the row, and the two-way stability of the half row under
both.  Build

    Γ₀ = F₀ ∗_{ξ₀} t₀ ,    Γ₁ = Γ₀ ∗_{ξ₁} t₁ ,

the second extension conjugating the copy of `F₀` inside `Γ₀` onto the copy of
`ξ₁(F₀)`, and take `L = ⟨b, t₀, t₁⟩`.  Then

* `L ∩ F₀ ⊆ HalfRow` is two descents: the outer one is `stableWitness` at
  `Z = ⟨HalfRow, t₀⟩ ≤ Γ₀`, whose stability is *the inner descent* --- that
  subgroup meets `F₀` in `HalfRow` and nowhere else, so `ξ₁` and `ξ₁⁻¹` see only
  the half row, where `Higman.HalfRowEndo` has already made them stable;
* `HalfRow ⊆ L` is the binary expansion: `bₙ = ξ_l b_{(n-l)/2}` with
  `l = n % 2`, so a strong induction on `n` walks every nonnegative index down
  to `b₀ = b`, one stable letter per binary digit.

The half row `⟨bᵢ : i ≥ 0⟩` and the strictly positive half row `⟨bᵢ : i > 0⟩`
that `Agree.piV` codes differ by one conjugation, and benignness is invariant
under `BenignTF.congr`, so `benignTF_rowSub_piV` closes the leaf
`Agree.AgreeInputs.half`.

## What is left

The other two leaves are *kernels* of the deletion retraction --- normal
closures in the row of a set of row elements --- rather than subgroups
generated by row elements, and neither is an instance of what is proved here:
`ξ₀` and `ξ₁` carry the odd indices onto even ones, so neither
`zetaV = ⟨⟨b₀⟩⟩` nor `ker (killOn evenIdx) = ⟨⟨bᵢ : i odd⟩⟩` is stable under
them in the sense `stableWitness` asks for, and the stability hypothesis is
what the descent runs on.  They are recorded here in the shape the transfer
lemma leaves them --- statements about `⟨b, c⟩`, with `F₃` gone --- as the
hypotheses `benignTF_rowSub_zetaV` and `benignTF_rowSub_ker_killOn` take.
`stableWitness` is stated in the generality a different stable-letter system
would need, so a route for either of them can be plugged into it.
-/

namespace GroupApproximation
namespace Higman

noncomputable section

/-! ## 1.  The benign witness a stable letter builds -/

/-- **The witness a stable letter builds.**  In `P ∗_φ t`, the subgroup
generated by a finite set `S` of base elements and the stable letter meets the
base in `Z`, provided `Z` is stable and `S` generates it with the letter's
help.  The extension is finitely presented because `A` is finitely generated,
and torsion-free because `P` is. -/
def stableWitness {P : Type} [Group P] [Group.IsFinitelyPresented P]
    {A B : Subgroup P} [Group.FG ↥A] (φ : A ≃* B) (hP : IsPowerTorsionFree P)
    {Z : Subgroup P} (hst : HNNDescent.Stable φ Z) {S : Set P} (hSfin : S.Finite)
    (hSZ : S ⊆ (Z : Set P))
    (hgen : ∀ x ∈ Z, (HNNExtension.of x : HNNExtension P A B φ) ∈
      Subgroup.closure ((HNNExtension.of : P →* HNNExtension P A B φ) '' S ∪
        {(HNNExtension.t : HNNExtension P A B φ)})) :
    TorsionFreeBenignWitness Z where
  witness :=
    { K := HNNExtension P A B φ
      fp := HNNFinitePresentation.isFinitelyPresented_hnnExtension φ
      emb := (HNNExtension.of : P →* HNNExtension P A B φ)
      emb_injective := HNNExtension.of_injective (φ := φ)
      L := Subgroup.closure ((HNNExtension.of : P →* HNNExtension P A B φ) '' S ∪
        {(HNNExtension.t : HNNExtension P A B φ)})
      L_fg := by
        refine (Subgroup.fg_iff _).mpr
          ⟨(HNNExtension.of : P →* HNNExtension P A B φ) '' S ∪
            {(HNNExtension.t : HNNExtension P A B φ)}, rfl, ?_⟩
        exact (hSfin.image _).union (Set.finite_singleton _)
      comap_eq := by
        refine Subgroup.ext fun x => ?_
        constructor
        · intro hx
          exact HNNDescent.mem_of_mem_closure_subset φ hst S hSZ (Subgroup.mem_comap.mp hx)
        · intro hx
          exact Subgroup.mem_comap.mpr (hgen x hx) }
  torsionFree := HNNBritton.isPowerTorsionFree_hnn φ hP

/-- **The witness a stable letter builds**, in `Prop` form. -/
theorem benignTF_of_stable {P : Type} [Group P] [Group.IsFinitelyPresented P]
    {A B : Subgroup P} [Group.FG ↥A] (φ : A ≃* B) (hP : IsPowerTorsionFree P)
    {Z : Subgroup P} (hst : HNNDescent.Stable φ Z) {S : Set P} (hSfin : S.Finite)
    (hSZ : S ⊆ (Z : Set P))
    (hgen : ∀ x ∈ Z, (HNNExtension.of x : HNNExtension P A B φ) ∈
      Subgroup.closure ((HNNExtension.of : P →* HNNExtension P A B φ) '' S ∪
        {(HNNExtension.t : HNNExtension P A B φ)})) :
    BenignTF Z :=
  ⟨stableWitness φ hP hst hSfin hSZ hgen⟩

namespace Row

/-! ## 2.  The first stable letter, `ξ₀` -/

/-- `ξ_l`, as an isomorphism onto its image. -/
def xiEmb (l : ℤ) : F₀ ≃* ↥((xi l).range) :=
  MonoidHom.ofInjective (xi_injective l)

@[simp] theorem coe_xiEmb (l : ℤ) (x : F₀) :
    ((xiEmb l x : ↥((xi l).range)) : F₀) = xi l x :=
  MonoidHom.ofInjective_apply (xi_injective l)

/-- `ξ₀`, transported to the top subgroup: the isomorphism the first stable
letter conjugates by. -/
def xiTop : ↥(⊤ : Subgroup F₀) ≃* ↥((xi 0).range) :=
  (Subgroup.topEquiv).trans (xiEmb 0)

theorem coe_xiTop (a : ↥(⊤ : Subgroup F₀)) :
    ((xiTop a : ↥((xi 0).range)) : F₀) = xi 0 (a : F₀) := rfl

theorem xi_coe_xiTop_symm (u : ↥((xi 0).range)) :
    xi 0 ((xiTop.symm u : ↥(⊤ : Subgroup F₀)) : F₀) = (u : F₀) := by
  have h := coe_xiTop (xiTop.symm u)
  rw [xiTop.apply_symm_apply] at h
  exact h.symm

/-- The first extension, `F₀ ∗_{ξ₀} t₀`. -/
abbrev GamZero : Type := HNNExtension F₀ ⊤ ((xi 0).range) xiTop

theorem fg_top_F₀ : Group.FG ↥(⊤ : Subgroup F₀) := by
  letI : Group.FG F₀ := ProductFinitePresentation.fg_of_isFinitelyPresented F₀
  exact Group.fg_of_surjective (f := (Subgroup.topEquiv (G := F₀)).symm.toMonoidHom)
    (Subgroup.topEquiv (G := F₀)).symm.surjective

theorem isFinitelyPresented_gamZero : Group.IsFinitelyPresented GamZero := by
  letI : Group.FG ↥(⊤ : Subgroup F₀) := fg_top_F₀
  exact HNNFinitePresentation.isFinitelyPresented_hnnExtension xiTop

theorem torsionFree_gamZero : IsPowerTorsionFree GamZero :=
  HNNBritton.isPowerTorsionFree_hnn xiTop IsPowerTorsionFree.of_isMulTorsionFree

theorem ofZero_injective : Function.Injective (HNNExtension.of : F₀ →* GamZero) :=
  HNNExtension.of_injective (φ := xiTop)

/-- **The relation the first stable letter imposes.** -/
theorem conj_ofZero (x : F₀) :
    (HNNExtension.t : GamZero) * HNNExtension.of x * (HNNExtension.t : GamZero)⁻¹
      = HNNExtension.of (xi 0 x) := by
  have h := HNNExtension.equiv_eq_conj (φ := xiTop) ⟨x, Subgroup.mem_top x⟩
  rw [coe_xiTop] at h
  exact h.symm

/-! ## 3.  The half row is stable under the first letter -/

theorem stable_xiTop : HNNDescent.Stable xiTop HalfRow := by
  refine ⟨?_, ?_⟩
  · intro a ha
    rw [coe_xiTop]
    exact xi_mem_halfRow le_rfl ha
  · intro u hu
    refine mem_halfRow_of_xi_mem_halfRow (l := 0) le_rfl (by norm_num) ?_
    rw [xi_coe_xiTop_symm]
    exact hu

/-- The subgroup of the first extension generated by the half row and the first
stable letter.  By the descent it meets `F₀` in the half row exactly. -/
def ZSub : Subgroup GamZero := Subgroup.closure (HNNDescent.genSet xiTop HalfRow)

theorem of_mem_ZSub {x : F₀} (hx : x ∈ HalfRow) : (HNNExtension.of x : GamZero) ∈ ZSub := by
  have hmem : (HNNExtension.of x : GamZero) ∈ HNNDescent.genSet xiTop HalfRow := by
    show (HNNExtension.of x : GamZero) ∈
      ((HalfRow.map (HNNExtension.of : F₀ →* GamZero) : Set GamZero) ∪
        {(HNNExtension.t : GamZero)})
    exact Or.inl ⟨x, hx, rfl⟩
  exact Subgroup.subset_closure hmem

theorem t_mem_ZSub : (HNNExtension.t : GamZero) ∈ ZSub := by
  have hmem : (HNNExtension.t : GamZero) ∈ HNNDescent.genSet xiTop HalfRow := by
    show (HNNExtension.t : GamZero) ∈
      ((HalfRow.map (HNNExtension.of : F₀ →* GamZero) : Set GamZero) ∪
        {(HNNExtension.t : GamZero)})
    exact Or.inr rfl
  exact Subgroup.subset_closure hmem

/-- **The inner descent.**  A base element of `⟨HalfRow, t₀⟩` is in the half
row. -/
theorem mem_halfRow_of_of_mem_ZSub {x : F₀} (hx : (HNNExtension.of x : GamZero) ∈ ZSub) :
    x ∈ HalfRow := by
  have hx' : (HNNExtension.of x : GamZero) ∈
      Subgroup.closure (HNNDescent.genSet xiTop HalfRow) := hx
  exact HNNDescent.mem_of_of_mem_closure xiTop stable_xiTop hx'

theorem b_mem_halfRow : b ∈ HalfRow := by
  have h := row_mem_halfRow (i := 0) le_rfl
  rwa [row_zero] at h

/-! ## 4.  The second stable letter, `ξ₁` -/

/-- The copy of `F₀` inside the first extension. -/
def Acopy : Subgroup GamZero := MonoidHom.range (HNNExtension.of : F₀ →* GamZero)

/-- The copy of `ξ₁(F₀)` inside the first extension. -/
def Bcopy : Subgroup GamZero :=
  MonoidHom.range ((HNNExtension.of : F₀ →* GamZero).comp (xi 1))

/-- `F₀` and its copy. -/
def embA : F₀ ≃* ↥Acopy := MonoidHom.ofInjective ofZero_injective

@[simp] theorem coe_embA (x : F₀) :
    ((embA x : ↥Acopy) : GamZero) = (HNNExtension.of x : GamZero) :=
  MonoidHom.ofInjective_apply ofZero_injective

theorem ofZero_xi_injective :
    Function.Injective ((HNNExtension.of : F₀ →* GamZero).comp (xi 1)) := by
  intro x y hxy
  exact xi_injective 1 (ofZero_injective hxy)

/-- `F₀` and the copy of its image under `ξ₁`. -/
def embB : F₀ ≃* ↥Bcopy := MonoidHom.ofInjective ofZero_xi_injective

@[simp] theorem coe_embB (x : F₀) :
    ((embB x : ↥Bcopy) : GamZero) = (HNNExtension.of (xi 1 x) : GamZero) :=
  MonoidHom.ofInjective_apply ofZero_xi_injective

/-- `ξ₁`, transported to the copy of `F₀`: the isomorphism the second stable
letter conjugates by. -/
def xiOneA : ↥Acopy ≃* ↥Bcopy := (embA.symm).trans embB

theorem xiOneA_embA (x : F₀) : xiOneA (embA x) = embB x := by
  show embB (embA.symm (embA x)) = embB x
  rw [embA.symm_apply_apply]

theorem xiOneA_symm_embB (x : F₀) : xiOneA.symm (embB x) = embA x := by
  rw [← xiOneA_embA, MulEquiv.symm_apply_apply]

theorem coe_xiOneA_embA (x : F₀) :
    ((xiOneA (embA x) : ↥Bcopy) : GamZero) = (HNNExtension.of (xi 1 x) : GamZero) := by
  rw [xiOneA_embA, coe_embB]

theorem coe_xiOneA_symm_embB (x : F₀) :
    ((xiOneA.symm (embB x) : ↥Acopy) : GamZero) = (HNNExtension.of x : GamZero) := by
  rw [xiOneA_symm_embB, coe_embA]

/-- The second extension, `Γ₀ ∗_{ξ₁} t₁`. -/
abbrev GamOne : Type := HNNExtension GamZero Acopy Bcopy xiOneA

theorem fg_Acopy : Group.FG ↥Acopy := by
  letI : Group.FG F₀ := ProductFinitePresentation.fg_of_isFinitelyPresented F₀
  exact Group.fg_of_surjective (f := embA.toMonoidHom) embA.surjective

/-- **The relation the second stable letter imposes.** -/
theorem conj_ofOne (x : F₀) :
    (HNNExtension.t : GamOne) * HNNExtension.of (HNNExtension.of x : GamZero)
        * (HNNExtension.t : GamOne)⁻¹
      = HNNExtension.of (HNNExtension.of (xi 1 x) : GamZero) := by
  have h := HNNExtension.equiv_eq_conj (φ := xiOneA) (embA x)
  rw [coe_xiOneA_embA, coe_embA] at h
  exact h.symm

/-! ## 5.  `⟨HalfRow, t₀⟩` is stable under the second letter

This is where the inner descent is consumed: the part of `⟨HalfRow, t₀⟩` inside
the copy of `F₀` is the half row and nothing more, and `Higman.HalfRowEndo` has
already proved the half row stable under `ξ₁` in both directions. -/

theorem stable_xiOneA : HNNDescent.Stable xiOneA ZSub := by
  refine ⟨?_, ?_⟩
  · intro a ha
    obtain ⟨x, rfl⟩ : ∃ x : F₀, a = embA x :=
      ⟨embA.symm a, (embA.apply_symm_apply a).symm⟩
    have hxZ : (HNNExtension.of x : GamZero) ∈ ZSub := by
      have hcoe : (HNNExtension.of x : GamZero) = ((embA x : ↥Acopy) : GamZero) :=
        (coe_embA x).symm
      rw [hcoe]
      exact ha
    rw [coe_xiOneA_embA]
    exact of_mem_ZSub (xi_mem_halfRow (l := 1) (by norm_num) (mem_halfRow_of_of_mem_ZSub hxZ))
  · intro u hu
    obtain ⟨y, rfl⟩ : ∃ y : F₀, u = embB y :=
      ⟨embB.symm u, (embB.apply_symm_apply u).symm⟩
    have hyZ : (HNNExtension.of (xi 1 y) : GamZero) ∈ ZSub := by
      have hcoe : (HNNExtension.of (xi 1 y) : GamZero) = ((embB y : ↥Bcopy) : GamZero) :=
        (coe_embB y).symm
      rw [hcoe]
      exact hu
    rw [coe_xiOneA_symm_embB]
    refine of_mem_ZSub ?_
    exact mem_halfRow_of_xi_mem_halfRow (l := 1) (by norm_num) (by norm_num)
      (mem_halfRow_of_of_mem_ZSub hyZ)

/-! ## 6.  The finitely generated subgroup, and the binary expansion -/

/-- The two base elements the finitely generated subgroup is built from: the
generator `b`, and the first stable letter. -/
def seedSet : Set GamZero := {(HNNExtension.of b : GamZero), (HNNExtension.t : GamZero)}

theorem seedSet_finite : seedSet.Finite := by
  show ({(HNNExtension.of b : GamZero), (HNNExtension.t : GamZero)} : Set GamZero).Finite
  exact (Set.finite_singleton _).insert _

theorem seedSet_subset : seedSet ⊆ (ZSub : Set GamZero) := by
  intro y hy
  have hy' : y = (HNNExtension.of b : GamZero) ∨
      y ∈ ({(HNNExtension.t : GamZero)} : Set GamZero) := hy
  rcases hy' with rfl | hy'
  · exact of_mem_ZSub b_mem_halfRow
  · rw [Set.mem_singleton_iff] at hy'
    subst hy'
    exact t_mem_ZSub

/-- `L = ⟨b, t₀, t₁⟩`, the finitely generated subgroup that cuts the half row
out of `F₀`. -/
def LSub : Subgroup GamOne :=
  Subgroup.closure ((HNNExtension.of : GamZero →* GamOne) '' seedSet ∪
    {(HNNExtension.t : GamOne)})

/-- The generating set of `L`, spelled out. -/
theorem lSubGen (y : GamOne) (hy : y ∈ ((HNNExtension.of : GamZero →* GamOne) '' seedSet ∪
    {(HNNExtension.t : GamOne)})) : y ∈ LSub :=
  Subgroup.subset_closure hy

theorem of_of_b_mem_LSub :
    (HNNExtension.of (HNNExtension.of b : GamZero) : GamOne) ∈ LSub := by
  refine lSubGen _ (Or.inl ⟨(HNNExtension.of b : GamZero), ?_, rfl⟩)
  show (HNNExtension.of b : GamZero) = (HNNExtension.of b : GamZero) ∨
    (HNNExtension.of b : GamZero) ∈ ({(HNNExtension.t : GamZero)} : Set GamZero)
  exact Or.inl rfl

theorem of_t_mem_LSub : (HNNExtension.of (HNNExtension.t : GamZero) : GamOne) ∈ LSub := by
  refine lSubGen _ (Or.inl ⟨(HNNExtension.t : GamZero), ?_, rfl⟩)
  show (HNNExtension.t : GamZero) = (HNNExtension.of b : GamZero) ∨
    (HNNExtension.t : GamZero) ∈ ({(HNNExtension.t : GamZero)} : Set GamZero)
  exact Or.inr rfl

theorem t_mem_LSub : (HNNExtension.t : GamOne) ∈ LSub :=
  lSubGen _ (Or.inr rfl)

/-- **The binary expansion.**  Every nonnegative row element is a word in `b`
and the two stable letters: `bₙ = ξ_l b_{(n-l)/2}` for `l = n % 2`, and the
index strictly decreases. -/
theorem of_of_row_mem_LSub : ∀ n : ℕ,
    (HNNExtension.of (HNNExtension.of (row (n : ℤ)) : GamZero) : GamOne) ∈ LSub := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    rcases Nat.eq_zero_or_pos n with rfl | hn
    · have h0 : ((0 : ℕ) : ℤ) = (0 : ℤ) := Nat.cast_zero
      rw [h0, row_zero]
      exact of_of_b_mem_LSub
    · have hlt : n / 2 < n := Nat.div_lt_self hn (by norm_num)
      have hih := ih (n / 2) hlt
      rcases Nat.mod_two_eq_zero_or_one n with h2 | h2
      · have hidx : 2 * ((n / 2 : ℕ) : ℤ) + (0 : ℤ) = (n : ℤ) := by omega
        have hrow : row ((n : ℕ) : ℤ) = xi 0 (row ((n / 2 : ℕ) : ℤ)) := by
          rw [xi_row, hidx]
        rw [hrow, ← conj_ofZero, map_mul, map_mul, map_inv]
        exact Subgroup.mul_mem _ (Subgroup.mul_mem _ of_t_mem_LSub hih)
          (Subgroup.inv_mem _ of_t_mem_LSub)
      · have hidx : 2 * ((n / 2 : ℕ) : ℤ) + (1 : ℤ) = (n : ℤ) := by omega
        have hrow : row ((n : ℕ) : ℤ) = xi 1 (row ((n / 2 : ℕ) : ℤ)) := by
          rw [xi_row, hidx]
        rw [hrow, ← conj_ofOne]
        exact Subgroup.mul_mem _ (Subgroup.mul_mem _ t_mem_LSub hih)
          (Subgroup.inv_mem _ t_mem_LSub)

theorem of_of_mem_LSub_of_mem_halfRow {w : F₀} (hw : w ∈ HalfRow) :
    (HNNExtension.of (HNNExtension.of w : GamZero) : GamOne) ∈ LSub := by
  rw [halfRow_eq_closure] at hw
  refine Subgroup.closure_induction
    (p := fun z _ => (HNNExtension.of (HNNExtension.of z : GamZero) : GamOne) ∈ LSub)
    ?_ ?_ ?_ ?_ hw
  · rintro _ ⟨i, hi, rfl⟩
    have hi' : (0 : ℤ) ≤ i := hi
    have hcast : ((i.toNat : ℕ) : ℤ) = i := Int.toNat_of_nonneg hi'
    have h := of_of_row_mem_LSub i.toNat
    rwa [hcast] at h
  · rw [map_one, map_one]
    exact Subgroup.one_mem _
  · intro y z _ _ hy hz
    rw [map_mul, map_mul]
    exact Subgroup.mul_mem _ hy hz
  · intro y _ hy
    rw [map_inv, map_inv]
    exact Subgroup.inv_mem _ hy

/-- **The generation half.**  `⟨HalfRow, t₀⟩` is carried into `⟨b, t₀, t₁⟩`. -/
theorem gen_ZSub : ∀ x ∈ ZSub, (HNNExtension.of x : GamOne) ∈ LSub := by
  intro x hx
  have hx' : x ∈ Subgroup.closure (HNNDescent.genSet xiTop HalfRow) := hx
  refine Subgroup.closure_induction
    (p := fun z _ => (HNNExtension.of z : GamOne) ∈ LSub) ?_ ?_ ?_ ?_ hx'
  · intro y hy
    have hy' : y ∈ ((HalfRow.map (HNNExtension.of : F₀ →* GamZero) : Set GamZero) ∪
        {(HNNExtension.t : GamZero)}) := hy
    rcases hy' with hy' | hy'
    · obtain ⟨w, hw, rfl⟩ := hy'
      exact of_of_mem_LSub_of_mem_halfRow hw
    · rw [Set.mem_singleton_iff] at hy'
      subst hy'
      exact of_t_mem_LSub
  · rw [map_one]
    exact Subgroup.one_mem _
  · intro y z _ _ hy hz
    rw [map_mul]
    exact Subgroup.mul_mem _ hy hz
  · intro y _ hy
    rw [map_inv]
    exact Subgroup.inv_mem _ hy

/-! ## 7.  Example 3.7 -/

/-- The outer descent: `⟨HalfRow, t₀⟩` is benign in `Γ₀`, with a torsion-free
witness. -/
def zSubWitness : TorsionFreeBenignWitness ZSub := by
  letI : Group.IsFinitelyPresented GamZero := isFinitelyPresented_gamZero
  letI : Group.FG ↥Acopy := fg_Acopy
  exact stableWitness xiOneA torsionFree_gamZero stable_xiOneA seedSet_finite
    seedSet_subset gen_ZSub

theorem benignTF_ZSub : BenignTF ZSub := ⟨zSubWitness⟩

theorem comap_ZSub : ZSub.comap (HNNExtension.of : F₀ →* GamZero) = HalfRow := by
  refine Subgroup.ext fun x => ?_
  constructor
  · intro hx
    exact mem_halfRow_of_of_mem_ZSub (Subgroup.mem_comap.mp hx)
  · intro hx
    exact Subgroup.mem_comap.mpr (of_mem_ZSub hx)

/-- `F₀` is its own torsion-free finitely presented overgroup. -/
def f0Overgroup : TorsionFreeFPOvergroup F₀ where
  K := F₀
  torsionFree := IsPowerTorsionFree.of_isMulTorsionFree
  emb := MonoidHom.id F₀
  emb_injective := fun _ _ h => h

/-- **Higman's Example 3.7: the half row `⟨bᵢ : i ≥ 0⟩` is benign**, with a
torsion-free witness. -/
theorem benignTF_halfRow : BenignTF HalfRow := by
  have h := BenignTF.comap f0Overgroup (HNNExtension.of : F₀ →* GamZero) benignTF_ZSub
  rwa [comap_ZSub] at h

/-! ## 8.  The strictly positive half row -/

/-- Conjugation by `c`, as an automorphism of `F₀`.  It moves the row down by
one, so it carries the strictly positive half row onto the half row. -/
def conjC : F₀ ≃* F₀ where
  toFun x := c * x * c⁻¹
  invFun x := c⁻¹ * x * c
  left_inv x := by
    show c⁻¹ * (c * x * c⁻¹) * c = x
    group
  right_inv x := by
    show c * (c⁻¹ * x * c) * c⁻¹ = x
    group
  map_mul' x y := by
    show c * (x * y) * c⁻¹ = c * x * c⁻¹ * (c * y * c⁻¹)
    group

/-- **The strictly positive half row**, `⟨bᵢ : i > 0⟩`. -/
def PosHalfRow : Subgroup F₀ := Subgroup.closure ((fun i : ℤ => row i) '' {i : ℤ | 0 < i})

theorem conj_mem_posHalfRow {y : F₀} (hy : y ∈ HalfRow) : c⁻¹ * y * c ∈ PosHalfRow := by
  rw [halfRow_eq_closure] at hy
  refine Subgroup.closure_induction (p := fun z _ => c⁻¹ * z * c ∈ PosHalfRow) ?_ ?_ ?_ ?_ hy
  · rintro _ ⟨i, hi, rfl⟩
    have hi' : (0 : ℤ) ≤ i := hi
    have hstep : c⁻¹ * row i * c = row (i + 1) := by
      have h := conj_row' 1 i
      simp only [zpow_neg, zpow_one] at h
      exact h
    rw [hstep]
    exact Subgroup.subset_closure ⟨i + 1, show (0 : ℤ) < i + 1 by omega, rfl⟩
  · have h1 : c⁻¹ * (1 : F₀) * c = 1 := by group
    rw [h1]
    exact Subgroup.one_mem _
  · intro u v _ _ hu hv
    have hmul : c⁻¹ * (u * v) * c = (c⁻¹ * u * c) * (c⁻¹ * v * c) := by group
    rw [hmul]
    exact Subgroup.mul_mem _ hu hv
  · intro u _ hu
    have hinv : c⁻¹ * u⁻¹ * c = (c⁻¹ * u * c)⁻¹ := by group
    rw [hinv]
    exact Subgroup.inv_mem _ hu

theorem posHalfRow_eq_comap : PosHalfRow = HalfRow.comap conjC.toMonoidHom := by
  refine le_antisymm ?_ ?_
  · refine (Subgroup.closure_le _).mpr ?_
    rintro _ ⟨i, hi, rfl⟩
    have hi' : (0 : ℤ) < i := hi
    show row i ∈ HalfRow.comap conjC.toMonoidHom
    refine Subgroup.mem_comap.mpr ?_
    have hconj : conjC.toMonoidHom (row i) = row (i - 1) := by
      show c * row i * c⁻¹ = row (i - 1)
      have h := conj_row 1 i
      simp only [zpow_neg, zpow_one] at h
      exact h
    rw [hconj]
    exact row_mem_halfRow (by omega)
  · intro x hx
    have hx' : c * x * c⁻¹ ∈ HalfRow := Subgroup.mem_comap.mp hx
    have h := conj_mem_posHalfRow hx'
    have heq : c⁻¹ * (c * x * c⁻¹) * c = x := by group
    rwa [heq] at h

/-- **The strictly positive half row is benign**, with a torsion-free
witness. -/
theorem benignTF_posHalfRow : BenignTF PosHalfRow := by
  rw [posHalfRow_eq_comap]
  exact BenignTF.congr conjC benignTF_halfRow

/-- The subgroup of `FreeGroup ℤ` the operation `π` uses codes the strictly
positive half row. -/
theorem map_piV_basisHom : Agree.piV.map basisHom = PosHalfRow := by
  unfold Agree.piV PosHalfRow
  rw [MonoidHom.map_closure]
  congr 1
  refine Set.ext fun x => ?_
  constructor
  · rintro ⟨_, ⟨i, hi, rfl⟩, rfl⟩
    have hi' : ¬ i ≤ 0 := hi
    exact ⟨i, show (0 : ℤ) < i from not_le.mp hi', (basisHom_of i).symm⟩
  · rintro ⟨i, hi, rfl⟩
    have hi' : (0 : ℤ) < i := hi
    exact ⟨FreeGroup.of i, ⟨i, show ¬ i ≤ 0 from not_le.mpr hi', rfl⟩, basisHom_of i⟩

end Row

/-! ## 9.  From `⟨b, c⟩` to `⟨a, b, c⟩` -/

/-- The inclusion of the rank-two free group in the rank-three one. -/
def inclHom : Row.F₀ →* Conj.F₃ :=
  FreeGroup.lift (fun i : Fin 2 => if i = 0 then Conj.b else Conj.c)

@[simp] theorem inclHom_b : inclHom Row.b = Conj.b := by
  unfold inclHom Row.b
  rw [FreeGroup.lift_apply_of]
  simp

@[simp] theorem inclHom_c : inclHom Row.c = Conj.c := by
  unfold inclHom Row.c
  rw [FreeGroup.lift_apply_of]
  simp

theorem retract_comp_inclHom : Seq.retract.comp inclHom = MonoidHom.id Row.F₀ := by
  refine FreeGroup.ext_hom _ _ fun i => ?_
  fin_cases i
  · show Seq.retract (inclHom Row.b) = Row.b
    rw [inclHom_b, Seq.retract_b]
  · show Seq.retract (inclHom Row.c) = Row.c
    rw [inclHom_c, Seq.retract_c]

theorem inclHom_injective : Function.Injective inclHom := by
  have h : Function.LeftInverse Seq.retract inclHom := by
    intro x
    exact congrArg (fun f : Row.F₀ →* Row.F₀ => f x) retract_comp_inclHom
  exact h.injective

/-- **The row coding factors through the inclusion.** -/
theorem inclHom_comp_basisHom : inclHom.comp Row.basisHom = Seq.rowHom := by
  refine FreeGroup.ext_hom _ _ fun i => ?_
  show inclHom (Row.basisHom (FreeGroup.of i)) = Seq.rowHom (FreeGroup.of i)
  rw [Row.basisHom_of, Seq.rowHom_of]
  unfold Row.row Seq.rowElt
  rw [map_mul, map_mul, map_zpow, map_zpow, inclHom_b, inclHom_c]

/-- **The transfer lemma: a row subgroup of `F₃` is benign as soon as the
subgroup of `F₀` it codes is.**  Nothing about `V` is used. -/
theorem benignTF_rowSub_of_benignTF_map {V : Subgroup (FreeGroup ℤ)}
    (h : BenignTF (V.map Row.basisHom)) : BenignTF (Agree.rowSub V) := by
  have hmap : BenignTF ((V.map Row.basisHom).map inclHom) :=
    BenignTF.mapEmb IsPowerTorsionFree.of_isMulTorsionFree h inclHom inclHom_injective
  rw [Subgroup.map_map, inclHom_comp_basisHom] at hmap
  exact hmap

/-! ## 10.  The three leaves -/

/-- **`Agree.AgreeInputs.half`, discharged**: the positive half-row of `F₃` is
benign with a torsion-free witness.  This is Higman's Example 3.7 carried along
the inclusion `⟨b, c⟩ ↪ ⟨a, b, c⟩`. -/
theorem benignTF_rowSub_piV : BenignTF (Agree.rowSub Agree.piV) := by
  refine benignTF_rowSub_of_benignTF_map ?_
  rw [Row.map_piV_basisHom]
  exact Row.benignTF_posHalfRow

/-- **The `ζ` and `θ` leaves, with `F₃` removed.**  For any coordinate
predicate, benignness of the row subgroup cut out by the deletion kernel is a
statement about `⟨b, c⟩` alone. -/
theorem benignTF_rowSub_ker_killOn (p : ℤ → Prop) [DecidablePred p]
    (h : BenignTF ((MonoidHom.ker (Split.killOn p)).map Row.basisHom)) :
    BenignTF (Agree.rowSub (MonoidHom.ker (Split.killOn p))) :=
  benignTF_rowSub_of_benignTF_map h

/-- **The `ζ` leaf, with `F₃` removed.**  `Agree.zetaV` is the deletion kernel
at `p = (· ≠ 0)`, so this is one instance of the previous statement. -/
theorem benignTF_rowSub_zetaV
    (h : BenignTF (Agree.zetaV.map Row.basisHom)) :
    BenignTF (Agree.rowSub Agree.zetaV) :=
  benignTF_rowSub_of_benignTF_map h

/-- **The `θ` leaf, with `F₃` removed** --- the row input of
`Higman.Seq.benignTF_ASub_thetaOp_of_lanes`. -/
theorem benignTF_rowSub_ker_killOn_evenIdx
    (h : BenignTF ((MonoidHom.ker (Split.killOn Seq.evenIdx)).map Row.basisHom)) :
    BenignTF (Agree.rowSub (MonoidHom.ker (Split.killOn Seq.evenIdx))) :=
  benignTF_rowSub_ker_killOn Seq.evenIdx h

/-- **The agreement inputs, with Example 3.7 gone.**  What `ζ` and `π` cost is
now the normal closure of `b` in the row, and the `ω` residue. -/
theorem agreeInputs_of_zeta (hzeta : BenignTF (Agree.rowSub Agree.zetaV))
    (k : Omega.OmegaInput) : Agree.AgreeInputs :=
  Omega.agreeInputs_of benignTF_rowSub_piV hzeta k

end

end Higman
end GroupApproximation
