import GroupApproximation.Higman.BenignClosure
import GroupApproximation.Algebra.HNNFinitePresentation
import GroupApproximation.Algebra.HNNTorsionFree
import Mathlib.GroupTheory.FreeGroup.Basic

/-!
# The row subgroup `⟨bᵢ : i ∈ ℤ⟩` is benign

This is Higman's first concrete benign subgroup --- Example 3.5 in the modern
write-up (Mikaelian, arXiv:1908.10153), and the base case of every later one.

Let `F₀ = ⟨b, c⟩` be free of rank two and put `bᵢ = c⁻ⁱ b cⁱ`.  The subgroup

    Row = ⟨bᵢ : i ∈ ℤ⟩

is free of countably infinite rank, so it is certainly not finitely
generated; it is nevertheless benign, and the witness is one line of group
theory:

* let `σ` be the automorphism of `F₀` with `σ b = b¹ = c⁻¹bc` and `σ c = c`;
* let `Γ = F₀ ∗_σ t` be the corresponding HNN extension, which is an ascending
  --- in fact bijective --- one, so both associated subgroups are the whole
  of `F₀`, and `Γ` is finitely presented;
* let `L = ⟨b, t⟩ ≤ Γ`, which is generated by two elements.

Then `F₀ ∩ L = Row`.  One inclusion is `tⁱ b t⁻ⁱ = bᵢ`.  The other is the
"collecting" process: every element of `⟨b, t⟩` is a product of conjugates
`t^k b^{±1} t^{-k} = bₖ^{±1}` followed by a power of `t`, because `Row` is
normalized by `t`; and an element of `Γ` that lies in `F₀` has stable-letter
length zero, so that power of `t` is trivial.

The stable-letter grading is `HNNTorsionFree.lengthHom`, already in the
repository; the finite presentation of `Γ` is
`HNNFinitePresentation.isFinitelyPresented_hnnExtension`.
-/

namespace GroupApproximation
namespace Higman
namespace Row

open HNNExtension

/-- The free group of rank two. -/
abbrev F₀ : Type := FreeGroup (Fin 2)

/-- The first generator. -/
def b : F₀ := FreeGroup.of 0

/-- The second generator. -/
def c : F₀ := FreeGroup.of 1

/-- The `i`-th row element `bᵢ = c⁻ⁱ b cⁱ`. -/
def row (i : ℤ) : F₀ := c ^ (-i) * b * c ^ i

@[simp] theorem row_zero : row 0 = b := by
  unfold row
  simp

set_option linter.dupNamespace false in
/-- The row subgroup. -/
def Row : Subgroup F₀ := Subgroup.closure (Set.range row)

theorem row_mem (i : ℤ) : row i ∈ Row :=
  Subgroup.subset_closure ⟨i, rfl⟩

/-! ## 1.  The shift automorphism -/

/-- The endomorphism `b ↦ c⁻¹bc`, `c ↦ c`. -/
def shiftHom : F₀ →* F₀ :=
  FreeGroup.lift (fun i : Fin 2 => if i = 0 then c⁻¹ * b * c else c)

/-- Its inverse, `b ↦ cbc⁻¹`, `c ↦ c`. -/
def shiftInv : F₀ →* F₀ :=
  FreeGroup.lift (fun i : Fin 2 => if i = 0 then c * b * c⁻¹ else c)

@[simp] theorem shiftHom_b : shiftHom b = c⁻¹ * b * c := by
  unfold shiftHom b
  rw [FreeGroup.lift_apply_of]
  simp

@[simp] theorem shiftHom_c : shiftHom c = c := by
  unfold shiftHom c
  rw [FreeGroup.lift_apply_of]
  simp

@[simp] theorem shiftInv_b : shiftInv b = c * b * c⁻¹ := by
  unfold shiftInv b
  rw [FreeGroup.lift_apply_of]
  simp

@[simp] theorem shiftInv_c : shiftInv c = c := by
  unfold shiftInv c
  rw [FreeGroup.lift_apply_of]
  simp

theorem shiftInv_comp_shiftHom : shiftInv.comp shiftHom = MonoidHom.id F₀ := by
  refine FreeGroup.ext_hom _ _ fun i => ?_
  fin_cases i
  · show shiftInv (shiftHom b) = b
    rw [shiftHom_b, map_mul, map_mul, map_inv, shiftInv_b, shiftInv_c]
    group
  · show shiftInv (shiftHom c) = c
    rw [shiftHom_c, shiftInv_c]

theorem shiftHom_comp_shiftInv : shiftHom.comp shiftInv = MonoidHom.id F₀ := by
  refine FreeGroup.ext_hom _ _ fun i => ?_
  fin_cases i
  · show shiftHom (shiftInv b) = b
    rw [shiftInv_b, map_mul, map_mul, map_inv, shiftHom_b, shiftHom_c]
    group
  · show shiftHom (shiftInv c) = c
    rw [shiftInv_c, shiftHom_c]

/-- The shift, as an automorphism. -/
def shift : F₀ ≃* F₀ where
  toFun := shiftHom
  invFun := shiftInv
  left_inv x := congrArg (fun f : F₀ →* F₀ => f x) shiftInv_comp_shiftHom
  right_inv x := congrArg (fun f : F₀ →* F₀ => f x) shiftHom_comp_shiftInv
  map_mul' := map_mul _

@[simp] theorem shift_b : shift b = c⁻¹ * b * c := shiftHom_b

@[simp] theorem shift_c : shift c = c := shiftHom_c

/-- The shift moves the row along. -/
theorem shift_row (i : ℤ) : shift (row i) = row (i + 1) := by
  unfold row
  rw [map_mul, map_mul, map_zpow, map_zpow, shift_b, shift_c]
  simp only [zpow_neg, zpow_add, zpow_one]
  group

/-! ## 2.  The extension -/

/-- The shift, transported to the top subgroup. -/
def shiftTop : ↥(⊤ : Subgroup F₀) ≃* ↥(⊤ : Subgroup F₀) :=
  (Subgroup.topEquiv).trans (shift.trans (Subgroup.topEquiv).symm)

theorem coe_shiftTop (x : ↥(⊤ : Subgroup F₀)) :
    ((shiftTop x : ↥(⊤ : Subgroup F₀)) : F₀) = shift (x : F₀) := rfl

/-- The ascending HNN extension along the shift. -/
abbrev Gam : Type := HNNExtension F₀ ⊤ ⊤ shiftTop

theorem conj_of (x : F₀) :
    (t : Gam) * of x * (t : Gam)⁻¹ = of (shift x) := by
  have h := HNNExtension.equiv_eq_conj (φ := shiftTop) ⟨x, Subgroup.mem_top x⟩
  rw [coe_shiftTop] at h
  exact h.symm

theorem isFinitelyPresented_gam : Group.IsFinitelyPresented Gam := by
  letI : Group.FG ↥(⊤ : Subgroup F₀) :=
    Group.fg_of_surjective (f := (Subgroup.topEquiv (G := F₀)).symm.toMonoidHom)
      (Subgroup.topEquiv (G := F₀)).symm.surjective
  exact HNNFinitePresentation.isFinitelyPresented_hnnExtension shiftTop

/-- The finitely generated subgroup that cuts the row out. -/
def Lsub : Subgroup Gam := Subgroup.closure {(of b : Gam), (t : Gam)}

theorem Lsub_fg : Lsub.FG := by
  refine (Subgroup.fg_iff _).mpr ⟨{(of b : Gam), (t : Gam)}, rfl, ?_⟩
  exact (Set.finite_singleton _).insert _

/-! ## 3.  The row is what `L` cuts out -/

theorem of_row_mem_Lsub (i : ℤ) : (of (row i) : Gam) ∈ Lsub := by
  induction i using Int.induction_on with
  | zero =>
      rw [row_zero]
      exact Subgroup.subset_closure (Set.mem_insert _ _)
  | succ n ih =>
      have hstep : (of (row ((n : ℤ) + 1)) : Gam)
          = (t : Gam) * of (row (n : ℤ)) * (t : Gam)⁻¹ := by
        rw [conj_of, shift_row]
      rw [hstep]
      have ht : (t : Gam) ∈ Lsub :=
        Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
      exact Subgroup.mul_mem _ (Subgroup.mul_mem _ ht ih) (Subgroup.inv_mem _ ht)
  | pred n ih =>
      have hstep : (of (row (-(n : ℤ) - 1)) : Gam)
          = (t : Gam)⁻¹ * of (row (-(n : ℤ))) * (t : Gam) := by
        have h := conj_of (row (-(n : ℤ) - 1))
        rw [shift_row] at h
        have h' : (-(n : ℤ) - 1) + 1 = -(n : ℤ) := by ring
        rw [h'] at h
        rw [← h]
        group
      rw [hstep]
      have ht : (t : Gam) ∈ Lsub :=
        Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
      exact Subgroup.mul_mem _ (Subgroup.mul_mem _ (Subgroup.inv_mem _ ht) ih) ht

theorem map_Row_le_Lsub : Row.map (of : F₀ →* Gam) ≤ Lsub := by
  rintro _ ⟨x, hx, rfl⟩
  refine Subgroup.closure_induction (p := fun z _ => (of z : Gam) ∈ Lsub) ?_ ?_ ?_ ?_ hx
  · rintro _ ⟨i, rfl⟩
    exact of_row_mem_Lsub i
  · rw [map_one]
    exact Subgroup.one_mem _
  · intro y z _ _ hy hz
    rw [map_mul]
    exact Subgroup.mul_mem _ hy hz
  · intro y _ hy
    rw [map_inv]
    exact Subgroup.inv_mem _ hy

/-- The image of the row is normalized by the stable letter. -/
theorem conj_map_Row (x : F₀) (hx : x ∈ Row) :
    (t : Gam) * of x * (t : Gam)⁻¹ ∈ Row.map (of : F₀ →* Gam) := by
  refine Subgroup.closure_induction
    (p := fun z _ => (t : Gam) * of z * (t : Gam)⁻¹ ∈ Row.map (of : F₀ →* Gam))
    ?_ ?_ ?_ ?_ hx
  · rintro _ ⟨i, rfl⟩
    rw [conj_of, shift_row]
    exact ⟨row (i + 1), row_mem _, rfl⟩
  · rw [map_one, mul_one, mul_inv_cancel]
    exact Subgroup.one_mem _
  · intro y z _ _ hy hz
    have hsplit : (t : Gam) * of (y * z) * (t : Gam)⁻¹
        = ((t : Gam) * of y * (t : Gam)⁻¹) * ((t : Gam) * of z * (t : Gam)⁻¹) := by
      rw [map_mul]
      group
    rw [hsplit]
    exact Subgroup.mul_mem _ hy hz
  · intro y _ hy
    have hsplit : (t : Gam) * of y⁻¹ * (t : Gam)⁻¹
        = ((t : Gam) * of y * (t : Gam)⁻¹)⁻¹ := by
      rw [map_inv]
      group
    rw [hsplit]
    exact Subgroup.inv_mem _ hy

theorem conj_zpow_map_Row (k : ℤ) (x : F₀) (hx : x ∈ Row) :
    (t : Gam) ^ k * of x * ((t : Gam) ^ k)⁻¹ ∈ Row.map (of : F₀ →* Gam) := by
  induction k using Int.induction_on with
  | zero =>
      rw [zpow_zero, one_mul, inv_one, mul_one]
      exact ⟨x, hx, rfl⟩
  | succ n ih =>
      obtain ⟨y, hy, hyeq⟩ := ih
      have hstep : (t : Gam) ^ ((n : ℤ) + 1) * of x * ((t : Gam) ^ ((n : ℤ) + 1))⁻¹
          = (t : Gam) * ((t : Gam) ^ (n : ℤ) * of x * ((t : Gam) ^ (n : ℤ))⁻¹) *
              (t : Gam)⁻¹ := by
        rw [zpow_add, zpow_one]
        group
      rw [hstep, ← hyeq]
      exact conj_map_Row y hy
  | pred n ih =>
      obtain ⟨y, hy, hyeq⟩ := ih
      have hstep : (t : Gam) ^ (-(n : ℤ) - 1) * of x * ((t : Gam) ^ (-(n : ℤ) - 1))⁻¹
          = (t : Gam)⁻¹ * ((t : Gam) ^ (-(n : ℤ)) * of x * ((t : Gam) ^ (-(n : ℤ)))⁻¹) *
              (t : Gam) := by
        rw [zpow_sub, zpow_one]
        group
      rw [hstep, ← hyeq]
      obtain ⟨z, hz, hzeq⟩ := conj_map_Row y hy
      refine ⟨shift.symm y, ?_, ?_⟩
      · have hyrow : shift (shift.symm y) = y := shift.apply_symm_apply y
        have : shift.symm y ∈ Row := by
          refine Subgroup.closure_induction
            (p := fun z _ => shift.symm z ∈ Row) ?_ ?_ ?_ ?_ hy
          · rintro _ ⟨i, rfl⟩
            have : shift.symm (row i) = row (i - 1) := by
              refine shift.injective ?_
              rw [shift.apply_symm_apply, shift_row]
              congr 1
              ring
            rw [this]
            exact row_mem _
          · rw [map_one]
            exact Subgroup.one_mem _
          · intro u v _ _ hu hv
            rw [map_mul]
            exact Subgroup.mul_mem _ hu hv
          · intro u _ hu
            rw [map_inv]
            exact Subgroup.inv_mem _ hu
        exact this
      · have h := conj_of (shift.symm y)
        rw [shift.apply_symm_apply] at h
        rw [← h]
        group

end Row
end Higman
end GroupApproximation

namespace GroupApproximation
namespace Higman
namespace Row

open HNNExtension

/-! ## 4.  The collecting process -/

/-- Elements of the shape "row element times a power of the stable letter".
This is where the collecting process happens: the set is a subgroup because
the row is normalized by the stable letter. -/
def NormalSub : Subgroup Gam where
  carrier := {w : Gam | ∃ u ∈ Row.map (of : F₀ →* Gam), ∃ k : ℤ,
    w = u * (t : Gam) ^ k}
  one_mem' := by
    refine ⟨1, Subgroup.one_mem _, 0, ?_⟩
    rw [zpow_zero, mul_one]
  mul_mem' := by
    rintro x y ⟨u, hu, k, rfl⟩ ⟨v, hv, m, rfl⟩
    obtain ⟨v₀, hv₀, rfl⟩ := hv
    refine ⟨u * ((t : Gam) ^ k * of v₀ * ((t : Gam) ^ k)⁻¹),
      Subgroup.mul_mem _ hu (conj_zpow_map_Row k v₀ hv₀), k + m, ?_⟩
    rw [zpow_add]
    group
  inv_mem' := by
    rintro x ⟨u, hu, k, rfl⟩
    obtain ⟨u₀, hu₀, rfl⟩ := hu
    refine ⟨(t : Gam) ^ (-k) * of u₀⁻¹ * ((t : Gam) ^ (-k))⁻¹, ?_, -k, ?_⟩
    · exact conj_zpow_map_Row (-k) u₀⁻¹ (Subgroup.inv_mem _ hu₀)
    · rw [map_inv]
      group

theorem Lsub_le_normalSub : Lsub ≤ NormalSub := by
  refine (Subgroup.closure_le _).mpr ?_
  intro x hx
  rcases hx with rfl | hx
  · refine ⟨of b, ⟨b, ?_, rfl⟩, 0, ?_⟩
    · rw [← row_zero]
      exact row_mem 0
    · rw [zpow_zero, mul_one]
  · rw [Set.mem_singleton_iff] at hx
    subst hx
    refine ⟨1, Subgroup.one_mem _, 1, ?_⟩
    rw [zpow_one, one_mul]

/-! ## 5.  The intersection -/

theorem comap_Lsub : Lsub.comap (of : F₀ →* Gam) = Row := by
  refine le_antisymm ?_ ?_
  · intro x hx
    have hx' : (of x : Gam) ∈ Lsub := Subgroup.mem_comap.mp hx
    obtain ⟨u, hu, k, hk⟩ := Lsub_le_normalSub hx'
    obtain ⟨y, hy, rfl⟩ := hu
    have hlen := congrArg (HNNTorsionFree.lengthHom shiftTop) hk
    rw [map_mul, map_zpow, HNNTorsionFree.lengthHom_of,
      HNNTorsionFree.lengthHom_of, HNNTorsionFree.lengthHom_t, one_mul] at hlen
    have hk0 : k = 0 := by
      have h1 : ((Multiplicative.ofAdd (1 : ℤ)) ^ k) = 1 := hlen.symm
      have h2 : ((Multiplicative.ofAdd (1 : ℤ)) ^ k) = Multiplicative.ofAdd k := by
        rw [← ofAdd_zsmul]
        congr 1
        simp
      rw [h2] at h1
      have h3 := congrArg Multiplicative.toAdd h1
      simpa using h3
    rw [hk0, zpow_zero, mul_one] at hk
    have hxy : x = y := of_injective (φ := shiftTop) hk
    rw [hxy]
    exact hy
  · intro x hx
    refine Subgroup.mem_comap.mpr ?_
    exact map_Row_le_Lsub ⟨x, hx, rfl⟩

/-! ## 6.  The witness -/

/-- **Higman's Example 3.5: the row subgroup is benign.** -/
noncomputable def rowWitness : BenignWitness Row where
  K := Gam
  fp := isFinitelyPresented_gam
  emb := of
  emb_injective := of_injective (φ := shiftTop)
  L := Lsub
  L_fg := Lsub_fg
  comap_eq := comap_Lsub

theorem benign_row : Benign Row := ⟨rowWitness⟩

end Row
end Higman
end GroupApproximation
