import GroupApproximation.Higman.SwapWitnessTower
import GroupApproximation.Higman.OmegaClosure

/-!
# Route D: what the `ω` lane's carrier supplies, and the one thing it does not

`Higman.SwapWitnessTower` reduces Higman's operation `τ` to `Seq.SwapCarrier`:
a finitely generated `L` inside a finitely presented torsion-free overgroup of
`F₃`, containing every coded conjugate `a_f`, together with an automorphism of
`L` performing `f ↦ τ f` on them.  The natural place to look for such an `L` is
`Higman.OmegaClosure`, whose `Omega.benignTF_ASub_univ` says that `A_E`, the
subgroup generated by *all* the `a_f`, is benign — and a benign witness is
exactly a finitely generated subgroup of a finitely presented group.

This file answers the question that raises, in both directions.

## 1.  What it gives: everything except the automorphism

`Carrier` is `Seq.SwapCarrier` with the automorphism deleted, and
`nonempty_carrier_of_omegaInput` builds one **from `Omega.OmegaInput` alone**.
The membership clause is not an extra hypothesis: `comap_eq` says
`F₃ ∩ L = A_E`, and every `a_f` lies in `A_E`.  So of the six things
`SwapCarrier` asks for, five are already available the moment the `ω` leaf
lands, and the residual is exactly

    psi : ↥L ≃* ↥L   with   psi (a_f) = a_{τ f} .

`Carrier.toSwapCarrier` closes the gap, and
`benignTF_ASub_tauOp_of_carrier_aut` states `τ` in that form.

## 2.  What it does not give, and why no benign witness can

`BenignTF` is `Nonempty (TorsionFreeBenignWitness _)`, and the *only* property
its `L` is required to have is `L.comap emb = A_E`.  Nothing in that
determines `L`, so no automorphism can be extracted from the interface: the
question "does the `L` of `benignTF_ASub_univ` carry the permutation?" has no
answer until a *particular* `L` is built.  That is a statement about the
interface, not a defect in it.

What can be said, and is proved here, is sharper and is a genuine obstruction
to the carriers this repository actually builds.  Every finitely generated
carrier for a coded family in `Higman/` — `Higman.Row.Lsub = ⟨b, t⟩`, and the
two-generated carrier of Higman's base case `S` — has the shape *"the coded
generators, plus one element implementing the shift"*.  For such a carrier the
answer is **no**:

* `Carrier.implements_map` — if `s` implements an index map `ν` and `psi`
  performs `τ`, then `psi s` implements `τ ∘ ν ∘ τ`;
* `tauSeq_shiftSeq_tauSeq_ne_shiftSeq` — `τ σ τ ≠ σ`, witnessed at
  `f = single 0 1`, where `τ σ τ f = single 2 1` and `σ f = single 1 1`;
* `Carrier.psi_moves_shift` — therefore `psi s` does **not** implement the
  shift, so a carrier closed under `psi` must contain an element implementing
  `τ σ τ` as well, and cannot be generated by the coded family together with a
  single shift.

Concretely: the group of index maps a shift-carrier realizes is the
translations, and `τ` conjugates the shift out of that group.  A `τ`-carrier
has to realize the whole of `⟨σ, τ⟩` — the finitary permutations of `ℤ`
extended by the shift.

## 3.  Why that is not the same obstruction as the one in `SwapWitnessTower`

`Seq.not_tau_of_endomorphism` and the design constraint recorded on
`Seq.WindowApparatus` both bite only when the map preserves `emb F₃`: they turn
on `emb F₃ ∩ C(emb a) = emb ⟨a⟩`, which needs `emb b` and `emb c` to be
present.  **`SwapCarrier` asks for none of that.**  `psi` is an automorphism of
`L`, not of `K`; `L` is not required to contain `emb b` or `emb c`, and no
condition is placed on `L ∩ F₃` at all.  So inside `L` one *may* impose that
the row letters commute modulo the centralizer of `a` — Higman's Lemma 4.2 —
without collapsing anything, because the elements that would be identified are
not in `L`.

That is the sense in which route D localizes the apparatus rather than avoiding
it: what Higman builds as a global overgroup of `F₃` is needed here only inside
one finitely generated subgroup, where the collapse argument has no purchase.
-/

namespace GroupApproximation
namespace Higman
namespace Seq

open GroupApproximation.Higman.Conj

/-! ## 1.  The carrier, without its automorphism -/

/-- **`Seq.SwapCarrier` with the automorphism deleted.**  Everything a benign
witness for `A_E` already supplies. -/
structure Carrier where
  /-- The finitely presented overgroup. -/
  K : Type
  /-- Its group structure. -/
  [group : Group K]
  /-- It is finitely presented. -/
  [fp : Group.IsFinitelyPresented K]
  /-- It is torsion-free. -/
  torsionFree : IsPowerTorsionFree K
  /-- `F₃` sits inside it. -/
  emb : F₃ →* K
  /-- ... as a subgroup. -/
  emb_injective : Function.Injective emb
  /-- The carrier. -/
  L : Subgroup K
  /-- ... which is finitely generated. -/
  L_fg : L.FG
  /-- It contains every coded conjugate. -/
  mem_L : ∀ f : E, emb (aElt f) ∈ L

attribute [instance] Carrier.group Carrier.fp

/-- The coded conjugate, read inside the carrier.  Naming it keeps the
dependent pair out of every statement below. -/
noncomputable def Carrier.gen (c : Carrier) (f : E) : ↥c.L :=
  ⟨c.emb (aElt f), c.mem_L f⟩

theorem Carrier.coe_gen (c : Carrier) (f : E) :
    (c.gen f : c.K) = c.emb (aElt f) := rfl

/-- **The coded conjugates are distinct in the carrier.** -/
theorem Carrier.gen_injective (c : Carrier) : Function.Injective c.gen := by
  intro f g h
  have h' : c.emb (aElt f) = c.emb (aElt g) := congrArg Subtype.val h
  exact aElt_injective (c.emb_injective h')

/-! ## 2.  The carrier is what the `ω` leaf already produces -/

/-- **A benign witness for `A_E` is a carrier.**  The membership clause is
`comap_eq` unwound: `F₃ ∩ L = A_E`, and `a_f ∈ A_E`. -/
noncomputable def Carrier.ofBenignUniv
    (u : TorsionFreeBenignWitness (ASub (Set.univ : Set E))) : Carrier where
  K := u.witness.K
  fp := u.witness.fp
  torsionFree := u.torsionFree
  emb := u.witness.emb
  emb_injective := u.witness.emb_injective
  L := u.witness.L
  L_fg := u.witness.L_fg
  mem_L := by
    intro f
    have hmem : aElt f ∈ ASub (Set.univ : Set E) :=
      Subgroup.subset_closure ⟨f, Set.mem_univ f, rfl⟩
    rw [← u.witness.comap_eq] at hmem
    exact Subgroup.mem_comap.mp hmem

theorem nonempty_carrier_of_benignTF_univ
    (h : BenignTF (ASub (Set.univ : Set E))) : Nonempty Carrier := by
  obtain ⟨u⟩ := h
  exact ⟨Carrier.ofBenignUniv u⟩

/-- **From the `ω` leaf alone.**  Five of `Seq.SwapCarrier`'s six demands are
met the moment `Omega.OmegaInput` is inhabited; only the automorphism is
left. -/
theorem nonempty_carrier_of_omegaInput (k : Omega.OmegaInput) : Nonempty Carrier :=
  nonempty_carrier_of_benignTF_univ (Omega.benignTF_ASub_univ k)

/-! ## 3.  The residual, and `τ` from it -/

/-- An automorphism of the carrier that performs the transposition on the
coded conjugates.  This is the whole of what route D still owes. -/
def Carrier.IsSwap (c : Carrier) (psi : ↥c.L ≃* ↥c.L) : Prop :=
  ∀ f : E, psi (c.gen f) = c.gen (tauSeq f)

/-- **A carrier with such an automorphism is a `Seq.SwapCarrier`.** -/
def Carrier.toSwapCarrier (c : Carrier) (psi : ↥c.L ≃* ↥c.L)
    (hswap : c.IsSwap psi) : SwapCarrier where
  K := c.K
  fp := c.fp
  torsionFree := c.torsionFree
  emb := c.emb
  emb_injective := c.emb_injective
  L := c.L
  L_fg := c.L_fg
  mem_L := c.mem_L
  psi := psi
  -- `Carrier.gen f` is the anonymous constructor `SwapCarrier.psi_apply` names,
  -- so this is `hswap` read through the coercion; `rw` would not see it, since
  -- the goal spells the pair out and `hswap` does not.
  psi_apply := fun f => congrArg Subtype.val (hswap f)

/-- **Higman's operation `τ`, from the `ω` lane's carrier plus one
automorphism.** -/
theorem benignTF_ASub_tauOp_of_carrier_aut (c : Carrier) (psi : ↥c.L ≃* ↥c.L)
    (hswap : c.IsSwap psi) (B : Set E) (h : BenignTF (ASub B)) :
    BenignTF (ASub (tauOp B)) :=
  benignTF_ASub_tauOp_of_carrier (c.toSwapCarrier psi hswap) B h

/-! ## 4.  The obstruction: a shift-carrier does not admit the automorphism -/

/-- An element of the carrier whose conjugation action moves the index of every
coded conjugate by `ν`. -/
def Carrier.Implements (c : Carrier) (s : ↥c.L) (ν : E → E) : Prop :=
  ∀ f : E, s * c.gen f * s⁻¹ = c.gen (ν f)

/-- An element implements at most one index map. -/
theorem Carrier.implements_unique (c : Carrier) {s : ↥c.L} {ν μ : E → E}
    (hν : c.Implements s ν) (hμ : c.Implements s μ) (f : E) : ν f = μ f :=
  c.gen_injective ((hν f).symm.trans (hμ f))

/-- **The transposition conjugates an implemented index map.**  If `s`
implements `ν`, then `psi s` implements `τ ∘ ν ∘ τ`.  This is the whole
mechanism of the obstruction, and it uses nothing but `tauSeq_involutive`. -/
theorem Carrier.implements_map (c : Carrier) {psi : ↥c.L ≃* ↥c.L}
    (hswap : c.IsSwap psi) {s : ↥c.L} {ν : E → E} (hs : c.Implements s ν) :
    c.Implements (psi s) (fun f => tauSeq (ν (tauSeq f))) := by
  intro f
  have h := congrArg psi (hs (tauSeq f))
  rw [map_mul, map_mul, map_inv, hswap (tauSeq f), hswap (ν (tauSeq f)),
    tauSeq_involutive] at h
  exact h

/-! ### The index calculus the obstruction needs -/

theorem shiftSeq_single (i n : ℤ) :
    shiftSeq (Finsupp.single i n) = Finsupp.single (i + 1) n := by
  refine Finsupp.ext fun j => ?_
  rw [shiftSeq_apply, Finsupp.single_apply, Finsupp.single_apply]
  by_cases h : j = i + 1
  · rw [if_pos (by omega : i = j - 1), if_pos (by omega : i + 1 = j)]
  · rw [if_neg (by omega : ¬ i = j - 1), if_neg (by omega : ¬ i + 1 = j)]

theorem tauSeq_single_of_ne (i n : ℤ) (h0 : i ≠ 0) (h1 : i ≠ 1) :
    tauSeq (Finsupp.single i n) = Finsupp.single i n := by
  refine Finsupp.ext fun j => ?_
  by_cases hj0 : j = 0
  · subst hj0
    rw [tauSeq_zero, Finsupp.single_apply, Finsupp.single_apply,
      if_neg (by omega : ¬ i = (1 : ℤ)), if_neg (by omega : ¬ i = (0 : ℤ))]
  by_cases hj1 : j = 1
  · subst hj1
    rw [tauSeq_one, Finsupp.single_apply, Finsupp.single_apply,
      if_neg (by omega : ¬ i = (0 : ℤ)), if_neg (by omega : ¬ i = (1 : ℤ))]
  · exact tauSeq_of_ne _ j hj0 hj1

/-- **The transposition does not normalize the shift.**  At `f = single 0 1`,
`τ σ τ f = single 2 1` while `σ f = single 1 1`.  This is the arithmetic the
whole obstruction rests on, and it is why `τ` cannot be carried by the same
kind of subgroup that carries `σ`. -/
theorem tauSeq_shiftSeq_tauSeq_ne_shiftSeq :
    tauSeq (shiftSeq (tauSeq (Finsupp.single (0 : ℤ) 1)))
      ≠ shiftSeq (Finsupp.single (0 : ℤ) 1) := by
  rw [tauSeq_single_zero, shiftSeq_single, shiftSeq_single,
    tauSeq_single_of_ne _ _ (by omega) (by omega)]
  intro h
  have h2 : (Finsupp.single ((1 : ℤ) + 1) (1 : ℤ)) 2
      = (Finsupp.single ((0 : ℤ) + 1) (1 : ℤ)) 2 := by rw [h]
  rw [Finsupp.single_apply, Finsupp.single_apply,
    if_pos (by omega : (1 : ℤ) + 1 = 2), if_neg (by omega : ¬ (0 : ℤ) + 1 = 2)] at h2
  exact absurd h2 (by omega)

/-- **The obstruction.**  In a carrier admitting the transposition, the image
of a shift element is *not* a shift element.  So a carrier generated by the
coded conjugates together with a single shift is never closed under such an
automorphism: `psi s` implements `τ σ τ`, which is a different index map.

Every finitely generated carrier this repository builds for a coded family has
exactly that shape, which is why none of them answers route D as it stands, and
why a `τ`-carrier must realize the whole group `⟨σ, τ⟩` of index maps rather
than the translations alone. -/
theorem Carrier.psi_moves_shift (c : Carrier) {psi : ↥c.L ≃* ↥c.L}
    (hswap : c.IsSwap psi) {s : ↥c.L} (hs : c.Implements s shiftSeq) :
    ¬ c.Implements (psi s) shiftSeq := by
  intro hcon
  exact tauSeq_shiftSeq_tauSeq_ne_shiftSeq
    (c.implements_unique (c.implements_map hswap hs) hcon (Finsupp.single (0 : ℤ) 1))

end Seq
end Higman
end GroupApproximation
