import GroupApproximation.BooneHigman.GroupRing.Semidirect
import Mathlib.RingTheory.Finiteness.Defs
import Mathlib.GroupTheory.Abelianization.Defs

/-!
# Finite generation of the split metabelian group of a module

Let `Q` be a finitely generated group and `M` a finitely generated `ℤ[Q]`-module. Then
`Affine ℤ Q M = M ⋊ Q` is a finitely generated group. It is generated by the translations by module
generators together with generators of `Q`, because conjugation by `q` is the module action of `q`
(`inr_mul_inl_mul_inr_inv`).

* `inl_mem_of_mem_span`: a subgroup containing every `inr q` and the translations by a set `S`
  contains the translations by the `ℤ[Q]`-span of `S`.
* `group_fg_affine`: `Affine ℤ Q M` is finitely generated.
* `group_fg_abelianization`: the abelianization of a finitely generated group is finitely
  generated.
-/

namespace GroupApproximation
namespace BooneHigman
namespace GroupRing

open SemidirectProduct

variable {Q : Type*} [Group Q] {M : Type*} [AddCommGroup M] [Module (MonoidAlgebra ℤ Q) M]

/-- A subgroup containing every `inr q` and the translations by `S` contains the translations by
the `ℤ[Q]`-span of `S`. -/
theorem inl_mem_of_mem_span {H : Subgroup (Affine ℤ Q M)} (hQ : ∀ q, (inr q : Affine ℤ Q M) ∈ H)
    {S : Set M} (hS : ∀ m ∈ S, (inl (Multiplicative.ofAdd m) : Affine ℤ Q M) ∈ H)
    {m : M} (hm : m ∈ Submodule.span (MonoidAlgebra ℤ Q) S) :
    (inl (Multiplicative.ofAdd m) : Affine ℤ Q M) ∈ H := by
  induction hm using Submodule.span_induction with
  | mem x hx => exact hS x hx
  | zero =>
    rw [ofAdd_zero, map_one]
    exact H.one_mem
  | add x y _ _ hx hy =>
    rw [ofAdd_add, map_mul]
    exact H.mul_mem hx hy
  | smul a x _ hx =>
    induction a using MonoidAlgebra.induction_on with
    | hM q =>
      rw [← inr_mul_inl_mul_inr_inv]
      exact H.mul_mem (H.mul_mem (hQ q) hx) (hQ q⁻¹)
    | hadd f g hf hg =>
      rw [add_smul, ofAdd_add, map_mul]
      exact H.mul_mem hf hg
    | hsmul r f hf =>
      rw [smul_assoc, ofAdd_zsmul, map_zpow]
      exact H.zpow_mem hf r

/-- **`M ⋊ Q` is finitely generated** when `Q` is a finitely generated group and `M` is a finitely
generated `ℤ[Q]`-module. -/
theorem group_fg_affine [Group.FG Q] [Module.Finite (MonoidAlgebra ℤ Q) M] :
    Group.FG (Affine ℤ Q M) := by
  obtain ⟨T, hT, hTfin⟩ := Group.fg_iff.mp ‹Group.FG Q›
  obtain ⟨S, hSfin, hS⟩ :=
    Submodule.fg_def.mp (Module.finite_def.mp ‹Module.Finite (MonoidAlgebra ℤ Q) M›)
  let gens : Set (Affine ℤ Q M) :=
    (fun m => (inl (Multiplicative.ofAdd m) : Affine ℤ Q M)) '' S ∪ inr '' T
  refine Group.fg_iff.mpr ⟨gens, ?_, (hSfin.image _).union (hTfin.image _)⟩
  refine eq_top_iff.mpr fun x _ => ?_
  have hQ : ∀ q, (inr q : Affine ℤ Q M) ∈ Subgroup.closure gens := by
    have hle : Subgroup.closure T ≤ (Subgroup.closure gens).comap inr :=
      (Subgroup.closure_le _).mpr fun t ht => Subgroup.subset_closure (Or.inr ⟨t, ht, rfl⟩)
    intro q
    have hq : q ∈ Subgroup.closure T := by
      rw [hT]
      exact Subgroup.mem_top q
    exact hle hq
  have hM : ∀ m : M, (inl (Multiplicative.ofAdd m) : Affine ℤ Q M) ∈ Subgroup.closure gens := by
    intro m
    refine inl_mem_of_mem_span hQ
      (fun m hm => Subgroup.subset_closure (Or.inl ⟨m, hm, rfl⟩)) ?_
    rw [hS]
    exact Submodule.mem_top
  have hl := hM (Multiplicative.toAdd x.left)
  rw [ofAdd_toAdd] at hl
  rw [← inl_left_mul_inr_right x]
  exact (Subgroup.closure gens).mul_mem hl (hQ x.right)

/-- The abelianization of a finitely generated group is finitely generated. -/
theorem group_fg_abelianization (G : Type*) [Group G] [Group.FG G] :
    Group.FG (Abelianization G) :=
  Group.fg_of_surjective (f := Abelianization.of) (QuotientGroup.mk'_surjective _)

end GroupRing
end BooneHigman
end GroupApproximation
