import GroupApproximation.Manuscript.SpectralPaper.MainTheorems

/-! Axiom surface for the closed endpoints of the spectral-compression paper. -/

#print axioms GroupApproximation.SpectralComponentMotion.norm_sub_le_of_clopen_projections_eq
#print axioms GroupApproximation.SpectralCompression.corona_spectral_component_motion_supremum
#print axioms GroupApproximation.SpectralCompression.corona_zero_dimensional_spectral_collapse
#print axioms GroupApproximation.FinitePerfectLamp.finitePerfectPackage
#print axioms GroupApproximation.FinitePerfectLamp.precomp_bijective_actualCorona
#print axioms GroupApproximation.FinitePerfectLamp.precomp_bijective_generalLinearGroup
#print axioms GroupApproximation.FinitePerfectLamp.precomp_bijective_profinite
#print axioms GroupApproximation.SpectralPaper.oneInvisibleRelationPackage
#print axioms GroupApproximation.SpectralPaper.a5UniversalInvisibility
#print axioms GroupApproximation.SpectralPaper.invisibleKernelTame
