import GroupApproximation.Meta.AxiomGuard
import GroupApproximation.Manuscript.SpectralPaper.MainTheorems

/-! Axiom surface for the closed endpoints of the spectral-compression paper. -/

#audit_axioms GroupApproximation.SpectralComponentMotion.norm_sub_le_of_clopen_projections_eq
#audit_axioms GroupApproximation.SpectralCompression.corona_spectral_component_motion_supremum
#audit_axioms GroupApproximation.SpectralCompression.corona_zero_dimensional_spectral_collapse
#audit_axioms GroupApproximation.FinitePerfectLamp.finitePerfectPackage
#audit_axioms GroupApproximation.FinitePerfectLamp.precomp_bijective_actualCorona
#audit_axioms GroupApproximation.FinitePerfectLamp.precomp_bijective_generalLinearGroup
#audit_axioms GroupApproximation.FinitePerfectLamp.precomp_bijective_profinite
#audit_axioms GroupApproximation.SpectralPaper.oneInvisibleRelationPackage
#audit_axioms GroupApproximation.SpectralPaper.a5UniversalInvisibility
#audit_axioms GroupApproximation.SpectralPaper.invisibleKernelTame
#audit_axioms GroupApproximation.SpectralPaper.spectralCompressionTheorem
#audit_axioms GroupApproximation.SpectralPaper.zeroDimensionalSpectralCollapseTheorem
#audit_axioms GroupApproximation.SpectralPaper.finitePerfectUniversalInvisibility
