import GroupApproximation.Manuscript.NonMFNotes.Full.Gstar.Basic
import GroupApproximation.Manuscript.NonMFNotes.Full.Gstar.VerticalCongr
import GroupApproximation.Manuscript.NonMFSentences.IntroWitnessSignSentence
import GroupApproximation.Meta.AxiomGuard

/-!
# `G_*` is the repository's vertical group `V(Γ̄, conjD)`

Manuscript `non_mf_group_notes.tex`, subsection "The heightwise abelian quotient"
(tex lines 1943--1960), and the identification used throughout `cor:notes-a5-relation`
(tex lines 2052--2073).  The repository proves the approximation properties of `G_*` for the
matrix model: `Γ̄ ≤ GL₄(ℚ)` generated by the affine matrices, with doubling
`conjD u = D u D⁻¹`, `D = diag(2,2,2,1)`, and vertical group
`Vertical conjD conjD_injective = Telescope ⋊ ℤ`.  This file identifies that group with the
literal ascending HNN extension `Gstar` of `ℤ³ ⋊ SL₃(ℤ)` along `α(v,A) = (2v,A)`.

Main declarations:

* `gammaEquiv_alpha` — the isomorphism `ℤ³ ⋊ SL₃(ℤ) ≃* Γ̄`, `(v,A) ↦ [[A,v],[0,1]]`,
  intertwines `α` with `conjD`;
* `printedVerticalEquiv` — `Vertical α ≃* Vertical conjD`;
* `gstarEquivPrintedVertical` — `Gstar ≃* Vertical α` (Mathlib HNN extension vs telescope);
* `gstarEquivVertical` — **`Gstar ≃* Vertical conjD conjD_injective`**, with
  `gstarEquivVertical_ofGamma` and `gstarEquivVertical_stableLetter`.
-/

namespace GroupApproximation.Full.NN05

open MarkedCompression ExplicitLinearModel
open Manuscript.NonMFSentences.IntroWitnessSignSentence (gammaEquiv gammaEquiv_apply)

/-- The affine matrix isomorphism `ℤ³ ⋊ SL₃(ℤ) ≃* Γ̄` intertwines the doubling
`α(v,A) = (2v,A)` with conjugation by `D = diag(2,2,2,1)`. -/
theorem gammaEquiv_alpha (g : GammaStar) :
    gammaEquiv (alphaStar g) = conjD (gammaEquiv g) := by
  apply Subtype.ext
  show ((gammaEquiv (alphaStar g) : gammaBar) : Matˣ) =
    dU * ((gammaEquiv g : gammaBar) : Matˣ) * dU⁻¹
  have hconj : ∀ u : Matˣ, dU * u * dU⁻¹ = (dU ^ (-1 : ℤ))⁻¹ * u * dU ^ (-1 : ℤ) :=
    fun u => by rw [zpow_neg_one, inv_inv]
  rw [gammaEquiv_apply, gammaEquiv_apply, hconj]
  refine (AffineHNNBase.dU_zpow_conj' (-1 : ℤ) g.right _ _ ?_).symm
  intro i
  show ((Multiplicative.toAdd (alphaStar g).left i : ℤ) : ℚ) =
    (2 : ℚ) ^ (-(-1 : ℤ)) * ((Multiplicative.toAdd g.left i : ℤ) : ℚ)
  have hw : Multiplicative.toAdd (alphaStar g).left i = 2 * Multiplicative.toAdd g.left i := by
    change (2 : ℕ) • Multiplicative.toAdd g.left i = 2 * Multiplicative.toAdd g.left i
    exact (two_nsmul _).trans (two_mul _).symm
  rw [hw, neg_neg, zpow_one, Int.cast_mul, Int.cast_two]

/-- The vertical group of `(ℤ³ ⋊ SL₃(ℤ), α)` is the vertical group of `(Γ̄, conjD)`. -/
noncomputable def printedVerticalEquiv :
    Vertical alphaStar alphaStar_injective ≃* Vertical conjD conjD_injective :=
  verticalCongr alphaStar alphaStar_injective conjD conjD_injective gammaEquiv gammaEquiv_alpha

/-- The literal ascending HNN extension is the telescope vertical group of `(Γ_*, α)`. -/
noncomputable def gstarEquivPrintedVertical : Gstar ≃* Vertical alphaStar alphaStar_injective :=
  (VerticalAscendingHNN.verticalEquivHNN alphaStar alphaStar_injective).symm

theorem gstarEquivPrintedVertical_ofGamma (g : GammaStar) :
    gstarEquivPrintedVertical (ofGamma g) = iotaVertical alphaStar alphaStar_injective g :=
  VerticalAscendingHNN.toVertical_of alphaStar alphaStar_injective g

theorem gstarEquivPrintedVertical_stableLetter :
    gstarEquivPrintedVertical stableLetter = tVertical alphaStar alphaStar_injective :=
  VerticalAscendingHNN.toVertical_t alphaStar alphaStar_injective

/-- **`G_* ≅ V(Γ̄, conjD)`.**  The ascending HNN extension of `ℤ³ ⋊ SL₃(ℤ)` along `α` is
isomorphic to the repository's vertical group `Vertical conjD conjD_injective`, sending the base
`Γ_*` to the level-zero copy of `Γ̄` and the stable letter to the stable letter. -/
noncomputable def gstarEquivVertical : Gstar ≃* Vertical conjD conjD_injective :=
  gstarEquivPrintedVertical.trans printedVerticalEquiv

theorem gstarEquivVertical_ofGamma (g : GammaStar) :
    gstarEquivVertical (ofGamma g) = iotaVertical conjD conjD_injective (gammaEquiv g) := by
  show printedVerticalEquiv (gstarEquivPrintedVertical (ofGamma g)) = _
  rw [gstarEquivPrintedVertical_ofGamma]
  exact verticalCongr_iota alphaStar alphaStar_injective conjD conjD_injective gammaEquiv
    gammaEquiv_alpha g

theorem gstarEquivVertical_stableLetter :
    gstarEquivVertical stableLetter = tVertical conjD conjD_injective := by
  show printedVerticalEquiv (gstarEquivPrintedVertical stableLetter) = _
  rw [gstarEquivPrintedVertical_stableLetter]
  exact verticalCongr_t alphaStar alphaStar_injective conjD conjD_injective gammaEquiv
    gammaEquiv_alpha

#audit_axioms gammaEquiv_alpha
#audit_axioms gstarEquivVertical
#audit_axioms gstarEquivVertical_ofGamma
#audit_axioms gstarEquivVertical_stableLetter

end GroupApproximation.Full.NN05
