import GroupApproximation.Sofic.FreeGroupResiduallyFinite

#check QuotientGroup.rightRel
#check QuotientGroup.rightRel_apply
#check Quotient.map
#check Quotient.map'
#check Quotient.sound
#check Quotient.exact
#check Finset.biUnion
#check Finset.image
#check Finset.attach
#check Set.Finite.toFinset
#check Set.Finite.subset_biUnion
#check Equiv.sumCompl
#check Fintype.equivOfCardEq
#check Subgroup.fg_iff
#check Subgroup.closure_induction
#check FreeGroup.lift_mk
#check FreeGroup.mk_toWord
#check FreeGroup.isReduced_toWord
#check List.drop
#check List.range
#check List.finRange
#check Finset.range
#check Finset.mem_image
#check List.prod_drop_succ
#check List.drop_succ_cons
#check FreeGroup.mk_cons
#check FreeGroup.mk_append
#check FreeGroup.mk_singleton
#check FreeGroup.lift_of
#check FreeGroup.lift_unique
#check FreeGroup.lift.of
#check List.drop_eq_getElem_cons
#check Equiv.Perm.mul_apply
#check Equiv.Perm.inv_apply_eq_iff_eq
