import GroupApproximation.Stability.MixedApproximation
import GroupApproximation.Leavitt.HilbertHotelModelNonMF
import Mathlib.Analysis.InnerProductSpace.SingularValues

open GroupApproximation

#check GroupApproximation.FiniteModel
#check GroupApproximation.naturalFiniteModel
#check Matrix.toEuclideanLin
#check GroupApproximation.OpAlmostRepresentation
#check GroupApproximation.HilbertHotel.Cover.Model
#print GroupApproximation.FiniteModel
#print GroupApproximation.naturalFiniteModel
#check GroupApproximation.exists_eigenvalue_mul_conjTranspose_eq_sq_opNorm
#check exists_eigenvalue_mul_conjTranspose_eq_sq_opNorm
#check Matrix.toLin_conjTranspose
#check Matrix.toLin_mul
#check Matrix.toEuclideanLin_eq_toLin_orthonormal
#check finrank_euclideanSpace
#check Module.finrank_pi
#check LinearMap.sq_singularValues_fin
