#!/usr/bin/env python3
"""Emit the non-propositional sentences of a manuscript as Lean data.

`scripts/sentence_census.py` grades every printed sentence.  Most rows name a
declaration; the `attribution`, `open` and `provenance` rows cannot, and should
not, because those sentences make no mathematical assertion of their own.  This
script gives them a Lean counterpart anyway, as a `List SentenceRecord` -- data
with no `Prop` field and no proof, so that nothing in it can be read as a
formalization.

    scripts/sentence_records.py --emit      write the generated Lean modules
    scripts/sentence_records.py --check     regenerate and diff, both ways

`--check` is the gate.  It fails if a record exists with no matching census row,
if a census row with one of the three statuses has no record, if a status
disagrees, or if the checked-in Lean file is not what the map generates.  That
is what makes the coverage union in
`GroupApproximation/Manuscript/Meta/SentenceRecords.lean` exact rather than
aspirational.

`structural` is deliberately NOT emitted: a structural sentence's counterpart is
its census row.  Recording it here as well would triple the generated files and
add nothing checkable.

This script does not modify `sentence_census.py`.  It imports it, so the two
cannot disagree about what a sentence is or what its key is, and the gate that
the manuscripts actually depend on is left alone.
"""

from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import sentence_census as sc  # noqa: E402  (path set above)

# status in the census  ->  constructor of `Meta.SentenceStatus`
EMITTED = {
    "attribution": "attribution",
    "open": "openProblem",
    "provenance": "provenance",
}

MODULE_DIR = os.path.join(ROOT, "GroupApproximation", "Manuscript", "Meta")

PAPERS = {
    "non-mf": {
        "tex": os.path.join(ROOT, "non_mf_groups_exist.tex"),
        "map": os.path.join(ROOT, "metadata", "NON_MF_SENTENCE_MAP.tsv"),
        "ledger": os.path.join(ROOT, "metadata", "NON_MF_PROOF_LEDGER.md"),
        "module": os.path.join(MODULE_DIR, "NonMFSentenceRecords.lean"),
        "decl": "nonMFSentenceRecords",
        "title": "non_mf_groups_exist.tex",
        "badges_need_rows": True,
    },
    "recognition": {
        "tex": os.path.join(ROOT, "mf_recognition_complexity.tex"),
        "map": os.path.join(ROOT, "metadata",
                            "MF_RECOGNITION_SENTENCE_MAP.tsv"),
        "ledger": os.path.join(ROOT, "metadata",
                               "MF_RECOGNITION_PROOF_LEDGER.md"),
        "module": os.path.join(MODULE_DIR,
                               "MFRecognitionSentenceRecords.lean"),
        "decl": "mfRecognitionSentenceRecords",
        "title": "mf_recognition_complexity.tex",
        "badges_need_rows": True,
    },
}


def lean_string(text: str) -> str:
    """A Lean string literal for `text`.

    Only backslash and double quote need escaping; the corpus already carries
    non-ASCII mathematics in docstrings, so the rest passes through.  Control
    characters cannot appear in a normalized sentence, but are stripped rather
    than trusted.
    """
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ord(ch) < 0x20:
            out.append(" ")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def records_for(paper: dict) -> list[dict]:
    rows, probes = sc.load_ledger(paper["ledger"])
    records = sc.extract(paper["tex"])
    sc.attach_anchors(records, paper["tex"], probes)
    overlay = sc.load_map(paper["map"])
    records = sc.join(records, overlay, rows, paper["badges_need_rows"])
    return [r for r in records if r["status"] in EMITTED]


def render(paper: dict, records: list[dict]) -> str:
    lines = [
        "import GroupApproximation.Manuscript.Meta.SentenceRecords",
        "",
        "/-!",
        f"# `{paper['title']}`: the sentences that are records, not claims",
        "",
        "GENERATED by `scripts/sentence_records.py` -- do not edit.  The",
        "assignments live in the sentence map; this file is their projection",
        "onto the three statuses that name no declaration, and",
        "`scripts/sentence_records.py --check` fails if the two disagree in",
        "either direction.",
        "",
        "`SentenceRecord` carries no `Prop` and no proof.  A row here records",
        "that the manuscript credits someone, poses an open question, or",
        "discloses how the work was produced; it asserts nothing, which is",
        "exactly why the sentence has no theorem.",
        "-/",
        "",
        "namespace GroupApproximation",
        "namespace Manuscript",
        "namespace Meta",
        "",
        f"/-- The `attribution`, `open` and `provenance` sentences of",
        f"`{paper['title']}`, as data. -/",
        f"def {paper['decl']} : List SentenceRecord := [",
    ]
    body = []
    for r in sorted(records, key=lambda r: (r["line"], r["key"])):
        body.append(
            "  { key := " + lean_string(r["key"]) + "\n"
            "    status := SentenceStatus." + EMITTED[r["status"]] + "\n"
            "    tex := " + lean_string(r["sentence"]) + "\n"
            "    note := " + lean_string(r["note"]) + " }")
    lines.append(",\n".join(body))
    lines += [
        "]",
        "",
        "end Meta",
        "end Manuscript",
        "end GroupApproximation",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--summary", action="store_true")
    args = ap.parse_args()

    failures = 0
    for name, paper in PAPERS.items():
        records = records_for(paper)
        text = render(paper, records)
        counts: dict[str, int] = {}
        for r in records:
            counts[r["status"]] = counts.get(r["status"], 0) + 1
        summary = ", ".join(f"{k} {v}" for k, v in sorted(counts.items()))
        print(f"{name:12s} {len(records):3d} records ({summary})")

        if args.emit:
            os.makedirs(os.path.dirname(paper["module"]), exist_ok=True)
            with open(paper["module"], "w", encoding="utf-8") as fh:
                fh.write(text)
        elif args.check:
            if not os.path.exists(paper["module"]):
                print(f"MISSING MODULE\t{paper['module']}")
                failures += 1
                continue
            with open(paper["module"], encoding="utf-8") as fh:
                current = fh.read()
            if current != text:
                print(f"STALE MODULE\t{paper['module']} is not what the map "
                      "generates; run --emit")
                failures += 1
            # the reverse direction: every emitted key must still be a census
            # row with the same status
            keys = {r["key"] for r in records}
            for line in current.splitlines():
                line = line.strip()
                if not line.startswith("{ key := "):
                    continue
                key = line.split('"')[1]
                if key not in keys:
                    print(f"ORPHAN RECORD\t{key} has no census row with an "
                          "emitted status")
                    failures += 1

    if args.check:
        print(f"{failures} record integrity failure(s)")
        return 1 if failures else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
