#!/usr/bin/env python3
"""Gate for the sentence census of simple_kazhdan_sofic_group.tex.

`scripts/sk_sentence_census.py --merge` derives the census from the lanes' row
files, but it never looks at Lean: a row can name a constant that was renamed,
never landed, or lives in a module the root file does not import (so CI never
builds it).  This scan closes that gap from the source text:

  * every census row is assigned (no `unassigned` status);
  * every `formalized` or `partial` row names at least one constant;
  * every constant a row names is declared in a module reachable from the root
    `GroupApproximation.lean` through `import GroupApproximation.*` lines.

The declaration scan is textual (namespaces, `theorem`/`def`/... headers,
`_root_`), so it cannot see names generated by `structure` fields or
`to_additive`; census rows should name the declared constant itself.  It does
not attest to a successful build, which only `lake build` gives.

    python3 scripts/sk_census_check.py              # gate; nonzero exit on any finding
    python3 scripts/sk_census_check.py --self-test  # calibration of the scan
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CENSUS = os.path.join(ROOT, "metadata", "SK_SENTENCE_CENSUS.tsv")
ROOT_FILE = "GroupApproximation.lean"

IMPORT = re.compile(r"^\s*import\s+(GroupApproximation(?:\.[A-Za-z0-9_']+)+)\s*$")
NAMESPACE = re.compile(r"^\s*namespace\s+(\S+)")
SECTION = re.compile(r"^\s*(?:noncomputable\s+)?section\b(?:\s+(\S+))?")
END = re.compile(r"^\s*end(?:\s+(\S+))?\s*$")
DECL = re.compile(
    r"^\s*(?:@\[[^\]]*\]\s*)*"
    r"(?:(?:private|protected|noncomputable|unsafe|partial|nonrec)\s+)*"
    r"(theorem|lemma|def|abbrev|structure|class|inductive|instance|opaque|axiom)\s+"
    r"([^\s:({\[]+)")
COMMENT_BLOCK = re.compile(r"/-.*?-/", re.S)
CONSTANT = re.compile(r"^\S+$")


def module_path(root: str, module: str) -> str:
    return os.path.join(root, *module.split(".")) + ".lean"


def rooted_files(root: str) -> list[str]:
    """Files reachable from the root file through GroupApproximation imports."""
    seen: set[str] = set()
    todo = [os.path.join(root, ROOT_FILE)]
    while todo:
        path = todo.pop()
        if path in seen or not os.path.exists(path):
            continue
        seen.add(path)
        with open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                m = IMPORT.match(line)
                if m:
                    todo.append(module_path(root, m.group(1)))
    return sorted(seen)


def declarations(path: str) -> set[str]:
    with open(path, encoding="utf-8", errors="replace") as fh:
        source = COMMENT_BLOCK.sub(lambda m: "\n" * m.group(0).count("\n"), fh.read())
    names: set[str] = set()
    scopes: list[tuple[str, list[str]]] = []  # (kind, namespace components)
    for line in source.split("\n"):
        line = line.split("--", 1)[0]
        m = NAMESPACE.match(line)
        if m:
            scopes.append(("namespace", m.group(1).split(".")))
            continue
        m = SECTION.match(line)
        if m and not DECL.match(line):
            scopes.append(("section", []))
            continue
        m = END.match(line)
        if m:
            if scopes:
                scopes.pop()
            continue
        m = DECL.match(line)
        if m:
            name = m.group(2)
            if name.startswith("_root_."):
                names.add(name[len("_root_."):])
                continue
            prefix = [c for _, comps in scopes for c in comps]
            names.add(".".join(prefix + [name]))
    return names


def load_rows(path: str) -> list[dict]:
    rows = []
    with open(path, encoding="utf-8") as fh:
        header = None
        for raw in fh:
            line = raw.rstrip("\n")
            if line.startswith("#") or not line:
                continue
            cols = line.split("\t")
            if header is None:
                header = cols
                continue
            rows.append(dict(zip(header, cols)))
    return rows


def check(root: str, census: str) -> list[str]:
    files = rooted_files(root)
    if not files:
        return [f"root file {ROOT_FILE} not found under {root}"]
    declared: set[str] = set()
    for f in files:
        declared |= declarations(f)
    findings: list[str] = []
    for r in load_rows(census):
        where = f"{r['key']} (l.{r['line']}-{r['end']}, {r['status']})"
        if r["status"] == "unassigned":
            findings.append(f"{where}: unassigned")
            continue
        consts = r.get("decls", "").split()
        if r["status"] in ("formalized", "partial") and not consts:
            findings.append(f"{where}: names no constant")
        for c in consts:
            if not CONSTANT.match(c):
                findings.append(f"{where}: malformed constant {c!r}")
            elif c not in declared:
                findings.append(f"{where}: {c} is not declared in a rooted module")
    return findings


def self_test() -> int:
    """Each planted defect must be reported, and the clean tree must be silent."""
    with tempfile.TemporaryDirectory() as d:
        os.makedirs(os.path.join(d, "GroupApproximation", "A"))
        with open(os.path.join(d, ROOT_FILE), "w") as fh:
            fh.write("import GroupApproximation.A.B\n")
        with open(os.path.join(d, "GroupApproximation", "A", "B.lean"), "w") as fh:
            fh.write("namespace GroupApproximation.Full\n/-- theorem fake : True -/\n"
                     "section\ntheorem kept : True := trivial\nend\n"
                     "@[simp] theorem _root_.rootName : True := trivial\n"
                     "end GroupApproximation.Full\n")
        with open(os.path.join(d, "GroupApproximation", "A", "Orphan.lean"), "w") as fh:
            fh.write("theorem orphan : True := trivial\n")
        census = os.path.join(d, "census.tsv")
        head = "key\tline\tend\tsection\tenv\tlabel\tstatus\tdecls\tsentence\n"

        def run(rows: str) -> list[str]:
            with open(census, "w") as fh:
                fh.write("# generated\n" + head + rows)
            return check(d, census)

        clean = run("aaa\t1\t1\t\t\t\tformalized\tGroupApproximation.Full.kept rootName\tx\n"
                    "bbb\t2\t2\t\t\t\tattribution\t\ty\n")
        planted = {
            "unassigned": "ccc\t3\t3\t\t\t\tunassigned\t\tz\n",
            "names no constant": "ddd\t4\t4\t\t\t\tformalized\t\tz\n",
            "orphan": "eee\t5\t5\t\t\t\tpartial\torphan\tz\n",
            "fake": "fff\t6\t6\t\t\t\tformalized\tGroupApproximation.Full.fake\tz\n",
        }
        ok = not clean
        if clean:
            print("self-test: clean tree reported " + "; ".join(clean))
        for label, row in planted.items():
            if not run(row):
                print(f"self-test: planted defect not reported: {label}")
                ok = False
    print("self-test " + ("passed" if ok else "FAILED"))
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--root", default=ROOT, help="checkout containing GroupApproximation.lean")
    ap.add_argument("--census", default=CENSUS)
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    findings = check(args.root, args.census)
    for f in findings:
        print("FINDING: " + f)
    print(f"{len(findings)} finding(s)")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
