import GroupApproximation.Kourovka1759.PC

/-!
# The transposition presentation of `CT_P(ℤ)` and its evaluation map

Research node: `class-transposition-presentation-has-central-kernel` (Kourovka 17.61 lane).

For a finite set `P` of primes, a box is *admissible* if every prime factor of its modulus lies in
`P' = P ∪ {2}`. The group `TranspGroup P` is generated by one symbol `t(A,B)` for each pair of
disjoint admissible boxes, subject to the following relations:

* `t(A,B) = t(B,A)`;
* `t(A,B)² = 1`;
* `t(C,D) t(A,B) t(C,D) = t(A',B')` whenever the class transposition of `C, D` maps `A` onto `A'`
  and `B` onto `B'` canonically;
* `t(A,B) = ∏_{j<k} t(A_j, B_j)` for the `k`-children `A_j = place A (child k j)` whenever these
  children are admissible.

All four hold for class transpositions, so `t(A,B) ↦ swap A B` defines `eval P`. The research
question (Kourovka 17.61 via this presentation) is whether `eval P` is injective.
-/

namespace GroupApproximation.ClassTransposition.Presentation

open GroupApproximation.Kourovka1759 Equiv Box

/-! ### Identities among swaps -/

/-- A permutation that maps `A` onto `B` and `B` onto `A` canonically and fixes the rest is the
swap of `A` and `B`. -/
theorem swap_eq_of (g : Perm ℤ) {A B : Box} (h : A.Disj B) (h1 : CanonOn g A B)
    (h2 : CanonOn g B A) (h3 : ∀ n, ¬ A.Mem n → ¬ B.Mem n → g n = n) : g = swap A B h := by
  refine Equiv.ext fun n => ?_
  by_cases ha : A.Mem n
  · exact h1.agree (swap_canon h) ha
  by_cases hb : B.Mem n
  · exact h2.agree (swap_canon' h) hb
  rw [h3 n ha hb, swap_fix h ha hb]

theorem swap_comm {A B : Box} (h : A.Disj B) : swap A B h = swap B A h.symm :=
  swap_eq_of _ h.symm (swap_canon' h) (swap_canon h) fun _ hb ha => swap_fix h ha hb

theorem swap_mul_self {A B : Box} (h : A.Disj B) : swap A B h * swap A B h = 1 := by
  refine Equiv.ext fun n => ?_
  rw [Perm.mul_apply, Perm.one_apply, swap_apply, swap_apply]
  exact swapFun_invol h n

theorem swap_inv {A B : Box} (h : A.Disj B) : (swap A B h)⁻¹ = swap A B h :=
  inv_eq_of_mul_eq_one_right (swap_mul_self h)

/-- Conjugating a swap by a permutation that is canonical on both boxes gives the swap of the
image boxes. -/
theorem conj_swap {c : Perm ℤ} {A B A' B' : Box} (h : A.Disj B) (h' : A'.Disj B')
    (hA : CanonOn c A A') (hB : CanonOn c B B') : c * swap A B h * c⁻¹ = swap A' B' h' := by
  refine swap_eq_of _ h' ?_ ?_ ?_
  · have := (hA.inv.comp (swap_canon h)).comp hB
    simpa only [mul_assoc] using this
  · have := (hB.inv.comp (swap_canon' h)).comp hA
    simpa only [mul_assoc] using this
  · intro n ha hb
    have ha' : ¬ A.Mem (c⁻¹ n) := fun hm => ha (by simpa using hA.mem hm)
    have hb' : ¬ B.Mem (c⁻¹ n) := fun hm => hb (by simpa using hB.mem hm)
    rw [Perm.mul_apply, Perm.mul_apply, swap_fix h ha' hb', Perm.apply_inv_self]

/-- `n` lies in the `j`-th pair of `k`-children of `A, B`. -/
def InKid (A B : Box) (k : ℕ) (j : Fin k) (n : ℤ) : Prop :=
  (place A (child k j)).Mem n ∨ (place B (child k j)).Mem n

theorem inKid_disj {A B : Box} (h : A.Disj B) {k : ℕ} {j j' : Fin k} (hjj : j ≠ j') {n : ℤ}
    (hj : InKid A B k j n) : ¬ InKid A B k j' n := by
  rintro (ha' | hb') <;> rcases hj with ha | hb
  · exact disj_place (child_disj k hjj) n ha ha'
  · exact disj_place_of h.symm n hb ha'
  · exact disj_place_of h n ha hb'
  · exact disj_place (child_disj k hjj) n hb hb'

/-- The swap of the `j`-th pair of `k`-children. -/
noncomputable def kidSwap {A B : Box} (h : A.Disj B) (k : ℕ) (j : Fin k) : Perm ℤ :=
  swap (place A (child k j)) (place B (child k j)) (disj_place_of h)

theorem prod_kidSwap_fix {A B : Box} (h : A.Disj B) (k : ℕ) (n : ℤ) :
    ∀ l : List (Fin k), (∀ j ∈ l, ¬ InKid A B k j n) → (l.map (kidSwap h k)).prod n = n
  | [], _ => rfl
  | j :: l, hl => by
    rw [List.map_cons, List.prod_cons, Perm.mul_apply,
      prod_kidSwap_fix h k n l fun j' hj' => hl j' (List.mem_cons_of_mem _ hj')]
    have hj := hl j List.mem_cons_self
    exact swap_fix _ (fun ha => hj (Or.inl ha)) (fun hb => hj (Or.inr hb))

theorem kidSwap_inKid {A B : Box} (h : A.Disj B) {k : ℕ} {j : Fin k} {n : ℤ}
    (hn : InKid A B k j n) : InKid A B k j (kidSwap h k j n) := by
  rcases hn with ha | hb
  · exact Or.inr ((swap_canon (disj_place_of h)).mem ha)
  · exact Or.inl ((swap_canon' (disj_place_of h)).mem hb)

theorem prod_kidSwap_apply {A B : Box} (h : A.Disj B) (k : ℕ) (j₀ : Fin k) (n : ℤ)
    (hn : InKid A B k j₀ n) :
    ∀ l : List (Fin k), l.Nodup → j₀ ∈ l → (l.map (kidSwap h k)).prod n = kidSwap h k j₀ n
  | [], _, hm => absurd hm List.not_mem_nil
  | j :: l, hnd, hm => by
    rw [List.nodup_cons] at hnd
    rw [List.map_cons, List.prod_cons, Perm.mul_apply]
    by_cases hj : j = j₀
    · subst hj
      rw [prod_kidSwap_fix h k n l fun j' hj' =>
        inKid_disj h (fun e => hnd.1 (by rw [e]; exact hj')) hn]
    · have hm' : j₀ ∈ l := (List.mem_cons.1 hm).resolve_left (Ne.symm hj)
      rw [prod_kidSwap_apply h k j₀ n hn l hnd.2 hm']
      have hk := inKid_disj h (Ne.symm hj) (kidSwap_inKid h hn)
      exact swap_fix _ (fun ha => hk (Or.inl ha)) (fun hb => hk (Or.inr hb))

/-- The splitting relation: a swap is the product of the swaps of its `k`-children. -/
theorem swap_split {A B : Box} (h : A.Disj B) (k : ℕ) (hk : 0 < k) :
    ((List.finRange k).map (kidSwap h k)).prod = swap A B h := by
  refine Equiv.ext fun n => ?_
  by_cases hn : ∃ j, InKid A B k j n
  · obtain ⟨j₀, hj₀⟩ := hn
    rw [prod_kidSwap_apply h k j₀ n hj₀ _ (List.nodup_finRange k) (List.mem_finRange j₀)]
    rcases hj₀ with ha | hb
    · exact (swap_canon (disj_place_of h)).agree ((swap_canon h).place _) ha
    · exact (swap_canon' (disj_place_of h)).agree ((swap_canon' h).place _) hb
  · have hn' : ∀ j, ¬ InKid A B k j n := fun j hj => hn ⟨j, hj⟩
    rw [prod_kidSwap_fix h k n _ fun j _ => hn' j]
    have ha : ¬ A.Mem n := fun ha =>
      hn' (classOf k hk (n / A.m)) (Or.inl (mem_place.2 ⟨ha, mem_classOf k hk _⟩))
    have hb : ¬ B.Mem n := fun hb =>
      hn' (classOf k hk (n / B.m)) (Or.inr (mem_place.2 ⟨hb, mem_classOf k hk _⟩))
    exact (swap_fix h ha hb).symm

/-! ### The presentation -/

/-- `B` is admissible for `P`: every prime factor of its modulus lies in `P ∪ {2}`. -/
def Adm (P : Finset ℕ) (B : Box) : Prop :=
  ∀ p : ℕ, p.Prime → (p : ℤ) ∣ B.m → p ∈ insert 2 P

/-- A generator `t(A,B)`: an ordered pair of disjoint admissible boxes. -/
structure Gen (P : Finset ℕ) where
  A : Box
  B : Box
  disj : A.Disj B
  admA : Adm P A
  admB : Adm P B

/-- The generator with its two boxes exchanged. -/
def Gen.flip {P : Finset ℕ} (g : Gen P) : Gen P := ⟨g.B, g.A, g.disj.symm, g.admB, g.admA⟩

/-- The `j`-th pair of `k`-children of a generator, given that it is admissible. -/
def Gen.kid {P : Finset ℕ} (g : Gen P) (k : ℕ) (j : Fin k)
    (hA : Adm P (place g.A (child k j))) (hB : Adm P (place g.B (child k j))) : Gen P :=
  ⟨place g.A (child k j), place g.B (child k j), disj_place_of g.disj, hA, hB⟩

/-- The relations of the transposition presentation. -/
inductive Rel (P : Finset ℕ) : FreeGroup (Gen P) → Prop
  | symm (g : Gen P) : Rel P (FreeGroup.of g * (FreeGroup.of g.flip)⁻¹)
  | sq (g : Gen P) : Rel P (FreeGroup.of g * FreeGroup.of g)
  | conj (c g g' : Gen P) (hA : CanonOn (swap c.A c.B c.disj) g.A g'.A)
      (hB : CanonOn (swap c.A c.B c.disj) g.B g'.B) :
      Rel P (FreeGroup.of c * FreeGroup.of g * FreeGroup.of c * (FreeGroup.of g')⁻¹)
  | split (g : Gen P) (k : ℕ) (hk : 0 < k)
      (hc : ∀ j : Fin k, Adm P (place g.A (child k j)) ∧ Adm P (place g.B (child k j))) :
      Rel P (FreeGroup.of g *
        ((List.finRange k).map fun j => FreeGroup.of (g.kid k j (hc j).1 (hc j).2)).prod⁻¹)

/-- The group presented by the transposition relations. -/
abbrev TranspGroup (P : Finset ℕ) : Type := PresentedGroup {r | Rel P r}

/-- A generator evaluates to its class transposition. -/
noncomputable def evalGen (P : Finset ℕ) (g : Gen P) : Perm ℤ := swap g.A g.B g.disj

theorem rel_eval (P : Finset ℕ) :
    ∀ r ∈ {r | Rel P r}, FreeGroup.lift (evalGen P) r = 1 := by
  intro r hr
  change Rel P r at hr
  cases hr with
  | symm g =>
    rw [map_mul, map_inv, FreeGroup.lift_apply_of, FreeGroup.lift_apply_of, mul_inv_eq_one]
    exact swap_comm g.disj
  | sq g =>
    rw [map_mul, FreeGroup.lift_apply_of]
    exact swap_mul_self g.disj
  | conj c g g' hA hB =>
    rw [map_mul, map_mul, map_mul, map_inv, FreeGroup.lift_apply_of, FreeGroup.lift_apply_of,
      FreeGroup.lift_apply_of, mul_inv_eq_one]
    show swap c.A c.B c.disj * swap g.A g.B g.disj * swap c.A c.B c.disj = swap g'.A g'.B g'.disj
    have key := conj_swap (c := swap c.A c.B c.disj) g.disj g'.disj hA hB
    rwa [swap_inv c.disj] at key
  | split g k hk hc =>
    rw [map_mul, map_inv, map_list_prod, List.map_map, mul_inv_eq_one, FreeGroup.lift_apply_of]
    show swap g.A g.B g.disj = _
    rw [← swap_split g.disj k hk]
    congr 1
    refine List.map_congr_left fun j _ => ?_
    simp only [Function.comp_apply, FreeGroup.lift_apply_of]
    rfl

/-- The evaluation map `t(A,B) ↦` the class transposition of `A` and `B`. -/
noncomputable def eval (P : Finset ℕ) : TranspGroup P →* Perm ℤ :=
  PresentedGroup.toGroup (rel_eval P)

@[simp] theorem eval_of (P : Finset ℕ) (g : Gen P) :
    eval P (PresentedGroup.of g) = swap g.A g.B g.disj :=
  PresentedGroup.toGroup.of (rel_eval P)

/-- The image of `eval` consists of class-transposition products. -/
theorem eval_mem_ct (P : Finset ℕ) (x : TranspGroup P) : eval P x ∈ classTranspositionGroup := by
  obtain ⟨w, rfl⟩ := PresentedGroup.mk_surjective _ x
  induction w using FreeGroup.induction_on with
  | C1 => rw [map_one, map_one]; exact Subgroup.one_mem _
  | of g =>
    show eval P (PresentedGroup.of g) ∈ _
    rw [eval_of]
    exact swap_mem_ct _
  | inv_of g ih =>
    rw [map_inv, map_inv]
    exact Subgroup.inv_mem _ ih
  | mul a b iha ihb =>
    rw [map_mul, map_mul]
    exact Subgroup.mul_mem _ iha ihb

end GroupApproximation.ClassTransposition.Presentation
