import GroupApproximation.Analysis.CStarSeparableFaithfulRepresentation
import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap
import Mathlib.Analysis.CStarAlgebra.Hom
import Mathlib.Analysis.CStarAlgebra.Unitization

/-!
# The stabilization `𝒦 ⊗ B` of a non-unital C⋆-algebra

Cuntz's picture of Kasparov theory (J. Cuntz, *A new look at KK-theory*, K-Theory 1 (1987)
31--51; Blackadar, *K-Theory for Operator Algebras*, 13 and 17.8) uses the
stabilization `𝒦 ⊗ B` of a C⋆-algebra `B` by the compact operators on `ℓ²(ℕ)`.
We realize it spatially:

* `Stab.rep B : B →⋆ₙₐ[ℂ] B(H_B)`: a faithful representation of `B`, the diagonal GNS
  representation of all states of the unitization `B⁺` restricted to `B`
  (`CStarSeparableFaithfulRepresentation`);
* `Stab.Ambient B := B(ℓ²(ℕ, H_B))`, a unital C⋆-algebra;
* `Stab.matUnit i j T`: the operator `x ↦ δ_i ⊗ T (x j)`, i.e. `e_{ij} ⊗ T`;
* `Stab B`: the norm closure of the `⋆`-algebra generated by the `e_{ij} ⊗ π(b)`, that is the
  closure of the finitely supported `ℕ × ℕ` matrices over `B`; this is `𝒦 ⊗ B`;
* `Stab.corner B : B →⋆ₙₐ[ℂ] Stab B`, `b ↦ e_{00} ⊗ b`.

The matrix unit relations `e_{ij} e_{kl} = δ_{jk} e_{il}` and `(e_{ij} ⊗ T)^* = e_{ji} ⊗ T^*`
are proved here; functoriality is in `StabMap`.

Manuscript: `non_mf_group_notes.tex`, UCT hypothesis of `thm:fixed-radical-membership`
(lane TWWKK-Stab, work order WO-TWWKK-A1).
-/

namespace GroupApproximation.Full.TWWKK

universe u

noncomputable section

namespace Stab

variable (B : Type u) [NonUnitalCStarAlgebra B]

/-! ## A faithful representation -/

/-- The index family of the faithful representation: all states of the unitization. -/
def states : CStarState.State (Unitization ℂ B) → CStarState.State (Unitization ℂ B) :=
  id

/-- The Hilbert space of the faithful representation of `B`: the Hilbert sum of the GNS spaces
of all states of the unitization. -/
abbrev RepSpace : Type u :=
  CStarState.FamilyGNSSpace (states B)

/-- **The faithful representation** of `B`: the diagonal GNS representation of the unitization,
restricted to `B`. -/
def rep : B →⋆ₙₐ[ℂ] (RepSpace B →L[ℂ] RepSpace B) :=
  (CStarState.familyGNSStarAlgHom (states B)).toNonUnitalStarAlgHom.comp
    (Unitization.inrNonUnitalStarAlgHom ℂ B)

/-- The representation `rep B` is faithful: the GNS family of all states separates points of the
unitization (`exists_state_norm_le_gnsRep`). -/
theorem rep_injective : Function.Injective (rep B) := by
  intro a b h
  have hsep : ∀ x : Unitization ℂ B, x ≠ 0 →
      ∃ φ : CStarState.State (Unitization ℂ B), ((states B φ).gnsRep).hom x ≠ 0 := by
    intro x hx
    obtain ⟨φ, hφ⟩ := CStarState.exists_state_norm_le_gnsRep x
    refine ⟨φ, fun h0 => hx ?_⟩
    have h0' : (φ.gnsRep).hom x = 0 := h0
    rw [h0', norm_zero] at hφ
    exact norm_le_zero_iff.mp hφ
  have h' : CStarState.familyGNSStarAlgHom (states B) (a : Unitization ℂ B) =
      CStarState.familyGNSStarAlgHom (states B) (b : Unitization ℂ B) := h
  exact Unitization.inr_injective (CStarState.familyGNSStarAlgHom_injective (states B) hsep h')

/-- The faithful representation is isometric. -/
theorem norm_rep (b : B) : ‖rep B b‖ = ‖b‖ :=
  NonUnitalStarAlgHom.norm_map (rep B) (rep_injective B) b

/-! ## The ambient algebra `B(ℓ²(ℕ, H_B))` and matrix units -/

/-- The Hilbert space `ℓ²(ℕ, H_B)`. -/
abbrev Space : Type u := lp (fun _ : ℕ => RepSpace B) 2

/-- The ambient unital C⋆-algebra `B(ℓ²(ℕ, H_B))`. -/
abbrev Ambient : Type u := Space B →L[ℂ] Space B

/-- The inclusion of the `i`-th summand of `ℓ²(ℕ, H_B)`. -/
def inj (i : ℕ) : RepSpace B →L[ℂ] Space B :=
  lp.singleContinuousLinearMap ℂ (fun _ : ℕ => RepSpace B) 2 i

/-- The projection onto the `i`-th summand of `ℓ²(ℕ, H_B)`. -/
def proj (i : ℕ) : Space B →L[ℂ] RepSpace B :=
  lp.evalCLM ℂ (fun _ : ℕ => RepSpace B) 2 i

/-- **The matrix unit operator** `e_{ij} ⊗ T : x ↦ δ_i ⊗ T (x j)`. -/
def matUnit (i j : ℕ) (T : RepSpace B →L[ℂ] RepSpace B) : Ambient B :=
  inj B i ∘L T ∘L proj B j

variable {B}

theorem inj_apply (i : ℕ) (v : RepSpace B) : inj B i v = lp.single 2 i v :=
  rfl

theorem proj_apply (i : ℕ) (x : Space B) : proj B i x = x i :=
  rfl

theorem matUnit_apply (i j : ℕ) (T : RepSpace B →L[ℂ] RepSpace B) (x : Space B) :
    matUnit B i j T x = lp.single 2 i (T (x j)) :=
  rfl

theorem matUnit_add (i j : ℕ) (S T : RepSpace B →L[ℂ] RepSpace B) :
    matUnit B i j (S + T) = matUnit B i j S + matUnit B i j T := by
  refine ContinuousLinearMap.ext fun x => ?_
  change lp.single 2 i ((S + T) (x j)) = lp.single 2 i (S (x j)) + lp.single 2 i (T (x j))
  exact lp.single_add 2 i (S (x j)) (T (x j))

theorem matUnit_smul (i j : ℕ) (c : ℂ) (T : RepSpace B →L[ℂ] RepSpace B) :
    matUnit B i j (c • T) = c • matUnit B i j T := by
  refine ContinuousLinearMap.ext fun x => ?_
  change lp.single 2 i ((c • T) (x j)) = c • lp.single 2 i (T (x j))
  exact lp.single_smul 2 i c (T (x j))

theorem matUnit_zero (i j : ℕ) : matUnit B i j 0 = 0 := by
  refine ContinuousLinearMap.ext fun x => ?_
  change lp.single 2 i ((0 : RepSpace B →L[ℂ] RepSpace B) (x j)) = 0
  exact lp.single_zero 2 i

theorem matUnit_neg (i j : ℕ) (T : RepSpace B →L[ℂ] RepSpace B) :
    matUnit B i j (-T) = -matUnit B i j T := by
  refine ContinuousLinearMap.ext fun x => ?_
  change lp.single 2 i ((-T) (x j)) = -lp.single 2 i (T (x j))
  exact lp.single_neg 2 i (T (x j))

theorem matUnit_sub (i j : ℕ) (S T : RepSpace B →L[ℂ] RepSpace B) :
    matUnit B i j (S - T) = matUnit B i j S - matUnit B i j T := by
  rw [sub_eq_add_neg, matUnit_add, matUnit_neg, ← sub_eq_add_neg]

/-- **Matrix unit multiplication**: `(e_{ij} ⊗ S)(e_{kl} ⊗ T) = δ_{jk} e_{il} ⊗ ST`. -/
theorem matUnit_mul_matUnit (i j k l : ℕ) (S T : RepSpace B →L[ℂ] RepSpace B) :
    matUnit B i j S * matUnit B k l T = if j = k then matUnit B i l (S * T) else 0 := by
  refine ContinuousLinearMap.ext fun x => ?_
  change lp.single 2 i (S ((lp.single 2 k (T (x l)) : Space B) j)) =
    (if j = k then matUnit B i l (S * T) else 0) x
  by_cases h : j = k
  · rw [if_pos h, h]
    exact congrArg (fun v => lp.single 2 i (S v)) (lp.single_apply_self 2 k (T (x l)))
  · rw [if_neg h, lp.single_apply_ne 2 k _ h, map_zero]
    exact lp.single_zero 2 i

theorem matUnit_mul_self (i j l : ℕ) (S T : RepSpace B →L[ℂ] RepSpace B) :
    matUnit B i j S * matUnit B j l T = matUnit B i l (S * T) := by
  rw [matUnit_mul_matUnit, if_pos rfl]

theorem matUnit_mul_of_ne {i j k l : ℕ} (h : j ≠ k) (S T : RepSpace B →L[ℂ] RepSpace B) :
    matUnit B i j S * matUnit B k l T = 0 := by
  rw [matUnit_mul_matUnit, if_neg h]

/-- **The adjoint of a matrix unit operator**: `(e_{ij} ⊗ T)^* = e_{ji} ⊗ T^*`. -/
theorem star_matUnit (i j : ℕ) (T : RepSpace B →L[ℂ] RepSpace B) :
    star (matUnit B i j T) = matUnit B j i (star T) := by
  rw [ContinuousLinearMap.star_eq_adjoint (matUnit B i j T), eq_comm,
    ContinuousLinearMap.eq_adjoint_iff]
  intro x y
  change inner ℂ (lp.single 2 j ((star T) (x i)) : Space B) y =
    inner ℂ x (lp.single 2 i (T (y j)) : Space B)
  rw [lp.inner_single_left, lp.inner_single_right, ContinuousLinearMap.star_eq_adjoint T]
  exact ContinuousLinearMap.adjoint_inner_left T (y j) (x i)

/-! ## The stabilization -/

variable (B)

/-- The generators `e_{ij} ⊗ π(b)` of the finite matrices over `B`. -/
def generators : Set (Ambient B) :=
  {x | ∃ (i j : ℕ) (b : B), x = matUnit B i j (rep B b)}

/-- The `⋆`-algebra of finitely supported `ℕ × ℕ` matrices over `B`. -/
def finiteMatrices : NonUnitalStarSubalgebra ℂ (Ambient B) :=
  NonUnitalStarAlgebra.adjoin ℂ (generators B)

/-- The norm closure of the finite matrices: `𝒦 ⊗ B` inside `B(ℓ²(ℕ, H_B))`. -/
def closedSubalgebra : NonUnitalStarSubalgebra ℂ (Ambient B) :=
  (finiteMatrices B).topologicalClosure

instance isClosed_closedSubalgebra : IsClosed (closedSubalgebra B : Set (Ambient B)) :=
  (finiteMatrices B).isClosed_topologicalClosure

end Stab

/-- **The stabilization `𝒦 ⊗ B`**: the norm closure of the finitely supported `ℕ × ℕ` matrices
over `B`, realized in `B(ℓ²(ℕ, H_B))` for a faithful representation `B ⊆ B(H_B)`. -/
abbrev Stab (B : Type u) [NonUnitalCStarAlgebra B] : Type u :=
  Stab.closedSubalgebra B

noncomputable instance Stab.instNonUnitalCStarAlgebra (B : Type u) [NonUnitalCStarAlgebra B] :
    NonUnitalCStarAlgebra (Stab B) :=
  NonUnitalStarSubalgebra.nonUnitalCStarAlgebra (Stab.closedSubalgebra B)

namespace Stab

variable {B : Type u} [NonUnitalCStarAlgebra B]

theorem finiteMatrices_le_closedSubalgebra : finiteMatrices B ≤ closedSubalgebra B :=
  (finiteMatrices B).le_topologicalClosure

theorem generators_subset_finiteMatrices : generators B ⊆ finiteMatrices B :=
  NonUnitalStarAlgebra.subset_adjoin ℂ (generators B)

theorem matUnit_rep_mem_finiteMatrices (i j : ℕ) (b : B) :
    matUnit B i j (rep B b) ∈ finiteMatrices B :=
  generators_subset_finiteMatrices ⟨i, j, b, rfl⟩

theorem matUnit_rep_mem (i j : ℕ) (b : B) : matUnit B i j (rep B b) ∈ closedSubalgebra B :=
  finiteMatrices_le_closedSubalgebra (matUnit_rep_mem_finiteMatrices i j b)

/-- The element `e_{ij} ⊗ b` of `Stab B`. -/
def single (i j : ℕ) (b : B) : Stab B :=
  ⟨matUnit B i j (rep B b), matUnit_rep_mem i j b⟩

theorem coe_single (i j : ℕ) (b : B) : (single i j b : Ambient B) = matUnit B i j (rep B b) :=
  rfl

variable (B) in
/-- **The corner embedding** `B → 𝒦 ⊗ B`, `b ↦ e_{00} ⊗ b`. -/
def corner : B →⋆ₙₐ[ℂ] Stab B where
  toFun b := single 0 0 b
  map_smul' c b := Subtype.ext <| by
    change matUnit B 0 0 (rep B (c • b)) = c • matUnit B 0 0 (rep B b)
    rw [map_smul, matUnit_smul]
  map_zero' := Subtype.ext <| by
    change matUnit B 0 0 (rep B 0) = 0
    rw [map_zero, matUnit_zero]
  map_add' a b := Subtype.ext <| by
    change matUnit B 0 0 (rep B (a + b)) = matUnit B 0 0 (rep B a) + matUnit B 0 0 (rep B b)
    rw [map_add, matUnit_add]
  map_mul' a b := Subtype.ext <| by
    change matUnit B 0 0 (rep B (a * b)) = matUnit B 0 0 (rep B a) * matUnit B 0 0 (rep B b)
    rw [map_mul, matUnit_mul_self]
  map_star' b := Subtype.ext <| by
    change matUnit B 0 0 (rep B (star b)) = star (matUnit B 0 0 (rep B b))
    rw [map_star, star_matUnit]

theorem corner_apply (b : B) : corner B b = single 0 0 b :=
  rfl

end Stab

end

end GroupApproximation.Full.TWWKK
