import GroupApproximation.Manuscript.NonMF.TorsionFreeJoint.EndpointStatement
import GroupApproximation.Manuscript.NonMF.TorsionFreeOsinNotion
import GroupApproximation.Manuscript.NonMF.TorsionFreeLimitSetNotion
import GroupApproximation.Meta.AxiomGuard

/-!
# `thm:torsion-free` with `cor:regular-nonmf-algebra`, same `Q`, at Osin's two notions

`non_mf_groups_exist.tex`, `thm:torsion-free` (tex lines 295-301):

> There is a two-generated, finitely presented, torsion-free, acylindrically
> hyperbolic group `Q` with property (T) such that every homomorphism from `Q`
> to an MF group is trivial.  In particular, no nontrivial quotient of `Q` is
> MF.

and `cor:regular-nonmf-algebra` (tex lines 2203-2207), about the `Q` of that theorem:

> The algebra `C*_r(Q)` is separable, unital, simple, and generated by two
> unitaries.  It has a unique tracial state and stable rank one, and it is
> stably finite but not MF.

`TorsionFreeJoint.PrintedTorsionFreeTheoremWithRegularAlgebra` states the two together
for one existential `Q`, at Hull's Cayley-graph notion `IsAcylindricallyHyperbolic`.
This module gives the same statement at the two other spellings of "acylindrically
hyperbolic" in the corpus:

* Osin's notion with two independent loxodromics, `GGT.IsAcylindricallyHyperbolicOsin`
  (the clause of `TorsionFreeOsinNotion.PrintedTorsionFreeTheoremOsin`);
* the limit-set notion `GGT.SequentialBoundary.IsAcylindricallyHyperbolicLimitSet`,
  "acylindrical action on a geodesic hyperbolic space with more than two limit points"
  (the clause of `TorsionFreeLimitSetNotion.PrintedTorsionFreeTheoremLimitSet`).

The clause lists are the lane-06 list word for word, with only the
acylindrical-hyperbolicity clause changed.  The C⋆ clauses come from
`TorsionFreeJoint.regularAlgebraClauses`, which needs Hull's notion as an instance.
The endpoint modules reach it through `GGT.isAcylindricallyHyperbolic_iff_osin` and
`GGT.OsinClassification.isAcylindricallyHyperbolicOsin_of_limitSet`.
-/

namespace GroupApproximation
namespace Manuscript
namespace NonMF
namespace TorsionFreeJointNotions

open GroupApproximation.Manuscript.NonMF.TorsionFree
open GroupApproximation.Manuscript.NonMF.TorsionFreePrinted
open GroupApproximation.ReducedGroupCStarTrace

/-- **`thm:torsion-free` with `cor:regular-nonmf-algebra` for the same `Q`, at Osin's
notion** (tex lines 297 and 2204).  This is `TorsionFreeJoint.PrintedTorsionFreeTheoremWithRegularAlgebra`
with `IsAcylindricallyHyperbolic Q` replaced by `GGT.IsAcylindricallyHyperbolicOsin Q`. -/
def PrintedTorsionFreeTheoremWithRegularAlgebraOsin : Prop :=
  ∃ (Q : Type) (_ : Group Q) (g₁ g₂ : Q),
    Subgroup.closure ({g₁, g₂} : Set Q) = ⊤ ∧
    Group.IsFinitelyPresented Q ∧ IsPowerTorsionFree Q ∧
    GGT.IsAcylindricallyHyperbolicOsin Q ∧ HasKazhdanPropertyT.{0, 0} Q ∧
    (∀ (M : Type) (_ : Group M), IsOperatorMF M →
      ∀ (f : Q →* M) (x : Q), f x = 1) ∧
    (∀ (L : Type) (_ : Group L) (r : Q →* L), Function.Surjective r →
      Nontrivial L → ¬ IsOperatorMF L) ∧
    TopologicalSpace.SeparableSpace (ReducedGroupCStar Q) ∧
    (1 : ReducedGroupCStar Q) ≠ 0 ∧
    leftRegularOperator Q g₁ ∈ unitary (GroupHilbert Q →L[ℂ] GroupHilbert Q) ∧
    leftRegularOperator Q g₂ ∈ unitary (GroupHilbert Q →L[ℂ] GroupHilbert Q) ∧
    (StarAlgebra.adjoin ℂ
      ({leftRegularOperator Q g₁, leftRegularOperator Q g₂} :
        Set (GroupHilbert Q →L[ℂ] GroupHilbert Q))).topologicalClosure
      = reducedGroupCStarSubalgebra Q ∧
    IsSimpleCStar (ReducedGroupCStar Q) ∧
    HasUniqueTracialState (ReducedGroupCStar Q) ∧
    IsStableRankOne (ReducedGroupCStar Q) ∧
    IsStablyFiniteCStarAlgebra (ReducedGroupCStar Q) ∧
    ¬ IsMFAlgebra (ReducedGroupCStar Q)

/-- **`thm:torsion-free` with `cor:regular-nonmf-algebra` for the same `Q`, at the
limit-set notion** (tex lines 297 and 2204).  This is `TorsionFreeJoint.PrintedTorsionFreeTheoremWithRegularAlgebra`
with `IsAcylindricallyHyperbolic Q` replaced by
`GGT.SequentialBoundary.IsAcylindricallyHyperbolicLimitSet Q`. -/
def PrintedTorsionFreeTheoremWithRegularAlgebraLimitSet : Prop :=
  ∃ (Q : Type) (_ : Group Q) (g₁ g₂ : Q),
    Subgroup.closure ({g₁, g₂} : Set Q) = ⊤ ∧
    Group.IsFinitelyPresented Q ∧ IsPowerTorsionFree Q ∧
    GGT.SequentialBoundary.IsAcylindricallyHyperbolicLimitSet Q ∧
    HasKazhdanPropertyT.{0, 0} Q ∧
    (∀ (M : Type) (_ : Group M), IsOperatorMF M →
      ∀ (f : Q →* M) (x : Q), f x = 1) ∧
    (∀ (L : Type) (_ : Group L) (r : Q →* L), Function.Surjective r →
      Nontrivial L → ¬ IsOperatorMF L) ∧
    TopologicalSpace.SeparableSpace (ReducedGroupCStar Q) ∧
    (1 : ReducedGroupCStar Q) ≠ 0 ∧
    leftRegularOperator Q g₁ ∈ unitary (GroupHilbert Q →L[ℂ] GroupHilbert Q) ∧
    leftRegularOperator Q g₂ ∈ unitary (GroupHilbert Q →L[ℂ] GroupHilbert Q) ∧
    (StarAlgebra.adjoin ℂ
      ({leftRegularOperator Q g₁, leftRegularOperator Q g₂} :
        Set (GroupHilbert Q →L[ℂ] GroupHilbert Q))).topologicalClosure
      = reducedGroupCStarSubalgebra Q ∧
    IsSimpleCStar (ReducedGroupCStar Q) ∧
    HasUniqueTracialState (ReducedGroupCStar Q) ∧
    IsStableRankOne (ReducedGroupCStar Q) ∧
    IsStablyFiniteCStarAlgebra (ReducedGroupCStar Q) ∧
    ¬ IsMFAlgebra (ReducedGroupCStar Q)

end TorsionFreeJointNotions
end NonMF
end Manuscript
end GroupApproximation
