import GroupApproximation.AlgTop.ComplexProjectiveSphere

/-!
# Products of complex projective spaces

The base of the LIX construction is

```text
Y = ∏_{j} ℂP^{d_j},     m = ∑_j d_j
```

(manuscript `research/artifacts/stw59-simple-ah-k1-counterexample-manuscript-2026-09-05.md`
§2). This file introduces `Y` and its point-set properties. The cohomological statements
about `Y` — that `H^{2m}(Y;ℤ) ≅ ℤ` is generated by `∏_j h_j^{d_j}`, equation (2.1) — are
stated in `notes/cpn-cohomology-signatures-2026-09-05.md` §B.3 and wait on the Künneth
isomorphism owned by lane `found-cohomology-ring`.

The empty product is allowed and is a point, matching the manuscript's convention that
`ℓ = 0` gives `Y = pt`, `H = 0`.

## Main results

* `CPn.CPProd dd` — the product space, with `CompactSpace`, `T2Space`, `Nonempty`
  instances;
* `CPn.CPProd.proj` — the projections, continuous;
* `CPn.CPProd.dim dd = ∑ j, dd j` — the complex dimension `m`;
* `CPn.subsingleton_CPProd_of_forall_zero` — `∏_j ℂP^0` is a point, the base case of any
  induction over the multi-index.
-/

noncomputable section

namespace GroupApproximation.AlgTop

open GroupApproximation.STW59

namespace CPn

/-- `Y = ∏_j ℂP^{d_j}`, the base of the LIX construction. -/
abbrev CPProd {ι : Type} [Fintype ι] (dd : ι → ℕ) : Type := ∀ j : ι, CP (dd j)

namespace CPProd

variable {ι : Type} [Fintype ι] (dd : ι → ℕ)

-- `CPProd` is an `abbrev`, so the product instances are inherited rather than declared:
-- `TopologicalSpace`, `T2Space`, `CompactSpace` (Tychonoff) and `Nonempty` all come from
-- the corresponding `Pi` instances. Recorded as checks rather than as new instances, so
-- that no second path into instance resolution is created.
example : TopologicalSpace (CPProd dd) := inferInstance
example : T2Space (CPProd dd) := inferInstance
example : CompactSpace (CPProd dd) := inferInstance
example : Nonempty (CPProd dd) := inferInstance

/-- The complex dimension `m = ∑_j d_j` of `Y`; the top nonvanishing cohomology of `Y`
sits in degree `2 * dim dd`. -/
def dim : ℕ := ∑ j, dd j

/-- Projection onto the `j`-th factor. -/
def proj (j : ι) : CPProd dd → CP (dd j) := fun y => y j

theorem continuous_proj (j : ι) : Continuous (proj dd j) := continuous_apply j

/-- The base point of `Y`. -/
def basePoint : CPProd dd := fun j => CPn.basePoint (dd j)

variable {dd}

theorem entry_proj_continuous (j : ι) (a b : Fin (dd j + 1)) :
    Continuous fun y : CPProd dd => entry (y j) a b :=
  (continuous_entry a b).comp (continuous_apply j)

theorem ext {y z : CPProd dd} (h : ∀ j, y j = z j) : y = z := funext h

end CPProd

/-- A product of copies of `ℂP^0` is a point. This is the base case of an induction over
the multi-index `d`. -/
theorem subsingleton_CPProd_of_forall_zero {ι : Type} [Fintype ι] {dd : ι → ℕ}
    (h : ∀ j, dd j = 0) : Subsingleton (CPProd dd) := by
  refine ⟨fun y z => CPProd.ext fun j => ?_⟩
  haveI : Subsingleton (CP (dd j)) := by rw [h j]; infer_instance
  exact Subsingleton.elim (y j) (z j)

end CPn

end GroupApproximation.AlgTop
