import GroupApproximation.Domination.PaperStatements

/-! Axiom audit for the paper-facing domination endpoints. -/

#print axioms GroupApproximation.finiteActionCollapse_iff_linearPermutationDomination
#print axioms GroupApproximation.finiteDimensionalCollapse_iff_linearUnitaryDomination
#print axioms GroupApproximation.permutationDomination_of_unitaryDomination
#print axioms GroupApproximation.characterDefect_eq_zero_of_soficPresentationInvisible
#print axioms GroupApproximation.finiteJet_contradicts_soficPresentationInvisible
#print axioms GroupApproximation.obstruction_requires_matrixDimensionEscape
#print axioms GroupApproximation.boundedIrreducibleDegree_linearDomination
#print axioms GroupApproximation.obstruction_requires_irreducibleDegreeEscape
