import GroupApproximation.Analysis.ProjectionOrbitCollapse
import GroupApproximation.Analysis.RankNormalizedLambda

/-!
# The displacements lie in the ideal `𝓘_q`

Proof-ledger row `CO.21`, the two sentences of the paragraph *An exact cocycle*
in the proof of `thm:projection-collapse` in `non_mf_groups_exist.tex` that put
`d_g` in the domain of `Λ` (navigate by the label; that file is under
concurrent edit):

> For `a ∈ S` the projection `q_a` annihilates `∏_{b∈S}(1 − q_b)`, so
> `q_a q = q_a` and `d_a = d_a q_a = d_a q ∈ 𝓘_q`.  … and `𝓘_q` is
> inner-invariant, so `d_g ∈ 𝓘_q` for every `g ∈ L`.

`Analysis/ProjectionOrbitCollapse` proves the algebra of the first sentence in
an arbitrary ring with involution — `mul_one_sub_listProd` is `q_a q = q_a`,
`sub_mul_sq_sub` is `d_a = d_a q_a` — and `Analysis/RankNormalizedLambda` builds
the ideal and `Λ` on it.  What neither does is the second sentence, and the row
records the consequence: `lambda_cocycle` takes the displacement family
`d : H → 𝓘_q` as a hypothesis rather than producing it from a corona
representation, because membership in the ideal was available only at the
generators.

Both sentences are here, over the corona.

* `displacement_mul_join` is the first, assembled: `d_a q = d_a` for a
  generator, from the two `ProjectionOrbitCollapse` identities in the order the
  print composes them.
* `displacement_mem_rankIdeal` is the second.  It is an induction over
  `Subgroup.closure S` on the *cocycle identity itself*: the generators are the
  first sentence, `d_1 = 0` because `p_1 = p`, `d_{xy} = d_x + Θ(x) d_y Θ(x)*`
  makes the product a sum of an ideal element and an inner-automorphic image of
  one, and `d_{x⁻¹} = −Θ(x⁻¹) d_x Θ(x⁻¹)*` is the same identity read at
  `(x⁻¹, x)`.  Inner invariance is `RankNormalizedLambda.mul_mem_rankIdeal`,
  which holds for arbitrary corona factors and so covers conjugation without a
  separate argument.

The printed sentence says "inner-invariant", and that is exactly the shape the
induction needs: nothing here uses that the conjugating element is unitary,
only that `𝓘_q` absorbs multiplication on both sides.

## What this does not yet supply

`lambda_cocycle` also wants the conjugating corona element to be the class of a
coordinatewise unitary sequence, so that `Λ` is equivariant for it.  That is
`lem:unitarycorona`, and choosing such lifts compatibly across `H` is a
separate step; this file supplies the membership, not the lift.
-/

namespace GroupApproximation
namespace CollapseDisplacementIdeal

open ProjectionOrbitCollapse RankNormalizedLambda
open UltraproductModelConstruction

noncomputable section

universe u

/-! ## `d_a = d_a q` at a generator -/

section Ring

variable {A : Type*} [Ring A] [StarRing A] {G : Type u} [Group G]

/-- **The printed `d_a = d_a q_a = d_a q`.**  The join absorbs each of its own
generators, and the cube identity absorbs the square, so the displacement at a
generator is already a right multiple of the join.

This is the two `ProjectionOrbitCollapse` identities composed in the printed
order, and it is what puts `d_a` in the ideal generated by `q`. -/
theorem displacement_mul_join (ρ : G →* unitary A) (p : A)
    (hp : IsIdempotentElem p) (l : List G)
    (hP : ∀ a ∈ l, IsIdempotentElem (conj ρ p a))
    (hcomm : ∀ a ∈ l, Commute p (conj ρ p a))
    (hpair : (l.map fun b ↦ (conj ρ p b - p) ^ 2).Pairwise Commute)
    {a : G} (ha : a ∈ l) :
    (conj ρ p a - p) *
        ((1 : A) - ((l.map fun b ↦ (conj ρ p b - p) ^ 2).map
          fun y ↦ 1 - y).prod)
      = conj ρ p a - p := by
  have hidem : ∀ y ∈ (l.map fun b ↦ (conj ρ p b - p) ^ 2),
      IsIdempotentElem y := by
    intro y hy
    obtain ⟨b, hb, rfl⟩ := List.mem_map.1 hy
    exact isIdempotentElem_sq_sub hp (hP b hb) (hcomm b hb)
  have hmem : (conj ρ p a - p) ^ 2 ∈ (l.map fun b ↦ (conj ρ p b - p) ^ 2) :=
    List.mem_map.2 ⟨a, ha, rfl⟩
  have h1 := mul_one_sub_listProd hidem hpair hmem
  have h2 := sub_mul_sq_sub hp (hP a ha) (hcomm a ha)
  calc (conj ρ p a - p) *
        ((1 : A) - ((l.map fun b ↦ (conj ρ p b - p) ^ 2).map
          fun y ↦ 1 - y).prod)
      = ((conj ρ p a - p) * (conj ρ p a - p) ^ 2) *
          ((1 : A) - ((l.map fun b ↦ (conj ρ p b - p) ^ 2).map
            fun y ↦ 1 - y).prod) := by rw [h2]
    _ = (conj ρ p a - p) * ((conj ρ p a - p) ^ 2 *
          ((1 : A) - ((l.map fun b ↦ (conj ρ p b - p) ^ 2).map
            fun y ↦ 1 - y).prod)) := by rw [mul_assoc]
    _ = (conj ρ p a - p) * (conj ρ p a - p) ^ 2 := by rw [h1]
    _ = conj ρ p a - p := h2

end Ring

/-! ## `d_g ∈ 𝓘_q` for every `g` -/

section Corona

variable (Y : ℕ → FiniteModel) [∀ n, Nonempty (Y n)]

/-- **The printed *"`𝓘_q` is inner-invariant, so `d_g ∈ 𝓘_q` for every
`g ∈ L`"*.**

The hypothesis is the printed one at the generators only, `d_a q = d_a`, which
`displacement_mul_join` supplies; the conclusion is membership for every
element of the subgroup they generate.  The induction runs on
`eq:collapse-cocycle`, so the only ambient facts used are that the ideal is a
submodule and that it absorbs multiplication on both sides.

This is what `CollapseLambdaCocycle.lambda_cocycle` takes as a hypothesis: with
it, the displacement family of an actual corona representation is a family of
ideal elements, and `β(g) = Λ(d_g)` is defined. -/
theorem displacement_mem_rankIdeal {H : Type u} [Group H] (P : MatFam Y)
    (Θ : H →* unitary (NormMatrixCStarCorona (fun n ↦ Y n)))
    (p q : NormMatrixCStarCorona (fun n ↦ Y n)) (hq : q ∈ rankIdeal Y P)
    (S : Set H) (hS : ∀ a ∈ S, (conj Θ p a - p) * q = conj Θ p a - p)
    {g : H} (hg : g ∈ Subgroup.closure S) :
    conj Θ p g - p ∈ rankIdeal Y P := by
  induction hg using Subgroup.closure_induction with
  | mem a ha =>
      have hmul : (conj Θ p a - p) * q * 1 ∈ rankIdeal Y P :=
        mul_mem_rankIdeal Y P _ _ hq
      rwa [mul_one, hS a ha] at hmul
  | one =>
      have h : conj Θ p (1 : H) - p = 0 := by rw [conj_one, sub_self]
      rw [h]
      exact Submodule.zero_mem _
  | mul x y _ _ hx hy =>
      rw [sub_conj_mul]
      exact Submodule.add_mem _ hx (mul_mem_rankIdeal Y P _ _ hy)
  | inv x _ hx =>
      have hid := sub_conj_mul Θ p x⁻¹ x
      rw [inv_mul_cancel, conj_one, sub_self] at hid
      have hval : conj Θ p x⁻¹ - p
          = -((Θ x⁻¹ : NormMatrixCStarCorona (fun n ↦ Y n)) *
              (conj Θ p x - p) *
              star ((Θ x⁻¹ : unitary (NormMatrixCStarCorona (fun n ↦ Y n))) :
                NormMatrixCStarCorona (fun n ↦ Y n))) := by
        rw [eq_neg_iff_add_eq_zero]
        exact hid.symm
      rw [hval]
      exact Submodule.neg_mem _ (mul_mem_rankIdeal Y P _ _ hx)

end Corona

end

end CollapseDisplacementIdeal
end GroupApproximation
