import GroupApproximation.Analysis.AbstractSpectralGap
import GroupApproximation.Analysis.CStarSpectralProjection

/-!
# Absorption identities for the Kazhdan projection

Fully algebra-internal absorption bricks for the strict-compression
program:

* a finite sum of positives vanishing forces each summand to vanish;
* the second-moment identity: if the unitary average of a symmetric set
  absorbs a self-adjoint idempotent on both sides, then **every
  individual unitary** of the set fixes it (`u * p = p`), and hence so
  does the whole subgroup generated by the set;
* the resolvent factorisation `1 - p = cfc h m * (1 - m)` of the
  complement of the spectral projection, which converts `m' * p = p`
  into `q * p = p` for a conjugated projection `q = u p u⁻¹` without any
  functional-calculus naturality.

Bricks of `docs/FORMALIZATION_DIRECTIVES_2026-08-15.md` §1 (b2).
-/

namespace GroupApproximation
namespace KazhdanProjectionAbsorption

open AbstractSpectralGap CStarSpectralProjection

noncomputable section

variable {A : Type*} [CStarAlgebra A]

section SumZero

variable [PartialOrder A] [StarOrderedRing A]

/-- A finite sum of positives vanishing forces each summand to vanish. -/
theorem eq_zero_of_sum_nonneg_eq_zero {ι : Type*} {s : Finset ι}
    {f : ι → A} (hf : ∀ i ∈ s, 0 ≤ f i) (hsum : ∑ i ∈ s, f i = 0) :
    ∀ i ∈ s, f i = 0 := by
  intro i hi
  have h1 : f i ≤ ∑ j ∈ s, f j := Finset.single_le_sum hf hi
  rw [hsum] at h1
  exact le_antisymm h1 (hf i hi)

end SumZero

section SecondMoment

variable [PartialOrder A] [StarOrderedRing A]
variable {G : Type*} [Group G]

/-- **Each unitary fixes the projection.**  If the unitary average of a
symmetric set absorbs a self-adjoint idempotent on both sides, every
individual unitary of the set fixes it. -/
theorem unitary_mul_eq_of_average_absorbs
    (ρ : G →* unitary A) {S : Finset G}
    (hsym : ∀ g ∈ S, g⁻¹ ∈ S)
    {p : A} (hpsa : IsSelfAdjoint p) (hp2 : p * p = p)
    (_hmp : unitaryAverage ρ S * p = p)
    (hpm : p * unitaryAverage ρ S = p) :
    ∀ g ∈ S, ((ρ g : unitary A) : A) * p = p := by
  classical
  intro g hg
  have hScard : ((S.card : ℂ)) ≠ 0 := by
    exact_mod_cast Finset.card_ne_zero.mpr ⟨g, hg⟩
  set T : A := ∑ s ∈ S, ((ρ s : unitary A) : A) with hT
  have hTavg : T = (S.card : ℂ) • unitaryAverage ρ S := by
    rw [unitaryAverage, smul_smul, mul_inv_cancel₀ hScard, one_smul]
  have hpT : p * T = (S.card : ℂ) • p := by
    rw [hTavg, mul_smul_comm, hpm]
  have hTsa : star T = T := by
    have hmsa := isSelfAdjoint_unitaryAverage ρ hsym
    rw [hTavg, star_smul, star_natCast, hmsa.star_eq]
  have hexpand : ∀ s ∈ S,
      star (((ρ s : unitary A) : A) * p - p)
        * (((ρ s : unitary A) : A) * p - p)
      = p - p * star ((ρ s : unitary A) : A) * p
        - p * ((ρ s : unitary A) : A) * p + p := by
    intro s _
    have hu : star ((ρ s : unitary A) : A) * ((ρ s : unitary A) : A) = 1 :=
      (ρ s).property.1
    rw [star_sub, star_mul, hpsa.star_eq]
    have hexp : (p * star ((ρ s : unitary A) : A) - p)
        * (((ρ s : unitary A) : A) * p - p)
        = p * (star ((ρ s : unitary A) : A) * ((ρ s : unitary A) : A)) * p
          - p * star ((ρ s : unitary A) : A) * p
          - p * ((ρ s : unitary A) : A) * p + p * p := by
      noncomm_ring
    rw [hexp, hu, mul_one, hp2]
  have ha : p * star T * p
      = ∑ s ∈ S, p * star ((ρ s : unitary A) : A) * p := by
    rw [hT, star_sum, Finset.mul_sum, Finset.sum_mul]
  have hb : p * T * p = ∑ s ∈ S, p * ((ρ s : unitary A) : A) * p := by
    rw [hT, Finset.mul_sum, Finset.sum_mul]
  have hval : p * T * p = (S.card : ℂ) • p := by
    rw [hpT, smul_mul_assoc, hp2]
  have haval : p * star T * p = (S.card : ℂ) • p := by
    rw [hTsa]
    exact hval
  have hsum0 : ∑ s ∈ S,
      star (((ρ s : unitary A) : A) * p - p)
        * (((ρ s : unitary A) : A) * p - p) = 0 := by
    rw [Finset.sum_congr rfl hexpand, Finset.sum_add_distrib,
      Finset.sum_sub_distrib, Finset.sum_sub_distrib,
      ← ha, ← hb, haval, hval, Finset.sum_const,
      ← Nat.cast_smul_eq_nsmul ℂ S.card p]
    abel
  have hvz : star (((ρ g : unitary A) : A) * p - p)
      * (((ρ g : unitary A) : A) * p - p) = 0 :=
    eq_zero_of_sum_nonneg_eq_zero
      (fun s _ => star_mul_self_nonneg _) hsum0 g hg
  have hnorm := CStarRing.norm_star_mul_self
    (x := ((ρ g : unitary A) : A) * p - p)
  rw [hvz, norm_zero] at hnorm
  have hzero : ((ρ g : unitary A) : A) * p - p = 0 :=
    norm_eq_zero.mp (mul_self_eq_zero.mp hnorm.symm)
  exact sub_eq_zero.mp hzero

omit [PartialOrder A] [StarOrderedRing A] in
/-- The subgroup generated by the set fixes the projection. -/
theorem unitary_mul_eq_of_closure
    (ρ : G →* unitary A) {S : Finset G} {p : A}
    (hgen : ∀ g ∈ S, ((ρ g : unitary A) : A) * p = p)
    {g : G} (hg : g ∈ Subgroup.closure (S : Set G)) :
    ((ρ g : unitary A) : A) * p = p := by
  induction hg using Subgroup.closure_induction with
  | mem s hs => exact hgen s hs
  | one =>
      rw [map_one]
      show (1 : A) * p = p
      rw [one_mul]
  | mul a b _ _ iha ihb =>
      rw [map_mul]
      show ((ρ a : unitary A) : A) * ((ρ b : unitary A) : A) * p = p
      rw [mul_assoc, ihb, iha]
  | inv a _ iha =>
      rw [map_inv]
      have h2 : (((ρ a)⁻¹ : unitary A) : A) * ((ρ a : unitary A) : A)
          = 1 := by
        rw [show (((ρ a)⁻¹ : unitary A) : A) * ((ρ a : unitary A) : A)
            = (((ρ a)⁻¹ * ρ a : unitary A) : A) from rfl,
          inv_mul_cancel]
        rfl
      calc (((ρ a)⁻¹ : unitary A) : A) * p
          = (((ρ a)⁻¹ : unitary A) : A)
            * (((ρ a : unitary A) : A) * p) := by rw [iha]
        _ = ((((ρ a)⁻¹ : unitary A) : A)
            * ((ρ a : unitary A) : A)) * p := by rw [mul_assoc]
        _ = p := by rw [h2, one_mul]

end SecondMoment

section Resolvent

/-- The gap resolvent: `(1 - x)⁻¹` at or below the gap, `0` above it. -/
def gapResolvent (c : ℝ) : ℝ → ℝ := fun x => if x ≤ c then (1 - x)⁻¹ else 0

theorem continuousOn_gapResolvent {m : A} {c : ℝ} (hc : c < 1)
    (hgap : ∀ μ ∈ spectrum ℝ m, μ ≤ c ∨ μ = 1) :
    ContinuousOn (gapResolvent c) (spectrum ℝ m) := by
  intro x hx
  have hball : spectrum ℝ m ∩ Metric.ball x (1 - c)
      ∈ nhdsWithin x (spectrum ℝ m) :=
    inter_mem_nhdsWithin _ (Metric.ball_mem_nhds x (by linarith))
  rcases hgap x hx with hxc | hx1
  · have hev : gapResolvent c =ᶠ[nhdsWithin x (spectrum ℝ m)]
        fun y => (1 - y)⁻¹ := by
      refine Filter.eventuallyEq_of_mem hball ?_
      rintro y ⟨hys, hyb⟩
      rcases hgap y hys with hyc | hy1
      · exact if_pos hyc
      · exfalso
        rw [Metric.mem_ball, Real.dist_eq, hy1] at hyb
        have habs : 1 - x < 1 - c := lt_of_le_of_lt (le_abs_self _) hyb
        linarith
    have hcont : ContinuousWithinAt (fun y : ℝ => (1 - y)⁻¹)
        (spectrum ℝ m) x := by
      apply ContinuousAt.continuousWithinAt
      apply ContinuousAt.inv₀
      · exact (continuous_const.sub continuous_id).continuousAt
      · intro h0
        have : x = 1 := by linarith [sub_eq_zero.mp h0]
        linarith
    exact hcont.congr_of_eventuallyEq hev (if_pos hxc)
  · have hev : gapResolvent c =ᶠ[nhdsWithin x (spectrum ℝ m)]
        fun _ => (0 : ℝ) := by
      refine Filter.eventuallyEq_of_mem hball ?_
      rintro y ⟨hys, hyb⟩
      rcases hgap y hys with hyc | hy1
      · exfalso
        rw [Metric.mem_ball, Real.dist_eq, hx1] at hyb
        have h1 : 1 - y ≤ |1 - y| := le_abs_self _
        rw [abs_sub_comm] at h1
        have habs : 1 - y < 1 - c := lt_of_le_of_lt h1 hyb
        linarith
      · rw [hy1]
        exact if_neg (not_le.mpr hc)
    refine (continuousWithinAt_const).congr_of_eventuallyEq hev ?_
    rw [hx1]
    exact if_neg (not_le.mpr hc)

/-- **Resolvent factorisation** of the complement of the spectral
projection: `1 - p = cfc h m * (1 - m)`. -/
theorem one_sub_spectralProjection_eq (m : A) {c : ℝ}
    (hm : IsSelfAdjoint m) (hc : c < 1)
    (hgap : ∀ μ ∈ spectrum ℝ m, μ ≤ c ∨ μ = 1) :
    (1 : A) - spectralProjection m c
      = cfc (gapResolvent c) m * ((1 : A) - m) := by
  have hind := continuousOn_gapIndicator hc hgap
  have hres := continuousOn_gapResolvent hc hgap
  have hone : (1 : A) = cfc (fun _ : ℝ => (1 : ℝ)) m := (cfc_one ℝ m).symm
  have hid : m = cfc (fun x : ℝ => x) m := (cfc_id ℝ m).symm
  have h1 : (1 : A) - spectralProjection m c
      = cfc (fun x => 1 - gapIndicator c x) m := by
    rw [spectralProjection, cfc_sub (fun _ : ℝ => (1 : ℝ))
      (gapIndicator c) m continuousOn_const hind]
    conv_lhs => rw [hone]
  have h2 : (1 : A) - m = cfc (fun x : ℝ => 1 - x) m := by
    rw [cfc_sub (fun _ : ℝ => (1 : ℝ)) (fun x : ℝ => x) m
      continuousOn_const (continuousOn_id' _)]
    conv_lhs => rw [hid, hone]
  rw [h1, h2, ← cfc_mul _ _ m hres (by fun_prop)]
  apply cfc_congr
  intro x hx
  show 1 - gapIndicator c x = gapResolvent c x * (1 - x)
  rcases hgap x hx with hxc | hx1
  · rw [gapIndicator_of_le hxc, sub_zero]
    show (1 : ℝ) = (if x ≤ c then (1 - x)⁻¹ else 0) * (1 - x)
    rw [if_pos hxc,
      inv_mul_cancel₀ (by linarith : (1 : ℝ) - x ≠ 0)]
  · subst hx1
    rw [gapIndicator_one hc, sub_self]
    show (0 : ℝ) = gapResolvent c 1 * 0
    rw [mul_zero]

/-- **Conjugated absorption**: if the conjugated average absorbs `p` on
the left, then the conjugated spectral projection absorbs `p`.  No
functional-calculus naturality is used: the complement factors through
`1 - m` by the resolvent identity, and the factor annihilates `p`. -/
theorem conjugated_projection_absorbs {m p u : A} {c : ℝ}
    (hm : IsSelfAdjoint m) (hc : c < 1)
    (hgap : ∀ μ ∈ spectrum ℝ m, μ ≤ c ∨ μ = 1)
    (h1 : star u * u = 1) (h2 : u * star u = 1)
    (hmp : (u * m * star u) * p = p) :
    (u * spectralProjection m c * star u) * p = p := by
  have hx : ((1 : A) - m) * (star u * p) = 0 := by
    have hb : u * (((1 : A) - m) * (star u * p))
        = ((1 : A) - u * m * star u) * p := by
      rw [sub_mul, sub_mul, one_mul, one_mul, mul_sub]
      congr 1
      · rw [← mul_assoc, h2, one_mul]
      · rw [← mul_assoc, ← mul_assoc]
    have ha : u * (((1 : A) - m) * (star u * p)) = 0 := by
      rw [hb, sub_mul, one_mul, hmp, sub_self]
    have hc2 := congrArg (fun z => star u * z) ha
    rw [← mul_assoc, h1, one_mul, mul_zero] at hc2
    exact hc2
  have hfac := one_sub_spectralProjection_eq m hm hc hgap
  have hqp : ((1 : A) - u * spectralProjection m c * star u) * p = 0 := by
    have hone : (1 : A) - u * spectralProjection m c * star u
        = u * ((1 : A) - spectralProjection m c) * star u := by
      rw [mul_sub, sub_mul, mul_one, h2]
    rw [hone, hfac]
    have hassoc : u * (cfc (gapResolvent c) m * ((1 : A) - m)) * star u * p
        = u * cfc (gapResolvent c) m * (((1 : A) - m) * (star u * p)) := by
      noncomm_ring
    rw [hassoc, hx, mul_zero]
  rw [sub_mul, one_mul] at hqp
  exact (sub_eq_zero.mp hqp).symm

end Resolvent

/-! ## Normality, algebraically

`thm:normal-kazhdan`: "For `g ∈ H̄` the projection `π(g)Pπ(g)*` has range
`Fix π(gK̄g⁻¹) = Fix π(K̄)` by normality, so `P` and `q` commute with `π(H̄)`
exactly."

The printed argument is about ranges, hence about vectors.  It has an
algebra-internal counterpart that needs no ambient Hilbert space, no Dedekind
finiteness, and no injectivity of the representation, and that is what is proved
here — so the identity is available in the norm ultraproduct itself, where the
printed `P` lives, and not only in the operators on the Hilbert-space
ultraproduct.

The three bricks are already above.  `unitary_mul_eq_of_average_absorbs` turns
the two absorption identities of the spectral projection into "every unitary of
the Kazhdan set fixes `P`"; `unitary_mul_eq_of_closure` extends that to the
subgroup the set generates, which is the printed `K̄`; and
`conjugated_projection_absorbs` converts an absorption statement for the
conjugated *average* into one for the conjugated *projection*.  Normality is
spent in exactly one place: it says the conjugates of the Kazhdan set still lie
in `K̄`, so the conjugated average still fixes `P`. -/

section Normality

variable [PartialOrder A] [StarOrderedRing A]
variable {G : Type*} [Group G]

omit [PartialOrder A] [StarOrderedRing A] in
/-- **The conjugated average still fixes `P`.**  This is where normality is
spent, and it is the only place: `π(g)π(a)π(g)* = π(gag⁻¹)` and `gag⁻¹` is
again in the subgroup generated by the Kazhdan set. -/
theorem conj_unitaryAverage_mul_eq (ρ : G →* unitary A) {S : Finset G}
    (hS : S.Nonempty) {p : A}
    (hclosure : ∀ k ∈ Subgroup.closure (S : Set G),
      ((ρ k : unitary A) : A) * p = p)
    (hnorm : ∀ g : G, ∀ k ∈ Subgroup.closure (S : Set G),
      g * k * g⁻¹ ∈ Subgroup.closure (S : Set G)) (g : G) :
    (((ρ g : unitary A) : A) * unitaryAverage ρ S
        * star ((ρ g : unitary A) : A)) * p = p := by
  classical
  have hScard : ((S.card : ℂ)) ≠ 0 := by
    exact_mod_cast Finset.card_ne_zero.mpr hS
  have hstar : star ((ρ g : unitary A) : A) = ((ρ g⁻¹ : unitary A) : A) :=
    star_unitary_coe ρ g
  have hterm : ∀ a ∈ S, ((ρ g : unitary A) : A) * ((ρ a : unitary A) : A)
      * ((ρ g⁻¹ : unitary A) : A) * p = p := by
    intro a ha
    have hmul : ((ρ g : unitary A) : A) * ((ρ a : unitary A) : A)
        * ((ρ g⁻¹ : unitary A) : A)
        = ((ρ (g * a * g⁻¹) : unitary A) : A) := by
      rw [map_mul, map_mul]
      rfl
    rw [hmul]
    exact hclosure _ (hnorm g a (Subgroup.subset_closure (Finset.mem_coe.2 ha)))
  have hexpand : ((ρ g : unitary A) : A) * unitaryAverage ρ S
        * ((ρ g⁻¹ : unitary A) : A) * p
      = ((S.card : ℂ))⁻¹ • ∑ a ∈ S, (((ρ g : unitary A) : A)
          * ((ρ a : unitary A) : A) * ((ρ g⁻¹ : unitary A) : A) * p) := by
    rw [unitaryAverage, mul_smul_comm, smul_mul_assoc, smul_mul_assoc,
      Finset.mul_sum, Finset.sum_mul, Finset.sum_mul]
  rw [hstar, hexpand, Finset.sum_congr rfl hterm, Finset.sum_const,
    ← Nat.cast_smul_eq_nsmul ℂ S.card p, smul_smul, inv_mul_cancel₀ hScard,
    one_smul]

/-- **`π(g) P π(g)* = P`, with no vectors.**

The printed conjugation identity of `thm:normal-kazhdan`, proved inside the
algebra the printed `P` belongs to.  `hnorm` is the printed `gK̄g⁻¹ = K̄` with
`K̄` the subgroup generated by the Kazhdan set, which is what the print takes `S`
to generate. -/
theorem conj_spectralProjection_eq_of_normal (ρ : G →* unitary A)
    {S : Finset G} (hS : S.Nonempty) (hsym : ∀ g ∈ S, g⁻¹ ∈ S) {c : ℝ}
    (hc : c < 1)
    (hgap : ∀ μ ∈ spectrum ℝ (unitaryAverage ρ S), μ ≤ c ∨ μ = 1)
    (hnorm : ∀ g : G, ∀ k ∈ Subgroup.closure (S : Set G),
      g * k * g⁻¹ ∈ Subgroup.closure (S : Set G)) (g : G) :
    ((ρ g : unitary A) : A) * spectralProjection (unitaryAverage ρ S) c
        * star ((ρ g : unitary A) : A)
      = spectralProjection (unitaryAverage ρ S) c := by
  have hm : IsSelfAdjoint (unitaryAverage ρ S) :=
    isSelfAdjoint_unitaryAverage ρ hsym
  have hPsa : IsSelfAdjoint (spectralProjection (unitaryAverage ρ S) c) :=
    isSelfAdjoint_spectralProjection _
  have hP2 : spectralProjection (unitaryAverage ρ S) c
      * spectralProjection (unitaryAverage ρ S) c
      = spectralProjection (unitaryAverage ρ S) c :=
    isIdempotentElem_spectralProjection _ hm hc hgap
  have hclosure : ∀ k ∈ Subgroup.closure (S : Set G),
      ((ρ k : unitary A) : A) * spectralProjection (unitaryAverage ρ S) c
        = spectralProjection (unitaryAverage ρ S) c := fun k hk ↦
    unitary_mul_eq_of_closure ρ
      (unitary_mul_eq_of_average_absorbs ρ hsym hPsa hP2
        (mul_spectralProjection _ hm hc hgap)
        (spectralProjection_mul _ hm hc hgap)) hk
  have hstarg : star ((ρ g : unitary A) : A) = ((ρ g⁻¹ : unitary A) : A) :=
    star_unitary_coe ρ g
  have hstargi : star ((ρ g⁻¹ : unitary A) : A) = ((ρ g : unitary A) : A) := by
    have h := star_unitary_coe ρ g⁻¹
    rwa [inv_inv] at h
  have hab : ((ρ g : unitary A) : A) * ((ρ g⁻¹ : unitary A) : A) = (1 : A) := by
    have h : (ρ g : unitary A) * (ρ g⁻¹ : unitary A) = 1 := by
      rw [← map_mul, mul_inv_cancel, map_one]
    exact congrArg (fun z : unitary A ↦ (z : A)) h
  -- `Q P = P`, from the conjugated average fixing `P`.
  have hi : (((ρ g : unitary A) : A)
        * spectralProjection (unitaryAverage ρ S) c
        * star ((ρ g : unitary A) : A))
      * spectralProjection (unitaryAverage ρ S) c
      = spectralProjection (unitaryAverage ρ S) c :=
    conjugated_projection_absorbs hm hc hgap (ρ g).2.1 (ρ g).2.2
      (conj_unitaryAverage_mul_eq ρ hS hclosure hnorm g)
  -- the same at `g⁻¹`, then conjugated back: `P Q = Q`.
  have hi' : ((((ρ g⁻¹ : unitary A) : A)
        * spectralProjection (unitaryAverage ρ S) c
        * ((ρ g : unitary A) : A))
      * spectralProjection (unitaryAverage ρ S) c)
      = spectralProjection (unitaryAverage ρ S) c := by
    have h := conjugated_projection_absorbs (u := ((ρ g⁻¹ : unitary A) : A))
      hm hc hgap (ρ g⁻¹).2.1 (ρ g⁻¹).2.2
      (conj_unitaryAverage_mul_eq ρ hS hclosure hnorm g⁻¹)
    rwa [hstargi] at h
  have hii : spectralProjection (unitaryAverage ρ S) c
      * (((ρ g : unitary A) : A) * spectralProjection (unitaryAverage ρ S) c
        * ((ρ g⁻¹ : unitary A) : A))
      = ((ρ g : unitary A) : A) * spectralProjection (unitaryAverage ρ S) c
        * ((ρ g⁻¹ : unitary A) : A) := by
    have h := congrArg (fun z : A ↦ ((ρ g : unitary A) : A) * z
      * ((ρ g⁻¹ : unitary A) : A)) hi'
    calc spectralProjection (unitaryAverage ρ S) c
          * (((ρ g : unitary A) : A)
            * spectralProjection (unitaryAverage ρ S) c
            * ((ρ g⁻¹ : unitary A) : A))
        = (((ρ g : unitary A) : A) * ((ρ g⁻¹ : unitary A) : A))
            * spectralProjection (unitaryAverage ρ S) c
            * (((ρ g : unitary A) : A)
              * spectralProjection (unitaryAverage ρ S) c
              * ((ρ g⁻¹ : unitary A) : A)) := by rw [hab, one_mul]
      _ = ((ρ g : unitary A) : A)
            * ((((ρ g⁻¹ : unitary A) : A)
              * spectralProjection (unitaryAverage ρ S) c
              * ((ρ g : unitary A) : A))
              * spectralProjection (unitaryAverage ρ S) c)
            * ((ρ g⁻¹ : unitary A) : A) := by noncomm_ring
      _ = ((ρ g : unitary A) : A)
            * spectralProjection (unitaryAverage ρ S) c
            * ((ρ g⁻¹ : unitary A) : A) := h
  have hQsa : IsSelfAdjoint (((ρ g : unitary A) : A)
      * spectralProjection (unitaryAverage ρ S) c
      * star ((ρ g : unitary A) : A)) := by
    rw [IsSelfAdjoint, star_mul, star_mul, star_star, hPsa.star_eq, ← mul_assoc]
  have hstar_hi : spectralProjection (unitaryAverage ρ S) c
      * (((ρ g : unitary A) : A)
        * spectralProjection (unitaryAverage ρ S) c
        * star ((ρ g : unitary A) : A))
      = spectralProjection (unitaryAverage ρ S) c := by
    have h := congrArg star hi
    rwa [star_mul, hPsa.star_eq, hQsa.star_eq] at h
  rw [hstarg] at hQsa hstar_hi ⊢
  exact hii.symm.trans hstar_hi

/-- **`P` commutes with `π(g)` exactly.**  The printed consequence. -/
theorem commute_spectralProjection_of_normal (ρ : G →* unitary A)
    {S : Finset G} (hS : S.Nonempty) (hsym : ∀ g ∈ S, g⁻¹ ∈ S) {c : ℝ}
    (hc : c < 1)
    (hgap : ∀ μ ∈ spectrum ℝ (unitaryAverage ρ S), μ ≤ c ∨ μ = 1)
    (hnorm : ∀ g : G, ∀ k ∈ Subgroup.closure (S : Set G),
      g * k * g⁻¹ ∈ Subgroup.closure (S : Set G)) (g : G) :
    ((ρ g : unitary A) : A) * spectralProjection (unitaryAverage ρ S) c
      = spectralProjection (unitaryAverage ρ S) c
        * ((ρ g : unitary A) : A) := by
  have hconj := conj_spectralProjection_eq_of_normal ρ hS hsym hc hgap hnorm g
  have hus : star ((ρ g : unitary A) : A) * ((ρ g : unitary A) : A) = 1 :=
    (ρ g).2.1
  calc ((ρ g : unitary A) : A) * spectralProjection (unitaryAverage ρ S) c
      = ((ρ g : unitary A) : A) * spectralProjection (unitaryAverage ρ S) c
          * (star ((ρ g : unitary A) : A) * ((ρ g : unitary A) : A)) := by
        rw [hus, mul_one]
    _ = (((ρ g : unitary A) : A) * spectralProjection (unitaryAverage ρ S) c
          * star ((ρ g : unitary A) : A)) * ((ρ g : unitary A) : A) := by
        noncomm_ring
    _ = spectralProjection (unitaryAverage ρ S) c
          * ((ρ g : unitary A) : A) := by rw [hconj]

/-- **`q = 1 − P` commutes with `π(g)` exactly.** -/
theorem commute_one_sub_spectralProjection_of_normal (ρ : G →* unitary A)
    {S : Finset G} (hS : S.Nonempty) (hsym : ∀ g ∈ S, g⁻¹ ∈ S) {c : ℝ}
    (hc : c < 1)
    (hgap : ∀ μ ∈ spectrum ℝ (unitaryAverage ρ S), μ ≤ c ∨ μ = 1)
    (hnorm : ∀ g : G, ∀ k ∈ Subgroup.closure (S : Set G),
      g * k * g⁻¹ ∈ Subgroup.closure (S : Set G)) (g : G) :
    ((ρ g : unitary A) : A)
        * ((1 : A) - spectralProjection (unitaryAverage ρ S) c)
      = ((1 : A) - spectralProjection (unitaryAverage ρ S) c)
        * ((ρ g : unitary A) : A) := by
  rw [mul_sub, sub_mul, one_mul, mul_one,
    commute_spectralProjection_of_normal ρ hS hsym hc hgap hnorm g]

end Normality

/-! ## The compression of the average to the complementary corner

`thm:abstract-nk`, in the compression paragraph:

> The compression of `h` to the corner satisfies `q h q ≤ θ q` in `B_ω`.

This is where the gap is cashed as an *order* statement rather than a spectral
one, and it is what the coordinate estimate of the next step is the image of.
It is algebra-internal: `q = 1 − χ_{{1}}(h)` is itself a continuous function of
`h`, so both sides are, and the inequality is the pointwise inequality of the
two functions on the spectrum.  On the spectrum the gap indicator takes only the
values `0` and `1`, so `q` is idempotent there and the difference collapses to
`(1 − χ)(t)·(θ − t)`: at `t ≤ θ` that is `θ − t ≥ 0`, and at the isolated point
`t = 1` it is `0`. -/

section Compression

variable [PartialOrder A] [StarOrderedRing A]

/-- **`q h q ≤ θ q`**, for the complementary corner of the spectral projection
at an isolated top of the spectrum. -/
theorem compression_le_gap (m : A) {c : ℝ} (hm : IsSelfAdjoint m) (hc : c < 1)
    (hgap : ∀ μ ∈ spectrum ℝ m, μ ≤ c ∨ μ = 1) :
    ((1 : A) - spectralProjection m c) * m * ((1 : A) - spectralProjection m c)
      ≤ algebraMap ℝ A c * ((1 : A) - spectralProjection m c) := by
  have hcont : ContinuousOn (gapIndicator c) (spectrum ℝ m) :=
    continuousOn_gapIndicator hc hgap
  have hFcont : ContinuousOn (fun t : ℝ ↦ 1 - gapIndicator c t)
      (spectrum ℝ m) := continuousOn_const.sub hcont
  have hone : (1 : A) = cfc (fun _ : ℝ ↦ (1 : ℝ)) m := (cfc_one ℝ m).symm
  have hq : cfc (fun t : ℝ ↦ 1 - gapIndicator c t) m
      = (1 : A) - spectralProjection m c := by
    rw [cfc_sub (fun _ : ℝ ↦ (1 : ℝ)) (gapIndicator c) m continuousOn_const hcont,
      spectralProjection]
    conv_rhs => rw [hone]
  have hprod : cfc (fun t : ℝ ↦ (1 - gapIndicator c t) * t
        * (1 - gapIndicator c t)) m
      = cfc (fun t : ℝ ↦ 1 - gapIndicator c t) m * m
        * cfc (fun t : ℝ ↦ 1 - gapIndicator c t) m := by
    rw [cfc_mul (fun t : ℝ ↦ (1 - gapIndicator c t) * t)
        (fun t : ℝ ↦ 1 - gapIndicator c t) m
        (hFcont.mul (continuousOn_id' _)) hFcont,
      cfc_mul (fun t : ℝ ↦ 1 - gapIndicator c t) (fun t : ℝ ↦ t) m
        hFcont (continuousOn_id' _), cfc_id' ℝ m]
  have hscal : cfc (fun t : ℝ ↦ c * (1 - gapIndicator c t)) m
      = algebraMap ℝ A c * cfc (fun t : ℝ ↦ 1 - gapIndicator c t) m := by
    rw [cfc_mul (fun _ : ℝ ↦ c) (fun t : ℝ ↦ 1 - gapIndicator c t) m
      continuousOn_const hFcont, cfc_const c m hm]
  rw [← sub_nonneg, ← hq, ← hprod, ← hscal,
    ← cfc_sub (fun t : ℝ ↦ c * (1 - gapIndicator c t))
      (fun t : ℝ ↦ (1 - gapIndicator c t) * t * (1 - gapIndicator c t)) m
      (continuousOn_const.mul hFcont)
      ((hFcont.mul (continuousOn_id' _)).mul hFcont)]
  refine cfc_nonneg fun t ht ↦ ?_
  rcases hgap t ht with hle | h1
  · rw [gapIndicator_of_le hle]
    nlinarith
  · rw [h1, gapIndicator_one hc]
    norm_num

end Compression

end

end KazhdanProjectionAbsorption
end GroupApproximation
