import GroupApproximation.Analysis.AbstractSpectralGap
import GroupApproximation.Analysis.CStarSpectralProjection

/-!
# Absorption identities for the Kazhdan projection

Fully algebra-internal absorption bricks for the strict-compression
program:

* a finite sum of positives vanishing forces each summand to vanish;
* the second-moment identity: if the unitary average of a symmetric set
  absorbs a self-adjoint idempotent on both sides, then **every
  individual unitary** of the set fixes it (`u * p = p`), and hence so
  does the whole subgroup generated by the set;
* the resolvent factorisation `1 - p = cfc h m * (1 - m)` of the
  complement of the spectral projection, which converts `m' * p = p`
  into `q * p = p` for a conjugated projection `q = u p u⁻¹` without any
  functional-calculus naturality.

Bricks of `docs/FORMALIZATION_DIRECTIVES_2026-08-15.md` §1 (b2).
-/

namespace GroupApproximation
namespace KazhdanProjectionAbsorption

open AbstractSpectralGap CStarSpectralProjection

noncomputable section

variable {A : Type*} [CStarAlgebra A]

section SumZero

variable [PartialOrder A] [StarOrderedRing A]

/-- A finite sum of positives vanishing forces each summand to vanish. -/
theorem eq_zero_of_sum_nonneg_eq_zero {ι : Type*} {s : Finset ι}
    {f : ι → A} (hf : ∀ i ∈ s, 0 ≤ f i) (hsum : ∑ i ∈ s, f i = 0) :
    ∀ i ∈ s, f i = 0 := by
  intro i hi
  have h1 : f i ≤ ∑ j ∈ s, f j := Finset.single_le_sum hf hi
  rw [hsum] at h1
  exact le_antisymm h1 (hf i hi)

end SumZero

section SecondMoment

variable [PartialOrder A] [StarOrderedRing A]
variable {G : Type*} [Group G]

/-- **Each unitary fixes the projection.**  If the unitary average of a
symmetric set absorbs a self-adjoint idempotent on both sides, every
individual unitary of the set fixes it. -/
theorem unitary_mul_eq_of_average_absorbs
    (ρ : G →* unitary A) {S : Finset G}
    (hsym : ∀ g ∈ S, g⁻¹ ∈ S)
    {p : A} (hpsa : IsSelfAdjoint p) (hp2 : p * p = p)
    (_hmp : unitaryAverage ρ S * p = p)
    (hpm : p * unitaryAverage ρ S = p) :
    ∀ g ∈ S, ((ρ g : unitary A) : A) * p = p := by
  classical
  intro g hg
  have hScard : ((S.card : ℂ)) ≠ 0 := by
    exact_mod_cast Finset.card_ne_zero.mpr ⟨g, hg⟩
  set T : A := ∑ s ∈ S, ((ρ s : unitary A) : A) with hT
  have hTavg : T = (S.card : ℂ) • unitaryAverage ρ S := by
    rw [unitaryAverage, smul_smul, mul_inv_cancel₀ hScard, one_smul]
  have hpT : p * T = (S.card : ℂ) • p := by
    rw [hTavg, mul_smul_comm, hpm]
  have hTsa : star T = T := by
    have hmsa := isSelfAdjoint_unitaryAverage ρ hsym
    rw [hTavg, star_smul, star_natCast, hmsa.star_eq]
  have hexpand : ∀ s ∈ S,
      star (((ρ s : unitary A) : A) * p - p)
        * (((ρ s : unitary A) : A) * p - p)
      = p - p * star ((ρ s : unitary A) : A) * p
        - p * ((ρ s : unitary A) : A) * p + p := by
    intro s _
    have hu : star ((ρ s : unitary A) : A) * ((ρ s : unitary A) : A) = 1 :=
      (ρ s).property.1
    rw [star_sub, star_mul, hpsa.star_eq]
    have hexp : (p * star ((ρ s : unitary A) : A) - p)
        * (((ρ s : unitary A) : A) * p - p)
        = p * (star ((ρ s : unitary A) : A) * ((ρ s : unitary A) : A)) * p
          - p * star ((ρ s : unitary A) : A) * p
          - p * ((ρ s : unitary A) : A) * p + p * p := by
      noncomm_ring
    rw [hexp, hu, mul_one, hp2]
  have ha : p * star T * p
      = ∑ s ∈ S, p * star ((ρ s : unitary A) : A) * p := by
    rw [hT, star_sum, Finset.mul_sum, Finset.sum_mul]
  have hb : p * T * p = ∑ s ∈ S, p * ((ρ s : unitary A) : A) * p := by
    rw [hT, Finset.mul_sum, Finset.sum_mul]
  have hval : p * T * p = (S.card : ℂ) • p := by
    rw [hpT, smul_mul_assoc, hp2]
  have haval : p * star T * p = (S.card : ℂ) • p := by
    rw [hTsa]
    exact hval
  have hsum0 : ∑ s ∈ S,
      star (((ρ s : unitary A) : A) * p - p)
        * (((ρ s : unitary A) : A) * p - p) = 0 := by
    rw [Finset.sum_congr rfl hexpand, Finset.sum_add_distrib,
      Finset.sum_sub_distrib, Finset.sum_sub_distrib,
      ← ha, ← hb, haval, hval, Finset.sum_const,
      ← Nat.cast_smul_eq_nsmul ℂ S.card p]
    abel
  have hvz : star (((ρ g : unitary A) : A) * p - p)
      * (((ρ g : unitary A) : A) * p - p) = 0 :=
    eq_zero_of_sum_nonneg_eq_zero
      (fun s _ => star_mul_self_nonneg _) hsum0 g hg
  have hnorm := CStarRing.norm_star_mul_self
    (x := ((ρ g : unitary A) : A) * p - p)
  rw [hvz, norm_zero] at hnorm
  have hzero : ((ρ g : unitary A) : A) * p - p = 0 :=
    norm_eq_zero.mp (mul_self_eq_zero.mp hnorm.symm)
  exact sub_eq_zero.mp hzero

omit [PartialOrder A] [StarOrderedRing A] in
/-- The subgroup generated by the set fixes the projection. -/
theorem unitary_mul_eq_of_closure
    (ρ : G →* unitary A) {S : Finset G} {p : A}
    (hgen : ∀ g ∈ S, ((ρ g : unitary A) : A) * p = p)
    {g : G} (hg : g ∈ Subgroup.closure (S : Set G)) :
    ((ρ g : unitary A) : A) * p = p := by
  induction hg using Subgroup.closure_induction with
  | mem s hs => exact hgen s hs
  | one =>
      rw [map_one]
      show (1 : A) * p = p
      rw [one_mul]
  | mul a b _ _ iha ihb =>
      rw [map_mul]
      show ((ρ a : unitary A) : A) * ((ρ b : unitary A) : A) * p = p
      rw [mul_assoc, ihb, iha]
  | inv a _ iha =>
      rw [map_inv]
      have h2 : (((ρ a)⁻¹ : unitary A) : A) * ((ρ a : unitary A) : A)
          = 1 := by
        rw [show (((ρ a)⁻¹ : unitary A) : A) * ((ρ a : unitary A) : A)
            = (((ρ a)⁻¹ * ρ a : unitary A) : A) from rfl,
          inv_mul_cancel]
        rfl
      calc (((ρ a)⁻¹ : unitary A) : A) * p
          = (((ρ a)⁻¹ : unitary A) : A)
            * (((ρ a : unitary A) : A) * p) := by rw [iha]
        _ = ((((ρ a)⁻¹ : unitary A) : A)
            * ((ρ a : unitary A) : A)) * p := by rw [mul_assoc]
        _ = p := by rw [h2, one_mul]

end SecondMoment

section Resolvent

/-- The gap resolvent: `(1 - x)⁻¹` at or below the gap, `0` above it. -/
def gapResolvent (c : ℝ) : ℝ → ℝ := fun x => if x ≤ c then (1 - x)⁻¹ else 0

theorem continuousOn_gapResolvent {m : A} {c : ℝ} (hc : c < 1)
    (hgap : ∀ μ ∈ spectrum ℝ m, μ ≤ c ∨ μ = 1) :
    ContinuousOn (gapResolvent c) (spectrum ℝ m) := by
  intro x hx
  have hball : spectrum ℝ m ∩ Metric.ball x (1 - c)
      ∈ nhdsWithin x (spectrum ℝ m) :=
    inter_mem_nhdsWithin _ (Metric.ball_mem_nhds x (by linarith))
  rcases hgap x hx with hxc | hx1
  · have hev : gapResolvent c =ᶠ[nhdsWithin x (spectrum ℝ m)]
        fun y => (1 - y)⁻¹ := by
      refine Filter.eventuallyEq_of_mem hball ?_
      rintro y ⟨hys, hyb⟩
      rcases hgap y hys with hyc | hy1
      · exact if_pos hyc
      · exfalso
        rw [Metric.mem_ball, Real.dist_eq, hy1] at hyb
        have habs : 1 - x < 1 - c := lt_of_le_of_lt (le_abs_self _) hyb
        linarith
    have hcont : ContinuousWithinAt (fun y : ℝ => (1 - y)⁻¹)
        (spectrum ℝ m) x := by
      apply ContinuousAt.continuousWithinAt
      apply ContinuousAt.inv₀
      · exact (continuous_const.sub continuous_id).continuousAt
      · intro h0
        have : x = 1 := by linarith [sub_eq_zero.mp h0]
        linarith
    exact hcont.congr_of_eventuallyEq hev (if_pos hxc)
  · have hev : gapResolvent c =ᶠ[nhdsWithin x (spectrum ℝ m)]
        fun _ => (0 : ℝ) := by
      refine Filter.eventuallyEq_of_mem hball ?_
      rintro y ⟨hys, hyb⟩
      rcases hgap y hys with hyc | hy1
      · exfalso
        rw [Metric.mem_ball, Real.dist_eq, hx1] at hyb
        have h1 : 1 - y ≤ |1 - y| := le_abs_self _
        rw [abs_sub_comm] at h1
        have habs : 1 - y < 1 - c := lt_of_le_of_lt h1 hyb
        linarith
      · rw [hy1]
        exact if_neg (not_le.mpr hc)
    refine (continuousWithinAt_const).congr_of_eventuallyEq hev ?_
    rw [hx1]
    exact if_neg (not_le.mpr hc)

/-- **Resolvent factorisation** of the complement of the spectral
projection: `1 - p = cfc h m * (1 - m)`. -/
theorem one_sub_spectralProjection_eq (m : A) {c : ℝ}
    (hm : IsSelfAdjoint m) (hc : c < 1)
    (hgap : ∀ μ ∈ spectrum ℝ m, μ ≤ c ∨ μ = 1) :
    (1 : A) - spectralProjection m c
      = cfc (gapResolvent c) m * ((1 : A) - m) := by
  have hind := continuousOn_gapIndicator hc hgap
  have hres := continuousOn_gapResolvent hc hgap
  have hone : (1 : A) = cfc (fun _ : ℝ => (1 : ℝ)) m := (cfc_one ℝ m).symm
  have hid : m = cfc (fun x : ℝ => x) m := (cfc_id ℝ m).symm
  have h1 : (1 : A) - spectralProjection m c
      = cfc (fun x => 1 - gapIndicator c x) m := by
    rw [spectralProjection, ← cfc_sub (fun _ : ℝ => (1 : ℝ))
      (gapIndicator c) m continuousOn_const hind]
    conv_lhs => rw [hone]
  have h2 : (1 : A) - m = cfc (fun x : ℝ => 1 - x) m := by
    rw [cfc_sub (fun _ : ℝ => (1 : ℝ)) (fun x : ℝ => x) m
      continuousOn_const (continuousOn_id' _)]
    conv_lhs => rw [hid, hone]
  rw [h1, h2, ← cfc_mul _ _ m hres (by fun_prop)]
  apply cfc_congr
  intro x hx
  show 1 - gapIndicator c x = gapResolvent c x * (1 - x)
  rcases hgap x hx with hxc | hx1
  · rw [gapIndicator_of_le hxc, sub_zero]
    show (1 : ℝ) = (if x ≤ c then (1 - x)⁻¹ else 0) * (1 - x)
    rw [if_pos hxc,
      inv_mul_cancel₀ (by linarith : (1 : ℝ) - x ≠ 0)]
  · subst hx1
    rw [gapIndicator_one hc, sub_self]
    show (0 : ℝ) = gapResolvent c 1 * 0
    rw [mul_zero]

/-- **Conjugated absorption**: if the conjugated average absorbs `p` on
the left, then the conjugated spectral projection absorbs `p`.  No
functional-calculus naturality is used: the complement factors through
`1 - m` by the resolvent identity, and the factor annihilates `p`. -/
theorem conjugated_projection_absorbs {m p u : A} {c : ℝ}
    (hm : IsSelfAdjoint m) (hc : c < 1)
    (hgap : ∀ μ ∈ spectrum ℝ m, μ ≤ c ∨ μ = 1)
    (h1 : star u * u = 1) (h2 : u * star u = 1)
    (hmp : (u * m * star u) * p = p) :
    (u * spectralProjection m c * star u) * p = p := by
  have hx : ((1 : A) - m) * (star u * p) = 0 := by
    have hb : u * (((1 : A) - m) * (star u * p))
        = ((1 : A) - u * m * star u) * p := by
      rw [sub_mul, sub_mul, one_mul, one_mul, mul_sub]
      congr 1
      · rw [← mul_assoc, h2, one_mul]
      · rw [← mul_assoc, ← mul_assoc]
    have ha : u * (((1 : A) - m) * (star u * p)) = 0 := by
      rw [hb, sub_mul, one_mul, hmp, sub_self]
    have hc2 := congrArg (fun z => star u * z) ha
    rw [← mul_assoc, h1, one_mul, mul_zero] at hc2
    exact hc2
  have hfac := one_sub_spectralProjection_eq m hm hc hgap
  have hqp : ((1 : A) - u * spectralProjection m c * star u) * p = 0 := by
    have hone : (1 : A) - u * spectralProjection m c * star u
        = u * ((1 : A) - spectralProjection m c) * star u := by
      rw [mul_sub, sub_mul, mul_one, h2]
    rw [hone, hfac]
    have hassoc : u * (cfc (gapResolvent c) m * ((1 : A) - m)) * star u * p
        = u * cfc (gapResolvent c) m * (((1 : A) - m) * (star u * p)) := by
      noncomm_ring
    rw [hassoc, hx, mul_zero]
  rw [sub_mul, one_mul] at hqp
  exact (sub_eq_zero.mp hqp).symm

end Resolvent

end

end KazhdanProjectionAbsorption
end GroupApproximation
