import GroupApproximation.Analysis.VectorOmegaCoronaAction
import GroupApproximation.Analysis.VectorOmegaKazhdanGap
import GroupApproximation.Sofic.UltraproductKazhdanProjection

/-!
# The Kazhdan projection inside `B_ω = ∏_ω M_{d_n}` itself

`\label{thm:normal-kazhdan}` says of the spectral projection

> `P = χ_{{1}}(h)` **lies in the norm ultraproduct** with range `Fix π(K̄)`.

That is one sentence and it asks for one object: a `P` that is *both* an element
of `B_ω` *and* the projection onto the fixed space of the representation on
`H_ω`.  `Analysis/VectorOmegaKazhdanGap.lean` proves the range clause and the
nonvanishing of `q = 1 − P` for the projection taken in `B(H_ω)`, the bounded
operators on the Hilbert-space ultraproduct.  This file forms the projection in
`B_ω` and identifies its image with that one, so that the two halves are about
the same `P` and the printed conjunction is proved rather than its two
conjuncts separately.

## The route

Everything is the Kazhdan argument run one level down, in `B_ω` rather than in
`B(H_ω)`, plus the naturality of the functional calculus to bring it back up.

* `coronaClass` — `π(g) = [V_{g,n}]_ω` as a unitary of `B_ω`.  The
  representatives are coordinatewise unitary, so they are already a unitary of
  the bounded sequences, and the class of a unitary is a unitary.
* `coronaRep` — those classes as a group homomorphism.  This is where the
  manuscript's hypothesis is spent and no more of it: the coordinate family is
  only *asymptotically* multiplicative, and the classes multiply exactly because
  the defect is null along `ω`.  Unitality is not assumed either — `V_{1,n}`
  need not be the identity matrix, and the class at `1` is `1` because a unitary
  idempotent is `1`.
* `coronaSpectrumInclusion` — the printed spectral inclusion
  `sp(h) ⊆ [−1, θ] ∪ {1}`, `θ = 1 − ε₀²/(4·card S)`, for the average taken in
  `B_ω`.  `AbstractSpectralGap.unitaryAverage_spectrum_le` is stated for a
  unitary representation in an *arbitrary* unital C*-algebra, so it applies here
  verbatim; the ω-corona is such an algebra by
  `filterMatrixCStarCoronaCStarAlgebra`.
* `manuscriptKazhdanProjection` — `χ_{{1}}(h)` formed **inside** `B_ω`, and
  `actCorona_manuscriptKazhdanProjection` — its image under the action is the
  projection `Analysis/VectorOmegaKazhdanGap.lean` forms in `B(H_ω)`.  This is
  `VectorOmegaCoronaAction.actCorona_cfc`, the naturality of the calculus under
  the action, whose continuity hypothesis is the contractivity of the corona
  lift.

## Why no closed-range theorem is needed

The obvious route to "P lies in `B_ω`" is to put `P` in the closed unital
⋆-subalgebra generated by `h` (mathlib's `range_cfcHom`) and then to argue that
the range of the action is closed, which for a ⋆-homomorphism of C*-algebras is
true and is not in the pinned mathlib -- it needs the quotient C*-algebra and
the isometry of an injective ⋆-homomorphism.  None of that is used here.  Taking
the calculus in `B_ω` exhibits the preimage outright, so the range never has to
be closed and the action never has to be injective.

## What is deliberately not claimed

The action of `B_ω` on `H_ω` is *not* asserted to be injective, and nothing
below needs it.  One consequence is visible in the last clause of the main
theorem: the nonvanishing of `q = 1 − P` transfers *from* `B(H_ω)` *to* `B_ω`
in the printed direction only -- nontriviality of `π` on the Kazhdan set gives
`1 − p ≠ 0` -- and the converse would need injectivity.  The printed sentence
asserts exactly the direction proved: `q = 0` would make `π` trivial.
-/

namespace GroupApproximation
namespace OmegaCoronaKazhdanProjection

open Filter Matrix Topology
open AbstractSpectralGap VectorOmegaAction VectorOmegaCoronaAction
open VectorOmegaKazhdanGap VectorHilbertUltraproduct
open scoped Matrix.Norms.L2Operator

noncomputable section

universe u

variable (Y : ℕ → FiniteModel) (ω : Ultrafilter ℕ) [∀ n, Nonempty (Y n)]
variable {G : Type u} [Group G]

/-! ## `π(g) = [V_{g,n}]_ω` as a unitary representation in `B_ω` -/

section Representation

variable {Y}

omit [Group G] in
/-- **The coordinate unitaries are unitary as a bounded sequence.**  Nothing
about `ω` enters: `V_{g,n}ᴴ V_{g,n} = 1` at every stage. -/
theorem unitarySeq_star_mul_self (V : ∀ n, G → Matrix.unitaryGroup (Y n) ℂ)
    (g : G) :
    star (unitarySeq Y V g) * unitarySeq Y V g = 1 :=
  Subtype.ext (funext fun n ↦ unitarySeq_star_mul Y V g n)

omit [Group G] in
theorem unitarySeq_mul_star_self (V : ∀ n, G → Matrix.unitaryGroup (Y n) ℂ)
    (g : G) :
    unitarySeq Y V g * star (unitarySeq Y V g) = 1 :=
  Subtype.ext (funext fun n ↦ Unitary.mul_star_self_of_mem (V n g).2)

variable (Y)

/-- **`π(g) = [V_{g,n}]_ω`, as a unitary of `B_ω`.**  The representatives are
unitary at every stage, and the class of such a sequence is a unitary. -/
def coronaClass (R : OmegaUnitaryRep Y ω G) (g : G) :
    unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
  ⟨filterMatrixCStarCoronaMk (Idx Y) (ω : Filter ℕ) (unitarySeq Y R.V g),
    filterMatrixCStarCoronaMk_mem_unitary (Idx Y) (ω : Filter ℕ) _
      (unitarySeq_star_mul_self R.V g) (unitarySeq_mul_star_self R.V g)⟩

@[simp] theorem coronaClass_coe (R : OmegaUnitaryRep Y ω G) (g : G) :
    ((coronaClass Y ω R g :
        unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
        FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
      = filterMatrixCStarCoronaMk (Idx Y) (ω : Filter ℕ) (unitarySeq Y R.V g) :=
  rfl

/-- **The classes multiply exactly.**  The coordinate family multiplies only up
to a defect null along `ω`, and a null sequence has class zero, so the defect
disappears in `B_ω`.  This is the whole of what passing to the ultrafilter
buys. -/
theorem coronaClass_mul (R : OmegaUnitaryRep Y ω G) (g h : G) :
    coronaClass Y ω R (g * h) = coronaClass Y ω R g * coronaClass Y ω R h := by
  refine Subtype.ext ?_
  have hz := (filterMatrixCStarCoronaMk_eq_iff (Idx Y) (ω : Filter ℕ)
    (unitarySeq Y R.V (g * h))
    (unitarySeq Y R.V g * unitarySeq Y R.V h)).2 (R.mul_null g h)
  rw [map_mul] at hz
  exact hz

/-- **`π(1) = 1`, without assuming `V_{1,n} = 1`.**  The class at `1` is
idempotent by the defect at the pair `(1, 1)`, and an idempotent unitary is the
identity. -/
theorem coronaClass_one (R : OmegaUnitaryRep Y ω G) :
    coronaClass Y ω R (1 : G) = 1 := by
  have h := coronaClass_mul Y ω R (1 : G) 1
  rw [mul_one] at h
  have h' : coronaClass Y ω R (1 : G) * 1
      = coronaClass Y ω R (1 : G) * coronaClass Y ω R (1 : G) := by
    rw [mul_one]; exact h
  exact (mul_left_cancel h').symm

/-- **`π(g) = [V_{g,n}]_ω` is a unitary representation of `G` in `B_ω`.**

The printed clause of `\ref{thm:normal-kazhdan}` at the level the print states
it: the classes, not their representatives, and in the norm ultraproduct, not in
the operators on the Hilbert-space ultraproduct. -/
def coronaRep (R : OmegaUnitaryRep Y ω G) :
    G →* unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) where
  toFun := coronaClass Y ω R
  map_one' := coronaClass_one Y ω R
  map_mul' := coronaClass_mul Y ω R

@[simp] theorem coronaRep_apply (R : OmegaUnitaryRep Y ω G) (g : G) :
    coronaRep Y ω R g = coronaClass Y ω R g := rfl

end Representation

/-! ## The two representations are the same one -/

section Compatibility

/-- **The action of the class is the operator the `H_ω` side calls `π(g)`.** -/
theorem actCorona_coronaClass (R : OmegaUnitaryRep Y ω G) (g : G) :
    actCorona Y ω ((coronaRep Y ω R g :
        unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
        FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
      = ((repUnitary' Y ω R g :
        unitary (VecOmega Y ω →L[ℂ] VecOmega Y ω)) :
        VecOmega Y ω →L[ℂ] VecOmega Y ω) := by
  show actCorona Y ω (filterMatrixCStarCoronaMk (Idx Y) (ω : Filter ℕ)
      (unitarySeq Y R.V g)) = _
  rw [actCorona_mk]
  exact ContinuousLinearMap.ext fun _ ↦ rfl

/-- **The averages correspond.**  `h` formed in `B_ω` acts as the `h` formed in
`B(H_ω)`, because the action is a ℂ-algebra homomorphism and the two averages
are the same linear combination of corresponding unitaries. -/
theorem actCorona_unitaryAverage (R : OmegaUnitaryRep Y ω G) (S : Finset G) :
    actCorona Y ω (unitaryAverage (coronaRep Y ω R) S)
      = unitaryAverage (repUnitary' Y ω R) S := by
  unfold AbstractSpectralGap.unitaryAverage
  rw [map_smul, map_sum]
  exact congrArg (fun t : VecOmega Y ω →L[ℂ] VecOmega Y ω ↦ ((S.card : ℂ))⁻¹ • t)
    (Finset.sum_congr rfl fun g _ ↦ actCorona_coronaClass Y ω R g)

/-- **`B_ω` is nontrivial.**  It acts unitally on `H_ω`, which has a vector of
norm one, so its unit is not its zero.  No estimate on the corona norm is
needed. -/
theorem coronaNontrivial :
    Nontrivial (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) := by
  refine ⟨1, 0, fun h ↦ ?_⟩
  have h1 : (1 : VecOmega Y ω →L[ℂ] VecOmega Y ω) = 0 := by
    have hc := congrArg (actCorona Y ω) h
    rwa [map_one, map_zero] at hc
  obtain ⟨x, hx⟩ := exists_ne (0 : VecOmega Y ω)
  refine hx ?_
  have := congrArg (fun T : VecOmega Y ω →L[ℂ] VecOmega Y ω ↦ T x) h1
  simpa using this

end Compatibility

/-! ## The Kazhdan gap, inside `B_ω` -/

section Gap

/-- **`NK.05`'s conclusion, one level down.**

> `sp(h) ⊆ [−1, θ] ∪ {1}` with `θ = 1 − ε₀²/(4·card S)`.

for the average of the classes taken **in the norm ultraproduct**.  The abstract
gap is stated for a unitary representation in an arbitrary unital C*-algebra, so
nothing about this ambient is special; what had been missing is that the ambient
was assembled at all. -/
theorem coronaSpectrumInclusion (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1) :
    spectrum ℝ (unitaryAverage (coronaRep Y ω R) S)
      ⊆ Set.Icc (-1 : ℝ) (1 - ε ^ 2 / (4 * S.card)) ∪ {(1 : ℝ)} := by
  letI : PartialOrder (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
    CStarAlgebra.spectralOrder (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
  letI : StarOrderedRing (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
    CStarAlgebra.spectralOrderedRing
      (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
  haveI := coronaNontrivial Y ω
  intro μ hμ
  have hnorm : ‖unitaryAverage (coronaRep Y ω R) S‖ ≤ 1 :=
    UltraproductKazhdanProjection.norm_unitaryAverage_le_one (coronaRep Y ω R) hS
  have hle : ‖μ‖ ≤ 1 := le_trans (spectrum.norm_le_norm_of_mem hμ) hnorm
  have hlow : (-1 : ℝ) ≤ μ :=
    neg_le_of_abs_le (by simpa [Real.norm_eq_abs] using hle)
  by_cases hμ1 : μ = 1
  · exact Or.inr hμ1
  · refine Or.inl ⟨hlow, ?_⟩
    have hμℂ : (μ : ℂ) ∈ spectrum ℂ (unitaryAverage (coronaRep Y ω R) S) := by
      have h := spectrum.algebraMap_mem ℂ hμ
      rwa [show (algebraMap ℝ ℂ) μ = (μ : ℂ) by simp] at h
    exact unitaryAverage_spectrum_le (coronaRep Y ω R) hQ S hQS hone hsymm hεone
      hμℂ hμ1

/-- The gap in the form the functional calculus consumes. -/
theorem coronaGap (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1) :
    ∀ μ ∈ spectrum ℝ (unitaryAverage (coronaRep Y ω R) S),
      μ ≤ 1 - ε ^ 2 / (4 * S.card) ∨ μ = 1 := by
  intro μ hμ
  rcases coronaSpectrumInclusion Y ω R hQ S hS hQS hone hsymm hεone hμ with h | h
  · exact Or.inl h.2
  · exact Or.inr h

end Gap

/-! ## The projection, formed in `B_ω` -/

section Projection

/-- **`P = χ_{{1}}(h)`, formed inside the norm ultraproduct.** -/
def manuscriptKazhdanProjection (R : OmegaUnitaryRep Y ω G) (S : Finset G)
    (c : ℝ) : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ) :=
  CStarSpectralProjection.spectralProjection
    (unitaryAverage (coronaRep Y ω R) S) c

/-- **It acts as the projection the `H_ω` side forms.**

Naturality of the continuous functional calculus under the action, which is a
continuous unital ⋆-homomorphism.  The gap proved in `B_ω` is what makes the
gap indicator continuous on the spectrum *there*, which is the hypothesis the
naturality needs -- the gap on the image would not supply it, since a
⋆-homomorphism only shrinks the spectrum. -/
theorem actCorona_manuscriptKazhdanProjection (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1) :
    actCorona Y ω
        (manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)))
      = CStarSpectralProjection.spectralProjection
          (unitaryAverage (repUnitary' Y ω R) S) (1 - ε ^ 2 / (4 * S.card)) := by
  have hsa : IsSelfAdjoint (unitaryAverage (coronaRep Y ω R) S) :=
    isSelfAdjoint_unitaryAverage (coronaRep Y ω R) hsymm
  have hc : 1 - ε ^ 2 / (4 * S.card) < 1 := gapConstant_lt_one hQ.1 hS
  have hcont := CStarSpectralProjection.continuousOn_gapIndicator hc
    (coronaGap Y ω R hQ S hS hQS hone hsymm hεone)
  show actCorona Y ω
      (cfc (CStarSpectralProjection.gapIndicator (1 - ε ^ 2 / (4 * S.card)))
        (unitaryAverage (coronaRep Y ω R) S)) = _
  rw [actCorona_cfc Y ω _ _ hsa hcont, actCorona_unitaryAverage]
  rfl

/-- **`NK.06`, as the printed sentence, with one `P`.**

> `P = χ_{{1}}(h)` lies in the norm ultraproduct with range `Fix π(K̄)`, and
> `q = 1 − P` is nonzero because `q = 0` would make `π` trivial on `K̄`.

There is a single `p`, an element of `B_ω`; it is a self-adjoint idempotent; its
action on `H_ω` is exactly the spectral projection `Analysis/VectorOmegaKazhdanGap.lean`
forms there, so the range identification proved for that projection is a
statement about *this* `p`; a vector is fixed by it precisely when the Kazhdan
set fixes the vector; and nontriviality of `π` on the Kazhdan set forces
`1 − p ≠ 0`.

The last clause runs in the printed direction only, and that is the direction
the print asserts.  The converse would say that the action separates `1 − p`
from zero, which is injectivity of the representation of `B_ω` on `H_ω` -- true,
but not proved here and not used. -/
theorem manuscriptNormalKazhdanProjectionInBOmega (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1) :
    ∃ p : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ),
      IsSelfAdjoint p ∧ IsIdempotentElem p
        ∧ actCorona Y ω p
            = CStarSpectralProjection.spectralProjection
                (unitaryAverage (repUnitary' Y ω R) S)
                (1 - ε ^ 2 / (4 * S.card))
        ∧ (∀ x : VecOmega Y ω, actCorona Y ω p x = x
            ↔ ∀ g ∈ S, ((repUnitary' Y ω R g :
                unitary (VecOmega Y ω →L[ℂ] VecOmega Y ω)) :
                VecOmega Y ω →L[ℂ] VecOmega Y ω) x = x)
        ∧ ((∃ g ∈ S, ((repUnitary' Y ω R g :
                unitary (VecOmega Y ω →L[ℂ] VecOmega Y ω)) :
                VecOmega Y ω →L[ℂ] VecOmega Y ω) ≠ 1)
            → (1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) - p ≠ 0) := by
  have hsa : IsSelfAdjoint (unitaryAverage (coronaRep Y ω R) S) :=
    isSelfAdjoint_unitaryAverage (coronaRep Y ω R) hsymm
  have hc : 1 - ε ^ 2 / (4 * S.card) < 1 := gapConstant_lt_one hQ.1 hS
  have hgap := coronaGap Y ω R hQ S hS hQS hone hsymm hεone
  have hact := actCorona_manuscriptKazhdanProjection Y ω R hQ S hS hQS hone hsymm
    hεone
  refine ⟨manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)),
    CStarSpectralProjection.isSelfAdjoint_spectralProjection _,
    CStarSpectralProjection.isIdempotentElem_spectralProjection _ hsa hc hgap,
    hact, ?_, ?_⟩
  · intro x
    rw [hact]
    exact manuscriptNormalKazhdanFixedSpace Y ω R hQ S hS hQS hone hsymm hεone x
  · rintro hne hzero
    have hP : (1 : VecOmega Y ω →L[ℂ] VecOmega Y ω)
        - CStarSpectralProjection.spectralProjection
            (unitaryAverage (repUnitary' Y ω R) S)
            (1 - ε ^ 2 / (4 * S.card)) = 0 := by
      have := congrArg (actCorona Y ω) hzero
      rwa [map_sub, map_one, map_zero, hact] at this
    exact (manuscriptNormalKazhdanComplementNeZero Y ω R hQ S hS hQS hone hsymm
      hεone).2 hne hP

end Projection

end

end OmegaCoronaKazhdanProjection
end GroupApproximation
