import GroupApproximation.Analysis.VectorOmegaCoronaAction
import GroupApproximation.Analysis.VectorOmegaKazhdanGap
import GroupApproximation.Analysis.CoronaProjectionLifting
import GroupApproximation.Sofic.UltraproductKazhdanProjection

/-!
# The Kazhdan projection inside `B_ω = ∏_ω M_{d_n}` itself

`\label{thm:normal-kazhdan}` says of the spectral projection

> `P = χ_{{1}}(h)` **lies in the norm ultraproduct** with range `Fix π(K̄)`.

That is one sentence and it asks for one object: a `P` that is *both* an element
of `B_ω` *and* the projection onto the fixed space of the representation on
`H_ω`.  `Analysis/VectorOmegaKazhdanGap.lean` proves the range clause and the
nonvanishing of `q = 1 − P` for the projection taken in `B(H_ω)`, the bounded
operators on the Hilbert-space ultraproduct.  This file forms the projection in
`B_ω` and identifies its image with that one, so that the two halves are about
the same `P` and the printed conjunction is proved rather than its two
conjuncts separately.

## The route

Everything is the Kazhdan argument run one level down, in `B_ω` rather than in
`B(H_ω)`, plus the naturality of the functional calculus to bring it back up.

* `coronaClass` — `π(g) = [V_{g,n}]_ω` as a unitary of `B_ω`.  The
  representatives are coordinatewise unitary, so they are already a unitary of
  the bounded sequences, and the class of a unitary is a unitary.
* `coronaRep` — those classes as a group homomorphism.  This is where the
  manuscript's hypothesis is spent and no more of it: the coordinate family is
  only *asymptotically* multiplicative, and the classes multiply exactly because
  the defect is null along `ω`.  Unitality is not assumed either — `V_{1,n}`
  need not be the identity matrix, and the class at `1` is `1` because a unitary
  idempotent is `1`.
* `coronaSpectrumInclusion` — the printed spectral inclusion
  `sp(h) ⊆ [−1, θ] ∪ {1}`, `θ = 1 − ε₀²/(4·card S)`, for the average taken in
  `B_ω`.  `AbstractSpectralGap.unitaryAverage_spectrum_le` is stated for a
  unitary representation in an *arbitrary* unital C*-algebra, so it applies here
  verbatim; the ω-corona is such an algebra by
  `filterMatrixCStarCoronaCStarAlgebra`.
* `manuscriptKazhdanProjection` — `χ_{{1}}(h)` formed **inside** `B_ω`, and
  `actCorona_manuscriptKazhdanProjection` — its image under the action is the
  projection `Analysis/VectorOmegaKazhdanGap.lean` forms in `B(H_ω)`.  This is
  `VectorOmegaCoronaAction.actCorona_cfc`, the naturality of the calculus under
  the action, whose continuity hypothesis is the contractivity of the corona
  lift.

## Why no closed-range theorem is needed

The obvious route to "P lies in `B_ω`" is to put `P` in the closed unital
⋆-subalgebra generated by `h` (mathlib's `range_cfcHom`) and then to argue that
the range of the action is closed, which for a ⋆-homomorphism of C*-algebras is
true and is not in the pinned mathlib -- it needs the quotient C*-algebra and
the isometry of an injective ⋆-homomorphism.  None of that is used here.  Taking
the calculus in `B_ω` exhibits the preimage outright, so the range never has to
be closed and the action never has to be injective.

## What is deliberately not claimed

The action of `B_ω` on `H_ω` is *not* asserted to be injective, and nothing
below needs it.  One consequence is visible in the last clause of the main
theorem: the nonvanishing of `q = 1 − P` transfers *from* `B(H_ω)` *to* `B_ω`
in the printed direction only -- nontriviality of `π` on the Kazhdan set gives
`1 − p ≠ 0` -- and the converse would need injectivity.  The printed sentence
asserts exactly the direction proved: `q = 0` would make `π` trivial.
-/

namespace GroupApproximation
namespace OmegaCoronaKazhdanProjection

open Filter Matrix Topology
open AbstractSpectralGap VectorOmegaAction VectorOmegaCoronaAction
open VectorOmegaKazhdanGap VectorHilbertUltraproduct
open scoped Matrix.Norms.L2Operator

noncomputable section

universe u

variable (Y : ℕ → FiniteModel) (ω : Ultrafilter ℕ) [∀ n, Nonempty (Y n)]
variable {G : Type u} [Group G]

/-! ## `π(g) = [V_{g,n}]_ω` as a unitary representation in `B_ω` -/

section Representation

variable {Y}

omit [Group G] in
/-- **The coordinate unitaries are unitary as a bounded sequence.**  Nothing
about `ω` enters: `V_{g,n}ᴴ V_{g,n} = 1` at every stage. -/
theorem unitarySeq_star_mul_self (V : ∀ n, G → Matrix.unitaryGroup (Y n) ℂ)
    (g : G) :
    star (unitarySeq Y V g) * unitarySeq Y V g = 1 :=
  Subtype.ext (funext fun n ↦ unitarySeq_star_mul Y V g n)

omit [Group G] in
theorem unitarySeq_mul_star_self (V : ∀ n, G → Matrix.unitaryGroup (Y n) ℂ)
    (g : G) :
    unitarySeq Y V g * star (unitarySeq Y V g) = 1 :=
  Subtype.ext (funext fun n ↦ Unitary.mul_star_self_of_mem (V n g).2)

variable (Y)

/-- **`π(g) = [V_{g,n}]_ω`, as a unitary of `B_ω`.**  The representatives are
unitary at every stage, and the class of such a sequence is a unitary. -/
def coronaClass (R : OmegaUnitaryRep Y ω G) (g : G) :
    unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
  ⟨filterMatrixCStarCoronaMk (Idx Y) (ω : Filter ℕ) (unitarySeq Y R.V g),
    filterMatrixCStarCoronaMk_mem_unitary (Idx Y) (ω : Filter ℕ) _
      (unitarySeq_star_mul_self R.V g) (unitarySeq_mul_star_self R.V g)⟩

@[simp] theorem coronaClass_coe (R : OmegaUnitaryRep Y ω G) (g : G) :
    ((coronaClass Y ω R g :
        unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
        FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
      = filterMatrixCStarCoronaMk (Idx Y) (ω : Filter ℕ) (unitarySeq Y R.V g) :=
  rfl

/-- **The classes multiply exactly.**  The coordinate family multiplies only up
to a defect null along `ω`, and a null sequence has class zero, so the defect
disappears in `B_ω`.  This is the whole of what passing to the ultrafilter
buys. -/
theorem coronaClass_mul (R : OmegaUnitaryRep Y ω G) (g h : G) :
    coronaClass Y ω R (g * h) = coronaClass Y ω R g * coronaClass Y ω R h := by
  refine Subtype.ext ?_
  have hz := (filterMatrixCStarCoronaMk_eq_iff (Idx Y) (ω : Filter ℕ)
    (unitarySeq Y R.V (g * h))
    (unitarySeq Y R.V g * unitarySeq Y R.V h)).2 (R.mul_null g h)
  rw [map_mul] at hz
  exact hz

/-- **`π(1) = 1`, without assuming `V_{1,n} = 1`.**  The class at `1` is
idempotent by the defect at the pair `(1, 1)`, and an idempotent unitary is the
identity. -/
theorem coronaClass_one (R : OmegaUnitaryRep Y ω G) :
    coronaClass Y ω R (1 : G) = 1 := by
  have h := coronaClass_mul Y ω R (1 : G) 1
  rw [mul_one] at h
  have h' : coronaClass Y ω R (1 : G) * 1
      = coronaClass Y ω R (1 : G) * coronaClass Y ω R (1 : G) := by
    rw [mul_one]; exact h
  exact (mul_left_cancel h').symm

/-- **`π(g) = [V_{g,n}]_ω` is a unitary representation of `G` in `B_ω`.**

The printed clause of `\ref{thm:normal-kazhdan}` at the level the print states
it: the classes, not their representatives, and in the norm ultraproduct, not in
the operators on the Hilbert-space ultraproduct. -/
def coronaRep (R : OmegaUnitaryRep Y ω G) :
    G →* unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) where
  toFun := coronaClass Y ω R
  map_one' := coronaClass_one Y ω R
  map_mul' := coronaClass_mul Y ω R

@[simp] theorem coronaRep_apply (R : OmegaUnitaryRep Y ω G) (g : G) :
    coronaRep Y ω R g = coronaClass Y ω R g := rfl

end Representation

/-! ## The two representations are the same one -/

section Compatibility

/-- **The action of the class is the operator the `H_ω` side calls `π(g)`.** -/
theorem actCorona_coronaClass (R : OmegaUnitaryRep Y ω G) (g : G) :
    actCorona Y ω ((coronaRep Y ω R g :
        unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
        FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
      = ((repUnitary' Y ω R g :
        unitary (VecOmega Y ω →L[ℂ] VecOmega Y ω)) :
        VecOmega Y ω →L[ℂ] VecOmega Y ω) := by
  show actCorona Y ω (filterMatrixCStarCoronaMk (Idx Y) (ω : Filter ℕ)
      (unitarySeq Y R.V g)) = _
  rw [actCorona_mk]
  exact ContinuousLinearMap.ext fun _ ↦ rfl

/-- **The averages correspond.**  `h` formed in `B_ω` acts as the `h` formed in
`B(H_ω)`, because the action is a ℂ-algebra homomorphism and the two averages
are the same linear combination of corresponding unitaries. -/
theorem actCorona_unitaryAverage (R : OmegaUnitaryRep Y ω G) (S : Finset G) :
    actCorona Y ω (unitaryAverage (coronaRep Y ω R) S)
      = unitaryAverage (repUnitary' Y ω R) S := by
  unfold AbstractSpectralGap.unitaryAverage
  rw [map_smul, map_sum]
  exact congrArg (fun t : VecOmega Y ω →L[ℂ] VecOmega Y ω ↦ ((S.card : ℂ))⁻¹ • t)
    (Finset.sum_congr rfl fun g _ ↦ actCorona_coronaClass Y ω R g)

/-- **`B_ω` is nontrivial.**  It acts unitally on `H_ω`, which has a vector of
norm one, so its unit is not its zero.  No estimate on the corona norm is
needed. -/
theorem coronaNontrivial :
    Nontrivial (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) := by
  refine ⟨1, 0, fun h ↦ ?_⟩
  have h1 : (1 : VecOmega Y ω →L[ℂ] VecOmega Y ω) = 0 := by
    have hc := congrArg (actCorona Y ω) h
    rwa [map_one, map_zero] at hc
  obtain ⟨x, hx⟩ := exists_ne (0 : VecOmega Y ω)
  refine hx ?_
  have := congrArg (fun T : VecOmega Y ω →L[ℂ] VecOmega Y ω ↦ T x) h1
  simpa using this

end Compatibility

/-! ## The Kazhdan gap, inside `B_ω` -/

section Gap

/-- **`NK.05`'s conclusion, one level down.**

> `sp(h) ⊆ [−1, θ] ∪ {1}` with `θ = 1 − ε₀²/(4·card S)`.

for the average of the classes taken **in the norm ultraproduct**.  The abstract
gap is stated for a unitary representation in an arbitrary unital C*-algebra, so
nothing about this ambient is special; what had been missing is that the ambient
was assembled at all. -/
theorem coronaSpectrumInclusion (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1) :
    spectrum ℝ (unitaryAverage (coronaRep Y ω R) S)
      ⊆ Set.Icc (-1 : ℝ) (1 - ε ^ 2 / (4 * S.card)) ∪ {(1 : ℝ)} := by
  letI : PartialOrder (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
    CStarAlgebra.spectralOrder (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
  letI : StarOrderedRing (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
    CStarAlgebra.spectralOrderedRing
      (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
  haveI := coronaNontrivial Y ω
  intro μ hμ
  have hnorm : ‖unitaryAverage (coronaRep Y ω R) S‖ ≤ 1 :=
    UltraproductKazhdanProjection.norm_unitaryAverage_le_one (coronaRep Y ω R) hS
  have hle : ‖μ‖ ≤ 1 := le_trans (spectrum.norm_le_norm_of_mem hμ) hnorm
  have hlow : (-1 : ℝ) ≤ μ :=
    neg_le_of_abs_le (by simpa [Real.norm_eq_abs] using hle)
  by_cases hμ1 : μ = 1
  · exact Or.inr hμ1
  · refine Or.inl ⟨hlow, ?_⟩
    have hμℂ : (μ : ℂ) ∈ spectrum ℂ (unitaryAverage (coronaRep Y ω R) S) := by
      have h := spectrum.algebraMap_mem ℂ hμ
      rwa [show (algebraMap ℝ ℂ) μ = (μ : ℂ) by simp] at h
    exact unitaryAverage_spectrum_le (coronaRep Y ω R) hQ S hQS hone hsymm hεone
      hμℂ hμ1

/-- The gap in the form the functional calculus consumes. -/
theorem coronaGap (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1) :
    ∀ μ ∈ spectrum ℝ (unitaryAverage (coronaRep Y ω R) S),
      μ ≤ 1 - ε ^ 2 / (4 * S.card) ∨ μ = 1 := by
  intro μ hμ
  rcases coronaSpectrumInclusion Y ω R hQ S hS hQS hone hsymm hεone hμ with h | h
  · exact Or.inl h.2
  · exact Or.inr h

end Gap

/-! ## The projection, formed in `B_ω` -/

section Projection

/-- **`P = χ_{{1}}(h)`, formed inside the norm ultraproduct.** -/
def manuscriptKazhdanProjection (R : OmegaUnitaryRep Y ω G) (S : Finset G)
    (c : ℝ) : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ) :=
  CStarSpectralProjection.spectralProjection
    (unitaryAverage (coronaRep Y ω R) S) c

/-- **It acts as the projection the `H_ω` side forms.**

Naturality of the continuous functional calculus under the action, which is a
continuous unital ⋆-homomorphism.  The gap proved in `B_ω` is what makes the
gap indicator continuous on the spectrum *there*, which is the hypothesis the
naturality needs -- the gap on the image would not supply it, since a
⋆-homomorphism only shrinks the spectrum. -/
theorem actCorona_manuscriptKazhdanProjection (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1) :
    actCorona Y ω
        (manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)))
      = CStarSpectralProjection.spectralProjection
          (unitaryAverage (repUnitary' Y ω R) S) (1 - ε ^ 2 / (4 * S.card)) := by
  have hsa : IsSelfAdjoint (unitaryAverage (coronaRep Y ω R) S) :=
    isSelfAdjoint_unitaryAverage (coronaRep Y ω R) hsymm
  have hc : 1 - ε ^ 2 / (4 * S.card) < 1 := gapConstant_lt_one hQ.1 hS
  have hcont := CStarSpectralProjection.continuousOn_gapIndicator hc
    (coronaGap Y ω R hQ S hS hQS hone hsymm hεone)
  show actCorona Y ω
      (cfc (CStarSpectralProjection.gapIndicator (1 - ε ^ 2 / (4 * S.card)))
        (unitaryAverage (coronaRep Y ω R) S)) = _
  rw [actCorona_cfc Y ω _ _ hsa hcont, actCorona_unitaryAverage]
  rfl

/-- **`q = 1 − P` is nonzero, in `B_ω`.**

> `q = 1 − P` is nonzero because `q = 0` would make `π` trivial on `K̄`, against
> the operator-norm separation.

The printed direction: nontriviality of `π` on the Kazhdan set forces `1 − p ≠
0`.  It transfers from `B(H_ω)`, where the fixed-space characterisation lives,
because `p = 0` there would make its action zero.  The converse would need the
action to be injective. -/
theorem manuscriptKazhdanProjection_one_sub_ne_zero (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1)
    (hnt : ∃ g ∈ S, ((repUnitary' Y ω R g :
      unitary (VecOmega Y ω →L[ℂ] VecOmega Y ω)) :
      VecOmega Y ω →L[ℂ] VecOmega Y ω) ≠ 1) :
    (1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
        - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card))
      ≠ 0 := by
  intro hzero
  have hP : (1 : VecOmega Y ω →L[ℂ] VecOmega Y ω)
      - CStarSpectralProjection.spectralProjection
          (unitaryAverage (repUnitary' Y ω R) S)
          (1 - ε ^ 2 / (4 * S.card)) = 0 := by
    have h := congrArg (actCorona Y ω) hzero
    rwa [map_sub, map_one, map_zero,
      actCorona_manuscriptKazhdanProjection Y ω R hQ S hS hQS hone hsymm
        hεone] at h
  exact (manuscriptNormalKazhdanComplementNeZero Y ω R hQ S hS hQS hone hsymm
    hεone).2 hnt hP

/-- **`NK.06`, as the printed sentence, with one `P`.**

> `P = χ_{{1}}(h)` lies in the norm ultraproduct with range `Fix π(K̄)`, and
> `q = 1 − P` is nonzero because `q = 0` would make `π` trivial on `K̄`.

There is a single `p`, an element of `B_ω`; it is a self-adjoint idempotent; its
action on `H_ω` is exactly the spectral projection `Analysis/VectorOmegaKazhdanGap.lean`
forms there, so the range identification proved for that projection is a
statement about *this* `p`; a vector is fixed by it precisely when the Kazhdan
set fixes the vector; and nontriviality of `π` on the Kazhdan set forces
`1 − p ≠ 0`.

The last clause runs in the printed direction only, and that is the direction
the print asserts.  The converse would say that the action separates `1 − p`
from zero, which is injectivity of the representation of `B_ω` on `H_ω` -- true,
but not proved here and not used. -/
theorem manuscriptNormalKazhdanProjectionInBOmega (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1) :
    ∃ p : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ),
      IsSelfAdjoint p ∧ IsIdempotentElem p
        ∧ actCorona Y ω p
            = CStarSpectralProjection.spectralProjection
                (unitaryAverage (repUnitary' Y ω R) S)
                (1 - ε ^ 2 / (4 * S.card))
        ∧ (∀ x : VecOmega Y ω, actCorona Y ω p x = x
            ↔ ∀ g ∈ S, ((repUnitary' Y ω R g :
                unitary (VecOmega Y ω →L[ℂ] VecOmega Y ω)) :
                VecOmega Y ω →L[ℂ] VecOmega Y ω) x = x)
        ∧ ((∃ g ∈ S, ((repUnitary' Y ω R g :
                unitary (VecOmega Y ω →L[ℂ] VecOmega Y ω)) :
                VecOmega Y ω →L[ℂ] VecOmega Y ω) ≠ 1)
            → (1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) - p ≠ 0) := by
  have hsa : IsSelfAdjoint (unitaryAverage (coronaRep Y ω R) S) :=
    isSelfAdjoint_unitaryAverage (coronaRep Y ω R) hsymm
  have hc : 1 - ε ^ 2 / (4 * S.card) < 1 := gapConstant_lt_one hQ.1 hS
  have hgap := coronaGap Y ω R hQ S hS hQS hone hsymm hεone
  have hact := actCorona_manuscriptKazhdanProjection Y ω R hQ S hS hQS hone hsymm
    hεone
  refine ⟨manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)),
    CStarSpectralProjection.isSelfAdjoint_spectralProjection _,
    CStarSpectralProjection.isIdempotentElem_spectralProjection _ hsa hc hgap,
    hact, ?_, ?_⟩
  · intro x
    rw [hact]
    exact manuscriptNormalKazhdanFixedSpace Y ω R hQ S hS hQS hone hsymm hεone x
  · exact manuscriptKazhdanProjection_one_sub_ne_zero Y ω R hQ S hS hQS hone
      hsymm hεone

end Projection

/-! ## `NK.07` in the norm ultraproduct: commutation, and the lift of `q`

`thm:abstract-nk` continues:

> normality gives `π(g)Pπ(g)* = P`, so `P` and `q` commute with `π(H̄)` exactly.
> Lift `q` to projections `q_n ∈ M_{d_n}(ℂ)`, nonzero along `ω` and with
> `‖[q_n, V_{g,n}]‖ →_ω 0` for every `g ∈ H̄`.

Both sentences are about `B_ω`, and both are proved here about the `p` of
`manuscriptKazhdanProjection`. -/

section Normality

/-- **The conjugation identity in the printed ambient.**

`Analysis/VectorOmegaKazhdanGap.lean` proves it on `H_ω`, through the fixed
spaces, which is the printed argument.  This is the same identity inside `B_ω`,
where the printed `P` lives, and it is what the lift below consumes: an equality
of *classes* is what makes a commutator of representatives vanish, and an
equality of the operators they act by would not.

`Analysis/KazhdanProjectionAbsorption.lean` carries the argument, and it uses no
vectors: the absorption identities of the spectral projection make every unitary
of the Kazhdan set fix `P`, that extends to the subgroup the set generates --
the printed `K̄` -- and normality says the conjugated average still fixes `P`. -/
theorem manuscriptNormalKazhdanConjugationInBOmega (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1)
    (hnorm : ∀ g : G, ∀ k ∈ Subgroup.closure (S : Set G),
      g * k * g⁻¹ ∈ Subgroup.closure (S : Set G)) (g : G) :
    ((coronaRep Y ω R g :
          unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
          FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
        * manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card))
        * star ((coronaRep Y ω R g :
            unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
            FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
      = manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)) := by
  letI : PartialOrder (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
    CStarAlgebra.spectralOrder (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
  letI : StarOrderedRing (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
    CStarAlgebra.spectralOrderedRing
      (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
  exact KazhdanProjectionAbsorption.conj_spectralProjection_eq_of_normal
    (coronaRep Y ω R) hS hsymm (gapConstant_lt_one hQ.1 hS)
    (coronaGap Y ω R hQ S hS hQS hone hsymm hεone) hnorm g

/-- **`q = 1 − P` commutes with `π(H̄)` exactly, in `B_ω`.** -/
theorem manuscriptNormalKazhdanCommutationInBOmega (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1)
    (hnorm : ∀ g : G, ∀ k ∈ Subgroup.closure (S : Set G),
      g * k * g⁻¹ ∈ Subgroup.closure (S : Set G)) (g : G) :
    ((coronaRep Y ω R g :
          unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
          FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
        * ((1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
          - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)))
      = ((1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
          - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)))
        * ((coronaRep Y ω R g :
            unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
            FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) := by
  letI : PartialOrder (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
    CStarAlgebra.spectralOrder (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
  letI : StarOrderedRing (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
    CStarAlgebra.spectralOrderedRing
      (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
  exact KazhdanProjectionAbsorption.commute_one_sub_spectralProjection_of_normal
    (coronaRep Y ω R) hS hsymm (gapConstant_lt_one hQ.1 hS)
    (coronaGap Y ω R hQ S hS hQS hone hsymm hεone) hnorm g

/-- **The printed lift of `q`.**

> Lift `q` to projections `q_n ∈ M_{d_n}(ℂ)`, nonzero along `ω` and with
> `‖[q_n, V_{g,n}]‖ →_ω 0` for every `g ∈ H̄`.

All three clauses, for the printed `q = 1 − P` with `P` the projection formed in
`B_ω`.  The projections are genuine, not approximate; the nonvanishing is the
printed "nonzero along `ω`" and comes from the operator-norm separation through
the nontriviality hypothesis, exactly as the print has it; and the commutator
estimate is exact commutation in `B_ω` read on representatives, with no estimate
of its own.

What this does *not* do is the rest of the compression paragraph: the lift of
`h` to coordinates, the corner spectral inequality `q h q ≤ θ q` in its
coordinate form, the diagonal subsequence, and the polar-corrected compression.
See the ledger row. -/
theorem manuscriptComplementProjectionLift (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1)
    (hnorm : ∀ g : G, ∀ k ∈ Subgroup.closure (S : Set G),
      g * k * g⁻¹ ∈ Subgroup.closure (S : Set G))
    (hnt : ∃ g ∈ S, ((repUnitary' Y ω R g :
      unitary (VecOmega Y ω →L[ℂ] VecOmega Y ω)) :
      VecOmega Y ω →L[ℂ] VecOmega Y ω) ≠ 1) :
    ∃ qn : BoundedMatrixSequence (Idx Y),
      (∀ n, KazhdanCornerMatrices.IsOrthogonalProjectionMatrix
          ((qn : ∀ n, Matrix (Idx Y n) (Idx Y n) ℂ) n))
        ∧ filterMatrixCStarCoronaMk (Idx Y) (ω : Filter ℕ) qn
            = (1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
              - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card))
        ∧ {n | (qn : ∀ n, Matrix (Idx Y n) (Idx Y n) ℂ) n ≠ 0}
            ∈ (ω : Filter ℕ)
        ∧ ∀ g : G, IsNullMatrixSequence (Idx Y) (ω : Filter ℕ)
            (unitarySeq Y R.V g * qn - qn * unitarySeq Y R.V g) := by
  have hsa : IsSelfAdjoint (unitaryAverage (coronaRep Y ω R) S) :=
    isSelfAdjoint_unitaryAverage (coronaRep Y ω R) hsymm
  have hc : 1 - ε ^ 2 / (4 * S.card) < 1 := gapConstant_lt_one hQ.1 hS
  have hgap := coronaGap Y ω R hQ S hS hQS hone hsymm hεone
  have hPsa : IsSelfAdjoint
      (manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card))) :=
    CStarSpectralProjection.isSelfAdjoint_spectralProjection _
  have hPi : IsIdempotentElem
      (manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card))) :=
    CStarSpectralProjection.isIdempotentElem_spectralProjection _ hsa hc hgap
  obtain ⟨qn, hproj, hmk⟩ :=
    CoronaProjectionLifting.exists_projection_lift (Idx Y) (ω : Filter ℕ)
      ((1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
        - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)))
      (by rw [IsSelfAdjoint, star_sub, star_one, hPsa.star_eq]) hPi.one_sub
  refine ⟨qn, hproj, hmk, ?_, ?_⟩
  · refine CoronaProjectionLifting.mem_of_mk_ne_zero (Idx Y) ω ?_
    rw [hmk]
    exact manuscriptKazhdanProjection_one_sub_ne_zero Y ω R hQ S hS hQS hone
      hsymm hεone hnt
  · intro g
    refine CoronaProjectionLifting.isNullMatrixSequence_commutator_of_commute
      (Idx Y) (ω : Filter ℕ) ?_
    rw [hmk]
    exact manuscriptNormalKazhdanCommutationInBOmega Y ω R hQ S hS hQS hone
      hsymm hεone hnorm g

end Normality

/-! ## The coordinate lift of `h`, and the compression to the corner

`thm:abstract-nk` continues:

> and lift `h` to the self-adjoint coordinates
> `h_n = (2|S|)⁻¹ ∑_{a∈S} (V_{a,n} + V_{a,n}*) ∈ M_{d_n}(ℂ)`, which represent
> `h` because `S` is symmetric.  The compression of `h` to the corner satisfies
> `q h q ≤ θ q` in `B_ω`.

Both sentences are here.  `hermitianAverageSeq` is the printed formula on the
nose, and `mk_hermitianAverageSeq` is the printed reason it represents `h`:
symmetry of `S` makes the average self-adjoint, so adding the adjoint changes
nothing at the level of classes. -/

section Compression

/-- **The printed coordinate lift of `h`**:
`h_n = (2|S|)⁻¹ ∑_{a∈S} (V_{a,n} + V_{a,n}*)`, as a bounded sequence. -/
def hermitianAverageSeq (R : OmegaUnitaryRep Y ω G) (S : Finset G) :
    BoundedMatrixSequence (Idx Y) :=
  (2 * (S.card : ℂ))⁻¹ •
    ∑ a ∈ S, (unitarySeq Y R.V a + star (unitarySeq Y R.V a))

/-- The coordinates are self-adjoint at every stage, not merely along `ω`.
This is what the printed "self-adjoint coordinates" asserts. -/
theorem hermitianAverageSeq_selfAdjoint (R : OmegaUnitaryRep Y ω G)
    (S : Finset G) :
    star (hermitianAverageSeq Y ω R S) = hermitianAverageSeq Y ω R S := by
  have hstar2 : star ((2 * (S.card : ℂ))⁻¹) = (2 * (S.card : ℂ))⁻¹ := by
    rw [star_inv₀]
    simp
  rw [hermitianAverageSeq, star_smul, star_sum, hstar2]
  congr 1
  refine Finset.sum_congr rfl fun a _ ↦ ?_
  rw [star_add, star_star, add_comm]

/-- The scalar bookkeeping of the printed halving, isolated because the opaque
corona's scalar action reaches `rw` through a different path than the `Module`
lemmas are stated for; `exact` sees through it and `rw` does not. -/
private theorem inv_two_mul_smul_add_self {M : Type*} [AddCommGroup M]
    [Module ℂ M] (x : M) (c : ℂ) : (2 * c)⁻¹ • (x + x) = c⁻¹ • x := by
  rw [smul_add, ← add_smul]
  congr 1
  rw [mul_inv, ← two_mul, ← mul_assoc,
    mul_inv_cancel₀ (by norm_num : (2 : ℂ) ≠ 0), one_mul]

/-- **They represent `h`, because `S` is symmetric.**  The average of the
classes is already self-adjoint, so adding its adjoint and halving returns
it. -/
theorem mk_hermitianAverageSeq (R : OmegaUnitaryRep Y ω G) {S : Finset G}
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) :
    filterMatrixCStarCoronaMk (Idx Y) (ω : Filter ℕ)
        (hermitianAverageSeq Y ω R S)
      = unitaryAverage (coronaRep Y ω R) S := by
  classical
  have hstep : ∀ a ∈ S,
      filterMatrixCStarCoronaQuotient (Idx Y) (ω : Filter ℕ)
        (unitarySeq Y R.V a + star (unitarySeq Y R.V a))
      = ((coronaRep Y ω R a :
            unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
            FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
        + star ((coronaRep Y ω R a :
            unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
            FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) := by
    intro a _
    rw [map_add, map_star]
    rfl
  have hTsa : star (∑ a ∈ S, ((coronaRep Y ω R a :
        unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
        FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)))
      = ∑ a ∈ S, ((coronaRep Y ω R a :
        unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
        FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) := by
    rw [star_sum, show (∑ a ∈ S, star ((coronaRep Y ω R a :
          unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
          FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)))
        = ∑ a ∈ S, ((coronaRep Y ω R a⁻¹ :
          unitary (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))) :
          FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) from
      Finset.sum_congr rfl fun a _ ↦ star_unitary_coe (coronaRep Y ω R) a]
    refine Finset.sum_nbij' (fun g ↦ g⁻¹) (fun g ↦ g⁻¹) ?_ ?_ ?_ ?_ ?_
    · intro g hg; exact hsymm g hg
    · intro g hg; exact hsymm g hg
    · intro g _; exact inv_inv g
    · intro g _; exact inv_inv g
    · intro g _; rfl
  show filterMatrixCStarCoronaQuotient (Idx Y) (ω : Filter ℕ)
      (hermitianAverageSeq Y ω R S) = _
  rw [hermitianAverageSeq, map_smul, map_sum, Finset.sum_congr rfl hstep,
    Finset.sum_add_distrib, ← star_sum, hTsa]
  exact inv_two_mul_smul_add_self _ _

/-! ### The order on `B_ω`

The compression statement is an *order* statement, so the ambient needs the
C*-order.  It is installed here rather than globally, and by the repository's
standard idiom: the spectral order of a C*-algebra, which is the only order the
inequality could mean. -/

local instance coronaPartialOrder :
    PartialOrder (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
  CStarAlgebra.spectralOrder (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))

local instance coronaStarOrderedRing :
    StarOrderedRing (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ)) :=
  CStarAlgebra.spectralOrderedRing
    (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))

/-- **`q h q ≤ θ q` in `B_ω`**, for the printed `h`, `q` and `θ`.

The gap cashed as an order statement.  It is algebra-internal:
`KazhdanProjectionAbsorption.compression_le_gap` proves it for the spectral
projection at an isolated top of the spectrum in any C*-algebra, from the
pointwise inequality of two continuous functions on the spectrum, and the
ultraproduct contributes only the gap. -/
theorem manuscriptCornerCompression (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1) :
    ((1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
          - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)))
        * unitaryAverage (coronaRep Y ω R) S
        * ((1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
          - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)))
      ≤ algebraMap ℝ (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
            (1 - ε ^ 2 / (4 * S.card))
        * ((1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
          - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card))) :=
  KazhdanProjectionAbsorption.compression_le_gap
    (unitaryAverage (coronaRep Y ω R) S)
    (isSelfAdjoint_unitaryAverage (coronaRep Y ω R) hsymm)
    (gapConstant_lt_one hQ.1 hS)
    (coronaGap Y ω R hQ S hS hQS hone hsymm hεone)

/-- The printed corner defect `θ q − q h q`, as a bounded sequence.  Written
with the algebra map rather than a scalar action because the opaque corona's
scalar action does not rewrite; at a coordinate it is `θ q_n − q_n h_n q_n`. -/
def cornerDefectSeq (R : OmegaUnitaryRep Y ω G) (S : Finset G)
    (qn : BoundedMatrixSequence (Idx Y)) (c : ℝ) :
    BoundedMatrixSequence (Idx Y) :=
  algebraMap ℂ (BoundedMatrixSequence (Idx Y)) (c : ℂ) * qn
    - qn * hermitianAverageSeq Y ω R S * qn

open scoped ComplexOrder in
/-- **The corner inequality in coordinates.**

> that inequality is exactly the coordinate statement
> `‖(q_n h_n q_n − θ q_n)₊‖ →_ω 0`.

For every tolerance, the printed corner defect is bounded below by minus that
tolerance at almost every coordinate along `ω` -- which is what the vanishing of
the positive part says, and the form the trace estimate of the next paragraph
consumes.

The passage is `CoronaProjectionLifting.eventually_posSemidef_smul_one_add`, and
the one order step happens here, where the order instance lives: a nonnegative
element of a C*-algebra is `star b * b`, and a representative of `b` makes the
coordinate difference null along `ω`. -/
theorem manuscriptCornerCompressionCoordinates (R : OmegaUnitaryRep Y ω G)
    {Q : Finset G} {ε : ℝ} (hQ : IsKazhdanPair.{u, 0} G Q ε)
    (S : Finset G) (hS : S.Nonempty) (hQS : Q ⊆ S) (hone : 1 ∈ S)
    (hsymm : ∀ g ∈ S, g⁻¹ ∈ S) (hεone : ε ≤ 1)
    (qn : BoundedMatrixSequence (Idx Y)) (hqsa : star qn = qn)
    (hqn : filterMatrixCStarCoronaMk (Idx Y) (ω : Filter ℕ) qn
      = (1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
        - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)))
    {δ : ℝ} (hδ : 0 < δ) :
    ∀ᶠ n in (ω : Filter ℕ),
      (((δ : ℂ) • (1 : Matrix (Idx Y n) (Idx Y n) ℂ))
        + (cornerDefectSeq Y ω R S qn (1 - ε ^ 2 / (4 * S.card)) :
            ∀ n, Matrix (Idx Y n) (Idx Y n) ℂ) n).PosSemidef := by
  have hbridge : algebraMap ℝ (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
        (1 - ε ^ 2 / (4 * S.card))
      = algebraMap ℂ (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
        ((1 - ε ^ 2 / (4 * S.card) : ℝ) : ℂ) := by
    rw [IsScalarTower.algebraMap_apply ℝ ℂ
      (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))]
    rfl
  have hnn : 0 ≤ algebraMap ℂ (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
        ((1 - ε ^ 2 / (4 * S.card) : ℝ) : ℂ)
        * ((1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
          - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)))
      - ((1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
          - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card)))
        * unitaryAverage (coronaRep Y ω R) S
        * ((1 : FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
          - manuscriptKazhdanProjection Y ω R S (1 - ε ^ 2 / (4 * S.card))) := by
    rw [← hbridge, sub_nonneg]
    exact manuscriptCornerCompression Y ω R hQ S hS hQS hone hsymm hεone
  obtain ⟨b, hb⟩ := CStarAlgebra.nonneg_iff_eq_star_mul_self.mp hnn
  have hsa : star (cornerDefectSeq Y ω R S qn (1 - ε ^ 2 / (4 * S.card)))
      = cornerDefectSeq Y ω R S qn (1 - ε ^ 2 / (4 * S.card)) := by
    have hstarAlg : star (algebraMap ℂ (BoundedMatrixSequence (Idx Y))
          ((1 - ε ^ 2 / (4 * S.card) : ℝ) : ℂ))
        = algebraMap ℂ (BoundedMatrixSequence (Idx Y))
          ((1 - ε ^ 2 / (4 * S.card) : ℝ) : ℂ) := by
      rw [Algebra.algebraMap_eq_smul_one, star_smul, star_one,
        Complex.star_def, Complex.conj_ofReal]
    rw [cornerDefectSeq]
    simp only [star_sub, star_mul, hqsa, hermitianAverageSeq_selfAdjoint,
      hstarAlg, mul_assoc, Algebra.commutes]
  have hmk : filterMatrixCStarCoronaMk (Idx Y) (ω : Filter ℕ)
      (cornerDefectSeq Y ω R S qn (1 - ε ^ 2 / (4 * S.card))) = star b * b := by
    have halg : filterMatrixCStarCoronaMk (Idx Y) (ω : Filter ℕ)
          (algebraMap ℂ (BoundedMatrixSequence (Idx Y))
            ((1 - ε ^ 2 / (4 * S.card) : ℝ) : ℂ))
        = algebraMap ℂ (FilterMatrixCStarCorona (Idx Y) (ω : Filter ℕ))
          ((1 - ε ^ 2 / (4 * S.card) : ℝ) : ℂ) :=
      (filterMatrixCStarCoronaQuotient (Idx Y) (ω : Filter ℕ)).commutes _
    rw [cornerDefectSeq, map_sub, map_mul, map_mul, map_mul, halg, hqn,
      mk_hermitianAverageSeq Y ω R hsymm]
    exact hb
  exact CoronaProjectionLifting.eventually_posSemidef_smul_one_add (Idx Y)
    (ω : Filter ℕ) _ hsa hmk hδ

end Compression

end

end OmegaCoronaKazhdanProjection
end GroupApproximation
