import GroupApproximation.Analysis.NormMatrixCorona
import GroupApproximation.Analysis.RankNormalizedHilbertization

/-!
# `Λ`, the rank-normalized Hilbertization of the ideal `𝓘_q`

Proof-ledger row `CO.20`, the paragraph *The `q`-normalized Hilbert space* in
the proof of the theorem labelled `thm:projection-collapse` in
`non_mf_groups_exist.tex` (navigate by the label; that file is under
concurrent edit).

`Analysis/RankNormalizedHilbertization` proved every estimate the printed `Λ`
has to satisfy — the two halves of `eq:rank-frobenius`, boundedness and
well-definedness at the rank weight, `‖Λ(q)‖ = 1` on the projection lift, and
the stability of the kernel under two-sided multiplication — but stated each of
them about the *coordinate families* a lift would produce.  The row records the
consequence in one sentence: *`Λ` as a function is not built*, and grading the
clauses while the object they are about is missing would certify a true
statement standing in for the printed one.

This file builds the object.

## The construction

The printed `Λ` sends `z = ∑_{j≤r} x_j q y_j` to the class `[Z_n]_ω` of
`Z_n = ∑_{j≤r} X_{j,n} Q_n Y_{j,n}`.  Two things make that legitimate, and both
are already proved: `rank Z_n ≤ r k_n`, and `eq:rank-frobenius` turning an
operator-norm-null family of rank `O(k_n)` into a family that is null at the
rank weight.  Neither refers to the *shape* `∑_j X_j Q_n Y_j` of the
representative — only to its rank.  So the domain of `Λ` is cut out by the rank
bound alone:

* `rankControlled P` is the submodule of `ℓ∞(M_{d_n})` of sequences with
  `rank a_n ≤ r · rank P_n` for some `r`.  Uniform norm boundedness, the second
  hypothesis of the printed estimate, is automatic in `ℓ∞`.
* `lambdaBounded` is the class map `a ↦ [a_n]_ω` on that submodule, valued in
  the rank-normalized `K_ω` of `Sofic/KOmegaHilbert`; it is a linear map
  because `rankControlled` sits inside the numerator `massBounded` at the rank
  weight.
* `lambdaBounded_congr` is the printed *"its class in `K_ω` depends only on
  `z`"*: two rank-controlled sequences with the same corona class differ by a
  sequence that is null in operator norm along `cofinite`, hence along `ω`, and
  `massNull_of_rank_le_of_tendsto_opNorm` makes it null at the rank weight.
* `rankIdeal P` is the image of `rankControlled P` in the corona, and
  `lambda` — the printed `Λ` — is the induced linear map
  `rankIdeal P →ₗ[ℂ] K_ω`, with `lambda_apply` its defining property.

`coronaIdeal_le_rankIdeal` is what ties the domain to the printed one: the
two-sided ideal `𝓘_q` generated by `q = [Q_n]` lies inside `rankIdeal (Q_n)`,
because `x q y` lifts to `X_n Q_n Y_n`, of rank at most `rank Q_n`.  So `Λ` is
defined on `𝓘_q`, and on the slightly larger domain that the estimate actually
supports.

## The printed clauses, now about `Λ`

* `norm_lambda_projection` is `‖Λ(q)‖ = lim_ω (Tr Q_n / k_n)^{1/2} = 1`;
* `lambda_mul_mul_eq_zero` is `Λ(z) = 0 ⟹ Λ(x z y) = 0` for `x, y` in the
  corona, and `mul_mul_mem_rankIdeal` is the invariance of the domain that
  makes the statement well formed;
* `lambda_conj_eq_zero` is the same for the inner automorphisms, which is the
  invariance the conjugation representation of the next step needs.

The corona here is the cofinite one, `NormMatrixCStarCorona`, which is the
`𝒬` of the theorem statement; the ultrafilter enters only through `K_ω`, and
the hypothesis relating them is the printed *"a free ultrafilter `ω`"* in the
form `ω ≤ cofinite`.
-/

namespace GroupApproximation
namespace RankNormalizedLambda

open Filter Matrix Topology
open KazhdanCornerMatrices InvolutionRankMass ScaledKazhdanTransport
open UltraproductModelConstruction RankNormalizedHilbertization
open HilbertUltraproductSpace KOmegaHilbert
open scoped Matrix.Norms.L2Operator

noncomputable section

variable (Y : ℕ → FiniteModel)

/-! ## Coordinates -/

/-- The coordinate family of a bounded matrix sequence, as a `ℂ`-linear map.
`lp` is an additive subgroup of the product with pointwise operations, so this
is the identity on underlying data. -/
def coord : BoundedMatrixSequence (fun n ↦ Y n) →ₗ[ℂ] MatFam Y where
  toFun a := fun n ↦ a n
  map_add' _ _ := by funext n; rfl
  map_smul' _ _ := by funext n; rfl

@[simp] theorem coord_apply (a : BoundedMatrixSequence (fun n ↦ Y n)) (n : ℕ) :
    coord Y a n = a n := rfl

/-! ## The rank-controlled sequences -/

/-- **The domain of a coordinate representative.**  The bounded matrix
sequences whose coordinate ranks are `O(k_n)` at `k_n = rank P_n`.

The printed proof produces its representatives in the shape
`Z_n = ∑_{j≤r} X_{j,n} P_n Y_{j,n}` and uses exactly two things about them:
`rank Z_n ≤ r k_n`, which is `rank_idealSum_le`, and a uniform operator-norm
bound.  The second is automatic for an element of `ℓ∞`, so the rank bound is
the whole condition, and it is a submodule condition: rank is subadditive and
a scalar multiple is a left multiple. -/
def rankControlled (P : MatFam Y) :
    Submodule ℂ (BoundedMatrixSequence (fun n ↦ Y n)) where
  carrier := {a | ∃ r : ℕ, ∀ n, (a n).rank ≤ r * (P n).rank}
  zero_mem' := by
    refine ⟨0, fun n ↦ ?_⟩
    show ((0 : Matrix (Y n) (Y n) ℂ)).rank ≤ 0 * (P n).rank
    rw [Matrix.rank_zero]
    exact Nat.zero_le _
  add_mem' := by
    rintro a b ⟨ra, ha⟩ ⟨rb, hb⟩
    refine ⟨ra + rb, fun n ↦ ?_⟩
    show ((a n : Matrix (Y n) (Y n) ℂ) + b n).rank ≤ (ra + rb) * (P n).rank
    rw [add_mul]
    exact (InvolutionRankMass.rank_add_le _ _).trans
      (Nat.add_le_add (ha n) (hb n))
  smul_mem' := by
    rintro c a ⟨r, ha⟩
    refine ⟨r, fun n ↦ ?_⟩
    show (c • (a n : Matrix (Y n) (Y n) ℂ)).rank ≤ r * (P n).rank
    have hca : (c • (1 : Matrix (Y n) (Y n) ℂ)) * (a n)
        = c • (a n : Matrix (Y n) (Y n) ℂ) := by
      rw [smul_mul_assoc, one_mul]
    calc (c • (a n : Matrix (Y n) (Y n) ℂ)).rank
        = ((c • (1 : Matrix (Y n) (Y n) ℂ)) * (a n)).rank := by rw [hca]
      _ ≤ (a n).rank := Matrix.rank_mul_le_right _ _
      _ ≤ r * (P n).rank := ha n

theorem mem_rankControlled_iff (P : MatFam Y)
    (a : BoundedMatrixSequence (fun n ↦ Y n)) :
    a ∈ rankControlled Y P ↔ ∃ r : ℕ, ∀ n, (a n).rank ≤ r * (P n).rank :=
  Iff.rfl

/-- **The domain is a two-sided ideal.**  Sandwiching does not raise the rank
above that of the middle factor, so `rankControlled` is stable under
multiplication on either side by an arbitrary bounded sequence.  This is the
printed *"`𝓘_q` is a two-sided ideal of `𝒬`"* at the level of
representatives. -/
theorem mul_mul_mem_rankControlled (P : MatFam Y)
    (x y : BoundedMatrixSequence (fun n ↦ Y n))
    {a : BoundedMatrixSequence (fun n ↦ Y n)} (ha : a ∈ rankControlled Y P) :
    x * a * y ∈ rankControlled Y P := by
  obtain ⟨r, hr⟩ := ha
  refine ⟨r, fun n ↦ ?_⟩
  show ((x n : Matrix (Y n) (Y n) ℂ) * a n * y n).rank ≤ r * (P n).rank
  exact (rank_mul_mul_le (x n) (a n) (y n)).trans (hr n)

/-- A rank-controlled sequence is mass bounded at the rank weight, so it has a
class in `K_ω`.  This is `massBounded_of_rank_le_of_opNorm_le` with the norm
bound supplied by membership in `ℓ∞`. -/
theorem coord_mem_massBounded (P : MatFam Y)
    {a : BoundedMatrixSequence (fun n ↦ Y n)} (ha : a ∈ rankControlled Y P) :
    coord Y a ∈ massBounded Y (rankWeight Y P) := by
  obtain ⟨r, hr⟩ := ha
  exact massBounded_of_rank_le_of_opNorm_le Y P (coord Y a) r ‖a‖ hr
    fun n ↦ boundedMatrixSequence_coord_norm_le (fun m ↦ Y m) a n

/-- The coordinate family of a rank-controlled sequence, landing in the
numerator of `K_ω` at the rank weight. -/
def coordRC (P : MatFam Y) :
    rankControlled Y P →ₗ[ℂ] massBounded Y (rankWeight Y P) :=
  LinearMap.codRestrict (massBounded Y (rankWeight Y P))
    ((coord Y).comp (rankControlled Y P).subtype)
    fun a ↦ coord_mem_massBounded Y P a.2

@[simp] theorem coordRC_coe (P : MatFam Y) (a : rankControlled Y P) :
    ((coordRC Y P a : massBounded Y (rankWeight Y P)) : MatFam Y)
      = coord Y (a : BoundedMatrixSequence (fun n ↦ Y n)) := rfl

/-! ## `Λ` on representatives -/

/-- The printed `K_ω`: the Hilbert-space ultraproduct of the coordinate spaces
`(M_{d_n}(ℂ), Tr(y*x)/k_n)` at the rank weight `k_n = rank P_n`. -/
abbrev KRank (P : MatFam Y) (ω : Ultrafilter ℕ) : Type :=
  KOmega Y (rankWeight Y P) ω (rankWeight_nonneg Y P)

/-- The class map `ξ ↦ [ξ_n]_ω` of `Sofic/KOmegaHilbert`, bundled.  `K_ω` is
the quotient of the numerator by the null families, so this is that quotient's
own projection read at the opaque interface. -/
def mkKLin (P : MatFam Y) (ω : Ultrafilter ℕ) :
    massBounded Y (rankWeight Y P) →ₗ[ℂ] KRank Y P ω :=
  Submodule.mkQ (nullIn Y (rankWeight Y P) ω)

/-- **`Λ` on a coordinate representative**: the printed `Λ(z) = [Z_n]_ω`,
before the passage to the corona element `z` that `Z_n` represents. -/
def lambdaBounded (P : MatFam Y) (ω : Ultrafilter ℕ) :
    rankControlled Y P →ₗ[ℂ] KRank Y P ω :=
  (mkKLin Y P ω).comp (coordRC Y P)

@[simp] theorem lambdaBounded_apply (P : MatFam Y) (ω : Ultrafilter ℕ)
    (a : rankControlled Y P) :
    lambdaBounded Y P ω a
      = mkK Y (rankWeight Y P) ω (rankWeight_nonneg Y P) (coordRC Y P a) :=
  rfl

/-- `Λ` kills exactly the representatives that are null at the rank weight. -/
theorem lambdaBounded_eq_zero_iff (P : MatFam Y) (ω : Ultrafilter ℕ)
    (a : rankControlled Y P) :
    lambdaBounded Y P ω a = 0
      ↔ coord Y (a : BoundedMatrixSequence (fun n ↦ Y n))
          ∈ massNull Y (rankWeight Y P) ω := by
  show (Submodule.Quotient.mk (coordRC Y P a) : Vec Y (rankWeight Y P) ω) = 0
    ↔ _
  rw [Submodule.Quotient.mk_eq_zero]
  exact Iff.rfl

/-- **The analytic heart of well-definedness.**  A rank-controlled sequence
whose operator norms vanish along `ω` has zero class in `K_ω`: this is
`eq:rank-frobenius` applied to the difference of two coordinate
representatives of the same element. -/
theorem lambdaBounded_eq_zero_of_tendsto (P : MatFam Y) (ω : Ultrafilter ℕ)
    (a : rankControlled Y P)
    (ha : Tendsto (fun n ↦ ‖(a : BoundedMatrixSequence (fun n ↦ Y n)) n‖)
      (ω : Filter ℕ) (𝓝 0)) :
    lambdaBounded Y P ω a = 0 := by
  obtain ⟨r, hr⟩ := a.2
  rw [lambdaBounded_eq_zero_iff]
  exact massNull_of_rank_le_of_tendsto_opNorm Y ω P
    (coord Y (a : BoundedMatrixSequence (fun n ↦ Y n))) r hr ha

/-- **Kernel stability on representatives.**  The printed *"`Λ(z) = 0` implies
`Λ(x z y) = 0`, since bounded lifts of `x` and `y` multiply `‖Z_n‖_F` by a
bounded factor"*. -/
theorem lambdaBounded_mul_mul_eq_zero (P : MatFam Y) (ω : Ultrafilter ℕ)
    (x y : BoundedMatrixSequence (fun n ↦ Y n)) (a : rankControlled Y P)
    (ha : lambdaBounded Y P ω a = 0) :
    lambdaBounded Y P ω
        ⟨x * (a : BoundedMatrixSequence (fun n ↦ Y n)) * y,
          mul_mul_mem_rankControlled Y P x y a.2⟩ = 0 := by
  rw [lambdaBounded_eq_zero_iff] at ha ⊢
  exact massNull_mul_mul Y (rankWeight Y P) ω (coord Y x) (coord Y y)
    (coord Y (a : BoundedMatrixSequence (fun n ↦ Y n))) ‖x‖ ‖y‖
    (fun n ↦ boundedMatrixSequence_coord_norm_le (fun m ↦ Y m) x n)
    (fun n ↦ boundedMatrixSequence_coord_norm_le (fun m ↦ Y m) y n) ha

/-! ## `Λ` on the corona ideal -/

section Corona

variable [∀ n, Nonempty (Y n)]

/-- The corona quotient map as a `ℂ`-linear map. -/
def coronaLinear :
    BoundedMatrixSequence (fun n ↦ Y n) →ₗ[ℂ]
      NormMatrixCStarCorona (fun n ↦ Y n) :=
  (normMatrixCStarCoronaQuotient (fun n ↦ Y n)).toAlgHom.toLinearMap

@[simp] theorem coronaLinear_apply (a : BoundedMatrixSequence (fun n ↦ Y n)) :
    coronaLinear Y a = normMatrixCStarCoronaMk (fun n ↦ Y n) a := rfl

/-- **`Λ` is well defined.**  Two rank-controlled coordinate representatives of
the same corona element have the same class in `K_ω`.

This is the printed *"Its class in `K_ω` depends only on `z`: a sequence
`Z_n'` obtained from a second decomposition satisfies `‖Z_n − Z_n'‖ → 0` and
`rank(Z_n − Z_n') ≤ (r+r') k_n`, so `‖Z_n − Z_n'‖_F² / k_n → 0`"*.  Nothing
about the *decompositions* is used, only that the two representatives have the
same class in the corona, which is exactly what having a common value
`z = ∑_j x_j q y_j` gives. -/
theorem lambdaBounded_congr (P : MatFam Y) (ω : Ultrafilter ℕ)
    (hω : (ω : Filter ℕ) ≤ cofinite) (a b : rankControlled Y P)
    (h : coronaLinear Y (a : BoundedMatrixSequence (fun n ↦ Y n))
      = coronaLinear Y (b : BoundedMatrixSequence (fun n ↦ Y n))) :
    lambdaBounded Y P ω a = lambdaBounded Y P ω b := by
  have hmk : normMatrixCStarCoronaMk (fun n ↦ Y n)
      ((a : BoundedMatrixSequence (fun n ↦ Y n)) -
        (b : BoundedMatrixSequence (fun n ↦ Y n))) = 0 := by
    rw [map_sub]
    exact sub_eq_zero.mpr h
  have hnull : IsNullMatrixSequence (fun n ↦ Y n) cofinite
      ((a : BoundedMatrixSequence (fun n ↦ Y n)) -
        (b : BoundedMatrixSequence (fun n ↦ Y n))) :=
    (normMatrixCStarCoronaMk_eq_zero_iff (fun n ↦ Y n) _).mp hmk
  have homega : IsNullMatrixSequence (fun n ↦ Y n) (ω : Filter ℕ)
      ((a : BoundedMatrixSequence (fun n ↦ Y n)) -
        (b : BoundedMatrixSequence (fun n ↦ Y n))) :=
    IsNullMatrixSequence.mono (fun m ↦ Y m) cofinite hω hnull
  have hzero : lambdaBounded Y P ω (a - b) = 0 :=
    lambdaBounded_eq_zero_of_tendsto Y P ω (a - b) homega
  rw [map_sub] at hzero
  exact sub_eq_zero.mp hzero

/-- **The domain of `Λ` in the corona.**  The image of the rank-controlled
sequences.  `coronaIdeal_le_rankIdeal` shows it contains the printed ideal
`𝓘_q`; it is the largest domain on which `eq:rank-frobenius` licenses the
construction. -/
def rankIdeal (P : MatFam Y) :
    Submodule ℂ (NormMatrixCStarCorona (fun n ↦ Y n)) :=
  Submodule.map (coronaLinear Y) (rankControlled Y P)

theorem mem_rankIdeal_iff (P : MatFam Y)
    (z : NormMatrixCStarCorona (fun n ↦ Y n)) :
    z ∈ rankIdeal Y P ↔ ∃ a : rankControlled Y P,
      coronaLinear Y (a : BoundedMatrixSequence (fun n ↦ Y n)) = z := by
  constructor
  · intro hz
    obtain ⟨a, ha, hfa⟩ := Submodule.mem_map.1 hz
    exact ⟨⟨a, ha⟩, hfa⟩
  · rintro ⟨a, ha⟩
    exact Submodule.mem_map.2
      ⟨(a : BoundedMatrixSequence (fun n ↦ Y n)), a.2, ha⟩

/-- A chosen rank-controlled coordinate representative. -/
def lift (P : MatFam Y) (z : rankIdeal Y P) : rankControlled Y P :=
  Classical.choose
    ((mem_rankIdeal_iff Y P (z : NormMatrixCStarCorona (fun n ↦ Y n))).1 z.2)

theorem coronaLinear_lift (P : MatFam Y) (z : rankIdeal Y P) :
    coronaLinear Y
        ((lift Y P z : rankControlled Y P) :
          BoundedMatrixSequence (fun n ↦ Y n))
      = (z : NormMatrixCStarCorona (fun n ↦ Y n)) :=
  Classical.choose_spec
    ((mem_rankIdeal_iff Y P (z : NormMatrixCStarCorona (fun n ↦ Y n))).1 z.2)

/-- Every rank-controlled representative computes the same class as the chosen
one; this is `lambdaBounded_congr` in the form the construction below uses. -/
theorem lambdaBounded_lift (P : MatFam Y) (ω : Ultrafilter ℕ)
    (hω : (ω : Filter ℕ) ≤ cofinite) (z : rankIdeal Y P)
    (a : rankControlled Y P)
    (ha : coronaLinear Y (a : BoundedMatrixSequence (fun n ↦ Y n))
      = (z : NormMatrixCStarCorona (fun n ↦ Y n))) :
    lambdaBounded Y P ω (lift Y P z) = lambdaBounded Y P ω a :=
  lambdaBounded_congr Y P ω hω _ a (by rw [coronaLinear_lift, ha])

/-- **`Λ`.**  The printed rank-normalized Hilbertization: the linear map from
the ideal to `K_ω` sending an element to the class of any of its
rank-controlled coordinate representatives.

This is the object `CO.20` is about.  Every clause of the printed paragraph is
recorded below as a statement about it: `lambda_apply` is the recipe,
`norm_lambda_projection` is `‖Λ(q)‖ = 1`, and `lambda_mul_mul_eq_zero` is
`Λ(z) = 0 ⟹ Λ(x z y) = 0`. -/
def lambda (P : MatFam Y) (ω : Ultrafilter ℕ)
    (hω : (ω : Filter ℕ) ≤ cofinite) :
    rankIdeal Y P →ₗ[ℂ] KRank Y P ω where
  toFun z := lambdaBounded Y P ω (lift Y P z)
  map_add' z w := by
    have h1 : ((lift Y P z + lift Y P w : rankControlled Y P) :
          BoundedMatrixSequence (fun n ↦ Y n))
        = (lift Y P z : BoundedMatrixSequence (fun n ↦ Y n))
          + (lift Y P w : BoundedMatrixSequence (fun n ↦ Y n)) := rfl
    have h2 : ((z + w : rankIdeal Y P) :
          NormMatrixCStarCorona (fun n ↦ Y n))
        = (z : NormMatrixCStarCorona (fun n ↦ Y n))
          + (w : NormMatrixCStarCorona (fun n ↦ Y n)) := rfl
    have hsum : coronaLinear Y
        ((lift Y P z + lift Y P w : rankControlled Y P) :
          BoundedMatrixSequence (fun n ↦ Y n))
        = ((z + w : rankIdeal Y P) :
          NormMatrixCStarCorona (fun n ↦ Y n)) := by
      rw [h1, h2, map_add, coronaLinear_lift, coronaLinear_lift]
    show lambdaBounded Y P ω (lift Y P (z + w))
      = lambdaBounded Y P ω (lift Y P z) + lambdaBounded Y P ω (lift Y P w)
    rw [lambdaBounded_lift Y P ω hω (z + w) _ hsum, map_add]
  map_smul' c z := by
    have h1 : ((c • lift Y P z : rankControlled Y P) :
          BoundedMatrixSequence (fun n ↦ Y n))
        = c • (lift Y P z : BoundedMatrixSequence (fun n ↦ Y n)) := rfl
    have h2 : ((c • z : rankIdeal Y P) :
          NormMatrixCStarCorona (fun n ↦ Y n))
        = c • (z : NormMatrixCStarCorona (fun n ↦ Y n)) := rfl
    have hsm : coronaLinear Y
        ((c • lift Y P z : rankControlled Y P) :
          BoundedMatrixSequence (fun n ↦ Y n))
        = ((c • z : rankIdeal Y P) :
          NormMatrixCStarCorona (fun n ↦ Y n)) := by
      rw [h1, h2, map_smul, coronaLinear_lift]
    show lambdaBounded Y P ω (lift Y P (c • z))
      = c • lambdaBounded Y P ω (lift Y P z)
    rw [lambdaBounded_lift Y P ω hω (c • z) _ hsm, map_smul]

/-- **The defining property of `Λ`.**  On any rank-controlled coordinate
representative of `z`, `Λ(z)` is the `K_ω`-class of that representative. -/
theorem lambda_apply (P : MatFam Y) (ω : Ultrafilter ℕ)
    (hω : (ω : Filter ℕ) ≤ cofinite) (z : rankIdeal Y P)
    (a : rankControlled Y P)
    (ha : coronaLinear Y (a : BoundedMatrixSequence (fun n ↦ Y n))
      = (z : NormMatrixCStarCorona (fun n ↦ Y n))) :
    lambda Y P ω hω z = lambdaBounded Y P ω a :=
  lambdaBounded_lift Y P ω hω z a ha

/-! ## The printed ideal `𝓘_q` sits inside the domain -/

/-- The printed two-sided ideal `𝓘_q` of finite sums `∑_{j≤r} x_j q y_j`. -/
def coronaIdeal (q : NormMatrixCStarCorona (fun n ↦ Y n)) :
    Submodule ℂ (NormMatrixCStarCorona (fun n ↦ Y n)) :=
  Submodule.span ℂ {z | ∃ x y, z = x * q * y}

/-- A single generator `x q y` of the printed ideal is rank controlled: it
lifts to `X_n Q_n Y_n`, whose rank is at most `rank Q_n = k_n`.  This is the
printed `rank(Z_n) ≤ r k_n` in the case `r = 1`. -/
theorem mul_mul_mem_rankIdeal (Q : BoundedMatrixSequence (fun n ↦ Y n))
    (x y : NormMatrixCStarCorona (fun n ↦ Y n)) :
    x * coronaLinear Y Q * y ∈ rankIdeal Y (coord Y Q) := by
  obtain ⟨a, rfl⟩ := normMatrixCStarCoronaMk_surjective (fun m ↦ Y m) x
  obtain ⟨b, rfl⟩ := normMatrixCStarCoronaMk_surjective (fun m ↦ Y m) y
  have hQ : Q ∈ rankControlled Y (coord Y Q) := by
    refine ⟨1, fun n ↦ ?_⟩
    show (Q n).rank ≤ 1 * (Q n).rank
    rw [one_mul]
  refine (mem_rankIdeal_iff Y (coord Y Q) _).2
    ⟨⟨a * Q * b, mul_mul_mem_rankControlled Y (coord Y Q) a b hQ⟩, ?_⟩
  show normMatrixCStarCoronaMk (fun m ↦ Y m) (a * Q * b)
    = normMatrixCStarCoronaMk (fun m ↦ Y m) a
      * normMatrixCStarCoronaMk (fun m ↦ Y m) Q
      * normMatrixCStarCoronaMk (fun m ↦ Y m) b
  rw [map_mul, map_mul]

/-- **`Λ` is defined on the printed ideal.**  The two-sided ideal generated by
`q = [Q_n]` lies in the domain of `Λ`. -/
theorem coronaIdeal_le_rankIdeal (Q : BoundedMatrixSequence (fun n ↦ Y n)) :
    coronaIdeal Y (coronaLinear Y Q) ≤ rankIdeal Y (coord Y Q) := by
  refine Submodule.span_le.2 ?_
  rintro _ ⟨x, y, rfl⟩
  exact mul_mul_mem_rankIdeal Y Q x y

/-! ## `‖Λ(q)‖ = 1` -/

/-- **CO.20, `‖Λ(q)‖ = 1`, about `Λ`.**  The value of `Λ` at the corona class
of a projection lift of positive rank is a unit vector:
`‖Λ(q)‖ = lim_ω (Tr Q_n / k_n)^{1/2} = 1`, because the coordinate mass of an
orthogonal projection is its rank and the weight is that rank. -/
theorem norm_lambda_projection (Q : BoundedMatrixSequence (fun n ↦ Y n))
    (ω : Ultrafilter ℕ) (hω : (ω : Filter ℕ) ≤ cofinite)
    (hproj : ∀ n, IsOrthogonalProjectionMatrix (Q n))
    (hrk : ∀ n, 0 < (Q n).rank) (z : rankIdeal Y (coord Y Q))
    (hz : (z : NormMatrixCStarCorona (fun n ↦ Y n)) = coronaLinear Y Q) :
    ‖lambda Y (coord Y Q) ω hω z‖ = 1 := by
  have hQ : Q ∈ rankControlled Y (coord Y Q) := by
    refine ⟨1, fun n ↦ ?_⟩
    show (Q n).rank ≤ 1 * (Q n).rank
    rw [one_mul]
  rw [lambda_apply Y (coord Y Q) ω hω z ⟨Q, hQ⟩ hz.symm, lambdaBounded_apply]
  exact norm_mkK_projection Y ω (coord Y Q) hproj hrk _ rfl

/-! ## Kernel stability -/

/-- The domain of `Λ` is a two-sided ideal of the corona. -/
theorem mul_mem_rankIdeal (P : MatFam Y)
    (x y : NormMatrixCStarCorona (fun n ↦ Y n)) {z}
    (hz : z ∈ rankIdeal Y P) : x * z * y ∈ rankIdeal Y P := by
  obtain ⟨a, ha⟩ := (mem_rankIdeal_iff Y P z).1 hz
  have ha' : normMatrixCStarCoronaMk (fun m ↦ Y m)
      (a : BoundedMatrixSequence (fun n ↦ Y n)) = z := ha
  obtain ⟨u, rfl⟩ := normMatrixCStarCoronaMk_surjective (fun m ↦ Y m) x
  obtain ⟨v, rfl⟩ := normMatrixCStarCoronaMk_surjective (fun m ↦ Y m) y
  refine (mem_rankIdeal_iff Y P _).2
    ⟨⟨u * (a : BoundedMatrixSequence (fun n ↦ Y n)) * v,
      mul_mul_mem_rankControlled Y P u v a.2⟩, ?_⟩
  show normMatrixCStarCoronaMk (fun m ↦ Y m)
      (u * (a : BoundedMatrixSequence (fun n ↦ Y n)) * v)
    = normMatrixCStarCoronaMk (fun m ↦ Y m) u * z
      * normMatrixCStarCoronaMk (fun m ↦ Y m) v
  rw [map_mul, map_mul, ha']

/-- **CO.20, kernel stability, about `Λ`.**  The printed *"`Λ(z) = 0` implies
`Λ(x z y) = 0` for all `x, y ∈ 𝒬`"*. -/
theorem lambda_mul_mul_eq_zero (P : MatFam Y) (ω : Ultrafilter ℕ)
    (hω : (ω : Filter ℕ) ≤ cofinite) (z : rankIdeal Y P)
    (hz : lambda Y P ω hω z = 0)
    (x y : NormMatrixCStarCorona (fun n ↦ Y n)) (w : rankIdeal Y P)
    (hw : (w : NormMatrixCStarCorona (fun n ↦ Y n))
      = x * (z : NormMatrixCStarCorona (fun n ↦ Y n)) * y) :
    lambda Y P ω hω w = 0 := by
  obtain ⟨u, hu⟩ := normMatrixCStarCoronaMk_surjective (fun m ↦ Y m) x
  obtain ⟨v, hv⟩ := normMatrixCStarCoronaMk_surjective (fun m ↦ Y m) y
  have hlift : lambdaBounded Y P ω (lift Y P z) = 0 := hz
  have hl : normMatrixCStarCoronaMk (fun m ↦ Y m)
      ((lift Y P z : rankControlled Y P) :
        BoundedMatrixSequence (fun n ↦ Y n))
      = (z : NormMatrixCStarCorona (fun n ↦ Y n)) :=
    coronaLinear_lift Y P z
  have hsand : coronaLinear Y
      (u * ((lift Y P z : rankControlled Y P) :
          BoundedMatrixSequence (fun n ↦ Y n)) * v)
      = (w : NormMatrixCStarCorona (fun n ↦ Y n)) := by
    show normMatrixCStarCoronaMk (fun m ↦ Y m)
        (u * ((lift Y P z : rankControlled Y P) :
          BoundedMatrixSequence (fun n ↦ Y n)) * v) = _
    rw [map_mul, map_mul, hl, hu, hv, hw]
  rw [lambda_apply Y P ω hω w
    ⟨u * ((lift Y P z : rankControlled Y P) :
        BoundedMatrixSequence (fun n ↦ Y n)) * v,
      mul_mul_mem_rankControlled Y P u v (lift Y P z).2⟩ hsand]
  exact lambdaBounded_mul_mul_eq_zero Y P ω u v (lift Y P z) hlift

/-- **Inner invariance.**  The printed *"`𝓘_q` is a two-sided ideal of `𝒬`
invariant under inner automorphisms"*, together with the kernel stability that
lets the conjugation representation act on the image of `Λ`. -/
theorem lambda_conj_eq_zero (P : MatFam Y) (ω : Ultrafilter ℕ)
    (hω : (ω : Filter ℕ) ≤ cofinite) (z : rankIdeal Y P)
    (hz : lambda Y P ω hω z = 0)
    (x : NormMatrixCStarCorona (fun n ↦ Y n)) (w : rankIdeal Y P)
    (hw : (w : NormMatrixCStarCorona (fun n ↦ Y n))
      = x * (z : NormMatrixCStarCorona (fun n ↦ Y n)) * star x) :
    lambda Y P ω hω w = 0 :=
  lambda_mul_mul_eq_zero Y P ω hω z hz x (star x) w hw

end Corona

end

end RankNormalizedLambda
end GroupApproximation
