import GroupApproximation.Sofic.InvolutionRankMass
import GroupApproximation.Sofic.KOmegaHilbert

/-!
# The rank-normalized Hilbertization of the ideal `Q q Q`

Proof-ledger row `CO.20`, the paragraph *A Hilbert space attached to `q`* in
the proof of the theorem labelled `thm:projection-collapse` in
`non_mf_groups_exist.tex` (navigate by the label; that file is under
concurrent edit).

The printed step fixes a projection lift `Q_n` of `q` with
`k_n = rank Q_n ≥ 1`, gives `M_{d_n}(ℂ)` the inner product
`⟨x,y⟩_n = Tr(y* x)/k_n`, and forms the Hilbert-space ultraproduct `K_ω` of
these spaces along `ω`.  For an element `z = ∑_{j ≤ r} x_j q y_j` of the
two-sided ideal `I_q` it takes coordinate lifts and sets
`Z_n = ∑_{j ≤ r} X_{j,n} Q_n Y_{j,n}`, of rank at most `r k_n`, and argues
from

  `‖Z‖_F² ≤ rank(Z) ‖Z‖² ≤ r k_n ‖Z‖²`                   (eq:rank-frobenius)

that `(Z_n)` is bounded for `⟨·,·⟩_n`, that its class `Λ(z) = [Z_n]_ω`
depends only on `z`, that `‖Λ(q)‖ = 1`, and that `Λ(z) = 0` forces
`Λ(x z y) = 0`.

Everything in that list except the choice of lifts is proved here, against
the weight-`w` ultraproduct `K_ω` of `Sofic/KOmegaHilbert`, taken at the
**rank weight** `w n = k_n = rank (Q n)`:

* `rank_idealSum_le` and `matMass_idealSum_le` are the two halves of
  `eq:rank-frobenius`;
* `massBounded_of_rank_le_of_opNorm_le` puts a coordinate representative in
  the numerator `massBounded Y (rankWeight Y Q)`, so it has a class in `K_ω`;
* `massNull_of_rank_le_of_tendsto_opNorm` is the well-definedness step: two
  representatives of the same ideal element differ by a family of rank
  `O(k_n)` whose operator norm vanishes along `ω`, hence by a null family;
* `matMass_eq_rank_of_isOrthogonalProjection` and `norm_mkK_projection` give
  `‖Λ(q)‖ = lim_ω (Tr Q_n / k_n)^{1/2} = 1`;
* `massNull_mul_mul` and `massBounded_mul_mul` are the printed *"bounded
  lifts of `x` and `y` multiply `‖Z_n‖_F` by a bounded factor"*, i.e. the
  stability of `ker Λ` and of the ideal under left and right multiplication;
* `massNull_unitary_conj` and `massBounded_unitary_conj` are the same for the
  inner automorphisms under which `I_q` is invariant, and are what makes the
  conjugation representation `π` of the next step act on `K_ω`.

What is deliberately **not** here is the map `Λ` itself as a function on the
corona ideal: that needs a choice of bounded coordinate lift for each element
of `Q`, which is a property of the ambient corona and not of the rank
normalization.  The statements above are exactly the estimates that make such
a choice legitimate, each stated about the coordinate families the lift would
produce.
-/

namespace GroupApproximation
namespace RankNormalizedHilbertization

open Filter Matrix Topology
open KazhdanCornerMatrices InvolutionRankMass ScaledKazhdanTransport
open UltrafilterLimit UltraproductModelConstruction UltraproductScaledTransport
open HilbertUltraproductSpace KOmegaHilbert
open scoped Matrix.Norms.L2Operator

noncomputable section

/-! ## `eq:rank-frobenius`: the rank of a coordinate representative -/

/-- Rank is subadditive along a finite sum, by `rank_add_le`. -/
theorem rank_sum_le {Y : Type*} [Fintype Y] {ι : Type*}
    (s : Finset ι) (f : ι → Matrix Y Y ℂ) :
    (∑ i ∈ s, f i).rank ≤ ∑ i ∈ s, (f i).rank := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert a t ha ih =>
      rw [Finset.sum_insert ha, Finset.sum_insert ha]
      exact (rank_add_le _ _).trans (Nat.add_le_add_left ih _)

/-- Sandwiching does not raise the rank above that of the middle factor:
`rank (A P B) ≤ rank P`. -/
theorem rank_mul_mul_le {Y : Type*} [Fintype Y] (A P B : Matrix Y Y ℂ) :
    (A * P * B).rank ≤ P.rank :=
  (Matrix.rank_mul_le_left (A * P) B).trans (Matrix.rank_mul_le_right A P)

/-- **`eq:rank-frobenius`, rank half.**  A coordinate representative
`Z = ∑_{j < r} X_j P Y_j` of an element of the ideal generated by `P`,
written with `r` summands, has rank at most `r · rank P`. -/
theorem rank_idealSum_le {Y : Type*} [Fintype Y] (r : ℕ)
    (P : Matrix Y Y ℂ) (X Z : ℕ → Matrix Y Y ℂ) :
    (∑ j ∈ Finset.range r, X j * P * Z j).rank ≤ r * P.rank := by
  refine (rank_sum_le _ _).trans ?_
  calc ∑ j ∈ Finset.range r, (X j * P * Z j).rank
      ≤ ∑ _j ∈ Finset.range r, P.rank :=
        Finset.sum_le_sum fun j _ ↦ rank_mul_mul_le (X j) P (Z j)
    _ = r * P.rank := by
        rw [Finset.sum_const, Finset.card_range, smul_eq_mul]

/-- **`eq:rank-frobenius`.**  The unnormalized Frobenius mass of a coordinate
representative with `r` summands is at most `r · rank P · ‖Z‖²`: the squares
of the singular values number at most `rank Z ≤ r · rank P`, and each is at
most the squared operator norm. -/
theorem matMass_idealSum_le {Y : Type*} [Fintype Y] [DecidableEq Y] (r : ℕ)
    (P : Matrix Y Y ℂ) (X Z : ℕ → Matrix Y Y ℂ) :
    matMass (∑ j ∈ Finset.range r, X j * P * Z j)
      ≤ (r : ℝ) * (P.rank : ℝ)
          * ‖∑ j ∈ Finset.range r, X j * P * Z j‖ ^ 2 := by
  refine (matMass_le_rank_mul_sq_opNorm _).trans ?_
  refine mul_le_mul_of_nonneg_right ?_ (sq_nonneg _)
  exact_mod_cast rank_idealSum_le r P X Z

/-! ## The rank weight `k_n = rank Q_n` -/

/-- The printed weight `k_n = rank Q_n` of the collapse proof's Step 3. -/
def rankWeight (Y : ℕ → FiniteModel) (P : MatFam Y) : ℕ → ℝ :=
  fun n ↦ ((P n).rank : ℝ)

theorem rankWeight_nonneg (Y : ℕ → FiniteModel) (P : MatFam Y) :
    ∀ n, 0 ≤ rankWeight Y P n := fun _ ↦ Nat.cast_nonneg _

/-- The Frobenius mass of an orthogonal projection is its rank:
`Tr(p* p) = Tr p = rank p`. -/
theorem matMass_eq_rank_of_isOrthogonalProjection {Y : Type*} [Fintype Y]
    [DecidableEq Y] {p : Matrix Y Y ℂ} (hp : IsOrthogonalProjectionMatrix p) :
    matMass p = (p.rank : ℝ) := by
  rw [matMass_eq_re_trace_conjTranspose_mul, hp.1, hp.2,
    re_trace_eq_rank_of_isOrthogonalProjection hp]

/-! ## `Λ` is defined on the ideal, and well defined -/

/-- **CO.20, boundedness.**  A coordinate family of uniformly bounded operator
norm whose ranks are `O(k_n)` is mass bounded at the rank weight, so it has a
class in the rank-normalized ultraproduct.  This is the printed *"and `(Z_n)`
is a bounded sequence for the inner products `⟨·,·⟩_n`"*. -/
theorem massBounded_of_rank_le_of_opNorm_le (Y : ℕ → FiniteModel)
    (P Z : MatFam Y) (r : ℕ) (C : ℝ)
    (hrank : ∀ n, (Z n).rank ≤ r * (P n).rank)
    (hnorm : ∀ n, ‖Z n‖ ≤ C) :
    Z ∈ massBounded Y (rankWeight Y P) := by
  refine ⟨(r : ℝ) * C ^ 2, fun n ↦ ?_⟩
  show matMass (Z n) ≤ (r : ℝ) * C ^ 2 * ((P n).rank : ℝ)
  have hr : (0 : ℝ) ≤ (r : ℝ) := Nat.cast_nonneg _
  have hrk : (0 : ℝ) ≤ ((P n).rank : ℝ) := Nat.cast_nonneg _
  have h2 : ((Z n).rank : ℝ) ≤ (r : ℝ) * ((P n).rank : ℝ) := by
    exact_mod_cast hrank n
  have h3 : ‖Z n‖ ^ 2 ≤ C ^ 2 := by
    have h0 : (0 : ℝ) ≤ ‖Z n‖ := norm_nonneg _
    nlinarith [hnorm n]
  calc matMass (Z n) ≤ ((Z n).rank : ℝ) * ‖Z n‖ ^ 2 :=
        matMass_le_rank_mul_sq_opNorm (Z n)
    _ ≤ ((r : ℝ) * ((P n).rank : ℝ)) * ‖Z n‖ ^ 2 :=
        mul_le_mul_of_nonneg_right h2 (sq_nonneg _)
    _ ≤ ((r : ℝ) * ((P n).rank : ℝ)) * C ^ 2 :=
        mul_le_mul_of_nonneg_left h3 (mul_nonneg hr hrk)
    _ = (r : ℝ) * C ^ 2 * ((P n).rank : ℝ) := by ring

/-- **CO.20, well-definedness.**  Two coordinate representatives of the same
ideal element differ by a family whose rank is `O(k_n)` and whose operator
norm vanishes along `ω`; by `eq:rank-frobenius` such a family is null at the
rank weight, so the class in `K_ω` depends only on the ideal element and not
on the chosen decomposition. -/
theorem massNull_of_rank_le_of_tendsto_opNorm (Y : ℕ → FiniteModel)
    (ω : Ultrafilter ℕ) (P D : MatFam Y) (r : ℕ)
    (hrank : ∀ n, (D n).rank ≤ r * (P n).rank)
    (hnorm : Tendsto (fun n ↦ ‖D n‖) (ω : Filter ℕ) (𝓝 0)) :
    D ∈ massNull Y (rankWeight Y P) ω := by
  intro ε hε
  have hlim : Tendsto (fun n ↦ (r : ℝ) * ‖D n‖ ^ 2) (ω : Filter ℕ) (𝓝 0) := by
    have h2 : Tendsto (fun n ↦ (r : ℝ) * ‖D n‖ ^ 2) (ω : Filter ℕ)
        (𝓝 ((r : ℝ) * 0 ^ 2)) :=
      Filter.Tendsto.mul
        (tendsto_const_nhds : Tendsto (fun _ : ℕ ↦ (r : ℝ)) _ _)
        (hnorm.pow 2)
    simpa using h2
  have hev : ∀ᶠ n in (ω : Filter ℕ), (r : ℝ) * ‖D n‖ ^ 2 ≤ ε := by
    filter_upwards [(Metric.tendsto_nhds.mp hlim) ε hε] with n hn
    rw [Real.dist_eq, sub_zero] at hn
    exact (lt_of_abs_lt hn).le
  filter_upwards [hev] with n hn
  show matMass (D n) ≤ ε * clipWeight (rankWeight Y P) n
  rw [clipWeight_eq (rankWeight Y P) (rankWeight_nonneg Y P) n]
  show matMass (D n) ≤ ε * ((P n).rank : ℝ)
  have hrk : (0 : ℝ) ≤ ((P n).rank : ℝ) := Nat.cast_nonneg _
  have h2 : ((D n).rank : ℝ) ≤ (r : ℝ) * ((P n).rank : ℝ) := by
    exact_mod_cast hrank n
  calc matMass (D n) ≤ ((D n).rank : ℝ) * ‖D n‖ ^ 2 :=
        matMass_le_rank_mul_sq_opNorm (D n)
    _ ≤ ((r : ℝ) * ((P n).rank : ℝ)) * ‖D n‖ ^ 2 :=
        mul_le_mul_of_nonneg_right h2 (sq_nonneg _)
    _ = ((r : ℝ) * ‖D n‖ ^ 2) * ((P n).rank : ℝ) := by ring
    _ ≤ ε * ((P n).rank : ℝ) := mul_le_mul_of_nonneg_right hn hrk

/-! ## `‖Λ(q)‖ = 1` -/

/-- The projection family is mass bounded at its own rank weight, with
constant `1`: its coordinate masses are exactly the weights. -/
theorem projection_mem_massBounded (Y : ℕ → FiniteModel) (P : MatFam Y)
    (hP : ∀ n, IsOrthogonalProjectionMatrix (P n)) :
    P ∈ massBounded Y (rankWeight Y P) := by
  refine ⟨1, fun n ↦ ?_⟩
  show matMass (P n) ≤ 1 * ((P n).rank : ℝ)
  rw [one_mul]
  exact le_of_eq (matMass_eq_rank_of_isOrthogonalProjection (hP n))

/-- **CO.20, `‖Λ(q)‖ = 1`.**  The class of the projection lift is a unit
vector of the rank-normalized ultraproduct:
`‖Λ(q)‖ = lim_ω (Tr Q_n / k_n)^{1/2} = 1`, because the coordinate mass of an
orthogonal projection is its rank and the weight is that rank. -/
theorem norm_mkK_projection (Y : ℕ → FiniteModel) (ω : Ultrafilter ℕ)
    (P : MatFam Y) (hP : ∀ n, IsOrthogonalProjectionMatrix (P n))
    (hrk : ∀ n, 0 < (P n).rank)
    (ξ : massBounded Y (rankWeight Y P)) (hξ : (ξ : MatFam Y) = P) :
    ‖mkK Y (rankWeight Y P) ω (rankWeight_nonneg Y P) ξ‖ = 1 := by
  have hfun : (fun n ↦ matMass ((ξ : MatFam Y) n) / rankWeight Y P n)
      = fun _ : ℕ ↦ (1 : ℝ) := by
    funext n
    rw [hξ]
    show matMass (P n) / ((P n).rank : ℝ) = 1
    rw [matMass_eq_rank_of_isOrthogonalProjection (hP n)]
    exact div_self (Nat.cast_ne_zero.mpr (hrk n).ne')
  rw [norm_mkK, hfun, ulim_const, Real.sqrt_one]

/-- The same statement at the canonical representative. -/
theorem norm_mkK_projection_mk (Y : ℕ → FiniteModel) (ω : Ultrafilter ℕ)
    (P : MatFam Y) (hP : ∀ n, IsOrthogonalProjectionMatrix (P n))
    (hrk : ∀ n, 0 < (P n).rank) :
    ‖mkK Y (rankWeight Y P) ω (rankWeight_nonneg Y P)
        ⟨P, projection_mem_massBounded Y P hP⟩‖ = 1 :=
  norm_mkK_projection Y ω P hP hrk _ rfl

/-! ## Stability of the ideal and of `ker Λ` -/

/-- Two-sided multiplication multiplies the Frobenius mass by at most
`‖A‖² ‖B‖²`. -/
theorem matMass_mul_mul_le {Y : Type*} [Fintype Y] [DecidableEq Y]
    (A X B : Matrix Y Y ℂ) :
    matMass (A * X * B) ≤ ‖A‖ ^ 2 * ‖B‖ ^ 2 * matMass X := by
  calc matMass (A * X * B) ≤ ‖B‖ ^ 2 * matMass (A * X) :=
        matMass_mul_le_right (A * X) B
    _ ≤ ‖B‖ ^ 2 * (‖A‖ ^ 2 * matMass X) :=
        mul_le_mul_of_nonneg_left (matMass_mul_le_left A X) (sq_nonneg _)
    _ = ‖A‖ ^ 2 * ‖B‖ ^ 2 * matMass X := by ring

/-- **CO.20, the ideal is stable.**  Sandwiching a mass-bounded family between
uniformly bounded families keeps it mass bounded: this is the numerator half
of *"bounded lifts of `x` and `y` multiply `‖Z_n‖_F` by a bounded factor"*. -/
theorem massBounded_mul_mul (Y : ℕ → FiniteModel) (w : ℕ → ℝ)
    (A B ξ : MatFam Y) (Ca Cb : ℝ)
    (hA : ∀ n, ‖A n‖ ≤ Ca) (hB : ∀ n, ‖B n‖ ≤ Cb)
    (hξ : ξ ∈ massBounded Y w) :
    (fun n ↦ A n * ξ n * B n) ∈ massBounded Y w := by
  obtain ⟨C, hC⟩ := hξ
  refine ⟨Ca ^ 2 * Cb ^ 2 * C, fun n ↦ ?_⟩
  show matMass (A n * ξ n * B n) ≤ Ca ^ 2 * Cb ^ 2 * C * w n
  have ha2 : ‖A n‖ ^ 2 ≤ Ca ^ 2 := by
    nlinarith [norm_nonneg (A n), hA n]
  have hb2 : ‖B n‖ ^ 2 ≤ Cb ^ 2 := by
    nlinarith [norm_nonneg (B n), hB n]
  have hprod : ‖A n‖ ^ 2 * ‖B n‖ ^ 2 ≤ Ca ^ 2 * Cb ^ 2 := by
    nlinarith [sq_nonneg ‖A n‖, sq_nonneg ‖B n‖, sq_nonneg Ca, sq_nonneg Cb]
  calc matMass (A n * ξ n * B n)
      ≤ ‖A n‖ ^ 2 * ‖B n‖ ^ 2 * matMass (ξ n) := matMass_mul_mul_le _ _ _
    _ ≤ Ca ^ 2 * Cb ^ 2 * matMass (ξ n) :=
        mul_le_mul_of_nonneg_right hprod (matMass_nonneg _)
    _ ≤ Ca ^ 2 * Cb ^ 2 * (C * w n) :=
        mul_le_mul_of_nonneg_left (hC n) (by positivity)
    _ = Ca ^ 2 * Cb ^ 2 * C * w n := by ring

/-- **CO.20, `ker Λ` is stable.**  Sandwiching a null family between uniformly
bounded families keeps it null, which is the printed *"`Λ(z) = 0` implies
`Λ(x z y) = 0` for all `x, y ∈ Q`"*. -/
theorem massNull_mul_mul (Y : ℕ → FiniteModel) (w : ℕ → ℝ)
    (ω : Ultrafilter ℕ) (A B ξ : MatFam Y) (Ca Cb : ℝ)
    (hA : ∀ n, ‖A n‖ ≤ Ca) (hB : ∀ n, ‖B n‖ ≤ Cb)
    (hξ : ξ ∈ massNull Y w ω) :
    (fun n ↦ A n * ξ n * B n) ∈ massNull Y w ω := by
  intro ε hε
  obtain ⟨c, hcpos, hclt⟩ := exists_pos_mul_lt hε (Ca ^ 2 * Cb ^ 2)
  filter_upwards [hξ c hcpos] with n hn
  show matMass (A n * ξ n * B n) ≤ ε * clipWeight w n
  have hclip : (0 : ℝ) ≤ clipWeight w n := clipWeight_nonneg w n
  have ha2 : ‖A n‖ ^ 2 ≤ Ca ^ 2 := by
    nlinarith [norm_nonneg (A n), hA n]
  have hb2 : ‖B n‖ ^ 2 ≤ Cb ^ 2 := by
    nlinarith [norm_nonneg (B n), hB n]
  have hprod : ‖A n‖ ^ 2 * ‖B n‖ ^ 2 ≤ Ca ^ 2 * Cb ^ 2 := by
    nlinarith [sq_nonneg ‖A n‖, sq_nonneg ‖B n‖, sq_nonneg Ca, sq_nonneg Cb]
  calc matMass (A n * ξ n * B n)
      ≤ ‖A n‖ ^ 2 * ‖B n‖ ^ 2 * matMass (ξ n) := matMass_mul_mul_le _ _ _
    _ ≤ Ca ^ 2 * Cb ^ 2 * matMass (ξ n) :=
        mul_le_mul_of_nonneg_right hprod (matMass_nonneg _)
    _ ≤ Ca ^ 2 * Cb ^ 2 * (c * clipWeight w n) :=
        mul_le_mul_of_nonneg_left hn (by positivity)
    _ = (Ca ^ 2 * Cb ^ 2 * c) * clipWeight w n := by ring
    _ ≤ ε * clipWeight w n := mul_le_mul_of_nonneg_right hclt.le hclip

/-! ## Inner invariance: the conjugation representation acts -/

/-- Conjugating a mass-bounded family by a unitary family keeps it mass
bounded, with the same constant: unitary conjugation is mass exact.  This is
the numerator half of *"`I_q` is a two-sided ideal invariant under inner
automorphisms"* and of *"conjugation by a unitary preserves each
`⟨·,·⟩_n`"*. -/
theorem massBounded_unitary_conj (Y : ℕ → FiniteModel) (w : ℕ → ℝ)
    (U : ∀ n, Matrix.unitaryGroup (Y n) ℂ) (ξ : MatFam Y)
    (hξ : ξ ∈ massBounded Y w) :
    (fun n ↦ (U n : Matrix (Y n) (Y n) ℂ) * ξ n *
      (U n : Matrix (Y n) (Y n) ℂ)ᴴ) ∈ massBounded Y w := by
  obtain ⟨C, hC⟩ := hξ
  refine ⟨C, fun n ↦ ?_⟩
  show matMass ((U n : Matrix (Y n) (Y n) ℂ) * ξ n *
    (U n : Matrix (Y n) (Y n) ℂ)ᴴ) ≤ C * w n
  rw [matMass_unitary_conj (U n).2 (ξ n)]
  exact hC n

/-- Conjugating a null family by a unitary family keeps it null: the
denominator half of the same statement.  Together with the previous lemma this
is what lets `π(h) = [Ad U_n(h)]_ω` act on `K_ω`. -/
theorem massNull_unitary_conj (Y : ℕ → FiniteModel) (w : ℕ → ℝ)
    (ω : Ultrafilter ℕ) (U : ∀ n, Matrix.unitaryGroup (Y n) ℂ)
    (ξ : MatFam Y) (hξ : ξ ∈ massNull Y w ω) :
    (fun n ↦ (U n : Matrix (Y n) (Y n) ℂ) * ξ n *
      (U n : Matrix (Y n) (Y n) ℂ)ᴴ) ∈ massNull Y w ω := by
  intro ε hε
  filter_upwards [hξ ε hε] with n hn
  show matMass ((U n : Matrix (Y n) (Y n) ℂ) * ξ n *
    (U n : Matrix (Y n) (Y n) ℂ)ᴴ) ≤ ε * clipWeight w n
  rw [matMass_unitary_conj (U n).2 (ξ n)]
  exact hn

end

end RankNormalizedHilbertization
end GroupApproximation
