import GroupApproximation.Analysis.UniversalCStarAmalgam

/-!
# Words in the factor images are dense in the universal amalgam

`UniversalCStarAmalgam iA iB` is, by definition, the topological closure of the
star subalgebra generated by the two factor images inside the bounded product
of all compatible representations.  So the elements of the amalgam that lie in
that star subalgebra --- the *words* in the generators --- form a dense set.

This is the density that `ShulmanFill.norming_of_dense_norming` consumes: to
show that the MF-carrier coordinates compute the amalgam norm, it suffices to
show it on words.
-/

namespace GroupApproximation
namespace ShulmanFill

universe u

variable {C A B : Type u} [CStarAlgebra C] [CStarAlgebra A] [CStarAlgebra B]
  (iA : C →⋆ₐ[ℂ] A) (iB : C →⋆ₐ[ℂ] B) [Nonempty (CStarAmalgamRepresentation iA iB)]

/-- The elements of the amalgam that are words in the two factor images. -/
def adjoinSet : Set (UniversalCStarAmalgam iA iB) :=
  {x | (x : UniversalCStarAmalgamAmbient iA iB) ∈
    StarAlgebra.adjoin ℂ
      (Set.range (universalCStarAmalgamLeftAmbient iA iB) ∪
        Set.range (universalCStarAmalgamRightAmbient iA iB))}

theorem mem_adjoinSet_iff (x : UniversalCStarAmalgam iA iB) :
    x ∈ adjoinSet iA iB ↔
      (x : UniversalCStarAmalgamAmbient iA iB) ∈
        StarAlgebra.adjoin ℂ
          (Set.range (universalCStarAmalgamLeftAmbient iA iB) ∪
            Set.range (universalCStarAmalgamRightAmbient iA iB)) :=
  Iff.rfl

/-- **The words are dense in the amalgam.**  The amalgam is the closure of the
generated star subalgebra, so every element is a limit of words. -/
theorem dense_adjoin_universalCStarAmalgam : Dense (adjoinSet iA iB) := by
  rw [Metric.dense_iff]
  intro x r hr
  have hx : (x : UniversalCStarAmalgamAmbient iA iB) ∈
      closure ((StarAlgebra.adjoin ℂ
        (Set.range (universalCStarAmalgamLeftAmbient iA iB) ∪
          Set.range (universalCStarAmalgamRightAmbient iA iB)) :
            StarSubalgebra ℂ (UniversalCStarAmalgamAmbient iA iB)) :
              Set (UniversalCStarAmalgamAmbient iA iB)) := by
    have hmem : (x : UniversalCStarAmalgamAmbient iA iB) ∈
        ((StarAlgebra.adjoin ℂ
          (Set.range (universalCStarAmalgamLeftAmbient iA iB) ∪
            Set.range (universalCStarAmalgamRightAmbient iA iB))).topologicalClosure :
              Set (UniversalCStarAmalgamAmbient iA iB)) := x.2
    rwa [StarSubalgebra.topologicalClosure_coe] at hmem
  obtain ⟨y, hy, hdist⟩ := Metric.mem_closure_iff.mp hx r hr
  refine ⟨⟨y, StarSubalgebra.le_topologicalClosure _ hy⟩, ?_, hy⟩
  rw [Metric.mem_ball, Subtype.dist_eq, dist_comm]
  exact hdist

/-- The same, as a statement about every element of the amalgam. -/
theorem exists_adjoin_near (x : UniversalCStarAmalgam iA iB) {ε : ℝ} (hε : 0 < ε) :
    ∃ y ∈ adjoinSet iA iB, dist x y < ε := by
  have hx : x ∈ closure (adjoinSet iA iB) := (dense_adjoin_universalCStarAmalgam iA iB) x
  exact Metric.mem_closure_iff.mp hx ε hε

end ShulmanFill
end GroupApproximation
