import GroupApproximation.GGT.ElementaryIndependence
import GroupApproximation.GGT.DGOQuasiGeodesicChainAt
import GroupApproximation.GGT.HullSCFillingAlphabetReduction
import GroupApproximation.GGT.HullSCRelatorSeparation2ConeOff
import GroupApproximation.GGT.HullHeGXPairOfFamily

/-!
# The non-elementarity half of Hull's filling alphabet

Hull's proof does not preserve non-elementarity merely from inclusion of the
old alphabet.  Before taking the quotient, Corollary 5.7 chooses cyclic
hyperbolically embedded subgroups generated by non-commensurable loxodromics
inside every prescribed suitable subgroup.  The small-cancellation quotient
theorem preserves that auxiliary hyperbolically embedded family.  Lemma 5.8
then reads the surviving cyclic subgroups back as suitability in the quotient.

`HypEmbeddedCore₂` packages a pair of directions, but does not say that its
peripheral subgroups are the cyclic groups those directions generate.
`AuxiliaryNonElementaryCores` adds exactly those equalities and this file
flattens the cores for `N` and the finite prescribed family into the one
peripheral family to which Hull's Lemma 4.4 is applied.  Its quotient output is recorded as
`QuotientPeripheralPreservation`: the mapped family stays hyperbolically
embedded and the quotient is injective on its union.

The quotient peripherals themselves are elliptic in the relative graph, so it
would be wrong to call their generators the quotient's loxodromic witnesses.
Instead, injectivity on the union proves that the first mapped cyclic subgroup
is still proper in the image of the suitable subgroup.  Hull's Lemma 5.8 then
enlarges the quotient alphabet and produces a new loxodromic direction of the
form `g * h^n`.  That final common-alphabet application is the exact remaining
geometric premise.

Alphabet inclusion remains completely separate in `QuotientHullAlphabet`.
-/

namespace GroupApproximation
namespace HullSC

open GroupApproximation.GGT
open GroupApproximation.HullGeometry
open GroupApproximation.Manuscript.NonMF.TorsionFree

universe u

/-- The auxiliary cyclic-pair cores chosen before quotienting, one for `N` and
one for every prescribed suitable subgroup. -/
structure AuxiliaryNonElementaryCores
    {G : Type u} [Group G] (A : HullGeneratingSet G) (N : Subgroup G)
    {k : ℕ} (S : Fin k → Subgroup G) where
  coreN : HypEmbeddedCore₂ A N
  coreS : ∀ j : Fin k, HypEmbeddedCore₂ A (S j)
  cyclicN : ∀ b : Bool,
    coreN.H b = Subgroup.zpowers (coreN.lox b)
  cyclicS : ∀ (j : Fin k) (b : Bool),
    (coreS j).H b = Subgroup.zpowers ((coreS j).lox b)

/-- A pair core inside a subgroup already proves that the subgroup acts
non-elementarily.  Trivial intersection rules out a common nonzero power, and
Osin's common-power criterion turns that algebraic separation into geometric
independence. -/
theorem actsNonElementarily_of_hypEmbeddedCore₂
    {G : Type u} [Group G] {A : HullGeneratingSet G} {N : Subgroup G}
    (E : HypEmbeddedCore₂ A N) :
    ActsNonElementarily N (Cayley.base A.alphabet) := by
  refine ⟨E.lox false, E.le false (E.lox_mem false),
    E.lox true, E.le true (E.lox_mem true),
    E.lox_isLoxodromic false, E.lox_isLoxodromic true, ?_⟩
  apply ElementaryMorse.independentOfNoCommonZpow_cayley A
    (E.lox false) (E.lox true) (E.lox_isLoxodromic false)
      (E.lox_isLoxodromic true)
  intro p r hp hr hpow
  have hp_mem : E.lox false ^ p ∈ E.H false :=
    Subgroup.zpow_mem (E.H false) (E.lox_mem false) p
  have hr_mem : E.lox false ^ p ∈ E.H true := by
    rw [hpow]
    exact Subgroup.zpow_mem (E.H true) (E.lox_mem true) r
  have hp_one : E.lox false ^ p = 1 :=
    E.disjoint (E.lox false ^ p) hp_mem hr_mem
  exact Elementary.zpow_ne_one_of_isLoxodromic
    (E.lox_isLoxodromic false) hp hp_one

/-- Indices for the two auxiliary peripherals of `N` and of each `S j`. -/
abbrev AuxiliaryPeripheralIndex (k : ℕ) := Option (Fin k) × Bool

/-- The source peripheral family obtained by flattening all auxiliary cores. -/
def AuxiliaryNonElementaryCores.peripheral
    {G : Type u} [Group G] {A : HullGeneratingSet G} {N : Subgroup G}
    {k : ℕ} {S : Fin k → Subgroup G} (D : AuxiliaryNonElementaryCores A N S) :
    AuxiliaryPeripheralIndex k → Subgroup G
  | (none, b) => D.coreN.H b
  | (some j, b) => (D.coreS j).H b

/-- A *simultaneously* hyperbolically embedded family of all the auxiliary
pairs.  Separate applications of Corollary 5.7 do not provide the `embedded`
field: hyperbolic embeddedness of each pair need not imply hyperbolic
embeddedness of their flattened union. -/
structure AuxiliaryPeripheralFamily
    {G : Type u} [Group G] (A : HullGeneratingSet G) (N : Subgroup G)
    {k : ℕ} (S : Fin k → Subgroup G) where
  cores : AuxiliaryNonElementaryCores A N S
  rel : GGT.RelGenSet G (AuxiliaryPeripheralIndex k)
  base_eq : rel.base = A.alphabet.carrier
  fam_eq : ∀ i : AuxiliaryPeripheralIndex k,
    rel.fam i = cores.peripheral i
  embedded : rel.IsHyperbolicallyEmbedded

/-- **The simultaneous source witness-selection premise.**

Corollary 5.7 supplies finite collections of cyclic peripherals inside one
suitable subgroup.  Using it independently for `N` and each `S j` is not the
same as obtaining one hyperbolically embedded union.  This is the exact
finite-family strengthening needed before Hull's Lemma 4.4 can be applied
once to a common quotient. -/
def SimultaneousAuxiliaryPeripheralSelection : Prop :=
  ∀ {G : Type u} [Group G] (A : HullGeneratingSet G) {N : Subgroup G}
    {k : ℕ} (S : Fin k → Subgroup G), Suitable A.alphabet N →
      (∀ j : Fin k, Suitable A.alphabet (S j)) →
        Nonempty (AuxiliaryPeripheralFamily A N S)

/-- The distinguished subgroup attached to a block of the simultaneous
auxiliary family. -/
def AuxiliaryTarget {G : Type u} [Group G] (N : Subgroup G) {k : ℕ}
    (S : Fin k → Subgroup G) : Option (Fin k) → Subgroup G
  | none => N
  | some j => S j

/-- Hull Corollary 5.7 (`suitsubc`) in its printed all-`m`, one-subgroup
form.  This is stronger than the repository's current `YiSuitablePair`, but it
still does not itself coordinate witnesses belonging to different suitable
subgroups. -/
def YiSuitableFiniteFamily : Prop :=
  ∀ {G : Type u} [Group G] (A : HullGeneratingSet G) {T : Subgroup G},
    Suitable A.alphabet T → ∀ m : ℕ,
      ∃ g : Fin m → G, (∀ i, g i ∈ T) ∧
        (∀ i, IsLoxodromic (g i) (Cayley.base A.alphabet)) ∧
        PairwiseNonCommensurable g ∧
        ∀ i, GGT.Elementary.elementaryClosure (g i) =
          Subgroup.zpowers (g i)

/-- Two elements have conjugate nonzero powers.  This is the orientation used
by `PairwiseNonCommensurable`. -/
def AreCommensurable {G : Type u} [Group G] (a b : G) : Prop :=
  ∃ (p q : ℤ) (t : G), p ≠ 0 ∧ q ≠ 0 ∧
    t * a ^ p * t⁻¹ = b ^ q

theorem areCommensurable_symm {G : Type u} [Group G] {a b : G}
    (h : AreCommensurable a b) : AreCommensurable b a := by
  obtain ⟨p, q, t, hp, hq, hab⟩ := h
  refine ⟨q, p, t⁻¹, hq, hp, ?_⟩
  rw [inv_inv, ← hab]
  group

theorem areCommensurable_trans {G : Type u} [Group G] {a b c : G}
    (hab : AreCommensurable a b) (hbc : AreCommensurable b c) :
    AreCommensurable a c := by
  obtain ⟨p, q, t, hp, hq, hab⟩ := hab
  obtain ⟨r, s, u, hr, hs, hbc⟩ := hbc
  refine ⟨p * r, s * q, u * t, mul_ne_zero hp hr, mul_ne_zero hs hq, ?_⟩
  calc
    (u * t) * a ^ (p * r) * (u * t)⁻¹ =
        u * (t * (a ^ p) ^ r * t⁻¹) * u⁻¹ := by
          rw [zpow_mul]
          group
    _ = u * (t * a ^ p * t⁻¹) ^ r * u⁻¹ := by
      rw [GGT.Elementary.conj_zpow_eq]
    _ = u * (b ^ q) ^ r * u⁻¹ := by rw [hab]
    _ = u * (b ^ r) ^ q * u⁻¹ := by
      rw [← zpow_mul, ← zpow_mul, mul_comm q r]
    _ = (u * b ^ r * u⁻¹) ^ q :=
      GGT.Elementary.conj_zpow_eq u (b ^ r) q
    _ = (c ^ s) ^ q := by rw [hbc]
    _ = c ^ (s * q) := by rw [← zpow_mul]

/-- Pairwise non-commensurability forbids the relation above at distinct
indices. -/
theorem not_areCommensurable_of_pairwise {G : Type u} [Group G]
    {ι : Type*} {a : ι → G} (h : PairwiseNonCommensurable a)
    {i j : ι} (hij : i ≠ j) : ¬ AreCommensurable (a i) (a j) := by
  rintro ⟨p, q, t, hp, hq, heq⟩
  exact h i j hij p q hp hq t heq

/-- A candidate is non-commensurable with every member of a finite forbidden
set, in both ordered directions. -/
def AvoidsFiniteCommensurability {G : Type u} [Group G]
    (F : Finset G) (a : G) : Prop :=
  ∀ x ∈ F, ¬ AreCommensurable a x ∧ ¬ AreCommensurable x a

/-- **The pure finite-avoidance lemma needed to iterate `suitsubc`.**

A pairwise non-commensurable family with `|F|+2` members has two members
outside all commensurability classes represented by `F`: one forbidden
element can meet at most one candidate, by transitivity of commensurability.
The repository currently has neither that transitivity/counting lemma nor this
selection theorem. -/
def FiniteCommensurabilityAvoidance : Prop :=
  ∀ {G : Type u} [Group G] (F : Finset G)
    (a : Fin (F.card + 2) → G), PairwiseNonCommensurable a →
      ∃ i j : Fin (F.card + 2), i ≠ j ∧
        AvoidsFiniteCommensurability F (a i) ∧
        AvoidsFiniteCommensurability F (a j)

/-- The finite-avoidance lemma is pure algebra and counting. -/
theorem finiteCommensurabilityAvoidance :
    FiniteCommensurabilityAvoidance.{u} := by
  classical
  intro G _ F a hpair
  let bad : Finset (Fin (F.card + 2)) :=
    Finset.univ.filter (fun i => ∃ x ∈ F, AreCommensurable x (a i))
  have hbad_spec : ∀ i, i ∈ bad → ∃ x ∈ F, AreCommensurable x (a i) := by
    intro i hi
    exact (Finset.mem_filter.mp hi).2
  let pick : {i // i ∈ bad} → {x // x ∈ F} := fun i =>
    ⟨Classical.choose (hbad_spec i i.property),
      (Classical.choose_spec (hbad_spec i i.property)).1⟩
  have hpick_comm : ∀ i : {i // i ∈ bad},
      AreCommensurable (pick i).1 (a i.1) := by
    intro i
    exact (Classical.choose_spec (hbad_spec i i.property)).2
  have hpick_inj : Function.Injective pick := by
    intro i j hpick
    apply Subtype.ext
    by_contra hij
    have hsame : (pick i).1 = (pick j).1 := congrArg Subtype.val hpick
    have hjcomm : AreCommensurable (pick i).1 (a j.1) := by
      rw [hsame]
      exact hpick_comm j
    have hijcomm : AreCommensurable (a i.1) (a j.1) :=
      areCommensurable_trans (areCommensurable_symm (hpick_comm i))
        hjcomm
    exact (not_areCommensurable_of_pairwise hpair hij) hijcomm
  have hbad_card : bad.card ≤ F.card := by
    have hcard := Fintype.card_le_of_injective pick hpick_inj
    simpa using hcard
  have hcompl : 1 < (badᶜ : Finset (Fin (F.card + 2))).card := by
    rw [Finset.card_compl, Fintype.card_fin]
    omega
  obtain ⟨i, j, hi, hj, hij⟩ := Finset.one_lt_card_iff.mp hcompl
  have hi_bad : i ∉ bad := Finset.mem_compl.mp hi
  have hj_bad : j ∉ bad := Finset.mem_compl.mp hj
  have hAvoid : ∀ z, z ∉ bad → AvoidsFiniteCommensurability F (a z) := by
    intro z hz x hx
    have hnot : ¬ AreCommensurable x (a z) := by
      intro hxa
      apply hz
      exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, ⟨x, hx, hxa⟩⟩
    exact ⟨fun hax => hnot (areCommensurable_symm hax), hnot⟩
  exact ⟨i, j, hij, hAvoid i hi_bad, hAvoid j hj_bad⟩

/-- The local induction step required for simultaneous Yi selection: choose a
cyclic pair in one suitable subgroup while avoiding a prescribed finite family
of earlier witnesses. -/
def YiSuitablePairAvoidingFinite : Prop :=
  ∀ {G : Type u} [Group G] (A : HullGeneratingSet G) {T : Subgroup G},
    Suitable A.alphabet T → ∀ F : Finset G,
      ∃ g : Bool → G, (∀ b, g b ∈ T) ∧
        (∀ b, IsLoxodromic (g b) (Cayley.base A.alphabet)) ∧
        PairwiseNonCommensurable g ∧
        (∀ b, GGT.Elementary.elementaryClosure (g b) =
          Subgroup.zpowers (g b)) ∧
        ∀ b, AvoidsFiniteCommensurability F (g b)

/-- Printed all-`m` `suitsubc`, plus the pure counting lemma, gives the exact
finite-avoidance induction step. -/
theorem yiSuitablePairAvoidingFinite_of_family_of_avoidance
    (hyi : YiSuitableFiniteFamily.{u})
    (havoid : FiniteCommensurabilityAvoidance.{u}) :
    YiSuitablePairAvoidingFinite.{u} := by
  intro G _ A T hT F
  obtain ⟨a, haT, halox, hanc, hac⟩ := hyi A hT (F.card + 2)
  obtain ⟨i, j, hij, hiF, hjF⟩ := havoid F a hanc
  let g : Bool → G := fun b => bif b then a j else a i
  have hgT : ∀ b, g b ∈ T := by
    intro b
    cases b
    · change a i ∈ T
      exact haT i
    · change a j ∈ T
      exact haT j
  have hglox : ∀ b, IsLoxodromic (g b) (Cayley.base A.alphabet) := by
    intro b
    cases b
    · change IsLoxodromic (a i) (Cayley.base A.alphabet)
      exact halox i
    · change IsLoxodromic (a j) (Cayley.base A.alphabet)
      exact halox j
  have hgnc : PairwiseNonCommensurable g := by
    intro b c hbc p q hp hq t
    cases b <;> cases c
    · exact (hbc rfl).elim
    · change t * a i ^ p * t⁻¹ ≠ a j ^ q
      exact hanc i j hij p q hp hq t
    · change t * a j ^ p * t⁻¹ ≠ a i ^ q
      exact hanc j i hij.symm p q hp hq t
    · exact (hbc rfl).elim
  refine ⟨g, hgT, hglox, hgnc, ?_, ?_⟩
  · intro b
    cases b
    · change GGT.Elementary.elementaryClosure (a i) = Subgroup.zpowers (a i)
      exact hac i
    · change GGT.Elementary.elementaryClosure (a j) = Subgroup.zpowers (a j)
      exact hac j
  · intro b
    cases b
    · change AvoidsFiniteCommensurability F (a i)
      exact hiF
    · change AvoidsFiniteCommensurability F (a j)
      exact hjF

/-- Iterating the finite-avoidance step over a `Fin`-indexed family of suitable
subgroups. -/
theorem exists_yiSuitablePairs_fin_of_avoiding
    (hstep : YiSuitablePairAvoidingFinite.{u})
    {G : Type u} [Group G] (A : HullGeneratingSet G) :
    ∀ (n : ℕ) (T : Fin n → Subgroup G),
      (∀ i, Suitable A.alphabet (T i)) →
      ∃ g : Fin n × Bool → G,
        (∀ i, g i ∈ T i.1) ∧
        (∀ i, IsLoxodromic (g i) (Cayley.base A.alphabet)) ∧
        PairwiseNonCommensurable g ∧
        ∀ i, GGT.Elementary.elementaryClosure (g i) =
          Subgroup.zpowers (g i) := by
  classical
  intro n
  induction n with
  | zero =>
      intro T hT
      refine ⟨fun i => Fin.elim0 i.1, ?_, ?_, ?_, ?_⟩
      · intro i
        exact Fin.elim0 i.1
      · intro i
        exact Fin.elim0 i.1
      · intro i
        exact Fin.elim0 i.1
      · intro i
        exact Fin.elim0 i.1
  | succ n ih =>
      intro T hT
      obtain ⟨old, holdT, holdLox, holdNc, holdCyc⟩ :=
        ih (fun i => T i.succ) (fun i => hT i.succ)
      let F : Finset G := Finset.univ.image old
      obtain ⟨new, hnewT, hnewLox, hnewNc, hnewCyc, hnewAvoid⟩ :=
        hstep A (hT 0) F
      let g : Fin (n + 1) × Bool → G := fun ib =>
        Fin.cases (new ib.2) (fun i => old (i, ib.2)) ib.1
      have hgT : ∀ i, g i ∈ T i.1 := by
        rintro ⟨i, b⟩
        refine Fin.cases ?_ (fun j => ?_) i
        · change new b ∈ T 0
          exact hnewT b
        · change old (j, b) ∈ T j.succ
          exact holdT (j, b)
      have hgLox : ∀ i, IsLoxodromic (g i) (Cayley.base A.alphabet) := by
        rintro ⟨i, b⟩
        refine Fin.cases ?_ (fun j => ?_) i
        · change IsLoxodromic (new b) (Cayley.base A.alphabet)
          exact hnewLox b
        · change IsLoxodromic (old (j, b)) (Cayley.base A.alphabet)
          exact holdLox (j, b)
      have hgCyc : ∀ i, GGT.Elementary.elementaryClosure (g i) =
          Subgroup.zpowers (g i) := by
        rintro ⟨i, b⟩
        refine Fin.cases ?_ (fun j => ?_) i
        · change GGT.Elementary.elementaryClosure (new b) =
            Subgroup.zpowers (new b)
          exact hnewCyc b
        · change GGT.Elementary.elementaryClosure (old (j, b)) =
            Subgroup.zpowers (old (j, b))
          exact holdCyc (j, b)
      have hgNc : PairwiseNonCommensurable g := by
        rintro ⟨i, b⟩ ⟨j, c⟩ hne p q hp hq t
        rcases Fin.eq_zero_or_eq_succ i with hi | ⟨i', hi⟩
        · subst i
          rcases Fin.eq_zero_or_eq_succ j with hj | ⟨j', hj⟩
          · subst j
            have hbc : b ≠ c := by
              intro hbc
              exact hne (Prod.ext rfl hbc)
            change t * new b ^ p * t⁻¹ ≠ new c ^ q
            exact hnewNc b c hbc p q hp hq t
          · subst j
            have hx : old (j', c) ∈ F := by
              exact Finset.mem_image.mpr ⟨(j', c), Finset.mem_univ _, rfl⟩
            have hav := (hnewAvoid b (old (j', c)) hx).1
            change t * new b ^ p * t⁻¹ ≠ old (j', c) ^ q
            intro heq
            exact hav ⟨p, q, t, hp, hq, heq⟩
        · subst i
          rcases Fin.eq_zero_or_eq_succ j with hj | ⟨j', hj⟩
          · subst j
            have hx : old (i', b) ∈ F := by
              exact Finset.mem_image.mpr ⟨(i', b), Finset.mem_univ _, rfl⟩
            have hav := (hnewAvoid c (old (i', b)) hx).2
            change t * old (i', b) ^ p * t⁻¹ ≠ new c ^ q
            intro heq
            exact hav ⟨p, q, t, hp, hq, heq⟩
          · subst j
            have hne' : (i', b) ≠ (j', c) := by
              intro heq
              exact hne (congrArg
                (fun z : Fin n × Bool => (z.1.succ, z.2)) heq)
            change t * old (i', b) ^ p * t⁻¹ ≠ old (j', c) ^ q
            exact holdNc (i', b) (j', c) hne' p q hp hq t
      exact ⟨g, hgT, hgLox, hgNc, hgCyc⟩

/-- **The exact simultaneous `suitsubc` witness still required.**

Hull's printed `suitsubc` produces arbitrarily large pairwise
non-commensurable cyclic elementary closures inside one suitable subgroup.
The filling theorem needs the corresponding choice across the finite list
`N, S₁, …, Sₖ`: two elements in each distinguished subgroup and pairwise
non-commensurability across the whole flattened family. -/
def SimultaneousYiSuitableFamily : Prop :=
  ∀ {G : Type u} [Group G] (A : HullGeneratingSet G) {N : Subgroup G}
    {k : ℕ} (S : Fin k → Subgroup G), Suitable A.alphabet N →
      (∀ j : Fin k, Suitable A.alphabet (S j)) →
        ∃ g : AuxiliaryPeripheralIndex k → G,
          (∀ i, g i ∈ AuxiliaryTarget N S i.1) ∧
          (∀ i, IsLoxodromic (g i) (Cayley.base A.alphabet)) ∧
          PairwiseNonCommensurable g ∧
          ∀ i, GGT.Elementary.elementaryClosure (g i) =
            Subgroup.zpowers (g i)

/-- Hull's all-`m` Corollary 5.7 can be iterated over a finite family of
suitable subgroups.  At each step we request two more witnesses than there are
previous witnesses; finite commensurability avoidance then makes the new pair
independent from the entire family already chosen. -/
theorem simultaneousYiSuitableFamily_of_finiteFamily
    (hyi : YiSuitableFiniteFamily.{u}) :
    SimultaneousYiSuitableFamily.{u} := by
  classical
  have hstep : YiSuitablePairAvoidingFinite.{u} :=
    yiSuitablePairAvoidingFinite_of_family_of_avoidance hyi
      finiteCommensurabilityAvoidance
  intro G _ A N k S hN hS
  let T : Fin (k + 1) → Subgroup G := Fin.cases N S
  have hT : ∀ i, Suitable A.alphabet (T i) := by
    intro i
    refine Fin.cases hN (fun j => hS j) i
  obtain ⟨a, haT, halox, hanc, hac⟩ :=
    exists_yiSuitablePairs_fin_of_avoiding hstep A (k + 1) T hT
  let idx : Option (Fin k) → Fin (k + 1)
    | none => 0
    | some j => j.succ
  let unidx : Fin (k + 1) → Option (Fin k) := Fin.cases none some
  have hunidx : Function.LeftInverse unidx idx := by
    intro i
    cases i <;> simp [idx, unidx]
  have hidx : Function.Injective idx := hunidx.injective
  let g : AuxiliaryPeripheralIndex k → G := fun ib => a (idx ib.1, ib.2)
  have hgT : ∀ i, g i ∈ AuxiliaryTarget N S i.1 := by
    rintro ⟨i, b⟩
    cases i with
    | none =>
        change a (0, b) ∈ N
        exact haT (0, b)
    | some j =>
        change a (j.succ, b) ∈ S j
        exact haT (j.succ, b)
  have hglox : ∀ i, IsLoxodromic (g i) (Cayley.base A.alphabet) := by
    rintro ⟨i, b⟩
    exact halox (idx i, b)
  have hgnc : PairwiseNonCommensurable g := by
    rintro ⟨i, b⟩ ⟨j, c⟩ hij
    have hij' : (idx i, b) ≠ (idx j, c) := by
      intro heq
      apply hij
      have hi : i = j := hidx (congrArg Prod.fst heq)
      have hb : b = c := congrArg Prod.snd heq
      cases hi
      cases hb
      rfl
    exact hanc (idx i, b) (idx j, c) hij'
  have hgcyc : ∀ i, GGT.Elementary.elementaryClosure (g i) =
      Subgroup.zpowers (g i) := by
    rintro ⟨i, b⟩
    exact hac (idx i, b)
  exact ⟨g, hgT, hglox, hgnc, hgcyc⟩

/-- A hyperbolically embedded family crosses an alphabet equality, for an
arbitrary index type. -/
theorem isHyperbolicallyEmbedded_coneOffFamily_of_alphabet_eq_general
    {G : Type u} [Group G] {ι : Type} {A₁ A₂ : Alphabet G}
    (h : A₁ = A₂) {K : ι → Subgroup G}
    (he : (coneOffFamily A₁ K).IsHyperbolicallyEmbedded) :
    (coneOffFamily A₂ K).IsHyperbolicallyEmbedded := by
  subst h
  exact he

/-- Hull's family `heGX` specialised to a Hull generating set.  The empty
cone-off supplies the relative generating set required by `HeGXFamily`; the
result is transported back across its alphabet equality. -/
theorem isHyperbolicallyEmbedded_elementaryClosure_family_of_heGXFamily
    (hhe : GGT.HeGXFamily.{u, 0}) {G : Type u} [Group G]
    (A : HullGeneratingSet G) (ι : Type) [Finite ι] (g : ι → G)
    (hlox : ∀ i, IsLoxodromic (g i) (Cayley.base A.alphabet))
    (hnc : PairwiseNonCommensurable g) :
    (coneOffFamily A.alphabet
      (fun i => GGT.Elementary.elementaryClosure (g i))).IsHyperbolicallyEmbedded := by
  have halph := alphabet_coneOffFamily_empty A.alphabet
  have hemb₀ : (coneOffFamily A.alphabet
      (Empty.elim : Empty → Subgroup G)).IsHyperbolicallyEmbedded :=
    { hyperbolic := GGT.hyperbolic_of_alphabet_eq halph ⟨A.delta, A.hyperbolic⟩
      locallyFinite := fun lam => lam.elim }
  have hacyl₀ : IsAcylindrical G (Cayley (coneOffFamily A.alphabet
      (Empty.elim : Empty → Subgroup G)).alphabet) :=
    isAcylindrical_of_alphabet_eq halph A.acylindrical
  have hlox₀ : ∀ i, IsLoxodromic (g i)
      (Cayley.base (coneOffFamily A.alphabet
        (Empty.elim : Empty → Subgroup G)).alphabet) :=
    fun i => isLoxodromic_of_alphabet_eq halph (hlox i)
  have hnc₀ : ∀ i j : ι, i ≠ j → ∀ (c : G) (p q : ℤ), p ≠ 0 → q ≠ 0 →
      c⁻¹ * g i ^ p * c ≠ g j ^ q := by
    intro i j hij c p q hp hq
    simpa only [inv_inv] using hnc i j hij p q hp hq c⁻¹
  have hout := hhe G Empty
    (coneOffFamily A.alphabet (Empty.elim : Empty → Subgroup G))
    hemb₀ hacyl₀ ι g hlox₀ hnc₀
  exact isHyperbolicallyEmbedded_coneOffFamily_of_alphabet_eq_general halph hout

/-- The simultaneous Yi witness and Hull/DGO `heGX` produce the exact jointly
embedded auxiliary source family needed by Lemma 4.4. -/
theorem simultaneousAuxiliaryPeripheralSelection_of_yi_of_heGX
    (hyi : SimultaneousYiSuitableFamily.{u})
    (hhe : GGT.HeGXFamily.{u, 0}) :
    SimultaneousAuxiliaryPeripheralSelection.{u} := by
  intro G _ A N k S hN hS
  obtain ⟨g, hg, hlox, hnc, hcyc⟩ := hyi A S hN hS
  let gN : Bool → G := fun b => g (none, b)
  let gS : Fin k → Bool → G := fun j b => g (some j, b)
  have hgN : ∀ b, gN b ∈ N := by
    intro b
    simpa [gN, AuxiliaryTarget] using hg (none, b)
  have hgS : ∀ j b, gS j b ∈ S j := by
    intro j b
    simpa [gS, AuxiliaryTarget] using hg (some j, b)
  have hloxN : ∀ b, IsLoxodromic (gN b) (Cayley.base A.alphabet) :=
    fun b => hlox (none, b)
  have hloxS : ∀ j b, IsLoxodromic (gS j b) (Cayley.base A.alphabet) :=
    fun j b => hlox (some j, b)
  have hncN : ∀ (c : G) (p q : ℤ), p ≠ 0 → q ≠ 0 →
      c⁻¹ * gN false ^ p * c ≠ gN true ^ q := by
    intro c p q hp hq
    have hne : ((none, false) : AuxiliaryPeripheralIndex k) ≠
        ((none, true) : AuxiliaryPeripheralIndex k) := by
      intro heq
      exact Bool.false_ne_true (congrArg Prod.snd heq)
    simpa only [gN, inv_inv] using
      hnc (none, false) (none, true) hne p q hp hq c⁻¹
  have hncS : ∀ j, ∀ (c : G) (p q : ℤ), p ≠ 0 → q ≠ 0 →
      c⁻¹ * gS j false ^ p * c ≠ gS j true ^ q := by
    intro j c p q hp hq
    have hne : ((some j, false) : AuxiliaryPeripheralIndex k) ≠
        ((some j, true) : AuxiliaryPeripheralIndex k) := by
      intro heq
      exact Bool.false_ne_true (congrArg Prod.snd heq)
    simpa only [gS, inv_inv] using
      hnc (some j, false) (some j, true) hne p q hp hq c⁻¹
  have hpair : HeGXPair.{u} := heGXPair_of_heGXFamily hhe
  have hembN : (coneOffFamily A.alphabet
      (fun b => Subgroup.zpowers (gN b))).IsHyperbolicallyEmbedded := by
    have he := hpair A gN hloxN hncN
    have heq : (fun b => GGT.Elementary.elementaryClosure (gN b)) =
        fun b => Subgroup.zpowers (gN b) := by
      funext b
      exact hcyc (none, b)
    rwa [heq] at he
  have hembS : ∀ j, (coneOffFamily A.alphabet
      (fun b => Subgroup.zpowers (gS j b))).IsHyperbolicallyEmbedded := by
    intro j
    have he := hpair A (gS j) (hloxS j) (hncS j)
    have heq : (fun b => GGT.Elementary.elementaryClosure (gS j b)) =
        fun b => Subgroup.zpowers (gS j b) := by
      funext b
      exact hcyc (some j, b)
    rwa [heq] at he
  let EN : HypEmbeddedCore₂ A N := HypEmbeddedCore₂.ofConeOff
    (fun b => Subgroup.zpowers (gN b))
    (fun b => Subgroup.zpowers_le.mpr (hgN b)) hembN gN
    (fun b => Subgroup.mem_zpowers (gN b)) hloxN
    (fun x hx₀ hx₁ => eq_one_of_mem_zpowers_of_notCommensurable hncN hx₀ hx₁)
  let ES : ∀ j, HypEmbeddedCore₂ A (S j) := fun j => HypEmbeddedCore₂.ofConeOff
    (fun b => Subgroup.zpowers (gS j b))
    (fun b => Subgroup.zpowers_le.mpr (hgS j b)) (hembS j) (gS j)
    (fun b => Subgroup.mem_zpowers (gS j b)) (hloxS j)
    (fun x hx₀ hx₁ => eq_one_of_mem_zpowers_of_notCommensurable (hncS j) hx₀ hx₁)
  let C : AuxiliaryNonElementaryCores A N S :=
    { coreN := EN
      coreS := ES
      cyclicN := by intro b; rfl
      cyclicS := by intro j b; rfl }
  have hembAll : (coneOffFamily A.alphabet
      (fun i => Subgroup.zpowers (g i))).IsHyperbolicallyEmbedded := by
    have he := isHyperbolicallyEmbedded_elementaryClosure_family_of_heGXFamily
      hhe A (AuxiliaryPeripheralIndex k) g hlox hnc
    have heq : (fun i => GGT.Elementary.elementaryClosure (g i)) =
        fun i => Subgroup.zpowers (g i) := funext hcyc
    rwa [heq] at he
  refine ⟨⟨C, coneOffFamily A.alphabet (fun i => Subgroup.zpowers (g i)),
    rfl, ?_, hembAll⟩⟩
  rintro ⟨i, b⟩
  cases i <;> rfl

/-- The printed all-`m` Yi selection, finite commensurability avoidance, and
the all-family `heGX` theorem discharge the simultaneous source-selection
interface used by the filling argument. -/
theorem simultaneousAuxiliaryPeripheralSelection_of_finiteYi_of_heGX
    (hyi : YiSuitableFiniteFamily.{u})
    (hhe : GGT.HeGXFamily.{u, 0}) :
    SimultaneousAuxiliaryPeripheralSelection.{u} :=
  simultaneousAuxiliaryPeripheralSelection_of_yi_of_heGX
    (simultaneousYiSuitableFamily_of_finiteFamily hyi) hhe

/-- Hull's published `ε`-piece relation with both compared subwords exposed.
The repository's older `IsPiece` existentially hides `u'`, so its
`pieces_small` field can only bound `u`, whereas Definition 4.3 bounds the
maximum of both lengths. -/
def RelWord.IsPublishedPiece {G : Type u} [Group G] {Λ : Type*}
    (D : GGT.RelGenSet G Λ) (W : Set (List (GGT.RelLetter G Λ)))
    (eps : ℕ) (u u' v : List (GGT.RelLetter G Λ)) : Prop :=
  v ∈ W ∧ (∃ s, v = u ++ s) ∧
    ∃ v' ∈ W, ∃ s', v' = u' ++ s' ∧
      ∃ y z : G, WordMetric.wordNorm D.base y ≤ eps ∧
        WordMetric.wordNorm D.base z ≤ eps ∧
        GGT.RelLetter.listVal u' = y * GGT.RelLetter.listVal u * z ∧
        GGT.RelLetter.listVal v' ≠
          y * GGT.RelLetter.listVal v * y⁻¹

/-- Hull's published `ε`-primepiece relation.  Here the two close subwords
occur in the same relator, and the second may match either orientation of the
first.  This is the extra relation controlled by `C₁`. -/
def RelWord.IsPrimePiece {G : Type u} [Group G] {Λ : Type*}
    (D : GGT.RelGenSet G Λ) (W : Set (List (GGT.RelLetter G Λ)))
    (eps : ℕ) (u u' v : List (GGT.RelLetter G Λ)) : Prop :=
  v ∈ W ∧
    ∃ middle tail, v = u ++ middle ++ u' ++ tail ∧
      ∃ y z : G, WordMetric.wordNorm D.base y ≤ eps ∧
        WordMetric.wordNorm D.base z ≤ eps ∧
        (GGT.RelLetter.listVal u' = y * GGT.RelLetter.listVal u * z ∨
          GGT.RelLetter.listVal u' = y * (GGT.RelLetter.listVal u)⁻¹ * z)

/-- **The extra hypotheses Hull's Lemma 4.4 actually consumes.**

`RelWord.IsSmallCancellation` records the piece, depth, length and symmetry
clauses, but Hull's published `C(ε,μ,λ,c,ρ)` condition also requires every
relator path to be `(λ,c)`-quasi-geodesic and the family to be strongly
bounded.  Theorem 7.1 uses `(λ,c) = (1/4,1)`, expressed here in the reciprocal
constant convention of `IsQuasiGeodesicChainAt`.

This is deliberately a strengthened input, not a replacement interpretation
of `RelWord.IsSmallCancellation`: the quotient-preservation theorem is not
soundly attributable to the weaker predicate alone. -/
structure RelWord.IsLemma44Input {G : Type u} [Group G] {Λ : Type*}
    (D : GGT.RelGenSet G Λ) (W : Set (List (GGT.RelLetter G Λ)))
    (eps : ℕ) (mu : ℝ) (rho : ℕ) : Prop extends
    RelWord.IsSmallCancellation D W eps mu rho where
  quasiGeodesic : ∀ v ∈ W,
    GGT.IsQuasiGeodesicChainAt D.alphabet.carrier 4 1
      (fun i => GGT.RelLetter.listVal (v.take i)) v.length
  publishedPiecesSmall : ∀ u u' v,
    RelWord.IsPublishedPiece D W eps u u' v →
      max (u.length : ℝ) (u'.length : ℝ) < mu * v.length
  stronglyBounded :
    {a : GGT.RelLetter G Λ |
      (∃ lam h, a = GGT.RelLetter.comp lam h) ∧ ∃ v ∈ W, a ∈ v}.Finite

/-- **Hull Lemma 4.9's actual `C₁` input.**  No-new-torsion uses the
primepiece clause in addition to every clause consumed by Lemma 4.4.  This
field is absent from `RelWord.IsSmallCancellation`, so finite-order lifting
cannot soundly be obtained from that weaker structure alone. -/
structure RelWord.IsLemma49Input {G : Type u} [Group G] {Λ : Type*}
    (D : GGT.RelGenSet G Λ) (W : Set (List (GGT.RelLetter G Λ)))
    (eps : ℕ) (mu : ℝ) (rho : ℕ) : Prop extends
    RelWord.IsLemma44Input D W eps mu rho where
  primePiecesSmall : ∀ u u' v, RelWord.IsPrimePiece D W eps u u' v →
    max (u.length : ℝ) (u'.length : ℝ) < mu * v.length

/-- **Hull Lemma 4.4's exact quotient output for the auxiliary family.**

The quotient relative generating set contains the image of the old alphabet,
its peripheral family is pointwise the image of the chosen source family, and
that family is hyperbolically embedded.  Injectivity on the whole peripheral
union is stated explicitly because it is what proves that a mapped cyclic
peripheral remains a proper subgroup of the mapped suitable subgroup.

This structure does not choose the final Hull alphabet: its peripherals are
letters in `rel.alphabet`, hence elliptic there. -/
structure QuotientPeripheralPreservation
    {G : Type u} [Group G] {A : HullGeneratingSet G} {N : Subgroup G}
    {k : ℕ} {S : Fin k → Subgroup G} {Q : Type u} [Group Q] (q : G →* Q)
    (D : AuxiliaryPeripheralFamily A N S) where
  rel : GGT.RelGenSet Q (AuxiliaryPeripheralIndex k)
  base_image : ∀ a ∈ A.alphabet.carrier, q a ∈ rel.base
  fam_map : ∀ i : AuxiliaryPeripheralIndex k,
    rel.fam i = (D.cores.peripheral i).map q
  embedded : rel.IsHyperbolicallyEmbedded
  injOn_peripheralUnion :
    Set.InjOn q
      (⋃ i : AuxiliaryPeripheralIndex k, (D.cores.peripheral i : Set G))

/-- **Hull Lemma 4.4, isolated as a named interface.**

The quantifier order records that the small-cancellation constants are chosen
from the jointly hyperbolically embedded source family before the symmetrized
relator family.  The result is exactly the preserved peripheral family and
union-injectivity above.  It deliberately says nothing about the final Hull
alphabet or suitability. -/
def HullLemma44PreservedPeripheralFamily : Prop :=
  ∀ {G : Type u} [Group G] {A : HullGeneratingSet G} {N : Subgroup G}
    {k : ℕ} {S : Fin k → Subgroup G} (D : AuxiliaryPeripheralFamily A N S),
      ∃ (eps rho : ℕ) (mu : ℝ), 0 < mu ∧
        ∀ (W : Set (List (GGT.RelLetter G (AuxiliaryPeripheralIndex k))))
          {Q : Type u} [Group Q] (q : G →* Q),
          RelWord.IsLemma44Input D.rel W eps mu rho →
          Function.Surjective q →
          q.ker = Subgroup.normalClosure (GGT.RelLetter.listVal '' W) →
            Nonempty (QuotientPeripheralPreservation q D)

/-- Injectivity on a disjoint auxiliary pair keeps the first mapped peripheral
proper in the image of the subgroup containing both.  This is the algebraic
input to Hull's Lemma 5.8. -/
theorem map_first_lt_of_injOn_pair
    {G : Type u} [Group G] {Q : Type u} [Group Q] (q : G →* Q)
    {A : HullGeneratingSet G} {T : Subgroup G} (E : HypEmbeddedCore₂ A T)
    (hinj : Set.InjOn q ((E.H false : Set G) ∪ (E.H true : Set G))) :
    (E.H false).map q < T.map q := by
  refine lt_of_le_of_ne (Subgroup.map_mono (E.le false)) ?_
  intro heq
  have hrightT : q (E.lox true) ∈ T.map q :=
    ⟨E.lox true, E.le true (E.lox_mem true), rfl⟩
  have hrightFirst : q (E.lox true) ∈ (E.H false).map q := by
    rw [heq]
    exact hrightT
  obtain ⟨x, hx, hqx⟩ := hrightFirst
  have hxdom : x ∈ (E.H false : Set G) ∪ (E.H true : Set G) :=
    Set.mem_union_left _ hx
  have hloxdom : E.lox true ∈ (E.H false : Set G) ∪ (E.H true : Set G) :=
    Set.mem_union_right _ (E.lox_mem true)
  have hxeq : x = E.lox true := hinj hxdom hloxdom hqx
  have hone : E.lox true = 1 :=
    E.disjoint (E.lox true) (hxeq ▸ hx) (E.lox_mem true)
  exact (Elementary.zpow_ne_one_of_isLoxodromic
    (E.lox_isLoxodromic true) (by norm_num : (1 : ℤ) ≠ 0)) (by simp [hone])

/-- Lemma 4.4's union-injectivity keeps the primary auxiliary peripheral for
`N` proper in `q(N)`. -/
theorem QuotientPeripheralPreservation.map_coreN_first_lt
    {G : Type u} [Group G] {A : HullGeneratingSet G} {N : Subgroup G}
    {k : ℕ} {S : Fin k → Subgroup G} {Q : Type u} [Group Q] {q : G →* Q}
    {D : AuxiliaryPeripheralFamily A N S}
    (P : QuotientPeripheralPreservation q D) :
    (D.cores.coreN.H false).map q < N.map q := by
  apply map_first_lt_of_injOn_pair q D.cores.coreN
  intro x hx y hy hxy
  apply P.injOn_peripheralUnion
  · rcases hx with hx | hx
    · exact Set.mem_iUnion.mpr ⟨(none, false), by simpa [AuxiliaryNonElementaryCores.peripheral]⟩
    · exact Set.mem_iUnion.mpr ⟨(none, true), by simpa [AuxiliaryNonElementaryCores.peripheral]⟩
  · rcases hy with hy | hy
    · exact Set.mem_iUnion.mpr ⟨(none, false), by simpa [AuxiliaryNonElementaryCores.peripheral]⟩
    · exact Set.mem_iUnion.mpr ⟨(none, true), by simpa [AuxiliaryNonElementaryCores.peripheral]⟩
  · exact hxy

/-- The same properness conclusion for every prescribed subgroup image. -/
theorem QuotientPeripheralPreservation.map_coreS_first_lt
    {G : Type u} [Group G] {A : HullGeneratingSet G} {N : Subgroup G}
    {k : ℕ} {S : Fin k → Subgroup G} {Q : Type u} [Group Q] {q : G →* Q}
    {D : AuxiliaryPeripheralFamily A N S}
    (P : QuotientPeripheralPreservation q D) (j : Fin k) :
    ((D.cores.coreS j).H false).map q < (S j).map q := by
  apply map_first_lt_of_injOn_pair q (D.cores.coreS j)
  intro x hx y hy hxy
  apply P.injOn_peripheralUnion
  · rcases hx with hx | hx
    · exact Set.mem_iUnion.mpr ⟨(some j, false), by simpa [AuxiliaryNonElementaryCores.peripheral]⟩
    · exact Set.mem_iUnion.mpr ⟨(some j, true), by simpa [AuxiliaryNonElementaryCores.peripheral]⟩
  · rcases hy with hy | hy
    · exact Set.mem_iUnion.mpr ⟨(some j, false), by simpa [AuxiliaryNonElementaryCores.peripheral]⟩
    · exact Set.mem_iUnion.mpr ⟨(some j, true), by simpa [AuxiliaryNonElementaryCores.peripheral]⟩
  · exact hxy

/-- **The remaining simultaneous Hull Lemma 5.8/common-alphabet premise.**

Given Lemma 4.4's preserved auxiliary peripherals, construct one quotient Hull
alphabet containing `q(A)` in which all distinguished images act
non-elementarily.  Hull proves the one-subgroup version by taking a proper
infinite cyclic peripheral `⟨h⟩ < q(T)` and producing a loxodromic `g h^n`;
the finite-family version must make those alphabet enlargements simultaneously.
This is not asserted to be the printed one-subgroup Lemma 5.8: it is the
finite simultaneous strengthening required by the repository's
`suitable_map_family` field.
-/
def HullLemma58SuitableFamily : Prop :=
  ∀ {G : Type u} [Group G] {A : HullGeneratingSet G} {N : Subgroup G}
    {k : ℕ} {S : Fin k → Subgroup G} {Q : Type u} [Group Q] (q : G →* Q)
    (D : AuxiliaryPeripheralFamily A N S),
    QuotientPeripheralPreservation q D →
      ∃ B : QuotientHullAlphabet A q,
        ActsNonElementarily (N.map q) (Cayley.base B.hullSet.alphabet) ∧
          ∀ j : Fin k,
            ActsNonElementarily ((S j).map q) (Cayley.base B.hullSet.alphabet)

/-- Lemma 5.8's common-alphabet conclusion, together with torsion-freeness,
reassembles the full filling alphabet. -/
theorem nonempty_fillingAlphabetData_of_peripheralPreservation
    (hcommon : HullLemma58SuitableFamily.{u})
    {G : Type u} [Group G] {A : HullGeneratingSet G} {N : Subgroup G}
    {k : ℕ} {S : Fin k → Subgroup G} {Q : Type u} [Group Q] {q : G →* Q}
    (hQ : IsPowerTorsionFree Q) (D : AuxiliaryPeripheralFamily A N S)
    (P : QuotientPeripheralPreservation q D) :
    Nonempty (FillingAlphabetData A N S q) := by
  obtain ⟨B, hN, hS⟩ := hcommon q D P
  exact ⟨FillingAlphabetData.ofQuotientHullAlphabet B
    (suitableImagesInQuotient_of_torsionFree B hQ hN hS)⟩

/-- **The non-elementarity-preservation lane, with every literature premise
visible.**

The simultaneous source selection is used once, Lemma 4.4 preserves that
whole peripheral family in the quotient, and the simultaneous Lemma 5.8
interface constructs one common quotient alphabet.  No loxodromic peripheral
generator is transported directly: those generators are elliptic in the
relative graph used by Lemma 4.4. -/
theorem exists_fillingAlphabetData_parameters_of_hull44_hull58
    (hselect : SimultaneousAuxiliaryPeripheralSelection.{u})
    (h44 : HullLemma44PreservedPeripheralFamily.{u})
    (h58 : HullLemma58SuitableFamily.{u})
    {G : Type u} [Group G] (A : HullGeneratingSet G) {N : Subgroup G}
    {k : ℕ} (S : Fin k → Subgroup G) (hN : Suitable A.alphabet N)
    (hS : ∀ j : Fin k, Suitable A.alphabet (S j)) :
    ∃ D : AuxiliaryPeripheralFamily A N S,
      ∃ (eps rho : ℕ) (mu : ℝ), 0 < mu ∧
        ∀ (W : Set (List (GGT.RelLetter G (AuxiliaryPeripheralIndex k))))
          {Q : Type u} [Group Q] (q : G →* Q),
          RelWord.IsLemma44Input D.rel W eps mu rho →
          Function.Surjective q →
          q.ker = Subgroup.normalClosure (GGT.RelLetter.listVal '' W) →
          IsPowerTorsionFree Q → Nonempty (FillingAlphabetData A N S q) := by
  obtain ⟨D⟩ := hselect A S hN hS
  obtain ⟨eps, rho, mu, hmu, hpreserve⟩ := h44 D
  refine ⟨D, eps, rho, mu, hmu, ?_⟩
  intro W Q _ q hsc hsurj hker hQ
  obtain ⟨P⟩ := hpreserve W q hsc hsurj hker
  exact nonempty_fillingAlphabetData_of_peripheralPreservation h58 hQ D P

end HullSC
end GroupApproximation
