import GroupApproximation.GGT.HullSCTheorem51

/-!
# Hull's condition `C(ε, μ, ρ)`, and the split of his Theorem 5.1

M. Hull, *Small cancellation in acylindrically hyperbolic groups*, Groups
Geom. Dyn. 10 (2016) 1077-1119, §4 and §5, after Olshanskii and after
D. Osin, *Small cancellations over relatively hyperbolic groups and embedding
theorems*, Ann. of Math. 172 (2010), §4.

`GGT/HullSCTheorem51.lean` reduces the whole lane to `HullTheorem51Statement`,
which bundles two different things: that a relator can be *chosen* (Hull's §6)
and that a relator's quotient is *good* (Hull's Theorem 5.1 proper).  This
module separates them, and the separation is formal rather than rhetorical
because the small cancellation condition is a definition with a body here, not
an opaque predicate:

* `HullQuotientStatement` -- **Theorem 5.1.**  For every radius and every
  prescribed family of suitable subgroups there are parameters `ε, μ, ρ` such
  that *any* `C(ε, μ, ρ)` family gives a quotient with the filling clauses.
* `HullRelatorStatement` -- **§6.**  For *any* parameters there is `u ∈ N`
  whose relator `t⁻¹u` lies in a `C(ε, μ, ρ)` family.
* `hullTheorem51_of_relator_of_quotient` -- **proved**: the parameters come out
  of the first and go into the second, and the composite is
  `HullTheorem51Statement`.

The quantifier order is what makes the composition work and is also the
mathematically honest one: the parameters depend on the group, the alphabet,
the hyperbolically embedded subgroup and the prescribed data, and the relator
is chosen afterwards, by taking the exponents in
`u = h₁^{n₁} h₂^{n₂} ⋯` large enough.

## The condition

A relator is a word in `X ⊔ H`, so a `List (GGT.RelLetter G Unit)`: each letter
is either a letter of the base or a letter of the hyperbolically embedded
subgroup.  Against that:

* `RelWord.IsPiece D W ε u w` -- `u` is an **`ε`-piece** of `w`: `w` begins with
  `u`, some *other* member of the family begins with a `u'`, and `u'` and `u`
  differ by `X`-words of length at most `ε` on either side.  This is Olshanskii's
  and Osin's notion, transcribed.
* `RelWord.IsSmallCancellation D W ε μ ρ` -- the family is symmetrized, every
  member is admissible and has at least `ρ` letters, every `H`-letter of every
  member is **deep**: outside the relative ball of radius `ρ` about `1` -- and
  every `ε`-piece is **short**: fewer than `μ` times the length of its word.

`GGT.RelGenSet.relBall` is what makes the depth clause statable: it is the ball
of Osin's relative metric `d̂`, and "the `H`-letters are long" means exactly
that they escape it.  Taking the exponents in `u` large is what puts `h₁^{nᵢ}`
outside `relBall ρ`, so the depth clause is the one §6 arranges directly.

## What is deliberately not claimed

Hull's condition is stated for *isolated* components and involves the
symmetrized closure of a finite family; the transcription here takes the family
as given, requires it to be closed under cyclic permutation and formal
inversion as fields, and states the piece condition for prefixes.  For a family
generated by a single relator -- the only case Theorem 7.1 uses -- these agree,
because every cyclic subword of a cyclic permutation is a prefix of a cyclic
permutation.  The general case of Hull's §4, with several relators and the
isolated-component bookkeeping, is not transcribed, and nothing here claims it
is: the two statements below are quantified over families satisfying the
condition as defined *in this file*, so the citation and its consumer cannot
drift apart.
-/

namespace GroupApproximation
namespace HullSC

open GroupApproximation.HullGeometry
open GroupApproximation.WordMetric
open GroupApproximation.Manuscript.NonMF.TorsionFree

universe u w

/-! ## Words over a relative generating set -/

namespace RelWord

variable {G : Type u} [Group G] {Λ : Type w}

/-- The formal inverse of a relative letter. -/
def inv : GGT.RelLetter G Λ → GGT.RelLetter G Λ
  | GGT.RelLetter.base g => GGT.RelLetter.base g⁻¹
  | GGT.RelLetter.comp lam h => GGT.RelLetter.comp lam h⁻¹

theorem val_inv (a : GGT.RelLetter G Λ) :
    (inv a).val = (a.val)⁻¹ := by
  cases a <;> rfl

/-- The formal inverse of a word: reverse it and invert every letter. -/
def revInv (v : List (GGT.RelLetter G Λ)) : List (GGT.RelLetter G Λ) :=
  (v.map inv).reverse

/-- Every letter of the word is a legal letter of `D`. -/
def IsAdmissible (D : GGT.RelGenSet G Λ) (v : List (GGT.RelLetter G Λ)) : Prop :=
  ∀ a ∈ v, D.IsLetter a

/-- **An `ε`-piece.**  `u` is an `ε`-piece of `v` when `v` begins with `u`, some
other member `v'` of the family begins with a `u'`, and `u'` and `u` name group
elements differing by base words of length at most `ε` on either side. -/
def IsPiece (D : GGT.RelGenSet G Λ) (W : Set (List (GGT.RelLetter G Λ)))
    (eps : ℕ) (u v : List (GGT.RelLetter G Λ)) : Prop :=
  v ∈ W ∧ (∃ s, v = u ++ s) ∧
    ∃ v' ∈ W, v' ≠ v ∧ ∃ u' s', v' = u' ++ s' ∧
      ∃ y z : G, wordNorm D.base y ≤ eps ∧ wordNorm D.base z ≤ eps ∧
        GGT.RelLetter.listVal u' = y * GGT.RelLetter.listVal u * z

/-- **Hull's condition `C(ε, μ, ρ)`** for a symmetrized family `W` of words over
the relative generating set `D`. -/
structure IsSmallCancellation (D : GGT.RelGenSet G Λ)
    (W : Set (List (GGT.RelLetter G Λ))) (eps : ℕ) (mu : ℝ) (rho : ℕ) : Prop where
  /-- Every word is spelled in legal letters. -/
  admissible : ∀ v ∈ W, IsAdmissible D v
  /-- The family is closed under formal inversion. -/
  inv_mem : ∀ v ∈ W, revInv v ∈ W
  /-- The family is closed under cyclic permutation. -/
  rotate_mem : ∀ v ∈ W, ∀ n : ℕ, v.rotate n ∈ W
  /-- Every word has at least `ρ` letters. -/
  long : ∀ v ∈ W, rho ≤ v.length
  /-- Every letter of the hyperbolically embedded family is deep: it escapes the
  relative ball of radius `ρ` about `1`.

  The relative metric is per-index -- `D.relBall lam n` counts only paths
  avoiding edges of `Γ_{H lam}`, and says nothing about the other components --
  so the index has to be pinned to the letter's own.  The guard
  `a.IsCompOf lam` does that: `GGT.RelLetter.IsCompOf lam (comp mu h)` is
  `mu = lam`, so for a component letter the clause fires at exactly one `lam`,
  its own; and `IsCompOf lam (base _)` is `False`, so base letters carry no
  depth condition, which is right -- only the `H`-letters have to be long. -/
  deep : ∀ v ∈ W, ∀ (a : GGT.RelLetter G Λ), a ∈ v → ∀ lam : Λ,
    a.IsCompOf lam → a.val ∉ D.relBall lam rho
  /-- Every `ε`-piece is shorter than `μ` times its word. -/
  pieces_small : ∀ u v : List (GGT.RelLetter G Λ), IsPiece D W eps u v →
    (u.length : ℝ) < mu * v.length

end RelWord

/-! ## The two halves of Hull's Theorem 5.1 -/

/-- **Hull, Theorem 5.1 proper: the quotient by a small cancellation family.**

> Let `G` be acylindrically hyperbolic with Hull's alphabet `A`, let `N` be
> suitable, let `H ≤ N` be hyperbolically embedded with a loxodromic element,
> let `S₁, …, S_k` be suitable and let `R` be a radius.  Then there are
> `ε, μ, ρ` such that for every family `W` satisfying `C(ε, μ, ρ)` over `H` and
> every `w ∈ W`, the quotient of `G` by the normal closure of the element `w`
> spells is acylindrically hyperbolic over an alphabet containing the image of
> `A`, injective on the `R`-ball of `Γ(G,A)`, keeps `N` and every `Sⱼ`
> suitable, and lifts finite order.

The parameters are produced *before* the family, which is the direction Hull's
proof runs: `ε, μ, ρ` are read off from the hyperbolicity constant of the
coned-off graph, from the acylindricity data, and from the radius, and the
relator is chosen afterwards to satisfy the resulting condition. -/
def HullQuotientStatement : Prop :=
  ∀ {G : Type u} [Group G] (A : HullGeneratingSet G) (N : Subgroup G)
    (E : HypEmbeddedCore A N), Suitable A.alphabet N →
      ∀ {k : ℕ} (S : Fin k → Subgroup G),
        (∀ j : Fin k, Suitable A.alphabet (S j)) → ∀ R : ℕ,
          ∃ (eps rho : ℕ) (mu : ℝ), 0 < mu ∧
            ∀ (W : Set (List (GGT.RelLetter G Unit)))
              (v : List (GGT.RelLetter G Unit)), v ∈ W →
              RelWord.IsSmallCancellation E.rel W eps mu rho →
                Nonempty (HullFillingQuotient A N S
                  (GGT.RelLetter.listVal v) R)

/-- **Hull, §6: the relator can be chosen.**

> For every `ε, μ, ρ` there is `u ∈ N` and a `C(ε, μ, ρ)` family over `H`
> containing a word spelling `t⁻¹u`.

This is where suitability of `N` and the hyperbolic embedding of `H` are spent:
`N` contains two independent loxodromic elements `h₁, h₂` (that is clause (2) of
Hull's Definition 1.4, and over a torsion-free ambient group
`Manuscript.NonMF.HullInputsProved.exists_pair_suitable_of_torsionFree` proves
it), `H` contains `h₁`, and taking the exponents in
`u = h₁^{n₁} h₂^{n₂} ⋯ ∈ N` large puts every `H`-letter of `t⁻¹u` outside
`relBall ρ` and makes every `ε`-piece short.  The one syllable of the relator
that is not chosen is the one spelling `t⁻¹`, and it is of bounded length, which
is why `μ` can be met. -/
def HullRelatorStatement : Prop :=
  ∀ {G : Type u} [Group G] (A : HullGeneratingSet G) (N : Subgroup G)
    (E : HypEmbeddedCore A N), Suitable A.alphabet N → ∀ (t : G)
      (eps rho : ℕ) (mu : ℝ), 0 < mu →
        ∃ u ∈ N, ∃ W : Set (List (GGT.RelLetter G Unit)),
          (∃ v ∈ W, GGT.RelLetter.listVal v = t⁻¹ * u) ∧
            RelWord.IsSmallCancellation E.rel W eps mu rho

/-- **Hull's Theorem 5.1 with the §6 relator, from its two halves.**

The parameters produced by the quotient theorem are fed to the relator theorem,
and the family it returns is fed back.  Nothing is lost in the seam because
both statements are quantified over `RelWord.IsSmallCancellation` as defined in
this file: the citation and its consumer cannot drift apart, which is the whole
point of giving the condition a body. -/
theorem hullTheorem51_of_relator_of_quotient
    (hrel : HullRelatorStatement.{u}) (hquot : HullQuotientStatement.{u}) :
    HullTheorem51Statement.{u} := by
  intro G _ A N E hN k S hS t R
  obtain ⟨eps, rho, mu, hmu, hgood⟩ := hquot A N E hN S hS R
  obtain ⟨u, huN, W, ⟨v, hvW, hvval⟩, hsc⟩ := hrel A N E hN t eps rho mu hmu
  refine ⟨u, huN, ?_⟩
  have hq := hgood W v hvW hsc
  rwa [hvval] at hq

/-- **Hull's Theorem 7.1 for one relator, from the two halves of Theorem 5.1.**
Composing with `HullSC.hullOneStep_of_theorem51`. -/
theorem hullOneStep_of_relator_of_quotient
    (hEmb : ExistsHypEmbeddedInSuitable.{u}) (hrel : HullRelatorStatement.{u})
    (hquot : HullQuotientStatement.{u}) : HullOneStepStatement.{u} :=
  hullOneStep_of_theorem51 hEmb
    (hullTheorem51_of_relator_of_quotient hrel hquot)

end HullSC
end GroupApproximation
