import GroupApproximation.GGT.HullSCRelatorSeparation2ConeOff
import GroupApproximation.GGT.HullSCRelatorSeparation2Quotient

/-!
# Hull's Theorem 7.1 for one relator, over a pair of subgroups

`HullSC.hullOneStep_of_theorem51` derives `HullSC.HullOneStepStatement` from
Hull's Theorem 5.1 over one hyperbolically embedded subgroup.  That form of
Theorem 5.1 cannot be used: over one subgroup Hull's relator
`p·h^{m₁}⋯h^{m_k}` is a single run of `H`-letters, so it spells a word whose
letters all lie in one component of `Γ(G, X ⊔ H)`, and
`HullSC.not_quasiGeodesic_relatorWord` shows it is then not quasi-geodesic,
which is what §5 needs of it.  The faithful form is over a pair, with the
relator alternating between the two components.

This module is that derivation over a pair.  **It is the seam the whole Bool
chain was missing**: `HullSC.HullTheorem51Statement₂` had no consumer, so
nothing above it could reach `HullOneStepStatement`, and the tower
(`HullSC.hullTower_of_oneStep`), the ball form
(`HullSC.hullBallFormNG_of_oneStep`) and Hull's Corollary 7.4
(`HullSCFreeProductFactor.hullCommonQuotient_of_oneStep_of_geometry`) all hang
off that one statement.  With this, the Bool chain reaches every one of them.

Nothing in `HullOneStepStatement` mentions the index type -- it quantifies over
a suitable `N` and produces a quotient -- so the conclusion is the same
statement the one-subgroup route produced, and the two clauses that mention the
target `t` are proved here exactly as they are there:

* `q(t) ∈ q(N)` -- the relator `t⁻¹u` dies in the quotient, so `q(t) = q(u)`,
  and `u` was chosen in `N`;
* `ker q` is normally generated by one element -- it is the normal closure of
  `t⁻¹u`, which is the manuscript's remark on Hull's construction at `m = 1`.

The pair of subgroups comes from `HullSC.ExistsHypEmbeddedConeOff₂`, through
`HullSC.nonempty_hypEmbeddedCore₂_of_coneOff`; over one subgroup the
corresponding step was `HullSC.ExistsHypEmbeddedInSuitable`.
-/

namespace GroupApproximation
namespace HullSC

open GroupApproximation.HullGeometry
open GroupApproximation.Manuscript.NonMF.TorsionFree

universe u

/-- **Hull's Theorem 7.1 at `m = 1`, from his Theorem 5.1 over a pair.**

The one-subgroup version is `HullSC.hullOneStep_of_theorem51`, and this differs
from it only in where the hyperbolically embedded data comes from: a pair of
subgroups with loxodromic elements and Hull's (W4) disjointness, rather than a
single subgroup.  The proof after that is identical, because
`HullFillingQuotient` does not mention the index type. -/
theorem hullOneStep_of_theorem51₂ (hEmb : ExistsHypEmbeddedConeOff₂.{u})
    (h51 : HullTheorem51Statement₂.{u}) : HullOneStepStatement.{u} := by
  intro G _ A N hN k S hS t R
  obtain ⟨E⟩ := nonempty_hypEmbeddedCore₂_of_coneOff hEmb A hN
  obtain ⟨u, huN, ⟨D⟩⟩ := h51 A N E hN S hS t R
  have hrel : D.q (t⁻¹ * u) = 1 := by
    rw [← MonoidHom.mem_ker, D.ker_eq]
    exact Subgroup.subset_normalClosure rfl
  have hqt : D.q t = D.q u := by
    rw [map_mul, map_inv] at hrel
    exact inv_mul_eq_one.mp hrel
  refine ⟨{ step := D.toHullStep
            mem_map := ?_
            kerNormallyGenerated := ⟨{t⁻¹ * u}, by simp, ?_⟩ }⟩
  · intro _
    show D.q t ∈ N.map D.q
    rw [hqt]
    exact Subgroup.mem_map_of_mem _ huN
  · show D.q.ker = Subgroup.normalClosure ((({t⁻¹ * u} : Finset G)) : Set G)
    rw [D.ker_eq, Finset.coe_singleton]

/-- **Hull's Theorem 7.1 at `m = 1`, on the three leaves of the Bool chain**:
his §5 in the two halves `ExistsHypEmbeddedConeOff₂` and
`HullConeOffStatement₂`, his §6 relator, and Dahmani-Guirardel-Osin's Theorem
5.3 in its repaired form. -/
theorem hullOneStep₂_of_coneOff (hEmb : ExistsHypEmbeddedConeOff₂.{u})
    (hcone : HullConeOffStatement₂.{u}) (hrel : HullRelatorStatement₂.{u})
    (hDGO : DGOQuotientStatementGeodesic.{u, u}) : HullOneStepStatement.{u} :=
  hullOneStep_of_theorem51₂ hEmb
    (hullTheorem51₂_of_relator_of_quotient hrel
      (hullQuotientStatement₂_of_coneOff hcone hDGO))

end HullSC
end GroupApproximation
