import GroupApproximation.GGT.RelHypDefinition

/-!
# A quotient of `U ∗ H` in which the source generators land in the partner's
image is filled by the partner

Fournier-Facio's Proposition 2.3 -- [FF25] = *Stability, approximable quotients,
and higher property (T)*, arXiv:2512.09180, and the statement that
`non_mf_groups_exist.tex`'s quotient sentence cites through [FFF] -- concludes
with `π(g_i) ∈ π(Λ)`, one `g_i` per generator of the peripheral factor.  What
the manuscript uses is the *surjection* `H ↠ P`.  This module is the step
between the two, and it is the only step: nothing here is geometric, and no
small-cancellation input is spent.

## The argument

`U ∗ H` is generated by its two factors, so a quotient of it is generated by
their images.  The partner's image is a subgroup, so it contains the image of
the source as soon as it contains the image of a *generating set* of the source
-- which is the hypothesis.  Hence it is everything.

`Sofic/OsinWeightedMetric.WeightedRouterDesign.partnerHom_surjective` runs this
argument for a router design, where the generating-set hypothesis is the
design's `tie` field.  The form below is the same argument with the design taken
out, so that it can be spent against a transcription of Proposition 2.3 as well.

## Why a generating set rather than finite presentation

The hypothesis is `Subgroup.closure g = ⊤` for a set `g`, not `[Group.
IsFinitelyPresented U]`.  Finiteness of `g` is what the *cited* proposition
needs -- it adds one relator per generator, and a finitely presented quotient
needs finitely many -- but it is not what this step needs, and stating it here
would make the lemma weaker for no gain.
-/

namespace GroupApproximation
namespace GGT
namespace RelHyp

open Monoid

/-! ## 1.  The two factor inclusions -/

/-- The inclusion of the peripheral factor `U` into `U ∗ H`. -/
def freeProductSourceHom (U H : Type) [Group U] [Group H] :
    U →* CoprodI (pairFamily U H) :=
  (CoprodI.of : pairFamily U H false →* CoprodI (pairFamily U H))

/-- The inclusion of the partner factor `H` into `U ∗ H`. -/
def freeProductPartnerHom (U H : Type) [Group U] [Group H] :
    H →* CoprodI (pairFamily U H) :=
  (CoprodI.of : pairFamily U H true →* CoprodI (pairFamily U H))

/- The index of `CoprodI.of` has to be pinned on the *function*, as in the two
definitions above, and not by ascribing the argument: a type ascription
elaborates its term at the ascribed type but reports the term's own inferred
type, so `(x : pairFamily U H false)` hands the elaborator an `x : U` and leaves
the index an unassigned metavariable. -/

theorem freeProductSourceHom_apply (U H : Type) [Group U] [Group H] (x : U) :
    freeProductSourceHom U H x
      = (CoprodI.of : pairFamily U H false →* CoprodI (pairFamily U H)) x :=
  rfl

theorem freeProductPartnerHom_apply (U H : Type) [Group U] [Group H] (y : H) :
    freeProductPartnerHom U H y
      = (CoprodI.of : pairFamily U H true →* CoprodI (pairFamily U H)) y :=
  rfl

/-! ## 2.  The source's image lies in the partner's -/

variable {U H Q : Type} [Group U] [Group H] [Group Q]

/-- **The whole source factor lands in the partner's image**, once a generating
set of the source does.  Lying in a subgroup is a closure condition, so the
hypothesis on generators propagates for free. -/
theorem mem_range_partner_of_sourceGen
    (pi : CoprodI (pairFamily U H) →* Q) {g : Set U}
    (hgen : Subgroup.closure g = ⊤)
    (hmem : ∀ x ∈ g,
      pi (freeProductSourceHom U H x)
        ∈ (pi.comp (freeProductPartnerHom U H)).range) (x : U) :
    pi (freeProductSourceHom U H x)
      ∈ (pi.comp (freeProductPartnerHom U H)).range := by
  have hsub : (⊤ : Subgroup U) ≤
      ((pi.comp (freeProductPartnerHom U H)).range).comap
        (pi.comp (freeProductSourceHom U H)) := by
    rw [← hgen, Subgroup.closure_le]
    intro y hy
    exact hmem y hy
  exact hsub (Subgroup.mem_top x)

/-! ## 3.  The partner fills the quotient -/

/-- **The partner factor surjects onto the quotient.**

`U ∗ H` is generated by its two factors and `pi` is onto, so the quotient is
generated by the two images; the partner's image is a subgroup containing the
source's, by `mem_range_partner_of_sourceGen`, so it is the whole quotient.

This is the clause `∃ p : H →* P, Function.Surjective p` of
`Manuscript.NonMF.TheoremC.FournierFacioQuotientStatement`, from the clause
`π(g_i) ∈ π(Λ)` that the cited proposition actually states. -/
theorem surjective_partner_of_sourceGen
    (pi : CoprodI (pairFamily U H) →* Q) (hpi : Function.Surjective pi)
    {g : Set U} (hgen : Subgroup.closure g = ⊤)
    (hmem : ∀ x ∈ g,
      pi (freeProductSourceHom U H x)
        ∈ (pi.comp (freeProductPartnerHom U H)).range) :
    Function.Surjective (pi.comp (freeProductPartnerHom U H)) := by
  rw [← MonoidHom.range_eq_top, eq_top_iff]
  rintro q -
  obtain ⟨w, rfl⟩ := hpi q
  induction w using Monoid.CoprodI.induction_on with
  | one =>
      rw [map_one]
      exact one_mem _
  | of b x =>
      cases b with
      | false => exact mem_range_partner_of_sourceGen pi hgen hmem x
      | true => exact ⟨x, rfl⟩
  | mul u v hu hv =>
      rw [map_mul]
      exact mul_mem hu hv

end RelHyp
end GGT
end GroupApproximation
