import Mathlib.Combinatorics.SimpleGraph.Metric
import Mathlib.Combinatorics.SimpleGraph.Clique
import Mathlib.Combinatorics.SimpleGraph.Maps
import Mathlib.Algebra.Order.Group.End
import Mathlib.Data.List.Chain
import Mathlib.Logic.Relation

/-!
# Flag complexes of simple graphs: simple connectivity and 6-large links

Vocabulary for Carbone--Cordero--Kangaslampi--Walker Theorem 3.1(ii) and the
Januszkiewicz--Świątkowski projection lemma in dimension two, stated over
Mathlib's `SimpleGraph`.

* `TriangleMove G p q`: `q` is obtained from the closed edge path `p` by deleting a
  backtrack `u v u ↦ u` or by shortcutting a triangle `u v w ↦ u w`.  These are the
  elementary homotopies of edge paths in the flag complex of `G` (its 2-cells are the
  triangles of `G`).
* `FlagSimplyConnected G`: every closed edge path based at `v` is equivalent to the
  constant path `[v]` under the equivalence relation generated by `TriangleMove G`.
* `LinksSixLarge G`: no cycle of length `3`, `4` or `5` made of neighbours of a vertex
  closes up (the flag link of every vertex has girth at least `6`).

## Manuscript status

Infrastructure for the torsion-free hyperbolic property (T) witness on the
Kotowski--Ollivier route; certifies no manuscript step on its own.
-/

namespace GroupApproximation
namespace Systolic

variable {V : Type*} (G : SimpleGraph V)

/-- **Elementary homotopies of edge paths in the flag complex of `G`.** -/
inductive TriangleMove : List V → List V → Prop
  | backtrack (p q : List V) (u v : V) (h : G.Adj u v) :
      TriangleMove (p ++ u :: v :: u :: q) (p ++ u :: q)
  | triangle (p q : List V) (u v w : V) (huv : G.Adj u v) (hvw : G.Adj v w) (huw : G.Adj u w) :
      TriangleMove (p ++ u :: v :: w :: q) (p ++ u :: w :: q)

/-- **The flag complex of `G` is simply connected**: every closed edge path based at `v`
reduces to the constant path under the equivalence generated by triangle moves. -/
def FlagSimplyConnected : Prop :=
  ∀ (v : V) (l : List V), List.IsChain G.Adj (v :: l ++ [v]) →
    Relation.EqvGen (TriangleMove G) (v :: l ++ [v]) [v]

/-- **Every vertex link is 6-large** (no cycle of length `3`, `4` or `5` among the
neighbours of a vertex closes up). -/
def LinksSixLarge : Prop :=
  ∀ (v : V) (c : List V), 3 ≤ c.length → c.length ≤ 5 → c.Nodup → (∀ x ∈ c, G.Adj v x) →
    ¬ List.IsChain G.Adj (c ++ c.take 1)

/-- The automorphisms of `G` form a group (`RelIso.instGroup` through the `Iso` abbrev),
so a group action by graph automorphisms is a homomorphism `Γ →* (G ≃g G)`. -/
example : Group (G ≃g G) := inferInstance

end Systolic
end GroupApproximation
