import GroupApproximation.Leavitt.AryWords
import GroupApproximation.Leavitt.AryLeavitt
import GroupApproximation.Meta.AxiomGuard

/-!
# Monomial normal form for the universal `d`-ary Leavitt algebra

`L_k(1,d)` is spanned, as a `k`-vector space, by the monomials `s_α t_β` over
pairs of finite words in `List (Fin d)`.  This is `Leavitt/LeavittNormalForm.lean`
at arbitrary arity, and stage two of generalising

`LeavittWords → LeavittNormalForm → LeavittSimplicity → division`

from arity `2` to arity `d`, which is what
`HasSingleSandwichDivision (AryLeavittAlgebra k d)` needs.

## The measurement, which came out against my prediction

I expected this stage to resist, because unlike the words layer it uses the
**presentation** of the algebra — `RingQuot` of a free algebra — and not merely
an abstract family of elements.  Reading it first, as the words layer was read,
shows the presentation is touched in only three places, and all three are
arity-blind:

* `RingQuot.mkAlgHom_surjective` — the quotient map is surjective;
* `FreeAlgebra.adjoin_range_ι` — a free algebra is generated by `ι`'s range;
* each generator is a length-one word, `genS i = wordS [i]` and
  `genT i = wordT [i]`.

None of the three mentions the number of generators.  Everything else in the
binary file is either the words layer — which `AryWords.lean` already carries —
or generic `Submodule.span` / `Subalgebra` bookkeeping.

So the substitution that worked for the words layer works here too, and my
expectation of resistance was wrong.  The one real change is cosmetic: the binary
file enumerates its four generators with `fin_cases`, and here the generator type
is `Fin d ⊕ Fin d`, so the enumeration becomes a `Sum` case split with an index.
-/

namespace GroupApproximation
namespace AryLeavitt

open CompleteMatrixFamily

noncomputable section

variable (k : Type*) [Field k] (d : ℕ)

/-- The generator map of the presentation, as a function on generator names. -/
def generator (g : Generator d) : AryLeavittAlgebra k d :=
  quotientMap k d (FreeAlgebra.ι k g)

@[simp] theorem generator_inl (i : Fin d) :
    generator k d (Sum.inl i) = genS k d i := rfl

@[simp] theorem generator_inr (i : Fin d) :
    generator k d (Sum.inr i) = genT k d i := rfl

/-- The monomials `s_α t_β`. -/
def monomialSet : Set (AryLeavittAlgebra k d) :=
  {x | ∃ a b : List (Fin d),
    x = (family k d).wordS a * (family k d).wordT b}

/-- The product of two monomials is a monomial or zero.

Pure words layer: the prefix trichotomy, then one of the two prefix collapses or
the incomparability annihilation. -/
theorem monomial_mul_monomial {x y : AryLeavittAlgebra k d}
    (hx : x ∈ monomialSet k d) (hy : y ∈ monomialSet k d) :
    x * y ∈ monomialSet k d ∨ x * y = 0 := by
  obtain ⟨a, b, rfl⟩ := hx
  obtain ⟨c, e, rfl⟩ := hy
  by_cases hbc : b <+: c
  · obtain ⟨f, rfl⟩ := hbc
    left
    refine ⟨a ++ f, e, ?_⟩
    calc (family k d).wordS a * (family k d).wordT b *
          ((family k d).wordS (b ++ f) * (family k d).wordT e)
        = (family k d).wordS a *
            ((family k d).wordT b * (family k d).wordS (b ++ f)) *
              (family k d).wordT e := by simp only [mul_assoc]
      _ = (family k d).wordS (a ++ f) * (family k d).wordT e := by
          rw [wordT_mul_wordS_append_left, wordS_append]
  by_cases hcb : c <+: b
  · obtain ⟨f, rfl⟩ := hcb
    left
    refine ⟨a, e ++ f, ?_⟩
    calc (family k d).wordS a * (family k d).wordT (c ++ f) *
          ((family k d).wordS c * (family k d).wordT e)
        = (family k d).wordS a *
            ((family k d).wordT (c ++ f) * (family k d).wordS c) *
              (family k d).wordT e := by simp only [mul_assoc]
      _ = (family k d).wordS a * (family k d).wordT (e ++ f) := by
          rw [wordT_append_mul_wordS, wordT_append, mul_assoc]
  · right
    calc (family k d).wordS a * (family k d).wordT b *
          ((family k d).wordS c * (family k d).wordT e)
        = (family k d).wordS a *
            ((family k d).wordT b * (family k d).wordS c) *
              (family k d).wordT e := by simp only [mul_assoc]
      _ = 0 := by
          rw [wordT_mul_wordS_of_incomparable (family k d) b c hbc hcb]
          simp

/-- The monomial span is a subalgebra. -/
def monomialSubalgebra : Subalgebra k (AryLeavittAlgebra k d) where
  carrier := ↑(Submodule.span k (monomialSet k d))
  add_mem' := fun ha hb ↦ Submodule.add_mem _ ha hb
  mul_mem' := by
    intro x y hx hy
    induction hx using Submodule.span_induction with
    | mem u hu =>
        induction hy using Submodule.span_induction with
        | mem v hv =>
            rcases monomial_mul_monomial k d hu hv with h | h
            · exact Submodule.subset_span h
            · rw [h]
              exact Submodule.zero_mem _
        | zero =>
            rw [mul_zero]
            exact Submodule.zero_mem _
        | add v w _ _ hv hw =>
            rw [mul_add]
            exact Submodule.add_mem _ hv hw
        | smul c v _ hv =>
            rw [mul_smul_comm]
            exact Submodule.smul_mem _ c hv
    | zero =>
        rw [zero_mul]
        exact Submodule.zero_mem _
    | add u v _ _ hu hv =>
        rw [add_mul]
        exact Submodule.add_mem _ hu hv
    | smul c u _ hu =>
        rw [smul_mul_assoc]
        exact Submodule.smul_mem _ c hu
  algebraMap_mem' := by
    intro c
    rw [Algebra.algebraMap_eq_smul_one]
    refine Submodule.smul_mem _ c (Submodule.subset_span ?_)
    exact ⟨[], [], by simp⟩

/-- Every generator lies in the monomial span: it is a length-one word.

Where the binary file writes `fin_cases` over four generators, this splits on
`Sum` and keeps the index. -/
theorem generator_mem_monomialSubalgebra (g : Generator d) :
    generator k d g ∈ monomialSubalgebra k d := by
  apply Submodule.subset_span
  cases g with
  | inl i => exact ⟨[i], [], by simp [family]⟩
  | inr i => exact ⟨[], [i], by simp [family]⟩

/-- The presented quotient is generated by its generators.

This is the only genuinely presentation-level step, and it never mentions the
number of generators. -/
theorem adjoin_range_generator :
    Algebra.adjoin k (Set.range (generator k d)) = ⊤ := by
  have hrange : Set.range (generator k d) =
      ⇑(quotientMap k d) '' Set.range (FreeAlgebra.ι k) := by
    rw [← Set.range_comp]
    rfl
  rw [hrange, ← AlgHom.map_adjoin, FreeAlgebra.adjoin_range_ι, Algebra.map_top]
  exact (AlgHom.range_eq_top _).mpr
    (RingQuot.mkAlgHom_surjective k (Relation k d))

/-- **Monomial normal form at arity `d`**: the universal `d`-ary Leavitt algebra
is spanned by the monomials `s_α t_β`. -/
theorem span_monomialSet_eq_top :
    Submodule.span k (monomialSet k d) = ⊤ := by
  have hle : (⊤ : Subalgebra k (AryLeavittAlgebra k d)) ≤
      monomialSubalgebra k d := by
    rw [← adjoin_range_generator k d]
    apply Algebra.adjoin_le
    rintro _ ⟨g, rfl⟩
    exact generator_mem_monomialSubalgebra k d g
  rw [Submodule.eq_top_iff']
  intro x
  exact hle Algebra.mem_top

end

end AryLeavitt
end GroupApproximation

/-! ### Axiom audit -/

#audit_axioms GroupApproximation.AryLeavitt.monomial_mul_monomial
#audit_axioms GroupApproximation.AryLeavitt.generator_mem_monomialSubalgebra
#audit_axioms GroupApproximation.AryLeavitt.adjoin_range_generator
#audit_axioms GroupApproximation.AryLeavitt.span_monomialSet_eq_top
