import GroupApproximation.Leavitt.Leavitt
import GroupApproximation.Leavitt.ElementaryNoFiniteQuotients

/-!
# The Leavitt mark is nonzero, so the defect is a nontrivial group element

`non_mf_groups_exist.tex`, Proposition `prop:defect`, last clause: the defect
`d = e₀₂(q)` is **nontrivial**.  The manuscript justifies this by `q ≠ 0`, which
it reads off `eq:pq`.  This file formalizes exactly that chain, over an
arbitrary ring carrying a `LeavittFamily` (`Leavitt.lean`), with no hypothesis
on the ring beyond `Nontrivial`:

1. `t₁ q s₁ = 1` for `q = p₁ = s₁t₁` — one line from `eq:pq`, because
   `t₁ (s₁t₁) s₁ = (t₁s₁)(t₁s₁) = 1 · 1 = 1` (`LeavittFamily.t1_mul_p1_mul_s1`);
   and symmetrically `t₀ p₀ s₀ = 1` (`LeavittFamily.t0_mul_p0_mul_s0`).
2. Hence `q ≠ 0` in every nontrivial ring: `q = 0` would read `1 = t₁ 0 s₁ = 0`
   (`LeavittFamily.p1_ne_zero`), and likewise `p₀ ≠ 0`
   (`LeavittFamily.p0_ne_zero`).  With `p₀ + p₁ = 1`
   (`LeavittFamily.p0_add_p1`, already in `Leavitt.lean`) this says the two
   range idempotents of `eq:pq` are a partition of `1` into two nonzero pieces.
3. An elementary matrix is trivial exactly when its coefficient vanishes:
   `x_{ij}(a) = 1 ↔ a = 0` (`elementaryUnit_eq_one_iff`), which is
   `elementaryUnit_injective` against `elementaryUnit_zero`.
4. Therefore `x_{ij}(q) ≠ 1` (`elementaryUnit_p1_ne_one`), and the same at the
   level of the bundled generator of `EL_ι(R)`
   (`LeavittMark.elGen_p1_ne_one`).  That is the manuscript's `d ≠ 1`.

## Why this is the literature-free step

Step 1 is the whole reason the headline needs no structure theory of the Leavitt
algebra.  `t₁ q s₁ = 1` says `1 ∈ R q R` — the two-sided ideal generated by the
defect coefficient is already everything — and it is a *one-line consequence of
the defining relations `eq:pq`*.  No simplicity of `L_{𝔽₂}(1,2)`, no pure
infiniteness, no exchange-ring property, no computation of a centre, and no
Preusser-style normal-subgroup theorem enters anywhere in this file: the input
is `t₁s₁ = 1` and nothing else.  Every ring carrying a binary Leavitt family —
including every quotient of one that is still nontrivial — satisfies the whole
chain.

## Overlap with the rest of the repository

The `p₁` half of steps 1 and 2 is also recorded, for the rank-`16` frame, as
`HilbertHotel.r1_mul_q_mul_s1` and `HilbertHotel.q_ne_zero`
(`HilbertHotelBlocks.lean`), and re-exported by `HilbertHotelBinary.lean`; those
are the same two facts stated in the Hilbert-hotel namespace, and they should be
re-derived from the two `LeavittFamily` lemmas below rather than reproved.  The
`p₀` half, the `iff` of step 3 and the unit-level nontriviality of step 4 have no
counterpart elsewhere.  At the `elGen` level, `ElementaryNormalGeneration.lean`
proves the same two statements from a *unit sandwich* hypothesis
(`elGen_eq_one_iff`, `ne_zero_of_unit_sandwich`, `elGen_p1_ne_one`); the
versions below are kept in the `LeavittMark` namespace so that the two readings
cannot collide, and are proved from the elementary-matrix level instead.
-/

namespace GroupApproximation

/-! ## The two range idempotents are nonzero -/

namespace LeavittFamily

variable {A : Type*} [Ring A] (L : LeavittFamily A)

/-- **`eq:pq` gives the mark a two-sided unit sandwich.**  `t₁ q s₁ = 1` for
`q = p₁ = s₁t₁`: the defect coefficient generates the unit ideal, by the
defining relations alone. -/
theorem t1_mul_p1_mul_s1 : L.t1 * L.p1 * L.s1 = 1 := by
  rw [L.t1_mul_p1, L.t1_s1]

/-- The complementary statement for the other range idempotent: `t₀ p₀ s₀ = 1`. -/
theorem t0_mul_p0_mul_s0 : L.t0 * L.p0 * L.s0 = 1 := by
  rw [L.t0_mul_p0, L.t0_s0]

/-- **`q ≠ 0`.**  In a nontrivial ring the mark cannot vanish: `q = 0` would turn
`t₁ q s₁ = 1` into `0 = 1`. -/
theorem p1_ne_zero [Nontrivial A] : L.p1 ≠ 0 := by
  intro h
  have h1 : (1 : A) = 0 := by
    rw [← L.t1_mul_p1_mul_s1, h, mul_zero, zero_mul]
  exact one_ne_zero h1

/-- `p₀ ≠ 0`, by the same argument at the other index. -/
theorem p0_ne_zero [Nontrivial A] : L.p0 ≠ 0 := by
  intro h
  have h1 : (1 : A) = 0 := by
    rw [← L.t0_mul_p0_mul_s0, h, mul_zero, zero_mul]
  exact one_ne_zero h1

/-- The two range idempotents partition `1` into two nonzero orthogonal pieces:
`p₀ + p₁ = 1` is `LeavittFamily.p0_add_p1`, and neither summand is `0`. -/
theorem p0_ne_zero_and_p1_ne_zero [Nontrivial A] : L.p0 ≠ 0 ∧ L.p1 ≠ 0 :=
  ⟨L.p0_ne_zero, L.p1_ne_zero⟩

end LeavittFamily

/-! ## An elementary matrix is trivial exactly when its coefficient is -/

section Elementary

variable {ι R : Type*} [Fintype ι] [DecidableEq ι] [Ring R]

/-- `x_{ij}(a) = 1 ↔ a = 0` for `i ≠ j`: the two directions are
`elementaryUnit_injective` and `elementaryUnit_zero`. -/
theorem elementaryUnit_eq_one_iff (i j : ι) (h : i ≠ j) (a : R) :
    elementaryUnit i j h a = 1 ↔ a = 0 := by
  constructor
  · intro ha
    have h1 : elementaryUnit i j h a = elementaryUnit (R := R) i j h 0 := by
      rw [elementaryUnit_zero]
      exact ha
    exact elementaryUnit_injective i j h h1
  · intro ha
    rw [ha, elementaryUnit_zero]

/-- A nonzero coefficient gives a nontrivial elementary matrix. -/
theorem elementaryUnit_ne_one_of_ne_zero (i j : ι) (h : i ≠ j) {a : R}
    (ha : a ≠ 0) : elementaryUnit i j h a ≠ 1 := fun hcon =>
  ha ((elementaryUnit_eq_one_iff i j h a).mp hcon)

/-- **`prop:defect`, last clause, at the level of matrices.**  `d = x_{ij}(q)` is
a nontrivial element of `GL_ι(R)` for every nontrivial ring carrying a binary
Leavitt family. -/
theorem elementaryUnit_p1_ne_one [Nontrivial R] (L : LeavittFamily R) (i j : ι)
    (hij : i ≠ j) : elementaryUnit i j hij L.p1 ≠ 1 :=
  elementaryUnit_ne_one_of_ne_zero i j hij L.p1_ne_zero

/-- The same for the complementary idempotent. -/
theorem elementaryUnit_p0_ne_one [Nontrivial R] (L : LeavittFamily R) (i j : ι)
    (hij : i ≠ j) : elementaryUnit i j hij L.p0 ≠ 1 :=
  elementaryUnit_ne_one_of_ne_zero i j hij L.p0_ne_zero

/-! ## The same statements inside `EL_ι(R)`

`elGen` (`ElementaryNoFiniteQuotients.lean`) is the elementary matrix bundled as
an element of the subgroup `EL_ι(R)`; equality there is equality of the
underlying matrices, so nothing new happens. -/

namespace LeavittMark

/-- `e_{ij}(a) = 1` in `EL_ι(R)` exactly when `a = 0`. -/
theorem elGen_eq_one_iff (i j : ι) (h : i ≠ j) (a : R) :
    elGen i j h a = 1 ↔ a = 0 := by
  constructor
  · intro ha
    exact (elementaryUnit_eq_one_iff i j h a).mp (congrArg Subtype.val ha)
  · intro ha
    rw [ha, elGen_zero]

/-- A nonzero coefficient gives a nontrivial element of `EL_ι(R)`. -/
theorem elGen_ne_one_of_ne_zero (i j : ι) (h : i ≠ j) {a : R} (ha : a ≠ 0) :
    elGen i j h a ≠ 1 := fun hcon => ha ((elGen_eq_one_iff i j h a).mp hcon)

/-- **`prop:defect`, last clause.**  The defect `d = e_{ij}(q)` is a nontrivial
element of `EL_ι(R)`, for every nontrivial ring carrying a binary Leavitt family
and every pair of distinct indices.  The only input is `eq:pq`. -/
theorem elGen_p1_ne_one [Nontrivial R] (L : LeavittFamily R) (i j : ι)
    (hij : i ≠ j) : elGen i j hij L.p1 ≠ 1 :=
  elGen_ne_one_of_ne_zero i j hij L.p1_ne_zero

/-- The same for the complementary idempotent. -/
theorem elGen_p0_ne_one [Nontrivial R] (L : LeavittFamily R) (i j : ι)
    (hij : i ≠ j) : elGen i j hij L.p0 ≠ 1 :=
  elGen_ne_one_of_ne_zero i j hij L.p0_ne_zero

end LeavittMark

end Elementary

end GroupApproximation
