import GroupApproximation.Algebra.LocallyMatricial
import GroupApproximation.Leavitt.CongruenceSubgroups
import GroupApproximation.Leavitt.CornerUnitHom
import GroupApproximation.Leavitt.ElementaryFTwoMatrixProduct
import GroupApproximation.Sofic.LocallyFiniteMF
import Mathlib.Algebra.GroupWithZero.Units.Fintype
import GroupApproximation.Meta.AxiomGuard

/-!
# The restriction kernel `K_n = EL_n(R_X, I)` is locally finite

`non_mf_groups_exist.tex`, `thm:core-mf-radical`:

> For $n\ge2$, $K_n=\EL_n(R_X,I)$ is locally finite.

and its proof:

> If $g\in\GL_n(R_X)$ restricts to the identity, put all entries of $g-1$ and $g^{-1}-1$
> inside one finite matrix-product algebra $B=\prod_a M_{h_a}(\F_2)\subset I$, with local
> identity $p$.  Then $g=(1-p)I_n+h$ with $h\in\GL_n(B)$.  [...]  Thus $g$ is generated by roots
> with coefficients in $I$.  This proves equality of the elementary and general linear
> restriction kernels with $\EL_n(R_X,I)$.  The same argument for finitely many $g$ at once
> places them in a common finite group, proving local finiteness.

Generic form: `f : R →+* S` is the restriction, `I = ker f`, and `I` is locally matricial over
`F_2` (`ChainCore.IsLocallyMatricialIn`).  `K_n = ker (GL_n(R) → GL_n(S))` is the kernel of
`elementaryMatrixUnitMap f`, and `n ≥ 2` is `[Nontrivial ι]`.

* `exists_cornerUnitHom_eq_of_finset`: finitely many `g ∈ K_n` are corner units `(1 - p) I_n + h`
  over one `B` with `B ⊆ I`;
* `ker_elementaryMatrixUnitMap_le_closure_rootsIn`: `g` is generated by roots with coefficients
  in `I`;
* `ker_elementaryMatrixUnitMap_eq`, `ker_elementaryGroupMap_eq_relativeElementary`: the general
  linear and the elementary restriction kernels are `EL_n(R, I)`;
* `isLocallyFiniteGroup_ker_elementaryMatrixUnitMap`: `K_n` is locally finite.
-/

namespace GroupApproximation
namespace ChainRadical

variable {ι R S : Type*} [Fintype ι] [DecidableEq ι] [Ring R] [Ring S]

/-- The roots `x_{ij}(a)` with coefficients `a ∈ I`, as units. -/
def rootsIn (ι : Type*) [Fintype ι] [DecidableEq ι] (I : TwoSidedIdeal R) : Set (Matrix ι ι R)ˣ :=
  {g | ∃ (i j : ι) (hij : i ≠ j) (a : R), a ∈ I ∧ g = elementaryUnit i j hij a}

theorem map_cornerUnitHom_le_closure_rootsIn {A : Type*} [Ring A] (φ : A →ₙ+* R)
    {I : TwoSidedIdeal R} (hφI : ∀ y, φ y ∈ I) :
    (elementaryGroup ι A).map (cornerUnitHom φ) ≤ Subgroup.closure (rootsIn ι I) := by
  refine Subgroup.map_le_iff_le_comap.2 ((Subgroup.closure_le (K := _)).2 ?_)
  rintro _ ⟨i, j, hij, a, rfl⟩
  refine Subgroup.mem_comap.2 ?_
  rw [cornerUnitHom_elementaryUnit]
  exact Subgroup.subset_closure ⟨i, j, hij, φ a, hφI a, rfl⟩

theorem closure_rootsIn_le_map_relativeElementary (I : TwoSidedIdeal R) :
    Subgroup.closure (rootsIn ι I) ≤ (relativeElementary ι I).map (elementaryGroup ι R).subtype := by
  refine (Subgroup.closure_le (K := _)).2 ?_
  rintro _ ⟨i, j, hij, a, ha, rfl⟩
  exact Subgroup.mem_map.2 ⟨elGen i j hij a, elGen_mem_relativeElementary i j hij ha, rfl⟩

section Kernel

variable (f : R →+* S)

theorem sub_one_apply_mem_ker {g : (Matrix ι ι R)ˣ}
    (hg : g ∈ (elementaryMatrixUnitMap (ι := ι) f).ker) (k l : ι) :
    ((g : Matrix ι ι R) - 1) k l ∈ TwoSidedIdeal.ker f := by
  have h1 : (g : Matrix ι ι R).map f = 1 := congrArg Units.val (MonoidHom.mem_ker.1 hg)
  have h2 : ((g : Matrix ι ι R) - 1).map f = 0 := by
    rw [Matrix.map_sub _ (map_sub f), h1, Matrix.map_one _ (map_zero f) (map_one f), sub_self]
  exact (TwoSidedIdeal.mem_ker f).2 (congrFun (congrFun h2 k) l)

/-- Corner units over `B ⊆ ker f` restrict to the identity. -/
theorem cornerUnitHom_mem_ker {A : Type*} [Ring A] (φ : A →ₙ+* R)
    (hφI : ∀ y, φ y ∈ TwoSidedIdeal.ker f) (u : (Matrix ι ι A)ˣ) :
    cornerUnitHom φ u ∈ (elementaryMatrixUnitMap (ι := ι) f).ker := by
  have h0 : ∀ y, f (φ y) = 0 := fun y ↦ (TwoSidedIdeal.mem_ker f).1 (hφI y)
  refine MonoidHom.mem_ker.2 (Units.ext ?_)
  change (Matrix.scalar ι (1 - φ 1) + (u : Matrix ι ι A).map φ).map f = 1
  ext k l
  rw [Matrix.map_apply, Matrix.add_apply, Matrix.map_apply, map_add, h0, add_zero,
    Matrix.scalar_apply, Matrix.diagonal_apply, Matrix.one_apply]
  split_ifs
  · rw [map_sub, map_one, h0, sub_zero]
  · exact map_zero f

theorem relativeElementary_map_subtype_le_ker :
    (relativeElementary ι (TwoSidedIdeal.ker f)).map (elementaryGroup ι R).subtype ≤
      (elementaryMatrixUnitMap (ι := ι) f).ker := by
  refine Subgroup.map_le_iff_le_comap.2 (Subgroup.normalClosure_le_normal ?_)
  rintro _ ⟨i, j, hij, a, ha, rfl⟩
  refine Subgroup.mem_comap.2 (MonoidHom.mem_ker.2 ?_)
  change elementaryMatrixUnitMap f (elementaryUnit i j hij a) = 1
  rw [elementaryMatrixUnitMap_elementaryUnit, (TwoSidedIdeal.mem_ker f).1 ha, elementaryUnit_zero]

theorem ker_elementaryGroupMap_eq_comap :
    (elementaryGroupMap (ι := ι) f).ker =
      (elementaryMatrixUnitMap (ι := ι) f).ker.comap (elementaryGroup ι R).subtype := by
  ext g
  rw [MonoidHom.mem_ker, Subgroup.mem_comap, MonoidHom.mem_ker]
  exact Subtype.ext_iff

variable [Algebra (ZMod 2) R]

/-- **Finitely many `g ∈ K_n` are corner units over one finite `B ⊆ I`.** -/
theorem exists_cornerUnitHom_eq_of_finset
    (hI : ChainCore.IsLocallyMatricialIn (ZMod 2) (TwoSidedIdeal.ker f : Set R))
    (s : Finset (Matrix ι ι R)ˣ) (hs : ∀ g ∈ s, g ∈ (elementaryMatrixUnitMap (ι := ι) f).ker) :
    ∃ (m : ℕ) (h : Fin m → ℕ) (φ : MatrixProductFTwo m h →ₙ+* R),
      (∀ y, φ y ∈ TwoSidedIdeal.ker f) ∧ ∀ g ∈ s, ∃ u, cornerUnitHom φ u = g := by
  classical
  obtain ⟨m, h, φ, hφ, hφI, hcov⟩ := hI.exists_nonUnitalRingHom
    ((s ×ˢ (Finset.univ : Finset (ι × ι))).image
        (fun q ↦ ((q.1 : Matrix ι ι R) - 1) q.2.1 q.2.2) ∪
      (s ×ˢ (Finset.univ : Finset (ι × ι))).image
        (fun q ↦ (((q.1⁻¹ : (Matrix ι ι R)ˣ) : Matrix ι ι R) - 1) q.2.1 q.2.2))
    (by
      intro x hx
      rcases Finset.mem_union.1 hx with hx | hx <;>
        obtain ⟨⟨g, k, l⟩, hq, rfl⟩ := Finset.mem_image.1 hx
      · exact sub_one_apply_mem_ker f (hs g (Finset.mem_product.1 hq).1) k l
      · exact sub_one_apply_mem_ker f (inv_mem (hs g (Finset.mem_product.1 hq).1)) k l)
  refine ⟨m, h, φ, hφI, fun g hg ↦ exists_cornerUnitHom_eq φ hφ g (fun k l ↦ hcov _ ?_)
    (fun k l ↦ hcov _ ?_)⟩
  · exact Finset.mem_union_left _
      (Finset.mem_image.2 ⟨(g, k, l), Finset.mem_product.2 ⟨hg, Finset.mem_univ _⟩, rfl⟩)
  · exact Finset.mem_union_right _
      (Finset.mem_image.2 ⟨(g, k, l), Finset.mem_product.2 ⟨hg, Finset.mem_univ _⟩, rfl⟩)

/-- **`g` is generated by roots with coefficients in `I`** (`n ≥ 2`). -/
theorem ker_elementaryMatrixUnitMap_le_closure_rootsIn [Nontrivial ι]
    (hI : ChainCore.IsLocallyMatricialIn (ZMod 2) (TwoSidedIdeal.ker f : Set R)) :
    (elementaryMatrixUnitMap (ι := ι) f).ker ≤ Subgroup.closure (rootsIn ι (TwoSidedIdeal.ker f)) := by
  intro g hg
  obtain ⟨m, h, φ, hφI, hs⟩ := exists_cornerUnitHom_eq_of_finset f hI {g} fun g' hg' ↦ by
    rw [Finset.mem_singleton.1 hg']
    exact hg
  obtain ⟨u, rfl⟩ := hs g (Finset.mem_singleton_self g)
  exact map_cornerUnitHom_le_closure_rootsIn φ hφI (Subgroup.mem_map_of_mem _
    (eq_top_iff.1 (elementaryGroup_matrixProductFTwo_eq_top m h) (Subgroup.mem_top u)))

/-- **The general linear restriction kernel is `EL_n(R, I)`** (`n ≥ 2`). -/
theorem ker_elementaryMatrixUnitMap_eq [Nontrivial ι]
    (hI : ChainCore.IsLocallyMatricialIn (ZMod 2) (TwoSidedIdeal.ker f : Set R)) :
    (elementaryMatrixUnitMap (ι := ι) f).ker =
      (relativeElementary ι (TwoSidedIdeal.ker f)).map (elementaryGroup ι R).subtype :=
  le_antisymm ((ker_elementaryMatrixUnitMap_le_closure_rootsIn f hI).trans
    (closure_rootsIn_le_map_relativeElementary _)) (relativeElementary_map_subtype_le_ker f)

theorem ker_elementaryMatrixUnitMap_le_elementaryGroup [Nontrivial ι]
    (hI : ChainCore.IsLocallyMatricialIn (ZMod 2) (TwoSidedIdeal.ker f : Set R)) :
    (elementaryMatrixUnitMap (ι := ι) f).ker ≤ elementaryGroup ι R := by
  rw [ker_elementaryMatrixUnitMap_eq f hI]
  exact Subgroup.map_subtype_le _

/-- **The elementary restriction kernel is `EL_n(R, I)`** (`n ≥ 2`). -/
theorem ker_elementaryGroupMap_eq_relativeElementary [Nontrivial ι]
    (hI : ChainCore.IsLocallyMatricialIn (ZMod 2) (TwoSidedIdeal.ker f : Set R)) :
    (elementaryGroupMap (ι := ι) f).ker = relativeElementary ι (TwoSidedIdeal.ker f) := by
  rw [ker_elementaryGroupMap_eq_comap, ker_elementaryMatrixUnitMap_eq f hI,
    Subgroup.comap_map_eq_self_of_injective (elementaryGroup ι R).subtype_injective]

/-- **`K_n` is locally finite**: finitely many `g ∈ K_n` lie in the finite image of `GL_n(B)`. -/
theorem isLocallyFiniteGroup_ker_elementaryMatrixUnitMap
    (hI : ChainCore.IsLocallyMatricialIn (ZMod 2) (TwoSidedIdeal.ker f : Set R)) :
    IsLocallyFiniteGroup (elementaryMatrixUnitMap (ι := ι) f).ker := by
  classical
  intro s
  obtain ⟨m, h, φ, hφI, hs⟩ := exists_cornerUnitHom_eq_of_finset f hI (s.image Subtype.val)
    fun g hg ↦ by
      obtain ⟨g, -, rfl⟩ := Finset.mem_image.1 hg
      exact g.2
  let c : (Matrix ι ι (MatrixProductFTwo m h))ˣ →* (elementaryMatrixUnitMap (ι := ι) f).ker :=
    (cornerUnitHom φ).codRestrict _ (cornerUnitHom_mem_ker f φ hφI)
  refine ⟨c.range, Finite.of_surjective _ c.rangeRestrict_surjective, fun g hg ↦ ?_⟩
  obtain ⟨u, hu⟩ := hs g (Finset.mem_image_of_mem Subtype.val hg)
  exact MonoidHom.mem_range.2 ⟨u, Subtype.ext hu⟩

end Kernel

section ModelTests

/-- Model test (degenerate): the zero ideal `ker (id)` is locally matricial, with the empty
product `m = 0`. -/
theorem isLocallyMatricialIn_ker_id (T : Type*) [Ring T] [Algebra (ZMod 2) T] :
    ChainCore.IsLocallyMatricialIn (ZMod 2) (TwoSidedIdeal.ker (RingHom.id T) : Set T) :=
  fun _ hF ↦ ⟨0, fun _ ↦ 0, 0, fun _ _ _ ↦ funext fun i ↦ Fin.elim0 i,
    fun _ ↦ SetLike.mem_coe.2 ((TwoSidedIdeal.mem_ker (RingHom.id T)).2 rfl),
    fun x hx ↦ ⟨0, ((TwoSidedIdeal.mem_ker (RingHom.id T)).1 (SetLike.mem_coe.1 (hF x hx))).symm⟩⟩

end ModelTests

end ChainRadical
end GroupApproximation

#audit_axioms GroupApproximation.ChainRadical.map_cornerUnitHom_le_closure_rootsIn
#audit_axioms GroupApproximation.ChainRadical.closure_rootsIn_le_map_relativeElementary
#audit_axioms GroupApproximation.ChainRadical.cornerUnitHom_mem_ker
#audit_axioms GroupApproximation.ChainRadical.relativeElementary_map_subtype_le_ker
#audit_axioms GroupApproximation.ChainRadical.exists_cornerUnitHom_eq_of_finset
#audit_axioms GroupApproximation.ChainRadical.ker_elementaryMatrixUnitMap_le_closure_rootsIn
#audit_axioms GroupApproximation.ChainRadical.ker_elementaryMatrixUnitMap_eq
#audit_axioms GroupApproximation.ChainRadical.ker_elementaryMatrixUnitMap_le_elementaryGroup
#audit_axioms GroupApproximation.ChainRadical.ker_elementaryGroupMap_eq_relativeElementary
#audit_axioms GroupApproximation.ChainRadical.isLocallyFiniteGroup_ker_elementaryMatrixUnitMap
#audit_axioms GroupApproximation.ChainRadical.isLocallyMatricialIn_ker_id
